### ISSUE TITLE
Detects self as (XSRF) Attack

### ISSUE THREAD

**Issue by kale1d0code** [salesagility/SuiteCRM#10014]
#### Issue

Certain actions performed on the CRM system (I just tried changing my password) after a clean install causes a CSRF/XSRF error message

```
Possible Cross Site Request Forgery (XSRF) Attack Detected
If you think this is a mistake please ask your administrator to add the following site to the acceptable referer list
<CRM_SITE_URL>
```

#### Expected Behavior

return to user detail view after changing password

#### Actual Behavior

presented with CSRF/XSRF attack message

#### Possible Fix

could add the crm site url to http_referer but this feels redundant, the CRM system should already know its own url from within the config file.

#### Steps to Reproduce

1. Change your password
2.
3.
4.

#### Context

Low priority as the problem can be avoided by adding the crm's url to the referer list

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Chrome Version 112.0.5615.49 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
* MariaDB 10.9.4
* PHP 8.0.26
* Operating System and version (e.g Ubuntu 16.04):
* Alpine Linux v3.16

**Comment by pgorod** [comment]
You didn't write the SuiteCRM version on the Issue, that is an essential information...

Where is the Forum thread on this problem, had you asked in the Forums before? (sorry, maybe I saw it and forgot)

It's just that you would need to check that this is not simply a problem in your own configuration, before posting here. A nice check would be to try it on the live demo.

**Comment by kale1d0code** [comment]
@pgorod you're right.

I encountered this issue a few times on some systems I've setup, I should have checked the forums first.

The exact cause is outlined in this post https://community.suitecrm.com/t/ask-suitecrm-csrf-detected/50263/11

adding the url as the servers name removed the issue.
