### ISSUE TITLE
PHP Constructors

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#1002]
Much of the codebase uses the old style PHP constructors rather than the recommended `__construct` method.

These are deprecated in PHP 7 and will be removed at some point in the future. We should move to the new style constructors (perhaps having the old methods call the new to preserve backwards compatibility).

In particular we'd want to ensure that beans generated by Module Builder were doing the right thing.

**Comment by mattlorimer** [comment]
modules built with module builder already use __construct
