### ISSUE TITLE
7.12.11 Update fails with "The zip file is missing a manifest.php file. Cannot proceed." 

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#10038]
#### Issue
Tried to run the update from 7.12.10 to 7.12.11 that was released 3 days ago.
After the checks, the upload of the update package `SuiteCRM-7.12.11.zip` fails with the following message
```The zip file is missing a manifest.php file. Cannot proceed.```

#### Expected Behavior
The update should upload and be processed and proceed to the Preflight stage.

#### Actual Behavior
The upload and processing of the update file `SuiteCRM-7.12.11.zip` fails with the following message
```The zip file is missing a manifest.php file. Cannot proceed.```

#### Possible Fix
Add the manifest.php file??

#### Steps to Reproduce
1. Start update from Admin Update page after downloading the file from the [Downloads page](https://suitecrm.com/download/137/suite712/562268/suitecrm-7-12-11.zip)
2. click next until you get to the Upload Upgrade Package
3. select the `SuiteCRM-7.12.11.zip` and press UPLOAD PACKAGE
4. The upload doesn't complete and gives the error above.

#### Context
Can't update to the most recent build of 7.12.x

#### Your Environment
* SuiteCRM Version used: 7.12.10
* Browser name and version: Firefox 112.0.2
* Environment name and version (e.g. MySQL, PHP 7): MariaDB version 10.3.38, php 7.3.31
* Operating System and version: Debian 10 updated

**Comment by pgorod** [comment]
The correct package is called `SuiteCRM-Upgrade-7.12.x-to-7.12.11.zip`

**Comment by johnM2401** [comment]
Hey folks!

Thanks for clearing that up @pgorod, your time is much appreciated as always!

Also, Thank you for getting back in touch to confirm, @bunk3m.

I'll close this issue now, but please get in touch if you come across any bugs in the CRM!
