### ISSUE TITLE
Bad path after moving out modules from custom

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1005]
pls fix!
https://github.com/salesagility/SuiteCRM/blob/master/modules/Schedulers/_AddJobsHere.php#L535

`require_once 'custom/modules/InboundEmail/AOPInboundEmail.php';`

file is not there anymore it's in core module folder

it breaks w\ FATAL error

tnx

**Comment by ghermans** [comment]
There already is a fix for this and will be released in the next update.
If you can't wait for that, just grab the hotfix from Github.

Write in your terminal

     git -b hotfix https://github.com/salesagility/SuiteCRM.git

or download it from [here](https://github.com/salesagility/SuiteCRM/archive/hotfix.zip)

**Comment by adamjakab** [comment]
good to know, thanks
