### ISSUE TITLE
this system doesn't have any relationships with the tables?

### ISSUE THREAD

**Issue by hatetocode** [salesagility/SuiteCRM#10066]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
Hi there @hatetocode 

If you have questions, please ask in the Community forums:

https://community.suitecrm.com

If you have a proper bug report, please fill in the entire Issue template.
