### ISSUE TITLE
&nbsp; being replaced with bad characters in Email Templates

### ISSUE THREAD

**Issue by faizanaliyounas** [salesagility/SuiteCRM#10062]
When editing HTML Email Templates, you may encounter a situation where random characters, such as "Â", appear throughout the template. Even if you manually remove these characters from the HTML code and save the template, they reappear when the template is submitted. This issue becomes apparent when an email is sent, and the recipient sees the "Â" character instead of the intended content.

It is likely that this problem is related to encoding within the email message. The incorrect encoding causes the characters to be displayed incorrectly.

#### Your Environment

* SuiteCRM Version used: 7.13.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chromium Version 96.0.4664.93
* Environment name and version (e.g. MySQL, PHP 7):mysql  Ver 14.14  ,  PHP7.4
* Operating System and version (e.g Ubuntu 16.04):Ubuntu Version 96.0.4664.93

**Comment by pgorod** [comment]
It would be better if you provided specific text that causes the problem so that developers can try and reproduce it.

**Comment by chris001** [comment]
The non-breaking space character is byte `0xA0` in ISO-8859-1 and Windows-1252.  When encoded to UTF-8 it'd be `0xC2,0xA0`, which, if you (incorrectly) view it as ISO-8859-1 or Windows-1252, comes out as "`Â `". That includes a trailing `nbsp` which you might not be noticing on screen, gets saved, sent by email, and seen by the email recipient.

**Comment by faizanaliyounas** [comment]
![image](https://github.com/salesagility/SuiteCRM/assets/73401012/fceb1825-8de4-49ae-ad79-16dc039bb13c)

Whenever I use the default editor in suiteCRM to create a template, any additional lines or spaces I include in the template are replaced with undesirable characters when I try to send it.
And this is what I received.

![image](https://github.com/salesagility/SuiteCRM/assets/73401012/5f3f6b0a-1e2c-4268-a961-0a815b9e0225)


We encounter a situation where inexperienced users upload templates using the default editor without paying attention to the extra spaces they include.

**Comment by faizanaliyounas** [comment]
> It would be better if you provided specific text that causes the problem so that developers can try and reproduce it.

This is my email template:
![image](https://github.com/salesagility/SuiteCRM/assets/73401012/7c2b5ba0-e615-4d6d-a478-79881171c7f0)


Whenever I use the default editor in suiteCRM to create a template, any additional lines or spaces I include in the template are replaced with undesirable characters when I try to send it.

And this is what I received.
![image](https://github.com/salesagility/SuiteCRM/assets/73401012/59831480-efd1-4600-8433-44fd851c20f0)

We encounter a situation where inexperienced users upload templates using the default editor without paying attention to the extra spaces they include.

**Comment by chris001** [comment]
@faizanaliyounas 

Try this.

1. Are you the admin of this Ubuntu 16.04 server?
  No: Please have that person join this thread.
2. Connect to your Ubuntu 16.04 server and run this command: 
`php -m | grep mbstring`
3. Do you see `mbstring` print on the screen?
No:  Connect to server. Run these commands
```
sudo apt install -y php-mbstring
sudo phpenmod mbstring
sudo systemctl daemon-reexec
```

4. Paste these lines into the `mbstring.ini` settings file, used by your web server.
For example, on ubuntu, with apache and php 7.4,
the  file you add these lines to should be : `/etc/php/7.4/apache2/conf.d/20-mbstring.ini`
Note, that "`20`" at the beginning of the file name, could be any number, 
so add these to the file which name ends with "`-mbstring.ini`".
```
mbstring.language = all
mbstring.internal_encoding = UTF-8
mbstring.http_input = auto
mbstring.http_output = UTF-8
mbstring.encoding_translation = On
mbstring.detect_order = UTF-8
mbstring.substitute_character = none;
mbstring.func_overload = 0
mbstring.strict_encoding = Off
```
Connect to server and run this command:
`sudo systemctl daemon-reexec`

5. Try your Editing Email Templates again.

6. Report back your results here.

**Comment by chris001** [comment]
@faizanaliyounas   Did you have success?
Was your `php-mbstring` module not installed previously?
Please report back the cause of your issue.
