### ISSUE TITLE
preg_match on e-mail is incomplete

### ISSUE THREAD

**Issue by topesantos** [salesagility/SuiteCRM#10078]
#### Issue
Some special e-mails are truncated

#### Expected Behavior
Shouldn't be truncated

#### Actual Behavior
teste-freguesia-alpalhao@sapo.pt 
becomes
alpalhao@sapo.pt

#### Possible Fix
In
/modules/Emails/Email.php

where is
preg_match("/[A-Z0-9._%-\\']+@[A-Z0-9.-]+\\.[A-Z]{2,}/i",$v, $match);
should be
preg_match("/[A-Z0-9._%-\\-\\']+@[A-Z0-9.-]+\\.[A-Z]{2,}/i",$v, $match);

#### Steps to Reproduce

1. Try saving a new contact with email above

#### Context
Our customers have these types of emails.

#### Your Environment

* SuiteCRM Version used:
7.13.3

**Comment by chris001** [comment]
Good catch.

**Comment by chris001** [comment]
@topesantos  To make PR, just click on the "Edit" icon ✏️ located at the top right side of the file you want to modify, follow the steps to arrive at the editing page, make your changes, and follow 2 more steps until your PR's created.

**Comment by topesantos** [comment]
I'll do it on the right file.
