### ISSUE TITLE
PROJECT TASKS: Database failure. Please refer to suitecrm.log for details.

### ISSUE THREAD

**Issue by reggieeuser** [salesagility/SuiteCRM#10073]
Hi-

We get the message above on the screen when attempting to look at Project Tasks in a Project.  The suitecrm.log file shows the error below: 

Fri May 26 17:17:18 2023 [883268][1][FATAL] Mysqli_query failed.
Fri May 26 17:17:18 2023 [883268][1][FATAL] Error retrieving Project list: Query Failed: (SELECT project_task.id , project_task.name , project_task.date_start , project_task.date_finish ,
project_task.assigned_user_id, ‘projecttask’ panel_name FROM project_task INNER JOIN project projecttask_rel ON project_task.project_id=projecttask_rel.id AND projecttask_rel.deleted=0 where ( project_task.project_id=‘75d8d439-b9af-d28f-3af4-64710a8aa401’) AND project_task.deleted=0) ORDER BY project_task.project_task_id asc LIMIT 0,10: MySQL error 1109: Unknown table ‘project_task’ in order clause
Fri May 26 17:17:18 2023 [883268][1][FATAL] [ListView::processUnionBeans] . Database failure. Please refer to suitecrm.log for details.

There appears to be something wrong with the “INNER JOIN” part of this query. If we extract it, that is, change the query to:

SELECT project_task.id , project_task.name , project_task.date_start , project_task.date_finish ,
project_task.assigned_user_id, ‘projecttask’ panel_name FROM project_task ORDER BY project_task.project_task_id asc LIMIT 0,10;

and run the query in Mysql, it returns the expected data.

Any help in correcting this would be greatly appreciated.

FYI, we are running a fresh instance of SuiteCRM 8.3.0 on:

Ubuntu 22.04 with
PHP v. 8.0.28,
MySQL: 8.0.33-0ubuntu0.22.04.2,
Apache/2.4.57 (Ubuntu)

Thanks!

**Comment by CrazyTux** [comment]
@reggieeuser 

It looks to me like the example query:

`(SELECT project_task.id , project_task.name , project_task.date_start , project_task.date_finish ,
project_task.assigned_user_id, ‘projecttask’ panel_name FROM project_task INNER JOIN project projecttask_rel ON project_task.project_id=projecttask_rel.id AND projecttask_rel.deleted=0 where ( project_task.project_id=‘75d8d439-b9af-d28f-3af4-64710a8aa401’) AND project_task.deleted=0) ORDER BY project_task.project_task_id asc LIMIT 0,10`

Is incomplete?  Please note the beginning ( parenthesis around SELECT.  This looks like it is an inner sub-query possibly?  I would have to dig in further to see what exactly is going on, can you please provide the exact query you are manually testing with?  Thanks.

**Comment by pgorod** [comment]
Does this fix your problem?

https://github.com/salesagility/SuiteCRM/pull/9843/files

**Comment by reggieeuser** [comment]
Yes!  Thank you very much @pgorod that seems to solve the problem as the error message does not display after making those changes to SugarBean.php and Project tasks now display as expected.

I'm hopeful these changes will be reflected in future releases, but I'll retain this solution just in case.

Many thanks again!
