### ISSUE TITLE
Workflow action create record on CRON set incorrect date field values from related entity

### ISSUE THREAD

**Issue by re8260** [salesagility/SuiteCRM#10099]
#### Issue
Workflow action Create Record works different from on screen save and CRON.
On cron run it set incorrect date values based on CRON user date time format
When save from screen - all works correct
Example WF:
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/5eebcfb8-13a7-4f6f-a8d9-6188b0fe2020)

#### Expected Behavior

All START and END date should be same when saving from screen or by cron and should not be based on CRON user datetime format and timezone.
#### Actual Behavior

![image](https://github.com/salesagility/SuiteCRM/assets/18328936/40a402c7-103c-4138-901b-d9a2e15f2ce7)
There is same workflow runs before and after fix with 3 different sets:
1. When workflow runs from trigger ON_SAVE system user date format not effect on the result
2. When workflow runs from trigger In_Scheduler with system user date format DD/MM/YYYY+3
3. When workflow runs from trigger In_Scheduler with system user date format YYYY-MM-DD+3

#### Possible Fix

https://github.com/salesagility/SuiteCRM/pull/10101
#### Steps to Reproduce

1. Create Workflow with action create record
2. set bean datetime field from workflow bean date field (example screenshot attached)
3. run cron

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
Cron doesn't execute for any specific user.

Suppose your company has users in multiple timezones, which one would you use in CRON?

**Comment by re8260** [comment]
hi @pgorod I just cloned this repo from here, create Workflow, and run the cron, to show this issue and fix.

By "CRON USER" in my case I meant the current CRM user and not system user that running the cron function.
public/cron.php
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/6322b95d-41c7-4f75-a4d8-2501ccd0ba75)
by default is the user ID:1, admin user
public/modules/Users/User.php
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/7b7c5e6c-e2d2-413d-8279-78ca5f706e63)

When workflow runs with **same user** from trigger by screen or from cron running the result is different, the result must be the same.

**Comment by pgorod** [comment]
I understand where you get the user when it is triggered from the screen.

But when triggered from cron, how can it be the same? The same as which one? How do you plan to select the user from all the users in your system?

**Comment by re8260** [comment]
@pgorod I'm not selecting the user, the CRM do it in the CORE code.
I attached the files and lines that doing that from the CORE code.

From **screen** CRM always use the current logedin user, I'm not selecting it
From **scheduler (cron)** CRM use system user, by default its user with ID=1 - you can see the user in creaed by bean field

Here is my test workflow:
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/3ed28ddd-9273-4e6f-8563-889280273338)

And this is the event that was created from scheduler (from corn run)
```*    *    *    *    *     cd /home/www/public; php -f cron.php > /dev/null 2>&1```
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/66873796-0867-4910-98ae-90cc42af517b)

**Comment by serhiisamko091184** [comment]
One more time thanks for your contribution and additional details @re8260 ,
I am afraid, I can't replicate the issue: 

![image](https://github.com/salesagility/SuiteCRM/assets/116086008/1cd8e830-a893-48ad-b5f9-12011e59d554)

![image](https://github.com/salesagility/SuiteCRM/assets/116086008/eee0e351-4149-42c9-956e-c159d64bfb66)

Would you mind to provide me with additional information how to achieve this result, please:  
![image](https://github.com/salesagility/SuiteCRM/assets/116086008/cef6a37b-0b47-461f-9272-33846cb4bcfb)
 
Just detailed explanation/screenshots on further steps how do you change user date / time format preferences to reveal the bug.

Thank you very much!

Regards,
Serhii

**Comment by re8260** [comment]
Hi @serhiisamko091184 
Sure I will give you all information that you need because its 100% reproduceble on this branch `hotfix`.

1. change the `Run` option to be `Only In The Scheduler` (because `on save` it works correct)
2. go to your admin user and update date format to **dd**/**mm**/yyyy and set timezone other then 0
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/2fcfcbbe-8cd8-4c85-a916-74f3f6c62422)
3. run cron command from terminal: `php -f public/cron.php` or wait if its runs automatically every minute.
4. after cron run, new event bean will be created, validate that in was created by `admin` user (if was created not by admin, update the time format for user that create event and run cron again to create new event)
![image](https://github.com/salesagility/SuiteCRM/assets/18328936/231e7e5a-79e5-4514-8571-0904a0705648)
5. check the value of the event END date - it should be 1970....

**Comment by serhiisamko091184** [comment]
Hello @re8260 ,
thanks for your guidelines, 
everything is clear and I've replicated the issue. 

Many thanks.

Regards,
Serhii

**Comment by re8260** [comment]
@serhiisamko091184 this fix the issue https://github.com/salesagility/SuiteCRM/pull/10101
