### ISSUE TITLE
Calendar Settings - End Time Always 00 hours

### ISSUE THREAD

**Issue by tkoehn1962** [salesagility/SuiteCRM#10095]
#### Issue
Each time the Calendar Settings. is opened and the Begin Time or End Time has been saved with a value of >= Hour 10 the value displayed is always set to 00 Hours.  Clicking Apply without changing this value will result in an empty Calendar.  Saving the Begin Time or End Time Hour to any value < hour 10 will retain the settings and the Calendar will show correctly.  The values are actually saved.

#### Expected Behavior
When a user changes these settings,  it should open up with the previous saved values.

#### Actual Behavior
Each time you open the Calendar Settings.  The Begin Time and End Time is always set to 00 Hours anytime the these files have been saved greater than Hour >= 10.

#### Possible Fix
PHP Strings containing valid decimal ints, unless the number is preceded by a + sign, will be cast to the int type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer. [PHP Manual](https://www.php.net/manual/en/language.types.array.php)
In CalendarDisplay.php remove the code that attempts to force the key as a string.
`
        for ($i = $start_at; $i <= $num_of_hours; $i++) {
            // $i = $i . "";
            // if (strlen($i) == 1) {
            //     $i = "0" . $i;
            // }
            $hours_arr[$i] = $i;  // php does not cast integer keys as a strong so long as they are valid interger types.  So cast all as integers
        }
`
Case $d_start_hour and $d_end_hours as integers when calling get_select_options_with_id.
`        $TIME_START_HOUR_OPTIONS = get_select_options_with_id($hours_arr, intval($d_start_hour));  // modified
        $TIME_START_MINUTES_OPTIONS = get_select_options_with_id(array('0' => '00', '15' => '15', '30' => '30', '45' => '45'), intval($d_start_min));
        $TIME_END_HOUR_OPTIONS = get_select_options_with_id($hours_arr, intval($d_end_hour));  // modified
        $TIME_END_MINUTES_OPTIONS = get_select_options_with_id(array('0' => '00', '15' => '15', '30' => '30', '45' => '45'), intval($d_end_min));  // modified
`

#### Steps to Reproduce
1. Open Calendar / Settings.  Set End Time.  Click Apply.
2. Open Calendar / Settings.  See if End Time has been set.
3. 
#### Context
This was noticed when making a change in the settings and applying it. With out realizing it the End Time was set to 00:00. 
Upon Clicking Apply the Calendar no longer showed any events. After tracing the code and seeing that the get_select_options_with_id method is using the === operator which not only checks if the value matches but also checks to see if the variable type matches.  A dumping the $hours_arr reveals that all values < 10 are cast as a string and any value >= 10 are cast as integers.  This results in no match.

Any user that opens the settings and attempts to make a change and if no change is made to the End Time they will immediately be face with a blank Calendar.

#### Your Environment
* SuiteCRM Version used: Version 7.13.2 and Version 7.13.3  This may also exist in other Version 7.x
* Browser name: Version 114.0.5735.134 (Official Build) (64-bit)
* Environment:  MySQL, PHP 7.4
* Operating System: Debian 10 (buster)

**Comment by serhiisamko091184** [comment]
Hello @tkoehn1962 ,

thanks for raising this bug. 

This is no longer an issue in the latest version (7.14.2).

Fixed by this PR:
https://github.com/salesagility/SuiteCRM/pull/10195

Thanks a lot!

Regards,
Serhii
