### ISSUE TITLE
Results are not filtered in the Targets Module popup - SuiteCrm 7.13.3

### ISSUE THREAD

**Issue by kunanSA** [salesagility/SuiteCRM#10093]
#### Expected behavior
Filter results by creation date in targets module popup

#### Actual behavior
When trying to select from the "Targets" sub-panel, in the popup filter, you want to get records by "creation date". The action performed does not get results and the list is shown blank. The crm does not generate an error log, therefore it is not possible to know the origin of this problem in greater detail.

#### Steps to reproduce
1. Create multiple targets records (try altering their creation date per database) or use existing records.
2. Enter the "Targets List" module and create a record
3. Add for study the filter in the target audience popup, the field "Creation date"
4. In the detail view of "Targets list", try to select in the "Targets" sub-panel and the popup will open
5. Within the popup, try filtering by "creation date"
6. Get an empty list of results, where there are results and the filter is not working.

#### Context
This error comes from several versions of suitecrm, I was able to verify that it exists both in the version from 7.12.x to the latest 7.12.11. I could verify the same with the latest version of 7.13.x, up to its current version 7.13.3

#### Your environment
* SuiteCRM version used: 7.13.3
* Browser name and version: Chrome version 114 (64-bit)
* Environment name and version: PHP 7.4.33 and MariaDb +10
* Operating system and version: Debian 11

**Comment by pgorod** [comment]
I don't recognize some of those names (`Target audience`, `Public target list`), maybe you're working from a translation? You can have a look at the online demo and see how things are called there, to make it easier to reproduce your error exactly. Thanks
