### ISSUE TITLE
Cannot enter text in JotPad dashlet

### ISSUE THREAD

**Issue by reggieeuser** [salesagility/SuiteCRM#10094]
After adding the JotPad dashlet to SuiteCRM dashboard, we cannot enter text in the text field, which means it doesn't work. Clicking the Edit icon brings a popup that only shows:

##########
JotPad : Options

Title |                           JotPad
Height (1 - 300) |         200
##########
 
We have searched, but do not find this issue mentioned anywhere. 

There is nothing in suitecrm.log that relates to this.  In php_error_log, while we see nothing relating to JotPad specifically, we do find this relating to dashlets:

##########
652567 [25-Jun-2023 13:57:45 America/New_York] PHP Warning:  Undefined array key "bold" in /var/www/suitecrm/cache/smarty/templates_c/%%14^148^14804A90%%DashletGenericDisplay.tpl.php on line 184
652568 [25-Jun-2023 13:57:45 America/New_York] PHP Warning:  Undefined array key "link" in /var/www/suitecrm/cache/smarty/templates_c/%%14^148^14804A90%%DashletGenericDisplay.tpl.php on line 184
652569 [25-Jun-2023 13:57:45 America/New_York] PHP Warning:  Undefined array key "customCode" in /var/www/suitecrm/cache/smarty/templates_c/%%14^148^14804A90%%DashletGenericDisplay.tpl.php on line 184
652570 [25-Jun-2023 13:57:45 America/New_York] PHP Warning:  Undefined array key "tabindex" in /var/www/suitecrm/include/Smarty/plugins/function.sugar_field.php on line 104
652571 [25-Jun-2023 13:57:45 America/New_York] PHP Warning:  Undefined array key "link" in /var/www/suitecrm/cache/smarty/templates_c/%%14^148^14804A90%%DashletGenericDisplay.tpl.php on line 184
##########

From DashletGenericDisplay.tpl:

##########
182                         {if !empty($quickViewLinks)}
183                         <td width='1%' class='{$_rowColor}S1' bgcolor='{$_bgColor}' nowrap>
184                                 {if $pageData.rowAccess[$id].edit}
185                     {capture name='tmp1' assign='alt_edit'}{sugar_translate label="LNK_EDIT"}{/capture}
186                     {capture name='tmp1' assign='alt_view'}{sugar_translate label="LBL_VIEWINLINE"}{/capture}
187                     <a title='{$editLinkString}' class="list-view-data-icon" href='index.php?action=EditView&module={$pageData.bean.moduleDir}&record={$rowData.ID}&offset={$pageData.offsets.current+$smarty.f    oreach.rowIteration.iteration}&stamp={$pageData.stamp}&return_module=Home&return_action=index'> <span class="suitepicon suitepicon-action-edit"></span></a>
188                                 {/if}
189                                 {if $pageData.access.view}
190                 <a title='{$viewLinkString}' class="list-view-data-icon" href='index.php?action=DetailView&module={$pageData.bean.moduleDir}&record={$rowData[$params.parent_id]|default:$rowData.ID}&offset={$    pageData.offsets.current+$smarty.foreach.rowIteration.iteration}&stamp={$pageData.stamp}&return_module=Home&return_action=index' title="{sugar_translate label="LBL_VIEW_INLINE"}"> <span class="suitepicon sui    tepicon-action-view-record"></span></a>
191                                 {/if}
192                         </td>
193                         {/if}
#########

This problem exists when using Firefox 114.0.1, and Chromium 114.0.5735.106.

We are running SuiteCRM 8.3.0 on:

Ubuntu 22.04 with
PHP v. 8.0.28,
MySQL: 8.0.33-0ubuntu0.22.04.2,
Apache/2.4.57 (Ubuntu)

We'll appreciate any guidance!

**Comment by reggieeuser** [comment]
PS - Also tested with Microsoft Edge 114.0.1823.43 and Google Chrome 114.0.5735.110 - same result.

Thanks!

**Comment by pgorod** [comment]
Any JS errors in the browser's Developer Console?
