### ISSUE TITLE
Meeting/Call/Task not sync to Calendar via API

### ISSUE THREAD

**Issue by lukyrys** [salesagility/SuiteCRM#101]
Meeting/Call/Task not sync to Calendar when i add or update one of them via soap api...
How to solve it? 
This problem i also have problem in SugarCRM 6.5.7

Thanks

**Comment by mattlorimer** [comment]
you need to add a relationship in the meetings_users relationship between the meeting and user who's calender you want it to show, simply assigning the user to a meeting will not show in there calendar, similar for calls etc
