### ISSUE TITLE
Calendar issue:  Meetings don't show for users with restricted time access

### ISSUE THREAD

**Issue by CaptainChainsaw** [salesagility/SuiteCRM#1011]
There is an issue with the calendar where meetings aren't showing if there is a time overlap, this is apparent on the shared calendar.  If a meeting is set on the calendar for an admin user starting at 8am and finishes at 8pm and the calendar is viewed by another user who only has access to the calender between 10am and 6pm the meeting won't show at all.  This user should see the meeting as being from 10am-6pm as that's all they have access to.

**Comment by samus-aran** [comment]
@CaptainChainsaw is this not similar to a issue you dealt with?  If so, can you provide the fix?

**Comment by Mausino** [comment]
maybe has something similary with #1890
