### ISSUE TITLE
Unable to import CSV files 

### ISSUE THREAD

**Issue by Tylerke254** [salesagility/SuiteCRM#10117]
I am unable to import csv files on all modules including the custom ones. I am running Suitecrm 8.3.1 

#### Expected Behavior
I downloaded the file format from the crm and keyed in data in the correct fields. I even removed phone numbers and emails. But I get a clear screen after verifying the fields to be imported. 

#### Actual Behavior
I am getting the following error 

Tue Jul 18 10:44:59 2023 [19830][1][ERROR] File upload://import/dupes_1.csv cannot be touched
Tue Jul 18 10:44:59 2023 [19830][1][ERROR] File upload://import/dupesdisplay_1.csv cannot be touched
Tue Jul 18 10:44:59 2023 [19830][1][ERROR] File upload://import/errorrecords_1.csv cannot be touched
Tue Jul 18 10:44:59 2023 [19830][1][ERROR] File upload://import/errorrecordsonly_1.csv cannot be touched
Tue Jul 18 10:45:20 2023 [20548][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:45:20 2023 [20548][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:49:59 2023 [25938][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:49:59 2023 [25938][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:49:59 2023 [25938][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:49:59 2023 [25938][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_quotes
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship emails_email_templates
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship am_projecttemplates_contacts_resources
Tue Jul 18 10:50:07 2023 [26438][1][ERROR] Unable to find relationship projects_contacts_resources

#### Steps to Reproduce

* SuiteCRM Version used: 8.3.1 
* Browser name and version (e.g. Firefox, Safari, Chrome)
* Environment name and version (e.g. MySQL, PHP 8.0 & 8.1)):
* Operating System: Installed through softaculous on cpanel

**Comment by pgorod** [comment]
This is an issue for the Community Forums, not for Github.

You need to troubleshoot your installation first. Those files that cannot be touched are probably a sign of insufficient permissions or wrong file ownerships.

**Comment by Tylerke254** [comment]
Okay. Thank you.

**Comment by johnM2401** [comment]
Hey Folks!
Thanks for getting in touch @Tylerke254 

I'm closing this for now as, like @pgorod noted, the un-touchable files indicate a permissions/ownership issue.

If you have ensured your permissions/ownership values are set well and are still experiencing issues, please feel free to get back in touch!

Thanks
John
