### ISSUE TITLE
Cache files given overly permissive file permissions

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#10131]
#### Issue
When cache files are rebuilt, the default file mode set by sugar_file_put_contents_atomic is too permissive by default and the file mode set in the config is not applied.

#### Expected Behavior
File mode defined in the config should be reflected when cache files are rebuilt.

#### Actual Behavior
File mode 755 is applied by default and the filemode set in the config is not used.

#### Possible Fix
Use filemode defined in the config.php

#### Steps to Reproduce

1. Delete cache
2. Load a page in the crm to rebuild a cache file
3. See filemode is 755 and not what is defined in the config

#### Context
Cache files are rebuilt without reflecting the filemode defined in the config.php

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): 18.04

**Comment by johnM2401** [comment]
Hey @JackBuchanan

I've given this a try on a local copy of 7.13.4/php7.4 and it appears to work as expected, (unless ive perhaps misunderstood your issue/steps?):

I have the file_mode set as 493 (which translates to 755 perms):
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/4a3f2ee2-a396-415c-baba-8077d5e8087a)

Deleting Cache and accessing Homepage builds the langauge files with 755 perms:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/b2952220-b2ae-4671-a1f6-ac43ac80d072)


Then, if I set the file_mode to 420, (which translates as 644):
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/383630c4-1821-463c-b679-d23fadc3dcf9)

Clearing Cache & loading homepage builds the lang file with 644 perms:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/3a078df0-38a2-4901-9fc2-6c964c81e804)


Do you know if this is perhaps on a specific version of Suite?
(Or on a specific environment/setup?)

Thanks!

**Comment by JackBuchanan** [comment]
Hey John,

I maybe should have been more specific with what files are built with 755, only some files are rebuilt with the 755 permissions.

The main areas are the cache vardefs or relationship files, I believe if you check the files at /cache/Relationships/relationships.cache.php or /cache/modules/<module>/<module>vardefs.php you should be able to replicate.

**Comment by johnM2401** [comment]
Hey!

Ah yep, Can confirm the issue on /cache/modules/Accounts/Accountvardefs.php

Have file_mode set as 420/644, and that file built as though it was 755:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/d9e8bcdf-ae6d-4600-b238-73cb7030a854)

Thanks Jack!
