### ISSUE TITLE
7.5.1 Project Gantt View cuts off Project Task field

### ISSUE THREAD

**Issue by abeo** [salesagility/SuiteCRM#1014]
The default setting in 7.5.1 for Project Gantt View cuts off the Project Task Name field to short, cutting off most of the Project Task name making them hard to determine what a particular Project Task is.

Suggested fixes; make the field longer by default or, ideally, allow for adjusting the Project Task Name field width.

![suitecrm-predecessors](https://cloud.githubusercontent.com/assets/1320436/13353652/dd15cc46-dc63-11e5-85a9-efb4a2938bc7.PNG)

**Comment by recci** [comment]
This is because your Predecessor names are very long so all the space in the table is used up. The size of the div that contains the gantt chart is a fixed width.

**Comment by abeo** [comment]
Recci,

Thanks for the reply. 

Can you tell why my Predecessor field names are all running together? They should not be all showing up for every Project Task. 

~eric

**Comment by recci** [comment]
Ah I see, there must be another issue causing that to happen with the Predecessor names. Will look into it when I get some time.

**Comment by abeo** [comment]
Okay, thanks.

**Comment by shogunpol** [comment]
The issue has been tested on the recent version of SuiteCRM(7.7.4), and it not appear,
@abeo , can you confirm the issue is not exist any more? 
If yes can you close an issue?

**Comment by ijdavie** [comment]
The fields do not appear to be cut off but hidden to allow the span of the table to appear as expected if the table is given more space using the drag element between that and the gant chart the text appears. The other issue with the predecessor can be found under #1013,
