### ISSUE TITLE
New cases display orphaned case attachments

### ISSUE THREAD

**Issue by ojs87** [salesagility/SuiteCRM#10141]
#### Issue
When a Cases record with Notes related to it is deleted, the orphaned notes will be loaded into the Case Attachements field when creating a new Cases record.

This causes a display bug on the Create Case view

#### Expected Behavior
If a Case has no id yet on the edit view, no Case Attachments should be loaded

#### Actual Behavior
Orphaned Case Attachments are displayed in the Case Attachments field

#### Possible Fix
in the display_case_attachments function in Case_Updated.php, return if the $case->id is empty

#### Steps to Reproduce

1. Create a Cases record
2. Add/relate a Notes record to the Cases record
3. Delete the Case
4. Click on Create Case
5. The Case Attachments field will contain the orphaned Note

#### Your Environment

* SuiteCRM Version used: SuietCRM 7.12.12
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 106
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04.3 LTS

**Comment by johnM2401** [comment]
Hey!

I've given this a try in 7.14, but I'm not sure if I can replicate

OOTB, when creating a new Case, the "Case Attachments"/"Case Updates" fields don't show on the Editview

Do you know if you perhaps need any customizations to Cases for this?

After following the steps above, (and adding the Case Attachments/Updates fields to editview), it shows as following after Deleting a Case->Creating a new case:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/2eac97ee-e76a-40a8-98c7-751276efc50c)


Do you maybe have some more steps to help replicate this?

Thanks!

**Comment by ojs87** [comment]
Hi @johnM2401,

Thanks for testing that, sorry my steps were not as comprehensive as they should have been.

There has to be a note with an attachment added to a Case before deleting it, if the note doesn't have an attachment it doesn't show the link.

So the easiest way to recreate this is to just create a Note, relate to a Case with no Case selected, and upload a random image/file to the Note.

You can also relate it to a Case and then delete the case, which is how this issue first arose.

This should then show the orphaned link on the Create Case view.

Thanks
