### ISSUE TITLE
Use default from settings for emails when composing emails - specific to version 7.11.x

### ISSUE THREAD

**Issue by JamesBrickell** [salesagility/SuiteCRM#10149]
#### Issue

When composing an email within Suite, if Inbound Email settings are not set up for the user the from dropdown box will not populate with data. The history of the email will also record the from as null. However the email that is actually sent is fine and contains the default from that is in the suites settings.

#### Expected Behavior
If no inbound email settings are found, it should populate with the systems default from settings.

#### Actual Behavior
The 'From' dropdown box will not populate with any data as no data is there to be found.

#### Possible Fix
In EmailsControllerActionGetFromFields.php in the handleActionGetFromFields function, if $dataAddresses populate a similar data structure with values from the config table pertaining to the values associated with orginizations settings. 

#### Steps to Reproduce

1. Have no inbound email settings for a users.
2. Compose an email, from in box will not be populated with data.

#### Context

This bug, is of low priority,  it effects the visuals of composing an email and records it as null for the purpose of history. The email that is actually sent does contain the default system ```From Address``` and ```From Name```. I also believe this bug is fixed for the newer versions of suitecrm, but I am unable to prove so using the demo site. 

#### Your Environment
* SuiteCRM Version used: 7.11.23
* Environment name and version (e.g. MySQL, PHP 7): Php 5.6.

**Comment by JamesBrickell** [comment]
I have a potential fix for this that is compatible with php 5.6; however I don't see a hotfix-7.11.x branch should one be created for the purpose of patching this version of suitecrm since it is still supported ?

**Comment by mattlorimer** [comment]
Support ended for 7.11 in October 2021, where do you see it still supported?

https://docs.suitecrm.com/community/supported-versions/

**Comment by JamesBrickell** [comment]
You are correct my apologies, I though 7.11 was still supported based off of the issue template.
```-- Please be aware that as of the 31st January 2022 we no longer support 7.10.x.```
That was a bad assumption on my part thank you for the helpful link!
