### ISSUE TITLE
Numbering display issue on subpanels

### ISSUE THREAD

**Issue by serhiisamko091184** [salesagility/SuiteCRM#10157]
#### Issue
Within the header of the subpanel, on the right hand side, the count/numbering/total for subpanel records is not correctly aligned vertically.

#### Expected Behavior
Example from SuiteCRM 8: 
![image](https://github.com/salesagility/SuiteCRM/assets/116086008/4c9e7abf-f561-46b4-bd05-2fb4ad8fcc67)

#### Actual Behavior
Missalignment
![image](https://github.com/salesagility/SuiteCRM/assets/116086008/f4220b61-ab60-4b76-8705-a07973852c37)

#### Possible Fix
Slight CSS changes in panels.scss

#### Steps to Reproduce
Open any subpanel of the record.

#### Context
Make UI cleaner.

#### Your Environment

* SuiteCRM Version used: 7.14.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 115.0.5790.170 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4, 10.6.5-MariaDB
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by johnM2401** [comment]
Hey!

I've had a look at this, and it does look good to me as-is

However, I think it could use some further improvement.

See screenshot, taken after applying fix:

The counter is still off-centre, and quite high on the row:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/ae77729f-a40c-426f-9154-97188ca188bb)

Further breaking it down, it seems like it's a good few px off-center:
![image](https://github.com/salesagility/SuiteCRM/assets/13675281/48804387-b4e2-459d-9707-40e2d0aeb21c)

(Blue Lines is the text alignment, Red line is the centre of the buttons)

What are your thoughts?
