### ISSUE TITLE
Emails don't show subject, from, to, cc, bcc fields

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#10172]
#### Issue

Fresh installation of SuiteCRM 7.14

I tried find this issue in other tickets but i was not, please if it duplicate, please let me know to which issue in github.

If you set up emails => outbound + inbound  and when you load emails

It missing information like: **FROM, TO, CC, BCC, SUBJECT**

This is listview
![email_issue1](https://github.com/salesagility/SuiteCRM/assets/5773777/80cf6e72-a107-40c7-a466-bd9516fbeaa5)

This is detail view of non imported email
![email_issue2](https://github.com/salesagility/SuiteCRM/assets/5773777/7bdf24ca-04e3-4d42-8f89-adaf946c58e0)

This is detail view of imported email
Here you can see that FROM, TO fields are filled. I assume that will also work for CC, BCC
![email_issue3](https://github.com/salesagility/SuiteCRM/assets/5773777/6bc7cf28-b9cf-4166-b397-be9c591179f1)

#### Expected Behavior

Should work, because in DB i see this informations, when you import it.

#### Actual Behavior

See images. 
In every view is missing SUBJECT
In list view is missing SUBJECT. To field is filled
In detail view is missing all this fields.
In imported view is missing only SUBJECT

#### Steps to Reproduce

1. Connect email mail server
2. List Emails
3. Detail Email
4. Import Email

#### Your Environment

* SuiteCRM Version used: 7.14
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 117
* Environment name and version (e.g. MySQL, PHP 7): 5.7.42,   php 8.1.12
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by aurelien1980** [comment]
Same here. I dont know how to do it. I connect to OFFICE 365
