### ISSUE TITLE
Finsales - Definition and use

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1018]
What is Finsales and in what context is this used?
`'LBL_FINSALES' => 'Finsales',`

It should have a description field too. 

Language file with the term:
https://github.com/salesagility/SuiteCRM/blob/master/modules/Connectors/language/en_us.lang.php

**Comment by mattlorimer** [comment]
its not used, probably should be removed

**Comment by shogunpol** [comment]
@horus68 , this label is not used and will be removed.

**Comment by shogunpol** [comment]
(tag and Close issue)

@horus68  - Thank you for highlighting this issue, however, this is a duplicate of issue #2552. This is issue will be closed, please follow the original issue.

**Comment by horus68** [comment]
No problem, this is an old one (nine months!)
