### ISSUE TITLE
Gmail imap bug

### ISSUE THREAD

**Issue by JoshTW** [salesagility/SuiteCRM#1019]
I have installed SuiteCRM but have run into the problem of not being able to connect to my gmail account. I can setup and connect to my live.com imap account just fine (imap-mail.outlook.com) and can connect to my gmail imap from a php file and the command line of the server using openssl.  The openssl test gave this error `Verify return code: 20 (unable to get local issuer certificate)` but the error is fixed by including a non-existent path in the `-CApath` argument (causing it to open the default CA location).

This is the file that I successfully tested connecting to gmail with. I crossed out the username and password and renamed it to have ".txt" at the end but otherwise this is what I ran on my SuiteCRM server with same owner and group as the SuiteCRM files.

[testimap.php.txt](https://github.com/salesagility/SuiteCRM/files/149667/testimap.php.txt)

Apache is running as the same user as the entire SuiteCRM folder and files on my server (this is also true for the test php file linked above).  I tried both php70 and php56. I am running on a freeNAS server (which is build on freeBSD). With Apache inside a jail with the following pkg's installed.
`pcre-8.37_4`
`apache24-2.4.18`
`libxml2-2.9.3`
`php70-7.0.3`
`mod_php70-7.0.3`
`libedit-3.1.20150325_1`
`mysql56-client-5.6.27`
`php70-extensions-1.1` Which installed a bunch of other php70 pkg's
`php70-mysqli-7.0.3`
`php70-mbstring-7.0.3`
`php70-zip-7.0.3`
`php70-zlib-7.0.3`
`php70-curl-7.0.3`
`php70-imap-7.0.3`
`php70-gd-7.0.3`

I have since removed php70 and installed php56, and installed `php56-openssl`. And even tried creating a second working live.com IncomingEmail settings and manually modified the entry in `inbound_email` table on the database. I also tried changing the `service` field from `::::ssl::imap::::::` to `::::ssl-nocert::imap::::::` and `::::novalidate-cert::imap::::::` but have not figured out how to make it work.

I have tried to find any security messages or setting on gmail that might be causing a problem. I even re-enabled "Access for less secure apps". If it was a problem on google's end, I would think that the php test file I used would have failed to work. (But the testimap.php file worked to show me my gmail inbox).

Any suggestions would be welcomed, this e-mail integration feature would make using SuiteCRM so much more useful.

Josh

**Comment by sgaved** [comment]
Hello Josh,

I am able to connect to gmail, using the settings of port 587 over tls. Have you tried these settings?

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this is still an issue it can be reopened with more information. 
Thanks.
