### ISSUE TITLE
Calls - duration_minutes field value is lost when editing a call

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#10198]
#### Issue

When edit an existing call, the value selected in the `duration_minutes` field is lost.

![Lost_minutes_duration](https://github.com/salesagility/SuiteCRM/assets/61022311/d34f4fe2-1783-470e-a1b4-68ce2b9c0f78)

#### Expected Behavior
The `duration_minutes` field value should not be lost when editing a call

#### Steps to Reproduce
1. Create a call and select a value other than 0 in the `duration_minutes` field
2. Check that when you edit it again, the value of the `duration_minutes` field has been lost

#### Context
High priority

#### Possible Fix

The field is defined as an integer although in this view it behaves like an enum, so we think that the `===` operator is the cause of the selected value being lost.

Without being sure of the proposal, we propose to change the line 1893 of the include/utils.php file, replace `($option_key !== '' && $selected_key === $option_key)` with `($option_key !== '' && $selected_key == $option_key)`

Related with this commit: https://github.com/salesagility/SuiteCRM/commit/a83a845a4726d312abc3e3837e841917d3c575c2

#### Your Environment
* SuiteCRM Version used: 7.12.12
* Environment name and version: MariaDB 10.6.5, PHP 7.4
* Operating System and version : Ubuntu 20.04

**Comment by serhiisamko091184** [comment]
Hi @SinergiaCRM,

thanks for raising this bug.

This is no longer an issue in the latest version (7.14.2). 

This particular PR fixes the issue: 
https://github.com/salesagility/SuiteCRM/pull/10195

Thanks a lot! 

Regards, 
Serhii
