### ISSUE TITLE
Problem synchronizing with ElasticSearch/get_list returning row_count=0 when list contains rows

### ISSUE THREAD

**Issue by gboban** [salesagility/SuiteCRM#10209]
When running Elasticsearch indexing from admin->Elasticsearch (buttons "Schedule full indexing" and "Schedule partial indexing"), the resulting cron job is not sending data to Elasticsearch. Cron job finishes with status success but no data is sent.

#### Expected Behavior

To be able to see data sent to Elasticsearch using Elasticsearch query such as ```http://localhost:9200/accounts/_search?pretty``` or ```http://localhost:9200/contacts/_search?pretty``` or having count (e.g. ```http://localhost:9200/accounts/_count?pretty```) greater than zero since I used test data imported during SuiteCRM installation.

#### Actual Behavior

Above Elasticsearch queries return zero hits (_count being 0 as well).

#### Possible Fix

Observing line 173 in ```lib/ElasticSearch/ElasticSearchModuleDataPuller.php```, I noticed that ```$results['row_count']```is zero even when corresponding ```$results['list'']``` contains array with non-zero rows.

Replacing given line (```return $results['row_count'] ? $results['list'] : null;```) with:
```return count($results['list']) ? $results['list'] : null;```

Solved the problem but it seems that the real problem is in ```$this->seed->get_list(....)``` (line 168) which returns results with row_count=0. The **PROPER** solution should look into **get_list** function.

#### Steps to Reproduce

1. Install SuiteCRM with test data
2. Ensure that you don't have cache/ElasticSearchIndexer.lock file if you run Elasticsearch synchronization before
3. Go to admin-&gt;Elasticsearch
4. Start full indexing ("Schedule full indexing") button
5. Wait for the cron job to finish
6. Check data in your Elasticsearch (e.g. ```http://localhost:9200/accounts/_count```

Note: you may need to fix issue #10207 first.

#### Context

Trying to synchronize SuiteCRM with Elasticsearch

#### Your Environment

* SuiteCRM Version used: 7.14.0 / Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 117.0.5938.92 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.1.2-1ubuntu2.14
* Operating System and version (e.g Ubuntu 16.04):
XUbuntu
Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release: 22.04
Codename: jammy

**Comment by JanSiero** [comment]
Fixed as per #10275
