### ISSUE TITLE
Dynamic required fields don't work in v 8.2.4

### ISSUE THREAD

**Issue by ViralAgency** [salesagility/SuiteCRM#10218]
#### Issue

It is impossible to use dynamic logic to set a field as "required" as described in the documentation available at the link: [Official Documentation](https://docs.suitecrm.com/8.x/developer/extensions/frontend/logic/field-logic/fe-extensions-required-logic/)

In /public/legacy/extension/modules/Accounts/Ext/Layoutdefs/customfilename.php: 

```
$dictionary['Account']['fields']['vat_number_c'] = array(
    'name' => 'vat_number_c',
    'vname' => 'LBL_VAT_NUMBER',
    'type' => 'varchar',
    'len' => 13,
    'comment' => 'Partita IVA',
    'merge_filter' => 'enabled',
    'logic' => [
        'required' => [
            'key' => 'required',
            'modes' => ['edit', 'create'],
            'params' => [
                'fieldDependencies' => [
                    'fiscal_code_c'
                ],
                'activeOnFields' => [
                    'fiscal_code_c' => [
                        ''
                    ],
                ],
            ],
        ]
    ],
);
```

#### Expected Behavior
The fields **vat_number_c** becomes required if the field **vat_number_c** is not filled.

#### Actual Behavior
No effects.

#### Possible Fix
Fix documentation or code.

#### Steps to Reproduce
1. Create a custom field like above.
2. Run Repair & Rebuild. 
3. Try to insert values in edit mode.
4. Check if condition is triggered.

#### Context
I try to get required fields that are activated dynamically.

#### Your Environment
* SuiteCRM Version used: 8.2.4
* Browser name and version): Chrome Version 117.0.5938.92 (Official Build) (x86_64)
* Environment name and version: PHP 7.4.33 (cli), MySql Ver 8.0.33 for Linux on x86_64 
* Operating System and version: Ubuntu 22.04.3 LTS

**Comment by ViralAgency** [comment]
The fields were defined 2 times, once in the studio and a second time in the code, and for this reason, the data validation logic did not work as expected.

**Comment by chris001** [comment]
This issue is about v8 so it should be moved to https://github.com/salesagility/SuiteCRM-Core/issues/
