### ISSUE TITLE
createcase group mail box Archiving all Emails

### ISSUE THREAD

**Issue by opensourcecrm** [salesagility/SuiteCRM#1023]
Hi 

Can anyone suggest a fix how to resolve it. we have setup an group inbound email to create cases for our support system. previously it was working fine. but now it fetching all the emails from inbox creating a email record in suitecrm but its achieving all the emails due to which cases are not getting created.

even i tried to figure out with inbondemail.php but no success was achieve.  can anyone suggest me a right fix for this issue.

**Comment by ghermans** [comment]
What version are you using?

**Comment by opensourcecrm** [comment]
Suite7.4.3

**Comment by opensourcecrm** [comment]
Hi Ghermans,

Can you plz help us out with this issue.

**Comment by ghermans** [comment]
@opensourcecrm  did you try Administrator -> Repair -> Quick Repair and Rebuild ?
Also maybe it is a good idea to create a topic on the [forum](https://suitecrm.com/forum/index).

**Comment by opensourcecrm** [comment]
we have already posted it on the forum but no response over there. even the case update functionality is also not working.
https://suitecrm.com/forum/suitecrm-7-0-discussion/8427-createcase-group-mail-box-archiving-all-emails

**Comment by willrennie** [comment]
This looks like a specific bug/issue with your CRM and we will respond accordingly to your forum post.

**Comment by opensourcecrm** [comment]
Hi Will

Its not a specific instance issue i tried three instance with same version of the SuiteCRM 7.4.3 the issue is same in all version.

**Comment by mattlorimer** [comment]
what schedulers do you have enabled?

**Comment by opensourcecrm** [comment]
@mattlorimer please find the attached screen shot of the schedulers enabled in the system.

![file1](https://cloud.githubusercontent.com/assets/17160050/14048430/38a2102a-f2d4-11e5-8120-cfb6768b7ddd.png)

![file2](https://cloud.githubusercontent.com/assets/17160050/14048450/55c89494-f2d4-11e5-8ca5-66c4a0091353.png)
