### ISSUE TITLE
Remove Modules from SuiteCRM

### ISSUE THREAD

**Issue by zackzulg** [salesagility/SuiteCRM#1026]
Hey guys, 

I'de like to know how to remove modules from SuiteCRM Project, actually I just need Devis, Prospects, Accounts and some other modules. 

Regards.

**Comment by Mausino** [comment]
Hi, @zackzulg  as i told you before .. this is spam !!!

I you need answers go to https://suitecrm.com/forum/index

I hope, that you understand it :-1:

**Comment by zackzulg** [comment]
Good morning Mausino, 

As I can see there is no participation there, I mean even when I put my issues there I had no answer, I could fix my issues by disscussing on github.
I can see github.com/salesagility/"SuiteCRM/issues" so to me it's a place to share issues ( what I understood from the link ).

Regards.

**Comment by samus-aran** [comment]
Hi @zackzulg 
Asking how to use the system is different than raising an 'issue'.  The forums is there for raising issues and user interaction with the system.  But essentially GitHub we would prefer that it was just kept to the topic of issues with the system.

Now I have found your forum post/thread and it was only created 30ish minutes before you created this GitHub 'issue'.  Now 30 minutes isn't a long time...

I will answer your question in the next 30 minutes myself.  See you on the forums.
