### ISSUE TITLE
SearchView.tpl broken for Assigned_user_name after 7.14.2 update

### ISSUE THREAD

**Issue by cyb456** [salesagility/SuiteCRM#10276]
#### Issue

looks like {php} is no longer a valid tag in smarty 4
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/SugarFields/Fields/Assigned_user_name/SearchView.tpl#L43

#### Steps to Reproduce

1. Enable a assigned/created/modified user search field, this will break the entire listview from loading
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.14.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chromium Version 119.0.6045.159 (Official Build) snap (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 11.2.2, PHP 7.4.33
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by cyb456** [comment]
I'd argue this is important not moderate, there is no practical workaround other than commenting out the code that makes it work

**Comment by cyb456** [comment]
Sorry Just saw this: https://github.com/salesagility/SuiteCRM/issues/10264 should I close this issue?

**Comment by johnM2401** [comment]
Hey @cyb456 

Ahh, good catch, thank you for bringing that ticket up!
Apologies, that other one must have slipped under my radar, haha

As #10264 does appear to be the same issue, I'll close this ticket off. 
However, please feel free to pass over any extra info you may have, (or even your proposed solution), to #10264 

Thank you again!
