### ISSUE TITLE
Error installing custom module

### ISSUE THREAD

**Issue by edusca** [salesagility/SuiteCRM#1028]
Hi, I'm using 7.5.1 version of SuiteCRM, and when I want to install a custom module (exported from the module builder) there is an error on my log and the process end:

PHP Fatal error:  Call to undefined method AXION_Assembly_Service_sugar::AXION_Assembly_Service_sugar() in /var/www/suitecrm72/modules/AXION_Assembly_Service/AXION_Assembly_Service.php on line 47, referer: http://localhost/suitecrm72/index.php?module=Administration&view=module&action=UpgradeWizard_prepare

I have an old package (one month old), and the class AXION_Assembly_Service_sugar doesn't have any more the AXION_Assembly_Service_sugar() method, now is using the __construct method, is this a bug in the module loader in the last version of Suite?

Thanks in advance...

**Comment by mattlorimer** [comment]
Please ask your question on the [support forum](https://suitecrm.com/forum/index)
