### ISSUE TITLE
Adding a new field with a new dropdown list results in core field edit

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1029]
An issue occurs when a user adds a new drop down field with a new drop down list for the field. For example, if a user adds a new 'employees' field with a drop down list 'employees_list' and saves this, the existing core 'employees' field is modified, instead of a new 'employees_c' field being generated. This could have further implications on existing functionality/data.

**Comment by vladbar** [comment]
@willrennie This issue seems to be fixed already - if you try to add a dropdown field with a similar name, validation functionality will not allow it through (it will display the following message):
Invalid Value: Field Name already exists

**Comment by willrennie** [comment]
Nope, this is still a valid bug. Please re-read the issue carefully and you will be able to reproduce. Please ask myself or @JimMackin if you still can't replicate.

**Comment by vladbar** [comment]
there are similar issues with fields type: Radio and MultiSelect
These issues remain to be fixed.

**Comment by vladbar** [comment]
Both pull requests 80572f3 and 0403a7f should be applied in order to fix this issue.

**Comment by vladbar** [comment]
0403a7f had a problem. 
Both pull requests 80572f3 and c134a4a should be applied in order to fix this issue.
