### ISSUE TITLE
LDAP Authentication Issue

### ISSUE THREAD

**Issue by maarisk** [salesagility/SuiteCRM#10303]
In SuiteCRM 7.14.x instances randomly users which are authenticated against LDAP cannot login and get Insufficient Privileges when correct username and password is supplied.

#### Issue
Instances exhibiting issue had previously authenticated bind to LDAP which later was disabled. In these random cases it is noticed, by enhancing debugging on LDAPAuthenticateUser.php, that during login process SuiteCRM is still getting from somewhere old bind credentials which results in failed login.

After admin logs in and saves Password Options without any changes (no bind credentials are shown), users can login normally.

#### Expected Behavior
User is successfully logged in after supplying correct username and password

#### Actual Behavior
User is shown error Insufficient privileges

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.14.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04):

**Comment by chris001** [comment]
Screenshots?  
Log entries?  
Exact steps to reproduce?  
Does it reproduce on the online demo?

**Comment by maarisk** [comment]
Error screenshot:
<img width="533" alt="Screenshot 2024-01-11 at 21 20 50" src="https://github.com/salesagility/SuiteCRM/assets/15897145/c2db7471-adf8-48d0-95b7-0db791c096b7">
Custom log entry produced from LDAPAuthenticateUser.php function ldap_rdn_lookup:
Thu Jan 11 21:20:39 2024 [3790][-none-][ERROR] LDAP Props: Server = 127.0.0.1; BaseDN = ; Admin user = uid=maskeduser,cn=users,dc=server,dc=masked-domain,dc=com; User attr = uid; B
ind attr = dn; Port = 389

Password management settings:
<img width="759" alt="Screenshot 2024-01-11 at 21 26 23" src="https://github.com/salesagility/SuiteCRM/assets/15897145/e2842396-1050-4b8b-a969-0e4756b7f2f0">
<img width="764" alt="Screenshot 2024-01-11 at 21 26 33" src="https://github.com/salesagility/SuiteCRM/assets/15897145/2404a880-1f6a-4ed6-a516-5833f0ac8ac5">

Steps to reproduce:
1. In Admin -> Password Management create authenticated bind to LDAP server (Authentication checked and User name and Password fields that are shown filled out) and save. Login several times.
2. Change LDAP bind user password
3. Disable authenticated bind (clear user name and password fields as well as uncheck Authentication) and save settings
4. Try to login (issue comes up randomly and can be rectified with logging in as administrator and saving Password Management options without any changes)

In situations when user canot login, after adding new line to be logged, it turns out, old LDAP bind authentication settings are retrieved from somewhere. In database table config, these ldap settings have been deleted.

On the online demo issue hasn't been tested.

**Comment by chris001** [comment]
Which LDAP server is it, OpenLDAP on Linux?
What happens when you set "Login attribute" to `cn`  and try to login?  This is the value given for OpenLDAP in the Help `?` popup.

**Comment by maarisk** [comment]
The main issue here is not with LDAP server itself and Login attribute, but with the fact that randomly old Authenticated binding data, including old password, is retrieved during login process although it has been disabled.

**Comment by chris001** [comment]
Can you 1. delete the contents of the `cache` folder, located in suitecrm root folder, 2. delete browser cache, 3. try again to login, and post your results back here, including error message on screen, and error log messages, if any?
