### ISSUE TITLE
OAuth Providers and Connections change from Group to Personal on edit

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#10316]
If you create a Group Provider or Connection and save it, it is Type "group".
If you now edit it it becomes Type "Personal".

#### Expected Behavior
Type should stay as saved and not change.

#### Actual Behavior
Type gets changed to "Personal"

#### Steps to Reproduce

1. Create External OAuth Provider with type "Group"
2. Save
3. Open in Detailview, Type shows "Group"
4. Go to Editview, Type shows "Personal"
5. Save
6. You now saved tha Provider as Personal instead of Group

#### Your Environment

* SuiteCRM Version used: 7.14.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by johnM2401** [comment]
Hey!

Thanks for getting in touch and raising this!

Luckily, we've recently merged a PR on this exact issue: https://github.com/salesagility/SuiteCRM/pull/10312

This should resolve this issue, but please let us know if it does not.

Thanks!

**Comment by gunnicom** [comment]
Ok, will test it later. But as it seems to be the bug, I close here.
