### ISSUE TITLE
Login not possible after 2FA enabled

### ISSUE THREAD

**Issue by ps-ohanel** [salesagility/SuiteCRM#10349]
#### Enabling 2FA disables user to login
- 2FA can be enabled for user ✅ 
- user can enter username and passwrod ✅ 
- the email with the token is sent to user ✅ 
- user cannot input it anywhere, because the login sceen fails ❌ 

#### Expected Behavior
- an input field is rendered for user to be able to enter the sent 2FA code

#### Actual Behavior
- error message gets triggered from the UI perspective
- checking out the network tab in the browser, I can see that one of the GQL calls actually returns the  HTML template snipped that contains a fragment with the input field
- my assumption is that it is the "legacy" behaviour but the new Frontend cannot react to it?

#### Steps to Reproduce
1. Instantiate docker setup for easy local dev: [GitHub - jontitmus-code/SuiteCRM8_docker: SuiteCRM Docker Compose Script](https://github.com/jontitmus-code/SuiteCRM8_docker)
    - extend docker-compose.yml with those two lines to override all the php.ini files
    - ./docker/config/php/php.ini:/etc/php/7.4/fpm/php.ini
    - ./docker/config/php/php.ini:/etc/php/7.4/cli/php.ini
2. Make a new installation of: SuteCRM Version 8.5.0
3. Setup some SMTP that will enable you to see the sent emails. I used a free account on https://mailtrap.io/
4. Create a new user
5. Turn on 2FA checkbox for the user
6. Try to login
7. Mail is sent with the 2FA token
8. Error is triggered on the login screen

#### Your Environment

* SuiteCRM Version used: SuteCRM Version 8.5.0
* Setup provided by: [GitHub - jontitmus-code/SuiteCRM8_docker: SuiteCRM Docker Compose Script](https://github.com/jontitmus-code/SuiteCRM8_docker)

**Comment by serhiisamko091184** [comment]
Hi @ps-ohanel,

thanks for raising the issue! 

Regards,
Serhii

**Comment by ps-ohanel** [comment]
I think i created the issue in a wrong repo, as it affects version 8.xx
[SouteCRM-Core issue](https://github.com/salesagility/SuiteCRM-Core/issues/432)

**Comment by serhiisamko091184** [comment]
Hi @ps-ohanel,

one more time thanks, 

closing this one as well. 

Regards,
Serhii
