### ISSUE TITLE
Password Expired after N logins not working

### ISSUE THREAD

**Issue by ps-ohanel** [salesagility/SuiteCRM#10348]
#### Setting up expire password after N logins does not work
- when the password generation is enabled, the initial password is correctly sent to user ✅ 
- when enabling the option to expire password after N logins, it has no effect. User can login as many times as possible ❌ 

#### Expected Behavior
- the user is prompted to enter a new password when N logins happen

#### Actual Behavior
- the user can login with his initial password forever

#### Steps to Reproduce
1. Instantiate docker setup for easy local dev: [GitHub - jontitmus-code/SuiteCRM8_docker: SuiteCRM Docker Compose Script](https://github.com/jontitmus-code/SuiteCRM8_docker)
    - extend docker-compose.yml with those two lines to override all the php.ini files
    - ./docker/config/php/php.ini:/etc/php/7.4/fpm/php.ini
    - ./docker/config/php/php.ini:/etc/php/7.4/cli/php.ini
2. Make a new installation of: SuteCRM Version 8.5.0
3. Turn on the "Auto generate password feature"
4. Set that the password expires after 1 logins
5. Setup some SMTP that will enable you to see the sent emails. I used a free account on https://mailtrap.io/
6. Create a new user
7. Email with the initial password should be sent
8. Login with the new user
9. Logout
10. Login again, repeat several times
11. Password never expires

#### Your Environment

* SuiteCRM Version used: SuteCRM Version 8.5.0
* Setup provided by: [GitHub - jontitmus-code/SuiteCRM8_docker: SuiteCRM Docker Compose Script](https://github.com/jontitmus-code/SuiteCRM8_docker)

**Comment by ps-ohanel** [comment]
I've re-created [the issue](https://github.com/salesagility/SuiteCRM-Core/issues/433) in the correct SuiteCRM-Core repo as it affects the version 8.xx

**Comment by serhiisamko091184** [comment]
Hi @ps-ohanel, 

thanks for raising the issue and moving it to the appropriate repo. 
I close this one. 

Many thanks! 

Regards,
Serhii
