### ISSUE TITLE
Elasticsearch search page language strings not processed

### ISSUE THREAD

**Issue by cyb456** [salesagility/SuiteCRM#10347]
#### Issue

When using the Elasticsearch engine, the $APP.LABEL strings are not replaced in lib/Search/UI/templates/search.form.tpl

This is most noticeable with the search button itself: 

![Screenshot_20240131_092721](https://github.com/salesagility/SuiteCRM/assets/100444802/562e62e3-7484-4501-af01-72ab1fdf3dd0)

#### Expected Behavior

The language strings should be replaced in the template
#### Actual Behavior

They are missing
#### Steps to Reproduce

1. Enable elasticsearch
2. search for something
3.
4.

#### Context

It is visual only, but an ugly bug
#### Your Environment

* SuiteCRM Version used: 7.14.2 with the recent elasticsearch fixes PR added in
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chromium
* Environment name and version (e.g. MySQL, PHP 7): php 7.4, mariadb 11.2
* Operating System and version (e.g Ubuntu 16.04): ubuntu 20.04

**Comment by serhiisamko091184** [comment]
Hello @cyb456,

thanks for raising the issue. 

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @cyb456,

thanks for reporting the bug,

This appears to be a duplicate of: #10182
Please let us know if you believe otherwise. 

Regards,
Serhii

**Comment by cyb456** [comment]
yes that would be a duplicate
