### ISSUE TITLE
Module builder - fails on publish or export

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#1035]
Version 7.5.1
OS: Ubuntu (Plesk environment)

When you `publish` or `deploy` a module it gives you the 403 page.

```Forbidden

You do not have permission to access this document.
```

My first guess is that these lines in `modules/modulebuilder/MB/ModuleBuilder.php` need to be modified.

```php
define ( 'MB_PACKAGE_PATH', 'custom/modulebuilder/packages' ) ;
define('MB_PACKAGE_BUILD', 'custom' . DIRECTORY_SEPARATOR . 'modulebuilder' . DIRECTORY_SEPARATOR . 'builds');
require_once ('modules/ModuleBuilder/MB/MBPackage.php') ;
```

@mattlorimer maybe if you could provide some feedback i would be happy to contribute to this one.
I checked if someone reported this on Github, however i did not find any bug reports regarding this.
If so this one can be linked.

**Comment by ijdavie** [comment]
@ghermans, is this still a issue that you have been seeing ?

**Comment by ghermans** [comment]
i don't know since i am not using SuiteCRM anymore.
