### ISSUE TITLE
SuiteCRM 7.14.3 PDF Template Landscape orientation is ignored when using the Legacy MPDF Engine

### ISSUE THREAD

**Issue by CommuniG8** [salesagility/SuiteCRM#10376]
If the Admin PDF Settings is set to use the Legacy MPDF Engine and a PDF Template with Orientation Landscape checked is used,
the PDF is generated as Portrait, as if Orientation had been set to Portrait. The orientation works correctly using the TCPDF Engine.

#### Expected Behavior
The PDF should be generated in Landscape orientation when Orientation Landscape is checked in the PDF Template.

#### Actual Behavior
The PDF is generated in Portrait orientation regardless of the Orientation setting in the PDF Template.

#### Steps to Reproduce
1. In Admin PDF Settings, set the Engine to MPDF
2. Generate a PDF (from any module that supports this) where the Template has Orientation Landscape
3. The generated PDF is in Portrait orientation

#### Context
We have a number of PDF templates with enough columns to need a Landscape Orientation.
We cant use the new TCPDF Engine due to the current issues with formatting a large number of columns.

#### Your Environment
* SuiteCRM Version used: 7.14.3
* Browser name and version: Any
* Environment name and version (e.g. MySQL, PHP 7): 7.4.3
* Operating System and version (e.g Ubuntu 16.04): 20.04.6

**Comment by serhiisamko091184** [comment]
Hello @CommuniG8! 

Thanks for raising this issue!

Regards,
Serhii

**Comment by CommuniG8** [comment]
That is a pity as it means, currently, SuiteCRM has no means at all to produce a correctly formatted PDF in Landscape orientation.

**Comment by pgorod** [comment]
@CommuniG8 are you using the same mpdf.php that was part of SuiteCRM before this change (5.7.1, see [here](https://github.com/salesagility/SuiteCRM/blob/42fd6a9e5e4f8442da04d8144bc13b4731d0c2ff/modules/AOS_PDF_Templates/PDF_Lib/mpdf.php#L842))? Or are you using a newer version? If it's different, you need to check if the constructor of the mPDF class was changed. The 'orientation' is one of the positional parameters passed into it.

The calling code is [here](https://github.com/salesagility/SuiteCRM/blob/873557561b8fbed15d586a0d9217037a0b96820c/lib/PDF/LegacyMPDF/LegacyMPDFEngine.php#L161), I believe.

**Comment by CommuniG8** [comment]
@pgorod mpdf.php is 5.71 but without the constructor change.
I changed the function, as in the link you gave, but it makes no difference.

**Comment by chris001** [comment]
The newest version of mpdf supports php 8:
https://github.com/mpdf/mpdf

**Comment by pgorod** [comment]
Ideally, someone who uses this should upgrade mpdf, adapt SuiteCRM to that new version, and make a PR here with those changes.

Then we would close that PR without merging (due to the licensing problems), but we could point people there is they want to use mpdf.
