### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by Iliya5digital** [salesagility/SuiteCRM#10417]
Issue
After unpacking the archive, I came across the Forbidden 403 error

Expected Behavior
The initial setup wizard should appear

Actual Behavior
No

Possible Fix
The initial setup wizard should appear, but not instead of 403 forbitten

Context
I want to get a full-fledged working system
High priority

Environment

SuiteCRM Version used: 8.6.0
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 124.0.6367.119
Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 8.2.11
Operating System and version (e.g Ubuntu 16.04): Windows 11 23H2

**Comment by johnM2401** [comment]
Hey @Iliya5digital 
Thank you for getting in touch!

As @pgorod mentioned, the best place to reach out for installation assistance would be the community forums.

We would ideally keep this Github repo as a place to log valid and replicable Bugs with the CRM's functionality.

So, I'll close this ticket off for now.

However, if you feel you do indeed have a replicable bug with the CRM, please get in touch and we'd be happy to investigate.

Thanks again!
