### ISSUE TITLE
Inline edit - date format issue + issue of replacing the orig. date by actual date

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1042]
Hi, If are you inline editing the date in any module, it has 2 issues:

First... it is replacing your saved date with your actual date... and it is confusing, because if i want change some date only for one day forward, it show me actual date and i must search which date was there... in editview it is working without issue...

look on video: http://screencast.com/t/7oL4DAkZq

Second: after inline editing you will see the date in default US format... after refresh you will see date in format which you set up in your settings

![date](https://cloud.githubusercontent.com/assets/5773777/13489386/fd0228c0-e126-11e5-826a-64051e239cbe.png)

Miky

**Comment by shogunpol** [comment]
@Mausino , the both issues described above seems to not appear in recent version of SuiteCRM(7.7.8), can you confirm this, if yes i can close an issue.

**Comment by Mausino** [comment]
@shogunpol Yes, i agree 👍 i am closing those 2 issues :)
