### ISSUE TITLE
Error:Connecting to ./index.php?entryPoint=json_server Error:SyntaxError: Unexpected token B in JSON at position 0 When using email template on the quick compose email

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#1044]
Error:Connecting to ./index.php?entryPoint=json_server
Error:SyntaxError: Unexpected token B in JSON at position 0
When using email template on the quick compose email

Steps to reproduce:
Compose an email
On the right side click on the collapsible panel
On the options tab select an email template to be used

**Comment by bennnjamin** [comment]
I'm having this issue too. Were you able to fix it?

**Comment by vjaro** [comment]
@bennnjamin  Yes i applied a coded fix. I have committed the files. see the referenced commits
