### ISSUE TITLE
Module Loader view broken

### ISSUE THREAD

**Issue by kale1d0code** [salesagility/SuiteCRM#10458]
### Issue

Module Loader styles are brittle, and does not render tables correctly when resizing the browser window.
only fix is to refresh the page
![Screenshot from 2024-06-26 13-37-14](https://github.com/salesagility/SuiteCRM/assets/13876156/8c36b21e-89ef-4a7c-821d-e0a971a85a09)
![Screenshot from 2024-06-26 13-39-47](https://github.com/salesagility/SuiteCRM/assets/13876156/23a0c48b-3fcc-4046-b29b-976f343ecc45)

### Possible Fix

rewrite the styles for this view

### Steps to Reproduce the Issue

```bash
1. view module loader
2.
3.
...
```

### Context

view screenshot

### Version

7.14.4

### What browser are you currently using?

Chrome

### Browser Version

dfgjlvnsdfvjlv

### Environment Information

php 8.1

### Operating System and Version

dfvlnhzdfvdf

**Comment by mattlorimer** [comment]
please stop creating issue and add invalid data "dfvlnhzdfvdf"
