### ISSUE TITLE
Search field unexpectedly closing

### ISSUE THREAD

**Issue by mvmshakkir** [salesagility/SuiteCRM#10529]
https://github.com/user-attachments/assets/c6e1e905-8d80-4795-b240-c61ce00f675e

### Issue

After migrating from 7.14 to 8.6.2, the search unexpectedly closes when I click inside the field on Android mobile, while there are no issues on iPhone iOS and desktop systems. Later, I found that the issue wasn't on my side; the SuiteCRM demo site also shows the same issue.

### Steps to Reproduce the Issue

```bash
Clicking inside the search field automatically closes it, and I am unable to enter any data.
```

### Context

I'm not able to search anything .

### Version

8.6.2

### What browser are you currently using?

Chrome

### Browser Version

chrome128.0.6613.146

### Environment Information

php 8.2

### Operating System and Version

Ubuntu

**Comment by johnM2401** [comment]
Hey!
Thank you for getting in touch with this
Just to let you know I'll close this ticket off as this Repo pertains to SuitCRM 7 specific issues, and I'll keep your other one on the SuiteCRM-Core repo open.
Thank you again!
