### ISSUE TITLE
Populating Target Lists with workflows

### ISSUE THREAD

**Issue by madmatone** [salesagility/SuiteCRM#1052]
Trying to recreate your manual:
https://suitecrm.com/wiki/index.php/Userguides#Customers_to_Target_List

SuiteCRM 7.3.1 and 7.5 do NOT display the Target Lists in the dropdown field, to choose the list that the contacts should be added to.

![suitecrm](https://cloud.githubusercontent.com/assets/17727562/13608223/1d0055f8-e554-11e5-9696-b7609ddab35f.png)

Tested with FF44.02 and Chrome 48

**Comment by mattlorimer** [comment]
this is because you have selected, the record type of 'Target Lists', you should just leave it as Contacts and add the relationship, but this kind og question would be better served on our [support forum](https://suitecrm.com/forum/index)
