### ISSUE TITLE
T_CONSTANT_ENCAPSED_STRING check in ModuleScanner broke our build

### ISSUE THREAD

**Issue by trollr** [salesagility/SuiteCRM#10579]
### Issue

Hi, 

we use `array_push($installdefs['copy'], array(....` at the end of our mainfest.php file to add custom implementations. These are some custom classes, but also schedulers etc. Why are we doing this? So that we can apply the changes from the Module Builder with IDE Function `Compare with...` without constantly breaking our manifest.php or having to make annoying merges.

With commit e572230abd0dad205b24a96acce72590b20bf69d (T_CONSTANT_ENCAPSED_STRING and check on ]) you seem to have introduced a security check that prevents this. Is there any recommendation? Our manifest.php is very large, as we have about 50 custom modules with custom logic. 

### Steps to Reproduce the Issue

```bash
1.
2.
3.
...
```

### Version

7.14.6

### What browser are you currently using?

Chrome

### Environment Information

7.4.3-4ubuntu2.19

### Operating System and Version

Ubuntu

**Comment by serhiisamko091184** [comment]
Hello @trollr, 

thanks for bringing our attention to this matter, 

the issue you have raised appears to relate to a custom plug-in and as such we would suggest raising your question on the Community forum:

https://community.suitecrm.com

Thank you in advance! 

Regards,
Serhii
