### ISSUE TITLE
The hamburger menu on the resposive dashboard is listing the menu items without a correct colour setting.

### ISSUE THREAD

**Issue by paulgodley** [salesagility/SuiteCRM#1062]
Suite 7.5.2, clean install.  If you resize the screen so that the hamburger menu item is visible, the items listed have incorrect css values and are see through as shown below (both Chrome and Firefox):
![screenshot-localhost 2016-03-09 15-42-46](https://cloud.githubusercontent.com/assets/9193412/13640751/d0728e30-e60d-11e5-9a28-40094586902a.png)

**Comment by paulgodley** [comment]
@emcrobert has put in a fix for this in issue #724.  When that fix is pulled in, this will be resolved.

**Comment by JimMackin** [comment]
Closing since #724 is now resolved.
