### ISSUE TITLE
Request: A UI message for every success in the repair/rebuild section.

### ISSUE THREAD

**Issue by GeorgeWL** [salesagility/SuiteCRM#1063]
It can be confusing when, for example, the rebuild .htaccess doesn't give some sort of message to let you know the process was a success but rather a page with no content.

http://i.imgur.com/EfCXToJ.png

**Comment by Mausino** [comment]
:+1:

**Comment by samus-aran** [comment]
I would actually state this as a bug since we should be alerting users of the success.

**Comment by GeorgeWL** [comment]
:+1:

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.

**Comment by GeorgeWL** [comment]
So there's no pages where after a process completes, it shows just a empty area then?

**Comment by Dillon-Brown** [comment]
@GeorgeWL It should show the message "DONE":

![test](https://user-images.githubusercontent.com/26431166/52335304-fd03f000-29f9-11e9-9557-ba52635d6a89.png)
