### ISSUE TITLE
In 7.5.2 error in report parameters

### ISSUE THREAD

**Issue by rouhu** [salesagility/SuiteCRM#1064]
When trying to use 2 report parameters with "AND" (record created date greater than value [date] AND record created date less than value [date]) in report you get error. In editing they work but not when pressing the Update button in report viewer.
Wed Mar  9 18:29:34 2016 [25117][1][FATAL] aor_reports for aor_report_aor_conditions failed to load
Wed Mar  9 18:29:34 2016 [25117][1][FATAL] aor_reports for aor_report_aor_conditions failed to load

**Comment by jellydonuts** [comment]
i was having a similar problem with the dates myself... though not sure if it's the same one as I didn't check the php logs for errors. I think it may have to do with the suitecrm's date format vs the user creating the report &/OR task's date format. 

For example:

System: yyyy-mm-dd
User: dd-mm-yyyy

User creates task (lets say you're reporting on `task`.date_start), that gets set to the format dd-mm-yyyy, and then you create a report as an admin which uses the date format yyyy-mm-dd.

Can you try standardizing on a date format all around?

1. check admin > locale > date format
2. check every admin > employees > usermanagement > 'user' > advanced > date format
3. make sure these are all the same
4. go back and update the date for each 'task' (or whatever you're reporting on) to the same format.

**Comment by JimMackin** [comment]
Seems to be fixed by the fix for #1082 which is fixed in the next release. Thanks for reporting this issue.
