### ISSUE TITLE
"Last Month" date period is the same as "This Month" date period

### ISSUE THREAD

**Issue by jellydonuts** [salesagility/SuiteCRM#1066]
culprit in modules/AOR_Reports/aor_utils.php on line 166

fix is potentially changing method of finding last month to

 $datetime_period = $datetime_period->setDate($datetime_period->format('Y'), $datetime_period->format('m') - 1, 1);

OR

$datetime_period = $datetime_period->setTimestamp(strtotime('first day of last month'));

**Comment by paulgodley** [comment]
Thanks @jellydonuts, I have updated this method as per your suggestion.

**Comment by jellydonuts** [comment]
No problem, thanks for the speedy fix.
