### ISSUE TITLE
Javascript setModuleFieldsPendingFinishedCallback is not defined in Reports.

### ISSUE THREAD

**Issue by paulgodley** [salesagility/SuiteCRM#1068]
Suite 7.5.2 checked out from the hotfix branch.  When you try to create a report, you get the Javascript error  setModuleFieldsPendingFinishedCallback is not defined. This is happening in Firefox but Chrome does not seem to have this issue.

**Comment by paulgodley** [comment]
This appears to be the call in modules/AOR_Reports/tpls/EditViewFooter.tpl which is returning the undefined error.

**Comment by holdusback** [comment]
Got this error in latest SuiteCRM version : 7.11.5

When I go in one of my report I have this error in the console : 

Uncaught ReferenceError: setModuleFieldsPendingFinishedCallback is not defined
    at testModuleFieldsPendingFinished (eval at <anonymous> (sugar_grp1.js?v=dKWdnLPtYRg_SI2p6-uI_w:438)
    at Object.success (eval at <anonymous> (sugar_grp1.js?v=dKWdnLPtYRg_SI2p6-uI_w:438)
    at Object.handleTransactionResponse (sugar_grp1_yui.js?v=dKWdnLPtYRg_SI2p6-uI_w:109)
    at sugar_grp1_yui.js?v=dKWdnLPtYRg_SI2p6-uI_w:109
