### ISSUE TITLE
Leads Module - Clicking Cancel on Show Duplicates page 

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1074]
If you create a lead which is detected as a possible duplicate, You are taken to the page that shows potential Duplicates: 
![screenshot from 2016-03-10 16 17 44](https://cloud.githubusercontent.com/assets/13675281/13675993/e7d80c02-e6db-11e5-8f85-dbe2bf97b1f0.png)

Clicking "Cancel" here will direct you to a page that simply shows the text: 
**_Error retrieving record. This record may be deleted or you may not be authorized to view it._**

Tested on Accounts, Contacts and this did not occur. Clicking cancel redirects to the Module's Listview.

Tested this on both 7.4.3 and 7.5.2

**Comment by jellydonuts** [comment]
i attempted this fix for the Tasks module however it doesn't seem to be working.

**Comment by paulgodley** [comment]
Hi @jellydonuts. can you please log this as a new issue in github?
