### ISSUE TITLE
Commit breaks 

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1089]
The commit https://github.com/salesagility/SuiteCRM/commit/625b573297761ed47fe18a019aca0145622fb599 breaks custom function for me in vardefs.

I got a vardef definition like:

<pre>  'show_tickets' => 
  array (
    'name' => 'show_tickets',
    'vname' => 'LBL_SHOW_INFOS',
    'source' => 'non-db',
    'function' => 
    array (
      'name' => 'show_tickets',
      'returns' => 'html',
      'params' => 
      array (
        0 => 'id',
      ),
      'include' => 'custom/Extension/modules/nx_te/Ext/functions.php',
    ),
  ),</pre>

With the cleanVardefs there is no show of my infos in the detailview.
When i dont clean the vardefs i get my output as before. My Workaround for me for now:
<pre>       //$data = self::cleanVardefs($GLOBALS['dictionary'][$object]);
        $data = $GLOBALS['dictionary'][$object];</pre>

**Comment by mattlorimer** [comment]
you are missing the type definition on your field, 'type' => 'function',

**Comment by gunnicom** [comment]
The missing 'type' => 'function', did not help.

**Comment by gunnicom** [comment]
Ok, sorry. That does help. Well these type of customization was never good documented by sugar, and so it did work till now ;)

**Comment by gunnicom** [comment]
Oh, and thanks for your hint.
