### ISSUE TITLE
AOS Modules - SubPanel Sort-by buttons not working

### ISSUE THREAD

**Issue by jshwhitlow** [salesagility/SuiteCRM#1090]
In a brand new instance of SuiteCRM 7.5.1, I have some issues with clicking columns to sort items by different fields specifically in aos module subpanels. (In this case i was in the contacts module)

In the javascript console, I'm getting:

```
Uncaught SyntaxError: missing ) after argument listwaitUntilLoaded @ sugar_grp1.js?v=6c-a6q5L4KH-Ly-agkWh_g:467
VM102265:1 Uncaught SyntaxError: missing ) after argument listwaitUntilLoaded @ sugar_grp1.js?v=6c-a6q5L4KH-Ly-agkWh_g:467
VM102268:1 Uncaught SyntaxError: missing ) after argument listwaitUntilLoaded @ sugar_grp1.js?v=6c-a6q5L4KH-Ly-agkWh_g:467
VM102280:3 Uncaught SyntaxError: Unexpected stringwaitUntilLoaded @ sugar_grp1.js?v=6c-a6q5L4KH-Ly-agkWh_g:467
VM108490:1 Uncaught SyntaxError: Unexpected token ILLEGAL

```

Anyways, clicking on several of them brought me too this code:

`document.getElementById("subpanel_contact_aos_invoices"").cookie_name="contact_aos_invoices"_v";`

and 

`document.getElementById("subpanel_contact_aos_contracts"").cookie_name="contact_aos_contracts"_v";`

so then i clicked on the "unexpected string" one and it brought me to this:

```
    	var SubpanelInit = function() {
    		SubpanelInitTabNames(["activities","history","documents","opportunities","leads","campaigns","cases","bugs","contacts","contact_aos_quotes"","contact_aos_invoices"","contact_aos_contracts"","fp_events_contacts","project","securitygroups"]);
    	}
        var SubpanelInitTabNames = function(tabNames) {
    		subpanel_dd = new Array();
    		j = 0;
    		for(i in tabNames) {
    			subpanel_dd[j] = new ygDDList('whole_subpanel_' + tabNames[i]);
    			subpanel_dd[j].setHandleElId('subpanel_title_' + tabNames[i]);
    			subpanel_dd[j].onMouseDown = SUGAR.subpanelUtils.onDrag;
    			subpanel_dd[j].afterEndDrag = SUGAR.subpanelUtils.onDrop;
    			j++;
    		}

    		YAHOO.util.DDM.mode = 1;
    	}
    	currentModule = 'Contacts';
    	SUGAR.util.doWhen(
    	    "typeof(SUGAR.subpanelUtils) == 'object' && typeof(SUGAR.subpanelUtils.onDrag) == 'function'" +
    	        " && document.getElementById('subpanel_list')",
    	    SubpanelInit
    	);
    
```

Every single bit of this code with that extra double quote which is only coming from aos modules, is coming from:
include/subpanel/SubPanelTiles.php on lines 370-371 and then lines 398-444.

Still actively working on trying to figure out where the extra double quote is coming from.

**Comment by jshwhitlow** [comment]
UPDATE: This problem is not occurring within my development instance that I have been working on, only within a fresh install of where I installed 7.2, then upgraded from 7.2-7.3, then 7.3 to 7.4, 7.4 to 7.5.

So I would then think that the upgrade process may have been related to this issue.

**Comment by ijdavie** [comment]
@jshwhitlow can you confirm this issue is now not a problem ? and if so are you able to close this issue ? 
Thanks.

**Comment by jshwhitlow** [comment]
I attempted to duplicate the issue once again by following the same steps, and was unable to replicate the issue. It appears to have either been resolved or was a fluke issue.
