### ISSUE TITLE
Quotes/problems in Line items

### ISSUE THREAD

**Issue by zhukas21** [salesagility/SuiteCRM#1098]
![crm_fails](https://cloud.githubusercontent.com/assets/17876862/13809721/bdf1dec0-eb74-11e5-9a6c-e939151d1136.PNG)

**Comment by ijdavie** [comment]
This appears to look like a permission issue rather than a bug. please consult the SuiteCRM Forums.

**Comment by zhukas21** [comment]
ok. thank you.
