### ISSUE TITLE
Why isn't Address Country a dropdown by default?

### ISSUE THREAD

**Issue by GeorgeWL** [salesagility/SuiteCRM#1099]
There's only a limited number of countries in the world and by being a textfield by default it causes the problem of UK, United Kingdom and the various misspellings appearing as separate entities in the data (which also applies to others of course.)

For data integrity wouldn't it make sense to have it behave as a drop down of all countries?

I'd suggest in the format of [Country Name (ISO 3166-1 Code)] or even to be fancy [Country Flag Icon 
Country Name(Country ISO Code)]

 for e.g. 
![](https://cloud.githubusercontent.com/assets/5931248/13812392/c50b66f0-eb73-11e5-9b42-fa6d2b8bb7c2.png) United Kingdom (GB)

**Comment by mattlorimer** [comment]
duplicate  of #970

**Comment by chris001** [comment]
Agreed, activate the countries dropdown would be a sensible improvement for the app, to keep the country data clean and tidy.
The country dropdown list, `countries_dom`, is already shipping with the app, so, why not use it.
Code to use the country list was provided by Andrew McLauchlan  @recci  , 2.5 years ago, as a hand modification.
Why not make a pull request to add this to the core?  Save a lot of time for a LOT of users.
https://suitecrm.com/suitecrm/blog/entry/convert-the-country-text-field-in-suitecrm-to-a-drop-down-list

**Comment by chris001** [comment]
In the same vein, there's an official list of all 249 legal ISO country codes on the planet, with their 2-letter ISO abbreviation, their 3-letter UN abbreviation, and their national dialing code prefix(es, Dominican Republic has three).
http://www.worldatlas.com/aatlas/ctycodes.htm
Once the user selects the country, if any phone number fields are blank, the app could autocomplete the country code part of the phone numbers.

**Comment by mattlorimer** [comment]
I agree it would be ideal to have a country dropdown, and it would be simple to add. However, the only issue with this is for upgrades, where the country field could have lots of various ways of naming a country in it, that if it doesn't exactly match the dropdown value it would be picked up. So we need to have nice way to handle this or to upgrade values somehow.

**Comment by chris001** [comment]
@mattlorimer Agreed.  If the data type of the field stays the same, text, then existing entries would remain untouched, only new entries would autofill a preset text value based on user selected country.

Furthermore, there is the user experience issue, of, for many organizations, agents enter addresses where 80% or 90% or 99% of these addresses are from one country.  So this dropdown should be smart enough to auto default to, for example, "UK", for crm instances that are constantly seeing new addresses added from the UK.

Or, for smarter address autofill, using google or any equivalent search engine, to intelligently autofill those text entries, by the interactive jquery calls going to google, from when the agent starts to type the address, all the agent has to do is enter the street, and select the correct full complete address out of the several suggestions returned by google.  Province/state, country, and postal code are auto filled.

**Comment by chris001** [comment]
Ready to use csv file, complete list of country and dialing codes.
https://github.com/EspaceNetworks/CountryCodes/blob/master/espacenetworks%20country%20codes.csv

**Comment by GeorgeWL** [comment]
It really does seem a collosal oversight, as I can't think of a single reason a user wouldn't want to use a country from a dropdown by default.

**Comment by chris001** [comment]
Right, using available information to help the user with auto complete (as on smart devices with auto correct) is best.

**Comment by shogunpol** [comment]
@chris001 , will be great if you will try to handle an enhancement, and create PR so we can "fast" implement it.

**Comment by chris001** [comment]
@mattlorimer 
@shogunpol 
I believe there's a free google service which uses artificial intelligence to smart detect and correct addresses, which would be useful to upgrade existing data in the Country field, to an intelligent guess based on the rest of the address fields.  Probably faster and more accurate at guessing the correct Country than any home grown solution, however at the rather high sacrifice price of permanent loss of data privacy.

**Comment by GeorgeWL** [comment]
@chris001 
I feel address autocomplete should be a separate issue or even an attachable module. 

Whereas this is merely an incorrectly implemented feature, as the solution to manually tweak it already exists, it just seems weird that the solution has been posted for two years by the main team on the suitecrm blog but not implemented into the main repo yet.

**Comment by GeorgeWL** [comment]
could this be of some help? https://www.smashingmagazine.com/2011/11/redesigning-the-country-selector/

**Comment by chris001** [comment]
@GeorgeWL Definitely, this looks like the perfect upgrade for choosing the Country.
Unfortunately it's not on `packagist.org`
However, it's available here:
https://github.com/JamieAppleseed/selectToAutocomplete
Should add it soon.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Why isn't Address Country a dropdown by default?](https://trello.com/c/NJmqld5Q/112-why-isn-t-address-country-a-dropdown-by-default)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by chris001** [comment]
This one also is more of a defect than a suggestion.  While it's not a crash bug, it's certainly substandard when you compare with competing software, and makes users lives unnecessarily difficult, for such a simple fix.  Not to mention, the enumeration of country names and codes is already included in the application, it was omitted from being used by mistake or lack of attention to detail, and it really should be used.

**Comment by samus-aran** [comment]
I get that, but we need to separate bugs from suggestions quite cleanly and this case, its a nice to have - may be it essential to have - but its not a bug.  It will remain as a suggestion.

**Comment by GeorgeWL** [comment]
I'd say that it's not a "nice to have" it's an oversight,  which makes it a bug.

**Comment by nzi200779** [comment]
Was this ever resolved?

**Comment by tsmgeek** [comment]
2019 still not resolved?

**Comment by GeorgeWL** [comment]
# Re-open the ticket

**Comment by jgramp** [comment]
Has this been resolved yet?

**Comment by GeorgeWL** [comment]
I'd say that it's not a "nice to have" it's an oversight, which makes it a bug.

**Comment by pgorod** [comment]
@jgramp no, it hasn't. The Issue was only closed because we were moving suggestions to a different platform at the time. Anyway as you can see there are some vocal defenders of the need to add this feature. Are you thinking of contributing a solution? Thanks.

**Comment by GeorgeWL** [comment]
but this is a bugfix. not a suggestion.

**Comment by pgorod** [comment]
George, how many times have you said that? We heard you. There's no point in repeating it. If you can offer to fix it, or to pay someone to fix it, then that would be quite helpful.
