### ISSUE TITLE
Issues with fields/layouts modifications in studio after Export Customisations package installation

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1108]
Users cannot make changes to Studio fields/layouts if those fields/layouts have been created/modified as part of a package that was built using the 'Export Customisations' tool within Studio. Changes made look like they revert or do not save, such as label changes to tabs/fields. These changes are saved but are not loaded in a suitable order so it looks like these changes have not been implemented to the end user making these changes.

**Comment by wheathcock** [comment]
Same issue

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
