### ISSUE TITLE
Something wrong in the core handling translations

### ISSUE THREAD

**Issue by mikebeck** [salesagility/SuiteCRM#1109]
Hello guys, first of all thanks for your collaboration in this project, and for the people in translating SuiteCRM. I have this next question:

I think that there's a core issue relating the Calendar module and additional details of items in the Calendar when using a language pack that's not the default 'en_us'.

How to reproduce:

1- Using SuiteCRM 7.5.3 default with english language, create a new task
2- Open Calendar module and click in the recently created task->additional_details (info button), a box will pop up
3- Using tasks as example, you will have Subject, Start, Due, Priority and Status all with their respective content filled up
4- Change the SuiteCRM language to another one, let's use the 100% completed translation from transifex Portugal - Portugues pack
5- Again, open Calendar module and click in the recently created task->additional_details (info button), a box will pop up
6- Again, using tasks as example, you will have Subject, Start, Due, Priority and Status all filled up again except Priority and Status items

My thought are that someting in the core is not showing the $app_list_strings of the languages pack that are stated as 100% translated.

My attempts to troubleshoot this are as follows:
1- Tried to change the global $current_language to en_us even using the pt_PT as current language, it shows in english but still without content
2- If I set this line of code
`if (!empty($fields['STATUS'])) $overlib_string .= '<b>' . $mod_strings['LBL_STATUS'] . '</b> ' . $app_list_strings['task_status_dom'][$fields['STATUS']] . '<br>';`
to
`if (!empty($fields['STATUS'])) $overlib_string .= '<b>' . $mod_strings['LBL_STATUS'] . '</b> ' . $app_list_strings['task_status_dom']['Not Started'] . '<br>';`
it gets translated, I think that has something to do with the $fields of a dropdown field, but then again that 'Not started' is a enforced value, not the current one

I hop that this gets fixed, is a long long problem in SugarCRM/SuiteCRM

this is the post in the forums containing screenshots

https://suitecrm.com/forum/international-language-support/8594-something-wrong-in-the-core-handling-translations

My System:
Ubuntu 14.04.4 LTS (GNU/Linux 3.19.0-51-generic x86_64)
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
Mysqld 5.5.47-0ubuntu0.14.04.1
Apache/2.4.7 (Ubuntu)
SuiteCRM Version 7.5.3
Sugar Version 6.5.23 (Build 1061)
Language Pack from Transifex pt_PT

**Comment by mikebeck** [comment]
OK I fixed it

https://github.com/salesagility/SuiteCRM/pull/1116

best regards

**Comment by horus68** [comment]
Solved in actual code - version 7.7.8. 
@shogunpol  This issue should be closed.

**Comment by shogunpol** [comment]
@horus68 , @pgorod - thanks for testing an issue, due to your opinion i will close PR and issue.
