### ISSUE TITLE
Required Field email address in Quick Create not working

### ISSUE THREAD

**Issue by AsimPervez93** [salesagility/SuiteCRM#1120]
Hi All, 

I posted in the SuiteCRM forums and was directed here as one of the admins thinks my issue is a bug.

I've made the email address field in contacts required:

![image](https://cloud.githubusercontent.com/assets/17923501/13872955/05289384-ece6-11e5-9261-1657d93eb04e.png)

And this works within the contacts module as shown:

![image](https://cloud.githubusercontent.com/assets/17923501/13872966/165e8e7e-ece6-11e5-9159-a02f7943f68d.png)

However, it does not work when using the quick create layout from a different module:

![image](https://cloud.githubusercontent.com/assets/17923501/13872973/2348ced8-ece6-11e5-858f-a37982c04fec.png)

There is a red * there to mark it as required but it still allows the user to save the contact without an email address.

Can anyone help?

Kind Regards,

**Comment by AsimPervez93** [comment]
anybody?

**Comment by samus-aran** [comment]
Thanks @AsimPervez93.  I understand you raised this a week ago, but we do not set out an SLA for bugs being raised, so we appreciate some patience with all bugs raised and we try to resolve issues as soon as able.

Regards to comments - we don't necessarily need to respond unless we need clarification.  In this case it was fairly clear but we had to replicate the issue in order to provide you a response (which we have now done).

Hopefully we can resolve this soon.

**Comment by AsimPervez93** [comment]
Thanks @samus-aran for your reply.  I'll wait for a resolution and keep an eye on this thread.  Thank you.

**Comment by samus-aran** [comment]
@sathishsengodan Is looking into this.

**Comment by AsimPervez93** [comment]
Excellent!  Hopefully this can be resolved.

**Comment by vladbar** [comment]
Hello AsimPervez93 . 
I could not replicate this issue. 

I tried to change email1 field to required, I also created other fields in studio, made them required and added them to the Edit View and Quick Create View, but all these fields work as they should - highlighted in red, error message appears underneath, prevents from saving. 

Could you please provide some more details on this issue (error logs, SuiteCRM version).

**Comment by vladbar** [comment]
I would also suggest to use the latest SuiteCRM version.

**Comment by vladbar** [comment]
Hello AsimPervez93 , 

I was able to replicate this issue by following Accounts -> Contacts subpanel -> Select -> Create Contact -> Save .

Thank you for reporting this issue. I have submitted a pull request with proposed solution.

**Comment by ApatheticCosmos** [comment]
I see this was marked as closed/resolved two years ago, however I'm still seeing this bug in 7.10.4 with both Contacts and Leads. Was it not merged into the 7.10 branch?

**Comment by ApatheticCosmos** [comment]
While I still see this bug behavior in 7.10.4, I checked the code on my server and the above pull request is in the code. I'm unsure if I should have this issue reopened or create a new issue report.
