### ISSUE TITLE
Create button missing styling in some areas

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1121]
The Create Button style needs applied in some areas where it is missing, such as:
Employees
Admin -> InboundEmail
Admin -> Releases

**Comment by CaptainChainsaw** [comment]
looks like the id is missing from the html, for example:

`<a id="create_link" class="utilsLink" href="index.php?module=Releases&action=EditView&return_module=Releases&return_action=DetailView"> Create </a>`


adding `id="create_link"` should sort this.

**Comment by samus-aran** [comment]
@sathishsengodan Looking into this.
