### ISSUE TITLE
Moving edit/remove buttons on subpanel in Studio not respected

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1122]
If you move the edit/remove buttons within a subpanel in Studio, the changes are saved but these are not respected/read. This means the edit/remove buttons/action menu will always display at the end of the subpanel after all fields are listed, despite the position in Studio.

Raised on the SuiteCRM forums: https://suitecrm.com/forum/suitecrm-7-0-discussion/8547-move-the-subpanel-edit-remove-button#29869

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Moving edit/remove buttons on subpanel in Studio not respected](https://trello.com/c/JITUQ2Zb/223-moving-edit-remove-buttons-on-subpanel-in-studio-not-respected)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
