### ISSUE TITLE
Export in Reportsmodule

### ISSUE THREAD

**Issue by mlwmaklers** [salesagility/SuiteCRM#1125]
Reports module

Export and Download PDF are not Available.

The link to references to:

download_csv_button_old
download_pdf_button_old

**Comment by willrennie** [comment]
Can you provide more details on your environment, your SuiteCRM version etc. Do you receive any browser console errors when you click the buttons(Ctrl+Shift+J in Chrome or Ctrl+Shift+K in Firefox)? Export and Download PDF work for me in the latest version of SuiteCRM(7.5.3).

**Comment by mlwmaklers** [comment]
Hello,

the problem arises only in the Reports Module. In all other modules it works flawlessly.

I have
Ubuntu 14:04
PHP 5.4.45
Chrome 49 + Firefox 44 same problem
suitecrm 7.5.3

The button appears to have no function.
In the demo suitecrm the same problem exists.

Have a screenshot of the console attached

![unbenannt](https://cloud.githubusercontent.com/assets/10342507/13913783/286a6a00-ef4a-11e5-95cb-0bc9fd3773d8.PNG)

**Comment by willrennie** [comment]
Did you upgrade from a previous version? Have you run a Quick Repair & Rebuild in Admin?

**Comment by mikesolo** [comment]
We have the same problem see #1056
We have copied AOR_Reports from 7.5,1 to fix this issue

**Comment by mlwmaklers** [comment]
Hi Will,
yes it was an upgrade from 7.4.3 to 7.5.3
on our production system (Ubuntu), the problem arises,
also on the backup system (Windows). There seems to be an old reference, which can not be resolved by Quick Repair. The rebuild of the JS Group files does not help here.

@mikesolo
Thanks for the hint, I would have the next even tried. What you have copied the whole folder?

**Comment by mattlorimer** [comment]
try commenting out/removing line 140:- 
`RGraph.redraw(); `

in modules/AOR_Reports/views/view.detail.php

**Comment by mlwmaklers** [comment]
> try commenting out/removing line 140:- 

 RGraph.redraw();

> in modules/AOR_Reports/views/view.detail.php

Perfect,

 that works.

thank you

**Comment by mikesolo** [comment]
That works for me as well :)
