### ISSUE TITLE
AOR - Suite7 Theme issue with large number of fields/columns

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1127]
When there are a large number of columns/fields returned on the AOR detail view on the Suite7 theme, the table CSS breaks and the user has to scroll the whole page on the x-axis to view some data.

See the forum topic for full information and screen shots: https://suitecrm.com/forum/suite-themes/5894-view-error-in-report-module#29959

**Comment by Dillon-Brown** [comment]
Expected behaviour.
