### ISSUE TITLE
"Email" Action on Listview gives Error

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1136]
Navigate to the Listview of a module. (I was able to replicate this on Accounts, Contacts & Leads Modules)
Select a few records with the checkbox on the left of the row.
Expand the Dropdown on the "Delete" button
Select "Email"
![screenshot from 2016-03-22 09 28 39](https://cloud.githubusercontent.com/assets/13675281/13947175/d4e602aa-f010-11e5-972e-5b076a882258.png)

You are met with the error: TypeError: sListView.send_form_for_emails is not a function 

Highlighted by the forum post: https://suitecrm.com/forum/suitecrm-7-0-discussion/8475-list-view-selected-records-to-send-emails-by-clicking-email-option-from-dropdown-not-working

I have also tested this and could replicate in 7.5.3

**Comment by amgluck** [comment]
I have the same problem in 7.5.2 but do not receive an error message, just javascript:void(0)
