### ISSUE TITLE
Postcode treated as number in invoices

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#1137]
See: https://suitecrm.com/forum/suitecrm-7-0-discussion/8389-postal-code#29192

Apparently the postcode `00187` is displayed as `187`. This seems to suggest that this is being treated and displayed as a number. We may also want to check that something similar doesn't happen to phone numbers.

**Comment by CaptainChainsaw** [comment]
Looks like this has already been fixed.  Works for me in a local hotfix branch.

![gh-issue-1137](https://cloud.githubusercontent.com/assets/3913259/14079603/e5714f04-f4f6-11e5-808d-c5fcbfbcf5a0.png)
![gh-issue-1137-2](https://cloud.githubusercontent.com/assets/3913259/14079626/0fad628a-f4f7-11e5-8ad9-15e31b6f251d.png)

**Comment by JimMackin** [comment]
Working in latest version.
