### ISSUE TITLE
AOW_WorkFlow - execution on 'New Records' fails when user's dateformat is not strtotime compatible

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1138]
A workflow defined to run on: 'On_Save' + 'New_Records' is not executed when user has a date format defined in profile as 'd/m/Y' (and most probably others).
The method `check_valid_bean` in modules/AOW_WorkFlow/AOW_WorkFlow.php has:

```
$beanDateEnteredTimestamp = strtotime($timedate->asUser(new DateTime($timedate->fromDb($bean->date_entered))));
$beanDateModifiedTimestamp = strtotime($timedate->asUser(new DateTime($timedate->fromDb($bean->date_modified))));
$thisDateEnteredTimestamp = strtotime($this->date_entered);
```

and `strtotime` will return (FALSE|-1) if the output is not a correctly formatted string:

[PHP.NET](http://php.net/manual/en/function.strtotime.php)

> 'strtotime — Parse about any English textual datetime description into a Unix timestamp ... Returns a timestamp on success, FALSE otherwise. Previous to PHP 5.1.0, this function would return -1 on failure....Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed. If, however, the year is given in a two digit format and the separator is a dash (-, the date string is parsed as y-m-d.'

and because `$timedate->asUser` WILL also return dates formatted differently.

The use of strtotime here is inappropriate and in some cases will lead to the skipping of the workflow
In some cases because if the date is 
- '3/3/2016' then the date conversion to unixtimestamp will work 
- '3/4/2016' - maybe works but date is converted erronously to the equivalent of 4th of march if 'd/m/Y' is used because as stated before when slash is used in string the American format is assumed(m/d/y)
- '13/3/2016' - will NOT WORK and workflow will be skipped because of the above reason will identify month===13 which clearly does not exists

...PR coming on hotfixes.. ;)...

**Comment by adriangibanelbtactic** [comment]
I think I am not finding this bug in Suitecrm 7.5.x versions.

Did you apply the PR and forgot to close this bug?

Thank you.

**Comment by ijdavie** [comment]
This appears to relate to the following pull requests #1146 and #1144

**Comment by shogunpol** [comment]
@adamjakab  , I tested this issue in recent version of SuiteCRM(7.7.1), and try with different format of the date. In all cases i tested the issue not appear.
Can you confirm tis is not an issue any more?

**Comment by adamjakab** [comment]
yes I have made PRs for this as @ijdavie says but as it appeares i have closed them before they got merged. This was the clean one: #1146
That was a long time ago - here is the fix I came up with [https://github.com/salesagility/SuiteCRM/pull/1146/files](https://github.com/salesagility/SuiteCRM/pull/1146/files)

where, as far as I can recall, I replaced strtotime with date_create_from_format function using the date format user has defined in his profile.

as i can see it [on master branch ](https://github.com/salesagility/SuiteCRM/blob/master/modules/AOW_WorkFlow/AOW_WorkFlow.php#L460) these three lines are as they were when I wrote the issue/PR so I suspect the 
issue is not resolved.

**Comment by ijdavie** [comment]
Hi @adamjakab,

I see this can be a issue on certain dates. Thanks for the quick reply.

**Comment by EZS-JD** [comment]
Is the following bug due to the same issue?

Run: "only on save"
Run on: "Run on all records"
Repeated Runs: checked

Action Modify Record (on module AOS_Invoices):
Due Date > Date > Invoice Date > + > 10 > days

Expected result:
Due Date field = Invoice Date + 10 days

Actual result:
after first save: Today + 10days (regardless of what's entered in invoice date)
after 2. and subsequent saves: Due Date + 10 days. (as expected)

**Comment by mattlorimer** [comment]
Previously Fixed in https://github.com/salesagility/SuiteCRM/commit/0f2f884f88cd488b5d763de79cb10ef13457820c
