### ISSUE TITLE
Imported Opacus e-mails are not in Contact/Account after converting a Lead

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#1139]
When the Lead has imported Opacus e-mails , they disappear after that this Lead has been converted in a Contact or an Account.
To reproduce, just convert a Lead who has two e-mails, one manual and one from Opacus, this one will not be there anymore.

Tested on a clear install of SuiteCRM 7.5.1 on Mozilla Firefox, Thunderbird with Opcaus Addon (prenium)

**Comment by willrennie** [comment]
This sounds like an Opacus API issue as if creating the email within the CRM(manual) carries across on conversion, the Opacus plug-in must not be creating/building the correct relationships. I would recommend you log a bug with the Opacus team.
