### ISSUE TITLE
Problem AOS -  line items desappear

### ISSUE THREAD

**Issue by cmarrero** [salesagility/SuiteCRM#115]
Hi 

If i have a quote and try to conver to invoice or contract  the line items desappear

Regards

![2015-01-24 19-52-28](https://cloud.githubusercontent.com/assets/212819/5889708/00a9ec5e-a403-11e4-80f1-6e15fc30a8f7.png)
![2015-01-24 19-52-44](https://cloud.githubusercontent.com/assets/212819/5889709/00ad2fae-a403-11e4-9017-872fc9297c64.png)

**Comment by cmarrero** [comment]
Hi 
I think is related to bug  #117 
regards

**Comment by mattlorimer** [comment]
I agree, issue will be fixed with #117

**Comment by SpudR** [comment]
This bug is still evident with the #117 fix implemented.

**Comment by mattlorimer** [comment]
if you have implemented the fix try clearing your browser cache.

**Comment by SpudR** [comment]
I did delete the browser cache - and tried on different browsers and tried on different PCs.
All still have the error.

**Comment by SpudR** [comment]
I fixed it!
https://suitecrm.com/forum/installation-upgrade-help/3519-invoices-and-quotes-are-broken-following-7-1-5-upgrade#13982
Using your #117 fix, but using the entire file instead of just manually making the change!
Confused??
