### ISSUE TITLE
radio button ignored in tab order, not even presented

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#1150]
using SuiteCRM 7.4.3 AND vanilla installation 7.5.3...
if you have a radio button field and you tab in the form to fill it up the radio button field is skipped entirelly and never get focus...

This is important for people using accessibility (blind or very low vision) since they never use the mouse...

I know that it was mentioned in the grand father sugar 6.5.18 as bug 58277 but the link to their bug issue no longer works, see https://community.sugarcrm.com/thread/20280

**Comment by shogunpol** [comment]
The issue has been tested on the recent version of SuiteCRM(7.7.4), and it not appear,
@bmwtourer  , can you confirm the issue is not exist any more? 
If yes can you close an issue?

**Comment by bmwtourer** [comment]
I just checked on 7.7.4 and the situation is still problematic
my contact record contains radio button with the right tab order in studio
 and the are never referenced doing edit on a record
tabbing along the form...
The document module having similar radio button does not show problem.
tried to modify my contact radio to find if related to particular field setting but because of bug
"Studio: Can't modify fields - getting 'Invalid Value: Field Name already exists' #2183"
I can not continue... 

Will try with a new test installation and report

**Comment by bmwtourer** [comment]
oups closed by mistake...

**Comment by bmwtourer** [comment]
finally  I remove all tab orders defined, still same problem
then I deleted the whole from and started fresh, it appear this solved the issue.
