### ISSUE TITLE
Contacts missing in export from Target List 

### ISSUE THREAD

**Issue by DylanW101** [salesagility/SuiteCRM#1151]
If a target list consisting of contacts is exported, only the contacts with a related account are included in the export.  Any contact on the target list without an account is just missed in the export.  

I've verified this happens in 7.3.1 and it is also reported [in 7.5](https://suitecrm.com/forum/developer-help/7866-export-of-target-list-doesn-t-export-contacts).  I also have an older instance of Suite (V7.1.4) where exports of all contacts from target lists are working fine, so it seems like this is only happening in the newer versions/ newest version.

**Comment by vladbar** [comment]
Hello DylanW101, thank you for reporting this issue. 

The problem was that the Download ZIP file did not have the latest issue fixes.
It has been resolved. Could you please download the latest version.

**Comment by DylanW101** [comment]
Thanks, we'll test it out on our staging.



On 4/28/2016 4:33 AM, vladbar wrote:
>
> Hello DylanW101, thank you for reporting this issue.
>
> The problem was that the Download ZIP file did not have the latest 
> issue fixes.
> It has been resolved. Could you please download the latest version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/salesagility/SuiteCRM/issues/1151#issuecomment-215395692>
>

-- 


PowerPlay Destination Properties <http://www.powerplaydestination.com>

*DYLAN WHEELER* - DIGITAL MARKETING DIRECTOR

PowerPlay Destination Properties Inc.
#400-601 W Broadway
Vancouver BC Canada V5Z 4C2

Phone +1 778-999-2423 <skype:+17789992423?call>
Skype           dylan-wheeler
Email: dylan@powerplay.properties <mailto:dylan@powerplay.properties>

Notice: this e-mail, including any attachments, is for the intended 
recipient only.  Any dissemination, distribution, copying or action 
taken based on it by anyone else is prohibited. If you received this 
e-mail in error, please notify me immediately at the above e-mail 
address and delete this copy without reading, copying, or forwarding it. 
Thank you.

**Comment by willrennie** [comment]
Tested and resolved in the latest releases of 7.6 and 7.7. @DylanW101 if you have any further issues please comment.
