### ISSUE TITLE
Inline editing confirmation message is hardcoded.

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#1160]
See comments here: https://github.com/salesagility/SuiteCRM/pull/1107

The inline editing message "You have clicked away from the field ..." is hardcoded. It should be in a language file so it can be translated.

**Comment by likhobory** [comment]
Inline editing alert message is also hardcoded in line 473
"There was an error loading the field..."

**Comment by celsocos** [comment]
Yes, the same for me, I can confirm. If this can be changed, will be nice.
