### ISSUE TITLE
opportunity currency ignored in tab order, not even part of tab sequence

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#1162]
using SuiteCRM7.4.3 
the currency field does not appear in tab sequence while editing and I presume for detail view as well.
in fact no tab element is part of the code
 
This is important for people using accessibility (blind or very low vision) since they never use the mouse...

![image](https://cloud.githubusercontent.com/assets/9001018/14019272/50b8b6dc-f1a8-11e5-901c-ac767a03baa9.png)

**Comment by CaptainChainsaw** [comment]
This issue is working for me on Chrome and FF, is there a specific module or area of Suite that this is happening on?  What browser did you experience this on?


Thank you

**Comment by bmwtourer** [comment]
strange, ie and chrome does not on my instance, look at the code there is no html tag....
do you have one?

**Comment by bmwtourer** [comment]
really weird.
in one test instance, yes the sequence is ok but not in most and in production.
I am closing the issue but I still have problems.
thank you CaptainChainsaw  btw it only happens on opportunity edit view...

**Comment by Mausino** [comment]
#609 http://screencast.com/t/oqXKxwaH  it is part of your problem ?

**Comment by bmwtourer** [comment]
Nope, this is going fine for us, we support US$, Canadian$, Australian$, Pound and Euros.
*but* my default currency is US$, which might be part of your problem....
