### ISSUE TITLE
Upgrading to SuiteCRM:  Timesheet module SQL error

### ISSUE THREAD

**Issue by CaptainChainsaw** [salesagility/SuiteCRM#1164]
I had an issue when doing an upgrade with the timesheet module:

`SELECT count(*) c FROM securitygroups LEFT JOIN securitygroups_cstm ON securitygroups.id = securitygroups_cstm.id_c INNER JOIN securitygroups_records ON securitygroups.id=securitygroups_records.securitygroup_id AND securitygroups_records.record_id=N'a8ef002f-7c2a-1747-7d0d-56f3c87000e5' AND securitygroups_records.deleted=0 AND securitygroups_records.module = N'Timesheet' where securitygroups.deleted=0 )`

`SQL Error : Incorrect syntax near ')'.`

This is happening because of the trailing ")".

Just found out this is not part of Suite so can't commit a fix for it.  Here's the fix anyway:

change the following function in `modules/Timesheet/Timesheet.php`

    'function _get_num_rows_in_query($query) {
        $query = preg_replace("/^\((.*?)\)$/", $matches[1], $query); 
        return parent::_get_num_rows_in_query($query);
    }`

**Comment by willrennie** [comment]
Closing as this is not a SuiteCRM bug but a Timesheet extension/module bug. This should be raised to the Timesheet project developers/community if there is an active page/project.
