### ISSUE TITLE
Reminder Emails Not Being Sent but Notifications Appear on Desktop and in Browser

### ISSUE THREAD

**Issue by ACC-Medlink** [salesagility/SuiteCRM#1166]
I set a reminder to be sent about  phone call. The popup is there but no emails arrive in my inbox regarding the call reminder. All other emails are being sent. The correct data is being entered into the database but no email is ever sent.

V 7.5

**Comment by shogunpol** [comment]
@ACC-Medlink , I tested this issue on recent version of SuiteCRM(7.7.1), and does not appear, all reminders through CRM and also receive emails it work. 
Can you confirm the issue is not appear in recent version of SuiteCRM?

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this is still an issue it can be reopened with more information. 
Thanks.
