### ISSUE TITLE
Bug in 7.5.3 with MSSQL

### ISSUE THREAD

**Issue by derekngreene** [salesagility/SuiteCRM#1171]
After upgrade to 7.5.3 on save of existing lead/contract - the system throws a "database failure" and doesn't save the record.  The log shows the following issue:

03/28/16 07:12:49 [13056][4079df2b-41d6-03d8-1896-515eb34b8b28][FATAL]  Query Failed:SELECT meetings.* from meetings_users,meetings  WHERE ((meetings.date_start >= CONVERT(datetime,N'2016-03-27 04:00:00',120) AND meetings.date_start < CONVERT(datetime,N'2016-05-27 04:00:00',120)) OR (meetings.date_start < CONVERT(datetime,N'2016-03-27 04:00:00',120) AND date_end > CONVERT(datetime,N'2016-03-27 04:00:00',120)) AND meetings_users.accept_status != N'decline') AND ::: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'AND'.

Seems the query wasn't written correctly for MSSQL.  Please add to the bugs list for the next release

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.3), and it not appear.
Can you try replicate this again on recent version of SuiteCRM(7.7.3), 
And when you upgrade, please do repair->quick repair and rebuild.
Thanks for your contribution.

**Comment by ijdavie** [comment]
Due to lack of activity this issue will be closed, if more information is given and the issue still exists the issue can be reopened.
