### ISSUE TITLE
Some Logic Hooks Fail On Security Groups

### ISSUE THREAD

**Issue by daniel-samson** [salesagility/SuiteCRM#1174]
In relation to a post in the [SuiteCRM Forum](https://suitecrm.com/forum/developer-help/8668-after-relationship-delete-logic-hook-for-securitygroup-module#30342).

The before_relationship_delete and after_relationship_delete will not be called. The problem is in data/Relationships/M2MRelationship.php in lines 265 - 361. It has been deliberately prevented. 

```
/* BEGIN - SECURITY GROUPS */
//Need to hijack this as security groups will not contain a link on the module side
//due to the way the module works. Plus it would remove the relative ease of adding custom module support
```

To me this seems like unexpected behaviour. 

I tested this on fresh copy of suite 7.5.3 - the issue still stands.

**Comment by willrennie** [comment]
@daniel-samson if this is a bug in the core of the Security Suite extension(basic extension is standard in SuiteCRM out of the box) it may be best to contact the Security Suite team as they may be able to fix for all versions of the extension and we can then merge the fix into our product going forward.
