### ISSUE TITLE
Global search issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1175]
After update from 7.4.3 to 7.5.3 version we got this error in global search

![global](https://cloud.githubusercontent.com/assets/5773777/14104730/fa285f36-f5a6-11e5-8f52-ec4decc6ebe2.png)

Reason is that we disabled the SecuritySuite module and this overwrote some files :-1: afer allow it, it is working fine

**Comment by ijdavie** [comment]
Hi Mausino, 

From what you are saying you have disabled Security Suite via code, Security Suite currently can not be turned off and trying to do this could cause unforeseen issues as it was not intended to be disabled. 

If you still have problems with your customisation's if you raise them in the forums other developers can help.

**Comment by Mausino** [comment]
The issue was resolved by our developer :) Thanks for your answer.
