### ISSUE TITLE
Issue creating new fields

### ISSUE THREAD

**Issue by timgent** [salesagility/SuiteCRM#1177]
When trying to add or edit fields in a module an error message is shown:
( ! ) Warning: Creating default object from empty value in C:\xampp\htdocs\crm\trunk\modules\ModuleBuilder\views\view.modulefield.php on line 151 

For full details and code change (which also works in SuiteCRM) see here:
http://stackoverflow.com/questions/20468830/sugercrm-warning-creating-default-object-from-empty-value

**Comment by MikeyJC** [comment]
What version of SuiteCRM are you using?

**Comment by timgent** [comment]
7.5.3
If you have docker and docker-compose you can replicate the issue quickly using this repo:
https://github.com/timgent/docker-suitecrm

Commands are:
docker-compose build
docker-compose up

**Comment by vladbar** [comment]
Hello timgent,
thank you for your suggestion. 

Ive read the forum posts, added the code and tested it.
As you mentioned, it prevents the warning from appearing.

**Comment by timgent** [comment]
Great thanks
