### ISSUE TITLE
Reminder emails are not being generated

### ISSUE THREAD

**Issue by ACC-Medlink** [salesagility/SuiteCRM#1180]
Desktop alerts and in browser alerts work fine but no email is generated for reminders. As a work around I tried to send an email every time an alert is created with a workflow but it fails a lot for some reason. Any ideas why?

**Comment by daniel-samson** [comment]
@ACC-Medlink Do you have the email setting set up inside SuiteCRM?

**Comment by willrennie** [comment]
@ACC-Medlink please can you respond to @daniel-samson questions to further debug your issue?

**Comment by ijdavie** [comment]
Due to lack of activity we will close this issue, if this issue is still a problem it can be reopened or a new issue created for it. 
Thanks .
