### ISSUE TITLE
Outbound Email issue - smtp server madness

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1182]
This has been bugging me for a while now - maybe today I understood what the problem is:
I have an smtp server DNS which is a CNAME:

```
;; ANSWER SECTION:
mail.staff.something.it.    235     IN      CNAME   email2-wh.something-it.com.
email2-wh.something-it.com. 177  IN      A       xxx.xxx.xxx.xxx
```

If I configure the SMTP with 'SMTP Server':
- mail.staff.something.it - DOES NOT WORK,
- email2-wh.something-it.com - WORKS
- xxx.xxx.xxx.xxx - WORKS

When it does not wotk I find this in the logs:

```
Wed Mar 30 14:38:07 2016 [23158][1][FATAL] SugarPHPMailer encountered an error: The outbound mail server selected for the mail account you are using is invalid.  Check the settings or select a different mail server for the mail account.
Wed Mar 30 14:38:07 2016 [23158][1][FATAL] SugarPHPMailer encountered an error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

could it be something to do with DNS/cname resolution in outdated PHPMailer class?

**Comment by adamjakab** [comment]
...and the same thing happens on inbound mail - if I use imap.gmail.com I cannot connect to my account.

```
;; ANSWER SECTION:                                                                                                                              
imap.gmail.com.         300     IN      CNAME   gmail-imap.l.google.com.                                                                        
gmail-imap.l.google.com. 300    IN      A       74.125.133.109                                                                                  
gmail-imap.l.google.com. 300    IN      A       74.125.133.108   
```

also here "imap.gmail.com" is a CNAME - if I use the ip or 'gmail-imap.l.google.com' it works.

**Comment by adamjakab** [comment]
I have extracted the connect method from phpmailer's class.smtp.php class using the stream_socket_client method. [Here is the gist to test.](https://gist.github.com/adamjakab/82756e24c69119cedddcc64725632e48)

Here is what it says:

```
Warning: stream_socket_client(): Peer certificate CN=`email2-wh.vhosting-it.com' did not match expected CN=`mail.staff.mekit.it' in mailtest.php on line 40

Warning: stream_socket_client(): Failed to enable crypto in mailtest.php on line 40

Warning: stream_socket_client(): unable to connect to ssl://mail.staff.mekit.it:993 (Unknown error) in mailtest.php on line 40
CONN-NOPE!

```

It is quite clear, we are connecting to 'mail.staff.mekit.it' which resolves to 'email2-wh.vhosting-it.com' and recieves its certificate which however states that the CN is  'email2-wh.vhosting-it.com' and NOT 'mail.staff.mekit.it' - i'd say correctly.

I guess the only way to resolve this s to resolve the dns beforehand...

any ideas?

**Comment by JimMackin** [comment]
Your gist does work for me for both `imap.gmail.com` and `mail.staff.mekit.it`:
```
HOST1 - imap.gmail.com
CONN-OK
HOST2 - ssl://imap.gmail.com
CONN-OK
```

```
HOST1 - mail.staff.mekit.it
CONN-OK
HOST2 - ssl://mail.staff.mekit.it
CONN-OK
```

I suspect this then may be caused by differing PHP versions/environments.

Can you provide your PHP version, OS and OS Version and the contents of `$errno` and `$errstr` when the connection fails?

For reference I tried using PHP 5.5.9 on Ubuntu 14.04/
