### ISSUE TITLE
Unable to get proper side for link assigned_user_link within Campaign Wizard 

### ISSUE THREAD

**Issue by tmdpny** [salesagility/SuiteCRM#119]
I am trying to attach a target list to a campaign through the Campaign Wizard.

If I try to create a new target list from within the wizard, nothing happens when I click the 'create button'
-- no action on the screen
-- no errors in the log

When I click on the Select button in the 'Use existing Target List' the pop up opens and allows me to select an existing list, then closes.
The list is not added to the campaign and I get these errors in the log

Sun Feb 1 03:30:47 2015 [19488][1][ERROR] Unable to get proper side for link assigned_user_link
Sun Feb 1 03:30:47 2015 [19488][1][ERROR] Unable to get proper side for link assigned_user_link

Thoughts?

**Comment by willrennie** [comment]
Works for me in the latest release(7.3). Please ensure you have performed a Quick Repair & Rebuild and Rebuild Relationships in Admin -> Repair.
