### ISSUE TITLE
Request: Live chat community support for developers

### ISSUE THREAD

**Issue by Georgiel** [salesagility/SuiteCRM#1192]
it's a pity the SuiteCRM community doesn't have a live community support chat room, would be a great way to help new users figure the ins and outs and I think the immediacy of it all would make it more effective than the forum is.

There's Gitter, which makes a live chat for any github repository. And other options too.

**Comment by ghermans** [comment]
:+1:

**Comment by willrennie** [comment]
Thank you for your comments and I can understand the requirement and desire for chat and this has been discussed before on the forums and there are various threads there. I would keep the discussions active on the forums, as this is not a suggestion relevant to the product or project itself, but to the community. The community is very important to the success of SuiteCRM and I am sure as the community grows with the product more options to engage will be discussed and implemented.

**Comment by Georgiel** [comment]
But,  love chat is free to setup or of minimal cost....so I don't see why it would need to wait

**Comment by Georgiel** [comment]
But, live chat is free to setup or of minimal cost....so I don't see why it would need to wait
