### ISSUE TITLE
Not searching invitees  while creating new meeting

### ISSUE THREAD

**Issue by chrisdent** [salesagility/SuiteCRM#1194]
I have SuiteCRM version 7.5.2 Installed.

While creating a new meeting and trying to add invitees by searching for them it wont search, like the button does not work.

Best regards,

Chris

**Comment by MikeyJC** [comment]
What browser are you using? I would also recommend trying other browsers if you're able.

**Comment by chrisdent** [comment]
Fixed it!

Changing in include/util.php :
Line 2137: comment it.
// preg_match('/[\'"<>]/', $value, $matches);
Adding just below:
2138:	preg_match('/\'"<>/', $value, $matches);

Seems to be a problem with php 5.6

Thanks and best regards.
