### ISSUE TITLE
EntryPoint download fails when no _cstm table

### ISSUE THREAD

**Issue by baxtian** [salesagility/SuiteCRM#1195]
Just changes lines 157 and 158 in file download.php with these:

$query = "SELECT " . $image_field ." FROM " . $file_type . " ";
if(substr($image_field, -2) == "_c" ) $query .= "LEFT JOIN " . $file_type . "_cstm cstm ON cstm.id_c = " . $file_type . ".id ";
$query .= "WHERE " . $file_type . ".id= '" . $db->quote($image_id) . "'";

**Comment by vladbar** [comment]
Hello baxtian could you please provide some more details in regards to how the problem manifests itself - which conditions cause the code on line 157 to fail. Thank you.

**Comment by baxtian** [comment]
Hi Vladbar, thanks for answer.

This is the list of actions to replicate the situation.

- Create a module using the Module Builder.
- Add a field of type image to the new module using the Module Builder (**do not use the studio** for this).
- Save and deploy the new package.
- Go to the module that has the image field, try to upload the image.

The system uploads the image (you can see it in the upload directory) but the Entry Point (download) returns an error.

Debuging the EntryPoint I found the query uses a LEFT JOIN with the _cstm table, and because the module was created using Module Builder and I haven't used the Studio so far, there is no _cstm table.

My first solution was to create a ghost field using the studio (it creates the required table).
The other one I can imagine is to force the Module Builder to create the _cstm table.
The solution I have implemented is to use the JOIN LEFT only if the image_field ends with _c.

Thanks.

**Comment by vladbar** [comment]
Hi baxtian , thank you for finding this issue and providing suggestions on how to fix it. I implemented the solution, which you mentioned and tested it with both filed types - created in Module Builder and created in Studio - both of them work with your fix applied. Thanks again!
