### ISSUE TITLE
Error creating task from workflow

### ISSUE THREAD

**Issue by fgpalacios** [salesagility/SuiteCRM#120]
I'm trying to define a simple rule in the workflow module, but does not work.

I want to evaluate the status of a task (completed) if it is true that you create a new task.

**Comment by willrennie** [comment]
Is this still an issue? If so, can you provide steps to repeat and attach screen shots?

**Comment by willrennie** [comment]
I have tested this functionality and it works out of the box. I would suggest checking your php error.log and sugarcrm.log for any workflows when the workflow fires. If the workflow doesn't fire, please check the 'Run AOW Workflow' scheduler in Admin -> Scheduler.
