### ISSUE TITLE
Emails: save() does not recognize parent_(bean|id) modifications in fetched_row

### ISSUE THREAD

**Issue by croessler** [salesagility/SuiteCRM#1200]
SuiteCRM: 7.0.2 (but does not matter, that error even was in SugarCE)

**Description:**
When Editing an Email one can modify the parent relation. Let's say I am about to store an Email to an Account. I chose Account as parent-type and type in the accountname ("account A"). Saving the Email saves the parent relation correctly. That Email ist related to to "account A".

Now i edit that Email egain, but now choose another account ("account B") as parent. 
- Saving that Email shows the Email in "Account A" and "Account B".
- There are multiple undeleted entries in table "emails_beans" for that email-bean.
- The code in /Emails/Email.php, save(), line ~1065 checks for modified parent-type and/or parent-id by comparing $bean->parent_type and $bean->fetched_row['parent_type']... But that particular code is AFTER parent::save() and thus $bean->fetched_row is not set anymore (with the beans contents before saving) and cannot be compared. Thus there are no modifications, the old parent relation is not deleted but the new parent relation is added. 

**Expected Behaviour:**
- when changing the emails beans parent id/type, old parent relations must be softdeleted and only one (the new one) relation must exist.
- One email can only be related to one parent bean (but one Account can have multiple different emails).

PR follows.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
