### ISSUE TITLE
Users subpanel in SecurityGroups Module

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#1202]
Hi, in SuiteCRM 7.5.3 the Users subpanel in SecurityGroups Module has been overwritten.
There's no more Edit Button or "not inheritable" checkbox.

See here for screenshots:
https://suitecrm.com/forum/suitecrm-7-0-discussion/8693-securitysuite-in-users-subpanel-there-s-no-more-edit-button

===
Edit
===
I can say that if you go from Users module, you will see a SecurityGroups subpanel with "Edit Button". This allows you to select the "Not inheritable" property.

**Comment by MikeyJC** [comment]
In modules/SecurityGroups/metadata/subpaneldefs.php, on line 17 you should see:

`'subpanel_name' => 'default',`

Change this to:

`'subpanel_name' => 'ForSecurityGroups',`

Repair and rebuild and you should see the correct subpanel being displayed.

**Comment by mayerelyashiv** [comment]
Great!
It works, thank you
