### ISSUE TITLE
Project Tasks - mass update function error

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1203]
When i want mass update the project task status on listview, i got this error:

Fatal error: Call to a member function format() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/ProjectTask/updateProject.php on line 53

**Comment by daniel-samson** [comment]
Hi,

Can you give me some information about the bug?

I need to know:
* what web browser are you using?
* what version is the version of SuiteCRM  (go into Admin -> About).
* what webserver is SuiteCRM running on?

I can't seem to reproduce the error on SuiteCRM 7.5.3

**Comment by Mausino** [comment]
Hi, some info for you :)

Videoscreen of issue: http://screencast.com/t/Htznqtpzt
Browser version: 51.0.2704.22 beta-m (64-bit) (i tried opera + edge) same result
SuiteCRM version: Version 7.5.3 Sugar Version 6.5.23 (Build 1061)
PHP: 5.4.45 and Linux (2 x 3.0 GHz CPU Cores, CentOS, 5GB RAM, 50GB SSD, cPanel,)
