### ISSUE TITLE
Search function in list view disappears in smaller windows

### ISSUE THREAD

**Issue by HarleyScotcher** [salesagility/SuiteCRM#1208]
Hi All,

If I shrink my browser or bounce them to the side of the screen I lose the search fields in list view. The screen gets to a certain size and the search fields disappear, shrinking the browser further creates a search button but that button does not work.

at 990x1080 I can still search, by 960x1080 I can no longer use the search fields

Anyone else experiencing this issue?

**Comment by shogunpol** [comment]
This issue happens in suite R - theme, and we have raised this as a bug.
However in recent version of SuiteCRM(7.7.1), in Suite-P theme, problem is solved.
Thanks for raise this issue.
