### ISSUE TITLE
Detailview in Studio is broken

### ISSUE THREAD

**Issue by mlwmaklers** [salesagility/SuiteCRM#121]
The detail view in Studio is broken. Layouts can not be customized. The display is incomplete.

**Comment by willrennie** [comment]
Can you detail steps to repeat? I cannot replicate.

**Comment by dbphoto84** [comment]
sounds like an isolated incident to your installation. Check any custom changes for the module your trying to change.

**Comment by mlwmaklers** [comment]
Yes the problem has resolved with the finished release of 7.2. It reappeared on the stage, when the theme was not yet ready. Thanks
