### ISSUE TITLE
Suite 7 Theme - undefined indexes

### ISSUE THREAD

**Issue by jellydonuts** [salesagility/SuiteCRM#1216]
Getting these errors on every page in my apache error log

PHP Notice: Undefined index: buttontop in themes/Suite7/css/colourSelector.php on line 50 

The errors are between lines 46 and 50 and are about the "buttonbottom", "buttontop", "buttonmid" "button1", "button4" array indexes in the $sugar_config['theme_settings']['Suite7'] array

**Comment by MikeyJC** [comment]
Hi @jellydonuts 
What version of SuiteCRM are you using? I've tried to replicate on 7.6.3 and 7.6.4 with no success. It's possible that the issue was fixed in an update.

**Comment by ijdavie** [comment]
Due to lack of activity we will close this issue, if this issue is still a problem it can be reopened or a new issue created for it. 
Thanks .
