### ISSUE TITLE
No metadata/popupdefs.php in EmailTemplates

### ISSUE THREAD

**Issue by axestr** [salesagility/SuiteCRM#1217]
Version 7.5.3
Sugar Version 6.5.23 (Build 1061)

All => Emails => Creater Email Template => [Document]
A popup comes just showing a trace:
`Warning: require_once(modules/EmailTemplates/metadata/popupdefs.php): failed to open stream: No such file or directory in /var/www/home_ssl_pmIT/SuiteCRM/include/Popups/Popup_picker.php on line 68 Call Stack: 0.0001 655408 1. {main}() /var/www/home_ssl_pmIT/SuiteCRM/index.php:0 0.0559 6843264 2. SugarApplication->execute() /var/www/home_ssl_pmIT/SuiteCRM/index.php:49 0.0666 9523136 3. SugarController->execute() /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/SugarApplication.php:90 0.0670 9682464 4. SugarController->processView() /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/Controller/SugarController.php:295 0.0677 9903464 5. SugarView->process() /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/Controller/SugarController.php:348 0.0689 9956416 6. ViewClassic->display() /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/View/SugarView.php:143 0.0689 9956544 7. SugarView->includeClassicFile() /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/View/views/view.classic.php:74 0.0709 10222432 8. require_once('/var/www/home_ssl_pmIT/SuiteCRM/modules/EmailTemplates/PopupDocumentsCampaignTemplate.php') /var/www/home_ssl_pmIT/SuiteCRM/include/MVC/View/SugarView.php:721 0.1061 10361144 9. Popup_Picker->Popup_Picker() /var/www/home_ssl_pmIT/SuiteCRM/modules/EmailTemplates/PopupDocumentsCampaignTemplate.php:49 `

URL Part: index.php?module=EmailTemplates&action=PopupDocumentsCampaignTemplate&to_pdf=true&target=

There is no metadata/popupdefs.php in EmailTemplates:
`ls modules/EmailTemplates/metadata/
 listviewdefs.php
 searchdefs.php
 SearchFields.php
 subpaneldefs.php
`
But required by include/Popups/Popup_picker.php:68:
`require_once('modules/' . $currentModule . '/metadata/popupdefs.php');`

**Comment by MikeyJC** [comment]
Hi, you should create a popupdefs.php file in the modules/EmailTemplates/metadata folder and insert the following code:

`<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$module_name = 'EmailTemplates';
$table_name = 'email_templates';
$popupMeta = array('moduleMain' => 'EmailTemplate',
    'varName' => $module_name,
    'orderBy' => $table_name.'.name',
    'whereClauses' =>
        array('name' => $table_name . '.name',
        ),
    'searchInputs'=> array('name'),
    'listview' => 'modules/' . $module_name. '/metadata/listviewdefs.php',
    'search'   => 'modules/' . $module_name . '/metadata/searchdefs.php',

);
?>` 

That should hopefully create the correct popup!

**Comment by axestr** [comment]
Perfekt, that works, thx!
=> Closed
