### ISSUE TITLE
Add Tabs Issues

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#122]
Add Tabs seems to have intermittent issues when users try to add new tabs and/or remove existing tabs. This has been reported several times by different users.

**Comment by Egarretsen** [comment]
I can confirm this issue, there is also a thread about this on https://suitecrm.com/forum/developer-help/1823-unable-to-add-dashlet-at-home-page-screen 
Adding a dashlet only works for me when first clicking the "Suite Dashboard" tab before clicking on "Add Dashlets"
