### ISSUE TITLE
Image Field upload is not working in chrome on Inline editing if an image field is added to a module through Studio

### ISSUE THREAD

**Issue by sathishsengodan** [salesagility/SuiteCRM#1222]
If a image field is added to Accounts Module and then in the module, if you try to add an image through inline editing, it breaks and saves the path as "c:/fakepath/*.jpeg" in chrome browser

It is almost similar in Firefox as well.  

Although, in the editview, everything works fine on both the browsers.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
