### ISSUE TITLE
AOR - Date as parameter issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1224]
Hi, when you use date as parameter, first it will show date but after using filter doesn't show it (it will stay blank, but filter works correctly)

Before 

![filter_before](https://cloud.githubusercontent.com/assets/5773777/14379517/9baddc70-fd7a-11e5-8071-56284be830ed.png)

After

![filter_after](https://cloud.githubusercontent.com/assets/5773777/14379519/9f4427b8-fd7a-11e5-9848-c8af3aeb8e30.png)

**Comment by jellydonuts** [comment]
hey Mausino, I had lots of issues with the AOR Reports and date fields, see these bugs that I've gotten fixed. #1082 #1083 

As well, you may want to standardize on using the Y-M-D format as this works perfectly for me and I recall having some issues with the reports module using different date formats than that of the actual value in the system.

**Comment by vladbar** [comment]
This issue is a duplicate and have been fixed in #1082 #1083.
