### ISSUE TITLE
Fetching vCal of non-existing user breaks Basic Authentication in Chrome

### ISSUE THREAD

**Issue by metaxmx** [salesagility/SuiteCRM#1225]
In Chrome, receiving a status code 401 (Unauthorized) will invalidate active Basic Authentication credentials and will ask the user again for the credentials.

The "vCal WebDAV Server " module in SuiteCRM returns this status code when a calendar is requested for a non-existing user. Apparently this method is sometimes requested for non-users (e.g. "Leads") if you want to edit a reminder including a Lead.

So if you use SuiteCRM behind a Basic Authentication protection, you have to re-enter your credentials every time you enter such a page.

Possible solution: return another status code than 401 in case of a non-existing user id for this request.

**Comment by ijdavie** [comment]
This relates to Pull Request - #1226
