### ISSUE TITLE
Upgrade using SuiteCRM-Upgrade-7.5.x-to-7.5.3 version differences

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#1227]
Upgrading from 7.5.1 -> 7.5.3 ( according to suitecrm_version.php)

suitecrm_version.php shows $suitecrm_version      = '7.5.3';
config.php shows 'suitecrm_version' => '7.5.2',

The system being upgraded was also inconsistent:
suitecrm_version.php was $suitecrm_version      = '7.5.1';
config.php was 'suitecrm_version' => '7.2.2'

I am taking suitecrm_version.php contents as correct.

**Comment by mattlorimer** [comment]
suitecrm_version.php is correct

**Comment by 604MediaDeveloper** [comment]
Extract the upgrade package and do the following change and then archive and install the package.

File Location : SuiteCRM-Upgrade-7.5.x-to-7.5.3/scripts/suite_install/suite_install.php
Remove : $sugar_config['suitecrm_version'] = '7.5.2';
Add : $sugar_config['suitecrm_version'] = '7.5.3';
Now config.php will show the correct version
