### ISSUE TITLE
Checkbox not displayed when exported to PDF

### ISSUE THREAD

**Issue by DavidBogar** [salesagility/SuiteCRM#123]
I didn't see a bugfix for this, hoping it can make it into the next release? 

When generating a PDF the value of 'checked' in checkbox's is not displayed as checked in the PDF. I was looking in modues/AOR_Reports for the bugfix.

**Comment by dbphoto84** [comment]
I fixed this issue - 
Controller.php in AOS_Reports 
Replace Lines 143 and 144 
$pdf->WriteHTML( str_replace('CHECKED', 'checked="checked"', $printable), 3);
$pdf->Output($this->bean->name.'.pdf', "D");

submitted request

**Comment by r3code** [comment]
Fix posted in a Pull request #128
