### ISSUE TITLE
Use and move to any type of standards code recommendation 

### ISSUE THREAD

**Issue by JoshuaQ** [salesagility/SuiteCRM#1231]
I think that is imposible to debug or make robust code or legible code if inside there are code without any type of standards. 
Is necesary to define a any type of standard, for example http://www.php-fig.org/ or whatelse, and when anybody touch a file, minimal, minimal, use the auto-format, previous to save to correct the indent. 
My eyes hurts when I try to debug an error by the core sugar. 
PLEASE you define to use any standard, and bit a bit implement inside. It is necessary to move forward.

**Comment by JimMackin** [comment]
Similar to #782

**Comment by mattlorimer** [comment]
Thanks for your suggestion, we are gradually/slowly cleaning up the code to PSR standards
