### ISSUE TITLE
AOR_Reports - Rows per page for pagination 

### ISSUE THREAD

**Issue by jellydonuts** [salesagility/SuiteCRM#1232]
Hi there,

The AOR_Reports module does not adhere to the system's configuration value for "Listview items per page:" 

it is instead hardcoded to return 20 rows in modules/AOR_Reports/AOR_Report.php on line 532:
` 532         $max_rows = 20;`

There should be some way to set this, preferably a configuration value for each user, or at least a system wide setting.

**Comment by 604MediaDeveloper** [comment]
Please do the following changes to overcome this issue
File Location : modules/AOR_Reports/AOR
File Changes : 
   Remove : $max_rows = 20;
   Add : if($sugar_config['list_max_entries_per_page']!='')
            {
                  $max_rows = $sugar_config['list_max_entries_per_page'];
            }
           else
           {
                  $max_rows = 20; 
           }

It will take Listview count value from Admin -> System Settings -> Listview items per page

**Comment by vladbar** [comment]
Hi  jellydonuts, 
thank you for your comment. 

The line that you mentioned here (532) relates to the function build_report_html, which deals with a single report not "Listview items per page:" . 

As mentioned here by  604MediaDeveloper you can change the ListView value by changing it in:
Admin -> System Settings -> Listview items per page.

**Comment by jellydonuts** [comment]
thanks for the fix guys.
