### ISSUE TITLE
Menu transparency on mobile devices

### ISSUE THREAD

**Issue by gregsoper** [salesagility/SuiteCRM#1240]
The menu background becomes transparent when rendered on a mobile device - tested on tablet (Samsung Note 8) and phone (LG G4), both Android and tested in Firefox and Chrome
![screen](https://cloud.githubusercontent.com/assets/6449723/14537436/45515404-0277-11e6-9ca5-30159058a383.png)

This makes SuiteCRM unusable on a mobile device.

Image attached

**Comment by samus-aran** [comment]
This looks like it has been resolved -  #1062
