### ISSUE TITLE
History Due Dates shown in Red

### ISSUE THREAD

**Issue by TheFlyinGeek** [salesagility/SuiteCRM#1242]
Once I've finished and closed a Task/Phone Call within an Account/Opportunity it moves to the History subpanel, however the Due Date still shows up in red colours. In my opinion Due Dates shouldn't be coloured anymore in the History subpanel as they have been dealt with. Is this a bug or can this be changed?

**Comment by 604MediaDeveloper** [comment]
Please do the following changes to overcome the above bug.

For Call Module : 

For Task Module :

**Comment by 604MediaDeveloper** [comment]
**For Task Module :** 

    ** File location :** modules/Tasks/Task.php
     **File changes :**  
              **Remove :** $taskClass = 'overdueTask';
              **Add :** if($task_fields['STATUS']=='Completed' || $task_fields['STATUS']=='Deferred'){ $taskClass = '';} else { $taskClass = 'overdueTask'; }

**Comment by 604MediaDeveloper** [comment]
**For Meeting Module :** 

     **File location :** modules/Meetings/Meeting.php
     **File changes :**  
              **Remove :** $meeting_fields['DATE_START']= "<font class='overdueTask'>".$meeting_fields['DATE_START']."</font>";
              **Add :** if($meeting_fields['STATUS']=='Held' || $meeting_fields['STATUS']=='Not Held') { $meeting_fields['DATE_START']= "<font>".$meeting_fields['DATE_START']."</font>"; } else {  $meeting_fields['DATE_START']= "<font class='overdueTask'>".$meeting_fields['DATE_START']."</font>"; }
 Please let me know if you still facing this issue.

**Comment by TheFlyinGeek** [comment]
Thanks a lot, that did the trick! Hope this will be permanently fixed in future releases.
