### ISSUE TITLE
AOR_Reports - Crash when main group is custom dropdown

### ISSUE THREAD

**Issue by jellydonuts** [salesagility/SuiteCRM#1251]
When I create a report and set the main group to be a dropdown from the tasks module, I am shown a white screen with the following error being displayed.

`PHP Catchable fatal error:  Argument 4 passed to AOR_Report::build_report_query_join() must be an instance of SugarBean, string given, called in modules/AOR_Reports/AOR_Report.php on line 401 and defined in modules/AOR_Reports/AOR_Report.php on line 1038`

**Comment by jellydonuts** [comment]
i think there is a missing parameter there. Not exactly sure what the $parent alias is supposed to be, but if i change the call to the function like so, it's fixed. Please verify of proper solution.

`$query_array = $this->build_report_query_join($table_alias.'_cstm', $table_alias.'_cstm', '', $field_module, 'custom', $query);`

**Comment by vladbar** [comment]
Hi  jellydonuts could you please provide a bit more details about the report which you are trying to create (Report Module, fields, conditions, charts). I tried to recreate this issue by Creating the following report:
- Report Module: Tasks
- Fields: Custom field of type Dropdown (I created this field in Studio and added activity_dom list for the 'Drop Down List:' field)
but it does not show me any errors.

**Comment by vladbar** [comment]
Hello  jellydonuts, 
I have tested the solution which you proposed and it works. I created a pull request so the code can be reviewed and hopefully merged.
Thanks again for your help!

**Comment by jellydonuts** [comment]
No problem.

Just wondering, your fix looks exactly like the line that was commented out/replaced in the current version of the file... why was it commented out in the first place?
