### ISSUE TITLE
Wrong placement of task on calendar

### ISSUE THREAD

**Issue by KipchirchirIan** [salesagility/SuiteCRM#1259]
Every time I create task it is somehow placed an hour after on the calendar. For example, below, the task is set to start at 10.00am. If you look closely at the calendar, the task has been placed at the 11.00am line. My timezone is EAT(Africa/Nairobi)...if I got something wrong/misunderstood...my apologies. I am new to SuiteCRM.
![taskcalbugsuitecrm](https://cloud.githubusercontent.com/assets/3757280/14694520/cba8ff26-0771-11e6-857d-603efcd10dcc.png)

**Comment by mikebeck** [comment]
The Task module in calendar shows the Due Date & Tim, is not extended like is with Calls and Meetings

**Comment by KipchirchirIan** [comment]
Thank you for the clarification.
