### ISSUE TITLE
AOS_PDF_Templates templateParser guesses the field type

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#126]
The templateParser class in AOS_PDF_Templates does some cleanup if the field name has the string "date" in it. However if this is a text field then the string is corrupted (in the date example only the first word is shown. 

These values are built up in a loop that has access to the field_defs. We should probably check the field type rather than guessing what processing to do based on the name.

**Comment by daniel-samson** [comment]
I have created a solution. See pull request #753.
