### ISSUE TITLE
Suite 7.6rc: Version in manifest of upgrade packages is wrong

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1266]
In the upgrade package from 7.6beta2-to-7.6rc the following is wrong:
            'regex_matches' =>
                array (
                  '^7\.6beta2\.(.*)'
                ),

This matches '7.6beta2.' but not the version of beta2 which is '7.6beta2' without the dot.
I think it should be:
            'regex_matches' =>
                array (
                  '^7\.6beta2(.*)'
                ),

**Comment by willrennie** [comment]
Closing as 7.6 is now in production and having checked all available installation/upgrade packages available for 7.6 they all have correct manifest/version details.
