### ISSUE TITLE
Suite CRM : Can't resize my dashlet

### ISSUE THREAD

**Issue by zackzulg** [salesagility/SuiteCRM#1270]
Good morning,

When I click on edit dashlet ( default ones and customized ) an error eppears : There was an error handling this request.

I tried to use SuiteCRM 7.5 , 7.5.1 and 7.5.3 and all of them give the same issue.
![sans titre](https://cloud.githubusercontent.com/assets/11558642/14736417/d4d71d96-086e-11e6-962c-5a342dea3f0d.png)

**Comment by ghermans** [comment]
I tried to replicate the issue and can't confirm this issue.

![selection_170](https://cloud.githubusercontent.com/assets/1594411/14736507/d8ff0ea2-0877-11e6-888e-6042e4bbdd38.png)

**Comment by zackzulg** [comment]
Hello and thanks for the reply, you use edit dashlet calendar, it works too for me, i hope you could try editing calls or accounts and see if it gives you the Same  issue. Regards

**Comment by ghermans** [comment]
i tried both and i don't have any issues with it. (this is a clean 7.5.3 install from 2 days ago)

![selection_172](https://cloud.githubusercontent.com/assets/1594411/14760005/f270ccee-0936-11e6-8f2b-2b591b484239.png)
![selection_173](https://cloud.githubusercontent.com/assets/1594411/14760006/f274941e-0936-11e6-8d47-eb70e56a3bcc.png)

**Comment by ghermans** [comment]
I also did some extra checking by changing the theme to suite 7, however still no issues.
You can try to find a solution for this on the [Forum](https://suitecrm.com/forum/index)

**Comment by samus-aran** [comment]
@zackzulg Is the Calendar customised?  The screenshot shows its different from the default calendar Suite uses.  Can you confirm if this is still an issue with the default calendar in dashlets.

**Comment by willrennie** [comment]
Closing as this appears to be a custom calendar that is causing the issue and is not an issue with the core calendar/dashlet. If you have any further questions/issues, please post on the forums as mentioned by @ghermans
