### ISSUE TITLE
Project Template and date format

### ISSUE THREAD

**Issue by SNDK77** [salesagility/SuiteCRM#1274]
I create a project template and when I try to create a new project from the Project Template module system ask about the name and start date.

If you don´t fill the date then system give Error 500

Also the date format is in MM/DD/AAAA but system and user date format are in DD/MM/AAAA. This bug is a really trouble cause my users doesn´t know how to input the date and if they don´t fill it project doesn´t create.

Suitecrm Versión 7.5.3 Sugar Versión 6.5.23 (Build 1061)
Tipo de servidor: MySQL
Versión del servidor: 5.6.28 - MySQL Community Server (GPL)
Chrome 49.0.2623.112 m

**Comment by 604MediaDeveloper** [comment]
Please apply the following changes to fix start date issue while creating new project from from Project template.

File Location  : modules\AM_ProjectTemplates\controller.php  
Remove : $dateformat = $current_user->getPreference('datef');
   $startdate = DateTime::createFromFormat($dateformat, $project_start);
   $start = $startdate->format('Y-m-d');

Add : if($project_start!='')
  {
   $dateformat = $current_user->getPreference('datef');
   $startdate = DateTime::createFromFormat($dateformat, $project_start);
   $start = $startdate->format('Y-m-d');
  }

This will allow you to create new project from project template without start date.

**Comment by 604media** [comment]
Can you please provide more details on date format issue. I'm not able to reproduce the date format issue.
