### ISSUE TITLE
DetailView formatting error when single column

### ISSUE THREAD

**Issue by mmcaughan** [salesagility/SuiteCRM#1276]
When all columns have been removed form the right side EditView2.php getPanelWithFillers method inserts a column in the final row to maintain the panel width with other 2 column panels.

The template DetailView.tpl sets the scope="col" on all label columns so this filler cell gets a gray background. The temporary solution for us was to make the DetailView.tpl "smarter".  I'm sure something better can be done like adding metadata elements that specify filler but this was quick and dirty for us.

CODE BEFORE
 `<td width='{{$def.templateMeta.widths[$smarty.foreach.colIteration.index].label}}%' scope="col">
`

CODE AFTER

`{{if $colData.field.name == ''}}`

`<td width='{{$def.templateMeta.widths[$smarty.foreach.colIteration.index].label}}%' scope="none">`

`{{else}}`

`<td width='{{$def.templateMeta.widths[$smarty.foreach.colIteration.index].label}}%' scope="col">`

`{{/if}}`
`

**Comment by Dillon-Brown** [comment]
Unable to replicate on 7.10.2. Please re-open if this is still an issue you can replicate and we will investigate further. Thanks.
