### ISSUE TITLE
Do not run e-mail templates for incoming mail

### ISSUE THREAD

**Issue by Slawka** [salesagility/SuiteCRM#1277]
It does not operate standard templates. SuiteCRM 7.5.3 Released
built-in templates do not work for incoming mail (variables do not apply)

I get to the post office at the institution issues

$acase_name $acase_name (# $acase_case_number)  $acase_date_entered

$acase_status
$acase_case_number
$acase_description

**Comment by samus-aran** [comment]
Hi @Slawka Can you describe the issue abit more clearly?  i.e. a step by step action of what happens.  Thanks

**Comment by willrennie** [comment]
Case email templates can only be utilised/populated when using the automated case functionality within the CRM which generates creation/update emails for cases. They will not work if you are sending an email directly with the email client or with workflow. I would recommend that you post any further questions like this on the SuiteCRM forum: https://suitecrm.com/forum
