### ISSUE TITLE
Data type: Phone - Suggestion

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1285]
In many contacts, accounts, etc. we have more as one or two phone records. This make us problem with exact search if we changed the logic of global search from "something%" to "something" tha means, it must exact macht the record (or  user add % operator for more possibilities) #1284 

![mobile](https://cloud.githubusercontent.com/assets/5773777/14796033/93dc6548-0b2b-11e6-81be-74b305c55664.png)

I want ask if the phone data field can changed and will look similary to email data type.
I explain: user can add or remove additional phone, can choose the primary, oupted out or invalid number

Please let me know your opinion on this suggestion

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data type: Phone - Suggestion](https://trello.com/c/8dGlWJdJ/103-data-type-phone-suggestion)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@samus-aran @PedroErnst @daniel-samson 

We're working on this extension by own.. little showcase how can it looks :)

@horus68 @pgorod please let me know your opinions, if you have time :)

When done.. we provide code :) maybe will used here

![2018-01-24_1428](https://user-images.githubusercontent.com/5773777/35334491-e32d38aa-0112-11e8-8886-6d3c7e0a6cdd.png)

**Comment by horus68** [comment]
Good work, The way it should be now!

**Comment by pgorod** [comment]
Looks like a step forward, but be careful with the implications that this might have. 

For example: 
- will these changes be also for Targets and Leads? 
- if so, check if conversion works correctly
- try to remember minor mechanisms like [this one](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/17375-do-not-update-phone-work-in-contact-editview-while-selecting-account#58556) to make sure you don't break anything...

**Comment by Mausino** [comment]
@pgorod yes,  it is not easy as it looks.. but it is easier do by own as prepare it that it will upgrade save and don't break all intestacies of SuiteCRM 

We started fist on Targets... after testing it.. will move on Leasds, Contacts, Accounts....

We are not transforming fields.. we created new one "Mobile Improved" and trying to copy data from phone, office phone, fax fields.... problem also is that we have so much modifications (like we have mobile 1 and mobile 2 fields) in our SuiteCRM that i must check if this changes is in official SuiteCMR or only in our :D 

Many of our client have more mobiles or phone numbers... and many are outdated... and we can't look still in changelog and look on old data..  phone numbers need new revolution like @salesagility did with emails 🥇
