### ISSUE TITLE
Marker legend overlap Toggle Clustering button

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1288]
Hi, here is screenshot of the issue

![countries](https://cloud.githubusercontent.com/assets/5773777/14823816/2637cbdc-0bd4-11e6-9e92-46ad87b56ae4.png)

I recommend to move the Clustering button next to Remove Button

**Comment by shogunpol** [comment]
The issue has been tested on the current version of SuiteCRM(7.7.4), and not appear.
If you can replicate this issue on recent version of SuiteCRM. If not can you close an issue.
@Mausino , thanks for raise this issue.

**Comment by Mausino** [comment]
@shogunpol i have still same problem after upgrade on 7.7.4 + clustening issue #1288

![maps1](https://cloud.githubusercontent.com/assets/5773777/18627450/35cd6670-7e5b-11e6-9821-d76444e62700.png)

The JJWG Maps doesnt cooperate... If you put there some issue... nobody respond... the project of JJWG is half dead

Here is videoscreen how you can replicate issue http://screencast.com/t/EoXiUaRxb

**Comment by Mausino** [comment]
@Dillon-Brown small issue.. proposed solution.. created pull request.. but it stucks here

Should be assigned pull request merged and should be issue added to next relase :) ?

**Comment by Dillon-Brown** [comment]
@Mausino I think this can be closed, the proposed fix has already been merged here: https://github.com/salesagility/SuiteCRM/pull/5521/files.

Let me know if this is still an issue for you and we can re-open. Thanks!
