### ISSUE TITLE
MySQL 1366 error when save APO_Case_updates

### ISSUE THREAD

**Issue by r3code** [salesagility/SuiteCRM#129]
I often have an error 
```
[FATAL] Error inserting into table: aop_case_updates: 
Query Failed: INSERT INTO aop_case_updates (id,name,date_entered,date_modified,modified_user_id,
created_by,description,deleted,assigned_user_id,case_id,internal)
VALUES ('18148487-72ee-fb6c-eb50-54edd9bf0e8c','Сообщите, удалось ли вам реѮ..',
'2015-02-25 14:19:10','2015-02-25 14:19:10','1','1',
'Сообщите, удалось ли вам решить проблему?',0,'1',
'c69a43f7-4c31-22bc-89fe-54e5ce0bde11',1): 
MySQL error 1366: Incorrect string value: '\xD1...' for column 'name' at row 1
```
It's strange that sometimes adding a symbol to the original Case Update Description removes the error, e.g. a message causes error
```
Сообщите, удалось ли вам решить проблему?
```
and other not!
```
#Сообщите, удалось ли вам решить проблему?
```
The problem in `name` column MYSQL says.
So I've converted a table and name column charset to utf8mb4 following the http://dev.mysql.com/doc/refman/5.5/en/charset-unicode-upgrading.html

_Check again and receive the same error!_

## What next?

Next I dig into CaseUpdatesHook.php and found out that it cuts the `$case_update->name` with `substr`. 
The `substr` and `strlen` is not safe for non latain symols http://stackoverflow.com/questions/12446877/php-is-it-possible-to-correctly-substr-a-utf-8-string

*So we must use `mb_substr` and `mb_strlen`!*
And note about the correct `mb_internal_encoding('utf-8');`.

## What can I do?

1. Fix the code which handles MySql data 
 * replace `substr` calls with `sugar_substr` from `include\utils`.
 * replace `strlen` calls with `sugar_strlen` (example code `n = function_exists('mb_strlen') ? mb_strlen($name) : strlen($name);` see sugar_substr code)
2. Inspect the code for improper use of `strlen` and `substr` in multibyte sensitive code and replace them.

**Comment by r3code** [comment]
The cause is substr itself - it handle 1-byte chars so multi-byte char sometimes spitted into 1 and 1 byte.
In my example above `substr('Сообщите, удалось ли вам решить проблему?', 50)` uses `strlen` and gets length 75 instead of 41, and then cuts first 50 bytes. 
So one of the symbols is splited into two single bytes and we see as the result a corrupted symbol at the end `Сообщите, удалось ли вам реѮ`

**Comment by r3code** [comment]
* To find `strlen` calls use regexp `.*\bstrlen\(.*`
* To find `substr` use  `.*\bsubstr\(.*`

**Comment by shogunpol** [comment]
I did testing, by adding the multiple "Cyrillic" sentences into Case updated Threaded in DetailView, and also in EditView. The Sentences was added with, and without "#" symbol. The "Cyrillic" sentences covers all alphabet symbols. 

Conclusion: In current version of SuiteCRM, error not appear, so bug doesn't exist anymore.

**Comment by r3code** [comment]
I've checked it here http://demo.suiteondemand.com/index.php?module=Cases&action=DetailView&record=14b0f838-2bce-0d57-699e-57add5b2ac27
Works fine!
