### ISSUE TITLE
Suite 7.6rc notification module error upon upgrade

### ISSUE THREAD

**Issue by tdseward** [salesagility/SuiteCRM#1298]
Receiving a Fatal error when upgrading to 7.6rc on dev install with the notification module enabled.

Fatal error: Call to undefined method Basic::Basic() in /home/tdseward/public_html/dev/rp/modules/bc_Notification/bc_Notification_sugar.php on line 70

extension mondule provided by store.biztechconsultancy.com/sugarcrm-desktop-notification-plugin.htm

**Comment by mattlorimer** [comment]
fixed in final release
