### ISSUE TITLE
Use mb_strings everywhere to avoid multi-byte characters issues

### ISSUE THREAD

**Issue by r3code** [salesagility/SuiteCRM#130]
Currently the code in some places use mb_strlen without a check `function_exists('mb_strlen')` and other parts uses strlen. 
So some modules fail to handle  multi-byte characters strings because of `strlen` and `substr`. Often symptom is MySql error 1366 on insert.

_I suggest to use mb_strings everywhere in the code that prepares strings for the inserting to the database to avoid multi-byte characters issues._

**Comment by r3code** [comment]
Changes title error

**Comment by JimMackin** [comment]
It's probably worth creating `suite_strlen`, `suite_substr`, e.t.c. functions which check for the appropriate mb function and fall back if it doesn't exist.

**Comment by simbanic** [comment]
+

**Comment by r3code** [comment]
@JimMackin +1
1) Also we have to update the installer to notify user during installation about the limitation and possible issues if mb_ functions not available.
2) I don't remember if SuiteCRM has a tool in the backend to show matching between required and actual parameters (php version required, MySQL, mb_strings, etc.) It would be great to have such tool to do the debug process  easier .

**Comment by paulgodley** [comment]
Going forward, would it be worth using the PHP [function overloading](http://php.net/manual/en/mbstring.overload.php) to allow for the multi-byte equivalents to be called when available?

**Comment by JimMackin** [comment]
Good catch Paul, though this would rely on users php.ini being setup correctly which wont always be the case. Because this is a global change also it means there would be no way to use the vanilla strlen if it was needed.

**Comment by samus-aran** [comment]
Hi @r3code Would be great to get examples of these failures to assess how deep and frequent this goes.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use mb_strings everywhere to avoid multi-byte characters issues](https://trello.com/c/bF9XhYsX/163-use-mb-strings-everywhere-to-avoid-multi-byte-characters-issues)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by r3code** [comment]
@samus-aran Test Case 1: create an Accont named "Фирма Юла", enable Full-Text search, Rebuild Search Index, Try to search. 
Create a new Case and try add the text "Когда я был молодым и красивым женщины очень любили меня, а я очень любил их. Я тратил на них все, что зарабатывал и не жалею об этом. Я встретил ту единственную с которой я по сей день." It will fail to add, because of strlen() and pos() counts chars invalid suggesting 1 byte per symbol.
