### ISSUE TITLE
Empty Favorite

### ISSUE THREAD

**Issue by MarathonMax** [salesagility/SuiteCRM#1301]
I do not know what I have done to get this but I now have an empty report as a favorite. Editing it (by clicking the Pencil icon next to the entry in Favorites on the bottom left) brings an empty Create Report page. I ran a Quick Repair and Rebuild to no avail. Running "SuiteCRM Version 7.5.3 Sugar Version 6.5.23 (Build 1061)"

**Comment by pgorod** [comment]
I had the same problem as you and solved it by deleting the row from the database directly (the table is called `favorites`). You can do this easily if you have MySql access with phpMyAdmin (or equivalent).

Still, that is just a workaround, so it would be nice to have a proper way for any end-user to clear this kind of left-over favorites...

If you go into the database to delete the row, please leave a note here with the contents you find there, before you delete it. That will surely help debugging this issue.

**Comment by vladbar** [comment]
Hello MarathonMax,

I've tried to replicate this issue, but was unable achieve the same result.

When you see this empty report as a favourite, could you check its change log ?

**Comment by MarathonMax** [comment]
Hey vlad, can not see the change log. From the favorites bar (bottom left), when I click on the edit pencil, it brings me to the create report page, when I click in the report icon it brings an empty page (no edit button on the top left).

**Comment by Mausino** [comment]
Some update here? It is very annoying problem... becausue if you delete the favorite record, you are still see this record in dashboard or in sidebar....  

![favorites](https://cloud.githubusercontent.com/assets/5773777/17735158/174c33c8-6481-11e6-9117-d774ca93f899.png)

**Comment by bekann** [comment]
This bug can be closed. It was fixed and released within 7.7.8. 
If anyone is interested here's the commit which solved the issue **SHA: 2ac97abe0c5e391a14f0016bdcd3022d3eb303be**
