### ISSUE TITLE
JotPad dashlet doesn't save text when line break is added

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1302]
Possibly related to this issue:
https://github.com/salesagility/SuiteCRM/issues/786
... which is supposed to be resolved in 7.5.x., but I'm getting this behavior in version 7.5.3., possibly it's a different thing.

Since I didn't get any response in my comments there, and I don't know if there is anybody hearing that conversation on a closed issue, I'm assuming the correct thing is to open a new issue (but correct me if I'm wrong).

The JotPad dashlet will save the text typed into it as long as there aren't any line breaks (even if the paragraph spans several lines). But as soon as the first carriage return character is inserted, when exiting the edit mode the text will disappear and be lost.

(A different issue, not to be confused with this one, is if all text is lost but you are seeing "$defaultText" shown on your JotPad; that is a bug with translation files coming from Crowdin platform; already solved in the latest builds).

**Comment by 604media** [comment]
Please see the below pull request to fix this issue
#1322

**Comment by pgorod** [comment]
I confirm the fix works on my system.

Maybe this issue would benefit from being tagged "**Fix proposed**" and "**High priority**". If https://github.com/salesagility/SuiteCRM/issues/786 was "High Priority", then this problem with the same consequences should also be.

This is very visible, affects end-users directly, and is a bit treacherous: you paste some phone number onto the JotPad and trust that it's going to be there a minute later - but it can disappear for ever.

If you take that past issue, the current issue, and the translation code bug I mentioned above, the amount of people out there that are exposed to malfunctional JotPads is probably huge. It would be a pity if this would be forgotten here on Github and didn't make it into a release ASAP, imho.

Thanks to everyone involved.

**Comment by samus-aran** [comment]
Thanks for your contribution @pgorod. We are aware of this fix and I have stated that this PR will be looked at for the next release.  With regards to setting labels, we agreed there needs to be way to easily define what is 'high priority' etc and we are currently looking into how to do this in our github process.  The aim is to allow you guys to be involved (contributors and commentors) and identify what you feel is a more widely affecting bug and thus be a focus to resolve for future releases.

**Comment by pgorod** [comment]
Thank you @samus-aran. I agree that finding ways of letting more people contribute is definitely important for this project, it's a big project with a big audience, it naturally puts too much pressure on SalesAgility people, and you can't possibly handle everything: bugs, new features, support on forums, documentation...
I'm afraid I can't contribute any specific proposals now, since I am still learning my way around GitHub. What I can tell you is that any input from SalesAgility personnel is highly valued: however simple it is, it shows attention is being payed by the people running the show. 
Even if it is just a label, or an assignment to somebody, or even one of those "add your reaction" that you can use on comments. I don't expect you to send "hearts" out to everybody but a "+1" sometimes could be enough : - ) . Thanks.

**Comment by pgorod** [comment]
@samus-aran off-topic, but I didn't know where else to post this: remember to also update this page on the wiki after each release:
https://suitecrm.com/wiki/index.php/Versions
Also the "News" section would need update announcing the new version. But I'm not sure that is worth the trouble. On the other hand, then we could question what that entire section is doing there... Thanks.

**Comment by samus-aran** [comment]
@pgorod I'm assuming it was yourself that updated the last versions - thanks for pointing that out to me.  This will be noted the next time. :+1:

**Comment by pgorod** [comment]
@samus-aran Yes, that was me. BTW, it just occurred to me that this page here is even more important:
https://suitecrm.com/wiki/index.php/Compatibility_Matrix
People keep asking in the forums about PHP versions etc.

**Comment by samus-aran** [comment]
Thanks @pgorod - We are currently reviewing how we can improve processes in a number of areas and certainly the Wiki is one of them.  I'll raise this internally and see the best way to maintain a consistent update of the wiki and other aspects of the releases.  Feel free to message me on the forums if you have anything else to add/or spot regarding updating other areas.

**Comment by pgorod** [comment]
@samus-aran Ok, I do have a few more ideas. Exactly how am I supposed to message you on the forums, there isn't any private message (or mention) feature there? 

Or do you mean just post something on a new thread and trust that you will see it?

**Comment by samus-aran** [comment]
@pgorod You can send me an email (which is on my profile on the forums) or via twitter (MiniRidley) :+1:

**Comment by pgorod** [comment]
@samus-aran sorry, you must have your email set as private in the forums, it's not showing (at least I can't find it). https://suitecrm.com/forum/profile/32053-samus-aran
I don't use Twitter...
Anyway, I think the kinds of suggestions I have will actually be better in public, so I will post in the forums.
Other things related to the wiki I think I will simply edit things there, I suppose you or somebody is keeping an eye there. BTW, I won't mind if you revert any of my edits, I'll suppose there is good reason for it. Wikis work better when people don't think too much before editing, and don't get offended when reverted or corrected.
