### ISSUE TITLE
7.6 In reports conditions for date not working properly

### ISSUE THREAD

**Issue by Tetryt** [salesagility/SuiteCRM#1307]
When selecting a date range like:

![crm_date_range](https://cloud.githubusercontent.com/assets/18421032/14913835/23db4d62-0e06-11e6-84ed-17e394c68e7f.png)

the results do not comply with the set range

![crm_date_range_result](https://cloud.githubusercontent.com/assets/18421032/14913753/82caf986-0e05-11e6-8c51-bc2d63f1204a.png)

When using each of these ranges separately they work fine. It looks like the AND operator brakes something. Worked fine in 7.5.3

-Marcin

**Comment by mdemaree99** [comment]
Output itself should not have the time associated with the results.
Fields are DATE    vs     DATETIME.

https://github.com/salesagility/SuiteCRM/issues/2084

**Comment by shogunpol** [comment]
@mmadey , the issue has been tested in recent version of SuiteCRM(7.7.6) , and it not appear.
Can you confirm is not issue any more, if yes can you close an issue?
Thanks for your contribution.

**Comment by mdemaree99** [comment]
@shogunpol   I updated to the latest version and still see the issue.
Does not grab users default format for report.


![dateissue](https://cloud.githubusercontent.com/assets/3958770/19652727/87666896-99d7-11e6-9ef4-511bdbc696ac.PNG)

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
