### ISSUE TITLE
AOR Reports wont generate a PDF or CSV when a date parameter is selected

### ISSUE THREAD

**Issue by emcrobert** [salesagility/SuiteCRM#1309]
If you have a date condition on a report and check the parameter checkbox then you get an SQL error when you try to view the report as a PDF OR CSV.

Below is an example I encountered on an opportunities report
 `opportunities`.date_entered = DATE_ADD(opportunities., INTERVAL   )

If you uncheck the parameter checkbox the same report exports without any issues.

This issue exists in 7.5.1 and 7.6. Not tested any other versions.

**Comment by Glen206** [comment]
I confirmed this bug in 7.6.2 when using the companies module in the reports. I have 2 date condition fields and when the parameters are selected, you can run a report but cannot export into CSV or PDF.

Running on LAMP

**Comment by cjmny** [comment]
This is still happening in 7.6.3.

**Comment by cjmny** [comment]
I'm sure you are aware, but this is still occurring in 7.6.4.

**Comment by cjmny** [comment]
This is still occurring in 7.7 Beta 1.

**Comment by cjmny** [comment]
Issue is still present in 7.7 RC

**Comment by Dillon-Brown** [comment]
Fixed here: #4062
