### ISSUE TITLE
Campaigns - Stage 3 - Unable to Save Template Creation 

### ISSUE THREAD

**Issue by gregsoper** [salesagility/SuiteCRM#1310]
This MUST have an option to Save the Template. 
The menu options should be Back, Cancel, Save, Next

Back - back one step
Cancel - cancel with warning if unsaved information
Save - Save template and stay on page
Next - Save Template and go to next stage

**Comment by willrennie** [comment]
@gregsoper can you confirm this has been resolved? From what I can see, the Back button you requested is missing from this step but the template can be saved.

**Comment by willrennie** [comment]
Closing as this issue has been resolved and templates can be selected, edited, created and saved within the campaign wizard.
