### ISSUE TITLE
Issue with report conditions

### ISSUE THREAD

**Issue by rouhu** [salesagility/SuiteCRM#1315]
This issue was detected in 7.5.3.
![report_issue](https://cloud.githubusercontent.com/assets/6568669/14940617/a902a594-0f7d-11e6-8a45-c43e3ece051e.jpg)
The report field condition value cannot be entered if the condition goes 3 levels down the path.

**Comment by virtualme123** [comment]
I think I have a similar issue but it isn't just three levels down my example below demonstrates it:

![crm-aor](https://cloud.githubusercontent.com/assets/17426483/18746510/c440d3ea-80bf-11e6-9ed3-a7ff1330bd34.png)

**Comment by shogunpol** [comment]
@rouhu ,may i ask about more details about an issue, for example:
- Do you created custom module? (first screen),
- What exact value you expect in 3rd row,
Thanks for your contribution.

**Comment by stenfalp** [comment]
Just updated to 7.7.8 but the problem is still present. It is not dependent from the field position.
![cattura](https://cloud.githubusercontent.com/assets/22146544/20426261/9d23f6a2-ad7e-11e6-9aea-b0a79010d16c.PNG)

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.10.x. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
