### ISSUE TITLE
Email module subpanels - duplicate folders

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1318]
Is this correct that in modules/Emails there is a folder "subpanels" under "metadata", ie. where it sould be  and there is another "subpanels" folder in the root of the module: modules/Emails/subpanels

**Comment by shogunpol** [comment]
@horus68  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
