### ISSUE TITLE
2 duplicate files when unzipping 7.6 and 7.6.1

### ISSUE THREAD

**Issue by RichardLukins** [salesagility/SuiteCRM#1319]
Hi 
when unzipping the install files, there are 2 duplicate files within the zip, both in target directory "\themes\default\images"
- icon_jjwg_Maps.gif
- icon_jjwg_Maps.png
  both files (for each duplication) appear to be the same size and same content/image, but clearly this leads to warnings and checks that can be avoided.
  Thanks
  Richard

**Comment by RichardLukins** [comment]
This issue remains in the latest V7.7 download, and upgrade 7.6 to 7.7
The folder path is: \themes\default\images
The duplication is reported under Windows XP/7/10 using either 7zip or windows built-in archive handler.

I know not a show stopper, but surely a simple thing to remove and avoid a pointless error warning?

These are the sorts of loose ends that put off new users, who expect near seemless installs and upgrades ... 

Any chance of seeing this solved in 7.7.x please?!
Richard

**Comment by horus68** [comment]
Confirmed on Windows systems. 
This is a long time issue!
