### ISSUE TITLE
Basic search does not work with SQL Server

### ISSUE THREAD

**Issue by ParkratPro** [salesagility/SuiteCRM#1325]
Basic search does not work with SQL Server and generates an invalid query. Two things are wrong with the query. The first is a syntactical problem, which throws an error, but even were that to be OK, SOME of the literal strings are delimited with double quotes instead of single quotes. SQL Server's default behavior is treat double quotes as column names. 

This is a problem both in 7.5.3 and 7.6. 

Advanced search works OK. 

```
05/03/16 12:41:46 [2644][54ef04ee-c36d-8681-d31a-572789913830][FATAL]  Query Failed:SELECT TOP 21 * FROM
                                (
                                     SELECT  contacts.id , contacts.assigned_user_id , LTRIM(RTRIM(ISNULL(contacts.first_name,'')+N' '+ISNULL(contacts.last_name,''))) as name, contacts.first_name , contacts.last_name , contacts.salutation  , accounts.name account_name, jtl0.account_id account_id, contacts.title , contacts.phone_work  , jt1.user_name assigned_user_name , jt1.created_by assigned_user_name_owner  , N'Users' assigned_user_name_mod, contacts.date_entered , contacts.created_by  , ROW_NUMBER()
                                    OVER (ORDER BY contacts.date_entered DESC) AS row_number
                                    FROM contacts  LEFT JOIN contacts_cstm ON contacts.id = contacts_cstm.id_c   LEFT JOIN  accounts_contacts jtl0 ON contacts.id=jtl0.contact_id AND jtl0.deleted=0

 LEFT JOIN  accounts accounts ON accounts.id=jtl0.account_id AND accounts.deleted=0
 AND accounts.deleted=0  LEFT JOIN  users jt1 ON contacts.assigned_user_id=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0 where ((contacts.id IN (SELECT favorites.parent_id FROM favorites
			                    WHERE favorites.deleted = 0
			                        and favorites.parent_type = "Contacts"
			                        and favorites.assigned_user_id = "1") OR NOT (0))) AND contacts.deleted=0 
                                ) AS a
                                WHERE row_number > 0::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near ')'.

```

**Comment by chris001** [comment]
It's bugs like this which make you think, maybe there are many more SQL generation bugs, similar to this one, happening on the same or other databases, which have possibly not even been discovered or reported.

Maybe it's time to look at migrating the DBManager class to use a well maintained open source database abstraction layer, for example adoDB, Doctrine DBAL.

https://packagist.org/packages/doctrine/dbal
https://github.com/doctrine/dbal

https://packagist.org/packages/adodb/adodb-php
https://github.com/ADOdb/ADOdb

Opinions?

**Comment by ParkratPro** [comment]
Well, from a relative new perspective, when I chose SuiteCRM, it was because it advertised support for MySQL and SQL Server (I have a legacy system that runs on SS). I don't know how many more DBs you would need to support, but abstraction would likely remove some concerns. A quick look has me favoring ADOdb as at least having good documentation.  BTW, another bug that surfaced in 7.6 was an attempted DB server ping in checkConnection -- that would ping the host server, but not necessarily the host DB server. I had to remove that to even get past the install. Regarding this particular issue, I'm investigating deep in the bowels of SearchForm2.php when I have some spare time trying to find why the query comes back so mangled (is the syntax above valid in MySQL?).

**Comment by chris001** [comment]
@ParkratPro 
If you paste the SQL code 
`SELECT TOP 21 * FROM
                                (
                                     SELECT  contacts.id , contacts.assigned_user_id , LTRIM(RTRIM(ISNULL(contacts.first_name,'')+N' '+ISNULL(contacts.last_name,''))) as name, contacts.first_name , contacts.last_name , contacts.salutation  , accounts.name account_name, jtl0.account_id account_id, contacts.title , contacts.phone_work  , jt1.user_name assigned_user_name , jt1.created_by assigned_user_name_owner  , N'Users' assigned_user_name_mod, contacts.date_entered , contacts.created_by  , ROW_NUMBER()
                                    OVER (ORDER BY contacts.date_entered DESC) AS row_number
                                    FROM contacts  LEFT JOIN contacts_cstm ON contacts.id = contacts_cstm.id_c   LEFT JOIN  accounts_contacts jtl0 ON contacts.id=jtl0.contact_id AND jtl0.deleted=0

 LEFT JOIN  accounts accounts ON accounts.id=jtl0.account_id AND accounts.deleted=0
 AND accounts.deleted=0  LEFT JOIN  users jt1 ON contacts.assigned_user_id=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0 where ((contacts.id IN (SELECT favorites.parent_id FROM favorites
                                WHERE favorites.deleted = 0
                                    and favorites.parent_type = "Contacts"
                                    and favorites.assigned_user_id = "1") OR NOT (0))) AND contacts.deleted=0 
                                ) AS a
                                WHERE row_number > 0`
...into this MySQL syntax checker page...
https://www.piliapp.com/mysql-syntax-check/
It tells you that it's syntax error at line 1, near "SELECT TOP 21* FROM"

This syntax is not supported in MySQL, nor in Oracle.  Yet it is supported in Microsoft SQL Server.
See more details here:
http://www.w3schools.com/sql/sql_top.asp

Yet another reason to let a database abstraction layer, such as adoDB or Doctrine DBAL, deal with generating the proper syntax depending on the database it's talking to, rather than reinventing a database abstraction layer to do the same exact things, talk  in multiple SQL dialects to the top customer requested databases..

**Comment by ParkratPro** [comment]
Yes, the "SELECT TOP xxx" syntax *IS* valid MS SQL Server syntax, but that's not the cause of my problem -- it's the double quotes around string literals, and the "OR NOT (0))" which throws the error "An expression of non-boolean type specified in a context where a condition is expected". If I change the double quotes to single quotes, and delete that clause, the select works as expected. While abstraction will help in the future, it's not getting this bug fixed now. I have still not found exactly where this query is being constructed but, admittedly, I have not spent a great deal of time looking as the workaround of using Advanced Search is appeasing the users (for now).

**Comment by ParkratPro** [comment]
OK, I found the incorrect syntax, and it's in the _module_.searchdefs.php.  I was able to correct the syntax by going into the custom\modules\_module_\metadata\searchdefs.php and changing this code

`  'favorites_only' => 
  array (
    'query_type' => 'format',
    'operator' => 'subquery',
    'subquery' => 'SELECT favorites.parent_id FROM favorites
			                    WHERE favorites.deleted = 0
			                        and favorites.parent_type = "_module_"
			                        and favorites.assigned_user_id = "1") OR NOT ({0}',
`

to this: 

`  'favorites_only' => 
  array (
    'query_type' => 'format',
    'operator' => 'subquery',
    'subquery' => 'SELECT favorites.parent_id FROM favorites
			                    WHERE favorites.deleted = 0
			                        and favorites.parent_type = \'_module_\'
			                        and favorites.assigned_user_id = \'1\' ',
`

Oh, and I just saw a resolution for this issue posted as I was writing this. I'll refrain from going into all the modules and correcting this for now. Does the fact that these are in the custom module, mean they won't be automatically corrected when I update? (I use the maps modules which altered all the vardefs for almost all the modules).

**Comment by ParkratPro** [comment]
Reviewing the fixes, I'm still perplexed as to what the `OR NOT ({0}` is supposed to do? Still syntactically incorrect for SQL Server. Also, the single quotes had to be escaped in my custom searchdefs.php.

**Comment by ParkratPro** [comment]
The fixes to the module name and user id did work, but I verified that the `OR NOT ({0}` clause doesn't work with SQL Server (I'm using 2012, but also tried 2008 compatibility mode). This minor change does work for both SQL Server 2008, 2012 and MySQL 5.1.63: 
`OR NOT (1={0}` 
(and I did realize what the clause is for -- to return all records when "My Favorites" is not checked)

Also, and **please tell me if I should open a separate bug for this**, the SearchFields.php that gets generated in custom\modules\ _module_ \metadata has the module name and the assigned_user_id set as string literals. The user id is set to the userid that did the rebuild (in my case the admin, or "1") as in this example from Accounts (shown with the non-functioning double-quote syntax): 

`  'favorites_only' => 
  array (
    'query_type' => 'format',
    'operator' => 'subquery',
    'subquery' => 'SELECT favorites.parent_id FROM favorites
			                    WHERE favorites.deleted = 0
			                        and favorites.parent_type = "Accounts"
			                        and favorites.assigned_user_id = "1") OR NOT ({0}',
`

All other users were getting the admin's accounts and not their own. 

Being new to this system, but also having spent some time debugging SearchForm and SearchForm2, perhaps "favorites" should be handled in SearchForm/2 just as "my items" and "closed items" are, rather than as a subquery in SearchFields that gets mangled on a rebuild. (or perhaps there's some way to avoid having putting in parameters as literals. 

Thanks for all your efforts on this. At least now I've got Basic Search back.
