### ISSUE TITLE
Print page - link issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1338]
Hi, i want print page via ctrl+P but instead names of links show me their related urls + subpanels are not responsible

SuiteCRM 7.5.3 + same issue after upgrade on 7.6.1

![print_crm](https://cloud.githubusercontent.com/assets/5773777/15017676/d49e2034-1216-11e6-9ea5-1b05f4b69b1c.png)

**Comment by irgreeny** [comment]
7.7.4 - Suite R theme - same issue

**Comment by mrbarletta** [comment]
7.7.6 Suite P Theme is happening too.

**Comment by cumanacr** [comment]
Listviews on SuiteCRM 7.7.7 SuiteP theme have the same issue.

Sample PDF uploaded:

[Accounts » SuiteCRM.pdf](https://github.com/salesagility/SuiteCRM/files/590372/Accounts.SuiteCRM.pdf)

**Comment by SpudR** [comment]
Can this please be looked at and priority raised please?
It's causing some issues in my business now...

Thanks :)

**Comment by edilex** [comment]
Can this please be adressed ? Causing issues in my company. Thanks.

**Comment by mbates14** [comment]
I just tried the fixed CSS files, still does the same thing!
