### ISSUE TITLE
Upgrade 7.1.1 to .7.2 HTTP 500 error

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#134]
Use the Admin page, Upgrade Wizard, upgraded an existing, running 7.1.1  with the 7.2 upgrade package.

At the final step 5, upon clicking the Next button, the browser shows 500 Internal Server Error.
 
Here is the log entries:

     Mon Mar  2 18:06:40 2015 [28253][1][FATAL] createRelationshipMeta: Metadata for table  does not exist
     Mon Mar  2 18:06:40 2015 [28253][1][FATAL] createRelationshipMeta: Metadata for table  does not exist
     Mon Mar  2 18:06:48 2015 [28253][1][FATAL] createRelationshipMeta: Metadata for table  does not exist
     Mon Mar  2 18:06:48 2015 [28253][1][FATAL] createRelationshipMeta: Metadata for table  does not exist
     Mon Mar  2 18:06:52 2015 [28253][1][FATAL] Unable to place hover field link on metadata for module Users
     Mon Mar  2 18:23:30 2015 [28253][1][FATAL]  Query Failed:  ALTER TABLE aor_fields CHANGE function field_function VARCHAR( 100 ): MySQL error 1054: Unknown column 'function' in 'aor_fields'

Any suggestion.  Has anyone else seen this error.

**Comment by mattlorimer** [comment]
have you check your php logs?

**Comment by chris001** [comment]
Yes, checked the php logs, there is no PHP being logged.
I checked the Apache logs, found the error there, and found the cause.
The server control panel (Virtualmin) threw the HTTP 500 error because it detected you had added a deprecated, security risky, option to the .htaccess.
There is a better more recommended option to add to .htaccess.
Creating a pull request....

**Comment by willrennie** [comment]
The AOR error is just a check, to ensure if the field needs to be updated(if it was a keyword) it will do so. I tested upgrading 7.1.1 to 7.2.1 today. If the upgrade white screens, simply refresh the upgrade page and the upgrade will complete. If you have further issues/errors, please update.
