### ISSUE TITLE
Web installer not working!?

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1345]
On branch master or devel the web installer reports 'Cannot load DB manager'
whilst using the same credentials in config_si.php and launching tests/testinstall.php I can install without any problem

**Comment by shogunpol** [comment]
@adamjakab , I tested raised issue on recent version if SuiteCRM(7.7.1), and issue doesn't appear. 
Can you confirm this is not now an issue?

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this issue is still seen we can reopen this with more information. 
Thanks.
