### ISSUE TITLE
migration errors from version 7.1.5

### ISSUE THREAD

**Issue by cmarrero** [salesagility/SuiteCRM#135]
Hi, 

I'm migrating from version 7.1.5 and have found three errors:

- Can't use the report module. From the log file:
Mon Mar  2 18:21:04 2015 [8041][1][FATAL]  Query Failed:  ALTER TABLE aor_fields CHANGE function field_function VARCHAR( 100 ): MySQL error 1054: Unknown column 'function' in 'aor_fields' 

This is reported too in #134 

In other test after open Reports module said this :

Warning: require_once(modules/AOR_Reports/aor_utils.php): failed to open stream: No such file or directory in /home/danielgd2584/webapps/suitecrm_gonm/modules/AOR_Reports/controller.php on line 27

Fatal error: require_once(): Failed opening required 'modules/AOR_Reports/aor_utils.php' (include_path='/home/danielgd2584/webapps/suitecrm_gonm/include/HTMLPurifier/standalone:/home/danielgd2584/webapps/suitecrm_gonm/include/..:.:/usr/local/share/pear55') in /home/danielgd2584/webapps/suitecrm_gonm/modules/AOR_Reports/controller.php on line 27

------------------------------------------------------------------------------------------------------------------------------
- After install if I do a quick repair says:

Differences found between database and vardefs
/* Table : cases */
/*COLUMNS*/
/*MISSING IN DATABASE - contact_created_by_id -  ROW*/
/* INDEXES */
ALTER TABLE cases   add COLUMN contact_created_by_id char(36)  NULL ;
 
------------------------------------------------------------------------------------------------------------------------------

 - Cant switch themes, even if i disable the classic one still appearing and only change the login page

Regards

**Comment by mattlorimer** [comment]
Thanks for highligting these issue, there was an issue with the installer removing aor_utils after install, so we have re-issued the upgrade pack to correct this, 

are you switching theme in your user profile?

**Comment by cmarrero** [comment]
hi

If i disable the Suite 7 theme and stablish Suite R as default the user only see de Suite 7 theme.

There ir a option to change all the users theme?

regards

**Comment by mattlorimer** [comment]
not currently  but here does seem to be an issue that disabled theme, just continue to work if that is your current theme
