### ISSUE TITLE
Workflow Module Inline Edit for Actions

### ISSUE THREAD

**Issue by kyriakoy** [salesagility/SuiteCRM#1350]
Trying to inline edit the fields at actions sub panel on Detail view.
Fields and values are randonly missing from all the actions

This is happen when more than one actions exists. I cannot reproduce it with one action only

Version 7.5.3 and 7.6.1 (ubuntu 14.04)

**Comment by kyriakoy** [comment]
The same apply also to inline editing for multiple conditions at report module.
It produce an 403 error for URLs belong to randomly selected fields (insected using firebug)

**Comment by kyriakoy** [comment]
Fixed!
Because of incorect configuration of mod evasive security module for apache 
http://www.techtutorials.net/articles/introduction_to_apache_mod_evasive.html

**Comment by samus-aran** [comment]
Thanks @kyriakoy for providing a fix for those who may have this similar problem.
