### ISSUE TITLE
AOR: Reports with multiple conditions don't work

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1356]
I have create a report with 2 conditions in version 7.6.1. Only the first condition will apply.

Example:
Accounts Name starts with "a"
AND Accounts Billing State equal to "ca"

Checked on your demo site http://sdemo.suiteondemand.com:
Accounts with Billng State "ny" will also be listed.

-- Andreas

**Comment by medaidservices** [comment]
I have the same problem too.

Also, the "One of" type returns zero results, although there are records in the database which should be returned (and did before upgrading).

**Comment by cjmny** [comment]
Experiencing the same issue here.  We have many reports with multi level conditions that are just not showing correct results.

**Comment by jason-huett** [comment]
Same issue with multiple conditions and with use of "One Of" lists... no results.

**Comment by medaidservices** [comment]
I believe this has been fixed in release 7.6.2. https://suitecrm.com/wiki/index.php/Release_notes_7.6.2#SuiteCRM_7.6.2
See #1320  and #1332

**Comment by willrennie** [comment]
Tested and confirmed as working in the latest 7.6 and 7.7 releases.

**Comment by fedo911** [comment]
This issue is still not fixed in 7.8.1, see details in [https://github.com/salesagility/SuiteCRM/issues/3167](#3167).

**Comment by belchfireid** [comment]
"one of" bug is not fixed in 7.10.7.

**Comment by belchfireid** [comment]
Multiple conditions seems to work in 7.10.7.  Perhaps this should be split into two bugs.
