### ISSUE TITLE
Upgrade to 7.6.1 fails with MS SQL database due to dbmanager.php 

### ISSUE THREAD

**Issue by csomers** [salesagility/SuiteCRM#1357]
Looks like there is an issue with the additions from commit f970ddf850100daed8c4ea1dcc1390bcf2f59a2d which adds a $this->database->ping(); to include/database/DBManager.php which doesn't work with MS SQL. 

If I comment out the line in the upgrade zip file and then upgrade, it goes through correctly.

**Comment by adminibt** [comment]
The problem with the ping should not be specific to MS SQL. I'm using MYSQL under Unix and I have the same problem. In my environment a normal ping does not work and there are quite a few common environments where a ping does not work.

A bit funny is the situation during an installation: You enter all the params for the database and admin setting. Then hit "Next" and the installer will not continue - no problems will be mentioned. The database connection is ok but the following ping fails!

If possible please remove the ping.

**Comment by csomers** [comment]
As far as I know this is not a standard 'ping' but a mysql specific function that checks for an open database connection.

**Comment by csomers** [comment]
Looks like this was fixed in https://github.com/salesagility/SuiteCRM/commit/ff24a46ddc598a840b74fdc385fcc7564c923c77
