### ISSUE TITLE
E-Mail action from the list view does not work

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#1360]
Selection "E-Mail" from the action menu doesn't seem to do anything.  Tried from Accounts and Prospects.  Doesn't seem to generate anything in the error logs either. Tested with single selection and multiple selections.

**Comment by samus-aran** [comment]
@cjmny Thank for raising this. I believe this has already been raised.  Please see this issue #1136.  There is also a proposed fix here if you would like to test it out:https://github.com/salesagility/SuiteCRM/pull/1168

**Comment by cjmny** [comment]
Thanks for the update.  Not sure if I should open another issue for this, but with the fix in place the email sends, but it doesn't include any of the variables in the templates (e.g. Instead of "John", the email is addressed to "prospect_first_name").

**Comment by samus-aran** [comment]
Hi @cjmny Yes I would ask you raise it as an issue and refer to the fix ( in the pull request) and we can assign it out.
