### ISSUE TITLE
Events in 7.6.1: Delegates panel doesn't show up

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1362]
The delegates panel will not be displayed after creating a new event. Furthermore, after choosing "Event" and the the created event an error box pops up with:

An error has occurred:
There was an error processing your request, please try again at a later time

Checked this on your test webpage.

In versioon 7.4.3 this worked.

**Comment by adminibt** [comment]
Benoit from the SuiteCRM forum suggested this:

Remove
array('widget_class' => 'SubPanelTopButton_c'),
in modules/FP_events/metadata/subpaneldefs.php

Worked for me.

Any chance this will go in?

**Comment by adminibt** [comment]
Rechecked this (Remove array('widget_class' => 'SubPanelTopButton_c')) in 7.6.3:

The panel showes up - but it is not possible to change the "Status" and "Accept Status". So removing this is not the fix.

-- Andreas

**Comment by willrennie** [comment]
This has been fixed and merged into the hotfix branch, so will be available in the next bug fix release or major release if there is no bug-fix release before SuiteCRM 7.7. See pull request #1531  for the code fix and more information.

**Comment by willrennie** [comment]
This has been fixed in 7.6 and 7.7 releases.
