### ISSUE TITLE
wysiwyg editor is missing

### ISSUE THREAD

**Issue by rasheid** [salesagility/SuiteCRM#1372]
- When i try to create a email template the wysiwyg editor for the body section is missing.
- When I try create a pdf template using the **top right create button** in the pdf template page the wysiwyg editor is missing, only a text field is there in this instance. but If i use the **create pdf template** link located on the shortcut panel on the left, the wysiwyg editor shows.

SuiteCRM Version 7.6.2
Sugar Version 6.5.23 (Build 1061)

Apache version: Apache/2.2.27
PHP version: 5.6.14 
MySQL version: 5.1.73

**Comment by samus-aran** [comment]
Hi @rasheid, The WYSIWYG has been replaced with a drag and drop sectioned functionality (the same as the updated Campaign Wizard Template editor).  Are you able to attach a screenshot and what browser you are currently using.

Thanks

**Comment by rasheid** [comment]
It was actually a permission issue As suggested by someone in another forum: https://suitecrm.com/forum/suitecrm-7-0-discussion/9258-missing-wysiwyg-editor-for-creating-email-templates

**Comment by samus-aran** [comment]
@rasheid Thanks for that!
