### ISSUE TITLE
Is this debug code?

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1380]
https://github.com/salesagility/SuiteCRM/blob/master/modules/EmailMan/EmailMan.php#L934
and
https://github.com/salesagility/SuiteCRM/blob/master/modules/InboundEmail/InboundEmail.php#L1986

**Comment by samus-aran** [comment]
@adamjakab 

Looks to be - its been existing from SugarCRM

https://github.com/sugarcrm/sugarcrm_dev/blob/master/modules/EmailMan/EmailMan.php#L916
and
https://github.com/sugarcrm/sugarcrm_dev/blob/master/modules/InboundEmail/InboundEmail.php#L1981

**Comment by adamjakab** [comment]
if we remove them and modify this test with [progress_bar_utilsTest](https://gist.github.com/adamjakab/84652e4ae55ba0f1bb8f57a742972566) we can have phpunit tests running without garbage output - I have PR'd this one once but it got lost on the way

**Comment by adamjakab** [comment]
hi @mattlorimer , I think you were looking for this - in some post we have exchanged you were asking in which PR this was done - well, I don't remember but I saw yesterday that the mods I have done to [progress_bar_utils.php](https://github.com/salesagility/SuiteCRM/blob/master/include/utils/progress_bar_utils.php) - where I have added the $flush parameter to each function with default value 'true' so the original functionality is preserved has been merged. 
Now, the tests can call these functions with $flush=false parameter as you can see on the gist i linked above.
If you pull that one in and remove the above mentioned echo lines (they were only for temporary debugging forgotten there) we can run the tests without garbage

**Comment by mattlorimer** [comment]
@adamjakab it works, good find.
