### ISSUE TITLE
AOR Reports Value Type "Date" Changes?

### ISSUE THREAD

**Issue by Glen206** [salesagility/SuiteCRM#1383]
I have a report with 2 date created fields as parameters.
The purpose of having 2 date created fields is so that can create a report with "Is Between" similar to advanced search option in list view of modules.

Below are my parameter settings:

1) Company / Date Created / Greater Than or Equal to / value / Date
2) Company / Date Created / Less Than or Equal to / value / Date

The report works, however when I hit the "update" button and the screen refreshes the date values are automatically reduced by one day. 

For example: 
if I select the 1st and 2nd dates as follows 1) = 03/31/2016 & 2) = 05/01/2016, When I select the "update" Button the dates will automatically adjust to) = 03/30/2016 & 2) = 04/30/2016. Every consecutive selection of the "update" button results in the date values being reduced by 1 day.

Running 7.6.2 on LAMP

**Comment by shogunpol** [comment]
This issue is does not appear in recent version of SuiteCRM(7.7.1),
@Glen206 , can you confirm is issue does not exist in recent version of SuiteCRM?

**Comment by Glen206** [comment]
This is no longer happening with 7.7.1

**Comment by ijdavie** [comment]
Hi @Glen206, 

Thank you for coming back to us with this. I will close this now.
