### ISSUE TITLE
SuiteCRM 7.2 Compatibility Issues with PHP 5.2

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#139]
Installation fails with error: unexpected T_FUNCTION.

Installation succeds in PHP 5.3 onwards.

See topic: https://suitecrm.com/forum/installation-upgrade-help/3800-suitecrm-7-2-requirements-compatibility-matrix#14912

**Comment by mattlorimer** [comment]
SuiteCRM 7.2 requires php 5.3+
