### ISSUE TITLE
AOR Conditions from custom fields from a related module do not work

### ISSUE THREAD

**Issue by japio** [salesagility/SuiteCRM#1396]
By selecting any of the custom fields from the Accounts module as a condition in a report on Contacts does fail. Not a single record is reported.
I have this only tested this with a roprt on Contacts and Accounts conditions. Conditions from from standard fields work fine.

Thanks,

Jaap

**Comment by shogunpol** [comment]
@japio , The bug been replicated in recent version of SuiteCRM(7.7.1).
Thanks for raise this issue, we are work on solution.

**Comment by shogunpol** [comment]
Changes from commit"83ca7a1", created by: @604media , has been implemented to recent version of suiteCRM(7.7.8).
Thanks for your contribution.
