### ISSUE TITLE
error in IT translation

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1397]
pls have this checked:

include/language/it_IT.lang.php

'sales_probability_dom' => // keys must be the same as sales_stage_dom
    array(
        'Prospecting' => '10',
        'Qualification' => '20',
        'Needs Analysis' => '25',
        'Value Proposition' => 'Ogni 30 minuti',
        'Id. Decision Makers' => '40',
        'Perception Analysis' => '50',
        'Proposal/Price Quote' => '65',
        'Negotiation/Review' => '80',
        'Closed Won' => '100',
        'Closed Lost' => '0',
    ),

at key 'Value Proposition' we should have '30' but it says: every 30 minutes - clearly wrong and when passed into fixUpFormatting() it will Zero it because it expects int

**Comment by horus68** [comment]
Fixes can be submitted directly on Crowdin translation project.

I already fixed here https://crowdin.com/project/suitecrmtranslations/

**Comment by ijdavie** [comment]
As @horus68 has fixed this as part of the SuiteCRMtranslations project on Crowdin.com I will close this issue.
