### ISSUE TITLE
Module install error on unchmodabble filesystems

### ISSUE THREAD

**Issue by antonioribeiro** [salesagility/SuiteCRM#1406]
When you are on an hybrid filesystem, for instance, a Windows NTFS mounted on a Linux host, your filesystem may not be chmoddable, but the folder may be still writable. The result will the known error message while trying to install a module: 

```
Specified directory '' for zip file 'file.zip' extraction does not exist.
```

**Comment by pgorod** [comment]
:+1: +1 for the concept of _unchmoddability_ of a file system... : - )
