### ISSUE TITLE
"My Activity Stream" dashlet: new "Created by" column empty

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1420]
At some point after 7.4.3 a new column was introduced in the dashlet. You can see screenshots in the forum discussion of this issue: 
https://suitecrm.com/forum/suitecrm-7-0-discussion/9206-does-this-my-activity-stream-layout-look-good-to-you
This column is always empty and I believe it shouldn't be there because the creator of each row is already mentioned in the main column (e.g. "admin created a new lead...").

If there is a reason for this, I'm all ears. I tried asking in the forums first... : - )

If there isn't, then this can easily be fixed by going into file `modules/SugarFeed/metadata/dashletviewdefs.php`
https://github.com/salesagility/SuiteCRM/blob/master/modules/SugarFeed/metadata/dashletviewdefs.php
and commenting out that `created_by_name` item in the columns array.

**Comment by paulgodley** [comment]
Hi @pgorod, thank you for this.  I will get this sorted as soon as possible.
