### ISSUE TITLE
Person form not passing dropdown custom field

### ISSUE THREAD

**Issue by ishanloya** [salesagility/SuiteCRM#1431]
I have a dropdown custom field that doesn't populate when the person form is submitted. It was working earlier. Regular fields (name, email, etc.) are being passed fine.

**Comment by ishanloya** [comment]
Tried with v7.6.2 and 7.6.3. The field and the dropdown list were both created in the Studio and I have the permissions set to the values in the installation guide.

**Comment by ulslope** [comment]
I found a added customer checkbox field works as do text fields or an existing drop down field. I tried the fix by make changes to the two files. Did a quick rebuild but still not working. How did you get this change to work?

Thanks
