### ISSUE TITLE
Add Create Task Radio Button in Calendar Module

### ISSUE THREAD

**Issue by psatasiya** [salesagility/SuiteCRM#1432]
Hi,
When I want to add any activity(like Task,Meeting or Call) in calendar module,When I click on any time period then quick create popup is displays and it is showing two radio button "Schedule Meeting" and "Log Call" but it is not showing "Create Task" Which I want.

Is there any option in admin panel or config that allow us to enable crate task?

I've added some lines of code in /modules/Calendar/tpls/form.tpl after line number 62.

`{literal}
	<input type="radio" id="radio_task" value="Tasks" onclick="CAL.change_activity_type(this.value);" checked="true"  name="appttype" tabindex="100"/>
	{/literal}
	<label for="radio_task">{$MOD.LBL_CREATE_TASK}</label>`

After adding this line I'm able to see create task option but when I'm saving task it is giving error "Error in saving" and in suitecrm.log file it is  "File TaskFormBase.php doesn't exist".

I am using suiteCRM 7.2.1.

I have attached two screenshots for reference.

Thanks in advance.
Prafull

![2016-05-18 12-16-31_1](https://cloud.githubusercontent.com/assets/19162814/15350339/696235fe-1cf6-11e6-8043-16193cb94f5f.png)
![2016-05-18 12-16-31](https://cloud.githubusercontent.com/assets/19162814/15350338/695cc22c-1cf6-11e6-9c55-a23ac03ca1df.png)

**Comment by ijdavie** [comment]
Hi, 
This question would be best for on the forum (https://suitecrm.com/forum/index). 
Thanks, 
Ian.

**Comment by graphix** [comment]
Hi, did you get answer? I have the simmilar problem.

Marcel

**Comment by krisjana1** [comment]
Hi ,I have the same problem.I have added the previous code on my files but i can't see "create task" .What i se is only a third(extra) radio button circle.Can you help me? Is there sth else except the previous code that  i had to add to see at least "create task"?
