### ISSUE TITLE
Reports and database: Fields/behaviour with "" and NULL

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1437]
When I create a new lead containing a "First Name" and a "Last Name" the record will be stored with "Salutation"="". Then I edit the record without changing the salutation and the record will contain "Salutation"=NULL. So, it will change from "" to NULL. Is this correct?

I have a couple of reports that will filter for "Salutation"="" (first enty of the drop down list). After adding the first record the report is ok. After the modifcation the report will not mention the above record. So that seems wrong, or? Or can I filter with NULL?

The expample with the salutation and the lead is just an example. This behaviour is all over the place: Contacts etc.
Add first:
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+
| id                                   | date_entered        | date_modified       | modified_user_id | created_by | description | deleted | assigned_user_id | salutation | first_name | last_name | title | photo | department | do_not_call | phone_home | phone_mobile | phone_work | phone_other | phone_fax | primary_address_street | primary_address_city | primary_address_state | primary_address_postalcode | primary_address_country | alt_address_street | alt_address_city | alt_address_state | alt_address_postalcode | alt_address_country | assistant | assistant_phone | converted | refered_by | lead_source | lead_source_description | status | status_description | reports_to_id | account_name | account_description | contact_id | account_id | opportunity_id | opportunity_name | opportunity_amount | campaign_id | birthdate | portal_name | portal_app | website |
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+
| eed43028-c43c-fc57-72fe-573cbfdf8aa1 | 2016-05-18 19:15:09 | 2016-05-18 19:15:09 | 1                | 1          |             |       0 | 1                |            | Hubert     | Noname    |       | NULL  |            |           0 | NULL       |              |            | NULL        |           |                        |                      |                       |                            |                         |                    |                  |                   |                        |                     | NULL      | NULL            |         0 |            |             |                         | New    |                    | NULL          |              | NULL                |            |            |                | NULL             |                    |             | NULL      | NULL        | NULL       | http:// |
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+

Then modify:
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+
| id                                   | date_entered        | date_modified       | modified_user_id | created_by | description | deleted | assigned_user_id | salutation | first_name | last_name | title | photo | department | do_not_call | phone_home | phone_mobile | phone_work | phone_other | phone_fax | primary_address_street | primary_address_city | primary_address_state | primary_address_postalcode | primary_address_country | alt_address_street | alt_address_city | alt_address_state | alt_address_postalcode | alt_address_country | assistant | assistant_phone | converted | refered_by | lead_source | lead_source_description | status | status_description | reports_to_id | account_name | account_description | contact_id | account_id | opportunity_id | opportunity_name | opportunity_amount | campaign_id | birthdate | portal_name | portal_app | website |
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+
| eed43028-c43c-fc57-72fe-573cbfdf8aa1 | 2016-05-18 19:15:09 | 2016-05-18 19:16:21 | 1                | 1          | NULL        |       0 | 1                | NULL       | Hubert     | Noname    | NULL  | NULL  | NULL       |           0 | NULL       | NULL         | NULL       | NULL        | NULL      | NULL                   | NULL                 | NULL                  | NULL                       | NULL                    | NULL               | NULL             | NULL              | NULL                   | NULL                | NULL      | NULL            |         0 | NULL       | NULL        | NULL                    | New    | NULL               |               | NULL         | NULL                |            |            |                | NULL             | NULL               |             | NULL      | NULL        | NULL       | http:// |
+--------------------------------------+---------------------+---------------------+------------------+------------+-------------+---------+------------------+------------+------------+-----------+-------+-------+------------+-------------+------------+--------------+------------+-------------+-----------+------------------------+----------------------+-----------------------+----------------------------+-------------------------+--------------------+------------------+-------------------+------------------------+---------------------+-----------+-----------------+-----------+------------+-------------+-------------------------+--------+--------------------+---------------+--------------+---------------------+------------+------------+----------------+------------------+--------------------+-------------+-----------+-------------+------------+---------+

Many fields turn from "" into NULL!

Done this with a fresh 7.6.3 installation. Also seen this in 7.4.3.

-- Andreas

**Comment by adminibt** [comment]
I am sorry. The filter works in 7.6.3; in 7.4.3 it does not.

Still: Is it necessary to change "" to NULL?

-- Andreas

**Comment by shogunpol** [comment]
@adminibt  ,The above issue was tested in recent version of SuiteCRM(7.7.1), and we do not see any issues with salutation and reports, 

If you have any questions around this these can be raised in the SuiteCRM Forums.
https://suitecrm.com/forum/index

 If you see further bugs you can raise a bug here on github. 

Thanks.
