### ISSUE TITLE
Cannot add 'To' recipient on Quick Compose/Email Pop-up

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#145]
When clicking 'To' button on quick compose/email pop-up, nothing happens.

TypeError: document.getElementById(...) is null

See topic: https://suitecrm.com/forum/suitecrm-7-0-discussion/3827-to-button-in-quick-compose-window

**Comment by cadc** [comment]
I have the same problem it is coming from the EmailUICompose.js file in the Emails Module.
Initially clicking the to button causes an error on line 252: body is null
Following clicks cause an error on line 304 id:relatedBeanColumn doesn't exist

**Comment by cadc** [comment]
I've found a solution.
/jssource/src_files/include/javascript/quickCompose.js line 52 
replace with 
YAHOO.util.Dom.insertBefore(divTag, document.getElementsByTagName('footer')[0]);
the insertbefore didn't like the 'footer' string

**Comment by willrennie** [comment]
This issue has been resolved in the latest releases.
