### ISSUE TITLE
7.6.x AOD create issue

### ISSUE THREAD

**Issue by hturkoz** [salesagility/SuiteCRM#1450]
Hi, 
php 5.6, fresh install
When AOD is enable, we have this error :   
 [3333][1][FATAL] Job a93a44ef-3c56-7201-cdcb-573dfe721a3e (Perform Lucene Index) failed in CRON run

I have too see a problem with php "iconv"  (module or function)  
On forum, some person can't access to admin section, for me, email attachment for inbound email don't work.

My solution for this moment is "disable AOD".

Regards

**Comment by shogunpol** [comment]
@hturkoz , the issue has been tested on current version of SuiteCRM (7.7.1), and issue does not appear.
Can you confirm, you still have this issue in current version of SuiteCRM.

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this issue is still seen we can reopen this with more information. 
Thanks.
