### ISSUE TITLE
Major BUG: AOR Reports seems to use translated strings in query, query fails

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1451]
When building a report with a condition the query is build with translated strings and so it fails. As example with the condition "contains" the suitecrm log shows the query with german "enthält". When running the report logged in with english language the report works.

> Fri May 20 11:17:15 2016 [80601][1][FATAL]  Query Failed: SELECT count(*) c FROM (SELECT `meetings`.id AS 'meetings_id', `meetings`.assigned_user_id AS 'Zugewiesen_an0', COUNT(`meetings`.id) AS 'ID1' FROM `meetings`  WHERE ( `meetings`.name Enthält CONCAT('%', 'Ersttermin' ,'%') ) AND  meetings.deleted = 0  GROUP BY `meetings`.assigned_user_id) as n: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Enthält CONCAT('%', 'Ersttermin' ,'%') ) AND  meetings.deleted = 0  GROUP BY `m' at line 1
> Fri May 20 11:17:15 2016 [80601][1][FATAL]  Query Failed: SELECT `meetings`.id AS 'meetings_id', `meetings`.assigned_user_id AS 'Zugewiesen_an0', COUNT(`meetings`.id) AS 'ID1' FROM `meetings`  WHERE ( `meetings`.name Enthält CONCAT('%', 'Ersttermin' ,'%') ) AND  meetings.deleted = 0  GROUP BY `meetings`.assigned_user_id LIMIT 0,20: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Enthält CONCAT('%', 'Ersttermin' ,'%') ) AND  meetings.deleted = 0  GROUP BY `m' at line 1

**Comment by gunnicom** [comment]
Foudn out its a problem in the language file. Probably its better to not get the operators from a language file.
Its the array index aor_sql_operator_list in the file include/language/en_us.lang.php

**Comment by gunnicom** [comment]
Same issue for ARO_Workflow module.

**Comment by horus68** [comment]
@gunnicom on the workflow module see this new PR https://github.com/salesagility/SuiteCRM/pull/2458
Please make some tests on it! :)

**Comment by gunnicom** [comment]
Thanks @horus68 . Will test it next week, but looks good from the first look.
