### ISSUE TITLE
Email merge not working with decimals.

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#1458]
I have an email template being sent out via workflow.
Mail merged decimal fields do not get values.
Integer fields merge correctly.

I have Suite 7.5.2

Cheers
Davd Younger
TSM

**Comment by shogunpol** [comment]
@davidyounger  I tried replicate this bug in recent version of SuiteCRM(7.7.1), and the issue does not appear.
Can you confirm, this issue still exist in current version of SuiteCRM?

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this issue still exists this issue can be reopen with more information. 
Thanks.

**Comment by davidyounger** [comment]
I just tried it again.
Some additional information.
Sending an Email from the Accounts screen by clicking on the email address and then selecting an email template DOES correcly merge in decimal fields in the output.

However, using workflow to send an email template on change of field value does not merge the decimal values.

Cheers
David
