### ISSUE TITLE
send embedded images in mail is not working

### ISSUE THREAD

**Issue by HeiHyd** [salesagility/SuiteCRM#1461]
Uploaded images in new Wizard are not markt as embedded in table notes.
It is not possible to send emails with embedded images. (inline)
Images are shown as question mark in email, Images are delivered as attachments.

regards,
Heimo

**Comment by samus-aran** [comment]
Hi @Heimo

What mail client do you receive it from?

Have you checked the 'show remote content' on the email?

Also, is the SuiteCRM instance on a public domain i.e not from your localhost?

**Comment by HeiHyd** [comment]
The receiving mail client is Apple Mail.
In the past (version 7.5) the pictures were included as base64.

I did al lot of research, here the result:
including one image, works sometimes (system create a external link: http://mycrmdomain.com/public/26139301-=
efec-980b-d234-573f74e34d63.jpg)

including more than one images there is no Link im email source code:

Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">=0A<html xmlns=3D"http://www.=
w3.org/1999/xhtml" lang=3D'de_de'>=0A<head>=0A=09<meta http-equiv=3D"Conten=
t-Type" content=3D"text/html; charset=3DUTF-8" />=0A<title>[Test]: Business=
 Info Murau - Juni</title>=0A</head>=0A<body><div class=3D"mozaik-inner" st=
yle=3D"max-width: initial; font-family: Arial, Helvetica, sans-serif; font-=
size: 14px; line-height: 22.4px; color: rgb(68, 68, 68); padding: 0px 30px;=
 margin: 0px; width: initial; position: relative;"><p style=3D"font-family:=
 Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color:=
 #444444; padding: 0px; margin: 0px;" data-mce-style=3D"font-family: Arial,=
 Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color: #44444=
4; padding: 0px; margin: 0px;">&nbsp;<br style=3D"font-family: Arial, Helve=
tica, sans-serif; font-size: 14px; line-height: 22.4px; color: #444444; pad=
ding: 0px; margin: 0px;" data-mce-style=3D"font-family: Arial, Helvetica, s=
ans-serif; font-size: 14px; line-height: 22.4px; color: #444444; padding: 0=
px; margin: 0px;"></p><h1 style=3D"font-family: Arial, Helvetica, sans-seri=
f; font-size: 24px; line-height: 38.4px; color: #444444;=0Apadding: 0px; ma=
rgin: 0px;" data-mce-style=3D"font-family: Arial, Helvetica, sans-serif; fo=
nt-size: 24px; line-height: 38.4px; color: #444444; padding: 0px; margin: 0=
px;"><img src=3D"https://suitecrm.mcs-onlinemarketing.com//public/26139301-=
efec-980b-d234-573f74e34d63.jpg" alt=3D"" width=3D"376" height=3D"217" styl=
e=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-heigh=
t: 22.4px; color: rgb(68, 68, 68); padding: 0px; margin: 0px;"><br style=3D=
"font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 2=
2.4px; color: #444444; padding: 0px; margin: 0px;" data-mce-style=3D"font-f=
amily: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; =
color: #444444; padding: 0px; margin: 0px;"></h1><p style=3D"font-family: A=
rial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color: #=
444444; padding: 0px; margin: 0px;" data-mce-style=3D"font-family: Arial,=
=0AHelvetica, sans-serif; font-size: 14px; line-height: 22.4px; color: #444=
444; padding: 0px; margin: 0px;">&nbsp;<br style=3D"font-family: Arial, Hel=
vetica, sans-serif; font-size: 14px; line-height: 22.4px; color: #444444; p=
adding: 0px; margin: 0px;" data-mce-style=3D"font-family: Arial, Helvetica,=
 sans-serif; font-size: 14px; line-height: 22.4px; color: #444444; padding:=
 0px; margin: 0px;"></p><div class=3D"mozaik-clear" style=3D"font-family: A=
rial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color: #=
444444; padding: 0px; margin: 0px; height: 0px;" data-mce-style=3D"font-fam=
ily: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; co=
lor: #444444; padding: 0px; margin: 0px; height: 0px;">&nbsp;<br style=3D"f=
ont-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.=
4px; color: #444444; padding: 0px; margin: 0px;" data-mce-style=3D"font-fam=
ily: Arial,=0AHelvetica, sans-serif; font-size: 14px; line-height: 22.4px; =
color: #444444; padding: 0px; margin: 0px;"></div></div><br /><span style=
=3D'font-size:0.8em'>Um sich von der E-Mail Liste abzumelden  <a href=3D'ht=
tps://suitecrm.mcs-onlinemarketing.com/index.php?entryPoint=3Dremoveme&iden=
tifier=3D24580ea5-f76c-bcb0-3509-573f7541295c'>hier klicken</a></span><br /=
><img alt=3D'' height=3D'1' width=3D'1' src=3D'https://suitecrm.mcs-onlinem=
arketing.com/index.php?entryPoint=3Dimage&identifier=3D24580ea5-f76c-bcb0-3=
509-573f7541295c' /></body></html>

regards,
Heimo

**Comment by gymad** [comment]
@HeiHyd 
Hi Heimo
How did you added the images to the template, can you take a screenshot of your template via the template editor and please check the URLs of your images. You find the inserted image URL if select template > click on image and select it in the editor area > click the image btn on toolbar > in 'Source' field of popup. 
Make sure the remote email clients having correct access rights to your images url.
if you add some image or documents in the attachments make sure the attachment added to the template correctly.

**Comment by HeiHyd** [comment]
I added the images with the new client. Everything on Webpage works fine.

![bildschirmfoto 2016-05-24 um 18 11 18](https://cloud.githubusercontent.com/assets/5616374/15511301/35d93194-21db-11e6-9ba8-c9d5528d2348.png)

![screen_01](https://cloud.githubusercontent.com/assets/5616374/15511167/bcb67f4c-21da-11e6-9e2f-5e5941d1419e.png)

**Comment by samus-aran** [comment]
Hi @HeiHyd

Have you updated the public folder (i.e. setting permissions) since you created this issue?  As we can now see the below image were as before we were unable:
http://suitecrm.mcs-onlinemarketing.com/public/26139301-efec-980b-d234-573f74e34d63.jpg

Inside the email template you sent out the URL should be the above, not an entrypoint (as this caused images not being visible on certain mail clients).  

Can you include the src url from your issue email here?

**Comment by ijdavie** [comment]
This looks like it is related to #1521, I will close this and any new information can be added to the other issue. 
Thanks.
