### ISSUE TITLE
Fatal Error when AOP function redeclared

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#147]
Fatal error: Cannot redeclare pollMonitoredInboxesCustomAOP() (previously declared in crminstance/custom/modules/Schedulers/_AddJobsHere.php:41) in crminstance/custom/modules/Schedulers/Ext/ScheduledTasks/scheduledtasks.ext.php on line 240

See topic: https://suitecrm.com/forum/bug-tracker/3835-fatal-error-cannot-redeclare-pollmonitoredinboxescustomaop

**Comment by jshwhitlow** [comment]
This issue happened on our instance of 7.5.1 for an unknown reason as well. I would consider this problem still relevant. When I went to the scheduler I saw nothing, I enabled php.ini and found this error:

`"Fatal error: Cannot redeclare processAOW_Workflow() (previously declared in /admin/modules/Schedulers/_AddJobsHere.php:739) in admin/custom/modules/Schedulers/Ext/ScheduledTasks/scheduledtasks.ext.php on line 34"`

When I checked both I found this function was being called twice in both files mentioned above.
```
function processAOW_Workflow() {
    require_once('modules/AOW_WorkFlow/AOW_WorkFlow.php');
    $workflow = new AOW_WorkFlow();
    return $workflow->run_flows();
}
```

I simply commented out the code in scheduledtasks.ext.php and everything seems to be fixed.
