### ISSUE TITLE
Duplicating report with a chart removes the chart from the original report

### ISSUE THREAD

**Issue by emcrobert** [salesagility/SuiteCRM#1489]
As per title, if you duplicate a report that has a chart, the chart gets removed from the original report, though everything looks correct in the duplicated report.

Originally reported by TaufiqueAhmed on the forums and I can replicate the issue myself using 7.6.2.

**Comment by horus68** [comment]
@mattlorimer there are 2 different PR to the same issue. (aug 2015) This is a decision on Salesagility regarding the way you prefer to solve it.
