### ISSUE TITLE
Meeting and Call Reminders are showed as overriden by User Reminder Preferences in Calendar

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#1490]
Hi,
on a SuiteCRM 7.5.3 or 7.6.3

when you click on a Meeting (or Call) in a Calendar cell (or on a Calendar Dashlet cell) the reminders time dropdown values are showed as overridden by the User Reminder Preferences.

If you go to the full form, you can view them right. They have been saved properly. But are showed wrong.

**Comment by paulgodley** [comment]
Hi @mayerelyashiv, thank you for this.  I will get this resolved and let you know when the fix is in place as soon as possible.
