### ISSUE TITLE
Unknown Error (8192) in Roles

### ISSUE THREAD

**Issue by LewMegas** [salesagility/SuiteCRM#1493]
Hi all,

I haven't been able to find this issue so apologies if this turns out to be a dupe.

We are seeing the following message in Admin>Role Management>Custom Role

Unknown Error (8192): Non-static method ACLRole::getRoleActions() should not be called statically, assuming $this from incompatible context occurred in /xxxx/public_html/modules/ACLRoles/DetailView.php on line 60 [2016-05-26 10:38:54] display_stack_trace caller, file: /xxxx/public_html/include/utils.php line#: 3254

Appreciate any advice/feedback

**Comment by shogunpol** [comment]
@LewMegas  ,can you give some more information about, how you manage receive this error log. If you can describe in details, how to replicate this issue.
I run through the roles module and i been unable to reproduce this error, any help will be good.

**Comment by ijdavie** [comment]
We will close this issue due to lack of activity, if this issue still exists this issue can be reopen with more information. 
Thanks.
