### ISSUE TITLE
Possible Meetings Bug

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#150]
See topic: https://suitecrm.com/forum/bug-tracker/2258-bug-error-adding-people-to-meeting

**Comment by willrennie** [comment]
Possible fix mentioned in post: https://suitecrm.com/forum/bug-tracker/2258-bug-error-adding-people-to-meeting#15383

**Comment by vladbar** [comment]
I've tried to replicate this issue, but was unable to get the same error. In my tests I can add Users, Contacts or Leads as Invitees without any problems.

**Comment by JimMackin** [comment]
Unable to reproduce. Possibly has been fixed. Will close and reopen if there are more reports.
