### ISSUE TITLE
Bug with Campaign ROI Chart Dashlet 

### ISSUE THREAD

**Issue by urdhvatech** [salesagility/SuiteCRM#1501]
Found a bug with Campaign ROI Chart Dashlet. It doesn't Generate any report as there is a flaw in the query.
**- modules/Charts/Dashlets/CampaignROIChartDashlet/CampaignROIChartDashlet.php**

In the **function constructQuery**
The campaign id gets converted to int, Where as the campaign id would be a 36chars UID. This makes the query return no data at all.
Below is the line, Which should be removed.
**$campaign_id = (int) $campaign_id;**

You may include this fix in next release

**Comment by paulgodley** [comment]
Thank you for this @urdhvatech, I will get this investigated and resolved as soon as possible.
