### ISSUE TITLE
getBeansByEmailAddress method can return empty beans

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#1504]
The getBeansByEmailAddress method in SugarEmailAddress.php returns a list of beans for a given email address. However if one or more of the beans have been deleted this method still attempts to load the bean and add it to the array.

This results in an array of beans where some of the beans have no fields set which can cause issues in later code.

I suggest changing this method to load using the bean factory and to check the result of the load call to ensure the bean is loaded.

**Comment by Dillon-Brown** [comment]
Confirmed in latest 7.10.x

**Comment by grahambrown11** [comment]
@Dillon-Brown can you review the pull request #8082 which addresses this issue

**Comment by Dillon-Brown** [comment]
@grahambrown11 Approved, just needs assessed and then merged. Thanks!
