### ISSUE TITLE
IE11 does not display uploaded images 

### ISSUE THREAD

**Issue by vladbar** [salesagility/SuiteCRM#1506]
IE11 cannot display generic 'application/octet-stream' (which is defined as "arbitrary binary data" in RFC 2046).

**Comment by vladbar** [comment]
issue 1: IE11 does not display image saved through the field of type Image.

issue 2: Firefox and Google Chrome display cached image.
Steps to reproduce: 
use image field in the Contacts module. 
Add an image in Edit View, then save. 
Go back to the edit view and and add another image and save again.
The detail view still displays the first image.

**Comment by pgorod** [comment]
Is this the same as https://github.com/salesagility/SuiteCRM/issues/1304 ? In that issue I reported, images don't show at all, only little crosses like "X".
