### ISSUE TITLE
en_us code inside a long sentence

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1512]
In file /modules/Leads/language/en_us.lang.php there is this sentence
`    'ERR_DELETE_RECORD' => 'en_us A record number must be specified to delete the lead.',`

en_us is to be translated to the language code of the translation pack or not?
File:
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Leads/language/en_us.lang.php

**Comment by paulgodley** [comment]
Hi @horus68, please remove this from the label, this was probably a cut-and-paste error.  Many thanks

**Comment by horus68** [comment]
Closed by fix https://github.com/salesagility/SuiteCRM/pull/1514
