### ISSUE TITLE
Accounts Module - Copy to Contacts Button Does Not Work

### ISSUE THREAD

**Issue by briansalesagility** [salesagility/SuiteCRM#1516]
In the Account module there is a 'Copy' button next to the Billing Address and Shipping Address fields. When you hover over the button the prompt 'Copy to Contacts' appears. 

![copy button](https://cloud.githubusercontent.com/assets/17987506/15669619/2d63110e-2719-11e6-8887-c4b58a490f42.png)

On clicking the button a pop up window appears with the matching Contact with 'Copy to Primary Address' and 'Copy to Other Address' options:

![copy to contact](https://cloud.githubusercontent.com/assets/17987506/15669631/3be19b56-2719-11e6-817e-fd75344a5779.png)

Neither of these buttons look as if they work. Also, when there is an address in the Account the 'Copy' button is hidden. Maybe the 'Copy' button should be visible when there is an address in the Account and hidden when there is not? It looks like currently you can only copy a blank address.

**Comment by CaptainChainsaw** [comment]
The functionality of the copy button has been confirmed to be working as expected.  There is an issue relating to inline editing however, this has been raised in this issue more specifically:

https://github.com/salesagility/SuiteCRM/issues/1544
