### ISSUE TITLE
first time main screen display defective

### ISSUE THREAD

**Issue by tuntex** [salesagility/SuiteCRM#1522]
![2016-05-31 22_40_38-citywidelog](https://cloud.githubusercontent.com/assets/15256154/15697633/96bfce90-2781-11e6-8752-c9a5b8ca3f5f.png)
See attachment screenshot of how it looks like right after the installation and first login.
Please advise. Thanks!

**Comment by ghermans** [comment]
you should set the following permissions on the SuiteCRM directory 

- sudo chmod -R 755 . 
- sudo chmod -R 775 cache custom modules themes data upload config_override.php

**Comment by tuntex** [comment]
i had to do that initially because the installation would not even start. 
Do I need to it one more time?

**Comment by tuntex** [comment]
yes it worked. I had to do it twice.

**Comment by samus-aran** [comment]
@tuntex 

Going forward try setting your default_permissions in config.php to dir_mode = 1517 (or 1533) and file_mode = 420.
