### ISSUE TITLE
AOR - Ajax Load causes issues

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1532]
Begin Creating a report by clicking the "Create" button on the right of the screen.
On the report, you are unable to change tabs. (i.e, Fields, Conditions, Charts)

**Comment by gunnicom** [comment]
For me i can change the tabs, until i choose the report module. Then i am unable to change the tabs.
So for now i save the report and then edit it as a workaround.

**Comment by gunnicom** [comment]
Well, at least sometimes. This time it worked.

**Comment by johnM2401** [comment]
I found another method of replicating this.

If you have a report in the "Recently Viewed" panel on the left of the CRM,  Click the Pencil icon to go straight to the Editview for this report.
Then, you are unable to change tabs.  I imagine this is a similar, if not the same issue as the "Create" button on top-right.

**Comment by shogunpol** [comment]
@johnM2401 , an issue has been tested on recent version of SuiteCRM(7.7.8), and not appear, can you confirm it, and close an issue?

**Comment by johnM2401** [comment]
Issue still seems to exist in SuiteR theme using both methods described above. ("Create" button and "recently viewed"


Additionally, it looks like the issue can also be replicated in the SuiteP theme using the method described above: "-If you have a report in the "Recently Viewed" panel, (Either on the Left of the CRM, or the one found by hovering over "Reports" on the Navigation bar), Click the Pencil icon to go straight to the Editview for this report. Then, you are unable to change tabs."

![screenshot from 2017-01-04 15 14 17](https://cloud.githubusercontent.com/assets/13675281/21647209/3e7f78dc-d291-11e6-8824-df333d9f2abd.png)
