### ISSUE TITLE
Email templates HTML source code editor no longer available

### ISSUE THREAD

**Issue by ishanloya** [salesagility/SuiteCRM#1540]
Can no longer change the HTML source code directly within email templates

**Comment by samus-aran** [comment]
@ishanloya 

You should be able to edit it via the WYSIWYG via the 'Tools' dropdown and an option called Source Code.

Let me know if you can't find this.

**Comment by ishanloya** [comment]
@samus-aran 

The 'Tools' dropdown itself isn't showing up since the upgrade to 7.6.4. Maybe I'm missing something. I only see the 'File', Edit', View' and 'Format' menus.

**Comment by samus-aran** [comment]
@ishanloya   I've attached a screenshot of where the Tools dropdown should be.  Try deleting your browser cache to refresh the javascript for the WYSIWYG.
![suitecrm](https://cloud.githubusercontent.com/assets/4041275/15741573/425cac10-28b2-11e6-9ead-d0a8d824397d.png)

**Comment by ishanloya** [comment]
Deleting the browser cache worked. Thanks @samus-aran
