### ISSUE TITLE
Words with ' are cuted in lists

### ISSUE THREAD

**Issue by Petrouchka** [salesagility/SuiteCRM#1541]
If the name of a choice list field contains ', it is cutted after ' when the another field is modified, after registering the choice list.
Exemple : Groupe d'entreprise -> Groupe d
![screenshot at 2016-06-02 10 52 45](https://cloud.githubusercontent.com/assets/3955499/15739504/9a327bce-28b0-11e6-992c-fcab06c2cc1e.png)

**Comment by MikeyJC** [comment]
This looks like a duplicate of #1456
