### ISSUE TITLE
7.6.4 Roles Not showing Enabled/Disabled labels

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#1552]
7.6.4 Roles Not showing Enabled/Disabled labels.  Ran quick repair, still appears to not show the labels.  Showing "LBL_ACCESS_DISABLED"/"LBL_ACCESS_ENABLED"/"LBL_ACCESS_DEFAULT" instead.

**Comment by willrennie** [comment]
This works fine for me in 7.6.4. Have you ensured you have the correct permissions set in your environment? Have you made any recent changes or recently upgraded? Do you see any 'undefined' labels or any other areas in the CRM where labels do not show as expected?

**Comment by cjmny** [comment]
This can probably be closed.  I fixed permissions, repaired, repaired roles many, many times and the problem persisted.  This morning I decided to try it one last time before posting a screenshot here and it worked.  Maybe order of operations had something to with it?
