### ISSUE TITLE
Campaign wizard goes to blank screen at "Target Lists" Step (v7.6.4)

### ISSUE THREAD

**Issue by kyriakoy** [salesagility/SuiteCRM#1557]
Apply to versions 7.6.3 and 7.6.4. 
When I open the new Campaign wizard, If I click on Target List or Campaign Header, the screen goes blank.

Repported also here from other people:
https://suitecrm.com/forum/suitecrm-7-0-discussion/9501-7-6-3-campaign-wizard-blank-screen

My Installation:
SuiteCRM 7.6.4/Ubuntu 14.04/ php 5.5.9/ mysql 5.5.49

chown -Rf www-data:www-data crm.website.folder
sudo chown -R www- data:www-data .
chmod 664 config.php
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php

**Comment by samus-aran** [comment]
Hi @kyriakoy What browser are you currently using?  Can you try and refreshing your browser's cache?

**Comment by kyriakoy** [comment]
Hi,

Yes I have multiple times with diffrent computers, connections, browsers etc....

I found that the problem is only with an existing Campaign (created with prior versions). When I refresh the page I show to log the following:
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query:SELECT campaign_trkrs.* FROM campaign_trkrs  WHERE campaign_trkrs.id = '5b480df8-aef7-d5b8-cc45-5470859919c2' AND campaign_trkrs.deleted=0 LIMIT 0,1
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query Execution Time:3.6954879760742E-5
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query:SELECT name from campaigns where id = '41c7b4f6-ef1e-eb5d-8ccb-54705d670387'
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query Execution Time:3.3855438232422E-5
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] Hook called: CampaignTrackers::after_retrieve
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] get_full_list:  order_by = '' and where = ''
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] SugarBean[ProspectList].load_relationships, Loading relationship (assigned_user_link).
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] rebuilding cache for prospectlists
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='prospectlists' AND  deleted = 0
Wed Jun  8 17:22:10 2016 [1027][1][INFO] Query Execution Time:4.1007995605469E-5
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] Failed to load vardefs for prospectlists: in linkFieldsForModule<br/>
Wed Jun  8 17:22:10 2016 [1027][1][ERROR] Unable to get proper side for link assigned_user_link
Wed Jun  8 17:22:10 2016 [1027][1][ERROR] Unable to get proper side for link assigned_user_link
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] SugarBean[ProspectList].load_relationships, Loading relationship (modified_user_link).
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] SugarBean.load_relationships, Error Loading relationship (modified_user_link)
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] SugarBean[ProspectList].load_relationships, Loading relationship (created_by_link).
Wed Jun  8 17:22:10 2016 [1027][1][DEBUG] SugarBean.load_relationships, Error Loading relationship (created_by_link)

then I search for :
 # grep -rl "assigned_user_link" ./ |grep "Prospect"
./cache/modules/Prospects/Prospectvardefs.php
./cache/modules/ProspectLists/ProspectListvardefs.php

As you can see exist only at cache. Is this proper ?
I have already Rebuild Cache and Relatiotionships

Permissions are:
sudo chmod -R 775 cache custom modules themes data upload config_override.php

Thank you,
Nikos

**Comment by kyriakoy** [comment]
I check it also and with another existing Campaign with the same problem (blank problem) and in sugarcrm.log I didn't found the previews error
But one additional debuging with Firebug shows Internal Error 500 and apache log shows:

http://mycrm.com/index.php?action=WizardMarketing&module=Campaigns&return_module=Campaigns&return_action=WizardHome&return_id=41c7b4f6-ef1e-eb5d-8ccb-54705d670387&campaign_id=41c7b4f6-ef1e-eb5d-8ccb-54705d670387&jump=3&show_wizard_marketing=1&marketing_id=5cd80d11-1ccc-6f20-c929-547081d44cdb&record=5cd80d11-1ccc-6f20-c929-547081d44cdb&campaign_type=Email
[Wed Jun 08 18:43:02.338239 2016] [:error] [pid 4736] [client 62.169.208.109:2024] PHP Fatal error:  Call to a member function get_entry_count() on a non-object in /var/www/mycrm.com/modules/Campaigns/WizardNewsletter.php on line 480, referer: http://mycrm.com/index.php?action=WizardMarketing&module=Campaigns&return_module=Campaigns&return_action=WizardHome&return_id=41c7b4f6-ef1e-eb5d-8ccb-54705d670387&campaign_id=41c7b4f6-ef1e-eb5d-8ccb-54705d670387&jump=3&show_wizard_marketing=1&marketing_id=5cd80d11-1ccc-6f20-c929-547081d44cdb&record=5cd80d11-1ccc-6f20-c929-547081d44cdb&campaign_type=Email

Maybe this can help

**Comment by kyriakoy** [comment]
Thank you for the update
I confirm that is working
