### ISSUE TITLE
Email Attachments Sent By Workflow Do Not Show In Related Activity

### ISSUE THREAD

**Issue by jcastleman** [salesagility/SuiteCRM#1561]
When sending emails manually, if there's an attachment(s) on the email template, the related activity created in List View will show a paper clip to indicate there's an attachment, and in Detail View, there are links below the email to the attachments.

This does not happen when email templates with attachments are sent by the workflow.  It does appear to send the attachments, but there is NO paperclip on the related activity in List View and NO links indicating any attachments in Detail View.

Version is 7.5.2

**Comment by ijdavie** [comment]
From what I can see here, Workflow does not send the attachment which explains why this paperclip does not show as no attachment is logged in the activity. 
Thanks for raising this as a issue.

**Comment by vladbar** [comment]
Every time an email is sent by the Workflow module if there are some attachments, new Notes need to be created with unique ids and sent email id as a parent id.
Also a new file needs to be created based on the original attachment file. This file must have the newly generated Note id as its name, as the modules/Emails/DetailView.php generates a link which points to this file.
