### ISSUE TITLE
Need Upgrade Files [7.6beta2 to 7.6.4]

### ISSUE THREAD

**Issue by kismetgerald** [salesagility/SuiteCRM#1562]
I would like to upgrade my lab from v7.6beta2 to current stable production release but the installation files are nowhere on the download page. Can someone please help me with this, thanks.

**Comment by kismetgerald** [comment]
Any chance I'll get some help on this please?

**Comment by ijdavie** [comment]
Hi, A list of upgrade packages can be found at the following link. However not all beta releases will have upgrade paths to stable releases this is one of the reasons why we do not recommend using a beta in a Live environment. 

https://sourceforge.net/projects/suitecrm/files/upgrades/

**Comment by kismetgerald** [comment]
Thanks, but you incorrectly assumed I was running in a production environment - I'm smart enough not to do that.  This is my test box that I'd upgraded to test v7.6beta2 but got sidetracked with another project and by the time I got to it you guys have made the release and removed the upgrade files.

I've already checked the link you provided and couldn't find one for v7.6beta2.  I'm sure you guys keep copies of the files somewhere can you please find it.  Or if there's a way to revert the upgrades that you can show me I can possible revert the system back to v7.5.x then upgrade to latest.
