### ISSUE TITLE
Scaling on barcharts incorrect

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1563]
![chart_axis](https://cloud.githubusercontent.com/assets/550251/15888561/9dc2e6be-2d67-11e6-865a-dabf261774e1.PNG)
For small y-axis max values that are not dividable by 5 the axis scaling is faulty.
In the graph you can see its 1,2,4,5,6 so 3 is missing and scaling is bad (2 shows as 1.7)
For me it works better if skipping the function calculateMaxYForSmallNumbers() completely, so rgraph handles the scaling better.

```
modules/AOR_Chart.php   
                ymax:calculateMaxYForSmallNumbers($chartDataValues)      [position 392:22]  
                ymax:calculateMaxYForSmallNumbers($chartDataValues)      [position 434:22]  
                ymax:calculateMaxYForSmallNumbers($chartDataValues)      [position 467:22]  
                ymax:calculateMaxYForSmallNumbers($chartDataValues),      [position 546:22] 
```

```
include/SuiteGraphs/RGraphIncludes.php  
                function calculateMaxYForSmallNumbers(dataPoints)      [position 28:26] 
```

**Comment by paulgodley** [comment]
Hi there.  The calculateMaxYForSmallNumbers was added to resolve bug #876.  A compromise would be to make the maxYForSmallNumbers set to 10, as this should allow for appropriate scaling of the smaller numbers?

**Comment by gunnicom** [comment]
That would not change the problem, as it will then again occur with eleven. I think it maybe good to have the scale dividable by 5. I will add a patch for that.

**Comment by gunnicom** [comment]
Just for reference, there is something on that on rgraph. But got no real solution:

http://www.rgraph.net/forum/message.html/y-axis-labels-are-incorrect-when-all-data-values-are-1-ok-if-one-or-more-20140529132751.html

**Comment by gunnicom** [comment]
Closed first pull request because i like the new one more.
