### ISSUE TITLE
SuiteCRM 7.6.4 module id instead module name in the Security Suite Settings

### ISSUE THREAD

**Issue by d52b8ee381** [salesagility/SuiteCRM#1576]
SuiteCRM 7.6.4 module id instead module name in the Security Suite Settings

screen shot attached

![screenclip](https://cloud.githubusercontent.com/assets/17437851/15901782/7aaf6634-2dad-11e6-916f-ae3f6cd75fd4.png)

**Comment by 604media** [comment]
#1377

**Comment by willrennie** [comment]
Confirmed as fixed in the latest release(7.6.5).
