### ISSUE TITLE
Currency Formatting Issue when Creating Opportunities from Quotes

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#158]
Number is being unformatted but not re-formatted, so when creating an Opportunity from a Quote with a 1000's separator of . and decimal separator of , the amount is incorrect.

**Comment by celsowebber** [comment]
This problem happens also on the Contracts module, please have a look at this forum post:
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/9045-aos-contracts-problem-with-1000-s-separator-and-decimal-symbol-suitecrm-7-5-3

Thanks.
