### ISSUE TITLE
Unable to send email campaign after adding multiple outbound Email Account in SuitCRM 7.6.4

### ISSUE THREAD

**Issue by chandan999** [salesagility/SuiteCRM#1581]
Hi all,
       After adding multiple outbound account in Outgoing SMTP Mail Servers,I am not able to send campaign email.All email are getting stuck in email queue in suitcrm 7.6.4.

**Comment by willrennie** [comment]
What start date/time is set on your email marketing record? Emails will only be sent out at the start date/time of the email marketing record. Also, make sure your 'Run Nightly Mass Email Campaigns' scheduler is running in Admin -> Schedulers.

**Comment by willrennie** [comment]
We have received no response to questions asked so I would suggest that you maybe post this question on the SuiteCRM forums with more information.
