### ISSUE TITLE
AOR_Report - secondary grouping issue

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1583]
AOR_Report adds fields to 'second_group_by' in a forced manner (and therefore also in the final report sql statement) resulting in unexpected result:

**current version**: 
commit: 4c7587b , 
SuiteCrm Version 7.6.4
Sugar Version 6.5.23 (Build 1061)

**The report**: I want to list all accounts (with or without quotes) and for each account show the sum of the total of the quotes related to that account.

**The configuration**: 
![image](https://cloud.githubusercontent.com/assets/1028115/15961915/e146aafa-2f07-11e6-84cb-5214f6801722.png)

**The result(BAD)**:
![image](https://cloud.githubusercontent.com/assets/1028115/15961939/081570f8-2f08-11e6-85ab-c71c40c76fdb.png)

**The issue**: I need the sum of the totals for each account and not the individual total values (as shown in screenshot)

**The SQL**:  this is the sql statement generated by the report module:
`SELECT 'accounts'.name AS 'Name0', 'accounts:aos_quotes'.currency_id AS 'accounts:aos_quotes_currency_id', SUM('accounts:aos_quotes'.total_amount) AS 'Grand_Total1' FROM 'accounts' LEFT JOIN aos_quotes 'accounts:aos_quotes' ON 'accounts'.id='accounts:aos_quotes'.billing_account_id AND 'accounts:aos_quotes'.deleted=0 WHERE accounts.deleted = 0 GROUP BY 'accounts'.name, 'accounts:aos_quotes'.currency_id, 'accounts:aos_quotes'.total_amount ORDER BY 'accounts'.name ASC`

**Thoughts**:
1) It is clear from the SQL that if we are grouping by `accounts:aos_quotes.total_amount` we will get individual quote totals but this is not what i have configured in the report.

2) investigating further I found this in the $query_array in `build_report_query()` method:
`QUERY-ARRAY: Array ( [group_by] => Array ( [0] => 'accounts'.name ) [sort_by] => Array ( [0] => 'accounts'.name ASC ) [select] => Array ( [0] => 'accounts'.name AS 'Name0' [accounts:aos_quotes_currency_id] => 'accounts:aos_quotes'.currency_id AS 'accounts:aos_quotes_currency_id' [1] => SUM('accounts:aos_quotes'.total_amount) AS 'Grand_Total1' ) [join] => Array ( [accounts:aos_quotes] => LEFT JOIN aos_quotes 'accounts:aos_quotes' ON 'accounts'.id='accounts:aos_quotes'.billing_account_id AND 'accounts:aos_quotes'.deleted=0 ) [second_group_by] => Array ( [0] => 'accounts:aos_quotes'.currency_id [1] => 'accounts:aos_quotes'.total_amount ) [where] => Array ( [0] => accounts.deleted = 0 ) )`
which is used the build the sql string but which has already got  `accounts:aos_quotes.total_amount` field added for grouping in the `second_group_by` key

3) so I tracked down where this array is built - in `build_report_query_select()` method, and I find a 'forced' (=== without any condition) (https://github.com/salesagility/SuiteCRM/blob/master/modules/AOR_Reports/AOR_Report.php#L1103) of adding all fields to `second_group_by`  key if they are not added in 'group_by' (manually in report configuration.
Which basically means that module groups by all fields added for select.

4) if I comment line 1103: `$query['second_group_by'][] = ...` fields that are not explicitly set fior grouping in report configuration are not present in `second_group_by`, hence the sql statement I get is as expected:
`SELECT 'accounts'.name AS 'Name0', 'accounts:aos_quotes'.currency_id AS 'accounts:aos_quotes_currency_id', SUM('accounts:aos_quotes'.total_amount) AS 'Grand_Total1' FROM 'accounts' LEFT JOIN aos_quotes 'accounts:aos_quotes' ON 'accounts'.id='accounts:aos_quotes'.billing_account_id AND 'accounts:aos_quotes'.deleted=0 WHERE accounts.deleted = 0 GROUP BY 'accounts'.name, 'accounts:aos_quotes'.currency_id ORDER BY 'accounts'.name ASC`
and hence also the result of the report is correct:
![image](https://cloud.githubusercontent.com/assets/1028115/15962413/2ed18ac6-2f0b-11e6-9c9c-41d3cb7d1939.png)

**Question**: I guess there is a point to this `second_group_by` thing otherwise it would not be there - but what is it, in which cases? This report of mine is an extremely simple example that is probably the most common usage of reporting and should/must work.

**Note**: I will, in my deployment keep this line commented and try to think of complex reports and see if I get unexpected results because of commenting this line. (Have you got a use case where this is necesary?)

**Comment by mattlorimer** [comment]
it only really required for mssql compatibility, but there a fix for this issue #1519

**Comment by adamjakab** [comment]
ok thanks, i implemented the fix and I confirm that it is now working as expected
