### ISSUE TITLE
en_us language code in a value - To be translated?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1588]
In file     
https://github.com/salesagility/SuiteCRM/blob/master/modules/Leads/language/en_us.lang.php

there is this string:
`    'ERR_DELETE_RECORD' => 'en_us A record number must be specified to delete the lead.',`

What is a language code en_us doing here? Is this to be translated or is just an error?

**Comment by JimMackin** [comment]
Duplicate of #1512
