### ISSUE TITLE
PHP Error: Redefinition of parameter $fieldRequired

### ISSUE THREAD

**Issue by daniel-samson** [salesagility/SuiteCRM#1591]
in modules/Campaigns/WebToLeadFormBuilder.php line 183

the method signature:

    getFieldBoolHTML($fieldName, $fieldRequired, $fieldLabel, $webRequiredSymbol, $fieldRequired)

has two parameters with the same identifier. This syntax is incorrect and needs to be fixed.

**Comment by ijdavie** [comment]
Relates to Pull request #1592
