### ISSUE TITLE
PHP 7.1.0 - Fix Notices

### ISSUE THREAD

**Issue by daniel-samson** [salesagility/SuiteCRM#1595]
Notice: A non well formed numeric value encountered in /home/daniel/Projects/php/suitecrm/include/utils.php on line 3421

**Comment by daniel-samson** [comment]
Warning: Illegal string offset 'ACLAction' in /home/daniel/Projects/php/suitecrm/modules/ACLActions/vardefs.php on line 44

Notice: Array to string conversion in /home/daniel/Projects/php/suitecrm/modules/ACLActions/vardefs.php on line 44
.
Warning: Illegal string offset 'ACLRole' in /home/daniel/Projects/php/suitecrm/modules/ACLRoles/vardefs.php on line 42

Notice: Array to string conversion in /home/daniel/Projects/php/suitecrm/modules/ACLRoles/vardefs.php on line 42
.
Warning: Illegal string offset 'Relationship' in /home/daniel/Projects/php/suitecrm/modules/Relationships/vardefs.php on line 41

Notice: Array to string conversion in /home/daniel/Projects/php/suitecrm/modules/Relationships/vardefs.php on line 41
.
Warning: Illegal string offset 'Lead' in /home/daniel/Projects/php/suitecrm/modules/Leads/vardefs.php on line 41

Notice: Array to string conversion in /home/daniel/Projects/php/suitecrm/modules/Leads/vardefs.php on line 41
.
Warning: Illegal string offset 'Case' in /home/daniel/Projects/php/suitecrm/modules/Cases/vardefs.php on line 42

Notice: Array to string conversion in /home/daniel/Projects/php/suitecrm/modules/Cases/vardefs.php on line 42

Warning: Illegal string offset 'Case' in /home/daniel/Projects/php/suitecrm/modules/Cases/vardefs.php on line 447

**Comment by daniel-samson** [comment]
PHP Notice:  Undefined index: indices in /home/daniel/Projects/php/suitecrm/install/performSetup.php on line 316

**Comment by daniel-samson** [comment]
PHP 5.6.22 Deprecated: Non-static method DynamicField::deleteCache() should not be called statically, assuming $this from incompatible context in /home/daniel/Projects/php/suitecrm/data/SugarBean.php on line 1768
.

**Comment by shogunpol** [comment]
Thanks for raise this issue.
It is assigned as a bug.

**Comment by duynguyenhoang** [comment]
If it is possible I am willing to fix and create new pull request for this one

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
