### ISSUE TITLE
[Suggestion] LOCK function of record - 2 or more users can't edit in same time same record

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1602]
I think, that the great  will if we will use the lock function integrated in SuiteCRM, because many times happend that 2 users working on same project or same records and when one edits same record as other, he/she overwrites record.

Or it will so great, if will somewhere indicator, that somebody is editing record... Like "Lock" icon next the record name or some message in edit view that user will know, that the record is editing by another user xyz or something similarly.

Please let me your feedback. Miky

**Comment by gunnicom** [comment]
That worked for me earlier, but i dont know if it was Sugar or if it was Suite.
That was reported to me recently, and i think it is a regression, or was this disabled on purpose?

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Suggestion] LOCK function of record - 2 or more users can't edit in same time same record](https://trello.com/c/cT6uzeCx/94-suggestion-lock-function-of-record-2-or-more-users-can-t-edit-in-same-time-same-record)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by gunnicom** [comment]
It is not a suggestion it is a regression bug.

**Comment by samus-aran** [comment]
@gunnicom Is it a regression?  I haven't been able to see the change unless it did come from Sugar to which arguable why was it removed. I'll keep it as a suggestion until confirmed its a regression.

**Comment by gunnicom** [comment]
Ah, maybe i misread the poster. He wants an indicator, i thought he menat like it is now, that on save you get that message, that the record has been saved. So suggestion seems fine to me now :D
