### ISSUE TITLE
Removing Related Invited from Meeting/Call via subpanel needs to be removed from Invited Reminders

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#1603]
In relation to this proposed fix - need to do the same via the subpanel.

https://github.com/salesagility/SuiteCRM/pull/1584

**Comment by willrennie** [comment]
Tested and confirmed as resolved in the latest releases of 7.6 and 7.7. Related issue has also been closed and PR merged. It was noted during testing that you have to refresh the page for the reminder details to update, but I do not see this as a bug/issue.
