### ISSUE TITLE
Currency field has Unusual Behaviour on Search View

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1608]
Logged by forum post:  https://suitecrm.com/forum/suitecrm-7-0-discussion/9776-advanced-search-currency-field-not-working-right

The issue is as described:
1. The field is shown as a text field instead of dropdown or list to choose from.
2. The default currency is always prefilled (as long text), everytime the search page is loaded.
3. When the currency text field is prefilled with the long name of the default currency, 0 results are shown.

I also noticed that searching for the Currency's ID in this field returns results as expected. 
(i.e, Searching -99  returns records where the currency used was the default one)

**Comment by shogunpol** [comment]
This issue is partially related to issue #609

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
