### ISSUE TITLE
AOR_Reports - "add to target list" not working

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#1612]
This used to work - now it does not. Here is my [fixed up code](https://gist.github.com/adamjakab/ef79c5dcc3414a3c380b8f86fb8074b7) (cannot make PR at the moment).

The Report must have Id column(can also be hidden) of the bean on which the report is based (as a matter of fact only id column is required). 

Originally this method did not return anything - I have implemented (for testing reasons) an $answer array which is printed out at the end as response - it could be used to give some feedback to user which now is not there.

**Comment by vladbar** [comment]
Hi  adamjakab, 

which SuiteCRM version and OS do you use? I cannot replicate this error.

**Comment by adamjakab** [comment]
OS: linux as server with php 7
SuiteCRM: lastest commit from master

**Comment by Glen206** [comment]
I have the same issue.

SuiteCRM 7.6.6
Chrome Version 51.0.2704.106 m (64-bit)

Database server
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.0.95 - Source distribution
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Web server
Apache
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - 
PHP extension: mysqli Documentation
PHP version: 5.5.36

**Comment by Glen206** [comment]
In my comment above I had stated my php version was 5.5.36 it is actually 5.4

Same issue still persists in newly updated SuiteCRM 7.7

**Comment by LewMegas** [comment]
We've experienced this problem since 7.0

**Comment by ijdavie** [comment]
This appears to be related to issue #1728 and a fix has been proposed #1964.
