### ISSUE TITLE
AOR - Asc/Des function break the Main Group view

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1617]
Hi,

On screen we see 2 issues: videoscreen http://screencast.com/t/BRKFNTgB6KI

1. The custom relationship shows instead of Name like LBL_PROJECT_UNSUR_RESERVATIONS_1_FROM_UNSUR_RESERVATIONS_TITLE and this is the issue for all custom modules of SuiteCRM in AOR

2. If you group by main group view and you choosed possibility none... the view working on ascending principe by default. But if you choose the Acending or Descending possibility from drop down of selected Main Group row.... this break the function of Main Group view. 

Version 7.6.3 / Chrome 52.0.2743.41 beta-m (64-bit)

**Comment by ijdavie** [comment]
1, This appears to work as expected in the latest version of SuiteCRM with the labels existing on custom relationships. 

2, This looks related to #1118
