### ISSUE TITLE
Ensure Site URL is used for all images link generation in email editors

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#1619]
This includes, via Campaign Wizard, Email templates (via the module and via the Email's windows) and Workflow Templates.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
