### ISSUE TITLE
Pagination bar in Emails 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#163]
Hi,

We have in system more as 1000 emails, but if i want go to history, the pagination nav bar is under layer which show the emails

http://screencast.com/t/JEWzNWCzBe

I think is css issue, but i didn't find the solution to fix it  :(

Miky

**Comment by dpalmerjr** [comment]
In the file /modules/Emails/javascript/complexLayout.js if you change line 54 from

				    scroll:false, // grid should autoScroll itself

To
				    scroll:true,

The nav bar appears and seems to work correctly.  I have played around with it on my server, but have not fully tested it yet.

Best Regards,

Darryl

**Comment by leenyx** [comment]
It's a css issue, the above solution didn't solve it for me.

I have changed the line 361 in EmailUI css file in the email module to the following:

#listViewDiv .pagination {
    margin: 2px 0px 20px 0px;
    padding-bottom: 20px;
    height: 30px;	
}

I can see the pagination now. This solution should be optimised as this is not upgrade safe, and the pagination doesn't display correctly either, but at least brings the functionality back.

**Comment by adriangibanelbtactic** [comment]
I confirm this bug happens in Suitecrm 7.4.

* When using: 'Classic' theme it does not happen.
* When using: 'Suite 7' theme the buttons are seen cut in half.
* When using: 'Suite R' (Default on raw Suitecrm install) the buttons are not seen as described originally in this bug.

We have not tested any of the workarounds mentioned in this bug yet.

**Comment by thiras** [comment]
I confirm too. 7.4.3 with default theme.

**Comment by blloyd78** [comment]
I can confirm that this remains a problem in SuiteCRM 7.7 using any of the supplied themes (Classic, P and R). None of the suggested CSS tweaks resolve the problem either.

**Comment by gunnerman1** [comment]
This is ongoing as of 7.8.8. 

I have tried the various css and js fixes listed online such as changing the .pagination margin from 20px to -20 to -50px which does bring back functionality in some cases however it is very dependent on browser and screen size.

Interestingly, (and I don't know why this happens) in Chrome while on the Email page, if I open the inspector and search for the pagination div and then click on  the <div class="pagination"> statement the pagination controls appear and function perfectly (responsive and positioned properly). I have not been able to track down what specifically causes it to appear properly so maybe someone with a better understanding of css and the Chrome inspector can enlighten us.

I hope we can find a fix soon, it has been frustrating our entire organization :(.

**Comment by Mausino** [comment]
@gunnerman1  i reported this problem 12 Mar 2015 👎  that's more as 2 and half year ago...  now it's coming new version of SuiteCMR 7.10... in this time it's in beta2 but will relased this or in january next year... 

@daniel-samson  in LTS 7.10 will use new email system of 7.9 or old one from 7.8 ??? because when i tested latest version.. there was the new email system with many bugs + errors and old email system has great stability. I am only asking.. if this issue has any sense to be open or should i close it after years?

**Comment by blloyd78** [comment]
None of the proposed workarounds work on the Safari browser.

The new email system in 7.9 is so unreliable I have rolled back to 7.8. Upgrading is _not_ a viable alternative.

**Comment by daniel-samson** [comment]
@Mausino I think you should leave it open for now. 7.8.x is also a LTS. It will be supported after 7.10 is released. So we will need to move the fix to hotfix-7.8.x. @Dillon-Brown can you please re assess this?

**Comment by Mausino** [comment]
@daniel-samson @Dillon-Brown thank you for you answer.. many user complain that the solution in this patch working only for some resolutions but in many cases not. I think that is not usable for now. I can't (wont) test it... because we fight with revamped email module. 

i'm thinking that is only 50% usable if compare to old one. but we believe and will give our heart for it, because is in good way and we believe that in LTS 7.10 will not have same headache as all we had when we moved on 7.9 revamped emails. 

It will for few days new year, and i wish that in new one will SuiteCRM go forward as now and will never stop and beats all commercial CRM softwares 🥇

**Comment by billlee76** [comment]
Hello All,
I suggest adding this to the bottom of your EmailUI.css  this way you dont modify any original code: This puts everything nicely on one line for you.
``#listViewDiv {
     margin-bottom: 10px;
}
 .pagination {
     margin: -5px 0;
}
 .paginator-start {
     height: 13px;
}
 .paginator-previous {
     height: 13px;
}
 .paginator-next {
     height: 13px;
}
 .paginator-end {
     height: 13px;
}

**Comment by blloyd78** [comment]
Does this proposed solution work for all themes, or just 'Classic'?
I have added the CSS, but the nav buttons are still missing on theme P.

**Comment by billlee76** [comment]
Ah. Sorry i just realized this was for theme R. I'll take a look at theme P.

**Comment by Mausino** [comment]
@samus-aran should i close this issue ? I asked maybe 5 times if will this moved to LTS 7.8.x version.. but without success. When new relase 7.11 will relased.. the life of 7.8 will ended and this ticket will have any addional sense. 

After 3,5 years of open status will find this ticket piece in closed issues 🌍

**Comment by samus-aran** [comment]
7.8.x will be receiving security fixes until the first couple of Qs in 2019 but I get where you are coming from.

https://github.com/salesagility/SuiteCRM/issues/163#issuecomment-356704295 <--- Is that a suitable fix?
Or is it this? https://github.com/salesagility/SuiteCRM/pull/2384 <---

**Comment by Mausino** [comment]
@samus-aran #2384 worked great.. sorry we are far away from 7.8.x version yet... https://github.com/salesagility/SuiteCRM/issues/163#issuecomment-356704295 is trying to solve issue with theme R didn't test this comment solution

we used only what gymad created @shogunpol
