### ISSUE TITLE
Change AOS Product Images to use an entry point

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#164]
Product images currently links directly to the image in the upload folder. This only works if SuiteCRM is configured poorly and the upload folder is accessible (i.e. the .htaccess files are being ignored). We should change the product image code to refer to the image via the download entry point.

**Comment by EZS-JD** [comment]
has this been fixed? It looks to me like the code _is_ referring to the image via the download entry point, but still getting 403 error and image won't show. (Suite 7.7.4)

**Comment by shogunpol** [comment]
@EZS-JD , "Fix Proposed" label means a pull request has been submit and need to be reviewed before be pulled in.

**Comment by aryeharmon** [comment]
still not fixed...

**Comment by Mausino** [comment]
@samus-aran @Dillon-Brown i think will great if we will see that will in new relase 7.10.12 

When we will have assigned milestones to tickets, we as community memebers can better expect what will come in next relases :)

What do you think about it?

**Comment by samus-aran** [comment]
Hey @Mausino This has been merged indicated by the label "Resolved Next Release" Which was part of the PR Party :tada: 
Regards to setting up milestones we are doing some housekeeping from the event and will be assigning all the issues that have this label "Resolved Next Release" to the 7.10.12 milestone :+1:

**Comment by Mausino** [comment]
@samus-aran 
> will be assigning all the issues that have this label "Resolved Next Release" to the 7.10.12 milestone 👍

Hi, should all "Resolved Next Relase" get the 7.10.12 milestone ? Only we wont forget on them.

**Comment by babington-andy** [comment]
Hey @Dillon-Brown @samus-aran from this issue thread it looks like this issue was fixed in 7.10.12, however the issue still appears to be present in 7.11.5. Is the fix going to be merged into 7.11.x too?

Many thanks,
Andy

**Comment by Dillon-Brown** [comment]
Hi @babington-andy, I've created a duplicate PR for this here: #7539. It will need to be re-assessed and code-reviewed before getting merged into the next 7.10.x and 7.11.x release.

**Comment by manrodriguezf** [comment]
Hi all,
At least with SuiteCRM 7.10.24, still can't access the image for a product.
Cheers

**Comment by samlau0086** [comment]
yet, not fixed on suitecrm 8
