### ISSUE TITLE
Mobile view - Activity stream missing "Post" button

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1641]
When in the mobile view, the Activity stream dashlet is missing the "Post" Button & Textfield:
![screenshot from 2016-06-22 15 36 00](https://cloud.githubusercontent.com/assets/13675281/16270686/168cb368-388f-11e6-836c-09bb87a9a395.png)

Found via Forum post: https://suitecrm.com/forum/suitecrm-7-0-discussion/9850-missig-post-button-in-my-activity-stream

**Comment by Dillon-Brown** [comment]
Unable to replicate on 7.10.2. Please re-open if this is still an issue you can replicate and we will investigate further. Thanks.
