### ISSUE TITLE
Permissions are breaking more in 7.6.4? Specifically, CSS files

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1655]
I hesitated before starting such a vague issue, but here it goes...

Recently the forums have been flooded with people (usually newbies) with problems that look to be the typical permissions issues:
https://suitecrm.com/forum/installation-upgrade-help/9713-new-install-no-theme
https://suitecrm.com/forum/installation-upgrade-help/9912-users-are-missing-css
https://suitecrm.com/forum/installation-upgrade-help/9819-after-installation-of-7-6-4-layout-destroyed
https://suitecrm.com/forum/suite-themes/9739-problems-with-the-theme
https://suitecrm.com/forum/suitecrm-7-0-discussion/9878-what-the-what
and here on Github:
https://github.com/salesagility/SuiteCRM/issues/1522
and this one maybe is a different issue, I don't know:
https://suitecrm.com/forum/suitecrm-7-0-discussion/9901-undefined-error-on-pop-up-screen

All of them (except the last) seem to be having permissions problems with CSS files. I didn't double-check, but I believe all of them (but some of them don't say) are with version 7.6.4. All of these threads were active in the past 3-4 days.

Unfortunately, none of them seemed sufficiently technically proficient for me to collect any usable information about the actual root of the problem. Most of the times I struggled to even get them to correct their permissions at all.

Questions: 
1. Did anything change in 7.6.4 that could justify these problems?
2. Can anybody reproduce this in a brand new installation and debug it?
3. Even if we can't find what's causing it, can we think of ways to mitigate it somehow? It seems to be causing a lot of grief, and driving adopters away.

I thought it would be useful to collect these threads here and call the attention of developers, but feel free to close this issue if you don't know what to do with it...

**Comment by mattlorimer** [comment]
the difference in 7.6.4 is that cache/themes is missing from the distribution package, but ultimately this issue is caused by no write permission to the cache folder. Which could be solved by including the cache/themes folder as is it meant to be or likley better not to include pre built cache files or folder so that it is created with appropriate permissions, and have a longer install process, but likely if your permission are wrong on cache they will be wrong elsewhere anyway

**Comment by pgorod** [comment]
I'm not sure of why all this happens, so I'm not sure which would be the best way to go.

But I think it would be positive to try and mitigate this somehow. **Two new threads** have popped up on the forums since I opened this ticket, I really think something made the installer more fragile in terms of permissions problems.

I have another personal experience to add. I created a new VM and installed Ubuntu server 16.04 (with PHP 7) from scratch. Then I downloaded SuiteCRM 7.7 Beta 2 Full Installer and unizpped the files into the web server directory.

I set all the ownerships and permissions correctly, and ran the installer.

When the installer finished (correctly, without errors) I was taken to a broken login screen: the CSS was correct, but the labels were all missing (I saw all strings as LBL_PASSWORD, LBL_USERNAME, etc).

I fixed the permissions again and everything was alright. 

So I wonder what could have gone wrong in the installer, or if this is a PHP7 problem, or what?...

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.3), and it not appear.
Can you try replicate this again on recent version of SuiteCRM(7.7.3).
Thanks for raise this issue.

**Comment by pgorod** [comment]
@shogunpol exactly what issue did you try to replicate? There are so many different things mentioned in this thread...

I am pretty sure we don't have a consistent handling of permissions in SuiteCRM. Just have a look at the forums. For me, this is the single greatest problem in SuiteCRM.

But it might be that this particular issue isn't helping much. I don't have a specific test case, so it's not easy to debug. **You can close this issue** if you want, if you don't know what to do with it...

But the problem is real, and very relevant. Maybe the best discussion is the one found on issue #1688. See my comment there on the 5th of July. (I see @ijdavie has assigned someone to that bug - that is really good news). Thanks.

**Comment by dhaupin** [comment]
Omg, cmon. This issue has existed since at least May 2016, which is 7 months ago. We just installed a new instance and guess what.... IT'S STILL THERE! Why was this not repaired and closed? There are obvious errors with those permissions when thrown against common stacks. Not sure how/why the devs are not able to reproduce the issue, it's super obviously there without a doubt, and there are enough people running into it to make it a valid concern IMO.

It's a 6 character fix in config:

493 is equal to 755 permissions for folders.

420 is equal to 644 permissions for files.

Not hard to push into release. Am I wrong?

**Comment by pgorod** [comment]
@dhaupin it's more complicated than that, I'm afraid.

Question: are you running your Scheduler jobs as root?

#2787

**Comment by dhaupin** [comment]
There are no scheduling jobs yet, this is a fresh install without any crons set. Upon extraction, everything's 777. When init installation, utils.php contains the default arrays prior to config.php's existence. So when I see a folder with "02770", and it's a public facing asset like JS/CSS, how is that supposed to work? Also, in a multi tenant env, or one that runs with isolation/cages, even Apache itself as "nobody" user can't access those folders.

I do believe that in a single app instance, with like no protections/securities/cages/isolations, perhaps on a localhost dev instance, that the permissions set by default *may* work. But in real world production instances, probably not. Too strict when ran under a real world schema.

**Comment by pgorod** [comment]
I see, this has nothing to do with cron. I'd like to understand your case a little better, please. 

Can you fill in some blanks for me? 

1. Upon extraction:
- dir permissions are ____
- file permissions are 777
- owner / group is  _____ /_____

2. After install (for the files with broken permissions):
- dir permissions are ____
- file permissions are ____
- owner / group is  _____ /_____

3. Your web server user/group is _____ / _____

4. Your umask is ____

I'm not sure I can help, but I'm investigating all this for quite a while and when I see a case (with a user that understands what he's talking about, as seems to be your case) I like to grab on to it : - ) I am determined to get all this solved.

(BTW - the numbers you specified, 493, 420 - we don't need to use decimal, in PHP a leading 0 means the number is octal, so 0755 and 0644 would suffice and be more human-readable).

**Comment by pgorod** [comment]
@dhaupin this has been a while and I assume you're not facing this problem anymore and are no longer in a position to give me the details I asked for. 

There are other Issues involving efforts to improve permissions handling, maybe this one won't add much to the discussion. Is it ok with you if I close this issue?
