### ISSUE TITLE
Image field and Required setting

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#166]
If you add an image field and set it to required, and add an image, the record doesn't save as it does not pick up the image field/value is set.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email view issue if to much attachments](https://trello.com/c/Rxwp4duH/91-email-view-issue-if-to-much-attachments)

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email view issue if to much attachments](https://trello.com/c/Rxwp4duH/91-email-view-issue-if-to-much-attachments)
