### ISSUE TITLE
Option "View Change Log" on edit button in detailview is missing on calls, tasks, meeting and notes modules

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#1660]
eg: In contacts module "View Change Log" option exists in the dropdown for the edit button on the detailview:

![desktop1-08-2016-06-27](https://cloud.githubusercontent.com/assets/6874136/16397061/662984d4-3c7f-11e6-9abf-8259c0f8f42f.png)

But the option is missing on calls, tasks, meeting and notes modules detailview:

![desktop1-09-2016-06-27](https://cloud.githubusercontent.com/assets/6874136/16397060/6627450c-3c7f-11e6-9792-2e0d0c76e37b.png)

It's the expected behaviour?
Can it be activated?
It's a bug?

Regards

**Comment by ijdavie** [comment]
This from what I can see is expected as these modules appear to be not audit enabled, which is why this option is not in the list,
If you wish to activate this option for these modules please refer to the SuiteCRM Forums for help.
