### ISSUE TITLE
Reports empty if conditions strings for aor_sql_operator_list are translated

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1662]
If you translate strings for aor_sql_operator_list in \include\language\xx_XX.lang.php reports with conditions will be empty.
All languages with this strings translated (tested on the values "LIKE") are affected by this. Note: didn't verified all conditions and operator lists! Confirmed in several versions and installations.
**So its a major bug on reports working with conditions on non english language.**

_Test using latest SuiteCRM 7.7 Beta 2 with demo data installed:_ 
1- Use any language pack or edit the english one!
2- Go to \include\language\xx_XX.lang.php 
3- Check lines 3315 if the value of LIKE operator is actually translated (as in COMO or Enthält)

english value is
```
$app_list_strings['aor_sql_operator_list']['Contains'] = 'LIKE';
$app_list_strings['aor_sql_operator_list']['Starts_With'] = 'LIKE';
$app_list_strings['aor_sql_operator_list']['Ends_With'] = 'LIKE';
```
change to a translated value
```
$app_list_strings['aor_sql_operator_list']['Contains'] = 'COMO';
$app_list_strings['aor_sql_operator_list']['Starts_With'] = 'COMO';
$app_list_strings['aor_sql_operator_list']['Ends_With'] = 'COMO';
```

4- Create a report for contacts (first and last name)
![reports_fileds](https://cloud.githubusercontent.com/assets/3055443/16411053/29f840ce-3d1d-11e6-81d5-c0e34867aefb.png)

5- Create a condition (last name must contain "Melchor")
![reports_conditions](https://cloud.githubusercontent.com/assets/3055443/16411060/379fabd6-3d1d-11e6-84bb-9cb1d1e2bcec.png)

6- Save report
7- It will be empty if aor_sql_operator_list is translated!
![reports_empty](https://cloud.githubusercontent.com/assets/3055443/16411152/92b3d4f2-3d1d-11e6-9714-48b54ebb6ac1.png)

If no translation and its fine:
![reports_ok](https://cloud.githubusercontent.com/assets/3055443/16411099/5e2b8022-3d1d-11e6-84e1-7fb4132ce5a0.png)

Forum topic related:
https://suitecrm.com/forum/international-language-support/8276-german-language-pack-reports-not-working-correct#34075

**Comment by horus68** [comment]
Possible duplicated from: 
Major BUG: AOR Reports seems to use translated strings in query, query fails · Issue #1451 · salesagility/SuiteCRM - https://github.com/salesagility/SuiteCRM/issues/1451

**Comment by horus68** [comment]
I need to know what to do before next release:
- Will you fix it or 
- Do I have to make a "dirty hack" and disable those strings in translations so people do not have do edit their language packs?

**Comment by horus68** [comment]
Requesting labels for this: Bug + High Priority
Bug confirmed by many users, reports function will not work for any full translated language, so this should be considered a "release stopper"

**Comment by horus68** [comment]
Requesting labels for this: Bug + High Priority
Bug confirmed by many users, reports function will not work for any full translated language, so this should be considered a "release stopper"

**Comment by pgorod** [comment]
I think @samus-aran needs a mention here or else she won't see your request, she's not a participant in this issue so the notification emails aren't going out to her. FTFY.
