### ISSUE TITLE
MSSQL query Error

### ISSUE THREAD

**Issue by sathishsengodan** [salesagility/SuiteCRM#1664]
The below errors were found in the logs when used with MSSQL. SuiteCRM version 7.6.4

    Query Failed: SELECT TOP 20  [accounts].name AS N'Name0' FROM [accounts]  WHERE ( [accounts].name LIKE CONCAT(N'test' ,N'%') ) AND  accounts.deleted = 0 : SQL Server error: 'CONCAT' is not a recognized built-in function name.
    Query Failed: SELECT id FROM aor_charts WHERE aor_charts.aor_report_id = N'14c47175-5ef0-5a1c-89fc-57726b88fae3' AND aor_charts.deleted=0: SQL Server error: 'CONCAT' is not a recognized built-in function name.

**Comment by gunnicom** [comment]
Just as additional Info:
"CONCATdoesn't exist in SQL Server 2008, it is new since SQL Server 2012."
( http://stackoverflow.com/questions/8547737/sql-server-2008-express-concat-doesnt-exist )

**Comment by sathishsengodan** [comment]
This appears to be fixed now.
