### ISSUE TITLE
SuiteP Theme - Suggestions

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1665]
![crm1](https://cloud.githubusercontent.com/assets/5773777/16419899/a56f0b5c-3d4f-11e6-9aab-be379b0dab09.png)
![crm2](https://cloud.githubusercontent.com/assets/5773777/16419904/aa2c61da-3d4f-11e6-9854-4fc8e42d8112.png)

**Comment by samus-aran** [comment]
:+1: Thanks @Mausino for your feedback.  As this is still being implemented so some areas are unfinished i.e. like the pagination colour etc.  The more feedback the better understanding of what the community wants in regards of the new theme. :star:

**Comment by pribeiro42** [comment]
Hello all, after trying this theme, i got the impression is very much "touch-oriented" and for people with fairly large fingers :smile: ... I would like to have less height on the buttons and inputs.. Right now, they have ca. 40px, i suppose a 30px height wouldn't hurt... 
Also some elements don't work well (at least with firefox), e.g., the "Edit" buttons on the sub-panel rows, with the drop-down menu, make the page jump continuously to the top. so its impossible to open the button drop-down... 
Overall the theme design is fine, but there's a sense of.... "something not quite right".. i really don't know how top explain better, maybe its the overall size of the inputs or something....

**Comment by pgorod** [comment]
I also agree the spacing is excessive. I value screen space. I understand it's a trade-off, mobile users need to be able to press buttons, but anyway the SuiteR setting for this was better, imho.

The screens to select a contact, select an account, etc. look terrible, they amplify this spacing issue and fill the screen with search fields instead of letting the user understand he's supposed to be looking at a list of items.

Anyway, in general, I like the new theme and the typography looks much better! Congratulations!

**Comment by gregsoper** [comment]
Understand first: THIS IS A BETA RELEASE. There is more work before it goes in to Production. Lots of stuff isn't right yet. That's the purpose of a Beta Release.

Understadn second: We know that there is no design in the world that is going to please everyone. It's an impossible task. Everyone with a dog in the fight is going to have an opinion. The beauty of open source is that you're free to modify it to suit your needs. And if you improve it and contribute it back to the project then everyone wins.

**Comment by Mausino** [comment]
@gregsoper :) we want help you only with practical advices :) nowbody cares abou colors or something like this.... we are users, and we use this every day :) that is reason why we have some opinions on functionality... We know that is beta2... it's right time to show what is wrog before will stable version. 

You all from salesagility did awesome work and you are changing the world of CRM systems :)

**Comment by pgorod** [comment]
To keep this at a very generic level, if the theme is responsive, and the CSS includes clauses to change the design according to screen size, that can be applied to padding and spacing also. So we could have a design with larger buttons for mobile and one that makes better use of screen space for desktops.
Maybe those could be useful theme options: padding for mobile, padding for desktop.

I know how to tweak these things and customize them in my system, so if I'm talking about this here it's to discuss whether they would be good options for the project as a whole. As Greg said, you can't get people to agree on design. Let the designers decide, it's their "baby". My sole purpose is to throw some ideas at them to see if they find them interesting. : - )

**Comment by pribeiro42** [comment]
@gregsoper It was no intention of mine to disregard or diminish your excelent work on this platform, you guys are doing a terrific job, please carry on... About the design, of course you can't please everyone, i was only giving my feedback, consideering this is a Beta, it's the proper time to say something.. easier now than to wait for the release. I also agree with @pgorod that we know that we can tweak the theme to suit our needs, we are just giving some ideias for the "Default" configuration...

Cheers,

**Comment by gregsoper** [comment]
Thank you each for your support!!

I wanted to make sure that this did not become a discussion about design. @pgorod is correct. Let the designers decide. I sincerely hope we give you a far better design than the current one. And I also would really welcome any contributions that improve it. But the design is what it is.

**Comment by pgorod** [comment]
To add something that is related to this spacing issue, but is more of a **functional problem** (not just aesthetics), the responsive-design top menu is collapsing into its compact form (showing the "hamburguer Menu" instead of each menu option) way too soon, in terms of screen width. 

Anything below 1280px collapses to "mobile" mode. Anybody with smaller screens, or who isn't working with a maximized browser window, will get the crippled (well... condensed) menu. 

I believe window widths of at least 1024 pixels should be guaranteed to get the full menu, and I would say even below that (basically, keep the full menu in as small a window as possible). Remember not everybody maximizes their windows on desktops.

**Comment by gregsoper** [comment]
@pgorod ... with respect ... wait for the production release .. we are still working on it :-)

**Comment by chris001** [comment]
@gregsoper Highest respect for Sales Agility and SuiteCRM 7.7b2!
Back on topic, here's a cool reference page to draw CSS code from, for the new SuitePea responsive template design, while I suppose the designers maybe already are aware of it, so I'll include this link in case the others on this gihub issue conversation would like to learn and enjoy...

Google material design metrics and keylines incl baseline grids, spacing, ratios, sizing, touch target size...
https://material.google.com/layout/metrics-keylines.html

Free license MDB material design bootstrap UI kit for bootstrap 3 or 4:
http://mdbootstrap.com/material-design-for-bootstrap/

Material Design Lite components from Google with free Apache license... easy to fork on github..
https://github.com/google/material-design-lite

**Comment by gregsoper** [comment]
@chris001 Thanks Chris. I'll pass those references around the team so if they weren't aware of them .. they will be now :-)

**Comment by samus-aran** [comment]
Hi Everyone!

With the production has been release I am closing this github 'issue'  What I would suggest is create a thread in the forum as there we can have more of a conversation of your experience and areas you feel requires improvements.

https://suitecrm.com/forum/suite-themes/10405-suite-7-7-feedback
