### ISSUE TITLE
Wrong colors in settings of SuiteP theme (SuiteCRM 7.7 beta2)

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1666]
Hi, there are the wrong colors in settings, more in videoscreen: http://screencast.com/t/GomFJ6OB

![suitep](https://cloud.githubusercontent.com/assets/5773777/16420849/329b276a-3d53-11e6-83c9-26c95a0dbf0f.png)

**Comment by Mausino** [comment]
The problem is persisting also in SuiteCRM 7.7 RC2

**Comment by ghermans** [comment]
This bug is also in the 7.7 release. i really don't understand why this hasn't been fixed before releasing it

**Comment by shogunpol** [comment]
The colour picker from version 7.7.3 does not exist any longer in Suite P theme, this maybe something we will introduce in the future.
Since functionality will doesn't exist, this issue will be closed?
@Mausino , thanks for your contribution.
