### ISSUE TITLE
'Leads created bar' on the Campaign status view not increasing

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#1671]
Given you create Leads / Leads created from Web-to-form and the Leads are associated to the Campaign.......the Leads Created bar on the chart does not increase.

![image](https://cloud.githubusercontent.com/assets/6104874/16448836/77f70e26-3deb-11e6-8852-2363e7546c08.png)

![image](https://cloud.githubusercontent.com/assets/6104874/16448828/6a0f25aa-3deb-11e6-9a57-3d00bd917ceb.png)

**Comment by ijdavie** [comment]
It is worth noting that along with the relationship not being generated the date was also not populating as you would expect.
