### ISSUE TITLE
"Created by contact" column in list view is always blank

### ISSUE THREAD

**Issue by edman545** [salesagility/SuiteCRM#1674]
I added the "created by contact" field to the search options in the cases module, and the column to the list view.  The column is always blank in list view.

I built an instance of suitecrm on a windows/iis/PHP/mssql platform and also on a LAMP server, and the issue exists on both servers.

Currently running a clean install of 7.6.4 build 1061

![list](https://cloud.githubusercontent.com/assets/17354206/16456274/68f080ac-3de5-11e6-98dc-f4f05e41409c.png)
![detail](https://cloud.githubusercontent.com/assets/17354206/16456275/68f10b62-3de5-11e6-94f0-3ab79ce9d344.png)

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open this issue if you are able to replicate and provide clear steps for this issue. Thanks.
