### ISSUE TITLE
Error When Duplicate Campaign 7.6.4

### ISSUE THREAD

**Issue by deftaxias** [salesagility/SuiteCRM#1687]
Hi,

When trying to duplicate a campaign in 7.6.4 i am getting Bad data passed in; Return to Home

Anyone else has the same problem?

Thanks
DE

**Comment by willrennie** [comment]
I do not receive this error. I would suggest that you look to post your issue with more details and possible server/CRM log files/data on the forums as this does not appear to be a code bug but most likely a setup/configuration issue.
