### ISSUE TITLE
HTTP 500 error on upgrade or new install of 7.2

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#169]
Hosting control panel has tightened up security.  +FollowSymLinks is forbidden, replaced by +SymLinksIfOwnerMatch.  Upgrade to 7.2 or new install of 7.2 overwrites this change.

See also

https://www.drupal.org/node/1269780
https://my.bluehost.com/cgi/help/search?sort=&search=SymLinksIfOwnerMatch
https://my.hostmonster.com/cgi/help/htaccess
http://www.virtualmin.com/node/24260

Proposed solution:
Change to +SymLinksIfOwnerMatch in core installer and upgrade code.

More info:
http://blog.sucuri.net/2013/05/from-a-site-compromise-to-full-root-access-symlinks-to-root-part-i.html

Shared hosting is still a mass market and as more and more sharehosters disable +FollowSymLinks for good reasons.
So in fact
- +SymLinksIfOwnerMatch is the evolving option you can safely rely on
- +FollowSymLinks you can not rely on and if you need it you know what to do.

Here is the PR to fix this issue.
https://github.com/salesagility/SuiteCRM/pull/137

**Comment by willrennie** [comment]
Is this issue still valid?

**Comment by chris001** [comment]
@willrennie  Yes.  Just change the PR from master to hotfix.

**Comment by Mausino** [comment]
This issue is closed by wird way because the github still think that is open.. I am not sure if is our problem of way how was closed the issue or it will GITHUB issue 

https://github.com/salesagility/SuiteCRM/issues?page=5&q=is%3Aopen+label%3A%22Fix+Proposed%22+label%3Abug look as last in pagination
