### ISSUE TITLE
Products and Line items for Contracts in 7.2.1

### ISSUE THREAD

**Issue by ehsulve** [salesagility/SuiteCRM#170]
We are using Products in our environment and we are using Line Items.
When you are going to create a Contract, the Line Items section should be empty and it should not show any Products. 
In the Line Items section, you should be able to select one or several Products and then Save. 

As it is now in 7.2.1, the Line Items-section is pre-populated with many Products. We assume this is a bug.
![line_items_721](https://cloud.githubusercontent.com/assets/11499265/6663307/ababa928-cbc5-11e4-8ef9-56f826db8aec.png)

**Comment by ehsulve** [comment]
This is the same bug as described here: https://salesagility.com/forum/8-aos-5x/3283-bug-new-aos-contracts-shows-groups-by-default.

**Comment by ehsulve** [comment]
This is the same bug as described here: https://salesagility.com/forum/8-aos-5x/3283-bug-new-aos-contracts-shows-groups-by-default.

**Comment by himingby** [comment]
The bug is in 7.1.1 and 7.1.5. which release is ok?

**Comment by himingby** [comment]
With AOS 5.3.3: when creating a new Contract, the empty Contract already shows a number of Groups and Line_items. I can see the same happening in the SuiteCRM demo 7.1.3.

This behaviour is caused when you delete a Contract with one or more Line items in it, without deleting the Line items first.
Deleting the Contract, causes the parent_id of the line item in aos_products_quotes to be deleted (no value: '').

The query in 'modules/AOS_Products_Quotes/Line_Items.php' doesn't take in account that a new Contract doesn't have a unique id yet, so this id is '' as well. Hence, the line items (including groups) of a deleted Contract are shown on every new contract.

There are 2 solutions:
1. The right one: making sure Groups and line items are set to deleted = 1 when deleting the parent. I couldn't make a solution for this.
2. Fixing the symptoms: changing the query, so line items with an empty parent_id aren't shown. Change row 59, and add "AND pg.parent_id <> '' " before "AND pg.deleted = 0".

--
It is a good way, I changed the Line_item.php, now it is ok.
