### ISSUE TITLE
AOR Report Dashlet date parameters wont work

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1700]
#### Expected Behavior

If you put a report in a dashlet with date parameter you should be able to change them.
#### Actual Behavior

If you change the parameter in the dashlet they wont be taken. Sometimes the result is empty after changing, sometimes it displays all rows without filter.
#### Possible Fix

Dont know.
#### Steps to Reproduce

Make a report.
Add one or more date field Parameters.
Add this Report as Dashlet to homepage.
Change date parameter value in dashlet.
#### Context

Reporting is totally broken not only in dashlets.
#### Your Environment
- SuiteCRM Version used: 7.6.4, 7.7beta2
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 47
- Environment name and version (e.g. MySQL, PHP 7): PHP 5.6
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 15.10

All in all it is not good that suitecrm concentrates on a new theme or a new reporting tool, or a new issue template, and leaves hundreds of bugs lying around for month. The template makes more work for bug reporters, and then the bugs wont get fixed, and then the frustration is higher because of the more work for open a new issue.

**Comment by gunnicom** [comment]
Maybe fixed, or at least partial fixed by https://github.com/salesagility/SuiteCRM/pull/1710

**Comment by recci** [comment]
If you use greater than or less than as the param it works fine. The problem on seem to occur with equal to because in the report it could be a date and time field but in the parameters you can only add it as a date field. So therefore its only possible to fix this by adding date & time field to the report params. Not sure if this make this bug null and void.

**Comment by vladbar** [comment]
Latest commit after some testing done by our Support Team.
