### ISSUE TITLE
AOP assign to contacts assigned user

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#171]
It would be nice if there was a feature to assign a case to the same user as the assigned user for the contact creating the case.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AOP assign to contacts assigned user](https://trello.com/c/XMdANF7c/159-aop-assign-to-contacts-assigned-user)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
