### ISSUE TITLE
SugarWebServiceImplv4.php and SugarWebServiceUtilv4.php have missing parameters across service versions.

### ISSUE THREAD

**Issue by maxrandolph** [salesagility/SuiteCRM#1714]
There are function declaration warnings that throw off the api calls returning JSON correctly formatted.
#### Expected Behavior
There shouldn't be any warnings.
#### Actual Behavior
There are warnings interfering with requests if php.ini file has not been configured to suppress warnings.

#### Possible Fix
give default declarations to those functions that are uniform across version of service being used.
#### Context
Trying to use SuiteCRM API and encountered warnings that confused json_decode()

[fixed_declarations.zip](https://github.com/salesagility/SuiteCRM/files/350900/fixed_declarations.zip)

**Comment by shogunpol** [comment]
This appearance is appears to be related to #942
If you will like include the fix code for us, please create pull-request back to project.

**Comment by pgorod** [comment]
@maxrandolph could you please make that PR so we can more easily see the diffs between your code and the current code? Or explain a little better here exactly what warnings you get and how you fixed them?

I'm trying to list all of these declaration warnings so we can fix them properly in this issue #942 , I guess your suggestion could help in this effort. Thanks.
