### ISSUE TITLE
V. 7.6.3+ Dashlet Chart: "All Opportunities by Lead Source" shows values instead of labels

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#1723]
#### Issue

Hi in V. 7.6.3, 7.6.4 and 7.6.5 i've just found that the Dashlet: "All Opportunities by Lead Source" (you can see it in the Chart tab)
shows values instead of labels in the legend square.

![image](https://cloud.githubusercontent.com/assets/2909933/16734690/b84e580e-4786-11e6-9ecd-a51a5c7d1ea4.png)

![image](https://cloud.githubusercontent.com/assets/2909933/16734708/cb1ee82c-4786-11e6-96be-9e808f766bb6.png)
#### Your Environment

- SuiteCRM Version used: SuiteCRM 7.6.3, 7.6.4, 7.6.5
#### Afterword

I opened a topic here:  [https://suitecrm.com/forum/installation-upgrade-help/10100-v-7-6-3-dashlet-chart-all-opportunities-by-lead-source-shows-values-instead-of-labels#34604](url)
User **mikebeck** confirmed this behaviour

**Comment by horus68** [comment]
Correct forum URL
https://suitecrm.com/forum/installation-upgrade-help/10100-v-7-6-3-dashlet-chart-all-opportunities-by-lead-source-shows-values-instead-of-labels#34604

**Comment by 604media** [comment]
Can you please anyone help me on this - Why my fixes are not displaying in related issue?
For now I'm pasting this URL manually
#1837

**Comment by horus68** [comment]
using your PR link here: https://github.com/salesagility/SuiteCRM/pull/1837
