### ISSUE TITLE
new code committed use obsolete function mime_content_type

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#1725]
problem upgraded to 7.6.5 download.php line 174 contains obsolete content that breaks functionnality of existing system 
problem also occurs on SuiteCRM 7.7 Beta 2

**as reported by the French, German and Russian,Spanish php manual page (but not by the english version ???)**
http://php.net/manual/fr/function.mime-content-type.php
in the notes you will find:
---
Avertissement
Cette fonction est obsolète, vu que l'extension PECL Fileinfo fournit la même fonctionnalité (et bien plus) de façon plus claire.
---
but this warning does not appear in the english version

So the document.php file lines 173 to 176 contains:
`
        // Fix for issue 1506 and issue 1304 : IE11 and Microsoft Edge cannot display generic 'application/octet-stream' (which is defined as "arbitrary binary data" in RFC 2046).
        $mime_type = mime_content_type($local_location);
        if($mime_type == null || $mime_type == '') {
            $mime_type = 'application/octet-stream';
        }`

**Running this on my php 5.6 environment gave me error 500 on the page** and in php error log:
[11-Jul-2016 13:21:31 America/New_York] PHP Notice:  Undefined offset: 1 in C:\inetpub\wwwroot\weblive\download.php on line 110
[11-Jul-2016 13:21:31 America/New_York] PHP Fatal error:  Call to undefined function mime_content_type() in C:\inetpub\wwwroot\weblive\download.php on line 174

I switched download.php from previous version and the problem went away, but most likely bugs/issue  issue 1506 and issue 1304  are not resolved on my instance...

#### Possible Fix
 I am not at ease to replace the code with finfo as suggested in php manual...

#### Steps to Reproduce
Happened on my updated SuiteCRM  environment and (after/debugging) on a fresh test install...

* SuiteCRM Version used:7.6.5
* Browser name and version (e.g. Version 51.0.2704.103 m 
* Environment name and version (e.g. PHP 6.7, MSSQL
* Operating System and version windows server 2008 r2 IIS

**Comment by pribeiro42** [comment]
Well, according to the language status pages, at least three of those languages have their translation outdated. Also, in the manual page http://php.net/manual/en/fileinfo.installation.php it says that, on Windows, the users must check if the dll php_fileinfo.dll is included on the php.ini file.

I guess this last item should be your problem....

**Comment by bmwtourer** [comment]
Thank you Pedro
so I am confused... I did enabled the php_fileinfo.dll and reverted to  "problematic" download.php with the new add ons and the problem is gone.  :-)

So does this mean that the function mime_content_type is in this dll? 
what is relation between this dll and the function mime_content_type *which is not the finfo replacement as recommened from the php french manual page*. 

But the more I read the more confused about this...
Should we still use this function or better practice would get us to move on the new finfo function...

**Comment by samus-aran** [comment]
But would it be best practise as the function isn't obsolete doesn't look like it will be in the current PHP packages PHP7+.  Looking into it the PECL extension it has updated how it packages up it's magic files (which is used to get mime_content_type).  
http://php.net/manual/en/fileinfo.installation.php
Something to consider updating in our installation documentation.
