### ISSUE TITLE
Upgrade from 7.6.4 to 7.6.5 fails

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#1726]
I'm getting the following error while performing the upgrade to 7.6.5:

`Thu Jul  7 13:27:48 2016 [8256][1][FATAL]  Query Failed: ALTER TABLE alerts   modify COLUMN subscribers varchar(65534)  NULL : MySQL error 1074: Column length too big for column 'subscribers' (max = 21845); use BLOB or TEXT instead`

#### Your Environment

* SuiteCRM Version used: 7.6.4 to 7.6.5
* MySQL 5.7.12-0ubuntu1 - (Ubuntu) Server charset: UTF-8 Unicode (utf8)
* PHP version: 7.0.8-3+deb.sury.org~xenial+1
* OS: ubuntu 16.04

**Comment by samus-aran** [comment]
@tfreier  on a fresh instance of 7.6.4 to 7.6.5 there is no subscribers column for alerts.  Is that from your upgradewizard.log?

**Comment by tfreier** [comment]
@samus-aran the error was from the sugarcrm.log. The SuiteCRM instance is from 5 years ago and was kept up to date. So I assume it's far from being a fresh install... :)

The upgradeWizzard.log shows this:

`
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: save files...
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: Remove files...
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: upgrade removal will remove: custom/Extension/modules/Schedulers/Ext/ScheduledTasks/AODScheduler.php
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: upgrade removal will remove: custom/Extension/modules/Schedulers/Ext/ScheduledTasks/AOPScheduler.php
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: upgrade removal will remove: custom/Extension/modules/Schedulers/Ext/ScheduledTasks/AORScheduler.php
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - upgrade custom cleanup: debug: upgrade removal will remove: custom/Extension/modules/Schedulers/Ext/ScheduledTasks/aow_workflow.php
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - Upgrading the database from 6.5.23 to version 
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - Running SQL file /var/www/crm/public_html/cache/upgrades/temp/LUagd0/scripts/65x_to__mysql.sql
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - *** ERROR: Schema change script [/var/www/crm/public_html/cache/upgrades/temp/LUagd0/scripts/65x_to__mysql.sql] could not be found!
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - Rebuilding JS Langauages
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - Rebuilding Dashlets
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - At updateVersions()... updating config table and sugar_version.php.
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - *** ERROR: no sugar_version.php file location found! - cannot complete upgrade...
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - rebuild grouping js files..
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - unlink: cache/include/javascript/sugar_grp1.js
Thu, 07 Jul 2016 12:58:15 -0500 [UpgradeWizard] - cwd: /var/www/crm/public_html
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - Performing UWrebuild()...
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - UWrebuild() done.
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - post_install() done.
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - check if current_db_version in $_SESSION equals target_db_version in $_SESSION
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - finished check to see if current_db_version in $_SESSION equals target_db_version in $_SESSION
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - running deleteChance() function
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - running deleteCache() function
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - call addNewSystemTabsFromUpgrade(upload://upgrades/patch/SuiteCRM-Upgrade-7.6.x-to-7.6.5-restore)
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - check to see if new modules exist
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - new modules to add are array (
)
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - module tabs updated
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - finished addNewSystemTabsFromUpgrade
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - Registering upgrade with UpgradeHistory
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - Resetting error_reporting() to system level.
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - Rebuilding style js file: cache/themes/SuiteR/js/style-min.js
Thu, 07 Jul 2016 12:58:19 -0500 [UpgradeWizard] - Rebuilding language cache
Thu, 07 Jul 2016 12:58:23 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 12:58:25 -0500 [UpgradeWizard] - [At end.php]
Thu, 07 Jul 2016 12:58:25 -0500 [UpgradeWizard] - About to repair the database.
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - [At commit.php]
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - Setting error_reporting() to E_ERROR while running upgrade
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - Resetting error_reporting() to system level.
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - Rebuilding style js file: cache/themes/SuiteR/js/style-min.js
Thu, 07 Jul 2016 13:01:00 -0500 [UpgradeWizard] - Rebuilding language cache
Thu, 07 Jul 2016 13:01:03 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:01:05 -0500 [UpgradeWizard] - [At end.php]
Thu, 07 Jul 2016 13:01:05 -0500 [UpgradeWizard] - About to repair the database.
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - [At commit.php]
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - Setting error_reporting() to E_ERROR while running upgrade
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - Resetting error_reporting() to system level.
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - Rebuilding style js file: cache/themes/SuiteR/js/style-min.js
Thu, 07 Jul 2016 13:08:10 -0500 [UpgradeWizard] - Rebuilding language cache
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - [At commit.php]
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - Setting error_reporting() to E_ERROR while running upgrade
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - Resetting error_reporting() to system level.
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - Rebuilding style js file: cache/themes/SuiteR/js/style-min.js
Thu, 07 Jul 2016 13:14:14 -0500 [UpgradeWizard] - Rebuilding language cache
Thu, 07 Jul 2016 13:16:47 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:16:48 -0500 [UpgradeWizard] - [At end.php]
Thu, 07 Jul 2016 13:16:48 -0500 [UpgradeWizard] - About to repair the database.
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - [At commit.php]
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - Setting error_reporting() to E_ERROR while running upgrade
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - Resetting error_reporting() to system level.
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - Rebuilding style js file: cache/themes/SuiteR/js/style-min.js
Thu, 07 Jul 2016 13:27:42 -0500 [UpgradeWizard] - Rebuilding language cache
Thu, 07 Jul 2016 13:27:45 -0500 [UpgradeWizard] - setting session variables...
Thu, 07 Jul 2016 13:27:47 -0500 [UpgradeWizard] - [At end.php]
Thu, 07 Jul 2016 13:27:47 -0500 [UpgradeWizard] - About to repair the database.
`

**Comment by samus-aran** [comment]
@tfreier  - still looking into this as we are unable to see where the schedulers field is being used for alerts.  Are you able to post the structure of your alerts table incase there is more customisations we are unaware of.

**Comment by tfreier** [comment]
No problem. 

`
--
-- Table structure for table alerts
--

CREATE TABLE alerts (
  id char(36) NOT NULL,
  name varchar(255) DEFAULT NULL,
  date_entered datetime DEFAULT NULL,
  date_modified datetime DEFAULT NULL,
  modified_user_id char(36) DEFAULT NULL,
  created_by char(36) DEFAULT NULL,
  description text,
  deleted tinyint(1) DEFAULT '0',
  assigned_user_id char(36) DEFAULT NULL,
  is_read tinyint(1) DEFAULT NULL,
  target_module varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  url_redirect varchar(255) DEFAULT NULL,
  content_type varchar(255) DEFAULT NULL,
  delivery_datetime datetime DEFAULT NULL,
  was_sent tinyint(1) DEFAULT '0',
  send_email tinyint(1) DEFAULT '0',
  send_popup tinyint(1) DEFAULT '0',
  send_sms tinyint(1) DEFAULT '0',
  send_to_manager tinyint(1) DEFAULT '0',
  target_module_id char(36) DEFAULT NULL,
  subscribers mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

Also, I think it's worth noting that my alerts table is completely empty. So if any columns aren't supposed to be there I could probably remove them manually but I'm not sure what impact that would have and whether I would need to adjust php files as well. 

Thank you so much for your help!

**Comment by tfreier** [comment]
UPDATE:

I did some more testing and it turns out that changing the type for the subscription column from varchar to text in modules/Alerts/vardefs.php fixes the issue. However, I don't know if that's the best solution to properly fix the issue.

**Comment by tfreier** [comment]
I guess since this is not part of a standard install and I was able to resolve it on my end I will close this issue.
