### ISSUE TITLE
Graph name is messed with graph graphic + bar graph width

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1734]
#### Issue

The name of graph is over the graph graphic + bar graph tooks  max 75% of width of report page

![firmy](https://cloud.githubusercontent.com/assets/5773777/16777680/c6c7cc82-486a-11e6-8516-c064aef4eb1e.png)

![firma2](https://cloud.githubusercontent.com/assets/5773777/16777686/ce091104-486a-11e6-997a-efe9b20e20bc.png)
#### Expected Behavior

Name of Graph --> space (one or 2 rows) --> graph graphic
#### Actual Behavior

The chart name is mainly for pie chart hard readable
#### Possible Fix

Space between Name of graph and graph graphic
Maybe it has something with this reported issue #1563
#### Your Environment

- SuiteCRM Version used: 7.6.5
- Browser name and version: Verzia 52.0.2743.60 beta-m (64-bit)
- Environment name and version: MySQL 5.6, PHP 5.6
- Operating System and version: Linux on hosting (more i don't know)

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
