### ISSUE TITLE
Inline editing does't work correct with dropdowns and currency fields

### ISSUE THREAD

**Issue by DanielsCode** [salesagility/SuiteCRM#1749]
I had installed SuiteCRM 7.5.1 and had a problem with inline editing in list/edit views of dropdown fields.  I found this closed issue: https://github.com/salesagility/SuiteCRM/issues/492 and had the hope that SuiteCRM 7.5.6 will fix it. But with 7.5.6 I got the following:

#### Issue
Inline editing doesn't save the values of dropdowns and currency fields in e.g. listview 

#### Expected Behavior
After inline editing (double click, select/enter new value, press enter or click the check icon) the field should have this new value.

#### Actual Behavior
After inline editing (double click, select/enter new value, press enter or click the check icon) the field will be cleared and it's empty. There is also sending a notification via mail (this happens after the update to 7.5.6 - it is realy annoying). If I use the normal edit mode then everything works. 

#### Possible Fix
No idea. I am happy for any ideas to fix the inline edititng bug and the mail notification. Thanks in advance

#### Steps to Reproduce
1. Go to opportunitites 
2. Double click a field like sales stages in list view
3. Select new value
4. Save it (enter or check icon)

Further information: I modified the dropdown values with my custom ones.

#### Context
For me this is a high priority. Because I would like to use this feature a lot to update my records.

#### Your Environment
* SuiteCRM Version used: 7.5.6 (updated from 7.5.1)
* Browser name and version: FireFox 45.2.0
* Environment name and version: PHP 5.3.10, MYSQL 14.14 
* Operating System and version: Ubuntu 12.04.5 LTS

**Comment by 604media** [comment]
@DanielsCode - Seems inline editing issue with dropdown value has been fixed in https://github.com/salesagility/SuiteCRM/issues/492 and its working fine SuiteCRM 7.7

For Currency field I'm adding the fix here 
#1879
