### ISSUE TITLE
What is bug 8242

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1771]
#### Issue

in the file   include/language/jsLanguage.php
there is a comment to bug 8242 - non-US langpack chokes
1- What bug is this? 
2- Is it from Sugar or SuiteCRM? 
3- Already fixed or just a temp fix?
4- Should the files include/language/jsLanguage.php and  include/language/getJSLanguage.php
also be included in language packs?

See lines 66 and 888
```
    static function createAppStringsCache($lang = 'en_us') {
        // cn: bug 8242 - non-US langpack chokes
```
```
    static function createModuleStringsCache($moduleDir, $lang = 'en_us', $return = false) {
        $json = getJSONobj();

        // cn: bug 8242 - non-US langpack chokes
```

#### Context

We should have a proper bug tracker!

**Comment by samus-aran** [comment]
@horus68 
That is a Sugar fix.
https://web.sugarcrm.com/support/issues/cc1155c0-211d-a0f6-978c-44e4b5cd75a7
