### ISSUE TITLE
 Not translatable labels  in ver. 7.7RC

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#1772]
Subj.

**Scenarios**
Sales (Opportunities, Leads) & other scenarios/modules names: Marketing, Finance etc.
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L12
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L22-L23
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L34
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L58
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L82
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/install/suite_install/scenarios.php#L102

**WebToLead form**
"Add all Fields", "Reset all Fields", "Next"
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/Campaigns/WebToLeadCreation.html#L152-L154	

**Campaigns**
--None--  https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/Campaigns/TrackDetailView.php#L167 

**AOS**
'AOS Products' https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOS_Product_Categories/metadata/subpaneldefs.php#L58 

**AOP**
Internal https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOP_Case_Updates/Case_Updates.php#L311 
Save https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOP_Case_Updates/Case_Updates.php#L313 

**PROJECT**
None https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/Project/controller.php#L197  

**AOR**
PARAMETERS https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOR_Reports/tpls/report.tpl#L17
REPORT https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOR_Reports/tpls/report.tpl#L91 

**AOW** 
ACTIONS & CONDITIONS 
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOW_WorkFlow/metadata/detailviewdefs.php#L141
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOW_WorkFlow/metadata/detailviewdefs.php#L148

https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOW_WorkFlow/metadata/editviewdefs.php#L117
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/AOW_WorkFlow/metadata/editviewdefs.php#L124	
									
**Studio**
Insert Field https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/DynamicFields/templates/Fields/Forms/iframe.tpl#L71
Insert Field https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/DynamicFields/templates/Fields/Forms/url.tpl#L67 

**Module loader**
Show Details https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/Administration/UpgradeWizard_commit.php#L538
Hide Details https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/Administration/UpgradeWizard_commit.php#L539

**Google Maps**
 'OK', 'ZERO_RESULTS', 'INVALID_REQUEST', 'OVER_QUERY_LIMIT', 'REQUEST_DENIED'
https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/modules/jjwg_Maps/controller.php#L30

**Comment by horus68** [comment]
@samus-aran requesting tags for this:
high priority
language

**Comment by likhobory** [comment]
**SuiteP Theme**
Back to top
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/AM_ProjectTemplates/create_project.js#L59
Create
https://github.com/salesagility/SuiteCRM/blob/v7.7/themes/SuiteP/tpls/_headerModuleList.tpl#L469

**Project**
All Projects
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L122
All Users
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L146
All Contacts
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L169
None
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/controller.php#L274
Add
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L169
Cancel
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L1197
Delete
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L300
Cancel
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L314
Update
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L462
Cancel
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Project/chart.php#L504

**AM_ProjectTemplates**
New project created
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/AM_ProjectTemplates/controller.php#L166
Create Project
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/AM_ProjectTemplates/create_project.js#L59
Cancel
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/AM_ProjectTemplates/create_project.js#L75
None
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/AM_ProjectTemplates/controller.php#L355

**Calendar**
Module Body Border Text
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Calendar/tpls/settings.tpl#L194

**Administration**
"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"
https://github.com/salesagility/SuiteCRM/blob/v7.7/modules/Administration/BusinessHours.php#L26

**Comment by likhobory** [comment]
All labels has been translated exept button labels in Project module.
@recci make please a PR in #1956 and I'll close this issue.
