### ISSUE TITLE
Windows+MSSQL fresh install - ProjectTemplates query generating invalid MSSQL query 

### ISSUE THREAD

**Issue by lcdcarneiro** [salesagility/SuiteCRM#1785]
This erros apply only to MSSQL database, I´ve tested in the last 2 versions.

Create a new Project Template. When you went to the project template list, this template was not shown.
In the log file you can see that there is an error with the querie. I´ve tested with MySQL and the error doesn´t occurs (the project list is ok).

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
