### ISSUE TITLE
Unable to save duplicate Contact/Lead records

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#179]
When 'duplicate' screen appears and user clicks 'Save', when creating a record, message appears: Error retrieving record. This record may be deleted or you may not be authorized to view it.

https://suitecrm.com/forum/bug-tracker/4176-unable-to-save-duplicate-contact#16321

**Comment by mariostevenson** [comment]
We may need to revisit this issue. On my edition, when clicking "Save," the file attempts to re-parse itself, meanwhile failing:
(i) an unparsed file attempts to download;
(ii) no changes are  made to the current page;
(iii) processing occurred in the background resulting in duplicate projects / project tasks equal to the number of times the "Save" button has been clicked.
