### ISSUE TITLE
Unable to load dashboard javascript - Release Candidate 2

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1802]
I updated from RC to RC 2 and now SuiteCRM Dashboard is not loading. Although I waited several minutes, still the screen is as attached. 
![2016-07-28 11_06_07-dashboard](https://cloud.githubusercontent.com/assets/20369981/17205363/6401cbd4-54b3-11e6-9539-3309ef690b6d.png)
 
I wanted to let you know this since this can be a bug.

Gokhan

**Comment by gokhanerdogdu** [comment]
Similar problem also occurs when Add Dashlet is used. 
![2016-07-28 11_08_42-add_dashlet](https://cloud.githubusercontent.com/assets/20369981/17205425/b8223cf8-54b3-11e6-8841-672da668a428.png)

**Comment by samus-aran** [comment]
@gokhanerdogdu Are you able to see if there is an error in the browser's console log.

When creating a github issue there should be a template to follow specifying which environment you use and what browser you see this on.  Please try to follow the guidelines so we can look in to the issue with as much information as possible.

**Comment by gokhanerdogdu** [comment]
Sorry for the missing information. Browser is Chrome, version 52.0.2743.82 (64bit). PHP version is 5.5 and the hosting provider is Dreamhost, not local machine. 

Attached is the screenshot of browser console. As I understand, there is permission problem. There added new js and images in RC 2 
![2016-07-28 12_29_34-chrome](https://cloud.githubusercontent.com/assets/20369981/17208205/407d577a-54c0-11e6-9095-ac31d699a4bc.png)
and it is needed to change the permissions on the server. The problem here, why in every update, there is a need to change the permissions manually. Is there a better way?

**Comment by samus-aran** [comment]
@gokhanerdogdu 

When you set the permissions on the server does this resolve your initial issue?

Regards to the permissions automatically being set is a difficult solution to provide simply due to the number of different ways a server can be set up and this can be done via a host provider or by your own tech team (if you were in that sort of environment).  Unfortunately we can't give a one size fits all solution when it comes to updating.  We recommend setting this in your config.php file:

```
'default_permissions' =>
array (
'dir_mode' => 1517,
'file_mode' => 420,
'user' => 'www-data',
'group' => 'www-data',
),
```

**Comment by gokhanerdogdu** [comment]
Thank you very much. When permissions are changed manually from the server, the problem was solved.
