### ISSUE TITLE
Unable to export/create custom dropdown values of any module by using export customization feature of studio in SuiteCRM 7.7

### ISSUE THREAD

**Issue by chandan999** [salesagility/SuiteCRM#1806]
Earlier by using export customization,we were able to export custom fields along with related drop down values attached with custom field.But now we are able to export only custom fields not related custom drop down values.

#### Expected Behavior

It was able to export custom fields,related drop down fields in suitecrm 7.2 but not in suitecrm 7.7
#### Possible Fix

It is not creating this array for $installdefs in manifest.php
   'language' => 
  array (
	0 => 
  array (
      'from' => '<basepath>/SugarModules/include/language/en_us.custom_name.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
)
So manifest is not creating 'include' directory in SugarModules.
Kindly fix it.
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.7 RC2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome
* Environment name and version (e.g. MySQL, PHP 7):Mysql,Php 5.5.38
* Operating System and version (e.g Ubuntu 16.04): windows 7

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it not appear.
Can you confirm if this issue do not appear in recent version of SuiteCRM.
@chandan999  , thanks for raise this issue.

**Comment by chandan999** [comment]
Thanks.This issue is not there with suitecrm 7.7.4
