### ISSUE TITLE
Unable to load some codes - Release Candidate 2

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1807]
#### Issue
1 - After updating from RC to RC 2, at some parts, there are warning about not being able to load some codes/files. Attached is the screen. This problem occurs on View screen for all objects. 

![2016-07-28 13_48_43-opportunity](https://cloud.githubusercontent.com/assets/20369981/17210339/09dd83b0-54cb-11e6-9c6a-30bc68e97541.png)

2- Similar problem exist when the details of the account is displayed. As seen in the attachment, there are some errors. In addition to these errors, although in line editing is enabled, the pencil is not seen on the field. But when double clicked to the field, it is possible to make inline editing.

![2016-07-28 13_53_16-account-details](https://cloud.githubusercontent.com/assets/20369981/17210350/11a5e56a-54cb-11e6-84ce-5262b8d36893.png)
![2016-07-28 13_54_02-inline-editing](https://cloud.githubusercontent.com/assets/20369981/17210351/11aa38b8-54cb-11e6-991e-a081e630e75a.png)

#### Your Environment

* SuiteCRM Version used: RC 2
* Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 5.5):

**Comment by samus-aran** [comment]
Hi @gokhanerdogdu These aren't errors messages for unable to load files - they are php warnings appearing in the application.  This is usually set by your php environment.  Try switching off your php errors.

Regards to the pencil that is known and we will need to supply a pencil icon.
