### ISSUE TITLE
Error with AOR link 

### ISSUE THREAD

**Issue by cmarrero** [salesagility/SuiteCRM#181]
Error. When you schedule a report to be send by email and a field is a link in the report, the mail doesn't include the base url of the site, so the link can't be open.

**Comment by danieljsamson** [comment]
The reason it doesn't work in the email is because the link doesn't include the domain / web address of the SuiteCRM instance. Instead the href attribute is set to eg index.php?module=Leads&action=DetailView&record=14d42e1b-87cc-de34-15ac-55d450965899
