### ISSUE TITLE
Creating user in French translation, Save button doesn't work

### ISSUE THREAD

**Issue by certinet** [salesagility/SuiteCRM#1814]
#### Issue
When using the CRM in French, if I create users, the save button won't do anything.

#### Expected Behavior
In English, the save button creates the user or saves the data

#### Actual Behavior
Nothing happen when the button is clicked

#### Steps to Reproduce
1. Put SuiteCRM in French
2. Create a new user
3. Hit Sauvegarder (Save in French)

#### Context
Need to switch in English when creating users

#### Your Environment
* SuiteCRM Version used: Version 7.6.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome, IE, Firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP Version 5.4.42, mysqlnd 5.0.10
* Operating System and version (e.g Ubuntu 16.04): Windows 10 Pro

**Comment by horus68** [comment]
Tested but not confirmed. No problem for me:
![2016-07-28 22_54_19-suitecrm](https://cloud.githubusercontent.com/assets/3055443/17230829/6480c21e-5516-11e6-93bd-3b6fbbea3440.png)

SuiteCRM 7.6.6 - French pack from Crowdin project (last week version)

**Comment by horus68** [comment]
Also working fine in 7.7 RC (even tested with today language pack from Crowdin)
https://crowdin.com/project/suitecrmtranslations/fr
![2016-07-28 23_08_35-suitecrm77](https://cloud.githubusercontent.com/assets/3055443/17231200/621421d6-5518-11e6-8e9b-cc09b38334bb.png)

**Comment by samus-aran** [comment]
Closing issue as we are unable to replicate.
