### ISSUE TITLE
SuiteCRM_MultiSelect_Reports_Conditions

### ISSUE THREAD

**Issue by JoeNewUser** [salesagility/SuiteCRM#1816]
I want the ability to associate a contact with one or more tags (also know as a group or category).  Any given contact can have one-or-more tags.  And, any given tag can have one-or-more contacts.

I think the MultiSelect Data Type may meet my requirement.  It is a special type of drop-down list that allows the selections of several items from the list.  I can add a custom field to the Contact module and assign one or more tags to a contact name.  However, reporting seems to be a problem.  I can add the custom field to a report, but can’t successful use that custom field in a Condition for the report.

Several key SuiteCRM support questions:

1. Does SuiteCRM support the MultiSelect Data Type?
2. Does SuiteCRM support using a MultiSelect custom field in the Reports Fields?
3. Does SuiteCRM support using a MultiSelect custom field in the Reports Conditions?

Regarding item 3, I have not been successful in using the custom field in a Condition statement.

See the attached document for more details. 
[SugarCRM_MultiSelect_Problem_02.docx](https://github.com/salesagility/SuiteCRM/files/389735/SugarCRM_MultiSelect_Problem_02.docx)

**Comment by shogunpol** [comment]
After testing the bug it appears.

**Comment by ijdavie** [comment]
I will close this issue as it appears that this is related to #1645 and appears to display the same issues.

**Comment by LewMegas** [comment]
I believe we are suffering with a very similar issue. We have contact categories (Programmer, Recruiter, Ex Employee etc) and while we are able to see them in reports we have no way of removing undesired categories from certain reports.

For example a Programmer may also be an Ex Employee (who we don't want to target in this instance). There is no working set of conditions that will enable us to include Programmers but not include any Programmers who are also Ex Employees.
