### ISSUE TITLE
CSS Problem On Activities Panel - RC2

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1818]
#### Issue
In activities subpanel, there is css problem for Create shortcut. When arrow is clicked, Schedule Meeting and Log Call are not seen. They seem to be white. When you browse the mouse over, they are seen.
![2016-07-29 11_00_57-activities](https://cloud.githubusercontent.com/assets/20369981/17241738/18dc91ec-557c-11e6-8cf2-84fbf6ad0da3.png)

Your Environment
SuiteCRM Version used: RC 2
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (MySQL, PHP 5.5):

**Comment by willrennie** [comment]
I don't see this issue in 7.7.1. Can you confirm if you still have this issue?

**Comment by shogunpol** [comment]
Bug is not existing in version 7.7.1
