### ISSUE TITLE
Actian Buttons Positions Differ- RC2

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1820]
#### Issue
In RC2, actian button positions differ from object to object. For some of them, these buttons are floating left, some of them on the right. For example;

Opportunity 
![2016-07-29 12_07_55-actian-buttons1](https://cloud.githubusercontent.com/assets/20369981/17243414/5eb2bee0-5585-11e6-81e9-8bd5814c38cc.png)

Account
![2016-07-29 12_07_55-actian-buttons2](https://cloud.githubusercontent.com/assets/20369981/17243419/65752f06-5585-11e6-859c-09e6fb5abcfd.png)

#### Environment
SuiteCRM Version used: RC 2
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (MySQL, PHP 5.5):

**Comment by willrennie** [comment]
I don't see this issue in 7.7.1. Can you confirm if you still have this issue?

**Comment by gokhanerdogdu** [comment]
Yes, it was solved.
