### ISSUE TITLE
7.7RC2 Cannot use Studio to edit subpanels

### ISSUE THREAD

**Issue by 2xaronl** [salesagility/SuiteCRM#1828]
In 7.7RC2 I'm getting
```
Notice: Undefined index: type in /var/www/suitecrm/include/SubPanel/SubPanelDefinitions.php on line 98

Notice: Undefined index: type in /var/www/suitecrm/include/SubPanel/SubPanelDefinitions.php on line 98
{"center":{"title":"Project Tasks Subpanel","crumb":"\"\"<\/a> \"\"<\/a> | Studio<\/a> > Projects<\/a> > Subpanels<\/a> > Project Tasks<\/span>

","content":"
\n\n
```
as a popup when I try to edit a subpanel in Studio.  The editor does not appear.

Expected Behavior
The editor should load.

Actual Behavior
The editor does not load and I am presented with a popup error.

Steps to Reproduce
1. Navigate to the Admin console
2. Select Studio
3. Expand the tree to a module that contains subpanels
4. Click on a subpanel item under the Subpanels folder OR click on the Subpanels folder and click on a subpanel item in the right-hand pane
5. Popup error occurs

Context
Subpanels cannot be edited.

Your Environment
SuiteCRM Version used: 7.7RC2
Browser name and version: Firefox 47.0.1, Chrome 51.0.2704.103 m
Environment name and version: MySQL 5.6, PHP 5.5.9
Operating System and version: Ubuntu 14.04.4 LTS

**Comment by c0cl3c** [comment]
I am not experiencing this issue. Installed on Ubuntu 16.04 with PHP 7.0. Accessing via Chrome 51.0.2704 on OSX.

**Comment by samus-aran** [comment]
@2xaronl Have you got Notices running on your php environment - if you reduce the error logging are you able to edit the subpanels?

**Comment by 2xaronl** [comment]
@samus-aran Notices were being reported.  I changed my /etc/php5/apache2/php.ini file from
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`
to
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE`
and restarted my apache server and I can now edit subpanels.


Is this a required setting?

**Comment by willrennie** [comment]
@2xaronl it is a recommended setting(to hide from display warnings/notices) for SuiteCRM. There are various warnings/notices reported when the CRM is being used but these do not inhibit the CRM functionality so can simply be hidden from view but still be logged if required. Thanks for confirming you can now edit subpanels and please follow up if you have any further issues.
