### ISSUE TITLE
7.7RC2 Edit Button in Role Management still not showing Drop down Options

### ISSUE THREAD

**Issue by c0cl3c** [salesagility/SuiteCRM#1829]
In Role Management, Red Edit Button is shown with no options (Duplicate, etc).

This did exist in RC1 and I remember seeing a Bug ticket for it. I ahve cleared Browser history since upgrading from RC1 but still exists.

I have noticed that if you Select a User from User Management this Red Icon appears very briefly as well, but changes within half a second to the correct grey button.

#### Expected Behavior
Should be a Grey Edit Button with a dropdown for Duplicate and Delete

#### Actual Behavior
Red Button with only Edit until you edit and save a role, in which the correct Edit button returns.

#### Steps to Reproduce

1. Admin --> Role Management
2. Select a Role
3. At this stage you will see the red Edit Button with no options
4. Choose a role to edit
5. Immediately save the role 
6. The grey Edit button with Option dropdown should return.

#### Your Environment
-7.7RC2
-Ubuntu 16.04 LTS
-PHP 7.0
-Mac OSX with Chrome 64 bit 51.0.2704

**Comment by samus-aran** [comment]
This is resolved in 7.7.1 so closing this.
