### ISSUE TITLE
Searching for anything

### ISSUE THREAD

**Issue by c0cl3c** [salesagility/SuiteCRM#1830]
#### Issue

Pretty easy one to explain because its experienced everywhere in SuiteCRM. Any search box you can find. If for example I have an account called 'Test Account' and I want to search for this, I would expect to put in any combination of characters and find the account as long as the letters are in the same order. Such as 'est', or 'account', or 'acc'.

Currently I have to add letters from the first word to find what I am looking for. I can enter 'T' or 'Te' and it will find it. 

Very hard to find products in a 10,000 plus product database if I can only search for first words. Half our staff don't even know what a product is called. They will likely need a field where they can enter any keyword and see a list of results.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

Using 7.7RC2 but noticed this issue is evident in earlier stable versions. Tried using Safari and Chrome.

**Comment by samus-aran** [comment]
Hey @c0cl3c I know you say everywhere, you will need to be more specific and use the supplied issue template.

Regards to searching are you meaning Related fields, Global search (basic advanced) or Search Filters (basic or Advanced) via modules.

Because in at least the module search (if you search by text) you can add wildcard search terms i.e. %

e.g. If in the Accounts Listview in 'Name' search field I can type '%Tech' and this will list 'SuperG Tech' as a found account.

**Comment by c0cl3c** [comment]
I was referring to all module field searches. For example, in Accounts, In advanced I search for '2ndname' with the full account name being '1stname 2ndname'. 

But I just found out that Wildcard searching is supported, I just need to enter % in front. This is good but I don't understand why it would be needed. I would prefer to just search any word in any field and see all the results under that module. That way if I have 1000+ entries (Products for example) and I cannot remember the exact name, I can try a few different searches until I find what I am looking for.

**Comment by willrennie** [comment]
Advice on how to search using wildcards given to resolve searching questions/issues. I don't see that any further action is required here and don't see removing the wildcard as necessary/logical. If you have any further feedback, please comment.
