### ISSUE TITLE
Problem with installation: "You did not include config_si.php in the document root..."

### ISSUE THREAD

**Issue by theodotos** [salesagility/SuiteCRM#1839]
#### Issue

I am trying to install SuiteCRM on Debian jessie. I have followed the Installation guide blindly:

https://suitecrm.com/wiki/index.php/Installation

When I point my browser to `http://crm.mydomain.com/install.php` I get:

```
You did not include config_si.php in the document root, or you did not define $sugar_config_si in config.php
```

I have gave the correct permissions to the SuiteCRM DocumentRoot:

```
chown -R www-data:www-data /var/www/html/suitecrm
chmod -R 755 /var/www/html/suitecrm
chmod -R 775 /var/www/html/suitecrm/{cache,custom,modules,themes,data,upload,config_override.php}
```

The *sugarcrm.log* file under the DocumentRoot is empty.

#### Expected Behavior

I am expecting for the Web Installer to start the installation procedure.

#### Actual Behavior

* On Firefox:
    When I visit the "install.php" page, I get a dump of the php code and then the page reloads with: `You did not include config_si.php in the document root, or you did not define $sugar_config_si in config.php`

* On Chromium:
    I get the first page of the Installation wizard but ticking and clicking the "I accept" option is unresponsive.

#### Steps to Reproduce

1. A Debian jessie server or VM
2. Install LAMP: `apt -y install apache2 php5 libapache2-mod-php5 mariadb-server`
3. Install pre-requisities: apt -y install php5-json php5-imap``
4. Download SuiteCRM: `wget -O SuiteCRM-7.6.6.zip 'https://suitecrm.com/component/dropfiles/?task=frontfile.download&id=93'`
5. Unzip: `unzip SuiteCRM-7.6.6.zip`
6. Move under Apache DocumentRoot: `mv SuiteCRM-7.6.6 /var/www/html/suitecrm`
7. Setup Permissions:
    ```
chown -R www-data:www-data /var/www/html/suitecrm
chmod -R 755 /var/www/html/suitecrm
chmod -R 775 /var/www/html/suitecrm/{cache,custom,modules,themes,data,upload,config_override.php}
    ```
8. I have setup an Apache vhost for SuiteCRM:
    ```
cat > /etc/apache2/sites-available/crm.mydomain.com.conf << EOF
<VirtualHost *:80>
    ServerName crm.mydomain.com
    ServerAdmin webmaster@mydomain.com
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/ [R,L]
</VirtualHost>
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin webmaster@mydomain.com
                ServerName crm.mydomain.com
                DocumentRoot /var/www/html/suitecrm
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
                SSLEngine on
                SSLCertificateFile /etc/letsencrypt/live/crm.mydomain.com/fullchain.pem
                SSLCertificateKeyFile /etc/letsencrypt/live/crm.mydomain.com/privkey.pem
                Include /etc/letsencrypt/options-ssl-apache.conf
                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                BrowserMatch "MSIE [2-6]" \
                                nokeepalive ssl-unclean-shutdown \
                                downgrade-1.0 force-response-1.0
                BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
        </VirtualHost>
</IfModule>
EOF
    ```
9. Enabled the Apache vhost: `a2ensite crm.mydomain.com`
10. When I visit `https://crm.mydomain.com/install.php` I get (on Firefox):
    ```
You did not include config_si.php in the document root, or you did not define $sugar_config_si in config.php
    ```

#### Context

We are trying to install SuiteCRM to evaluate it for our CRM needs.

#### Your Environment

* SuiteCRM Version used: v7.6.6
* Browser name and version: Firefox 47.0 on Ubuntu 16.04 (64 bit), Chromium Version 51.0.2704.79 Ubuntu 16.04 (64-bit)
* Environment name and version: Apache: 2.4.10-10+deb8u5, MariaDB: 10.0.26-0+deb8u1, PHP: 5.6.24+dfsg-0+deb8u1
* Operating System and version: Debian jessie: 8.5

**Comment by samus-aran** [comment]
It looks as though it thinks you are installing it silently - hence the config_si file.  In the install.php there is a check that determines if it is a silent install or not based on a $_REQUEST - Can you provide detailed error.log from your php for the action of loading the install.php page?

**Comment by theodotos** [comment]
It seems I have forgot to install *php5-mysql*. I installed it and then used a *config_si.php* to finish the installation. 

Thanks for the help!
