### ISSUE TITLE
Meetings in scheduler shifted by one hour

### ISSUE THREAD

**Issue by albertodalsant** [salesagility/SuiteCRM#1840]
#### Issue

Scheduler in Meeting/calls module show occupation blue boxes shifted by one hour from the start date and time As on the attachments
#### Expected Behavior

Occupation boxes (accepted) should be posistioned in the time in wich the meeting/call actually are planned
#### Actual Behavior

Occupation boxes are shifted by an hour, as seen in the attachments
#### Steps to Reproduce

In demo version of suite (edit of an existing meeting)
http://demo.suiteondemand.com/index.php?module=Meetings&offset=2&stamp=1470126825007969600&return_module=Meetings&action=EditView&record=127e4c60-5148-e7fa-9b3b-578e93d6e20a
1. Create new meeting
2. Save and edit again
3. See results on scheduler section
#### Context

For my company it is important to see the correct availability timeslot of the employees in order to schedule a meeting in the right time.
#### Your Environment
- SuiteCRM Version used: Bug only on version >7.6 (it is ok on 7.5.2)
- Browser name and version: affect every browser
- Environment name and version (e.g. MySQL, PHP 7): mysql 5.5, php 5.3
- Operating System and version: tested in both Windows 10 and ubuntu server 12.4

![suitecrm_meeting_scheduling_demo](https://cloud.githubusercontent.com/assets/20790372/17322317/5663af54-589d-11e6-97d1-b632e2957fd5.png)

![suitecrm_meeting_scheduling](https://cloud.githubusercontent.com/assets/20790372/17322320/5c07d962-589d-11e6-9603-4f2fb37a75cc.png)

**Comment by albertodalsant** [comment]
Any news?

**Comment by ijdavie** [comment]
@albertodalsant, have you tried upgrading to the latest version of SuiteCRM 7.7.4 ?

**Comment by albertodalsant** [comment]
@ijdavie, Yes, i've upgraded my system to the latest version, but the problem still occours.
However the problem is not bounded to my system, you can replicate it in the demo version of suite.

Here is the a test meeting i've created to replicate the bug.
http://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DMeetings%26action%3DDetailView%26record%3Ddb847285-6c7b-b316-ee05-57e4d4e26765

A screenshot is attached.
![scheduler_bug_meeting](https://cloud.githubusercontent.com/assets/20790372/18777547/02cfb828-8170-11e6-8342-c04c5f98966b.JPG)

**Comment by TB-effective** [comment]
Just to make sure everyone is aware: even though the PR is marked merged, and this ticket closed, the issue is still present in a 7.11.18 install out of the box. Applying the patch from the PR does fix it, but must still be done manually at this time.

Are there any plans to get the fix into the official release?
