### ISSUE TITLE
Security updates SugarCRM 6.5.24

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1843]
SugarCRM 6.5.24 has been released with a couple of security fixes. See

http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/CE/Sugar_Release_Notes_6.5.24/

Do they also also affekt SuiteCRM?

**Comment by adminibt** [comment]
That was quick! Thanks

Just one question: Will version 7.6 als be patched?

**Comment by samus-aran** [comment]
@adminibt We are scheduling a 7.6.x release in the coming weeks :+1:
