### ISSUE TITLE
7.7 SuiteP missing icons

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1850]
"My Activity Stream" do not display icons.
Fresh install, untouched 7.7 version, no errors on install.

#### Issue

Icons not displayed. See pic (with Firefox code inspector)

#### Expected Behavior

Icons should be displayed

#### Actual Behavior

Some icons not displayed

#### Possible Fix

Code must be fixed to state an icon file on any panel

#### Steps to Reproduce

1. Install 7.7 with no demo data, all scenarios
2. See first screen
![suite_icons_missing](https://cloud.githubusercontent.com/assets/3055443/17363027/14bba65a-5970-11e6-9b6b-5ea134364e29.png)

#### Context

UI low quality = medium priority 

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version: Firefox 47.0.1 (32-bit)
* Environment name and version (Wamp, PHP 5.5.12, Mysql 5.6.17):
* Operating System and version: Windows 10 Pro

**Comment by appomattox** [comment]
I've seen this too.

SuiteCRM v 7.7
Firefox v47.0
MAMP (php v5.6.1, Apache v2.0, MySQL v5.5.42
