### ISSUE TITLE
suiteP admin icons: gif mixed with svg files

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1851]
#### Issue

Admin icons for SuiteP template include a mix from new ones (beautiful svg files) with old icons (poor gif files)
Is it the expected behavior or are there missing icons or WIP? :(

#### Expected Behavior

All icons should be svg files

#### Actual Behavior

Mixed files and mixed quality

#### Possible Fix

New icons!

#### Steps to Reproduce

Admin screen pics:
![1](https://cloud.githubusercontent.com/assets/3055443/17363692/d813b95a-5973-11e6-9631-0f13ebc0c2ac.png)
![2](https://cloud.githubusercontent.com/assets/3055443/17363697/dcd9779a-5973-11e6-9014-925132820362.png)
![3](https://cloud.githubusercontent.com/assets/3055443/17363701/e48ec134-5973-11e6-88eb-59755addcc2f.png)

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version: Firefox 47.0.1 (32-bit)
* Environment name and version (Wamp, PHP 5.5.12, Mysql 5.6.17):
* Operating System and version: Windows 10 Pro

**Comment by daniel-samson** [comment]
This issue has been fixed in https://github.com/salesagility/SuiteCRM/pull/1858.

We do not yet have new icons for everything in SuiteCRM. So we have opted to fallback onto the old icon set. There are missing icons for some of the dashlets as well.
