### ISSUE TITLE
Empty needle error from smarty templates

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1853]
#### Issue

On a fresh 7.7 install (no demo data) you get an Empty needle error notice from Smarty templates when you enter almost any menu (as in accounts, Leads and so on)
`Warning: strpos(): Empty needle in \cache\smarty\templates_c\%%85^852^85294558%%get_form_header.tpl.php on line 23`

#### Expected Behavior

No notices! Please do not say "turn off errors!"

#### Actual Behavior

![4](https://cloud.githubusercontent.com/assets/3055443/17364557/b6c16e8c-5978-11e6-9a75-35a56d95ca26.png)

#### Clues

The file get_form_header.tpl.php has this on line 23
`            <?php $this->assign('found_match', ((is_array($_tmp=$this->_tpl_vars['left'])) ? $this->_run_mod_handler('strpos', true, $_tmp, $this->_tpl_vars['other_text']) : strpos($_tmp, $this->_tpl_vars['other_text']))); ?>`

The file \modules\Accounts\AccountsListViewSmarty.php on line 105
`		return "<a href='javascript:void(0)' id=\"targetlist_listview_". $loc ." \" onclick=\"$js\">{$app_strings['LBL_ADD_TO_PROSPECT_LIST_BUTTON_LABEL_ACCOUNTS_CONTACTS']}</a>";
`

This could be linked to the language string
`    'LBL_ADD_TO_PROSPECT_LIST_BUTTON_LABEL_ACCOUNTS_CONTACTS' => 'Add Contacts To Target List',`
or to the arguments ordering.

For those who can code... maybe you get inspired from this reply
See Warning: strpos(): Empty needle in ......wordpress Plugin - http://stackoverflow.com/questions/26325407/warning-strpos-empty-needle-in-wordpress-plugin

#### Your Environment
* SuiteCRM Version used: 7.7, clean install, no demo data
* Browser name and version: Firefox 47.0.1 (32-bit)
* Environment name and version (Wamp, PHP 5.5.12, Mysql 5.6.17):
* Operating System and version: Windows 10 Pro

**Comment by daniel-samson** [comment]
In you php.ini configuration, do you have error reporting turned off?

What is your configuration for error reporting?

**Comment by horus68** [comment]
I know I can hide those errors, but I think this one should not be considered a notice error but a bad code usage. The question is how to make it away!

Visible if php.ini
```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
display_errors = On
```

Hidden if php.ini
```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
display_errors = Off
```

**Comment by websolprov** [comment]
I have exactly the same issue having installed the latest SuiteCRM version, its very annoying.  Even when I switch from Suite P to Suite R then I see the same error, so I am not sure why these things happen.

**Comment by horus68** [comment]
Related PR: #1910

**Comment by websolprov** [comment]
Thanks for fixing so quickly.
