### ISSUE TITLE
7.7 Events

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1854]
"Manage Delegates" and "Manage Acceptance" don't change "Status" and "Accept Status".

#### Issue

Delegates in an event can't be modified concerning their "Status" and "Accept Status". This worked in version 7.6.6.

#### Expected Behavior

The "Status" of the delegate should now be "Not Invited".

#### Actual Behavior

The "Status" of the delegate does not chance at all.

#### Steps to Reproduce

1. Create an event
2. Add a couple of delegates
3. Mark the first one
4. Choose "Manage Delegated"
5. Pick "Not Invited"

#### Your Environment

* SuiteCRM Version used: 7.7.0
* Browser name and version (Firefox 48.0):
* Environment name and version (MySQL 5.6.30, PHP 5.6.24):
* Operating System and version (FreeBSD 10.2):

**Comment by samus-aran** [comment]
HI @adminibt - Can you use the issue template and explain a little more detail on the issue.  What version of SuiteCRM are you using, browser, enviroment etc etc

**Comment by adminibt** [comment]
Hi @samus-aran, sorry. I hope the new explanation will help. If you need more infos please contact me.

-- Andreas

**Comment by willrennie** [comment]
Confirmed as a bug, marked as medium priority as this prevents you from being able to manage delegates and invites for delegates for an event.

**Comment by adminibt** [comment]
The subpanel is now working as expected. Thanks @daniel-samson
