### ISSUE TITLE
RSS dashlet formatting in 7.7

### ISSUE THREAD

**Issue by emcrobert** [salesagility/SuiteCRM#1855]
#### Issue

In the latest release (7.7) the RSS dashlets displays the HTML tags instead of rendering them.
#### Expected Behavior

User should see nicely formatted content
#### Actual Behavior

User sees HTML Tags
#### Steps to Reproduce
1. install 7.7
2. add dashlet
3. choose web and enter RSS feed into 2nd text box
#### Your Environment
- SuiteCRM 7.7
- Chrome
- MySQL
- Ubuntu

**Comment by daniel-samson** [comment]
I can't replicate the issue. I have tried bbc and cnet news feeds.

Have you upgraded to SuiteCRM  7.7 or is this a fresh / clean install?

(If you have upgraded) Have you tried resetting file permissions and running a repair and rebuild?

**Comment by emcrobert** [comment]
It was a fresh install, permissions definitely OK and repair and rebuild makes no difference.

The RSS feed I used was:
https://community.sugarcrm.com/community/feeds/allcontent?community=2017

which displays correctly in previous versions of the dashlet.

**Comment by daniel-samson** [comment]
It looks like the rss feed is breaking the way the rss dashlet parses the xml.

We will need to look into this further.

**Comment by ahhhaweb** [comment]
I managed to fix this issue by reverting some changes in modules/Home/Dashlets/RSSDashlet.php that were committed on Aug 2.

**Add this back:**
`line 176     <h3><a href="{$item->link}" target="_child">{$item->title}</a></h3>`
`line 177      {$item->description}`
**To replace this change:**
`  <h3><a href="{$link}" target="_child">{$title}</a></h3>`
`      {$description}`

-----------------------------------------
**Same thing here - Add this back:**
`line 194 +    <h3><a href="{$link}" target="_child">{$entry->title}</a></h3>`
`line 195 +    {$entry->summary}`

**To replace this change:**
`     <h3><a href="{$link}" target="_child">{$title}</a></h3>`
`     {$summary}`

Also, if you want the alternating row colors in the output add the code noted in bold below in the output starting at line 197, 
`foreach ( $channel->item as $item ) {`
`                        $link = htmlspecialchars($item->link, ENT_QUOTES, 'UTF-8');`
`                        $title = htmlspecialchars($item->title, ENT_QUOTES, 'UTF-8');`
`                        $description = htmlspecialchars($item->description, ENT_QUOTES, 'UTF-8');`
`>> add line 179						**$x++; `
`>> add line 180						$class = ($x%2 == 0)? 'evenListRowS1': 'oddListRowS1'; ** `
`                        $output .= <<<EOHTML`

And add the class style variable to the table row (I added a little padding as well):
`>> change line 184 <tr class="{$class}">`
`>>change line 185 <td style="padding: 5px 0px 0px 10px;">**`
`<h3><a href="{$item->link}" target="_child">{$item->title}</a></h3>`
`    {$item->description}`
`</td>`
`</tr>`
`EOHTML;`
