### ISSUE TITLE
Version 7.7 File Permissions

### ISSUE THREAD

**Issue by appomattox** [salesagility/SuiteCRM#1856]
#### Issue

In /includes/utils.php at lines 137 & 138 and lines 279 & 280 the directory and file permissions are set to 02770 and 0755 respectively.  
#### Expected Behavior

These lines are supposed to set the directory and file permissions to 755 and 644 respectively when the CRM writes new directories and files as the admin modifies the CRM, but they don't.
#### Actual Behavior

The directory and file permissions for the custom and cache directories get set to a value where you can't write to them or read them and weird stuff begins to happen as you use the CRM. Labels come up as undefined and the CRM begins to break down.
#### Possible Fix

Recommend changing the dir_mode and file_mode to 0755 and 0644
#### Context

I have had to go into the utils.php file every time I get ready to initialize an instance and change the permissions variable.

I've seen this problem pop up a lot in the forums, I've posted about it myself as well, and I think it may have been brought up in here, but no action has been taken.
[https://suitecrm.com/forum/installation-upgrade-help/6680-why-are-the-permissions-set-to-02770-and-0660-in-utils-php](https://suitecrm.com/forum/installation-upgrade-help/6680-why-are-the-permissions-set-to-02770-and-0660-in-utils-php)

This is an issue that causes a lot of loss of faith in the usability of your software, so, I'd say it could be a high priority issue.
#### Your Environment
- SuiteCRM Version used: 7.7 and earlier versions
- Browser name and version:  Any
- Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.5.35
- Operating System and version (e.g Ubuntu 16.04): CENT OS

**Comment by pgorod** [comment]
Probably related to 
#1655 Permissions are breaking more in 7.6.4? Specifically, CSS files 
#1688 403 errors in cache folder

The current issue, however, has the advantage of pointing to a solution. : - )

If it's the same thing, I strongly suggest High Priority bug labels, this is having terrible consequences for lots of people.

**Comment by Mausino** [comment]
@salesagility @samus-aran  the version 7.7 or earlier don't are supported anymore. 

I'm suggesting to close the issue.
