### ISSUE TITLE
User profile tabs show data from all tabs

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1862]
#### Issue
When updating profile information in SuiteCRM 7.7, the tabs appear to show all fields/data instead of fields/data specific to each tab. This means that all tabs show the same information and appear redundant(if the layout should work like this). In previous versions, tabs showed specific fields/data for that tab, such as the password tab simply showing fields to allow users to change/update their password.

#### Expected Behavior
Clicking on individual tabs within the user profile should show fields specific to that tab.

#### Actual Behavior
Clicking on individual tabs shows all fields for all of the tabs, so when you click different tabs you simply get the same fields listed.

#### Possible Fix
The fix I would suggest is to ensure that only user preferences relevant to the tab that you have clicked on is shown and not all of the user preferences shown in one tab. Alternatively, if the profile is to show all fields in one page/tab, the tabs should be deprecated.

#### Steps to Reproduce
1. Install SuiteCRM 7.7. 
2. Login to the CRM and navigate to your user profile(hover over username in the top right menu and click the 'Profile' link).
3. Click any tab within your profile.
4. Observe that user preferences from all tabs are shown within tabs which should only show fields and data specific to that tab, such as the 'Password' tab.

#### Context
The bug has affected me as it was apparent that all fields were showing when I simply wanted to change my password. When clicking the password tab, I only expected to see password fields and not be shown all of my user preferences.

I feel this should be of medium priority.

#### Your Environment
* SuiteCRM Version used: 7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 43.0.2357.130, Firefox 47.
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46), MySQL Server version: 5.5.47-0ubuntu0.14.04.1 (Ubuntu)
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by cjmny** [comment]
I think there may be further issues with this bug that would raise the priority.  In my testing of 7.7, it appears that the tabs are not functioning properly when there are subpanels.  For example, if you have a module where the first tab contains 3 panels the first three tabs on the edit/detail screens for that module won't change view to the appropriate tab.  The fourth tab will then show info for what is designated as the second tab in the studio.  This should be High Priority, it makes complex forms unusable,.

**Comment by willrennie** [comment]
Tested and confirmed as working in 7.7.1 release.
