### ISSUE TITLE
List View bug when users perform/clear searches

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1865]
#### Issue

When performing/clearing searches in SuiteCRM 7.7, it appears that the footer links get merged into the 'Security Group' mass assign panel.
#### Expected Behavior

Security Groups Mass Assign panel does not merge with/overflow onto the footer section within the list view.
#### Actual Behavior

Security Groups Mass Assign panel merges with/overflows onto the footer section within the list view causing a bug in the UI.
#### Possible Fix

The fix I would suggest is to ensure that the Security Groups Mass Assign panel and the footer elements are styled to ensure they are always kept separate and are not affected by list view searches/changes.
#### Steps to Reproduce
1. Install SuiteCRM 7.7. 
2. Login to the CRM and navigate to any module list view.
3. Perform a basic or advanced search.
4. Observe that the footer links/section has merged/is being overlapped with the Security Groups Mass Assign panel.
#### Context

The bug has affected me as I would not expect when performing searches for view elements to merge/overlap and this affects the usability of some elements.

I feel this should be of low priority.
#### Your Environment
- SuiteCRM Version used: 7.7
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 43.0.2357.130, Firefox 47.
- Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46), MySQL Server version: 5.5.47-0ubuntu0.14.04.1 (Ubuntu)
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
