### ISSUE TITLE
7.7 SuiteP missing login page icons

### ISSUE THREAD

**Issue by 604media** [salesagility/SuiteCRM#1869]
SuiteP theme missing login page icons
#### Issue

Login page icons not displaying in Firefox but looks good in chrome
#### Expected Behavior

Login page Icons should be displayed
#### Actual Behavior

Login page icons are not displaying
#### Steps to Reproduce

1. Install fresh SuiteCRM 7.7 and set crm theme as SuiteP
2.
![login_page](https://cloud.githubusercontent.com/assets/64729/17396672/15161486-5a52-11e6-8596-4b02d3c6992c.jpg)

3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
SuiteCRM 7.7
Browser : Firefox 47
Environment : XAMPP - PHP 5.4, MYSQL 5.5
Operating Sysytem - Windows 7

**Comment by 604media** [comment]
Fixed #1871

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2
