### ISSUE TITLE
Suite P theme Tab/Panel (Edit/Detail View) Major Issues

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#1878]
#### Issue
In my testing of 7.7, it appears that the tabs are not functioning properly in the Suite P Theme when there are subpanels.  For example, if you have a module where the first tab contains 3 panels the first three tabs on the edit/detail screens for that module won't change view to the appropriate tab.  The fourth tab will then show info for what is designated as the second tab in the studio.  This should be High Priority, it makes complex forms unusable,.  

#### Expected Behavior
Clicking on a tab in a module should bring you to that tab.

#### Actual Behavior
If a tab has multiple panels, clicking on the next tab keeps you in the data for the first tab. 

#### Steps to Reproduce
1.  In a multi tab module, add a second panel to the main/default tab (tab A)
2. Save and deploy
3. Open the module in view/edit and click on tab B (data from tab A should still be visible).
4. Click on tab C and the data from tab B should be visible.

#### Context
 This should be High Priority, it makes complex forms unusable,.  

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version: Chrome for Windows  Version 51.0.2704.103 m Firefox 47
* Environment name and version MySQL, PHP 5.6:
* Operating System and version Centos 7

**Comment by willrennie** [comment]
I couldn't replicate this. Is your view customised via Studio or otherwise? Is this an issue across all modules? Can you provide some screen shots?

**Comment by cjmny** [comment]
Will, most of the views we use were customized in the studio and work fine on the other themes.  I could provide some screenshots if needed, but I would have to scrub some data out of it.  

In my situation, the Accounts module was most affected.  I have 6 total tabs (Tabs A, B, C, D, E, and F) in the studio.  On Tab A, I have 3 panels.  Selecting Tab A, B, or C shows the same exact information.  Clicking on Tab D finally shows what should be on B.  Tab B is designed as one panel, so clicking on Tab E shows what should be Tab C.   etc.  

I have modified the Prospects module as well and this is exhibiting the same behavior.

**Comment by gokhanerdogdu** [comment]
We are also suffering same problem. I had opened the same issue at https://github.com/salesagility/SuiteCRM/issues/1817.

**Comment by samus-aran** [comment]
@gokhanerdogdu I believe that this is a different issue.  As yours is regarding subpanels and this is tabs and panels on the edit/detail view.

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2

**Comment by itglaafs** [comment]
Dear Sirs,

We have similar problem with SuiteP theme but only after 10th tab under any module, 11th and 12th tab and more are repeating with same content as 1st, 2nd tab and so....
We are on 7.8.2 and have tested editview.tpl file from 7.8.5 LTS with same result.

Does anyone has similar problem and possible fix for this?
