### ISSUE TITLE
Disable TinyMCE editor for a textarea

### ISSUE THREAD

**Issue by raghavendra89** [salesagility/SuiteCRM#188]
Hi,

In the cases module I've a Status Description field(LBL_Description). It's just a text area but TinyMCE editor appears instead of textarea in the edit mode. 
 Because of this when Cases are created/edited html tags are saved in the DB. I want to disable this TinyMCE editor and just have a textarea in place of it.

How do I it?

Thanks in Advance,

**Comment by jonathan-alban** [comment]
Hi @raghavendra89 did you ever find a solution for this?

**Comment by willrennie** [comment]
You could create a custom detailviewdefs.php in custom/modules/Cases/metadata to override the html type to resolve this issue.
