### ISSUE TITLE
Error Message When Adding or Removing Target Lists in Campaigns

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#1888]
An error message appears when adding or removing target lists from campaigns.

`Fatal error: Uncaught Error: Call to a member function fill_in_additional_detail_fields() on boolean in /var/www/crm/public_html/include/SearchForm/SearchForm2.php:657 Stack trace: #0 /var/www/crm/public_html/include/SubPanel/SubPanel.php(420): SearchForm->generateSearchWhere(true, NULL) #1 /var/www/crm/public_html/include/SubPanel/SubPanel.php(92): SubPanel->buildSearchQuery() #2 /var/www/crm/public_html/modules/Campaigns/SubPanelViewer.php(88): SubPanel->__construct('Campaigns', 'a66f01f7-5602-c...', 'prospectlists', NULL, '') #3 /var/www/crm/public_html/include/MVC/View/SugarView.php(738): include_once('/var/www/crm/pu...') #4 /var/www/crm/public_html/modules/Campaigns/views/view.classic.php(77): SugarView->includeClassicFile('modules/Campaig...') #5 /var/www/crm/public_html/include/MVC/View/SugarView.php(160): CampaignsViewClassic->display() #6 /var/www/crm/public_html/include/MVC/Controller/SugarController.php(363): SugarView->process() #7 /var/www/crm/public_html/include/MVC/Controller/SugarController.php(310): Suga in /var/www/crm/public_html/include/SearchForm/SearchForm2.php on line 657`
#### Steps to Reproduce

1. Go into an existing campaing
2. Add or remove a target list
3. The error appears in the target list subpanel
#### Context

When refreshing the page it appears that the action was executed. In other words it does add or remove the target list. Therefore this issue is non critical but can certainly freak out users. 
#### Your Environment

- SuiteCRM Version used: 7.7
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome / Ubuntu 64-bit
- Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
Hi @tfreier, Are you adding Target Lists via the Campaign Wizard or the Campaign's Target List subpanel?  Also are these existing Campaigns prior to upgrading and what instance did you upgrade from or is this a fresh install?

**Comment by tfreier** [comment]
Hi @samus-aran, I added the target lists in the target list subpanel. However, since you mentioned it: I wasn't able to use the campaign wizzard to create a new campaign. I had planned to investigate it more later but it might be related. I couldn't get past the step where you select the target lists. I just got an empty page and couldn't find an obvious error. I'll do some more testing on that issue later this week.

**Comment by tfreier** [comment]
I did some more testing regarding the issue with creating campaigns. Unfortunately I was not able to find any errors in sugar or apache log. However, I noticed that I also can't update existing campaigns anymore using the wizard. I tried updating the the campaign budget. Unfortunately the change wasn't saved and I did not get an error anywhere.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear,
We will label this issue as a bug.
@tfreier , thanks for raise this issue.

**Comment by virtualme123** [comment]
Not sure if it is related or a different bug (please feel free to move it), when I have added a target list, then go back through the campaign wizard the target list disappears and the target lists go back to the default (Subscription List, Unsubscription List). Having multiple target lists per campaign is quite important to me so hope it is just a bug...

**Comment by tfreier** [comment]
It appears that this issue has been resolved. I can no longer reproduce it in version 7.8.
