### ISSUE TITLE
Insecure Stylesheet Error

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1891]
#### Issue
When SuiteCRM is deployed to https hosting, there are insecure stylesheet errors from yahoo. Attached is the screenshot. 

![2016-08-08 10_49_20-https_css](https://cloud.githubusercontent.com/assets/20369981/17472938/6701ca9a-5d56-11e6-86ca-ac57e76dcfd1.png)

#### Expected Behavior
For https, the style sheets should be loaded from https sources. 

#### Possible Fix
If Yahoo also has the stylesheets in https, those links should be changed with https versions.

#### Your Environment
SuiteCRM Version used: SuiteCRM 7.7
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (e.g. MySQL, PHP 5.5): https hosting.

**Comment by Mausino** [comment]
I think that is duplicate #719
