### ISSUE TITLE
Suite P Theme: cannot enter email when creating user with system generated passwords enabled

### ISSUE THREAD

**Issue by simjker** [salesagility/SuiteCRM#1892]
#### Issue
If you enable system generated passwords (Admin->Password Management) then when you attempt to create a new user (Admin->User Management) you cannot provide an email address for the user.

#### Expected Behavior
As part of new user creation I can enter the email for the new user as part of the user profile section of the user profile tab of the create user form.

#### Actual Behavior
When you select to create a new user with system generated passwords enabled then the create user form does not have any field to enter the user email

#### Possible Fix
WORK AROUND:
Leave system generated passwords enabled and just save the user when you have entered the other details.   An error page is generated which allows entry of missing information - the user email

Other Notes:
If you disable system generated passwords then a new tab is displayed on the create user form called Passwords.  On this tab you can enter the user email details.

#### Steps to Reproduce
1. Login as an Admin user
2. Open Admin screen 
3. Open Password Management form and enable system generated passwords saving changes
4. Open Admin screen
5. Open User Management screen and select to Create New User
6. Try and enter email for the new user

#### Context
Assessing maturity/stability of release 7.7

#### Your Environment
SuiteCRM 7.7 installed on XAMPP 5.6.23.
Chrome Version 51.0.2704.103 m on Windows 7 Pro SP 1

**Comment by simjker** [comment]
Related to #1862

**Comment by samus-aran** [comment]
@simjker - this should be resolved in 7.7.1 release (but it didn't automatically close it) so I will close it now.

**Comment by simjker** [comment]
Thanks for the prompt fix.
I have installed the changed Suite P/style.js and I can now enter an email when creating a user.
