### ISSUE TITLE
Dashboard Problem - Can't add Dashlet to bottom of Column Side

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1894]
#### Issue

In the main dashboard, by drag and drop, I am trying to change the positions of the dashlets. In frame, I can see the place of the dashlet, but when I dropped the dashlet, it is not there. The dashlet is also disappered from the screen. The problem is as below;

![2016-08-08 17_03_12-dashboard](https://cloud.githubusercontent.com/assets/20369981/17482526/d4b20f26-5d8a-11e6-9906-4cb83d1122f6.png)

When the page is rebuilt, I can see the dashlet at the desired position.

![2016-08-08 17_03_12-dashboard_rebuilt](https://cloud.githubusercontent.com/assets/20369981/17482534/db68d14c-5d8a-11e6-827b-fbc0defd5650.png)
#### Environment

SuiteCRM Version used: SuiteCRM 7.7
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (e.g. MySQL, PHP 5.5)

**Comment by shogunpol** [comment]
@gokhanerdogdu ,The issue has been tested in recent version of SuiteCRM(7.7.6), and not appear, can you confirm is not issue any more, if yes can you close the issue.
Thanks for your contribution.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
