### ISSUE TITLE
It would be safe to to add *.ext.php files to .gitignore file?

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#1898]
#### Issue

It would be safe to to add *.ext.php files to .gitignore file?

All *.ext.php file begin with:

    <?php 
     //WARNING: The contents of this file are auto-generated

They are hinting that they can be add it to .gitignore file without problem.

Am I right?

#### Your Environment

* SuiteCRM Version used: Version 7.7

**Comment by sgaved** [comment]
Hi @cumanacr ,

These files are created on a repair and rebuild. So it would be fine to add to git ignore as long as you do a repair and rebuild.
