### ISSUE TITLE
Unable to load Calendar in PHP5.3

### ISSUE THREAD

**Issue by rdzsjpr** [salesagility/SuiteCRM#1903]
After upgrading to version 7.7, the calendar module throws this error while using the Suite P theme:

Parse error: syntax error, unexpected '[' in /public_html/crm/modules/Calendar/CalendarDisplay.php on line 182

**Comment by samus-aran** [comment]
Hey @rdzsjpr - Can you use the Issue template to supply more information. i.e what environment and steps to reproduce.

Are you using a language other than English?
