### ISSUE TITLE
AOW: action not saved

### ISSUE THREAD

**Issue by lehha** [salesagility/SuiteCRM#1904]
#### Issue
If create a AOW Action with fields its did not save a selected actions and fields

#### Expected Behavior
Its must save them, correct?

#### Steps to Reproduce
look on my screenshots

#### Your Environment
* SuiteCRM Version used: 7.7  Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox Latest
* Environment name and version (e.g. MySQL, PHP 7): Mysql, php 5.3
* Operating System and version (e.g Ubuntu 16.04): CentOS 6

Ive create a field for action and save AOW:
<img width="729" alt="need" src="https://cloud.githubusercontent.com/assets/4051362/17524496/8e529068-5e67-11e6-8a84-5c1535f3824f.PNG">

After opening this AOW for edit, action is empty! In actual run, calls created an empty:
<img width="734" alt="got" src="https://cloud.githubusercontent.com/assets/4051362/17524495/8e51456e-5e67-11e6-8759-90f1067418ff.PNG">

**Comment by lehha** [comment]
Javascript Console have a error:
<img width="554" alt="console" src="https://cloud.githubusercontent.com/assets/4051362/17527004/559ce27c-5e72-11e6-9e11-d2c0dab7c770.PNG">

**Comment by willrennie** [comment]
This works without issue for me in 7.7. Was this a fresh install or an upgrade? Have you run a Quick Repair & Rebuild in Admin -> Repair and also ensured permissions are set correctly for your environment? It is also worth doing a rebuild of JS Grouping files in Admin -> Repair -> Repair JS Grouping files.

**Comment by lehha** [comment]
Its fresh install from latest archive.
Yes, i've do all repair, rebuild and etc.

I think trouble in this - look at js debug. One field have a comma (") in name? And js came broken.

<img width="937" alt="debug" src="https://cloud.githubusercontent.com/assets/4051362/17549963/72b0a838-5efb-11e6-9961-ac1410b6b395.PNG">

**Comment by lehha** [comment]
yes, I found that. Module installed not correctly, it have a comma in label
<img width="403" alt="field" src="https://cloud.githubusercontent.com/assets/4051362/17550844/b2fee6a8-5eff-11e6-8cad-be822af4ba23.PNG">

change, rebuild and go work!
self solved))

**Comment by willrennie** [comment]
Great, I was just about to follow up to ask if you had Asterisk customisations as it's not an out of the box module. Thanks for confirming and glad you were able to resolve it.
