### ISSUE TITLE
Upgrade from 7.6.x to 7.7 generates strict standards errors (2633 times)

### ISSUE THREAD

**Issue by RichardLukins** [salesagility/SuiteCRM#1909]
#### Issue

Upgrading a very basic unchanged 7.6.x (7.6.3 but failed to make a note of it, sorry!) and not customised and never upgraded previously install, generates 2633 errors during upgrade
#### Expected Behavior

Error free upgrade!
#### Actual Behavior

After Pre-Flight checks all passed and upgrade clicked, this error is generated:
Strict Standards: Only variables should be passed by reference in /var/sites/c/crm.XYZ.com/public_html/include/SubPanel/SubPanelDefinitions.php on line 102

This error occurred 2633 times during the upgrade
#### Possible Fix

Are these just warnings, if so what should be configured differently to avoid them?
Should the preflight have generated a warning and recommend the corrective action in future?

The install had not been upgraded previously, and no alterations of system parameters had been done

Improve pre-flight checks if a configuration issue or upgrade process to avoid such error generation, or simplify output to a single error rather than 2633 of them!
#### Steps to Reproduce
1. Install 7.6.x
2. Do nothing !
3. Upgrade to 7.7 (using the 7.6.x to 7.7 upgrade files)
4. preflight success and install finishes - see errors
#### Context

Test Upgrade files
#### Your Environment
- SuiteCRM Version used: 7.6.x to 7.7
- Firefox on Win10 x64 - Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0 

Server information 
Linux #6 SMP Fri May 20 17:37:06 BST 2011 x86_64
Server software version Apache
PHP version 5.6.22
Memory limit 128M
MySQL version 5.6.30

**Comment by RichardLukins** [comment]
Changing the error reporting in the PHP.ini file to this:
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
fixes the issue, although not why the upgrade is not "strict" compliant?!

**Comment by garrettw** [comment]
I just installed SuiteCRM on my web server yesterday and I'm getting tons of "Strict Standards" error messages too. They break the layout quite badly.

**Comment by Dillon-Brown** [comment]
No longer relevant as 7.6.x and 7.7.x are no longer supported. Please create a new issue if you are still encountering this problem in later versions. Thanks.
