### ISSUE TITLE
Menu ACTIONS its not translatable - SuiteP

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1915]
#### Issue

There is no way to translate the main menu "ACTIONS" on SuiteP template

#### Expected Behavior

A string and a value to translate that menu name!

#### Actual Behavior

Value is hard-coded and do not translate!
![11](https://cloud.githubusercontent.com/assets/3055443/17563358/fa27e206-5f26-11e6-9d5e-0765e3974737.png)

#### Steps to Reproduce

1. Use any other language then english and see the home screen Actions menu

#### Context

The submenus are translated, not the main menu!
Also take a look int some other labels without translation already posted as issue #1772

#### Your Environment
* SuiteCRM Version used: 7.7
* Browser name and version: Firefox 47.0.1 (32-bit)
* Environment name and version (Wamp, PHP 5.5.12, Mysql 5.6.17):
* Operating System and version: Windows 10 Pro

**Comment by recci** [comment]
fix- pull request submitted

**Comment by horus68** [comment]
fixed by PR merged
