### ISSUE TITLE
Auto-complete only returns a single record on the Related to field of the compose email screen

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#1916]
#### Issue

Auto-complete only returns a single record on the "Related to" field of the compose email screen.
Note, this problem only seems to affect the new Suite P theme
#### Expected Behavior

The auto-complete field should find and display all results matching the text entered.
#### Actual Behavior

As text is entered, the system only one matching entry
#### Possible Fix

This problem is only apparent when using the Suite P theme
#### Steps to Reproduce

1. Compose a new email
2. Select an option from the "Related to:" drop down
3. Begin entering text in the supplied field
4. Only the first matching result is displayed in the context menu
#### Context

This is annoying rather than being a show-stopper. It does however decrease productivity as extra mouse clicks and screens are required to file emails correctly.
#### Your Environment

- SuiteCRM Version used: 7.7
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 9.1.2
- Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7 / PHP 7.0
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by shogunpol** [comment]
Yes issue appear, on email module all drop down menus are used White Text on White background.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.8) and not appear,
@blloyd78 , can you confirm it, if yes can you close an issue.

**Comment by blloyd78** [comment]
Apologies for the delay in responding @shogunpol - I have now tested and can confirm the issue is resolved in version 7.7.8.

Thanks for your help.
