### ISSUE TITLE
Translation issues. Duplicated lang. strings in ver. 7.7

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#1918]
--------------------

['project_priority_default']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L463
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2456

'project_priority_options'['High']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L459
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2458

'project_priority_options'['Medium']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L460
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2459

'project_priority_options'['Low']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L461
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2460

['moduleList']['KBDocuments']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L111
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2490

['LBL_LISTVIEW_OPTION_CURRENT']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1753
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3253

['LBL_LISTVIEW_OPTION_ENTIRE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1754
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3254

['LBL_LISTVIEW_NONE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1752
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3255

['case_status_default_key']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L383
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3274

'dom_email_distribution_for_auto_create'['roundRobin']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L756
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3292

'dom_email_distribution_for_auto_create'['leastBusy']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L757
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3293

['product_category_dom']['']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L593
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3464

['LBL_NUMBER_OF_COLUMNS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2173
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3910

['moduleList']['AOBH_BusinessHours']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L59
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3939

--------------------

['ERR_CHECKSYS_CALL_TIME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L63
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L65

['ERR_CHECKSYS_SAFE_MODE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L92
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L93

['LBL_STEP1']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L427
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L429

['LBL_STEP2']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L428
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L430

--------------------

['LBL_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L51
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L101

['LBL_TASK_NAME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L83
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L116

['LBL_START']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L111
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L119

['LBL_FINISH']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L112
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L120

['LBL_PREDECESSORS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L84
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L121

['LBL_PERCENT_COMPLETE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L107
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L122

['LBL_REMOVE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L58
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L146

--------------------

['LBL_MODULE_NAME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L44
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L51

['LBL_AGENDADAY']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L45
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L65

['LBL_AGENDAWEEK']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L46
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L67

--------------------

['LBL_NEWSLETTER_TITLE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Campaigns/language/en_us.lang.php#L56
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Campaigns/language/en_us.lang.php#L529

--------------------

['LBL_WIZARD_LOCALE_DESC']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Configurator/language/en_us.lang.php#L418
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Configurator/language/en_us.lang.php#L436

--------------------

['LBL_CHOOSE_EMAIL_PROVIDER']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/OutboundEmailAccounts/language/en_us.lang.php#L82
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/OutboundEmailAccounts/language/en_us.lang.php#L95

--------------------

['LBL_PROJECT_TASKS_SUBPANEL_TITLE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L97
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L131

['LBL_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L58
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L141

['LBL_STATUS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L64
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L159

--------------------

['LBL_WIZARD_LOCALE_DESC']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Users/language/en_us.lang.php#L555
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Users/language/en_us.lang.php#L560

--------------

See also #1772

**Comment by horus68** [comment]
Good work. I know someday we will succeed on cleaning up language files.
Need I say please @samus-aran ?

**Comment by likhobory** [comment]
I hope so.
