### ISSUE TITLE
mssql column escape

### ISSUE THREAD

**Issue by diaF** [salesagility/SuiteCRM#1922]
When installing 7.7 -7.7.1

a lot of the MSSQL TABLE CREATEs fail as the column names are not escaped, and is conflicting with reserved words. only 160 of the 211 tables are created.

/include/database/MssqlManager.php line 1775

needs to be changed

 from 
            return "{$ref['name']} {$ref['colType']} {$ref['default']} {$ref['required']} {$ref['auto_increment']}";
to
            return "[{$ref['name']}] {$ref['colType']} {$ref['default']} {$ref['required']} {$ref['auto_increment']}";

**Comment by samus-aran** [comment]
A github user @OttoG has supplied the following PR for this issue.

https://github.com/salesagility/SuiteCRM/pull/1955

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2
