### ISSUE TITLE
7.7.1 SuiteP missing icons

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1923]
#### Issue

After 7.7.1 update many items are now in good quality and the issues with icons missing on SuiteP template are almost solved. Some are missing.

#### Expected Behavior

Icons should be there!
I do remember of a PR on those icons but don't know why they was not in 7.7.1 update
https://github.com/salesagility/SuiteCRM/pull/1913

#### Actual Behavior

Some missing links. See pics

#### Steps to Reproduce

1. Add a dashlet

![1](https://cloud.githubusercontent.com/assets/3055443/17593814/15941bbe-5fdf-11e6-92cb-82d08388ab82.png)
![2](https://cloud.githubusercontent.com/assets/3055443/17593847/296ca7f0-5fdf-11e6-944f-7c9a430a6cf0.png)
and the icons for Reports on the left side (recent)
![4](https://cloud.githubusercontent.com/assets/3055443/17593900/5bbf1526-5fdf-11e6-811d-1117b49c1a1f.png)

Note: I did some rebuilds!

#### Context

Bad looking UI

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version: Firefox 48.0 (32-bit)
* Environment name and version (Wamp, PHP 5.5.12, Mysql 5.6.17):
* Operating System and version: Windows 10 Pro

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2 (let us know if any other icons are missing)
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2
