### ISSUE TITLE
Error accessing spot

### ISSUE THREAD

**Issue by fgpalacios** [salesagility/SuiteCRM#1925]
I downloaded version 7.7.1 and tested suitecrm functionality spot

#### Issue

I try to enter the module spot shows an HTTP ERROR 500
I analyzed the Apache error and shows the following:
SuiteCRM-7.7.1 \\ htdocs \\ \\ Spots \\ controller.php modules on line 145

I changed the line 145:
$ ReturnArray = [];
by
$ ReturnArray = array ();

The same did with the lines 201, 202 and 208 because they have the same error.
Then I could enter the module Spot and create a registry, but return wrong information.
![error2](https://cloud.githubusercontent.com/assets/2921066/17598751/5dfe5020-5fd2-11e6-807d-94b7ea4595e8.png)
![error](https://cloud.githubusercontent.com/assets/2921066/17596631/b732bc1c-5fc8-11e6-8e3c-291a6f8dce98.png)

#### Expected Behavior

You should enter without error.

#### Actual Behavior

Not enter the module
#### Possible Fix

I changed the line 145:
$ ReturnArray = [];
by
$ ReturnArray = array ();

The same did with the lines 201, 202 and 208 because they have the same error.

#### Steps to Reproduce

1. Create a record
2. Select Area for Analysis: Accounts
3. I select Configuration Table, Count, in the Industry rows and columns in the Account Type
4. Reports 1, when there are 3 Accounts.

#### Context

high priority
#### Your Environment

* SuiteCRM Version used:
Version SuiteCRM 7.71
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Chrome Version 52.0.2743.82 m
* Environment name and version (e.g. MySQL, PHP 7):
PHP Version 5.3.8
MySQL Server 5.5
* Operating System and version (e.g Ubuntu 16.04):
Windows 7 64 bits

**Comment by shogunpol** [comment]
This issue cannot be consider as an issue, Because SuiteCRM version 7.7.1 is doesn't support the PHP version 5.3.8.  Supported version of PHP is 5.5.9.
Issue was tested on compatible version PHP and do not appear.
