### ISSUE TITLE
AOR - Empty condition problem

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1927]
Conditions in report which contain "Equal to ''" don't work correct.

#### Issue

Take two "and" conditions. One condition should check for "empty". The other for a special string, i.e.
The result is wrong.
#### Actual Behavior

In the logs I find this:

Thu Aug 11 18:45:24 2016 [48633][1][INFO] Query:SELECT `contacts`.first_name AS 'First_Name0', `contacts`.last_name AS 'Last_Name1', `contacts`.salutation AS 'Salutation2' FROM `contacts`  WHERE ( `contacts`.salutation = '' OR `contacts`.salutation IS NULL AND `contacts`.first_name = 'Frau' ) AND  contacts.deleted = 0  LIMIT 0,20

There is a parenthisis missing:
... (`contacts`.salutation = '' OR `contacts`.salutation IS NULL) ...

If I add a parenthisis to the condition everything works fine.
#### Possible Fix

Rethink the SQL statement.
#### Steps to Reproduce

1. Create a report
2. Add a "And" condition like above.
3. Generate the report.
#### Your Environment

- SuiteCRM Version used: 7.7.1, 7.6.6
- Browser name and version (Firefox 48.0):
- Environment name and version (MySQL 5.6.30, PHP 5.6.24):
- Operating System and version (FreeBSD 10.2):

**Comment by adminibt** [comment]
Maybe this makes it a little bit clearer what I meant with "Empty":


![cond](https://cloud.githubusercontent.com/assets/19223035/17634386/a486b3f6-60d2-11e6-909a-711a245153b0.png)

The value is empty. With the parenthisis it works, without not.

**Comment by dhayner** [comment]
I can confirm this issue on 7.6.6

**Comment by PeterPhilipM** [comment]
I think this is related to #3375 which has been fixed.
I have tried reproducing it on my own 7.9.4 version and the demo site's 7.9.3 and it seems to work as it should. Also #1812 seems to be another open duplicate.
