### ISSUE TITLE
Email signature popup console errors on v7.7

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#1929]
#### Issue
In the "Emails" module, click the "Settings" button and then the "Create" or "Edit" button of the "Signatures" field. The popup opens but console errors are thrown and the html editor is not loaded in the "Signature" field .

#### Expected Behavior
The popup should load the html editor and not throw any errors like prior versions.

#### Actual Behavior
![email signature](https://cloud.githubusercontent.com/assets/20977561/17603724/86dbfaac-5fe0-11e6-9980-f3e8842f4e14.png)

#### Your Environment
SuiteCRM v7.7.1 (clean install)
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 52 on Windows 10

**Comment by staganyi** [comment]
Just tested on v7.7.5 and it's fixed. I did notice though that the popup is not using the SuiteP styling. Seems to be using SuiteR for some reason.

![image](https://cloud.githubusercontent.com/assets/20977561/19204482/2625c862-8cab-11e6-8cb0-ce634cbaf7e7.png)

**Comment by ijdavie** [comment]
@staganyi, to keep this inline with the issue that was raised I will close this as the issue appears to be resolved. If you are seeing issues with the SuiteP theme if you can raised this as a separate issue that would be great.
