### ISSUE TITLE
Drop Down Items are not seen after upgrade to 7.7.1

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1930]
#### Issue
After SuiteCRM is upgraded to 7.7.1 from 7.7, during object creation drop down list items are shown, but selected item is not shown in the screen. Although the selected item is not shown on the screen during creation, you can see the selected item in detail view.

Screenshot 1 - During Account Creation (Drop Down is clicked)
![2016-08-11 23_40_54-sc1](https://cloud.githubusercontent.com/assets/20369981/17604221/89e74eda-601d-11e6-9ea5-7d272ba62961.png)

Screenshot 2 - One of the items is selected, but is not shown in edit view
![2016-08-11 23_40_54-sc2](https://cloud.githubusercontent.com/assets/20369981/17604235/9b35bae6-601d-11e6-9351-1ae39edb3491.png)

Screenshot 3 - Selected items are shown in detail view
![2016-08-11 23_40_54-sc3](https://cloud.githubusercontent.com/assets/20369981/17604249/a9dcdb2e-601d-11e6-9f9c-93cd4fc2c7ed.png)

In inline editing, when the field is double clicked, the selected items again disappear.

#### Your Environment

SuiteCRM Version used: SuiteCRM 7.7
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (e.g. MySQL, PHP 5.5): https hosting.

**Comment by samus-aran** [comment]
Hi @gokhanerdogdu I am unable to replicate this, I also upgraded from 7.7.0 to 7.7.1 without refreshing my browser cache or repairing and building and I was able to see my selected dropdowns.  Are you currently using a language packe and what one is it?  I suspect its a CSS issue - so try refreshing your browser cache.  Is the dropdown you are refering to have a default value?

**Comment by gokhanerdogdu** [comment]
I cleared browser cache but the problem still continues. Addirional info is that the problem occurs only on my machine in google chrome. It works in firefox and safari.

**Comment by samus-aran** [comment]
@gokhanerdogdu If you select any dropdown value does it not appear selected or is it only certain values (i.e. with special characters?).

**Comment by gokhanerdogdu** [comment]
@samus-aran the problem exists for all dropdowns and the selected dropdown does not appear as selected during edit screen. When the page is saved, the selected drop down is seen in detail view.

**Comment by gokhanerdogdu** [comment]
As I observe the problem is occuring on Google Chrome Version 52.0.2743.82 (64-bit). I uninstalled this version and installed 32 bit version of Google Chrome 52.0.2743.116 m and now drop downs are working correctly. But please note that this problem occured with 7.7.1. There was no problem in 7.7.

**Comment by Mausino** [comment]
The issue still persist in chrome 53.0.2785.70 beta-m (64-bit) (tested on official demo page) Tested in Edge, Opera, Mozilla :)

**Comment by Mausino** [comment]
@samus-aran  hi, here is videoscreen http://screencast.com/t/witCg7QvuJA on which i showed the type of browser + the issue of dropdown

But now to core :) The dropdowns didn't work on my version of chrome, but only the dropdown of  LAYOUT OPTIONS  worked without issue like you can see on videoscreen....  Maybe it can help to solve this issue

**Comment by gokhanerdogdu** [comment]
I uninstalled 64 bit version of Chrome and installed 32 bit version on 64 Bit machine and now system is working as desired.

**Comment by ijdavie** [comment]
This appears to be a issue only seen in the 64bit version of chrome, seems like it could be down to styling.

**Comment by Mausino** [comment]
@ijdavie here is what i wrote before 11 days

"hi, here is videoscreen http://screencast.com/t/witCg7QvuJA on which i showed the type of browser + the issue of dropdown

But now to core :) The dropdowns didn't work on 64 bit version of chrome, but only the dropdown of LAYOUT OPTIONS worked without issue like you can see on videoscreen.... Maybe it can help to solve this issue

I tested it on official SuiteCRM demo site 7.7.1"

**Comment by gokhanerdogdu** [comment]
The problem now also exists for 32 bit version of Google Chrome with the latest update. Google Chrome is updated to 53.0.2785.113 m and as seen below, drop down items are not seen correctly. I think this is a high priority Bug since most of the users are using Google Chrome and Google Chrome is updated automatically to the latest versions.

![2016-09-15 20_57_37-dropdowns](https://cloud.githubusercontent.com/assets/20369981/18561149/49e96522-7b87-11e6-80aa-052cbbf28c33.png)

**Comment by gokhanerdogdu** [comment]
The label has been changed to Resolved: Next Release, but I can not see any commit/pull request for the issue. Is there any work on this currently?

**Comment by Mausino** [comment]
@gokhanerdogdu @mattlorimer @ijdavie  The great news are that the issue will SuiteCRM team resolve before version 7.7.5, because all my employees are using the SuiteR theme only because there are some big issues as this one, reports export+ others. When the SuiteCRM Team fix this issues , it will huge step forward :)

**Comment by mattlorimer** [comment]
Resolved: Next Release means a fix is in the hotfix branch and will be in the next release, there is no referencing commit, as this issue was already fixed before the issue was raised

**Comment by Mausino** [comment]
@gokhanerdogdu @mattlorimer @ijdavie i want confirm, that this bug now more exist 🎯 👍 👍 
Chrome  53.0.2785.116 m 32 bit version

**Comment by Mausino** [comment]
@ijdavie i apologise for my English, i want write: "that this bug are not more exist"  but i wrote other :(
