### ISSUE TITLE
Error creating reports

### ISSUE THREAD

**Issue by ekkusu** [salesagility/SuiteCRM#1936]
#### Issue
when entering the area of creating reports, any field does not appear to add

#### Expected Behavior

should appear to add fields and create the report
#### Actual Behavior

instead nothing comes
#### Steps to Reproduce

1.crm entry
2.reports menu
3.the module tree fields and boxes are blank
4.I can not create the report

#### Context

the problem affects me because I can not evaluate the data using graphs, I consider the problem a high priority
#### Your Environment

* SuiteCRM Version used:
SuiteCRM 7.7.1
* Google Chrome 52.0.2743.116 m (64-bit)
* PhP version: 5.5 MySQL version:
* Windows 10 Professional 64 bits

**Comment by samus-aran** [comment]
Hi @ekkusu Do you have a screenshot of the issue?

When you create a report you are required to at least select a module to report on - its the dropdown field underneath the Report's Name field.

**Comment by ekkusu** [comment]
hi @samus-aran, the printscreen: 
![print](https://cloud.githubusercontent.com/assets/6969782/17624598/dadce12c-606a-11e6-889a-a6d18e54277f.jpg)
anyway I'll database repair and reinstall the CRM to see what happens

**Comment by samus-aran** [comment]
@ekkusu What language you using?  Does it work on English?  Do you have any PHP error logs?

**Comment by ekkusu** [comment]
I backup database, uninstall and reinstall the CRM and the problem disappeared, thanks for the help.
