### ISSUE TITLE
Calendar issues with Day, Week & Month views on 7.7.1

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#1938]
#### Issue
When viewing the calendar in day or week view (dashlet or calendar module), the hours do not show in the first column, you cannot add a meeting/call when clicking in it (only the "dall-day" row clicks work), and you cannot see calendar events scheduled during the day. If you switch to Month view, the calendar events display, but are listed in the previous day (time is correct).

#### Expected Behavior
On day and week views, the time in the first column should be view able, you should be able to add a meeting/call when clicking a certain hour, and existing calendar events should be displayed. In month view, the calendar events should display on the correct day.

#### Actual Behavior
When viewing the calendar in day or week view, no time slots or existing calendar events display
![image](https://cloud.githubusercontent.com/assets/20977561/17625966/2796e6c6-6079-11e6-894d-d6bb534f9f5c.png)

and no errors in the php logs, only notices:
PHP Notice:  Undefined property: FP_events::$rel_users_table in SuiteCRM/modules/Calendar/CalendarActivity.php on line 188, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined property: Task::$rel_users_table in SuiteCRM/modules/Calendar/CalendarActivity.php on line 188, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: LBL_PREVIOUS_AGENDAWEEK in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 511, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: LBL_NEXT_AGENDAWEEK in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 492, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 240, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 241, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 240, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 241, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 240, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: CalendarColors in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 241, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: Meeting in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 232, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: Call in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 232, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: Task in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 232, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: LBL_PREVIOUS_AGENDAWEEK in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 511, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined index: LBL_NEXT_AGENDAWEEK in SuiteCRM/modules/Calendar/CalendarDisplay.php on line 492, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0
PHP Notice:  Undefined property: Task::$rel_users_table in SuiteCRM/modules/Calendar/CalendarActivity.php on line 188, referer: SuiteCRM/index.php?module=Calendar&action=index&view=agendaWeek&year=2016&month=8&day=12&hour=0

When clicking in an hour row, a console error is thrown
![image](https://cloud.githubusercontent.com/assets/20977561/17626002/54c9fa0c-6079-11e6-8b1a-ac835858cb2d.png)
![image](https://cloud.githubusercontent.com/assets/20977561/17626049/95a75aba-6079-11e6-857c-eeffda1f7f3f.png)

If I change to month view, the calendar events will show but on the previous day they're scheduled for (the time is correct). In the image below, the "test", "test2" & "test3" meetings are scheduled for Friday Aug 12th and "test4" is for Sat Aug 13th but they display on the previous day (Thurs Aug 11th and Fri Aug 12th)
![image](https://cloud.githubusercontent.com/assets/20977561/17626638/0ebbfdb4-607c-11e6-8e71-58f4b807a583.png)

#### Possible Fix
I think the day/week issues are actually working for some people, so it may be platform/version related. Not sure about the month view (obviously some date conversion gone wrong).

#### Your Environment
SuiteCRM v7.7.1 (clean install)
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 52 on Windows 10

**Comment by mattlorimer** [comment]
This is a known issue and one we looking into, but for now as a work around generally you can get it working by going into settings on week view and unchecking 'Display time slots in Day and Week views' saving, then re-enter settings and recheck 'Display time slots in Day and Week views' and save. Thanks for reporting this issue

**Comment by staganyi** [comment]
Yes that did work. Thanks for the workaround. I'm guessing that was a per user setting. Can I apply that to all users without doing it manually? Secondly, the month view is actually the bigger problem for my users, is there a workaround for that?

**Comment by mattlorimer** [comment]
thanks for confirming, month a new one for me, so no work around or fix for that as yet but looking into it, think it per user and not got a global work around yet
