### ISSUE TITLE
When SuiteP sidebar is minimized, horizontal scrollbar appears

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#1941]
#### Issue
When you minimize the sidebar, a horizontal scrollbar appears.

#### Expected Behavior
If sidebar is minimized, it should behave like when it's open, there should not be a horizontal scrollbar
![image](https://cloud.githubusercontent.com/assets/20977561/17635997/991cea32-60a8-11e6-8cb3-f8bd04d225db.png)

#### Actual Behavior
When minimized, a horizontal scrollbar appears
![image](https://cloud.githubusercontent.com/assets/20977561/17635983/78464be6-60a8-11e6-91b2-5c146ae607f4.png)

#### Your Environment
SuiteCRM v7.7.1 (clean install)
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 52 on Windows 10

**Comment by shogunpol** [comment]
Yes, problem is existed, it is a bug. The suggestion what causing appearance of the horizontal scroll bar is the "BACK TO TOP" - functionality position, after re-positioning it more to the LHS, problem should disappear.

**Comment by staganyi** [comment]
Is it possible this was fixed in v7.7.2? I just did a clean install and it seems to be working correctly.
