### ISSUE TITLE
Studio - Add relationship - Allows to create unwanted relationship duplicates

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#1944]
#### Issue

When you create a new relationship the "Save & Deploy" button gives no feedback unlike when you are creating a new field that after pressing "Save" a floating div appears:

    In progress.. 
    Please wait, loading...

and when the field is created changes to:

    Result
    This operation is completed successfully

This give the users the feeling that maybe they don't click the button correctly, pressing it again and again and again...

You grab the idea. :laughing:

Resulting this:
![selection-02-2016-08-12](https://cloud.githubusercontent.com/assets/6874136/17639966/86215f32-60b5-11e6-8b8b-b92173de7702.png)

#### Expected Behavior

When you click on "Save & Deploy" button a floating div appears:

    In progress.. 
    Please wait, loading...

and when the relationship is created changes to:

    Result
    This operation is completed successfully

Back to relationships list where you can see your newly created relationship.

#### Actual Behavior

When you click on "Save & Deploy" button, no feedback is given to the user, a minute or so lapse pass, then back to relationships list where you cannot see your newly created relationship.

So you have to go to admin -> repair -> quick repair and rebuild

Check back the relationship list where now you can find the new relationship.

#### Possible Fix

Same behavior when creating a new field on a module.

#### Steps to Reproduce

1. Go to Administrator Menu -> Admin -> Studio
2. Select any module (Projects recommended for this example)
3. Click on Relationships -> ADD RELATIONSHIP
4. Choose a many to many relationship with other module (Products recommended for this example)
5. Click "Save & Deploy" button
6. No feedback is given
7. Click "Save & Deploy" button consecutively 6 more times to simulate create copies by mistake
8. Wait 7 minutes... (www.youtube.com recommend for this example)
9. Back to relationships list where you cannot see your newly created relationship
10. Go to Administrator Menu Admin -> Repair -> Quick repair and rebuild
11. Check back the relationship list where now you can find the new relationship and 6 unwanted copies to same module.

![selection-02-2016-08-12](https://cloud.githubusercontent.com/assets/6874136/17639966/86215f32-60b5-11e6-8b8b-b92173de7702.png)

#### Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
* Environment name and version:
  * mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
  * PHP Version 5.6.24-1+deb.sury.org~xenial+1
  * Apache/2.4.18 (Ubuntu)
* Operating System and version: 
  * Distributor ID: neon
  * Description:    KDE neon User Edition 5.7
  * Release:        16.04
  * Codename:       xenial

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2
