### ISSUE TITLE
Size of Required Symbol

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1949]
#### Issue
It may be better to use somebit smaller required symbol, since in some forms, it is mixing with the fields. The below is an example from Convert Lead screen. It is possible to change this from custom css, but I am writing here because I think this should be also used in normal installation.

![2016-08-15 15_27_28-required-symbol](https://cloud.githubusercontent.com/assets/20369981/17664514/4dd0085a-62fd-11e6-917d-0c6cc94a48c6.png)

#### Your Environment
SuiteCRM Version used: SuiteCRM 7.7.1
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (e.g. MySQL, PHP 5.5): https hosting.

**Comment by samus-aran** [comment]
Hey @gokhanerdogdu We have noted this and being worked on.  Thanks for raising this.

**Comment by samus-aran** [comment]
This should be resolved in v7.7.2
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2
