### ISSUE TITLE
editview layout does not change using module builder on suitecrm 7.7

### ISSUE THREAD

**Issue by vger72** [salesagility/SuiteCRM#1958]
#### Issue

In version 7.7 of SuiteCRM, changing editview layout on module builder works the first time but later changes don't show up in the layouts. I keep getting the original layout.
#### Expected Behavior

The new layout defined in the editview layout using Module Builder should be the active one.
#### Actual Behavior

Old layout keeps showing with no changes.
#### Possible Fix

Doing a Quick Rebuild & Repair makes all layouts to be correctly displayed.
#### Steps to Reproduce

1. Go to module builder
2. Change the EditView layout of a given module
3. Save and Deploy
4. Go to the module edit view and verify that no change happened

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 48.0
* Environment name and version (e.g. MySQL, PHP 7): httpd-2.4.6-40.el7.centos.x86_64, mariadb-5.5.44-2.el7.centos.x86_64, php-mysql-5.4.16-36.el7_1.x86_64
* Operating System and version (e.g Ubuntu 16.04): CentOS 7 (3.10.0-327.10.1.el7.x86_64)

**Comment by shogunpol** [comment]
@vger72  just short question, is that issue is about admin/studio or admin/module builder.

**Comment by vger72** [comment]
Hi,
it happens either Studio or Module Builder.
I upgraded to 7.7.1 and it's the same.

Even before now, I went to studio and changed the layout of AOS_Contracts DetailView.
Made Save&Deploy and after accessing the module the layout is the same.

Closed the browser (Firefox 48.0) and cleared the cache. Result is the same.
Only after Quick Repair&Rebuild the layout was ok.

**Comment by tomi798** [comment]
Hello, i have the same problem, changes made in the studio does not appear need to quick/repair, the problem occurred after suite upgrade to 7.7.2 from 7.7.1.
