### ISSUE TITLE
date fields are not displaying properly for Suite P Theme in advanced search

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#1969]
Issue
Using the SuiteP theme date searches do not work properly

The problem is todo with the layout of date fields where there is a dropdown for Equals, Not On etc.

Where there are two date fields only the 2nd dropdown works

See Campaigns advanced Search
![2016-08-17 09_35_53-suitecrm - pale moon](https://cloud.githubusercontent.com/assets/3176876/17730010/a46aaad2-645e-11e6-940b-691055bd83d9.png)

Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version Firefox (48)
* Environment name and version ( MySQL, 5.5 PHP 7.09):
* Operating System and version (Centos: 6.8)

**Comment by shogunpol** [comment]
This appearance is related to #1940
