### ISSUE TITLE
CSS of favorite has wird design on sidebar + #826

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1974]
#### Issue

If you choose the record as favorite you will see  a wird design/behavior on sidebar + also we have still problem with issue of #826 
#### Actual Behavior

Look on videoscreen http://screencast.com/t/vZt2p8qhXj after refresh of page it is looking fine :)
#### Steps to Reproduce

1. Go to detaiview of some record
2. Choose the record as favorite
3. Look on sidebar
4. Refresh the page
#### Your Environment

- SuiteCRM Version used:
- Browser name and version Chrome 53.0.2785.70 beta-m (64-bit)
- Environment name and version (e.g. MySQL, PHP 7): PHP 5,6, MySQL 5.6
- Operating System and version (e.g Ubuntu 16.04): Linux (Hosting)

**Comment by samus-aran** [comment]
Closing this as the incorrect styling of favourites has been resolved and the deleted favourites still showing in the sidebar has a dedicated issue relating to it.
