### ISSUE TITLE
Fail on import when item not found in dropdown

### ISSUE THREAD

**Issue by chollingsworth** [salesagility/SuiteCRM#1976]
#### Issue

FATAL error  on import

NOTICE: [8] Undefined index: LBL_ERROR_INVALID_DYNAMICENUM on line 492 in file /var/www/html/helpdesk/modules/Import/Importer.php

Importing from CSV where imported data is incorrect.    child in dynamic drop down does not exist.
#### Expected Behavior

Expected behaviour - system should capture the error and flag
#### Actual Behavior

Actual behaviour - FATAL error
#### Steps to Reproduce

1. To reproduce  import to a dynamic dropdown child with a value that does not exist in the dropdown. (may also be for all dropdowns.  Not tested.)
#### Context

low priority but would be good to have it noted.
#### Your Environment

- SuiteCRM Version used: 7.7.1
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
- Environment name and version (e.g. MySQL, PHP 7):  php 5.6 / mySQL: 5.0.11
- Operating System and version (e.g Ubuntu 16.04): Amazon linux

Logs:

Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: Accessing static property ImportFieldSanitize::$createdBeans as non static
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: Undefined index: LBL_ERROR_INVALID_DYNAMICENUM
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: stat(): stat failed for upload/import/error_1.csv
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: Accessing static property ImportFieldSanitize::$createdBeans as non static
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: stat(): stat failed for upload/import/status_1.csv
Thu Aug 18 10:23:28 2016 [2925][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!

**Comment by shogunpol** [comment]
When you import the dynamic dropDown field i see the imports without the problem, an it does not check the existing values for that field. I've tagged it as a bug.
Thanks for raising this.

**Comment by PedroErnst** [comment]
@pgorod 

You mentioned that someone brought this up recently on the forums, can you maybe link that post? Or direct that user here?

I've just run the following steps on 7.8.13 and gotten the correct result, which is an error explaining that the dropdown doesn't contain the given value.

Add a custom dynamic dropdown to contacts
Export a contact
Change the dropdown value in the CSV from a correct value (Customer) to a faulty one (Something)
Importing the csv throws the error we would expect

![screenshot from 2018-02-08 11-37-52](https://user-images.githubusercontent.com/34056696/35971081-884325a4-0cc4-11e8-933a-159a63165824.png)

**Comment by pgorod** [comment]
Thanks @PedroErnst 

This was the discussion:
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/17651-no-view-import-results-when-importing-targets

I wonder if it is, in fact, the same issue? I'm not sure.

**Comment by PedroErnst** [comment]
I don't think it is.

But this issue should be fixed now :+1:
