### ISSUE TITLE
Can't move widget to the next column

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#1977]
#### Issue
When widgets are displayed only on left column and you try to move widget from left to right column it won't work, but when there is atleast one widget on right column it works.

#### Expected Behavior
It should shift to right.

#### Actual Behavior
It doesn't hook in the right column, it simply return to the left.
#### Steps to Reproduce
Delete all widgets from right column then try to move widget from left column to right.

#### Context
medium

#### Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 52.0.2743.116 m
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):Win10

**Comment by samus-aran** [comment]
Closing this as this is a duplicate to https://github.com/salesagility/SuiteCRM/issues/1946
