### ISSUE TITLE
Exporting leads when searching using Campaign name

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#198]
If a user searches via campaign name and then selects all leads and tries to export, a database failure message is received and the error outputted:

SELECT leads.*, email_addresses.email_address email_address, '' email_addresses_non_primary, users.user_name as assigned_user_name ,leads_cstm.jjwg_maps_address_c,leads_cstm.jjwg_maps_geocode_status_c,leads_cstm.jjwg_maps_lat_c,leads_cstm.jjwg_maps_lng_c 
FROM leads 
LEFT JOIN users ON leads.assigned_user_id=users.id  
LEFT JOIN email_addr_bean_rel on leads.id = email_addr_bean_rel.bean_id and email_addr_bean_rel.bean_module = 'Leads' and email_addr_bean_rel.deleted = 0 and email_addr_bean_rel.primary_address = 1 
LEFT JOIN email_addresses on email_addresses.id = email_addr_bean_rel.email_address_id  
LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c 
WHERE ((campaign_name like 'campaignname%')) AND  leads.deleted=0

MySQL error 1054: Unknown column 'campaign_name' in 'where clause'

**Comment by Jason-Dang** [comment]
Can no longer replicate in 7.8.x 

Filtered Leads by Campaign Name and successfully exported the resulting Leads.
