### ISSUE TITLE
Notice error on file M2MRelationship.php (SecurityGroup lines)

### ISSUE THREAD

**Issue by gutierrezgarbiero** [salesagility/SuiteCRM#1981]
#### Issue

Hi, i have an issue when i try to import contacts from a .CSV file. 
#### Actual Behavior

This is the error message i get when i try to import:

> NOTICE: [8] Undefined property: Account::$SecurityGroups on line 284 in file /home/bluebamboocomar/public_html/am/data/Relationships/M2MRelationship.php
> NOTICE: [8] Undefined property: Account::$SecurityGroups on line 301 in file /home/bluebamboocomar/public_html/am/data/Relationships/M2MRelationship.php
#### Expected Behavior

I would like to import the contacts from the csv file without problems.
#### Possible Fix

I try adding an "s" ant the end of "SecurityGroup" but didn't solve the problem. In some forums say that a solution is to turn off/disable notices in php.ini file but i don't think that is the best way.

The piece of code betwen lines 265 and 308, from M2MRelationship.php file:

```
/* BEGIN - SECURITY GROUPS */ 
        //Need to hijack this as security groups will not contain a link on the module side
        //due to the way the module works. Plus it would remove the relative ease of adding custom module support

        if(get_class($lhs) == 'SecurityGroup' || get_class($rhs) == 'SecurityGroup') {
            $dataToRemove = array(
                $this->def['join_key_lhs'] => $lhs->id,
                $this->def['join_key_rhs'] => $rhs->id
            );


              if (empty($_SESSION['disable_workflow']) || $_SESSION['disable_workflow'] != "Yes")
              {
                  if (get_class($lhs) != 'SecurityGroup' && $lhs->$lhsLinkName instanceof Link2)
                  {
                      $lhs->$lhsLinkName->load();
                      $this->callBeforeDelete($lhs, $rhs, $lhsLinkName);
                  }

                  if (get_class($rhs) != 'SecurityGroup' && $rhs->$rhsLinkName instanceof Link2)
                  {
                      $rhs->$rhsLinkName->load();
                      $this->callBeforeDelete($rhs, $lhs, $rhsLinkName);
                  }
              }

            $this->removeRow($dataToRemove);

            if (empty($_SESSION['disable_workflow']) || $_SESSION['disable_workflow'] != "Yes")
            {
                if (get_class($lhs) != 'SecurityGroup' && $lhs->$lhsLinkName instanceof Link2)
                {
                    $lhs->$lhsLinkName->load();
                    $this->callAfterDelete($lhs, $rhs, $lhsLinkName);
                }

                if (get_class($rhs) != 'SecurityGroup' && $rhs->$rhsLinkName instanceof Link2)
                {
                    $rhs->$rhsLinkName->load();
                    $this->callAfterDelete($rhs, $lhs, $rhsLinkName);
                }
            }
        } else {
        /* END - SECURITY GROUPS */        

```

I hope you can help me.

Thanks in advance.

**Comment by shogunpol** [comment]
@gotogg , did the contacts actually import? as notice errors, should not affect the import process, unless your error_reporting is not set correctly in your php.ini file.
Notice errors have been noted as a bug and will be dealt with.

**Comment by gotogg** [comment]
@shogunpol I can solve it adding an "s" to "SecurityGroup". When i post this i didn't replace all the "SecurityGroup" to "SecurityGroups". When i did that the error message did not show any more.

Without replacing that not all the contacts were import, only a half of them.

I cosider this issue closed.

Thanks.

**Comment by willrennie** [comment]
Closing issue as per creator's latest comments.
