### ISSUE TITLE
Quick create arrow not aligning to the button text

### ISSUE THREAD

**Issue by Szellszi** [salesagility/SuiteCRM#1987]
#### Issue

The quick create button at the top of the page has an arrow which has a fixed background-position, so if the CREATE text is localized to a longer text (like ERSTELLEN in german) the arrow will be positioned inside the text.

![image](https://cloud.githubusercontent.com/assets/4948556/17809035/0cc2b668-6614-11e6-9eab-9b0a82c3833c.png)
#### Expected Behavior

The arrow should align after the text (or to the right side of the button), no matter how long it is.
#### Actual Behavior

The arrow positioned inside the text if the label is longer than the english CREATE label.
#### Possible Fix

Offset the background to the right instead of fixed position, like:
background-position: right 10px top;
#### Steps to Reproduce

Open SuiteCRM with a language pack installed where the CREATE label is localized to a longer text.
#### Your Environment

- SuiteCRM Version used: 7.7.1
- Browser name and version: Google Chrome 52.0.2743.116 m (64-bit)
- Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
- Operating System and version (e.g Ubuntu 16.04): Windows 10 / Windows Server 2012 R2

**Comment by shogunpol** [comment]
@Szellszi Its assigned as a bug.
Thanks for raise this issue.
