### ISSUE TITLE
New Project Management sub-panels not configurable

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#199]
Users cannot easily display/hide the new project sub-panels introduced with the project management enhancements due to these not being configurable in Admin -> Display Modules and Subpanels.

**Comment by willrennie** [comment]
Display Modules and Subpanels only allows enabling/disabling of subpanels where it is a subpanel for a configurable module such as 'Projects'. Subpanels like 'Resources' do not show as these are not configurable modules within Admin/Studio so would not be applicable in this scenario.

**Comment by sieberta** [comment]
@willrennie - my upgraded version (went from 7.3.x to 7.7.3) didn't get the 'Resources' subpanel, which is causing multiple issues.  Where is this defined so that I can add it, since I cannot add it in Studio?
