### ISSUE TITLE
Studio - custom lead radio field - checkbox_dom - can't delete "-blank-" position

### ISSUE THREAD

**Issue by Eclectitech** [salesagility/SuiteCRM#1997]
On 7.7, I could go into Studio, add a custom field - "Subscription" in this case - then make it a checkbox_dom type. It automatically provides options of "-blank-", yes and no. I could remove the "-blank-" option in 7.7 but can no longer remove it in 7.7.1

#### Issue
Since it worked before but no longer works - same server, same settings, same primary MySQL instance, I assume a bug was introduced that does not enable the editing

#### Expected Behavior
should be able to click trash Icon on the right and remove the -blank- option

#### Actual Behavior
trash icon is not 'clickable'

#### Possible Fix
No idea - just have javascript:void() as browsing

#### Steps to Reproduce
1. go to Admin -> Studio -> Leads -> fields
2. ADD field - data type 'radio'
3. select drop-down list - 'checkbox_dom' and EDIT
4. try to delete -blank- entry

#### Context
I am integrating a subscription service with standard one-time payments with a business in a triangle of wordpress, suiteCRM and Mautic. For clean logic, delete should be possible - presume this is not a low priority as it probably affects numerous custom field entries

#### Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 52.0.2743.116 m 64bit
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 7 - ISPConfig
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
Hi @Eclectitech this is similar to an issue already raised, https://github.com/salesagility/SuiteCRM/issues/1945
and this is resolved by this following PR https://github.com/salesagility/SuiteCRM/pull/1994 scheduled for the next minor release.  That's why I'll set it as a duplicate and close it :smile:

**Comment by Eclectitech** [comment]
Thanks - I tried to find other examples first
