### ISSUE TITLE
On Suite P theme, horizontal scroll bars shouldn't appear

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#1998]
#### Issue

On the Suite P theme, it's a Responsive theme, yet horizontal scroll bars appear.  Even on a 1280 pixel wide LCD.  This is not a good user experience.  Cumbersome to have to scroll horizontally lest you miss some important customer information.  Horizontal scrolling is best avoided in all cases at all times.

#### Expected Behavior

A Responsive theme is supposed to render pages within the constraints of the width of the current browser page width, whether that's 320 pixels, or 1920 pixels, therefore, no horizontal scroll bars should need ever to appear. 

#### Actual Behavior

Horizontal scroll bars do appear, because the theme seems to be miscalculating the width higher than the true width available, then rendering pages wider than the available pixels, and forcing the browser to show horizontal scroll bars which breaks the Responsiveness.

#### Possible Fix

1. This short script - 609 bytes compressed - may be able to help accurately calculate the viewport width, on all browsers.
About the reason this exists: http://matanich.com/2013/01/07/viewport-size
Test: http://tysonmatanich.github.io/viewportSize/
Demo: http://matanich.com/test/viewport-width

2. Also this css ought to keep individual elements within the maximum width.  You can add more also, such as, div, p, table, etc.
```
img {
    max-width: 100%;
    height: auto;
}
embed,
iframe,
object,
video {
    max-width: 100%;
}
```

3. Chrome developer tools - inspect element.  To narrow down the cause of the problem by finding out exactly the width every element is set to or consuming.
https://developer.chrome.com/devtools/docs/dom-and-styles#inspecting-elements

#### Steps to Reproduce

1.  Open firefox 49.0b5. Install add-on "Tab Group" which adds a list of tabs along the left edge of browser window.  Similar to a wide scroll bar, a common setup.  The code was formerly part of Firefox and is not split out into an add-on.  This makes for a slightly different than default, yet totally standard, browser viewport area.
2. Log into suite crm 7.7.1 with suite P theme set as default and the only theme enabled.
2. Home page - shows horizontal scrollbars, which breaks responsive design.
3. Rebuild Schedulers - same.
4. PDF Templates - same.
5. View Contracts - same.
6. Many others...

#### Context

Allowing a horizontal scroll bar is one of the most common mistakes in Responsive Web Design. The horizontal scroll bar occurs when some element on your page is wider than your viewport.

Unnecessarily burdensome on the user to make them stress about remembering to horizontally scroll. Simple solution, the theme should render all information within the browser viewport width.  This may require the use of a small library to help calculate the viewport width properly on all browsers.

#### Your Environment

* SuiteCRM Version used: 7.7.1 , Suite P theme
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0b5
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5 , PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Debian 7

**Comment by shogunpol** [comment]
The issue that you have raised I am unable to replicate, I installed the add-on that you have spoken about however it appears to not have caused any problem with the application. is it possible you could provide a screen shot?. 

There does appear to be more than one reference of the tab groups add on, so it could be possible that the "Tab Groups" add-on I have installed is different.

**Comment by chris001** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/259416/17995088/b24876c8-6b2c-11e6-8633-9908927c33a1.png)
The SuiteCRM application home page, as you can see, is being rendered way too wide by the suitep theme.
The usable width in the browser is exactly 1110px after you subtract the 17px for the vertical scroll bar.
SuiteP theme is rendering it to probably 1500 or 1600 pixels.
The right hand side dashlets, "My Activity Stream," and "SuiteCRM News," are rendering double width of what they should be to fit in their column.
The way Responsive is supposed to work, if the dashlet is too wide to fit the page width, it's supposed to wrap to the next row, in other words, render that overly wide dashlet on the next line.
For some reason the Suite P theme seems to be trying to force certain items onto the same line, when it should actually just let the browser "wordwrap" the various elements such as dashlets, so as to fit the browser.
Remember, the user can always tile their phone or tablet, so you can't set a fixed width the page.  You have to just let the browser wordwrap the various blocks or divs in the best way it can. 
Ultimately, the user won't mind scrolling up and down, or left and right.
But not both up/down AND left/right, that's against the responsive web design rules.

**Comment by shogunpol** [comment]
The issue is labelled as the bug.
Thanks for raise this issue.

**Comment by chris001** [comment]
As you can see in these screenshots, the fix has made a big improvement in eliminating most of the horizontal scroll bar, yet this bug is still there, you still get horizontal scroll bar.

![issue with horizontal scroll bars in suitecrm suitep theme](https://cloud.githubusercontent.com/assets/259416/19839094/85379a60-9eb2-11e6-987f-9fd3c328709b.png)

Obviously there still is some fixed width items, which are being forced onto the layout at too high of a width, they're probably not being calculated responsively as a proportional percentage of the actual current width of the screen viewport and client area, as mentioned originally.

![issue with horizontal scroll bars in suitecrm suitep theme](https://cloud.githubusercontent.com/assets/259416/19839087/722f0250-9eb2-11e6-82b5-45a5499f5261.png)
