### ISSUE TITLE
In SuiteP is missing new icon for Employees module (record)

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2004]
Tested on official SuiteCRM demo site (version 7.7.1)

The icon only for the employees module is missing (is old)... all other modules are ok :)

![empl](https://cloud.githubusercontent.com/assets/5773777/17847257/6356207e-684d-11e6-894f-b462d334e174.png)

**Comment by ijdavie** [comment]
This issue is addressed in the following pull request #1953

**Comment by samus-aran** [comment]
This should be resolved in 7.7.2
