### ISSUE TITLE
AOR Export functionality doesn't respect updated parameters

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#201]
If the user changes the parameters for an AOR report and updates using the functionality on the detail view of the report, and exports the results, the export data returned is built from the original parameters specified on report creation, not the updated parameters. Tested issue and confirmed.

See forum topic: https://suitecrm.com/forum/bug-tracker/4344-reports-export-pdf-csv-does-not-respect-the-parameter-values

**Comment by molnus** [comment]
Is there any update on this? I have just upgraded to 7.4 but still the same.

**Comment by axion-edusca** [comment]
I post in the SuiteCRM Forum a solution for this, but in each upgrade you hace to check if the controller file of AOR_Reports change, for change in the custom/module too. Take a look: https://suitecrm.com/forum/developer-help/6976-report-module-doesn-t-export-in-pdf-or-csv-with-the-users-params

**Comment by ecovantage** [comment]
@axion-edusca your fix worked for me.
Thank You!
