### ISSUE TITLE
Studio - Layouts - Panel name cannot be edited

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#2012]
#### Issue

I can't click pen button to edit a panel name (Highlighted with yellow on image)
![desktop1-03-2016-08-22](https://cloud.githubusercontent.com/assets/6874136/17864770/bb63c154-685c-11e6-9df8-fd9ee4dede44.png)
#### Expected Behavior

Click on pen button and change panel label as needed.
#### Actual Behavior

Pen button cannot be clicked and browser console.log isn't displaying any error.
#### Possible Fix

This is in the new SuiteP theme, maybe something related with css?
#### Steps to Reproduce

1. Go to Administrator Menu -> Admin -> Studio
2. Select any module (Opportunities recommended for this example)
3. Go to Layouts -> EditView
4. On panel **Other** click on pen button, nothing happens.
#### Context

This is a low priority bug
#### Your Environment

- SuiteCRM Version used: 7.7.1
- Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
- Environment name and version:
  - mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
  - PHP Version 5.6.24-1+deb.sury.org~xenial+1
  - Apache/2.4.18 (Ubuntu)
- Operating System and version: 
  - Distributor ID: neon
  - Description:    KDE neon User Edition 5.7
  - Release:        16.04
  - Codename:       xenial

**Comment by shogunpol** [comment]
Thanks for raise this issue. We have raised as a bug.
