### ISSUE TITLE
Upgrade 7.7.x to 7.7.2 fails

### ISSUE THREAD

**Issue by vogelap** [salesagility/SuiteCRM#2022]
#### Issue
I am attempting to upgrade from 7.7.1 to 7.7.2 via the Upgrade Wizard and it fails with the following message: "The uploaded file is not compatible with this version of SuiteCRM: SuiteCRM System Version: 7.7.1"

#### Expected Behavior
The upgrade should complete successfully.

#### Actual Behavior
It fails with the following message: "The uploaded file is not compatible with this version of SuiteCRM: SuiteCRM System Version: 7.7.1".

#### Steps to Reproduce
1. Go to SuiteCRM 7.7.1's Admin page.
2. Select Upgrade Wizard and go through the first check.
3. Specify the file "SuiteCRM-Upgrade-7.7.x-to-7.7.2.zip" and upload it.
4. See the issue.

#### Your Environment
* SuiteCRM Version used: 7.7.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 52.0.2743.116 m (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL , PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubunutu 16.04.1 LTS

**Comment by gokhanerdogdu** [comment]
The same problem also occured on my 7.7.1 instance. The error is same as"
The uploaded file is not compatible with this version of SuiteCRM: 
SuiteCRM System Version: 7.7.1"

**Comment by samus-aran** [comment]
Hi Guys, that is the 7.7.x upgrade package updated - this should pass the preflight checks.
