### ISSUE TITLE
UI Problems - Advanced Search

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2024]
#### Issue
In 7.7.2, there are still UI problems in Advanced Search Screen as attached.

![2016-08-24 12_10_52-advanced search](https://cloud.githubusercontent.com/assets/20369981/17925080/24ad7bc6-69f4-11e6-9622-46b0f650c36f.png)

#### Your Environment

* SuiteCRM Version used: 7.7.2
* Browser name and version (Chrome Version 52.0.2743.116 m):
* Environment name and version (MySQL, PHP 5.6):
* Operating System and version (Ubuntu 16.04):

**Comment by Mausino** [comment]
Similary problem (duplicate) like with bugs  #1967  #1969  #1940

**Comment by samus-aran** [comment]
If you have an issue which already exists add a comment to existing duplicate, thanks. :)
