### ISSUE TITLE
AOW Round Robin is having an issue.

### ISSUE THREAD

**Issue by ioriyong** [salesagility/SuiteCRM#2032]
#### Issue

I have created a workflow and it will be run through a scheduler. The workflow is with the following condition and action as listed below.
1. Condition -> Modules --> status --> Equal To --> One of --> 'blank', New, Recycled.
2. Action --> Modify Record
2a. Record Type = Lead
2a1. Assigned To --> round robin --> ALL Users in role --> Sales Agent
2a2. Status --> Value --> Assigned
#### Expected Behavior

The round robin assignment should be excluding inactive user or employee status = terminated.
#### Actual Behavior

The round robin assignment is including the inactive user or employee status = terminated.
#### Possible Fix

Suggest to exclude the inactive user or terminated employee.
#### Steps to Reproduce

Mentioned above.
#### Context

I am trying to assign a huge listing to all the sales agents. It is very troublesome to assign it manually.
Medium priority bug as the staff turn over is quite high.
#### Your Environment

- SuiteCRM Version used: Version 7.6.6
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 52.0.2743.116 (64-bit)
- Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 5.5
- Operating System and version (e.g Ubuntu 16.04): Mac OS X EL CAPITAN

**Comment by shogunpol** [comment]
This issue was tested on current version of SuiteCRM(7.7.2), and is labelled as a bug.
Thanks for raise this issue, we work on solution.

**Comment by SenileDroid** [comment]
I see that this issue is still open currently. I am experiencing the same issue on version 7.10.9.

Has there been any update or potential workaround identified?

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by lalitrane** [comment]
Hi,

I am having the same issue in Version 7.11.17

This workflow is running 'always' -

Condition -> Modules --> Language --> Equal To --> One of --> 'blank', Mandarin, Hindi, German.
Action --> Modify Record
2a. Record Type = Lead
2a1. Assigned To --> round robin --> ALL Users in Security Group --> Secruritygroupname

Expected Behavior
The round robin assignment should be excluding inactive user or employee status = terminated.

Actual Behavior
The round robin assignment is including the inactive user or employee status = terminated.
