### ISSUE TITLE
Email Template System is broken

### ISSUE THREAD

**Issue by KP987** [salesagility/SuiteCRM#2033]
#### Issue
I can [Compose] and [Send] an email without a problem, but if I apply a template it won't send and I get an error.  Also, if I try to create or edit a template I get redirected to the home page and the add/change is not saved.

#### Expected Behavior
Activities / Emails / [Compose] / [Options] / (select a template) / (add email address) / [Send] / and then the email is delivered.

#### Actual Behavior
An error modal pops-up with a transparent section, followed by a portion of the Dashboard (within the error poup) and the email is not delivered.

#### Possible Fix
Above my pay grade ;-)

#### Steps to Reproduce
(see expected behavior above)

#### Context

This is a high priority item for us, as we use SuiteCRM for telemarketing campaigns using the email templates with every call.

#### Your Environment

* SuiteCRM Version used: 7.7.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Same results on Firefox 47.0.1  and  Chrome 52.0.2743.116
* Operating system : Cent OS 5
* MySQL Version 10.0.23-MariaDB
* PHP version 5.6

#### Other
Q: are there any plans for V8 to replace the email system with something like RoundCube?
(that would be nice)

**Comment by sgaved** [comment]
Hi @KP987 ,

Following these steps: Activities / Emails / [Compose] / [Options] / (select a template) / (add email address) / [Send] 
I am able to send an email doing this. Can you provide any more information about the error? Is there any errors in the suitecrm log or php log?

**Comment by pgorod** [comment]
Hello @KP987 

I wonder if this could be related to issue #1717. I discovered that bug just looking at the code, and I don't have a test case for it. I wonder if your issue is caused by those wrong permissions saving the template.

Maybe you could try applying those changes in your code (changing the 777 to 0777) and checking if the template gets saved correctly? Thanks!

**Comment by KP987** [comment]
I changed 777 to 0777 as instructed, and now I can [Compose] and [Send] emails, but still can't edit or save Templates.  I checked  error_log as instructed and found 3 instances of this error with the same time stamp:
  
[24-Aug-2016 23:15:33 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/upfront/public_html/crm/modules/EmailTemplates/EmailTemplate.php on line 681
  
Line 681, 682, and 683 are as follows (with a bunch of IF statements after that):
  
        foreach ($focus->field_defs as $field_def) {
            $fieldName = $field_def['name'];
            if (isset($focus->$fieldName)) {
  
Please advise (and thank you for your help)

**Comment by pgorod** [comment]
It's interesting that _some_ things started working with that change.

But I'm afraid I don't have much to advise, I don't know. Perhaps some of the data in your database is already inconsistent, because of the previously created templates that couldn't be saved correctly? Can you try on a clean system? Or debug that code to see the values in the variables?

**Comment by ijdavie** [comment]
Hi @KP987,

You may be better asking this in the forums, I have tried replicating this as well as @sgaved, 

is there any errors in the console for the browser ?

**Comment by KP987** [comment]
No. I tested in Fifefox and Chrome.  I think it might be a server config issue, or possibly the result of multiple upgrades on the same SuiteCRM install.  I'm going to try to import mt data into a fresh install on a different VPS next week.  I'm sure that will do it.  In the meantime, I can send Templated emails now, so we're back in business.  Thanks for the help  :-)
