### ISSUE TITLE
Campaign Wizard missing Start and End Date Field.

### ISSUE THREAD

**Issue by ioriyong** [salesagility/SuiteCRM#2034]
#### Issue
The campaign wizard for non email based campaign is missing required fields which is the end date. I've compare the other version and noted that the campaign header should have start and end date of the campaign. The log from SuiteCRM.log is showing -->

Thu Aug 25 10:26:43 2016 [1823][1][FATAL] Error inserting into table: campaigns: Query Failed: INSERT INTO campaigns (id,name,date_entered,date_modified,modified_user_id,created_by,deleted,assigned_user_id,tracker_count,refer_url,end_date,status,impressions,currency_id,budget,expected_revenue,campaign_type,frequency)
					VALUES ('ec4b249a-f867-9581-a052-57be57285b71','September','2016-08-25 02:26:43','2016-08-25 02:26:43','1','1',0,'1',0,'http://','0000-00-00','Planning',0,'-99',20000,40000,'Telesales',''): MySQL error 1292: Incorrect date value: '0000-00-00' for column 'end_date' at row 1
Thu Aug 25 10:26:43 2016 [1823][1][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.

#### Expected Behavior
Expecting that i would be able to create a non email based campaign through the wizard.

#### Actual Behavior
I cannot create the campaign due to some missing fields with the log above.

#### Possible Fix
To us, campaign is quite an important module for us to track and trace on our agent and our conversion result and it is part of automation process. I would like to request this to be fix by adding back the missing field to the wizard.

#### Steps to Reproduce

1. Login as administrator and create a campaign through campaign wizard.
2. Select non email based campaign.
3. Enter all the required value into the wizard for each iteration.

#### Context
I am trying to create a campaign and use it for my own AB testing.
Medium priority because it is needed for me to proceed to the next stage.

#### Your Environment

* SuiteCRM Version used: 7.6.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 5.5
* Operating System and version (e.g Ubuntu 16.04): Mac OS X El Capitan

**Comment by sgaved** [comment]
Hello, 

This query works for me. Do you have strict mode enabled in mysql?

**Comment by ioriyong** [comment]
I am using mysql server 5.7.14. My sql mode is 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'. It must be it. The latest version of mysql is with strict mode...

**Comment by sgaved** [comment]
You need to remove NO_ZERO_DATE . This should fix your issue.

**Comment by ioriyong** [comment]
Thanks and i have done that. Btw, may i know which file i can use to modify the general tab for me to include the start and end date of the campaign?
