### ISSUE TITLE
Can't add new dashboard page on SuiteP

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2039]
#### Issue
Subj.

#### Expected Behavior
Addning new dashboard page

#### Actual Behavior
Nothing happens 

#### Steps to Reproduce
1. Add tab on home page
2. Enter Dashboard Name & Save

#### Your Environment

   * SuiteCRM Version used:  clean 7.7.2 with demo data
   * FF 48.0.1
   * PHP 5.6, Mysql 5.5
   * Debian 8.5

**Comment by samus-aran** [comment]
Hi @likhobory Do you have any error logs or console logs on your browser/instance?  Does the page refresh when you enter Dashboard Name & Save?

**Comment by likhobory** [comment]
> Does the page refresh when you enter Dashboard Name & Save?
Yes
Console log:
unreachable code after return statement

**Comment by likhobory** [comment]
Win7 / Chrome 54.0.2816.0 dev-m (64-bit)
It works.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.3), and it appear, i assign the bug label.
@likhobory , thanks for raise this issue.
