### ISSUE TITLE
Description in module Cases in DetailView shows html tags

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2040]
#### Issue
Description in module Cases in DetailView shows html tags.

#### Expected Behavior
It shouldn't show html tags.

#### Actual Behavior
Shows html tags only in DetailView

#### Steps to Reproduce
Used AOP function to create Case when user sends email to my mailbox but if you create case and fill description field it show html tags too.
#### Context
medium
#### Your Environment
* SuiteCRM Version used: 7.7.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 52.0.2743.116 m
* Environment name and version (e.g. MySQL, PHP 7): 
![hmltags](https://cloud.githubusercontent.com/assets/21075768/17964072/a50b9f7c-6ab8-11e6-8743-1175b0a9b5f0.jpg)
5.5.3
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment]
this is a duplicate #398
