### ISSUE TITLE
Renamed Modules name is not reflected in User Management

### ISSUE THREAD

**Issue by ioriyong** [salesagility/SuiteCRM#2050]
#### Issue

Renamed modules name is not reflected in the access tab under user management.
#### Expected Behavior

The renamed module name should be reflected in the access tab under user management.
#### Actual Behavior

The renamed module is left blanked in the access tab under user management.
#### Possible Fix

If few of the renamed modules is not reflected in the access tab under user management, user might get confused or changes inside that particular function will cause trouble.
#### Steps to Reproduce
1. Rename the module name and save it under admin - Rename Modules.
2. Go to the admin - User Management and click on the access tab.
3. You will notice that the rename module will be blanco.
#### Context

This will affect me if i am not setting any roles to users and i am using user management to control the user access. The renamed modules will be blank.
Low priority because i can use eye ball to track the blanko module name to determine its actual module.
#### Your Environment

SuiteCRM Version used: 7.6.6
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116 (64-bit)
Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 5.5
Operating System and version (e.g Ubuntu 16.04): Mac OS X El Capitan

**Comment by shogunpol** [comment]
I tested this issue and it will be labelled as a bug. As additional information some of the labels even when no change appear to be missing.
Thanks for raise this issue, we work on solution.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
