### ISSUE TITLE
Can't add Spots to Favorites 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2053]
#### Issue

Favorites icon is not displayed on Spot's DetailView.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.2), and it appear, i assign the bug label.
@likhobory  , thanks for raise this issue.

**Comment by horus68** [comment]
@mattlorimer the fix works fine. Please merge it!
