### ISSUE TITLE
Gantt View Overlay covering Project Task popup

### ISSUE THREAD

**Issue by Kaylakaze** [salesagility/SuiteCRM#2057]
When clicking on a task in the Gantt View, the gray overlay covers the popup, preventing any action on the popup.

![gantt_problem](https://cloud.githubusercontent.com/assets/1363591/18009005/6edf0dc4-6b78-11e6-8239-341c7eb19323.JPG)

Technical aspect of problem:
The ui-dialog box in question has the ui-front class assigned to it which gives it a z-index of 1100 !important-ed. The element itself has a z-index of 1101 applied to it, however, it is not !important so the specified z-index is not taking effect.

Solution:
add !important to the popup box element's style tag.
#### Your Environment

SuiteCRM 7.7 tested on both Chrome and Firefox with both R and P themes.

**Comment by samus-aran** [comment]
Hi @Kaylakaze this was resolved in 7.7.1 - please let us know upgrading resolves the issue.

**Comment by Kaylakaze** [comment]
Updating to 7.7.3 seems to have fixed it in the P theme. Is there any easy way to modify the P theme? It's way to fat as it is. Could you explain where this problem exists in the theme so that I can fix the R theme?

**Comment by Kaylakaze** [comment]
I removed the .ui-front class definition from the style.css file and that seems to have worked. Let me know if that's not the correct way to fix this.

**Comment by shogunpol** [comment]
@Kaylakaze ,I tested again your issue on recent version of SuiteCRM(7.7.3), and after you provided additional information, i been able to replicate the bug.
The bug is appear when Mozilla Firefox is used, in Chrome issue doesn't exist.
We label this issue as a bug.
Thanks for raise this issue.
Partially Related to #2058

**Comment by samus-aran** [comment]
This should be resolved - tested in Chrome and Firefox.

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.
