### ISSUE TITLE
Gantt View Page Reload failure

### ISSUE THREAD

**Issue by Kaylakaze** [salesagility/SuiteCRM#2058]
When using Project Gantt view and adding or editing a task in a project created from a template, the page hangs with "Loading Page, Please wait...". There is a "main_lib.js:605 Uncaught TypeError: Cannot set property 'width' of undefined" error in the console log on Chrome and "TypeError: rect is undefined rect.width = item.width();" in Firefox, which may be preventing further JS processes and clearing of the overlay.

In Project Template mode, an action that causes a "Loading Page" popup then makes popups (such as Add Task) into "Powered by SugarCRM" boxes.

SuiteCRM 7.7.3

**Comment by Kaylakaze** [comment]
Further testing has led me to believe that the reload and JS error is a result of having a predecessor task in the template. The new project from the template seems to have broken predecessor functionality (predecessor list is empty). When I un-predecessored the tasks in the template and made a new project, I had no problems.

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and the issue is not appear.
Can you give me some more details about this issue, for example:
- Your environment?
- Is this issue appear only for tasks with predecessor?
- and any other details what you think ,may be useful to replicate the bug.
Thanks for raise this issue.

**Comment by Kaylakaze** [comment]
The non-reload issue only appears to be on tasks made from project templates that have a predecessor. I suspect that something is not setting the predecessor properly in the new project which is causing the conflict. If I make the predecessor after the new project creation, it works as expected.

The "Powered by SugarCRM" happens all the time with Project Templates, regardless of predecessors.

Our Suite instance is running on Ubuntu. Frontend was tested on both Chrome and Firefox in Windows 10. I've tested with both the P and R themes.

Replication:
1) Create project template
2) Add two tasks to the template, one being a predecessor of the other
3) Create a new project with this template
4) View new project's Gantt view
5) Go to Project Templates and view the Gantt chart for the newly created template
6) Open the popup by selecting the first task
7) Close the popup
8) Re-open the popup by clicking either task or the Add Task button

**Comment by shogunpol** [comment]
@Kaylakaze  ,I tested again your issue on recent version of SuiteCRM(7.7.3), and after you provided additional information, i been able to replicate the bug.
The bug is appear when Mozilla Firefox is used, in Chrome issue doesn't exist.
We label this  issue as a bug.
Thanks for raise this issue.

**Comment by Kaylakaze** [comment]
It happens for me on Chrome as well. How you can't duplicate it in Chrome is beyond me.

**Comment by noelhunter** [comment]
I get the following php errors logged:

PHP Fatal error:  Maximum execution time of 60 seconds exceeded in modules/Project/controller.php on line 187, referer: /index.php?module=Project&action=view_GanttChart&project_id=

PHP Fatal error:  Call to a member function format() on a non-object in /modules/Project/controller.php on line 102

**Comment by noelhunter** [comment]
The loop in controller.php arounf line 187 is while $duration >= $d, but never increments $duration

**Comment by noelhunter** [comment]
So in this code in modules/Project/controller.php 

`
while($duration >= $d){
    $day = $enddate->format('l');
    //$GLOBALS['log']->fatal( $day . '--' . $bhours[$day] );
        if($bhours[$day] != 0 ){
             $d += 1;	
        }
        $enddate = $enddate->modify('+1 Days');
} `

If $bhours[$day] != 0 always evaluates to false, the while loop never exits.

**Comment by samus-aran** [comment]
@noelhunter @Kaylakaze This should be resolve in the upcoming release.  Issue experienced is that if you didn't have $bhours set (at all in the database) it would do an infinite loop.  This has been addressed and will be available in 7.8.4+ and 7.9.0

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.
