### ISSUE TITLE
New Record Workflow fails on Campaign Log modules

### ISSUE THREAD

**Issue by klou** [salesagility/SuiteCRM#206]
https://github.com/salesagility/SuiteCRM/blob/2c529f735a72ad6730a692660249175797be7d0b/modules/AOW_WorkFlow/AOW_WorkFlow.php#L369

When building the query, this apparently looks for `*.date_entered`, which does not exist on the `campaign_log` table.  Instead, there's `activity_date`.

Log:
`Invalid column name 'date_entered'.: SELECT campaign_log.id AS id FROM campaign_log  WHERE campaign_log.activity_type = N'link' AND campaign_log.target_type = N'Contacts' AND campaign_log.date_modified > N'2015-04-10 21:13:31' AND campaign_log.date_entered <> campaign_log.date_modified AND NOT EXISTS (SELECT * FROM aow_processed WHERE aow_processed.aow_workflow_id=N'a3d3dcc8-351d-0f37-736c-55283cb395d4' AND aow_processed.parent_id=campaign_log.id AND aow_processed.status = N'Complete' AND aow_processed.deleted = 0) AND campaign_log.deleted = 0`

My end goal is to create a workflow based off of Campaign Click-thrus.

A solution might be to change the `campaign_log.activity_date` to `date_entered` to leave the Workflow module alone.

**Comment by shogunpol** [comment]
@klou , can you provide more information about an issue? Im not sure what you mean by: "My end goal is to create a workflow based off of Campaign Click-thrus."
and, can you confirm is that issue still appear in recent version of SuiteCRM(7.8.1) ?

**Comment by klou** [comment]
Sorry, I no longer use SuiteCRM.  

However, I was referring to an automation event/workflow that is triggered by tracked Click-thru, specifically scheduling followup calls on an assigned account manager's To Do based upon a target's URL click.

More specific to the bug was a mislabeling of columns in the query vs. what was in the db schema at the time (don't know if it's been resolved).

**Comment by Jason-Dang** [comment]
@klou The issue with the missing database column for 'date_entered' should be resolved shortly. I'm aware you said you don't use SuitCRM anymore but just for future clarification when a target clicks-thru on a campaign email, a new record is created in the 'campaign_log' table with an 'activity_type' value of 'link'. To catch this in a Workflow you would need to set it to run on new records and have a condition to check this 'activity_type' value is 'link'.
