### ISSUE TITLE
QuickCreate menu, mouse cursor does not highlight menu items as it goes over them.

### ISSUE THREAD

**Issue by zebelcrm** [salesagility/SuiteCRM#2060]
#### Issue

QuickCreate menu, mouse cursor does not highlight menu items as it goes over them.
#### Expected Behavior

When the cursor goes over a navigation menu item, it should be highlighted.
#### Actual Behavior

You don't see any highlighted menu items.

*Added on 09/19/2016:

The same holds true of both QuickCreate Menu Items and the Action button on the homepage (for dashlets and tabs).

![image](https://cloud.githubusercontent.com/assets/20979933/18654040/f492129a-7e92-11e6-9a8e-e1a523355e77.png)
#### Steps to Reproduce

1.
2.
3.
4.
#### Your Environment

- SuiteCRM Version used:
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04):

**Comment by zebelcrm** [comment]
Sorry, SuiteCRM version 7.7.3
Running on Linux Ubuntu/PHP/MYSQL

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and it will be labelled as a bug. 
Thanks for raise this issue.

**Comment by zebelcrm** [comment]
The same goes for the actions button on the home page where you can add dashlets and/or tabs.

![image](https://cloud.githubusercontent.com/assets/20979933/18653946/70a323e8-7e92-11e6-969c-ab7cade13782.png)

**Comment by samus-aran** [comment]
This can be done via Sass provided the fix below:
https://github.com/salesagility/SuiteCRM/pull/3199

**Comment by zebelcrm** [comment]
Do I have to make the changes manually or will they be included in the next release?
 
--------- Original Message --------- Subject: Re: [salesagility/SuiteCRM] QuickCreate menu, mouse cursor does not highlight menu items as it goes over them. (#2060)
