### ISSUE TITLE
responsive theme 'next page' button when multiple 'my cases' exist

### ISSUE THREAD

**Issue by mwattley** [salesagility/SuiteCRM#2061]
#### Issue

When the home page has multiple 'my cases' dashlets (i use them with different filter settings) in two columns, clicking the 'next page' button on one of the re-draws multiple dashlets, instead of just the one clicked.  Same behaviour in chrome, firefox, edge.
#### Expected Behavior

Only the clicked dashlet should re-draw.
#### Actual Behavior

multiple dashlets re-draw in place of the single one clicked.  Page then looks like it has three columns.
#### Possible Fix

i'm guessing the dashlet buttons for a given module all have the same name.  keep track of how many dashlets are on the page, and give their controls unique names
#### Steps to Reproduce

1. Add a 'my cases' dashlet to the home page in column one
2. Add another 'my cases' dashlet to the home page in column two
3. Click the 'next button' on one of the dashlets.
   4.
#### Context

I use multiple 'my cases' dashlets with different filters to keep track of which team members are working on which cases, and how many they have open.

low priority.  we can continue to use suite 7 theme
#### Your Environment

webuzo virtual appliance
- SuiteCRM Version used: 7.7.3
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
  firefox 48.0.2
  chrome 52.0.2743.116 m
  edge 38.14393.0.0
  all on windows 10 64 bit
- Environment name and version (e.g. MySQL, PHP 7):
  mysql
  php 5.5.38
- Operating System and version (e.g Ubuntu 16.04):
  centos 6.4 64bit

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and it will be labelled as a bug. 
Thanks for raise this issue.

**Comment by sieberta** [comment]
@gymad, @ijdavie,
I attempted this hotfix on 7.7.4 with SuiteR theme, and it does not seem to be effective...  I did switch to SuiteP and it worked as anticipated, although switching pages seems very slow...
sieberta

**Comment by sieberta** [comment]
My apologies, the bug is apparently a bit different on SuiteR than SuiteP.  Simply nothing happens when the "next" button is pressed, rather than all modules refreshing/paging.  But the point still remains, this fix doesn't resolve it.

**Comment by shogunpol** [comment]
@sieberta , i confirm the issue has been tested on the recent version of SuiteCRM(7.7.5) , and it appears on suite-R theme only(SuiteP works fine).
Thanks for your contribution.
