### ISSUE TITLE
Forward/Back Buttons on Email Screen in Suite P & Suite R Missing

### ISSUE THREAD

**Issue by idfbobby** [salesagility/SuiteCRM#2068]
When looking at the email screen for a shared inbox, the next page and previous page buttons do not show up.  They appear to be hidden under the frame so that you can not advance to the next page to view additional unread emails, etc.  The Suite 7 Theme doesn't appear to have this problem.  I've tried in Chrome and Firefox and can duplicate the problem in both under both themes.

#### Issue
When looking at the email screen for a shared inbox, the next page and previous page buttons do not show up.  They appear to be hidden under the frame so that you can not advance to the next page to view additional unread emails, etc.  The Suite 7 Theme doesn't appear to have this problem.  I've tried in Chrome and Firefox and can duplicate the problem in both under both themes.

#### Expected Behavior
You should be able to move to next and previous pages.

#### Actual Behavior
You are unable to move to next and previous pages

#### Steps to Reproduce
Go to /index.php?module=Emails&action=index&
1.
2.
3.
4.

#### Context
We are unable to view emails outside of the ones that are loaded up into the screen.  The arrows went away quite a while back and haven't returned, so we would consider them a high priority now.  Kept hoping it would get resolved in another release. (Sorry, My bad)

#### Your Environment
* SuiteCRM Version used: 7.7.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MySQL
* Operating System and version (e.g Ubuntu 16.04): Debian

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and it will be labelled as a bug. 
Thanks for raise this issue.

**Comment by bennnjamin** [comment]
Is there any update on this? It makes the email module basically unusable. I am willing to take a look at a fix if you can point me in the right direction.

This occurs on 7.7.5

**Comment by bennnjamin** [comment]
@shogunpol Found someone who suggested a fix in SuiteCRM forums (https://suitecrm.com/forum/installation-upgrade-help/3965-mail-pagination-is-not-working) which involved changing bootstrap.min.css. That's not really practical since bootstrap is maintained by a 3rd party.

Instead there is a file EmailUI.css which seems to override some bootstrap css properties.

Applying the fix starting on line 361 seems to work (the pagination class is moved to a support css block):

`#listViewDiv {
    margin-bottom: 10px;	
}

.pagination {
    margin: -20px 0;	
}`

**Comment by shogunpol** [comment]
@bennnjamin , the fix for this issue is on related issue #163

**Comment by corellon1** [comment]
Have you found a solution to this problem?
In version 7.8.1 the problem still exists.

![image](https://cloud.githubusercontent.com/assets/10621279/23184005/47ab739e-f87e-11e6-8106-8d2ec36700da.png)

**Comment by ijdavie** [comment]
@corellon1, There is a fix on a related issue which may fix the issue that you are seeing. #163

**Comment by billlee76** [comment]
If you dont carry on to the link above. I suggest this : 

A
![email-fix](https://user-images.githubusercontent.com/28277354/34790818-d9a3e980-f5f7-11e7-876a-0a6fbaf4f3b0.jpg)
dding this to the bottom of your EmailUI.css this way you dont modify any original code: This puts everything nicely on one line for you.
#listViewDiv {
margin-bottom: 10px;
}
.pagination {
margin: -5px 0;
}
.paginator-start {
height: 13px;
}
.paginator-previous {
height: 13px;
}
.paginator-next {
height: 13px;
}
.paginator-end {
height: 13px;
}
