### ISSUE TITLE
SuiteP Theme: vertical scroll bar appearing

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2069]
#### Issue

I'm seeing a vertical scroll bar to the right of the tab titles in detail view (in any module) at certain zoom levels -> See screenshot example at 90% zoom.

![screen shot 2016-08-30 at 11 41 37](https://cloud.githubusercontent.com/assets/15463075/18084254/c643c984-6ea6-11e6-8af6-6b21c2cebc30.jpg)

#### Expected Behavior

no vertical scroll bar ever appears along titles of any kind.

#### Actual Behavior

vertical scroll bar appears along the titles of the tabs depending on browser zoom level

#### Steps to Reproduce

1. open detail view of (e.g.) a contact dataset with at least two tabs showing
2. zoom out in the browser
3. notice the vertical scroll bar appearing to the right of the tabs
4.

#### Your Environment

* SuiteCRM Version used: Version 7.7beta2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 52.0.2743.116 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Mac OS 10.11.6

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.3), and it not appear.
Can you try replicate this again on recent version of SuiteCRM(7.7.3), 
And when you upgrade, please do repair->quick repair and rebuild
@EZS-JD  , thanks for raise this issue.

**Comment by EZS-JD** [comment]
I upgraded and tested on SuiteCRm 7.7.3. Whole theme looks alot better and this problem not longer occurs. Thanks!

**Comment by ijdavie** [comment]
@EZS-JD, Thanks for the update, We will close this issue as it no longer occurs.
