### ISSUE TITLE
Turkish Character Problems

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2074]
#### Issue
When Turkish localization package is loaded, there are some problems in some Turkish special characters. Below is the sample screenshot. 

In Turkish there are special characters as ı, İ, Ğ, etc.

![2016-08-30 16_11_48-turkish-characters](https://cloud.githubusercontent.com/assets/20369981/18090391/2f6e4bac-6ecd-11e6-9512-9b0fe9723690.png)

#### Your Environment

SuiteCRM Version used: SuiteCRM 7.7.3
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (MySQL, PHP 5.5): https hosting.

**Comment by shogunpol** [comment]
The translations for SuiteCRM are made by: https://crowdin.com/project/suitecrmtranslations 
and can be contributed back there. 
@horus68 may be able to help with this.  
Thanks for contribution.

**Comment by gokhanerdogdu** [comment]
Hello,

The problem is not seem to be about translated strings. The strings seem to be correct in the project. But some special Turkish characters are not seen as correct for some cases. Can it be because of some settings in SuiteCRM?

**Comment by shogunpol** [comment]
@gokhanerdogdu ,I did check the language translation for this issue, and the strings in language files appear to match what i seen in this screenshot, in the language strings that we checked.

This leads us to believe the issue lies with the translation of the strings rather than how the instance is displaying these.

**Comment by gokhanerdogdu** [comment]
Thank you very much for the explanation @shogunpol . You are correct that there are problems in the downloaded language file. Just a quick question. I edited the translations on crowdin, but when I downloaded the package from crowdin again after correcting the problems, I can not see the corrected translation on the downloaded package. What am I missing?

**Comment by shogunpol** [comment]
@gokhanerdogdu  , you can edit the files you downloaded and manually change names, and install the packagein terms of update or contribute in public, if is not updating them you best person to contact, would be @horus68 .

**Comment by horus68** [comment]
The language packs requires a rebuild (done daily or by request) so the new translations are included.
You can see the time of last rebuild on the right column of the crowdin project page https://crowdin.com/project/suitecrmtranslations

Note: you should delete all wrong translations so they are cleared also from the translation memory, not just approve new ones)
