### ISSUE TITLE
PDF-Template Chooser: Implement Sort order!

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2076]
#### Issue

When choosing a PDF-Template e.g. in the Invoices Module by clicking on Action "Print PDF", I see all active PDF-Templates for this module in a little popup-window to choose the desired template. This list of templates is not sorted in any way I can figure out and makes it very user-unfriendly. Please implement a sort order!

PS: The template chooser windows looks a bit crammed for my taste -> maybe add some more padding to fit more into the rest of the Suite P theme?

#### Expected Behavior

List of possible PDF-Templates sorted by name.

#### Actual Behavior

List of possible PDF-Templates randomly sorted.

#### Your Environment

* SuiteCRM Version used: 7.7.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment]
This has been raised as a suggestion before on #712. I will close this one and any new information can be added to the existing suggestion.
