### ISSUE TITLE
Dublicate meetings

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2083]
#### Issue
When two attendees are selected during meeting creation, two dublicate meetings are created in stead of one. When one of the attendees is deleted, the dublicate meeting is alao deleted. 

#### Expected Behavior
Only one meeting should be created whether there is one or more attendees on the card. 

#### Steps to Reproduce
In the create meeting screen, at the bottom of the card select two attendees except the creater of the meeting. Then two dublicate meetings will be created in stead of one. 

#### Your Environment

* SuiteCRM Version used: 7.7.3
* Browser name and version ( Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (MySQL, PHP 5.6):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by samus-aran** [comment]
Hi @gokhanerdogdu I was unable to replicate this.

Step 1. Go to Meetings module
Step 2. Schedule a Meeting
Step 3. Add Attendees (myself, Contact and Lead)
Step 4. Saved
Step 5. Taken me to the detail view of the Meeting, and confirmed all three invitees where in their appropriate sub panels
Step 6. Go to Meetings List view (again)
Step 7. confirm only one meeting of that name exists
Step 8. Checked the attendees records and compare record ids with their Meeting in their activities sub panel.

Let me know if I have missed or added steps to try and replicate this?

**Comment by gunnicom** [comment]
Are really two meetings created, or is the same meeting (same ID) shown twice?

**Comment by gokhanerdogdu** [comment]
When I check the id's of the records, they are same. Then is this problem about only listing problem?

**Comment by mattlorimer** [comment]
this is intended behaviour if you don't want this don't show the contact in list view

**Comment by gokhanerdogdu** [comment]
Thanks for your explanations. As I understand, this is working as desired. As a feature request, it may be listed as Contact1 ; Contact2 in list view in one row if there are more than 1 attendees rather than listing the same record in multiple rows. What do you think? Can we tag it as "Feature Request"?
