### ISSUE TITLE
Date Field in Report Module shows time

### ISSUE THREAD

**Issue by mdemaree99** [salesagility/SuiteCRM#2084]
#### Issue

Date Field in Report Module appears as datetime field.  
Field shows time vs just date.

#### Expected Behavior
Date Created Field should show Date only without timestamp
Date fields in Reports should show Date only without timestamp
ie..  08/30/2016

#### Actual Behavior

Date Created Field shows Date and Timestamp.  
Dates fields in reports show Date and Timestamp.
ie..  08/30/2016  20:22

#### Steps to Reproduce

1.  Click All --> Reports  (If reports has already been created you can see date and time of report)
2.  Run any report.  Date field will show timestamp

#### Context
  Should not show timestamp.

#### Your Environment

* SuiteCRM Version used:  SuiteCRM Version 7.7.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Firefox
* Environment name and version (e.g. MySQL, PHP 7):  MySQL

**Comment by samus-aran** [comment]
Hi @mdemaree99 this is expected behaviour.  The Date Created and other core datetime fields ( like Date Modified) are displayed as they would be in a normal module list view.  Feel free to update this ticket if I have misinterpreted the issue.

**Comment by mdemaree99** [comment]
Fields with a DATE format are showing Date and Time in the report module.
Example:  Contacts:  birthdate
In reports shows up as DateTime
![date_field_format](https://cloud.githubusercontent.com/assets/3958770/18174290/a6d035d2-7032-11e6-9f24-ba830d1a3fdd.png)

In normal View shows Date.

**Comment by mdemaree99** [comment]
![report_date__field_opportunity_compare](https://cloud.githubusercontent.com/assets/3958770/18278196/be348a9c-7416-11e6-9879-81f0e8dfbf53.png)
See attached example of Report using Opportunity Module and compare it to the  actual Opportnity Module.  Date field shows the time in the report.
