### ISSUE TITLE
Subpanels in Cases expands,  drop-down list shifted behind the screen

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2085]
#### Issue
Subpanels in Cases expands, drop-down list shifted behind the screen, 
![subpanel](https://cloud.githubusercontent.com/assets/21075768/18120304/2ea14110-6f5f-11e6-98a9-884806225dfd.jpg)
( tested on 1366x768 and 1920 x 1080)

#### Expected Behavior
It shouldn't expands, drop-down list should be shifted to right

#### Actual Behavior
Subpanels in Cases expands, drop-down list shifted behind the screen

#### Steps to Reproduce
1. Go to studio>Cases>
2.  Add Panel in DetailView
3. Save and deploy
4.  Go to admin> quick repair

#### Context
medium/high

#### Your Environment
* SuiteCRM Version used: 7.7.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 52.0.2743.116 m
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Win10

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and it will not appear.
@tomi798  , can you give me more details about your SuiteCRM (version and also is that upgraded or fresh version)?
Also can you confirm did you do 'admin->repair->quick repair and rebuild'? 
Thanks for raise this issue.

**Comment by tomi798** [comment]
This problem occured in suite 7.7.3( it was upgraded from 7.7.1 to 7.7.2 and to 7.7.3) but i installed fresh suite(7.7.3) few mins ago and problem occured again. I did the same steps:
1: Created case
2. Went to studio>Cases>Layouts>DetalView
3. Droped new panel below case updates panel
4. Droped address field to that panel(just for example, it could be anything)
5. Clicked save and deploy
6.On new chrome tab went to admin->repair->quick repair and rebuild
7. Then ctrl+f5 chrome browser and the problem appeared again
@shogunpol
