### ISSUE TITLE
Add Dashlets not working under theme Suite P version 7.7

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#2086]
#### Issue

With theme Suite P I am unable to add dashlets because items are never loaded. 
When I click the "add dashlets", the popup would open with the loading gif and that's it.  Loading.gif is running entirely. Tried it in FireFox, IE and Chrome but the problem persists in all of them.
When in any other theme (eg theme 7) dashlets panel loads items and everything works fine.

#### Your Environment

* SuiteCRM Version used: 7.7.3
* Browser name and version: FireFox 48.0.2
* Environment name and version: IIS7,5 MySQL, PHP7.0.9, wincache2.0
* Operating System and version: Windows 7

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and i been not able to replicate the issue.
May i ask for some more details like: console logs, server/system logs.  
Thanks for raise this issue.

**Comment by vmijalkovic** [comment]
When logged in there are few error related to fonts for this theme:

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/1YwB1sO8YE1Lyjf12WNiUA.woff2"

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/UyBMtLsHKBKXelqf4x7VRQ.woff2"

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/EsvMC5un3kjyUhB9ZEPPwg.woff2"

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/H2DMvhDLycM56KNuAtbJYA.woff2"

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/PLygLKRVCQnA5fhu3qk5fQ.woff2"

"NetworkError: 404 Not Found - http://localhost/php/crm/sugarcrm/themes/SuiteP/fonts/tI4j516nok_GrVf4dhunkg.woff2"

But when I click on "add dashlets" nothing is being logged (no error, no warning, nothing)

**Comment by vmijalkovic** [comment]
Ok. I found something. Could be related. For some reason I get NetworkError for js file:

NetworkError: A network error occurred.
http://localhost/php/crm/sugarcrm/cache/include/javascript/sugar_grp1_jquery.js?v=siXuaH_ar4QjeO0OZbuy9A
Line 4

Do you have any idea what is going on?

**Comment by shogunpol** [comment]
@vmijalkovic , Can you check permissions for SuiteCRM folder, they need to be at least for write.

**Comment by vmijalkovic** [comment]
IUSR and IIS_IUSR set to FULL permission on the complete suitecrm folder and all subfolders

**Comment by shogunpol** [comment]
@vmijalkovic , I tested this issue on recent version of SuiteCRM(7.7.3) and it will be labelled as a bug. 
Thanks for raise this issue.

**Comment by staganyi** [comment]
I have the same issue since upgrading from 7.2 to 7.7 using SuiteP theme, I can't add dashlets. If I switch to Suite7 theme, I can. I did a clean install to test on 7.7.3 and I could add dashlets with SuiteP theme.

**Comment by raidoa** [comment]
Had same issue with the 7.7.4.
Tried to add new Dashlets - they will not appear. But seems that the system registers them (based on the query that updates the **user_preferences** table (I tried to add Calendar and other widgets multiple times).
The decoded base64 that is used to update the user_preferences was like that (although the calendars and others do not appear):

`a:2:{s:8:"dashlets";a:20:{s:36:"7a9fa571-2254-04c3-ab46-57cb47741bc0";a:5:{s:9:"className";s:14:"MyCallsDashlet";s:6:"module";s:5:"Calls";s:11:"forceColumn";i:0;s:12:"fileLocation";s:56:"modules/Calls/Dashlets/MyCallsDashlet/MyCallsDashlet.php";s:7:"options";a:0:{}}s:36:"7dd3e5cd-4928-0840-bc74-57cb471241c5";a:5:{s:9:"className";s:17:"MyMeetingsDashlet";s:6:"module";s:8:"Meetings";s:11:"forceColumn";i:0;s:12:"fileLocation";s:65:"modules/Meetings/Dashlets/MyMeetingsDashlet/MyMeetingsDashlet.php";s:7:"options";a:0:{}}s:36:"7ee65004-be14-6cda-7d14-57cb47403621";a:5:{s:9:"className";s:22:"MyOpportunitiesDashlet";s:6:"module";s:13:"Opportunities";s:11:"forceColumn";i:0;s:12:"fileLocation";s:80:"modules/Opportunities/Dashlets/MyOpportunitiesDashlet/MyOpportunitiesDashlet.php";s:7:"options";a:0:{}}s:36:"82021403-2d0d-6f1f-cd95-57cb4725ff05";a:5:{s:9:"className";s:17:"MyAccountsDashlet";s:6:"module";s:8:"Accounts";s:11:"forceColumn";i:0;s:12:"fileLocation";s:65:"modules/Accounts/Dashlets/MyAccountsDashlet/MyAccountsDashlet.php";s:7:"options";a:0:{}}s:36:"8393b3ae-df3a-3b38-b58c-57cb473ef55b";a:5:{s:9:"className";s:14:"MyLeadsDashlet";s:6:"module";s:5:"Leads";s:11:"forceColumn";i:0;s:12:"fileLocation";s:56:"modules/Leads/Dashlets/MyLeadsDashlet/MyLeadsDashlet.php";s:7:"options";a:0:{}}s:36:"23b90e4c-526f-f7ed-c7ac-57dc3c2371fb";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"7d27c194-ed30-1684-cf8f-57dc3c298cd8";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"5d88b152-9b57-a134-d59d-57dc3cd890df";a:4:{s:9:"className";s:14:"MyTasksDashlet";s:6:"module";s:5:"Tasks";s:7:"options";a:0:{}s:12:"fileLocation";s:56:"modules/Tasks/Dashlets/MyTasksDashlet/MyTasksDashlet.php";}s:36:"1cd6ec82-963f-c6ff-2c7b-57dc3c5eac91";a:4:{s:9:"className";s:14:"MyTasksDashlet";s:6:"module";s:5:"Tasks";s:7:"options";a:0:{}s:12:"fileLocation";s:56:"modules/Tasks/Dashlets/MyTasksDashlet/MyTasksDashlet.php";}s:36:"3f15a9f4-c6d2-fa5d-01ab-57dc3f43748f";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"525674e4-bd77-33ee-4624-57dc40d32c54";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"ed6bda9b-3fdb-3fe7-35a3-57dc5b5658d9";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"d678026e-128c-bbff-9cdb-57dc5b5f9360";a:4:{s:9:"className";s:20:"AOS_ContractsDashlet";s:6:"module";s:13:"AOS_Contracts";s:7:"options";a:0:{}s:12:"fileLocation";s:76:"modules/AOS_Contracts/Dashlets/AOS_ContractsDashlet/AOS_ContractsDashlet.php";}s:36:"7c7736d7-f957-9cb3-218d-57dc5bcb59c2";a:4:{s:9:"className";s:14:"MyCallsDashlet";s:6:"module";s:5:"Calls";s:7:"options";a:0:{}s:12:"fileLocation";s:56:"modules/Calls/Dashlets/MyCallsDashlet/MyCallsDashlet.php";}s:36:"49b7edc5-2dd5-0d56-b8a8-57dc5b0b0870";a:4:{s:9:"className";s:15:"MyEmailsDashlet";s:6:"module";s:6:"Emails";s:7:"options";a:0:{}s:12:"fileLocation";s:59:"modules/Emails/Dashlets/MyEmailsDashlet/MyEmailsDashlet.php";}s:36:"71dfb239-af30-9f36-f8e9-57dc5d916ce2";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"cd3f31f2-9fc5-8cfc-1e51-57dc5d989d95";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"20fd7aeb-d324-81d2-a820-57dc5eeb2b75";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"4f217d6c-5aaf-f5ff-f07c-57dc5efb8c68";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}s:36:"83aa29d5-480c-c413-e09d-57dc5e2ba63f";a:4:{s:9:"className";s:15:"CalendarDashlet";s:6:"module";s:8:"Calendar";s:7:"options";a:0:{}s:12:"fileLocation";s:61:"modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php";}}s:5:"pages";a:1:{i:0;a:3:{s:7:"columns";a:2:{i:0;a:2:{s:5:"width";s:3:"60%";s:8:"dashlets";a:4:{i:0;s:36:"7dd3e5cd-4928-0840-bc74-57cb471241c5";i:1;s:36:"7ee65004-be14-6cda-7d14-57cb47403621";i:2;s:36:"82021403-2d0d-6f1f-cd95-57cb4725ff05";i:3;s:36:"8393b3ae-df3a-3b38-b58c-57cb473ef55b";}}i:1;a:2:{s:5:"width";s:3:"40%";s:8:"dashlets";a:1:{i:0;s:36:"7a9fa571-2254-04c3-ab46-57cb47741bc0";}}}s:10:"numColumns";s:1:"3";s:14:"pageTitleLabel";s:20:"LBL_HOME_PAGE_1_NAME";}}}`


 If there is any way I can help with debugging, please give some guidelines and I'll do my best.

**Comment by ijdavie** [comment]
This could be down to what dashlets you have already on the tab, is this the default tab or a newly created tab. ?

**Comment by staganyi** [comment]
I think @raidoa has a separate issue, where he can add a dashlet but it doesn't show up afterwards? The initial issue is the "Add Dashlets" popup does not load anything. See below.

![image](https://cloud.githubusercontent.com/assets/20977561/18716382/a3be6658-7fea-11e6-93df-368523a2b5c0.png)

**Comment by raidoa** [comment]
@staganyi I guess you are right. I also discovered that in my case changing theme does not help, neither does adding new Tab.
I'll create separate issue.

**Comment by ijdavie** [comment]
has anyone tried to reset the dashets for the user which is having the problems to see if that makes any difference, anything in the logs even the console log ?

**Comment by staganyi** [comment]
Yes, that is the first thing I tried without luck.

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.5) and i been not able to replicate the issue.
@vmijalkovic , can you confirm is that issue not appear on recent version of SuiteCRM? If yes can you close an issue?

Thanks for your contribution.

**Comment by staganyi** [comment]
I will test this again at some point today, but in my case the issue was only present on an upgraded instance (from 7.2) and was not a problem on a clean install.

**Comment by shogunpol** [comment]
@staganyi   , If you test this for us it will be great, so we can close an issue.
thanks for your contribution.

**Comment by staganyi** [comment]
On a 7.7.5 clean install, the "Add Dashlets" works under SuiteP but not Suite7 or SuiteR. No console or log errors.

SuiteP
![image](https://cloud.githubusercontent.com/assets/20977561/19127257/3f0e30da-8b0c-11e6-8083-4b5264faa15f.png)

Suite7
![image](https://cloud.githubusercontent.com/assets/20977561/19127186/fcc548b2-8b0b-11e6-9e6e-0ce2c95d4deb.png)

SuiteR
![image](https://cloud.githubusercontent.com/assets/20977561/19127328/792fe5ce-8b0c-11e6-990d-6577f791d36a.png)

**Comment by staganyi** [comment]
Same behavior on my 7.7.5 upgraded instance (from 7.2). Originally I had mentioned that the "Add Dashlets" popup would not load any items on the SuiteP theme, but after some digging, I found that the "Group Messages" dashlet from the SecuritySuite plugin (paid version) was the culprit of that.

**Comment by ijdavie** [comment]
I will close this as the dashboard problems that are seen have been raised in #2370.
