### ISSUE TITLE
Case LogicHook Failed Case Updates

### ISSUE THREAD

**Issue by lpabcdefgh** [salesagility/SuiteCRM#2096]
#### Issue

After registering a Module LogicHook for Cases module, case update stopped working.  This happens in an clean install copy of both 7.7.4 and 7.7.1.
#### Expected Behavior

LogicHooks will execute the code in the appointed file, class, and method, without breaking case updates module. In other word, once logichook is registered for cases, case update should still work.  
#### Actual Behavior

After registering logichook via 'Custom->Extension->modules->Cases->Ext->LogicHooks->casefilter.php(tried other names as well, doesn't work)', and pointing to another file(has php open tag, entry point line, correct class name, correct method name and passing in variable) in this folder, 'Case Update' module stopped working.
In detail, after you type something in the case update box, click 'Save', it will show the message box, but nothing actually happens after that, case update not saved.
#### Possible Fix

I have checked the ajax call, seems to be passing alright, even though it is throwing an error but it won't affect.
#### Steps to Reproduce

1. Register the logichook via 'Custom->Extension->modules->Cases->Ext->LogicHooks->casefilter.php(tried other names as well, doesn't work)'
2. put these codes in
$hook_version = 1;
$hook_array = Array();
$hook_array['before_save'][] = Array(1, 'casesFilteringOnType', 'custom/Extension/modules/Cases/Ext/LogicHooksCode/casesFiltering.php', 'casesFilteringOnType', 'casesFilteringOnType'); 
3. Create file, name it accordingly.  Then put class name and method name accordingly.
4. Quick Rebuild System
5. Check Case update again, it stopped working
6. Checked suitecrm.log and sugarcrm.log, both not showing any warning or fatal error message.
7. Checked browser console, no error coming up

#### Context

We are trying to implement some logic linking and remove linking with Security Group, which cannot be implemented through workflow.  This is one of the core functionality for our CRM system.  

High Priority Please.
#### Your Environment

* SuiteCRM Version used: 7.7.4 at the moment
* Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.50, PHP 5.5.36
* Operating System and version (e.g Ubuntu 16.04): Centos 6.7

**Comment by ijdavie** [comment]
hi @lpabcdefgh, 
I haven't tested this but from what I can see with what steps you have added to reproduce you are clearing out the hooks array when you are adding your new hook. so from what I can see here no logichooks found in custom/modules/cases will fire because of this, you need to check and see if the hook_array is set before setting it like this. 
 
$hook_array = Array();

**Comment by lpabcdefgh** [comment]
@ijdavie Hi ijdavie,
I have actually done that.  The exact code ...
<?php
$hook_version = 1;
$hook_array = Array();
$hook_array['before_save'][] = Array(1, 'casesFilteringOnType', 'custom/Extension/modules/Cases/Ext/LogicHooksCode/casesFilteringOnType.php', 'casesFilteringOnType', 'casesFilteringOnType');

I have put and names the file, class and methods accordingly...

**Comment by ijdavie** [comment]
Hi @lpabcdefgh, 

That code is incorrect if that is what has been put in the Extensions Framework as this will clear out the custom/module/Cases/logichooks file. as you are emptying the array in the extensions framework which is loaded after. so you must check to see if the $hook_array exists as it could do and in this example it will exist and contain hooks for cases.

**Comment by lpabcdefgh** [comment]
Hi @ijdavie 
Thanks for the valuable information.  Didn't thought it will override the array in normal extension framework.
I have test it again, it's all good now.  Sorry for the false alarm.

Thanks,
Shaun
