### ISSUE TITLE
Unable to rename checkbox name in case_updates

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2097]
#### Issue
Unable to rename checkbox name in case_updates, this checkbox is named "Internal".

#### Expected Behavior
Rename it using language file

#### Actual Behavior
Unable to rename

#### Possible Fix
Add label insted of default text.
modules/AOP_Case_Updates/Case_Updates.php
linie 311
#### Steps to Reproduce
Go to module Cases and click on detailview of random record.

#### Context
low
#### Your Environment
* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): win10

**Comment by ijdavie** [comment]
Hi @tomi798, 
We see this issue, we will put a fix in for this, expected to use the same label as the field label in studio for the internal field. 
a pull request will be created for this change shortly. 
Thanks for raising.

**Comment by ijdavie** [comment]
duplicate issue of #1772
