### ISSUE TITLE
Gifs not loading in Emails module

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2103]
#### Issue

Gifs not loading in Emails module
#### Expected Behavior

They should load.
#### Actual Behavior

They didn't.
#### Steps to Reproduce

1.Go to Emails module
#### Context

low
#### Your Environment
- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 52.0.2743.116 m
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04): win10
  ![zjd](https://cloud.githubusercontent.com/assets/21075768/18167536/6493b5f8-7051-11e6-92e8-f4ee59702514.jpg)

**Comment by shogunpol** [comment]
@tomi798  , I tested this issue on recent version of SuiteCRM(7.7.4) and it will be labelled as a bug. 
Thanks for raise this issue.
