### ISSUE TITLE
Not Possible to Create Meeting on Dashboard My Calendar Dashlet

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2107]
#### Issue

When you first login to SuiteCRM and try to create meeting from My Calendar on homepage dashboard, it is not possible to create it. You can not select time interval from the calendar to have popup. In order to create it;
- Press the Edit pencil icon and without changing anything Press Save. 
- Screen refreshes and it becomes possible to create meeting from the calendar. 
#### Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (Chrome Version 52.0.2743.116 m):
- Environment name and version (MySQL, PHP 5.6):
- Operating System and version (Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
