### ISSUE TITLE
Adding Account Name to Opportunity Report in AOR

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#211]
If a user adds the Account Name for an Opportunity within AOR, no results are returned. If the user re-edits the report, the relationship has gone from Opportunities::Accounts Name to Opportunities::Opportunities Opportunity Name.

See forum topic: https://suitecrm.com/forum/bug-tracker/4601-reports-account-name

**Comment by sl4sher** [comment]
AOR_Report.php:684
`$query = $this->build_report_query_join($data['relationship'],$table_alias, $oldAlias, $field_module, 'relationship', $query, $new_field_module);`

$oldAlias is not set to anything. Which produces:

`LEFT JOIN accounts_opportunities [|accounts] ON [].id=[|accounts].opportunity_id AND [|accounts].deleted=0`

Needs
`$oldAlias = $table_alias;`
before 682.

Need the same thing in `build_report_query_where($query)` around 848 or parameters will fail in the same way.

Finally, the relate parameters aren't changeable in the detail view via popup unless the parameter area is wrapped in a `<form name="EditView">`.

**Comment by vladbar** [comment]
Hi Will, this https://github.com/salesagility/SuiteCRM/issues/211 has been fixed by Matt  on 19 Oct. 

Matt implemented a fixed proposed by sl4sher (described in the comment on this issue:  https://github.com/salesagility/SuiteCRM/issues/211). 

Could you please close it.
​I tested it and it works.
