### ISSUE TITLE
Hover over favorites item, shows module name, not label in 7.7.4

### ISSUE THREAD

**Issue by zebelcrm** [salesagility/SuiteCRM#2111]
When you hover over an item under favorites list on the left side pane, it shows the module name (e.g. opportunities), rather than the module label (which could've been changed to xyz).
#### Issue

When you hover over an item under favorites list on the left side pane, it shows the module name (e.g. opportunities), rather than the module label (which could've been changed to xyz).

This is a bug because the hover action should refer to the module label and not its name.
#### Expected Behavior

Hovering over a favorites item should display the module label.
#### Actual Behavior

Hovering shows module name.
#### Possible Fix

Change module name reference to the module label reference.
#### Steps to Reproduce

1.
2.
3.
4.
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7): MYSQL, and PHP7
- Operating System and version (e.g Ubuntu 16.04): Ubuntu

**Comment by shogunpol** [comment]
This issue was tested on recent version of SuiteCRM(7.7.4), and appear.
We will labeled it as a bug.
@zebelcrm  , thanks for raise this issue.

**Comment by Mac-Rae** [comment]
Confirmed in latest 7.10.x

**Comment by Kevconry** [comment]
Was able to replicate in 7.13.1
