### ISSUE TITLE
Text areas in Suite P - non-responsive

### ISSUE THREAD

**Issue by zebelcrm** [salesagility/SuiteCRM#2112]
Text areas are non-responsive in SuiteP.
#### Issue

When you have 2 fields on the same line and the one on the left is a text area, (the other being a simple date or text field), the field label for the field on the right overlays the text area. If you change window zoom, as the screen elements get smaller, the screen begins to look OK at 75% zoom. Also, if you RESIZE the window, all elements move except for the text area which does not resize.
#### Expected Behavior

Resize or move screen elements proportionally, especially when there are text areas involved.
#### Actual Behavior

Right now field labels overlay the text area. See attachment.
#### Steps to Reproduce

1.
2.
3.
4.
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
- Environment name and version (e.g. MySQL, PHP 7): php 7
- Operating System and version (e.g Ubuntu 16.04): Ubuntu
  ![overlaynarrowwindow2](https://cloud.githubusercontent.com/assets/20979933/18186921/8330108e-705a-11e6-91e8-0ed29ffd98c3.png)
  ![overlaynarrowwindow1](https://cloud.githubusercontent.com/assets/20979933/18186923/83393eca-705a-11e6-936a-2029abd7aea9.png)
  ![overlay75percentzoom](https://cloud.githubusercontent.com/assets/20979933/18186920/832fca8e-705a-11e6-938d-64f1cb15d9b9.png)
  ![overlay90percentzoom](https://cloud.githubusercontent.com/assets/20979933/18186919/832fc67e-705a-11e6-8f84-41837bf68ae9.png)
  ![overlay100percentzoom](https://cloud.githubusercontent.com/assets/20979933/18186922/83305fe4-705a-11e6-9285-2a7ea9726744.png)

**Comment by shogunpol** [comment]
This issue was tested on recent version of SuiteCRM(7.7.4), and appear.
We will labeled it as a bug.
@zebelcrm , thanks for raise this issue.

**Comment by zebelcrm** [comment]
Sorry, I'm not too familiar with github and bug fixes. When does "fix proposed" progress to the next phase in the bug fix cycle? And do I have to do anything as the person who opened the issue?

**Comment by shogunpol** [comment]
@zebelcrm , NO you dont have to do anything else,
"fix proposed" means, That someone has created a pull request which should fix this issue. it will be reviewed and if it does fix this issue it will be pulled in to the main project and packed with the next release. 
Of course you can use the changes on your instance straight away if you wish.
Thanks for your contribution.

**Comment by zebelcrm** [comment]
Thank you for the information. If I did want to implement the changes, what's the best way to do so? Download the file or cut and paste manually?

**Comment by samus-aran** [comment]
SHould be resolved
