### ISSUE TITLE
Mass update action on dropdown displays incorrectly

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#2113]
#### Issue

This is a minor bug, mass update function, is working ok, the problem is only visual.

Mass update action on dropdown displays incorrectly.

![selection-03-2016-09-01](https://cloud.githubusercontent.com/assets/6874136/18189129/3aedce9a-7075-11e6-8c8f-4dc147f37848.png)

#### Expected Behavior

Dropdown menu on mass update actions can be read with no problems

#### Actual Behavior

Dropdown menu overlaps with Recently Viewed menu

#### Possible Fix

CSS could be the problem, on class="subnav ddopen"

#### Steps to Reproduce

1. Go to accounts module (listview)
2. Go to checkbox left to disabled delete button and click it
3. Delete button is enabled now, click to the arrow on delete button
4. Dropdown menu generated cannot be readed

#### Context

I was trying to perform a mass update on accounts records

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
* Environment name and version:
  * mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
  * PHP Version 5.6.25-2+deb.sury.org~xenial+1
  * Apache/2.4.18 (Ubuntu)
* Operating System and version: 
  * Distributor ID: neon
  * Description:    KDE neon User Edition 5.7
  * Release:        16.04
  * Codename:       xenial

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.3) and it will be labelled as a bug. 
Thanks for raise this issue.

**Comment by cumanacr** [comment]
@shogunpol this is happening on SuiteCRM 7.7.4 too, regards

**Comment by shogunpol** [comment]
@cumanacr , thanks for this additional information.

**Comment by ijdavie** [comment]
@cumanacr, It appears there is a fix in the hotfix branch for this issue and will be in the next release. 
Thanks.

**Comment by cumanacr** [comment]
@ijdavie you're welcome, I'm glad helping a little bit
