### ISSUE TITLE
Suite P theme scheduler icon doesn't exist

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#2119]
There is no scheduler icon that could be displayed in the recently viewed bar.
It looks broken like this.
![schedulersicon](https://cloud.githubusercontent.com/assets/19668751/18203021/557f7f70-7114-11e6-84f1-90fcaac53cc4.png)

**Comment by shogunpol** [comment]
This issue was tested on recent version of SuiteCRM(7.7.4), and appear.
We will labeled it as a bug.
@vmijalkovic , thanks for raise this issue.
