### ISSUE TITLE
7.6.6: Salutation not saved

### ISSUE THREAD

**Issue by martin-huber** [salesagility/SuiteCRM#2120]
#### Issue

When creating a new contact or updating a contact in SuiteCRM 7.6.6 the salutation is not saved. 

#### Expected Behavior

salutation should be saved
#### Actual Behavior

is not saved
#### Steps to Reproduce

1. create new contact (or open existing one)
2. fill lastname and select salutation
3. save
4. re-open saved contact => salutation is empty

#### Context

* increased loglevel to debug. DB update command does not contain salutation.
** if only changing salutation no "UPDATE contacts" is performed at all
** if additionally changing another field, all the field values can be seen in the "UPDATE contacts" statement, but "`salutation`=NULL"
* html representation of salutation in EditView looks like:
```
<select name="salutation" id="salutation">
<option label="" value="" selected="selected"></option>
<option label="Mr." value="Mr.">Mr.</option>
<option label="Ms." value="Ms.">Ms.</option>
<option label="Mrs." value="Mrs.">Mrs.</option>
<option label="Dr." value="Dr.">Dr.</option>
<option label="Prof." value="Prof.">Prof.</option>
<option label="Frau" value="Frau">Frau</option>
<option label="Herr" value="Herr">Herr</option>
<option label="Madame" value="Madame">Madame</option>
<option label="Monsieur" value="Monsieur">Monsieur</option>
<option label="Signora" value="Signora">Signora</option>
<option label="Signore" value="Signore">Signore</option>
</select>
```

#### Your Environment

* SuiteCRM Version used: 7.6.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 52.0.2743.116, FireFox 48.0.2 ...
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1ubuntu4.19
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by mattlorimer** [comment]
cannot replicate you likely have the salutation field twice in editview

**Comment by martin-huber** [comment]
exactly this. Thanks!
