### ISSUE TITLE
SuiteP dashlets issues with icons + broken icons in dashlets after uprade from 7.6.x versions

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2124]
#### Issue

- The texts for Website + News Feed dashlet is missing in dashled window 
- The icons are missing (or are old)  in dahslet pop up window after upgrade
- Broken icons of existing dashlets after upgrade
#### Steps to Reproduce

1. Home page
2. Action menu button
3. Add Dashlet
4. Web Tab in Dashlet pop up window

![dashlet1](https://cloud.githubusercontent.com/assets/5773777/18207067/d1f09034-7129-11e6-811e-980cfcf4225e.png)
#### Context

When we upgraded from 7.6.x to 7.7.x , we see those broken icons for web dashlet / jotpad /custom modules icons 

![dashlet2](https://cloud.githubusercontent.com/assets/5773777/18207289/da8b5a0c-712a-11e6-952d-cf44abb4c9e7.png)
- i have not change icons of dashlets after upgrade

![dashlet3](https://cloud.githubusercontent.com/assets/5773777/18207290/df08d406-712a-11e6-957c-84d46889a23f.png)

![dashlet4](https://cloud.githubusercontent.com/assets/5773777/18207293/e41c9cde-712a-11e6-9e77-c0f65245bfd0.png)

![dashlet5](https://cloud.githubusercontent.com/assets/5773777/18207299/ea822666-712a-11e6-86cb-de393eec90b8.png)
#### Your Environment

- SuiteCRM Version used:
- Browser name and version Chrome Version 53.0.2704.63 (64-bit)
- Environment name and version MySQL 5.6, PHP 5.6:
- Operating System and version : Hosting -- Linux

**Comment by ijdavie** [comment]
@Mausino what version have you upgraded to ? 
Thanks.

**Comment by Mausino** [comment]
from 7.6.5 to 7.7.3 (in next few days i will upgrade to latest)

**Comment by ijdavie** [comment]
@Mausino,

If you can upgrade to 7.7.4 this should change most of the icons, this still leaves a couple which we are currently working on,

**Comment by Mausino** [comment]
@ijdavie i sure let you know the news when my programmer uprade on newiest version in next few days

**Comment by Mausino** [comment]
in Suite 7.7.5 still issue icons on dashlets + in Add dashlet window now everything ok :)

![suite775](https://cloud.githubusercontent.com/assets/5773777/19150348/9e00c4e4-8bc6-11e6-9136-23aa3058096e.png)

**Comment by horus68** [comment]
@shogunpol this can now be closed as solved!
SuiteCRM 7.7.8 + fixes with merged PR https://github.com/salesagility/SuiteCRM/pull/2500
