### ISSUE TITLE
Global Search Problem - Indexing broken at table document_revisions

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2129]
Perform Lucene Index (function::aodIndexUnindexed) stops when indexing table document_revisions

#### Issue

After upgrading to 7.7.4 I wanted to get fresh indexes for the global search. Steps taken:
filesystem: rm -r modules/AOD_Index/Index/*
mysql: truncate aod_indexevent;
mysql: truncate aod_index;
Schedule "Perform Lucene Index"

I have more than 30000 records stored. So,
   select count(*) from aod_indexevent;
should give me an equal number compared to my records. In my case it returned about 10000.
So, it seems there is something wrong (and global seach did not find matches in notes).
Contacts will be seached.

Some thoughts what happens:
aodIndexUnindexed calls performLuceneIndexing. In the foreach-loop all tables should be picked
and indexed:
  am_projecttemplates
  am_tasktemplates
  aobh_businesshours
  ...
  cases
  contacts
  document_revisions
And here it stops and returns to aodIndexUnindexed which then thinks it is finished. I currently have no clue why it stops.

As a workaround I did this (second line after "foreach"):
  if (!$bean || !method_exists($bean, "getTableName") || !$bean->getTableName() || ($bean->getTableName() == 'document_revisions')) {
It just skips the document_revisions table and walks through all tables (as expected).

#### Expected Behavior

Indexing (for global search) should go through all tables.

#### Actual Behavior

Indexing (for global search) stops when document_revisions are being indexed.

#### Steps to Reproduce

See above.

#### Your Environment

* FF 48.0.2
* php 5.6, mysql 5.6
* FreeBSD 10.2
* SuiteCRM 7.7.4

**Comment by shogunpol** [comment]
@adminibt , did you have any errors on apachie/php logs. 
With this amount of record it is processing it could be timing out.
So it is could be worth checking.

**Comment by adminibt** [comment]
@shogunpol , I don't think this a timing problem. Nothing is logged in apache. Below you will find a part of the output of suitecrm.log (debug logging).

Please note that this is version 7.6.6 - so the problem also exists here.

It starts with the rest of indexing contacts. Please search for "Suche 2: document_revisions". This is where the table document_revisions will be indexed. I just added
$GLOBALS['log']->fatal('Suche 2: '.$bean->getTableName());
in modules/Schedulers/_AddJobsHere.php (line 703)
I have 18 ducument, so it should walks over every one.

If you need more logs please let me know. 

....
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00030207633972168
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Hook called: Contacts::after_retrieve
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] get_full_list:  order_by = '' and where = 'aod_indexevent.record_id = '942cb837-8570-5fd0-04b8-570bfd5d096e' AND aod_indexevent.record_module = 'Contacts''
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (modified_user_link).
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (created_by_link).
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (assigned_user_link).
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] process_full_list_query: query is  SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = '942cb837-8570-5fd0-04b8-570bfd5d096e' AND aod_indexevent.record_module = 'Contacts') AND aod_indexevent.deleted=0
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query: SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = '942cb837-8570-5fd0-04b8-570bfd5d096e' AND aod_indexevent.record_module = 'Contacts') AND aod_indexevent.deleted=0
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00030112266540527
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] process_full_list_query: result is mysqli_result Object
(
    [current_field] => 0
    [field_count] => 22
    [lengths] =>
    [num_rows] => 0
    [type] => 0
)

Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Hook called: AOD_IndexEvent::before_save
Tue Sep  6 15:48:13 2016 [11725][1][DEPRECATED] SugarBean.php: preprocess_fields_on_save() is deprecated
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query:INSERT INTO aod_indexevent (id,name,date_entered,date_modified,modified_user_id,created_by,deleted,success,record_id,record_module)
                                        VALUES ('60b24f3a-3e9b-6fe8-cb9d-57cec9a12747','Mr.  Miedaner','2016-09-06 13:48:13','2016-09-06 13:48:13','1','1',0,1,'942cb837-8570-5fd0-04b8-570bfd5d096e','Contacts')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.0010559558868408
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SecuritySuite: Get SecuritySuite Enabled Modules: SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query:SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00043988227844238
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SecuritySuite: Get SecuritySuite Enabled Modules: SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query:SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00040793418884277
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] SecuritySuite: Get SecuritySuite Enabled Modules: SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query:SELECT lhs_module, rhs_module FROM relationships WHERE deleted=0 AND (lhs_module = 'SecurityGroups' OR rhs_module='SecurityGroups')
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00043797492980957
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Hook called: AOD_IndexEvent::after_save
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Creating new instance of hook class AOD_LogicHooks without parameters
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Creating new instance of hook class AssignGroups without parameters
Tue Sep  6 15:48:13 2016 [11725][1][DEBUG] Creating new instance of hook class AOW_WorkFlow without parameters
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query:SELECT id FROM aow_workflow WHERE aow_workflow.flow_module = 'AOD_IndexEvent' AND aow_workflow.status = 'Active' AND (aow_workflow.run_when = 'Always' OR aow_workflow.run_when = 'On_Save' OR aow_workflow.run_when = 'Create') AND aow_workflow.deleted = 0
Tue Sep  6 15:48:13 2016 [11725][1][INFO] Query Execution Time:0.00017213821411133
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Hook called: AOD_Index::before_save
Tue Sep  6 15:48:25 2016 [11725][1][DEPRECATED] SugarBean.php: preprocess_fields_on_save() is deprecated
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query:UPDATE aod_index
                                        SET `name`='Index',`date_modified`='2016-09-06 13:46:00',`modified_user_id`='1',`created_by`='1',`description`=NULL,`assigned_user_id`='',`last_optimised`='2016-09-06 13:46:00',`location`='modules/AOD_Index/Index/Index'
                                         WHERE  aod_index.id = '1' AND deleted=0
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.0011458396911621
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Hook called: AOD_Index::after_save
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Creating new instance of hook class AOD_LogicHooks without parameters
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Creating new instance of hook class AssignGroups without parameters
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Creating new instance of hook class AOW_WorkFlow without parameters
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query:SELECT id FROM aow_workflow WHERE aow_workflow.flow_module = 'AOD_Index' AND aow_workflow.status = 'Active' AND (aow_workflow.run_when = 'Always' OR aow_workflow.run_when = 'On_Save' OR aow_workflow.run_when = 'Create') AND aow_workflow.deleted = 0
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.00021100044250488
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Auditing: createAuditRecord was not called, audit record will not be created.
Tue Sep  6 15:48:25 2016 [11725][1][FATAL] Suche 2: document_revisions
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Limit Query:SELECT b.id FROM document_revisions b LEFT JOIN aod_indexevent ie ON (ie.record_id = b.id AND ie.record_module = 'DocumentRevisions') WHERE b.deleted = 0 AND (ie.id IS NULL OR ie.date_modified < b.date_modified) ORDER BY b.date_modified ASC Start: 0 count: 500
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query:SELECT b.id FROM document_revisions b LEFT JOIN aod_indexevent ie ON (ie.record_id = b.id AND ie.record_module = 'DocumentRevisions') WHERE b.deleted = 0 AND (ie.id IS NULL OR ie.date_modified < b.date_modified) ORDER BY b.date_modified ASC LIMIT 0,500
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.00053286552429199
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Hook called: DocumentRevisions::before_retrieve
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Retrieve DocumentRevision : SELECT document_revisions.* FROM document_revisions  WHERE document_revisions.id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND document_revisions.deleted=0
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Limit Query:SELECT document_revisions.* FROM document_revisions  WHERE document_revisions.id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND document_revisions.deleted=0 Start: 0 count: 1
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query:SELECT document_revisions.* FROM document_revisions  WHERE document_revisions.id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND document_revisions.deleted=0 LIMIT 0,1
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.00018405914306641
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query:SELECT document_name, revision, document_revision_id FROM documents, document_revisions where documents.id = 'aa59e954-d7af-eef3-c682-578729f7a91e' AND document_revisions.id = documents.document_revision_id
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.00014686584472656
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Hook called: DocumentRevisions::after_retrieve
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] get_full_list:  order_by = '' and where = 'aod_indexevent.record_id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND aod_indexevent.record_module = 'DocumentRevisions''
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (modified_user_link).
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (created_by_link).
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] SugarBean[AOD_IndexEvent].load_relationships, Loading relationship (assigned_user_link).
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] process_full_list_query: query is  SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND aod_indexevent.record_module = 'DocumentRevisions') AND aod_indexevent.deleted=0
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query: SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = 'abf03d7e-0a9d-dd63-7639-5787296ceda3' AND aod_indexevent.record_module = 'DocumentRevisions') AND aod_indexevent.deleted=0
Tue Sep  6 15:48:25 2016 [11725][1][INFO] Query Execution Time:0.00029301643371582
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] process_full_list_query: result is mysqli_result Object
(
    [current_field] => 0
    [field_count] => 22
    [lengths] =>
    [num_rows] => 0
    [type] => 0
)

Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Hook called: ::server_round_trip
Tue Sep  6 15:48:25 2016 [11725][1][DEBUG] Calling MySQLi::disconnect()
Tue Sep  6 15:48:25 2016 [11725][1][FATAL] Job 3e7568a8-66ad-48ab-caac-57cec8dceccf (Perform Lucene Index) failed in CRON run

**Comment by adminibt** [comment]
@shogunpol , after digging arround I found this:

- Clean install 7.7.4
- Create a docx file with Msword Office 2010
- Create a document in SuiteCRM and upload the docx file with IE 11

IE "crashes" with this:

![d1](https://cloud.githubusercontent.com/assets/19223035/18282249/97e75442-7460-11e6-8e92-5d1428875371.png)


Translation: Website could no be disaplayed (http 500 - code). And php will print this (important?):
[Tue Sep 06 17:55:43.945680 2016] [:error] [pid 56589] [client 192.168.1.30:51258] PHP Fatal error:  Class 'DOMDocument' not found in /usr/local/www/apache24/data/modules/AOD_Index/Lib/Zend/Search/Lucene/Document/Docx.php on line 84, referer: http://192.168.1.155/index.php?module
=Documents&action=EditView&return_module=Documents&return_action=DetailView


On the documents page the entry will not be displayed. And with this entry the indexing will stop at the table document_revisions.
In the table I found this:
| d9348b21-6049-fc23-ec66-57cee6834f7a | Document Created | d8c555b4-3d57-da69-2253-57cee6691bae |        | Sugar    |         | 2016-09-06 15:55:43 | 1          | Diamant_Installation_Version_3.6.00-12.docx    | docx     | application/vnd.openxmlformats-officedocument.wordprocessingml.document | 1        |       0 | 2016-09-06 15:55:43 |
After deleting the record indexing will work again.

If I upload the docx with firefox (I don't have office 2010 installed) there is no problem. The mime-type will be "application/octet-stream" - and not "application/vnd.openxmlformats-officedocument.wordprocessingml.document" like above.

You might look at the mime-type thing. Also note that IE 11 and Office 2010 will do this with an xlsx file:
| b8b5a699-768a-ef36-2bb0-57cee6bfc650 | Document Created | b860be3a-17ea-1a92-8699-57cee69cd116 |        | Sugar    |         | 2016-09-06 15:53:42 | 1          | DeploymentSysteme.xlsx                         | xlsx     | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet       | 1        |       0 | 2016-09-06 15:53:42 |
Strange mime-type, or? But here IE will not crash.

So, is this whole mime-type stuff working correctly?

**Comment by ijdavie** [comment]
@adminibt This looks like the PHP version that is running on the server is missing DomDocument, can you check this ? 
http://php.net/manual/en/class.domdocument.php

Will come back to you on the mime-type.

**Comment by adminibt** [comment]
@ijdavie Yes, that was missing. Now everything is working.

Don't know if this is important. IE seems to use "application/vnd.openxmlformats-officedocument.wordprocessingml.document" only if Office is installed.
| 234fd8a9-9927-ea7c-cdda-57cff703eeba | Document Created | 22f4b166-f1c8-5648-81eb-57cff7f2e8f7 |        | Sugar    |         | 2016-09-07 11:18:16 | 1          | Diamant_Installation_Version_3.6.00-12.docx    | docx     | application/vnd.openxmlformats-officedocument.wordprocessingml.document | 1        |       0 | 2016-09-07 11:18:16 |
Same thing applies to xlsx files.

One other thing: Maybe you should check for the php DOM extension (and also php fileinfo extension) in your installer.

Thanks, Andreas

**Comment by Lehnerr** [comment]
I can see the same problem in my environment.
I can see it stuck on an pdf document.

Fri Sep  9 09:52:16 2016 [17336][1][DEBUG] process_full_list_query: query is  SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = 'f08b2e35-3849-c621-697b-511102599af9' AND aod_indexevent.record_module = 'DocumentRevisions') AND aod_indexevent.deleted=0
Fri Sep  9 09:52:16 2016 [17336][1][INFO] Query: SELECT  aod_indexevent.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM aod_indexevent   LEFT JOIN  users jt0 ON aod_indexevent.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON aod_indexevent.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON aod_indexevent.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (aod_indexevent.record_id = 'f08b2e35-3849-c621-697b-511102599af9' AND aod_indexevent.record_module = 'DocumentRevisions') AND aod_indexevent.deleted=0
Fri Sep  9 09:52:16 2016 [17336][1][INFO] Query Execution Time:0.00040388107299805
Fri Sep  9 09:52:16 2016 [17336][1][DEBUG] process_full_list_query: result is mysqli_result Object
(
    [current_field] => 0
    [field_count] => 22
    [lengths] => 
    [num_rows] => 0
    [type] => 0
)



in php-Error-log I can see following:
[09-Sep-2016 09:52:16 Europe/Berlin] PHP Notice:  iconv(): Detected an illegal character in input string in /var/www/sip                                                                                wise/modules/AOD_Index/Lib/Zend/Search/Lucene/Analysis/Analyzer/Common/Utf8Num.php on line 77


The name of the document is "VIES ERIKA 05.02.2013.pdf"


I removed the blanks in the name and it get processed.

Now I see it looping on allerts:
Fri Sep  9 10:17:36 2016 [17167][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0
Fri Sep  9 10:17:36 2016 [17167][1][INFO] Query Execution Time:0.00015497207641602
Fri Sep  9 10:17:36 2016 [17167][1][DEBUG] process_full_list_query: result is mysqli_result Object
(
    [current_field] => 0
    [field_count] => 22
    [lengths] =>
    [num_rows] => 0
    [type] => 0
)



My alerts-table is empty !!!!

BTW: DOM extension is enabled in my environment
pls help

**Comment by ijdavie** [comment]
@Lehnerr, This sounds like a different issue and I would advice raising this as a separate issue, so it can be investigated outwith this issue. Thanks.

**Comment by valcosoftj** [comment]
this aor index should be replaced by a normal SQL index and search if you ask me, why use sql and then not use it
