### ISSUE TITLE
Enabling Subpanel Tabs in SuiteP theme throws js error in detail view

### ISSUE THREAD

**Issue by dhavaldarji** [salesagility/SuiteCRM#2131]
![subpanel-group-issue](https://cloud.githubusercontent.com/assets/1948114/18247702/9db7f55e-7391-11e6-80c7-8268372588e8.png)
#### Issue

When you enable "Subpanel Tabs" from user profile section in new SuiteP theme, it throws error in Detail View, regarding using "match" (as seen in the attached screenshot) on an undefined element, and this happens on page load, see attached screenshot, if you disable "Subpanel Tabs" it won't throw the error. have tested on fresh install of 7.5 upgraded to 7.7.4.
#### Expected Behavior

Not sure but it should set active tab selected on page load when no subpanel tab is selected.
#### Actual Behavior

On page load the code tries to set active tab but fails with error "VM11899:30 Uncaught TypeError: Cannot read property 'match' of undefined" on line 30 
<code>
var tab = parseInt($(this).find('a').first().attr('id').match(/^tab(.)*$/)[1]);
</code>
#### Possible Fix

Type checking if the element is not undefined before calling match?
#### Steps to Reproduce

1. Enable Subpanel tabs from user profile
2. Navigate to any, say contact detail view
3. Open the chrome developer tool, it will show the error.
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116 (64-bit)
- Environment name and version (e.g. MySQL, PHP 7): PHP 5.5, 5.6
- Operating System and version (e.g Ubuntu 16.04): Centos 7 & Ubuntu 16.04

**Comment by dhavaldarji** [comment]
Also,
looking at the dom, for ex. 
<code>
\<li id="All_sp_tab" class="">
 \<a class="" href="javascript:SUGAR.subpanelUtils.loadSubpanelGroup('All');">All</a>
\</li>
</code>

the code
<code>
var tab = parseInt($(this).find('a').first().attr('id').match(/^tab(.)*$/)[1]); 
</code>
tries to find the "Id" of the "a" tag, which is not there!! this is causing the same issue with the upper block which is called on click of the "li" item.

So, may be the solution would be to give "Id" to the "a" tag or call the match on the "li" tag!!

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
The functionality of the application seems to work fine but it is Java Script issue.
We labeled this issue as a bug.
@dhavaldarji   , thanks for raise this issue.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.8), and not appear.
@dhavaldarji , can you confirm is not an isuue any more and close issue.

**Comment by dhavaldarji** [comment]
Confirmed... it's fixed 👍  Thanks
