### ISSUE TITLE
Emails related to Accounts workflow problem

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#2132]
For some reason I am unable to create working workflow. After consulting on the forum I decided to log this problem here because it might be a bug.
You will find what I have tried to accomplish if you take a look here: 
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/11029-custome-date-field-update-when-email-sent#37500

So basically it looks like I either don't understand how to create appropriate logic to trigger a change in the related field or some link is missing on development side.

Please take a look.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
We labeled it as a bug.
@animaleyeah , thanks for raise this issue.

**Comment by adriangibanelbtactic** [comment]
I'm not sure I reported this bug before but I'm pretty confident the problem lies in the condition:
"Not equals to" "Some empty string".

It should trigger when the field is null in addition to when the field is an empty string and it's actually only triggered when the field is an empty string.

**Comment by Mac-Rae** [comment]
This appears to be an issue with the way the workflow is configured.

If you are still interested in creating this functionality please message me back and I would be happy to assist :)
