### ISSUE TITLE
A: Update button css is missing + #1930 for 32 bit version

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2142]
#### Issue

A. Update button is looking same as was in SuiteR theme (i think, that css is missing for SuiteP)
B: #1930 but now on 32bit version of chrome :(

![reports](https://cloud.githubusercontent.com/assets/5773777/18270909/b46e6000-742f-11e6-977c-46bb77f0bada.png)

#### Your Environment

* SuiteCRM Version used: 7.7.3
* Browser name and version : Chrome 53.0.2785.89 m
* Environment name and version: MySQL 5.6, PHP 5.6
* Operating System and version: Linux Hosting

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
We labeled it as a bug.
@animaleyeah , thanks for raise this issue.

**Comment by Mausino** [comment]
@shogunpol i don't see any label here :)

**Comment by shogunpol** [comment]
@Mausino  is in red colour :)

**Comment by zer0890** [comment]
Hi, when you will fix it ?
