### ISSUE TITLE
SuiteP - Report PDF file - names of columns are missing

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2144]
#### Issue

Reports for SuiteR are much nicer and have the names of culumns in PDF Report file

![reports](https://cloud.githubusercontent.com/assets/5773777/18271324/c7e656c2-7431-11e6-8f2a-04e773b5099a.png)

Look the diffrence between the SuiteP and SuiteR theme
#### Your Environment

- SuiteCRM Version used: 7.7.3
- Browser name and version : Chrome 53.xx m
- Environment name and version: MySQL 5.6, PHP 5.6
- Operating System and version: Linux - Hosting

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
We labeled it as a bug.
@animaleyeah , thanks for raise this issue.

**Comment by liveincan** [comment]
I am using Version 7.7.5 and having the same issue. Any idea when this will be addressed?
