### ISSUE TITLE
URGENT !!! - Calls - RELATE TO field record (relationship) is missig after inline edit of Start date&time

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2145]
#### Issue

If you inline edit the Start date & time in calls, the relationship for RELATE TO disapear :( I tested and record it on official demo site of SuiteCRM 7.7.4 http://screencast.com/t/tsMWeDs7pE4C

BEFORE inline edit

![before](https://cloud.githubusercontent.com/assets/5773777/18272330/8b1d6ca2-7437-11e6-9861-fa603e75416e.png)

AFTER inline edit

![after](https://cloud.githubusercontent.com/assets/5773777/18272336/908225a2-7437-11e6-919b-d07b4f0a7668.png)
#### Expected Behavior

After inline edit of Start date&time changed only this field, no others !!!
#### Actual Behavior

See the videoscreen http://screencast.com/t/tsMWeDs7pE4C 
#### Steps to Reproduce

1. Open the call record in Detailview
2. Inline edit the field Start date&time
3. Save / Enter date&time
4. Refresh page
#### Your Environment

- SuiteCRM Version used:
- Browser name and version: Chrome 53.x m 
- Environment name and version: MySQL 5.6, PHP 5.6
- Operating System and version: Linux - Hosting

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and also in testing environment on:
http://demo.suiteondemand.com/ and i been unable to replicate it.
Is there any other information you can give to us to replicate the issue?
@animaleyeah , thanks for raise this issue.

**Comment by Mausino** [comment]
@shogunpol  http://screencast.com/t/aPWoQjj7  i tested it on official demo page in chrome inkoginto mode, edge, mozila and on all i have same results, i have win 10 basic 64bit version

**Comment by shogunpol** [comment]
@Mausino , now i see what the issue is,
I label it as a bug.
