### ISSUE TITLE
Images in PDFs not showing

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2153]
#### Issue

PDF images showing up in templates are not created when PDF is generated.
#### Expected Behavior

Create PDF template with a local image (located in custom/themes/default/images/).
Create PDF through invoice/quotes etc.
PDF created with images embedded.
#### Actual Behavior

PDF created with image placeholder (the square with the cross).
#### Other Testing Steps

I also tried linking to external images, hosted on a different platform - same error.
Checked all permissions and all are fine (and not changed since update).

Tested in Demo and that seems to work.
#### Context

This is directly effecting our ability to invoice our clients.
#### Your Environment
- SuiteCRM Version used 7.7.4 (was working in 6.7.x).
- All browsers tested (Chrome, Firefox, Internet Explorer, Edge).
- Environment name and version: MySQL, PHP 7.
- Windows 10 & 7 pro tested.

**Comment by shogunpol** [comment]
@SpudR  Linked directly to a image/file in the CRM e.g custom/themes/default is not recommended and should be prevented using the .htaccess file.
You would need to upload the file to say a note and use the url from the note record to link to the template. all files should be generates from a entrypoint rather than direct access. assuming that the CRM was setup using the install wizard your instance will contain the htaccess file which could be the reason why it is not working for you. 

The issue been tested on recent version of SuiteCRM(7.7.4), and it not appear.
Thanks for raise this issue.

**Comment by SpudR** [comment]
Thanks for the update - I'll have a test and update :)

**Comment by SpudR** [comment]
Changed the format of the image from PNG to JPG and the image shows in all locations.
I guess there's something screwy in the code about PDFs.

**Comment by SpudR** [comment]
Possibly related - creating the templates as 'Accounts' doesn't show the headers in the PDFs (though they appear in the preview).
Can someone please verify and let me know if this should be a separate issue...

**Comment by sgaved** [comment]
@SpudR This is working for me locally. This issue might be caused by not having the GD php library installed. Can you confirm whether it is?

**Comment by chris001** [comment]
@sgaved 
This is something the application can and should check for, by itself, with code.
I suggest adding the following code to check whether or not `gd` is installed.
If not installed, notify the user and notify the admin that `gd` is a system requirement for proper functioning of the parts of the app which process images, and that the app has attempted to install gd.  Web server may need to be restarted or reloaded for the newly installed extension to take effect.

```function checkGD()
{
  if (extension_exists('gd'))
  {
  /* The gd extension is installed. */
    return true;
  }
  else
  {
  /* gd is not installed.   */
  return false;
  }
}

function installGD()
{
  /*Try to install gd with linux commands.   */
  /* install gd for rpm and deb based distributions */
  system("yum -y install gd php-gd");
  system("apt-get -y install gd php-gd pgp5-gd php7.0-gd");
}
function notifyGDMissing()
{
  /* Alert the user, missing GD extension, contact your system admin. */
  /* Send notification to admin about missing GD extension */
}

if (!checkGD())
{
  installGD();
  notifyGDMissing();
}
```

**Comment by SpudR** [comment]
Hi guys
It worked fine pre the 7.7.4 update - here's the phpinfo(); output...
GD
---------------------------------
GD Support	enabled
GD headers Version	2.1.1
GD library Version	2.1.1
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.3.11
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	6b
PNG Support	enabled
libPNG Version	1.2.49
WBMP Support	enabled
XPM Support	enabled
libXpm Version	30411
XBM Support	enabled
WebP Support	enabled`

**Comment by SpudR** [comment]
7.7.8 update applied
This is still a problem - JPGs work PNGs dont

**Comment by ijdavie** [comment]
@SpudR can you supply more information with what you are seeing so someone can investigate this ?

**Comment by SpudR** [comment]
Simply create an invoice PDF template - insert a PNG image
Generate the invoice and it will only show the image placeholder
Insert a JPG image and generate again and the image shows.
In both these cases the images are stored in the same place in the file system so it is not a permissions issue.
All in the above detail :)

**Comment by shogunpol** [comment]
@SpudR , did you try more than one PNG files? like different size and so on.
And did you try on fresh installation, or did update?

**Comment by SpudR** [comment]
Yes - there is something else going on too - it's creating copies of the PDF templates if I change the PG to a PDF and save it.
I end up with 2 templates: 
One with a PNG that doesn't work
One with the JPG that does
?????????????????????????????
