### ISSUE TITLE
Click on Calendar Event  and  goes Edit Activity not View Activity 

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#2158]
#### Issue

Browse Mode: When we click on any event/call on calendar tab, we see it that open in Edit Mode whereas we want it to open in browse mode. In edit mode manager can not select the user and make the Calendar unusable 
#### Expected Behavior

Click on activity and go to Browse mode
#### Actual Behavior

Click on activity and go to Edit Mode
#### Steps to Reproduce

1. Click on Cal "Shared Month"
2. Click on Activity
3. Edit Mode comes up
   4.
#### Context

 In edit mode manager can not select the user and make the Calendar unusable 

High
#### Your Environment

- SuiteCRM Version used:
  Version 7.7.4
  Sugar Version 6.5.24 (Build 509)
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
  Chrome Version 
  Version 52.0.2743.116 m
- Environment name and version (e.g. MySQL, PHP 7):
  MySQL PHP6.5
- Operating System and version (e.g Ubuntu 16.04):
  GNU/Linux

**Comment by murdal** [comment]
Closing this issue as the User can both change the assigned to User and invite Targets/Leads/Contacts from the edit view of a Meeting/Call. DetailView can also be selected via hovering over the calendar item and clicking the eye icon.
