### ISSUE TITLE
Assignment Notification Repetitive/Arbitrary due to Project.php code

### ISSUE THREAD

**Issue by sieberta** [salesagility/SuiteCRM#2164]
#### Issue
It is possible to get multiple notifications of a project assignment to a user, even if the assigned_user_id did not change.

#### Expected Behavior
You would only get an assignment notification email from a project if it isn't assigned to yourself and if it is either a new project or the assignment changes.

#### Actual Behavior
You get multiple assignment notifications, even if you are assigning a project to yourself, or if the assignment has not changed.

#### Possible Fix
This statement in function save($check_notify = FALSE) evaluates to "True" when it should not... particularly when save() is called from a logic hook, or workflow.  In particular the final option: `!isset($_POST['user_invitees'])` always evaluates as "True" in these circumstances.

`		if( (isset($_POST['isSaveFromDetailView']) && $_POST['isSaveFromDetailView'] == 'true') ||
			(isset($_POST['is_ajax_call']) && !empty($_POST['is_ajax_call']) && !empty($focus->id) ||
			(isset($_POST['return_action']) && $_POST['return_action'] == 'SubPanelViewer') && !empty($focus->id))||
			 !isset($_POST['user_invitees']) // we need to check that user_invitees exists before processing, it is ok to be empty
		)`

When the above if statement resolves to true the following is called: `parent::save(true) ; //$focus->save(true);` <- Note is is forced to `save(true)`, not `save($check_notify)` as it was called.

That causes the following if statement to evaluate true from within SugarBean.php function _sendNotifications($check_notify):
`        if ($check_notify || (isset($this->notify_inworkflow) && $this->notify_inworkflow == true) // cn: bug 5795 - no invites sent to Contacts, and also bug 25995, in workflow, it will set the notify_on_save=true.
            && !$this->isOwner($this->created_by)
        )`

Which causes the system to see this as a user assignment change and send notifications ambiguously.

As an added note, this next block of code seems like it would never run, because if $_POST['user_invitees'] isset, then the first condition evaluates as true and the else condition to process those invitees would never run:
`
}else{
			if(!empty($_POST['user_invitees'])) {
			   $userInvitees = explode(',', trim($_POST['user_invitees'], ','));
			} else {
			   $userInvitees = array();
			}		
			if(!empty($_POST['contact_invitees'])) {
			   $contactInvitees = explode(',', trim($_POST['contact_invitees'], ','));
			} else {
			   $contactInvitees = array();
			}`

#### Steps to Reproduce
1. Turn on notifications in admin and in user profile.
2. Create a logic hook that calls $bean->save(false) for a project
3. Cause that logic hook to fire
4. See the multiple notifications

#### Context
My users are receiving multiple ambiguous notifications.  I don't know the consequences of changing this if statement to stop receiving multiple ambiguous notifications.  For my organization this is a high priority bug.

#### Environment
* SuiteCRM Version used: 7.7.3

**Comment by sieberta** [comment]
Removing `|| !isset($_POST['user_invitees']` seems to fox the problem, not sure what else that might be breaking.  Obviously isn't upgrade safe.

**Comment by tomi798** [comment]
Have the same problem and did the same.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
We are label this issue as a Bug.
Thanks for raise this issue.
