### ISSUE TITLE
Calls - Reminder shows blank field

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2165]
#### Issue

I tested it on official demo page of SuiteCRM version7.7.4

On default shows the reminder blank field, but if you edit the record of call, you see that there are checked checkboxes + times + invitees. After when you add new invitee, you see it as was designed.

![reminder](https://cloud.githubusercontent.com/assets/5773777/18338724/4e230194-759b-11e6-9a63-707e35b7a864.png)

![reminder2](https://cloud.githubusercontent.com/assets/5773777/18338726/52cc50d8-759b-11e6-817b-1661552dfc47.png)

![reminder3](https://cloud.githubusercontent.com/assets/5773777/18338733/57b086e6-759b-11e6-9ca1-3dc7d68a13ae.png)
#### Your Environment

- SuiteCRM Version used:
- Browser name and version: Chrome 53.x m
- Environment name and version : Official demo of SuiteCRM

**Comment by shogunpol** [comment]
The issue was tested on recent version of SuiteCRM(7.7.4), and also on official demo environment. 
For the purpose of the tests it was used Windows OS and Linux-Ubuntu OS. 
I used various web browsers depence on OS (IE, Firefox, Chrome, Chromium).
For all above environments i been not able replicate the issue. 
The Remainders facility need to be set up before it appears on the detail view for calls.
@Mausino ,Thanks for raise this issue.

**Comment by Mausino** [comment]
@shogunpol i think is my issue... i think it is issue of imported (demo records) 

Here is my videoscreen ... http://screencast.com/t/mAPvmdPl

But here is other issue with duration field... if i edit it... it shows me 0 but in editview of record is also the text field for nunber + dropdown and in inline edit only text field for number (i don't know if better report as new bug)

**Comment by shogunpol** [comment]
It appears on demo data.,
We will label it as a bug.
@Mausino ,Thanks for your contribution.

**Comment by shogunpol** [comment]
@Mausino , mentioned commit is already merged on recent version of suiteCRM(7.7.8), and issue not appear, this issue will be closed, however if you still can replicate issue, it will be reopened.

**Comment by Mausino** [comment]
Hi, i confim, that the issue doesn't appear anymore... @shogunpol thanks
