### ISSUE TITLE
Grouping checkboxes in the reports are not working in version 7.7.4

### ISSUE THREAD

**Issue by saleembdr** [salesagility/SuiteCRM#2166]
The grouping checkboxes are not working in the reports module. The problem was previously encountered in the issue with the URL https://github.com/salesagility/SuiteCRM/issues/1583.

#### Issue 
When checking the grouping checkboxes and selecting an aggregate result on other fields the result of the report is empty.

#### Expected Behavior
The report should show a list of records with the result of the aggregate fields.

#### Actual Behavior
The report is showing an empty result.

#### Steps to Reproduce

1. Go to the reports section in the activities menu
2. Create a new report
3. Select the 'Meetings' module
4. Add the 'Start Date', 'End Date' and 'Description' fields to the report
5. Use the group checkbox for the 'Start Date' and 'End Date' fields
6. Use the 'Count' option in the function dropdown of the 'Description' Field

![image](https://cloud.githubusercontent.com/assets/10287173/18806938/e7a45052-8243-11e6-8369-79ffd01187ee.png)

7. Save the report

![image](https://cloud.githubusercontent.com/assets/10287173/18806935/d99fefa2-8243-11e6-87be-8a1e04ee797e.png)

#### Context
I was trying to upgrade to version 7.7.4 from 7.6.3. I have previously applied the fix for issue 1583 manually and the grouping checkboxes were working correctly.

#### Your Environment
SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 7 on IIS.

**Comment by Mausino** [comment]
#1583 I have same issue

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear,
Clearly it causing use of MSSQL.
We will label this issue as a bug.
@Mausino , thanks for raise this issue.

**Comment by bmwtourer** [comment]
I confirm that we can not group either as "main group" or simple one.
running SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 5.6 on IIS.

**Comment by hamedcrm** [comment]
I'm experiencing the grouping issue as well but I'm using MariaDB with PHP5

**Comment by mattlorimer** [comment]
are you still experiencing these issue in 7.7.5?

**Comment by bmwtourer** [comment]
@mattlorimer I deployed in my test environment, and ...
 Grouping works, we need to indicate the grouping field(s) and then we can add the main group
**  but it appears to induce another problem, if you group you kill the link feature, i.e. you can not click on the account to show detail view of the account,   removing any grouping will permit the click to view record...**

**Comment by JiheneElHeni** [comment]
@mattlorimer i tried your solution, but i get a graph not properly done (you can see what i've got in the picture attached)
