### ISSUE TITLE
Inline edit issue if you click on pencil icon

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2172]
#### Issue

If you click on pencil, many times i recieved the warnig that i am not in editing area

For more info look on videoscreen http://screencast.com/t/fTqESJYPK

![warning](https://cloud.githubusercontent.com/assets/5773777/18347478/fdc97b8a-75c5-11e6-9dd3-1979324017d2.png)

This issue exist only in 7.7x version,  in 7.6.x and lower i had no problem with it
#### Expected Behavior

If i click on pencil i will immediately edit the record.
#### Actual Behavior

I must exactly clik on record, problem apear if the record is link... or on are between record and pencil icon
#### Steps to Reproduce

1. Listview/Detailview
2. Click on pencil icon on any field
#### Your Environment

- SuiteCRM Version used: Official demo - 7.7.4
- Browser name and version : Chrome 53.x m version
- Environment name and version: PHP 5.6, MySQL 5.6
- Operating System and version: Hosting - Linux

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear,
We will label this issue as a bug.
@Mausino  , thanks for raise this issue.
