### ISSUE TITLE
No gif and shifted text after saving task in gants view

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2175]
#### Issue

No gif and shifted text after saving task in gants view. Tested on your demo suite and my suite 7.7.4
![gant](https://cloud.githubusercontent.com/assets/21075768/18381065/a1462ef2-767a-11e6-8c8f-dcffd10024bc.jpg)
#### Steps to Reproduce
1. Open random Project
2. Change to gantt view
3. Add or edit task and save
4. Watch screen
#### Context

low/medium
#### Your Environment
- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 53.0.2785.101 m
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04): win 10

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4) and it appears.
We label this issue as a bug.
@tomi798 , thanks for raise this issue.

**Comment by samus-aran** [comment]
Gif image has been resolved - styling has not.

**Comment by Kevconry** [comment]
Was able to replicate in 7.13.1

the loading gif appears, however the text is still shifted
