### ISSUE TITLE
Days Dim - requesting context for translation

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2176]
#### Issue

What is the usage for "Days Dim" in language file
Can you elaborate to help translators?
Note: this string is from "marker_image_list" a strange set of strings as some of them seems already translated!
#### Expected Behavior

a comment to be used as context
#### Steps to Reproduce

lines is in the file
\include\language\en_us.lang.php

```
$app_list_strings['marker_image_list']['days_dim'] = 'Days Dim';
$app_list_strings['marker_image_list']['days_dom'] = 'Days Dom';
$app_list_strings['marker_image_list']['days_jeu'] = 'Days Jeu';
$app_list_strings['marker_image_list']['days_jue'] = 'Days Jue';
$app_list_strings['marker_image_list']['days_lun'] = 'Days Lun';
$app_list_strings['marker_image_list']['days_mar'] = 'Days Mar';
$app_list_strings['marker_image_list']['days_mer'] = 'Days Mer';
$app_list_strings['marker_image_list']['days_mie'] = 'Days Mie';
$app_list_strings['marker_image_list']['days_qua'] = 'Days Qua';
$app_list_strings['marker_image_list']['days_qui'] = 'Days Qui';
$app_list_strings['marker_image_list']['days_sab'] = 'Days Sab';
$app_list_strings['marker_image_list']['days_sam'] = 'Days Sam';
$app_list_strings['marker_image_list']['days_seg'] = 'Days Seg';
$app_list_strings['marker_image_list']['days_sex'] = 'Days Sex';
$app_list_strings['marker_image_list']['days_ter'] = 'Days Ter';
$app_list_strings['marker_image_list']['days_ven'] = 'Days Ven';
$app_list_strings['marker_image_list']['days_vie'] = 'Days Vie';
```
#### Context

Lack of information to translators

'marker_image_list' code is used in line 134 on
modules\jjwg_Markers\vardefs.php

```
        'marker_image' =>
            array(
                'required' => false,
                'name' => 'marker_image',
                'vname' => 'LBL_MARKER_IMAGE',
                'type' => 'enum',
                'massupdate' => '1',
                'default' => 'company',
                'comments' => '',
                'help' => 'Marker Image Type',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'len' => 100,
                'size' => '20',
                'options' => 'marker_image_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
```

**Comment by ijdavie** [comment]
This maybe best to contact the makers of JJWG Maps for clarification

**Comment by horus68** [comment]
Posted a question on JJWDesign Google Maps for SugarCRM
https://github.com/jjwdesign/JJWDesign-Google-Maps/issues/10

I don't know if this is maintained or monitored, and it seems this would require some refactoring.
Hope you can monitor this issue in future.

**Comment by pgorod** [comment]
It almost certainly stands for `Dimanche`, Sunday, since all the other examples alternate between French, Portuguese and Spanish day names.

(I once posted an issue on JJWDesign's Github and it never got any feedback...)

**Comment by horus68** [comment]
@ijdavie there is no response, it looks their github is not used anymore.
@salesagility needs to work on this as the module its been used in SuiteCRM core package!

**Comment by shogunpol** [comment]
@horus68  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by horus68** [comment]
@shogunpol  please reopen this.
This is not a forum topic but I created it anyway:
https://suitecrm.com/forum/suitecrm-7-0-discussion/11974-days-dim-in-language-file-marker-image-list

Following the issue conversation you can see it is now a code issue caused by a 3rd party module that is not really getting translations from the core language file "include" but uses 3 languages translations on the master en_US language file. 
This is a code from the Include language file that need to be refactored in order that translations are picked from each language code files not form the en_US language file (as it is now).

**The questions now are:**
- Are the strings actually used by the module? (In what screen are they visible?)
- How to remove the non-english translations strings from the english "include" language file and make the module to get the translations from each language pack?

Also, has the module makers did not reply and the module is packed as SuiteCRM core... this is a core issue now that require @salesagility to take some action, as it cannot be solved by users PR or collaboration

**Comment by Pawes** [comment]
I came across them when I was translating and it seems they are used as map markers.
These particular markers just display the text "Dim", "Dom" etc. Since they are not dynamically created, it makes no sense to translate them as the user will expect a different text then what will appear on the map. However, I guess the "Days" part should be translated. But I cannot think of a use case where I would need this on a map...
![mapmarkersscreenshot](https://user-images.githubusercontent.com/15903729/35269809-63d5137e-002d-11e8-93e1-c422979d3cec.png)

**Comment by pgorod** [comment]
@Pawes what does it mean, showing "Dim" on a map?

**Comment by Pawes** [comment]
That is what I want to know..

**Comment by pgorod** [comment]
If I'm not mistaken, all that `$app_list_strings['marker_image_list']` crap isn't used anywhere in the code, it's just defined in the language files...

But I wonder why it appears in the map, then...

**Comment by Pawes** [comment]
Well it is used here:
![markerlist](https://user-images.githubusercontent.com/15903729/35278200-86a4a16e-0049-11e8-8877-89844aab6a53.png)

But I don't know why you would want to place "Dim" or "Jeu" as a marker image.

**Comment by pgorod** [comment]
Oh, so I must have missed it somewhere.

I have a guess: it's meant for sales people to mark which places they will visit on Monday, Tuesday, etc.

**Comment by Pawes** [comment]
That sounds likely, but it would only be useful to French speakers, as the image will show "Dim" no matter what we translate the string in the list to.

**Comment by Dillon-Brown** [comment]
I'm guessing these are just the hard coded french versions of the days which we already have in English.

```
$app_list_strings['marker_image_list']['monday'] = 'Monday';
```
etc, I think we can just remove these.

**Comment by Pawes** [comment]
I am not sure how this module works, but I think this would cause unexpected behaviour.
If the user now chooses Monday in a version that has no corresponding marker image (eg. Russian) they will either be met by an error or will be presented with the English version of the marker:
![days_mon](https://user-images.githubusercontent.com/15903729/37269164-918c8290-25c9-11e8-8224-0f9471945ad6.png)

This is because these "day" marker images are not dynamically created and translated images only exist for a handful of languages (French, Portuguese? and Spanish?)

But if we keep the hard coded translations, at least the user will be aware that these marker images are not available in their language and avoid a potential error message.
