### ISSUE TITLE
Feature Request: Option to make a Subpanel appear visually indistinct from a regular Tab/Panel.

### ISSUE THREAD

**Issue by GeorgeWL** [salesagility/SuiteCRM#2180]
UI behaviour a client of mine really likes the idea of, to have all of the necessary data be visible solely through the top tabs.

For example the Detail View data of the Accounts table we have split into Panels, each of these Panels displayed as a Tab 
![e.g.](http://i.imgur.com/DnpYywc.png)

The idea is so that the data is divided into recognisable sections, whilst reducing the amount of scrolling required to view (as we really don't like the regular mode of Panels rather than Tabs, it makes the user have to scroll far too much and makes the data harder to read in context.)

Quick Mockup made through editing in Inspect, this is visual only, not actually real.
![mockup](http://i.imgur.com/6nipEFb.png)

**Comment by gunnicom** [comment]
For me this could be useful if i can do this for only some subpanels.

**Comment by acoolov** [comment]
Why was this closed? Was the feature made possible?
There is a lot of people that would like to change subpanels into tabs.

**Comment by Mausino** [comment]
@acoolov  Similar/Same suggestion is open under ticket #6038 Inject custom subpanel to any prefered Subpanel Tab created by Menu Module Filters

**Comment by acoolov** [comment]
I'll try that. 
Just a question, does that mean whatever I create in the menu filters I will have in the top menu? Because if that's the case, It's not a good solution.

**Comment by Mausino** [comment]
@acoolov when you look on practical view, for example in our company i tooked some new record of account module.. I dont think that will possible do Tabbed Subpanels for each module separately... it's better designed now by groups

+ Also will soon (hope 2019) SuiteCRM 8 which will complete redesign the detailview of record. https://suitecrm.com/new-user-interface-in-suite8/

When you still wont be satisfied, feel free to create own ticket where you will add all nessary informations about this new suggestion/enhacement which you/others want to have in future relases.

![bez nazvu](https://user-images.githubusercontent.com/5773777/50309254-707b8d80-049e-11e9-9f5e-5d9af4dabcb7.png)
