### ISSUE TITLE
AOR issue if i added the fied from other module

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2182]
#### Issue

In my report added new field and i got this issue in detailview of report record. SuiteCRM 7.7.4

![reports_issue](https://cloud.githubusercontent.com/assets/5773777/18388539/573239be-76a2-11e6-99e5-ab0410a00aa2.png)

![reports_issue2](https://cloud.githubusercontent.com/assets/5773777/18388548/5e712d20-76a2-11e6-9c89-a6ba7be1af9b.png)

#### Context

I am not sure if is the configuration mistake or serious issue in report system

#### Your Environment

* SuiteCRM Version used:
* Browser name and version: Chrome 53.x m
* Environment name and version: 5.6 PHP, 5.6 MySQL
* Operating System and version: Hosting - Linux

**Comment by ijdavie** [comment]
Hi @Mausino,
This looks like you have added custom relationships into the instance, If you have added custom relationships and your permissions were incorrect at that time it could cause the issue with the labels and possibly other issues depending on the root cause. 

We have tried this here with custom relationships and all works as expected with no error. I would suggest  maybe looking at the permissions and possibly the relationship in question. does this issue appear on other relationships ?

**Comment by Mausino** [comment]
Hi, i added image bellow

The red and green have same relationship instance... but green is working and red now. With red i got the issue as you saw in second screen.

![relationship](https://cloud.githubusercontent.com/assets/5773777/18428177/ce74b6ce-78cc-11e6-9172-b8ad50d85016.png)

My developer looks on it and i will add you later update from him.

**Comment by ijdavie** [comment]
@Mausino When you say it is not working, are you talking about the label or the data you would expect to return ?

**Comment by Mausino** [comment]
@ijdavie the data will not return... i want sort the reservations record via the id (which can be only numbers) and i got this error if i check to show this fields. I think, that it has something with type of data. I will soon have the report also from my developer :)

**Comment by ijdavie** [comment]
@Mausino any update on this?.

**Comment by Mausino** [comment]
@ijdavie my developer is on holiday, i / you can close now this report/issue and if i will more info i reopen this. Can we do this in this way ?

**Comment by ijdavie** [comment]
@Mausino, not a problem, yes, you should beable to reopen this as you created this. 
Thanks.
