### ISSUE TITLE
Studio: Can't modify fields - getting 'Invalid Value: Field Name already exists'

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2183]
Modifying a newly created field is not possible. SuiteCRM shows 'Invalid Value: Field Name already exists'

#### Issue

Create a field in Studio. Modifying i.e. the Display Label or Max Size is not possible any more. SuiteCRM show error message.
#### Expected Behavior

Modifying several attributes should be possible.
#### Actual Behavior

See above.
#### Steps to Reproduce

1. Fresh 7.7.4 install
2. Create a new field in Studio
3. 'Repair JS Files'
4. Logout
5. Clear browser cache
6. Login
7. Modify the created field is not possible ('Invalid Value: Field Name already exists')
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 48.0.2
- Environment name and version (e.g. MySQL, PHP 7): php 56, mysql 5.6
- Operating System and version (e.g Ubuntu 16.04): FreeBSD 10.2

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4) and it appears.
We label this issue as a bug.
@adminibt  , thanks for raise this issue.

**Comment by bmwtourer** [comment]
just to be clear, on the reference, my production is stil 7.6.5 so I could edit my view, I do have this issue in my dev environment 7.7.4...

**Comment by slalji** [comment]
Meanwhile I made the adjustment in the database. Table name fields_meta_data

**Comment by pktjuk** [comment]
I have this same problem too on suiteCRM 7.7.4

**Comment by wheathcock** [comment]
Same Issue here - SuiteCRM 7.7.4  Server: EC2- Amazon Linux  PHP: 5.6.25

**Comment by pktjuk** [comment]
Any update on this?

**Comment by Hope4hope** [comment]
no any fast fix?

**Comment by damoursf** [comment]
Same on 7.7.7, ovh, plesk, php 5.3, php display error off.

**Comment by cumanacr** [comment]
I having the same problem with a 7.7.5 instance but I want to audit changes on *industry* field that is a default field on Accounts module non a custom one.

IMHO this bug deserves a higher priority.

Regards,

**Comment by cumanacr** [comment]
I tried @slalji workaround and it works only for custom fields (thanks for that)

But I can't find default fields on fields_meta_data, so, I manually created:

custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_industry.php

    <?php
    // created: 2016-11-18 18:14:28
    $dictionary['Account']['fields']['industry']['audited']=1;
    ?>

And it's auditing now

**Comment by dursuntosun** [comment]
Is there any solution for this? I could not edit my field name :(

**Comment by ChangezKhan** [comment]
It seems that the issue with `jssource/src_files/include/javascript/sugar_3.php` file. On line no. 1186, in `case 'in_array':` block, it uses ajax method to call `getModuleFields` action and fetch all fields related to the selected module. And this is where the problem lies. 
In SugarCRM, it doesn't use this ajax call and it works fine. It fetches all fields only when we create the new fields, not when we edit. 
But in SuiteCRM, it fetches all fields using this ajax call everytime we create/edit fields and this creates this issue. 
For time being we can roll back to the old code, but it would be good if someone from team share their knowledge about this. Hey @shogunpol, need your help here.

**Comment by pktjuk** [comment]
Do you know when this fix will be released?

**Comment by dursuntosun** [comment]
When i try it, it does not work with 7.7.9. Problem is continue.

**Comment by samus-aran** [comment]
@ChangezKhan 
Yes we are aware of that, it was introduced to deal with another issue which the Sugar installation still remains.  There will be a follow issue raised regarding to tidying up that validation section soon.

**Comment by jssldb** [comment]
Hi, 

What's the timeline for merging this change with the release? Is it going to be present in the upcoming release? If not, are the above patches the only files that need to be changed to implemented on our Suite installation?

**Comment by aayushthakkar** [comment]
I had the same issue, I could not update the length of varchar column beyond 255. Did a hack to resolve it. There were 2 steps:

1. As mentioned by @slalji, I updated my field name in the "fields_meta_data".
Example:

update fields_meta_data 
SET len = <updated length>
where custom_module like '<module>' and name ='<field_name>'

2. Update the actual module with the desired datatype.
ALTER  <module> 
MODIFY <field_name> varchar(<updated length>)


P.S: I am not sure if this is the best way of doing.
