### ISSUE TITLE
DetailView isn't showing the columns in the same order given on studio

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#2188]
#### Issue

The detailView isn't showing the columns in the same order given on studio.

In Studio:
![selection-02-2016-09-09](https://cloud.githubusercontent.com/assets/6874136/18405967/6ef4f3ae-76b4-11e6-9a33-299272b1c858.png)

In DetailView (Image with only bad positioned fields):
![desktop1-04-2016-09-09](https://cloud.githubusercontent.com/assets/6874136/18405970/7396697e-76b4-11e6-8f3d-e0aa58471181.png)

#### Steps to Reproduce

1. Go to studio -> Opportunities -> DetailView
2. Copy the layout as I did on the attached image
3. Save & Deploy
4. Go check an opportunity
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
- Environment name and version:
  - mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
  - PHP Version 5.6.25-2+deb.sury.org~xenial+1
  - Apache/2.4.18 (Ubuntu)
- Operating System and version: 
  - Distributor ID: neon
  - Description:    KDE neon User Edition 5.7
  - Release:        16.04
  - Codename:       xenial

**Comment by horus68** [comment]
Confirmed with accounts detail view too!

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4) and it appears.
We label this issue as a bug.
@cumanacr  , thanks for raise this issue.

**Comment by vladbar** [comment]
Hi cumanacr, could you please specify which theme you are using ?
I tried to replicate this issue on SuiteCRM 7.8.1 Suite P theme, but it works as expected.

**Comment by cumanacr** [comment]
Hi @vladbar the problem persist on SuiteCRM 7.8.1 as well with SuiteP theme.

![selection-03-2017-02-08](https://cloud.githubusercontent.com/assets/6874136/22758805/d14ec20e-ee15-11e6-803f-64a085debb80.png)

Same layout as before...

![selection-05-2017-02-08](https://cloud.githubusercontent.com/assets/6874136/22758803/d1475f5a-ee15-11e6-8323-29a10e69678f.png)

... same results (sort of) **Address** is located now on its row that's an improvement, but, **Modify by User Name** and **Created By** should be on the right side of  the screen not on the left.

![selection-04-2017-02-08](https://cloud.githubusercontent.com/assets/6874136/22758804/d14cd17e-ee15-11e6-9fa5-9fc95ac68a44.png)

Regards,

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.1. When changing the names of the fields and moving them around, they change appropriately. please re-raise or Get in touch if you are still having this issue
