### ISSUE TITLE
Invoice record uploaded Images not showing in generated PDF file

### ISSUE THREAD

**Issue by cuffy3141** [salesagility/SuiteCRM#2190]
#### Issue

Invoice record has had a image field added to it. The image uploads and displays correctly when viewing record.
Adding the image field to a pdf template results in a missing image icon in the created PDF file.

#### Expected Behavior

When an field of type image is added to a pdf template, it is expected that the corresponding image from the record is added to the PDF file that is created. 

#### Actual Behavior

A missing image (red cross) icon is output to the PDF file.

#### Steps to Reproduce

1. Create a new field on invoice of type image
2. Add the new field to the edit screen of invoice
3. Create an invoice record and upload a jpg image to the new field.
4. Create a pdf template on invoice and add the image field to it.
5. Select Print as PDF on the created invoice record. 
6. Select the PDF template that you added the image field to.
7. Examine the generated PDF.

#### Context

This issues is stopping us from producing custom reports on the invoice records, which is causing a lot of manual intervention.

#### Your Environment

* SuiteCRM Version used: Version 7.7.4 Sugar Version 6.5.24 (Build 509)
* Browser name and version: Any browsers 
* Environment name and version (e.g. MySQL, PHP 7):5.5.44-MariaDB-cll-lve - MariaDB Server, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 and Windows 10

**Comment by cuffy3141** [comment]
I have also checked the functionality within other modules that use PDF templates and the results are the same. Instead of embedding the image in the PDF it just inserts the file name of the image without the preceeding record id.

**Comment by ijdavie** [comment]
This appears to be related to issue #2153, As that one is older I will close this duplicate.
