### ISSUE TITLE
Are [table] [column] placeholders not to be translated?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2192]
#### Issue

In the language file
\modules\UpgradeWizard\language\en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/language/en_us.lang.php#L135-L144

Are [table] and [column] placeholders and should not be translated?
Nothing should be translated? Or...?

```
    'LBL_UW_DB_NO_ADD_COLUMN'                   => 'ALTER TABLE [table] ADD COLUMN [column]',
    'LBL_UW_DB_NO_CHANGE_COLUMN'                => 'ALTER TABLE [table] CHANGE COLUMN [column]',
    'LBL_UW_DB_NO_CREATE'                       => 'CREATE TABLE [table]',
    'LBL_UW_DB_NO_DELETE'                       => 'DELETE FROM [table]',
    'LBL_UW_DB_NO_DROP_COLUMN'                  => 'ALTER TABLE [table] DROP COLUMN [column]',
    'LBL_UW_DB_NO_DROP_TABLE'                   => 'DROP TABLE [table]',
    'LBL_UW_DB_NO_INSERT'                       => 'INSERT INTO [table]',
    'LBL_UW_DB_NO_SELECT'                       => 'SELECT [x] FROM [table]',
    'LBL_UW_DB_NO_UPDATE'                       => 'UPDATE [table]',
```

**Comment by shogunpol** [comment]
@horus68  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by horus68** [comment]
topic here https://suitecrm.com/forum/suitecrm-7-0-discussion/11976-are-table-column-placeholders-not-to-be-translated

"What I would loved to here was a reply: placeholders needs to be clearly marked as placeholders so we will create a standar procedure for this and then revise the code"
 
That's "Life As It Should Be"
