### ISSUE TITLE
Icons missing on chart dashlets for SuiteP

### ISSUE THREAD

**Issue by KhyberPass** [salesagility/SuiteCRM#2194]
#### Issue

The SuiteP theme added new icons for various modules including dashlets. The dashlets now have an icon in the top left of the dashlet window.
When a Chart dashlet is added an icon is not shown, instead a missing image is displayed as shown below.
![image](https://cloud.githubusercontent.com/assets/5484293/18421218/cf4e9740-78c7-11e6-8ec8-e963c9605359.png)
#### Expected Behavior

A valid icon should be displayed.
#### Actual Behavior

An invalid image is shown.
#### Possible Fix

See posts below.
#### Steps to Reproduce

1. Use SuiteP theme
2. Add a chart dashlet to the home page, for example Pipeline By Sales Stage
3. View the icon for the dashlet
#### Context

Low priority but does not look good for a home page. Easy fix so should be done.
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116 m 64bit
- Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.48-37.8, PHP 5.4.45 
- Operating System and version (e.g Ubuntu 16.04): Hostgator CentOs 6.8

**Comment by KhyberPass** [comment]
The icons for dashlets are automatically determined from the defined module name for the dashlet. 
When the error occurs the following is the html source
`<img src="<br /><b>Warning</b>:  Smarty error: Missing required field:file in <b>/home3/uscom/public_html/zs-suitecrm/include/Smarty/Smarty.class.php</b> on line <b>1094</b><br />">`

The following code in the template file themes/SuiteP/include/Dashlets/DashletHeader.tpl is an example of how the icon is determined and the above source is generated.
`<img src="{sugar_getimagepath file_name=$DASHLET_MODULE file_extension='svg' directory='sidebar/modules'}"><span>{$DASHLET_TITLE}</span>
`
In this case $DASHLET_MODULE is defined in include/Dashlets/Dashlet.php as
`$template->assign('DASHLET_MODULE',$this->seedBean->module_name);`

So the issues is that $this->seedBean->module_name is not defined.

Other dashlets are more defined in their data retrieval displaying tables or lists, these use the bean mechanism to obtain the data. The Chart dashlets are different and use data and the bean differently. This means that the bean data is no populated.

**Comment by KhyberPass** [comment]
The Chart dashlets are located at modules/Charts/Dashlets. The following charts are available

- OpportunitiesByLeadSourceDashlet
- OpportunitiesByLeadSourceByOutcomeDashlet
- OutcomeByMonthDashlet
- CampaignROIChartDashlet
- PipelineBySalesStageDashlet
- MyPipelineBySalesStageDashlet
 
All these define a seed name 
```
`$_seedName = 'Opportunities';`
```
`These all include generic Chart dashlet code located at include/Dashlets/DashletGenericChart.php

A bean is actually created but under a different variable name - $_seedBean rather than $seedBean used by the code. This is done in the function getSeedBean().

So we just need to create the bean a bit earlier and set the module name variable. Then set the variable $sugarBean to equal this bean.

In the constructor add the following
```
$this->seedBean = $this->getSeedBean();
$this->seedBean->module_name = "Charts";
```

We also need to create a chart icon image file. In themes/SuiteP/images/sidebar/modules copy AOS_Products.svg to Charts.svg

**Comment by Mausino** [comment]
Similary to #2124

**Comment by apmuthu** [comment]
````include/SugarTheme/SugarTheme.php```` has references to ````pathCache.php````

````PATH_SEPARATOR```` and ````DIRECTORY_SEPARATOR```` causes ````cache/themes/SuiteP/pathCache.php```` to have 12 instances of ````sidebar/modules\ ```` like 
````
sidebar/modules\Calls.svg
themes/SuiteP/images/sidebar/modules\Calls.svg
sidebar/modules\Meetings.svg
````

**Comment by ijdavie** [comment]
This appears to have been fixed in a previous version of SuiteCRM, 

Due to the above I have closed the related PullRequest and this issue.
