### ISSUE TITLE
Dashlets with Bar Charts not drawn when there is a single element

### ISSUE THREAD

**Issue by KhyberPass** [salesagility/SuiteCRM#2196]
#### Issue

When a Chart dashlet, for example ‘Pipeline By Sales Stage’, contains only one bar in the bar graph the graph is not drawn.
![image](https://cloud.githubusercontent.com/assets/5484293/18421762/3560479c-78d5-11e6-98f6-110ae64c2f11.png)

#### Expected Behavior

A bar graph should be drawn with a single bar.

#### Actual Behavior

Graph is not displayed.

#### Possible Fix

Change the check for an empty data array in
modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php

#### Steps to Reproduce

1. Add a chart dashlet to the home page, for example 'Pipeline By Sales Stage'.
2. Note a sales stage that displays data on the bar graph.
3. Then configure the dashlet by clicking on the edit pencil icon. Configure the chart to just display the sales stage noted above and no other sales stage.
4. Save the configuration and no graph is shown even though there is valid data..

#### Context

If for a particular date range there is only one sales stage with data then it will not be shown which is an error. 

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116 m 64bit
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.48-37.8, PHP 5.4.45
* Operating System and version (e.g Ubuntu 16.04): Hostgator CentOs 6.8

**Comment by KhyberPass** [comment]
Before the introduction of the new RGraph engine a funnel graph was displayed for the ‘Pipeline By Sales Stage’. This has now changed to display a bar graph. Not too sure why this change was made, maybe because the funnel graph in RGraph does not look very good and uses width rather than height to display the data of each stage.
There was a comment in the code that an empty element was required at the end of the data array for the funnel. Therefore in modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php the following check was done when generating the graph.
```
if(!is_array($chartReadyData['data'])||count($chartReadyData['data']) < 2)
```
Because there is actually no empty element at the end of the array this should be
```
if(!is_array($chartReadyData['data'])||count($chartReadyData['data']) < 1)
```

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4) and it appears.
We label this issue as a bug.
@KhyberPass  , thanks for raise this issue.
