### ISSUE TITLE
7.7.4 Suite P theme not wrapping text in Accounts Billing and Shipping details

### ISSUE THREAD

**Issue by macue** [salesagility/SuiteCRM#2203]
#### Issue

When long strings of text are entered into the Billing Address and Shipping Address Account fields; they spill over their container boundaries instead of wrapping around.
The 'Copy...' buttons on each field also become displaced.

![suitecrmtextwrapping](https://cloud.githubusercontent.com/assets/22161231/18458279/1e2c932c-79a3-11e6-8947-77e308bde404.png)
#### Expected Behaviour

Long text strings for Billing and Shipping Address details should wrap around and remain within their container boundaries.
The Copy buttons should stay within their respective containers
#### Actual Behaviour

Long text strings for Billing and Shipping Address details spill over to their container boundaries making adjacent labels unreadable or interfering with other objects on the screen.
Copy buttons no longer line up with their own containers
#### Possible Fix

n/a
#### Steps to Reproduce
1. Create a New Account
2. Enter the following data in Billing Address
   2.1  Street: Australian Stock Exchange, Building 3, 23 Kingston Road
   2.2 City: Melbourne
   2.3 State: Victoria
   2.4 Postal Code: 3000
   2.5 Country: Australia
3. Click 'Copy address from left: '
4. Save / Create the new Record
5. Open and view the Customer details
6. may have to resize the width of the Browser window to see text not wrapping and Copy button displacement
#### Context

How has this bug affected you? What were you trying to accomplish?
Trying to enter customer details which contain long addresses

If you feel this should be a low/medium/high priority then please state so
I think this is a medium level priority as the bug interferes with being able to read what's on the screen
#### Your Environment
- SuiteCRM Version used: 7.7.4
- Browser name and version: IE 11, FireFox, Chrome 
- Environment name and version: MS SQL Express 2016; PHP 7.0.9
- Operating System and version: Windows 10 Pro 64-bit

**Comment by horus68** [comment]
Confirmed!
Also, the description field created on a previous version looks fine with multi-line text.
If you edit on the 7.4.4 version it will saved as a single (long) line...!

**Comment by cumanacr** [comment]
Confirmed on SuiteCRM 7.7.8 too, the problem is when a long text is typed on Street field.
eg:

    THIS IS A REALLY REALLY LONG DESCRIPTION OF A LATIN AMERICAN STREET ADDRESS WITH MULTIPLE  DETAILS ON NEIGHBOURS LOCATIONS.

**Comment by dhayner** [comment]
Is the cause here also related to how I see long field names in Accounts do not wrap on detailview or editview?
![image](https://cloud.githubusercontent.com/assets/17885806/22435721/1e54c7ca-e6ef-11e6-873e-6b9b52f6499c.png)

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
