### ISSUE TITLE
Issues with labels name in calendar events on dashlet of suitecrm-7.7.4 dashboard

### ISSUE THREAD

**Issue by chandan999** [salesagility/SuiteCRM#2207]
Undefined label when hover on calendar events present on dashlet.

#### Issue

when we hover on any events/task/activities on my calendar on dashlet present  in dashboard of suitecrm-7.7.4.The issues is there only with dashboard.But it is fine when we open calendar directly.
#### Expected Behavior

Not dispaly proper label about calender events
#### Actual Behavior

Should display proper label about calender events
#### Possible Fix

Label name might be missing in calendar dashlet language file.

#### Steps to Reproduce

1.
2.
3.
4.
#### Context

![calender_issue](https://cloud.githubusercontent.com/assets/18693306/18463650/4f15c232-79a9-11e6-8a50-ce1f365be59b.png)
#### Your Environment

- SuiteCRM Version used:7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chrome
- Environment name and version (e.g. MySQL, PHP 7):Mysql,Php 5.4
- Operating System and version (e.g Ubuntu 16.04):windows

**Comment by staganyi** [comment]
Can confirm it's still present on 7.7.6
![image](https://cloud.githubusercontent.com/assets/20977561/19697983/8ad12a90-9abb-11e6-92c9-9a8cf4c2a57e.png)

**Comment by chandan999** [comment]
Yes,
    It is still present in suitecrm 7.7.6.
   On homepage,we have this issue.

**Comment by staganyi** [comment]
This appears to be fixed in 7.7.7

**Comment by shogunpol** [comment]
The issue not appear from version 7.7.7, and not appear,
@chandan999 , this issue will be closed, however if issue still exist for you,
it can be reopen again.
