### ISSUE TITLE
v7.7.4 Install warning headers sent

### ISSUE THREAD

**Issue by apmuthu** [salesagility/SuiteCRM#2214]
Warning headers sent on last page of installation.
![suitecrm 774 install error](https://cloud.githubusercontent.com/assets/2995044/18484548/89f81a78-7a06-11e6-8cc6-624647447294.png)

#### Tested Environment
* SuiteCRM Version used: 7.7.4
* Browser name and version: FireFox v37.02 (32 bit)
* Environment name and version: MySQL 5.1, PHP 5.3.1 Apache 2.2 XAMPP v1.7.3
* Operating System and version: WinXP SP3

**Comment by ijdavie** [comment]
Hi @apmuthu, 

This appears like you have display errors on, on that server can you confirm this ? 

With this being a long term project and has been running for a while there is a number of issues around existing warnings and strict messages which we are working to resolve. and can be see with issue #942.

**Comment by apmuthu** [comment]
Yes, error / warnings display is on.

**Comment by ijdavie** [comment]
@apmuthu, turning off the display errors will fix this issue you see in the user interface. the warnings which get logged into the system logs have been raised as #942. I will close this case and will be addressed against #942.
