### ISSUE TITLE
PHP7 - v.7.7.4 : Blank screen when "Create Person Form" tries to generate

### ISSUE THREAD

**Issue by daschenbrener** [salesagility/SuiteCRM#2216]
when trying to generate a Create Person Form , the system generates a blank screen

#### Expected Behavior
The form code should be displayed

#### Actual Behavior
a blank screen

#### Possible Fix
?

#### Steps to Reproduce
create a from, and setup all the fileds and when clikcing Generate form, the area where the code should be displayed goes blank.

#### Your Environment
suitecrm 7.7.4
php 7
mariadb 10.0.27
centos 7

[suitecrm form blank creen.txt](https://github.com/salesagility/SuiteCRM/files/471032/suitecrm.form.blank.creen.txt)

**Comment by daschenbrener** [comment]
hi @ijdavie is there a quick workaround for this or someone has some basic template code i can utilize so I can move forward with having to generate the code from the site.

**Comment by mattlorimer** [comment]
this is related to #1591 and you can see the fix here #1989

**Comment by daschenbrener** [comment]
Thank You very much, works like a charm
