### ISSUE TITLE
Reports build using Suite Spots doesn't update

### ISSUE THREAD

**Issue by nQaze** [salesagility/SuiteCRM#2218]
Reports generated using Suite Spots doesn't updates itself until system is repaired and rebuild

#### Issue
I have made a analytic report using spots to view activities of my users, Now if any user creates any new activity, that new activity is not reflected in that earlier created report using spots.

#### Expected Behavior
The Spots Report should fetch current values and display accordingly.

#### Actual Behavior
If the count of calls of a user is 7, then even when user creates new calls, the report shows 7, i.e. the count which was there at the time of creation of report. 

#### Possible Fix
The Spot report displays updated values when the system is repaired and rebuild. But it is not feasible to keep on repairing and rebuilding again and again.

#### Steps to Reproduce
1.Create a Spot report for activities, "Count vs Type-Status by Assigned User"
2.Now for any user already selected in report, create a call/meeting/task with assigned to any user selected in spots report
3.Now again go to spots report which was created in step 1, The count should have increased but it doesn't.

####Environment

* SuiteCRM Version used: 7.7/7.7.4
* Browser name and version (e.g. Chrome Version 52.0.2743.116 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 5.5.12):
* Operating System and version ( Windows 7):

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear,
We assign this issue as a bug.
@daschenbrener  , thanks for raise this issue.

**Comment by ijdavie** [comment]
This is related to #1962, Due to this I will close this as a duplicate.
