### ISSUE TITLE
Workflow doesn't work correctly with dynamic dropdowns

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#222]
Workflow doesn't treat dynamic drop down that same as it would an ordinary dropdown

**Comment by mdemaree99** [comment]
Pull Request has been Submitted
Solution provided:
https://suitecrm.com/forum/bug-tracker/4723-dynamic-dropdown-in-reports

**Comment by ijdavie** [comment]
This was merged in previously however Pull Request was not linked to Issue. Closing due to issue is fixed in this PR
