### ISSUE TITLE
Collaborate on merging PR days - Request for Comments (RFC)

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2228]
#### Issue

There is a **backlog of Pull Requests** specially those posted by community users.
Salesagility wants to improve its workflow on community collaboration. 
We users could also help on reducing the backlog, joining something like a **Merging PR party** so we can have regular PR blasts.
Those days would be **organized by Salesagility**, who will create a series of rules on what and how to perform those tests. 
Its not intended to have a decision by committee, **merges will only happens by salesagility devs** (as usually) and also will manage those special days and the required step-by-step testing and merge.
This is to encourage more community members to test PRs and help things moving with a clear workflow.
#### Expected Behavior

The most talented SuiteCRM **community coders** should be invited by SalesAgility into a special day (twice a month?) to make a joint Pull Request day for testing + merging + clean up.
Regular merges of PR should always exists as it is now. 
The special days will:
- boost the number of merges and reducing issues and bugs
- empower users collaboration
- create an expectation for the special PR days, followed probably by a new version release.
## Discuss in the forum and share your time

Enter this topic forum to discuss the idea and enlist if you are interested in this
https://suitecrm.com/forum/feedback/11159-merging-pr-party

**Comment by shogunpol** [comment]
@horus68 , do you notice any progress on this suggestion?

**Comment by horus68** [comment]
@shogunpol Not really! There is a recent topic forum with some answers:
Looking for a SuiteCRM New Year resolutions over Bugs and Fixes  https://suitecrm.com/forum/feedback/12376-looking-for-a-suitecrm-new-year-resolutions-over-bugs-and-fixes
The proposals from Salesagility is to use the "Accessed" tag on PR + Votes to filter + community user direct call) but none are a real workflow as proposed here (to create a Planned and regular PR merges)

Note: The proposal was not on issues and bugs but on PR not merged. This makes us to use so many little fixes proposed but not merged from several versions old, and then the PR is unusable because some recent changes on some other files.
Note: Even the "Accessed" PR or the ones created by Salesagility team are not merged!
https://github.com/salesagility/SuiteCRM/labels/Assessed

So I'm waiting for better days in next year!

**Comment by murdal** [comment]
@horus68 - I'm going to close this issue as there is a forum thread for it and it is more a process discussion. We are looking at reducing the pull request backlog for 7.9 substantially and @samus-aran is working on developing processes in this area but the forum will become the main area to discuss these.

**Comment by horus68** [comment]
Ok, waiting then!
