### ISSUE TITLE
Created Calls are shown in History Panel

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2236]
#### Issue
Created calls are shown in history panel, rather than Activities panel. Since Call is an activity type, it should be shown in Activities panel.

![2016-09-15 20_48_42-call-activity](https://cloud.githubusercontent.com/assets/20369981/18560881/2397adee-7b86-11e6-86fb-a33681e7f28a.png)

#### Expected Behavior
Created Calls should be shown in Activities panel. 

#### Actual Behavior
Created Calls are shown in History Panel.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (Chrome Version 52.0.2743.116 m):
* Environment name and version (MySQL, PHP 5.6.24):
* Operating System and version (Ubuntu 16.04):

**Comment by ijdavie** [comment]
Hi @gokhanerdogdu, this appears as expected, If a call/Meeting is saved with the status held this record will appear in the history rather than the activity list. this is standard functionality.
