### ISSUE TITLE
Dynamic Dropdowns-Opportunities module issue!

### ISSUE THREAD

**Issue by itglaafs** [salesagility/SuiteCRM#2241]
#### Issue

When in Opportunities module in edit view and if you have dynamic child drop downs, they are not connected to parent dropdown until you choose another value in parent dropdown, only then they are working as they should and they are connected normally. 
This behaviour shows full list of all available options in child drop down, and you are able to save any option with parent dropdown which is sort of a bug.
I have tested same dropdown lists in another modules, e.g. Accounts, Contacts, Leads and they are working without problem.
#### Expected Behavior

Child drop down should show only options for related parent drop down
#### Actual Behavior

Child drop down is showing all options on edit regardless of parent drop down.
#### Steps to Reproduce

http://screencast-o-matic.com/watch/cDQD6Hj2dj

1. Create dynamic drop downs in Opportunities module with parent, child relationships and add some records to it.
2. Open up edit on any record in same module.
3. See if child drop down is showing all options or just related ones to it's parent.
4.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.2.2 max
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 52.0.2743.116
* Environment name and version (e.g. MySQL, PHP 7): Mysql 5.6.32 MyISAM, PHP 5.4.42
* Operating System and version (e.g Ubuntu 16.04): Redhat, 2.6.32-573.3.1.el6.x86_64

**Comment by shogunpol** [comment]
The issue has been tested on the current version of SuiteCRM(7.7.4), and not appear.
I can not say for sure what kind of customisation you did.
If you can replicate this issue on standard functionalities and modules, and gives us all details how you created all involved fields in issue. We try to examine and help you to solve your issue.
@itglaafs , thanks for raise this issue.

**Comment by itglaafs** [comment]
Hello @shogunpol,
Thank you for your input,
These are the new updates that i just discovered. Opportunities have 8 tabs in our CRM, if dynamic dropdown exists in first two tabs, it will show the whole lists no matter what the parent drop down is. If you move to from 3rd to 8th tab it will work as it should.  It's just the position and that's it. We tried all combinations, moved other type of fields from the first two tabs and it only worked when it was placed in 3rd tab and above with no matter what placement of other fields. This is really strange situation.

**Comment by itglaafs** [comment]
Hello @shogunpol 
Thank you for your comment.
We found potential problem. It appear that when you have second child dropdown that is related to first child dropdown, which is then connected to parent dropdown, first child dropdown will always show all values regardless of parent related dropdown if second child does not have value in first child dropdown. The error is when you try to connect dynamic dropdown to another dynamic dropdown. 

There is also another problem that you can save all values of second child dropdown, even if they are not connected with any of related parent dropdowns.

The way I connected dropdown was : 
Parent have values : A B C (dropdown)
First child dropdown: A_1 A_2 B_1 B_2 B_3 C_1 C_2 (dynamic dropdown)
Second child dropdown A_1_a A_1_b    (dynamic dropdown)

**Comment by shogunpol** [comment]
@itglaafs , The issue has been re-tested on the current version of SuiteCRM(7.7.4), and not appear.
I recreate structure mentioned by you in previous post, and still working.
The version what you have in your environment is extremely outdated, can you try replicate your issue in recent version of SuiteCRM?

**Comment by itglaafs** [comment]
Hello @shogunpol ,

I have tried to update from version 7.2.2 max to 7.7.4 on test system and it seems that it breaks Contacts module. Contacts module tabs are lost and you can't see any of fields that are there. 

It' worth mentioning that I am using Process Manager, Security Suite, Proximity Search and Reports for SugarCRM CE as additional modules. Mysql version is 5.6.32 and PHP is 5.4.42

Also, Accounts, Contacts, Leads and Opportunities have custom fields entered through Studio, but there is no code customization in the system itself.

Would you be able advise, if upgrade from 7.2.2 to version 7.7.4 is doable and how? Thank you very much.

**Comment by itglaafs** [comment]
I have also, recreated dropdowns on clean 7.7.4 and I can confirm that above described issue does not appear, but another one arose. 
If you choose A for value, then A_1 and related A_1_a it will show correctly, but if fields should have another value instead sometime in future, let's say B and B_1 which does not have related value in second child dropdown, it will show correctly in edit mode, but not in detail view.

A picture is worth a thousand words, let's try with video maybe that will be worth even more.

http://screencast-o-matic.com/watch/cDQYlcjbxh

**Comment by ijdavie** [comment]
@itglaafs, due to this being a separate issue, I think this is best we close this issue and this new issue is raised as new. this will keep it easier for anyone picking up this issue to understand what the main problem is. If you can raise this as a new issue that would be great. 
Thanks.
