### ISSUE TITLE
All History Filters and Delegates Filter totaly broken

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2242]
Trying to use these filters result in ether not filtering or showing a blank subpanel. It is very annoying that this is not working, esp. when you have large quantities of records in the subpanels.

BTW: This (at least the history filters) worked in 7.4.3.

#### Issue

Picking i.e. notes in a history filter will still show all entries.
Seraching for a term in history filter or delegate filter will show a blank subpanel.

#### Expected Behavior

The search should display the results.

#### Actual Behavior

See above.

#### Steps to Reproduce

1. See above and use the demo site.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 48.0.2
* Environment name and version (e.g. MySQL, PHP 7): php 56, mysql 5.6
* Operating System and version (e.g Ubuntu 16.04): FreeBSD 10.2

**Comment by ijdavie** [comment]
This is related to #2106, I will close this as seen as a duplicate.
