### ISSUE TITLE
Campaigns - Wizzard/Editview and unusable fields

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2255]
Campaigns can only be modified through Wizzard which makes couple of fields useless.

#### Issue

Startdate, Enddate and Frequency cannot be changed via the Wizzard.
#### Expected Behavior

The fields should be modified. Is there any way to just bring back the normal Editview? This is usefull in case custom fields are beeing used. How do you deal with custom fields when using the Wizzard?
#### Actual Behavior

No fields are presented.
#### Steps to Reproduce

1. 
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04):

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.1. The Start Date, End Date and frequency can be modified outside of the wizard and in the detail view of the record you are viewing.  please re-raise or Get in touch if you are still having this issue
