### ISSUE TITLE
Images in Campaign-Mail not embedded; shown as attachment

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2256]
Images in a HTML-Campaign-Mail are not shown embedded when opened with Outlook or Thunderbird. The images are beeing shown as attachments.

#### Issue

Images in HTML-Campaign-Mails don't work properly.

#### Expected Behavior

Images should show inside the email.

This worked in 7.4.3.

#### Steps to Reproduce

1.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment]
This appears to be the same issue as issue #1521, I will close this and mark it as a duplicate.
