### ISSUE TITLE
Reminder alerts are not working

### ISSUE THREAD

**Issue by saleembdr** [salesagility/SuiteCRM#2258]
The alerts are not showing for reminders.

#### Issue
SuiteCRM is not showing alerts for reminders that have the alert option selected.

#### Expected Behavior
SuiteCRM show show alerts for reminders that have the alert option selected.

#### Actual Behavior
No alerts are show for reminders that have an alert option selected when time is reached.

#### Possible Fix
The following statements in the file 'modules/Reminders/Reminders.php' are causing an incorrect format for the maximum and current dates:

$dateTimeNow = $db->convert($db->quoted($dateTimeNow), 'datetime');
$dateTimeMax = $db->convert($db->quoted($dateTimeMax), 'datetime');

The variables are used in conditions to compare to PHP date values, however, the 'db->convert' is adding syntax for conversion that is suitable in a database context. The following statement is used to compare dates of reminders:

(strtotime($relatedEvent->date_start) >= strtotime(self::unQuoteTime($dateTimeNow))

#### Steps to Reproduce
1. Create a meeting
2. Add a reminder with an alert option

![image](https://cloud.githubusercontent.com/assets/10287173/18665336/7131b0de-7f2f-11e6-8a24-820494047632.png)

3. Open SuiteCRM with a user that is associated with the reminder and wait for the alert

#### Context
I was testing the alerts function of SuiteCRM with meetings.

#### Your Environment
SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 7 on IIS.

**Comment by ijdavie** [comment]
This appears to be directly related to issue #2082, I will close this any further information can be added to #2082.
