### ISSUE TITLE
Converted/Dead Leads on Dashboard

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2259]
#### Issue
Converted/dead leads are also seen on homepage My Leads Dashboard. In order to followup New/Open Leads easier, these converted/dead leads should not be shown on Dashboard.

![2016-09-20 12_55_38-leads-dashboard](https://cloud.githubusercontent.com/assets/20369981/18665864/ce60a7f4-7f31-11e6-9c54-67d8ac11b2b2.png)

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (MySQL, PHP 5.6):
* Operating System and version (Ubuntu 16.04):

**Comment by ijdavie** [comment]
Hi @gokhanerdogdu  This is expected this is just going to list all leads assigned to your self regards of the status, you can change these settings in studio to define what fields are searchable and then in the settings of the dashlet.
