### ISSUE TITLE
Campaign subpanels not paginating

### ISSUE THREAD

**Issue by virtualme123** [salesagility/SuiteCRM#2261]
#### Issue

It seems to only be in the Campaigns module, but each subpanel that has pagination because there are more rows to see (like target lists) when you click the arrow makes the whole subpanel disappear.

#### Expected Behavior

Obviously with the pagination you expect to click the arrow and move to the next set of rows.

#### Actual Behavior

The whole subpanel collapses and you can only refresh the page to get the list back, but still can't get past the first rows to the next.

#### Possible Fix

Not really sure, likely to be the javascript incorrectly anchored?

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

Makes it difficult to view for instance other target lists, I can get around it in the admin settings increasing subpanel items per page.

I've looked through the list of bugs but can't seem to find this one, so it might just be me?

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 53.0.2785.116 m (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by dursuntosun** [comment]
Yes, i have this issue also.

**Comment by roy2098** [comment]
As do I and have commented on it elsewhere ...
