### ISSUE TITLE
Major issue SuiteP Theme UNUSABLE with Internet Explorer

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#2267]
if I try to edit a record the single line text field is not showing properly... only top portion of text is showed in the edit box. 
This is from IE
![image](https://cloud.githubusercontent.com/assets/9001018/18676259/026fc4b2-7f23-11e6-8110-a55ddb4c31f0.png)

We should see the text in the edit box, this is prone to errors

horus68 confirmed this is a bug 

see
[https://suitecrm.com/forum/suite-themes/11176-suitep-theme-incompatible-with-ie#38087](url)

using 7.7.4 on 
![image](https://cloud.githubusercontent.com/assets/9001018/18676418/83d16e3e-7f23-11e6-9e2f-892e03615860.png)

**Comment by mattlorimer** [comment]
thanks for reporting this this should be fixed in the next release, and should already be fixed in the hotfix branch
