### ISSUE TITLE
Calendar Widget

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2269]
#### Issue

The calendar widget is not showing the correct information when pressing the left/right buttons.
#### Expected Behavior

Pressing the left/right buttons should advance the calendar +/- 1 week
#### Actual Behavior

The widget gets confused with the dates
#### Steps to Reproduce

Press the left/right button on the widget
#### Context

It's a bit of a pain

**Comment by ijdavie** [comment]
@SpudR, which version are you using ?

**Comment by SpudR** [comment]
Sorry - shouldn't have assumed!
7.7.4
PHP 7 (I think)

**Comment by ijdavie** [comment]
Seems it is worth noting that in SuiteR the icons are there for the next/previous buttons and they work in a odd manor, of SuiteP they are hidden but clickable.

**Comment by SpudR** [comment]
Had a look at the logs and they are simply full of errors about guessing the timezone:
on Sep 26 10:58:11 2016 [171505][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone UTC. Please set date.timezone="UTC" in php.ini!
There is simply nothing else in there.
I have corrected that error, but the issue remains.
FYI - I have noticed that the first click moves the date line on to the next set, but the grid isn't updating.
Another click advances bot the date and the grid (now out of sync).

**Comment by SpudR** [comment]
Got some more logs (amended for security):

PHP Notice:  Undefined index: LBL_PREVIOUS_AGENDAWEEK in /SuiteCRM7.0.2/modules/Calendar/CalendarDisplay.php on line 522: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined index: LBL_NEXT_AGENDAWEEK in /SuiteCRM7.0.2/modules/Calendar/CalendarDisplay.php on line 503: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldVarchar::displayInput(&$layout_def) should be compatible with SugarWidgetField::displayInput($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldvarchar.php on line 106: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldName::queryFilterone_of($layout_def, $rename_columns = true) should be compatible with SugarWidgetFieldVarchar::queryFilterone_of(&$layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldname.php on line 46: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldName::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldname.php on line 46: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldId::queryFilterIs(&$layout_def) should be compatible with SugarWidgetReportField::queryFilterIs($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldid.php on line 48: /SuiteCRM7.0.2/index.php
PHP Notice:  Trying to get property of non-object in /SuiteCRM7.0.2/include/Dashlets/Dashlet.php on line 245: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined property: JotPadDashlet::$seedBean in /SuiteCRM7.0.2/include/Dashlets/Dashlet.php on line 245: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined property: Task::$rel_users_table in /SuiteCRM7.0.2/modules/Calendar/CalendarActivity.php on line 188: /SuiteCRM7.0.2/vcal_server.php
PHP Warning:  Declaration of SugarFieldText::getDetailViewSmarty($parentFieldArray, &$vardef, $displayParams, $tabindex) should be compatible with SugarFieldBase::getDetailViewSmarty($parentFieldArray, $vardef, $displayParams, $tabindex) in /SuiteCRM7.0.2/include/SugarFields/Fields/Text/SugarFieldText.php on line 85: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of & SugarWidgetSubPanelTopButtonQuickCreate::_get_form($defines, $additionalFormFields = NULL) should be compatible with & SugarWidgetSubPanelTopButton::_get_form($defines, $additionalFormFields = NULL, $asUrl = false) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelTopButtonQuickCreate.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelTopCreateNoteButton::display($defines, $additionalFormFields = NULL) should be compatible with SugarWidgetSubPanelTopButton::display($defines, $additionalFormFields = NULL, $nonbutton = false) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelTopCreateNoteButton.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelIcon::displayHeaderCell(&$layout_def) should be compatible with SugarWidgetField::displayHeaderCell($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelIcon.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelIcon::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelIcon.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelDetailViewLink::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php on line 137: /SuiteCRM7.0.2/index.php
PHP Warning:  Illegal string offset 'cookie_name' in /SuiteCRM7.0.2/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41: /SuiteCRM7.0.2/index.php
PHP Warning:  Illegal string offset 'cookie_name' in /SuiteCRM7.0.2/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41: /SuiteCRM7.0.2/index.php

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
