### ISSUE TITLE
Printing Task List

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2289]
#### Issue
Attempting to print the task view just shows links

#### Expected Behavior
Print shows tasks in table format

#### Actual Behavior
Printout shows only links

#### Steps to Reproduce
1. Open tasks list
2. CTRL+P to print (or press the print view button if there)
3. Check the print preview to see the problem4.

Confirmed with demo

#### Context
This makes printing the task list for meetings difficult - we need to screenshot the list then print that.

#### Your Environment
PHP 7
Suite 7.7.4

**Comment by ijdavie** [comment]
This seems like a duplicate of issue #1338
