### ISSUE TITLE
Cases fields not showing properly on different browsers

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2291]
#### Issue

Cases Modules, try to edit a record the single line text field is not showing properly
![7 7](https://cloud.githubusercontent.com/assets/3055443/18759171/297643f2-80f3-11e6-98c1-aecf3ce365b5.png)

Reported in forum by different users SuiteP theme incompatible with IE?
https://suitecrm.com/forum/suite-themes/11176-suitep-theme-incompatible-with-ie

#### Expected Behavior

Fields should show its contents properly, colors and looks should be similar, size should be similar.

#### Steps to Reproduce

Using SuiteP on desktop... Enter Cases Modules, edit a case and... 

Bug with Microsoft IE 11.103.14393.0
![cases_iexplorer11](https://cloud.githubusercontent.com/assets/3055443/18759157/18a50d06-80f3-11e6-94ee-282cd3e9e175.png)

It works almost fine with Firefox and Edge (even with lots of space, and big differences on browsers)

Left Firefox 48.0.2 / Right Microsoft Edge (Microsoft Edge 38.14393.0.0)
![cases_firefox_edge](https://cloud.githubusercontent.com/assets/3055443/18759163/1eb5bde4-80f3-11e6-974c-17c34a0dda65.png)

#### Your Environment

* SuiteCRM Version used: 7.7.4 Cases module with demo data: 
* Browser name and version:
Microsoft IE 11.103.14393.0
Firefox 48.0.2 
Microsoft Edge 38.14393.0.0

* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.17 / PHP 5.5.12
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by horus68** [comment]
Related issue:
Major issue SuiteP Theme UNUSABLE with Internet Explorer · Issue #2267  - https://github.com/salesagility/SuiteCRM/issues/2267

**Comment by ijdavie** [comment]
@horus68 this appears to be the same as issue #2267  and it has been resolved for next release.

**Comment by horus68** [comment]
Confirmed as solved in the hotfix (both browsers tested)
