### ISSUE TITLE
Email template variables aren't mapped when created from a Case

### ISSUE THREAD

**Issue by davenz** [salesagility/SuiteCRM#2294]
#### Issue
When a template-based email is sent from a SuiteCRM module (Cases in this example), inserted variables are not mapped.

#### Expected Behavior
The recipient should see the Case field data, pertaining to the Case the email was generated from, mapped to the email template's variables.

#### Actual Behavior
The recipient sees raw variables ("$acase_name" and so forth).

#### Steps to Reproduce
1) Using the Emails module I create an email template, with the "Type" value of "Email" (i.e. not a Campaign). Variables from the Cases module are inserted into the template subject and body.
2) From the Cases module, and viewing a Case, I compose an email from the Activities subpanel.
3) In the email Quick Compose window, I select the template created in step 1)
4) The email is then sent. 

#### Context
I expect this would be at least a medium priority bug affecting numerous other people (e.g. https://suitecrm.com/forum/suitecrm-7-0-discussion/2487-email-templates-not-filling-in-the-data-fields)

#### Your Environment

SuiteCRM v7.6.6, Ubuntu Server 14.04.

**Comment by ijdavie** [comment]
This is the same as issue #2292, I will close this any more information can be added issue #2292 
Thanks.
