### ISSUE TITLE
Project Task: Action "View Change Log" now available in Detail view

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2296]
#### Issue

When I turn on Changelog in vardefs of the ProjectTask module, it only shows up in edit-mode. In Detailview the Action is still missing.

#### Expected Behavior

After setting
$dictionary['ProjectTask']['audited']=true;
in vardefs I expect to see "View Change Log" in the actions menu of a project task Detailview as is the case e.g. in Project module after the analogous change to vardefs.

#### Actual Behavior

"View Change Log" only shows up as an action in Project Task editview (as a button)

#### Steps to Reproduce

1. add new vardef file to /custom/Extension/modules/ProjectTask/Ext/Verdefs containg the line $dictionary['ProjectTask']['audited']=true;
2. quick repair
3. open ProjectTask in detailview -> action "View Change log" not available
4. switch to editview -> action "View Change Log" is available (as button)

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment]
@EZS-JD This is because there is a flag in the detailviewdefs.php file for ProjectTasks called hideAudit which is set to true. if changed to false and a repair and rebuild wll allow this to display.

**Comment by EZS-JD** [comment]
much abliged!
