### ISSUE TITLE
Tasks widget won't advance >10

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2304]
#### Issue

Pressing the advance button on the the task widget does nothing, so a list with >10 tasks won't show anything from task 11 onward.
#### Expected Behavior

Task widget shows 10 tasks - pressing the advance button (single triangle pointing right) should show tasks 11 onward.
#### Actual Behavior

Nothing happens on mine.
Testing in the demo, it expands the list of tasks to full page width.
#### Steps to Reproduce

Press the right arrow on the task widget.
#### Your Environment

PHP 7
Suite 7.7.4

**Comment by shogunpol** [comment]
The issue been tested in recent version of SuiteCRM(7.7.4) and not apear,
@SpudR  can you give me some more information about issue, such as
error logs, browser and so on.

**Comment by SpudR** [comment]
Not sure where to get the logs from - advice would be welcomed!
I use Chrome for the test on my own site and the Suite CRM demo site...

**Comment by shogunpol** [comment]
@SpudR 
suitecrm.log is in Application library folder;

and for ubuntu servers(location may differ)
in terminal: cd /var/log/apache2
                  error.log

**Comment by SpudR** [comment]
Had a look at the logs and they are simply full of errors about guessing the timezone:
on Sep 26 10:58:11 2016 [171505][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone UTC. Please set date.timezone="UTC" in php.ini!
There is simply nothing else in there.
I have corrected that error, but the issue remains.
FYI - I have noticed that the first click moves the date line on to the next set, but the grid isn't updating.
Another click advances bot the date and the grid (now out of sync).

**Comment by SpudR** [comment]
Apache logs (amended for security):

PHP Notice:  Undefined index: LBL_PREVIOUS_AGENDAWEEK in /SuiteCRM7.0.2/modules/Calendar/CalendarDisplay.php on line 522: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined index: LBL_NEXT_AGENDAWEEK in /SuiteCRM7.0.2/modules/Calendar/CalendarDisplay.php on line 503: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldVarchar::displayInput(&$layout_def) should be compatible with SugarWidgetField::displayInput($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldvarchar.php on line 106: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldName::queryFilterone_of($layout_def, $rename_columns = true) should be compatible with SugarWidgetFieldVarchar::queryFilterone_of(&$layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldname.php on line 46: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldName::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldname.php on line 46: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetFieldId::queryFilterIs(&$layout_def) should be compatible with SugarWidgetReportField::queryFilterIs($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetFieldid.php on line 48: /SuiteCRM7.0.2/index.php
PHP Notice:  Trying to get property of non-object in /SuiteCRM7.0.2/include/Dashlets/Dashlet.php on line 245: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined property: JotPadDashlet::$seedBean in /SuiteCRM7.0.2/include/Dashlets/Dashlet.php on line 245: /SuiteCRM7.0.2/index.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined index: record_type_display in /SuiteCRM7.0.2/modules/Meetings/Meeting.php on line 500: /SuiteCRM7.0.2/vcal_server.php
PHP Notice:  Undefined property: Task::$rel_users_table in /SuiteCRM7.0.2/modules/Calendar/CalendarActivity.php on line 188: /SuiteCRM7.0.2/vcal_server.php
PHP Warning:  Declaration of SugarFieldText::getDetailViewSmarty($parentFieldArray, &$vardef, $displayParams, $tabindex) should be compatible with SugarFieldBase::getDetailViewSmarty($parentFieldArray, $vardef, $displayParams, $tabindex) in /SuiteCRM7.0.2/include/SugarFields/Fields/Text/SugarFieldText.php on line 85: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of & SugarWidgetSubPanelTopButtonQuickCreate::_get_form($defines, $additionalFormFields = NULL) should be compatible with & SugarWidgetSubPanelTopButton::_get_form($defines, $additionalFormFields = NULL, $asUrl = false) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelTopButtonQuickCreate.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelTopCreateNoteButton::display($defines, $additionalFormFields = NULL) should be compatible with SugarWidgetSubPanelTopButton::display($defines, $additionalFormFields = NULL, $nonbutton = false) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelTopCreateNoteButton.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelIcon::displayHeaderCell(&$layout_def) should be compatible with SugarWidgetField::displayHeaderCell($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelIcon.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelIcon::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelIcon.php on line 43: /SuiteCRM7.0.2/index.php
PHP Warning:  Declaration of SugarWidgetSubPanelDetailViewLink::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /SuiteCRM7.0.2/include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php on line 137: /SuiteCRM7.0.2/index.php
PHP Warning:  Illegal string offset 'cookie_name' in /SuiteCRM7.0.2/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41: /SuiteCRM7.0.2/index.php
PHP Warning:  Illegal string offset 'cookie_name' in /SuiteCRM7.0.2/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41: /SuiteCRM7.0.2/index.php

**Comment by shogunpol** [comment]
@SpudR  ,When you click on the button is the web browser console log says anything?

**Comment by SpudR** [comment]
It says this:
yui: NOT loaded: skin-sam-widget
sugar_grp1_yui.js?v=06FDALEwILS9V-Bb76GmMQ:2 yui: NOT loaded: skin-sam-overlay

**Comment by shogunpol** [comment]
@SpudR , one more question, in what types of web browsers you test this issue, and what is happen with other dashlets, or just this one is an issue?
thanks for your help.

**Comment by sieberta** [comment]
@SpudR & @shogunpol I have the same problem since upgrade to 7.7.4.  Suite R & Suite 7 theme.  SuiteP theme works fine (if the dashlet fix is applied).  I have tested on Chrome & Firefox.  I've particularly noticed it on the Projects dashlet, but I believe all dashlets are affected.

I've seen the behavior vary over time, without any coding changes.  One day they will work, the next day when you 'next' the dashlet, the entire dashboard loads where that dashlet was (very strange), and then another day nothing happens at all.  Console of browser doesn't show anything of use.

In my log file I have a bunch of PHP Warning: Declaration of SugarWidgetFieldDateTime::displayInput(&$layout_def) should be compatible with SugarWidgetField::displayInput($layout_def) in ../include/generic/SugarWidgets/SugarWidgetFielddatetime.php on line 817

**Comment by sieberta** [comment]
Ah, finally something helpful from the console...

MySugar.js?v=zzi7BvfwbgtSKBpbqwnz7A:53 Uncaught TypeError: Cannot read property 'getAttribute' of undefinedfillInDashlet @ MySugar.js?v=zzi7BvfwbgtSKBpbqwnz7A:53handleTransactionResponse @ sugar_grp1_yui.js?v=zzi7BvfwbgtSKBpbqwnz7A:55(anonymous function) @ sugar_grp1_yui.js?v=zzi7BvfwbgtSKBpbqwnz7A:55

**Comment by SpudR** [comment]
Broken in Edge/Chrome/Firefox for me...

**Comment by sieberta** [comment]
Related to #2263 & #2479.

Would love a fix for this!  Problem still exists (in some way shape or form) in 7.7.6...

sieberta

**Comment by samus-aran** [comment]
This should be resolved in the 7.7.7 release as completed by this PR
https://github.com/salesagility/SuiteCRM/pull/2548

Feel free to re-open an issue if this has not resolved this particular issue.
