### ISSUE TITLE
DetailView of OAuthKeys throughs an exception

### ISSUE THREAD

**Issue by bickart** [salesagility/SuiteCRM#2308]
#### Issue

After you have added an OAuthKeys, the DetailView throws an error.
( ! ) Fatal error: Cannot use object of type OAuthToken as array in SuiteCRM-7.7.4/modules/OAuthTokens/OAuthToken.php on line 305
#### Expected Behavior

The subpanel of related keys appears
#### Actual Behavior

( ! ) Fatal error: Cannot use object of type OAuthToken as array in SuiteCRM-7.7.4/modules/OAuthTokens/OAuthToken.php on line 305
#### Possible Fix

Update  SuiteCRM-7.7.4/modules/OAuthTokens/OAuthToken.php and replace the array structure with a object structure. Instead of 

function displayDateFromTs($focus, $field, $value, $view='ListView')
{
    $field = strtoupper($field);
    if(!isset($focus[$field])) return '';
    global $timedate;
    return $timedate->asUser($timedate->fromTimestamp($focus[$field]));
}

it should be

function displayDateFromTs($focus, $field, $value, $view='ListView')
{
    $field = strtoupper($field);
    if(!isset($focus->$field)) return '';
    global $timedate;
    return $timedate->asUser($timedate->fromTimestamp($focus->$field));
}
#### Steps to Reproduce

1. Login to SuiteCRM
2. Goto Admin
3. Select OAuth Keys
4. Create a new Key
5. View the key
#### Context

Trying to provide OAuth login capabilities to a 3rd party application
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04):

**Comment by chris001** [comment]
@bickart 
I tried this on 7.7.4 running on PHP 5.5, Firefox 50, MySQL 5.5, CentOS 6, and was not able to reproduce the crash.
Could it be a new stricter rule with PHP 7?

**Comment by bickart** [comment]
I used 5.6.25

Thanks,

Jeff Bickart
jeff.bickart@gmail.com

**Comment by shogunpol** [comment]
I tested this issue on recent version of SuiteCRM(7.7.4) and not appear.
@bickart may i ask about more details about this issue, for example:
version of browser, PHP, SQL, and other information what you can provide.
Thanks for raise this issue.

**Comment by bickart** [comment]
Latest version of Chrome
PHP 5.6.25
MariaDB 10.1.16


I’ll share a video of the issue


Thanks,

Jeff Bickart
@bickart
jeff.bickart@gmail.com
M: 703.303.4511

**Comment by shogunpol** [comment]
@bickart  ,thanks it will be really helpful to see video.

**Comment by bickart** [comment]
Please find the a .mp4 video attached. If you are unable to see the .mp4 I can load onto youtube





Thanks,

Jeff Bickart
@bickart
jeff.bickart@gmail.com
M: 703.303.4511

**Comment by bickart** [comment]
I emailed a video (.mp4) to you. If you were unable to view it or didn’t receive it, please let me know and I’ll load it onto YouTube for you.



Thanks,

Jeff Bickart
@bickart
jeff.bickart@gmail.com
M: 703.303.4511

**Comment by shogunpol** [comment]
Jeff, i still do not see any video in my mailbox.

**Comment by ijdavie** [comment]
@bickart is it possible you can supply this video to @shogunpol so we can proceed with this ? 
Thanks

**Comment by bickart** [comment]
I have posted the video at https://youtu.be/RpDZD4ICFLQ <https://youtu.be/RpDZD4ICFLQ> so that you can all view it.


Thanks,

Jeff Bickart
@bickart
jeff.bickart@gmail.com
M: 703.303.4511

**Comment by shogunpol** [comment]
The issue has been retested after provided additional info,
We labeled it as a Bug
@bickart , Thanks for additional info.

**Comment by DerekBuntin** [comment]
I experienced this very issue today:

Version 7.9.6
Sugar Version 6.5.25 (Build 344)
PHP Version: 7.0x

- Created oAuth 
- View the Keys

Is the downloadable version been updated with this fix as yet?

**Comment by it7steve** [comment]
We have the same problem with 

Version 7.9.4
Sugar Version 6.5.24 (Build 509)
PHP 5.6.32

Does anyone have a solution / workaround ?

**Comment by benoitrambaud** [comment]
**Working patch for SuiteCRM v7.10 (should works with previous version)** 
```
file : /html/modules/OAuthTokens
line : 302
```

change `function displayDateFromTs` code to : 

```
function displayDateFromTs($focus, $field, $value, $view='ListView')
{    
    $field = strtoupper($field);
    if(!isset($focus->$field)) return '';
    global $timedate;
    return $timedate->asUser($timedate->fromTimestamp($focus->$field));
}
```

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.1. After creating a private key, I am able to view the detail view of a record. please re-raise or Get in touch if you are still having this issue
