### ISSUE TITLE
Can't import email message to 2 or more different (modules) records

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2319]
#### Issue

I tried many times to import emial message to 2 or more records but i got this message.

![status](https://cloud.githubusercontent.com/assets/5773777/18835317/cd0f7ee8-83fa-11e6-90d7-5811481dab45.png)

For me is not good news. For example what if i want import email into project, case and opportunity ? Is possible do this ? it is not :(
#### Expected Behavior

I can import email anywhere i want :)
#### Steps to Reproduce

1. Email module (menu)
2. List of emails
3. Import to 2 or more modules/records
#### Your Environment

- SuiteCRM Version used: 7.7.4 
- Browser name and version : Chrome 53.x m 32 bit
- Environment name and version : 5.6 PHP & MySQL
- Operating System and version: Hosting, Linux

**Comment by shogunpol** [comment]
@Mausino , if you will be so kind to give me more details about the issue, im just not sure how to replicate an issue. So if you can extend your steps to reproduce to detail as possible.

**Comment by Mausino** [comment]
@shogunpol @ijdavie 

here is video from official demo of SuiteCRM where i tried one of our info mail addresses http://screencast.com/t/ir0qjeOR  (sorry on end of video is service temporary not available because demo was reboot to new instalation on demo page)

As you can see, one emial i can't import into more modules (records), first import is fine but on second time i got this situation:

A. The import button doesn't react on click (nothing happend as you can see on video)
    or
B. This issue ( i got only on my company version of SuiteCRM 7.7.4)
![status](https://cloud.githubusercontent.com/assets/5773777/18877144/8b33d15e-84cc-11e6-821e-c0a1742e4ce9.png)

**Comment by shogunpol** [comment]
@Mausino after additional information, i been able to replicate the issue.
We labelled this issue as a bug.
Thanks for your contribution.

**Comment by Mausino** [comment]
Some update here? it helps us so much to manage mail communication via SuiteCRM

**Comment by Dillon-Brown** [comment]
Update: Superseded by issue #3637 . This should have been labelled as a suggestion and not a bug.
