### ISSUE TITLE
SuiteP - Emails buttons have old style

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2328]
#### Issue

All buttons in pop up window in email module have old style like here:

![book](https://cloud.githubusercontent.com/assets/5773777/18877841/df53ecd6-84ce-11e6-904f-05463f3c4c4e.png)
#### Steps to Reproduce

1. Email Listview
2. Compose email
3. Warning message / To: (button/email address book)
#### Your Environment

- SuiteCRM Version used: Official demo of SuiteCRM 7.7.4

**Comment by horus68** [comment]
Confirmed in Hotfix branch too
Testes with Firefox and Chrome

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear,
We assign this issue as a bug.
@horus68 , thanks for additional informations.
@Mausino , thanks for raise this issue.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
