### ISSUE TITLE
Studio - Missing icons when deleting items

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#233]
When I want to delete items in Studio (any module - EditView, DetailView etc) it can be done when using theme Suite7 but it cannot be done using theme SuiteR.

Reason: The icons (and href) for deleting do not exist in SuiteR but do exist in Suite7 - in SuiteR they are just words (no link).

See forum topic: https://suitecrm.com/forum/suite-themes/4732-deleting-items-in-studio-e-g-editview-works-in-theme-suite7-but-not-in-theme-suite-r

**Comment by willrennie** [comment]
Not an issue as if the user drags to the delete text/area the item will be removed. New icon set will be implemented in future releases to fully address this, as adding in old icons is not a solution.

**Comment by pgorod** [comment]
@willrennie this is not working in SuiteCRM 7.6.4 with SuiteR. I must say, I didn't get a chance to test with Suite7, so I don't know if the problem is theme-related.

But dragging onto the "Delete" text doesn't do anything, so no fields can be removed.
