### ISSUE TITLE
Deploying custom module in module builder gives js error and halts

### ISSUE THREAD

**Issue by omidtak** [salesagility/SuiteCRM#2330]
#### Issue

None of the buttons on the Module Builder package work. 

I have couple of custom modules and I just added a field to one of them. The field saved and layout saved but when I try to deploy the package nothing happens. I also tried clicking on Publish or Export but nothing happens. 

When I looked at the javascript console in chrome and firefox I have the following errors:

Uncaught TypeError: Cannot read property 'value' of undefined
sugar_grp1.js?v=7xMBf5oTWFk7G7AgyxKIrw:228 
validate_form	@	sugar_grp1.js?v=7xMBf5oTWFk7G7AgyxKIrw:228
check_form	@	sugar_grp1.js?v=7xMBf5oTWFk7G7AgyxKIrw:160
packageDeploy	@	/sugar/modules/ModuleBuilder/javascript/ModuleBuilder.js?v=7xMBf5oTWFk7G7AgyxKIrw:955
onclick	@	VM198 index.php?module=ModuleBuilder&action=index&type=mb:1

#### Possible Fix
I read everywhere that the permission on folders should be correct which I double checked and they are all correct

#### Steps to Reproduce
1. Go to module builder
2. Make a small change to already existing custom module
3. Save the change
4. Deploy the package

#### Context
Cannot create or modify any custom module. This is a high priority for us because custom modules cannot be modified

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version: Chrome Version 53.0.2785.116 m
* Environment name and version: PHP Version 5.6.26
* Operating System and version: CENTOS 6.8 x86_64

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM and it not appear,
@omidtak , may i as you about to give us some additional information to help us replicate this issue, for example: version of SQL you use, what exactly permissions are set, also is this fresh or updated instance of SuiteCRM.
Thanks for your contribution.

**Comment by omidtak** [comment]
It's MySql version: 6.5.33 and I upgraded it from SugarCRM V6.5
**Permission:**
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php
Thank you,

**Comment by shogunpol** [comment]
@omidtak , we are just realise new version of SuiteCRm(7.7.5), can you check is new version solved your issue.

**Comment by hardikpanseriya** [comment]
Please download file named sugar_grp1.js(cache/include/javascript) from SuiteCRM-7.7.5 live instance.
Please replace the downloaded file named sugar_grp1.js(cache/include/javascript) into Suite774.

Thanks.

**Comment by omidtak** [comment]
That fixed the deploy problem, thank you.

Now after deploy I get the following error on all my custom modules:
Fatal error: Call to undefined method Fatal error: Call to undefined method psale_Commission_sugar::psale_Commission_sugar() in /sugar/modules/psale_Commission/psale_Commission.php on line 44

here is the content of psale_Commission.php
require_once('modules/psale_Commission/psale_Commission_sugar.php');
class psale_Commission extends psale_Commission_sugar {
	
	function psale_Commission(){	
		parent::psale_Commission_sugar();
	}
	
}
?>

and here is the content of psale_Commission_sugar.php located in the same folder

class psale_Commission_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'psale_Commission';
	var $object_name = 'psale_Commission';
	var $table_name = 'psale_commission';
	var $importable = false;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO

	var $id;
	var $name;
	var $date_entered;
	var $date_modified;
	var $modified_user_id;
	var $modified_by_name;
	var $created_by;
	var $created_by_name;
	var $description;
	var $deleted;
	var $securitygroup;
	var $securitygroup_display;
	var $created_by_link;
	var $modified_user_link;
	var $assigned_user_id;
	var $assigned_user_name;
	var $assigned_user_link;
	var $SecurityGroups;
	var $installed;
	var $commission_paid;
	var $system;
	var $kinetico_points;
	var $sales_order_date;
	var $invoice_date;
	var $invoice_number;
	var $invoice_paid;
	var $install_date;
	var $work_order_number;
	var $commission_percent;
	var $sales_amount_before_tax;
	var $currency_id;
	var $commission_paid_date;
	var $sale_type;
	var $customer_number;
	var $hst_paid_on_commission;
	var $bonus;
	var $commission_amount;
	var $cost_of_sale;
	var $discount;
	var $list_price;
	var $approved_to_pay;
	var $waiver_signed;
	
	function __construct(){
		parent::__construct();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
	}
		
}

**Comment by omidtak** [comment]
I found the solution [here](https://suitecrm.com/forum/installation-upgrade-help/7209-error-on-all-custom-modules-after-7-4-3-upgrade): https://suitecrm.com/forum/installation-upgrade-help/7209-error-on-all-custom-modules-after-7-4-3-upgrade
and that fixed it.
Thank you,
