### ISSUE TITLE
Parameter conditions on reports are not updated

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#2337]
#### Issue

On a report based on module quotes I defined a condition on the field Account as parameter.
If I click on the Update button the Account value is not updated, while it is correctly handled if the field is filled by the account search window.
#### Steps to Reproduce

1. Define a report on the quotes modules with the account field defined as a parameter;
2. On the Value text box enter the name of an existing account;
3. Click on the Update button.
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.1

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.8), and not appear, 
@stenfalp , can you confirm, if yes please close an issue.

**Comment by stenfalp** [comment]
Hi @shogunpol I've just tested it with 7.7.8 and the problem is still present: the update button works OK if the parameter is selected from the popup window and not if entered directly.

Regards,
Stenio

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.

**Comment by stenfalp** [comment]
The bug is still present in version 7.9.5. Here are the steps to reproduce it:

1) Create an account say "Account1";
2) Create a quote for Account1;
3) Click on create report on the report module;
4) Fill the Name field with "Test";
5) Fill "Report Modules" with "Quotes";
6) Drag the field "Quote number" on the right panel;
7) Click on "Conditions";
8) Drag the field "Account" on the right panel;
9) Click on parameter check box;
10) Save;
11) Fill the value field with the string Account1 and click update;

I expect a row to be shown with the specified account but nothing appens.

**Comment by Dillon-Brown** [comment]
Closing this in favour of #4303
