### ISSUE TITLE
SuiteP on mobile - Save&Continue or Pagination button is pushing others on one left site

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2338]
#### Issue

Here is video: http://screencast.com/t/coXJZMFodga 

For Mobile the Save&Continue button in Editview or the Paggination waste too much place

I think it should be the buttons like edit, cancel, delete etc on one row and  Pagination with save&continue button can go under them.. it saves to much place for mobiles.

Look on examples:
![oppor](https://cloud.githubusercontent.com/assets/5773777/18948011/a9a28e5e-8635-11e6-8451-7a0bbc30b2a4.png)

![opp2](https://cloud.githubusercontent.com/assets/5773777/18948022/b506b77a-8635-11e6-9aec-fc81cbe85744.png)

![meet](https://cloud.githubusercontent.com/assets/5773777/18948026/bb54beba-8635-11e6-8469-2161ec04e57c.png)

![meet2](https://cloud.githubusercontent.com/assets/5773777/18948068/eb6d029c-8635-11e6-978c-e45e237c535b.png)

#### Your Environment

* SuiteCRM Version used: 7.7.5 Official demo
* Browser name and version: Chrome 53.x m 32 bit version
* Operating System and version: Win10 home

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM, and it appear
We labelled this issue as a bug,
@Mausino ,thanks for raise this issue
