### ISSUE TITLE
Import field mappings should be able to be saved before import begins

### ISSUE THREAD

**Issue by KOM2015** [salesagility/SuiteCRM#234]
I'm converting from Salesforce.  We're currently going through the painful process of sanitizing our data so it can be imported into Suite.  When you go to import your data, you must do the field mappings first before you can import.  If there is a problem with the import and you want to rollback, it takes forever.  The last time I had to do it, it took about 90 minutes to rollback an Accounts import of ~28,000 accounts.  Since my install is virtual, I started making snapshots so that I could rollback in a matter of seconds, not hours.  The problem is that the field mapping doesn't save until after you try the import.  Otherwise, I would do the field mappings, save them, then do the import and if I had to rollback, my saved field mappings would already be done and ready for the next import attempt.  Now when I rollback, I have to do all the mappings again.

**Comment by vincentamari** [comment]
Why not do an import with just one record so you can save your mappings?

**Comment by KOM2015** [comment]
That's a decent workaround, thanks, but a separate Save button on the mappings page would be nice too.

**Comment by willrennie** [comment]
No planned changes to how the importer works as yet, suitable workaround given.
