### ISSUE TITLE
Search box issue in header

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2343]
#### Issue

Searching something on search bar, the box appear under the notification side.
#### Steps to Reproduce

1. Set "display full name" in Admin panel.
2. Search something in search bar.
#### Context

low
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.1
- Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
- Operating System and version (e.g Ubuntu 16.04): 
- Theme: Suite 7

![issue](https://cloud.githubusercontent.com/assets/22373035/18953254/2e934732-8656-11e6-8b27-f3c377c65750.png)

**Comment by dursuntosun** [comment]
It is ok, but a little bit bigger.

![issue1](https://cloud.githubusercontent.com/assets/22373035/18982585/ee2f7810-86ef-11e6-98e2-341d3efa5f74.png)
![issue2](https://cloud.githubusercontent.com/assets/22373035/18982587/f0ea1dbc-86ef-11e6-8f63-69bcba53e2f2.png)

**Comment by jack7anderson7** [comment]
This is no longer an issue in our latest 7.8 version if you find this is still an issue I suggest upgrading to that
