### ISSUE TITLE
Inline edit of field Assigned to does not show suggestion items

### ISSUE THREAD

**Issue by peter-haspra** [salesagility/SuiteCRM#2344]
#### Issue

Inline edit of an Assigned to field in list view works correctly for the first time. When i try to inline edit any other Assigned to field on the same page (without refreshing), suggestion items do not show.
#### Steps to Reproduce
1. Open list view of any module
2. Double click on Assigned to field in any row to inline edit selected record.
3. When typing, suggestion items show up.
4. Save row by clicking on tick icon.
5. Double click on Assigned to once again, this time suggestions do not show after typing.
#### Your environment

Browser: Chrome  53.0.2785.116 m (64-bit), Firefox 49.0.1
SuiteCRM Version 7.7.5
Sugar Version 6.5.24 (Build 509)
Themes: Suite7 and SuiteR

**Comment by shogunpol** [comment]
@peter-haspra , an issue has been tested on recent version of SuiteCRM(7.7.9), and not appear, can you confirm is this not issue any more?

**Comment by peter-haspra** [comment]
Trying on http://demo.suiteondemand.com, but the issue still persists. I am going to try it on fresh installation of SuiteCRM 7.7.9.

**Comment by shogunpol** [comment]
@peter-haspra , please let me know about testing progress, and can you also try on SuiteP theme?

**Comment by peter-haspra** [comment]
I recorded the video of testing on SuiteCRM demo: https://dl.dropboxusercontent.com/u/49522798/Rec%2001-04-17.avi

After testing on fresh installation of SuiteCRM 7.7.9, i will post my results.
