### ISSUE TITLE
Campaign view status page color text issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2346]
#### Issue

In campaign status page, explanation of the color text are not shown. They are white color, so does not shown.
#### Steps to Reproduce

1. Open Campaign status page
2. Look at the graph color explanation, there is no text. Color of the text is white color.
#### Context

low
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.1
- Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
- Operating System and version (e.g Ubuntu 16.04): 
- Theme: Suite 7

![issue](https://cloud.githubusercontent.com/assets/22373035/18954983/04cc99b4-865e-11e6-8c8f-0644d622cd80.png)

**Comment by shogunpol** [comment]
The issue has been tested in recent version of SuiteCRM(7.7.5), and it appers,
We labelled this issue as a bug.
@dursuntosun , thanks for raise this issue.

**Comment by dursuntosun** [comment]
Why dont merge it to new version?
