### ISSUE TITLE
AOR - Custom fields query fails

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#235]
AOR report returns 0 results if a user adds a custom field as a Condition on the Report.

Example:

Query Failed: SELECT `contacts`.id AS 'contacts_id', `contacts:accounts`.id AS 'contacts:accounts_id', `contacts:accounts`.name 
AS Name0', `contacts`.first_name AS 'First_Name1', `contacts`.last_name AS 'Last_Name2' FROM `contacts` LEFT JOIN accounts_contacts `contacts|contacts:accounts` 
ON `contacts`.id=`contacts|contacts:accounts`.contact_id AND `contacts|contacts:accounts`.deleted=0

LEFT JOIN accounts `contacts:accounts` ON `contacts:accounts`.id=`contacts|contacts:accounts`.account_id AND `contacts:accounts`.deleted=0

Thu May  7 10:45:42 2015 [18099][1][FATAL]  Query Failed: SELECT `contacts`.id AS 'contacts_id', `contacts:accounts`.id AS 'contacts:accounts_id', `contacts:accounts`.name 
AS 'Name0', `contacts`.first_name AS 'First_Name1', `contacts`.last_name AS 'Last_Name2' FROM `contacts` LEFT JOIN accounts_contacts `contacts|contacts:accounts` 
ON `contacts`.id=`contacts|contacts:accounts`.contact_id AND `contacts|contacts:accounts`.deleted=0

LEFT JOIN `accounts_cstm` `contacts:accounts_cstm` ON accounts.id = `contacts:accounts_cstm`.id_c  WHERE `contacts:accounts_cstm`.industryimported_c = 'Chemicals' AND contacts.deleted = 0 ) as n: 
MySQL error 1054: Unknown column 'accounts.id' in 'on clause'

LEFT JOIN accounts `contacts:accounts` ON `contacts:accounts`.id=`contacts|contacts:accounts`.account_id AND `contacts:accounts`.deleted=0

LEFT JOIN `accounts_cstm` `contacts:accounts_cstm` ON accounts.id = `contacts:accounts_cstm`.id_c  WHERE `contacts:accounts_cstm`.industryimported_c = 'Chemicals' AND contacts.deleted = 0  LIMIT 0,20:
MySQL error 1054: Unknown column 'accounts.id' in 'on clause'

LEFT JOIN `accounts_cstm` `contacts:accounts_cstm` ON accounts.id = `contacts:accounts_cstm`.id_c  WHERE `contacts:accounts_cstm`.industryimported_c = 'Chemicals' AND contacts.deleted = 0 : 
MySQL error 1054: Unknown column 'accounts.id' in 'on clause'

**Comment by vladbar** [comment]
Will, can you also close this issue. I've tested it many times and never been able to replicate it. In my latest test I included exactly the same fields: contacts.id , contacts:accounts.id , contacts:accounts.name , contacts.first_name , contacts.last_name and added a custom field as a condition. It runs without any problems and produces the correct result. Log is also clean .

**Comment by vladbar** [comment]
I also added a custom field from the Accounts. It works fine: there was a custom field ABCD For MC in the Accounts, so I added it to the report and everything displays fine. Log has no errors.

**Comment by websolprov** [comment]
How do you filter the master/detail left join so you ONLY get master records WITHOUT a related record?
