### ISSUE TITLE
Calendar 7.7 Time Slots can not be disabled in Shared Week View

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#2352]
#### Issue
In the Calendar Settings unticking "Display time slots in Day and Week views:" works for Day & Week but not shared week

#### Expected Behaviour
Time Slots should not be displayed for Shared Week

#### Context
The shared calendars can be very long
Removing timeslot would make the week view 

#### Your Environment
* SuiteCRM Version used: 7.7.5

**Comment by shogunpol** [comment]
Is a duplication of bug #2088
