### ISSUE TITLE
Google Autocomplete

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#2360]
#### Issue

Installed 3rd party free open source module, "Google Autocomplete", from the official list of SugarCRM CE free open source modules.   https://github.com/sugarcrm/SugarCE-Add-ons
This very simple module uses google web services and jQuery to auto complete street addresses inside SugarCRM CE 6.5.x (the engine under SuiteCRM). for Lead, Contact and Account Edit Views.
#### Expected Behavior

Creating an new Lead, (or Contact, Account) or Editing and existing Lead, should show the Edit Lead page, and perform the auto complete on the fields for the Address.
#### Actual Behavior

Blank screen on the Edit Lead page.  Blank as well on Edit Contact and Edit Account.
![image](https://cloud.githubusercontent.com/assets/259416/19009431/e672afd2-8741-11e6-9499-6046239f0801.png)
#### Possible Fix

Possibly a jQuery conflict ??  Should take a closer look at possibly running SuiteCRM jQuery in noconflict mode.  Google Autocomplete uses jQuery and is designed for SugarCRM CE 6.5.x which does not (?) use jQuery so there was no conflict there.
#### Steps to Reproduce

1. Install Google Autocomplete module from https://github.com/aniesshsethh/GoogleAutocomplete with Admin / Module Loader.
2. Click Create Lead, or Create Contact, or Create Account, or Edit Lead, Edit Contact, or Edit Account.
3. You'll see a blank page in the space where you expect to see the usual Edit form.
#### Context

Medium to high.  Any and all third party module which uses jQuery, would fail to run, due to conflict with the jQuery used by SuiteCRM SuiteP theme (and possibly also Suite 7 and Suite R themes).
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Mozilla Firefox 50
- Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
- Operating System and version (e.g Ubuntu 16.04): Debian 7.

**Comment by boombata** [comment]
Hi, 

had such blanck screen with recaptcha when my suitecrm was https and recaptcha was using http, chrome/firefox was blocking the mixed content. (https://github.com/salesagility/SuiteCRM/issues/2310)

I'm not sure at all it is the same issue, but I see that google api in account creation.js is https on line 1
$.getScript("https://maps.googleapis.com.....
give a try by replacing link to http if your suite crm is not under https.

**Comment by chris001** [comment]
Update: the cause of this bug can't be https http "mixed content."
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content
Mixed content would only block a crm runnning on https from using scripts/images retrieved from http.
The crm is running on http so mixed content policy blocks do not apply.

**Comment by shogunpol** [comment]
Hi @chris001, 

When I install this plugin this does not appear to break the leads module. I do however have to entered a maps API key. This might be worth looking at the logs on the server to determine what is causing this blank page?

**Comment by chris001** [comment]
@shogunpol @ijdavie 
http://www.jjwdesign.com/faq/
> QUESTION: Do I need an API Key to use the Google Maps API V3?
> This is really a two part question. No, you do not need an API Key to use the Google Maps API V3 geocoding services. Google does limit the number of geocoding requests to 2,500 per day. Yes, Google does recommended an API key if your application generates more than 25,000 map loads per day, but I don’t recommend using an API key unless absolutely necessary. A Google Maps business account is also available for large businesses.

Are you saying the Autocomplete module code is crashing without a google maps API key from the `jjwg_maps` module?  It should be working fine according to the author (see above).  But this module is `Google Autocomplete`, not `jjwg_maps`
Anyway, the jjwg module has a bug, the form is limiting the API key field to 32 characters, it should be at least 39 characters, this is the new length of the Google Maps Javascript API key..

**Comment by ijdavie** [comment]
@chris001, When we test the leads module without this plugin install no errors appear in the console, however after it is installed the error,

js?v=3.exp&sensor=false&libraries=places&callback=initialize&_=1476697783340:37 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

It appears that the autocomplete plugin uses the Maps Javascript API which requires a key to work, this key will not be used from the jjwg maps section. 

https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by chris001** [comment]
@ijdavie  I'm in communication with the Google Autocomplete SugarCRM 6.5 CE module developer.  We have determined some additional information.  Will update this issue until either issue is resolved or need more information from your side.

**Comment by shogunpol** [comment]
Response - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
