### ISSUE TITLE
Nested scroll bars

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#2363]
#### Issue

Nested horizontal and nested vertical scroll bars are still appearing which could/should be improved upon. 
#### Expected Behavior

The user should face only either a vertical scroll bar, or a horizontal scroll bar, per page view.  Like a smart phone.  You're only ever scrolling vertically, or sometimes only horizontally in some particular views in some apps.
#### Actual Behavior

Many popups will come up and the situation occurs where the html layout inside the popup is not limiting itself to its viewport width, so horizontal scroll bars appear.  Additionally, the height of the content can often exceed viewport height, so vertical scrollbars appear on the popup.
#### Possible Fix

All popups should set their height to be unlimited, users can scroll vertically that is no problem at all.
For width, the content should wrap, rather than setting a fixed width which often exceeds viewport width. Wrapped content wraps down vertically. so that horizontal scroll bars do not appear.
#### Steps to Reproduce

1. Tap Home
2. Email 
3. Settings popup
   4.
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50
- Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
- Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by shogunpol** [comment]
This issue is related to issue #1998

**Comment by chris001** [comment]
Checked out #1998, which is marked as "resolved in next release", and updated it with additional screen shots showing this issue is improved but not resolved.

**Comment by chris001** [comment]
Also related to #286 Email module window too wide when left sidebar is open.

The theme isn't responding to the actual viewport width / browser client area width.

Suggestion: I've found a Yahoo YUI CSS component 4.5KB in size which would probably solve this non responsiveness.

https://github.com/yahoo/pure

**Comment by shogunpol** [comment]
@chris001 , i tested issue on recent version of SuiteCRM(7.7.7), and it not appear, can you confirm is not an issue any more?

**Comment by chris001** [comment]
@shogunpol 
I've checked it and although the horizontal scroll bar now gone, however I call this issue partially still unsolved.
The reason is, the popup box is fixed width, seems to be about 965px wide, and non responsive, when it should be responsive.
This popup works fine on desktop 1280px width and high end mobile 1080px width.  Yet the greatest number of mobile smart devices are 640px wide for example iphone 5s, or 768px wide, ipad 2 in portrait mode.  So you're still forced to scroll horizontally, which is UI hell.
The proper solution would be to let the items inside the popup wordwrap to fit in whatever width the popup is calculated to be, at the time the popup is requested by the user.
And to have the popup, and indeed all UI elements, respond to window-resize browser events, such as for example when the user tilts their smart device screen 90 degrees while staying on the same page, and suddenly, the viewport client width changes which triggers an event.  The theme must be responsive to this event, and so recalculate and reset all non-automatic element widths, such as this popup width, to their optimal width, less or equal to the maximum available viewport client width.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
