### ISSUE TITLE
SuiteP - Buttons on User detailview are broken

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2378]
#### Issue

The Buttons on User Detailview are pushed on one site, are not inline.

![user](https://cloud.githubusercontent.com/assets/5773777/19105930/00a0fbf6-8ae5-11e6-961b-c0709a44143c.png)
#### Expected Behavior

The buttons will inline in one row
#### Steps to Reproduce

1. Admin
2. Users
3. Detailview of any user (must set up the non grouped buttons)
#### Your Environment

- SuiteCRM Version used: 7.7.5 
- Browser name and version: 32.x m 32 bit Chrome
- Environment name and version: 5.6 MySQL & PHP
- Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
The issue has been tested in recent version SuiteCRM(7.7.5), and it appear.
We labeled this issue as a bug.
@Mausino ,thanks for raise this issue.

**Comment by staganyi** [comment]
Yes I also can confirm this on 7.7.5

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
