### ISSUE TITLE
Calendar Dashlet not usable in SuiteCRM 7.7.5

### ISSUE THREAD

**Issue by vladimirpekez** [salesagility/SuiteCRM#2385]
Calendar Dashlet in Google Chrome is almost unusable. Meetings cannot be scheduled because click on time slot before late PMs does nothing. Clicking on late PMs does produce new meeting dialogue but the time is wrong (pls see attached screenshot).
#### Expected Behavior

I should be able to click on time slot and schedule a meeting with a correct date & time.
#### Steps to Reproduce
1. Log into online demo
2. Go to Home module
3. Add Calendar dashlet if not displayed
4. Try to schedule meeting
#### Your Environment

- SuiteCRM Version used:
- Google Chrome Version 53.0.2785.101 m (64-bit)
- SuiteCRM official demo environment
- Windows 7 Enterprise 64bit Service Pack 1 OS

Screenshot: [https://postimg.org/image/bl21bmu5n/](https://postimg.org/image/bl21bmu5n/)

**Comment by milosni** [comment]
I am having the same problem with Calendar Dashlet in Chrome browser. In Firefox Calendar works fine.

SuiteCRM 7.7.5
Chrome version (53.0.2785.101)
Firefox (49.0.1)

**Comment by staganyi** [comment]
Same behavior for me. Firefox works fine, but not Chrome.

SuiteCRM 7.7.5
Chrome version (53.0.2785.143)
Firefox (47.0.1)

**Comment by nikoup** [comment]
Same to me

Mac OSX
Chrome noop
Firefox yes
