### ISSUE TITLE
MIssing module images for Index, Index Event, Locations

### ISSUE THREAD

**Issue by KOM2015** [salesagility/SuiteCRM#239]
Running 7.2 that was upgraded to 7.2.1.  The Modules list in Studio seem to be missing 3 images for Index, Index Events and Locations.  See below.

![image](https://cloud.githubusercontent.com/assets/12281215/7523639/df612918-f4ca-11e4-8b2f-f44533937890.png)

**Comment by darthtang** [comment]
Index event and index is irrelevant anyways, so i have taken these options out. I have added a nice icon to the locations option now

**Comment by darthtang** [comment]
closed
