### ISSUE TITLE
SuiteP - Pop Ups of some modules have previus theme colors

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2390]
#### Issue

The pop up windows of custom instaled or created modules have the old colors

![module_x](https://cloud.githubusercontent.com/assets/5773777/19156755/457f22c6-8be3-11e6-832b-fc9f71f2c642.png)

![docum](https://cloud.githubusercontent.com/assets/5773777/19193048/c3d23864-8ca8-11e6-8a35-ad93fc4a7e8d.png)

#### Expected Behavior

System will apply the default colors

#### Your Environment

* SuiteCRM Version used: 7.7.5
* Browser name and version: 53.x m 32 bit Chrome
* Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.5), and it not appear
So if you can give me some more additional details how to replicate the bug it will be great, screenshots, step-by-steps basically everything what may help me replicate the issue.
@Mausino  ,thanks for raise this issue

**Comment by Mausino** [comment]
@shogunpol  Hi, i tried it on official demo, but it was not succesfully. I think that is my internal bug. I am closing this issue.
