### ISSUE TITLE
Bugs Module: dropdowns "found_in_release" & "fixed_in_release" not working

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2392]
#### Issue

In the module Bugs there are two fields of type DropDown installed by default:

- found_in_release
- fixed_in_release

These two fields are not connected to dropdown lists nor is it possible to connect them to DropDown lists that I create myself.

![stamp-2](https://cloud.githubusercontent.com/assets/15463075/19189520/baf86b7e-8c98-11e6-89b4-48badcab695e.jpg)

https://suitecrm.com/forum/suitecrm-7-0-discussion/6746-module-bugs-fields-found-in-release-and-fixed-in-release-problem#39121

#### Your Environment

* SuiteCRM Version used: 7.7.4

**Comment by ijdavie** [comment]
This is due to both of these fields being editable using the Releases section in the admin panel.
