### ISSUE TITLE
Dashlet clicking next button on Dashlet currupts  home page

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#2394]
#### Issue

If you press the next button on a dashlet the home page gets corrupted

![home_before](https://cloud.githubusercontent.com/assets/3176876/19191521/be3eace2-8c9a-11e6-8dcb-7114c762c44e.png)

![home_after](https://cloud.githubusercontent.com/assets/3176876/19191565/f95f0308-8c9a-11e6-88b5-ab536b40b650.png)
#### Expected Behaviour

Dashlet should display next set of records
#### Actual Behaviour

Dashlets get duplicated on page and page layout changes - see screenshot
#### Steps to Reproduce

Use next button on dashlet that has more records than show on screen
#### Context

We are attempting to use Dashlets properly
For us it is high priority as we use dashlets to control workload
#### Your Environment
- SuiteCRM Version used: 7.7.5
- Browser name and version Latest versions of Firefox, Chrome & Opera
- Environment name and version Mysql
- Operating System and version Centos

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.5), and it not appear
@mikesolo ,can you give me more details due to not been able to replicate an issue,  what module (if custom all parameters),  and so on.
thanks for raise this issue.

**Comment by khan01** [comment]
@shogunpol I have added 3 Leads Dashlets with custom where clause in process() for each one. When i click on next button in pagination of any one, all 3 dashlets get paginated and the results are wrong. See the image for whats happening. 
![multipleleadscustomdashltes](https://cloud.githubusercontent.com/assets/582150/19327456/909e21b2-90e8-11e6-9adf-b18238fab954.png)

**Comment by shogunpol** [comment]
Related to issue #2394

**Comment by ijdavie** [comment]
@mikesolo, is the first issue seen in all themes or just SuiteR ? The second I have managed to replicate.

**Comment by mikesolo** [comment]
@ijdavie This happens on all themes

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
