### ISSUE TITLE
Campaign module dropdowns on wizard aren't showing the selected value

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#2395]
#### Issue

Campaign module dropdowns on any wizard step 1 aren't showing the selected value

#### Expected Behavior

Be able to view selected value on the dropdown

#### Actual Behavior

Value is selected but dropdown but is not showing it
![selection-02-2016-10-07](https://cloud.githubusercontent.com/assets/6874136/19205152/e051949a-8c9d-11e6-9512-3450e1e3b552.jpg)

#### Possible Fix

css files?

#### Steps to Reproduce

1. Go to campaign module
2. Click on Create Campaing
3. Click on Non-email based Campaing
4. Go to status dropdown and select Active
5. Go to Type dropdown and select Mail
6. Complete wizard values are saved correctly but never shown correctly during creation.

#### Context

This is a low priority bug IMO

#### Your Environment

* SuiteCRM Version used: 7.7.5
* Browser name and version: Chrome Version 53.0.2785.143 (64-bit)
* Environment name and version:
  * mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
  * PHP Version 5.6.26-1+deb.sury.org~xenial+1
  * Apache/2.4.18 (Ubuntu)
* Operating System and version: 
  * Distributor ID: neon
  * Description:    KDE neon User Edition 5.8
  * Release:        16.04
  * Codename:       xenial

**Comment by nikoup** [comment]
I have also the same problem. At the beging i was thinking that what chrome problem but is not.

**Comment by shogunpol** [comment]
I tested this issue on recent version SuiteCRM(7.7.5), and it not appear, 
only one circumstance when bug been replicated when is Google Chrome used(so potentially is some problem related with this browser), and windows 2008 server.
We label this issue as a Bug.
@cumanacr , thanks for raise this issue.

**Comment by shogunpol** [comment]
@cumanacr ,just i will as about additional info to : check if outbound server has a limit of sended emails.
or any other server restriction if this is possible to check
Thanks for your contribution.

**Comment by cumanacr** [comment]
I'm not having problems with the campaign itself, is just with the dropdowns during creation, in fact a coworker told me that the dropdowns are failing in general.

We are using Chrome with all our clients

**Comment by ijdavie** [comment]
This appears to be directly related to the issue #2402 there is also a fix #2367 which should fix this for you.

**Comment by cumanacr** [comment]
@ijdavie the fix in #2367 worked, thanks
