### ISSUE TITLE
Calendar To Tab Dashlet not working after refresh

### ISSUE THREAD

**Issue by nikoup** [salesagility/SuiteCRM#2396]
Calendar To Tab Dashlet not working after refresh
#### Issue

Calendar in tab dashlet not working after refresh
#### Expected Behavior

Must work
#### Steps to Reproduce

1.
2.
3.
4.
#### Context

My clients works a lot with dashlet tabs
#### Your Environment
- SuiteCRM Version used: 7.7.5
- Browser name and version: 53.0.2785.143 (64-bit)
- Environment name and version: Php 7.1
- Operating System and version: Mac OSX Sierra

![calendar_tab_suitecrm](https://cloud.githubusercontent.com/assets/22731897/19223110/2d26b236-8e70-11e6-8620-4645a3d31788.png)

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM, and it appear
We labelled this issue as a bug,
@nikoup  ,thanks for raise this issue

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
