### ISSUE TITLE
Notifications Not Working 

### ISSUE THREAD

**Issue by nikoup** [salesagility/SuiteCRM#2397]
I tried to change crm time according to server time etc. Nothing happends

#### Issue
I put check box to notify me for some call but it doesn't

#### Steps to Reproduce
1. Create a Call, set notification to be 30minutes before.
2.
3.
4.

#### Your Environment
SuiteCRM Version used: 7.7.5
Browser name and version: 53.0.2785.143 (64-bit)
Environment name and version: Php 7.1
Operating System and version: Mac OSX Sierra

**Comment by pgorod** [comment]
Hello @nikoup have you tried bringing up this issue in the forums? You should first make sure it's not just a configuration problem on your system, before bringing it up as a bug here. 

I also had trouble setting this up in my system and a forum thread helped me.

**Comment by ijdavie** [comment]
there is a fix for this #2167 which puts a fix in for this. issue was raised in #2082
