### ISSUE TITLE
Collapse Panel in Edit View not working propertly

### ISSUE THREAD

**Issue by nikoup** [salesagility/SuiteCRM#2398]
Collapse Panel "Edit View"
#### Issue

When you add in one module at studio in "Edit View" one "Panel" and click to collapse it does't work right.
#### Expected Behavior

When you click + it must open the panel you ask
#### Actual Behavior

It open all "Panels"
#### Steps to Reproduce

1.
2.
3.
4.
#### Context

Comfused in order
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version: Chrome + Firefox latest
- Environment name and version: Php 7
- Operating System and version: Mac OSX SIerra + Android + iOS + Windows 8

**Comment by shogunpol** [comment]
@nikoup , i tested issue in recent version of SuiteCRM(7.7.5), and not appear.
I need more information and real steps to reproduce, like what module, what panel and so on.
Thanks for raise this issue.

**Comment by nikoup** [comment]
Go to AOS Quotes into Studio. Create new "Panels" to "EditView" (2-3 or more). Insert into the new Panels some fields that you want to be appeard, Save +Save and apply with "Collapse" check true.

Then go to Quotes, Press Create Quote, then go to any new "Panel" that you created and click on +, it opens ALL panels and not the only the one that you have clicked on.

I made some research and i found that the javascript has one one "Panel Collapse" true-false for all "Panels" not separate code for every "Panel"

**Comment by shogunpol** [comment]
Thanks for additional information, the issue has been sucessfuly able to replicate issue, (only in IE browser, windows OS environment).
We label this issue as a bug.
@nikoup , thanks for your contribution

**Comment by Mac-Rae** [comment]
Confirmed in latest 7.10.x

**Comment by Kevconry** [comment]
Can't replicate in 7.13.1, please re-raise or get in touch if you are still having this issue
