### ISSUE TITLE
SuiteP - Global Search Subpanels and Search fields are not responsive on mobile devices

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2399]
#### Issue

Result page for global search isn't responsible for mobile devices.

![cap1](https://cloud.githubusercontent.com/assets/5773777/19224800/966b74a8-8e8d-11e6-8c11-5e5cb4696c3e.png)

![cap2](https://cloud.githubusercontent.com/assets/5773777/19224803/a166bdea-8e8d-11e6-983b-64c7e687d91a.png)
#### Expected Behavior

The subpanels will responsible also for tablet & mobile view
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version: Chrome 53.x m 32 bit
- Environment name and version:  5.6 PPH & MySQL version
- Operating System and version: Win 10 home

**Comment by pgorod** [comment]
@Mausino you still need another fix in your title : - )

I think you mean "are not _responsive_ on mobile devices"

**Comment by Mausino** [comment]
@pgorod i fixed the name title as you suggested :)

**Comment by shogunpol** [comment]
@Mausino , an issue has been tested on recent version of SuiteCRM(7.7.9), and not appear, can you confirm it. If yes please close an issue.

**Comment by Mausino** [comment]
@shogunpol I will uprade on SuiteCRM 7.7.9 at Monday. I will respond on this ticket after monday, and if will everything ok, i close this issue :)

**Comment by Mausino** [comment]
Hi, i investigated, and i found that on offical version SuiteCRM 7.7.9 is working, but on my upraded version 7.7.9 not.. we will search for issue on our instance or SuiteCRM

I am closing the issue :) @shogunpol  thank you for you help 👍
