### ISSUE TITLE
Create Project Template - select Project Manager popup (Version 7.2.1)

### ISSUE THREAD

**Issue by UrvishSSPL** [salesagility/SuiteCRM#240]
I am getting below error while selecting Project Manager at Create Project Template Page.

The URL generated in address bar of **popup**
index.php?module=&action=Popup&mode=single&create=true&field_to_name[]=name
```
Warning: require_once(modules/Home/metadata/popupdefs.php): failed to open stream: No such file or directory in /home/someuser/officesuite/include/Popups/Popup_picker.php on line 68
Call Stack
#	Time	Memory	Function	Location
1	0.0001	128592	{main}( )	../index.php:0
2	0.2162	4168112	SugarApplication->execute( )	../index.php:49
3	0.2880	5378840	SugarController->execute( )	../SugarApplication.php:92
4	0.2884	5379864	SugarController->processView( )	../SugarController.php:295
5	0.2939	5462452	SugarView->process( )	../SugarController.php:348
6	0.3411	5590992	ViewPopup->display( )	../SugarView.php:143
7	0.3428	5609332	Popup_Picker->Popup_Picker( )	../view.popup.php:203
```
```
Fatal error: require_once(): Failed opening required 'modules/Home/metadata/popupdefs.php' (include_path='/home/someuser/officesuite/include/HTMLPurifier/standalone:/home/someuser/officesuite/include/..:.:/usr/share/php:/usr/share/pear') in /home/someuser/officesuite/include/Popups/Popup_picker.php on line 68
Call Stack
#	Time	Memory	Function	Location
1	0.0001	128592	{main}( )	../index.php:0
2	0.1275	4072020	SugarApplication->execute( )	../index.php:49
3	0.1612	5550648	SugarController->execute( )	../SugarApplication.php:92
4	0.1616	5551668	SugarController->processView( )	../SugarController.php:295
5	0.1698	5633512	SugarView->process( )	../SugarController.php:348
6	0.1761	5660060	ViewPopup->display( )	../SugarView.php:143
7	0.1778	5673676	Popup_Picker->Popup_Picker( )	../view.popup.php:203
```

**Comment by UrvishSSPL** [comment]
Any updates please

**Comment by UrvishSSPL** [comment]
Anybody?

**Comment by recci** [comment]
Try doing a quick repair and rebuild from the admin panel. You may also want to check your file permissions are correct.  For help like this I would search the SuiteCRM Support forums.

**Comment by UrvishSSPL** [comment]
Thank you. I will check this.

**Comment by UrvishSSPL** [comment]
Hi, Quick repair and rebuild did not solved my problem. I am still getting the same error and the specified file modules/Home/metadata/popupdefs.php does not exists.

**Comment by pribeiro42** [comment]
The problem is that the module parameter of the popup URL is not being populated..  the generated url should be: index.php?module=**Users**&action=Popup&mode=single&create=true&field_to_name[]=name

Don't know where this is failling.. because the AM\_ProjectTemplates module doesn't include custom code in this field...

**Comment by UrvishSSPL** [comment]
Is there any way we can fix this? manually?

**Comment by pribeiro42** [comment]
I solved it the following way:
  *  Edit the file **\<suitecrm\_root\>**/modules/AM\_ProjectTemplates/vardefs.php and around line 150 change the line that reads 'module' => '' to 'module' => 'Users' ;
  *  Run Quick repair and rebuild ;
  *  Be sure to get rid of the cached files (clean the **\<suitecrm\_root\>**/cache/modules and **\<suitecrm\_root\>**/cache/smarty/templates_c dirs)

**Comment by UrvishSSPL** [comment]
It worked for me too.

Thank you.
