### ISSUE TITLE
SuiteP- Mass update view - dropdowns show incorect with Chrome 53+version 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2402]
#### Issue

Mass update view has still old issue #1930 with browser Chrome 53+ version.  
videoscreen: http://screencast.com/t/Jmb0OTt9E2T 

![mass_update](https://cloud.githubusercontent.com/assets/5773777/19267078/0bcf4268-8fad-11e6-8b6c-c4f3404bcc76.png)

#### Your Environment

* SuiteCRM Version used: 7.7.5 Official Demo
* Browser name and version: Chrome 53.x m 32 bit
* Operating System and version: Win 10 Home

**Comment by ijdavie** [comment]
@Mausino There is a pull request which should address this. #2367

**Comment by Mausino** [comment]
@ijdavie  thanks  👍
