### ISSUE TITLE
SuiteP - 2 small css issues

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2406]
#### Issue

1. Inbound icon on sidebar has old design (but the inbound email on admin setting interface has new one)
2. Add chart button in editview in report record has old design

![reports](https://cloud.githubusercontent.com/assets/5773777/19283796/9a821e7c-8ff3-11e6-9872-b6cdf29db452.png)
#### Your Environment

- SuiteCRM Version used: SuiteCRM 7.7.5

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.5), and it appear
We labelled this issue as a bug,
@Mausino ,thanks for raise this issue

**Comment by Mausino** [comment]
@ijdavie pls could you put label here?
