### ISSUE TITLE
Email Templates (Maximum Lines)

### ISSUE THREAD

**Issue by nikoup** [salesagility/SuiteCRM#2407]
I'm importing an html template that i made (around 3000lines of code.
And it is not working.

#### Issue
Html template not works

#### Expected Behavior
After importing to be working

#### Actual Behavior
Shows error

#### Possible Fix
Change Maximum Lines on Email Template

#### Context
Auto email order

#### Your Environment
* SuiteCRM Version used: 7.7.5
* Browser name and version: Everyone
* Environment name and version : 7.1
* Operating System and version : MAC OSX Sierra
![2016-10-12 12 57 08](https://cloud.githubusercontent.com/assets/22731897/19290168/184116f6-9017-11e6-846d-2f1e58b5ab02.png)

**Comment by ijdavie** [comment]
@nikoup this is a limitation with mysql and the field type which is used for this field, it can be changed to allow a larger number of characters, I will mark this as a bug as it should really be notifying the user if it becomes larger than this number

**Comment by nikoup** [comment]
Finaly i found it. You must change into sql (phpMyAdmin) the email_templates/body_html from "TEXT" to "LONGTEXT"
