### ISSUE TITLE
SuiteP - Email button icons + Import email button + shifted fields

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2410]
#### Issue

1. New icons instead of old image icons - only suggestion for emails, we are using them daily :)
2. The fields are shifted 
3. Import Button (old type)

![emials_suite](https://cloud.githubusercontent.com/assets/5773777/19317478/6f512b46-90a5-11e6-85b3-4701a2a6e7c9.png)
#### Your Environment

- SuiteCRM Version used: 7.7.5 SuiteCRM
- Browser name and version: Chrome 53.0.x m 32 bit
- Operating System and version: Win 10 Home

**Comment by nikoup** [comment]
I have allready change them (for me) whats your opinion?

![suite_email_icons](https://cloud.githubusercontent.com/assets/22731897/19326042/80b10420-90d1-11e6-9a4e-2f2d7c55cf23.png)

**Comment by Mausino** [comment]
@nikoup i like it, good job! 

But maybe the group of SuiteCRM programmers have other changes prepared, but your work can serve as inspiration for them :)

**Comment by horus68** [comment]
@nikoup can you share the code changes in a github PR?
On a personal taste I would not used green on orange! :)

**Comment by nikoup** [comment]
Hi, i was not mada any changes to any css or make it as svg etc. I just change the images. 

You can import the attached images to crm/themes/default/images
[to_themes_default.zip](https://github.com/salesagility/SuiteCRM/files/527080/to_themes_default.zip)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteP - Email button icons](https://trello.com/c/6vhrGytE/222-suitep-email-button-icons)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
