### ISSUE TITLE
SuiteP -  Quick create case from email (or other modules) issues 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2412]
#### Issue

1. Huge space between buttons and tab navigation
2. If you scroll, the window is going under navigation bar and you can't close the window
3. No space between window header and buttons.
4. Why we need by default on fresh instal in quick edit view the update text ? The update text can't be add (for us is not working), because the record still no exist, that mean, update can be used only if is case created.
5. I can't resize the window (fixed size), it is so flustrating

![navigation](https://cloud.githubusercontent.com/assets/5773777/19341890/d53c6238-912f-11e6-9aee-dea68b746920.png)
#### Your Environment

- SuiteCRM Version used: Official SuiteCRM 7.7.5
- Browser name and version: Chrome 53.x m 32 bit
- Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
