### ISSUE TITLE
SuiteP - Recently view history is using only 1/2 of sidebar

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2414]
#### Issue

The Recently Viewed and Favorites are using only 1/2 of sidebar, but there is enough place.

![sidebar](https://cloud.githubusercontent.com/assets/5773777/19349723/d77cfe20-9154-11e6-8b06-d4d40b5607c3.png)
#### Your Environment

- SuiteCRM Version used: SuiteCRM 7.7.5
- Browser name and version: 53.x m Chrome 32 bit 
- Environment name and version: MySQL, PHP 5.6
- Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
@Mausino , in recent version of suiteCRM, the boundary is slightly moved, check is this OK for you.
If you happy about appearance in recent version (7.7.9), please close an issue, if you still think the improvement has to be made we keep them open. However i have to re-label this issue for "Suggestion".

**Comment by Mausino** [comment]
@shogunpol  i closing this ticket. Thanks for help
