### ISSUE TITLE
SuiteP - Email field go over other record

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2416]
#### Issue

If you have in 2 colums the email field and other field, the email box is over the second field in second column

![email](https://cloud.githubusercontent.com/assets/5773777/19352004/6082205c-915e-11e6-8f2d-45b7ef9e6dfd.png)
#### Your Environment

- SuiteCRM Version used:  SuiteCRM 7.7.5
- Browser name and version: Chrome 53.x m 32 bit
- Environment name and version MySQL 5.6, PHP 5.5
- Operating System and version: Win 10 Home

**Comment by nikoup** [comment]
You can just put the email field in new row (From Studio).

**Comment by Mausino** [comment]
@nikoup yes i did, but point is there is some css issue...

**Comment by shogunpol** [comment]
@Mausino , an issue module described in this case has been redesigned in newest version of SuiteCRM(7.7.9), can you confirm is that changes are acceptable for you, if yes please close an issue.

**Comment by Mausino** [comment]
@shogunpol thanks that your team resolved this issue :) i am closing this ticket
