### ISSUE TITLE
Module Builder cannot save and deploy new and existing packages.  

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#2418]
#### Issue
Module Builder cannot save and deploy new and existing packages.  The Save and Deploy buttons have no effect and page doesnt refresh or show any progress. Further investigations shows issues in the browser console. See screenshot attached. 
![screen shot](https://cloud.githubusercontent.com/assets/18371928/19355155/a10be8d2-9169-11e6-889f-fa5024bcf4be.png)

#### Expected Behavior
Save and Deploy buttons should work in Module Builder for new and existing custom modules. 

#### Actual Behavior
Save and Deploy buttons no not work in Module Builder. 

#### Possible Fix
Fix the error related to message reported in browser console: 
validate_form — sugar_grp1.js:228:87  TypeError: undefined is not an object (evaluating 'document.getElementsByName("view_module")[0].value')

#### Steps to Reproduce
1. Go to Module Builder and create new package
2. Fill in compulsory fields for new package. 
3. Click Save... nothing happens. 
4. Enable browser debug window, click Save again. Observe JS error. 

#### Context
Cannot deploy new or change existing custom modules therefore completely stopping my work. 

#### Your Environment
* SuiteCRM Version used: SuiteCRM 7.7.5 (and also reproduced in 7.7.4)
* Browser name and version: Safari 10.0 (12602.1.50.0.10) (and also reproduced in Firefox 47.0.1)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.35, MySQL  14.14 Distrib 5.6.30
* Operating System and version: CentOS 7.2.1511

**Comment by pgorod** [comment]
I tried this on my 7.7.5 with theme SuiteR, Save went ok, but Deploy gave a pop-up error on the user interface, saying `an error has occurred during deploy process, your package may not have installed correctly`. Nothing in the logs, and nothing in the browser console, though.

I went to the softaculous demo of SuiteCRM 7.7.5 with theme SuiteP and tried it, getting the exact same results as on my own install.

**Comment by shogunpol** [comment]
@evgu , the issue has been tested on recent version of SuiteCRM(7.7.5), and do not appear, i need some additional information: 
- before save created module set up correctly permissions for files?
- did you created at least one module on custom package?
- did you after save clicked deploy button?
- did you after save and deploy package done: admin->repair->Quick Repair and Rebuild, and after you scrolled down to click save changes in database?
Thanks for you contribution.

**Comment by evgu** [comment]
@shogunpol - Thank you for investigating. Responses below: 
- before save created module set up correctly permissions for files? I ran chmod & chown in the root of the CRM instance to ensure permissions and onership are correct. 
- did you created at least one module on custom package? Yes
- did you after save clicked deploy button? Yes 
- did you after save and deploy package done: admin->repair->Quick Repair and Rebuild, and after you scrolled down to click save changes in database? I ran Quick Repair and Rebuild. There is no 'save changes' after running quick repair and rebuild.

**Comment by shogunpol** [comment]
I did try again replicate an issue and still not appear, some more questions than, 
- did you try replicate issue in different browsers?
- did you try replicate issue in different themes?
- did you try replicate issue on newest version of SuiteCRM(7.7.6) ?
@evgu , thanks for your contribution.

**Comment by evgu** [comment]
@shogunpol - mostly grateful for your help. 
- did you try replicate issue in different browsers? Yes in Safari, Chrome, and Firefox (latest current versions).  
- did you try replicate issue in different themes? Only in Suite7. 
- did you try replicate issue on newest version of SuiteCRM(7.7.6)?  Just upgraded to 7.7.6 and this issue is resolved. Many thanks!!

**Comment by vasdaris** [comment]
I'm having the same exact issue on version  7.7.8

Cannot Save or Deploy modules or Create a new one. I've tried to manually create a module folder and a manifest file and then i could proceed to module builder actions.

Redeploying is simply not happening due to this error.

**Comment by MasadAshraf** [comment]
Download new SuiteCRM of your same version and replace your suger_grp1.js file in cache/include/javascript/ , with your new downloaded. 
Don't forget to repair Repair JS Files in admin . And clear your browser cache .

**Comment by evgu** [comment]
Thanks already done that and it fixes the problem. This bug can be closed.

**Comment by pgorod** [comment]
The fact that there is a manual workaround doesn't mean a bug can be closed... Why is this happening to several people? I wonder if could be permissions degradation on the cached sugar_grp1.js. 

If anybody runs into this issue in the future, please check the permissions on that file before doing the fix, and report it here.

**Comment by gunnicom** [comment]
Similar Error: https://github.com/salesagility/SuiteCRM/issues/2517

**Comment by pgorod** [comment]
@gunnicom it would be nice to know if, by any chance, [this fix](https://github.com/salesagility/SuiteCRM/pull/3918) in Module Builder and Studio solves these older problems.

Daniel is asking for help testing that PR, if you have some time it would be great if you could test it a bit. I'm afraid I'm leaving for vacations now so I can't help... thanks

**Comment by gunnicom** [comment]
I can not apply it straight forward as there are merge conflicts for my affected systems (7.7.7) for this patch.
I don't know if i can pin it down in a short time, but definitely will try sometimes.
