### ISSUE TITLE
Import of duplicate record fails to update dropdown field

### ISSUE THREAD

**Issue by JosiahCarberry** [salesagility/SuiteCRM#2421]
Steps to reproduce:
1. Create a dropdown list called language and populate it with the values "English", "German", "French". (see attached screenshot)
2. Add a field to leads, called "language", of the type of the dropdown list created above. Set the default value to "English". (see attached screenshot) NB: the value of Duplicate merge does not change the issue, which exists whether it is Enabled or Disabled.
3. Create a few lead records with language set to "English".
4. Create a csv file with the same first and last names as the leads just created. Add a "Language" column to the file, with the value "French" for each lead. (NB: in my case, I had first name, last name, email address, language)
5. Import the csv file, ensuring the mappings of all fields. Enable updating of existing records during the merge. NB: The problem exists whether you check for duplicates based on email address, or when based on first name plus last name.

Expected result:
All the records are imported, listed as duplicates. All of the lead records have the language changed to French.

Result:
All the records are imported, listed as duplicates. None of the lead records have the language changed to French - they remain as English.

Environment
* SuiteCRM Version used: 7.7.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox , but surely not relevant
* Environment name and version: MySQL 5.5, PHP 7.0.7, Apache 2.2
![dropdown](https://cloud.githubusercontent.com/assets/13927067/19390954/c0fe5a14-922a-11e6-8179-b2593f9bd49b.png)
![field](https://cloud.githubusercontent.com/assets/13927067/19390986/ca009848-922a-11e6-8927-62feaa51c6a6.png)

**Comment by ijdavie** [comment]
@JosiahCarberry, When importing data and you want it to update the existing data in the instance, you must supply the ID of the record which you are importing into, When using the duplicate checker in the import wizard this will only return any duplicates found and allow you to download the duplicate data. 

Without an ID it will not update existing data and only notify you of the found duplicate. This is expected
