### ISSUE TITLE
Error on create new fields in database Type verification

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2428]
Hi, i've detectet on 7.7.5 a issue when you create a new module with fields type "Verification" (CheckBox). Whe publish new module, system says error. And module has been installed (created all fields in MSSQL Database), and Screens are created, but if i go to installed modules, the module it's pending installation.
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All browsers
- Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7
- Operating System and version (e.g Ubuntu 16.04): Windows Server IIS + PHP system.

**Comment by shogunpol** [comment]
@GrupImatica , the issue has been tested on recent version of SuiteCRM(7.7.5) and it appear,
as additional info it appears only on MSSQL, and Load module but not install it.
We label this issue as a bug.
Thanks for raise this issue.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
