### ISSUE TITLE
Leads will not save except in IE (internet explorer)

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#2435]
Leads will not save in edit mode
Can not modify Leads
#### Issue

 We need to save Leads
#### Expected Behavior

Leads would save in all browsers
#### Actual Behavior

Nothing happens when saved except in IE (Javascript bug?)
#### Possible Fix

n/a
#### Steps to Reproduce
1. Login
2. Go to a lead
3. try to edit it
4.  save and nothing happens
#### Your Environment

Version 7.7.5
Sugar Version 6.5.24 (Build 509)
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Mysql , PHP 5.6, 
-  3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Mausino** [comment]
@wanesmith could you define which version of IE are you using?

**Comment by shogunpol** [comment]
@wanesmith , the issue has been tested in recent version of SuiteCRM(7.7.5), and it not appear, can i ask about some additional info, especially your environment, what OS, Browser, PHP and SQL version.
Thanks for your contribution.

**Comment by wanesmith** [comment]
Microsoft Edge 38.14393.0.0
CentOS Linux release 7.2.1511 (Core)

**Comment by wanesmith** [comment]
I tried with firefox and chrome and looked at the console and nothing comes up but in IE everything works and we tried different version of IE and they worked too.

**Comment by shogunpol** [comment]
@wanesmith , can you ask for my other questions? ,

**Comment by wanesmith** [comment]
mysql  Ver 15.1 Distrib 10.1.18-MariaDB, for Linux (x86_64) using readline 5.1
Browser is any that is not IE. My Chrome version is  53.0.2785.143 m
Microsoft Edge 38.14393.0.0
CentOS Linux release 7.2.1511 (Core)

**Comment by shogunpol** [comment]
@wanesmith , thanks for additional information, i did try again replicate an issue again in SuiteCRM(7.7.5), IE 11(11.0.9600.18499). i try test it on MSSQL and MySQL, and issue not appear, it must be something unique what i cannot capture, so how about some more questions? :)  such as:
1. Did you try replicate issue on more than one machine,
2. What exactly version of IE you use,
3. PHP logs
4. Apache log
5. Console log
Thanks for your contribution.

**Comment by wanesmith** [comment]
No php logs no apache logs and console is blank, I you wanted to I could
let you connect to teamview and see the issue in my dev environment?

W

**Comment by wanesmith** [comment]
Now I upgraded. Version 7.7.6
Sugar Version 6.5.24 (Build 509) and still having the same issue.

**Comment by wanesmith** [comment]
I can let someone teamview in to look at it if that is possible?

**Comment by wanesmith** [comment]
I believe that it is still a bug but this might be the answer to fixing it.
https://www.suitecrm.com/forum/installation-upgrade-help/2810-upgraded-to-7-1-4-now-my-leads-won-t-save-database-failure-please-refer-to-sugarcrm-log-for-details

**Comment by shogunpol** [comment]
@wanesmith , to replicate this issue i need extended amount information from you, so:
- what theme you use?
- are they been any customisation on your module, if yes please provide details about what exactly was customized (fields, code, etc..)?
- name and version of the browser you use (exact)?
Thanks for your contribution.

**Comment by wanesmith** [comment]
@shogunpol ,
we tested in on all themes (Classic, Suite 7, Suite P, Suite R)
There are customizations. (fields and code)  It allow me to save when I  Clear Extensions it lets me save. But when I try to save before nothing happens , no errors. 
Google chrome Version 54.0.2840.71 m

---

**Comment by shogunpol** [comment]
@wanesmith , i ask about customisation, because if it causing an issue, i cannot examine it , because i do not have information to let me recreate it. Please provide all necessary details to recreate your customisation.
Thanks for your contribution.

**Comment by wanesmith** [comment]
Here are the  customizations. I tared them before I Cleared Extensions.
[leads.zip](https://github.com/salesagility/SuiteCRM/files/561840/leads.zip)

**Comment by wanesmith** [comment]
@shogunpol 
power2016_10_25_013341.zip](https://github.com/salesagility/SuiteCRM/files/563089/power2016_10_25_013341.zip)
Here are all the customizations.

**Comment by shogunpol** [comment]
I installed your customisation, and it dont even appear in studio, i thing the problem in this case is because you exported customisation from studio, and is missing metadata and other files. The only way in this case to make it work is if you build your customisation again in recent version of SuiteCRM. 
However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by wanesmith** [comment]
![schedule](https://cloud.githubusercontent.com/assets/2706403/19989751/4a7c0058-a25b-11e6-85af-13652c73323f.jpg)

I am having the same issue on scheduling a meeting on leads sub-form. You say it is just a community issue because there is a customization on the form. Regardless suite should give an error or know how to handle the error. This screen just does nothing when you try to save. That is the part of the core SuiteCRM that is not working correctly. Again the meeting on the sub form will save on IE which again makes it seem like a bug and not a customization issue. When you go the full form it will save.
