### ISSUE TITLE
SuiteP - checkboxes on detailview are overlaid by field background color/layer

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2436]
#### Issue

Please look on image - checkboxes in detailview are overlaid by fied background color

![checkboxes](https://cloud.githubusercontent.com/assets/5773777/19472031/d86b8160-9525-11e6-84ec-78359490298c.png)
#### Steps to Reproduce

1. Open some record where are checkboxes
#### Your Environment

- SuiteCRM Version used: SuiteCRM 7.7.5
- Browser name and version: Chrome 53.x m 32 bit 
- Environment name and version: PHP 5.5, MySQL 5.6
- Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
This checkbox are disable in detail view, this is reason why they grey-out, this is expected feature of the system, the picture bellow on your screenshot is edit mode, when check boxes are active.
Due not appear an issue, can you close this issue, or we label it as a suggestion.
@Mausino , thanks for your contribution.

**Comment by Mausino** [comment]
@shogunpol first checkbox which is checked ( field "Landlord" ) is also overlaid by fied background color and on screen you can see how big diffrence is between unoverlaid and overlaid checkbox :) 

please let me your opinion (we have custom added the update function, this is reason why i can show you the diffrence)

![overlaid](https://cloud.githubusercontent.com/assets/5773777/19476953/32f47c5c-953c-11e6-813b-0c6fe109f8d1.png)

**Comment by ijdavie** [comment]
@Mausino, This from what I can see is not a overlay and is due to the field being marked as a disabled field. It may be the overlay around this field which is causing the look to be harder to read. (if you disable to the disabled attribute on the field there is no overlay on top of it. 

we could raise this as a suggestion unless others see this as a issue ?

**Comment by Mausino** [comment]
@ijdavie  my programmer will fix it, that this field will look as "default checkbox" which i see usually in editview or update tab. You can mark it as suggestion, but my and colleges which are using the CRM, we expencting same collor&contrast as is used as text, and same collor&contrast for checkbox which are checked .... Sorry is hard to explain for me in English

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteP - checkboxes on detailview are overlaid by field background color/layer](https://trello.com/c/I19r3LCV/65-suitep-checkboxes-on-detailview-are-overlaid-by-field-background-color-layer)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
I can't work with trello 🔢 shoudl we use for checked checkbox this icon ?

https://fontawesome.com/icons/check-square?style=regular
![2018-02-20_1343](https://user-images.githubusercontent.com/5773777/36424606-28dadd76-1644-11e8-8c3f-5730fa4f9951.png)
