### ISSUE TITLE
Add a product line on a quote

### ISSUE THREAD

**Issue by nicodelon** [salesagility/SuiteCRM#2438]
When I want modify a quote and add a product line in a quote createds, specialy when it is displayed as tab, considering what happens and the display, it is impossible to add a product line.
![otherbug](https://cloud.githubusercontent.com/assets/16166801/19478152/64311a8c-950f-11e6-9e88-902ca2d84d82.jpg)

**Comment by ijdavie** [comment]
@nicodelon This looks like the detail view. this should work correctly on the edit view ? I assume that you are using the inline edit for this field ?

**Comment by nicodelon** [comment]
Yes it is exactly what you describe : no problem when you directly edit the quote. The problem happens in the detail view when you use inline editing

**Comment by ijdavie** [comment]
@nicodelon this is a bug. either it shouldnt allow you to inline edit this or the save works as expected. 

This functionality that you see is a function field so inline edit does not work as there is no single field for this. I will mark this as a bug.
