### ISSUE TITLE
Old themes Add Dashlets not showing v7.7.5

### ISSUE THREAD

**Issue by leozanutto** [salesagility/SuiteCRM#2441]
#### Issue
Upon upgrading to 7.7.5, in old themes the add dashlets its not working 

#### Expected Behavior
Should show the dashlet panel

#### Actual Behavior
Blank Modal.

#### Possible Fix
Script in include/MySugar/javascript/MySugar.js
**Rapid fix**
Method showDashletsDialog
 change dashletsListDiv=$('*[id=dashletsList].modal-body'); to dashletsListDiv=$('*[id=dashletsList]');
**Best fix**
the role if sentence don't make much sense see :
`if ($('*[id=dashletsList]').length > 1) {
                        dashletsListDiv = $('*[id=dashletsList].modal-body');
                    } else {
                        dashletsListDiv = $('#dashletsList');
                    }`
It is cheking if you have more then one id  dashletsList and you have don't know why?
then sets var dashletsListDiv that contains modal-body but old themes don't have that class
and there you got the error.
**what to do I think**
`if ($('*[id=dashletsList]').length > 1) {
                        dashletsListDiv = $('*[id=dashletsList].modal-body');
}
if(!dashletsListDiv)
     dashletsListDiv = $('#dashletsList');
 `

#### Steps to Reproduce

1.With suiteCRM version v7.7.5 use a old theme
2.At Home page click Add dashlets
3.Modal appears but is blank.

#### Context
had to fix that so I can make upgrade in production where customers will not change their template
low priority.

#### Your Environment

* SuiteCRM Version used: 7.7.5
* Chrome Version 51.0.2704.63 (64-bit)
*MySQL, PHP 5.6
* CentOS Linux release 7.2.1511 (Core)

**Comment by shogunpol** [comment]
@leozanutto , yes the issue occurred in version 7.7.5 of the SuiteCRM, however in the recent version of SuiteCRM(7.7.6), the problem has been solved, can you confirm is this not issue any more, if yes can you close an issue?
Thanks for your contribution.

**Comment by leozanutto** [comment]
Yep! It's solved thanks.

**Comment by shogunpol** [comment]
@leozanutto , thanks for quick respond, can you close issue for me than?
Thanks for your contribution.
