### ISSUE TITLE
Invoice not Saving decimals in Invoice

### ISSUE THREAD

**Issue by daschenbrener** [salesagility/SuiteCRM#2443]
#### Issue
When I create an invoice and add a product that is setup as a service item, the invoice calculates that correctly, but when I go to save the invoice, it reverts to an integer.

#### Expected Behavior
The invoice should save the decimal item

#### Actual Behavior
it reverts to an integer value

**fix**
have the service line item to have a qty amount, and able to save a decimal,
or
Have the product line item accept the decimal ,

#### Steps to Reproduce
1. create invoice
2. add product item
3. add, for an amount 1.5
4. totals correct,
5. save the invoice, and print to pdf, and the total is correct but the line item amount reverts to an integer

#### Context
Issue is quite large as i cannot print to invoice from the system. 
I will have to edit the PDF manually

#### Your Environment
Suite CRM Version 7.7.5
Sugar Version 6.5.24 (Build 509)

**Comment by shogunpol** [comment]
The issue has been tested on the recent version of SuiteCRM(7.7.6), and it not appears,
@daschenbrener ,i want ask you about some more details for example, can you tell me what exact files you use in PDF Template, "add for an ammount 1.5" mean type quantity 1.5? also environment: web browser, OS, PHP and Database type?
Thanks for your contribution.

**Comment by daschenbrener** [comment]
Yes quantity 1.5 , browsers chrome, PHP 7, mariadb 10, Windows 10
and ive tried this with edge as well

**Comment by daschenbrener** [comment]
and the files i use are the invoice sample template that i loaded for the invoice.

**Comment by daschenbrener** [comment]
I just upgrade to 7.7.6 and this upgrade fixed the issue.
