### ISSUE TITLE
Attach file button in quick compose mail and TO: button

### ISSUE THREAD

**Issue by mmannik** [salesagility/SuiteCRM#245]
1. Attach file button in quick compose mail and TO: button does not responde:
https://www.suitecrm.co.uk/forum/bug-tracker/4879-attach-file-button-in-quick-compose-mail
It seems not reported orginally to Github.

2. Window "relate emails" button "relate" does not responde (window does not disapear after pushing) and in backround relation to opprortunity is not made. Seems same behaviour as in p.1.

Problems appeared after upgrade to version 7.2.1.
Tested with browsers IE 11.0; Chrome 42.0.2311.135

**Comment by mmannik** [comment]
Sorry , below issue still seems to work and had probably unrepeatable problem:

2.Window "relate emails" button "relate" does not responde (window does not disapear after pushing) and in backround relation to opprortunity is not made. Seems same behaviour as in p.1.

**Comment by willrennie** [comment]
Duplicate issue.
