### ISSUE TITLE
FP_events.svg duplicated file - v7.7.6

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2451]
#### Issue

Windows does not tolerate case insensitive duplicate file names. 
The following "duplicates" are there in v7.7.6 ( to 7.7.8 beta):
themes/SuiteP/images/sidebar/modules/

```
FP_events.svg
FP_Events.svg 
```

https://github.com/salesagility/SuiteCRM/tree/master/themes/SuiteP/images/sidebar/modules

its the same issue but not solved by #2215 (case insensitive)
#### Actual Behavior

When unzipping on Windows files are overwritten as duplicated
#### Possible Fix

Why not end with mixed case files? All lowercase would give us peace of mind (also useful for sorting files in a folder as Windows create an alphabetical order for Lower case and other for Uppercase
#### Your Environment

- SuiteCRM Version used: 7.7.6 to 7.7.8 beta
- Operating System and version: Windows 10

**Comment by horus68** [comment]
@shogunpol the problem remains in 7.7.8 beta

**Comment by shogunpol** [comment]
@horus68 , thanks for information

**Comment by shogunpol** [comment]
@horus68 , check in 7.7.9 and duplication not appear.

**Comment by horus68** [comment]
7.7.9 - no problem
7.8 beta from https://suitecrm.com/download/download-pre-release
the problem is there

This kind of issues is recurrent (on and off) maybe from the tools or system used on on SuiteCRM packaging. On some older versions the files involved was different!
It would be so good to have all files in lowercase! [New year wish] 

![2017-01-04 15_25_31-d__softwprodutos_suitecrm_downloads_77](https://cloud.githubusercontent.com/assets/3055443/21647456/3db022d4-d292-11e6-8715-ccac087049fe.png)

**Comment by shogunpol** [comment]
@horus68 , i will look at it closer, unfortunately i cant promise all files in lowercase :) , Happy new Year :)

**Comment by mattlorimer** [comment]
it will be in the next beta release
