### ISSUE TITLE
can not add custom dashlet (tools, chart or iframe) using Suite P

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#2456]
Actually we can not add any dashlet that are not on the first tab (modules).
if you want to add chart, tools or web dashlet clicking on the tab produce nothing...
only the first tab of add dashlet works.

I must add that I tried with ie and chrome
using 7.7.5

I does work with other themes...

**Comment by shogunpol** [comment]
@bmwtourer all issues about adding dashlets, charts and so on, are fixed in recent version of SuiteCRM(7.7.6), Can you confirm is not an issue any more in newest version.
If yes can you close the issue,
Thanks for your contribution.

**Comment by GrupImatica** [comment]
Works fine in 7.7.6 :)

**Comment by shogunpol** [comment]
@GrupImatica , if is not issue any more, can you close the issue?
Thanks for your contribution.

**Comment by GrupImatica** [comment]
This closes #2456
