### ISSUE TITLE
Module Builder Not working in 7.7.6 if upgraded

### ISSUE THREAD

**Issue by petedyer** [salesagility/SuiteCRM#2459]
Module Builder is not correctly deploying modules if built using an ****upgraded version**** of Suitecrm but works in a new install of suitecrm 7.7.6.

We have tried this on 2 separate installs one wamp windows and another using linux cloud server.
See screenshot of what the behaviour is like in configure module menu filters(the labels are blank)
![suite-sc1](https://cloud.githubusercontent.com/assets/17161452/19569733/bcbeba3e-96ee-11e6-98c8-50a4121a743b.JPG)

Also when in list view of the custom module there are no action buttons on the left hand side. these are missing
![image](https://cloud.githubusercontent.com/assets/17161452/19569828/0cd53ea8-96ef-11e6-9141-f6efafd1386d.png)

Also in log we get the following notice:
 Undefined index: TEST_Module in xxxx\include\GroupedTabs\GroupedTabStructure.php on line 126.

As mentioned this only happens if upgrading from 7.7.2 to latest version 7.7.6 AND not on a clean install

**Comment by shogunpol** [comment]
@petedyer , i do not have enough information about how to replicate an issue, i need step by step, plus what module, and screenshots says not much to me, i want ask you to all properties of your custom module.
Thanks for your contribution.

**Comment by petedyer** [comment]
Hi The screenshot is a result of the module builder not working.
The module is any custom module. So here are the steps.
1. issue only on SuiteCRM versions which have been upgraded from 7.7.2(that's when we started).New fresh 7.7.6 not affected.
2. Goto module builder and build any new module whit any name. no extra fields need to be added only the basic module type can be chosen.
3. Deploy module as per usual
4. can carry out quick rebuild from admin screen
4. Go into module menu filter - heres the first problem the newly created module label appears as a blank as per the first screenshot
5. drag the empty label across so you can access module from one of the menus latter on.
6. Access this new module from the menu. A per the second screenshot you will see that the actions are missing on the left hand side(all other modules have view and add etc on left hand side)
7. Only things we see is constant references to undefined index in our logs referring to the new module. The main error is undefined index: TEST_Module in xxxx\include\GroupedTabs\GroupedTabStructure.php on line 126.

If you need more info please let me know

**Comment by shogunpol** [comment]
@petedyer , the issue has been tested exactly through path you provided, and it not appear.  So to replicate this issue need ask for some additional info, so did you after repair&rebuild, scrolled down and clicked execute, or there is not any changes on tables? also i have to ask about environment: OS, browser (name and version), database used, and version of PHP.
Thanks for your contribution.

**Comment by petedyer** [comment]
Hi Yes we have rebuilt etc.. Tables in db all look correct. Have you tested on a upgrade version and not a clean install as new clean install version is fine. Issue is happening on 2 platforms with different phps
wamp details:
os: windows 10
browsers: edge/chrome 54.0.2840.59
php: 7.0.3
mysql: 5.6.17

Linux
os:cent 6.8
browsers:edge/chrome 54.0.2840.59
php:5.5.38
mysql: 5.0.11

**Comment by shogunpol** [comment]
@petedyer , yes it was installed 7.7.2 than after was upgraded to 7.7.6, the modules has been build in both initial and upgraded instance. If is anything else what you think it may help to replicate issue please post it.
Thanks for your contribution.

**Comment by petedyer** [comment]
only thing I can think of was that we used the same 7.7.2 copy for both installs .perhaps bad unfinished copy. We have couple of other installs from the days when suitecrm first started - we will check if the problem is in these too. Otherwise we will redownload a fresh copy 7.7.2 and try the upgrade path ourselves. Will keep you posted

**Comment by shogunpol** [comment]
@petedyer , thanks and please do post your results, the crucial part of processing GitHub issue is to replicate it.
Thanks for your contribution.

**Comment by petedyer** [comment]
okay we have tested it on 2 other servers with old suitecrms (6 series or 7.0.0) and the problem is not present. We did notice no plus or view icons are present on the custom modules but this is not an issue at the moment. So its looking like perhaps a bad copy. we will rebuild using a fresh on the effected linux server and report back

**Comment by petedyer** [comment]
we have redone the test on that server with a fresh copy and we cant replicated(also updated the php) the issue. I can only guess that the copy of 7.7.2 that we used across the other 2 servers was maybe missing something

**Comment by petedyer** [comment]
couple of issues have come up not sure if log here or separately. on fresh install of 7.7.6 for custom modules there is no eye icon(like all other modules) for the view button on the left hand side. Otherwise please mark this as resolved
