### ISSUE TITLE
Calendar js error: datepickerLang is not a function

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#2466]
#### Issue

When loading the calendar (dashlet or module view), the console error "a.fullCalendar.datepickerLang is not a function" is thrown in the file modules/Calendar/fullcalendar/lang-all.js.

![image](https://cloud.githubusercontent.com/assets/20977561/19605363/94767c80-9787-11e6-8623-5f3b7858034b.png)
#### Context

The calendar is such a critical component of the crm, and ever since the 7.7 release it has never worked properly as it previously did. We need the calendar issues to be fixed before we can go live.
#### Your Environment

SuiteCRM v7.7.6
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 53 on Windows 10

**Comment by staganyi** [comment]
Also happens on a clean install of 7.7.6

**Comment by shogunpol** [comment]
@staganyi , can you give me more explanation about an issue, so full steps to reproduce, and what functionalities is broke, 
Thanks for your contribution.

**Comment by staganyi** [comment]
No steps, simply loading the calendar (either dashlet or module view), the console error occurs. I wanted to keep this separate from the other calendar issues.

**Comment by staganyi** [comment]
This appears to be fixed in 7.7.7
