### ISSUE TITLE
Admin > Advanced OpenAdmin > Theme Settings Link broken

### ISSUE THREAD

**Issue by rustyspark** [salesagility/SuiteCRM#247]
Admin > Advanced OpenAdmin > Theme Settings Link broken
![suiteaos theme](https://cloud.githubusercontent.com/assets/3454836/7635280/af1d1036-fa25-11e4-9e13-8874284f8f5e.png)

It opens the URL of: 
> http://sugartest.[instance].com/index.php?module=Administration&action=colourAdmin

Which in prior to 7.2 would launch a color configuration screen. 
![theme settings](https://cloud.githubusercontent.com/assets/3454836/7635347/0fd18e98-fa26-11e4-99a2-f2cd941d8a8b.png)

However now it reports the following error:

> "There is no action by that name."

![suitetheme error](https://cloud.githubusercontent.com/assets/3454836/7635306/cbee9aae-fa25-11e4-83f8-452adeeadde4.png)

**Comment by willrennie** [comment]
You need to run a Quick Repair & Rebuild in Admin -> Repair. The Theme settings are no longer located in the AO Admin panel, but in Admin -> Themes. Clicking on the theme name within Admin -> Themes will show the colour picker for your specific theme. Thanks, Will.

**Comment by rustyspark** [comment]
Thanks Will! 
Do you mean: 

Repair
or
QuickCRM Update

**Comment by rustyspark** [comment]
After the re-build the theme adjustments still do not take effect. I see an existing bug that represents theme not taking effect unless you hit enter. But mine does not appear to work with enter either.

**Comment by mattlorimer** [comment]
check the permission on your config_overrride.php it may be failing to write to it

**Comment by rustyspark** [comment]
So we checked the permissions and they are the same for this file as for others. 
Our theme color choices are showing up in the config_override.php file.  However changes to these themes are not effecting the display of the site, unless we directly edit the Suite R theme.  

Steps to re-produce:
1. Set current users theme to Suite 7
2. Navigate to Admin > Themes > Suite 7
3. Attempt to change the header menu color (first box)
4. Strike [ENTER] key, click save. 
-- no change.

Try with new theme
5. Set current users theme to Suite R
6. Navigate to Admin > Themes > Suite R
7. Attempt to change the header menu color (first box)
8. Strike [ENTER] key, click save. 
-- change is instant

Clone original theme
9. Copy Suite 7 theme, rename  change themdef.php to reflect new name
10. repeat above steps
- no effect

Clone suite r theme
11. Copy Suite R theme, rename  change themdef.php to reflect new name
10. repeat above steps
- no effect

Check config_override.php
See that all theme changes have taken effect.

**Comment by rustyspark** [comment]
See the related thread here: 
https://suitecrm.com/forum/suite-themes/4242-suitecrm-demo-theme#18634

**Comment by rustyspark** [comment]
Is this expected behavior or do you think this is a bug?

**Comment by rustyspark** [comment]
I am getting no answer on either thread. Is anyone able to make a new theme work in Suite CRM?

**Comment by willrennie** [comment]
The theme settings link is removed in SuiteCRM 7.2/7.3 upgrades so this should not be an issue in current/future releases.

**Comment by rustyspark** [comment]
Thanks for responding! That doesn't work on all the elements on one of my builds, but it probably will when we update to your latest one.
