### ISSUE TITLE
using 7.7.6 dashlet navigation does not behave correctly 

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#2479]
upgraded to 7.7.6 on dev and production instance and I also tested on new 7.7.6 install, all shows same behavior:
using SuiteR and Suite7 themes  (the SuiteP theme seem to behave correctly).
in dashboad navigating to a dashlet works but behave incorrectly;  the dashlet replace the dashboard, only the dashlet is showed in full width of the page 

This is original dashlet **_from brand new install**_ (to check if it was my instances that were off)

![image](https://cloud.githubusercontent.com/assets/9001018/19650981/26a56370-99d9-11e6-9a16-d11ae7fcc346.png)

Now if we navigate...
![image](https://cloud.githubusercontent.com/assets/9001018/19650994/328aec0a-99d9-11e6-860a-107525c63491.png)

This is might be linked to   #2263 
I will close 2263 to continue with this one since it is a different bug.

**Comment by shogunpol** [comment]
@bmwtourer , what behaviour is incorrect? can you provide steps to reproduce issue, and also environment details please.
Thanks for your contribution.

**Comment by bmwtourer** [comment]
ok 
I just deleted my cache just to be sure...
using i.e 11  but same behaviour with Chrome 
using 7.7.6 and SuiteR theme

goto to home page
Click on a dashlet "next button" that have multiple pages
![image](https://cloud.githubusercontent.com/assets/9001018/19732308/6931436c-9b6e-11e6-8a1b-59262efc4f8d.png)

it will show the next page taking the whole dashlet area and kicking the other homepage dashlets out of the page.
and the worst part is that even if I want to go to the third page I can NOT, only the second page is showed.  actually the navigation is broken at that point, I can not go back either, I am stuck on the second page
![image](https://cloud.githubusercontent.com/assets/9001018/19732468/d82ad1fc-9b6e-11e6-8811-d9e43a851514.png)

The only way out is to select something else from either menu or click to go back on homepage...

**Comment by shogunpol** [comment]
@bmwtourer , after additional information provided, i been able to replicate the issue on recent version of SuiteCRM(7.7.6),
We label this issue as a "bug"
Thanks for your contribution.

**Comment by sieberta** [comment]
I'm not sure what is going on with Dashlets... they've been a problem pretty much since SuiteP was released.  This seems simlar/related to #2263, which was recently marked closed.  Although when I upgraded from 7.7.4 to 7.7.6 my behavior stayed the same as #2263, not what @bmwtourer is getting.

Furthermore, @JimMackin dashlets are pretty core functionality to SuiteCRM and they are, for all intents and purposes, completely broken at the moment.  I'm not sure 'Low Priority' cuts it for this bug.  Users are getting impatient with the fact this has been broken for months now... and I don't feel like I can force people to use the SuiteP theme since it is unuseable due to screen real estate useage.

sieberta

**Comment by sieberta** [comment]
Wait!  The behavior @bmwtourer indicated is what I see in **Chrome**.  But in **Firefox** it just 'does nothing' as reported in the previous instances.  That is why we were seeing different behavior.

sieberta

**Comment by bmwtourer** [comment]
I agree about priority.... my users are frustrated too.
we are trying hard to improve CRM usage but a basic feature like this can really  slow users enthusiasm.

The crm work but the home page is where most people start their day with it...

priority should be higher

**Comment by JimMackin** [comment]
Hi Folks,
We take your feedback seriously so I'm upping the priority.
Thanks,
Jim

**Comment by sieberta** [comment]
@shogunpol @daniel-samson,

This proposed fix has now been deployed on my instance, and seems to be working fine with no side effects so far.  Just implemented 5 minutes ago, however... will let you know if anything pops up.

THANK YOU!
sieberta

**Comment by daniel-samson** [comment]
@sieberta thanks for testing it. It really helps.
