### ISSUE TITLE
MVC framework used?

### ISSUE THREAD

**Issue by richhl** [salesagility/SuiteCRM#2481]
hi, evaluating for adopt CRM. is this product built agains any MVC 'standard' framework? symfony? zend? yii?  thx in advance.

**Comment by daniel-samson** [comment]
Hi @richhl,

SuiteCRM is built on the SugarCRM CE 6.5 framework. Which implements a moduler form of MVC. It doesn't use a framework like symphony. It has it's own framework, where you can create upgrade safe changes via module builder / studio. You can also integrate SuiteCRM into an other application such as Joomla, or a framework of your choosing via the REST/SOAP API. Please check out https://suitecrm.com/ for details. If you need support/guidance, please ask any questions you have on our forum. You can also try the demo on the website. You may wish to take a read of Jim Mackin's book "SuiteCRM for developers". It explains how to develop in SuiteCRM.

**Comment by richhl** [comment]
thx a lot @daniel-samson
