### ISSUE TITLE
User profile image not visible on Employee detail page

### ISSUE THREAD

**Issue by HVStechnik** [salesagility/SuiteCRM#2483]
#### Issue

A photo uploaded to the users profile (edit view / detailed view) into the 'photo' field of the 'users' table is visible in the users module only. Within the employees detail view the photo is not found:

![Photo missing](https://cloud.githubusercontent.com/assets/23050940/19680470/205cab04-9aa6-11e6-9d51-416dd9010954.PNG)
#### Expected Behavior

The profile image from the user module should be visible within the employee module as well.
#### Possible Fix

Within the download.php file for all requests to the Employee module, the table name should be changed to users since all fields within the Employees module are stored within the table 'users'.

e.g. add line 156 in download.php:
$file_type = ($file_type == "employees") ? "users" : $file_type;
#### Context

Low priority, but I think it is easy to fix...

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.6), and it appear,
We label this issue as a "Bug"
@HVStechnik , thanks for your contribution.
