### ISSUE TITLE
SuiteP - Bold font issue for same special characters

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2487]
#### Issue

Some special characters show bold in name of record

![font](https://cloud.githubusercontent.com/assets/5773777/19698516/de953750-9aef-11e6-8419-72cda9baae5e.png)
#### Steps to Reproduce

1. Edit any record
2. Use specila letters
3. Save the record
#### Your Environment

- SuiteCRM Version used: 7.7.6 Official Demo
- Browser name and version: Chrome 54.x 64 bit

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.6) and it appears,
We label this issue as a "bug"
@Mausino , thanks for raise this issue.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
