### ISSUE TITLE
Email Template Padding prevents proper alignment of body with signature

### ISSUE THREAD

**Issue by domtylerlovett** [salesagility/SuiteCRM#2494]
#### Issue

All blocks added to an email template include padding against the text.  This effectively indents the text so it's misaligned with any email signature for example and doesn't look professional.
#### Expected Behavior

Text within blocks should be unpadded so they align with an email signature.
#### Actual Behavior

Text within blocks are padded so they don't align with an email signature.
#### Possible Fix

Change padding: within HTML <div class=" code
#### Steps to Reproduce
1. Create an email autosig and set it as default
2. Create an email template and add at least one block which contains text
3. Compose and send a new email using the above template
4. Observe the alignment of text in the sent/rcvd email
#### Context

I was trying to send some professional looking emails out to prospects but I'm still doing this manually for now.
Most aspects of email-related features within SuiteCRM are not very intuitive or professional so this is high priority as an intermediate step.
#### Your Environment
- SuiteCRM Version used: 7.7.6
- Google Chrome (Latest)
- MySQL, PHP (unsure of version)
- Windows 10

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
