### ISSUE TITLE
Links in Email Template blocks are fixed font size

### ISSUE THREAD

**Issue by domtylerlovett** [salesagility/SuiteCRM#2495]
#### Issue

Links in Email Template blocks are fixed at a font size which may not match the rest of the size of that block's text.
#### Expected Behavior

Adding/converting to a link shouldn't affect the font size.
#### Actual Behavior

Adding/converting to a link affects the font size of that link.
#### Possible Fix

Stop it from happening by editing generated HTML
#### Steps to Reproduce
1. Add a block to an email template
2. Enter some text and set it to a non standard size (e.g. 18pt)
3. Convert one or more parts of the text into a link
4. Observe the font size change
#### Context

I was trying to send a professional looking email with links in it.
I believe this should be High priority.
#### Your Environment
- SuiteCRM Version used: 7.7.6
- Google Chrome (Latest)
- MySQL, PHP
- Windows 10

**Comment by dursuntosun** [comment]
Yes, i have this issue and mentioned in this post #2354
