### ISSUE TITLE
SuiteCRM 7.7.6 - Calendar Localization not working: days long and time slot

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#2498]
In SuiteCRM 7.7.6 Calendar is always in English language..
#### Issue

in SuiteCRM 7.7.6 the Calendar headers (days_long) and time slots are in English language even if all other dates and times are following the right Locale settings.

![screen shot 10-27-16 at 10 39 am](https://cloud.githubusercontent.com/assets/2909933/19760649/f1517888-9c32-11e6-8a54-d0ae2fd49b9f.PNG)

**Comment by mayerelyashiv** [comment]
About Days in long format (Monday, Tuesday,...)
i found that you have to take action here:
/modules/Calendar/fullcalendar/lib/moment.min.js
row#356 and following

**Comment by mayerelyashiv** [comment]
About Time slot (always in format 8AM, 9AM,...)
i found that you have to take action here:
/modules/Calendar/fullcalendar/fullcalendar.min.js

**Comment by mayerelyashiv** [comment]
i meant something like:

smallTimeFormat: function(t) {return t.longDateFormat("LT").replace(/\s*a$/i,"H:mm").substr(t.longDateFormat("LT").replace(/\s*a$/i,"H:mm").length - 4)}

**Comment by gunnicom** [comment]
The time format should follow the user preferences.

**Comment by mayerelyashiv** [comment]
Yes, it should

**Comment by mayerelyashiv** [comment]
I can add that in 7.7.6
on the Tooltip , the time slot is correctly formatted,
but in the div.fc-time::before section, time is not following user preferences:
![immagine](https://cloud.githubusercontent.com/assets/2909933/20189500/bdc3af08-a77d-11e6-8590-cbe62efb7d6f.png)
