### ISSUE TITLE
Inline edit wrong behavior

### ISSUE THREAD

**Issue by NaNmblsha** [salesagility/SuiteCRM#2499]
Inline edit doesn't work if you try to edit related fields (assigned user/accounts etc.) more then one time in a row. This means that if I make inline edit of Accounts on Details View I'll see list of account (see first attachment)
![inline working event](https://cloud.githubusercontent.com/assets/14258211/19762573/2faea7c6-9c43-11e6-896d-e2805060250c.png)

And after it (without reloading page) if I try to make inline edit for second time I won't see any data after typing anything in that filed (see second attachment)
![inline no event](https://cloud.githubusercontent.com/assets/14258211/19762581/3e9ea358-9c43-11e6-8cc4-59bb12ae3179.png)

As I noticed there is no appropriate event binded on that filed and there are some differences between html structure of this block and class names after inline edit. 

This occurs in SuiteCRM version 7.6.4. Also, on forum I was answered that this issue can be validated on 7.7.6. as well.

**Comment by shogunpol** [comment]
@NaNmblsha , please provide step by step replication bug, flow(did you done any customisation on code or modules?). Also if i may ask you about environment details.
Thanks for your contribution.

**Comment by ijdavie** [comment]
@NaNmblsha, This from what I can see is the auto complete does not work on the second edit. the save still works as expected if using the popup.

**Comment by NaNmblsha** [comment]
@shogunpol, here's how it can be reproduced (example will be for Opportunities module):
1) open Opportunities details view module;
2) click on inline edit sign for Accounts field;
3) in appeared field type some data to see list of Accounts;
4) chose one of them and click on save sign;
5) after successful save -> repeat step 2) and 3)
6) Now you'll see that field do not respond on any pasted data.

Yes, this module was customized but I have the same error on other "clean" modules.
Environment: Windows server 2012R, MsSQL, SuiteCRM version 7.6.4.

**Comment by kdjmonaghan** [comment]
Hi @NaNmblsha, I believe this has been resolved in 7.8. If you're still having issues with this, please check 7.8 and let me know if the problem still occurs for you.

**Comment by NaNmblsha** [comment]
Hi!
Thank you

вт, 7 февр. 2017 г. в 16:41, Kieran Monaghan <notifications@github.com>:
