### ISSUE TITLE
Cannot assign Calendar Meeting/Call to other person - bug or no bug that is the question ;-)

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#250]
Hi.

We used to be able to create Meetings and Calls for other people, then assign that to them and have that Meeting/Call show up in THEIR calendar - that was on the last install of SugarCRM.

Now we can't do that anymore, but I am not sure

  - whether I am doing something wrong (security settings??)
  - whether this is intentionally and by design
  - whether this is a bug.

I tried to add a meeting (logged in as admin) for another person, that did not show up int their calendar as well - so this worries me a little.

This was one of the good features the SugarCRM calendar had, our helpful office fairy could add entries into our calendars ... but sadly that is not possibly in the moment.

Any ideas anyone?

**Comment by ricktimmis** [comment]
Hi Jobst

We are using the Calendar in the way you describe and it works as you expect.

Have you checked the Setting button top right of the Calendar ?

Also, another idea.. I understand that when assigning a Call, or Meeting to another person, they have to Accept, Tentative, or Decline. I wonder if they need to accept it before it gets put in their calendar.

These are just ideas, I hope they help

Rick

**Comment by willrennie** [comment]
Non-issue and Rick has given some good advice on this issue.
