### ISSUE TITLE
Unused language strings (Activities)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2501]
See #2444

['LBL_DURATION_MINUTES']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L67
['LBL_NEW_TASK_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L97
['LBL_SCHEDULE_MEETING_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L100
['LBL_SCHEDULE_CALL_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L103
['LBL_NEW_NOTE_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L106
['LBL_TRACK_EMAIL_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/Activities/language/en_us.lang.php#L109

**Comment by horus68** [comment]
Excellent work. There are already 7 PR for language unused strings.
Hope to see them all merged at once so then I can upload all changes to Crowdin.
Keep on the good work!

**Comment by likhobory** [comment]
Thanks, I hope the solution for this issues will take less time than the issue with Russian forum.
