### ISSUE TITLE
Upgrade not working 7.7.5 to 7.7.6

### ISSUE THREAD

**Issue by psatasiya** [salesagility/SuiteCRM#2502]
Hi dear Experts,

I'm running a suiteCRM, Version 7.7.5. I'm trying to upgrade it to SuiteCRM 7.7.6 using SuiteCRM-Upgrade-7.7.x-to-7.7.6.zip

Now I'm trying with the Upgrade Assistant and in step 2 after choosing the upgrade package file and click on "Upload Package" I see the message "SuiteCRM-Upgrade-7.7.x-to-7.7.6.zip has been uploaded."

Yet in the following section (just below the Upload button) titled "The following upgrade packages are ready to be installed:" nothing is shown ("none").

When I click on "Next" I see the red error message "Upload a package before continuing."

So I'm stuck.

I've given this permissions to all files in the sugar directory, including the upgrade file.
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php
sudo chown -R user:group (username and group name is same.)
Any help appreciated!

Thanks
![before next](https://cloud.githubusercontent.com/assets/19162814/19765136/6c34ade6-9c64-11e6-92ef-21dadf470555.png)
![after next](https://cloud.githubusercontent.com/assets/19162814/19765139/71e1e3e4-9c64-11e6-98ec-072893b12ae7.png)

**Comment by mattlorimer** [comment]
according to you screenshot 7.7.6 has already been installed so it not letting you do it again, but this really more a question for the [forum](https://suitecrm.com/forum/index), you should be able to get better help with this there

**Comment by psatasiya** [comment]
@mattlorimer Thank you very much for your reply.
