### ISSUE TITLE
Error in image field for Project Task - Unidentified table names in queries

### ISSUE THREAD

**Issue by gpex1234** [salesagility/SuiteCRM#2514]
Adding an image field to the Projectask breaks the module.

Checked.
#### Issue

Adding an image field to the projectask breaks the module.
- We added a image field to the project task. The field is called 'screen_i'. The width and height are set to 768x432.
- When we add the field in studio it is properly added and shown on the relevant pages.
- We can also add an image by browsing for it without any problems.
- However, when you see the record the image is broken and not shown. 
- If you try to copy the image location (right click on broken image sign) and open in new tab. You get this error message:
  "Error retrieving record. This record may be deleted or you may not be authorized to view it."
#### Expected Behavior

The image should have shown properly. I have tried adding a similar field in "Project" detail view also and it works properly. So there is no permission issue.
#### Actual Behavior

The image is not shown. 
The attempt to copy image location and open in new tab leads to "Error retrieving record. This record may be deleted or you may not be authorized to view it."
#### Possible Fix

I have analyzed the error logs for it and found this:

From suitecrm.log:

> Sun Oct 30 17:25:01 2016 [11109][1][INFO] Query:INSERT INTO project_task_cstm (id_c ,finish_c ,screen_i_c ,start_c ) VALUES ('d2ebfc29-8159-ee97-57ba-5815df287daf' ,NULL ,'6-4315-13-Funny-Minion-Quotes-Of-The-Day-278.jpg' ,NULL )
> Sun Oct 30 17:25:01 2016 [11109][1][INFO] Query Execution Time:0.012243986129761

So the file is correctly inserted into database records. I have verified it.

Possible Reason#1
From suitecrm.log:

> Sun Oct 30 17:25:15 2016 [13155][1][INFO] Query:SELECT project_task._,project_task_cstm._ FROM project_task  LEFT JOIN project_task_cstm ON project_task.id = project_task_cstm.id_c  WHERE project_task.id = 'd2ebfc29-8159-ee97-57ba-5815df287daf_screen_i_c' AND project_task.deleted=0 LIMIT 0,1
> Sun Oct 30 17:25:15 2016 [13155][1][INFO] Query Execution Time:0.0099649429321289

This is the start of the problem. Note that we inserted cstm id and project_task id as 'd2ebfc29-8159-ee97-57ba-5815df287daf'. However it is trying to fetch record id: 'd2ebfc29-8159-ee97-57ba-5815df287daf_screen_i_c'.

Possible Reason#2
From suitecrm.log:

> Sun Oct 30 17:25:15 2016 [13155][1][INFO] Query:SELECT screen_i_c FROM projecttask LEFT JOIN projecttask_cstm cstm ON cstm.id_c = projecttask.id WHERE projecttask.id= 'd2ebfc29-8159-ee97-57ba-5815df287daf'
> Sun Oct 30 17:25:15 2016 [13155][1][INFO] Query Execution Time:0.0093271732330322

Note the name of the tables:projecttask & projecttask_cstm. The query returns an error:
Sun Oct 30 17:25:15 2016 [13155][1][FATAL]  Query Failed: SELECT screen_i_c FROM projecttask LEFT JOIN projecttask_cstm cstm ON cstm.id_c = projecttask.id WHERE projecttask.id= 'd2ebfc29-8159-ee97-57ba-5815df287daf': MySQL error 1146: Table 'syswwsen_testsuite.projecttask' doesn't exist
#### Steps to Reproduce

1. Create a new field in project task by name o screen_i
2. The width and height are set to 768x432. ( I have tried multiple combinations).
3. Edit the editview and detailview for it to be reflected properly.
4. Try to create a record with an image added to the screen_i field.
5. Try to view the record created.
#### Context

We were trying to add images to project tasks. In our case the image is the end result of the task hence it is really important.

It should be medium since it is important to identify why are the wrong table names being picked up.
#### Your Environment

- SuiteCRM Version used:Version 7.7.4 & Sugar Version 6.5.24 (Build 509)
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Tested on multiple browsers
- Environment name and version (e.g. MySQL, PHP 7): PHP Version 5.4.45, Mysql: 5.5.52 
- Operating System and version (e.g Ubuntu 16.04):CentOS 6.x with cPanel x64

**Comment by chrisdent** [comment]
Hi!

I have the same problem. Version 7.9.6
Sugar Version 6.5.25 (Compilation 344)

MySQL error 1146: Table 'crm.projecttask' doesn't exist

My case is replicated in possible reason #2.

Hope you can help me fixing the bug.

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our blog post
