### ISSUE TITLE
oauth_access method call via rest not possible

### ISSUE THREAD

**Issue by HVStechnik** [salesagility/SuiteCRM#2515]
I'm trying to implement an oauth connector into a different system authenticating against SuiteCRM via the Rest API.
I was able to request a request_token and an access_token via the 'oauth_request_token' and the 'oauth_access_token' REST method. Consequently, the general access authorization is working well!
However, I then wanted to transfer the users primary email address and username to the second system in order to identify the user, who is logging in. That is not possible, because I wasn't able to get a session ID for the REST connection, which would allow me to use e.g. the 'get_user_id' or 'get_entry' methods in order to receive the user's email address and username.
#### Issue

According to the sugar Rest API documentation (https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Authentication/Oauth/) the Rest method 'oauth_access' should return a session ID, if the request is properly authenticated by the oauth 1 authorization header. 
This is not working, because the authorization header is not even checked:
In the SugarWebServices utility file (suite/service/v4/SugarWebServiceUtilv4.php) in line 457 ff. the function checkSessionAndModuleAccess does only check the oauth authorization header, if an oauth_token is set directly within the request. For an oauth 1 request however, the oauth_token is part of the request during authorization only. Once the authorization is established, the oauth_token is send in the authorization header only. 
#### Expected Behavior

If the request contains an valid oauth authorization signature and header, the rest API should work without a session. Or at least the oauth_access method should work, in order to return the session id for later Rest requests.
#### Actual Behavior

The requests fails, because no session id is given in the request and the oauth authorization header is not checked.
#### Possible Fix

Change the checkSessionAndModuleAccess function in order to check the oauth authorization header, if the header is available and if no session id is given. I solved the issue by checking the authorization header for all oauth_access requests:

```
function checkSessionAndModuleAccess($session, $login_error_key, $module_name, $access_level, $module_access_level_error_key, $errorObject)
    {       
    // added oauth_access method tweak to allow access without token and session
        if(isset($_REQUEST['oauth_token']) || ($_REQUEST['method'] == 'oauth_access')) {
              $session = $this->checkOAuthAccess($errorObject);
              $GLOBALS['log']->fatal("Session: $session");
        }
        if(!$session) return false;
        return parent::checkSessionAndModuleAccess($session, $login_error_key, $module_name, $access_level, $module_access_level_error_key, $errorObject);
}
```
#### Your Environment

Latest version of suiteCRM

**Comment by shogunpol** [comment]
@HVStechnik  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
