### ISSUE TITLE
Cannot Deploy new modules or export modules after update to 7.7.6

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2517]
Hi, after upgrade to 7.7.6, last week we go to modify some fields of personalized modules, and cannot deploy. (Make's anything), and cannot export... (Make's anything)
#### Your Environment

- SuiteCRM Version used: 7.7.6
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
- Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP7
- Operating System and version (e.g Ubuntu 16.04): W 2012 R2

We go to module:

![mod1](https://cloud.githubusercontent.com/assets/20840700/19840576/40c5d40e-9ef9-11e6-8be2-9d0c6cd37de9.PNG)

we go to deploy

![mod2](https://cloud.githubusercontent.com/assets/20840700/19840578/4aeb9e64-9ef9-11e6-9928-09014945e54f.PNG)

result; Anything

![mod1](https://cloud.githubusercontent.com/assets/20840700/19840580/5750571c-9ef9-11e6-8e39-8c04246238a2.PNG)

I attach php error, but i think these errors has no relation with this, but, exists some errors relateds to SUITECRM.

[errorphp.pdf](https://github.com/salesagility/SuiteCRM/files/560804/errorphp.pdf)

**Comment by GrupImatica** [comment]
I tested to create a new module, and when i press SAVE, cannot make anything :(

**Comment by GrupImatica** [comment]
More information:

When i add some field in existing module i get this errors:

![1](https://cloud.githubusercontent.com/assets/20840700/19847991/caa106ac-9f4a-11e6-8c2d-69b7a61751ba.PNG)

But Field is created on module without any problem.

But when i deploy i get error:

![2](https://cloud.githubusercontent.com/assets/20840700/19848018/f7c40ba2-9f4a-11e6-8e77-011dbac642d7.PNG)

**Comment by GrupImatica** [comment]
Hi, i restored a Backup and the upgraded to 7.7.6 and works fine. Mmm, how can i detect really were making problem :/

**Comment by gunnicom** [comment]
I have the same Problem in 7.7.7 and 7.7.8

**Comment by gunnicom** [comment]
In case someone else has this problem. I fixed it for me now by:
    sudo rm cache/include -R
