### ISSUE TITLE
Using iCal in Google with cyrillic

### ISSUE THREAD

**Issue by vistar** [salesagility/SuiteCRM#252]
I use iCal link: http://imgur.com/GOT8qUPl.png
With google calendar, and use Cyrillic letters for events: http://imgur.com/T2yJ2vAl.png
On google calendar I see: http://imgur.com/GxRmuIml.png

Error on decode to iCal?

**Comment by vistar** [comment]
I view a genarated iCal file.
And see:
SUMMARY:ÐÐ¾Ð²ÑÐ¾ÑÐ½ÑÐ¹ Ð·Ð²Ð¾Ð½Ð¾Ðº - This is real "Повторный звонок"

This decoded are: ISO-8859-1 → UTF-8 in file: https://github.com/salesagility/SuiteCRM/blob/934ac6b0296cbfbbc62c4566cd398566536bee49/modules/iCals/iCal.php

**Comment by chandon** [comment]
This PR should solve the encoding problem #1163
