### ISSUE TITLE
Where do I submit a change to the Joomla! extension for Advanced Open Portal

### ISSUE THREAD

**Issue by eclecticeasel** [salesagility/SuiteCRM#253]
There is a small change needed to the controller in order to be compatible with Joomla! 3.4.x.

Around line 18 

function display($cachable = false) 
needs to be changed to 
function display($cachable = false, $urlparams = false) 

I have a patch ready I just can't figure out where to put it.

Thank you

**Comment by JimMackin** [comment]
Thanks for bringing this up. There wasn't a public repo with the Portal source. I don't have permission to create a repo under the salesagility organisation so have created the repo here: https://github.com/JimMackin/SuiteCRM-Portal-Joomla. This will get transferred to the salesagility organisation next week.

**Comment by JimMackin** [comment]
Now available at https://github.com/salesagility/SuiteCRM-Portal-Joomla
