### ISSUE TITLE
Report Writer - Boolean FIeld will not export to CSV

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#2531]
#### Issue
When you create a report with a boolean field and export to CSV the value is lost

#### Expected Behaviour
If the value is true it should show in the CSV as 1 otherwise it should be 0

#### Actual Behaviour
No values are passed in the export

#### Context
We need this for our reports
Status should be Medium

##### Fix of sorts
This is caused by line 925 in modules/AOR_Reports/AOR_Report.php

$csv .= $this->encloseForCSV(trim(strip_tags(getModuleField($att['module'], $att['field'], $att['field'], 'DetailView',$row[$name],'',$currency_id))));

getModuleField is in modules/AOW_Workflow/aow_utils.php

it returns the html for a checkbox for boolean fields that gets stripped

To get around this I modified the code:

$t = getModuleField($att['module'], $att['field'], $att['field'], 'DetailView',$row[$name],'',$currency_id);
                    	if (preg_match('/checkbox/',$t)) {
                    		$csv .= $row[$name];
                    	}else {
                    	$csv .= $this->encloseForCSV(trim(strip_tags(getModuleField($att['module'], $att['field'], $att['field'], 'DetailView',$row[$name],'',$currency_id))));
                    	                   	}

This now returns a 0 or 1 to the CSV
#### Your Environment

* SuiteCRM Version used: 7.7.6

**Comment by pstevens71** [comment]
This fix needs a couple of tweaks to work with current version as code has changed, but it does work on 7.8.18 LTS.  Just needs a couple of extra brackets.  Thanks!
