### ISSUE TITLE
Suite P Menu with fixed width (mostly issues with translations)

### ISSUE THREAD

**Issue by VRedguard** [salesagility/SuiteCRM#2540]
#### Issue

When switching to another language 
#### Expected Behavior

Width adjustable to largest item in menu.

#### Actual Behavior

Cut after X width, so similar items cannot be différenciated appart. 
#### Possible Fix

Use a width with % instead of fixed number of pixels.

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

Cannot pick similair items 

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 54.0
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):
![capture d ecran 2016-11-01 a 09 24 11](https://cloud.githubusercontent.com/assets/23078474/19891207/734c7cf8-a015-11e6-88e6-da3233d62f7f.png)

**Comment by edilex** [comment]
PS Works well /correct behavior in suite 7

**Comment by daniel-samson** [comment]
Fixed in https://github.com/salesagility/SuiteCRM/pull/2463

**Comment by edilex** [comment]
Yes, but with the new fix, when the action menu is to the complete left, the menu goes outside the window.

**Comment by edilex** [comment]
![capture d ecran 2016-11-03 a 09 39 55](https://cloud.githubusercontent.com/assets/23078474/19968149/ba35242c-a1a9-11e6-9c34-27493c01b1a3.png)

**Comment by daniel-samson** [comment]
Hi @edilex. Thanks for testing it :+1:. I have updated my pull request so that the menu now correctly displays when there is only one tab.

![only-child fix](https://cloud.githubusercontent.com/assets/12231216/19971189/39966f06-a1d6-11e6-9d0f-a3229e4906b8.png)
