### ISSUE TITLE
"Email Settings" section doesn't initially display when editing User (Firefox)

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#2544]
#### Issue

It appears that, when using Firefox, the "Email Settings" section on the User Profile Editview doesn't initially appear.
Looks like you have to change tab to something else, (i.e, Password), then change back to the "User Profile" tab to cause the "Email Settings" section to appear.

#### Expected Behavior

"Email Settings" section should appear without issue.

#### Actual Behavior

"Email Settings" section does not display without issue initially, user needs to move through tabs.

#### Possible Fix

-
#### Steps to Reproduce

1. Ensure you're using Firefox
2. Edit any User Profile
3. Try to find "Email Settings" section
4. Change tab to "Password"
5. Change tab back to "User Profile"
6. Then, you should see the "Email Settings" section

#### Context

I feel like this is probably Low Priority, as the section can be forced to appear, and is only an issue on Firefox.

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.2
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
