### ISSUE TITLE
Inline editing message displays multiple times

### ISSUE THREAD

**Issue by pkudyba** [salesagility/SuiteCRM#2545]
#### Issue

Sometimes during inline editing message "You have clicked away..." displays two or three time in row when I click on cancel button. 
#### Expected Behavior

Message should display only once.
#### Actual Behavior

Message about inline editing displays two or three times in row.
#### Steps to Reproduce

For example when I'm editing address in Accounts module message displays two times.

#### Your Environment

* SuiteCRM 7.7.6
* Google Chrome 54.0.2840.71
* MySQL, PHP 5.6
* Debian jessie

**Comment by shogunpol** [comment]
@pkudyba , is this when you click cancel and then click somewhere else on the page ?.

**Comment by pkudyba** [comment]
When i mark some field for inline editing and click ouside the message show
up. I click cancel on message and second message popup immediatlety. When I
click cancel second time focus goes back to edited field.

2016-11-02 16:38 GMT+01:00 Jerzy <notifications@github.com>:
