### ISSUE TITLE
Contact saved even when invalid email specified in Suite 7 and Suite R themes

### ISSUE THREAD

**Issue by simjker** [salesagility/SuiteCRM#2551]
#### Issue
In Suite 7 and Suite R themes, if you create a contact (using the 'Create' button on the Search Contacts page) with an invalid email address and click save then the contact is saved with an empty email address

#### Expected Behavior
When creating a contact, if you specify an invalid email address for the contact and click save then the field in error is highlighted with appropriate feedback (Invalid Value: Email Address) provided.

#### Actual Behavior
When creating a contact, if you specify an invalid email address for the contact and click save then the contact is saved with an empty email address.

#### Possible Fix
Change Create button on Search Contacts page not to be AJAX.

#### Steps to Reproduce
[SuiteCRM Demo](http://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3DEditView%26return_module%3DContacts%26return_action%3DDetailView)
1. On the menu, click Sales -> Contacts
2. On the Search Contacts page, click the Create button (on the right above basic search panel)
3. On the Create page, specify a Last Name and an invalid email address and click Save
4. Contact is saved and contact details page is displayed with blank email.

Note: The create functionality works as expected if the Create screen is invoked from the + menu option or the Contacts->Create Contact menu option.

#### Context
Evaluating latest version of SuiteCRM

#### Your Environment
* SuiteCRM Version used: 7.7.6
* SuiteCRM Theme: Suite 7 and Suite R
* Browser name and version: Chrome Version 54.0.2840.71 m
* Environment name and version: SalesAgilty SuiteCRM Demo
* Operating System and version: SalesAgility SuiteCRM Demo

**Comment by shogunpol** [comment]
@simjker , an issue has been tested on recent version of SuiteCRM(7.7.9), and not appear, can you confirm, and close an issue?

**Comment by simjker** [comment]
Hi,
Just tested this on the SuiteCRM 7.7.9 demo site and the issue is still there for both the Suite 7 and Suite P themes.

**Comment by shogunpol** [comment]
@simjker , did you used fresh install or upgraded once?

**Comment by simjker** [comment]
I used http://demo.suiteondemand.com which is currently running 7.7.9 though I don't know whether it is a fresh install or an upgrade

**Comment by blloyd78** [comment]
Further testing suggests that the email address is not saved for any new contact created from the Inbox even when there is a valid entry in that field.

**Comment by gunnicom** [comment]
Maybe my issue was similar but was closed as suite team could not find it.
https://github.com/salesagility/SuiteCRM/issues/2575

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)
