### ISSUE TITLE
Module Loader does not list installed modules

### ISSUE THREAD

**Issue by primozn** [salesagility/SuiteCRM#2563]
After update from 7.7.5 to 7.7.6.
If I go back to Module loader, no module is listed.

Screenshot: http://screencast.com/t/yJhq9lEX8edt

#### Your Environment
SuiteCRM Version used: 7.7.6
Browser name and version: Chrome 52.0.2743.116 m
Environment name and version: MySQL, PHP 7.0.5
Operating System and version: Windows NT WIN7-SRV 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586

**Comment by shogunpol** [comment]
@primozn , did you set proper permissions and also did you done repair and rebuild?

**Comment by primozn** [comment]
I did...

**Comment by shogunpol** [comment]
@primozn , can you try uninstall your install modules, and install them after upgrade? I see is also not default language installed, which potentially may causing an issue to as well.

**Comment by primozn** [comment]
As you can see, i have no modules in my module loader, so i can't uninstall them. I'm using 2 modules, one is language packet and other is QuickCRM. Can i uninstall them manually? I can also give you access (FTP & admin) and you can check it direct on site...

**Comment by primozn** [comment]
After upgrade to 7.7.7 today, module loader is working again. Funny thing...
http://screencast.com/t/ReOb4BlIA

**Comment by primozn** [comment]
Now i tried to add new language pack as module. After uploading file same issue returned...

**Comment by shogunpol** [comment]
The translations for SuiteCRM are made by: https://crowdin.com/project/suitecrmtranslations 
and can be contributed back there and are unable to be updated in this project on github
@horus68 may be able to help with this.

**Comment by primozn** [comment]
I don't thing the problem is in translation pack. Because i din't even install it. I just upload it and **Module Loader** stop working.

**Comment by shogunpol** [comment]
@primozn , i did follow your steps, and been not able replicate an issue. Can you download again package from : https://crowdin.com/project/suitecrmtranslations/sl#  (i assume this is right language pack), and reinstall again.

**Comment by primozn** [comment]
Ok, problem solved. If you access site through CroudFlare 'Module Loader' stop working. If i access site direct 'Module Loader' works perfect again.
