### ISSUE TITLE
SuiteR Theme Multiple Email Address issues on Contacts

### ISSUE THREAD

**Issue by sieberta** [salesagility/SuiteCRM#2566]
#### Issue
Cannot add additional email addresses, and attempting to causes deletion of the email_addr_bean_rel record.
Also, the radio buttons and checkboxes lost their labels

![image](https://cloud.githubusercontent.com/assets/21241249/20020795/0691d3e0-a2a1-11e6-9f73-d4b9648870b8.png)

#### Expected Behavior
When you click the [+] next to Email address, you would get another box to enter another email address for a contact.

#### Actual Behavior
Nothing appears to happen, but if you save the record the email_addr_bean_rel record 'deleted' flag is set.  You then cannot add another email address.

#### Possible Fix
I'm not sure, but I can temporarily fix records this happens to by changing the deleted flag back to a '1'.

#### Context
This is high priority from my perspective.  I cannot replicate on demo.suiteondemand.com, but I'm not in the SuiteR theme on that platform, and I'm not sure it goes through the upgrades the same way.  This issue, to my knowledge, did not show up until version 7.7.6

#### Your Environment
* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): LAMP stack (PHP7)
* Operating System and version (e.g Ubuntu 16.04): CentOS

**Comment by mattlorimer** [comment]
look like a caching issue try clearing you browser cache doing a quick repair and rebuild and Rebuild JS Grouping Files

**Comment by sieberta** [comment]
@mattlorimer 

Bingo!  Don't know how you know that (would appreciate any feedback on how you diagnosed or knew that).  And sorry it was listed here, apparently it would've more appropriately been a forum topic!

This is fixed and can be closed...
