### ISSUE TITLE
Improve web cache management

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#2572]
#### Issue

Would be great to Auto detect when caching becomes an issue.  Currently this bug forces the user to experience a non working application for some time, until they either figure it out, or are told, you need to Clear Your Browser Cache (CYBC), do a Quick Repair and Rebuild (QRR) and Rebuild JS Grouping Files (RJSGF).

#### Expected Behavior

The SuiteCRM application framework's cache management code should be upgraded so as to detect updated web assets (css, js, graphics, documents, etc) and automatically recompute the hash, which should be appended before the extension.  This is a standard technique to age out/force reload in the browser of these assets,

#### Actual Behavior

User gets stale web assets and often bad data in their broswer - javascript, graphics, css, html - until they figure out they need to Clear Your Browser Cache (CYBC), do a Quick Repair and Rebuild (QRR) and Rebuild JS Grouping Files (RJSGF).
 
#### Possible Fix

1. Upgrade the cache control code in the sugarcrm php framework.
2. Install a free open source cache control engine.
3. Configure the web server to use caching better, Etags, etc.  This is not ideal. Better to use software to do it for you, less chance of mucking it up.

#### Steps to Reproduce

1. See #2566 for steps to reproduce.  
2. Many other reports of the same bug.
3. This bug has been around for a long time.

#### Context

Hard to predict when this bug might happen.
The browser cache is managed separately from the SuiteCRM cache.
SuiteCRM app is not aware that its cache can become out of alignment with the browser cache.
A better more modern cache engine would solve this.

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6  PHP 7
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve web cache management](https://trello.com/c/kZ17VBZX/55-improve-web-cache-management)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by chris001** [comment]
Similar to my issue #3030 Add PSR-6 this is vital for performance and reducing a poor user browser experience of receiving outdated cached pages.

**Comment by Mausino** [comment]
![2019-01-04_1403](https://user-images.githubusercontent.com/5773777/50689696-0977e000-102b-11e9-8178-5224ae5fd35d.png)

This somtimes happen when server shut down

**Comment by SinergiaCRM** [comment]
We want to support @chris001 idea in improving web cache management. 

Whenever we update styles or JS code, users are always confused until they manage to clear their browser cache.

@samus-aran, for some reason we can't access Trello with our github account and vote the suggestion, we vote it here :1st_place_medal:
