### ISSUE TITLE
Add Dashlets tabs not working

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#2574]
#### Issue
On an upgraded instance of v7.7.6, when I click the "Add Dashlets" link on the home page, the popup opens fine, but when clicking the different tabs (modules, charts, tools, web and the search functionality) nothing happens. This works correctly on a clean install of v7.7.6.
![image](https://cloud.githubusercontent.com/assets/20977561/20061649/a90a6504-a4ce-11e6-8b8e-cc1f9f70dd71.png)

#### Expected Behavior
Should cycle through tabs like in a clean install
![image](https://cloud.githubusercontent.com/assets/20977561/20061671/ca521d2e-a4ce-11e6-86c7-30b1d9e7e7c2.png)

#### Actual Behavior
Nothing happens when clicking the other tabs (I can add dashlets from the default modules tab in case you were wondering). No console errors but in the apache logs, I get the following smarty error that does not appear in the functional clean install logs. I know it's only a php warning, but that's the only difference I've noticed between my upgrade and clean install.

PHP Warning:  Smarty error: Missing required field:file in /var/www/crm/include/Smarty/Smarty.class.php on line 1094, referer: /index.php?module=Home&action=index

#### Your Environment
SuiteCRM v7.7.6
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 54 on Windows 10 (same behavior with other browsers)

**Comment by staganyi** [comment]
I am able to navigate through the "add dashlets" tabs under the Suite7 theme. Appears to be a SuiteP theme issue.

**Comment by shogunpol** [comment]
@staganyi , some additional questions, to help me replicate issue:
1. Can you type history of upgrades (from which one to which one, if is a chain of upgrades, please provide details);
2. What type of SQL you use;
3. Are there any customisation done on previous versions(If yes please provide details).

**Comment by staganyi** [comment]
1. I've been a SuiteCRM user since the beginning, therefore I've been upgrading all the way since v7. Recently I've upgraded through all the v7.7 releases (7.7 to 7.7.7).

2. MySQL v5.5

3. No customization to the core, only studio layout and field changes.

**Comment by shogunpol** [comment]
@staganyi , from beginning it doesn't tells me what path of the upgrade you choose (there are at least 2 different once), if you cannot provide this information i cannot start replication process, in this case i suggest close this issue.

**Comment by staganyi** [comment]
7.2.1 to 7.3.2
7.3.2 to 7.4.3
7.4.3 to 7.6.4
7.6.4 to 7.7.0
7.7.0 to .1 .2 .3 .4 .5 .6 & now .7

I think this is something that was recently introduced because I think this was working in the earlier 7.7 releases and like I mentioned, only present with the SuiteP theme. Suite7 works fine.

**Comment by shogunpol** [comment]
@staganyi , the issue has been tested on provided upgrade path and not appear, this clearly indicate that fact it is not a core issue, it can be multiple things which is very unique in your instance, so customisation, download error and so on. So if you thing it is a core issue, you have to provide some evidence for further investigation. If you cannot provide to anything what can specify issue i suggest to close an issue or redirect to our community forum.

**Comment by staganyi** [comment]
Can you direct me to the piece of code that shows/hides those tabs so I can debug myself?

**Comment by shogunpol** [comment]
@staganyi  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
