### ISSUE TITLE
Unused language strings (EmailMan)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2576]
See #2444 

['LBL_IN_QUEUE_DATE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L52
['LBL_DISCLOSURE_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L61
['LBL_DISCLOSURE_TEXT_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L62
['LBL_DISCLOSURE_TEXT_SAMPLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L63
['LBL_NOTIFY_SEND_BY_DEFAULT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L117
['LBL_OLD_ID']
https://github.com/salesagility/SuiteCRM/tree/v7.7.6/modules/EmailMan/language/en_us.lang.php#L119

**Comment by samus-aran** [comment]
Looks like the following labels are used:
- LBL_IN_QUEUE_DATE
The rest can be removed.

**Comment by shogunpol** [comment]
@samus-aran , my Pull Request(Fix proposal), keep "LBL_IN_QUEUE_DATE" in file.
