### ISSUE TITLE
Module filter on dropdown/multi select shows no results

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#2581]
#### Issue
Do a search in any module on a dropdown/multi-select value produces no result and shows a query error in the log "Unknown column ..."

#### Expected Behavior
Results would be shown

#### Actual Behavior
No results

#### Possible Fix
Quote drop down search values

#### Your Environment
* SuiteCRM Version used: 7.7.7
* Browser name and version : chrome 54.0.2840.90 (64-bit)
* Environment name and version : 5.5
* Operating System and version : Ubuntu 14.04

**Comment by mikesolo** [comment]
The problem file is include/SearchForm/SearchForm2.php

Lines 787 to 807
