### ISSUE TITLE
Unused language strings (Emails) 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2582]
See #2444 

['LBL_EMAIL_QUOTE_FOR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L58
['LBL_QUOTE_LAYOUT_DOES_NOT_EXIST_ERROR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L59
['LBL_QUOTE_LAYOUT_REGISTERED_ERROR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L60
['LBL_FORWARD_HEADER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L125
['LBL_SAVE_AS_DRAFT_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L147
['LBL_SEND_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L154
['LBL_BUTTON_RAW_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L212
['LBL_BUTTON_FORWARD_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L222
['LBL_BUTTON_REPLY_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L223
['LBL_BUTTON_DISTRIBUTE_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L247
['LBL_BUTTON_GRAB_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L250
['LBL_SELECT_TEAM']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L267
['LBL_ACTIVITIES_REPORTS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L292
['LBL_EMAILS_NO_PRIMARY_TEAM_SPECIFIED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L302
['LBL_CONTACTS_SUBPANEL_TITLE_SNIP']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Emails/language/en_us.lang.php#L397

**Comment by samus-aran** [comment]
Looks like we use the following labels:
- LBL_EMAILS_NO_PRIMARY_TEAM_SPECIFIED
But the rest can be removed.

**Comment by shogunpol** [comment]
@samus-aran , LBL_EMAILS_NO_PRIMARY_TEAM_SPECIFIED - has not been removed in PR2601
