### ISSUE TITLE
SuiteP - Inbound Emials - 2 issues

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2589]
#### Issue

1. [ISSUE] I can't see the column header names - same color as background
2. [ISSUE] The checkbox position in bar is wrong, it isn't in middle of bar height... but somewhere down

![inbound_emails](https://cloud.githubusercontent.com/assets/5773777/20135043/0f44e1a0-a66e-11e6-953a-02863b1b56ea.png)

#### Steps to Reproduce

1. Go to Admin 
2. Choose Inbounds Emials

#### Your Environment

* SuiteCRM Version used: 7.7.7 SuiteCRM
* Browser name and version: Chrome 64bit 54.x
* Environment name and version: 5.6 MySQL & PHP
* Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
@Mausino , an issue has been tested on recent version of SuiteCRM(7.7.9), and seems to problem not appear any more, module have now nice improved layout and boxes are in proper positions, can you test it and close issue if you happy about solution?

**Comment by Mausino** [comment]
Tested and @shogunpol  thank you that you solved them. I am closing the ticket
