### ISSUE TITLE
Unused language strings (Employees) 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2590]
See #2444 

['LBL_NEW_EMPLOYEE_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L73
['LBL_EMPLOYEE_SETTINGS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L81
['LBL_CREATE_USER_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L116
['LBL_FAVORITE_COLOR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L117
['LBL_PORTAL_ONLY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L133
['LBL_FF_CLEAR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L139
['LBL_EXT_AUTHENTICATE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L141
['LBL_PORTAL_ONLY_USER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L147
['LBL_PSW_MODIFIED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L148
['LBL_SHOW_ON_EMPLOYEES']
https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Employees/language/en_us.lang.php#L149

**Comment by samus-aran** [comment]
We use a couple of those labels
- LBL_EXT_AUTHENTICATE
- LBL_PORTAL_ONLY_USER
- LBL_PSW_MODIFIED
- LBL_SHOW_ON_EMPLOYEES

The rest can be removed.

**Comment by shogunpol** [comment]
@samus-aran , labels you mention has not been removed from file in PR2603.
