### ISSUE TITLE
Reports: After Upgrade (to 7.7.6) grouping on assignment displays ID and not name 

### ISSUE THREAD

**Issue by aproposnix** [salesagility/SuiteCRM#2595]
#### Issue
Prior to release 7.7.6 I was able to group my opportunity report based on the assigned user name. Since Upgrading to 7.7.6 the group label (which should be the name of the assigned user) is showing the ID of the assigned user instead of his name. 

Detail From the SuiteCRM forum: 
Earlier this week, I upgraded my server to 7.7.6. After doing that I noticed that reports using "assigned" grouping in my opportunities reports no long shows the names of the assignee but the ID number of the Assignee. In the same report, for each line, the assignee name *is* shown. Just not the group label. Anyone know of a way to fix this?

I have since upgraded to 7.7.7 with the same result. 

![selection_348](https://cloud.githubusercontent.com/assets/6204273/20143707/58411d0c-a69a-11e6-93e7-893f6a9fddaa.png)

#### Expected Behavior
The assigned users name will be the label for the group and not the assigned user ID. 

#### Actual Behavior
I cannot display the user name for the group label. 

#### Possible Fix
Not known at this point. 

#### Steps to Reproduce

1. Create a report (based on opportunities) with "assignee" as the "group by "
2. Save Report and view

#### Context
The Report cannot be distributed without manually modifying it. 

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
 - Chrome 
 - Firefox v50 64bit Linux
* Environment name and version (e.g. MySQL, PHP 7): = 
 - MySQL v5.5.49
 - PHP v5.6.24
 - nginx - 1.6.2
* Operating System and version (e.g Ubuntu 16.04):
  - Debian Jessie

**Comment by mmadey** [comment]
Hi,

I have the same issue, but with an addition. Not only the Assigned user is not shown, but the data is repeated as many times as there are items for the specified user (3 times in this case). Version is 7.7.7

With kind regards,
Marcin

![error id](https://cloud.githubusercontent.com/assets/18421032/20176844/f9922e94-a749-11e6-9eaf-06fd7141ec4a.png)

**Comment by ijdavie** [comment]
There is a workaround for this as you can select the <module>:assigned to user, within this you can select the username which you can then group on. This should give the result you expect.

**Comment by mmadey** [comment]
Hi,

ijdavie, your solution solved the issue with displaying the proper user name instead of ID. Unfortunately it did not solve the issue with multiple instances of report for the same user.

- Marcin

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)
