### ISSUE TITLE
suitecrm version 7.2.5 beta: after session timeout - not inline editing notification

### ISSUE THREAD

**Issue by selimerunkut** [salesagility/SuiteCRM#261]
After a suitecrm session timeout there is no indication that inline editing is not available any more. It's al litle confusing for the user as he can edit the records but of course nothing is saved.
Only after reloading the page the login screen is displayed and the user knows that his session had enden.

**Comment by darthtang** [comment]
For this,

if they doubled clicked on something and are in the middle of editing but do not save nor do they click away....
Should the user be notified that the session is about to time out and be asked if they want to prolong the session? Or should another variation of notifications and questions be presented to the user?

**Comment by darthtang** [comment]
Im guessing it would be a bit rubbish if the user was told that ' your session has timed out. you were in the middle of inline editing but didnt save so if you made changes they will not be saved' 
any thoughts?

**Comment by JimMackin** [comment]
Not sure it's possible to avoid this. If the user leaves for an extended period of time then the session is gone. I think a message and/or disabling the edits is enough.

**Comment by darthtang** [comment]
I agree! once the session is lost...IT is lost and wont be able to 'travel back in time' so to speak! 
This issue is going to be resolved by adding an information alert warning the user that 'they have not saved whilst in the middle of editing! '

**Comment by shogunpol** [comment]
The replication process of this bug it fails, mean s in version of SuiteCRM (7.7), bug doesn't appear, when double click on inline editing records (when session is expired), you see pop-up with appropriate message.
The behaviour of the inline editing records has been tested in many different modules.

Suggestions: Close bug
