### ISSUE TITLE
Bug with line item

### ISSUE THREAD

**Issue by danicv94** [salesagility/SuiteCRM#2616]
It is explain right there:
https://suitecrm.com/forum/suitecrm-7-0-discussion/11950-input-in-line-item-change-to-html-code

There is an image explaining what is happening in the link. I dont know how to insert img in this web sorry.

Hey,

I'm having a weird problem right here, when i'm in the line items, in the field service name, i write for example "HI FORUM" (with ""), and then save, and when i click edit this text changed to "HI FORUM"
Is this on purpose? If it is, how can i change it?

**Comment by shogunpol** [comment]
@danicv94 , please follow the template of the github issue guideline, otherwise will be closed. To replicate issue i need to have all answers from template.

**Comment by sanchezfauste** [comment]
We believe that this is a duplicated of #3388 bug

**Comment by Dillon-Brown** [comment]
Duplicate. I'm closing this one as its superseded by #3388 which provides more detailed information.
