### ISSUE TITLE
suitecrm version 7.2.5 beta: Inline editing  - editing URLs

### ISSUE THREAD

**Issue by selimerunkut** [salesagility/SuiteCRM#262]
If a URL is to be edited , the user must double click next to it to edit the URL with inline editing, else the URL is opened in the browser.

**Comment by willrennie** [comment]
This is standard functionality of inline editing, of course if you click the URL it will direct you to where the URL is pointing to. Do you have a usability suggestion?

**Comment by selimerunkut** [comment]
it would be nice if suitecrm could distinguished between single click for opening a URL and double click to edit it.

**Comment by willrennie** [comment]
It does? All inline editing fields require a double click.

**Comment by willrennie** [comment]
Thanks for the suggestion, agreed it would be nice to distinguish.

**Comment by willrennie** [comment]
This issue has been resolved in the latest releases.
