### ISSUE TITLE
Advanced search with Dropdown type fields

### ISSUE THREAD

**Issue by babalou** [salesagility/SuiteCRM#2630]
#### Issue
In the advanced search of the Accounts module (or Contacts module), the search results is "No results found." when I selected 1 (or several) item(s) in criteria linked with a dropdown type fields (ex. : "Assigned to", "Salutation"...), although some Accounts (or Contacts) matches the criteria.

This issue seems to be related with dropdown type fields, because I don't have any problems with criteria linked with (for ex.) multienum type fields.

#### Steps to Reproduce
1. Open the demo instance of SuiteCRM (http://demo.suiteondemand.com).
2. Go to the Contacts module and open the advanced search.
3. Select "Chris Olliver" in the criteria "Assigned to".
4. Click on "Search" button.
5. Result is  "No results found." although some contacts are assigned to the user "Chris Olliver".

#### Context
I think it's a medium or high priority because it's an abnormal behavior:
- which prevents the search in several modules.
- which seems to be only in the 7.7.x branch (I didn't notice this issue in the 7.6.x branch) .

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.2
* Environment name and version (e.g. MySQL, PHP 7): Apache 2.4.23 / PHP 5.5.38 / MySQL 5.6.33.
* Operating System and version (e.g Ubuntu 16.04): CentOS 6.8

**Comment by ledaihoang** [comment]
Fixed in commit [f78af79](https://github.com/salesagility/SuiteCRM/commit/f78af79153ace354f93476c9a8cba8ffea1e177e#diff-3376daab197e71a097148f580dfdd038)

**Comment by babalou** [comment]
Hi,

I checked the fix. I modified the /include/SearchForm/SearchForm2.php (as explained in f78af79), do a quick repair, but I have the same issue : 
Search result is "No results found." when I select an item in a criteria linked with a dropdown type fields (ex. : when I select a salutation).

**Comment by milosni** [comment]
To fix the bug, change the line 794 in include/SearchForm/SearchForm2.php:
From: 
$field_value .= $val;
To: 
$field_value .= $db->quoteType($type, $val);

Values from Dropdown are not quoted in SQL query for search, and this will cause error in sugarcrm.log.

**Comment by mattlorimer** [comment]
that is the wrong commit refernced this commit addresses the issue [e736133](https://github.com/salesagility/SuiteCRM/commit/e736133f56e0abf3c9b3f853fd122cde729a3612)

However this is a duplicate issue of #2581
