### ISSUE TITLE
Import mapping publish button

### ISSUE THREAD

**Issue by sanchezfauste** [salesagility/SuiteCRM#2635]
When you publish an import mapping on "Targets" module, other users can not see it.

#### Issue
When you click the button "Publish" the text changes into "Cancel Publish" but it's not working. The console of navigator throws the following error:

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parse (https://crm.example.com/cache/include/javascript/sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:262:3983)
    at Object.success (https://crm.example.com/index.php?module=Import&action=Step1&import_module=Prospects&return_module=Prospects&return_action=index:1148:53)
    at Object.handleTransactionResponse (https://crm.example.com/cache/include/javascript/sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:55:4422)
    at https://crm.example.com/cache/include/javascript/sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:55:3935
parse	@	sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:262
success	@	index.php?module=Import&action=Step1&import_module=Prospects&return_module=Prospects&return_action=…:1148
handleTransactionResponse	@	sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:55
(anonymous function)	@	sugar_grp1_yui.js?v=HqrM2QCOmCUJMC4kIkGV5w:55
```

#### Expected Behavior
When you publish an import mapping other users have to see it when they use the import option.

#### Actual Behavior
When you publish an import mapping other users can not see it.

#### Steps to Reproduce

First of all we have to create the file "Targets_test.csv" with the following content:

```
"Last Name","Mobile","Office Phone","Home"
"Estes","(579) 711-4337","(480) 479-6818","(979) 669-1135"
"Chambers","(376) 862-2400","(339) 348-9133","(583) 987-6124"
"Sousa","(348) 930-8656","(926) 996-4659","(684) 630-2229"
```

##### Prospects Import

1. Enter in "Prospects" module (displayed as "Targets" module).
2. Once you're inside the module click the "Import Targets" option.
3. Upload the attached CSV sheet "Targets_test.csv", select "Create new records and update existing records" option and after click "Next".
4. Once you press the next button you're on the second step of the import. Click "Next".
5. Now you have to map the CRM fields with the CSV sheet fields. It is OK because the CSV has the same column names as CRM, so simply click "Next".
6. In the fourth step in the field "To save the import settings, provide a name for the saved settings:" type "prospects_mapping_test" and press "Import now".
7. The import is finished. Click the button "Exit".

##### Publish the mapping to all users

1. You're on the main screen of "Targets" module. Now you have to click "Import Targets" option again.
2. On the published mappings it will appear the mapping we saved as "prospects_mapping_test" and next to it you have two options: "Publish" and "Delete". You have to click "Publish" option. Here is when you can see the reported error on the browser console (Details at the Issue section of this bug).
3. At this point this fields mapping should be accessible to all users, so let's try it.

##### Check if mapping is accessible to another users

1. Login with another account and access the "Targets" module.
2. Go to "Import Targets" option.
3. Observe that in "To use pre-set import settings, select from below:" option, does not appear the "prospects_mapping_test" that we have published before with the other account.

#### Context
We created a custom mapping with one of our users. Now we tried to publish the specific mapping for all the users to use it, but other users can not see it.

#### Your Environment
* SuiteCRM Version used: Versión 7.2.1, Sugar Versión 6.5.20 (Build 1001) and Versión 7.7.6, Sugar Versión 6.5.24 (Compilación 509).
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Versión 54.0.2840.90 (64-bit).
* Environment name and version (e.g. MySQL, PHP 7):
    - Server version: Apache/2.4.7 (Ubuntu). Server built:   Sep 23 2015 15:34:04
    - mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
    - PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.3 LTS x64

**Comment by shogunpol** [comment]
@sanchezfauste  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by sanchezfauste** [comment]
This is not a question. It's a SuiteCRM core bug. We have updated the description of the bug in order to make easy to reproduce and understand. Please, can you check it and reopen the issue?

**Comment by ChangezKhan** [comment]
Sorry, I mistakenly closed pull request no. #2845 and deleted branch. Now, I am unable to reopen the same pull request.

**Comment by horus68** [comment]
You need to ask in the PR to reopen it.
You can also create a new branch from hotfix and recreate the closed PR and make a reference to this issue so its linked.

Hint: when removing code do not comment out lines, just delete the lines not wanted

**Comment by ChangezKhan** [comment]
Hey @horus68, I tried to create a branch from hotfix and recreated the closed PR, but couldn't merge it as it was saying there are no changes in hotfix and branch created from hotfix. 
I'll ask in the PR to reopen it. Thanks anyway. Also, I'll keep your advise in mind.

**Comment by shogunpol** [comment]
You can do it just by create new PR, only think you branch must have different name (can be old one plus "a" in end, to keep sort of consistency), other things can be exactly the same.
