### ISSUE TITLE
Campaign: custom views and metadata are ignored

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#2638]
#### Issue

I need a further subpanel in the campaign module.
So I copied the files modules/Campaigns/metadata/subpaneldefs.php and modules/Campaigns/views/view.detail.php  to the custom structure and do some modifications which never get applied.
Only when I edit the source files it works.

#### Expected Behavior

custom directory for Campaings should be read from application
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):  php 5.9
* Operating System and version (e.g Ubuntu 16.04): Ubunto 14.0.1

**Comment by shogunpol** [comment]
Response - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
