### ISSUE TITLE
Email Templates parse Dynamic DropDown fields as keys not as labels

### ISSUE THREAD

**Issue by vladbar** [salesagility/SuiteCRM#2642]
#### Issue
Emails which are based on Email Templates with some fields that have variables representing Dynamic DropDowns have keys instead of values (e.g americas_bolivia instead of Bolivia)

#### Steps to Reproduce
1. Created a dropdown called ARC_Sub_Region in Admin -> Dropdown Editor

2. Created a field for the Contact module called 'Test Dropdown'. This field is a Dynamic Dropdown type field and has ARC_Sub_Region as its dropdown. Added this field to the EditView and DetailsView of the Contact module.

3. Went to the Contacts record for Britney Walraven (example user) and set the 'Test Dropdown' to Bolivia.

4. Created an Email template for testing the dropdown values. Where variable corresponding to the 'Test Dropdown' field is included.

5. Created a WorkFlow record to send emails based on the above mentioned template.

6. Made sure that Admin -> Email Settings is setup correctly and sent a test email.

7. Made sure that Process Workflow Tasks sheduler is active.

8. Made sure that crontab is running for my instance.

#### Expected Behavior
I should have received:

Hello Britney Walraven,
your chosen dropdown option is Bolivia .
Best Regards.

#### Actual Behavior
Hello Britney Walraven,
your chosen dropdown option is americas_bolivia .
Best Regards.

**Comment by vladbar** [comment]
This should be fixed by modifying modules/AOS_PDF_Templates/templateParser.php
line 63 change to
} else if (($field_def['type'] == 'radioenum' || $field_def['type'] == 'enum' || $field_def['type'] == 'dynamicenum') && isset($field_def['options'])) {

**Comment by yulahab** [comment]
Same problem is with non dynamic multiselect fields. I fix it with returning old funcitionality

`class templateParser
{

		// ADDED BY NS-TEAM
		function getMultiEnumVal($options,$module,$val_array){
			$res = array();
			foreach($val_array as $key => $val) {
				$res[$key] = translate($options,$module,$val);
			}
			return $res;
		}
		// END ADDED BY NS-TEAM
    static function parse_template($string, $bean_arr)`


Change line:
`                   // $repl_arr[$key . "_" . $fieldName] = implode(', ', unencodeMultienum($focus->$fieldName));
					$repl_arr[$key."_".$fieldName] = implode(', ', templateParser::getMultiEnumVal($field_def['options'],$focus->module_dir,unencodeMultienum($focus->$fieldName)));`

**Comment by shogunpol** [comment]
@vladbar , i tested this issue on newest version of SuiteCRM(7.7.8), and not appear, can you confirm it and if yes can you close an issue?

@yulahab , can you raise separate issue for you case please, it will prevent to drop this issue.
