### ISSUE TITLE
Unused language strings (Leads)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2647]
See #2444 

['LBL_BACKTOLEADS'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L79)

['LBL_CONVERTLEAD_BUTTON_KEY'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L92)

['LBL_PORTAL_ACTIVE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L160)

['LBL_PORTAL_PASSWORD_ISSET'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L164)

['LBL_TARGET_BUTTON_LABEL'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L213)

['LBL_TARGET_BUTTON_TITLE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L214)

['LBL_TARGET_BUTTON_KEY'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L215)

['LBL_THANKS_FOR_SUBMITTING_LEAD'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L221)

['LBL_MESSAGE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L226)

['LBL_SAVED'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L227)

['LBL_CLICK_TO_RETURN'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L228)

['LBL_NOTICE_OLD_LEAD_CONVERT_OVERRIDE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L244)

**For export labels**

['LBL_PHONE_HOME'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L258)

['LBL_PHONE_MOBILE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L259)

['LBL_PHONE_WORK'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L260)

['LBL_PHONE_OTHER'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L261)

['LBL_EXPORT_ASSIGNED_USER_NAME'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L264)

['LBL_EXPORT_ASSIGNED_USER_ID'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L265)

['LBL_EXPORT_MODIFIED_USER_ID'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L266)

['LBL_EXPORT_CREATED_BY'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L267)

['LBL_EXPORT_PHONE_MOBILE'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L268)

['LBL_EXPORT_EMAIL2'](https://github.com/salesagility/SuiteCRM/tree/v7.7.7/modules/Leads/language/en_us.lang.php#L269)

**Comment by shogunpol** [comment]
@likhobory , i preferred your previous language issue layout(with references path for each label), now i have to open each one in separate page to check is this same document. I will be appreciate if you will back to previous layout.

**Comment by likhobory** [comment]
OK, done.
