### ISSUE TITLE
Issue with QUOTES totalAmount

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2649]
Hi,

in Quotes, the variable totalamount not making sum, shows the 2 values. When having 2 groups of lines with services.

And you see, of not respects the info of the template, system creates each table for each group.

I attach Code of the BODY to reproduce them:

`<table style="border: 0pt none; text-align: center; width: 100%; -x-border-x-spacing: 0pt; -x-border-y-spacing: 0pt;">
<tbody style="text-align: left;">
<tr style="text-align: left;">
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; background-color: #b0c4de; vertical-align: top; text-align: left; width: 50%;">Preparado Para</td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; background-color: #b0c4de; vertical-align: top; text-align: left; width: 50%;">Preparado Por</td>
</tr>
<tr style="text-align: left;">
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; width: 50%; vertical-align: top; text-align: left;">$aos_quotes_billing_account<br /> $aos_quotes_billing_address_street - $aos_quotes_billing_address_postalcode<br /> $aos_quotes_billing_address_city</td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; width: 50%; vertical-align: top; text-align: left;">
<div>$aos_quotes_modified_by_name</div>
</td>
</tr>
<tr style="text-align: left;">
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; background-color: #b0c4de; vertical-align: top; text-align: left; width: 50%;">Fecha</td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; background-color: #b0c4de; vertical-align: top; text-align: left; width: 50%;">Válida Hasta</td>
</tr>
<tr style="text-align: left;">
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; width: 50%; vertical-align: top; text-align: left;">
<div>$aos_quotes_date_entered</div>
</td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; width: 50%; vertical-align: top; text-align: left;">
<div>$aos_quotes_expiration</div>
</td>
</tr>
</tbody>
</table>
<p style="margin-top: 6px; height: 3px;"> </p>
<p> </p>
<table style="border: 0pt none; width: 100%;">
<tbody>
<tr>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: center; background-color: #b0c4de;"><small>Cantidad</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center; width: 238px;"><small>Producto</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center;"><small>P. Unitario</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center;"><small>Dto</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center;"><small>Precio neto</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center;"><small>Iva</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; background-color: #b0c4de; font-weight: bold; text-align: center;"><small>Total</small></td>
</tr>
<tr>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;" colspan="7"><strong>$aos_line_item_groups_name</strong></td>
</tr>
<tr>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; text-align: center;"><small>$aos_products_quotes_product_qty</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; width: 238px;"><small>$aos_products_quotes_name</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_products_quotes_product_list_price</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_products_quotes_product_discount</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_products_quotes_product_unit_price</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_products_quotes_vat</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_products_quotes_product_total_price</small></td>
</tr>
<tr>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;" colspan="7"><small><small><small>$aos_products_quotes_item_description</small></small></small></td>
</tr>
<tr>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;" colspan="2"><small>$aos_services_quotes_name</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_services_quotes_service_list_price</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_services_quotes_service_discount</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_services_quotes_service_unit_price</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_services_quotes_vat</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$aos_services_quotes_service_total_price</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Total</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$total_amt</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Descuento</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$discount_amount</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Subtotal</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$subtotal_amount</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Impuesto</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$tax_amount</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Envío</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$shipping_amount</small></td>
</tr>
<tr>
<td colspan="5"> </td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px; font-weight: bold; text-align: right;"><small>Gran Total</small></td>
<td style="border-style: solid; border-width: 0.5px; padding: 2px 6px;"><small>$total_amount</small></td>
</tr>
</tbody>
</table>`

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All browser
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP7
* Operating System and version (e.g Ubuntu 16.04): WS 2012R2

**Comment by mattlorimer** [comment]
either remove $aos_line_item_groups_name from your template or put the totals in a separte table below if using groups in the template, 

Groups will currently grab and duplicate the full table so this not a bug and working as intended. I would suggest you ask on [community forum](https://suitecrm.com/forum/index) if you need more help with templates
