### ISSUE TITLE
SuiteP - Different size of icons on sidebar

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2651]
#### Issue

![sidebar](https://cloud.githubusercontent.com/assets/5773777/20351172/0d517972-ac12-11e6-96c1-3aa7616e7de4.png)

#### Expected Behavior

All icons on sidebar will use same size

#### Actual Behavior

Some module icons are bigger.

#### Your Environment

* SuiteCRM Version used: 7.7.7 
* Browser name and version: Chrome 54.x 64bit
* Environment name and version: MySQL PHP 5.6
* Operating System and version: Win 10 Home

**Comment by samus-aran** [comment]
@Mausino - Are you able to test that this is fixed Mausino using the referenced PR?  
https://github.com/salesagility/SuiteCRM/issues/3426

**Comment by Mausino** [comment]
@samus-aran  thanks... it solved my issue 👍

**Comment by samus-aran** [comment]
Should've been resolved by https://github.com/salesagility/SuiteCRM/pull/5273
