### ISSUE TITLE
Blank Screens w/ iPad Air

### ISSUE THREAD

**Issue by mjones517** [salesagility/SuiteCRM#266]
I'm pretty sure there's a glitch with the responsive theme when using an iPad. I'm using an iPad Air WiFi 16GB. I frequently get screens that look like this:

http://i.imgur.com/Argf0D4.jpg

UPDATE 1: 
I am now 100% certain this is a bug. I was able to replicate the issue on the demo install. See these screen grabs:

http://i.imgur.com/RcZ2M5B.png

http://i.imgur.com/j50RAg7.png

This happens in both Chrome and Safari. The problem is identical. A few notes:

1.) It seems to primarily affect the Opportunities module. Looking at a specific opportunity or looking at the opportunities in list view causes the problem. 

2.) I thought it might be something to do with the layout, so I restored the opportunities layout to its default. This didn't resolve the issue. 

3.) I disabled all server caching and cleared the browser cache. This did not resolve the issue. 

4.) I disabled the speed enhancer feature in Chrome. This did not resolve the issue. 

5.) Portrait vs Landscape seems to make a difference. If I start my session in landscape mode and keep the "recently viewed" slider collaped, the problem doesn't happen as often (although it still crops up occasionally). 

6.) If I keep the iPad in portrait mode the Opportunities module consistently comes up blank. 

7.) I do not have problems with any other device. My MacBook Air, MacBook Pro (w/Retina), and iPhone 6 are all fine. 

Server config:
SuiteCRM 7.2.2
Apache 2.2.29
PHP 5.4.41
CENTOS 6.6 x86_64
MySQL 5.5

UPDATE 2: Just tested with both SuiteR and Suite7 themes. The issues are the same in both.

**Comment by mjones517** [comment]
Just an update on this... The issue goes away if I choose the "Request Desktop Site" option in Chrome for iOS. 

I wouldn't call this a "fix", but it could be a clue to the problem.

**Comment by willrennie** [comment]
Is this still an issue @mjones517

**Comment by mjones517** [comment]
No. It looks like it's been resolved in the newest release. 





On Fri, Jan 22, 2016 at 7:48 AM -0800, "Will Rennie" <notifications@github.com> wrote:












Is this still an issue @mjones517

**Comment by willrennie** [comment]
It was most likely fixed in an earlier commit we pushed which fixed multiple issues with iPad's specifically, but also in general with smaller resolutions by @johnM2401
