### ISSUE TITLE
Reports - Multi select combo box filter issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2663]
#### Issue

 I m using reports module to export contacts list. I have condition in my report which include multi select combo box field. When i add it to parameter in my list, it does not work. When i change my selection and update, there is no result. 

When i try it other condition, it works.

#### Expected Behavior

There should be result, when i change my selection and update.

#### Steps to Reproduce

1. Add contact list to Reports module
2. Add condition to reports
3. Use multi select combo box in condition
4. Select parameter check box in condition
5. List contact and select any parameter in combo box

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
* Operating System and version (e.g Ubuntu 16.04):
* Theme : Suite 7

![issue1](https://cloud.githubusercontent.com/assets/22373035/20423396/0b270ebc-ad81-11e6-8c59-b96fb6b5cb9f.png)

![issue2](https://cloud.githubusercontent.com/assets/22373035/20423397/0b284d5e-ad81-11e6-92de-3c7324b2dfa2.png)

**Comment by shogunpol** [comment]
@dursuntosun , looks like you use custom field: "Relation tags", can you provide details to recreate this field, without this information i'm not able to replicate issue.

**Comment by dursuntosun** [comment]
These are details;
![issue1](https://cloud.githubusercontent.com/assets/22373035/20424044/cbe9b9b2-ad84-11e6-9490-467ec961cbe1.png)

![issue2](https://cloud.githubusercontent.com/assets/22373035/20424045/cbebb6fe-ad84-11e6-9629-9a28f5bf18bc.png)

**Comment by shogunpol** [comment]
@dursuntosun , i started recreate described drop-down, and i'm not able to do it because validation disallows to use "-" sign in Item Names and Display Labels value, i'm not sure how you manage to do it, but can you remove "-"(dash) signs from those strings and try if it is work?

**Comment by dursuntosun** [comment]
But when change item names, my contact list does not have this parameter :(

**Comment by shogunpol** [comment]
@dursuntosun , i'm sorry for this, probably will be good idea to do this changes in future. 
However, i been able to replicate bug using "_"(instead of "-"), and issue appear anyway. 

I will close this issue as it appears that this is related to #1645 and appears to display the same issues.

**Comment by dursuntosun** [comment]
But it also work in contacts module search same situation :(

![issue1](https://cloud.githubusercontent.com/assets/22373035/20425129/33831636-ad8a-11e6-9c66-b580c020e7a6.png)

**Comment by dursuntosun** [comment]
Do you think, is it same bug with #1645 ?

**Comment by shogunpol** [comment]
@dursuntosun , yes it is.

**Comment by danieldias51** [comment]
Does anyone already read this post? 
https://suitecrm.com/forum/suggestion-box/656-reports-and-multi-select-fields#5687

I had the same problem with multiselect fields not filtering on reports and that solution fix the problem.

**Comment by dursuntosun** [comment]
When i try it with 7.8.3 version my problem is continue. Can you open my issue again? Are there any implementation for this?
https://suitecrm.com/forum/suggestion-box/656-reports-and-multi-select-fields#5687

**Comment by mayerelyashiv** [comment]
Hi, i found this same issue on a 7.8.18
Is it really fixed?
