### ISSUE TITLE
Search in multiple value dropdowns does not work

### ISSUE THREAD

**Issue by erikschwalbe** [salesagility/SuiteCRM#2672]
#### Issue

Search in multiple value dropdowns does not work
#### Expected Behavior

Select two or more values of a multiple value dropdown should find all entries in a module with this values (AND linked)
#### Actual Behavior

No results found

wrong DB query
"WHERE (xyz in (value1, value2))"

instead of

"WHERE (xyz in ('value1', 'value2'))"
#### Possible Fix

edit file include/SearchForm/SearchForm2.php
Line 794: $field_value .= $val;
change to: $field_value .= "'" . $val . "'";  
#### Steps to Reproduce

1. Search for Contacts
2. select multiple assigned users
3. click search

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 48
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5, PHP 5.5  
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by staganyi** [comment]
I think this was fixed in v7.7.8

**Comment by shogunpol** [comment]
This search appears to work as expected, When searching multiple options in a select field, it runs through the following code. 

$field_value .= $db->quoteType($type, $val);

This in turn will quote the value. Can you upgrade to the latest version and test with this ? 

Thanks.

**Comment by erikschwalbe** [comment]
Yes your right.
Version 7.7.8 fix the problem.
Sorry for that. Did not see, that there is a new version.
