### ISSUE TITLE
Error After install 7.7.7 nad Before Upgrade 7.7.8

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2675]
hi, when i try to install 7.7.8 version, i'm locked in this Screen. Is last Screen of Upgraded process of version 7.7.7

![upgrade1](https://cloud.githubusercontent.com/assets/20840700/20455440/6e3e405c-ae5c-11e6-9527-c86575dc056d.PNG)

how can i modify the setting to go first option ?

UpgradeLog:

Sat, 19 Nov 2016 15:28:07 +0300 [UpgradeWizard] - setting session variables...
Sat, 19 Nov 2016 15:28:07 +0300 [UpgradeWizard] - Upgrade Wizard At Layout Commits
Sat, 19 Nov 2016 15:28:07 +0300 [UpgradeWizard] - Layout Commits about to show selection table
Sat, 19 Nov 2016 15:52:28 +0300 [UpgradeWizard] - setting session variables...
Sat, 19 Nov 2016 15:52:28 +0300 [UpgradeWizard] - Upgrade Wizard At Layout Commits
Sat, 19 Nov 2016 15:52:28 +0300 [UpgradeWizard] - Layout Commits about to show selection table
Sat, 19 Nov 2016 15:56:25 +0300 [UpgradeWizard] - setting session variables...
Sat, 19 Nov 2016 15:56:30 +0300 [UpgradeWizard] - [At end.php]
Sat, 19 Nov 2016 15:56:30 +0300 [UpgradeWizard] - About to repair the database.

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): WS 2012 R2

**Comment by GrupImatica** [comment]
Ok, solved. I deleted info on cache folder

**Comment by GrupImatica** [comment]
After Upgrade, we cannot exit from this bucle
![upgrade2](https://cloud.githubusercontent.com/assets/20840700/20455736/2bd3f7f0-ae63-11e6-86a3-698906df016a.PNG)

**Comment by pgorod** [comment]
@GrupImatica this sort of thing should really be handled in the forums, not here. 

If I'm not mistaken, Github issues are more for when you know something is wrong with the software for everybody, not just for an isolated case...

**Comment by GrupImatica** [comment]
@pgorod it's possible but, it's the first update 7.7.7 and 7.7.8 that makes changes in Views (screens) or updates for them.

I think that it's problem with this new procedure.

**Comment by pgorod** [comment]
There have been many such upgrades tried, without this problem. Normally you need to check your permissions, try Repairs and rebuilds, check your logs, etc. This process typically involves a few messages back and forth, and is best done in the forums (I mean you get more attention there, and a better help!). 

Then if you have something more specific to report you come here and report. Even if it is a bug in the product, that previous work helps create good, well-reported Issues.

I am not an authority here, I'm just trying to help. Feel free to do things differently if you don't agree with me. : - )

**Comment by shogunpol** [comment]
@GrupImatica  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
