### ISSUE TITLE
Unused language strings (Studio & Portal.html)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2676]
See #2444 

['LBL_EDIT_ROWS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L48
['LBL_EDIT_COLUMNS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L49
['LBL_EDIT_LABELS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L50
['LBL_ADD_FIELDS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L52
['LBL_DISPLAY_HTML']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L53
['LBL_SAVE_LAYOUT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L55
['LBL_SELECT_A_SUBPANEL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L56
['LBL_SELECT_SUBPANEL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L57
['LBL_STAGING_AREA']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L60
['LBL_SUGAR_BIN_STAGE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L62
['LBL_VIEW_SUGAR_BIN']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L64
['LBL_SW_EDIT_WORKFLOW']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L94
['LBL_SMW_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L100

**SELECT MODULE ACTION**
['LBL_SMA_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L103
['LBL_SMA_EDIT_CUSTOMFIELDS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L104
['LBL_SMA_EDIT_LAYOUT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L105
['LBL_SMA_EDIT_LABELS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L106
['LBL_MB_COMPARE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L112
['LBL_MB_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L113
['LBL_ED_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L117

**EDIT CUSTOM FIELDS**
['LBL_EC_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L123
['LBL_EC_VIEW_CUSTOMFIELDS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L124
['LBL_EC_CREATE_CUSTOMFIELD']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L125
['LBL_EC_CLEAR_CACHE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L126
['LBL_SM_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L129
['LBL_BTN_ADDCOLS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L144
['LBL_TAB_SUBTABS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L152
['LBL_DISPLAY_OTHER_TAB']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L166

**SUGAR PORTAL**
['LBL_SW_SUGARPORTAL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L180
['LBL_SMP_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L181
['LBL_SP_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L182
['LBL_SP_SYNC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L183
['LBL_SYNCP_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L184
['LBL_LISTVIEWP_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L185
['LBL_SP_STYLESHEET']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L186
['LBL_SP_UPLOADSTYLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L187
['LBL_SP_UPLOADED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L188
['ERROR_SP_UPLOADED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L189
['LBL_SP_PREVIEW']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Studio/language/en_us.lang.php#L190

File [en_us.Portal.html](https://github.com/salesagility/SuiteCRM/blob/v7.7.8/modules/Studio/language/en_us.Portal.html) is not used.

**Comment by horus68** [comment]
`LBL_DISPLAY_OTHER_TAB_HELP` also to be deleted
