### ISSUE TITLE
Workflow not triggering with dates in AOS Invoice module

### ISSUE THREAD

**Issue by Caesar305** [salesagility/SuiteCRM#268]
Unable to create a workflow for sending email notifications for late invoices. Created a workflow with the following:

         
1	Invoices	Due Date	Equal To	Date	Now - 1 Days
2	Invoices	Status	Equal To	Value	Unpaid

The workflow will never trigger. If I specify "less than or equal to" date Now -1 Day, it will trigger but obviously this will simply send out emails to all invoices with a date range of less than today's date. 

Tried many different combinations such as Less than or equal to Today, with another condition of Greater than or equal to today -2 and still will not trigger. 

Thanks

**Comment by willrennie** [comment]
You can specify the workflow to only run on 'New Records' which would mean the 'Less than or Equal To Now -1 Day' trigger would only fire on new records.
