### ISSUE TITLE
Inline Edit make you loose Parent just on Calls module, Detail View

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#2689]
#### Issue
When you edit in line any field of the Calls module in Detail View, when the record is saved, the Parent record is not showed anymore.

#### Possible Fix
**I found that on the db the parent_id is still there. It's the parent_type that get lost.**

#### Steps to Reproduce
1. http://demo.suiteondemand.com/
2. go to Calls module
3. enter into detail view of a call
4. edit in line any field 
5. hit enter to save
6. the parent record link disappear

#### Your Environment
* SuiteCRM Version used: 7.6.5, 7.6.6, 7.7.6, 7.7.8
SuiteR and SuiteP theme
English and Italian language

**Comment by vladbar** [comment]
This issue is caused due to the fact that account_id is saved with a null value

**Comment by vladbar** [comment]
Will require some modifications as the parent field for Calls can be different (not just account_id)

**Comment by shogunpol** [comment]
@mayerelyashiv , an issue has been tested on recent version of SuiteCRM(7.8), and not appear. Can you confirm and close the case if works for you?

**Comment by mayerelyashiv** [comment]
Hi @shogunpol, i've just test it on Version 7.8.0 on http://demo.suiteondemand.com/ and it works.
Thank you
