### ISSUE TITLE
Unused language strings (Users)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2699]
See #2444 

['LBL_DELETE_PORTAL_CONFIRM']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L52
['ERR_NO_LOGIN_MOBILE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L66
['ERR_PASSWORD_CHANGE_FAILED_3']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L71
['ERR_PASSWORD_LINK_EXPIRED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L76
['ERR_USER_INFO_NOT_FOUND']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L80
['LBL_GENERATE_PASSWORD_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L182
['LBL_GROUP_USER_STATUS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L188
['LBL_LAST_NAME_SLASH_NAME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L196
['LBL_LOGIN_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L224
['LBL_LOGIN_WELCOME_TO']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L227
['LBL_LOGIN_ATTEMPTS_OVERRUN']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L231
['LBL_LOGIN_LOGIN_TIME_ALLOWED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L232
['LBL_LOGIN_LOGIN_TIME_DAYS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L233
['LBL_LOGIN_LOGIN_TIME_HOURS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L234
['LBL_LOGIN_LOGIN_TIME_MINUTES']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L235
['LBL_LOGIN_LOGIN_TIME_SECONDS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L236
['LBL_LOGIN_ADMIN_CALL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L237
['LBL_MAX_TAB']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L250
['LBL_MAX_TAB_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L251
['LBL_MAX_SUBTAB']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L252
['LBL_MAX_SUBTAB_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L253
['LBL_NEW_USER_PASSWORD_3']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L273
['LBL_NEW_USER_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L274
['LBL_NEW_USER_BUTTON_LABEL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L275
['LBL_NEW_USER_BUTTON_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L276
['LBL_NORMAL_LOGIN']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L277
['LBL_PASSWORD_GENERATED']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L285
['LBL_PICK_TZ_WELCOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L292
['LBL_PORTAL_ONLY_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L294
['LBL_PORTAL_ONLY_USER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L295
['LBL_REGISTER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L315
['LBL_REMOVED_TABS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L334
['LBL_RESET_TO_DEFAULT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L339
['LBL_SIGNATURE_DEFAULT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L357
['LBL_SIGNATURES']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L359
['LBL_SUBPANEL_LINKS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L362
['LBL_SUBPANEL_LINKS_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L363
['LBL_SUPPORTED_THEME_ONLY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L367
['LBL_SWAP_LAST_VIEWED_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L368
['LBL_SWAP_SHORTCUT_DESCRIPTION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L369
['LBL_SWAP_LAST_VIEWED_POSITION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L370
['LBL_SWAP_SHORTCUT_POSITION']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L371
['LBL_TAB_TITLE_EMAIL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L372
['LBL_TAB_TITLE_USER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L373
['LBL_THEME_COLOR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L375
['LBL_THEME_FONT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L376
['LBL_TIMEZONE_DST_TEXT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L379
['LBL_TIMEZONE_DST']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L380
['LBL_YOUR_QUERY_URL']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L397
['LNK_NEW_PORTAL_USER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L399
['LNK_REASSIGN_RECORDS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L402
['LBL_APPLY_OPTIMUMS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L413
['LBL_CERT_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L416
['LBL_CERT']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L417
['LBL_FIND_OPTIMUM_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L418
['LBL_FIND_OPTIMUM_MSG']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L419
['LBL_FIND_OPTIMUM_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L420
['LBL_FORCE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L421
['LBL_FORCE_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L422
['LBL_FOUND_OPTIMUM_MSG']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L423
['LBL_EMAIL_INBOUND_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L424
['LBL_EMAIL_OUTBOUND_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L425
['LBL_MAILBOX_SSL_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L428
['LBL_MARK_READ_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L433
['LBL_ONLY_SINCE_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L437
['LBL_TEST_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L445
['LBL_TLS_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L449
['LBL_TLS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L450
['LBL_OWN_OPPS']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L452
['LBL_EXTERNAL_AUTH_ONLY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L453
['LBL_ONLY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L454
['LBL_OWN_OPPS_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L455
['LBL_LDAP_ERROR']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L457
['LBL_USER_HOLIDAY_SUBPANEL_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L461

['LBL_PDF_SETTINGS']...
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L465-L491

['LBL_WIZARD_FINISH16']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L544
['LBL_WIZARD_FINISH17']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L545
['LBL_CHECKMARK']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L565
['LBL_THEMEPREVIEW']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L566
['LBL_OAUTH_TOKENS_SUBPANEL_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L569

**For export labels**
['LBL_PHONE_HOME']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L573
['LBL_PHONE_MOBILE']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L574
['LBL_PHONE_WORK']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L575
['LBL_PHONE_OTHER']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L576
['LBL_PORTAL_ONLY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L578
['LBL_IS_GROUP']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L580
['LBL_EXPORT_CREATED_BY']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/modules/Users/language/en_us.lang.php#L581

**Comment by horus68** [comment]
One more: 'LBL_BUTTON_CHECK_KEY'

**Comment by likhobory** [comment]
@horus68 
Yes, this label exists in E-mail & Users language files only, but there are much more unused strings..

**Comment by horus68** [comment]
Until PR 3550 (Combined language file update 2) is merged its difficult to list more new strings not used because we also need to verify if they are already reported in github!
@Dillon-Brown please make that merge happen!
As for me, I simply hidden the strings on that PR from Crowdin translators but its already difficult to keep in sync the online project, my personal and local master language (Hotfix branch with many fixes) and the official Hotfix branch!
