### ISSUE TITLE
SuiteCRM 7.1.7 Import/Export Chinese characters doesn't work 

### ISSUE THREAD

**Issue by himingby** [salesagility/SuiteCRM#270]
In the SuiteCRM 7.1.7, setup the Import/Export Character Set to UTF-8.
 At the moment, we can import/export Chinese characters or data in general, however it does not display the Chinese characters correctly. They show up garbled.
ps, just only Quotes\Report\Contracts\Invoices module have the issue, other modules like Contact support Chinese.
and SuiteCRM 7.1.1, Chines characters can import/export normally.
I think it is a bug.

**Comment by himingby** [comment]
and in Reports module in SuiteCRM 7.1.1, Chinese characters can import/export normally.

**Comment by darthtang** [comment]
HI 

i am using Version 7.3.1. There is no problem with exporting,. Perhaps also try updating
