### ISSUE TITLE
LBL_NO_PHP_CLI string do not allow further translations

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2703]
#### Issue

The language file for modules/Schedulers/language/en_us.lang.php includes one string that has some mixed code along values to translate.
This do not allow correct reading from Crowdin system on translation. The lines after that string are not available for translation (for that file). For now I had to move it to the end of the file.
This is also a long and complex string value: a value should only be a language value, not code.
The string is
https://github.com/salesagility/SuiteCRM/blob/master/modules/Schedulers/language/en_us.lang.php#L153

`
'LBL_NO_PHP_CLI' => 'If your host does not have the PHP binary available, you can use wget or curl to launch your Jobs.<br>for wget: <b>*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;wget --quiet --non-verbose ' . (isset($sugar_config['site_url'])?$sugar_config['site_url']:'http://yoursite') . '/cron.php > /dev/null 2>&1</b><br>for curl: <b>*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;curl --silent ' . (isset($sugar_config['site_url'])?$sugar_config['site_url']:'http://yoursite') . '/cron.php > /dev/null 2>&1',
`

#### Expected Behavior

Valeu should be just plain words to be translate. File should be totally parsed by Crowdin, as usual.

#### Actual Behavior

In Crowdin translation platform the string is parsed and included in translation but after that string no more strings are available to be translated. The strings after LBL_NO_PHP_CLI are just included in the downloaded translated file, but not recognized for translation on Crowdin system)

#### Context

Medium as it do not allow the remaining lines, from that file, to be translated.
Note also this is not an easy string to be translated. As a general rule code should be removed from language strings!

#### Your Environment

* SuiteCRM Version used: SuiteCRM Latest version

**Comment by pgorod** [comment]
@horus68 @shogunpol 

I just searched for this label and realized it's not even used anywhere:

https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=LBL_NO_PHP_CLI

All uses of the label are commented out. We might as well just delete all these references and remove the label. Or at least, horus68 can disable it in Crowdin, it's not worth translating.

**Comment by shogunpol** [comment]
@pgorod , i had quick check and you right, looks like this label is never used, if you can please create Issue and PR, so we can proceed "quick" refactored code, and merge to next release.

**Comment by horus68** [comment]
Confirmed. Already removed from Crowdin!

**Comment by samus-aran** [comment]
Labelling this as a bug as we have a fix.
