### ISSUE TITLE
Calendar widget not conforming to time format settings

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2704]
#### Issue
When setting the time settings in the profile settings I have formatted them to be 24hr (14:00).
This is also on the demo site...

#### Expected Behavior
Times in the calendar widget show as 24hr format

#### Actual Behavior
Times are shown as 12hr format (2:00)
The meetings widget shows the time correctly

#### Steps to Reproduce
Add something to the calendar, check the times in the calendar widget.

#### Context
Just minorly annoying!

#### Your Environment
* SuiteCRM Version used: 7.7.8
* Browser name and version:  Chrome, Firefox, IE
* Environment name and version: MySQL, PHP 7

**Comment by jack7anderson7** [comment]
After testing this in the latest version of SuiteCRM, I believe this is no longer an issue and I will close this issue on account of that.
