### ISSUE TITLE
Unused language strings (/include/SugarObjects/templates/company)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2705]
See #2444 

['LBL_PUSH_BILLING']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/include/SugarObjects/templates/company/language/en_us.lang.php#L103
['LBL_PUSH_SHIPPING']
https://github.com/salesagility/SuiteCRM/tree/v7.7.8/include/SugarObjects/templates/company/language/en_us.lang.php#L104

**Comment by horus68** [comment]
@likhobory when in SuiteCRM action can we see, in action,  the language files for SugarObjects templates (specially "company" and "person")

**Comment by likhobory** [comment]
@horus68, in module Builder, when administrator creates a new modules that are similar to Accounts, Contacts or Leads modules.
