### ISSUE TITLE
Dropdown Editor creates corrupt language file

### ISSUE THREAD

**Issue by jorr-it** [salesagility/SuiteCRM#2713]
When an end user edits and saves a dropdown list using the Dropdown Editor in Studio, the custom language file en_us.lang.php gets corrupt, causing a fatal error in the whole system. This is part of the file that gets corrupt:

```
$GLOBALS['app_list_strings']['onboard_asterisk_cli_list']=array (
 '' => '',
 '06....' => '....',
 '06....' => '.... Poseidon',
 '06....' => '....',
 '06....' => '....',
 '06....' => '....',
 '06....' => '.... Onboard',
 '06....' => '.... Sales',
 '06....' => '.... Management',
 '06....' => '.... Techniek',
 '06....' => '.... Iamsterdam',
 '06....' => '.... Recruitment',
 '06....' => '.... OV',
);
Keienbergweg 12, 1101 GB, Geen parkplaatsen!!',
);

$GLOBALS['app_list_strings']['onboard_locatie_list']=array (
 '' => '',
 'locatie_sittard...s' => 'Sec... Arendstraat 8, 6135 KT',
 'locatie_rosmale...as' => 'Se...n; De Grote Elst 70, 5246 JR',
 'locatie_amsterd...tas' => 'S...dam (ZO); Keienbergweg 12, 1101 GB, Geen parkplaatsen!!',
 'locatie_amsterd...d' => 'Onb...lein 2-N, 1013NJ, Amsterdam',
);
```

Please note that some of the text is dashed for privacy reasons. The concerning part is in the middle: Keienbergweg 12, 1101 GB, Geen parkplaatsen!!', and the line below. These two lines are not a paste failure of me, it is exactly the content of the language file generated by the Dropdown Editor. Manually fixing the file helps for some time, but gets corrupt as soon as end-user saves in Dropdown Editor. We even deleted and regenerated this dropdown list. I assume that the problem is the text ); (bracket+semicolon) in the third dropdown option of onboard_locatie_list.

Using SuiteCRM Version 7.7.6 on Sugar Version 6.5.24 (Build 509).

**Comment by shogunpol** [comment]
@jorr-it , , please do provide all necessary information to replicate issue listed in "New Issue" template, especially important are: 
- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug,
- Tell us what should happen,
- Tell us what happens instead,
- Provide a link to a live example, or an unambiguous set of steps to reproduce this bug include code to   reproduce, all details about field and selected option when created
- And environment you use: OS, PHP version, SQL version and so on.

If you do not provide enough information to replicate issue, an issue will be closed.
Thanks for your contribution.

**Comment by jorr-it** [comment]
My description should be fine. If you don't want to fix it, you can close the issue.

**Comment by shogunpol** [comment]
The issue has been closed because it wasn't provided requested details to replicate an issue.
