### ISSUE TITLE
Git Repo causes issues on Windows

### ISSUE THREAD

**Issue by simjker** [salesagility/SuiteCRM#2718]
#### Issue
The SuiteCRM repo contains two files which only differ in name by case.

```
https://github.com/salesagility/SuiteCRM/tree/master/themes/SuiteP/images/sidebar/modules/FP_Events.svg
https://github.com/salesagility/SuiteCRM/tree/master/themes/SuiteP/images/sidebar/modules/FP_events.svg

```
This can cause an issue when developing on Windows

Are both of these files required?

Looking at the rest of the files in that directory it would seem that there should only be one .svg file with a name that matches the .png file.

**Comment by horus68** [comment]
Confirmed as an issue on windows. This is an ongoing issue (each versions can varies on the files involved)
Its time to have a rule for "all lower case" file names!
I know this is not possible for retro-compatibility, but there is no reason to have new files created with mixed case!

**Comment by samus-aran** [comment]
This issue should be resolved now.  Please re-open if this is not the case.
