### ISSUE TITLE
Report paginating does not work correctly when a date condition Less Than is used

### ISSUE THREAD

**Issue by eborremans** [salesagility/SuiteCRM#2725]
#### Issue
We use suiteCRM 7.7.7
I set the locale for the current user to dd/mm/yyyy (12/23/2010).
I created a report based on the contacts module. 
The contacts module has relations to other custom modules
I included a related field from a custom module
I included field 'Contacts.Date Created'
I included a condition: 'Contacts.Date Created' Less Than (or Equal To) Value, Parameter enabled
I applied this report so that it results in more than 20 records
In this case the record selector will say something like (1 - 20 of 29).
Then when selecting the next result page it won't show any results. The net effect it that I can at most see 20 results in this report.

Note: the Greater Than (or Equal To) condition does NOT seem to suffer the same issue.
**Note: this issue does not occur when the locale is set to yyyy-mm-dd and hence seems to be related to an earlier date related [bug](https://github.com/salesagility/SuiteCRM/issues/1624) which caused date conditions in reports not to function properly when using anything different from the default mySQL locale.**

#### Expected Behavior
In this case when the record selector says (1 - 20 of 29), then when selecting the next result page it should actually show the next 9 records.

#### Actual Behavior
In this case when the record selector says (1 - 20 of 29), then when selecting the next result page it won't show any results. After selecting the next page the record selector shows (0 - 0 of 0). And no records are shown. After that, when selecting the previous page with the record selector, nothing happens. Then when selecting 'Update' it again shows the first 20 records.

#### Steps to Reproduce
We use suiteCRM 7.7.7
I set the locale for the current user to dd/mm/yyyy (12/23/2010).
I created a report based on the contacts module. 
The contacts module has relations to other custom modules
I included a related field from a custom module
I included field 'Contacts.Date Created'
I included a condition: 'Contacts.Date Created' Less Than (or Equal To) Value, Parameter enabled
I applied this report so that it results in more than 20 records
In this case the record selector will say something like (1 - 20 of 29).

#### Context
We use this functionality for several reports that are based on date ranges. The results for these reports are obviously limited to 20 records which of course is rather unacceptable. I would value the priority to be medium to high (since my customer won't accept the functionality).

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version: Chrome Version  54.0.2840.99 m (64-bit) and Firefox 45.4.0
* Environment name and version: MariaDB version 5.5.50, PHP version 5.4.16
* Operating System and version: CentOS Linux release 7.2.1511 (Core)

**Comment by shogunpol** [comment]
@eborremans - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
