### ISSUE TITLE
Project Tasks not respecting predecessor or Relationship type fields

### ISSUE THREAD

**Issue by kemen04** [salesagility/SuiteCRM#273]
Project tasks appear to be generated from task order and doesn't obey the predecessor or Relationship Type fields. I am trying to get tasks to run concurrently from the project template.

**Comment by recci** [comment]
This is not a bug,  project tasks have always been generated based on order. The predecessor has to be selected manually when you create a task. I just added the predecessor to allow for the creation of arrows connecting the tasks in the gantt chart.
