### ISSUE TITLE
unable to scroll dropdown menu longer than window height

### ISSUE THREAD

**Issue by franklinian** [salesagility/SuiteCRM#2738]
#### Issue
The 'ALL' dropdown menu with SuiteP theme does not scroll to items below the browser window height when the page zoom is set to less than 100%. Reproducible with latest versions of Chrome and Firefox on Windows 10.

#### Steps to Reproduce

1. Set browser zoom to any setting less than 100%
2. Hover over ALL menu
3. Attempt to scroll to menu items below bottom border of browser window
4. Be frustrated

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1 LTS

**Comment by shogunpol** [comment]
@franklinian , an issue has been tested on recent version SuiteCRM(7.8), and not appear, can you confirm and close an issue?

**Comment by horus68** [comment]
no issue anymore, this can be closed as solved
