### ISSUE TITLE
ListView and Subpanel View edits don't propagate on save and will force nonsensical order to items that can't be changed

### ISSUE THREAD

**Issue by GeorgeWL** [salesagility/SuiteCRM#2739]
#### Issue
When editing the List View and Subpanel View the click of drag of fields often completely ignores any attempt to make change and sets itself back to the previous state on save.

Also certain fields will not allow the user to change their level in the hierarchy, even when logically they should be able to..

this doesn't happen in all cases or for all fields.

#### Expected Behavior
changes propagate immediately or after a repair and rebuild

#### Actual Behavior
changes don't propagate even after a repair and rebuild

#### Steps to Reproduce
1. Enter to the studio
2. Try to edit the List View or SubPanel View using drag-drop behaviour
3. click save+deploy
4. watch it set itself back to previous state
5. check the updated view-> also in the same state as before edit attempt
7. try repair and rebuild
8. check the updated view-> also in the same state as before edit attempt

Short little looping video of the behaviour: 
https://streamable.com/e/4dqm

#### Context
Makes customisations difficult or frustrating sometimes
Medium priority

#### Your Environment
* SuiteCRM Version used:
* Browser name and version: Chrome Version 54.0.2840.99 m (32 bit)
* Environment name and version: MySQL via PHPMyAdmin, PHP Version 5.6.28, Hosted on a Remote Shared Hosting Server with cPanel 60.0.25 and WebHostManager WHM 60.0 (build 25)
* Operating System and version: CLOUDLINUX 7.3 x86_64 kvm for the Hosting, Windows 10 (Version 1607) 32-bit for the user acessing the web portal.

**Comment by shogunpol** [comment]
@GeorgeWL , the issue has been tested in recent version of SuiteCRM(7.7.8) and not appear,
there is two things what may causing described behaviour:
1. Inappropriate settings of the permissions;
2. Using older version of SuiteCRM.
Can you confirm this is the case?

**Comment by GeorgeWL** [comment]
I'm checking now.

Aha, yeah, rather old a version. 7.4.1. Hmm, the auto-install script should have been more up to date than that, shall have to tell hosting company.
