### ISSUE TITLE
Group email boxes

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#274]
In the CRM, there appears to be bugs/missing functionality with group mail boxes, where emails should be shown/mirrored via IMAP but none or very little emails are shown. This is evident with AOP where users send in case emails, but these aren't shown in the group mailbox.

**Comment by Mausino** [comment]
@willrennie @Dillon-Brown  @samus-aran is this issue relevant from almost 4 years ? I think that this issue don't appear in 7.10.11 and not sure if will fix for old email system 7.8.+ if is on end of its life.  

Maybe should be this issue close or add additional details how to test it step by step and in which version.
