### ISSUE TITLE
Error in Reports page after upgrade: Missing argument 4 for AOR_Report::ACLAccess(),

### ISSUE THREAD

**Issue by jssldb** [salesagility/SuiteCRM#2760]
#### Issue

We recently upgraded from Sugar Enterprise, to CE, then to Suite CRM. On opening the Reports tab for the first time, we get this error about the ACLAccess function in the AOR Reports module. We can't then access the page.

#### Expected Behavior

Expect to be able to access the Reports page.

#### Actual Behavior
The following error is displayed: "Warning: Missing argument 4 for AOR_Report::ACLAccess(), called in /../../../include/MVC/Controller/SugarController.php on line 356 and defined in /../../../modules/AOR_Reports/AOR_Report.php on line 120"

#### Possible Fix

I've looked through some files and seen that ACLAccess() is called in several different modules, but it's only in AOR Reports that it requires the fourth argument, even though ACLAccess is always called with only one argument, with the other two having default values. Does the fourth argument need to be present at all in AOR_Reports? 

#### Steps to Reproduce

1. In menu, go to All > Reports
2. ???
3. Error

#### Context

We won't be able to use the Reports functionality if we can't get past this error.

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Google Chrome Version 54.0.2840.98 (64-bit):

**Comment by dhayner** [comment]
jssldb - Why did you close this?  I have the same issue on a fresh install of 7.7.8 .  Thanks

**Comment by jssldb** [comment]
I thought that it must just be an issue with our install, because I looked at their demo and didn't see anything like our error. But it looks like it's a bigger issue, so I'll reopen.

**Comment by shogunpol** [comment]
@jssldb , is this mean you cannot open report module at all? , did you tried with fresh install?

**Comment by jssldb** [comment]
What I ended up doing, until we got an answer, was simply open the AOR_Report.php and comment out the fourth argument. I couldn't find a single place that actually called for that argument, and all other modules with a similar function only had three arguments.

After doing that, we were able to use to use the Report module.

**Comment by ijdavie** [comment]
@jssldb I would try replacing the line 

function ACLAccess($view,$is_owner='not_set',$in_group='not_set', $target_module){

with 

function ACLAccess($view,$is_owner='not_set',$in_group='not_set', $target_module=""){

from what I can see its complaining it is not being set, adding this may solve the problem. 

if you can confirm if this fixes it that would be great, Thanks.

**Comment by jssldb** [comment]
But then lines ~123-125 inside ACLAccess() say:
`if($target_module != ""){
                $result = ACLController::checkAccess($this->report_module, 'list', true);
}`

Which would mean the access is never actually checked, right?

**Comment by dhayner** [comment]
@ijdavie - I did that and can confirm the main reports page loads successfully now.  Create Report also initially works, however I don't have any data in this instance to test with until later today.  DH

**Comment by ijdavie** [comment]
@jssldb it looks like this fourth var is used to check if users have the ability to export the report data from reports on the detail view. but in some sections this is not used at all hint why it needs to have a ="" so if it is not used it is set.

**Comment by jssldb** [comment]
I added the `=''` and the error is gone.

**Comment by 8temps** [comment]
the same error

**Comment by pgorod** [comment]
In #942 I posted a complete (well, until we find more) list of similar errors. They could all be fixed in one go. There is also a pointer to a fix by gymad that can serve as a template to the correct way of handling this (deprecating the inconsistent interfaces).

**Comment by samus-aran** [comment]
Hi Everyone, this issue should now be resolved as the 4 argument has now been removed. Please re-open if it hasn't.
