### ISSUE TITLE
Can not select resources for Project Template

### ISSUE THREAD

**Issue by chornyitaras** [salesagility/SuiteCRM#2761]
#### Issue
When selecting User or Contact on Popup - selected User/Contact is not assisgned as Project Template resource. 

#### Expected Behavior
When selecting User or Contact on Popup - selected User/Contact should be assigend  as Project Template resource. 

####  Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version: Chrome Version  54.0.2840.99 m (64-bit)
* Environment name and version: MariaDB, PHP  5.5.14
* Operating System and version:  openSUSE Leap 42.2 

Additional info.

php errot log:
```
 PHP Fatal error:  Call to a member function add() on a non-object in /srv/www/htdocs/crm/include/generic/Save2.php on line 201, referer: https://127.0.0.1/crm/index.php?module=AM_ProjectTemplates&action=DetailView&record=720e9fd9-75a1-f458-409a-5845bff48e11&return_module=AM_ProjectTemplates&return_action=view_GanttChart 
````

**Comment by shogunpol** [comment]
@chornyitaras ,the issue has been tested in recent version of SuiteCRM(7.7.8), and not appear, can you provide environment information from "raise issue template", such as: OS, PHP and SQL version and so on?

**Comment by chornyitaras** [comment]
HI I just retested on http://demo.suiteondemand.com/ and issue is still there: 

steps:
1) create Project template.
2) Click on View Details on newly created template
![image](https://cloud.githubusercontent.com/assets/17271728/21094893/bb5f4720-c061-11e6-868b-d4ed13a879c9.png)
3) Click on Select User in selected resources section 
![image](https://cloud.githubusercontent.com/assets/17271728/21094935/eb3bb97e-c061-11e6-83f6-436149622a9c.png)
4) in Popup window select any user ans click on Select button:
![image](https://cloud.githubusercontent.com/assets/17271728/21094975/20fda216-c062-11e6-848b-0c07cac8f6f9.png)
5) Check that selected user is added as resource to project template:
![image](https://cloud.githubusercontent.com/assets/17271728/21095061/7bb20f58-c062-11e6-9da4-da1ed0becb83.png)
