### ISSUE TITLE
Saving EditView from Studio breaks if top row has only one field

### ISSUE THREAD

**Issue by dfstrauss** [salesagility/SuiteCRM#2765]
#### Issue
Modify an EditView inside Studio. Change the top row in any panel to display only one field instead of two. Now click "Save & Deploy". An error pops up and the view is cut off at the row with one field.

#### Possible Fix
I found the bug and will submit a pull request.

#### Your Environment
* SuiteCRM Version used: 7.6.10

**Comment by shogunpol** [comment]
@dfstrauss , an issue doesnt existed in recent version of SuiteCRM(7.7.8), and ben fixed in one of releases, can you confirm is not an issue any more?

**Comment by dfstrauss** [comment]
@shogunpol I found the issue originally on version 7.6.10. Need some time to confirm.

**Comment by dfstrauss** [comment]
@shogunpol I have not been able to reproduce the issue on SuiteCRM 7.6 or 7.7.
