### ISSUE TITLE
MAPS - download import template

### ISSUE THREAD

**Issue by gtrott808** [salesagility/SuiteCRM#277]
7.2.2
the link just takes me to a blank page?

index.php?entryPoint=export&module=jjwg_Maps&action=index&all=true&sample=true

can someone link me the template... would like to be able to import some map addresses soon.  

or is my 7.2.2 install broken?

<a href="javascript: void(0);" onclick="window.location.href='index.php?entryPoint=export&amp;module=jjwg_Maps&amp;action=index&amp;all=true&amp;sample=true'">Download Import File Template</a>

**Comment by willrennie** [comment]
I would take a look at the website and also the JJW Maps youtube for how to set up/use JJW Maps.

http://www.jjwdesign.com/google-maps-for-sugarcrm/
http://www.jjwdesign.com/tag/google-maps/
https://www.youtube.com/user/jjwdesign/videos
