### ISSUE TITLE
On email templates not working ipad/iphone

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#2774]
If you create a template and try to add in email using Ipad/Iphone  the subject will be filled in but the body will be empty.

I have checked and can not find matching bug.

#### Issue

You can not apply a template on iphone/ipad. I test it on Chrome on Android and it worked fine. 

#### Expected Behavior
Create a template and be able to insert it in an email on iPhone/iPad.
#### Actual Behavior
The Ok button never goes away and the Subject is set but body is not see attachment
![template_error](https://cloud.githubusercontent.com/assets/2706403/20970178/deae4e5c-bcbe-11e6-8e53-5beaaae67c6c.jpg)
#### Steps to Reproduce

With iphone/ipad go to the demo on suitecrm.com. Use options and insert template. The subject is completed but the body is not. 

#### Context
Our sales people sue ipads and are unable to send email correctly on the road.

This should be medium priority 

#### Your Environment

SuiteCRM Version used:
Version 7.7.8
Sugar Version 6.5.24 (Build 509)
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Safari/602.1 but also test with Chrome/opera/ firefox (all the latest versions)
Environment name and version (e.g. MySQL, PHP 7):
MySQL PHP6.5
Operating System and version (e.g Ubuntu 16.04):
GNU/Linux

but also does not work on you demo site.

**Comment by Kevconry** [comment]
SuiteCRM's Email/Template Functionality has had a major overhaul since 7.7.8, so this issue will no longer be applicable, as these pages no longer exist in the CRM
However, if you still experience this issue, (or any others), in the recent Email functionality, then please get in touch
