### ISSUE TITLE
can't abort deleting records with *_delete logichooks

### ISSUE THREAD

**Issue by kaleidoc0de** [salesagility/SuiteCRM#2779]
after_delete logic hooks is not working as expected and is unable to provide functionality to prevent deleting records by custom logic

#### Expected Behavior
1. setting deleted from 1 to 0 during after_delete event on record.
2. redirected to listview with the record still present in list.

#### Actual Behavior

1. setting deleted from 1 to 0 during after_delete event on record.
2. redirected to listview without the record in the list
3. checking up in database and can see that deleted was set back to 1 again
after the after_delete logichook

#### Possible Fix
I'm expecting some of the delete code to reside in the general sugarbean class, (the deleted variable definitely is <SuiteDIR>/data/SugarBean.php line 149)
I would also expect that somewhere the delete flag/variable is not being checked but instead being set back to 1.
It's hard to find the exact spot as I don't know if it is possible to stop and step through PHP as it is running

#### Steps to Reproduce
To reproduce
1. add the following to your <SuiteDIR>/custom/Extension/modules/<any module>/Ext/LogicHooks/logichooks.ext.php
`$hook_array['after_delete'][] = array(
    1,
    '',
    'someHook.php',
    'someClass',
    'someMethod',
);
`
2. in the file which the above is pointing to add something like
`class someClass
{
    public function someMethod($focus, $event, $arguments)
    {
      $focus->deleted = 0;
      $focus->save();
    }
}
`
3. repair and rebuild then delete a record of the type that your logic_hook runs

#### Context
I am trying to add custom logic where I can check for certain field values from nested relationships and when those certain values are found then the deleting of the record should be prevented

#### Your Environment
SUITECRM: SuiteCRM 7.7.8
CHROMIUM: Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

DBMS: 5.5.46-cll-lve MySQL Community Server (GPL) by Atomicorp
PHP: 7.0.13

CentOS 6.7

**Comment by shogunpol** [comment]
@kaleidoc0de  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
