### ISSUE TITLE
Adding a placeholder in the field name in the module opportunity

### ISSUE THREAD

**Issue by JiheneElHeni** [salesagility/SuiteCRM#2781]
hello,

What i m asking for, is to know how to add a placeholder in the field name in the module opportunity,
i'm looking for the place where the html is

**Comment by shogunpol** [comment]
@JiheneElHeni  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
