### ISSUE TITLE
Signatures not working on ipad/iphone

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#2789]
When creating an email on suitecrm the signature does not get inserted.

#### Issue
No signature is inserted when using ipad/ipod
#### Expected Behavior
When you have the option for email set on ipad it should insert an signature
#### Actual Behavior
No signature is created

#### Steps to Reproduce

On ipad/iphone go to demo site
In options create a signature 
Assign to the email 
Nothing happens

#### Context
Sales people can not add their signature to emails when trying to contact customers

#### Your Environment
Your Environment

SuiteCRM Version used:
Your demo site and 
ours 
Version 7.7.8
Sugar Version 6.5.24 (Build 509)
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Safari/602.1 but also test with Chrome/opera/ firefox (all the latest versions)
Environment name and version (e.g. MySQL, PHP 7):
MySQL PHP6.5
Operating System and version (e.g Ubuntu 16.04):
GNU/Linux

**Comment by shogunpol** [comment]
@wanesmith , an issue has been tested on recent version SuiteCRM(7.7.8), and not appear. As addition i can tell the drop-downs selection, works in different way, they did not open down, only trigger the selection bar below screen, and you have roll functionality to select an option from drop-down list.
The testing environment was Iphone 6.

**Comment by wanesmith** [comment]
Here is my ipad version
![img_0007](https://cloud.githubusercontent.com/assets/2706403/21182787/701508d6-c237-11e6-9950-16a55da6fe9f.PNG)
Where I have setup the signature on the demo site
![img_0008](https://cloud.githubusercontent.com/assets/2706403/21182846/b29833d6-c237-11e6-9ccf-7138feb17f88.PNG)
No signature in the email.
![img_0009](https://cloud.githubusercontent.com/assets/2706403/21182891/f1df70f4-c237-11e6-9ce1-08ba78aaacc7.PNG)

**Comment by shogunpol** [comment]
@wanesmith , you have also select a signature from drop-down menu, placed on right site of the module.
![001](https://cloud.githubusercontent.com/assets/10746892/21183468/fbd2c33c-c1ff-11e6-90c3-0fc458bec469.png)
![002](https://cloud.githubusercontent.com/assets/10746892/21183471/ff5c320e-c1ff-11e6-9502-ae1654869bb7.png)
![003](https://cloud.githubusercontent.com/assets/10746892/21183473/0217ad48-c200-11e6-9c9c-1bd18986dafe.png)
![004](https://cloud.githubusercontent.com/assets/10746892/21183477/052e6d00-c200-11e6-991a-5a3435de56c5.png)

**Comment by wanesmith** [comment]
![img_0010](https://cloud.githubusercontent.com/assets/2706403/21183823/3c4652d0-c23c-11e6-8ff4-49eae8d91bf9.PNG)

**Comment by shogunpol** [comment]
I did check this issue again in IPad 2 and issue appear.
@wanesmith , thanks for quick responds.

**Comment by wanesmith** [comment]
thank you @shogunpol

**Comment by wanesmith** [comment]
It seems that the problem is a space int the <br/> in the javascript
in vi EmailUICompose.js
this has a space after the br and before the  />
 '<div id="signature-begin"><br />';
 '<div id="signature-begin"><br />';

**Comment by wanesmith** [comment]
@shogunpol 
this is a bit of  kludge but it works:
jQuery(document).ready(function() {
jQuery('#composeButton').click(function(e){numtabs=jQuery("li[id^=composeTab]").length;tinymce.init({ selector: "#htmleditor"+numtabs });});
});

if the author of the script can give a better answer that would be great.

**Comment by Kevconry** [comment]
SuiteCRM's Email/Template Functionality has had a major overhaul since 7.7.8, so this issue will no longer be applicable, as these pages no longer exist in the CRM
However, if you still experience this issue, (or any others), in the recent Email functionality, then please get in touch
