### ISSUE TITLE
Checkbox Internal on Cases Detail View is without label

### ISSUE THREAD

**Issue by mayerelyashiv** [salesagility/SuiteCRM#2795]
#### Issue
The "Internal" Checkbox on Cases Detail View is empty
![image](https://cloud.githubusercontent.com/assets/2909933/21189658/b3a79dd8-c21f-11e6-990b-65297554140c.png)

#### Possible Fix
You have to add:
'LBL_AOP_INTERNAL' => 'Internal',

to /modules/Cases/language/en_us.lang.php

Now it's not working because
'LBL_AOP_INTERNAL' => 'Internal',
is in  /modules/AOP_Case_Updates/language/en_us.lang.php

#### Steps to Reproduce
http://demo.suiteondemand.com/index.php?action=Login&module=Users
Support > Cases 
Go into one Case Detail View

**Comment by samus-aran** [comment]
Technically this issue is closed as it has been resolved, but the issue being that do we need the 'internal' after the Checkbox?
