### ISSUE TITLE
SugarFeed content cut for UTF-8

### ISSUE THREAD

**Issue by Szellszi** [salesagility/SuiteCRM#2796]
#### Issue
Consider the following scenario:
You want to save an Opportunity with a name exactly 28 bytes long and the Account name is exactly 35 bytes long. The default currency is Euro with it's sign (€) in the config and the amount of the opportunity is 2016,03.

With the text of the SugarFeed, this will be more than 255 bytes long (since the € sign takes 3 bytes) so Suite gonna try to cut it after 255 bytes. Since this is at the "middle" of the 3 byte € sign, it will cut it half which results in two invalid characters, which can give the database a hard time.

If we count the UTF-8 characters instead of the bytes of the string, and cut the string as UTF-8, then the problem disappears.

#### Expected Behavior
It should handle well multi-byte characters.

#### Actual Behavior
If the cut happens at the middle of a multi-byte character, then the entry will contain a bad character

#### Possible Fix
Change string functions to their multi-byte counterparts

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: All
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP any
* Operating System and version (e.g Ubuntu 16.04): All

**Comment by dfaure-kdab** [comment]
@shogunpol Please raise the priority, this is a blocker issue because it leads to data loss (opportunity creation fails, the typed in data is just lost). In addition, a fix is proposed and it is confirmed to work. This fix should be applied ASAP. Thanks.
