### ISSUE TITLE
Suggestion - Customisable PDF export file names

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#2801]
#### Issue

Cannot currently alter default PDF file names after export

#### Expected Behavior

Should be able to change the file names of exported reports, invoices and quotes.

#### Actual Behavior

File names are not configurable or changeable

#### Possible Fix

The following code inserted into **modules/AOS_PDF_Templates/generatePdf.php** allows the quote export file name to be changed to the format **quote_[billing_account_name]_[quote_number].pdf**:

```
if ($bean->module_dir=="AOS_Invoices") { 
		// custom naming scheme for Invoices module
		$file_name = "Facture_".str_replace(" ","_",$bean->billing_account)."_".$bean->number."_".substr($bean->invoice_date, 0, 2).substr($bean->invoice_date, 3, 2).substr($bean->invoice_date, -2).".pdf";
		} elseif ($bean->module_dir=="AOS_Quotes") {
		// custom naming scheme for Quotes module
		$file_name = "Devis_".str_replace(" ","_",$bean->billing_account)."_".$bean->number.".pdf";
		} else {			
		$file_name = $mod_strings['LBL_PDF_NAME'] . "_" . str_replace(" ", "_", $bean->name) . ".pdf"; 	// original naming scheme			
	}	
```

#### Steps to Reproduce

None required.

#### Context

Must manually rename exported files to prevent duplicate file names.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - Customisable PDF export file names](https://trello.com/c/WPOnIu40/46-suggestion-customisable-pdf-export-file-names)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
We're suggesting add the field into part of settings of pdf and will aslo possible set variable to name of pdf that will created by variable as the body/subject of pdf template 👍 

Will very usable and the pdf's looks much more profesional if the names of pdf's are customised :) like number of invoice or report or whatever 

![2018-12-10_1053](https://user-images.githubusercontent.com/5773777/49724611-ff500500-fc69-11e8-8586-921e0743940f.png)

**Comment by samus-aran** [comment]
Thanks @Mausino.

So would the immediate solution be to include @blloyd78 suggestion of having the auto increment (bean->number) and then to further enhance that to add the ability to have record variables parsed upon save as the filename?

**Comment by Mausino** [comment]
@samus-aran  yes, can be part of solution.. I am not developer.. i cant test it for you ... but i can't  evaluate code 👍
