### ISSUE TITLE
Email Templates parse Multiselect fields as keys not as labels

### ISSUE THREAD

**Issue by yulahab** [salesagility/SuiteCRM#2802]
**Issue**

Emails which are based on Email Templates with some fields that have variables representing Multiselect  have keys instead of values (e.g in_progress instead of In Progress)

**Steps to Reproduce**

1. Created a dropdown called Object Status in Admin -> Dropdown Editor
2. Created a field for the Contact module called 'Test Multiselect'. This field is a Multiselect type field and has Object Status as its dropdown. Added this field to the EditView and DetailsView of the Contact module.
3. Went to the Contacts record for Britney Walraven (example user) and set the 'Test Multiselect' to In progress.
4. Created an Email template for testing the dropdown values. Where variable corresponding to the 'Test Multiselect' field is included.
5. Created a WorkFlow record to send emails based on the above mentioned template.
6. Made sure that Admin -> Email Settings is setup correctly and sent a test email.
7. Made sure that Process Workflow Tasks sheduler is active.
8. Made sure that crontab is running for my instance.

**Expected Behavior**

I should have received:

Hello,
Status is In Progress .
Best Regards.

**Actual Behavior**

Hello,
Status is in_progress .
Best Regards.

**Comment by yulahab** [comment]
I fixed it with returning old funcitionality

`class templateParser
{

		// ADDED BY NS-TEAM
		function getMultiEnumVal($options,$module,$val_array){
			$res = array();
			foreach($val_array as $key => $val) {
				$res[$key] = translate($options,$module,$val);
			}
			return $res;
		}
		// END ADDED BY NS-TEAM
    static function parse_template($string, $bean_arr)`


Change line:
`                   // $repl_arr[$key . "_" . $fieldName] = implode(', ', unencodeMultienum($focus->$fieldName));
					$repl_arr[$key."_".$fieldName] = implode(', ', templateParser::getMultiEnumVal($field_def['options'],$focus->module_dir,unencodeMultienum($focus->$fieldName)));`

**Comment by yulahab** [comment]
Fix is described in previous comment. Is there any plan for release?
[modules-AOS_PDF_Templates-templateParser.php.txt](https://github.com/salesagility/SuiteCRM/files/730137/modules-AOS_PDF_Templates-templateParser.php.txt)

**Comment by shogunpol** [comment]
@yulahab , can you kindly create Pull Request for your fix, if you do this it can be quickly implemented.
