### ISSUE TITLE
Dashlets wrong data on auto refresh

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#2806]
#### Issue
If Dashlets are set to auto-refresh then randomly the wrong data is displayed

The Title remains as it should be but the body is populated with another dashlet

#### Expected Behavior
The Dashlet should show the correct data

#### Actual Behaviour
Dashlets get mixed up

#### Steps to Reproduce
Install a copy of SuiteCRM 7.7.8 with demo data

Go to home page and amend all Dashlets so auto refresh is set to 30 seconds and untick 'Only My Items'

Keep an eye on the screen 

#### Context
We use Dashlets to monitor the business

My directors consider this a High Priority bug

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Tested in Firefox, Chrome & IE 
* Environment name and version: MySQL, PHP 7
* Operating System and version :  
![2016-12-20 15_01_46-new issue salesagility_suitecrm - cyberfox](https://cloud.githubusercontent.com/assets/3176876/21355306/6c59dd2e-c6c5-11e6-92f6-9666a51c2959.png)
Centos 6.8

**Comment by shogunpol** [comment]
@mikesolo , the issue has been tested in recent version of SuiteCRM(7.7.8) and not appear, 
may i ask is this fresh installation, and did you done any customisation on instance?

**Comment by mikesolo** [comment]
It first appeared on my Live system after I upgraded to 7.7.8
I thought it might be my code
I then installed a clean version of 7.7.8 with demo data
Logged in as admin I set refresh on all dashlets to 30 seconds and unticked 'Only My Items'
Got the issue fairly quickly
The screenshot is from the newly installed version

**Comment by mikesolo** [comment]
My phpinfo file if it helps
![phpinfo](https://cloud.githubusercontent.com/assets/3176876/21396283/98f707bc-c797-11e6-8829-dc5b2b8bc915.png)

**Comment by shogunpol** [comment]
@mikesolo , i tested an issue in very similar environment, and not appear, so another question:
can you test your issue on our official demo? http://demo.suiteondemand.com/  if still appear, it will be something unique in your environment, if not we can keep investigate it.

**Comment by mikesolo** [comment]
@shogunpol
Tried it on your demo
Changed to auto refesh 
watched for a few minutes
same problem
![demo](https://cloud.githubusercontent.com/assets/3176876/21429526/0aa2ece0-c857-11e6-9849-3272b7aba965.png)

**Comment by mikesolo** [comment]
@shogunpol
One other thing I did is move one of the Dashlets to the right hand side
Probably not relevant

**Comment by mikesolo** [comment]
file with problem is include/MySugar/javascript/MySugar.js

**Comment by mikesolo** [comment]
@shogunpol Can the priority of this be increased to high
This is really annoying my users
Dashlets hasn't been working properly for ages 
in 7.7.7 auto refresh breaks dashlets
in 7.7.6 the  you could not display next records
in 7.7.5 add dashlet was broken

**Comment by mikesolo** [comment]
copied MySugar.js from version 7.6.6
Seems to fix the Dashlets

**Comment by bmwtourer** [comment]
@mikesolo   using MySugar.js from version 7.6.6...
did it really solved the issue?
do you have other sideeffects?

We do have a group of people that are on my back because it is *really* disturbing for them

@shogunpol I have a video that shows the problem if interested...

This should be at the top of the medium priority list...  not a show stopper but really disturbing...
Serge

**Comment by mikesolo** [comment]
@bmwtourer 

Serge it does appear to have fixed the problem

Haven't seen any side effects

**Comment by samus-aran** [comment]
Hey @mikesolo, @bmwtourer Would you be able to apply the above proposed fix and see if that corrects the issue?  Would be super to get feedback on that :+1:

**Comment by mikesolo** [comment]
@samus-aran I've tested the fix and it is working well
