### ISSUE TITLE
Cases description won't appear in firefox, EditView

### ISSUE THREAD

**Issue by mikebeck** [salesagility/SuiteCRM#2809]
Cases description won't appear in firefox

Checked that's not duplicate issue
#### Issue

Open Demo page of SuiteCRM with Mozilla Firefox 50.1.0 64bits, select Suite R theme, go to Cases and use the CREATE button top right corner, the description html TinyMCE  box wont load
#### Expected Behavior

It should load the TinyMCE description box
#### Actual Behavior

It doesnt load, but it does on Chrome 55.0.2883.87 m (64-bit)
#### Possible Fix

Don't know a possible fix but is something related to the type of URL that the button calls, is you use the Left Panel "New Case" button does work, the CREATE button calls an ajax URL that it seems that Firefox doesn't like
#### Steps to Reproduce

Same as description

#### Context

This bug affected to me after Commit 1935 that fixed Issue 282, because I use the SuiteR theme and not the P theme

#### Your Environment

* SuiteCRM Version used:
Demo Page 7.7.8 with SuiteR theme
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Mozilla Firefox 50.1.0 64bits
* Environment name and version (e.g. MySQL, PHP 7):
Demo Page
* Operating System and version (e.g Ubuntu 16.04):
Demo Page

**Comment by sanchezfauste** [comment]
This issue is still present on 7.8.10 LTS

**Comment by PedroErnst** [comment]
Fixed by #5840

**Comment by pribeiro42** [comment]
Assessed. Not present in 7.10.11 with Firefox 60.3 (64-bit, Debian linux).

**Comment by samus-aran** [comment]
Will close then. Please reopen if regression.
