### ISSUE TITLE
Case Description Shows HTML Tags

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#282]
The case editor appears to use a new WYSIWG for the description field.  Unfortunately the case view screen handles it as normal text field and displays HTML tags. 

I suppose either the editor screen needs to be changed back to use a regular text field or the view screen has to be adjusted. 

![suite-case-html-issue](https://cloud.githubusercontent.com/assets/1142090/8197421/da169cb2-144c-11e5-9026-633aa0411d8d.png)

Tested with:
Suite CRM 7.2.1 & 7.2.2
PHP 5.3.10

**Comment by ghermans** [comment]
Will this solution get merged soon in a hotfix @willrennie @JimMackin @mattlorimer  ?

**Comment by tfreier** [comment]
@ghermans I'm not sure why they don't merge my pull request but you can make the change yourself.  You only have to change one line.

https://github.com/salesagility/SuiteCRM/pull/283/files

That's what we did.

**Comment by mattlorimer** [comment]
I guess because, I think we are looking more at the solution to display the description as html where present, and for it to be configurable to enable it for a wysiwyg field, but thanks for your input as this is a nice work around

**Comment by adriangibanelbtactic** [comment]
You might be interested on taking a look at my workaround:

https://github.com/salesagility/SuiteCRM/issues/659#issuecomment-207467588

Hopefully it's only a matter of adding a wysiwyg configuration setting as a conditional for my code.
