### ISSUE TITLE
Cannot send mail from outlook using PHP mailer

### ISSUE THREAD

**Issue by affaz2** [salesagility/SuiteCRM#2829]
Sending mail using outlook mail is giving error    'SMTP Error: Could not authenticate. '. What is wrong..Should i make any changes in settings of outlook account? This code is working well with gmail..
Please help me soon.

Code is below

require('phpmailer/class.phpmailer.php');
require('phpmailer/class.smtp.php');
$mail = new PHPMailer();
$emailBody = "helo";

$mail->IsSMTP();
$mail->SMTPDebug = 0;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "tsl";
$mail->Port     = 587;  
$mail->Username = MAIL_USERNAME;
$mail->Password = MAIL_PASSWORD;
$mail->Host     = 'mail.live.com';
$mail->Mailer   = 'smtp';

$mail->SetFrom(SENDER_EMAIL, SENDER_NAME);
$mail->AddReplyTo(SENDER_EMAIL, SENDER_NAME);
$mail->ReturnPath=SENDER_EMAIL;	
$mail->AddAddress($user["email"]);
$mail->Subject = "Test";		
$mail->MsgHTML($emailBody);
$mail->IsHTML(true);

if(!$mail->Send()) {
	$error_message = 'Problem in Sending Password Recovery Email';
} else {
	$success_message = 'Please check your email to reset password!';
}

**Comment by chris001** [comment]
Probably this line:
`$mail->SMTPSecure = "tsl";`
should be:
`$mail->SMTPSecure = "tls";`
Also, you should find and display the exact error message, because an error sending email could happen because of about 50 different reasons.

**Comment by affaz2** [comment]
thanks a lot.. that was the reason.
