### ISSUE TITLE
Autopopulate does not work for Contact Email addresss

### ISSUE THREAD

**Issue by khan01** [salesagility/SuiteCRM#2839]
Adding a relate field for Contact in Custom Module and setting populate_list and field_list to grab the related fields for the selected contact record, does not populate value for Email address. Other plain text fields are working. 

#### Issue

For showing relate fields from Contact module in my Custom Module, i setup the relate field for **Contacts** module in a my custom module with vardefs defined as.

```
'origin_contact_name' => 
	array (
		'inline_edit' => '',
		'labelValue' => 'Contact',
		'required' => false,
		'source' => 'non-db',
		'name' => 'origin_contact_name',
		'vname' => 'LBL_ORIGIN_CONTACT_NAME',
		'type' => 'relate',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'id_name' => 'origin_contact_id',
		'ext2' => 'Contacts',
		'module' => 'Contacts',
		'rname' => 'name',
		'quicksearch' => 'enabled',
		'studio' => 'visible',
		'populate_list' => 
		  array (
			0 => 'name',
			1 => 'id',
			2 => 'phone_mobile',
			3 => 'title',
			4 => 'email1',
		  ),
		'field_list' => 
		  array (
			0 => 'origin_contact_name',
			1 => 'origin_contact_id',
			2 => 'origin_contact_phone',
			3 => 'origin_contact_title',
			4 => 'origin_contact_email',
		), 
	),
	'origin_contact_id' => 
	array (
		'inline_edit' => 1,
		'required' => false,
		'name' => 'origin_contact_id',
		'vname' => 'LBL_ORIGIN_CONTACT_ID',
		'type' => 'id',
		'massupdate' => '0',
		'default' => NULL,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '36',
		'size' => '20',
	),
       'origin_contact_phone' => 
	  array (
		'required' => false,
		'name' => 'origin_contact_phone',
		'vname' => 'LBL_ORIGIN_CONTACT_PHONE',
		'type' => 'phone',
		'massupdate' => 0,
		'no_default' => false,
		'comments' => '',
		'help' => '',
		'importable' => 'true',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'inline_edit' => '',
		'reportable' => true,
		'unified_search' => false,
		'merge_filter' => 'disabled',
		'len' => '255',
		'size' => '20',
		'dbType' => 'varchar',
	  ),
	 'origin_contact_title' =>
		array(
			'name' => 'origin_contact_title',
			'vname' => 'LBL_ORIGIN_CONTACT_TITLE',
			'type' => 'varchar',
			'len' => '150',
			'comment' => '',
			'merge_filter' => 'enabled',
		),
	'origin_contact_email' =>
		array(
			'name' => 'origin_contact_email',
			'vname' => 'LBL_ORIGIN_CONTACT_EMAIL',
			'type' => 'varchar',
			'len' => '150',
			'comment' => '',
			'merge_filter' => 'enabled',
		),
```

In the Edit view of my Custom Module, i show the contacts field as 

```

			 0 => 
			  array (
				'name' => 'origin_contact_name',
				'label' => 'LBL_ORIGIN_CONTACT_NAME',
				'displayParams' => 
				array (
				  'field_to_name_array' => 
					  array (
						'id' 			=> 'origin_contact_id',
						'name' 			=> 'origin_contact_name',
						'phone_mobile'	=> 'origin_contact_phone',   
						'email1' 		=> 'origin_contact_email',
						'title' 		=> 'origin_contact_title',					
					 ),
			  	  ),
			 ),
			 1 => 
			  array (
				'name' => 'origin_contact_phone',
				'label' => 'LBL_ORIGIN_CONTACT_PHONE',
			  ),
			  2 => 
			  array (
				'name' => 'origin_contact_title',
				'label' => 'LBL_ORIGIN_CONTACT_TITLE',
			  ),
			  3 => 
			  array (
				'name' => 'origin_contact_email',
				'label' => 'LBL_ORIGIN_CONTACT_EMAIL',
			  ),
		
```

#### Expected Behavior

In my custom module edit view, if i type in the Contacts relate field, it shows me list of results and when i select a particular record, the fields in "populate_list" would be fetched from selected Contact and being populated in the "field_list" . 

#### Actual Behavior

All fields are populated except the Email Address. If i select the arrow and select a contact form Popup window, it does populate the Email address, but when i type contact name and select record from the suggested dropdown list, it does not populate email address. 

#### Steps to Reproduce

1. In any custom module add/paste the vardefs code for adding contact relate field 
2. In edit view of custom module, put the code for edit view that is provided above.
3. After repair/rebuild, edit the record in custom module. 
4. Type in contact name and select record
5. origin_contact_phone and origin_contact_title would be populated but not origin_contact_email.

#### Context

Medium
#### Your Environment

* SuiteCRM Version used: Version 7.7.8 Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 55.0.2883.87 (32-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.17, PHP 5.5.12
* Operating System and version (e.g Ubuntu 16.04): Windows 7 32-bit

**Comment by shogunpol** [comment]
@khan01  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by Er-Kalpesh** [comment]
So did you get any solution for this ?
