### ISSUE TITLE
Calls relationship is not displayed

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#284]
In the Accounts and Contacts module, the calls relationship panel is not displayed.

![schermafdruk van 2015-06-17 20 51 35](https://cloud.githubusercontent.com/assets/1594411/8215883/60617d8c-1533-11e5-9633-0409bd9807b0.png)
![schermafdruk van 2015-06-17 20 52 47](https://cloud.githubusercontent.com/assets/1594411/8215882/6060e4e4-1533-11e5-8810-a07405bf4217.png)

**Comment by mattlorimer** [comment]
calls  ( and meetings, tasks, emails), are shown in the activities and history subpanel
