### ISSUE TITLE
Selection of long name

### ISSUE THREAD

**Issue by CamoMacdonald** [salesagility/SuiteCRM#2844]
#### Issue

On Firefox, when you select an option from a multiselect the option name is cut off
#### Expected Behavior

Should display the whole name

#### Steps to Reproduce (FireFox)
1. Have a user with a long name 
2. Go to a module e.g. Cases and go to the Advanced search
3. Click on the users name 

#### Context
The user 'Long Name Test User Account' is displayed
![1](https://cloud.githubusercontent.com/assets/20798044/21548421/26558438-cde4-11e6-9051-a8dc717c806e.png)

When you select it the name is cut off to just 'Long Name Test'
![2](https://cloud.githubusercontent.com/assets/20798044/21548423/2899a490-cde4-11e6-9223-a9f5c58f6448.png)

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FireFox
* Operating System and version (e.g Ubuntu 16.04): 14.04

**Comment by Dillon-Brown** [comment]
No longer an issue in 7.8.x.
