### ISSUE TITLE
Cant remove USD from Currencies and set EUR as default 

### ISSUE THREAD

**Issue by JoinJoin** [salesagility/SuiteCRM#285]
Cant remove USD from Currencies and set EUR as a default. 

We do not want any USD hanging around the system to avoid possible miscalculations etc.

**Comment by mattlorimer** [comment]
you can set the default system currency in Admin->Locale, if that doesn't work your permissions are not set correctly,

you can also set the default currency in the config

**Comment by JoinJoin** [comment]
If after this USD is not visible to users and not used in any form, I am happy.

**Comment by Bobby-AgrilandFS** [comment]
I've read this multiple times!  Can someone screenshot where this is at?  Maybe its not on the updated copies but i'm stuck with Euro and need USD.  For the love of god there is absolutely no fucking where to change this at lol
