### ISSUE TITLE
Beta: Filters button does nothing

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#2850]
#### Issue
Trying out the new Beta, the "Select columns" button works as intended, but the filters button does nothing when clicked.

#### Expected Behavior
Open some kind of Filters window, I suppose.

#### Actual Behavior
Nothing happens, and the browser console shows the following error:

![filters](https://cloud.githubusercontent.com/assets/15945027/21586954/7aa06d36-d0ce-11e6-8446-8cfbfd445c83.jpg)

#### Steps to Reproduce
1. On the new 7.7.8  Beta, go to any list view and click the new filters button.

I tried on several different modules (Contacts, Accounts, Leads)
I also tried it on the two themes, SuiteR and SuiteP.

#### Your Environment

* SuiteCRM Version used: 7.8.0-beta
* Browser name and version: I tried it on Firefox and Edge, latest versions
* Environment name and version: MySQL 5.7, PHP 7.0
* Operating System and version: Ubuntu 16.04

**Comment by pgorod** [comment]
It seems to be working now, without any special intervention.

I had remembered to do a Quick Repair and Rebuild right after the upgrade, so that wasn't the problem. It must have been some caching issue...

**Comment by shogunpol** [comment]
@pgorod , so do you see issue or not? :)  If yes, what you mean by filters? (you mean those increase/decrease arrows?),
If not: can you close issue.

**Comment by pgorod** [comment]
@shogunpol 

The button I meant was this one:

![filters2](https://cloud.githubusercontent.com/assets/15945027/21639366/889ef0e8-d267-11e6-81c3-6fd649fe7ec6.jpg)

Anyway, I can definitely close, the issue is not happening anymore. I just found it strange to have 2 new buttons, one works, the other doesn't, but something with caching must have been causing the weird behavior.
