### ISSUE TITLE
Does an employee needs to be an administrator? [Language strings]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2851]
#### Issue

The language string in modules/Employees/language
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Employees/language/en_us.lang.php#L118-L119
states that an employee must be an administrator. Why? The requirement should only be for users, not necessarily employees.
```
  'ERR_LAST_ADMIN_1' => 'The employee name "',
  'ERR_LAST_ADMIN_2' => '" is the last employee with administrator access.  At least one employee must be an administrator.',
```

#### Expected Behavior

At least one user must be an administrator
see: modules/Users/language
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Users/language/en_us.lang.php#L67-L68

```
    'ERR_LAST_ADMIN_2' => '" is the last user with administrator access.	At least one user must be an administrator.',
```

#### Your Environment

* SuiteCRM Version used: 7.8 beta (same in previous versions)

**Comment by pgorod** [comment]
This is somewhat confusing, but I think that in SugarCRM/SuiteCRM `Employees` and `Users` are the same thing. I would prefer to conflate the two concepts and go with just `Users`, but it's probably too complicated to fix that in all places.

**Comment by likhobory** [comment]
Agree with @horus68, according to the [SugarCRM documentation](http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/CE/Application_Guide/Employees/) it's not the same thing.

**Comment by shogunpol** [comment]
@horus68 , syntactically is everything straight forward: the 'ERR_LAST_ADMIN_1' is used to assign user name on the beginning of error string, and after this is adding the: 'ERR_LAST_ADMIN_2'. 

And structure is merged together in User.php:
 $this->error_string .= $mod_strings['ERR_LAST_ADMIN_1'].$this->user_name.$mod_strings['ERR_LAST_ADMIN_2'];
After to those placeholders are added meaning, described in quotes after => sign.

@likhobory , yes SugarCRM doc, explain it by:
"All Sugar users are employees, not all employees are Sugar users." , which does not have any relation with naming placeholders for language strings.

**Comment by horus68** [comment]
@shogunpol question here is the statement at the end of the sentence `At least one employee must be an administrator`
This is not correct.

**Comment by shogunpol** [comment]
@horus68 , yes it is correct, according to: "All Sugar users are employees" [SugarCRM documentation](http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/CE/Application_Guide/Employees/),

however if you still suggest it is something wrong there, i can raise your suggestion for future investigation, if not please close an issue.

**Comment by horus68** [comment]
Its ok from me!
