### ISSUE TITLE
Prevent "Fatal error: Uncaught ArgumentCountError: Too few arguments to function AOR_Report::ACLAccess()"-Exception on PHP 7 environments

### ISSUE THREAD

**Issue by mugge6** [salesagility/SuiteCRM#2853]
#### Issue
Listview on module AOR_Reports will display a FATAL-Error on a SuiteCRM instance which is running on PHP 7.1

Following error will be displayed:
```
( ! ) ArgumentCountError: Too few arguments to function AOR_Report::ACLAccess(), 1 passed in /var/www/html/include/MVC/Controller/SugarController.php on line 356 and exactly 4 expected in /var/www/html/modules/AOR_Reports/AOR_Report.php on line 120
Call Stack
#	Time	Memory	Function	Location
1	0.0001	374440	{main}( )	.../index.php:0
2	0.1068	2621928	SugarApplication->execute( )	.../index.php:52
3	0.1238	3115368	SugarController->execute( )	.../SugarApplication.php:105
4	0.1509	3225288	SugarController->processView( )	.../SugarController.php:310
5	0.1592	3268752	AOR_Report->ACLAccess( $view = 'list', $is_owner = ???, $in_group = ???, $target_module = ??? )	.../SugarController.php:356
```

#### Expected Behavior
List view from module AOR_Reports

#### Actual Behavior
FATAL-Error will be displayed to the user.

#### Possible Fix
Make last argument on function ACLAccess on class AOR_Report optional with empty string as default value.

#### Steps to Reproduce
1. Install SuiteCRM 7.7.9
2. Got to Listview from module AOR_Reports
3. FATAL-Error will be displayed

#### Context
Tried to install newest SuiteCRM release with PHP 7.1.

#### Your Environment
* SuiteCRM Version used: 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 55.0.2883.87 m
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Windows

**Comment by pgorod** [comment]
I tried opening "Reports" on my SuiteCRM 7.8-beta with PHP 7.0.8 on Ubuntu 16.04 and it seems to work fine.
