### ISSUE TITLE
AOS_Quote quick edit not saved

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#2855]
#### Issue

Any value assigned to the "Opportunity" field on a quote is not saved when using the quick edit functionality - even when selected from the auto-complete options

#### Expected Behavior

Opportunity value should be saved.

#### Actual Behavior

The value is cleared and nothing is saved.

#### Possible Fix

Unknown

#### Steps to Reproduce

1. Create a new Quote, but save it without a value in the Opportunity field
2. Open the detail view for the new Quote
3. Double click the Opportunity field to access the quick-edit option
4. Type the name of a valid Opportunity, then select the appropriate entry from the available options.
5. Press Enter to save the new value

The field will automatically blank itself, and no data is saved.

#### Workaround
Using the "picker" tool to search and select the correct Opportunity. The selected result IS saved as expected.

This is an unsatisfactory long-term fix however as it severely impacts productivity by making the process much slower.

#### Context

Suggest medium priority as this could result in important contextual data being lost, or duplicate quotes being generated against Opportunities.

#### Your Environment

* SuiteCRM Version used: 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by shogunpol** [comment]
@blloyd78 , an issue has been tested on recent version of SuiteCRM(7.7.9), and not appear, did you try it on fresh install or upgraded once?

**Comment by blloyd78** [comment]
This issue was tested on a live 7.7.9 install that has been upgraded from 7.7.8 in the past few days.

**Comment by shogunpol** [comment]
@blloyd78 , two questions: 
1. error logs?
2. did you try other browser?

**Comment by blloyd78** [comment]
As requested:

1. There are no errors recorded in the suitecrm.log file
2. The same incorrect behaviour is present when using the Chrome browser.

I have also noted that any inline edits made to pre-populated Opportunity fields are not saved.

**Comment by shogunpol** [comment]
@blloyd78 , do you have done some customisation on module (and instance), 3rd party and so on?

**Comment by blloyd78** [comment]
The only 3rd party add-on installed is the QuickCRM Mobile Basic module - and that doesn't work on AOS_Quotes or AOS_Invoices.

**Comment by shogunpol** [comment]
can you try an issue on our official demo, if still appear it will be some environmental issue.

**Comment by blloyd78** [comment]
I have created Test Quote A (quote #1) here: http://demo.suiteondemand.com/index.php?module=AOS_Quotes&action=DetailView&record=b3b2ded3-1acd-c78c-e57a-586e1a6ef225

I can confirm that the problem is present here too - inline changes to the Opportunity name are not saved. I have also found that the autocomplete/search function only works once. You cannot attempt a second inline edit without first reloading the quote.

**Comment by geconly** [comment]
The inline edit does not work for the Contact or Account Either.

**Comment by horus68** [comment]
@geconly you missed the confirmation sign in each field:
![2017-09-20 12_10_17](https://user-images.githubusercontent.com/3055443/30640916-e738ee54-9dfc-11e7-94dc-2a6e18db2b1e.png)

@blloyd78 Can you close this issue?

**Comment by blloyd78** [comment]
Can no longer recreate this issue on the 7.9.5 demo site

**Comment by geconly** [comment]
The issue I am experiencing is NOT fixed.

You cannot edit inline the Name in the Lead detailview and have it save.

**Comment by horus68** [comment]
@geconly confirmed for the LEAD name.
I assume this is a different problem, so please can you start a new issue?
