### ISSUE TITLE
Email Module Window Too Wide When Left Sidebar is Open (7.2.2)

### ISSUE THREAD

**Issue by jnew1** [salesagility/SuiteCRM#286]
SuiteCRM: 7.2.2
OS: Linux
PHP: 5.3.28 
Database: 5.5.44-MariaDB
Web Server: LiteSpeed V5.5
Browsers: Firefox 38.0.1, Chrome 43.0.2357.125, Konqueror 4.11.5

Issue: When the Email Module is opened, and the left sidebar is active (i.e. opened), the email client is too wide for the browser window and horizontal scroll bars are active, forcing a horizontal scroll to see the right side of the email controls.This is especially disruptive when composing an email, and the Options or Attachment buttons are pressed, the respective option boxes are not visible without a horizontal scroll to the right.

When the left sidebar is closed, the horizontal scroll bars disappear and the email client is completely visible. When composing an email, and the Options or Attachment buttons are pressed, the respective option boxes become visible without a horizontal scroll to the right.

**Comment by samus-aran** [comment]
Issue Resolved in 7.8.x (regards to the centring of the settings windows)
