### ISSUE TITLE
Forums are not sending notification emails

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#2868]
This is just to notify SalesAgility that the SuiteCRM forums (https://suitecrm.com/forum) stopped sending notification emails earlier today.

At least for me - there were several threads that I had participated in (and was subscribed to) that got answers and I didn't receive the usual emails. My email seems to be working fine...

Do other people notice the same issue?

**Comment by horus68** [comment]
me too.
Latest was 4-Jan-2017 - 12:16 GMT

**Comment by willrennie** [comment]
This issue has been resolved. Please confirm that you're receiving notifications.

**Comment by samus-aran** [comment]
Just a wee note that lets keep Github to SuiteCRM project specific rather than bring forum issues here as well ;)  It may seem like a quicker response but lets nip this in the bud and if there is a forum specific issue then please make a forum thread about it (which I couldn't see one when I searched). :)

**Comment by pgorod** [comment]
@samus-aran had I know you would be so active on the forums again today, I wouldn't have hesitated to start this thread there... but yes, I did it here for the speed of handling - and, well, to get notifications of progress! : - )

Anyway, I stand corrected, and I've closed this, but I haven't actually seen the notifications working again, because nobody has yet replied to any of my threads in this period. I'll just assume that if it's working for you, it's working for everybody. Thanks

**Comment by samus-aran** [comment]
@pgorod No, no I understand why you posted here and it worked - it got Will and my attention.  I was just stating that we can't have the line crossed with regards to where help shoul dbe found and that is a known  situation internally.  
Regards to the notification, they should be working on subscribed thread as I have been receiving them now. :)  See you on the fourms :+1:
