### ISSUE TITLE
accounts_contacts relationship ambiguity

### ISSUE THREAD

**Issue by selimerunkut** [salesagility/SuiteCRM#287]
The native accounts_contacts relationship is definied as as a many-to-many relationship but is presented as a one-to-many relationship in the interface.
 
Sugarcrm also indicates the problem in this article:
https://support.sugarcrm.com/04_Knowledge_Base/03End_Users/100Accounts/Understanding_the_Accounts-Contacts_Relationship/

Because the relationship is capable of relating a contact records to multiple accounts but in the Views its displayed as its only related to a single account (Contact editView) or
Duplicate entries in the Contacts ListView if the contact is related to multiple Accounts.

My assumption is that sugarcrm did not really know what they where doing (its so obvious that they needed to create the above article) and because suitecrm has inherited the core of sugarcrm should address this Issue.

**Comment by selimerunkut** [comment]
In this forum posts (first 3 posts )are also some of the strange behaviors explained, although it is for sugarcrm 6.x Version the same behavior can be replicated in suitecrm:
https://community.sugarcrm.com/sugarcrm/topics/cant-change-relationship-between-accounts-and-contacts-1-many

**Comment by jobvector** [comment]
why invalid, issue can be replicated in suitecrm?

**Comment by mattlorimer** [comment]
its working as intended
