### ISSUE TITLE
Related Contacts\' Emails - Language string

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2872]
#### Issue
Why is there a `\' ` in `Related Contacts\' Emails` language value?
` 'LBL_CONTACT_HISTORY_SUBPANEL_TITLE' => 'Related Contacts\' Emails',
`
See 5 occurrences on language values
https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=%22Related+Contacts%27+Emails%22

#### Expected Behavior
`Related Contacts Emails`

#### Possible Fix

Remove the extra `\' `

#### Context
Confusion when translating

**Comment by pgorod** [comment]
It's supposed to have the apostrophe there, it's a [possessive of a plural noun](http://www.thepunctuationguide.com/apostrophe.html). 

With the apostrophe, it means `Emails of the related contacts`.

The backslash is not supposed to show, it's supposed to just escape the single quote. I guess that is what's misleading you.

**Comment by horus68** [comment]
Thanks! Crowdin was not escaping that string. After re-uploading its fine now.
