### ISSUE TITLE
Duplicated language strings in Case module (7.8.0-beta)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#2874]
Subj.

https://github.com/salesagility/SuiteCRM/blob/v7.8.0-beta/modules/AOP_Case_Updates/Case_Updates.php#L354-L355

![int](https://cloud.githubusercontent.com/assets/5983672/21750282/ba993476-d5c0-11e6-96df-d9bb83da1528.png)

------------------------------------

['LBL_INTERNAL'] 
['LBL_AOP_INTERNAL'] 

https://github.com/salesagility/SuiteCRM/blob/v7.8.0-beta/include/language/en_us.lang.php#L2453

https://github.com/salesagility/SuiteCRM/blob/v7.8.0-beta/modules/Cases/language/en_us.lang.php#L148

https://github.com/salesagility/SuiteCRM/blob/v7.8.0-beta/modules/AOP_Case_Updates/language/en_us.lang.php#L75-L76

All this labels are still relevant or part of them can be removed?

**Comment by shogunpol** [comment]
@likhobory , all those labels are used and cannot to be removed,

**Comment by likhobory** [comment]
thanks, @shogunpol 
Probably I awry combined two questions in one issue - and what about the first part of the issue? (see screenshot above). The label "Internal" displays twice near the checkbox.

**Comment by shogunpol** [comment]
case updates

**Comment by shogunpol** [comment]
@likhobory , first part of this issue is duplication of issue #2795 , it already have fix proposed, so i hope it help to you.
