### ISSUE TITLE
Inbound Email 7.8 Beta

### ISSUE THREAD

**Issue by CamoMacdonald** [salesagility/SuiteCRM#2878]
#### Issue

You cant select the inbound mail boxes
#### Expected Behavior

When you try select a mail box you should be able to click on the correct option
#### Actual Behavior

When you click select the screen becomes unresponsive and you cannot select a mail box

#### Steps to Reproduce

1. Go into Admin > Inbound Email 
2. Create a New Group Mail or Bounce Handling Account
3.  Fill in the appropriate information and click SELECT next to Monitored Folders etc
4. The Screen goes unresponsive and you cant select the mail box

#### Your Environment

* SuiteCRM Version used: 7.8 Beta
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox

**Comment by pgorod** [comment]
[In the forums](https://suitecrm.com/forum/suitecrm-beta/12734-7-8-beta-2-not-able-to-access-pop-up-windows#43019) somebody ran into similar issues, I wonder if they could be the same problem with the z-index... and I wonder if it's happening in more places.

> The pop up window cannot be accessed.
> 
> One example is at Admin > Email Settings > Send Test Email. The other example is at Emails > Settings 

Unfortunately, no screenshots were given, and that is the entire text, so we don't _really_ know what he means.
