### ISSUE TITLE
[7.8-beta] Search form not visible in Listview (all themes)

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#2884]
In the listview of a module the search form is not visible.
You have to click on the "filter" symbol.
Why i say it is a bug: 
When you want to see the listview, you almost always want to search. Needing one click more is not productive.
I can see no scenario where you want to see the listview as is without searching.

**Comment by samus-aran** [comment]
@gunnicom this was a functionality decision to reduce the space that the search layout takes up - which users have already stated they wish for a more compact design.  Yes initially an extra click will be present, to update a search, but if you have saved searches that will reduce the time and clearing searchs will also reduce the time.

Also you have the ability to revert to the standard basic/advanced search by setting in the config.php or config_overwrite.php

'use_legacy_search' => 
  array (
    0 => 'Accounts',
    1 => 'Users',
    2 => 'Employees',
      3 => 'Calls',
      4 => 'Meetings'
  ),

So those above modules will use the legacy search.
