### ISSUE TITLE
Custom Label of a relation not displayed

### ISSUE THREAD

**Issue by jcwerck** [salesagility/SuiteCRM#2886]
#### Issue
I have created a new relation between Users and Projects (1-N type).
When I want to customize the Label of the field added in the Project module, the new label is not taken into account.

#### Expected Behavior
I want to see the label "Chef de projet" instead of "Utilisateurs" in front of  the field added in the Projects module for the relation between "Users" and "Projects", by changing the value of the label LBL_USERS_PROJECT_1_FROM_USERS_TITLE in the studio.

#### Actual Behavior
When I click on "Save & Publish", the file custom/modules/Project/language/fr_FR.lang.php is updated (I find the right label for  'LBL_USERS_PROJECT_1_FROM_USERS_TITLE') but the label is still "Utilisateurs" in the Studio screen and the label is still "Utilisateurs" when I go to the Project screen.

#### Possible Fix
Perhaps it is because of the long name of the Label. Customization of others label for the same module works fine.

#### Steps to Reproduce
1. Create a custom relation 1-N between Users and Projects
2. Go to the Studio > Project > Labels and edit the value of LBL_USERS_PROJECT_1_FROM_USERS_TITLE
3. Click on "Sauvegarder & publier",
The file custom/modules/Project/language/fr_FR.lang.php is modified but label is still "Utilisateurs" in the screen.

#### Your Environment
* SuiteCRM Version used: 7.7.9
* Browser name and version : Chrome Version 55.0.2883.87 m (64-bit)
* Environment name and version : MariaDB 5.5.50 / PHP 5.4.16 / Apache 2.4.6
* Operating System and version : CentOS Linux release 7.2.1511

**Comment by Kevconry** [comment]
Can't replicate in 7.13.1, please re-raise or get in touch if you are still having this issue
