### ISSUE TITLE
Workflow Conditions Is Null operator console error

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#2888]
#### Issue
When adding a workflow condition and selecting the "Is Null" value, a console error is thrown
![image](https://cloud.githubusercontent.com/assets/20977561/21825460/d5bf09be-d751-11e6-9320-8a2273c8db51.png)

#### Expected Behavior
Should allow selection without console error

#### Actual Behavior
Console error is triggered.

#### Your Environment
SuiteCRM v7.7.8 & v7.7.9
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 55 on Windows 10 (same behavior with other browsers)

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.9.4. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
