### ISSUE TITLE
Workflow Condition on custom field error

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#2890]
#### Issue
If using a workflow condition on a custom field, the resulting query generates an error. For example, I've added the custom field "division_c" in the users module and if added as a workflow condition, a log error is generated

Tue Jan 10 16:39:00 2017 [6916][1][FATAL]  Get One Failed:
SELECT aos_quotes.id AS id
FROM aos_quotes
LEFT JOIN users assigned_user_link ON aos_quotes.assigned_user_id=assigned_user_link.id AND assigned_user_link.deleted=0
LEFT JOIN users_cstm assigned_user_link_cstm ON users.id = assigned_user_link_cstm.id_c
WHERE assigned_user_link_cstm.division_c = 'x' AND aos_quotes.id = 'x': MySQL error 1054: Unknown column 'users.id' in 'on clause'

By looking at at query, the 2nd left join should be assigned_user_link.id = assigned_user_link_cstm.id_c and not users.id = assigned_user_link_cstm.id_c

#### Your Environment
SuiteCRM v7.7.8 & v7.7.9
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 55 on Windows 10 (same behavior with other browsers)

**Comment by shogunpol** [comment]
@staganyi , i tested the issue on 7.7.9, and it not appear, i added custom field (type: TextField) using in work flow and works as expected, so to replicate an issue i need information about what ecact conditions and values you used. Also Assume instance is fresh install (or update?),

**Comment by staganyi** [comment]
This occurred on an upgrade and fresh install of 7.7.8 & 7.7.9. Below is a screen cap of the workflow and of note, the custom field is a drop down (maybe that has something to do with it).

![image](https://cloud.githubusercontent.com/assets/20977561/21853267/6d5584aa-d7e4-11e6-94aa-dade08fd813d.png)

**Comment by shogunpol** [comment]
@staganyi , is this issue happen in Windows environment? and what version of SQL you use. Also is there any errors in log?

**Comment by staganyi** [comment]
Sorry for not putting that in my environment info

Ubuntu Linux 14.04.1
MySQL version 5.5.53

**Comment by FibreCRM** [comment]
We have a fix for this issue.  We have this same issue and wrtoe a fix.  Can this fix be added to core?
[AOW_WorkFlow.zip](https://github.com/salesagility/SuiteCRM/files/852773/AOW_WorkFlow.zip)

**Comment by adriangibanelbtactic** [comment]
> @staganyi , i tested the issue on 7.7.9, and it not appear, i added custom field (type: TextField) using in work flow and works as expected, so to replicate an issue i need information about what exactly conditions and values you used. 

We happen to have found bug a while ago so we know how to describe.
The custom field that you create needs to be found on a related module (In the @staganyi example it is Users) not in the same module (In the @staganyi example it would be Quotes).

I think that if you use a non custom field then the bug does not happen.

**Comment by adriangibanelbtactic** [comment]
I have ported my fix based on v7.4.3 to 'develop' branch here:
https://github.com/btactic/SuiteCRM/commit/b8ea34003e4eeddeb96418573f58bd1bde672c7 .
I have been unable to test it though.

@FibreCRM . What do you think about our fix? I have overlooked your 'patch' and either ours was too overly complicated or yours only fixes some relationship scenarios but not everyone of them.

@shogunpol : Should I submit it as a pull request so that you can test it easier?
O r more testing is needed and you are ok on pulling manually from our https://github.com/btactic/SuiteCRM/tree/workflow-related-module-custom-field-issue-2890 branch for doing your own tests with our fix?

**Comment by adriangibanelbtactic** [comment]
Updated branch of my fix (be able to be merged on 7.7.X) : https://github.com/btactic/SuiteCRM/tree/workflow-related-module-custom-field-issue-2890-v2

Associated commit: https://github.com/btactic/SuiteCRM/commit/6789547d6df5a862eedaf324160da9f7178b6c6a .

**Comment by samus-aran** [comment]
Hi Guys there is a fix proposed which also includes unit tests provided by @sanchezfauste 
Can you please confirm that this works for all of yous when you have the chance so we can merge this in. Thanks
@staganyi @FibreCRM @adriangibanelbtactic
