### ISSUE TITLE
marketing campaigns not working

### ISSUE THREAD

**Issue by indra1** [salesagility/SuiteCRM#2894]
Hi,
I have a suite crm 7.7.8 installation on ubuntu server running php 7.0 that I am trying to get familiar to in order to add some customization.

When I try to add a marketing campaign by importing a file i get this error:
NOTICE: [8] Accessing static property ImportFieldSanitize::$createdBeans as non static on line 143 in file /var/www/html/exam/modules/Import/Importer.php
NOTICE: [8] Accessing static property ImportFieldSanitize::$createdBeans as non static on line 430 in file /var/www/html/exam/modules/Import/Importer.php
NOTICE: [8] Accessing static property ImportFieldSanitize::$createdBeans as non static on line 143 in file /var/www/html/exam/modules/Import/Importer.php
NOTICE: [8] Accessing static property ImportFieldSanitize::$createdBeans as non static on line 430 in file /var/www/html/exam/modules/Import/Importer.php

And when I try to add it manually at the last step it takes me back to the add campaigns page without saving anything.

Can you give me a solution or point me to the right piece of code please?

**Comment by mattlorimer** [comment]
This should be resolved in 7.7.9, I'd suggest you upgrade to that.

**Comment by dursuntosun** [comment]
Yes, when i try it with 7.7.9, it is solved.
