### ISSUE TITLE
Assigned to field not populated on new record creation

### ISSUE THREAD

**Issue by marbanas** [salesagility/SuiteCRM#291]
Hi!

 I have a problem with creation of new records:

 * when any kind of new record is being created, the field "Assigned to" is not populated automatically, and even if I click to select user - popup window for user selection pops out with no user to select from

 * this happens for any user except for admin = for admin user it works fine

 Can anyone suggest fix for this?

 I use:

Version 7.22 
Database: SQL Server
Hosted on IIS8
PHP 5.4
Browser: tried Chrome, IE, Mozzila, Opera = all same issue

Creation error - REGULAR USER
![creation_error_message_regular_user](https://cloud.githubusercontent.com/assets/13147951/8472985/19b2c930-20a6-11e5-9572-a9fa1b2718f1.PNG)

User selection popup REGULAR USER
![user_selection_popup_regular_user](https://cloud.githubusercontent.com/assets/13147951/8472987/19b48dec-20a6-11e5-8300-91252e90453f.PNG)

Creation screen - ADMIN USER
![creation_admin_user](https://cloud.githubusercontent.com/assets/13147951/8472986/19b3bc46-20a6-11e5-8ff1-5ec8be13f4e4.PNG)

User selection popup ADMIN USER
![user_selection_popup_admin_user](https://cloud.githubusercontent.com/assets/13147951/8472988/19b5c478-20a6-11e5-86f8-3f4b7d805053.PNG)

 Thx for swift reply! ;)

 Mario

**Comment by darthtang** [comment]
Hi Mario

I've just been investigating your bug and cant seem to reproduce it! When i use a user account, and then go to create an account. The 'assigned to' field is automatically filled in for me and have no problem  clicking on the 'assigned to' popup button!

have you tried creating a new instance of Suite and checking if the bug still occurs?

**Comment by willrennie** [comment]
Advice given, no response to this issue. If you are still having issues please try the recommended steps to resolve by darthtang.
