### ISSUE TITLE
install suitecrm and wordpress on the same sql table

### ISSUE THREAD

**Issue by marindumont** [salesagility/SuiteCRM#2916]
#### Issue
I have wordpress installed on a web hosting (ovh).
i try to install suitecrm on the same server and same sql database (no other database on my server)
After the installation of suitecmr, suitecrm is working fine but my blog wordpress need to be reinstalled. All data seems lost

#### Possible Fix
propose to choose a prefix of the sql table during installation like wordpress with wp_
I thinks it's solve the problem

#### Steps to Reproduce
1. install wordpress 
2. post some news on wordpress
3. install crmsuite, use it
4. run on wordpress: installation needed !

#### Context
Already a wordpress installed on the serveur, same database sql

#### Your Environment

* SuiteCRM Version used:  7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome updated / edge
* Environment name and version (e.g. MySQL, PHP 7): Mysql, php5.3
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by shogunpol** [comment]
@marindumont , you must have two databases separate for SuiteCRM and Wordpress, 
 Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.
