### ISSUE TITLE
My activity stream , empty lines due to security groups.

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#2921]
Got this behavior on suitecrm 7.7.9.

i'm working with sercurity groups. roles are set to GROUP so each security group users cannot see posts from the other group. however a blank line is added for each post from the other group.

![scrm](https://cloud.githubusercontent.com/assets/8605061/21985994/acc0eae0-dbfd-11e6-8525-757ac15f8493.png)

**Comment by pgorod** [comment]
@boombata you can close this yourself, if you agree. I've reopened the other bug and Jason Eggers has promised his help there - he's the author of all this Security Suite code. Thanks for your efforts, they helped nail this down and get a fix started again.

**Comment by boombata** [comment]
I agree thaks for your help
