### ISSUE TITLE
Intallation failure: PHP Fatal error:  Call to a member function error() on null

### ISSUE THREAD

**Issue by pgrzywacz** [salesagility/SuiteCRM#293]
During installation after choosing my installation language I get a blank page. In error log I have the following lines:

    [Mon Jul 06 16:00:12.860980 2015] [:error] [pid 2001] [client 192.168.6.34:44205] PHP Notice:  Undefined index: log in /var/www/suitecrm/include/utils/sugar_file_utils.php on line 87, referer: https://xxxx/install.php
    [Mon Jul 06 16:00:12.861259 2015] [:error] [pid 2001] [client 192.168.6.34:44205] PHP Fatal error:  Call to a member function error() on null in /var/www/suitecrm/include/utils/sugar_file_utils.php on line 87, referer: https://xxxx/install.php

It seems sugar_mkdir fails and tries to inform me about it using $GLOBALS['log'] before it is made available. Due to this I am unable to see which directory is causing problems.

PHP version:

    PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

Apache version: `Server version: Apache/2.4.10 (Debian)`

**Comment by willrennie** [comment]
You will need to set the appropriate permissions before installing the CRM. That is the most likely cause of the white screen after the language selection. If you're still having issues please respond.
