### ISSUE TITLE
Error on BETA2 7.8 creating new module

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2938]
Hi, i'm testing new BETA2 and i get error when creating a new module in Studio.

It's simple to reproduce, go to Studio, in Spanish translation (as you see in screenshoot), create new module, and cannot Create.

not Working on any language.

* SuiteCRM Version used:  7.8 B2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

![error creating new module](https://cloud.githubusercontent.com/assets/20840700/22043266/285f394c-dd0f-11e6-8d61-2f00e6027c9b.PNG)

**Comment by shogunpol** [comment]
@GrupImatica , you cannot create new module in studio, did you mean: create new package, and module in this package, in Module builder?

**Comment by GrupImatica** [comment]
New Package, sorry :)

**Comment by mattlorimer** [comment]
Thanks for reporting this issue, this has been addressed in the Release Candidate

**Comment by GrupImatica** [comment]
Sorry, in 7.7.9, error appears also. We cannot create any module.

Please, can you share solution to implement in our installation ¿?
