### ISSUE TITLE
SuiteP theme layout out of place, certain buttons and links are unreachable

### ISSUE THREAD

**Issue by ruistrecht-alt** [salesagility/SuiteCRM#2947]
#### Issue

SuiteP theme layout out of place, certain buttons and links are unreachable. I followed SuiteCRM Wiki Installation Guide and changed permissions accordingly (cannot changed ownership though).
`
Uncaught TypeError: Cannot read property 'undefined' of undefined
    at tabsRefresh (style.js:536)
    at style.js:549
`
This is my folder structure, the subdomains folder is SuiteCRM document root and is accessible:
![untitled2](https://cloud.githubusercontent.com/assets/23050598/22103631/cd8ac984-de33-11e6-83fd-6291cdfbfc22.png)

**UPDATE**
There is also an issue with the company_logo quality, whether if I upload a logo with the specified res of 450*170 or a larger one with the same ratio, the logo quality drops and gets pixalated:
(Note: changed the company logo to a smaller one, so it would'nt break the layout)
![untitled](https://cloud.githubusercontent.com/assets/23050598/22198962/bf70a2f4-e150-11e6-81de-e557d9e11c9f.png)

Another issue, within the same topic, is the UI overlaying. This happens when a tab is clicked and then you hover another tab:
![untitled2](https://cloud.githubusercontent.com/assets/23050598/22199116/740ff1a6-e151-11e6-8475-799d820164c9.png)

And like I referred in the title many elements are slightly out of place, like:
![untitled2](https://cloud.githubusercontent.com/assets/23050598/22199231/f118f88c-e151-11e6-92bd-4f6d5a68b764.png)

![untitled3](https://cloud.githubusercontent.com/assets/23050598/22199287/211b3d10-e152-11e6-8f8d-4b798b48b47b.png)

#### Expected Behavior

UI should be coherent across browsers and allow access to displayed elements

#### Actual Behavior

Tried to view in Opera and Chrome:
![untitled](https://cloud.githubusercontent.com/assets/23050598/22102947/2d3b3e16-de31-11e6-9eb0-860659bb07bd.png)

#### Steps to Reproduce

1. Open [http://suitecrm.aliartalentos.com](url) to view it live.

#### Your Environment

* SuiteCRM Version used: 7.7.9
* Browser name and version: Chrome 55.0.2883.87 m (64-bit), Opera 42.0.2393.137,
* Environment name and version: PHP 7.0.14, MariaDB 10.1.19, CPanel 62.0.2 (shared hosting)
* Operating System and version: Windows 10

**Comment by samus-aran** [comment]
@rxstriker We don't support Opera, so can you please provide issues you are having on Chrome which is a supported browser.

**Comment by rxstriker** [comment]
Updated issue with extra screenshots, and more UI related issues on the same topic.

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please reopen if this is still an issue you can replicate and provide steps for. Thanks.
