### ISSUE TITLE
Outbound email config: smtp pass truncated

### ISSUE THREAD

**Issue by joaoinacio** [salesagility/SuiteCRM#2948]
#### Issue
When configuring an outbound smtp , the password field is limited to 64 chars.
This makes it impossible to use with external services with use a longer 'key' (such as sendgrid's 69-char API key).

The password is limited to 100 characters at the DB level, in base64 form. This should allow for aprox. 73 characters to be used.

#### Expected Behavior
Longer passwords should be allowed, or a message warning/error should be displayed.

#### Actual Behavior
The password field is truncated before being posted, and smtp fails to authenticate.

#### Possible Fix
Increase the field's max-length to 70, or even further with an increase on DB field length.

#### Steps to Reproduce
1. use a free sendgrid account, create an API key for smtp.
2. fill in the details in EmailMan (Outbound email configuration)
3. try to send a test email.

####  Environment
* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):

**Comment by Dillon-Brown** [comment]
Appears to be resolved in latest hotfix and LTS with smtp pass limit being set to 100 chars.
