### ISSUE TITLE
converting lead - with move option - activities are not linked to the account

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#2950]
#### Issue
If the “move” option in (admin panel => systems => convert lead) is selected, after the lead is converted to a Contact & Account, the  activities are linked to the Contact but not to the Account.

with "copy" option the activities are linked to  Contact & Account
Tested with Suitecrm test data.
#### Expected Behavior
lead conversion: copy activities with the "move" option links activities to both Contact and Account like the "copy" option

#### Actual Behavior
after the lead conversion activities are not linked to the account (only to the contact)

#### Steps to Reproduce
Created a Call Activity "TestMove" for the Lead « test », assigned to test
Converted Lead to Contact (selecting contact, not Account)
RESULT => Contact Subpanel Activities : TestMove is here
RESULT => Account Subpanel Activities : No Data

#### Your Environment

    SuiteCRM Version used: 7.7.8
    Browser name and version: Firefox 50.1.0 (64-bit)
    Environment name and version: MySQL, PHP 7.0
    Operating System and version: Ubuntu 16.04 (64-bit)

**Comment by blloyd78** [comment]
I can confirm that I have replicated this issue in v7.7.9 too

**Comment by ijdavie** [comment]
Hi, 

If I understand this right, this is expected and not a bug. most of this is down to the activity only being able to be related to either a contact or an account and not both and due to the action being move, it will not create a activity to relate to the other record. 

on the convert to lead page you have the option to select which record the activity should be related to. 

Adding a new relationship would be a option and to modify the convert lead functionality however this is best raised in the forums if this is the option you wish to take. 

Thanks, 
Ian.

**Comment by jobvector** [comment]
Hi @ijdavie,

In my opinion, from a functional view point the expected behavior of copy and move should be the same, at this point its just not consistent. 
If the copy option can relate a call/email to both modules than the move option should also be able to do that.

Thanks,
jobvector

**Comment by ijdavie** [comment]
@jobvector, I can raise this as a suggestion if you wish?

however with the way the relationships work for the activities this currently is not possible, The copy option does relate a call/email to both modules and actually creates a call for each option selected in the convert a lead screen and then relates each one to a different record(e.g contact, lead etc). 

Ian.

**Comment by jobvector** [comment]
@ijdavie 
in my opinion if creating a call and relating it to a contact and account is functionally possible, than the same functionality should also be given for existing calls (that are "moved" from a lead to an contact/account);
but yes, please make this a suggestion

**Comment by samus-aran** [comment]
I believe this is superseded by this suggestion.
https://github.com/salesagility/SuiteCRM/issues/2332

Feel free to re-open if you do not feel that suggestion is accurate.
