### ISSUE TITLE
Problems with UI on different languages

### ISSUE THREAD

**Issue by SoapJson** [salesagility/SuiteCRM#2962]
<img width="1280" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/25264089/22175693/d00095d8-e002-11e6-8f7c-5afd8b390068.png">
<img width="1280" alt="2017-01-21 17 09 13" src="https://cloud.githubusercontent.com/assets/25264089/22175694/d1b6c96a-e002-11e6-84dc-3d1a7067cef5.png">

needs css improvement because in different languages menu has different sizes and it make many visual troubles

1. Log in Go to any module page
2. if you have Russian translation all will look a little bit strange

Found after installing new version

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (Chrome 55.0.2883.95 (64-bit)):
* device MacBook Pro (Retina, 13-inch, Early 2015)
* macOS Sierra 10.12.2 (16C67)

**Comment by horus68** [comment]
Confirmed. It only woks fine at 1500 px screens
@likhobory have you found some workaround, maybe a short word for "administration" menu?

1100 px wide:
![russian_1093](https://cloud.githubusercontent.com/assets/3055443/22176933/886c188c-e00c-11e6-9e93-1b8cc9fe40cf.png)

1221 px wide:
![russian_1221](https://cloud.githubusercontent.com/assets/3055443/22176937/b013aa8a-e00c-11e6-877a-663e740d2593.png)

1500 px wide:
![russian_1501](https://cloud.githubusercontent.com/assets/3055443/22176939/b9ae93ca-e00c-11e6-8440-0e2e11f68957.png)



My Setup: SuiteCRM 7.7.9, Windows, Firefox 50.1
MySQL 5.6.17 / PHP 5.5.12 / Apache 2.4.19 (Wamp server install)
Latest language pack from Crowdin https://crowdin.com/project/suitecrmtranslations

**Comment by SoapJson** [comment]
I understand that it's possible to find some ways to solve it as a simple user but it would be better to find javascript solution of auto detecting free size:
automatically hide menu buttons which are redundant in menu area
or automatically collapse to burger menu if row doesn't fit free space

**Comment by likhobory** [comment]
> maybe a short word for "administration" menu?
@horus68 Russian language is not so laconic,..
and I agree with @SoapJson , it should be a universal solution for all languages and resolutions.

**Comment by horus68** [comment]
Also agree... it affects any language.
The real problem is created by a template that includes the menus and the buttons on the same line when there are many menus

**Comment by SoapJson** [comment]
@likhobory , @horus68 
Here is the solution, which I made for one of our partners 
<img width="229" alt="2017-01-22 16 44 02" src="https://cloud.githubusercontent.com/assets/25264089/22183256/599c165e-e0c2-11e6-8140-50d8c40f2e66.png">

--------------------------------------------------------

<img width="230" alt="2017-01-22 16 43 50" src="https://cloud.githubusercontent.com/assets/25264089/22183257/5b882174-e0c2-11e6-89eb-4385c368c31d.png">

Suit R theme upgrade  (makes work more comfortable as main screen height increases and more info can be displayed  simultaneously)

some icons, some bootstrap tabs and a little bit of time

**Comment by horus68** [comment]
@SoapJson nice work.. Maybe some day create a github project for your revised template.
Take a look into the road taken by @urdhvatech
https://suitecrm.com/forum/suite-themes/10830-suite-p-theme-too-much-whitespace-need-more-compact-theme?start=30#40617
and
Fine tunning the SuiteCRM's new theme (SuiteP) - http://urdhva-tech.com/blogs/fine-tunning-the-suitecrm-new-theme

**Comment by horus68** [comment]
@SopaJson can you please edit the issue subject to be related with all languages? 
This should be considered a relevant issue to be solved.
Also looking for the opinions by usera @Mausino and @pgorod  (consider to place a Like in the first message)
Also requesting SalesAgility attention from @daniel-samson @gymad as this will require special coding and devs decisions.

**Comment by daniel-samson** [comment]
See my pull request #2936 for details. 

The issue is that the name of the current module is too wide. So my solution is to hide the filter menu's to the right. It uses the same behaviour, when you turn the filters off.

The problem with this fix is that we are making a trade off between showing the current module menu and show the filters.

My fix should be in the next release. Can I ask community members to test the next release?

**Comment by pgorod** [comment]
This seems related to issue #1852, currently the second most voted issue here on Github...

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
