### ISSUE TITLE
Report Count Functionality is Broken (Again) in v7.7.9 

### ISSUE THREAD

**Issue by aarondglover** [salesagility/SuiteCRM#2963]
#### Issue
Please see issue [Issue #2005](https://github.com/salesagility/SuiteCRM/issues/2005)

This problem has reappeared after upgrading from 7.7.4 to 7.7.9

#### Expected Behavior
Report should display count

#### Actual Behavior
Record IDs are displayed instead

Please review the previous closed issue... all relevent details are in there.

**Comment by aarondglover** [comment]
@sgaved I have just tested your proposed fix. Unfortunately it does not work as expected. You have indeed got the a value to show but it seems the grouping functionality has broken. The image below demonstrates that values which should be grouped are not being grouped. Because the Grouping of the Account Names is not working, the "COUNT/Number of Cases" column always displays "1".


Here is the setup:

![image](https://cloud.githubusercontent.com/assets/8821892/22275826/711f9592-e303-11e6-9364-609cf873c32d.png)


Here is the outcome.
![image](https://cloud.githubusercontent.com/assets/8821892/22275773/1080ad52-e303-11e6-8ea6-a33a35c5ae7d.png)


Changing the Group Field (which I think is wrong) also has no affect:

![image](https://cloud.githubusercontent.com/assets/8821892/22275861/a7d10ecc-e303-11e6-9cda-d4224b84ccaa.png)

**Comment by aarondglover** [comment]
I've been doing some more tinkering with these reports.

Here is what WORKS:

![image](https://cloud.githubusercontent.com/assets/8821892/22277925/9fd99ba2-e313-11e6-99e0-fd83f3865a81.png)



Here is what DOES NOT WORK.

If I Keep "LINK" ticked the report is broken in the following ways:

- The GROUPING fails to Group.

If I Group on the "Number of Cases" Field instead of the "Account Name" field the report is broken in the following ways:

- The Account "ID" is displayed instead of the "Count"

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.

**Comment by Miri13** [comment]
Hi there
i have 
Version 7.11.18
and this bug still being reproduce
Best
M
