### ISSUE TITLE
Calendar doesn't work in 7.8 BETA 2

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#2968]
#### Issue

With the new beta version the calendar doesn't show anymore due to an SQL error. The log file shows the following error:

`Mon Jan 23 11:47:18 2017 [26222][1][FATAL]  Query Failed: SELECT fp_events.* from fp_events  WHERE ((fp_events.date_start >= '2017-01-18 08:00:00' AND fp_events.date_start < '2017-01-30 08:00:00') OR (fp_events.date_start < '2017-01-18 08:00:00' AND fp_events.date_end > '2017-01-18 08:00:00') AND .accept_status != 'decline') AND  fp_events.assigned_user_id='1' AND fp_events.deleted=0 : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '!= 'decline') AND  fp_events.assigned_user_id='1' AND fp_events.deleted=0' at line 1
Mon Jan 23 11:47:18 2017 [26222][1][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.`

#### Steps to Reproduce

Open Calendar

#### Your Environment

* SuiteCRM Version used: 7.8.0-beta.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by mattlorimer** [comment]
Thanks for reporting this issue, it has been addressed in the release candidate
