### ISSUE TITLE
Missing "reply to" button in emails in history panel

### ISSUE THREAD

**Issue by leenyx** [salesagility/SuiteCRM#297]
We are archiving some emails automatically via the outlook plugin and archiving manually some other emails via the email form in SugarCRM. The problem I see is that some emails have a "reply to" when they are displayed the history panel while some other emails they don't provide this button.

I can't figure out the reason for this, the emails that don't have the reply to button are only the ones archived. I don't understand the difference between archived and imported, and if this is the case why can you edit something archived.

Is this the expected behaviour?

As reported here:

https://suitecrm.com/forum/suitecrm-outlook-plugin/4591-missing-reply-to-button-in-history-panel

![image](https://cloud.githubusercontent.com/assets/827487/8574570/a433122c-2597-11e5-8d44-7c252be282cc.png)

![image](https://cloud.githubusercontent.com/assets/827487/8574580/aef0afb2-2597-11e5-9a56-1c09fe72e52a.png)

**Comment by samus-aran** [comment]
Although you may feel like this is an issue, it really is a question for the forums (which you've already created).  Please keep questions for the forums and actual issues/bugs here in GitHub, Thanks
