### ISSUE TITLE
Camel Case in a sentence?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2972]
#### Issue

Any reason for this CAPS change?

7.8 rc
`    'UPDATE_DOLLARAMOUNTS_TXT' => 'UPDATE the U.S. Dollar amounts FOR sales based ON the CURRENT SET currency rates. This VALUE IS used TO calculate Graphs AND LIST VIEW Currency Amounts.',`

7.8 beta (and older versions)
`    'UPDATE_DOLLARAMOUNTS_TXT' => 'Update the U.S. Dollar amounts for sales based on the current set currency rates. This value is used to calculate Graphs and List View Currency Amounts.',`

Note - Actual wording is shared in 2 files:
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/SugarObjects/templates/sale/language/en_us.lang.php#L77
and 
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Opportunities/language/en_us.lang.php#L81

Just kidding as a non english user: Sometimes I wonder how coders get to differentiate where to put Caps in the same sentene, as in "currency rates" from "Currency Amounts". 

#### Expected Behavior

Revert the All caps. What I really wanted is the US Dollar to be changed in all language file by "Default currency"

#### Context

The translation update on Crowdin is case sensitive, so this breaks previously translated sentences and also considers 2 identical sentences to be different and then requiring to translate both!

#### Your Environment

* SuiteCRM Version used: 7.8 RC

**Comment by Dillon-Brown** [comment]
Fixed in #3349. These string have been removed.
