### ISSUE TITLE
ISSUE CRETAING NEW PACKAGE IN MODULE BUILDER 7.8 RC (BASED ON https://github.com/salesagility/SuiteCRM/issues/2938)

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2978]
Same error after updating to 7.8 RC

Based on issue: https://github.com/salesagility/SuiteCRM/issues/2938

**Comment by mattlorimer** [comment]
It is JS error so you may need to clear you cache etc to see if it's still an issue

**Comment by GrupImatica** [comment]
Yes, working after clean. Thanks!
