### ISSUE TITLE
AOR Reports causes MySQL error because of not escaping cstm table aliases

### ISSUE THREAD

**Issue by 7ochem** [salesagility/SuiteCRM#299]
We've set up a Report crossing account, contacts and their custom field tables (`*_cstm`) back and forth. The module doesn't escape the table aliases of the custom tables in front of the fields, like `contacts:accounts_cstm.field_c` should have been `` `contacts:accounts_cstm`.field_c`` in the following query that was displayed in our logs:

> Tue Jul 7 15:33:51 2015 [29287][af9a479d-55ea-d308-1232-512528326685][FATAL] Query Failed:
> SELECT count(*) c FROM (SELECT \`contacts\`.id AS 'contacts_id', \`contacts\`.date_entered AS 'Date_Created0', \`contacts\`.date_modified AS 'Date_Modified1', \`contacts\`.created_by AS 'Created_By2', \`contacts\`.assigned_user_id AS 'Assigned_to3', \`contacts\`.salutation AS 'Salutation4', \`contacts\`.first_name AS 'First_Name5', \`contacts\`.last_name AS 'Last_Name6', \`contacts\`.title AS 'Title7', \`contacts\`.department AS 'Department8', \`contacts\`.phone_mobile AS 'Mobile9', \`accounts\`.id AS 'accounts_id', \`accounts\`.id AS 'Account_Name10', contacts_cstm.twitter_user_c AS 'Twitter_User11', contacts_cstm.administratie_contact_c AS 'Administratie_Contact12', contacts_cstm.lid_van_c AS 'Organisatie_rol13', \`contacts:email_addresses\`.id AS 'contacts:email_addresses_id', \`contacts:email_addresses\`.email_address AS 'Email_Address14', \`contacts:accounts\`.id AS 'contacts:accounts_id', contacts:accounts_cstm.type_klant__c AS 'Type_klant_-_Accountmanagement_Ja/Nee15', contacts:accounts_cstm.circle_sales_eigenaar_c AS 'Circle_eigenaar_klant16', \`contacts:fp_events_contacts\`.id AS 'contacts:fp_events_contacts_id', \`contacts:fp_events_contacts\`.name AS 'Name17', \`contacts:accounts\`.account_type AS 'Type_relatie18' FROM \`contacts\` LEFT JOIN accounts_contacts \`|accounts\` ON \`\`.id=\`|accounts\`.contact_id AND \`|accounts\`.deleted=0
> 
> LEFT JOIN accounts \`accounts\` ON \`accounts\`.id=\`|accounts\`.account_id AND \`accounts\`.deleted=0
LEFT JOIN \`contacts_cstm\` \`contacts_cstm\` ON contacts.id = \`contacts_cstm\`.id_c LEFT JOIN email_addr_bean_rel \`contacts|contacts:email_addresses\` ON \`contacts\`.id=\`contacts|contacts:email_addresses\`.bean_id AND \`contacts|contacts:email_addresses\`.deleted=0
 AND \`contacts|contacts:email_addresses\`.bean_module = 'Contacts'
LEFT JOIN email_addresses \`contacts:email_addresses\` ON \`contacts:email_addresses\`.id=\`contacts|contacts:email_addresses\`.email_address_id AND \`contacts:email_addresses\`.deleted=0
LEFT JOIN accounts_contacts \`contacts|contacts:accounts\` ON \`contacts\`.id=\`contacts|contacts:accounts\`.contact_id AND \`contacts|contacts:accounts\`.deleted=0
>
> LEFT JOIN accounts \`contacts:accounts\` ON \`contacts:accounts\`.id=\`contacts|contacts:accounts\`.account_id AND \`contacts:accounts\`.deleted=0
LEFT JOIN \`accounts_cstm\` \`contacts:accounts_cstm\` ON accounts.id = \`contacts:accounts_cstm\`.id_c LEFT JOIN fp_events_contacts_c \`contacts|contacts:fp_events_contacts\` ON \`contacts\`.id=\`contacts|contacts:fp_events_contacts\`.fp_events_contactscontacts_idb AND \`contacts|contacts:fp_events_contacts\`.deleted=0
>
> LEFT JOIN fp_events \`contacts:fp_events_contacts\` ON \`contacts:fp_events_contacts\`.id=\`contacts|contacts:fp_events_contacts\`.fp_events_contactsfp_events_ida AND \`contacts:fp_events_contacts\`.deleted=0
 WHERE (\`contacts:accounts\`.account_type = '' OR \`contacts:accounts\`.account_type = 'prospects' OR \`contacts:accounts\`.account_type = 'samenwerkingspartners' OR \`contacts:accounts\`.account_type = 'vasteklanten') AND contacts.deleted = 0 ) as n
> : MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':accounts_cstm.type_klant__c AS 'Type_klant_-_Accountmanagement_Ja/Nee15', conta' at line 1

**Comment by JimMackin** [comment]
This is fixed in the hotfix-7.2.3 branch which should be in the next release.
