### ISSUE TITLE
Cannot Duplicate Project Template

### ISSUE THREAD

**Issue by Glen206** [salesagility/SuiteCRM#2992]
After creating a Project Template and its Project Task Templates, If you try to duplicate the Project Template you get a blank screen with only the side menu and header menu still present once you click  The "Duplicate" Button 

#### Expected Behavior
A new Project Template with its associated tasks should appear.

You can duplicate this on the Suite CRM Demo Site by trying to duplicate the existing Sample Project Template I created in it or create your own Project template and try to duplicate

#### Context
Tried to duplicate a project template with multiple tasks associated with it so as to not have to rebuild it. This is a low priority because we do not duplicate Project Templates that Often

SuiteCRM7.7.9
Chrome 
MySQL
PHP

**Comment by ChangezKhan** [comment]
Hello @Glen206, what does mean "If you try to duplicate the Project Template you get a blank screen"? Can you elaborate it more? Kindly share screenshot also if possible.

**Comment by samus-aran** [comment]
Great to see if this has been resolved using the above fix.  If not please re-open this issue when it is closed.
