### ISSUE TITLE
[QUESTION] Using 7.8RC Developer in Production env.

### ISSUE THREAD

**Issue by easaw** [salesagility/SuiteCRM#2993]
### How much of a bad idea is it to use the 7.8 Developer RC in a production environment (for a small business, which will have daily backups)?

Let's say 1=Okay, 10=Very Bad Idea...

 - Is it better to stick with 7.7.9 and wait for 7.8 then upgrade to 8.0 when it arrives?

**Comment by horus68** [comment]
As in any software in pre-release status... "This is NOT for Production use". Its only intended for developers of 3rd party software or testers to find errors and find solutions!
https://suitecrm.com/download/download-pre-release

So stick with 7.7.9 and wait for 7.8

**Comment by daniel-samson** [comment]
10! 

I agree with @horus68. When 7.8 is officially released you can use the upgrade packages to safely upgrade to the latest version.

**Comment by gunnicom** [comment]
Up to you. So something between 1 and 10 on your decision.
Some use only stable software, some run debian unstable on production system, and it never failed. 
Choose yourself.
