### ISSUE TITLE
Activate DNSSEC and DANE TLSA for suitecrm.com / suiteondemand.com

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#2996]
The domains suitecrm.com and suiteondemand.com don't have their DNSSEC and DANE TLSA records.

#### Issue

These domains are relatively easy for a malicious attacker to attack and intercept, such as at an internet cafe, by means of a man in the middle attack on an unsuspecting user.

#### Expected Behavior

The records for DNSSEC and DANE TLSA should be added and auto updated periodically via a script on the servers.

#### Actual Behavior

No DNSSEC, no DANE TLSA, records missing.

#### Possible Fix

Add DNSSEC and TLSA records.

#### Steps to Reproduce

1. Install two add-ons for Firefox, "Extended DNSSEC Validator", and "DNSSEC/TLSA Validator".
2. Visit both sites suitecrm.com and suiteondemand.com
3. Observe on right hand side of address bar, the grayed out key with red danger icon, and grayed out padlock with red danger icon.
4. When you activate DNSSEC and TLSA, the add-ons will validate the domains cryptographically, and these two key and padlock icons will be green.

#### Context

DNSSEC and TLSA are a requirement for many governmental departments, banks, financial, insurance, health.  Anything serious where hackers who steal personal information could be extremely costly to the public, to public safety, and to various institutions the public depends on.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox latest version 52.0b1
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by samus-aran** [comment]
Technically not a suggestion for SuiteCRM but I'll forward this to the appropriate departments.
