### ISSUE TITLE
Studio Edit View scrolled layout cant drag and drop items

### ISSUE THREAD

**Issue by weighsone** [salesagility/SuiteCRM#300]
When I'm in Studio -> Contacts -> Layout -> Edit view there is a long list on the left and then the box on the right to put items into.  I made the box on the right a bit smaller than default by removing some unnecessary rows and then when i wanted to add a block from the left I normally drag and drop it.  But when I scroll down to it and try to drag it to the right hand box the page doesn't scroll back up and i cant scroll whilst clicking and dragging. I have gotten around it for now by editing the css of the page in the Chrome inspect element thing by making #panels have a "position:absolute;" and "margin-left:200px;" which then makes it stay in the same place on the page (its a bit ugly just with those two css lines in there...its a start to a fix, but not complete by any means)

**Comment by darthtang** [comment]
I have added your suggestion to the core of suite for now so that at least the functionality is available to the user.
