### ISSUE TITLE
Warnings reported when cron.php is executed

### ISSUE THREAD

**Issue by lukekenny** [salesagility/SuiteCRM#3000]
When cron.php is executed by cron, the following warnings are produced:

`PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in /var/www/mycrmsite.com/public_html/include/SugarEmailAddress/SugarEmailAddress.php on line 1162`

This can be seen by executing the command the installer asks to be added to cron:

`php -f cron.php`

* SuiteCRM Version used: 7.7.9
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.20, PHP 7.0.14
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by pgorod** [comment]
See #942, you'll find a workaround there.
