### ISSUE TITLE
Cannot import email when using Theme P

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#3010]
#### Issue

When trying to import an email using the webmail interface, the whole screen "greys out", making it impossible to assign said email to a contact/lead/opportunity etc.

#### Expected Behavior

The import dialog should sit above any screen effects applied.

#### Actual Behavior

It would appear that a screen effect used to give the import dialog box focus is actually applied over the top, making it impossible to select any of the drop downs or to click the Import button itself

#### Possible Fix

The z-index value for .mask in the Suite P CSS file (line 70) needs to be changed from 10 to **3**:

`.mask{z-index:3 !important}`

As a workaround, you can revert to the Suite 7 theme

#### Steps to Reproduce

1. Ensure Theme P is applied to your user account
2. Attempt to import an email
3. Import Email dialog box cannot be accessed

I have been unable to verify this issue on the live demo system because (a) it is still running v7.7.9 and (b) there is no email account configured.

#### Context

The ability to import email is crucial - I would suggest this is a high priority bug

#### Your Environment

* SuiteCRM Version used: 7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 10.0.3 and Chrome 55.0.29xx
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
@blloyd78 Are you able to take a screenshot of what you are seeing?

**Comment by blloyd78** [comment]
Please see the attached screenshot with sensitive data obscured. You will see that the mask appears on top of the Import Email dialog box

<img width="1975" alt="screen shot 2017-01-31 at 14 59 10" src="https://cloud.githubusercontent.com/assets/17355746/22470184/5c1175ae-e7c6-11e6-9ac6-bd3cb492ddbd.png">

The CSS fix mentioned above reorders the mask to sit behind the dialog box as it does prior to the 7.8 upgrade.
