### ISSUE TITLE
SuiteR: Advanced filter displaying issue with non-english langpacks (7.8.0)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3012]
Subj. 
Tested with Russian & Portuguese langpacks.

![filt](https://cloud.githubusercontent.com/assets/5983672/22460995/8e25fc30-e7b8-11e6-8de0-f1a417922102.png)

**Comment by horus68** [comment]
Confirmed!
This can be directly related to the label "Any Phone", as translations uses more letters then english language.
What we need is the ability to break lines when a label is too big
