### ISSUE TITLE
7.8 Upgrade returns Javascript:void(0) for new filter functionality

### ISSUE THREAD

**Issue by edilex** [salesagility/SuiteCRM#3015]
#### Issue

When I access cases,  users, all the filters button are not clickable, on both Firefox and Chrome (up to date), address bar shows Javascript:Void(0). Have done Repair JS + QUick Repair following upgrade. I use both French and English interface.

#### Expected Behavior

It works

#### Actual Behavior

Not clickable.

#### Possible Fix

No clue.

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

Can't search for any tickets anymore.

#### Your Environment

* SuiteCRM Version used: 7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):
![capture d ecran 2017-01-31 a 11 17 56](https://cloud.githubusercontent.com/assets/23078474/22473528/368c14ac-e7a7-11e6-9c0b-a851995b46ad.png)

**Comment by samus-aran** [comment]
@edilex Have you tried : Rebuild Minified JS Files and then Rebuild JS Grouping Files.  After this you will need to refresh your browser cache.
Let us know how you get on.

**Comment by valentinhubert** [comment]
I have the same issue here : 

`<a href="javascript:void(0)" class="glyphicon glyphicon-filter parent-dropdown-handler" onclick="listViewSearchIcon.toggleSearchDialog('latest'); $('#searchDialog .nav-tabs .active').removeClass('active'); $('#searchDialog .nav-tabs li').first().addClass('active'); $('#searchDialog').modal('toggle');"></a>`

Console says : 

> sugar_grp1.js:550:106TypeError: null is not an object (evaluating 'adv.setAttribute')

Neither Rebuild Minified JS Files neither rebuild JS Grouping Files change a thing.

SuiteCRM Version used: 7.8.0
Browser name and version : SAFARI 10.0.3 or 51.0.1 (64 bits)
Environment name and version : PHP  7.1.1 / 10.1.19-MariaDB
Operating System and version (e.g Ubuntu 16.04): do no know

**Comment by edilex** [comment]
Everything with "Rebuild", "Reconstruct", or "JS" was used. Something with translation packages ? Quick repairs and permissions were used as well.
Using MariaDB, Centos, too. 

As well, I have noticed that my log tries to access ./suitecrm/acl_ac something, whereas I have no suitecrm folder in my installation (as if the home root for Suite CRM was hardcoded rather than variable).

**Comment by valentinhubert** [comment]
I've suspected translation packages too. I've disabled everyone of them. It didn't work.
I also tried to re-adjust permissions, didn't work too (i've set 777 to everything on a test environment).

When i've upload to 7.8.0-RC on another test environment, i didn't have the issue.

**Comment by markjn** [comment]
"upgrading" 7.8-7.8 fixed it for me

**Comment by valentinhubert** [comment]
I tried to upgrade also. The issue still exist.

**Comment by samus-aran** [comment]
Thanks for your input guys we are looking into replicating this on our end and shed some light :)

**Comment by valentinhubert** [comment]
It's an upgrade from 7.7.9.

**Comment by edilex** [comment]
Same, updgrade from 7.7.9

**Comment by valentinhubert** [comment]
When i click on "filter" i have this in the console : 

<img width="1277" alt="capture d ecran 2017-02-02 a 14 35 11" src="https://cloud.githubusercontent.com/assets/25481968/22551376/e09ec6fc-e954-11e6-9a96-469063249b5b.png">

**Comment by edilex** [comment]
could it be the version of java or php on our server ?

**Comment by edilex** [comment]
or an unfinished install ? (like it blocks somewhere)

**Comment by valentinhubert** [comment]
Don't think so. I have tried two versions so far.

**Comment by valentinhubert** [comment]
The upgrade wizard didn't say anything particular.

**Comment by valentinhubert** [comment]
By the way i'm unable to hide a column (i haven't see that yet). But no errors.

**Comment by valentinhubert** [comment]
If i use the previous filter system by adding : 

$sugar_config['enable_legacy_search'][] = 'Accounts';
$sugar_config['enable_legacy_search'][] = 'Users';
$sugar_config['enable_legacy_search'][] = 'Employees';

in config_override.php, it works. I can filter.
