### ISSUE TITLE
Doesn't show Order by column field in filter update in 7.8

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3022]
#### Issue

If you created filter and you want update it, you couldn't choose the field Order by column... because there is som css/js issue

![filter_update](https://cloud.githubusercontent.com/assets/5773777/22510485/6854dc76-e892-11e6-84ec-ccbf92f6830a.png)

#### Steps to Reproduce

1. Create by Save function in Advance search the new filter
2. Choose the filter
3. Click on filter icon 
4. Try to update actual filter

#### Your Environment

* SuiteCRM Version used: 7.8 Official SuiteCRM site
* Browser name and version: Chrome 56.0.2924.76 (64-bit)
* Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
@Mausino , an issue has been tested on SuiteCRM(7.8), and not appear, can you repair rebuild, also rebuild Js and so on, also clear cash and try if this help?

**Comment by Mausino** [comment]
@shogunpol I tested it on chrome inkognito + firefox and issue doesn't appear.. Thanks
