### ISSUE TITLE
Image missing from SuiteP theme image directory

### ISSUE THREAD

**Issue by MrSykes** [salesagility/SuiteCRM#3028]
#### Issue
The 'img_loading.gif' image is missing from the '../suitecrm/htdocs/theme/SuiteP/images' directory. This image is referenced in the 'Loading page, please wait.." dialog box. The online demo version (Version 7.8.0 Sugar Version 6.5.24 (Build 509)) is missing the image as well. Please note that the 'img_loading.gif' can be found in the other theme directories (default, Suite7, SuiteR).

#### Steps to Reproduce
1. Open a Project and click on 'View Gantt' from the 'Actions' tab. 
2. Add or edit a new task.
3. Note that the 'Loading page, please wait..' box is missing the 'img_loading.gif' image.

#### Your Environment
Server:
Version 7.8.0 Sugar Version 6.5.24 (Build 509)
Ubuntu Server 14.04 LTS
MySQL 14.14 , PHP 5.6.29

Client:
Chrome Version 55.0.2883.87 m
Windows 7 Pro 64

**Comment by horus68** [comment]
Confirmed. File its called from several files:
https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=%27img_loading.gif%27&type=Code

**Comment by chris001** [comment]
@horus68 
@MrSykes 
Isn't Suite supposed to load any missing images, from the `themes/default/images` folder?
