### ISSUE TITLE
Gantt chart dates do not match or consistently reflect local timezone offset

### ISSUE THREAD

**Issue by MrSykes** [salesagility/SuiteCRM#3029]
#### Issue
The Gantt chart view does not consistently reflect the users local timezone offset. Can reproduce issue using the online demo (Version 7.8.0 Sugar Version 6.5.24 (Build 509)).

#### Expected Behavior
Input and displayed dates should reflect the users timezone and the text and graphical sections should match each other.

#### Actual Behavior
The dates displayed in the text and graphical sections do not match if timezone offset is negative.

#### Possible Fix
Assume that user entered dates/times are entered using the users local time and not GMT. Convert the input to GMT when storing in the DB and to convert back to the users timezone when displayed. 

#### Steps to Reproduce
1. Edit your user profile and set the timezone to a negative offset (GMT-1 for example).
2. Open/Add a Project and click on 'View Gantt' from the 'Actions' tab.
3. Add a new task and set the task start date to February 1, 2017.
4. The left hand (text) side of the Gantt chart will incorrectly display the start date as January 31, 2017.
5. The right hand (graphical) side of the chart will show the correct starting date (February 1, 2017).
(Note: setting the timezone to GMT or a positive offset will make the text and graphical section match.)

#### Your Environment
Server:
Version 7.8.0 Sugar Version 6.5.24 (Build 509)
Ubuntu Server 14.04 LTS
MySQL 14.14 , PHP 5.6.29

Client:
Chrome Version 55.0.2883.87 m
Windows 7 Pro 64

**Comment by matt-o-matic** [comment]
Not really sure why this is "low priority" it makes using the project module very cumbersome.  No response on it for over a year too?  How much will it cost to get the issue fixed??

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
