### ISSUE TITLE
yui.css missing

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3038]
#### Issue

File include/javascript/yui3/index.html states:
`<link rel="stylesheet" type="text/css" href="assets/yui.css" >`
https://github.com/salesagility/SuiteCRM/blob/master/include/javascript/yui3/index.html#L7

Same goes on file modules/UpgradeWizard/uw_main.tpl that defines:
`<link rel='stylesheet' type='text/css' href="{sugar_getjspath file='themes/default/css/yui.css'}"/>`
https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/uw_main.tpl#L78

But file yui.css is not found!!
See folder: https://github.com/salesagility/SuiteCRM/tree/master/themes/default/css

#### Steps to Reproduce

1. Activate log on Warn level
2. `02/02/17 20:22:02 [10232][1][WARN] CSS File yui.css not found`

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.8

**Comment by gunnicom** [comment]
For me the file yui.css is in multiple locations. Don't know if it is there from an old version and stayed there all over the upgrades up to 7.8.21:

/var/www/suite/include/javascript/yui3/assets/yui.css
/var/www/suite/themes/Suite7/css/yui.css
/var/www/suite/themes/SuiteR/css/yui.css

**Comment by greenlanegreb** [comment]
Now it's gone again lol Sun Aug 25 21:52:10 2019 [19292][1][WARN] CSS File Dawn/yui.css not found

**Comment by horus68** [comment]
@Dillon-Brown ?
