### ISSUE TITLE
Error when save the reports: Missing argument 4 for AOR_Report::ACLAccess

### ISSUE THREAD

**Issue by zden2k** [salesagility/SuiteCRM#3047]
#### Issue

When users access to: All > Reports, and try to do some changes, they get error message "bad gataway 502"

#### Expected Behavior
Users expecting right access to Reports pages, where they have some data.

#### Actual Behavior
in nginx error messages I see this:
PHP message: PHP Warning:  Missing argument 4 for AOR_Report::ACLAccess(), called in /var/www/SuiteCRM-7.7.7/XTemplate/xtpl.php on line 363 and defined in /var/www/SuiteCRM-7.7.9/modules/AOR_Reports/AOR_Report.php on line 120

#### Steps to Reproduce
1. go to All > Reports
2. modify data, a save...
3. got "bad gataway 502" form nginx

#### Your Environment
* SuiteCRM Version used: 7.7.9
* Browser name: all browsers
* Environment name and version (e.g. MySQL, PHP 7): mysql Ver 14.14 Distrib 5.5.53
* Operating System and version (e.g Ubuntu 16.04): debian stable

**Comment by pgorod** [comment]
Related to #942, I suppose. This adds some information on _how_ the issue breaks the app for the user.

**Comment by ijdavie** [comment]
This is the same issue as #2760, there is also a fix been proposed for this issue there.
