### ISSUE TITLE
Some bug in Suite R in version 7.8.0

### ISSUE THREAD

**Issue by rainolf** [salesagility/SuiteCRM#3049]
Hello,
seems that in 7.8.0 some buttons are overlapped with something else ...

Please see the screenshots...
![edit](https://cloud.githubusercontent.com/assets/2652556/22611929/ad0b1b96-ea6d-11e6-9f06-11a325099186.png)
![select](https://cloud.githubusercontent.com/assets/2652556/22611930/ad0dc918-ea6d-11e6-95d2-ac7072f9edad.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please reopen if this is still an issue you can replicate and provide steps for. Thanks.
