### ISSUE TITLE
Remove item from a dropdown in module builder doesn't work

### ISSUE THREAD

**Issue by berpao** [salesagility/SuiteCRM#305]
Suitecrm version: 7.2.2 MAX
Os: Windows 2008 R2 Standard 64bit
Mysql: Mysql 5.6
Webserver: Apache/2.4.12 (Win32)
Php: 5.6.8 VC11 TS (Win32)

--------------------------------------------------------
I've created a custom module, and in this module i've created a dropdown field and linked it to a new dropdown list. Before deploying the module, i've tried to remove some items from my list; even if no error occurs, the removed items are still present after saving.
i've debugged the code and the problem seems to be related to this line (line 200):
    $values = sugarLangArrayMerge($values, $app_list_strings);
in the file:
    "modules/ModuleBuilder/MB/MBLanguage.php"
Anyway i'm not a php expert, so please check it.
Thanks in advance.
Paolo

**Comment by berpao** [comment]
Hi to all, sorry but which is the patch i need  to apply? the 3057506 or the 0fb6aa2.
thanks in advance
Paolo

**Comment by willrennie** [comment]
Paolo, can you confirm if you are still receiving this issue in 7.4/7.5, or if the issue is now resolved?

**Comment by berpao** [comment]
Hi Will, thank you and sorry for the late response.
I haven't tried 7.4/7.5 because it's a customer server and before make this type of upgrade the customer think about it twice... i'm not able to understand if there is a specific patch for it, if yes could you give me some advice to install it? i'll try it as soon as possible and give you a feedback about it. tank you again
Paolo

**Comment by ijdavie** [comment]
This Pull request was not linked to this issue, Link has been added and Pull Request has been pulled in previously.
