### ISSUE TITLE
AOW: dropdown lists is not updating (calclulate field & modified record action)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3050]
Parameter / Relation parameter dropdown lists in calclulate field action is not updating when user select another WorkFlow Module.

#### Steps to Reproduce
1. Create new workflow 
2. Select WorkFlow Module (Accounts for example)
3. Add  action & select calc. fields
4. Account fields are  displaying in the dropdowns
5. Select another WorkFlow Module (Bugs for example)
6. Account fields are  still displaying in the dropdowns

**Comment by samus-aran** [comment]
I believe this also applies to Modified Record also and not specific to Calculated Fields.

**Comment by jack7anderson7** [comment]
This is still an issue as yes it doesn't update straight away but an easy workaround for this would be to select another action (for example change "Calculate Fields" to "--None--") momentarily, then select "Calculate Fields" again and it should update as expected.
