### ISSUE TITLE
Calendar view - New colour settings for Completed Meetings, Calls and Tasks

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3053]
#### Issue

My team + me are wondered why the completed M/T/C aren't showing by different colour in calendar.

If user want show completed M/T/C in calendar, it will also great to have some possibility to change their colours

Here my suggestion draft:

![completed](https://cloud.githubusercontent.com/assets/5773777/22646222/84a32144-ec6b-11e6-8e83-205fa719b1aa.png)

#### Expected Behavior

Open and Completed (finished) T / M / C will look different

**Comment by samus-aran** [comment]
I would say that this suggestion is superseded by this suggestion (why an enhancement I can not remember I'll change it back).
