### ISSUE TITLE
ACL problem on filter in 7.8

### ISSUE THREAD

**Issue by sasha2002** [salesagility/SuiteCRM#3054]
#### Issue

After upgrade the Leads disappear from main Leads page (index.php?module=Leads&action=index).
If in ACL set List Lead as All, all is ok ican see all Leads, not just mine.
If i try to set owned instead of All, Leads does not shows but on search i can found it.

#### Expected Behavior

On Leads page i need to see my own leads

#### Actual Behavior

I can't see my own leads

#### Steps to Reproduce

1. Upgrade from 7.7.8 to 7.8.0
2. Open from Menu Sales->Leads
3. Leads not show

#### Context

High

#### Your Environment

* SuiteCRM Version used: Version 7.8.0 , Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any browser.
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.34-79.1 Percona Server, PHP 5.5.9-1ubuntu4.20
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by BillLudwig** [comment]
We are seeing the same thing but not restricted to just leads.  Our users are unable to see their Accounts, Opportunities, or Leads when the ACL settings are restricted to "Owner".  It might affect other modules but those are the only ones that we are using this way. Increasing their access to Group or All works as expected.

I did some debugging but I'm not very familiar with the codebase.  I couldn't find any recent changes that seemed like likely suspects but back on Sep 3, 2016 the SugarBean.php file was modified and that seems like the most likely cause.  We didn't change to Owner permissions until yesterday so I can't verify when the functionality changed.

**Possible Fix?**
in SugarBean.php->ACLAccess()
set $is_owner to true for listview before calling ACLController::checkAccess

so it looks like ...
```
switch ($view) {
            case 'list':
            case 'index':
            case 'listview':
                $is_owner = true;
                $view = "list";
                break;
```

**Comment by sasha2002** [comment]
Confirmed, works. But if set another value, like group or something else, again need to fix this in file.
Found where is deleted.
[ACL is deleted here](https://github.com/salesagility/SuiteCRM/commit/1f7689240ad19718fe93a1afa4172039cd636198#diff-5bb494d1dca998198a61c907931633ba)
Old file (Line 5298) :
```
     public function ACLAccess($view, $is_owner = 'not_set', $in_group = 'not_set')
     {
```
**Possible Fix?**
Add it back :)
I will try to add it, but need some time.

P.S.
Thanks @BillLudwig for hint where to search.

**Comment by sasha2002** [comment]
Ok, seems to work ok.
I commented our temporary fix and add this :
`            case 'listview':
//              $is_owner = true;
//                $view = "list";
//                break;
                return ACLController::checkAccess($this->module_dir, 'list', true, $this->acltype, $in_group);`
Can someone test?
