### ISSUE TITLE
French language JS error with calendar

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#3056]
#### Issue
Just installed the French Canadian language pack and the calendar (dashlet & module view) throw the following JS error:

![image](https://cloud.githubusercontent.com/assets/20977561/22659270/01fa5474-ec6b-11e6-93ef-af61fffb0b77.png)

Obvisouly, the error will occur with any language pack that contains a single quote in the LBL_REPEAT_UNTIL label.

#### Possible Fix
Changed to double quotes for now. Don't know what the proper builtin suitecrm escaping function is.

addToValidate('CalendarRepeatForm', 'repeat_until', 'date', true,"{/literal}{$MOD.LBL_REPEAT_UNTIL}{literal}");

#### Your Environment
SuiteCRM v7.7.9 & v7.8.1
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
MySQL version 5.5.53
Chrome 55 on Windows 10 (same behavior with other browsers)

**Comment by horus68** [comment]
I posted to be linked to the issue development.

**Comment by horus68** [comment]
I think this is a duplicated and is now solved. @staganyi can you please close this issue?
See https://github.com/salesagility/SuiteCRM/issues/1720

**Comment by staganyi** [comment]
The related issue #1720 refers to the email module, not calendar. I'm unable to test in the latest version to see if it's fixed. If you can test, than please do so to confirm it's fixed and I will close.

**Comment by horus68** [comment]
@staganyi you are right, I mixed the calendar and the module!
single quote still needs to be escaped in SuiteCRM 7.9.0 RC

`'LBL_REPEAT_UNTIL' => 'Répéter jusqu&#39;à'
`

@samus-aran this is one for you?

**Comment by chris001** [comment]
Where the strings are loaded and stored to the javascript files, the fix would go here:
https://github.com/salesagility/SuiteCRM/blob/master/include/SugarObjects/LanguageManager.php
How language packs are supposed to work in javascript:
http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Module_Framework/Language/

**Comment by horus68** [comment]
@Dillon-Brown any news on this?

**Comment by Dillon-Brown** [comment]
Hi @horus68, It's currently being looked at, you can expect a PR soon.
