### ISSUE TITLE
FullCalendar update to version 3.1

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3057]
#### Issue

FullCalendar packed with SuiteCRM is outdated ( path  \modules\Calendar\fullcalendar )

SuiteCRM 7.8.1 installed version:  v3.0.1 (2016-09-26) from the headers
even if changelog file is from v2.3.2 (2015-06-14)

Latest version from the developer: v3.1.0 (2016-12-05)

#### Expected Behavior

Any 3rd party code needs to be updated to the source

#### Actual Behavior

old version

#### Possible Fix

Update the code from 
https://fullcalendar.io/download/
https://github.com/fullcalendar/fullcalendar

#### Context

See Bugfixes from the dev changelog.txt

#### Your Environment

* SuiteCRM Version used: 7.8.1

**Comment by daniel-samson** [comment]
The changes in 3.1.0 are:
- experimental support for implicitly batched ("debounced") event rendering (#2938)
	- `eventRenderWait` (off by default)
- new `footer` option, similar to header toolbar (#654, #3299)
- event rendering batch methods (#3351):
	- `renderEvents`
	- `updateEvents`
- more granular touch settings (#3377):
	- `eventLongPressDelay`
	- `selectLongPressDelay`
- eventDestroy not called when removing the popover (#3416, #3419)
- print stylesheet and gcal extension now offered as minified (#3415)
- fc-today in agenda header cells (#3361, #3365)
- height-related options in tandem with other options (#3327, #3384)
- Kazakh locale (#3394)
- Afrikaans locale (#3390)
- internal refactor related to timing of rendering and firing handlers.
  calls to rerender the current date-range and events from within handlers
  might not execute immediately. instead, will execute after handler finishes.

These features will not make much difference to the calendar in SuiteCRM.

**Comment by horus68** [comment]
at least the files included in SuiteCRM should be refreshed (the changelog is from v2.3.2) the languages also need some update.
As a rule of thumb, when a software include external code in core there should be a close attention on updates.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FullCalendar update to version 3.1](https://trello.com/c/ppbfljmd/32-fullcalendar-update-to-version-3-1)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran as soon will relase 3.11 come here in Fullcalendar are great news

Latest version 3.9 
- it looks that the version 3.9 will last main version compatibile with our instace. Also bring many security + other fixes + enhacemnets from version 3.0.1 which we now have

@ApatheticCosmos this is also qestion on you if upgrade will now break all your work which you did for sync with google calendars

What you think... Is it time to think about update of Fullcalendar ?

Latest 4.0 alpa will https://fullcalendar.io/blog/2018/04/alpha-release-jquery-removal 
-more lightweight and allow for better integration with React/Vue/Angular. We have completed the detangling process!
- removing jQuery as a dependency is a **non-backwards-compatible** change of course, warranting a major version bump to v4.0.0.

**Comment by ApatheticCosmos** [comment]
@Mausino Unless the upgrade changes the way meetings are stored in the database, this would have no effect on Google Sync.

**Comment by Mausino** [comment]
@Dillon-Brown thank you for upgrade 

@samus-aran should it get label with 7.11 Milestone?
