### ISSUE TITLE
Viewed message count not updated in SuiteCRM

### ISSUE THREAD

**Issue by psatasiya** [salesagility/SuiteCRM#3059]
Hello,

I am using SuiteCRM 7.8.1.

I have created campaign and ran successfully but it is not updating viewed message count.I have tried with many options like, unblock web images in browser and also changed email client and computer also but no success.

I have also asked the same question at community also https://suitecrm.com/forum/suitecrm-7-0-discussion/12835-viewed-message-count-is-not-getting-updated-in-campaign-status

Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (Firefox and  Chrome(64-bit)):
* Environment name and version (MySQL, PHP 5.6.29):
* Operating System and version (linux):

Thanks,
Prafull

**Comment by shogunpol** [comment]
@psatasiya , an issue has been tested in version SuiteCRM you used(7.8.1), and everything fully work, remember to make sure is all correctly setting up, so best way is to send test to your email, and see if you receive it. Also check if is that email is sent in email queue.

**Comment by psatasiya** [comment]
@shogunpol Thanks for your reply.
I have successfully configured it and now it is working fine.
Actually problem is in my site_url.

Thanks again.
