### ISSUE TITLE
Intermittent cron setup will increase time between jobs

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#306]
Not sure if this is a bug or not but if the user has set cron up with something like `*/3 * * * *` and a job is set up to run every two minutes then, due to how SuiteCRM checks the times, this will only run every 6 minutes.

You could possibly work around this by using the `Execute if missed` option but this could be problematic if the job takes a while to run.

Not sure if it's possible to detect if a job has been missed versus whether the cron hasn't run at the specified time.

**Comment by shogunpol** [comment]
@JimMackin , The issue has been tested in recent version of SuiteCRM(7.7.8), and not appear, can you confirm it, if yes can you close an issue please.

**Comment by JimMackin** [comment]
Still occurs for me on a fresh install of 7.7.8. Created a scheduler to run every two minutes and set cron to run every three minutes (admittedly not an ideal setup). The job still runs every six minutes. See here:
![screenshot-localhost 2016-11-21 09-56-59](https://cloud.githubusercontent.com/assets/1968785/20478249/287bd626-afd1-11e6-9273-957eefa9d9fe.png)

**Comment by JimMackin** [comment]
@shogunpol As you mentioned my initial example doesn't make much sense since it's not possible for two jobs to run more often that every six minutes. I'll add a better example.

**Comment by JimMackin** [comment]
@shogunpol See here for a clearer example. I have cron running every 4 minutes and the job runs every 7 minutes. The issue here is that the job will only run when the minute is a multiple of both 7 and 4.

This means that the job will only run at 28 and 56 minutes past the hour. See the example below.

![screenshot-localhost 2016-11-21 10-57-15](https://cloud.githubusercontent.com/assets/1968785/20480178/5b86da9a-afd9-11e6-9da9-bd1fc6af3227.png)

**Comment by Mausino** [comment]
@JimMackin @Dillon-Brown @samus-aran 

I looked on latest version of 7.10.11 and i don't see that not working and i think was fixed.
All my schedulers when are set up for example in interval hour.. in the log are records with hour interval if 5 min there are every 5 min. 

I think this issue is expired and unrelevant.  Should be closed.
