### ISSUE TITLE
2nd page base64 error in Reports

### ISSUE THREAD

**Issue by mbates14** [salesagility/SuiteCRM#3061]
#### Issue
![crm error](https://cloud.githubusercontent.com/assets/22461464/22698844/b83739e2-ed23-11e6-8477-162f0955e774.png)

#### Expected Behavior

Should show the next page of items. 

#### Actual Behavior

Look above

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.4.16, MySQL something another. 
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by shogunpol** [comment]
To solve your issue we advise suppress warnings and notices in your php.ini file.
@mbates14  - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index).
