### ISSUE TITLE
Export Customizations feature of Studio does not work

### ISSUE THREAD

**Issue by sanchezfauste** [salesagility/SuiteCRM#3064]
Export Customizations feature of Studio does not export the custom fields properly, so when you import the package on another SuiteCRM installation the custom fields are not created.

#### Issue
The manifest file generated by MBPackage.php does not include the 'custom_fields' array.

This works as expected on 7.7.9 version. The issue appears on 7.8.0 and 7.8.1 versions.

#### Expected Behavior
The generated manifest must include the 'custom_fields' array definition.

#### Actual Behavior
The 'custom_fields' array is missing on the manifest file, so when you import the package the custom fields are not created and are not displayed on the studio.

#### Possible Fix
I have tryed to replace the 'modules/ModuleBuilder/MB/MBPackage.php' file with the 'MBPackage.php' of the 7.7.9 version and all works as expected. Is for this reason that I think that the problem is due the introduced changes on this file on version 7.8.0.

#### Steps to Reproduce
To reproduce the bug we need 2 installations of SuiteCRM v7.8.1.

##### Installation 1 of SuiteCRM v7.8.1
1. Enter to the Studio of a SuiteCRM.
2. Go to the Accounts module.
3. Create a custom field:
  - Data Type: TextField
  - Field Name: test_field
  - Display Label: Test Field
4. Save the custom fiel.
5. Go to the main screen of Studio.
6. Select the 'Export Customizations' option.
7. Provide a Package Name: 'export_test'.
8. Select the Accounts module.
9. Click on 'Export' and save the file.

##### Installation 2 of SuiteCRM v7.8.1
1. Go to the Administration page.
2. Go to 'Module Loader'.
3. Upload the zip generated on the installation 1.
4. Install the module clicking on 'Install'.
5. Check 'Accept' and click 'Commit'.
6. Go to the Studio.
7. Select Accounts module.
8. Click 'Fields' to display the fields of Accounts module.
9. Observe that the custom field 'test_field' is missing.

#### Context
I'm trying to export the customizations of SuiteCRM Account module to another intallation.

#### Your Environment
* SuiteCRM Version used: 7.8.0 and 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 56.0.2924.87 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.54, PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by amariussi** [comment]
The solution is on issue 3081 https://github.com/salesagility/SuiteCRM/issues/3081

**Comment by sanchezfauste** [comment]
#3086 solves the problem.
