### ISSUE TITLE
Quick Filter table width issue (Suite 7 theme)

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#3065]
#### Issue

When i prepare my quick filter schema in studio, some fields are out of pop up. 
#### Expected Behavior

They should be in pop up like others.
#### Steps to Reproduce

1. Open Studio
2. Add field to Quick Filter for any modules.
3. Open quick filter
4. See the result.

![screenshot_1](https://cloud.githubusercontent.com/assets/22373035/22735589/6dcd6ff0-ee0b-11e6-92cf-6e34499cdea9.png)

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27. PHP  7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Linux 16.04
* Theme : Suite 7

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please reopen if this is still an issue you can replicate and provide steps for. Thanks.
