### ISSUE TITLE
"Save" and "Save and continue" buttons are the same actions?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3069]
#### Issue

What is the difference on the module edit view between "Save" and "Save and continue" buttons?
Do they perform just the same actions?

#### Expected Behavior

If they are the same the "save and continue" is not necessary.
I would prefer to have a "Save and Close" and a "Save and Next"

#### Actual Behavior

Save: Apply the changes (stays on the same screen)
Save and continue : Apply the changes  (stays on the same screen but refresh the editview)

#### Context

The same question when editing: What button should I choose?!
(and some bugs when one works and the other don't!)

**Comment by mattlorimer** [comment]
'save and continue' will take you onto the next record, based on the records you have filtered on list view, 
'save' is the standard save option, save that record and return to where it is configured to go next e.g detail view

**Comment by horus68** [comment]
So there are some modules not working like that... will detail later!
