### ISSUE TITLE
ListView Relate Field Links not working

### ISSUE THREAD

**Issue by dgreeninger** [salesagility/SuiteCRM#307]
go to the Accounts module list view, switch to advanced search, use Layout Options to add 'Created By' to the 'Display Columns'

When you select the username that created the record, you'll be directed to a link that does not work.
It seems to be generating the link with the User module, but with the ID of the Account.

This applies across all modules for custom relate fields and default relate fields I add to the listview with 'Layout Options'.

**Comment by darthtang** [comment]
I am currently looking at the problem. 

What currently is happening now is that basically any custom fields that are added  (i.e created by or modified by etc) do not have any ID's of their own when viewed through the hyper-link widget. 
Which makes one to believe that when a custom field is added, it does not pull the correct related data into that custom field object. 

to see for yourself i suggest you this solution:

- Go to AccountListSmarty.php
- then -> process()
- then if you put this code inside that method : (doesnt matter where.... just put it somewhere)
echo vardump($data)
die();
-then reproduce the bug and you will then see that the ID for the custom field is not even shown

P.S This is currently under investigation and should have a fix soon
