### ISSUE TITLE
Google Maps do not work - possibly due to Google API Change

### ISSUE THREAD

**Issue by easaw** [salesagility/SuiteCRM#3070]
Fresh install on shared hosting, PHP 5.6 - maps broken 😢 

Hard to recommend OSS to clients when simple functions are broken. 

Anyone having the same issue?

_(I notice the maps is 3rd party?)_

**Comment by horus68** [comment]
Maps is from JJWDesign http://www.jjwdesign.com/google-maps-for-sugarcrm/
Latest version is Version 2.1.20 Changes 05/25/2015

Google Map is working on the demo. 
Google Map API requires you to register for your own code (this only apply to sites not using the API before some date in the past).
Code: 
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/modules/jjwg_Maps/jjwg_Maps.php#L58

See: https://developers.google.com/maps/documentation/javascript/get-api-key


Else you can use this:
http://suitecrmtweaks.blogspot.pt/2017/02/google-map-location-for-leads-contacts.html

**Comment by easaw** [comment]
I thought the API had to be put in using the Admin GUI, didn't think I would have to put in in manually! 😄

**Comment by daniel-samson** [comment]
I have a fix #2536 waiting to go into a future release.

**Comment by horus68** [comment]
@easaw esaw Before June 2016 an API key was not required!

**Comment by gody01** [comment]
For clustering images try this pull request:
https://github.com/salesagility/SuiteCRM/pull/3089

For missing reply after Add to Target List try this pull request:
https://github.com/salesagility/SuiteCRM/pull/3091

I tried on 7.7.9 and 7.8.0/1.
You should of course geocode Your data (on admin page are instructons what to put into the cron job for this to happen)

**Comment by shogunpol** [comment]
Response - Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by horus68** [comment]
@shogunpol this is not a forum topic for me. This is an error with Gogole Maps that no longer allows keyless access to API for new installations. 
Note: It keep on working on sites installed before June 2016, not on newer.
There is a PR to solve this (by creating a new setting to input the site key)... but not merged yet!
https://github.com/salesagility/SuiteCRM/pull/2536
This I think would be relevant to address!

**Comment by shogunpol** [comment]
@horus68 , you right, just your title confused me :) , next time i will advise do not use [question] in title please :)

**Comment by horus68** [comment]
this was not my question :)  but maybe you can edit the title!

**Comment by easaw** [comment]
@shogunpol & @horus68 Title amended as requested 😃 

@gody01 I'll look into your fixes, thanks.

**Comment by horus68** [comment]
@samus-aran This should be tagged as BUG and Medium as it affects module work on any new install
PR needs to be merged too!

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.
