### ISSUE TITLE
Email module: List navigation buttons missing in 7.8.1

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3071]
#### Issue
In the Emails module, viewing the list of incoming email there used to be VCR buttons to navigate the emails list. The buttons have gone missing.

#### Expected Behaviour
The navigation buttons should be there otherwise you can only see the firsts page of emails. In previous versions these buttons were partially hidden by the splitter bar but usable.

#### Actual Behaviour
No VCR navigation buttons. with Suite 7 and Suite P themes

#### Possible Fix
The whole page seems to have been reworked.

#### Steps to Reproduce
Open Email module viewing an account with more then 20 emails

#### Context

High priority because Email module is now unusable.

#### Your Environment

* SuiteCRM Version used: 7.8.1 (upgraded)
* Browser name and version : Firefox 51.0.1 (32 bit)
* Environment name and version: PHP 5.5.9
* Operating System and version: Ubuntu 14.04

**Comment by onneau** [comment]
Issue still excists. Please prioritize.

**Comment by horus68** [comment]
@onneau please confirm this for 7.9.0 version. Also confirm you had done a Quick repair after upgrade. If so edit the issue title to remove the version info from there

**Comment by Lehnerr** [comment]
Problem is still there in SuiteCRM 7.8.5 in Theme P and 7
Pls correct it.

**Comment by NirvashPrime** [comment]
Is this issue still present in SuiteCRM 7.10.9?

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
