### ISSUE TITLE
PHPMailer: missing include/phpmailer/extras/ntlm_sasl_client.php in 7.8.1 patch

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3085]
#### Issue

Sending a test mail to an IMAP Exchange Server account using NTLM AUTH fails with an exception in the log.

#### Expected Behavior
Should attempt NTLM Authentication with Exchange Server IMAP.

#### Actual Behavior

Log Message: SugarPHPMailer encountered an error: The outbound mail server selected for the mail account you are using is invalid.  Check the settings or select a different mail server for the mail account.

Additionally, 'Send Test Email' also forces port 465 when using TLS despite the fact that TLS on port 25 is configured in database. Sending regular emails from SuiteCRM works as configured.

#### Possible Fix

Copy include/phpmailer/extras/ntlm_sasl_client.php from PHPMailer distribution.
Also need to enable mcrypt module in PHP5.

#### Steps to Reproduce

1. Confurure personal outgoing email server to 3rd party hosted Exchange Server.
2. Server accepts GSSAPI and NTLM authentication over unencrypted connection
3. Attempt to send test email.
4.

#### Context

Workaround: It turns out that Exchange will offer AUTH LOGIN if the connection uses TLS so low priority for me.

#### Your Environment

* SuiteCRM Version used: 7.8.1 upgraded from 7.6.x
* Browser name and version:
* Environment name and version: PHP 5.5.9
* Operating System and version: Ubuntu 14.04

**Comment by chris001** [comment]
This should be fixed by having the application download the entire PHPmailer library with `composer` this way #2840 and check for it with `php -m | grep mcrypt` and if missing install it.  Enable it with `phpenmod mcrypt`.

**Comment by Dillon-Brown** [comment]
No longer relevant as PHPMailer has been moved to vendor.
