### ISSUE TITLE
Password reset sends new password only for admin account

### ISSUE THREAD

**Issue by datafence** [salesagility/SuiteCRM#3088]
If I try to send new password via "user detail" -> "Password reset" button, system sends "new account email" with new password for **admin** account.  

#### Issue

There is no other way to reset user password then do it manually in database

#### Expected Behavior

System should send new password for specific user account

#### Actual Behavior

Systems sends new password for admin account

#### Steps to Reproduce

1. Create new employee - user and use some your email address
2. In user detail view click on "Reset password button"
3. You receive new email in your admin mailbox with new temporary email
4.

#### Your Environment

* SuiteCRM Version used: 7.8.1.
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All browsers
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6.29,  Ver 15.1 Distrib 10.0.29-MariaDB 
* Operating System and version (e.g Ubuntu 16.04): Debian 8 Jessie

**Comment by kdjmonaghan** [comment]
Hi @datafence,

If you check the PR I opened regarding this issue, PR #3256, you'll see two changes to two files inside of that PR that fix this problem. If you require this functionality before it's pulled into a later version of Suite, you can adjust your files using the fix. :)
