### ISSUE TITLE
Can't add duration intervals in Calls Module

### ISSUE THREAD

**Issue by JFSolorzano** [salesagility/SuiteCRM#309]
I was trying to add duration intervals to the calls module, when you select the Duration of a Call you can only select in a interval of 15 min, what i was trying was to change it to let the user select in a interval of 5 min, but when i change the variable 
```php 
var $minutes_values = array('0'=>'00','15'=>'15','30'=>'30','45'=>'45'); 
``` 

nothing changes, even updating the cache...

**Comment by ghermans** [comment]
You can add more time intervals in the dropdown editor at the admin section

![schermafdruk van 2015-07-18 12 06 38](https://cloud.githubusercontent.com/assets/1594411/8761232/8b7443cc-2d45-11e5-972c-7e7597dc2226.png)

**Comment by willrennie** [comment]
ghermans has provided a suitable solution to this issue.

**Comment by JFSolorzano** [comment]
I already tried that, but fol the calls module it doesnt work

**Comment by ghermans** [comment]
I'm sorry to hear that, i just did this with a clean install and it works for calls to.
Did you try "Quick repair" after you changed the intervals and cleared cache?
