### ISSUE TITLE
Workflow & Reports date bug

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#3093]
#### Issue
I noticed this bug when using the reports module with date fields as parameters. No matter what date I put in, after hitting update, it would display the previous day. For example, you can see in the screenshot below the date 10/31/16 but I had in fact put 11/01/16.

![image](https://cloud.githubusercontent.com/assets/20977561/22843047/bc392bb6-efa5-11e6-821d-9c7bd6de7fb4.png)

I did some digging and found that in **modules/AOW_WorkFlow/aow_utils.php** on line 472

$fieldlist[$fieldname]['value'] = $timedate->to_display_date($value);

the function call $timedate->to_display_date($value) will convert the date from UTC to the time zone of the current user. Since my user is -5 and the value passed into this function is **2016-11-01 00:00:00**, the converted value is **2016-10-31 20:00:00**.

Since no timezone conversion should be done in this case, I simply changed the line above to:

$fieldlist[$fieldname]['value'] = $timedate->to_display_date($value, **false**);

#### Your Environment
SuiteCRM v7.7.9 (production) & v7.8.1 (web demo)
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
MySQL version 5.5.53
Chrome 55 on Windows 10 (same behavior with other browsers)

**Comment by shogunpol** [comment]
@staganyi , what timezone and time format you use?

**Comment by staganyi** [comment]
![image](https://cloud.githubusercontent.com/assets/20977561/22940808/28c1ca96-f2b1-11e6-83de-9e71646ba6ad.png)

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
