### ISSUE TITLE
in email template,only the first word in the case update description appear ( not all variables were  mapped when the case updateded)

### ISSUE THREAD

**Issue by alanoodh** [salesagility/SuiteCRM#3096]
#### Issue
in work flow > email template > User case update template .
it seems that some variables when inserted into an email template do  not actually populate when the email sent for case update description (in specific way )
#### Expected Behavior

The recipient email  should see the Case field data, pertaining to the Case the email was generated from, mapped to the email template's variables.
#### Actual Behavior
all the variable was appeared in the email except for the case update description . ( just the first word appear in the case update description ) 

Hi    ,
 
You've had an update to your case  TEST (# 37) on 2017-02-06:
  malazf said:
testing

*Should have other words after testing but only shows the first one

#### Context
its necessary to track our updated cases in the CRM.
#### Your Environment
* SuiteCRM Version used: SuiteCRM v7.7.8
* Browser name and version (Chrome):
* Environment name and version ( MySQL, PHP 5.5.9):
* Operating System and version ( Ubuntu 14.04):

**Comment by shogunpol** [comment]
This is the same as issue #2292, I will close this any more information can be added issue #2292
Thanks.
