### ISSUE TITLE
Upgrade TinyMCE text editor from 3.5.10 to current version 4.5.3

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#3097]
#### Issue

The TinyMCE editor included with SuiteCRM, version 3.5.10, is 3 years old.  The TinyMCE editor plugins in that version still use macromedia shockwave flash, this is outdated tech. Flash has been replaced by javascript in the latest version because flash fails to work on mobile devices such as ipad iphone etc.  The new version 4.5.3 is implemented in javascript HTML5, compatible with all smart mobile devices.

#### Expected Behavior

Audio/video media preview should work in the SuiteCRM TinyMCE editor on mobile devices.  The TinyMCE editor and its included plugins used by SuiteCRM should be upgraded to a version which doesn't depend on flash so it will work fully on any ipad iphone android tablet etc.
#### Actual Behavior

The Flash SWF objects, in TinyMCE 3.5.10 included in SuiteCRM, fail to load on ipad, due to the Flash browser plugin virtual machine is missing on iOS and Android devices.
#### Possible Fix

1. `composer require tinymce/tinymce` - Upgrade to TinyMCE current version 4.5.3
2. Update `SugarTinyMCE.php` to autoload the `tinymce.js` from `vendor/tinymce/tinymce/tinymce.js`.
3. Update the modules which are bypassing `SugarTinMCE.php` by directly including `'include/tiny_mce/tiny_mce.js'` - AOK, AOS, Module Builder, and User Signature Editor.  Update them to use `SugarTinyMCE.php` which needs load or autoload the tinymce javascript from the `vendor` folder.

#### Steps to Reproduce

1. Login to SuiteCRM on ipad or android tablet.
2. Edit an email campaign template.
3. Click button to add a video or audio file to the email.
4. Try to preview the video/audio file, flash fails to load - flash doesn't exist on mobile devices, so the media preview fails.

#### Context

Medium High priority, about 600 fixed bugs and security fixes between version 3.5.10 and current version 4.5.3
https://github.com/tinymce/tinymce/blob/master/changelog.txt

#### Your Environment

* SuiteCRM Version used: current 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): current Firefox 52.0b5
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade TinyMCE text editor from 3.5.10 to current version 4.5.3](https://trello.com/c/RaxiHIJY/31-upgrade-tinymce-text-editor-from-3-5-10-to-current-version-4-5-3)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Beatific-Angel** [comment]
i gonna upgrade tinymce editor 
what should i do?

**Comment by chris001** [comment]
> i gonna upgrade tinymce editor
> what should i do?

Currently using 4.3.4 (five years old release from Feb 2016):
https://github.com/salesagility/SuiteCRM/blob/207f5f65d260b842b8883e591783608ec758b28d/include/javascript/mozaik/vendor/tinymce/tinymce/changelog.txt

Current redistributable version is TinyMCE 5.5.1 :
https://github.com/tinymce/tinymce-dist

Coding Standards, TinyMCE should be moved into "vendor" and use `composer` to `include` the package, for effortless security and bugfix updates.
https://github.com/salesagility/SuiteCRM/blob/207f5f65d260b842b8883e591783608ec758b28d/include/javascript/mozaik/vendor/tinymce/tinymce/readme.md
