### ISSUE TITLE
Cron job takes 100% CPU load 

### ISSUE THREAD

**Issue by cmarrero** [salesagility/SuiteCRM#310]
Hi, 

AOD cosume a lot off CPU in the crotab job

More information:

https://www.suitecrm.co.uk/forum/bug-tracker/2372-perform-lucene-index-taking-long-to-run-and-using-alot-of-cpu?limitstart=0

https://suitecrm.com/forum/bug-tracker/2719-cron-job-takes-100-cpu-load

Regards

**Comment by cmarrero** [comment]
https://www.suitecrm.com/forum/developer-help/3005-aod-not-working

**Comment by JimMackin** [comment]
Possibly related to #911 or #897
