### ISSUE TITLE
Upgrade for HTML Purifier [Request]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3100]
#### Issue

HTML Purifier  \include\HTMLPurifier\HTMLPurifier.standalone.php
is the 4.6.0 version.

#### Expected Behavior

HTML Purifier 4.8.0 (Sept 2016) is a bugfix release, collecting a year of accumulated bug fixes.  In particular, we fixed some minor bugs and now declare full PHP 7 compatibility. 
See: http://htmlpurifier.org

#### Actual Behavior

HTML Purifier 4.6.0 version (Nov. 2013) shipped with SuiteCRM 7.8.1

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade for HTML Purifier [Request]](https://trello.com/c/VxSxOigS/30-upgrade-for-html-purifier-request)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran 

HTML Purifier 4.10.0 released ( February 22, 2018) Full support php 5 and php 7

HTML Purifier 4.10.0 is a maintenance release, collecting a year of accumulated bug fixes. The most critical fixes relate to supporting PHP 7.2 properly, and there are a few other minor fixes. One thing on the feature front: relative CSS length specifiers are now supported. Additionally, we have officially dropped support for PHP 5.3; while we have not purposely broken HTML Purifier for this version, we are no longer testing for it.

Should we also update it for relase 7.11 ?

**Comment by Mausino** [comment]
@Dillon-Brown thank you for upgrade

@samus-aran should it get label with 7.11 Milestone?
