### ISSUE TITLE
Icons on sidebar are missing in Process Audit listview

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3104]
#### Issue

Open workflow listview

![workflow1](https://cloud.githubusercontent.com/assets/5773777/22889883/e756eccc-f20a-11e6-8830-74daaf532b5b.png)

Go on sidebar and click on View Process Audit and icons from sidebar will disappear

![workflow2](https://cloud.githubusercontent.com/assets/5773777/22889917/06b60350-f20b-11e6-8331-ecc43ff94a52.png)

#### Your Environment

* SuiteCRM Version used: Official demo 7.8.1
* Browser name and version : Chrome 54.x
* Operating System and version: Win 10 Home

**Comment by horus68** [comment]
Confirmed

Icon OK:
`class="side-bar-View_Process_Audit side-bar-action-icon"`

Icon KO
`class="side-bar-AOW_Processed side-bar-action-icon"`
