### ISSUE TITLE
Campaign summary dropdown next items creates error

### ISSUE THREAD

**Issue by paullaz** [salesagility/SuiteCRM#3108]
#### Issue
When using the advance arrow in a campaign summary dropdown the following error appears:
ListViewSubPanel::initNewSmartyTemplate path must have an tpl extension

#### Expected Behavior
Should see next 10 records

#### Actual Behavior
ListViewSubPanel::initNewSmartyTemplate path must have an tpl extension

#### Steps to Reproduce
1. Campaign Summary
2. Click summary item expansion
3. Click next items arrow

#### Context
Arrow through items in list

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 51.0.1 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.17 PHP 5.6.30 Apache 2.2.15
* Operating System and version (e.g Ubuntu 16.04): Centos 6.8

**Comment by shogunpol** [comment]
@paullaz , i want to ask you about more information:
1 - can you provide screenshot 
2 - i do not really know what "advance arrow in campaign summary" mean.

**Comment by paullaz** [comment]
Snap 1 is original before action, Snap 2 is after clicking arrow, Snap 3 is after reload of window which shows correct anticipated result. I have indicated the "advance arrow".

![slv technology-1](https://cloud.githubusercontent.com/assets/6889633/22984617/cfbb8db0-f35a-11e6-861e-d913db811c30.png)
![slv technology-2](https://cloud.githubusercontent.com/assets/6889633/22984620/d54b083c-f35a-11e6-9986-561db082fd46.png)
![slv technology-3](https://cloud.githubusercontent.com/assets/6889633/22984625/dafb44f4-f35a-11e6-87c6-c3f8d33e54c1.png)

**Comment by stenfalp** [comment]
Same problem if you try to sort the column clicking on "Hits".

Regards

**Comment by gody01** [comment]
I can confirm behaviour on our installation.

**Comment by gody01** [comment]
$templatePath is:
"include/SubPanel/SubPanelDynamic.html"
And doesn't have .tpl extension.

**Comment by gody01** [comment]
Easy one-liner fix:

--- modules/Campaigns/SubPanelViewer.php.orig	2016-03-02 18:01:01.000000000 +0100
+++ modules/Campaigns/SubPanelViewer.php	2017-03-08 11:08:56.181647502 +0100
@@ -84,7 +84,7 @@
 
 $subpanel_object = new SubPanel($module, $record, $subpanel,null, $layout_def_key);
 
-$subpanel_object->setTemplateFile('include/SubPanel/SubPanelDynamic.html');
+$subpanel_object->setTemplateFile('include/SubPanel/tpls/SubPanelDynamic.tpl');
 
 if(!empty($_REQUEST['mkt_id']) && $_REQUEST['mkt_id'] != 'all') {// bug 32910
     $mkt_id = $_REQUEST['mkt_id'];

**Comment by stenfalp** [comment]
The fix works like a charm, thank you.

**Comment by virtualme123** [comment]
Running Version 7.8.2 and had the same problem - thought it was merged or have I missed something?

**Comment by samus-aran** [comment]
Hi @virtualme123 - It has been merged but the fix has not be pushed into the master branch i.e. 7.8.3 release.

**Comment by virtualme123** [comment]
Perfect thanks for the quick response. 

I do love SuiteCRM and its fore father SugarCRM but I am struggling these days to keep the case open for it within our company, little bugs like this can sadly be hard to explain away to management - shame these can't get spotted before going live...

**Comment by samus-aran** [comment]
Hi @virtualme123 - Sorry to hear that.  We are working hard to reduce the amount of regression issues and put into place processes to assist with release testing.

Your support  is much appreciated. :+1:
