### ISSUE TITLE
Unable to create email templates 7.8.1

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#3109]
I am no longer able to insert fields into new email templates.
Existing Templates are OK.
--->

#### Issue
If you create a new email template or edit an existing template that you created from new and want to insert a variable, you select the module and field and press Insert button.

Nothing happens.

#### Expected Behavior
I would expect the field to appear in the HTML / Plain text edit areas below.
I would expect there to be a white band in the HTML area to accept variables. This does not appear.

#### Actual Behavior
Nothing is inserted below.

#### Steps to Reproduce
1. Select Email Templates module
2. Create a new template.
3. In the Insert Variable line, select a module, select a field and press the Insert button.
4. Nothing happens in either HTML area or text area.
5. Now insert a title into the HTML area.
6. Press Insert and the field does get inserted into the HTML area and the text area but only in the title band in HTML.
7. Delete the title band and nothing is inserted.

#### Context
I cant create email templates without somehow duplicating an existing one.

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome, Firefox, IE
* Environment name and version (e.g. MySQL, PHP 7): MySQL N/A
* Operating System and version (e.g Ubuntu 16.04): Windows

**Comment by kdjmonaghan** [comment]
Hi,

When making an e-mail template, the way the insert functionality works is that you have to be already within an element on the template as it won't just append a new element when pressing insert.

You'll need to add an element to the template from the left before appending the variable you want from the insert. (so like the screenshot below, just pull across a section and begin editing the text there).

![picture](https://cloud.githubusercontent.com/assets/3587120/22929171/23160c28-f2b2-11e6-8eed-2ae4ff135aa7.png)

The point of insertion of the variable is where your mouse cursor is at the time you press insert (so if your cursor is in the middle of a word, it'd insert there, so just click into the part of the text you want the variable to be placed.)

In regards to the duplicating email problem I've not experienced this - can you go into this in further detail or show your step process of replicating the problem with screenshots? In my build (using version 7.8.1) I'm not experiencing a duplication problem.

Thanks. :)

**Comment by davidyounger** [comment]
This seems a change in functionality.
In previous versions, it would have a text area already inserted by default (I think).
Also, nothing inserts into the text area, only the HTML area. Is this how it used to be?
There does not appear to be an issue with dupliating.
Cheers
David

**Comment by shogunpol** [comment]
@davidyounger , before you insert any variable you need to have a white place on editor, so jou need:
- drag one of templates from LHS 
- drop into grey area
- select your variable
- select place where you want to paste it
- and click insert
- variable appear on template.

If instruction doesnt work, please provide screenshots, this may help us to replicate an issue.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity,
