### ISSUE TITLE
Inbound Email - Many fields cannot be clicked on.

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#311]
If a user goes into the 'Inbound Email' module. The user cannot fill in 'Name', Username, Mail server protocol, use SSL, Status .

Although I am not sure if some of these fields are supposed to have these characteristics, I am definitely sure something here is broken

**Comment by digitalmcgrath** [comment]
Is IMAP enabled on your server? I was having the same issue until I installed php5-imap and enabled it.

**Comment by darthtang** [comment]
Cheers! Didn't see the notice at the top!
