### ISSUE TITLE
Advanced workflow problem 7.8.1

### ISSUE THREAD

**Issue by SuiteLover** [salesagility/SuiteCRM#3112]
#### Issue
I got two main workflows doing most of work in my company:
There are to main security groups:
Leadhunters
Salesman

#### Expected Behavior
Whenever leadhunter creates an oppurtunity under account which is not connectem with salesman workflow change its owner using round robin mechanism to somebody in salesman security group, creates outgoing call connected with salesman and changes the owner of the account to the same salesman.

To avoid situation when there are two opportunites connected with same account but different salesman there is another workflow which works when account owner is in salseman security group.

Both of those creates outgoing calls for salesman.

#### Actual Behavior
Workflow are seen as working in process audit however they never ends, outgoing calls don't create.
It worked well under 7.7.9 after upragde to 7.8.1 suddenly stopped working

#### Your Environment

* SuiteCRM Version used: 7.8.1 
* Browser name and version Wersja 56.0.2924.87 (64-bit)

**Comment by Mausino** [comment]
@SuiteLover  in my case after upgrade on 7.8.1 i am getting in Audit Process the message Running. The task module work well as before. Now i getting this error if i want edit and save calls... i am not sure if is it connected with wird behaviour after upgrade.


Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Calls/Call.php on line 187

also if i want repair activities i got this error

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Administration/RepairActivities.php on line 51

**Comment by SuiteLover** [comment]
I am getting same error as you, however i managed worfklows to work Adding 0 in hour time of phone call - somehow alter upgrade parameter got lost or in 7.8.1 wasnt necessary. 

I am tryong to chceck whatsappa goging on witam error and będzie back asap i got sthg.

**Comment by kdjmonaghan** [comment]
@SuiteLover can you tell me more about how you've set up your workflows? From what you've described there isn't enough information for me to replicate your problem. Can you please tell me the exact configurations of both of your work flows so I can see this locally for debugging.

@Mausino this sounds like a different issue, please raise it as a separate issue.

**Comment by shogunpol** [comment]
@SuiteLover , can you provide all details of you workflows, and step by step replication process please.

**Comment by SuiteLover** [comment]
I managed to get everything going, if anyone else got this problems, explenations:

- if you want to create phonecall using workflow you have to set all the required paramteres - one of them is hours which in 7.7.9 I left empty in 7.8.1 i had to put 0 as value. When it was empty workflow was stuck and seen as working id process audit. 

In my case all mess done after was effect of how complicated was another parameters i had in another workflow.


Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Calls/Call.php on line 187

also if i want repair activities i got this error

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Administration/RepairActivities.php on line 51

I got rid of those simply by quick repair - DK really what was wrong but quick repair helped.
