### ISSUE TITLE
Log slow queries for MySQL

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#3119]
#### Issue
If you enable **Log slow queries** in settings, slow queries are not printing to the log when using MySQL. I looked at the code and there are no explicit calls to **include/database/DBManager.php::dump_slow_queries()** from **include/database/MysqliManager.php**.

#### Possible Fix
I looked at the **query()** function in **include/database/MysqliManager.php**, and added **$this->dump_slow_queries($sql);** to line 143 to get it to work.

#### Your Environment
SuiteCRM v7.7.9 (production) & v7.8.1 (web demo)
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
MySQL version 5.5.53
Chrome 56 on Windows 10 (same behavior with other browsers)

**Comment by shogunpol** [comment]
@staganyi , can you create PR with your solution?

**Comment by staganyi** [comment]
I'm not setup for PR's.

**Comment by pgorod** [comment]
For the simplest PR's touching only one file you can do it directly from Github - just click to "edit" the file and Github will fork, commit and do the PR for you:
https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by staganyi** [comment]
Thanks for the help pgorod.
