### ISSUE TITLE
List Filtering broken with 7.8.1

### ISSUE THREAD

**Issue by aproposnix** [salesagility/SuiteCRM#3120]
#### Issue
The old filtering for searching the list of items (cases for example) has been replaced by widgets that do not work at all.  Clicking on the filtering icon does nothing. 

#### Expected Behavior
I should be able to filter search results 

#### Actual Behavior
I cannot filter records in search

#### Possible Fix
N/A

#### Steps to Reproduce

1. Go to a list of records (cases for example)
2. Try to filter using the new buttons
3. Nothing happens
4

#### Context
Since upgrading to 7.8.1 

#### Your Environment

SuiteCRM Version used: 7.8.1
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Chrome
Firefox v50 64bit Linux
Environment name and version (e.g. MySQL, PHP 7): =
MySQL v5.5.49
PHP v5.6.24
nginx - 1.6.2
Operating System and version (e.g Ubuntu 16.04):
Debian Jessie

**Comment by samus-aran** [comment]
Duplicate issue:

https://github.com/salesagility/SuiteCRM/issues/3054
