### ISSUE TITLE
unable to save after invitee removed in call module

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#3121]
#### Issue
In firefox, unable to save a call if you edit the call and remove an invitee.
Also tested on the suitecrm demo, same Behavior. 
No problem in Chrome.
#### Expected Behavior
Change should be saved after editing a call and removing invitee.

#### Actual Behavior
No reaction when save button clicked 

#### Steps to Reproduce

1. Edit call 
2. Remove an Invitee 
3. click save button 

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Firefox Version 50.1.0 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by horus68** [comment]
@shogunpol Confirmed in the official demo, so this should be tagged as a bug
The content is saved but not able to remove an invitee.
Same behaviour on the "save and continue" button

**Comment by kdjmonaghan** [comment]
Hello,

Firefox has one deprecation in the console for the JavaScript of the save execution, though, replacing nodeValue with value does not resolve the issue you're experiencing.

In Chrome, everything seems to be working as expected, so I'm guessing this is a browser compatibility problem where someone has tested functionality for Chrome but not Firefox and there is something within the JavaScript that stops the execution of the save function from working.

When the open Call is saved, invitees value is appended to with "1," as the value for the input field. When you continue pressing the button in Mozilla FireFox, you can see the value is appended to the value attribute of #user_invitees as many times as you've clicked it, which makes me think part of the call for the redirect is broken and perhaps also the actual save write to the database.

In Chrome when you do this and save, however, it seems as though the assignee remains when you refresh or enter the page.

This is functionality I'm not yet familiar with in Suite, but I'll look into it. Perhaps there are more deprecation than what met the eye in the FireFox console.

**Comment by mabullo** [comment]
Hi, there,
I also have the same problem using both standard Firefox and Firefox developer

**Comment by Kevconry** [comment]
Can't replicate in 7.13.1, please re-raise or get in touch if you are still having this issue
