### ISSUE TITLE
upload file can not be replaced in Note module

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#3122]
#### Issue
In firefox, if you edit a Note and replace an upload file by an other one and try to download the new file in detailView, it download the old one. 
Tested on the suitecrm demo also
It works fine in Chrome.
#### Expected Behavior
Old file should be replaced by a new file and should be downloadable in DetailView.
#### Actual Behavior
In detailView the file has been replaced by the new one, but when you try to download it, 
it downloads the old file.

#### Steps to Reproduce
1. Create a Note with an Attachment and Save it.
2. Edit the Note, remove the Attachement and upload a new one and Save.
3. Download the Attachement.

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Firefox Version 50.1.0 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
