### ISSUE TITLE
Adding a Project Task from Project Module in Gantt Chart view hangs/fails

### ISSUE THREAD

**Issue by gunnerman1** [salesagility/SuiteCRM#3129]
#### Issue
The Project Gantt Chart view contains a button to add a new task to the project. When clicked it opens up a "Add New Task" modal. When the "add" button is clicked nothing appears to happen on the front end though web server cpu usage spikes significantly for a short period. 

When a user clicks "Cancel" in the Add New Task popup it displays a "Loading Please Wait" message with a broken icon image and closes the window.

#### Expected Behavior
When the "add" button is clicked the new task should be created and added to the project and the add task modal should close. The Gantt chart should be updated either via Ajax if enabled or by page refresh. 

#### Actual Behavior
Nothing happens when "Add" is clicked. No task is created or added to the project and the Add Task window remains open. 

#### Steps to Reproduce

1. Create a Project or navigate to an existing one. 
2.  In the Project view click the Actions dropdown and click View Gantt
3. Click the "+ Add New Task" button and input the required fields for the task.
4. Click "Add"

Error log snippet created:
`Tue Feb 14 11:17:01 2017 [2942][id][FATAL] error loading relationship quotes
Tue Feb 14 11:17:40 2017 [32263][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:17:40 2017 [32263][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:17:40 2017 [32263][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:17:40 2017 [32263][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:19:40 2017 [32266][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:45:05 2017 [3761][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:45:05 2017 [3761][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:45:05 2017 [3761][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:45:05 2017 [3761][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:52:05 2017 [3253][id][ERROR] Unable to find relationship projects_quotes
Tue Feb 14 11:52:05 2017 [3253][id][FATAL] quotes for projects_quotes failed to load

Tue Feb 14 11:52:05 2017 [3253][id][ERROR] Unable to find relationship projects_quotes
Tue Feb 14 11:52:05 2017 [3253][id][FATAL] quotes for projects_quotes failed to load

Tue Feb 14 11:52:10 2017 [3784][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:52:10 2017 [3784][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:52:10 2017 [3784][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 11:52:10 2017 [3784][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 12:07:05 2017 [4127][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 12:07:05 2017 [4127][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 12:07:05 2017 [4127][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 12:07:05 2017 [4127][id][ERROR] Unable to get proper side for link project_name_link
Tue Feb 14 12:07:32 2017 [4122][id][FATAL]  Query Failed: DESCRIBE versions: MySQL error 1146: Table 'crm.versions' doesn't exist
Tue Feb 14 12:07:32 2017 [4122][id][FATAL]  Query Failed: SHOW INDEX FROM versions: MySQL error 1146: Table 'crm.versions' doesn't exist
Tue Feb 14 12:07:32 2017 [4122][id][FATAL]  Query Failed: select * from versions: MySQL error 1146: Table 'crm.versions' doesn't exist`

#### Context

I would view this as a medium priority issue. Tasks can still be added via alternative means however this is a functionality issue that blatantly does not work for the end user.
#### Your Environment

* SuiteCRM Version used:  7.8.0 Sugar Version 6.5.24 (Build 509) any theme.
* Browser name and version: Chrome Version 56.0.2924.87
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0, MySQL  5.0.12
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1

**Comment by gunnerman1** [comment]
This bug seems to have resolved itself with the 7.8.1 update though img_loading.gif is still not found. This issue can be closed if no one objects.

**Comment by shogunpol** [comment]
@gunnerman1 , you are creator of this issue, so if you doesn't see an issue any more, you can close an issue yourself.

**Comment by gunnerman1** [comment]
Understood. I wanted to give anyone else possibly viewing this issue a chance to chime in since I had not yet extensively tested that the issue was resolved in many use cases.

**Comment by horus68** [comment]
@gunnerman1 
> though img_loading.gif is still not found.

See Fix path for img_loading.gif - https://github.com/salesagility/SuiteCRM/pull/3040

**Comment by samus-aran** [comment]
Closing as the PR for resolving the img_loading.gif has been merged.

**Comment by gunnerman1** [comment]
> Closing as the PR for resolving the img_loading.gif has been merged.
I'm not sure that will fix the issue here. Sorry I did not clarify when I reopened this issue. I reopened it as I got a message on the forums that trying to create a project task from the project module in Gantt Chart view still hangs/fails in 7.8.2. I went back and did observe the same behavior, so at this point, I am not sure what I did to get it to work intermittently after 7.8.2 upgrade :(

**Comment by gunnerman1** [comment]
In case anyone still has this issue there is a fix that [staganyi discovered](https://suitecrm.com/forum/feedback/10497-7-7-project-add-new-tasks-does-not-create-task#46849)

> Fixed the problem. In the admin, I had to reset my "Advanced OpenAdmin - Business hours".
