### ISSUE TITLE
Broken call module by workflow after upgrade on 7.8.1

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3132]
#### Issue

This issue i created as eparate issue from #3112 on advice from @kdjmonaghan 

After upgrade on 7.8.1 i am getting for Calls created by workflow in Audit Process the message Running in column process. The task module creaded by workflow work well as before. Now i'm getting this error if i want edit and save calls.

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Calls/Call.php on line 187

also if i want repair activities i got this error

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Administration/RepairActivities.php on line 51

the quick repail also didn't solve this problem but i found

--------

in #3112 that @suitelover described the issue + puts there solution:

I managed to get everything going, if anyone else got this problems, explenations:

if you want to create phonecall using workflow you have to set all the required paramteres - one of them is hours which in 7.7.9 I left empty in 7.8.1 i had to put 0 as value. When it was empty workflow was stuck and seen as working id process audit.
In my case all mess done after was effect of how complicated was another parameters i had in another workflow.

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Calls/Call.php on line 187

also if i want repair activities i got this error

Fatal error: Call to a member function asDb() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/Administration/RepairActivities.php on line 51

I got rid of those simply by quick repair - DK really what was wrong but quick repair helped.

--------

@suitelover described the solution and closed the ticket but i think, this is issue of workflow when you create the call records by it and it needs to be fix by code.

I want ask the community for your opinion :)

#### Your Environment

* SuiteCRM Version used: Suite 7.8.1
* Browser name and version: Chrome 54.x
* Environment name and version: 5.6 MySQL, 5.6 PHP
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
@Mausino Is this still an issue on 7.10.x/7.11.x or can it be closed?

**Comment by Mausino** [comment]
@Dillon-Brown thank you for your comment.. i'm closing the issue.. I can't replicate in 7.10+ versions
