### ISSUE TITLE
Broken user access/permissions to various modules after 7.8.1 upgrade

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#3134]
#### Issue
User permissions to various modules became sporadic after SuiteCRM 7.7.8 -> 7.8.1. upgrade. E.g. a user who pre-upgrade had access to their own leads, after the upgrade can no longer list and view their own leads.  Another user who had View(all) and List(All) access to Spots module can now only List, but cannot View the Spots reports.  

A good evidence is that the permissions shown in the user's access matrix do not match with the actuall permissions user has (e.g. Admin->User Management->(select a user)->User's Access Tab matrix. User according to the matrix has List(All) View(All) access to Spots when in relaity when they log-in they have no View access to the module, but only List access. Another user matrix shows for Leads: List(Owner) and View(Owner), but user cannot either list or view their leads. 

We have not changed user/role acccess before&during the upgrade. We also ran 'quick repair and rebuild' and also 'repair roles' but this did not fix the problem.     

#### Expected Behavior
Users to have the same access to various CRM Modules after the 7.7.8 -> 7.8.1 upgrade.

#### Actual Behavior
After the upgrade - Users actual acess access does not match the access they have been been previously assigned. 

#### Possible Fix
Not known. 

#### Steps to Reproduce
1. Admin->User Management->(select a user)->Note the User's Access Tab (i.e. user effective access matrix)
2. Login as the user and check each access which user is supposed to have according to his access matrix. In our example Leads View/List(Owner) for one user did not work. For another user View(All) to Spots no longer works.  

#### Context
This should be high/med priority as it affects data access which can potentially cause serious data breach for companies that work with personal/sensitive data. 

#### Your Environment

* SuiteCRM 7.7.8 upgraded to 7.8.1. 
* Theme: Suite 7
* Browsers tested: Safari 10.0.3 and Microsoft Edge 38.14393
* Environment: PHP 5.5.38, MySQL 5.6.35
* OS CentOS 7.3.1611

<img width="1204" alt="screen shot 2017-02-16 at 10 47 32" src="https://cloud.githubusercontent.com/assets/18371928/23020114/6607b964-f43d-11e6-93f8-c6e88fbbc769.png">

**Comment by shogunpol** [comment]
Related to #3054

**Comment by samus-aran** [comment]
@evgu I believe the fix proposed does resolve most of the issues you are having.  Although the Spots module is a unique scenario because the spots record doesn't contain an assigned_user value.  This would stop a user from accessing a spots report even if they were the Owner and they have the role Edit set to Owner.

Let us know in regards to the fix proposed that it helps with your list view issues and we'll consider opening a new issue regarding specifically to Spots.

**Comment by evgu** [comment]
@samus-aran Proposed fix (https://github.com/shogunpol/SuiteCRM/commit/894f631a0a467cde92afe87ca32e50a628340a07) resolves the ACL 'Owner' issue on leads. Thanks!!! 

Spots record access is not resolved by this fix. Can you please open a seperate issue and let us know the ID? See my screenshot earlier, View(All) access doesn't work.

**Comment by samus-aran** [comment]
Will do @evgu .  Closed this being a duplicate - https://github.com/salesagility/SuiteCRM/issues/3054
