### ISSUE TITLE
List view Filters Popup is too small in Suite 7 theme (for each module) after 7.8.1 upgrade.

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#3135]
In 7.8.1 upgrade there is a new modules view Filters which now requires users to clock on a button to view their list filter selection. There are two problems: 
1. In Suite 7 theme the module list Filter pop-up does not render correctly. 
2. From UX perspective the old filter view was much more UX friendly and easier to use on desktop/laptop as it rendered as soon as the module list was loaded. With this new filter is not clear to the users what filters are selected when they go to the module's listing, and they have to click around to understand the selected filters which wastes time and frustrates users.   

#### Issue
1. Module list Filter pop-up does not render correctly. 
2. UX of new Filter is not good. 

#### Expected Behavior
1. Have option to select the type of filter old/new. 
2. Fix new module listing Filter 

#### Actual Behavior
1. In Suite 7 theme the module list Filter pop-up does not render correctly. 
2. From UX perspective the old filter view was much more UX friendly and easier to use on desktop/laptop as it rendered as soon as the module list was loaded. With this new filter is not clear to the users what filters are selected when they go to the module's listing, and they have to click around to understand the selected filters which wastes time and frustrates users.   

#### Possible Fix
Bring back the previous filter view which was much more UX friendly and easier to use on desktop/laptop as it rendered as soon as the module listing was loaded. With this new filter is not clear to the users what filters were selected every time they go to a module listing, and they have to click around to understand the selected filters which wastes time and frustrates users.   

#### Steps to Reproduce
1. Upgrade to 7.8.1 and use Suite 7 theme. 
2. Go to any module list view and select the new view filter button. 
3. Filters window does not render correctly. 

#### Context
Cosmetic impact, the new filter form is not rendering correctly. We actually prefer the previous filter window especially for detailed filter queries. Everything was visible as soon as the module's list view was loaded.  

#### Your Environment
*SuiteCRM 7.7.8 upgraded to 7.8.1.
*Theme: Suite 7
*Browsers tested: Safari 10.0.3 and Microsoft Edge 38.14393
*Environment: PHP 5.5.38, MySQL 5.6.35
*OS CentOS 7.3.1611

![image001](https://cloud.githubusercontent.com/assets/18371928/23020375/abb05600-f43e-11e6-9a5f-78b8406b0e47.png)
<img width="1094" alt="screen shot 2017-02-16 at 11 32 11" src="https://cloud.githubusercontent.com/assets/18371928/23020373/aba9829e-f43e-11e6-846f-1ad245b565a5.png">

**Comment by samus-aran** [comment]
Hi @evgu  I have updated the title of your issue to be more specific.

Regards to the UX, there is a hover over tooltip on the filter button showing what is currently being search.

![3135](https://cloud.githubusercontent.com/assets/4041275/23021115/39d9a15e-f442-11e6-993c-8c99f8434a38.png)

**Comment by evgu** [comment]
Hi @samus-aran, Thank you for your response. This new version of the yellow hover over tooltip can be quite crammed from UX perspective, especially with a larger subset of variables - see attached. The old style of filter was much better as:
1. Users were aware geospatially on the screen where the various selection options were.  
2. Users could see the alternative choices for the filters selection. (from attached screenshot from the yellow box can you can not understand where have you gone wrong with your selection if you can not see the other dropdown alternatives.)
3. Users did not have to hover to see filter selection, which adds one extra step. 

Perhaps there could be a switch where this new style filter can be switched on/off in exchange for the old one? 

<img width="571" alt="screen shot 2017-02-16 at 16 05 40" src="https://cloud.githubusercontent.com/assets/18371928/23029774/86c6db6e-f463-11e6-9f3c-a57c748c5876.png">

**Comment by samus-aran** [comment]
Hey @evgu - there is a config setting for this :)

[https://suitecrm.com/wiki/index.php/Release_notes_7.8#SuiteCRM_7.8](SuiteCRM 7.8 Release Notes)

Thanks for the feedback on this.
