### ISSUE TITLE
TextAreas - it shows multirow text edited by inline edit as a text in one row in detaiview

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3136]
#### Issue

The point is simple. If you inline edit the area field, you cant go on next row, because on push enter keyboard button, it saves you the text in one line. 

If the text has a more lines or is breaked by empty row, you can edit it only on editview of record, not by inline edit in textarea, because you haven't chance to break or create new row in text area. 

#### Expected Behavior

You can enter for new rows in textarea by using of inline edit function

#### Steps to Reproduce

1. Go to detailview of record which has the textare field
2. Edit this field by inline edit
3. Try break the line row or create new row by enter

**Comment by sgaved** [comment]
Hi @Mausino,
You can do this by pressing shift+enter.

**Comment by Mausino** [comment]
@sgaved  thank you for you advice 👍 it solved 1. part of my problem.. but still is here issue with one line when you save it by enter or checkmark icon. For example: 

Inline edited textarea in detialview
![textarea1](https://cloud.githubusercontent.com/assets/5773777/23030165/3e328876-f46d-11e6-898e-3c784dd5ca64.png)

After enter or checkmark on inline edit in detailview
![textarea2](https://cloud.githubusercontent.com/assets/5773777/23030267/8c0b3aac-f46d-11e6-9fc4-a7d43b3030d7.png)

Edited by editview and saved. The result on detailview
![textarea3](https://cloud.githubusercontent.com/assets/5773777/23030471/2c7c00fc-f46e-11e6-8564-54ea2238825e.png)

**Comment by sgaved** [comment]
Hey - It appears it saves it correctly but doesn't display it correctly. On refresh you would see the correct way. However, it is a bug that it is not displaying it correctly after saving an inline edit.

**Comment by kdjmonaghan** [comment]
Corrected your issue, @Mausino - the changes will have to be reviewed and merged in before being released in the next build, though. If you're finding this frustrating, please refer to the reference above and add the changes to the file changed to get the results you expect. :)

**Comment by Mausino** [comment]
@kdjmonaghan @sgaved thank you both 👍
