### ISSUE TITLE
suggestion AOS_Products_Quotes: allow custom line_items.php

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#3143]
#### Issue

File /custom/modules/AOS_Products_Quotes/line_items.php is seemingly not picked up by SuiteCRM. 

#### Expected Behavior

File placed in /custom/modules/AOS_Products_Quotes/line_items.php would override /modules/AOS_Products_Quotes/line_items.php.

=> upgrade-safe changes to this file possible

#### Actual Behavior

File placed in /custom/modules/AOS_Products_Quotes/line_items.php has no effect. Changes must be made in /modules/AOS_Products_Quotes/line_items.php

=> changes cannot be made upgrade-safe

#### Your Environment

* SuiteCRM Version used: 7.7.9

**Comment by mattlorimer** [comment]
Line Items is a function field that sets the file that loads, which you can easy change in an upgrade safe way by extending and overriding the vardefs

**Comment by urdhvatech** [comment]
Hello @EZS-JD 

You just need to Extend Vardef of quotes and invoice modules as suggested by @mattlorimer , We did similar for few of our projects. 
Here is sample code :
```
$dictionary['AOS_Quotes']['fields']['line_items']['function'] = array(
            'name' => 'display_lines_custom',
            'returns' => 'html',
            'include' => 'custom/modules/AOS_Products_Quotes/Line_Items.php'
        );
```

**Comment by EZS-JD** [comment]
Thanks for this!

I got PHP errors like:
"Cannot redeclare display_lines()"
"Cannot redeclare stripDecimalPointsAndTrailingZeroes()"

until I either renamed or hid all functions in the custom script. (for anyone out there doing the same thing).

Apparently the standard script is always loaded as well, so you can't use the same function names twice.
