### ISSUE TITLE
Wrong SQL query in security groups module

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#3151]
There is a typo in modules/SecurityGroups/SecurityGroup.php
seect instead of select in SQL query.

#### Issue
A wrong query is generated

#### Possible Fix
in modules/SecurityGroups/SecutriyGroup.php, 
replace
        $query = 'seect securitygroups.id, securitygroups.name from securitygroups_users '
by
        $query = 'select securitygroups.id, securitygroups.name from securitygroups_users '

#### Steps to Reproduce

1.
2.
3.
4.

#### Context
This breaks REST API ... and probably much more

HIGH

#### Your Environment

* SuiteCRM Version used: 7.8.1

**Comment by pgorod** [comment]
@QuickCRM For the simplest PR's touching only one file, it's very easy, you can do it directly from Github - just click to "edit" the file and Github will fork, commit and do the PR for you:
https://help.github.com/articles/editing-files-in-another-user-s-repository/

Remember to switch branch first (to hotfix) before starting your edit.

I did this one for you but I just thought you might like to learn this (in case you didn't know yet, of course).

**Comment by QuickCRM** [comment]
Thanks. 
I had no idea it was that easy. 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile
