### ISSUE TITLE
SuiteCRM fails to adequately housekeep session files potentially resulting in server failure

### ISSUE THREAD

**Issue by anothermouse** [salesagility/SuiteCRM#3157]
There may be implications with Custom Session Directory #877 as that exacerbates the problem, but system concerned is unusable and it is not possible to test this..

#### Issue

session files are not adequately managed. This can result in huge numbers of session files accumulating on the server e.g:

ls -al session_dir | wc

after 6 months use gave:

483419 4350764 41090483

which is over half a million session files. Attempting to remove them:

# rm sess_*
bash: /bin/rm: Argument list too long

as by this point the damage had been done as bash relies on temporary files in order to do this, and as no spare inodes were available, the removal process failed. You can do each one individually.....but you can't keep up with the creation rate!

#### Expected Behavior

SuiteCRM *AND the server it is on* should not be brought to a halt! SuiteCRM can actually disable everything on the server.

#### Actual Behavior

All of the inodes on the mounted drive are used up preventing the writing of any data to the drive, preventing any application that needs to write to that drive from functioning correctly. Signs of this happening are:

pje@archimedes:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            4.0G  8.0K  4.0G   1% /dev
tmpfs           802M  244K  802M   1% /run
/dev/xvda2       99G   37G   57G  39% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            4.0G     0  4.0G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvda1      232M   82M  138M  38% /boot
pje@archimedes:~$ echo 1 > test.txt
-bash: test.txt: No space left on device

(i.e. you can't write to a drive that clearly has sufficient space on it)

In order to identify that you are affected by this issue, you can:
df -i
and you can find the offending directories with:
find / -xdev -size +100k -type d

#### Possible Fix

Add to the cron process that a command to housekeep the session folder on a regular basis. There are probably better ways within the framework to carry out housekeeping on the sessions directory. 

I have introduced a cron task to delete all of the session files at 1am as a temporary measure.

#### Steps to Reproduce

1.     Have a suiteCRM installation with a custom folder for session files.
2.     Wait 6 months for all of the session files to accumulate and use up all of the inodes on the storage device. Information above gives an understanding of the end result and points to the severity of the problem.

#### Context

Server failure

Probably a medium->high issue as it not only brings down the suiteCRM instance but also the rest of the server. 

There is also the failure that has occurred not being immediately obvious due to the logging needing to be improved on the operating system itself:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1665833

#### Your Environment

* SuiteCRM Version used:
Multiple versions of suiteCRM on the system, which started as 7.7.5, and have now all been updated to 7.7.8 and 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
mySQL/PHP - not important can't create temporary file: No space left on device when trying to diagnose anything!
* Operating System and version (e.g Ubuntu 16.04):
Ubuntu 14.04

**Comment by anothermouse** [comment]
Current workaround is to add the following to my crontab file:

#SuiteCRM kill off session files to prevent accumulation:
0 3 * * * rm -Rf /var/www/vhosts/crm.mysite.com/private/sess* > /dev/null

**Comment by chris001** [comment]
By default, the system removes session files older than about 30 minutes, on average, every 8 hours, more or less.  Clearly this is a bug because the system failed to remove them for 6 months.

**Comment by anothermouse** [comment]
Fresh install of 7.7.9 with custom session folder:
/var/www/vhosts/crm.mysite.com/
on Ubuntu 16.04. running the crontab command within root for testing:

root@apollo:/var/www/vhosts/crm.mysite.com/httpdocs# ls -al ../private | grep root | wc
   2885   25965  247923
root@apollo:/var/www/vhosts/crm.mysite.com/httpdocs# ls -al ../private | grep root | wc
   2889   26001  248267

...and we get 4 more session files left over every minute.

The session files are being left behind by the crontab entry and not deleted, so this is creating the orphaned session files that don't get cleaned up:

#SuiteCRM cron
* * * * * cd /var/www/vhosts/crm.mysite.com/httpdocs; php -f cron.php

Running:

cd /var/www/vhosts/crm.mysite.com/httpdocs; php -f cron.php

at the command line (as root) only gives a warning and does not leave behind any session files:

cd /var/www/vhosts/crm.mysite.com/httpdocs; php -f cron.php
PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in /var/www/vhosts/crm.mysite.com/httpdocs/include/SugarEmailAddress/SugarEmailAddress.php on line 1162

and the system appears to be operating correctly. Running this on the command line does not leave session files. All of these session files are zero bytes in size

**Comment by chris001** [comment]
I've developed the fix for this.  I found this bug and fixed it in late 2011 on my instances yet my fix shared with SugarCRM was not included in SugarCRM 6.5 CE at that time, maybe they weren't really checking the community forum closely.  I'll see if I can get this fix in here tonight.

**Comment by anothermouse** [comment]
Thankyou. It gets a little more interesting. I disabled the schedulers in:

include/SugarQueue/SugarCronJobs.php

...and then re-enabled them and the problem doesn't seem to repeatable any more? I'm beginning to wonder if something more subtle is going on here with the schedulers and the cron settings:

  'cron' =>
  array (
    'max_cron_jobs' => 10,
    'max_cron_runtime' => 30,
    'min_cron_interval' => 30,
  ),

finishing too early/overlapping? Hence issue related to performance of the machine that it was running on? Perhaps if cron was set to run every 5 minutes rather than every minute?....or higher spec machine? Can you remember what the root cause of the problem was that you had to fix?

**Comment by pgorod** [comment]
@anothermouse I'm not a Linux guru, but I think something like this could help you easily delete the files:

`find .session/ -atime +7  -exec rm {} \;`

That condition is for files older than 7 days, you may want to adjust that, but the important part is that this command calls `rm` once for every file, so it shouldn't break with many files (though it will be slow).

Just for curiosity, do you happen to have your cron jobs running as root?

**Comment by anothermouse** [comment]
Yes the cron jobs are running as root because the session files are 0600 for www-data and www-data has a nologin shell.

And yes your removal script is a lot more elegant than my suggested work around. Annoyingly:
find sessiondir
fails on the 'broken' system due to the number of files/lack of inodes/bash requirements, whereas
ls sessiondir
works. The reason for my grep against a sess_ file was because I'd also put logs and various other bits in the same folder....but if you've only got the session files yours is a much nicer solution:)

**Comment by pgorod** [comment]
@anothermouse make sure your cron jobs are **not** running as root! 

That could well be a part of your problem, and if you can test for that, it would be great. 

I know that [running cron as root breaks things](https://github.com/salesagility/SuiteCRM/issues/2787), but I would love to know about a new way in which it breaks things : - )

**Comment by anothermouse** [comment]
Thankyou....but clearing old session files that are "0600 www-data www-data "has to be done either as the user that created them, or as root. That's the whole point of file permissions, otherwise you get permission denied?

www-data has a no login shell for a very good reason.

**Comment by chris001** [comment]
@anothermouse   Do you have a user account on the system for whoever's the owner of that particular SuiteCRM application.  Such as a person, a company, an organization.

**Comment by anothermouse** [comment]
@pgorod sorry - just followed the link to running cron jobs as root - and yes I can see the problem, and now understand your comments.

Wrt to the suiteCRM crontask, this was running as user crm (which is the user account that the application is being installed into) on the original production system. Having said that the current system is running as root in order to test as close to the 'original install' as possible, without me changing/messing with file permissions etc. The article you link to is definitely interesting, and the fact that it manage to disable a server completely that I was working on indicates a pretty high severity.

Realistically a user will not be able to run the cron.php task as www-data (or httpd user), so it really ought to be run as the user account concerned, BUT that creates permission issues. I like chris001's approach of using curl to trigger the running of the script via a wget and combining it with a huge random secret. This simplifies permissions.....or there needs to be a better way to define the permissions allowing the user account to be part of the www-data group (which was the approach that I used).

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM fails to adequately housekeep session files potentially resulting in server failure](https://trello.com/c/RMHk0Agc/24-suitecrm-fails-to-adequately-housekeep-session-files-potentially-resulting-in-server-failure)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by anothermouse** [comment]
Note that this is a bug.....and a *really* serious one as it can brig down the server, not just the site!

**Comment by chris001** [comment]
@anothermouse @samus-aran Agreed, this is a bug, it kills the SuiteCRM server.

**Comment by samus-aran** [comment]
Reverted and set to Medium Priority

**Comment by dschroth** [comment]
This bug just took down my multi-tenant webserver that runs Plesk. All of my sites started wobbling and failing weirdly because my tempfs file system ran out of inodes... Deleted all sessions and it's back to normal, but I'm gaining several session files per minute.

**Comment by personman** [comment]
BUMP. I just had this bug very nearly bring down my server. SuiteCRM needs to clean up after itself.

**Comment by samus-aran** [comment]
Thanks for the bump, we are having an open backlog in discussion https://github.com/salesagility/SuiteCRM/issues/7358 Do you want to nominate it as a higher priority?

**Comment by samus-aran** [comment]
@personman @dschroth a PR is opened for this issue. Would be much appreciated if you were abel to confirm it resolves your issue. Thanks.

**Comment by ebogaard** [comment]
Just found out we had a lot of files in the php session dir. As we just increased the value for "session.gc_maxlifetime", that should be expected.
What was unexpected, was the number of 0 byte session files. These make up easily 90% of the total number of files in the session directory.
I was able to trace the creating of those to scheduled tasks that were triggered by the SuiteCRM cronjob. The 'many sessions created'-issue seems to be much closer to issue #877 (which is closed in favor of this issue), than this issue.

This issue is more about properly configuring php than a bug in SuiteCRM. I don't think it would be a good idea to set hard coded php.ini-variables in SuiteCRM (see row 57 of include/SessionHandler.php in 20f9093c9541ea6f5cf4f5d9d7096249604ac6f8). Primarily php,ini should be followed, unless this variable is not set in php.ini or overridden in config_override.php.

But actually, this is mainly a documentation- and/or php-knowledge-issue, not a code-issue.

**Comment by pgorod** [comment]
Since this causes some serious problems what we might do is to try providing a warning. So we could have a periodic check and notify Admins that there are tons of files in their session directory, and suggest that they check their PHP configuration.

**Comment by ebogaard** [comment]
Als the number of session files (or redis keys) created by SuiteCRM is crazy, I started looking into this issue and applied the PR.

First issue:
I can see that a custom session-folder is necessary. As I used redis using a socket, this wouldn't work at first: the "session_save_path()" when configured for redis is a socket or url. I think a situation like that should be taken into accounts by the PR.

Second issue (and main issue for me)
Still a number of sessions is created in redis! What that tells me, is that not all sessions are created using "include/MVC/SugarApplication.php".
When I look for session_start(), I can see that a number of files in "service/", "include/" and "modules/" also contain this function, which may lead to issues and duplicate session files.

**Comment by chris001** [comment]
@ebogaard 
You're right.  The session handling in Sugar 6.5 is less good than it should be.  All calls to session handling functions needs to be refactored out to call one class which handles sessions properly, ie doesn't leave behind a million session files which cause the server to fail, and well supports modern faster in memory session handlers such as `redis`.
