### ISSUE TITLE
Missing labels/options for email field

### ISSUE THREAD

**Issue by dycai** [salesagility/SuiteCRM#3160]
#### Issue

When creating or editing a new account the email field have strange radio buttons and checkboxes beside it which are unlabelled.
![screenshot_3](https://cloud.githubusercontent.com/assets/25896882/23117629/9b5bbb32-f78b-11e6-9e6f-9e2d342abfd7.png)

Whether or not they are selected, the email field would not be saved when I complete the creation of this account.

I just upgraded from 7.4.3 -> 7.6.10 and from 7.6.10 -> 7.8.`

#### Expected Behavior

Email address should be stored.

#### Actual Behavior

Email address is missing
#### Steps to Reproduce

1. Sales > Accounts
2. Create
3. Enter in details 
4. Save.

#### Context

It was working fine before the upgrade and now it isn't, so my sales team is currently at a halt on updating our client contacts under Accounts.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest version of Chrome as well as Firefox
* Environment name and version (e.g. MySQL, PHP 7): SuiteCRM was initially installed as an appliance from Turnkey Linux and upgraded from 7.4.3 -> 7.6.10 and then to 7.8.1 using the upgrade wizard.
* Operating System and version (e.g Ubuntu 16.04): Turnkey Linux? Debian based?

**Comment by horus68** [comment]
It could be an error on your side. 
Have you made the required "Quick repair and rebuild"?
Also make a full cache clean on your browser

This is a pic from the demo site
https://suitecrm.com/demo
![2017-02-20 11_05_20-suitecrm](https://cloud.githubusercontent.com/assets/3055443/23122586/b4476c60-f75c-11e6-9538-82a9d23dca56.png)

**Comment by shogunpol** [comment]
@dycai , please confirm is that issue still exist for you, if not please close an issue. 
If yes please provide information about customisation been made on your instance. I seen some added functionality in name field.

**Comment by dycai** [comment]
Yes this was due to cache. Thanks for the advice!

**Comment by dycai** [comment]
Hi, sorry for the late reply. Yes it was an issue with cache. Thanks for the advice! I'll close this.


On Feb 21, 2017 19:15, Jerzy <notifications@github.com> wrote:

@dycai<https://github.com/dycai> , please confirm is that issue still exist for you, if not please close an issue.
If yes please provide information about customisation been made on your instance. I seen some added functionality in name field.
