### ISSUE TITLE
PDF Templates List View error

### ISSUE THREAD

**Issue by zebelhra** [salesagility/SuiteCRM#3174]
When you go to PDF Templates, there is an error marked with an "x" popup in the list view. 

#### Issue
Go to ALL, then PDF Templates, you'll see an "x" in the list view. If you hover over the "x", you will see the error message as shown in the attachment.

#### Expected Behavior
The error message should not be there.

#### Actual Behavior
Error message popup.

#### Steps to Reproduce

1. Go to ALL -> PDF Templates
2. You should see the error popup marked with "x"

#### Your Environment

* SuiteCRM Version 7.8.1, Suite P theme
* Browser name and version: CHROME Version 56.0.2924.87 (64-bit):
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):

**Comment by shogunpol** [comment]
@zebelhra , can you provide screenshots?

**Comment by zebelcrm** [comment]
![pdf_error](https://cloud.githubusercontent.com/assets/20979933/23239047/c6071996-f919-11e6-9c91-88fd6cbcbad0.jpg)

**Comment by shogunpol** [comment]
@zebelcrm , the issue has been tested in recent version of the SuiteCRM(7.8.1), and not appear, do you use fresh install, or upgraded from previous version?

**Comment by zebelcrm** [comment]
I upgraded from version 7.7.9.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this in 7.9.x as a core issue. If this issue still exists and you can provide more information for us to proceed then it can be reopened. Thanks.
