### ISSUE TITLE
$sugar_config['enable_legacy_search'][] = 'Targets'; Does Not Enable Legacy Search

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#3179]
Using $sugar_config['enable_legacy_search'][] = 'Targets'; in config_override.php does not enable legacy search menu. 

#### Expected Behavior
$sugar_config['enable_legacy_search'][] = 'Targets';  enables legacy search menu. E.g. Similar to $sugar_config['enable_legacy_search'][] = 'Leads';

#### Actual Behavior
New-style search menu is shown. 

#### Steps to Reproduce
1. Insert $sugar_config['enable_legacy_search'][] = 'Targets'; on a new line in config_override.php
2. Run quick repair and rebuild  
3. Go to Targets module listing. New style filter is shown instead of the legacy one. 

#### Your Environment
* SuiteCRM Version 7.8.1
* Safari 10.0.3
* PHP 5.5.3
* CentOS 7.3.1611

**Comment by mattlorimer** [comment]
you need to us the actaul name of the module target is actually Prospects

**Comment by evgu** [comment]
@mattlorimer $sugar_config['enable_legacy_search'][] = 'Prospects';  resolves this. Many thanks.
