### ISSUE TITLE
DynamicDropdown field not working in Search View

### ISSUE THREAD

**Issue by ajedvaj** [salesagility/SuiteCRM#3185]
#### Issue

Values in child dropdown don't get reduces on selecting options in parent dropdown on Search and Popup Search (Filter view in SuiteCRM v7.8.1). On Edit view they work as expected.
The issue is tested and representing in versions 7.7.8 and 7.8.1.  

#### Expected Behavior

Selecting an option on parent dropdown should reduce list of options in child dropdown only to ones dependent to parent value.

#### Actual Behavior

The child dropdown list remains unchaged.

#### Steps to Reproduce

1. Add one dropdown field to any module and add one dynamic dropdown field where parent is the firstly created dropdown.
2. Put both fields on Search (Filter) views.
3. Go to modules List View
4. Try changing the value of parent dropdown in Search (or Filter) view and child dropdown won't change

#### Your Environment

* SuiteCRM Version used:
7.7.8 & 7.8.1.
* Browser name and version:
Chrome Version 52.0.2743.116 (64-bit)
Firefox v50.1.0
* Environment name and version:
mysql  Ver 14.14 Distrib 5.5.50
PHP 5.5.9-1ubuntu4.19 
* Operating System and version:
Linux Mint 17.1

**Comment by shogunpol** [comment]
@ajedvaj ,an issue has been tested in recent version of SuiteCRM(7.8.1), and not appear. did you assign values from drop down to accounts you tested?

**Comment by ajedvaj** [comment]
I think you didn't understand me. It's not problem with executing the search, but with the frontend behaviour of dropdowns as the list of options in the dynamic dropdown isn't reduced.

I have two dropdowns, a parent one (account_type) and a child one (account_subtype_c) which is dynamic with parent set  as  Type.

![dynamic](https://cloud.githubusercontent.com/assets/18736912/23356291/951a05d2-fcd9-11e6-8144-49eabccd7f5c.png)


The account_type has values:
-blank-
Analyst
Competitor
Customer
Integrator
...

The account_subtype_c has values:
Analyst_1 [A1]
Analyst_2 [A2]
Competitor_1 [Competitor_1]
Customer_1 [Customer_1]

I expect that if I in Search click on account_type 'Analyst' in account_subtype_c I should see only Analyst_1 and Analyst_2 as options, but that doesn't happen. I still see all the values in account_subtype dropdown.

![search](https://cloud.githubusercontent.com/assets/18736912/23356525/80d4c782-fcda-11e6-85d6-07cef560cca0.png)

**Comment by dvkesarwani** [comment]
Even i m having same issue.
In Search filters i m not getting dynamic dropdown functionality like in editview,
Child field is not showing data as per selection of parent field.

**Comment by samus-aran** [comment]
I agree @Mausino that this sounds like a suggestion and perhaps a complex one and that requires a little bit of decision making.

I agree that the dynamicdropdown should reflect accurately when one has been updated via the inline editing so your issue #4063 should remain open.
