### ISSUE TITLE
IMAP Keywords - better cooperation for the teams

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3188]
Hi, the company "mouses" as me are dreaming for IMAP Keywords

http://forum.rebex.net/878/how-to-use-keywords-custom-flags-in-imap

Because many departments have the access to one email address and they need life nessary flag the mails, because they need know in which step is the mail.. Cases are fine but are as from dinosaur ages. 

For example if i create a case, i will love if could mail be marked with IMAP keyword like CASE that everybody knows that this email was converted to case or IMPORTED (or whatever)... now when more people working together on one imap email address,  it's totaly mess and it's very hard colaborate. Could we move the EMAIL to next CENTURY?

Please i nessary need your oppinion because am i only one who is dreamig about this keywords (tags) for EMAILS ???
![preferencetag](https://cloud.githubusercontent.com/assets/5773777/23302012/06356274-fa8d-11e6-8f8e-153ce5dfe479.png)
If you like this suggestion, please like this ticket 🥇 that it will show that it has the support of community 👍

**Comment by chris001** [comment]
It makes sense.  Writing a "CASE" tag out to the email message on the email server, would have the effect of sorting all the Case-related email messages on the mail server.  When you do that, you're storing a mirror copy of part of the application state in the IMAP server.  From that point going forward it'd be best to update the state of the tag for that email message on the email server at any time there is a change in the state of the case email message inside the CRM.

**Comment by samus-aran** [comment]
@Mausino The concept of having the ability to categorise a email is in the roadmap.  It would be that on the email record you can select from the dropdown the emails category.  Would the fit your needs and add that dropdown to the filtering in the new email client?

**Comment by chris001** [comment]
@samus-aran @daniel-samson   What @Mausino is referring to is, the application needs to get/set/update/delete state in the email header `X-Keywords` this is the header which GMail, and other mail servers, use for categorizing email messages.  You need to not overwrite existing keywords already placed in there by the mail server or the user thru their email client app, and not use reserved system keywords unintentionally.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IMAP Keywords - better cooperation for the teams](https://trello.com/c/q0kMtznE/21-imap-keywords-better-cooperation-for-the-teams)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by pgorod** [comment]
I see we now have Email categories #3391 but I am not sure how it relates to IMAP labels.

**Comment by samus-aran** [comment]
@pgorod Its not related at the moment :)

**Comment by Mausino** [comment]
@samus-aran everything which helps with management of one email box for team is good. 

My question is... Will possible in future also add second categories or add tag system? Example: I see email, i see that is new unread (new text in column, unread that email has other backgroung), now Saleagility will add categories like case, project, etc... But it helps if will have second category like  that i will see: need input, completed,  redirect, rejected etc.

Your opinion?

**Comment by chris001** [comment]
@Mausino Right now the code's not doing anything.  This function will work as soon as the code persists the tags/labels/keywords to the email header, `X-Keywords`.

**Comment by Mausino** [comment]
@chris001 you are right... I know X-Keywords are not, but maybe it is fist step in SuiteCRM. Better something like nothing.  But X-Keywords could help sync the tags across the imap mail programs like Outlook or Thunderbird and etc. And i think that X-Keywords are the future for cross mail programs and crm cooperations.

 @samus-aran please did  Saleagility create some roadmap for email management ?

**Comment by chris001** [comment]
@Mausino There's a saying, if you're going to do it, then do it all the way.  What people don't know is, there are third party free php libraries available, made to straight forward store information and read information out of email headers.  Doing this right is nothing to shy away from.  This would be one of  those really nice productivity enhancing features that saves people a lot of time and aggravation over what's currently offered.
