### ISSUE TITLE
Display - advanced filter with 7.8.1

### ISSUE THREAD

**Issue by edilex** [salesagility/SuiteCRM#3190]
#### Issue

Fields go outside frame

#### Expected Behavior

Frame adjusts

#### Actual Behavior

Fields outside frame

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
!
![capture d ecran 2017-02-15 a 16 43 27](https://cloud.githubusercontent.com/assets/23078474/23307147/75d52f42-fa74-11e6-97ec-98ed8ed4740e.png)

**Comment by samus-aran** [comment]
Duplication of issue below.

https://github.com/salesagility/SuiteCRM/issues/3012
