### ISSUE TITLE
Error in query - SecurityGroup.php

### ISSUE THREAD

**Issue by lodevlayen** [salesagility/SuiteCRM#3193]
Login via mobile app QuickCRM (IOS) - error message: error login. check credentials and check crm logfile.
#### Issue

Typo error in query 
module: SecurityGroups 
file: SecurityGroup.php
function: public function getUserSecurityGroups($user_id)

#### Expected Behavior

Normal login app Quickcrm on IOS
#### Actual Behavior

Login fails
#### Possible Fix

change ‘seect' to ‘select’

#3192 ### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n.a.
* Environment name and version (e.g. MySQL, PHP 7): n.a.
* Operating System and version (e.g Ubuntu 16.04): n.a.

**Comment by chris001** [comment]
Good find.  The typo on the sql is in #3153 if you're able to, it's easy to apply the fix to the file in your instance.

**Comment by pgorod** [comment]
Isn't this an exact duplicate of #3153 ?

**Comment by mattlorimer** [comment]
yes good spot, duplicate and fixed in 7.8.2
