### ISSUE TITLE
Leads DetailView table cell color issue (Suite 7)

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#3203]
#### Issue

When i expand my row in studio, there is a cell color issue on DetailView.
![screenshot_2](https://cloud.githubusercontent.com/assets/22373035/23451844/ce86a83a-fe72-11e6-8ed5-4f8452482633.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/22373035/23451848/d35d0caa-fe72-11e6-82e9-4d434c82180d.png)

#### Expected Behavior

it should be like not expanded row.
#### Steps to Reproduce

1. Open studio
2. Add some field to leads detailview.
3. Expand added field.
4. See result.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 51.0.1 (32-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04):Ubuntu Linux 16.04
* Theme : Suite 7

**Comment by dursuntosun** [comment]
When i apply this fix, it appears fixed but there is an other issue like this;
![screenshot_1](https://cloud.githubusercontent.com/assets/22373035/23788709/73fb8f24-0580-11e7-8c4f-9d99a2cad698.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/22373035/23788711/78764abc-0580-11e7-80a1-42c55528acb3.png)

**Comment by dursuntosun** [comment]
Is it possible to align colored table same line. 
![screenshot_3](https://cloud.githubusercontent.com/assets/22373035/23788838/04e45de0-0581-11e7-81b5-271bfb4a7714.png)

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
