### ISSUE TITLE
Hitting enter in the password input saves the user but not the password

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#321]
In the edit user screen if you enter a new password for a user it will save the user but not the password. You need to hit "Save" in order to save the password (and then get the confirmation popup).

This should probably either behave the same in both cases or enter shouldn't cause the submit in the password field.

**Comment by darthtang** [comment]
Also note:

When filling in fields on the 'User Profile' tab when editing a user. And then if you hit space to save, the system WILL NOT save! The system will only save anything if you click on the 'Save' Button at the top. 

I also suggest maybe an 'Are you sure you want to save?' confirmation box before each save! This will add to a user friendly environment :+1:

**Comment by Dillon-Brown** [comment]
@Mausino I can replicate the same, will put up a fix.

**Comment by Mausino** [comment]
Great.. the patch is working 👍 @Dillon-Brown should it get some milestone ?

**Comment by Mac-Rae** [comment]
Confirmed in latest 7.10.x 

Doesn't save however does open user email settings located on the other page :/

**Comment by Mausino** [comment]
@Dillon-Brown why wasn't this solution merged yet? it needs something?

**Comment by Dillon-Brown** [comment]
@Mausino Hmm, not sure. I might have just missed it. Either way, it will need re-based to hotfix-7.10.x and the code-review comment completed. I'll take a look when I get a chance. Thanks!
