### ISSUE TITLE
Bug in 7.8.2 - checkboxes disabled in listview

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#3214]
#### Issue

Forum:
https://suitecrm.com/forum/feedback/12885-bug-in-7-8-checkboxes-disabled-in-listview

When in ListView, if you select all elements in the page you can correctly deselect those you don't want.
(see image 1)
Image 1:
![zz01](https://cloud.githubusercontent.com/assets/8026129/23528819/7390fcb2-ff9b-11e6-8eb5-6ddfe66861d3.png)

However, if you select all elements via the dropdown menu, the checkboxes are disabled so you have to keep all without the possibility to deselect unwanted elements.
(see image 2)
Image 2:
![zz02](https://cloud.githubusercontent.com/assets/8026129/23528838/8a2e483a-ff9b-11e6-9213-aa927857c966.png)

#### Expected Behavior

The de-selection of unwanted items should be allowed.

#### Actual Behavior

The de-selection is disabled. (see image 2)
Image 2:
![zz02](https://cloud.githubusercontent.com/assets/8026129/23528838/8a2e483a-ff9b-11e6-9213-aa927857c966.png)

#### Steps to Reproduce

1. go to accounts or any other listview
2. from the dropdown menu above the checkboxes: click on select all
3. once yu have done the selection you are unable to de-select specific items from the whole selection
4.

#### Your Environment

* latest (7.8.2) SuiteCRM Demo version hosted by SalesAgility
* Browser:latest available version of Chrome for Windows 10 Professional 64 bits

**Comment by shogunpol** [comment]
@amariussi , this is not an issue.When using "select all" is intended do not use tick boxes.

**Comment by amariussi** [comment]
This is an issue and it is clearly a bug!

If I want to select all elements except some that, because of the poor functionality of the search, I cannot filter out, and then add them to a target list, I am obliged to maintain also a second target list that contains the elements to be excluded.
The rigidity imposed as it is today is useless and it only makes life more difficult, while it produces no advantages: What would be the problem if using the checkboxes was enabled? None!!!

On the other hand there is a problem when it is disabled!!!

**Comment by horus68** [comment]
Sellect All and tehn untick just some is a basic feature/trick I assumed all people used in any list. Its a normal technic required on any software. So this should be considered a bug, even if it could by (bad)design.
So change design and activate the option!

**Comment by amariussi** [comment]
@shogunpol Please reopen.

This rigidity of the programme is useless.
If you have 10.000 records and you need to select them all except 20 you would have to spend hours. Your closing of this issue has been criticised by others. Please be realistic.

In any case: I have found how to enable the checkboxes. I am testing to make sure it doesn't impact other parts of the programme. Hopefully tomorrow I should be able to issue a pull request.

Thanks!

**Comment by amariussi** [comment]
@Dillon-Brown @samus-aran @CamoMacdonald Would you consider reopening this issue?

It doesn't harm anyone. But if improves the overall quality of the CRM by giving more flexibility and a much better user experience!

Furthermore, there is a fix here: https://github.com/salesagility/SuiteCRM/pull/3224
