### ISSUE TITLE
Location field doesn't show in Meetings email notifications

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3222]
#### Issue
There are two notification emails: one for meeting assignment, another is a reminder.

When meeting notification emails go out, the meeting location appears empty (in one email) or doesn't appear at all (in another).

#### Expected Behavior
Meeting location should be visible and filled in both emails.

#### Actual Behavior
As described above.

#### Possible Fix
This is because one template doesn't even include the field, and the other does, but the field wasn't even getting loaded into the template engine.

#### Steps to Reproduce
1. Fill meeting location field in a meeting
2. Generate email from that meeting (assignment / reminder)
3. Check absent location information

#### Context
This comes from a forum thread: 
https://suitecrm.com/forum/suitecrm-7-0-discussion/13251-meeting-confirmation-emails-location#44728
The user tested the solution on that thread.

#### Your Environment
Applies to all versions/environments

**Comment by pgorod** [comment]
Fix is proposed in PR #3223

**Comment by samus-aran** [comment]
Hey @pgorod thanks for providing the fix.

When supplying fixes via commits you can link the commit/PR to the issue by using the following commit  format:

git commit -m "Fix #1436 - Reports with nested Parentheses are removing parameters"

If you put in 'Fix #number of the issue' it will link the Issue to the PR automatically, AND when it is merged into master that it will close the issue automatically - which is a great help to us. :+1:

**Comment by pgorod** [comment]
But I did exactly that, the PR is called `Fix #3222 meeting location field in email notifications`, why didn't it link?

**Comment by samus-aran** [comment]
If you look at t yur commit you missed out the number of the issue :)

https://github.com/salesagility/SuiteCRM/pull/3223/commits

**Comment by pgorod** [comment]
Oh, I see, the number has to be in the commit, not in the PR title. Strange option, since there can be many commits in a single PR, and I don't know which one must have the reference; maybe the last one'

It would make more sense if Github would pick up the reference from the PR title... anyway, thanks for the explanation.

**Comment by horus68** [comment]
@pgorod In the PR description you just need to include the # followed by the issue number that PR is related. Same goes with comments on any Issue or PR
So there is no problem with several commits in the same PR.

**Comment by pgorod** [comment]
Basically the references work everywhere except on PR titles, which is quite weird. But ok, I know how to do it now.
