### ISSUE TITLE
Upgrade to Sugar 6.5.25

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#3226]
Version 6.5.25 is released, https://github.com/sugarcrm/sugarcrm_dev/

#### Issue

Sugar version in SuiteCRM is at 6.5.24.  Upgrade to current version of Sugar 6.5.25 released Thursday March 2, 2017.

#### Possible Fix

* Compare 6.5.24 to 6.5.25, add changes from the changed files.
* At first look it appears YUI, PHPMailer, and checksums were upgraded.
* Goal is to do `composer update` and that pulls in all the updates from Sugar CE source repo with no need to do any type of manual merge process.

**Comment by pgorod** [comment]
@samus-aran let's not forget to merge this one,  on their site they say this is a security update and _"we strongly recommend that you install this update at the earliest opportunity."_ 

Thanks!
