### ISSUE TITLE
Subpanel lists are not showing plus new filter search is not working-SuiteCRM 7.8.2!

### ISSUE THREAD

**Issue by itglaafs** [salesagility/SuiteCRM#3229]
Subpanels and new filter search are not working properly under respectable modules.

#### Issue

Upgraded from 7.7.9 to 7.8.2, Subpanels under any of modules are not showing correctly, all of the lists under subpanels are gone, only name of subpanels is showing up. Additionally new filter search is not working and you have to switch to old legacy search in order to see clients and data.

#### Expected Behavior

Subpanel should be showing links if there are any relationships with desired module. New filter search should be removed or improved, or at least we should have an option to choose if we want to use it in modules under admin panel.
#### Actual Behavior

Like I said it's all messed up and not working at all.
#### Steps to Reproduce

1.http://screencast-o-matic.com/watch/cbe1DU6uSW
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 51.0.1 32bit
* Environment name and version (e.g. MySQL, PHP 7): PHP  5.6.30, Mysql 5.6.35
* Operating System and version (e.g Ubuntu 16.04): Cpanel Linux kernel version 3.10.0-327.10.1.el7.x86_64

**Comment by horus68** [comment]
@itglaafs can you please copy and past the error message you highlighted on your screencast?

Also confirm this error if:
- You run again a quick repair
- You changed template to SuiteP
- Used a different browser (and cleaned the cache)

**Comment by itglaafs** [comment]
@Horus68

Thank you for your reply. We tried it all but it's same.

Best Regards,

Slaven.

**Comment by horus68** [comment]
Then maybe you need to post this on the forum to get help as this could be just on your installation. 
Github is for confirmed errors on the system itself.
Forum https://suitecrm.com/forum/index
Note: Please also include the error message as I requested.

**Comment by itglaafs** [comment]
This is the error message on any browser with many different machines that
we tested:

"ListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extension ListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extensionListViewSubPanel::initNewSmartyTemplate path must have an tpl
extension"

Note that this is after upgrade from 7.7.9 to 7.8.2. It's worth mentioning
that initial original SuiteCRM was 7.2.1 max, but all upgrades were almost
flawless so far, except for donwload.php page that we needed to restore
from older system and some other smaller bugs...however this latest upgrade
has apparently as you can see broken subpanel list under any modules, and
on top of it all, most important one of them all "History" is not linked
anymore, not showing any records related to Notes of Accounts or Leads or
any other module.

Best Regards,

Slaven.

**Comment by samus-aran** [comment]
Hi @itglaafs How much customisation have you made to your SuiteCRM?  That error message indicates that you have custom SubPanels or that you have created custom SubPanels (are the tabbed groups custom?)

1. The error you see:
ListViewSubPanel::initNewSmartyTemplate path must have an tpl extension

Is from the file:
https://github.com/salesagility/SuiteCRM/blob/master/include/ListView/ListViewSubPanel.php#L64

Basically whatever subpanel you should be seeing in place of those are not smarty templates and ending in .tpl

2. Looking further on in your screencast I can see a few console errors, and the ACTIONBULK ACTION button is clearly off.  This would definitely indicate that the upgrade wasn't successful.  

Just to ensure you have the correct upgrade and upgrade was successful I would highly recommend you compare the 7.7.9 - 7.8.2 upgrade pack and confirm that the files from that package match up to the files within your system.

Another thing to point out is that before/after an upgrade that you check the file permissions and hard refresh your cache to ensure JS scripts are re-cached by the system.

Generally this looks like not a specific issue but a overall upgrade issue you are having.

**Comment by semoru** [comment]
Hello,

I just upgraded from 7.7.3 to 7.8.2 and had the same problem.

However, the issue was solved by:

- running and "quick repair and rebuild"
- checking and re-setting the file permissions on the server
- and cleaning the cache in the browser

Hope it helps!

**Comment by itglaafs** [comment]
Hello,

I did it again on a new copy of production system and It's not working for
me. I tried with 3 different browsers, cleaning cache and doing repair,
rebuild. However, I did not tried with file permission changes as I don't
know which files or folders I need to alter permissions for?

I hope that it will help at the end. :)

Best Regards,

Slaven.

**Comment by semoru** [comment]
@itglaafs You could try setting

chown -R <user>:<group> /<suiteCRM_folder>

example: chown -R apache:apache /var/www/html/SuiteCRM

hope it helps!

Cheers
Sergio

**Comment by gunnicom** [comment]
For me on ubuntu i do following line once in a while:
`sudo chmod -R 775 cache custom data modules && sudo chmod 664 config.php && sudo chown www-data:www-data * -R`
