### ISSUE TITLE
System Outbound Account still visible on Users Mail Account when it should be disabled.

### ISSUE THREAD

**Issue by johnrigler** [salesagility/SuiteCRM#324]
I set up a system-wide SMTP mail server for admin messages.  Then I set up users, which were allowed to use it.  As an admin, I unclicked the option under Administration/Email Settings that says "Allow users to use this acount for outgoing email:" and expected that when I went into Emails/Settings/Mail Accounts, to no longer see a reference under "Outgoing SMTP Mail Servers".  It is still there however, and I see a message that says: "Warning: Missing username and password for outgoing mail account."  I would expect no entry at all.  I also don't seem to be able to delete this entry all-together.  I am using Version 7.2.2

**Comment by johnrigler** [comment]
![screenshot from 2015-07-28 17 12 56](https://cloud.githubusercontent.com/assets/7305117/8945315/f6547352-354b-11e5-88f8-0b2ff65101ab.png)

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that.
