### ISSUE TITLE
Update from SuiteCRM 7.8.1 to 7.8.2 -> The uploaded file is not compatible with this version of SuiteCRM:

### ISSUE THREAD

**Issue by mikebc23** [salesagility/SuiteCRM#3245]
I am trying to update from SuiteCRM 7.8.1 to 7.8.2. I use SuiteP theme.

Once I proceed I received this message:

The uploaded file is not compatible with this version of SuiteCRM.

#### Expected Behavior

I expected the update to be functional, due a 'normal update' from 7.8.1 to 7.8.2 

#### Actual Behavior

Error message: The uploaded file is not compatible with this version of SuiteCRM.

#### Steps to Reproduce

1. Proceed using Update Wizard and upload the file.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 56.0.2924.87 (64-bit) and Safari Version 10.0.3 (12602.4.8)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): CentOS Linux release 7.3.1611 (Core)

**Comment by horus68** [comment]
You should post this on forum, as it do not seems an error on the CRM but just on your system or file downloaded

**Comment by samus-aran** [comment]
@mikebc23  - @horus68 is correct that usually with Github we have issues with the product itself rather the upgrade packs, BUT since I am here - where did you download the upgrade pack from?  The website or soureforge?

**Comment by mikebc23** [comment]
I downloaded from https://suitecrm.com/download

SuiteCRM-Upgrade-7.8.x-to-7.8.2 option.

**Comment by samus-aran** [comment]
@mikebc23 Try downloading it from sourceforge and we can have a look if there is any issues between the  packages.

https://sourceforge.net/projects/suitecrm/files/upgrades/
