### ISSUE TITLE
Suite7 theme - inline editing does not work

### ISSUE THREAD

**Issue by peter-haspra** [salesagility/SuiteCRM#3247]
After upgrading from SuiteCRM 7.7.8 to 7.82, inline editing in List View in theme Suite7 does not work. It is not working even on fresh installation of SuiteCRM.

Tested on:
Version 7.8.2
Sugar Version 6.5.24 (Build 509)
Browsers: 
Mozilla Firefox 51.0.1 (32-bit)
Google Chrome 56.0.2924.87 (64-bit)

**Comment by shogunpol** [comment]
@peter-haspra , what modules, views (all of them?) , please provide steps to reproduce from real case, and provide information about where doesn't work.

**Comment by peter-haspra** [comment]
Test steps:
1. I downloaded and installed SuiteCRM 7.8.2 with sample data
2. I tried to inline edit some (random) fields in List View of modules: Accounts, Contacts, Leads, Tasks - none of it worked.
