### ISSUE TITLE
Uncaught Error in CalendarDisplay Line 178

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3254]
The PHP Log file reports
[10-Mar-2017 16:19:55 Australia/Melbourne] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /DELETED/SuiteCRM/modules/Calendar/CalendarDisplay.php:176

#### Issue

That line 176 in CalendarDisplay.php shows
$location_array = "";

#### Expected Behavior

That line 176 in CalendarDisplay.php SHOULD show instead
$location_array = array();

#### Actual Behavior

N/A

#### Possible Fix

Replace with
$location_array = array();

#### Steps to Reproduce

1.open  CalendarDisplay.php
2.goto line 176
3.check and it says  $location_array = "";
4.which crashed as error as $location_array is used as "$location_array[]=$view; " which leads to error

#### Context

it wont show the calendar properly

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):N/A
* Environment name and version (e.g. MySQL, PHP 7):php7.2 mysql 5.6.35
* Operating System and version (e.g Ubuntu 16.04):Centos6.X

**Comment by ijdavie** [comment]
This has been fixed and is due to be in the next release. you can see more information about this here #3227. Thanks.

**Comment by jobst** [comment]
thhx.
