### ISSUE TITLE
Reminder´s user preferences not saved

### ISSUE THREAD

**Issue by esantand** [salesagility/SuiteCRM#3258]
#### Issue

Every time a change in the reminders user preferences is set, then save, that change is not considered, keeping default preferences (i.e. not checked)
#### Steps to Reproduce

1. Edit User profile
2. In Advanced Tab, check: Reminder popup and Email invitees
3. Save
4. 

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Versión 56.0.2924.87
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5
* Operating System and version (e.g Ubuntu 16.04):

**Comment by jawadRT** [comment]
I am facing the same issue in Version 7.12.0, could you please tell me is it resolved in latest version ?
