### ISSUE TITLE
7.8.1 column choser does not apply/save modifications

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#3259]
using the new column chooser we can drag columns from top to bottom and vice versa, once done we save the button change color and we close ...  it would seem that the operation completed but nothing changed on the page.
no modification appears on the list page, even if we refresh the page.

tested with account module and case module same behavior

I had the $sugar_config['enable_legacy_search'][0] = 'Accounts';
and removed it to test -- same behavior
I performed a quick repair and emptied browser cache -- same behavior
tried with Suite7 theme and SuiteP -- same behavior

Tested with I.E. 11 and Chrome
running out of win 10 client
and iis server with mssql database.

.... as a patch waiting for correction/new version,  how can I get the old one back ?

**Comment by kdjmonaghan** [comment]
Hello,

I'm currently running an installation of SuiteCRM locally here on the following platform and software:

Operating System: Ubuntu 16.04
Server: Apache, local instance
DB: MySQL
Browser: Chrome, Version 55.0.2883.87 (64-bit)

On my environment,  I went into the Accounts module as you described in your opening post. Using SuiteP as the theme.

I opened the "Choose Columns" pane and restructured Name to be the second Column and for City to be the first Column and hit save.

The result is that the page restructured as expected.

This is using MySQL and Apache, not IIS and MSSQL, but, it seems like the functionality is working for me...

Out of curiosity, what version of Suite are you running? You didn't mention it in your opening message.

Thanks

**Comment by bmwtourer** [comment]
Okay, let's use SuiteP theme.
![image](https://cloud.githubusercontent.com/assets/9001018/24047279/96a26414-0afb-11e7-81f0-0db38b7a3131.png)
I get this
![image](https://cloud.githubusercontent.com/assets/9001018/24047298/a5b7a694-0afb-11e7-8884-51c83996e61d.png)

I move many column down.
![image](https://cloud.githubusercontent.com/assets/9001018/24047336/bfe65a92-0afb-11e7-8789-81db75ca8957.png)

I hit the save button at the end of the window, it is orange before I click on it and turn gray once clicked (I presume this confirms that I clicked on it.).
Now I hit the pinkist  Close button
and I get the very same screen as before
![image](https://cloud.githubusercontent.com/assets/9001018/24047439/152a063e-0afc-11e7-8f32-301c7b78e635.png)

I tried using the x to close the form after saving, same result...

running 7.8.1 in test environment iis and mssql2012
I can not put this in production...

**Comment by samus-aran** [comment]
The issue is that when you click Save Changes is should close the window for you - which it isn't doing - thus the saves aren't actually being saved.

**Comment by Kevconry** [comment]
Wasn't able to replicate in 7.13.1. When removing some of the columns to not be included in the search, the columns I removed were not included and only the ones I included were shown in the search.  Please re-raise or get in touch if you are still having this issue
