### ISSUE TITLE
Customer Portal Welcome Email Blank

### ISSUE THREAD

**Issue by nbouwsma** [salesagility/SuiteCRM#3261]
After upgrade to 7.8.1 we have observed that emails sent to newly created Portal Users are completely blank.  Prior to version 7.8.1 the email welcomed them and provided login credentials to Joomla Customer Portal (1.1.1)

#### Issue
Email is sent but with no Subject or Body

#### Expected Behavior
Welcome email template should be invoked and contain the username and password to leverage the Customer Portal

#### Actual Behavior
Email is deliverd to the Portal User though completely blank.  See https://www.suitecrm.com/forum/suitecrm-7-0-discussion/13070-aop-problem-templete-new-user-portal#44062

#### Possible Fix
Locate Template and invoke it to the email sent.

#### Steps to Reproduce

1. On 7.8.1-7.8.2 Create New Portal User
2. Receive Email that is blank.

#### Context
We now have to log into Joomla and set the authentication and provide to the Portal User manually

#### Your Environment
Suite CRM 7.8.1 Joomla Portal 3 using 1.1.1
Ubuntu 14.04

**Comment by chris001** [comment]
Probably should also post issue to https://github.com/salesagility/SuitCRM-Portal-Joomla/issues

**Comment by nicodelon** [comment]
I confirm the description of this bug.
I have this problem : I setup and open AOP but when I created access portal user, the user is created in Joomla and all works fine but the email received by the user is totally empty.

Below, what the user expects to receive (for example) :
Hi Mr. Super COOL,

An account has been created for you at http://www.blabla-crm.fr/

You may login using this email address and the password BHS677SGU

Below, what the user receives (after portal account creation) :
subject : (empty)
body : (empty)

Below, what the user receives if we send him an email by ourselves via the Joomla creation account template :
Hi Mr. Super COOL,

An account has been created for you at $portal_address.

You may login using this email address and the password $joomla_pass

By the way, do you know if there is a way to retrieve the user account portal password ? The only way I could to retrieve it to consult log. For waiting a correction of this bug, we thaught to send an email manually with the passord but we did not success to retrieve it (it would be great if we could see it in a field on the contact). 

So presently, for waiting, we decide to send an email including just the weblink portal and asking the user to create directly a new password with his own email on the portal page.

**Comment by nbouwsma** [comment]
Confirmed fixed.  Thank you @shogunpol and @mattlorimer!
