### ISSUE TITLE
Add $current_user to PDF Templates on custom module

### ISSUE THREAD

**Issue by immhub** [salesagility/SuiteCRM#3263]
Hello,

How can i add $current_user (the user that is currently logged in and generated the templated) to a PDF Template builded on a custom module?

**Comment by immhub** [comment]
Please Help :)

**Comment by pgorod** [comment]
Hello @immhub this is not a support forum to ask questions, I suggest you close this issue here and open a new thread on the forums:
https://suitecrm.com/forum/
I'm sure you'll get some help there. Thanks.
