### ISSUE TITLE
require_once(themes/SuiteP/layout_utils.php): failed to open stream:

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3264]
PHP Logfile reports this when trying to open admin pages, e.g. groups management

There are real issues with themes (see my other issues), these should be fixed and foremost before adding new features as it will become a vicious circle.

#### Issue

[12-Mar-2017 12:31:36 Australia/Melbourne] PHP Warning:  require_once(themes/SuiteP/layout_utils.php): failed to open stream: No such file or directory in /PATH/SUITEDIR/modules/SecurityGroups/config.php on line 35
[12-Mar-2017 12:31:36 Australia/Melbourne] PHP Fatal error:  require_once(): Failed opening required 'themes/SuiteP/layout_utils.php' (include_path='/PATH/SUITEDIR:/PATH/SUITEDIR/include/HTMLPurifier/standalone:/PATH/SUITEDIR/include/..:.:/usr/share/pear:/usr/share/php') in /PATH/SUITEDIR/modules/SecurityGroups/config.php on line 35

#### Expected Behavior

no error and page opens properlly

#### Actual Behavior

PHP error and page does not open properly

#### Possible Fix

CREATE the file as it is part of all other themes

#### Steps to Reproduce

1.click on security groups management using SUITE P
2.check the logs
3.no page displayed

#### Context

I can change the theme do it there

#### Your Environment

* SuiteCRM Version used:7.6.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):N/A
* Environment name and version (e.g. MySQL, PHP 7):N/A
* Operating System and version (e.g Ubuntu 16.04):N/A

N/A means it will happen no matter what.

**Comment by chris001** [comment]
This bug was fixed 7 months ago, see the commit message on `modules/SecurityGroups/config.php`.  You need to upgrade from your version 7.6.10, to current version 7.8.2 and it'll work fine.

**Comment by jobst** [comment]
OK, thanks - did not know. Problem cant do that in the moment because of all my other issues and problems with PHP7.X.

**Comment by chris001** [comment]
There should be a setting on your server to temporarily switch the version SuiteCRM is running on to PHP 5.6, then the Upgrade Wizard should work fine without error and get your system updated to 7.8.2.

**Comment by jobst** [comment]
that is not my only problem. we have colors defined for each meeting status (meeting_status_dom) otherwise the calendars for our people look just one big patch of color. But this does not work anymore.
I tried to upgrade but my people where complaining as the calendar was just a lake of one color 6B5171.

I used to be able to solve this by one simple javascript change in Cal.js, see
https://suitecrm.com/forum/developer-help/13406-defining-and-using-different-colors-in-the-calendar-for-different-types-of-entries

but this is not quite possible anymore as someone added a function called "chackActivities" in CalendarDisplay.php which basically renders what I have done impossible.

I have to find new ways - If you know one ...

**Comment by chris001** [comment]
You should create a New Issue with all the explanation above and refer to the place in `CalendarDisplay.php` where it reads the colors from your `config.php` and sets the colors.
https://github.com/salesagility/SuiteCRM/blob/master/modules/Calendar/CalendarDisplay.php#L240

**Comment by jobst** [comment]
@chris001, thx - see https://github.com/salesagility/SuiteCRM/issues/3273.
