### ISSUE TITLE
7.8.2 select all button in Search-Popup (MultiSelect) looks destroyed in Theme Suite7

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3265]
#### Issue

7.8.2 select all button in Search-Popup looks destroyed in Theme Suite7
See attached screenshot
![12-03-_2017_17-49-29](https://cloud.githubusercontent.com/assets/16813374/23833864/7071073a-074c-11e7-9c26-8e4f035ec0f7.png)

**Comment by kdjmonaghan** [comment]
Hi,

I looked into this a little, it seems like the markup for the form is actually just sort of wrong - the input checkbox I assume is supposed to sit above the rest of the individual selects (as most modern forms do) and not inside of the dropdown.

There seems to be a few further changes to make it look nice but see the image below, displaying the original (left side) against a few corrections (right side) I briefly looked into.

I'm not sure if this is also what you'd expect but let me know:

![brokeninput](https://cloud.githubusercontent.com/assets/3587120/23853820/4af7f50a-07e6-11e7-9c46-ad112012310b.png)

**Comment by Lehnerr** [comment]
Hi.

In Suitecrm 7.7.5 it looks good:

It  doesn't overlap to the columes.

regards Robert 

>>> Kieran Monaghan <notifications@github.com> 13.03.2017 13:15 >>>
Hi,
I looked into this a little, it seems like the markup for the form is
actually just sort of wrong - the input checkbox I assume is supposed to
sit above the rest of the individual selects (as most modern forms do)
and not inside of the dropdown.
There seems to be a few further changes to make it look nice but see
the image below, displaying the original (left side) against a few
corrections (right side) I briefly looked into.
I'm not sure if this is also what you'd expect but let me know:
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/salesagility/SuiteCRM/issues/3265#issuecomment-286090768)
, or mute the thread
(

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this in 7.8.x as a core issue. If this issue still exists and you can provide more information for us to proceed then it can be reopened. Thanks.

**Comment by Lehnerr** [comment]
HI.

I've installed now a fresh Suitecrm 7.8.6 system.
I logged in and changed to Theme7
I created an account 1
Then I go to contacts and 2 accounts (Just entering last name)
Then I go back to the account ->subpanel contacts-> select
![grafik](https://user-images.githubusercontent.com/16813374/30905071-12e64f7a-a374-11e7-83c9-8c21d0732374.png)


Problem is still there
Runing on LAMP Ubunto16.04  with latest Firefox on Windows 
regards Robert

**Comment by Dillon-Brown** [comment]
@Lehnerr Confirmed as a core issue. Thanks.

**Comment by sameekshaagrawal** [comment]
hey dillon i am getting same issue that select all button is not working in 7.8.2

**Comment by Mausino** [comment]
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL. Should it be closed.
