### ISSUE TITLE
in File Cal.js in function eventResize "debugger" statement left in code

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3271]
A developer left the "debugger" statement in file Cal.js in function eventResize

#### Issue

There is no more details to provide
A developer left the "debugger" statement in file Cal.js in function eventResize

#### Expected Behavior

The "debugger" statement in file Cal.js in function eventResize should be removed

#### Actual Behavior

The "debugger" statement in file Cal.js in function eventResize is still there

#### Possible Fix

Just remove it

#### Steps to Reproduce

1.open file Cal.js
2.move to function eventResize
3.look at the first line
4.

#### Your Environment

* SuiteCRM Version used:7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):N/A
* Environment name and version (e.g. MySQL, PHP 7):N/A
* Operating System and version (e.g Ubuntu 16.04):N/A

**Comment by samus-aran** [comment]
Line reference:
https://github.com/salesagility/SuiteCRM/blob/master/jssource/src_files/modules/Calendar/Cal.js#L1024
