### ISSUE TITLE
checkActivity() does not properly handle meeting_status_dom

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3273]
Cannot have my own color definition for any entry that exists ONLY in meeting_status_dom due to the changes in file "./modules?Calendar/CalendarDisplay.php", especially in the function "checkActivity()".

It used to be possible to make minor changes to Cal.js (extra 5 lines of code) to have different colors for "Planned", "Held", "Not Held" and other entries defined in meeting_status_dom as well as different color for Meeting/Calls/Tasks etc.

#### Issue

I used to be able to add a few lines to Cal.js to have my own colors defined to make the Calendar more readable (i.e. different colors for different status), see my own question to the developer forum https://suitecrm.com/forum/developer-help/13406-defining-and-using-different-colors-in-the-calendar-for-different-types-of-entries

If you have loads of Meetings (as some of our people have) but no calls the Calendar looks like a sea of blue where different meetings ALL have the same color ... it does not make it easy to read nor distinguish each entry easily.

For my previous SuiteCRM (and SugarCRM) version I defined different meeting statuses (meeting_status_dom), e.g. "Training Planned", "Training Held", "Meeting Internal Planned", "Meeting Internal Held", "Training External",  "Training In House" and more, then used the code as explained in "https://suitecrm.com/forum/developer-help/13406-defining-and-using-different-colors-in-the-calendar-for-different-types-of-entries" and suddenly each persons calendar ESPECIALLY in the share view was so easy to read as different statuses hve different colors.

Now that used to work until the function "checkActivity()" in file  "./modules?Calendar/CalendarDisplay.php" was created which does not look at all at the meeting_status_dom and ONLY lets the entries that are hard-coded in the array "$activityList" in file "./modules?Calendar/Calendar.php" pass - nothing else is let through!

This makes it impossible for ./modules?Calendar/Cal.js" to have access to any other entry other than defined in that array "$activityList" and makes the calendar with loads of meeting entries unreadable.

I, too, upgraded for 7.6.10 to 7.8.2 but my users refused to take the option of all meeting entries to be the same color, so I had to go back. I installed an extra directory with the latest install 7.8.2 and figured out how small changes to the code of 7.8.2 can get back the possibility of have different colors for each item in meeting_status_dom.

#### Expected Behavior

Not really expected ... but yes I would like the old behaviour back that allowed array entries defined in meeting_status_dom to pass!

#### Actual Behavior

Only the four entries defined in in the array "$activityList" in file "./modules?Calendar/Calendar.php" can pass, making it impossible to see extra entries in config_override.php.

#### Possible Fix

I have added 3 text files to this issue (named like the orignal but with .txt ending), each file has my changes ONLY in them.  It is easy to recognize where those code changes should be in the real code.

I only have added them to show for now, if patches are required, I can easily provide them.

The major change in the code is basically how the IF STATEMENT works in the original code 

     if(isset($GLOBALS['app_list_strings']['moduleList'][ $key ]) && !empty($GLOBALS['app_list_strings']['moduleList'][ $key ]) && !empty($this->cal->activityList[ $key ]) )
	 {
	   // only allows the ones defined in $activtyList to go through, nothing else
	 }
	 else
	 
	   // unsets everything else
	 }

and in my code 

     if(!empty($this->cal->activityList[ $key ]))
     {
       // this is in the default activity list
       //pinf("Not skipping, in the original default activity list $key ....");
       if(isset($GLOBALS['app_list_strings']['moduleList'][ $key ]) && !empty($GLOBALS['app_list_strings']['moduleList'][ $key ]) ){
         $activity[ $key ]['label'] = $GLOBALS['app_list_strings']['moduleList'][ $key ];
       }else{
         unset($activity[ $key ]);
       }
     }
     else
	 {
	   // this allows extra definitions to pass
	 }

In my code every extra meeting_status_dom that has a flag set to true (in the config_override.php) is let through and the calendar looks very colorful!

#### Steps to Reproduce

1. Click on any Calendar that has loads of meetings 
2. All meetings have the same color - very ugly.

#### Context

It's more about my users, they were used to different colors for different meeting statuses for a long time.

So I made some changes to the code that was easy to do even after an upgrade of SuiteCRM (SugarCRM) as this involved on a MINOR code change.

The tricky thing now is that a function exists (and in future versions) that does NOT ALLOW other entires defined in meeting_status_dom to go through at all.

If you allow that it is possible to make minor changes to Cal.js to have differen colors for different statuses.

#### Your Environment

* SuiteCRM Version used: 7.8.2 (not working) 7.6.10 (working)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7): N/A
* Operating System and version (e.g Ubuntu 16.04): N/A

[Cal_js.txt](https://github.com/salesagility/SuiteCRM/files/840496/Cal_js.txt)
[CalendarDisplay_php.txt](https://github.com/salesagility/SuiteCRM/files/840497/CalendarDisplay_php.txt)
[config_override_php.txt](https://github.com/salesagility/SuiteCRM/files/840498/config_override_php.txt)

**Comment by chris001** [comment]
If you could, Edit the title of this issue to fix the function name "checkActivity()"

**Comment by samus-aran** [comment]
HI @jobst I've set it as an enahancement.  The checkActivity is to ensure its only modules coming through and doing the old way of allow the colours to be brought in like I don't think is the best (though Sugar demonstrated it) and requires customisation regardless.

If you are willing to provide a solution that would be generic as possible then please create a PR.

**Comment by jobst** [comment]
Actually, the way I coded is it does not require customisation by default, it you do not anything to config_override.php nothing will change and it will still work. The way I do it you change "changeActivity()" a little without killing the check for (existing) modules, then add some code to that to bring the color across if they exist. In Cal.js you check whether the color is defined, if not use the standard ones.
However, one thing for sure - your Calendar is not just a see of (bloody) blue ;-)

**Comment by jobst** [comment]
Hi @samus-aran, I have just created two pull request as 2 file changes are required in:

  1. Cal.js
  2. CalendarDisplay.php

One extra change is needed (the only customisation required for each SuiteCRM install) in file config_override.php for EACH "meeting status dom" that is defined in the drop down editor. As an example I provide the change to the color for the standard "Planned" meeting status:

$sugar_config['CalendarColors']['Planned']['border']="555555";
$sugar_config['CalendarColors']['Planned']['body']  ="D8EFFF";
$sugar_config['CalendarColors']['Planned']['text']  ="000000";

But any "meeting_status_dom" will work, you just need to refer to the "item_name" not "display_name"

I also made sure that it does NOT break checkActivity().

However, there could be extra checks added to Cal.js for added fail checks.
Currently I am only checking for "body" and I imply the existence of all other.
I can fix that once the proposed change for "allow multiple meeting colors" is accepted.

**Comment by jobst** [comment]
Here @samus-aran, 
is an example calendar, we use this with 12 people, no problems.
Even the shared calendar has no performance issues.

![clipboard01](https://cloud.githubusercontent.com/assets/1762694/24486801/9bf4ada8-1557-11e7-94eb-00b2e1e371d8.png)

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [checkActivity() does not properly handle meeting_status_dom](https://trello.com/c/P6iDVkzp/16-checkactivity-does-not-properly-handle-meeting-status-dom)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

(moved into discussion)

**Comment by mzsolnay** [comment]
Hi !

I am a newbee SuiteCRM user, and would like to have the feature, to show completed tasks/meeting in the calendar differently. Preferedably strikethrough style, but dedicated color would be also just fine.

Could this be a standard feature, or do I have to make my own modifications, and if I do so, will it still work after an upgrade?

Thank you for your suggestions an for your help !

**Comment by jankowal-bm** [comment]
Hi !
I would like to know if there is any progres or any changes in the above solution to make the meetings status in calendar colored. 
Thank you in advance.
