### ISSUE TITLE
report CSV - currency

### ISSUE THREAD

**Issue by MAAVOOL** [salesagility/SuiteCRM#3274]
Bug in report export of currency field in CSV

#### Issue
when export report in CSV with filed opportunities/Currency, than you will receive bad result. Report in PDF is OK.

#### Expected Behavior
You will receive only "EUR"

#### Actual Behavior
You will receive:
"EUR
function CurrencyConvertAll() { return; }"

#### Steps to Reproduce
1. Create new report for module Opportunities
2. use filed Currency
3. save report
4. export to CSV

#### Your Environment
* SuiteCRM Version used: Version 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7): MySQL5.5.32, PHP5.5.38

**Comment by ChangezKhan** [comment]
It is working fine for currency `US Dollors: $`.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
