### ISSUE TITLE
No link on Name's contact to show the detailled view

### ISSUE THREAD

**Issue by jcwerck** [salesagility/SuiteCRM#3278]
Since the upgrade to 7.8.0, the link on Name's contact on Contacts list disapear. The only way to access the detailled view of a contact, is to edit it and then save.
#### Issue
Access to the detailled view of a contact is impossible without edit it. If you don't have the right to edit contacts, you cannot see the details.
![capture](https://cloud.githubusercontent.com/assets/25033399/23905580/d2b52ee6-08cb-11e7-9680-073dbede0845.PNG)
#### Expected Behavior
To have a link in the contact's name in the contacts list, like in the previous versions of SuiteCRM. 

#### Actual Behavior
No link on the contact's name. 

#### Possible Fix
Restore the link.

#### Steps to Reproduce
Just go to the contacts list.
#### Your Environment
* SuiteCRM Version used: 7.8.0 / 7.8.2 (the bug appear in both versions)
* Browser name and version Chrome Version 56.0.2924.87 (64-bit)
* Environment name and version : mysql  Ver 15.1 Distrib 5.5.50-MariaDB / PHP 5.4.16

* Operating System and version : CentOS Linux release 7.2.1511 (Core)

**Comment by horus68** [comment]
This is not confirmed in the demo. https://suitecrm.com/demo
Could it be related with MariaDB? Can you test with MySql?
It must be sothing on your upgrades or system environment
Verify logs, file permissions, cleaer instance and browser cache, make a repair and rebuild

![capturar](https://cloud.githubusercontent.com/assets/3055443/23913146/f0d9e6b0-08d9-11e7-8977-0dd99d92d93b.PNG)

**Comment by jcwerck** [comment]
I have found the solution : replacing column "Full name" by "Name" in the Studio !
