### ISSUE TITLE
Language files: DetailView or Detail View?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3281]
#### Issue

I assume `DetailView ` int the language file for ModuleBuilder its no placeholder and it should be in proper english as `Detail View ` (so it gets correctly translated), right?

modules/ModuleBuilder/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/modules/ModuleBuilder/language/en_us.lang.php#L373
`    'LBL_DETAILVIEW' => 'DetailView',`

Also in the same file
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/modules/ModuleBuilder/language/en_us.lang.php#L433
`    'LBL_SYNC_TO_DETAILVIEW' => 'Sync to DetailView',`

Note that the "include" file uses `Detail View` with a space in it.
include/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/include/language/en_us.lang.php#L2057
`    'LBL_DETAILVIEW' => 'Detail View',`

#### Context

Translation issues and consistency

**Comment by samus-aran** [comment]
I believe so horus, but that LBL seems to get used in some strange ways - this will require clarification.
Same applies to LBL_EDITVIEW

**Comment by horus68** [comment]
@Dillon-Brown any news on this?

**Comment by Dillon-Brown** [comment]
@horus68 Doesn't look like there would be any issues from changing these strings.

LBL_EDITVIEW
LBL_DETAILVIEW
LBL_LISTVIEW
LBL_QUICKCREATE
LBL_POPUP

All get used inside studio -> module -> layouts.
