### ISSUE TITLE
AOR Calls module Contact link only displays last_name rather than full name

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3283]
#### Issue

If you display the linked contact in a Calls module report, only the Contact's last name is shown rather than first + last

#### Possible Fix

In /modules/Calls/vardefs.php (SuiteCRM 7.8.2 line 262)
change
        'contact_name' =>
            array(
                'name' => 'contact_name',
                'rname' => 'last_name',
                'db_concat_fields' => array(0 => 'first_name', 1 => 'last_name'),

to
        'contact_name' =>
            array(
                'name' => 'contact_name',
                'rname' => 'name',
                'db_concat_fields' => array(0 => 'first_name', 1 => 'last_name'),

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by samus-aran** [comment]
Thanks @nelem - Are you able to provide a PR for this possible fix and I can label it appropriately?

**Comment by nelem** [comment]
I will gladly but not sure how.

**Comment by nelem** [comment]
Still an annoyance in 7.8.15. Why was it reverted on 16 Sep 17?
