### ISSUE TITLE
Add IP address to Failed Logins message for fail2ban detection

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3285]
#### Issue

Enhancement request: Add the IP address of the source of the failed login so that fail2ban and other log watchers can take appropriate action against that IP.

#### Possible Fix

In modules/Users/authentication/AuthenticationController.php change line 183 (SuiteCRM 7.8.2) to:

$GLOBALS['log']->fatal('FAILED LOGIN:attempts[' .$_SESSION['loginAttempts'] .'] - '. $username . ' from IP: ' . $_SERVER['REMOTE_ADDR']);

#### Context

Enhancement

#### Your Environment

* SuiteCRM Version used: 7.8.2

**Comment by pgorod** [comment]
Duplicate (actually triplicate), see #50 and #653 

Still, a good suggestion and one that would be nice to finally implement after all these years. 

Low development effort --> significant security increase

@nelem would you like to try [doing the Pull Request yourself](https://help.github.com/articles/editing-files-in-another-user-s-repository/)? Don't forget to switch to the hotfix branch before you start editing.

**Comment by chris001** [comment]
PR created #3285.  See also issues #50 and #653.  Thanks all.  Users have waited over 2 years to have this feature which took a very small modification to one line of code!

**Comment by nelem** [comment]
Thanks for doing this. I've never done a pull request and you've beaten me to it.
