### ISSUE TITLE
How to create N level hierarchy in SuiteCRM?

### ISSUE THREAD

**Issue by Vinothbsetec** [salesagility/SuiteCRM#3298]
#### Issue
We have a organization with 7 level hierarchy of team. Now we are implementing SuiteCRM for our organization. We tried to create the team structure with roles and security groups management. But we can create up to only 3 level. Is there any way to create more levels in SuiteCRM security groups and roles?
Also we can't find how to change a person's membership as Non-inheritable. I can change it when create are edit a group. How to change a person's membership as Non-inheritable?
* SuiteCRM Version used: 7.7.9

**Comment by pgorod** [comment]
@Vinothbsetec this site is for developers to report bugs and contribute fixes for SuiteCRM. 

The kind of question you're asking is more suitable to the forums:
https://suitecrm.com/forum/

So if it's alright with you, I'd say you should ask there, and close the issue here, please. Thanks!
