### ISSUE TITLE
Module builder and adding relationship fails in PHP 7.1

### ISSUE THREAD

**Issue by craigpanton** [salesagility/SuiteCRM#3299]
#### Issue

When trying to save and deploy a new relationship via Studio, I receive a stack trace error and it does not create the new relationship. I receive a similar output when trying to deploy a new module via module builder.

#### Expected Behavior

It is expected to deploy the relationship/module to the local instance of SuiteCRM.
#### Actual Behavior

It was failing to create the relationship. In the case of the module builder it hangs on the deployment screen.
#### Possible Fix

The error itself is due to the DeployedRelationships and UndeployedRelationship build function missing expected parameters (the line for the relationship bug is on modules/ModuleBuilder/Controller.php 580). 
It looks like it may be due to error handling within php version 7.1 as when I try in 5.6 it throws the same errors however continues on and works as expected.

#### Steps to Reproduce

1. Go to studio
2. Select a module
3. Select 'Relationships'
4. Select 'Add Relationship'
5. Provide any details
6. Select 'Save & Deploy'

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome/Firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1.2, MySQL 5.6.35 
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by gregecslo** [comment]
Same here but with PHP 7.1.3x64 and MS SQL 2014.
Going to PHP 7.0.17 resolves the issue for me.

Full stack trace for deploy operation: 

[28-Mar-2017 09:57:00 Europe/Ljubljana] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function UndeployedRelationships::build(), 1 passed in \modules\ModuleBuilder\MB\MBModule.php on line 429 and exactly 3 expected in \modules\ModuleBuilder\parsers\relationships\UndeployedRelationships.php:228
Stack trace:
#0 \modules\ModuleBuilder\MB\MBModule.php(429): UndeployedRelationships->build('custom\\modulebu...')
#1 \modules\ModuleBuilder\MB\MBPackage.php(213): MBModule->build('custom\\modulebu...')
#2 \modules\ModuleBuilder\MB\MBPackage.php(315): MBPackage->buildInstall('custom\\modulebu...')
#3 \modules\ModuleBuilder\controller.php(237): MBPackage->build(false)
#4 \include\MVC\Controller\SugarController.php(446): ModuleBuilderController->action_DeployPackage()
#5 \include\MVC\Controller\SugarController.php(419): SugarController->do_action()
#6 \include\MVC\Controller\SugarController.php(394): SugarC in \modules\ModuleBuilder\parsers\relationships\UndeployedRelationships.php on line 228

**Comment by gregecslo** [comment]
Whoops not true...
7.0.17 does deploy it, but when you enter data in deployed module WSOD happens.
Switched to PHP 5.6.30, redeployed same module, quick repair and now it works.

So SuiteCRM is not compatible with PHP 7.X at least custom modules are not.

**Comment by craigpanton** [comment]
It looks like argument count for user defined functions was upgraded from a warning to an error with PHP7.1 as per http://php.net/manual/en/migration71.incompatible.php. The only obvious solution I've found to that so far is to pass null parameters over for those functions.

**Comment by Dillon-Brown** [comment]
@craigpanton @gregecslo I've put up a PR for this issue. Let me know if this solves it on your end :).
