### ISSUE TITLE
Cannot Add New Tab on Home Page

### ISSUE THREAD

**Issue by nickbyfleet** [salesagility/SuiteCRM#33]
Hi,

I think there might be a problem with the add tab functionality. I am getting the following error in my PHP log file when I try to add a tab:

[Mon Apr 14 06:22:19 2014] [error] [client 124.150.160.81] PHP Notice:  Undefined variable: pages in /var/www/html/custom/modules/Home/AddDashboardPages.php on line 85, referer: http://crm.absolutevalue.co.nz/index.php

I will continue to search for a solution, but perhaps you could look into it.

Cheers,
NB

**Comment by divyarai** [comment]
hello 
i want to add new tab in leads page in suitecrm 
for show the dead lead and junk lead seperatly
please help me as soon as possible

Thanks & Regards
Divya Rai
