### ISSUE TITLE
Can't select in target list, with and without filter

### ISSUE THREAD

**Issue by matteoraggi** [salesagility/SuiteCRM#3302]
Suitecrm 7.8.2 error tested on all php versions: 5.3 5.4 5.5 5.6 7.0
This issue is similar and giving the same error of this other 2 issues:
https://github.com/salesagility/SuiteCRM/issues/3068
https://github.com/salesagility/SuiteCRM/issues/2557

Everytime I try to add new leads to a target list:
1) if I select all the leads (more of 1000) nothing happen and no error is received.
2) If I select few leads in the first page or all the first page generally it works
3) If I select a filtered list of leads in a multipagee, for example 100 leads, then I receive this error:
"Bad data passed in; Return to Home"

Here you can find log errors:
https://suitecrm.com/forum/suitecrm-7-0-discussion/13531-bad-data-passed-in-return-to-home-when-seleting-multipage-leads-to-add-in-the-target-list#45457

Without this step I can't populate the target lists with leads to send emails to the leads, I am loosing one of the main functions of suitecrm.
The same function is not working also in the softaculous demo:
https://www.softaculous.com/softaculous/demos/SuiteCRM

I will try to exaplain this trouble better creating a video.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by matteoraggi** [comment]
Here the description videos:
selecting 20 leads is ok:
https://www.eforte.eu/select_20_leads.mp4

selecting 114 leads give error:
https://www.eforte.eu/select_114leads.mp4

selecting all leads, nothing happen:
https://www.eforte.eu/select_all_leads.mp4

if selecting steps of 20leads/1page, then it looks to work, but at the end of the 6 steps it select 94 leads instead of 114...
Here an example .csv file with some leads to import for the tests:
https://www.eforte.eu/leads.csv

**Comment by matteoraggi** [comment]
The same trouble of the leads is happening also with the Targets (tested from me).

**Comment by pgorod** [comment]
Can you please paste here that error that you found in the logs, that you pasted in [the forum thread](https://suitecrm.com/forum/suitecrm-7-0-discussion/13531-bad-data-passed-in-return-to-home-when-seleting-multipage-leads-to-add-in-the-target-list)? That is a good clue. 

And then @horus68 can help us find out where that Italian license code might be coming from? I have my SuiteCRM localized in Portuguese and I don't see license texts in Portuguese in my PHP files...

**Comment by matteoraggi** [comment]
Here is a log:

> Thu Mar 23 12:33:00 2017 [126654][1][FATAL]  Query Failed: DESCRIBE versions: MySQL error 1146: Table 'vendiamo_clienti.versions' doesn't exist
Thu Mar 23 12:33:00 2017 [126654][1][FATAL]  Query Failed: SHOW INDEX FROM versions: MySQL error 1146: Table 'vendiamo_clienti.versions' doesn't exist
Thu Mar 23 12:33:00 2017 [126654][1][FATAL]  Query Failed: select * from versions: MySQL error 1146: Table 'vendiamo_clienti.versions' doesn't exist
Thu Mar 23 13:30:56 2017 [194283][-none-][FATAL] Slow Query (time:0.10403490066528
SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1
Thu Mar 23 13:56:06 2017 [226027][1][FATAL] Slow Query (time:0.24895405769348
 SELECT  leads.id , LTRIM(RTRIM(CONCAT(IFNULL(leads.first_name,''),' ',IFNULL(leads.last_name,'')))) as name, leads.first_name , leads.last_name , leads.salutation , leads.title , leads.phone_work , leads.assigned_user_id  ,leads.account_name FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  where ((leads.assigned_user_id = '1')) AND leads.deleted=0 ORDER BY leads.date_entered DESC LIMIT 0,6
Thu Mar 23 16:09:25 2017 [411687][1][FATAL] Slow Query (time:0.11074185371399
 SELECT  leads.id , LTRIM(RTRIM(CONCAT(IFNULL(leads.first_name,''),' ',IFNULL(leads.last_name,'')))) as name, leads.first_name , leads.last_name , leads.salutation , leads.title , leads.phone_work , leads.assigned_user_id  ,leads.account_name FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  where ((leads.assigned_user_id = '1')) AND leads.deleted=0 ORDER BY leads.date_entered DESC LIMIT 0,6
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: stat(): stat failed for upload/import/error_1.csv
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: stat(): stat failed for upload/import/errorrecords_1.csv
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: stat(): stat failed for upload/import/errorrecordsonly_1.csv
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: stat(): stat failed for upload/import/status_1.csv
Thu Mar 23 16:13:18 2017 [416558][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Mar 23 17:09:35 2017 [499046][1][FATAL] Slow Query (time:0.1168429851532
ALTER TABLE prospects_cstm add COLUMN tipo_di_clienti_c varchar(100)  NULL 
Thu Mar 23 17:18:19 2017 [512633][1][FATAL] Caught error: stat(): stat failed for upload/import/status_1.csv
Thu Mar 23 17:18:19 2017 [512633][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Mar 23 19:50:36 2017 [747863][1][FATAL] Slow Query (time:0.11017513275146
 SELECT  leads.id , LTRIM(RTRIM(CONCAT(IFNULL(leads.first_name,''),' ',IFNULL(leads.last_name,'')))) as name, leads.first_name , leads.last_name , leads.salutation , leads.title , leads.phone_work , leads.assigned_user_id  ,leads.account_name FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  where ((leads.assigned_user_id = '1')) AND leads.deleted=0 ORDER BY leads.date_entered DESC LIMIT 0,6

**Comment by matteoraggi** [comment]
Thsi is the suspicious error log, does it helps?

> [16-Mar-2017 20:56:10 Europe/Rome] PHP Fatal error:  Smarty error: [in cache/themes/SuiteP/modules/Leads/EditView.tpl line 344]: syntax error: unrecognized tag: *
/*********************************************************************************
* SugarCRM Community Edition &egrave; un programma CRM (Gestione Relazioni con i Clienti)
* sviluppato da SugarCRM, Inc. Copyright (C) 2004-2016 SugarCRM Inc.
* SuiteCRM &egrave; una estensione di SugarCRM Community Edition sviluppata da Salesagility Ltd.
* Copyright (C) 2011 - 2016 Salesagility Ltd.
*
* Questo programma &egrave; un software gratuito; Potete distribuirlo e/o modificarlo sottostando
* ai termini della licenza GNU Affero General Public License version 3 come pubblicato dalla
* &quot;Free Software Foundation&quot; con l'aggiunta dek seguente permesso aggiunto alla
* Sezione 15 e come permesso nella Sezione 7(a): PER QUALSIASI PARTE DEL LAVORO COPERTO
* DAL COPYRIGHT DI SUGARCRM, SUGARCRM NON RICONOSCE LA GARANZIA DI NON VIOLAZIONE 
* DEI DIRITTI DI TERZE PARTI.
*
* Questo programma &egrave; distribuito nel in SUITECRM/clientis/include/Smarty/Smarty.class.php on line 1094

**Comment by pgorod** [comment]
I noticed one of the similar issues you linked provides a fix:
https://github.com/imtg-suitecrm/SuiteCRM/commit/162236fcb53465d85100eee35d8683170aee790e

Can you test that change on your system and see if it solves the problem?

**Comment by matteoraggi** [comment]
Thanks for the patch! I tryed on chrome, but it was still in cache the old file so it was not working, then from Opera browser instead it worked like a charm! I selected more of 1600 leads in few seconds, great!

**Comment by horus68** [comment]
> And then @horus68 can help us find out where that Italian license code might be coming from?
I don't see where is it coming from. 
@matteoraggi do you use the italian translation created by devila.net or the one from Crowdin Managed by me)  https://crowdin.com/project/suitecrmtranslations ?

Side note: direct link to PR already referred above
https://github.com/salesagility/SuiteCRM/pull/3280

**Comment by matteoraggi** [comment]
I am using the italian translation coming from  https://crowdin.com/project/suitecrmtranslations

**Comment by pgorod** [comment]
The label seems to be `LBL_VIEWLICENSE_COM` which is not being used anywhere. It's included in one of the PR that deletes unused language strings, one that hasn't been merged yet.

Since the issue is solved, I would just ignore this, eventually the string will be removed.

**Comment by horus68** [comment]
confirmed the issue on the translation for Italian on that string, now cleared.
@matteoraggi hope you can find the time to improve the Italian translation on Crowdin!
