### ISSUE TITLE
Spots broken on MySql needs UNION ALL

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3304]
#### Issue

Spots uses a UNION to select the calls, meetings and task data for the pivot table. MySQL requires UNION ALL in order not to delete duplicate rows.

#### Expected Behavior

The 'duplicate' rows are required for the counts.

#### Actual Behavior

All counts are 1.
#### Possible Fix

In modules/Spots/controller.php function action_createActivitiesSpotsData 
replace UNION with UNION ALL when constructing the $mysqlQuery. I believe the MSSQL syntax also requires UNION ALL.

#### Steps to Reproduce

1. Create a pivot table on Activities.
2. Even when there are multiple Calls in each state only one of each state (Planned, Held, Not Held) the count is 1 for each state.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.2

**Comment by nelem** [comment]
#3305 Pull request. Hopefully done tight this time.

**Comment by Dillon-Brown** [comment]
@nelem I am to be unable to replicate this issue. Do you think you could clarify further or provide screenshots?

The calls, meetings and task data seem to be getting counted correctly here:
![issue-counts1](https://cloud.githubusercontent.com/assets/26431166/24911571/4d8fd42e-1ec3-11e7-9c5a-a5f620126d5c.png)

**Comment by chris001** [comment]
These MySQL and MSSQL syntax error bugs would be fixed and never happen again, once someone takes the time to upgrade the data layer to use PDO.

**Comment by nelem** [comment]
Are you sure the counts are correct?
Without UNION ALL
![spots_nounionall](https://cloud.githubusercontent.com/assets/12173666/24953152/2cf2cb40-1f72-11e7-892b-5e3435deff3b.png)

With UNION ALL
![spots_unionall](https://cloud.githubusercontent.com/assets/12173666/24953153/2cf391ba-1f72-11e7-8f39-2cb85949b41d.png)

?

**Comment by nelem** [comment]
Also, whilst I'm here, Spots always ask if I want to save when navigating away from a report.

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.
