### ISSUE TITLE
Log phone call - reminders keep coming back..

### ISSUE THREAD

**Issue by fischeh** [salesagility/SuiteCRM#3308]
#### Issue

I want to log a phone call which has been held (it's over, not upcoming)
I open the full form
I delete the reminders ((1) they shouldn't really be there as it has been held)
I enter the description of the call
(At this point, it would be nice to have some sort of 'Action Points' log,)
I save the form
I notice, that some parts of the description need to be revised
I click on edit
And there is the reminder again!!! (2)

#### Expected Behavior
1.) Reminder field should not appear in the first instance
2.) Reminder should not appear again once deleted and saved
#### Actual Behavior
Reminders are there.

#### Steps to Reproduce

1.see above
2.
3.
4.

#### Context
The problem is if reminders keep popping up, I am worried to send an accidental email to a client with the confidential description of the call attached. 
As such, I consider this a medium priority.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version: (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest Safari
* Environment name and version (e.g. MySQL, PHP 7): AWS, MySQL, Apache
* Operating System and version (e.g Ubuntu 16.04): latest AWS debian derivative on the server side, mac OS 10.12.3 client side.

**Comment by Dillon-Brown** [comment]
Hi @fischeh

Just to confirm that you find that if the Call is set to 'Held' then the reminders section should be empty unless there was already existing reminders set?
Would this also apply to 'Not Held'?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
