### ISSUE TITLE
Should i stop adding pull requests?

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#331]
Did some pull requests, no reaction from the suite team ... disappointing.

**Comment by mattlorimer** [comment]
It up to you but pulling in pull requests is not hat simple, we need to understand and validate it, we are working to get a dedicated resource on this so we can speed things up, but at the moment it may take a little longer for them to be integrated.

**Comment by gunnicom** [comment]
Well, but at least a reaction for months old request would be fine.

**Comment by willrennie** [comment]
Pull requests are monitored and are pulled into the project if they meet the code standard requirements. As Matt highlighted, we will be improving on the time dedicated to analysing and engaging with community contributions.
