### ISSUE TITLE
Print Calendar button

### ISSUE THREAD

**Issue by griffrog** [salesagility/SuiteCRM#3311]
Printing the calendar results in a messy page that includes nothing useful about the calendar entries.  Using the "Print" button is no different than using Ctrl+P.

If I print a day from the calendar I expect to see the details of each entry for that day, not just the blob with the title & time, amid lines of code, breadcrumbs, and other page graphics.

1. Open the Calendar module.
2. Select a date.
3. Ctrl+P (or press the print button if not using Suite P theme)
4. Scratch head.

* SuiteCRM Version 7.8.1
* Linux server.localhost.com 3.2.0-4-amd64 #1 SMP Debian 3.2.84-1 x86_64
* PHP Version 5.4.45-0+deb7u6
* MySQL Version 5.5.53 
* Browser: Firefox 64-bit on Windows 7 Professional 64-bit

**Comment by samus-aran** [comment]
Hi @griffrog - What details are you expecting to see on each entry?  Would it be similar to the tooltip additional details you get on the calendar itself?

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Print Calendar button](https://trello.com/c/c9Cvprlo/13-print-calendar-button)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by griffrog** [comment]
Details?  You want me to elaborate on the details of a calendar entry in SuiteCRM?

All of the details.  We both know what the calendar of a default SuiteCRM instance allows to be entered into an event.  Those are the details that should print when printing a day's from the calendar.  I'm not sure what else you could be asking of me here.
