### ISSUE TITLE
Click tracker is truncating the urls after the 30th character

### ISSUE THREAD

**Issue by matteoraggi** [salesagility/SuiteCRM#3316]
When I insert the click tracker, it alwasy truncate my urls (it was happening in sugarcrm 6.5.24 too), for example:
https://www.eforte.it/digital-signage-facile/
then transformed into a click tracking it became:
www.eforte.it/digital-signage- 
The problem is that also the text version is goign to get the same wrong urls, transfoming good urls into bad not working urls too...

second example:
https://www.eforte.it/prodotto/video-poster-2/
then beecame:
www.eforte.it/prodotto/video-p 

A quick patch would be to change the max value of 30 characters to a bigger number or permit to the admin to change that value by itself, freely from the admin area.

**Comment by chris001** [comment]
When you do these steps does it still have that bug:
https://web.sugarcrm.com/support/issues/950e6d6c-9f43-c5ee-b7b6-53a17d23d5cd
1. Create a new Campaign, entering the required field data.
2. Select a Target List, preferably a Default type list, to relate to the Campaign.
3. Create a Tracker-URL, that is not an Opt-out, using something like http://www.sugarcrm.com/ as the URL.
4. Once the Tracker-URL is saved, and you return to the Campaign DetailView, click on the Tracker-URL name to open its DetailView.
5. Copy the URL from your browser's address bar for the Tracker-URL.
6. Create an Email Marketing message entering the required information, clicking Create next to Email Template.
7. Add your Tracker-URL to the body of the email, then click the HTML button in the TinyMCE editor. Select the text in the href=" " and replace it with the address you copied earlier.
8. Save your new Email Template to return to the Email Marketing EditView. Finish entering any required information and save the Email Marketing message to return to the Campaign DetailView.
9. In the Tracker URL subpanel, click on your Tracker URL name to open it in DetailView.
10. Click on your link to activate the redirect.
11. Return to the Campaign DetailView, then click the View Status button.

Expected Results - The Campaign has not been sent, therefore none of the subpanels will be populated.

Actual Results - Clicking the link counts as a Click-Thru Link, it is captured as a Prospect entry, and contains no information, such as Recipient Name and Email Address.

**Comment by matteoraggi** [comment]
Thanks for the detailed answer... but what do you mean? That following your steps I can skip the 30 chars limit or what? I already know that by hand I can override that limit of 30 chars, it just make me to loosetime everytime I want to send an email, adding the possibility of some human errors.

**Comment by chris001** [comment]
You should post a step by step to each step required to reproduce the 30 character limit you're experiencing.

**Comment by matteoraggi** [comment]
Ok, bu I already get the 30 character limit, why reproduce it again? Which is the advantage of that action?

**Comment by chris001** [comment]
If you could spell out step by step exactly which steps in which order are needed to reproduce the bug.

**Comment by gody01** [comment]
I can confirm this bug.
Steps to reproduce:

1. Create Email Template
2. Create Campaign
3. Select Template
4. Create Tracker with more than 30 character in description
5. Save Campaign
6. Go to Next step
7. Return to Template selection

You will see, that now tracker is truncted to 30 characters.
