### ISSUE TITLE
Quick Create dropdown menu button opens on hovering rather than clicking

### ISSUE THREAD

**Issue by ChangezKhan** [salesagility/SuiteCRM#3317]
Quick Create dropdown menu button opens on hovering rather than clicking

#### Issue
When you try to create a new account, lead or contact using quick create button available on top bar, it shows dropdown options when you hover on the button.

![Quick Create Button on Top Bar](https://raw.githubusercontent.com/ChangezKhan/CRM/master/quick_create.jpg)

#### Expected Behavior
On clicking `Create` button available on top bar, dropdown menu should be visible.

#### Actual Behavior
On hovering `Create` button available on top bar, dropdown menu is shown.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome: 56.0.2924.87, Firefox: 52.0.1
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.4, MSSQL Express Edition 2008
* Operating System and version (e.g Ubuntu 16.04): Windows 7

**Comment by samus-aran** [comment]
Hi @ChangezKhan The ability to view the dropdown of the Quick Create menu on hover is keeping inline with the other Menu actions (main).  There is no need to click on the button similar to the other Menu actions.
So I will state this as invalid.
