### ISSUE TITLE
In Role Management, access headers are also toggling and shows in dropdown

### ISSUE THREAD

**Issue by ChangezKhan** [salesagility/SuiteCRM#3318]
#### Issue
In Role Management, if you click on access headers like 'Edit', 'Delete' or any, you'll get to see the dropdown menu with options like 'None', 'Not Set', etc.

![Role Management access headers issue](https://raw.githubusercontent.com/ChangezKhan/CRM/master/issue_1.jpg)

#### Expected Behavior
In Role management, access headers should not be clickable.

#### Actual Behavior
In Role Management, access header are clickable and shows dropdown options like 'None', 'Not Set', etc.

#### Steps to Reproduce

1. Go to Admin section.
2. Click on Role Management module.
3. Create a new role record if not present.
4. Click on any headers like, 'Edit', 'Delete', etc.

#### Context

It should be on low priority.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome: 56.0.2924.87, Firefox: 52.0.1
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.4, MSSQL Express Edition 2008
* Operating System and version (e.g Ubuntu 16.04): Windows 7

**Comment by pgorod** [comment]
I don't think this is a bug, it's a feature.

It's a quick way to change the entire column with a single selection. Very handy.

**Comment by ChangezKhan** [comment]
@pgorod , ohhh yeah, I got it. I thought it is a bug. I didn't know about this feature. Thanks.
