### ISSUE TITLE
 7.3 Beta 2 - new entry on case update threaded 

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#332]
When i post an update, i get the message box  "Performing task -> one moment please", this message wont disappear unless you close it manually or just refresh.  

tested with Firefox, chrome 
 
![schermafdruk van 2015-08-04 19 56 28](https://cloud.githubusercontent.com/assets/1594411/9068336/340b3fe0-3ae3-11e5-9cfe-28d9c0632912.png)

**Comment by ghermans** [comment]
issue has been fixed after restarting Apache.

**Comment by willrennie** [comment]
We should apply a fix for this, as an apache restart shouldn't be required.

**Comment by ghermans** [comment]
Thanks for investigating this @willrennie
