### ISSUE TITLE
Feature to override favicon "sugar_icon.ico"

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3324]
like the company logo, user should be able to upload an image for favicon and override it easily

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature to override favicon "sugar_icon.ico"](https://trello.com/c/zk1okQAh/10-feature-to-override-favicon-sugar-icon-ico)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
