### ISSUE TITLE
PDO should be used

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3325]
[http://php.net/manual/en/mysqlinfo.api.choosing.php](http://php.net/manual/en/mysqlinfo.api.choosing.php)

**Comment by chris001** [comment]
Agreed, but better is to use DBAL which provides a thin wrapper over PDO plus valuable features to make the code cleaner and easier to work with:
1. transactional mode which cleanly commit/rollback transaction for you (ugly code copy/pasted everywhere in regular PDO), 
2. transaction nesting (ugly in PDO you have to manually use save points), 
3. types conversion (very handy with dates), 
4. list of parameters conversion (ugly when using only PDO directly).
5. The list goes on.....

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDO should be used](https://trello.com/c/XCUwvBuJ/9-pdo-should-be-used)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by horus68** [comment]
@samus-aran I really don't like Trello (I did used it intensively some years ago on another project and it looks the same, with same problems. But that's me! 
Even if I don't think it is good for suggestions I understand that you need to clean up issues and improve the project ratings on github. 
I will be there too!

**Comment by samus-aran** [comment]
@horus68 
You want to jump onto the forums and we can discuss your issues with the platform in depth :+1:
