### ISSUE TITLE
Quick create dropdown does not respect roles/permissions

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#3327]
The quick create dropdown on the top toolbar lists create links to modules even if user does not have access to those modules.

#### Expected Behavior
only list modules to which user has 'modify' access.

#### Steps to Reproduce
1. Log in with a non admin user(userX) for which you can change permissions
2. select a module from dropdown, like: Documents
3. with administrator negate access to the module for userX
4. logout and re-login with userX and check quick create dropdown (create link is still there)

#### Your Environment
it's been there ever

##### Enhancement idea: 
provide configuration to personalize dropdown list and order

**Comment by sergio91pt** [comment]
Duplicate of #978

**Comment by adamjakab** [comment]
Agreed, duplicate of #978. Closing.
