### ISSUE TITLE
Selected Records for Mass Update in ListView are no Longer Maintained

### ISSUE THREAD

**Issue by khan01** [salesagility/SuiteCRM#3330]
#### Issue

On any module list view, Selecting Records by "Select this Page" dropdown or individually from their respective check-boxes, when we click on the Next Page, previous selections are lost. This feature existed as a core functionality and is very useful for filtering records for Mass Updates. Now only 20 or less records can be mass updated individuality and selection needs to be done each page. Increasing the number of records on List view would not be a best solution as that also increases loading time. 

#### Expected Behavior

Values selected in list view after clicking on pagination for next/previous page should be maintained. 

#### Actual Behavior

Values are no longer maintained and Selected shows 0

#### Steps to Reproduce

1. Go to List View of Account (or any other module)
2. In list view select some records by clicking on their check boxes shown as first column. You will get a count of records in Pagination Action as "Selected 20" or the number of records you selected.
3. Now navigate to next/previous page on list view. 
4. The Count and the Selected Records are no longer available. 

#### Context

This feature is need for mass updates and really doing filteration of records are users can go to different pages to pick up records on which they intend to perform a mass update function. Sometimes crietrias are not that good to exactly filter and needs hand picking. 

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome Version 56.0.2924.87 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.17 PHP 5.5.12
* Operating System and version (e.g Ubuntu 16.04): Windows 7 64-Bit

**Comment by Referro** [comment]
Could this issue please be given a higher priority? We use this functionality on a daily basis (we were used to use SugarCRM, where it is working perfectly), and it's really frustrating it's not working anymore.
Thanks!

**Comment by Kevconry** [comment]
Can't replicate in 7.13.1, please re-raise or get in touch if you are still having this issue
