### ISSUE TITLE
Hover variables in Suite P theme variables.scss

### ISSUE THREAD

**Issue by angromcas** [salesagility/SuiteCRM#3334]
#### Issue

I noticed that there is no config variables for setup hover of  for quickcreatebutton and action tab.
#### Expected Behavior

I need to change hover color of quick create button and hover color of action tab li in order to fit theme SuiteP to another company colors.
#### Actual Behavior

Quickcreatebutton:hover color is setup to the same color.
Action tab dropdown li: hover background is setup to action tab dropdown background
#### Possible Fix

Add variables to variables.scss and use them in tabs.scss and navbar.scss
![image](https://cloud.githubusercontent.com/assets/26764821/24452312/f322f650-1482-11e7-99e0-0008bbb47198.png)
#### Your Environment

* SuiteCRM Version used: 7.8
* Browser name and version: Chrome Version 51.0.2704.63 (64-bit)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Ubuntu 16.04

**Comment by daniel-samson** [comment]
I think this may be related my pr #3199
