### ISSUE TITLE
Dynamic/custom autoincrement field gets invalid value on new records due to bug in SugarFieldAutoincrement which fails to find the last sequence number used

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3335]
The aim of SugarFieldAutoincrement is to create a reference code with a prefix, date, sequence number and suffix. Example default format is:

`{TESTCO}{-}{y}{-}{0000}{-}{ACCOUNT}`

#### Issue
It keeps generating the same sequence number

#### Expected Behavior
It should increment the sequence number and use it

#### Actual Behavior
It does not increment

#### Possible Fix
- Dynamically adapt the SQL query which is hard-coded and relying on 4 characters on the right

`select [field-name]
from [module-name]_cstm
where ([field-name] <> '' or [field-name] is not null)
order by right([field-name], 4) desc
limit 1`

- Instead of relying on the records and scanning a custom module table, the sequence numbers can be kept in a simple table like settings table as key/value pairs. We can read that value, use it in custom module record, save the record, increment it and update setting record for the sequence number. I do not recommend native database sequences which may not be implemented in some database management systems.

#### Steps to Reproduce
1. Admin ==> Studio ==> choose a module e.g. Accounts
2. Fields editor
3. Add new field, data type: AutoIncrement, Format: leave default value like above example
4. Save
5. Go to layout editor for list view
6. Drag and drop the new field so that users can see it in accounts list
7. Create at least 3 accounts
8. Go to accounts list to see the reference codes generated
9. Some/all are same

**Comment by chris001** [comment]
Excellent find.  To fix the bug you'll want to look at why the function responsible for generating the field doesn't increment the sequence number, here's the code:
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/DynamicFields/templates/Fields/TemplateInt.php

Have a look at `TemplateInt::save($df)`.  I suspect the AutoIncrement `SugarField` type fails to increment because, `SugarField` treats this autoincrement field type as a special case of integer field, and the logic depends on comparison operators which fail to work as expected.

_**You should make a phpunit test file to detect the occurrence of this bug, so that when fixed, the bug won't be able to regress without warning.**_

**Comment by muratyaman** [comment]
Thank you, Chris.

(I am new to this system) I cannot see how those two classes are related esp. because this "special" autoincrement field is a text field.

I think the main issue is with the way the record/field is retrieved from the database before any comparison or pattern matching.

e.g.
Save op. 1. TESTCO-17-0001-ACCOUNT
Save op. 2. TESTCO-17-0002-ACCOUNT
Save op. 3. TESTCO-17-0002-ACCOUNT
Save op. 4. TESTCO-17-0002-ACCOUNT
Save op. 5. TESTCO-17-0003-ACCOUNT
Save op. 6. TESTCO-17-0003-ACCOUNT
Save op. 7. TESTCO-17-0003-ACCOUNT

Because the SQL command  (I've found in the debug log file)
cannot guarantee the retrieval of the last record we inserted:

`
select ref_code_c
from accounts_cstm
where (ref_code_c <> '' or ref_code_c is not null)
order by right(ref_code_c, 4) desc
limit 1
`

because right(ref_code_c, 4) is 'OUNT' for all records.

Next issue could be the pattern match around these lines of SugarFieldAutoincrement::save():

`
if ( $initializeCode ) {
   ***
} else {
    preg_match($pattern, $last_code, $ai_matches);
    ***
}
`

because the system does not prevent user to define a format like:

`{TESTCO}{-}{y}{-}{0000}{-}{ACCOUNT}`

and a starting number like 123456; they have different number of digits.

I can submit that bug separately but let me try to fix this function anyway.

**Comment by muratyaman** [comment]
apparently, SugarFieldAutoincrement class is a "custom" module file, not in this codebase :(
the fix is changing the order-by clause of the SQL command;
I've verified it.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDO should be used](https://trello.com/c/XCUwvBuJ/9-pdo-should-be-used)

**Comment by kvvaradha** [comment]
Is there any solution for this auto increment?.

I wanted to use it for account number
