### ISSUE TITLE
Calendar shows blank even after having the required permissions

### ISSUE THREAD

**Issue by Sid6555** [salesagility/SuiteCRM#334]
I have checked the permissions of the entire instance. All seem to have the required permissions, but both the dashlet and the module are showing blank. Also after this issue showed up I have manually recreated the cache folder with the required permissions but still the calendar is showing blank.

**Comment by Sid6555** [comment]
Any solution to this issue.

**Comment by Sid6555** [comment]
Another thing which I have found out is that the calendar module displays the calendar if there are no calls or meetings logged for that particular week. If any week contains any call or meeting the calendar does not show.

**Comment by willrennie** [comment]
Calendar works out of the box. Do you have any errors in your browser console log or in your sugarcrm.log/suitecrm.log? Have you run a Quick Repair & Rebuild in Admin -> Repair and cleared your browser cache?

**Comment by Sid6555** [comment]
I did run a quick repair and rebuild in the admin panel as well as cleared the browser cache but still no change. As far as the browser console log is concerned I did not find anything which could lead to the issue. I am attaching the browser console log for your kind perusal. I have uploaded two images, one is what the browser console showed when the page was refreshed and one is when only the calendar dashlet was refresh. On both occasions I had cleared the browser console before performing the operations.
![browser_console_on_page_refresh](https://cloud.githubusercontent.com/assets/5636954/9349209/22c4cc8c-4660-11e5-99ce-9b17e751f778.png)
![browser_console_on_calendar_refresh](https://cloud.githubusercontent.com/assets/5636954/9349214/3370c252-4660-11e5-828d-403a0eabfb46.png)

**Comment by Sid6555** [comment]
Hello,

Any solution guys. Was the above information helpful or you need more information. We have this issue on our demo instance so need to sort it out early. Please help.

**Comment by willrennie** [comment]
Which version of SuiteCRM are you running?

**Comment by Sid6555** [comment]
Hello,

I am running 7.1.5.

**Comment by mattlorimer** [comment]
Please ask any questions on the the [support forum](https://suitecrm.com/forum/index)
