### ISSUE TITLE
Search selector in Emails 7.8.3

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3341]
#### Issue

![2017-03-30_2211](https://cloud.githubusercontent.com/assets/5773777/24524717/eef1ec10-1597-11e7-8437-fc5ab4fe21b9.png)

1. Spec. characters in FROM column in email shows wrong, but in TO columns it's working without issue
2. Search issue of selectors (more in screenshot from official demo https://www.screencast.com/t/P7yKdn6zu)

#### Steps to Reproduce

1. Email detailvie
2. Search box for emails
3. Click "More" in search box
 
#### Your Environment

* SuiteCRM Version used: Official SuiteCRM demo 7.8.2
* Browser name and version: Chrome 54.x
* Operating System and version: Win 10 home

**Comment by Dillon-Brown** [comment]
@Mausino Hi, do you think you could rename this issue to just search selector and create a second issue for spec. characters in column FROM?. That way we can keep both of these issues separate. It would also be of great help if you could include the special characters that are being displayed wrong in your second issue. Thanks.

**Comment by Mausino** [comment]
@Dillon-Brown i changed the name of issue + i reported new issue for spec. characters, because this issue persist also in Emails version 7.9  #3626

**Comment by Mausino** [comment]
@Dillon-Brown  i see that both part solution for LTS version 7.8+ are available

plull request #3402 First part - Open status - waiting for merge
pull request #4980 Second part - need to duplicate for LTS version (merged for hotfilx branch)

First and Second parts was tested by community and theire are working fine.

**Comment by Mausino** [comment]
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL.  I closed it now :) because it is my issue ticket 👍
