### ISSUE TITLE
Requesting copyright revision on all language files

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3346]
#### Issue

Almost all language files require:

- Copyright revision 
- if statement for the valid entry point place and format
- License text comments

Code files are already getting those changes when edited. Languages need to be done in a single move so it can be synchronized with the translation pack creation.
Can @salesagility make a full language files revision in a single PR? Please do not change any other part of the language files on that PR (strings format, indentation and strings removal) so its easier to me to apply changes on Crowdin translations.

Any other changes on language files will be welcomed but on a separated PR without any trouble! 👍 

#### Expected Behavior

- All languages files will have same copyright and license. 
- Then same text will be also present in the translations from Crowdin project https://crowdin.com/project/suitecrmtranslations 

#### Actual Behavior

- Outdated copyright, different text for comments and license notes.
- Not in comply with Coding Standards for SuiteCRM for **License and entry point** https://suitecrm.com/wiki/index.php/Coding_Standards#License

#### Context

Keep translations in pace with english core language files

**Comment by samus-aran** [comment]
@horus68 

Just want to clarify.

You wish a single PR with JUST those changes:

- Copyright revision
- if statement for the valid entry point place and format
- License text comments

But then another PR with the strings then removed with format changes i.e. What Dillon Brown has done?

I'm not clued up on the translation process so please enlighten me in regards to this.  Why do you require these two PRs if the goal is that they would be all merged into the hotfix branch anyway?  
I just want to be aware is there a time delay of when you need us to merge the template headers commit in first and then the file format/string removal commit in second?

**Comment by horus68** [comment]
@samus-aran my request is a one time only to apply to all language files as it will apply to the comments section (not the actual strings). This will be a big change (every language files) so its easier for me to handle the file sync with crowdin.
Actually I have a local copy acting as a middle man to sync Github to Crowdin (that includes also some changes not implemented in this github project).

This is only relevant to update them all at once, this time only (as they need to be the same). 
In any other change (future or previous PR) you can edit any part of the file, it will be synched later.

**Comment by samus-aran** [comment]
Ok, so we'll create a PR with just those changes for all language files - it will be merged after approval - and then create the following PR with removed strings after.  Does it matter if the two PRs are merged close together i.e. 15 minutes after each other?

**Comment by horus68** [comment]
@samus-aran Thanks. No problem on the time delay!

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Requesting copyright revision on all language files](https://trello.com/c/cpNmhwmn/5-requesting-copyright-revision-on-all-language-files)

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Requesting copyright revision on all language files](https://trello.com/c/cpNmhwmn/5-requesting-copyright-revision-on-all-language-files)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by horus68** [comment]
@samus-aran this is not a suggestion... its a bug because we are in 2017 and the copyright says 2016.
Even if things do not break, its a bug on the code files!

**Comment by samus-aran** [comment]
@horus68 Reason why I've stated this as a suggestion is because doing it all in one go.  But in the suggestion box I have moved it already into discussion as it is currently schedules by Dillon - I'll re-open this when Dillon reviews if there are associated other issues start of next week.
