### ISSUE TITLE
Zend Search Lucene is unmaintained obsolete, crashes on PHP 7.

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#3352]
#### Issue

* The makers of Zend Search Lucene say to move to a more efficient search solution such as SOLR or Elasticsearch.
Reference: https://github.com/zendframework/ZendSearch/pull/8#issuecomment-230953378

* The Zend Search Lucene code reportedly crashes under PHP 7. The last version of PHP it was tested against was 5.3 a few years back, which is currently outdated unsupported obsolete.
Reference: https://github.com/zendframework/ZendSearch/issues/24

#### Expected Behavior

Search should be currently maintained by 3rd party maintainers.  Should run in PHP 7 without crashing.

#### Actual Behavior

Lucene itself has been updated thru several major versions currently supported is 6.5.

#### Possible Fix

Find a php search component on packagist to replace Zend Search Lucene.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
I didn't know it was obsolete, but it sure feels like a software stopped in time : - ) and the Issues here that are related to Search never tend to get any work done, it seems nobody knows how to deal with this.

I'd say 30% of the problems users have with this come from mis-configuration of Schedulers, 30% from corrupted Indexes, 30% from permissions degradation on Indexes, and 10% from problems with accents or email address searches.

It would be great to have better Global search in SuiteCRM. And finally get rid of the double search mode (Basic/Advanced).

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zend Search Lucene is unmaintained obsolete, crashes on PHP 7.](https://trello.com/c/cxXntkr7/176-zend-search-lucene-is-unmaintained-obsolete-crashes-on-php-7)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
