### ISSUE TITLE
[Suggestion] Requesting Github project for core update language files

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3357]
#### Issue

The Core update zip pack do not includes language files so its not possible to upgrade SuiteCRM in the user interface language.
- There is no Github project for the upgrade pack, so its not possible to collaborate.

#### Expected Behavior

Updating SuiteCRM needs to be done in the user language. 

#### Actual Behavior

Upgrade screens display English language

#### Possible Fix

- Create a new project just for the upgrade pack. 
- Translations are ready to be included from Crowdin project 
https://crowdin.com/project/suitecrmtranslations
- I will then upload translation files
- Salesagility will then be able to use them in the next upgrade pack.

#### Context

Using SuiteCRM in each user language, not mixing languages.

**Comment by chris001** [comment]
Yes @horus68 ,  Was just reading about this on crowdin.  If you don't want to wait any longer for SA to make this new github project, you could make your own github project for just the full set of language files, and connect it to automatically sync with the crowdin.  From then onward, when SA makes an upgrade pack, they could use a script to copy just the upgrade language files from your github language project, into the upgrade pack.
https://support.crowdin.com/github-integration/

**Comment by horus68** [comment]
I don't want to have extra work and then find SA do not want to use that feature. And I think its better the master files ar on Github projects owned by the main company in casa I went somewhere else in the future!
Same goes for Install language files https://github.com/salesagility/SuiteCRM/pull/1697

**Comment by pgorod** [comment]
I had to work on the installation process for #3268 and so I went looking into the upgrade packages and was surprised to find a lot of code there. Basically, some of the upgrades (sometimes from one specific version to another specific version) need more than just copying files, and there is code in there changing logic hooks, deleting old files, etc.

So, it there is code there, it would benefit from open sourcing it, getting cooperation, running automated tests, etc. I think moving that into Github makes perfect sense.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Suggestion] Requesting Github project for core update language files #3357](https://trello.com/c/khg9Sdli/170-suggestion-requesting-github-project-for-core-update-language-files-3357)

**Comment by samus-aran** [comment]
Hi everyone,

I have added this to the New Suggestion Box and moved it into discussion - as this is a very benefical feature for us as well.
