### ISSUE TITLE
Calendar - 1 Hour task consumes 2 Hours of space

### ISSUE THREAD

**Issue by stevejenkin** [salesagility/SuiteCRM#3359]
#### Issue
When generating a one hour task in the system, in the calendar the task placeholder consumes 2 hours of space instead of 1 hour. So other users would assume the task is for 2 hours when it should only be 1.

#### Expected Behavior
1 Hour task should only consume the proportionate space on the calendar 

#### Actual Behavior
Consumes 2 hours of space in the calendar

#### Steps to Reproduce
1. Create a new task with a start date/time of today at 12:00 and an end date/time of today at 13:00
2. Navigate to the calendar module and look at the week view.
3. The task placeholder consumes the space from 12:00 to 14:00

#### Context
I would say this is a High Priority bug as it causes confusion for all system users when looking at the calendar.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 56.0.2924.87
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6 and PHP 5.6.30
* Operating System and version (e.g Ubuntu 16.04): Centos 7.3 x86_64

**Comment by Dillon-Brown** [comment]
Hi @stevejenkin This has already been raised as a suggestion on SuiteCRM's new suggestion box: https://trello.com/c/YNyG2EVU/153-event-task-project-task-shows-only-end-date-on-calendar If you have anything you would like to add, please feel free to add it to the comments there. You can also up vote the suggestion to make it a higher priority. Thanks.
