### ISSUE TITLE
Sent emails with attachment using SuiteCRM (Exchange) not showing in SENT EMAIL folder of email client (OWA, Outlook, Thunderbird)

### ISSUE THREAD

**Issue by GeekyWebMistrss** [salesagility/SuiteCRM#336]
When sending email using the email module, those emails with attachments (via manually attaching files or using templates with attachments) are not showing in the SENT FOLDER of the mailbox. However, there is no problem with emails without attachments. Problem noticed on on 7.2.1 version, upgraded to 7.2.3 but the problem persists.

**Comment by Mausino** [comment]
@Dillon-Brown i think that this was solved in #4999 [Sent emails are not copied to the given 'Sent Folder'] and should be it closed.
