### ISSUE TITLE
Cannot create campaign, screen flicker and back to initial dialog

### ISSUE THREAD

**Issue by joaolcorreia** [salesagility/SuiteCRM#3360]
Can't create a campaign, go through all the steps and the screen flickers before summary and goes to the initial page. See video capture.

1. Click Create Campaign
2. Click Non-email Campaign (go to wizard)
3. Type campaign data 
4. Type budget
5. Select Target Lists
6. Click Next and Flickers and goes to 1.

#### Context
Impact is significant, I want to create a web form to include in the website and I need a campaign, not being able to create the campaign is major.

#### Your Environment
* SuiteCRM Version used: Version 7.8.2 - Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version Version 57.0.2987.133 (64-bit)
* Environment name and version: PHP 5.6.30 and MySQLi Server Info: 5.7.16-0ubuntu0.16.04.1
* Operating System and version: Ubuntu LTS

![bug](https://cloud.githubusercontent.com/assets/1695738/24739560/65536bdc-1a51-11e7-93b7-e695b5707701.gif)

**Comment by pgorod** [comment]
@joaolcorreia I can't reproduce this on the online demo.

It would be better to work out these issues in the forums before posting them on Github. Often it's just a specific problem with your installation or configuration and the forums provide a basic triage for that; then if you conclude it's really a bug you can come here and create the Issue for the developers with more specific information, errors found in the logs, etc. I'm sure you'll understand. Thanks.

**Comment by Dillon-Brown** [comment]
@joaolcorreia I'm unable to reproduce this issue.

If you are still having issues with this I suggest you consult the forums here: https://suitecrm.com/forum someone there will be able to help you with any specific problems you are having. Thanks.

**Comment by Dillon-Brown** [comment]
@joaolcorreia Looks like this issue is related to #3058 and will be fixed in the next release. if if you want you can have a go at applying this fix to your own instance. Let me know how it goes :).
