### ISSUE TITLE
In Products, I cannot delete the filter after applying it and searching for a product

### ISSUE THREAD

**Issue by Chris8080** [salesagility/SuiteCRM#3361]
#### Issue

In 7.7.9 we still had the search field / feature, specifically in the Products entity.
After upgrading to 7.8.2 I found the filter feature which is nice and works in contacts as desired. But in Products it won't show - I only can search one time for a product and I seem to be unable to remove the filter or view all products.

#### Expected Behavior
As with the contacts, I'd like to remove the filter.

#### Actual Behavior
The remove filter button and remove filter button aren't being displayed.

#### Possible Fix
An issue with the theme or business logic under the theme?
The problem seems to persist in Suite P and Suite R

#### Steps to Reproduce

1. Click on products
2. Search for a product via the filter / search feature

#### Context

I can't see all/any products anymore

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium and Firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP7, Nginx
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by Dillon-Brown** [comment]
@chris001 I am to be unable to replicate this issue. Do you think you could clarify further or provide screenshots?

Filtered for "Product 1":
![issue-3361_1](https://cloud.githubusercontent.com/assets/26431166/24915988/b2f3176a-1ed0-11e7-9349-8adc97c46598.png)

After clicking on x:
![issue-3361_2](https://cloud.githubusercontent.com/assets/26431166/24916002/bf780cfc-1ed0-11e7-84fb-d90adebb28ed.png)

**Comment by chris001** [comment]
@Dillon-Brown I think you meant @Chris8080

**Comment by Chris8080** [comment]
@Dillon-Brown The same Version 7.8.2?

![suitecrm_products_filter](https://cloud.githubusercontent.com/assets/3712952/24934065/081fe076-1f4c-11e7-8aac-2da2c3a5276b.jpeg)
A couple of days ago I searched for a product, now the filter is still active and I can't see any products, just the empty results page (the search yielded 0 results - there are around 200 products in the DB)

**Comment by Dillon-Brown** [comment]
@Chris8080 I still can't seem to replicate on 7.8.2. 

![issue-3361](https://cloud.githubusercontent.com/assets/26431166/25002705/b40555d6-2043-11e7-9639-4b4721a728df.png)

Have you tried repair/rebuild and clearing the cache?

**Comment by Chris8080** [comment]
@Dillon-Brown yes, I just did several times a Quick Repair and Rebuild without any changes.
And I just upgraded to 7.8.3 without an improvement as well.

I changed the file: modules/AOS_Products_Quotes/Line_Items.php to add images to the invoice detail view, but that shouldn't be related there?
After creating a new product, it disappears right away as well (since the filter is still active).

Creating a new user and logging in, I can see the products right away.
So I assume that the filter is persistant in my user session or similar? Is the filter stored in the DB? Maybe I can simply delete the filter in the DB?

**Comment by Dillon-Brown** [comment]
@Chris8080 I would suggest trying a different browser and seeing if that makes a difference. If that doesn't work then you could reset user preferences under profile. Be aware that this will delete ALL user preferences and put the user back to the out the box defaults.

**Comment by Chris8080** [comment]
@Dillon-Brown Thank you very much - reseting the user preferences worked fine, I can see all products again now. :)

**Comment by chris001** [comment]
Obviously, this is a defect. The app should provide a button to let the user manage/reset their search filters, without making the user have to reset all of their user preferences under profile.

**Comment by Dillon-Brown** [comment]
@chris001 I'll be closing this issue as we are unable to replicate it for further testing. If it comes up again and you are able to replicate it, please raise it as an issue :). Are you suggesting that we separate the user preferences out by category?
