### ISSUE TITLE
Products save and continue

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#3364]
#### Issue

When creating a product or when in the edit view, there is a save and continue button. This button currently does nothing.

#### Expected Behavior

Clicking on the save and continue button should take the user to the next product in the list.

#### Actual Behavior

Nothing.

#### Steps to Reproduce

1. Navigate to Products -> Create Product
2. Enter the details of the product  -> Click save and continue.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium(53.0.2) and FireFox (52.0.2)
* Environment name and version (e.g. MySQL, PHP 7): mySQL 5.7.17 and PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by horus68** [comment]
related issues:
https://github.com/salesagility/SuiteCRM/issues/3069
https://github.com/salesagility/SuiteCRM/issues/3238
