### ISSUE TITLE
AOR- Date parameter doesn't work with 'Equals' operator

### ISSUE THREAD

**Issue by polys248** [salesagility/SuiteCRM#3366]
#### Issue

Date parameter doesn't work with 'Equals' operator
#### Expected Behavior

Reports with a date parameter should display only results with date value in parameter
#### Actual Behavior

Report returns empty
#### Steps to Reproduce

1. Create a report with a date parameter condition
2. Run the report and select  "Equals" as condition operator
3. Empty report is returned
4.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome, Edge, Firefox
* Environment name and version (e.g. MySQL, PHP 7): Mariadb
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by Dillon-Brown** [comment]
@polys248 Hi, just to confirm was this issue with exporting as pdf and csv? my reports are returning the correct values until they are exported.
