### ISSUE TITLE
Failed to save user This email address is already registered.

### ISSUE THREAD

**Issue by vere-tech** [salesagility/SuiteCRM#337]
First time integrating joomla3 with suitecrm, i can confirm there both talking to one another from previous logs. I get the following error when creating portal access for a contact.

Failed to save user This email address is already registered.

There is only the admin account and the 1 test user that im trying to give portal access to both with different email addresses.
The apache error.log on Joomla3 shows nothing and on suiteCRM shows:

PHP Notice:  Undefined property: User::$default_team in /var/www/html/service/v4/SugarWebServiceImplv4.php on line 171

PHP Notice:  Undefined index: wl_list_max_entries_per_page in /var/www/html/service/v4/SugarWebServiceImplv4.php on line 180

PHP Notice:  Undefined index: wl_list_max_entries_per_subpanel in /var/www/html/service/v4/SugarWebServiceImplv4.php on line 181

PHP Notice:  Undefined property: stdClass::$success in /var/www/html/custom/modules/Contacts/createPortalUser.php on line 40, referer: http://example.com/index.php?action=DetailView&module=Contacts&record=7a3b24eb-38dc-2a49-5e59-55c506c0133f&offset=1

Any help on this would be great!

**Comment by vere-tech** [comment]
Here's a cut from the createPortalUser.php
''''
36 if(array_key_exists("aop",$sugar_config) && array_key_exists("joomla_url",$sugar_config['aop'])){
37    $portalURL = $sugar_config['aop']['joomla_url'];
38    $wbsv = file_get_contents($portalURL.'/index.php?option=com_advancedopenportal&task=create&sug='.$_REQUEST['record']);
39    $res = json_decode($wbsv);
40    if(!$res->success){
41        $msg = $res->error ? $res->error : $mod_strings['LBL_CREATE_PORTAL_USER_FAILED'];
42        SugarApplication::appendErrorMessage($msg);
43    }else{
44        45SugarApplication::appendErrorMessage($mod_strings['LBL_CREATE_PORTAL_USER_SUCCESS']);
46    }
47 }else{
48    SugarApplication::appendErrorMessage($mod_strings['LBL_NO_JOOMLA_URL']);
49 }
''''

**Comment by chris001** [comment]
A comment about this error.  I nominate that the code should be adapted so that the feature would "just work," regardless of whether the user email is already registered in Joomla user table first, or in Sugar/Suite user table first.
The code would "sync" the user data record from one side to the other, using the email address as the unique identifier/key.

**Comment by vere-tech** [comment]
Thanks heaps for the info Chris, I now understand whats happening and i can move forward with a lil manual intervention each time a new user registers... and I also 2nd you on that solution.

**Comment by chris001** [comment]
Note this code should be anaylzed for security risk. What if the admin of the sugar/suite app has his/her email registered in admin user account on sugar/suite app.  And no email registered on the joomla portal web site.  A malicious hacker registers the sugar/suite admin email on joomla portal site.  Might this then allow the hacker to single-sign-on to the sugar/suite app, and steal valuable crm data. Via forgot password recovery mechanism or simply reading the cleartext password or password hash from the sugar/suite admin user.
What is the true repository server of the users' identity.  Sugar/suite or joomla.  Or elsewhere, such as Microsoft AD, OpenLDAP, Samba4, Mysql, Radius, etc.  Should there be only one identity store that would be simplest to administer, and all apps configured to use it, across the organization.

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that.
