### ISSUE TITLE
Inline editing in detail view copies the value - 7.8.1

### ISSUE THREAD

**Issue by psatasiya** [salesagility/SuiteCRM#3372]
Dear Experts,

I'm using 7.8.1 and SuiteP theme.

Now, when I am going to Leads module detail view and click on any field for inline editing, and then double click on any other field without changing previous field then it copies the value of older selected field to new selected field.

For example,
I have two fields, Phone 1 and Phone 3 in detail view.
Now I will double click on Phone 1 field(I will not change or save anything).
Now I realize that I have to click on Phone 3 not on phone 1. So immediately I will double click on Phone 3.
When I double click on Phone 3 it will copy the value of Phone 1(Previously clicked field) to Phone 3.

For more understanding,I am attaching screenshots here.
![beforeinlineedit](https://cloud.githubusercontent.com/assets/19162814/24828131/393dfbf0-1c74-11e7-81fb-53f16413e76d.png)
![afterclick](https://cloud.githubusercontent.com/assets/19162814/24828135/408ced30-1c74-11e7-82ac-ff29b1e5bff3.png)
![afterclicktarget](https://cloud.githubusercontent.com/assets/19162814/24828137/4864e580-1c74-11e7-9c9e-6d5751917b11.png)

Thanks in advance,
Prafull

**Comment by psatasiya** [comment]
I am able to generate this on https://demo.suiteondemand.com also.

**Comment by Mausino** [comment]
@salesagility @samus-aran I tested it on many modules in nightly demo and the issue doesn't appear anymore

**Comment by samus-aran** [comment]
Woot thanks @Mausino
