### ISSUE TITLE
Apply Status to Case Updates

### ISSUE THREAD

**Issue by halterpc** [salesagility/SuiteCRM#3374]
#### Issue

At AOP and Case flow.
In the area "Admin>AOP Setting > Case Status Changes" not running.

#### Expected Behavior

When a new case update exists, the system must apply the state changes as established

#### Actual Behavior

Not change

#### Possible Fix

Ubicación: .../modules/AOP_Case_Updates/CaseUpdateHook.php
Clase, funcion: updateCaseStatus (line 299)
```
/* PPW - CODe - Modifiación CORE */
// if (!empty($case->id)) {
if (empty($case->id)) {
```
NOTE: (Deleted "!")

#### Steps to Reproduce

1. Go to Admin > Email Settings and configure smtp mail
2. Go to Admin > Inbound Email and configure inbound mail
3. Go to Admin > AOP  Setting > Enable AOP and configure "Case Status Changes"
4. Go to Cases > Creare a update case
5. Go to email final client and repply mail
6. Go to the case and verify that the status has not been changed

#### Context

Customer Support. High priority

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): Mysql/MariaDb, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by horus68** [comment]
@halterpc for each issue you want to propose code you need to create a new PR starting with your won frok created from the SuiteCRM Hotfix branch.
Each PR can have different commits on files.
Each PR needs to be for each issue and with its own branch so there is no conflict on files or one can be merged but not the other.

**Comment by halterpc** [comment]
Done

**Comment by chris001** [comment]
OK but those are commits to your own fork.  What you need to do is make a PR from your fork halterpc/suitecrm:hotfix to salesagility/suitecrm:hotfix.

**Comment by halterpc** [comment]
It is ok?

Un saludo,
Álvaro Fuentes

**Comment by chris001** [comment]
No you still have to make a PR against this repo hotfix branch.  Here's how to do it:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
Be sure to select hotfix branch, it looks like `salesagility/suitecrm:hotfix`.

**Comment by halterpc** [comment]
I will resolve problem to PR, monday 17

**Comment by halterpc** [comment]
the process is ok?

**Comment by halterpc** [comment]
hi? now, the process it´s ok?

**Comment by Dillon-Brown** [comment]
@halterpc Looks good. You just need to close your old PR here: #3379. Thanks.
