### ISSUE TITLE
The execution of workflow in order

### ISSUE THREAD

**Issue by halterpc** [salesagility/SuiteCRM#3376]
#### Issue

Proposal for the workflow of the same module to be executed in ascending order according to the name

#### Expected Behavior

N/A

#### Actual Behavior

N/A

#### Possible Fix

Ubicación: .../modules/AOW_WorkFlow/AOW_WorkFlow.php
Clase, funcion: AOW_WorkFlow (clase) / run_flows (funcion)
Code:
```
        // PPW - CODE - Modificación core para ejecutar ordenadamente los workflow
		$flows = AOW_WorkFlow::get_full_list(' aow_workflow.name ASC '," aow_workflow.status = 'Active'  AND (aow_workflow.run_when = 'Always' OR aow_workflow.run_when = 'In_Scheduler' OR aow_workflow.run_when = 'Create') ");
```

Ubicación: .../modules/AOW_WorkFlow/AOW_WorkFlow.php
Clase, funcion: AOW_WorkFlow (clase) / run_bean_flows (funcion)
Code:
```
            // PPW - CODE - Modificación core para ejecutar workflow en orden (solo añadido ORDER BY)
            $query = "SELECT id FROM aow_workflow WHERE aow_workflow.flow_module = '".$bean->module_dir."' AND aow_workflow.status = 'Active' AND (aow_workflow.run_when = 'Always' OR aow_workflow.run_when = 'On_Save' OR aow_workflow.run_when = 'Create') AND aow_workflow.deleted = 0 ORDER BY name ASC ";
```

#### Steps to Reproduce

N/A

#### Context

This functionality allows you to create more advanced business logic. This can create linked workflows

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all
* Environment name and version (e.g. MySQL, PHP 7): MySQL/MariaDB, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by halterpc** [comment]
I will resolve problem to PR, monday 17

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The execution of workflow in order](https://trello.com/c/9oGV3IVa/174-the-execution-of-workflow-in-order)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
