### ISSUE TITLE
Workflow field gets id instead of value

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#3381]
Create a task that subject equals account name in workflow and get id instead of value 
#### Issue
Shows wrong value when create task in opportunities module 

#### Expected Behavior
When you want the subject to be the account name it is the account name and not it's id.

#### Actual Behavior
When you create a workflow with the subject = account name in the opportunities module.

#### Steps to Reproduce

1. In new install  with 7.8.2
2. create workflow in opportunities module
3.
![image](https://cloud.githubusercontent.com/assets/2706403/24858420/79afcd0a-1e16-11e7-98b8-068589c08777.png)

4. get id instead of text in created  task
![image](https://cloud.githubusercontent.com/assets/2706403/24858453/93af68f0-1e16-11e7-9a28-fc4111a917ab.png)

#### Context
Unable to create proper workflow for opportunities module
Feel it is High Priority 

#### Your Environment

Version  7.8.2
Sugar Version 6.5.24 (Build 509)
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Safari/602.1 but also test with Chrome/opera/ firefox (all the latest versions)
Environment name and version (e.g. MySQL, PHP 7):
MySQL PHP6.5
Operating System and version (e.g Ubuntu 16.04):
GNU/Linux

**Comment by wanesmith** [comment]
I upgraded to 7.8.3 and the error persists.

**Comment by wanesmith** [comment]
I tested this with Version 7.9.0-rc
Sugar Version 6.5.24 (Build 509) and the issue is in that version too.

**Comment by wanesmith** [comment]
I have this fix but the problem persists

**Comment by ChangezKhan** [comment]
Hey @wanesmith, can you check one more time? I have updated my patch.

**Comment by wanesmith** [comment]
![image](https://cloud.githubusercontent.com/assets/2706403/26528915/6d573eca-436a-11e7-93f5-02bc2ea818c1.png)
I am getting blank fields now.

**Comment by ChangezKhan** [comment]
Hey, @wanesmith, can you share details of your workflow? So, i can create the same at my end and debug it.

**Comment by wanesmith** [comment]
![image](https://cloud.githubusercontent.com/assets/2706403/26529123/351b7bde-436f-11e7-8f33-912fb8bef504.png)
![image](https://cloud.githubusercontent.com/assets/2706403/26529125/3bb53dea-436f-11e7-9e47-0ca25cc48eee.png)
![image](https://cloud.githubusercontent.com/assets/2706403/26529126/44ce6136-436f-11e7-8265-24d0f253bb5e.png)
![image](https://cloud.githubusercontent.com/assets/2706403/26529127/4a00c374-436f-11e7-8edb-7c47e7dfaae1.png)

**Comment by wanesmith** [comment]
![image](https://cloud.githubusercontent.com/assets/2706403/26529134/6a123760-436f-11e7-9ced-4f594985f921.png)

**Comment by ChangezKhan** [comment]
Hey @wanesmith , are you correctly mapped opportunity fields with task's fields in your workflow? I mean, you shared a screenshot of blank `Opportunity` and `Account Name` fields of task module, but I am unable to find these two fields in above any screenshots of workflow. 

As per your screenshots, you mapped `Opportunity Name` to `Description` field and `Account Name` to `Account\Opportunity Name` field of task module. Kindly check once again that your workflow is correctly set up and let me know.

**Comment by wanesmith** [comment]
sorry the delay I set a new 7.9 instance with test data I updated your fix 
![image](https://cloud.githubusercontent.com/assets/2706403/26565155/eb244c86-4512-11e7-886c-494ddf5f4363.png)
![image](https://cloud.githubusercontent.com/assets/2706403/26565156/f946ef9e-4512-11e7-86ef-a8e2624936b7.png)
![image](https://cloud.githubusercontent.com/assets/2706403/26565159/08aca4a6-4513-11e7-8849-fd17528e8bd5.png)
and result
![image](https://cloud.githubusercontent.com/assets/2706403/26565176/37babbc0-4513-11e7-9f2a-bb3a73b3cb31.png)

**Comment by ChangezKhan** [comment]
Hey @wanesmith, It seems working fine on SuiteCRM 7.9.0. Can you check one more time that you patched the code correct way?

**Comment by wanesmith** [comment]
After I did the upgrade I replaced this https://github.com/ChangezKhan/SuiteCRM/blob/c85724ceabf07c09d3a1dfa7c8d23831337420fd/modules/AOW_Actions/actions/actionCreateRecord.php  file with the one in the file system and ran a repair is there something else I needed to do?

**Comment by ChangezKhan** [comment]
I think you did correct, but I don't know, why it is not working for you.

**Comment by wanesmith** [comment]
So I re did everything and it is working except it is not linking back to the opportunity 
![image](https://user-images.githubusercontent.com/2706403/27113353-7408bf8a-50e6-11e7-9ba4-ced79b416cc0.png)

**Comment by ChangezKhan** [comment]
@wanesmith , it is linking back to the opportunity at my end. Kindly check whether you have checked the "**Relate to Workflow module**" checkbox in workflow.

**Comment by wanesmith** [comment]
yes that worked thank you
