### ISSUE TITLE
Deleting a field in modulebuilder also deletes dropdown

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#3383]
#### Issue
If deleting a dropdown field in modulebuilder, the correxponding dropdown gets deleted as well.
Problem is, that if you have another field in the package that uses this dropdown, then this field gets destroyed, because dropdown is missing after that.

#### Expected Behavior
If deleting a dropdown field in modulebuilder, and the same dropdown list is used somewhere else in the same package, the list should not be deleted.

#### Actual Behavior
Dropdown list gets deleted.

#### Possible Fix
Dont delete corresponding dropdown list at all, or check if it is used somewhere else in the same package.

#### Steps to Reproduce
1. Create a package
2. Create two modules
3. Create a dropdown field Ax in module A with list A1
4. Create a dropdown field Bx in module B reuse list A1
5. delete field Ax

#### Your Environment

* SuiteCRM Version used: 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 52
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
