### ISSUE TITLE
Spots - export

### ISSUE THREAD

**Issue by MichalNowacki** [salesagility/SuiteCRM#3385]
#### Issue

It is suggestion.
I like to ask. Are you going to add export result of the spot?
For example, possibility to export data from spots to, csv, pdf or spreadsheet doc?

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spots - export](https://trello.com/c/ky8IGDsa/173-spots-export)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
