### ISSUE TITLE
MultiSelect Parameter In Reports

### ISSUE THREAD

**Issue by CamoMacdonald** [salesagility/SuiteCRM#3386]
#### Issue

If you have a report with a multi select field condition as a parameter and update that field through detail view the update does not take affect
#### Expected Behavior

The report should be updated to represent the new multiselect condition value

#### Steps to Reproduce

1. Create a report with a multi select field condition (parameter) and set the default to null
2. On detail view select a value that should display the additional results and press update
3. The result don’t update

#### Context

This stops users from making parameter reports with multi select fields
#### Your Environment

* SuiteCRM Version used: 7.8.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Dillon-Brown** [comment]
@CamoMacdonald I can't seem to replicate this on 7.8.3. 

Multi-select field with null as default:
![issue-3386_1](https://cloud.githubusercontent.com/assets/26431166/25134166/ccb41e3a-2446-11e7-9744-6034bf969c25.png)

After selecting value and hitting update:
![issue-3386_2](https://cloud.githubusercontent.com/assets/26431166/25134190/ddec4b82-2446-11e7-9f5f-a8a7b74cbf29.png)

**Comment by CamoMacdonald** [comment]
@Dillon-Brown If you have an actual multi select field rather than the 'Type' 'One of'. Example is below:
![dillion](https://cloud.githubusercontent.com/assets/20798044/25134773/5afa546a-2448-11e7-869e-647e1db46efb.png)

**Comment by belchfireid** [comment]
Bug is also in 7.10.7.  

Changing the parameter and Update does not work whether the Type is Value or One Of.

**Comment by lazka** [comment]
I've created #6811 for the "One of" case
