### ISSUE TITLE
Error on saving scheduled report

### ISSUE THREAD

**Issue by djughed** [salesagility/SuiteCRM#3390]
![error](https://cloud.githubusercontent.com/assets/22477008/24955080/479dd010-1f82-11e7-8b3a-8afa48103392.PNG)

#### Issue

im trying to create a scheduled report however every time i hit save i get this error. (attached) Also the report does not run as per the schedule set and when clicked on from the list view i get the error message " an unexpected error has occurred."
#### Expected Behavior

View report schedule information and automatically run at certain time.
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: Version 7.8.2
Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome Version 57.0.2987.133 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Hi @djughed Thanks for the question! However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our  [Community Forum](https://suitecrm.com/forum). We will be able to help you with your issue there.
