### ISSUE TITLE
Subpanel table overflows with large number of fields

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#3408]
#### Issue
The subpanel CSS has an issue where the table header does not extend with the table data row. This occurs when there is a large number of fields within the subpanel. It should possibly collapse or(not as ideal) the subpanel should have it's own scrollbar. Currently the subpanel flows off the page and requires a full page horizontal scroll to view all data which is not ideal.

Note: The header section of the panel being cut off is not an issue in the list view table, but the table does still overflow off the constraints of the page in list view.

#### Expected Behavior
The subpanel table header should extend/overflow with the table data row and not 'stop' or be 'cut short'. The subpanel should possibly also not extend past the constraints of the page but collapse to a smaller number of fields allowing the user to expand/collapse to view all data at their discretion. 

#### Actual Behavior
The subpanel field data/results overflows off the page, but the subpanel header stops within the constraints of the page so the table does not display correctly.

#### Possible Fix
Ensure that the table header row is designed to be the same width/display within the same constraint as the table data row(s). Possibly collapse the table to a smaller number of fields if there is a large number of fields added so that the table shows within the screen resolution being viewed and does not overflow.

#### Steps to Reproduce
1. Once logged into SuiteCRM, navigate to Studio
2. Navigate to a module subpanel layout to edit
3. Add a large number of fields(15+) with varying label lengths to the subpanel layout and save
4. Navigate to the module detail view where the subpanel displays and observe the issue

#### Context
This bug has affected the viewing of subpanels as the user can see that the header does not extend and the table also overflows off the page in most resolutions

This bug should be a low priority as it can simply be worked around by scrolling horizontally.

#### Your Environment
![subpaneloverflow](https://cloud.githubusercontent.com/assets/5641419/25092075/ffd057f2-2383-11e7-860f-a60549c4f748.png)

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium 53.0.2785.143, Firefox 52.0.2
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5, MySQL 5.5.54
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by daniel-samson** [comment]
I think we need to use a table plugin that collapses the headings down into a vertical layout. The current footables plugin only seems to handle when you are using a smaller device. Perhaps we need to create a new plugin which extends this function but has better handling for larger screens.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
