### ISSUE TITLE
Fields in module builder are not saved (PHP 5.5)

### ISSUE THREAD

**Issue by JanSiero** [salesagility/SuiteCRM#341]
- Go into module builder
 - Create a package and a module
 - Go to fields
 - Add new field
 - Save

=> The field is not saved

The error is not always reproducible, sometimes it works, sometimes not.
Error only occurs in PHP 5.5 (in php 5.4 it works)

See also:
https://suitecrm.com/forum/suitecrm-7-0-discussion/5866-module-builder-not-saving-fields

**Comment by willrennie** [comment]
Fix provided was merged into 7.2.3 and subsequently 7.3.
