### ISSUE TITLE
POSIX functions at \include\utils.php breaks Windows version - SuiteCRM 7.8.3. / PHP 5.3

### ISSUE THREAD

**Issue by ptwentypt** [salesagility/SuiteCRM#3411]
#### Issue

The POSIX functions at \include\utils.php breaks Windows version - SuiteCRM 7.8.3. / PHP 5.3. PHP is unable to parse this functions because they are not available in PHP for Windows.

#### Expected Behavior

We have solved the problem by commenting the offending code but this might be a problem for other users.

#### Possible Fix

Replace POSIX functions in line 426 of \include\utils.php

#### Steps to Reproduce

1. Upgrade from Sugar CRM 6.5.20 to SuiteCRM 7.6.6.
2. Upgrade from Suite CRM 7.6.6. to SuiteCRM 7.8.3.
3. Internal error 500
4. PHP complains about line 426 of file \include\utils.php
5. Only by commenting out the line 426 with the POSIX functions SuiteCRM will allow us to work

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 64-bit
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.3
* Operating System and version (e.g Ubuntu 16.04): Windows 2008 R2

**Comment by chris001** [comment]
This is accurate.

**Comment by Dillon-Brown** [comment]
Hi @ptwentypt 

I'm interested to know why that on the windows environment why the is_windows() function did not return as expected and thus by pass the Posix.

There is a fix for PHP 5.3 in regards to that PHP version here - https://github.com/salesagility/SuiteCRM/pull/3387/files  But my suspicion that we would need to figure out why it did that clause if its a windows environment.

**Comment by pgorod** [comment]
It should also have correctly executed `exec('whoami')` which with return a valid username. So that's _two_ conditions that should have been evaluated one way and (it seems) weren't.

Maybe if @ptwentypt could simply test [the fix mentioned above](https://github.com/salesagility/SuiteCRM/pull/3387/files) and see if that solves it? Maybe the problem is not really the `posix` functions, but the PHP 5.3 syntax issue...

**Comment by ptwentypt** [comment]
Hi @Dillon-Brown @pgorod ,

The is_windows() function works OK (returns 1/true).

I believe the problems relies on the file parsing itself. I just added some logging lines to the getRunningUser() function and the function is not called. As soon as I uncomment the 

`$runningUser = posix_getpwuid(posix_geteuid())['name'];`

line, it throws a 500 error.

The fix you provided:

`$usr = posix_getpwuid(posix_geteuid());
 $runningUser = $usr['name'];`

Works.

Thank you for your quick help.

**Comment by Dillon-Brown** [comment]
@ptwentypt @pgorod Thanks guys. Glad you got it resolved :). Should be another minor release soon that will get this fixed!
