### ISSUE TITLE
Reports with user input fail

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#3412]
Reports with user input fail to run

#### Issue
Reports with user input will display the user input form and then when you execute the report, it returns back to the reports list.

The report works correctly if ou have Auto or View for the report filters.

#### Expected Behavior
The report shoudl run with the filters applied according to the user input

#### Actual Behavior
The report returns to the reports list

#### Steps to Reproduce
Opportunity Report
Sales Stage is One Of (pick some).
Set to User Input
Close Data is greater than
Select a date
Set User Input
Run the report
Press Execute on user input form
Report returns to the reports list

#### Context
Since last upgrade

#### Your Environment

* 7.8.3
* All browsers
* MySQL
* Windows

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New functionality to send mail to an address stored in a "varchar"](https://trello.com/c/wJpicz5w/175-new-functionality-to-send-mail-to-an-address-stored-in-a-varchar)

**Comment by Dillon-Brown** [comment]
@davidyounger I'm unable to replicate this on 7.8.3. Do you think you could clarify further or maybe try and replicate this on the demo? 

[demo.suiteondemand.com](url)

**Comment by davidyounger** [comment]
[http://www.theservicemanager.com/images/newsletter/tsmlogo2.jpg]

Hi Dillon,
I realised that it’s the Alineasol report addon that has problems, not Suite reports.
Sorry.
cheers




David Younger
Managing Director
The Service Manager (TSM)
www.theservicemanager.com<http://www.theservicemanager.com.au/>
david@theservicemanager.com<mailto:laurence@purpose.com.au>
Suite2a, 199 Regent Street Redfern  NSW 2016
Ph: 02 9690 3888, Fax: 02 9690 3800




This e-mail message and any attachments contain information that is confidential and may be subject to legal privilege. If you are not the intended recipient, you must not peruse, use, pass on or copy this message or any attachments. If you have received this e-mail in error, please notify us by return e-mail and erase all copies of this message including any attachments. Thank you.
