### ISSUE TITLE
Reports export failing

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#3413]
Exporting a report that is displayed on the screen fails and returns to the reports list

#### Issue
Exporting a report that is displayed on the screen fails and returns to the reports list

#### Expected Behavior
Report should export

#### Actual Behavior
Returns to the reports list, no export occurs

#### Context
Cant export reports

#### Your Environment

* SuiteCRM Version used: 7.8.3
* All
* MySQL
* Windows

**Comment by Dillon-Brown** [comment]
@davidyounger I'm unable to replicate this on 7.8.3 Do you think you could clarify further or provide screenshots?

**Comment by davidyounger** [comment]
Alineasol problem
