### ISSUE TITLE
"ProspectLists" module add customize support in studio

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3417]
"ProspectLists" module add customize support in studio.

**Comment by Dillon-Brown** [comment]
@a277913835 i'll raise this as a suggestion. By default, the ProspectLists module is not available in studio. However, you can achieve this by adding a blank file named studio.php in this location: modules/ProspectLists/metadata/

**Comment by pgorod** [comment]
Does anybody know the reasoning behind this? I mean, why is it not currently included, and why @a277913835 thinks it should be?

Sometimes you enable Studio (like @Dillon-Brown explained) only to find out it doesn't really work with some particular module...

**Comment by Dillon-Brown** [comment]
@pgorod There are quite a few reasons why a module might not be included in studio. For example, there are some modules that are just too complex and as such, don't support standardised views and relationships such as the email module.

There are also modules that exist for the sole purpose of creating a relationship module between two different modules, such as line items.

Some modules have also been created without studio in mind and just need a .php file added in to work.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["ProspectLists" module add customize support in studio](https://trello.com/c/Q0ChR8im/180-prospectlists-module-add-customize-support-in-studio)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
