### ISSUE TITLE
td width truncates label in resource chart

### ISSUE THREAD

**Issue by 2007H3** [salesagility/SuiteCRM#342]
in Chrome Version 44.0.2403.125 m

The Project> Resource Chart has truncated the top-left label, as shown below.

![reschart](https://cloud.githubusercontent.com/assets/12518763/9185211/9367288c-3f7f-11e5-810f-6cf8721ee8c0.jpg)

**Comment by digitalmcgrath** [comment]
Pull request for this issue has been submitted. https://github.com/salesagility/SuiteCRM/pull/343
