### ISSUE TITLE
Regular user does not reach email address field in Reports module

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#3420]
#### Issue

I'm trying to create a report that will display the account and or contact's e-mail address among other information like opt out field. When creating the report the field for e-mail address is not available. 
I can create my reports and reach email field when i as an administrator user. When i as a regular user, i could not reach this field.
#### Expected Behavior

It should be available for permitted users.
#### Steps to Reproduce

1. Open Reports module and create new report.
2. Select contacts module
3.  Choose Email Address : Email Address and Email Address
4. Fields (Email Address) box is empty
![screenshot_1](https://cloud.githubusercontent.com/assets/22373035/25183238/ac984674-251f-11e7-82ad-62c6552d1e89.png)

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by adminibt** [comment]
For us this is a huge problem because email campaigns cannot be used anymore. Normal workflow is:
- Produce a report in which email addresses are a condition
- Export the report results into a target list
- Use the target list for email campaings

Is there any chance that this will be resolved soon?

**Comment by adminibt** [comment]
Maybe this is the solution: modules/ACL/ACLController.php, add these 3 lines of code starting at line 72:

                if($category == 'EmailAddresses'){
                 return ACLAction::userHasAccess($current_user->id, 'AOR_Reports', $action,'module', $is_owner, $in_group);
                }

At least this works for me.
@Dillon-Brown : Is this correct?

**Comment by mikesolo** [comment]
This is definitely a bug

The fix works for me
