### ISSUE TITLE
Language files change suggestion

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3430]
file: /modules/Campaigns/language/en_us.lang.php
line 230 'LBL_WIZARD_TARGET_MESSAGE2' => 'Create New Target:',
This should be "Create Target List" and may be need to change the label
line 520 'LBL_WIZARD_ADD_TARGET' => 'Add Existing Targets:',
This should be "Existing Target List" and may be need to change the label

file: /include/language/en_us.lang.php
line 1981     'LNK_BASIC_FILTER' => 'Quick Filter',
This label should be LNK_BASIC_SEARCH or LNK_QUICK_FILTER
line 1982     'LBL_ADVANCED_SEARCH' => 'Advanced Filter',
Why not like the following:
LBL_XXX_SEARCH => Xxx Search
and
LBL_XXX_FILTER => Xxx Filter

Forgive my poor english

**Comment by horus68** [comment]
@a277913835 can you edit this and create a new issue just for the include language file (about the Search/filter)?
This is related with a different PR and its bet to separate issues with different subjects

**Comment by horus68** [comment]
@Dillon-Brown On the first part of the issue user @a277913835 as a reason here:
We are not adding/creating "targets" but "targets lists". So this need to be changed!
See image when creating a campaign (where this strings are used)
![2017-04-21 13_02_57-target_lists](https://cloud.githubusercontent.com/assets/3055443/25276628/02ce256c-2693-11e7-8b42-61a21073de3b.png)
