### ISSUE TITLE
Unified Search - edit link opens employee module

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#3433]
Issue

In unified search clicking on the edit icon takes me to the Employees module rather than accounts

After much testing I found it only happens when the assigned user name is the last field marked with default => true in listviewdefs.php

Environment

SuiteCRM 7.7.8

**Comment by horus68** [comment]
Can you reproduce the issue in the demo https://suitecrm.com/demo
Please provide some pics/steps from there!

Note: actual version is 7.8.2, your version was released 8 months ago!

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
