### ISSUE TITLE
LDAPAuthenticateUser not compatible with SugarAuthenticateUser::loadUserOnLogin

### ISSUE THREAD

**Issue by LEAP-nishit** [salesagility/SuiteCRM#3442]
Enabling LDAP Authentication causes an warning message in logs. This warning floods the error logs with the message. 

#### Issue

When LDAP Authentication is enable the following error is generated in apache error logs:
`
PHP Warning:  Declaration of LDAPAuthenticateUser::loadUserOnLogin($name, $password) should be compatible with SugarAuthenticateUser::loadUserOnLogin($name, $password, $fallback = false, $PARAMS = Array) in /var/www/html/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 52, referer: https://crm.cobra.local/index.php?module=Users&action=Login
`
#### Expected Behavior

LDAPAuthenticateUser::loadUserOnLogin be compatible with SugarAuthenticateUser::loadUserOnLogin and not generate the warning. 

#### Actual Behavior

LDAPAuthenticateUser::loadUserOnLogin is  not compatible with SugarAuthenticateUser::loadUserOnLogin and generates warnings in error logs.
#### Possible Fix

LDAPAuthenticateUser::loadUserOnLogin signature be consistent with SugarAuthenticateUser::loadUserOnLogin. 

#### Steps to Reproduce

1. Enable LDAP Authentication
2. Enable Stack trace or watch apache error logs
3. Login with an ldap user

#### Context

Main issues is it generates many entries in the Apache error logs, and can be easily fixed. It does not appear to affect functionality.  It is a low priority issue. 

#### Your Environment

* SuiteCRM Version used 7.8.3
* Chrome Version 56.0.2924.87 (64-bit)
* MySQL, PHP 7
* Ubuntu 16.04

**Comment by gunnicom** [comment]
Relates to https://github.com/salesagility/SuiteCRM/issues/942
