### ISSUE TITLE
Duplicated language strings (ver. 7.9)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3445]
['LBL_EDIT_LAYOUT']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/InboundEmail/language/en_us.lang.php#L198
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/InboundEmail/language/en_us.lang.php#L212

['LBL_BUTTON_CREATE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L112
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L614

['LBL_BUTTON_EDIT']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L113
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L615

['LBL_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L144
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L656

['LBL_MODIFIED_BY']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L256
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L687

['LBL_SIGNATURE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L354
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L708

['LBL_LIST_STATUS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L210
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L827

['LBL_TEST_SETTINGS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L446
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L889

['LBL_SMTP_SERVER_HELP']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L493
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L898

['LBL_MISSING_DEFAULT_OUTBOUND_SMTP_SETTINGS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L494
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L899

['LBL_MAIL_SMTPAUTH_REQ']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L245
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L900

['LBL_MAIL_SMTPPASS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L495
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L901

['LBL_MAIL_SMTPUSER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L496
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L902

['LBL_MAIL_SMTPTYPE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L497
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L903

['LBL_MAIL_SMTP_SETTINGS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L498
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L904

['LBL_CHOOSE_EMAIL_PROVIDER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L499
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L905

['LBL_YAHOOMAIL_SMTPPASS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L500
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L906

['LBL_YAHOOMAIL_SMTPUSER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L501
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L907

['LBL_GMAIL_SMTPPASS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L502
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L908

['LBL_GMAIL_SMTPUSER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L503
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L909

['LBL_EXCHANGE_SMTPPASS']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L504
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L910

['LBL_EXCHANGE_SMTPUSER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L505
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L911

['LBL_EXCHANGE_SMTPPORT']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L506
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L912

['LBL_EXCHANGE_SMTPSERVER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L507
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L913

['LBL_HELP']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L563
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L925

['LBL_DATE_MODIFIED']

https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L582
https://github.com/salesagility/SuiteCRM/tree/v7.9.0/modules/Users/language/en_us.lang.php#L937

**Comment by horus68** [comment]
@likhobory can you please edit the issue title?
Those duplicated strings are now on the master/hotfix branch for 7.9.0

**Comment by likhobory** [comment]
OK, all links has been updated.
