### ISSUE TITLE
Request to specify the context for translation

### ISSUE THREAD

**Issue by maladrill** [salesagility/SuiteCRM#3448]
I am trying to translate LBL_PERFORM_CREATE_DB_2

But I need to know specific context.

It can be translated to polish in multiple meanings :-)

(na) on, for, to, at, in, of 
(w) in, at, on, into, by, upon 
(o) about, of, on, for, by, at 
(nad) on, above, by, beyond 
(po) on, in, at, by, for, upon 
(przy) at, with, by, on, to, upon 
(za) for, per, by, as, behind, on 
(przez) by, through, via, over, on, across 
(we) in, on, at, into, by, upon 
(u) at, with, from, of, on, by

https://crowdin.com/translate/suitecrmtranslations/591/engb-pl#15303

**Comment by pgorod** [comment]
It seems the only reference to that string is this line of code:
`/var/www/html/install/install_utils.php:675:    echo "{$mod_strings['LBL_PERFORM_CREATE_DB_1']} {$setup_db_database_name} {$mod_strings['LBL_PERFORM_CREATE_DB_2']} {$setup_db_host_name}...";`

so the sentence is going to look something like
`Creating the database SOMEDB on SOMEHOST.`

**Comment by maladrill** [comment]
Thank you
