### ISSUE TITLE
suite7 theme Problem with subpanels

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3460]
Subpanels are not aligned
#### Issue

I have an instance of suitecrm 7.8.3 running which was updated from SugarCRM CE 6.5.20 to 7.1,..... til 7.83. 
since 7.8 we have the problem that the view of subpanels in theme7 is not alligend correctly.
Here is the screenshot:
![grafik](https://cloud.githubusercontent.com/assets/16813374/25442083/575a233c-2aa4-11e7-8ded-0f58c79b2cb8.png)

The first subpanel looks right and all others are on the outerst left side.

I've tried to duplicate it in a fresh installation and i can reproduce it.
 
#### Expected Behavior

All subpanels should be alligned correctly
#### Steps to Reproduce

1.install a fresh instance
2. create an account and save it. Afterwards you can see the wrong positioned subpanels.
3.
4.

#### Context

Customer is  complaining about the ugly view. 
#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all browsers
* Environment name and version (e.g. MySQL, PHP 7): php 5.6.30
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by gunnicom** [comment]
I have the same problem. Additionally, if this occurs, if you sort within the first subpanel, the subpanel gets duplicated. Can anybody confirm this?
Only happens if object is loaded _not_ via AjaxUI. Then the html seems to be wrong, no "<ul>" and first subpanel without "<li>".
When the object is loaded via Ajax it seems to be fine.

**Comment by gunnicom** [comment]
Duplicate?
https://github.com/salesagility/SuiteCRM/issues/3355

**Comment by gunnicom** [comment]
This fixes it for me:
https://github.com/ale26/SuiteCRM/commit/26a51ca27fdc38cdbde1f380871c870d50773c44
