### ISSUE TITLE
 Illegal string offset 'cookie_name'

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3461]
After a fresh installation of suitecrm7.8.3  I got errors in apache error log
#### Issue

 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index
 PHP Warning:  Illegal string offset 'cookie_name' in /var/www/testinstance/cache/smarty/templates_c/%%E2^E2B^E2BC33C5%%SubPanelTiles.tpl.php on line 41, referer: https://test.local/testinstance/index.php?module=Accounts&action=EditView&return_module=Accounts&return_action=index

#### Expected Behavior

No errors in Error log
#### Possible Fix

doing this solved problem.
[https://suitecrm.com/forum/developer-help/10472-smarty-template-error-on-sub-panel]

#### Steps to Reproduce

1.Install a new instance 
2.create an account and look at afterwards in apache error log
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Fixed here: #3573
