### ISSUE TITLE
Suitecrm inbound group email not showing any emails

### ISSUE THREAD

**Issue by sonirules** [salesagility/SuiteCRM#3463]
The inbound email does not have any emails. I am receiving them in outlook or the main server but not in suite crm. I am set up the cronjob and scheduler properly. The personal email works fine. It is to do with the group email. I have also checked teh imap and smtp which is all ok

I am using Suitecrm version 7.8.3 and rest is all working apart from the inbound email. I am not sure what has gone wrong. I can see many people having the issue but no solution.

Appreciate help from some experts.

**Comment by samus-aran** [comment]
Hi @sonirules 

This is more of a question for the [forums](https://suitecrm.com/forum/index) where you will be guided by ourselves or the community to troubleshoot the issue.

Github is used for suggestions and core bug issues rather than individual instances set ups.
