### ISSUE TITLE
How to integrate ringcentral with with sugarcrm

### ISSUE THREAD

**Issue by sonirules** [salesagility/SuiteCRM#3464]
I would like to know how to integrate RingCentral softphone api with SugarCRM?

I am looking fro some plugin that can be uploaded in module loader and that can work.

Appreciate some advice

**Comment by mrbarletta** [comment]
@sonirules  - I am not aware of any existing plugin -  I did this once and was using their API and custom development inside SuiteCRM (log calls / search leads-contacts-accounts for phone number etc).

**Comment by sonirules** [comment]
@mrbarletta Please can you help me with the integration? Please. I would really appreciate your help and advise

**Comment by pgorod** [comment]
Guys, this is a discussions for the forums, not for Github... here you report bugs in the code. You should move this discussion to the forums and close the Issue...

**Comment by mrbarletta** [comment]
@pgorod you are right -   

@sonirules - Please, close the issue and post the link to a forum post in case anyone else finds this issue looking for info

**Comment by Dillon-Brown** [comment]
Hi @sonirules Thanks for the question! However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to the community forums.
