### ISSUE TITLE
Add Dashlet in Dashboard page doesn't work in PHP 5.6

### ISSUE THREAD

**Issue by Vinothbsetec** [salesagility/SuiteCRM#3466]
#### Issue
We are trying to add a new dashlet in the dashboard page, it displays the loading image only. What we diagnose is, the ajax function for dashlet is not triggered. So it keep displaying the loading image.

We are having live and demo environment. In demo, add dashlet is working without any issue. So we compared both servers. Demo having PHP version 5.4 and live environment having PHP version 5.6. To confirm the issue, we tested it in our local machine too. First we tested with 5.6 and the dashlet isn't working like live server. Then we downgrade the PHP version to 5.4 and then it is worked in the local.

Since SuiteCRM 7.7 requires PHP 5.5+, we can't downgrade PHP version in live server.

_Note:_ We also checked the issue #2370. I checked the fix 692838e also. We have this update. But still add dashlet causing this issue.

#### Expected Behavior
Should able to add new dashlets in all latest versions of PHP.

#### Your Environment
* SuiteCRM Version used: 7.7.9
* Browser name and version FireFox version: 53.0 (32-bit)
* Environment name and version (e.g. MySQL, PHP 5.6):
* Operating System and version: CentOS 7.x

**Comment by Dillon-Brown** [comment]
@Vinothbsetec I'm unable to replicate this on 7.8.9 with php 5.6. Do you think you could clarify further or maybe try and replicate this with a fresh instance?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
