### ISSUE TITLE
Help Text for field is not working in theme7

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3469]
#### Issue

I want to use the help text which should put an 'i' near the field in the edit view.
So I enter some text in the "help text" field via studio.
I also did a quick repair. But the 'i' near the field never appears. 
#### Expected Behavior

An 'i' should be presentated near the field and after klicking on it the help text should be displayed.
#### Actual Behavior

No 'i' is shown near the field
#### Steps to Reproduce

1.got to studio->accounts->fields->fax_number Fill in "Help Text"
2.run quick repair
3.Create or edit Account
4.

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  FF 53
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
@lehnerr Hi, the "Help Text" field in studio will not create an addition info popup that you would see on the listview. "Help Text" will show the text you placed in studio when you hover over the field.
