### ISSUE TITLE
Activate CodeReviewHub.com

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#3479]
#### Issue

Activate the free https://www.CodeReviewHub.com automatic code review, it offers follow up, analysis, test running status, reporting, much improved over the stock github code review, which is fully manual and overly laborious and time consuming.

Video demonstrating how easy it is - a few clicks - to add to this github project:
https://youtu.be/e6JPB0fct4w

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Activate CodeReviewHub.com](https://trello.com/c/HRXG9AlO/181-activate-codereviewhub-com)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
