### ISSUE TITLE
AOD results within a module differ from results 'Basic search'

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#3485]
#### Issue
When searching for a certain first name in global search, Basic search shows me two Contacts, but Advanced search shows me just one. Even tough this name is the first name of both Contacts shown in Basic search.
The module search (filter) shows two results as well.

Another issue is that with another search, the same Contact is show twice in Advanced search and just once (as expected) in basic search. I confirm it's the same Contact by checking the id of the Contacts.

Advanced search shows results from other modules as well, but that's not the point I'm trying to make.
This is about showing different results from the same module, while they clearly need to be identical.

#### Expected Behavior

Both search modes should show identical results within the same module.
So in this case, both Basic and Advanced search should show two Contacts with that first name and shouldn't show the same Contacts more than once.

#### Actual Behavior

Advanced search shows just one Contact, while Basic search shows both.
Advanced search shows a Contact more than once, while Basic search shows this Contact once.

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

I'm not sure how to make this reproducible, as it doesn't seem to happen to searches on all keywords (names).
Is there a way to check if this is an AOD index issue, or is this ideed a bug?

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 52
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1 + PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by pgorod** [comment]
The two searches are entirely different systems. There is probably no need for two systems, we should have just one (even if it has a number of search options or modes).

There have also been suggestions of dropping Lucene Search which seems to be deprecated.

So these paths would be preferable to just trying to fix differences between the output of the two systems...

**Comment by ebogaard** [comment]
Fair enough.
But if we focus on the facts as they are now: how do I explain to users that searching one way doesn't show all results and/or the same result twice?

If this is indeed an old or incomplete implementation of lucene: is there a planned to fix this?
Or will there be a migration to another engine?
Or will we need to revert to the old-style search?

**Comment by pgorod** [comment]
There was some discussion here #3352 but I don't know if that's is going anywhere...

I'll have to leave your other questions to Sales Agility folks, I don't know the answers...

**Comment by Dillon-Brown** [comment]
Raised as a suggestion in #3352. Currently this is the expected behaviour and not a bug.
