### ISSUE TITLE
When doing an advanced global search all pencils go to module > accounts except leads

### ISSUE THREAD

**Issue by billlee76** [salesagility/SuiteCRM#3488]
https://www.screencast.com/t/g3zuNnRCC

When doing a advanced search, we noticed that the pencil icons take you to Accounts instead of the related module EXCEPT for leads. 

#### Issue
The pencil icon takes you to the accounts module for every module under the advanced search except for leads. Leads works as expected.

#### Expected Behavior
I expect that when you click the pencil next to a contact that you would go to the edit view of a contact, or if you clicked the pencil next to the opportunites that i would go to the edit view of the opportunities.

#### Actual Behavior
All pencils icons take you to edit view of accounts instead of the actual module, except for leads.

#### Possible Fix
Update pencils to be the edit view of the module its in or hide pencils altogether might be an option. 

#### Steps to Reproduce

1. do an advance search that will bring up multiple results
2. click on the pencil next to a contact or a opportunity

#### Context
Its confusing to the users that the name of the contact or opportunity takes you to a different place than the pencil. As we do not use the accounts area, it is always empty. - Medium priority

#### Your Environment
SuiteCRM Version used: Version 7.8.3
Sugar Version 6.5.24 (Build 509)
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Ipad
Environment name and version (e.g. MySQL, PHP 7): mysql php 7
Operating System and version (e.g Ubuntu 16.04): nginx

**Comment by billlee76** [comment]
Any follow up to this?

**Comment by Dillon-Brown** [comment]
@billlee76 I'm unable to replicate this on 7.8.3. Is this still an issue you can replicate?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.

**Comment by billlee76** [comment]
Can we reopen please this issue still exists.

**Comment by billlee76** [comment]
I've been busy with other projects and will post it the video again with audio. Me describing the issue that is still happening. 

https://ama-atm.powerplaydestination.com/suite-issue.mp4

**Comment by Dillon-Brown** [comment]
Thanks for the detailed report :). Will re-open and do a bit more investigating to see if I can replicate this.

**Comment by willrennie** [comment]
I've been unable to replicate this issue in the latest 7.8.x release. If this is still an issue we can re-open and investigate further.

**Comment by billlee76** [comment]
Im affraid this has reared its ugly head again...
Version 7.11.1
Sugar Version 6.5.25 (Build 344)  in both leads and opps on a global search, pencils link to accounts  where as clicking on name goes to either lead or opp  https://www.screencast.com/t/0w48e9G55G

**Comment by billlee76** [comment]
> I've been unable to replicate this issue in the latest 7.8.x release. If this is still an issue we can re-open and investigate further.

see my comment.. its happening again. :(
