### ISSUE TITLE
For 1272 error you have to fix modules/AOR_Reports/AOR_Report.js file also (click event for export and update buttons)

### ISSUE THREAD

**Issue by nlv** [salesagility/SuiteCRM#3493]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
