### ISSUE TITLE
what does it mean "no mode specified" error

### ISSUE THREAD

**Issue by jacksparo21** [salesagility/SuiteCRM#3494]
i'am working on windows server 2012 r2, IIS, my problem is when i try to install a language package via the module loader, when i click install the error pop-up with "no mode specified". 
is-it a bug in suitecrm, do you have a clue.

**Comment by horus68** [comment]
Please do not cross post forum and git.
First you need to see if it is just with you or is it a problem for others too (Forum would be the place)
If it is a problem for others AND can be considered a bug then github is the place to report
Your forum topic: https://suitecrm.com/forum/international-language-support/14032-what-does-no-mode-specified-error-means-in-suitecrm#46996
Please close this issue until evidence it could be a bug

**Comment by jacksparo21** [comment]
thank you for your replay it's my first time using github forum, i didn't know the rules.
that topic  was posted by  me actually :)
