### ISSUE TITLE
SugarBean - array_seach function doesn't use strict parameter

### ISSUE THREAD

**Issue by ajedvaj** [salesagility/SuiteCRM#3499]
#### Issue

Storyline is as follows:
I tried to create WorkFlow with SendEmail action on custom module. For the recipient TO field I wanted to set it to Related field (that actual field is custom field and it's checked as required). However this field doesn't show in list, so I dig into the code to see where is the issue...

There should be field named 'Budget Manager' in dropdown list:
![emal_relate](https://cloud.githubusercontent.com/assets/18736912/25657557/c7e9d584-2ffe-11e7-8969-cbc68c123879.png)

The definition of field:
![field_def_relate](https://cloud.githubusercontent.com/assets/18736912/25657621/0a534a22-2fff-11e7-9a87-9c94c53ba683.png)

The snippet of field def as php array during execution:
![fielddef](https://cloud.githubusercontent.com/assets/18736912/25657847/28026570-3000-11e7-9fe0-e64f76be2f5e.png)

It truns out that **get_related_fields()** function from **SugarBean** class gets called and in this function there is a code snippet:
```php
foreach ($fieldDefs as $name => $properties) {
                if (array_search('relate', $properties) === 'type') {
                    $related_fields[$name] = $properties;
                }
            }
```
Since there is no $strict parameter there is no type comparison.
This results that `array_search('relate', $properties)` will return `'required'` in my example above probably because `'relate' == true` results in `true`. This then results in if condition `'required' == 'type'` which is then false and field doesn't get populated in $related_fields array 

 
#### Expected Behavior

There should be strict type checking parameter in call to array_search() function. With that the field won't be skipped because it's required.

#### Actual Behavior

There is no strict type checking parameter which results that the field is skipped.

#### Possible Fix

```php
foreach ($fieldDefs as $name => $properties) {
                if (array_search('relate', $properties, true) === 'type') {
                    $related_fields[$name] = $properties;
                }
            }
```
#### Steps to Reproduce

1. Create Relate field to Users module and set check the Required box
2. Create new Workflow with Send Email action
3. In recipient list select 'To' - 'Related Field'
4. The newly created relate field will be missing from list.

#### Context

I cannot create Workflow to send email because the user is missing from dropdown list.

#### Your Environment

* SuiteCRM Version used: 7.7.8 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.50, PHP 5.5.9-1ubuntu4.19
* Operating System and version (e.g Ubuntu 16.04): Mint 17.1

**Comment by chris001** [comment]
Excellent find!  Have you ever made a Pull Request before??  This bug fix is a one liner, it'd probably be accepted right away.

**Comment by ajedvaj** [comment]
No I have never done Pull Request before, but I will find out how to do it and create one.

**Comment by chris001** [comment]
OK, if you search the Issues section for How to do a pull request, I previously explained how to do it step by step recently.  Basically just make sure you switch to the "Hotfix" branch of this repo before you go to the file you need to change, and hit the "pencil icon".

**Comment by ajedvaj** [comment]
Ok, great. Thanks for the instructions, I have successfully created Pull Request:
#3503
