### ISSUE TITLE
Not translatable values in Activities/Popup_picker.php (develop branch)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3504]
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Activities/Popup_picker.php#L143
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Activities/Popup_picker.php#L193
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Activities/Popup_picker.php#L247
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Activities/Popup_picker.php#L288
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Activities/Popup_picker.php#L312
.....

![default](https://cloud.githubusercontent.com/assets/5983672/25692987/1581cef4-30af-11e7-986f-b6d4c4061269.png)

**Comment by likhobory** [comment]
Meeting status is not translated yet.

![default](https://cloud.githubusercontent.com/assets/5983672/25698389/51ce8dc6-30c7-11e7-8896-727878f01372.png)

**Comment by samus-aran** [comment]
@likhobory - If able can you raise issues with the PR in the actual PR so we don't miss them in the issue itself.  Thanks.

**Comment by likhobory** [comment]
Done.
