### ISSUE TITLE
reports - Blank pdf template when there are 2 conditions parameters

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#3506]
#### Issue

PDF export of a report containing 2 contional parameters does not include the report table. 

#### Expected Behavior

report table should be included in PDF 

#### Actual Behavior

no report table in PDF

#### Steps to Reproduce

- create a report 
- Add fields 
- Add 2 conditions and check "parameter", ie "created date is greater than value" and "created date is less than value" 
- save the report 
- in the report view change the 2 conditions and update the report.
- action -> "download pdf" 
result: PDF does not contain the report table. 
the table is OK with no or 1 parameter. 

#### Context

cannot let users create report of cases opened between 2 dates. 

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
this is reproducible in the DEMO instance 
https://suitecrm.com/demo

**Comment by boombata** [comment]
just noticed that if the report result is having multiple pages (not on the pdf but on the report view) and you click next page the next page is blank. again no problem if there is none or one condition parameter. both behaviors are probably linked.

**Comment by ChangezKhan** [comment]
Hey @boombata , can you provide screenshot of your report? It would be much easier to replicate the same.

**Comment by boombata** [comment]
@ChangezKhan please find the screenshot from the test instance here attached
![selection_290](https://cloud.githubusercontent.com/assets/8605061/26717408/97402f5a-477d-11e7-8456-41d6c64e5366.png)

**Comment by ChangezKhan** [comment]
One thing I have to mention here that, if I test this on demo instance, it reproduces the error, but if I test it on local instance, I couldn't reproduce the error. 
@boombata can you please check it on your local instance, if possible?

**Comment by natemccallum** [comment]
I believe I'm having this same issue. I am using 7.8.3. With 2 parameterized conditions I get a blank report, with just 1 it runs. I need 2 parameters for a date between report context. Additionally, without the custom code mentioned here [https://suitecrm.com/forum/developer-help/6976-report-module-doesn-t-export-in-pdf-or-csv-with-the-users-params](url) I get no headers on the report.

Any updates on the 2 parameters issue?

**Comment by boombata** [comment]
@ChangezKhan I confirm local instance have the same behavior.

**Comment by ChangezKhan** [comment]
@boombata , ok, let me check one more time.
