### ISSUE TITLE
creating file module using module builder works but  not able to create records using the created module

### ISSUE THREAD

**Issue by nadilhassan** [salesagility/SuiteCRM#3512]
#### Issue

I have created file module using module builder and I deployed that module into my SuiteCRM. When I try to create a record using that module it shows the error saying "There was an error processing your request, please try again at a later time." in a popup.

#### Expected Behavior

It should be able to insert a record.

#### Actual Behavior

A popup with an error message is showing

#### Possible Fix

Hope this can be fixed. I found the root cause of the problem in view.edit.php file which is located SuiteCRM/modules/mymodule/views/. In that view the generated code likes look.

"class <module_name > ViewEdit extends ViewEdit{"
but it should be like this
"class mymoduleViewEdit extends ViewEdit{"

After changing the line of the code, The module works well.

#### Steps to Reproduce

1. Go to module builder in admin
2. Create a module based on file
3. Deploy the module to the CRM
4. Go to module from the menu
5. Click "Create" button then it will show a pop up.

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 57.0.2987.133 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MSSQL
* Operating System and version (e.g Ubuntu 16.04): Windows Server

**Comment by nadilhassan** [comment]
anyone tested this...?

**Comment by mlorcam** [comment]
I had the exact problem after creating a simple package containing just one module based on File template (lets name it "**MyFileModule**"), and after 2 days of fight I encountered the same wrong code line.
I just replaced "class _**<module_name > ViewEdit**_" with "class **_MyFileModule_ViewEdit_**" (don't forget the **underscore** between "MyFileModule" and "ViewEdit") and finally all worked fine.

By the way, I had this problem in SuiteCRM version 7.8.3, using PHP v5.4.45 and MySQL v5.6.35-cll-lve on x64 Virtual Server from LiveHost.

**Comment by angeloio** [comment]
Exactly the same problem!

I created too a simple package containing just one module based on File template via module builder.
Deployed the package then added one relationship in Studio.
I tried to create a new record and got apache 500 error in return.

Apache error logs report:
_AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '<', expecting identifier (T_STRING) in /opt/bitnami/apps/suitecrm/htdocs/modules/pmnt__Payments/views/view.edit.php on line 45\n', referer: http://......................et:8987/?action=ajaxui_

Went into the file and saw the problematic line:
**class <module_name > ViewEdit extends ViewEdit{**

Running SuiteCRM version 7.8.3 bitnami virtual machine.
PHP 5.6.27
MySQLi Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $<BR>MySQLi Host Info: Localhost via UNIX socket<BR>MySQLi Server Info: 5.6.34<BR>MySQLi Client Encoding: utf8<BR>MySQL Character Set Settings: character_set_client = utf8, character_set_connection = utf8, character_set_database = utf8, character_set_filesystem = binary, character_set_results = utf8, character_set_server = utf8, character_set_system = utf8

**Comment by Dillon-Brown** [comment]
Fix here: 3678
