### ISSUE TITLE
Listview counter is not working, it shows negative values

### ISSUE THREAD

**Issue by ana-samoila** [salesagility/SuiteCRM#3514]
When you go to any Listview and you select an item, then you go to "next page", the counter resets.
If you go back to the first page you will see that the selection is maintained. But the counter doesn't work. If you deselect the selected item, the counter will say "Selected:-1".
It is clearly a bug because the counter should never display: "Selected: -1 items"

#### Steps to Reproduce
1. Go to a list view and select 3 records.
![image](https://cloud.githubusercontent.com/assets/28138802/25737357/f7fcdaaa-317f-11e7-9a13-269965c8d3ee.png)

2. Go to next page. You will see that the counter was reseted (but the selection is maintained in backend)
![image](https://cloud.githubusercontent.com/assets/28138802/25737388/36f992f2-3180-11e7-8b90-183da88af298.png)

3. Go back to the first page. Again, the counter was reseted but you can see that the 3 items remained selected
![image](https://cloud.githubusercontent.com/assets/28138802/25737414/5f98b06c-3180-11e7-9e54-ab8fa2a2f7ea.png)

4. Deselect the 3 items. The counter shows negative values:
![image](https://cloud.githubusercontent.com/assets/28138802/25737434/7eb48534-3180-11e7-9777-a5dc77ae0cb1.png)

#### Context
I suggest this as high priority

#### Your Environment
* SuiteCRM Version used: 7.8.1

**Comment by immhub** [comment]
Same here,

Please help.

**Comment by Dillon-Brown** [comment]
@ana-samoila Duplication of issue below:

#3330

**Comment by consulting123** [comment]
Values selected in list view after clicking on pagination for next/previous page are no longer maintained.
please Help
