### ISSUE TITLE
Custom module and relationship issue with built in module!

### ISSUE THREAD

**Issue by itglaafs** [salesagility/SuiteCRM#3525]
Filtered out data using custom field that is created by a many to one relationship, does not export any data, it sorts and filters and you can import data using same field, but export does not work at all, and when you look for the field in Contacts module it does not exists.

#### Issue

Hi all,

I have been trying to export data from Contacts but filtered out with custom module field.

Relationship between Contacts and Custom module is many to one and custom field is showing in Studio fields and other sections as a part of Contacts. The field from custom module is showing in filter section and you can sort and filter out without a problem, but export does not work properly.

There are 2 problems with export, First, when exporting up to 100 records, I can get csv file but the custom field (from other Custom module) that should be in Contacts due to relationship rule is not present. This is strange since you can filter out by that fields in advance filter section in Contacts.

Second problem is, when you filter out records and they are showing numbers above 100, the page goes blank after you start exporting and you can't get csv file at all.

<code>

MySQL error 1054: Unknown column 'hn_pr_hearnow_projects_contacts_1_name' in 'where clause'

</code>

SuiteCRM log shows that column or custom fields does not exist at all. and you can see that filtering works in screenshot.

![crmcustomfield-contactsexportproblem](https://cloud.githubusercontent.com/assets/22226663/25845615/eac5dc36-34f1-11e7-95fd-805a11f64cdf.jpg)

Best Regards,

Slaven. 

#### Expected Behavior

It should create same relationship as for example Users and Contacts. There is assigned to field that you can filter out data with, export it and import in Contacts module.

#### Actual Behavior

Custom relationship does not creates field in dependent built in module as it should.

#### Steps to Reproduce

Please follow the video below:

http://screencast-o-matic.com/watch/cbhQ65XO46

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox, Chrome , any browser. All up to date.
* Environment name and version (e.g. MySQL, PHP 7): Mysql 5.6.35, PHP 5.6.30 
* Operating System and version (e.g Ubuntu 16.04): Linux, Cpanel

**Comment by Dillon-Brown** [comment]
Unable to replicate with latest LTS. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
