### ISSUE TITLE
403 error while navigating through listview pages

### ISSUE THREAD

**Issue by immhub** [salesagility/SuiteCRM#3526]
#### Issue
When I click on a module and hit next page in list view i get 403 error.

#### Expected Behavior
Navigate to the next page and list in listview next 20 entry's

#### Actual Behavior
403 Error
#### Possible Fix
No ideea
#### Steps to Reproduce

1. Click on a module
2. Hit next page in list view
3. Hit next page again or back one page
4.

#### Context
The error from Google Chrome console : 
sugar_grp1.js?v=TTIWRGv-KV_NiecCjwgdkg:382 POST http:/.../index.php 403 (Forbidden)

#### Your Environment
Suitecrm 7.8.1
Chrome Browser

**Comment by pgorod** [comment]
I recommend that you post about this in the forums, not here. At least you need to troubleshoot a little, and get help finding any errors in your logs, web server config, etc., before you can post it as a bug. And that work is best done in the forums.

**Comment by Dillon-Brown** [comment]
Hi @immhub We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our  [Community Forum](https://suitecrm.com/forum). We will be able to help you with your specific issue there. Thanks.

**Comment by immhub** [comment]
I have some post on Community Forum that is not answered for 1 mounth. I think that this is not a solid support forum for that reason. 
My post on github is because on the community forum no one answers and i had hope that you will. Sadly i am bounced back an forward. Thank you for the quick replay anyway.

https://suitecrm.com/forum/suitecrm-7-0-discussion/14114-403-error-while-navigating-through-listview-pages

https://suitecrm.com/forum/feedback/13805-selection-in-listview-is-lost-after-applying-quick-filter

**Comment by pgorod** [comment]
@immhub we're basically the same people here and on the forums. :-)

I'm sorry you didn't get answers there. It happens sometimes. Sometimes we don't know the answer, sometimes we're too busy. It's a "community support" forum, so people there are ordinary users like you and me. Sometimes SalesAgility employees also help out. But obviously an open-source free product can't provide a "solid support forum" like if you were using a payed product, so you have to be patient...

But I believe after almost 1000 posts I did there on the forums (as user `pgr`) it's not fair to say "no one answers". :-)

See you there in your new post!

**Comment by pgorod** [comment]
@immhub we're basically the same people here and on the forums. :-)

I'm sorry you didn't get answers there. It happens sometimes. Sometimes we don't know the answer, sometimes we're too busy. It's a "community support" forum, so people there are ordinary users like you and me. Sometimes SalesAgility employees also help out. But obviously an open-source free product can't provide a "solid support forum" like if you were using a payed product, so you have to be patient...

But I believe after almost 1000 posts I did there on the forums (as user `pgr`) it's not fair to say "no one answers". :-)

See you there in your new post!

**Comment by ana-samoila** [comment]
Thank you @pgorod for the solution given on the forum!
https://suitecrm.com/forum/suitecrm-7-0-discussion/14114-403-error-while-navigating-through-listview-pages
You rock ;-)
