### ISSUE TITLE
Studio - Delegates Subpanel not loading

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#353]
Opening the delegates subpanel in studio gives the following in the firebug console on firefox:

    TypeError: studiotabs.fields[("subslot" + (msi - 1))] is undefined

In addition, if you then attempt to navigate to the expenses subpanel using the left hand menu you get a 500 error from the server.

Tested in 7.2.2

**Comment by willrennie** [comment]
Fixed in 7.4.x and later.
