### ISSUE TITLE
Email compose in 7.9 beta - top menu shows below the smaller menu in "to", "cc" and "bcc" fields

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3531]
Basically this is a minor z-index issue best described by this screenshot:

![zindex](https://cloud.githubusercontent.com/assets/15945027/25892814/83be0050-356d-11e7-91d0-e3d8261bc2e6.jpg)

The top-menu should show on top of the other smaller menu, so people can see (and choose) every option there.

#### Steps to Reproduce

1. Compose email
2. Click inside a field like "to", "cc", or "bcc": a small menu opens along the top of that field, so you can add Contacts, Leads, etc.
3. Click the top application menu (it will overlap, at least if the page is scrolled down a bit and the menu is a long one).

#### Your Environment

* SuiteCRM Version used: 7.9 beta, possibly with some other more recent email-related PR's pulled directly from Git
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox latest
* Environment name and version: PHP 7
* Operating System and version: Ubuntu 16.04

**Comment by pgorod** [comment]
It just occurred to me that maybe a better way to fix this, instead of just tweaking the z-index, would be to hide the smaller menu whenever the user clicks outside that field. The menu is helper to fill the field, and only appears when you click inside it, so it should disappear when the user goes somewhere else, whether it's by clicking the main menu, or any other place.

**Comment by daniel-samson** [comment]
@pgorod 

Changing the z-index is good enough. It may be possible to use the bootstrap events to hide the qtip.

See: http://getbootstrap.com/javascript/#dropdowns-events

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this in 7.9.x. If this issue still exists and you can provide more information for us to proceed then it can be reopened. Thanks.
