### ISSUE TITLE
Image field is not saving from sub panel quick create, when image field is made as required field

### ISSUE THREAD

**Issue by nadhiyahisham** [salesagility/SuiteCRM#3546]
#### Issue

We are using latest version SuiteCRM (7.8.3). When are making an image field as mandatory, the record is not able to save in Sub panel Quick Create screen. But able to save the record from Full form Edit view.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
@nadhiyahisham I'm unable to replicate this on 7.8.3.

Accounts module contact subpanel quick create with mandatory image:
![issue-3546-1](https://cloud.githubusercontent.com/assets/26431166/26003762/8a221066-372b-11e7-97b0-9068ef4731a0.png)

Image is correctly saved:
![issue-3546-2](https://cloud.githubusercontent.com/assets/26431166/26003770/917ceda4-372b-11e7-9e09-fc419a9de897.png)

Could you provide more information or see if you can replicate this on a fresh instance?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
