### ISSUE TITLE
Add ['merge_filter']='enabled/disabled' support in studio

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3547]
Add ['merge_filter']='enabled/disabled' support in studio.
This is a suggention.
Forgive my poor  English.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ['merge_filter']='enabled/disabled' support in studio](https://trello.com/c/yFlmjx45/182-add-merge-filter-enabled-disabled-support-in-studio)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
