### ISSUE TITLE
Add "Email Contract" Action in the detail view of the Contracts module

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3548]
Add "Email Contract" Action in the detail view of the Contracts module.
Similar to the Quotes module.

This is a suggention.
Forgive my poor English.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Email Contract" Action in the detail view of the Contracts module](https://trello.com/c/0FBrDuSd/183-add-email-contract-action-in-the-detail-view-of-the-contracts-module)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
