### ISSUE TITLE
Conditions missing on outbound email search for current user

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3549]
#### Issue
The system cannot find the correct outbound email record

#### Expected Behaviour
Load the correct outbound email record

#### Actual Behaviour
It loads the default outbound email record of type='system'

#### Possible Fix
file: include/OutboundEmail/OutboundEmail.php
function: getUserMailerSettings()
add these conditions in the where clause:
**deleted = 0 AND type = 'user'**

#### Your Environment
* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 58 (64-bit)):
* Environment name and version (e.g. MySQL 5.7, PHP 7.0):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
@muratyaman Just to confirm, is this also including ticking and unticking the box within email settings smpt for allowing a user to use the system email address?

With a user/pass set and this box left unticked I am presented with an unknown user/pass popup and am not able to send an email with the system account.

**Comment by muratyaman** [comment]
I am not sure about the side-effects of that setting but..

If there are multiple OutboundEmail accounts created by a user (e.g. admin - user ID: 1) the system selects the incorrect record. That's why we need to include additional conditions.

Thanks.

**Comment by muratyaman** [comment]
UPDATE:

actually where clause should include:

`deleted = 0 AND type IN ('user', 'system-override')`

After new user account is created and the user logs into the system for the first time, the configuration wizard creates an outbound email account of type 'system-override'.

So, to make sure we use the correct record, we have to be careful with the criteria here.

**Comment by sergio91pt** [comment]
@muratyaman While your SQL is safe (the code is missing the deleted check), you'll probably run into the same problem if you configure 2 (user) email accounts.

The fix for #3645 should resolve your problem: #3647
