### ISSUE TITLE
Ability to build modules via Module Builder

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#356]
Recently implemented functionality for Inline Editing has meant the generation and deployment of Modules utilising the Module Builder tool does not work in SuiteCRM 7.3.x. This can cause usability issues within the CRM.

**Comment by gunnicom** [comment]
Dont know, but maybe my pull request fixes this. Maybe you can try:

https://github.com/salesagility/SuiteCRM/pull/354

**Comment by willrennie** [comment]
Fixed in SuiteCRM 7.3.1.
