### ISSUE TITLE
Queries logged in multiple lines.

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#3560]
#### Issue

SuiteCRM records one system action in more than one log line.
	

#### Expected Behavior
Each log line should represent one (and only one) system action.
A log line with a query should be recorded this way:

     Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0     AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0

#### Actual Behavior
The previous log line is recorded in more than one line:

     Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0

     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0

     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0

     AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0

#### Possible Fix
Remove the breaks lines from the queries before they are executed and registered in the log

#### Steps to Reproduce
Just run SuiteCRM and watch the log ;-)

#### Context

When you are debuging it is **VERY annoying** that the queries (and other system actions) are recorded in the log in several lines.
That's not a style thing it's a productive one... with queries in several lines using unix tools (cat, grep, awk, sort, wc, etc, etc) is a headache

#### Your Environment

* SuiteCRM Version used: Any
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any
* Environment name and version (e.g. MySQL, PHP 7): Any
* Operating System and version (e.g Ubuntu 16.04): Any

**Comment by pgorod** [comment]
I ran out of icons to show my appreciation for this PR, but really, anything to make debugging less painful is really helpful. And you say very correctly, this is not just a question of style, but of productivity.

I really hope they get merged soon, like this other great initiative related to logging: #3486. 

Also #3401 !

Thanks!

**Comment by Abuelodelanada** [comment]
@pgorod thank you! I spend a lot of time looking at the log....

Great post !
