### ISSUE TITLE
InboundEmail entity/model class is doing too much: 6643 lines on master branch

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3561]
#### Expected Behaviour
It has to extend/implement only SugarBean and some relevant functions.
Many functions must be implemented by separate classes
esp. email management functions related to POP3 and IMAP
so that we can maintain and extend the features easily.
e.g. replace IMAP layer with a HTTP API
We must aim for smaller functions and classes:
[http://swreflections.blogspot.co.uk/2012/12/rule-of-30-when-is-method-class-or.html](http://swreflections.blogspot.co.uk/2012/12/rule-of-30-when-is-method-class-or.html)

#### Actual Behaviour
https://github.com/salesagility/SuiteCRM/blob/master/modules/InboundEmail/InboundEmail.php
Includes/implements so much code.
here is a short list of almost 170 functions

- InboundEmail::getFormattedRawSource()
- InboundEmail::convertToUtf8()
- InboundEmail::getFormattedHeaders()
- InboundEmail::emptyTrash()
- InboundEmail::importMessages()
- InboundEmail::checkEmail()
- InboundEmail::fetchCheckedEmails()
- InboundEmail::search()
- InboundEmail::retrieve*()
- InboundEmail::save*()
- InboundEmail::*IMAP*() many IMAP functions
- InboundEmail::*Pop3*() many POP3 functions
- InboundEmail::*Cache*() many Cache functions
- InboundEmail::*Mailserver() connect/disconnect etc.
- InboundEmail::*Folder() rename, delete etc.

etc. etc. !!! You get the idea :(

Also, it is polluted with a function and two classes:

- function this_callback
- class temp
- class Overview

#### Possible Fix
Many functions must be implemented by separate classes
e.g. ImapManager, Pop3Manager, EmailParser, CacheManager, FileSystemObject, etc.

#### Your Environment
* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 58 (64-bit)):
* Environment name and version (e.g. MySQL 5.7, PHP 7.0):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by chris001** [comment]
You're right, a refactoring is needed there.  It shouldn't re-implement its own php imap email library, better to call the email library functions provided by a 3rd party library package like `php-imap`.

Also, it shouldn't be playing with HTML and using the HTML templates classes.  It should just return text results, for the view to output the css and js plus this text content in the HTML template.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [InboundEmail entity/model class is doing too much: 6643 lines on master branch](https://trello.com/c/03OSDlSg/184-inboundemail-entity%2Fmodel-class-is-doing-too-much%3A-6643-lines-on-master-branch)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
