### ISSUE TITLE
Calendar item pop when hover, but do not close (not sure whether bug or my problem)

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3564]
Hovering over a calendar entry (single,week,month) a pop-up will show more details.
When moving away the pop-up will not close, you must press X.

#### Issue

Hovering over a calendar entry (single,week,month) a pop-up will show more details.
When moving away the pop-up will not close.
I would expect it to close automatically when you move away from the day/entry, but it does not.
I am not sure whether this is the intended solution by the person who wrote this.

#### Expected Behavior

when you move away from the day it should close automatically.

#### Actual Behavior

It stays open until you press x.

#### Possible Fix

I need to understand first whether this is a feature and intentionally coded this way, so it would NOT be a bug ...

If it IS coded intentionally this way I would be prepared to write the code for it to have a check icon to make BOTH possible.

#### Steps to Reproduce

1. open the calendar
2.have some items in the calendar
3.hover over one of them, pop-up will show more details
4.move away from entry, pop-up will stay.

#### Context

It's just annoying you have to press the X to close it.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest firefox 53.02
* Environment name and version (e.g. MySQL, PHP 7): N/A
* Operating System and version (e.g Ubuntu 16.04): N/A

**Comment by Dillon-Brown** [comment]
Issue #3756 is a duplicate. Will close this one as #3756 already has a proposed fix for calendar and studio popups.
