### ISSUE TITLE
Stacked bar chart translation

### ISSUE THREAD

**Issue by maladrill** [salesagility/SuiteCRM#3572]
While translating SuiteCRM in crowdin.com I found that there are two occurences of Stacked bar -(['aor_chart_types']['stacked_bar'], and ['LBL_RENDERERS_STACKED_BAR_CHART']
and one occurrence of Stacked Chart - ['chart_strings']['stackedchart']

Is there any difference between them? Does it relate to the stacked bar chart in every case?

**Comment by horus68** [comment]
Just adding some details, not answering your question.

`$app_list_strings['aor_chart_types']['stacked_bar'] = 'Stacked bar';`
/include/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/language/en_us.lang.php#L3362

chart_strings array
`        'stackedchart' => 'Stacked Chart',`
/include/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/language/en_us.lang.php#L960

**Comment by horus68** [comment]
@Dillon-Brown requesting a language label for this!

**Comment by Dillon-Brown** [comment]
Don't think this would be an issue. 

`$app_list_strings['aor_chart_types']['stacked_bar'] = 'Stacked bar';` is used in AOR_Chart.php.
'stackedchart' => 'Stacked Chart',`. Is used in SugarChart.php.
I can't seem to find LBL_RENDERERS_STACKED_BAR_CHART so i'm assuming it's been removed.

**Comment by horus68** [comment]
> I can't seem to find LBL_RENDERERS_STACKED_BAR_CHART so i'm assuming it's been removed.

@Dillon-Brown  see modules/Spots/language/en_us.lang.php
`'LBL_RENDERERS_STACKED_BAR_CHART' => 'Stacked Bar',`
https://github.com/salesagility/SuiteCRM/pull/5452/files#diff-d518d8b6b9e2bed7367bf7b6e2a7747fR200

Stacked Bar, Stacked Chart would be the same for "Stacked bar chart". 
But for translators (and userguides creators) it would be better to have same value in different places
