### ISSUE TITLE
 PHP Notice:  A non well formed numeric value encountered in SUITECRM/include/ListView/ListViewSmarty.php on line [102|108]

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#3577]
PHP Notice:  A non well formed numeric value encountered in SUITECRM/include/ListView/ListViewSmarty.php on line [102|108]

#### Issue

The problem is related to the WIDTH parameter passed in the function process of class  ListViewSmarty.php
If the width parameter is passed in pixel (i.e. 10) all is fine an the calculation continues without exception and correctly. If the width parameter is passed as a percentage the error happens and the calculation does not produce the correct values.

#### Expected Behavior

Well this is tricky. In real terms the programmer of ANY module should provide a pixel width and not a percentage ... that WAS fine for the OLD way of creating web displays. These days everything is responsive so you should use a percentage!
So thinking about this the class function "process" would need to be re-written to make it possible to specify width parms in %, ie 10%.

#### Actual Behavior

a PHP notice is raised but ALSO incorrect values are calculated!

#### Possible Fix

Tricky again ... needs to be decided as part of the direction SuiteCRM is taking and the code needs to be changed accordingly ....

#### Steps to Reproduce

1. click on contacts
2. wait for the list to come up
3. check the PHP log, its full of "A non well formed numeric value encountered ...."

#### Context

Well the display of the columns is skewed as the values in the function "process" are not evaluated correctly.

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7): N/A
* Operating System and version (e.g Ubuntu 16.04): N/A

**Comment by chris001** [comment]
You could update the function to detect incoming percentage parameters and handle them.

Note, this is an old way of generating HTML templates in PHP on the server, and should be upgraded, sooner or later, to responsive CSS3 templates handled by the browser.

**Comment by jobst** [comment]
@chris001 done updating, fix proposed. Not sure whether I messed up the branches - still getting used to this - sorry.

**Comment by chris001** [comment]
@jobst You merged your changes into your own fork, that's the first step, now, you need to make a PR from your fork to this repo.
1. Go to your repo.  
2. Click Code tab.
3. Click Compare (right side of page).
4. Select `SalesAgility/SuiteCRM:hotfix` and `jobst/SuiteCRM:hotfix` (assuming your used the hotfix branch of your form).
5. Create PR.

**Comment by jobst** [comment]
THX, this is not the problem, sorry.
I have been working on a few things at the same time ... all in one clone of SuiteCRM but in many different files (look at all of my issues), I also had to revert one change as I realized it was not required.
When I am trying to get ONE issue (like the changes for ListViewSmarty.php) for ONE PR, I can't do that as it seems there are always ALL of the files I made changes to (during the day) part of the new PR.
I can see all changes separately as they have all different names, e.g. jobst-ListViewSmarty-1, but as soon as I issue a PR they are ALL part of that PR, and that's not what I want and it would be confusing for the person to read as they are not related.
So how can I get ONE of the files I changed, e.g. branch jobst-ListViewSmarty-1, to be part of a PR and not all the other changes?

**Comment by chris001** [comment]
@jobst You'd need to keep your each set of changed files (for each PR you make) in its own branch in your repo, don't merge them into your own fork's master branch, nor merge them into your hotfix branch.
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by connorshea** [comment]
Seems like this was fixed by #5162?
