### ISSUE TITLE
Letter to PDF [Language]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3578]
#### Issue

File /include/language/en_us.lang.php has a "Generate Letter" language value when all other code is 
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/language/en_us.lang.php#L3478

This is used in Contacts, Leads and Accounts modules

#### Expected Behavior

A `Print as PDF` value
#### Actual Behavior

`$app_strings['LBL_GENERATE_LETTER'] = 'Generate Letter';`

#### Possible Fix

Dirty fix: Change the language value to
`$app_strings['LBL_GENERATE_LETTER'] = 'Print as PDF';`

Or a proper fix:  change the occurrences of the language key `'LBL_GENERATE_LETTER' ` in code file to `'LBL_PRINT_AS_PDF'` and edit the file /include/language/en_us.lang.php accordingly to add the string:
`$app_strings['LBL_PRINT_AS_PDF'] = 'Print as PDF';`

#### Context

Language consistency. Reported also by @a277913835

#### Your Environment

* SuiteCRM Version used: Hotfix branch

**Comment by cjmny** [comment]
This fix may have prevented the "Print as PDF" item from appearing in the Accounts in 7.8.5.

**Comment by horus68** [comment]
@cjmny can you create a new issue on this? Include version and pics for it (and refer to this issue too)
