### ISSUE TITLE
Module FP_events

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3582]
If you click one of "EVENTS records" detail view-> DELEGATES->Select Delegates ->Send Invites
 and then click other link in the DELEGATES, the screen will turn gray.

**Comment by horus68** [comment]
Please edit this issue title so it related to the module FP_events, as in
"Error translating string from FP_events"

What is the error you got?
So the difference on your translated values is a dot and a space in the end? What if you remove the ending space?


The english string, for reference
    'LBL_MANAGE_POPUP_ERROR' => 'No delegates have been selected.',
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/FP_events/language/en_us.lang.php#L96

**Comment by a277913835** [comment]
Yes, the difference is a dot at the end.  In Chinese language usually use "。" instead.

**Comment by horus68** [comment]
@samus-aran I can't help on this one!

**Comment by a277913835** [comment]
Sorry, my fault. 
If you click one of "EVENTS records" detail view-> DELEGATES->Select Delegates ->Send Invites
and then click other link in the DELEGATES, the screen will turn gray.   @horus68
