### ISSUE TITLE
Blank page after SuiteCRM 7.3 install with spanish language

### ISSUE THREAD

**Issue by rgarcia-tcnx** [salesagility/SuiteCRM#359]
Fresh SuiteCRM 7.3 installation with spanish language cause blank page and this error message in apache log:

PHP Parse error:  syntax error, unexpected ')' in custom/modules/Calls/Ext/Language/es_es.lang.ext.php on line 25

Problem is in custom/Extension/modules/Calls/Ext/Language/es_es.Reschedule.php line 12, last comma must be removed.

**Comment by cmarrero** [comment]
Hi, 
I can confirm this issue 
Related to #358 
Regards
