### ISSUE TITLE
Cannot edit document module search layout in studio due to "An error has occured" error

### ISSUE THREAD

**Issue by GeekyWebMistrss** [salesagility/SuiteCRM#360]
When you access Documents>Layout>Search and then "Popup listview" or "popup search", there is an error window that says "An error has occurred" error. Issue first noticed on 7.2.2 and then upgraded to 7.2.3 and now using 7.3 the issue is still there. Cannot edit the module layout.

**Comment by willrennie** [comment]
Resolved in 7.4.x and later
