### ISSUE TITLE
Unused language strings (securityGroups)

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3602]
See #2444

'LBL_MAKE_POST'
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/SecurityGroups/language/en_us.lang.php#L77

**Comment by likhobory** [comment]
@horus68 
I'll add an issue with additional unused language strings after merging PR #3550

Example (for SecurityGroups):

'LBL_MODIFIED_ID'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L11

'LBL_CREATED_ID'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L14

'LBL_LIST_USER_NONINHERITABLE'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L72

'LBL_MAKE_POST'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L76

'LBL_SELECT_GROUP'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L78

'LBL_HOOKUP_SELECT'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L81

'LBL_HOOKUP_CONFIRM_PART1'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L82

'LBL_HOOKUP_CONFIRM_PART2'
https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc//modules/SecurityGroups/language/en_us.lang.php#L83

**Comment by pgorod** [comment]
@horus68 not related to the current Issue, but please have a look at https://suitecrm.com/forum/suitecrm-7-0-discussion/14373-mandatory-filed-can-be-empty
it seems there's a problem with a language pack, although maybe it's a more generic permissions problem, his logs are too full of errors. But you might be able to help there. Thanks.

**Comment by horus68** [comment]
@pgorod done. Replied in the forum. It was an error translating the file \include\language\hu_HU.lang.php  (an extra line at the end of a translated value). It is just on Hungarian language. 
I really hate the include language file, its a shame this kind of mixed arrays and strange validations remains in a modern software.

**Comment by pgorod** [comment]
And look what I found in the pt-PT.lang.php file:

``` 
    // Note:  do not translate record_type_default_key
    //        it is the key for the default record_type_module value
    'record_type_default_key' => 'Contas',
``` 
That's a bug, isn't it? It says not to translate...

**Comment by horus68** [comment]
True.. but its not possible to not translate that line in Crowdin as it is auto filled from any other strings with same value. And there are others alike!
The the value of a default key (acting as a code) should never be a plain word

```
    'record_type_default_key' => 'Accounts',
    'record_type_display' => array(
        '' => '',
        'Accounts' => 'Account',
        'Opportunities' => 'Opportunity',
        'Cases' => 'Case',
        'Leads' => 'Lead',
        'Contacts' => 'Contact', // cn (11/22/2005) added to support Emails
        'Bugs' => 'Bug',
        'Project' => 'Project',
        'Prospects' => 'Target',
        'ProjectTask' => 'Project Task',
        'Tasks' => 'Task',

    ),
```

**Comment by pgorod** [comment]
I think the real fix would be to move every "do not translate" string that works as code, and is not displayed to the users, out of language files, and out of Crowdin. There are plenty of better places to put those strings. Do you know of many? Can you get a full list? I'm hoping they're not too many...

**Comment by horus68** [comment]
@pgorod a total of 20 (you can search for `default_key` into \include\language\en_US.lang.php.
Each of them are next of its related array

Note: some do not create a problem.
Example: this one is a correct one (the value Open_New is not a common word):
```
$app_list_strings['case_status_default_key'] = 'Open_New';
$app_list_strings['case_status_dom'] =
    array(
        'Open_New' => 'New',
        'Open_Assigned' => 'Assigned',
        'Closed_Closed' => 'Closed',
        'Open_Pending Input' => 'Pending Input',
        'Closed_Rejected' => 'Rejected',
        'Closed_Duplicate' => 'Duplicate',
    );
```

**Comment by horus68** [comment]
@pgorod Created a new issue for the default key problem.
https://github.com/salesagility/SuiteCRM/issues/3608

Lets delete all our previous messages here to avoid an _issue hijack_!
(will delete this one after your messages been deleted!)
