### ISSUE TITLE
Suggestion: Good to have Create and Duplicate options in Role Management module.

### ISSUE THREAD

**Issue by ChangezKhan** [salesagility/SuiteCRM#3605]
#### Issue

It is a suggestion, not a bug. I have seen many projects where we have to implement roles on `Create` and `Duplicate` actions in modules. 

I know, that there is an `Edit` action is available, but sometimes we need to give access to users only create the records and sometimes only edit the records. Same about the duplicate.

So, we somehow managed it by doing some code in view files. But it would be great, if we provide such above options in Role Management module itself.

**Comment by chris001** [comment]
If you share the Create and Duplicate code here, it might be added.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion: Good to have Create and Duplicate options in Role Management module](https://trello.com/c/jQKIRiFZ/186-suggestion%3A-good-to-have-create-and-duplicate-options-in-role-management-module)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
