### ISSUE TITLE
New contact info not saving

### ISSUE THREAD

**Issue by Najat77** [salesagility/SuiteCRM#3606]
I ve installed suite crm on my goddady server, it turns out that whenever we import a list, it doesnt import all the info so we have to enter in each contact and add info such as email or phone number but for some reason sometimes it saves the addeded info sometimes it doesnt. 
Also it seems the search bar cannot be cleared so whenever we go back to contacts or accounts we can only see the latest one searched for and not the whole list of accounts or contacts.

version : 7.2.2 
Browser: Safari but same issues on Chrome 

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by chris001** [comment]
Are you able to check your php error log at the time you did the action to import the data, and save the edited records.  If you can, post the contents, and remove your personal information.

**Comment by pgorod** [comment]
@Najat77 Version 7.2.2 is two years old, and 38 versions ago... unfortunately some shared hostings install this kind of thing, but it's really a bad move for you, starting work on SuiteCRM with a version like that.

With a newer version you would avoid serious security issues in that version, you would get a ton of cool new features, and you would get hundreds of bug fixes - possibly including the one you're raising here.

**Comment by Dillon-Brown** [comment]
@Najat77 We don't support 7.2.2. If you are able to replicate this on a later version e.g. 7.7, 7.8, 7.9. Then please raise a new issue and we will investigate.
