### ISSUE TITLE
Default keys requires a new key mapping - language file include/en_US.lang.php

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3608]
#### Issue

Translation work using Crowdin needs that default keys in `\include\language\en_US.lang.php ` get a new key mapping **if there is a required default key** on an array that is using a **common english word as a value**. 
Common english words are also used in other language files and because we use auto-fill on the same values across all language files, the values on the default keys are also filled with translated words. So the arrays using default keys gets scrambled on language packs. 

## This is not a suggestion but should be considered as a bug.
The request is not for all default keys because **this is already done in some arrays in that file but not in some others.** 
There is no solution from the Crowdin side (hidden those is not enough). So it must be done from the SuiteCRM side.

Note: You can find a total of 20 situations in `\include\language\en_US.lang.php` but not all are problematic (try to search for default_key on that file).

**Example 1 - Causes problems on language packs**:
```
    //Note:  do not translate case_relationship_type_default_key
//       it is the key for the default case_relationship_type_dom value
    'case_relationship_type_default_key' => 'Primary Contact',
    'case_relationship_type_dom' => array(
        '' => '',
        'Primary Contact' => 'Primary Contact',
        'Alternate Contact' => 'Alternate Contact',
    ),
```

**Example 2 - No problem for translators or language packs**
(note that the default key value uses a key_subkey format)

```
$app_list_strings['case_status_default_key'] = 'Open_New';
$app_list_strings['case_status_dom'] =
    array(
        'Open_New' => 'New',
        'Open_Assigned' => 'Assigned',
        'Closed_Closed' => 'Closed',
        'Open_Pending Input' => 'Pending Input',
        'Closed_Rejected' => 'Rejected',
        'Closed_Duplicate' => 'Duplicate',
    );
```

#### Expected Behavior

`default_key ` value shouldn't be a common english word but a composed term with underscore as in `key_subkey` 

#### Actual Behavior

the default key `Primary Decision Maker`  is auto-filled with a translation.

#### Possible Fix

See example 1 but now using underscore for key_subkey format

```
    //Note:  do not translate case_relationship_type_default_key
//       it is the key for the default case_relationship_type_dom value
    'case_relationship_type_default_key' => 'Primary_Contact',
    'case_relationship_type_dom' => array(
        '' => '',
        'Primary_Contact' => 'Primary Contact',
        'Alternate_Contact' => 'Alternate Contact',
    ),
```
Note: those arrays using just 1 word as key needs to have a subkey added so they are not common english words

#### Context

Translation project uses auto-fill settings to reduce translators work
Stats: 6141 strings (13 283 words) as Duplicate texts and do not need to be translated!

**Comment by pgorod** [comment]
This should be easy to fix on the language files, but to be on the safe side we would need to check the places in the code where these values are referenced. I fear that somebody might be using these values hard-coded somewhere - after all, they are on left-hand side of associative arrays, they are just indexes...
