### ISSUE TITLE
Mandatory fields not validated and saved when empty

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#3609]
#### Issue

When creating an account the name filed is mandatory and its not possible to save if empty. But if the language file `include/en_US.lang.php` (or the equivalent interface user language) has an **additional line in some strings** the validation do not fire and the record is saved empty. 
## This also happens with Accounts, Contacts, Opportunities, Cases, Meetings, Project, Targets, and Leads modules. But not with Campaign, Tasks, Calls, Notes, Documents, Contract or Bugs modules

- As posted in forum for one language but can be replicated for english language too https://suitecrm.com/forum/suitecrm-7-0-discussion/14373-mandatory-filed-can-be-empty

#### Expected Behavior

Normal and proper action:
1. Module: Sales -> Accounts
2. Add new account
3. Save (no data on name field)
4. Save not allowed with an alert
![2017-05-29 16_53_38-microsoft edge](https://cloud.githubusercontent.com/assets/3055443/26576172/ccb03e06-451f-11e7-8842-50069432a3f6.png)

#### Steps to Reproduce

1. EDIT file include/en_US.lang.php lines ~3594 - string `$app_strings['LBL_JJWG_MAPS_LAT'] = 'Latitude';` making an additional line after the word `latitude` so the `';` goes into next line.
![2017-05-30 08_47_26-_ en_us lang php - notepad2](https://cloud.githubusercontent.com/assets/3055443/26576100/9372c6fe-451f-11e7-83ad-52c79cded31a.png)

2. Module: Sales -> Accounts
3. Add new account
4. Save (no data on name field)
5. Record is created with empty data
![2017-05-30 09_14_48-microsoft edge](https://cloud.githubusercontent.com/assets/3055443/26576138/b23fe1d4-451f-11e7-81fc-0c649bfca306.png)

This seems related only with `LBL_JJWG_MAPS` strings. You can achieve the same results with this strings:
```

$app_strings['LBL_JJWG_MAPS_LNG'] = 'Longitude';
$app_strings['LBL_JJWG_MAPS_LAT'] = 'Latitude';
$app_strings['LBL_JJWG_MAPS_GEOCODE_STATUS'] = 'Geocode Status';
$app_strings['LBL_JJWG_MAPS_ADDRESS'] = 'Address';

```
Special note: the lines above the quoted ones ~3594 do NOT get this issue and will trigger the validation even with the extra line:

```
$app_strings['LBL_MAP'] = 'Map';
$app_strings['LBL_MAPS'] = 'Maps';
```
same goes with lines below 
`$app_strings['LBL_BUG_FIX'] = 'Bug Fix';`

#### Context

If a translator hits the ENTER key after a word in the translation it breaks the validation on mandatory fields!

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.8.3
* Browser name and version: Windows Firefox 32 bits
* Environment name and version (e.g. MySQL, PHP 7): php 7.0.11, MySQL 5.7.17
* Operating System and version (e.g Ubuntu 16.04): local WAMP install

**Comment by pgorod** [comment]
@horus68 do you think this would be a good generic validation for every language string:

- if there is one or more newlines at the beginning or end of a string, remove it

Or are there strings with newlines, that _should_ have newlines?

My line of thinking here is that this needs to be made more solid for everywhere, not just for these strings. String problems can really break PHP apps in unexpected ways. If some translator makes an innocent mistake it shouldn't break the app, much less in an obscure manner.

So if we can add generic validations (for newlines, for apostrophes, that sort of thing) we could make the app more robust. But we need to make sure we don't break the app in other places: I seem to remember there are language strings with HTML and maybe even javascript inside them, right?

**Comment by horus68** [comment]
There are strings using new lines without any html in it. (There are also some with HTML) 
On the Apostrophe there are several issues:
https://github.com/salesagility/SuiteCRM/issues/3056
https://github.com/salesagility/SuiteCRM/issues/1720

I can't comment on code changes. @samus-aran or other SalesAgility dev needs to reply you on that,

**Comment by pgorod** [comment]
Yes, what I was thinking is like what @chris001 suggests on his comment in #3056, a generic fix in the Language Manager.

**Comment by horus68** [comment]
@Dillon-Brown to the rescue?

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
