### ISSUE TITLE
Inbound group email doesn't show separatly 7.9

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3615]
#### Issue

Ok.... let's start screen by screen

When you create inbound group email account, you are suggesting that the all users will available to access this email account... but there is problem. I created the inbound group email.. but it isn't showing  in email settings ( in user profile). You can see the emails from this email group account only if you create the personal account.. let's look on screenshots

If you create only inbound group email account (in my case, its name is INFO GROUP) , you will see this
![inbound_listview](https://cloud.githubusercontent.com/assets/5773777/26618631/4eed2c10-45db-11e7-9c50-5bfd18517060.png)

How it looks in email settings
![inbound_settings](https://cloud.githubusercontent.com/assets/5773777/26618642/5651ccae-45db-11e7-8bb1-3121925fb340.png)
![inbound_accounts](https://cloud.githubusercontent.com/assets/5773777/26618650/5bf2a8ea-45db-11e7-823a-e8eb0bbf279c.png)

After when you create personal email, you are available to see this email group account also in listview of email module
![inbound_folder](https://cloud.githubusercontent.com/assets/5773777/26618656/62959e8c-45db-11e7-86f6-c9105d4efbe8.png)

#### Expected Behavior

When you create any group email account... users will available to use it without creating own personal one.

#### Steps to Reproduce

1. Create the inbound group email and look into email setting

#### Your Environment

* SuiteCRM Version used:  SuiteCRM 7.9
* Browser name and version: Chrome 59.x 64bit
* Environment name and version: MySQL 5.6 / PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
Issue appears to be unfixed in 7.9.4

**Comment by Mausino** [comment]
@Dillon-Brown this issue doesn't appear for me in latest 7.10.11 version. I am closing it.
