### ISSUE TITLE
Detailview of email record in 7.9 doen't have Reply to, Reply to All, Forward to, Delete BUTTONS

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3616]
#### Issue

We upgraded to 7.9 and i hope that is no joke :(

Has the detaiview of email any Reply To, Reply All, Forward, Delete  buttons ???

![email2](https://cloud.githubusercontent.com/assets/5773777/26620126/c6e14340-45e1-11e7-999e-94b88a414a6a.png)

![email](https://cloud.githubusercontent.com/assets/5773777/26620045/741de49c-45e1-11e7-8e30-af0aa09349ff.png)

How can i forward or reply to email which i recieved ? 
Me and all world know, that it is the most important thing to be availabe answer to emails... or i am wrong and i didn't unsderstand something ?

#### Expected Behavior

User can reply, forward or delete email in its detailview of email

#### Steps to Reproduce

1. See the list of mails
2. Open one mail record
3. Try find the buttons  or reply to/forward to this email record

#### Context

I believe that the version 7.9 wasn't publish without this important functions

#### Your Environment

*SuiteCRM Version used: SuiteCRM 7.9
*Browser name and version: Chrome 59.x 64bit
*Environment name and version: MySQL 5.6 / PHP 7.0.16
*Operating System and version: Win 10 Home

**Comment by Mausino** [comment]
@daniel-samson @Dillon-Brown thanks for path.. its working but only for no imported mail.

the issue is persisting, If you import emial, you are not available to reply to, reply all, forward the  imported/archived mail

**Comment by Mausino** [comment]
@Dillon-Brown i rewrited the ticket :)

**Comment by Dillon-Brown** [comment]
Hi @Mausino I'm not able to replicate this. With #3627 I have the option to reply, reply all , and forward on imported and non-imported emails.. Can you provide screenshots?

**Comment by Mausino** [comment]
@Dillon-Brown yes with #3627 is it working and i see the buttons there 👍  but in fresh install of SuiteCRM 7.9.0 isn't  there.

**Comment by Dillon-Brown** [comment]
@Mausino A fresh install using the hotfix branch? #3627 has only been merged into hotfix and not master. Fix appears to be functioning correctly on my end.

**Comment by samus-aran** [comment]
A lower priority has been raised for the delete from IMAP server on DetailView as it is currently available on the ListView.
