### ISSUE TITLE
Imported email in 7.9 doesn't show the body text

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3617]
#### Issue

When you import any email,  it doesn't show you the body text
![import](https://cloud.githubusercontent.com/assets/5773777/26620952/35da1e0e-45e5-11e7-83b6-434fea1d717c.png)

#### Expected Behavior

Will show  the body text (the most important part of the emails)

#### Steps to Reproduce

1. Import email 
2. Open imported email and look to body section

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9
* Browser name and version : Chrome 59.x 64 bit
* Environment name and version: MySQL 5.6 / PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by samus-aran** [comment]
@Mausino - There is a fix up for review - can you try this out if possible?  We just want to double check if the issue occurs when you have imported the emails after the upgrade or before?  If it was after then the fix should resolve the issue but will require a re-import of that particular record.  You should be able to delete the email (which only deletes the CRM record not the IMAP message) via the Detail View of the Record.

**Comment by Mausino** [comment]
@samus-aran  in the evening i will appy this and i will let you know the result :) thanks for the patch.

**Comment by Mausino** [comment]
@samus-aran @daniel-samson  I used the patch and it is working 👍 

Thanks

**Comment by Mausino** [comment]
@samus-aran @daniel-samson   now when i tested more... 

is working for emails which was recieved.. but was not imported

![1a](https://cloud.githubusercontent.com/assets/5773777/26677048/890c8130-46ca-11e7-9d4b-6f3372eee4d6.png)

isn't working for emails which system by itself imported email or if email was imported by user
 
![1b](https://cloud.githubusercontent.com/assets/5773777/26677068/9b5a2c16-46ca-11e7-8f46-d5b01fbbfb77.png)

**Comment by samus-aran** [comment]
Sorry @Mausino just to double check that the body still doesn't appear AFTER the fix was applied (https://github.com/salesagility/SuiteCRM/pull/3620) AND you imported an email (this won't work for those emails which have already been imported prior to the fix unless re-import them again).

**Comment by Mausino** [comment]
@samus-aran i will test it with my employees for few days... and we will see 👍 

Do you have some idea how reimport email which was imported? by admin --> repair -> sync inbound accounts ??? we will apply also tomorrow this patch #3621  and after we will try it... because now when i use import button for email which was imported.. I am thinking that it imports this email again, but still is without body...  

Thanks for your advice + asnwer and i will inform you :)

**Comment by samus-aran** [comment]
@Mausino - I would delete the imported email (don't worry it won't delete it from the IMAP server) and find it again on your listview (since its directly linked to your IMAP account) and re-import it again.

Let us know how you get on.

**Comment by oskapt** [comment]
This fixes the empty import, but it doesn't fix all issues:

- After initially importing HTML email, the body shows all HTML. If I exit out of the screen and re-enter to view the email again, it shows with correct formatting

There are three other problems, but I'll open separate issues for them.

**Comment by samus-aran** [comment]
Got it, Since it does import now I will Confirm that the body has imported but open up a separate issue with lower priority as there are other higher priorities to be dealt with. :)
