### ISSUE TITLE
Encoding TO/FROM in Email Detailview 7.9 is wird/wrong

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3626]
#### Issue

In the column TO the system strip the spec. charakters like á,ý,é  
-- e.g. orig: Lucia Bodnárová --> striped: Lucia Bodnarova
or 
add the "" around name if didn't sync/find the system email address 
![utf4](https://cloud.githubusercontent.com/assets/5773777/26637503/eb517504-461f-11e7-9a23-6231edeb2c29.png)
In detailview of email is the name FRO/TO showing right :)
![utf3](https://cloud.githubusercontent.com/assets/5773777/26637510/f11d057a-461f-11e7-9eb0-f2d69ba402cb.png)

in the column FROM  looks like:
![utf2](https://cloud.githubusercontent.com/assets/5773777/26637548/0aedca70-4620-11e7-8880-0869490ff15c.png)
![utf1](https://cloud.githubusercontent.com/assets/5773777/26637556/0fd7d710-4620-11e7-97a4-35e7e5b3eb59.png)

#### Steps to Reproduce

1. Visit email module :)

#### Your Environment

* SuiteCRM Version used: Suite 7.9
* Browser name and version: Chrome 59.x 64bit
* Environment name and version MySQL 5.6, PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by samus-aran** [comment]
Reduced the priority as it doesn't stop functionality - however it is noted that this was also an issue on previous versions.

**Comment by likhobory** [comment]
[Solution](https://spravkacrm.ru/forums/topic/119-%D0%BA%D1%80%D0%B8%D0%B2%D0%B0%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B2-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B5-email-%D0%B2-suitecrm-794/):
1. Open  modules/Emails/include/ListView/ListViewDataEmails.php 
2. Find `$ret = $emailHeader['from']; //line 504`
3. Replace with `html_entity_decode($inboundEmail->handleMimeHeaderDecode($emailHeader['from']));`

Tested with ver.7.7.9 and works as expected.

**Comment by Mausino** [comment]
@likhobory your code is working 🥇 
@PedroErnst could you create for it pull request?
