### ISSUE TITLE
Missing icons in filter bar when you edit Email Layout in 7.9

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3628]
#### Issue

We edited the Listview Layouts of Emails in studio and the icons (Compose Email, Email settings, Check for new Email, Select Folder) were disapear
![filterbar1](https://cloud.githubusercontent.com/assets/5773777/26646316/676399f4-463b-11e7-80ad-57053f18aafe.png)

After editing of Listview Layout
![filterbar2](https://cloud.githubusercontent.com/assets/5773777/26646361/948cfdc6-463b-11e7-8c0b-0aae3402ebad.png)

#### Steps to Reproduce

1. Go to Studio
2. Email section
3.  Layouts
4. Listiview
5. Change the order of columns and save/deploy

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9
* Browser name and version: Chrome 59.x 64bit
* Environment name and version: MySQL 5.6, PHP 7.0.16
* Operating System and version: Win 10 home

**Comment by Dillon-Brown** [comment]
@Mausino We'll target this specifically for the 7.9 emails list-view but i'll raise a separate issue for the "restore defaults" button not working correctly. The "restore defaults" button appears to be an issue present in all versions of Suite.
