### ISSUE TITLE
Folders in email settings are persisting after deleted inbound email accounts in 7.9

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3629]
#### Issue

When i upgraded from 7.8.3 to 7.9 and i deleted all inbound emails and recreate new one they stay for me the old  folders in email settings 

Please look on this videoscreen: https://www.screencast.com/t/RSMIjJiVj

+ the buttons Show folders and INBOX button with this issue doesn't work correctly
![folder_x](https://cloud.githubusercontent.com/assets/5773777/26670722/0dc5fb4e-46b3-11e7-993e-0299063c0df1.png)

#### Expected Behavior

In folders (email settings) will only actual folders

#### Steps to Reproduce

1. Upgrade the SuiteCRM to 7.9
2. Sync the email accounts in Repair section
3. Look into email setting window

#### Your Environment

* SuiteCRM Version used:  SuiteCRM 7.9
* Browser name and version: Chrome 59x 64bit
* Environment name and version: MySQL 5.6 , PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
@Mausino This issue should be resolved on 7.9.1.
