### ISSUE TITLE
User inline edit problems

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#363]
we updated from 7.2.1 to 7.3

we tried many times and also  we tried on fresh instaled version of 7.3 SuiteCRM

there is same problem :( if is user admin, it has any problem inline edit listview or detailview, but if we change it to normal user, that sometimes happend that can inline ediť and save it (in 90% is'nt working)

but if we changed user right again to admin, problem disappear

We are running on 5.4 PHP version

Miky

**Comment by NHBSam** [comment]
I am currently having the same issue.
Inline editing works fine with an admin account but doesn't work on a normal user account.

~ Sam

**Comment by Mausino** [comment]
Now the user inline editing is working fine :) :+1:

**Comment by vladbar** [comment]
I'm glad it helped!
