### ISSUE TITLE
Attachments in Emails 7.9 aren't showing - In List View

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3631]
#### Issue

In Email version 7.9 are not showing any email attachments 

I have set up the column Has Attachment
![attachment1](https://cloud.githubusercontent.com/assets/5773777/26670418/e12587f4-46b1-11e7-8b58-5e7086d8c97f.png)

And there are not there (in email client like mozilla, every second mail has the attachment)
![attachment2](https://cloud.githubusercontent.com/assets/5773777/26670449/046557a8-46b2-11e7-97b2-4c095f4a4322.png)

 #### Expected Behavior

Will indicate if email has or doesn't have attachments

#### Steps to Reproduce

1. Go to Email molule :)
2. Look on column Has Attachment

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9
* Browser name and version: Chrome 59.x 64bit
* Environment name and version: MySQL 5.6, PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
@Mausino Are the attachments missing only on the list-view? e.g. are the actual attachments themselves present on the email record?

**Comment by Mausino** [comment]
@Dillon-Brown  no in detaiview i see the issue :(

Thunderbird
![at2](https://cloud.githubusercontent.com/assets/5773777/26673825/8a9c063a-46be-11e7-9dea-e1e06a1f9a60.png)

SuiteCRM 7.9
![at1](https://cloud.githubusercontent.com/assets/5773777/26673837/96df4f10-46be-11e7-9216-99b35cf9f1a6.png)

**Comment by Dillon-Brown** [comment]
@Mausino This is due to the email not being imported into the CRM. The attachment icon won't appear until an email has been successfully been imported.

**Comment by Mausino** [comment]
@Dillon-Brown after import of emial and  doesn't see it on listview... in detailview i see the attachment field and there the name of the file....

But i didn't understand you in your sentence: "This is due to the email not being imported into the CRM. The attachment icon won't appear until an email has been successfully been imported."

You mean that will no possible see the email icon in listview and the name of file in detailview until system or user don't import email ???  If yes, how we will know if email has the attachment before importing... Without this BASIC function will the emails totally usefull !!!  

@pgorod @horus68 @samus-aran @daniel-samson please guys what are you thinking about it.. ???

**Comment by Dillon-Brown** [comment]
@Mausino See my edited comment. The attachment icon should be showing up regardless of importation. Raising this as a bug.

**Comment by Dillon-Brown** [comment]
@Mausino Can you confirm if you see the icon svg on your end? It should be in (themes/SuiteP/images/attachment-indicator.svg)

**Comment by Mausino** [comment]
@Dillon-Brown  yes, i found it
![indicator](https://cloud.githubusercontent.com/assets/5773777/26678092/21b35fa4-46cf-11e7-952f-38152a30489c.png)

**Comment by samus-aran** [comment]
Possible UI thing also to show that in the Detail View there is an Attachment Icon to indicate the attachment.

**Comment by Dillon-Brown** [comment]
@Mausino I'm unable to replicate this issue. It may be due to incorrect pathing. I've put up a PR that might fix this, let me know how you get on.

**Comment by Mausino** [comment]
@samus-aran  i will ask it my developer and tomorrow i will know more.. :) we will investigate issue on my site (custom module issue.. ) or i add the way how it replicate the bug on official SuiteCRM

**Comment by RobinHind** [comment]
I have the same problem, can't view attachments or the icon, proposed fix did not work for me

**Comment by Mausino** [comment]
@Dillon-Brown the proposed fix also doesn't work for me

**Comment by RobinHind** [comment]
This fix also did not work for me in 7.9.1

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran i think the email attachment icon on list view + attachment link in detail view or non imported email is the CORE function of emails and without it should the company lose many information's (quotes, invoices, contracts) which are too much important for companies!

Without it, is email function (module) useless for company, because can't trust the mails in list view...  

Could you change to Hight Priority... because this issue break the function of emails which are essential for this computer age :)

**Comment by Mausino** [comment]
@PedroErnst could you help us with this bug.. in the forum annoying this issue many users.. the email are unusable if you in listview don't know where are the attachments. thank you

**Comment by Mausino** [comment]
@PedroErnst we applied this fix #4866 and it's working.. 🥇
