### ISSUE TITLE
Compose email pop up window in 7.9  - UX suggestion

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3632]
#### Issue

In many email clients...  i am using only Thunderbird (but i give you 2 examples) are the  buttons for send, attachment and other still about the email addresses section like:

Thunderbird:

![composeemail1](https://cloud.githubusercontent.com/assets/5773777/26672026/e75e5a00-46b7-11e7-8d46-6542d56548f9.png)

Outlook 2013:

![composeemail2](https://cloud.githubusercontent.com/assets/5773777/26671588/5245481c-46b6-11e7-8646-9b648cfa75a4.png)

Suggestion to Email compose pop up window:

![suggestion_email](https://cloud.githubusercontent.com/assets/5773777/26671855/4dfe5f86-46b7-11e7-86cf-b1086f145aee.png)

A: 
---> this A section could have own TAB and will bellow Email Compose tab (this tab is not possible minimalise :( yet )

B:
---> this B section could be above the Email Compose tab... it will still stay everytime on eyes  and user will knows if he/she added attachment or document or etc. before sending of email... when will this section in bellow part, user could forgot do this. And it is ususally when you recieve the mail with attachments and those are in bellow part of email. But when you are composing the email is totaly unpractical has this section bellow... because in each EMAIL PROGRAMS are still ABOVE :)

#### Expected Behavior

A: section get so much place and could be as separate tab
B: section is to much important that is bellow of email pop up window if in each email client is above

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compose email pop up window in 7.9 - UX suggestion](https://trello.com/c/jQaE1tbi/188-compose-email-pop-up-window-in-79-ux-suggestion)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
