### ISSUE TITLE
Import button/function in 7.9 same logic/possibilities as in 7.8.x mail system

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3637]
#### Issue

In version 7.9 is import button, but it only imports the record to somewhere (based on email address relationship).  And can only import to one record.. i had ticket why will fine for more records : "Can't import email message to 2 or more different (modules) records" #2319

The point is that we have not possiblity to choose where will the record related/import. We can only import email and after edit imported/achived email and choose in field RELATE TO where will it relates to. 

Problem is that it relates email  to one record and this option are not giving as possibility to relate/import email to more records as i wrote in ticket #2319 and you must first import email and after you must edit it

![import](https://cloud.githubusercontent.com/assets/5773777/26719863/6ed24824-4786-11e7-8850-b97b457791d6.png)

#### Expected Behavior

User will have choise to choose where will the email imported/related to and  if will one or more records

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9

**Comment by Dillon-Brown** [comment]
@Mausino Since you have already raised this as a bug, this would be considered a duplicate. This should be considered a new feature so we will keep this one open and close the old one. 

We don't feel that the old issue should have been considered a bug as this is standard functionality. Having a related to field relate to a single record not multiples.

**Comment by blloyd78** [comment]
I would suggest updating the email documentation to reflect this change in functionality, otherwise long-time SuiteCRM users will continue to assume this is a bug.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import button/function in 7.9 same logic/possibilities as in 7.8.x mail system](https://trello.com/c/cH0Nrp23/189-import-button-function-in-79-same-logic-possibilities-as-in-78x-mail-system)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
