### ISSUE TITLE
Mark As Read/unread isn't in 7.9 mail system

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3638]
#### Issue

The common function of IMAP is

Mark As Read/Unread

isn't in SuiteCRM 7.9 mail system yet. (in older version 7.8.x was and was very usefull)

![flag](https://cloud.githubusercontent.com/assets/5773777/26719371/89afd50a-4784-11e7-9b62-7a7c52c2a228.png)

#### Expected Behavior

User will available to mark the emails as read/unread

**Comment by samus-aran** [comment]
Pull Request Created - https://github.com/salesagility/SuiteCRM/pull/3648
