### ISSUE TITLE
Can't send e-mail or save e-mail draft in FireFox (7.9)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3640]
In Firefox I'm trying to save e-mail draft and see the following picture without any result. 
IE/Egde & Chrome  - works fine.

![default](https://cloud.githubusercontent.com/assets/5983672/26722710/dd65b740-4799-11e7-9b8c-ba91d1227881.png)

#### Environment

* SuiteCRM Version used: 7.9 or Hotfix branch
* Browser name and version: FF 53 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Mysql 5.5 / PHP 5.5 or 5.6
* Operating System and version (e.g Ubuntu 16.04): Win7 (64-bit), Win10 (64-bit)

**Comment by likhobory** [comment]
The same problem when I Trying to send e-mail.

**Comment by Mausino** [comment]
@likhobory  for me isn't working save draft in Chrome 58.0.3029.110 (64-bit)... it opens the pop up window and still loading
![230869e4-47b0-11e7-92f8-9b2041bba4c1](https://cloud.githubusercontent.com/assets/5773777/26733299/b543ddde-47ba-11e7-9e94-47f2f1363744.png)

**Comment by likhobory** [comment]
I'm testing with Chrome  60.0.3112.11, dev (64 bit).

**Comment by samus-aran** [comment]
@Mausino and @likhobory - Can you test the fix proposed please.  Would be much appreciated.  Will require a refresh of your browser cache.

**Comment by likhobory** [comment]
Works as expected.
Tested with FF 53.0.3

**Comment by Mausino** [comment]
@samus-aran now it's working 👍
