### ISSUE TITLE
Created date/creator not shown after importing email

### ISSUE THREAD

**Issue by oskapt** [salesagility/SuiteCRM#3641]
- Attempting to import multiple emails failed silently. One email was imported.
- Emails are being recorded with a create date set to the import time. It would be better to record

#### Issue

- After importing an email the "Date Created" field initially shows " by " (no date, no creator). After exiting and returning to the screen it shows "2017/06/02 09:53 by " (date/time but no creator)

#### Expected Behavior
Date and creator should be correctly displayed

#### Steps to Reproduce
1. import email
2. note that field is displayed incorrectly
3. exit screen and return to email
4. note that field is displayed differently, although still not correct

#### Context

Low priority. Nuisance but doesn't interrupt functionality.

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 53.0.3 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Docker built from php:5.6-apache image

**Comment by Dillon-Brown** [comment]
Fix: #3607
