### ISSUE TITLE
Open email in separate pop up window from List View in 7.9 - suggestion 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3642]
#### Issue

It will cool if we can see the email in separate window...

User will  have choise if want click on name of email and takes him into detailview of email or behind/next to the checkboxes (screenshot) could be icon of email (or info icon) and if click on this icon, email record will open in separate pop up window. (this is very common behaviour of other programs or email clients)
![suggest](https://cloud.githubusercontent.com/assets/5773777/26730715/21a175e4-47b2-11e7-9e2a-405070837b12.png)

#### Expected Behavior

Reason is easy... if i am working wiht many emails... i don't want be interupted that i lost the overview about all emails... i want only open in new window email, to do some action with mail (reply to, import, flag, etc) and i continue with other mails.

#### Actual Behavior

Open me the email in same browser tab and after i must click on sidebar menu View Email. After i need some time to get the overview over emails and click/do some action with ohter email.  In english language is (i hope)--> it breaks the train of thoughts 
.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Open email in separate pop up window from List View in 7.9 - suggestion](https://trello.com/c/7lowyXFi/190-open-email-in-separate-pop-up-window-from-list-view-in-79-suggestion)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
