### ISSUE TITLE
7.9.0 Email: Template's Subject not replacing Subject content in editor

### ISSUE THREAD

**Issue by someguynamedphil** [salesagility/SuiteCRM#3643]
Select a template in Email compose window. 

Popup window with notice that content will be replaced. Click ok.

Body field is filled in with template content, subject field remains blank.

\
#### Your Environment

* SuiteCRM Version used: 7.9 
* Browser name and version:  58.0.3029.110 (64-bit) Mac OSX
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version Mac OSX 10.12.5

**Comment by Mausino** [comment]
@someguynamedphil I tested and you're right 👍 same issue on my site ...
