### ISSUE TITLE
Responsive template bugs related to css layers

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#365]
Suitecrm version 7.3.0 latest. 
SuiteR Responsive template.

Suite, in various places in the application, creates CSS popups that are so improperly large, that the X (close) and buttons (Save, Save and New, Cancel) are inaccessible, because they are hidden under the wrong CSS layers, and the scrollbars are operating on the wrong CSS layers, Suite strands the user no one screen that they cannot escape from, it makes their work impossible to save, impossible to back out of.

For example
1280x800 notebook screen resolution - 
Since it's responsive template, Suite should show all items within the 800 pixel width - from time to time you should have to do some vertical scrolling..
Steps to reproduce.
1. click Home
2. click Email.
3. click Settings
4. Try to scroll horizontally to see action buttons along the right edge the very wide Settings box - but scrolling right is impossible, as the scrollbars are scrolling the underneath CSS layer, the "Email" page.  In face it's impossible to exit this screen safely...
5. Hit the Mail Accounts, then Add.  This produces a very tall css popup, so tall that its top and bottom are obscured under the top and bottom edges of the browser.  Impossible to access the rest of this popup, as well as to exit this screen...

**Comment by willrennie** [comment]
I have addressed this issue and another issue which I have detailed in my commit. The fix has been applied to the hotfix-7.3.1 branch. If you have the time/ability you could check out the fix to see if it addresses your issue and if not let me know what further amendments are required.

**Comment by chris001** [comment]
Tested under the suite P theme, the popups are held within a usable position and size, the close buttons is accessible.
