### ISSUE TITLE
Leftover call to Emails/index.php in v7.9, breaks "Email Quotation" feature

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3654]
#### Issue
When using the "Email Quotation" action from the Quotes detail view, we get a blank screen and nothing happens.

The logs contain this
```
Mon Jun  5 16:39:10 2017 [1252][1][FATAL] emails_email_templates for emails_email_templates failed to load
Mon Jun  5 16:39:10 2017 [1252][1][FATAL] Failed to load relationship emails_email_templates while saving Emails
Mon Jun  5 16:39:10 2017 [1252][1][FATAL] emails_email_templates_idb for emails_email_templates failed to load
```

#### Expected Behavior
Option should work as in previous versions.

#### Possible Fix
It seems there is a leftover called to a file that was removed. The call is in `modules/Emails/compose.php`, line 72:
```
include('modules/Emails/index.php');
``` 
This file seems to have been deprecated and removed in v 7.9. I don't know exactly what should be put in the place of this call, though.

#### Steps to Reproduce
1. Create a Quotes Email Template (in PDF Templates module) if you don't have one yet
2. Create a Quote and Save it
3. From the Detail view of that Quote, select action `Email Quotation` from drop-down action menu

Note that there might be other ways to trigger this bug.

#### Context
This came from [a Forum thread](https://suitecrm.com/forum/suitecrm-7-0-discussion/14486-suite-7-9-0-email-quotation) reported by user `TaufiqueAhmed` and solved by user `xoanon`. 

#### Your Environment
* SuiteCRM Version used: 7.9

**Comment by jewelion** [comment]
Also invoked when emailing Invoice PDF
