### ISSUE TITLE
SuiteCRM 7.9.0 - Sending email from Activity Subpanel error

### ISSUE THREAD

**Issue by ckangwei83** [salesagility/SuiteCRM#3655]
#### Issue

When trying to send an email from Activity Subpanel -> Compose Email under the Case module, am getting a json error message printed on screen instead of js handling or showing error message in dialog box

#### Expected Behavior

Expect to have the email saved or send out. Even if any error should be display in dialog box

#### Actual Behavior

Email is sending out regardless if i send or save as draft. And error message appeal on screen instead of dialog box. A blank white screen printed with the error message in json format

#### Steps to Reproduce

1. Proceed to Case module
2. Click Compose Email under Activities subpanel
3. Input detail information and click on send/save as draft

#### Context

User are not able to reply email from the subpanel. I think this should be high in priority

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 58.0.3029.110 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6 & PHP 5.6.28
* Operating System and version (e.g Ubuntu 16.04): Windows 10 with MAMP running apache 2

![email_issue](https://cloud.githubusercontent.com/assets/29221734/26815602/cf01729c-4abf-11e7-97a1-c462dcd9c41c.png)

**Comment by Dillon-Brown** [comment]
@ckangwei83 I'm unable to replicate this issue. Is there any other information you could provide that might help with replication?

**Comment by ckangwei83** [comment]
@Dillon-Brown 
I am performing a fresh installation with demo data inserted.

Perhaps i guess you can try it with a clean 7.9.0 installation to try this. Or perhaps it might be some php setting that causing this? Does the message below sound familiar to you? I had also included the debugger information from chrome for your reference.

{"errors":{"type":"Email","id":"d8e209a4-f796-626f-b071-5939fec030ef","title":"Error Sending Email. Please contact your administrator for assistance."}}

By the way, my email did get saved.

I am just attaching the print screen on the step for your reference. Am not sure if that helps.

![step1](https://user-images.githubusercontent.com/29221734/26957604-ad7a1b2a-4cf8-11e7-8d8a-69eea64ebda3.png)

![step2](https://user-images.githubusercontent.com/29221734/26957605-ad7ebd2e-4cf8-11e7-9df2-ab883db74432.png)

![result](https://user-images.githubusercontent.com/29221734/26957682-3bfdf682-4cf9-11e7-8993-d5ca8d4d15c8.png)

**Comment by Dillon-Brown** [comment]
@ckangwei83 
Have you tried setting up a personal email account before saving the draft? The message:

{"errors":{"type":"Email","id":"d8e209a4-f796-626f-b071-5939fec030ef","title":"Error Sending Email. Please contact your administrator for assistance."}}

Should be appearing as a popup when you attempt to send as you have no email account in the "From" field. I Think this is related to a very similar bug where the same message occurs when you attempt to attach a document in FireFox.

**Comment by ckangwei83** [comment]
Hi,

This issue happen regardless if I had setup the inbound email or not. I
tried both and it still happening.

I am not attempt to send but just save as draft. The message is misleading
anyway.

I had tried to save as draft or send and both facing the same issue.

This only happen if i create the email through a subpanel. If i click into
Email module and do the compose email, then things are fine.


Thanks.







Best Regards,

Chong Kang Wei
Project Manager

+601 6691 1570

This communication contains information which may be confidential or
privileged.  The information is intended solely for the use of the
individual or entity named above.  If you are not the intended recipient,
be aware that any disclosure, copying, distribution or use of the contents
of this information is prohibited.  If you have received this communication
in error, please notify me by telephone immediately.

**Comment by Dillon-Brown** [comment]
Issue also present when sending drafts, forwarding, reply, reply all.

**Comment by gymad** [comment]
I have made a pull request for this. Can you please test that this corrects the issue?

**Comment by ckangwei83** [comment]
Looks good now that i can save draft. However, there are extra editor being render at the bottom of the page as below

![image](https://user-images.githubusercontent.com/29221734/27647408-efa95190-5c5d-11e7-838c-577434c62af3.png)
