### ISSUE TITLE
Сan't sort emails by Import status or attachment (7.9)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3660]
I can sort emails in ListView by date or Subject, but I can't do this with Import status or attachment.
It's a bug or a feature?

![default](https://cloud.githubusercontent.com/assets/5983672/26828916/1ace1142-4acc-11e7-84c0-3aacfa843270.png)

**Comment by Mausino** [comment]
@likhobory i thinked also on this.. why we cant sort emails by this columns

**Comment by Dillon-Brown** [comment]
Not a bug. I'll raise this as a suggestion.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Сan't sort emails by Import status or attachment (7.9)](https://trello.com/c/xJaGiV7S/191-%D1%81ant-sort-emails-by-import-status-or-attachment-79)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
