### ISSUE TITLE
Create new type of workflow action "Run script"

### ISSUE THREAD

**Issue by SoapJson** [salesagility/SuiteCRM#3665]
Create new type of workflow action "Run script"
It would be very useful feature to run script like in "Schedulers" by URL, but sending several variables in it from saved account for example.

suggestion

#### Your Environment

* SuiteCRM Version used: last;
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create new type of workflow action "Run script"](https://trello.com/c/Ym4XVkNy/192-create-new-type-of-workflow-action-run-script)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by pgorod** [comment]
@SoapJson do you mean run a command-line script with some parameters, or do you mean call an URL with some parameters?
