### ISSUE TITLE
Quick Create Popup is not displaying properly

### ISSUE THREAD

**Issue by arunqa** [salesagility/SuiteCRM#3667]
Quick Create Popup is not displaying properly

Click on first-time pop up is display properly, but if we click on the second time the popup is not displaying properly.
![suite crm issue](https://user-images.githubusercontent.com/5555183/26862862-1c4f8456-4b6c-11e7-9848-dc358a44f99a.png)

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
