### ISSUE TITLE
Imported email in 7.9 shows escaped html of body text (once imported) [from patch]

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#3675]
#### Issue

This issue has an extension of the following issue.
This has been resolved and scheduled into the next release.  The issue has followed up with a lower prioties sub issue which is this new issue.

When importing an email the html of the body is escaped and is not rendered correctly.  Howevere when re-loading the page it displays correctly.  See example from contributor's testing.

https://github.com/salesagility/SuiteCRM/issues/3610#issuecomment-305170255

#### Expected Behavior

1. Import a Email
2. Page Reloads and the HTML is rendered correctly.

#### Actual Behavior

1. Import a Email
2. Page Reloads and the HTML is escaped and showing as raw html.

#### Steps to Reproduce

1. Import a non imported Email
2. Page Reloads and the issue is seen.

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS.
