### ISSUE TITLE
Show the contacts by default from the account page view

### ISSUE THREAD

**Issue by matteoraggi** [salesagility/SuiteCRM#3680]
Hi, when I open the pageview of an Account, everytime I have to manually check if there are some contacts linked to it or not, and it make me firstly to use time, secondly I could do the mistake to don't click on every accordion tab to check every detail and I could do mistakes without know perfecly the informations of my account.

I suggest to to open by defautl the tabs of the contacts or at least to shwo the number of contacts linked to the opened Account?

Similar issue is not only about the contacts, but also about the activities, history, documents, opportunities, campaigns, leads, member organizations, cases, quotes, invoice,s contracts, products and services purchased, bugs, projects, security groups, etc..

Actually instead I see only a list of these titles, without know if there is something inside, and a dashboard born to watch the situation quickly and not to hide the informations.

I suggest to show the number of "contacts, activities, history, documents, opportunities, campaigns, leads, member organizations, cases, quotes, invoice,s contracts, products and services purchased, bugs, projects, security groups," linked to the accoint, close to or into these tabs of the vertcal accordion menu of every single account page.

How much time you needed to know which tab has something inside? and after all of that work, how do you feel to have the situation under control? Can you imagine to feel more comfortable knowing in few seconds which tabs has something inside and which not? I think yes.

Example account page:
https://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DAccounts%26offset%3D1%26stamp%3D1496934067023369100%26return_module%3DAccounts%26action%3DDetailView%26record%3D10ef652e-c584-0ec9-01f9-59382e714d33

If for example I have to call one contact, then I will need minutes only to check what is linked about, and I would save minutes with this little feature/UI trick.

How it look actually the account page
http://www.matteoraggi.com/account_now.png

and how it could looks with this new feature(mockup):
http://www.matteoraggi.com/account_featured.jpg

**Comment by pgorod** [comment]
I see my contacts subpanels are open by default.

Aren't there some settings to control whether the subpanels are open or closed by default? 

Or perhaps it's memorized and does whatever you used the last time you visited that screen?

**Comment by gunnicom** [comment]
Yes suite should remember the state, but they are too lazy to fix bugs:

https://github.com/salesagility/SuiteCRM/issues/2767

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show the contacts by default from the account page view](https://trello.com/c/DKcwm3uc/193-show-the-contacts-by-default-from-the-account-page-view)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by gunnicom** [comment]
@Dillon-Brown It is not a suggestion, it is a bug https://github.com/salesagility/SuiteCRM/issues/2767
