### ISSUE TITLE
Studio export customizations does not export custom fields

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3682]
#### Issue

I've created some fields in studio and want to export these modifications.
In manifest.php I cannot find the fields.
#### Expected Behavior

Fields section in manifest.php
#### Actual Behavior

No Custom fields are exported.
#### Steps to Reproduce

1.create some fields in Studio in one Module
2. start export customizations
3. Fileds are missing
4.

#### Your Environment

* SuiteCRM Version used: 7.8.4

**Comment by ChangezKhan** [comment]
This issue is already logged #3064

**Comment by chris001** [comment]
@ChangezKhan Correct.  Fix found in #3081 and fixed code provided in #3086 yet it has not been merged.
