### ISSUE TITLE
Download PDF for Reports not respecting date filtering on MySQL

### ISSUE THREAD

**Issue by david-pili** [salesagility/SuiteCRM#3686]
#### Issue
Reports show the correct filtered data based on date filtering on the web GUI, however downloading a PDF will remove date filtering and return every result that matches the remaining conditions.

#### Expected Behavior
The downloaded report should match the web report.

#### Possible Fix
The SQL query that is generated does not format the date correctly for MySQL it instead generates a query with the date in the format the end user has selected under their advanced account settings. Like this.
`WHERE ( accounts.name LIKE CONCAT('Great' ,'%') AND accounts:notes.date_entered >= '04/30/2017') AND  accounts.deleted = 0  ORDER BY accounts:notes.date_entered DESC`
MySQL then outputs _warning incorrect datetime value_ but then still runs the query and simply returns all values that match the other parts of the WHERE statement.

If the end user changes their date format to match the MySQL date format of y-m-d the issue goes away

A quick query against a MSSQL database makes me think that MSSQL is not effected by this, a query of `WHERE ModifiedOn > '04/14/2017'` 
Returns the expected data on MSSQL

#### Steps to Reproduce
1. Change account Date format to M/D/Y
2. Create a report with date created greater than or equal to as one of the parameters 
3. Add a second parameter such as account name
3. Download PDF of the report

#### Your Environment
* SuiteCRM Version used: 7.8.4, 7.9
* Environment name and version Apache, MySQL, php5
* Operating System and version : TurnKey GNU/Linux 14.1 / Debian 8.8 Jessie

**Comment by Dillon-Brown** [comment]
@david-pili Put up a fix that should resolve this issue. Let me know how you get on.

**Comment by david-pili** [comment]
Works perfectly, thank you for the quick fix.

**Comment by david-pili** [comment]
Just a follow up on this, it appears that this fix results in blank reports when using a greater then + lesser then date condition on a report if you leave the lesser then field blank. Previously report would be generated and only consider the greater then value.

**Comment by Dillon-Brown** [comment]
@david-pili Should be fixed now. The condition should also correctly include the current date when filtering.
