### ISSUE TITLE
Global search issue for contacts, leads, accounts

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#369]
We had same issue as:

https://suitecrm.com/forum/suitecrm-7-0-discussion/3824-global-search-box-in-suite-7-2#21843

We solved it like: (this is message from my external programmer, i cant fix it here)

Hi, our fix for this issue for our SuiteCRM 7.3, and he add me the solution for it.
## His message:

The problem is than on this sql part:
OR ( email IN (select bean_id ...

should be
OR ( contacts.id IN (select bean_id ...

This wrong sql is produced by include/SearchForm/SearchForm2.php + ...metadata/SearchFileds.php for Contacts, Accounts, Leads or any 'person' module available in global search
A solution is to change
/custom/modules/Contacts/metadata/SearchFileds.php
/custom/modules/Accounts/metadata/SearchFileds.php
/custom/modules/Leads/metadata/SearchFileds.php

files and set the email field like this:
'email' =>
array (
'query_type' => 'default',
'operator' => 'subquery',
'subquery' => 'SELECT eabr.bean_id FROM email_addr_bean_rel eabr JOIN email_addresses ea ON (ea.id = eabr.email_address_id) WHERE eabr.deleted=0 AND ea.email_address LIKE',
'db_field' =>
array (
0 => 'contacts.id',
),
),

I only replaced db_field array value with "0 => 'contacts.id'" instead of "0 => 'id'"

Another solution is to install "SecurityGroups - Full Edition" module. This module replaces the SearchForm2.php file with another one, which seems to resolve bugs from original SearchForm2.php

---

We hope, that help you guys :)

Miky

**Comment by Mausino** [comment]
Now we know if you upload (install) the Security Groups Full Edition, it modifies the include/SearchForm/SearchForm2.php and if you disable this module (or uninstall) it modifies the SearchForm2.php and after in pop up windows for Select function or search does not work the seach function of names, emails of cotntacts and etc. modules !!!

**Comment by Jason-Dang** [comment]
Can no longer Replicate in Suite 7.8.x. Global search appears to work fine on Contacts, Leads and Accounts using both Basic and Advanced. No PR references this issue.

**Comment by Mausino** [comment]
@Jason-Dang this issue is almost 3 year old 💃 and i think it should be close. if you want, close this ticket. I only inform that SecuritySuite module (3rd extension party) modifies the files of search.

**Comment by Jason-Dang** [comment]
@Mausino That is true, I am just confirming that the issue cannot be replicated in the LTS release of 7.8.10 so that our Product team can assess and close the issue.
