### ISSUE TITLE
Sidebar Recently viewed and Favorites: edit icon is missing

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3693]
In the SuiteP theme, for some reason the pencil icons to go directly into the Edit view of the records listed on the sidebar (Recently viewed and Favorites) have gone missing.

#### Issue
Perhaps this was done on purpose, but I see it as useful functionality... why not leave it there?

#### Expected Behavior
![sidebar](https://user-images.githubusercontent.com/15945027/27034668-703b6e8c-4f76-11e7-8772-c0c4b0594007.jpg)

#### Actual Behavior
No pencil icon, no direct access to Edit screen.

#### Possible Fix
I will provide PR.

#### Your Environment
* SuiteCRM Version used: 7.9 on the SuiteCRM live demo

**Comment by bmwtourer** [comment]
Thank you for fixing this
Just a hint and I am sure that many will share the same thoughts...
**The major complaint I get from my users (since 2010) is that they need too many clicks to perform tasks,
keeping and or adding such shortcuts will help a lot** 
Serge
