### ISSUE TITLE
Describe security bug reporting process

### ISSUE THREAD

**Issue by krzyc** [salesagility/SuiteCRM#3702]
#### Issue

As suggested by @sergio91pt reporting security problems by public tracker is not safe.

#### Expected Behavior
Pages about reporting bugs like
https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM
https://suitecrm.com/forum/bug-tracker/4799-found-a-bug-in-suitecrm
should contain informations about posting security problems directly to security team without disclosing them to public.

**Comment by pgorod** [comment]
I know from [here](https://suitecrm.com/forum/suitecrm-7-0-discussion/13955-security-issues#46741) that you can email security@suitecrm.com.

But I'm not sure where exactly that's publicized. Maybe now is the right time to have a "Security" page on the website.

**Comment by samus-aran** [comment]
Updated Readme.md, How to Contribute, Wiki and we'll update the website accordingly.
:+1:
