### ISSUE TITLE
Cannot sort by "Account Name" in "Target Lists => Details => Contacts"

### ISSUE THREAD

**Issue by tschiew** [salesagility/SuiteCRM#3704]
#### Issue
It's not possible to sort by "Account Name" in "Target Lists => Details => Contacts". Sorting by name, mail and phone is possible.

#### Expected Behavior
The sorting should be possible also for column "Account Name".

#### Your Environment
* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 52.1.2
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Windows 10
![suite](https://user-images.githubusercontent.com/11558132/27077117-50f703e2-502f-11e7-9cf4-8ba576d46179.PNG)

**Comment by tschiew** [comment]
In which version would the bug fix be included?

**Comment by Dillon-Brown** [comment]
Hi @tschiew. Thanks for the reminder, It seems I forgot to create a PR for this issue :). A fix for this issue should be included in the next release.
