### ISSUE TITLE
BUG - Dropdown editor: when you edit an existing dropdown the display labels are truncated at the first quote (or apostrophe) found

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#3705]
#### Issue

If you have dropdowns display labels that contain quotes or apostrophes, when you edit the dropdown and you add another element or just edit the display label of any element the resulting dropdown will have all the display labels truncated at the first quote (or apostrophe) found.

Note that the truncation takes place in all display labels except the new ones or the one being edited.

I noticed a second bug: only one lable can be edited. Then either you save and exit the dropdown editor or you are stuck in the inline edit mode of the label.
#### Expected Behavior

The display labels should be maintained intact.

#### Actual Behavior

The display labels are truncated at the first quote or apostrophe found..

#### Steps to Reproduce

1. Create a new drop down in Admin -> Dropdown editor
2. Add a few items and inside the display label put one or more ' (quote or apostrophe)
3. Save
4. Edit and save again
5. The display lables containing quotes (apostrophes) are truncated

#### Context

Medium priority bug

#### Your Environment

* SuiteCRM Version used: Softaculous online test and latest 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 64 latest
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): both Linux + Windows

**Comment by Dillon-Brown** [comment]
Duplicate #1456
