### ISSUE TITLE
Create a security group is blank

### ISSUE THREAD

**Issue by sergio91pt** [salesagility/SuiteCRM#3707]
#### Issue

A typo in a function name is preventing the proper display of the "Create a Security Group" page.

##### Stacktrace
```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function array_keys_exists() in /home/sergio/crm_data/www/include/EditView/EditView2.php:932
Stack trace:
#0 /home/sergio/crm_data/www/include/MVC/View/views/view.edit.php(116): EditView->display(true)
#1 /home/sergio/crm_data/www/include/MVC/View/SugarView.php(199): ViewEdit->display()
#2 /home/sergio/crm_data/www/include/MVC/Controller/SugarController.php(425): SugarView->process()
#3 /home/sergio/crm_data/www/include/MVC/Controller/SugarController.php(368): SugarController->processView()
#4 /home/sergio/crm_data/www/include/MVC/SugarApplication.php(105): SugarController->execute()
#5 /home/sergio/crm_data/www/index.php(52): SugarApplication->execute()
#6 {main}
```

#### Expected Behavior

Security group creation form is displayed.

#### Actual Behavior

There is no form. Basically a blank page.

#### Steps to Reproduce

1. Login to crm
2. Open create security group page (`https://crm.crmdev/index.php?module=SecurityGroups&action=EditView`)
3. Form is not displayed

#### Your Environment

* SuiteCRM Version used: hotfix branch

**Comment by samus-aran** [comment]
@sergio91pt - I haven't been able to reproduce this.
array_keys_exists is a standard PHP function.
What is PHP environment you on?
