### ISSUE TITLE
Gantt chart fails to render

### ISSUE THREAD

**Issue by uniun** [salesagility/SuiteCRM#3711]
#### Issue
Gantt chart is not rendered.
Maybe this is becase ProjectViewGanttChart::display() calls parent display method on [view.ganttchart.php#L78](https://github.com/salesagility/SuiteCRM/blob/master/modules/Project/views/view.ganttchart.php#L78) without setting a current bean record and it dies on [view.detail.php#L101](https://github.com/salesagility/SuiteCRM/blob/master/include/MVC/View/views/view.detail.php#L101)

#### Expected Behavior
Gantt chart is rendered

#### Actual Behavior
Blank screen is shown

#### Steps to Reproduce
1. Open any Project
2. Select 'View Gantt' action

#### Your Environment
* SuiteCRM 7.9.0
* Browser: Vivaldi 1.9.818.50 (Stable channel) (32-bit) (Win10 64-bit)
* Server env: 10.1.23-MariaDB, Apache/2.4.25, PHP/5.6.30
* Server OS: CentOS 7.3 (64-bit)

**Comment by Dillon-Brown** [comment]
Hi @uniun I can't seem to replicate this. Seems to work fine for me on the same browser:

![issue-3711](https://user-images.githubusercontent.com/26431166/27129395-047330a6-50fa-11e7-9813-2ebb5c16df24.png)

Can you provide error logs?

**Comment by uniun** [comment]
suitecrm.log
`
Wed Jun 14 14:11:11 2017 [3685][1][FATAL] Exception handling in /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/Controller/SugarController.php:367
Wed Jun 14 14:11:11 2017 [3685][1][FATAL] Exception in Controller: Error retrieving record. This record may be deleted or you may not be authorized to view it.
Wed Jun 14 14:11:11 2017 [3685][1][FATAL] backtrace:
#0 /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/View/views/view.detail.php(101): sugar_die('Error retrieving ...')
#1 /home/architek/domains/archigroup.lt/public_html/crm/modules/Project/views/view.ganttchart.php(78): ViewDetail->display()
#2 /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/View/SugarView.php(199): ProjectViewGanttChart->display()
#3 /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/Controller/SugarController.php(399): SugarView->process()
#4 /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/Controller/SugarController.php(336): SugarController->processView()
#5 /home/architek/domains/archigroup.lt/public_html/crm/include/MVC/SugarApplication.php(105): SugarController->execute()
#6 /home/architek/domains/archigroup.lt/public_html/crm/index.php(52): SugarApplication->execute()
#7 {main}
`

As I  said, I've called print_r() on view.detail.php(101) - Project bean is empty.

BTW. I don't know if it matters but this is not a clean install. It was 7.8 and then it was updated to 7.9

I can create login for testing, maybe it would help?

**Comment by uniun** [comment]
I know what has happened.

It looks like that link to Gantt chart has changed in 7.9 but in 
`/custom/modules/Project/metadata/detailviewdefs.php` it was still old `index.php?module=Project&action=view_GanttChart&project_id={$id}`

It looks like that I didn't update detail view after installing 7.9.

**Comment by Mausino** [comment]
@uniun we had same problem... but this is custom part of SuiteCRM and this is not changing in upgrade process. I was not sure if is possible fix by code... @samus-aran  created the pull request for upgrade process that user will notify by system that between modules and custom/modules are code changes, sorr i can find the pull request number

**Comment by samus-aran** [comment]
@uniun & @Mausino - The PR is here. https://github.com/salesagility/SuiteCRM/pull/3653

It won't be included in the 7.9.1 or 7.8.5 release as we haven't got round to testing it fully - but @uniun you are more than welcome to help us out by doing so.

I willclose this issue as it is specific to custom folders.

**Comment by incodevelope** [comment]
I had exactly the same problem after upgrading from 7.8.2 to 7.8.28, and then trying upgrading to 7.9, 7.10 and 7.11.3. "View Gantt" item inside any Project always gave "Error retrieving record. This record may be deleted or you may not be authorized to view it." or blank page.

Solved thanks to unium:

`/custom/modules/Project/metadata/detailviewdefs.php` had wrong URL for "View Gantt" menu item. I changed it from 

`index.php?module=Project&action=view_GanttChart&project_id={$id}`

 to 

`index.php?module=Project&action=view_GanttChart&record={$id}`
