### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by aeroflyte** [salesagility/SuiteCRM#3714]
#### Issue
Trying to upgrade from

Version 7.8.2
Sugar Version 6.5.24 (Build 509)

to the latest version I got to the point where I uploaded the zip file and the preflight check started.

And I get the below error.

Warning: Error while sending QUERY packet. PID=974563 in /home/compos24/public_html/SuiteCRM/dir/include/database/MysqliManager.php on line 135

Appreciate any help.

John

#### Expected Behavior
Wanted to upgrade

#### Actual Behavior

Fails

#### Steps to Reproduce

More from the log:

Here are the entries on the log during the upgrade:

Tue Jun 13 13:58:06 2017 [559731][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [320721][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [328676][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [333584][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [376743][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [377154][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [399188][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [398916][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [374703][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [392340][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [380927][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [337568][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [380737][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [334880][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [376218][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 17:05:59 2017 [383399][-none-][FATAL] Retrieving record by id users:1 found Query Failed: SELECT users.* FROM users WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: CREATE TABLE temp (id varchar(36)): MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: INSERT INTO temp (id) VALUES ('abcdef0123456789abcdef0123456789abcd'): MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: UPDATE temp SET id = '100000000000000000000000000000000000' WHERE id = 'abcdef0123456789abcdef0123456789abcd': MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: SELECT id FROM temp WHERE id='100000000000000000000000000000000000' LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Get One Failed:SELECT id FROM temp WHERE id='100000000000000000000000000000000000': MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: DELETE FROM temp WHERE id = '100000000000000000000000000000000000': MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: ALTER TABLE temp add COLUMN test varchar(50) NULL : MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: ALTER TABLE temp modify COLUMN test varchar(100) NULL : MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: ALTER TABLE temp drop COLUMN test: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: DROP TABLE IF EXISTS temp: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Checking privileges: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: SELECT version() version LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Get One Failed:SELECT version() version: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Query Failed: SELECT id FROM upgrade_history ORDER BY date_entered desc: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:41:56 2017 [951122][1][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.
Tue Jun 13 18:46:39 2017 [974563][1][FATAL] Query Failed: SELECT id FROM upgrade_history ORDER BY date_entered desc: MySQL error 2006: MySQL server has gone away
Tue Jun 13 18:46:39 2017 [974563][1][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.

1.
2.
3.
4.

#### Context

Can not upgrade

#### Your Environment

Hosted on InMotion

* SuiteCRM Version used:

* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
Hi @aeroflyte, I'm the same guy you're talking to [on the forums](https://suitecrm.com/forum/installation-upgrade-help/14616-failure-while-doing-upgrade) (pgr there).

You were doing it in the right place there. Not here. This is not a place to "get help", it is a place for technical bug reports and for developers to interact and cooperate on development. 

Also, we're basically the same people looking at both places, so you don't necessarily get a better response here. If it's alright with you, I ask you to close this Issue and we can continue there.

You see, 99% of problems reported are just issues in a single system, we first have to rule out sysadmin problems, mis-configurations, permissions problems, etc. We can still open an issue here if it proves appropriate, but at that point we should have a more technical diagnosis, and be able to reproduce your bug in other systems as well. I'm sure you'll understand.

**Comment by aeroflyte** [comment]
Oh sure thing!  Sorry. 

John Melilli
Cell: 856-534-2890
