### ISSUE TITLE
Exporter Query

### ISSUE THREAD

**Issue by lewisje1991** [salesagility/SuiteCRM#372]
When exporting notes if you search on the related to field it puts the wrong field into the query for exporting the records.

1. Search for notes related to an account.
2. Select all notes returned in search.
3. Export 

Database Failure.

**Comment by JimMackin** [comment]
This seems to happen when exporting any module where the search has been on a relationship (relate fields seem fine, relationship fields are not).

**Comment by JimMackin** [comment]
The default behaviour of the create_export_query method in a bean uses create_new_list_query which accounts for relationships. The create_export_query method in accounts however generates it's own (broken) SQL. It's not clear why this bean needs special treatment.

**Comment by shogunpol** [comment]
This issue was tested on recent version of SuiteCRM(7.7.2) , and it has not appear.
@lewisje1991  , if you agree this is not an issue any longer, can you close this issue?
