### ISSUE TITLE
History summary not sorted SuiteCRM 7.9

### ISSUE THREAD

**Issue by david-pili** [salesagility/SuiteCRM#3723]
#### Issue
History summary is not sorting based on date on 7.9
#### Expected Behavior
All items in history should be sorted by date modified
#### Actual Behavior
No sorting occurs
#### Possible Fix
Popup_picker.php includes a 'sort_value' in its array generation for each type of activity, this value is then never used for sorting. Multidimensional associative array sorting can be achieved with a simple one liner
array_multisort (array_column($array, 'sort_value'), SORT_DESC, $array);
furthermore I would recommend sorting the $summary_list array in a similar manner

#### Steps to Reproduce
1. Log into SuiteCRM demo
2. navigate to an account and view history summary

#### Your Environment
SuiteCRM demo environment

**Comment by pgorod** [comment]
@Dillon-Brown I would call this a bug, not a suggestion, because a "history" is, by definition, something that should be sorted by date...

The only thing that can be questioned is whether you need it sorted by `Due date`, `Modified date`, or `Created date`, I wonder if any of these is being used currently?

**Comment by david-pili** [comment]
Agreed, this should be a bug not a suggestion. Especially considering that this was the behavior before 7.9. I see no reason why a sort value would be created when building the arrays if it wasn't going to be used. 

From the popup_picker we can see that meetings and calls are supposed to be sorted by date_start, emails date_sent and notes date_modified.

**Comment by Dillon-Brown** [comment]
Agreed, each tab should be sorted by date by default. I'll raise this as a bug. However I would also suggest raising another suggestion for sorting based on 'Subject', 'Status', 'Contact' and 'Date' within the popup.

**Comment by hannu78** [comment]
Seems that this bug is present also in 7.8.18 LTS.
