### ISSUE TITLE
IMAP server delete button on DetailView

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#3727]
#### Issue

There should be an option to delete an email from IMAP server from the detailview/listview.

#### Expected Behavior

Users can Edit, Duplicate, Delete, Reply, Reply All, Forward but not Delete from IMAP.

#### Actual Behavior

There should be a button to delete an email from IMAP server.

#### Steps to Reproduce

1. Open email listview
3. Select an email
4. Click Actions 
5. No option to delete from IMAP server

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by RobinHind** [comment]
I also have this issue but have found that if i rename the file: custom/modules/Emails/metadata/listviewdefs.php
and refresh the email screen, my newmail icon refresh etc dissapear but under the bulk actions i get a delete option!
I don't know enough to fix this but thought it might point someone in the right direction?

also does anyone elses attachments show up in listview? mine don't!
![screen shot 2017-06-16 at 13 39 34](https://user-images.githubusercontent.com/29143013/27227101-eade7c08-5299-11e7-830b-06120b04f805.png)
![screen shot 2017-06-16 at 13 39 42](https://user-images.githubusercontent.com/29143013/27227102-eae14d02-5299-11e7-8c57-53f8c52fb92d.png)

**Comment by ErMaqui** [comment]
This bug also appears on 7.9.4-7.9.7 versions

**Comment by ErMaqui** [comment]
Any info about this? This bug are present on 7.9.11 too. I need the delete option to clean spam messages from CRM accounts.

**Comment by labcerouno** [comment]
I guess we could treat it as Medium Priority, don't you think? In a month it will be its 1st anniversary. And, by the way, the delete option will follow the rules for the security roles?

**Comment by labcerouno** [comment]
Happy birthday, issue!

**Comment by jyotiraghav93** [comment]
Looking for the same , bulk action of deletion on emails module , any fix?

**Comment by bongaquino** [comment]
bug!

**Comment by JohnDuck** [comment]
Version 7.10.7
Sugar Version 6.5.25 (Build 344)

**Bug -> cannot delete emails (IMAP server)**
for the present time, one person cleanses / deletes the spam manually in the mail program
PS high priority bug is not corrected for a year . . . .

**Comment by Mausino** [comment]
@JohnDuck we also must delete the spam by external program...  it's totally weird situation that in LTS 7.8 you have this function, but in latest version doesn't

Also true is that is, that email module has more bigger problems as this one 🗡 . Filter the bugs by word email and you will see that is more as 200 bugs related to emails :(

**Comment by labcerouno** [comment]
This feature is very commented in the forums. I think it should be high priority. @Dillon-Brown can't we add it to the next milestone?

**Comment by jyotiraghav93** [comment]
deleting the imported emails on suitecrm from detailview can also delete the email on imap server using before_delete logic hook as , 

Add the before_delete logic hook in emails module,
File Name : custom/modules/Emails/logic_hooks.php
$hook_array['before_delete'] = Array(); 
$hook_array['before_delete'][] = Array(30, 'Delete the emails from crm to imap server', 'custom/modules/Emails/delEmailCls.php','delEmailCls', 'delEmailFunc');

Add below code in file custom/modules/Emails/delEmailCls.php,

<?php
class delEmailCls{
	function delEmailFunc(&$bean,$event,$arguments){
		require_once('modules/InboundEmail/InboundEmail.php');
		$inbouneEmail = new InboundEmail();
		$inbouneEmail->retrieve($bean->mailbox_id);
        $uid = $bean->uid;
		//Deleting the email on mail server also
        $inbouneEmail->deleteMessageOnMailServer($uid);
	}
}
?>

It working fine :)

**Comment by Mausino** [comment]
@jyotiraghav93 should you create the pull request for it?

**Comment by jyotiraghav93** [comment]
ok will do

**Comment by ahmadtibrahim** [comment]
This issue still going on? coz i cant find the delete options as well.!
