### ISSUE TITLE
7.9.1 Email: Leads>Activities>Compose Email = multiple instances of TinyMCE editor on page

### ISSUE THREAD

**Issue by someguynamedphil** [salesagility/SuiteCRM#3732]
![screen shot 2017-06-16 at 9 54 43 am](https://user-images.githubusercontent.com/10147455/27229611-36a656ee-527a-11e7-8bea-592b16eef210.png)
Only occurs when composing email via Activities pop up
When composing via Collaborations>Emails only the expected one instance of TinyMCE appear

**Comment by stenfalp** [comment]
Same problem here. 
Also it seems not possible to use text only templates. Furthermore variable substition of, say, $account_name doesn't work.

**Comment by Mausino** [comment]
Same problem for all modules when you're creating/composing from History/Activities subpanel

**Comment by Dillon-Brown** [comment]
This should be resolved with fix #3802
