### ISSUE TITLE
Undefined values using templates from account module in 7.9.1

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#3735]
#### Issue

The email templates don't seem to work properly: a window with undefined values appear after the selection of a template. 

#### Expected Behavior

A window with a warning message should appear.
The message should be: Apply an Email Template
"This operation will override the email Body and Subject fields, do you want to continue?"

#### Actual Behavior

A windows with two undefined values appears.
![cattura](https://user-images.githubusercontent.com/22146544/27234247-a3440ef8-52bc-11e7-8233-a4dbcf1b298a.PNG)

#### Steps to Reproduce

1. Enter an account
2. On the Activities panel click Create task ->  compose email
3. Select an email template

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version: Firefox v54 
* Operating System and version: Windows 10

**Comment by pgorod** [comment]
This came up in the forums today, in a slightly different form:

- go to a Contact detail record
- click the email address to start the Compose modal dialog
- select a template
- see the "undefined" error

**Comment by pgorod** [comment]
This is still present in 7.9.4, [more users ](https://suitecrm.com/forum/suitecrm-7-0-discussion/15077-email-template-issue?start=15#51020) are getting trapped in this and can't send any email.

@Dillon-Brown maybe this should be High Priority...
