### ISSUE TITLE
Report Module - HTML contains invalid UTF-8 character(s)

### ISSUE THREAD

**Issue by jefrysuarez** [salesagility/SuiteCRM#3742]
Hello,

#### Issue

I found a issue, and also found what is the caused of the problem, but doesn't know how to fix this.

I create a basic report that how Open cases group by clients:
![image](https://user-images.githubusercontent.com/5199918/27273459-1ed44b46-549d-11e7-9077-2c1b9df535dc.png)

But when i try to "Download PDF", i receive a white HTML page with the message "Report Module - HTML contains invalid UTF-8 character(s)"

#### Possible Fix
Like i mentioned before, i found what caused the issue, it is a spanish accent symbol(ó) in the description field of an case:
![image](https://user-images.githubusercontent.com/5199918/27273609-d2393ff2-549d-11e7-9c20-80077f2e57a1.png)

If i remove that symbol(ó), everything works ok.

**Comment by bmwtourer** [comment]
I can confirm that the proposed fix works great!
I put the file in custom... and rebuilt....  SUCCESS! :-)

@Dillon-Brown Thank you!
Serge
