### ISSUE TITLE
7.9.1 Cannot Select Email Recipients from Anywhere in SuiteCRM (other than Email module)

### ISSUE THREAD

**Issue by pstevens71** [salesagility/SuiteCRM#3746]
Both in 7.9.0 and 7.9.1 when you try to create an email from the activities panel of a Lead/Contact/Target/Opp, or whatever. 

I've also tested this on the Demo version and same issue.   Can't select contacts on the activity panel in order to send an email to.

#### Issue

 There is no way to select the email recipient from any Activity panel of another module in SuiteCRM.  The popup box does not contain the "search contact, etc" buttons.  First of all, if you're sending and email from the contact, it should default to the contact, like it did in previous versions, that no longer happens.  Further, the buttons that appear in the email module to be able to select a contact don't show on the pop up, so it's impossible (unless you cut and paste an email address in) to send an email from anywhere in suiteCRM but the Email module (that doesn't work either for selecting contacts, I've already put in a bug report for that).
#### Expected Behavior

If you send an email from a contact for example, the "to" should be populated with the contact's email.  Further, the buttons should be available to select another contact if desired.
#### Actual Behavior

Field is blank and there is no way to search for a contact.

#### Possible Fix

?????
#### Steps to Reproduce

1. Open a contact
2.Open Activities, select "compose email"
3. Try to select a contact to send it to.

#### Context

I think this is a pretty high priority that you cannot send emails from SuiteCRM.

#### Your Environment

* SuiteCRM Version used: 7.9.1  (also occurs on the hosted demo version)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):   Chrome Version 51.0.2704.63
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6
* Operating System and version (e.g Ubuntu 16.04):

![suiteemail](https://user-images.githubusercontent.com/29544935/27288311-58cd6508-54d4-11e7-8c83-bc0531a37b05.jpg)

**Comment by Dillon-Brown** [comment]
@pstevens71 Do you have an inbound/outbound email account setup? 

![issue-3746](https://user-images.githubusercontent.com/26431166/27288829-e9c62f38-54ff-11e7-806a-df975afbb701.png)

I believe both this and the body sizing issue is related to having an unknown inbound/outbound email account.

**Comment by pstevens71** [comment]
Yes, I have both an inbound and outbound email address set up.

**Comment by pstevens71** [comment]
Actually, you put me on to something.  I double checked my email accounts and they were both set up for inbound and outbound correctly.  Just for giggles, I "deactivated" them and reactivated them and now my email is working like the pic you sent.  It appears to work now.
![suiteemail accounts](https://user-images.githubusercontent.com/29544935/27289621-8a9e6466-54d8-11e7-9c68-2acf93f1fd28.jpg)

**Comment by Dillon-Brown** [comment]
Might be a problem with email settings not saving correctly. If this reoccurs and you are able to consistently replicate it, please re-open the issue.
