### ISSUE TITLE
Suite7 - Subpanel pop up window cosmetic issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#3749]
#### Issue

When i use select function on subpanel, There is a cosmetic menu issue on bulk drop down menu.
![screenshot_2](https://user-images.githubusercontent.com/22373035/27318426-f2109f1c-5594-11e7-85e3-dfd202590feb.png)

![screenshot_1](https://user-images.githubusercontent.com/22373035/27318431-f79fe582-5594-11e7-8eac-bc9ce0ecc524.png)

#### Expected Behavior

it should be like other bulk menu.
Like this ;
![screenshot_3](https://user-images.githubusercontent.com/22373035/27318474-2af69926-5595-11e7-961f-8e1ff74bb52d.png)

#### Steps to Reproduce

1. Open any module
2. On the any sub panel, select 
3. When you see pop up window, look at the bulk action menu.

#### Your Environment

* SuiteCRM Version used: 7.8.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 54.0
* Environment name and version (e.g. MySQL, PHP 7): Php 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by dursuntosun** [comment]
Anybody solve this issue? It is really unusable.

**Comment by horus68** [comment]
I don't use 7.8.x versions so can't check. 
Did you already upgraded to latest 7.8.15 ? 
Or maybe test a local copy to go all the way into 7.10

**Comment by dursuntosun** [comment]
Yes, i already upgraded to latest 7.8.15. But same problem is continue. 
it is early upgrade to 7.10.

**Comment by horus68** [comment]
Sorry for that, hope other user can help you. 
Please update the details on your system info in the first post

**Comment by dursuntosun** [comment]
Thank you for response. I waiting for who will solve my problem :(

**Comment by dursuntosun** [comment]
I think, it is not difficult to solve this issue :(

**Comment by Mausino** [comment]
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL. Should it be closed.
