### ISSUE TITLE
Target List: Empty contact list after sorting by email

### ISSUE THREAD

**Issue by tschiew** [salesagility/SuiteCRM#3750]
#### Issue
It's not possible to sort by "Email" in "Target Lists => Details => Contacts". 

After clicking on the sort icon, the contact list is empty. 

The issue occurs with and without activated AJAX. 

#### Expected Behavior
Like sorting by name or by phone, sorting by mail should display the contact list in the right order.

#### Actual Behavior
The contact list is empty (see Screenshot). 
![github](https://user-images.githubusercontent.com/11558132/27319611-9bc7d690-5592-11e7-83be-f8d388254302.PNG)

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 52.1.2
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by Dillon-Brown** [comment]
@tschiew I'm unable to replicate this on 7.9. Are you able to replicate this on a fresh installation or is this an upgrade?

![targetlistcontacts](https://user-images.githubusercontent.com/26431166/27324403-0f5e2ea6-559d-11e7-955b-d843e743d4d2.png)

**Comment by tschiew** [comment]
@Dillon-Brown While trying to reproduce it: The problem does not occur with every list - some lists work, some others not. 
The installation itself is fresh (files on HDD), but works on a previously migrated Sugar-DB (Sugar migrated with your Package to Suite 7.9, then installed a fresh Suite 7.9 and bind it on the "old" DB).

When I refresh the page (F5) after getting the error, the gui seems to be broken - none of the sub-lists appear anymore. 

![github](https://user-images.githubusercontent.com/11558132/27326869-031a8dbe-55ad-11e7-8cd1-e3ff51470fc4.PNG)

And: When I browse to another list with that error, the gui is also broken (without trying to sort by mail before). Only after re-login, the contacts appear again.

=> Sorting by mail in list 1 works...list 2 works, too....list 3 has the error, the contact list is now empty. After refreshing the page, the gui is broken (see Screenshot above)....browsing to list 4 shows the same broken gui...list 5 works.

I cannot see any important differences in those lists.

**Comment by pgorod** [comment]
@tschiew what do you see in [your logs](https://pgorod.github.io/The-two-logs/) at the time of the broken screens?

**Comment by tschiew** [comment]
At the time of the broken screens, there is the following stacktrace in suitecrm.log:
[SuiteCRM_Stacktrace.txt](https://github.com/salesagility/SuiteCRM/files/1087990/SuiteCRM_Stacktrace.txt)

**Comment by pgorod** [comment]
Can you check if one of those Contacts, for some reason, has more than one primary email address defined in SQL table `email_addr_bean_rel`? 

This would require some ability with SQL or using phpMyAdmin... you can get some notions of the involved tables [here](https://pgorod.github.io/How-Emails-Stored/).

**Comment by tschiew** [comment]
I've checked it: Yes, there are mostly more than one primary address - but also for those lists where the error NOT occurs. 

My statement:
```
SELECT 
	cont.first_name, cont.last_name, cont.id 
FROM 
	contacts cont, 
	prospect_lists_prospects pros,
	email_addr_bean_rel rel,
	email_addresses mail 
WHERE 
	pros.related_id = cont.id 
	and rel.bean_id=cont.id 
	and rel.bean_module = 'Contacts'
	and rel.primary_address = 1
	and pros.prospect_list_id = '24372318-66b0-80b8-360f-4ffecbabfdb9'
	and pros.deleted = 0
	and mail.id = rel.email_address_id
	and mail.deleted = 0;
```	

Result:
The result set length is much longer than the length of the list in gui. 

I've also checked it for a single user:

`SELECT id, email_address_id, primary_address FROM email_addr_bean_rel where bean_id = 'dbf67a6b-4f06-f155-561b-4d6fa5192522' and primary_address = 1;`
(used contacts.id as parameter)
=> two rows in result set

`SELECT * FROM email_addresses WHERE id in (<2x email_addr_bean_rel.id from previous result set>) AND deleted = 0;`
=> two rows in result set: One old address and the current address.

**Comment by pgorod** [comment]
Ok, since you have that error in your logs saying `Subquery returns more than 1 row`, if my interpretation of the subquery is correct, then it isn't expecting more than one primary email address per contact - which sort of makes sense.

On the other hand, against this interpretation, we have the fact that some of your lists don't give errors despite having more than one address per contact.

Do you have any idea on how this situation might have arisen in your database? Did you do any manual imports, or anything peculiar to load those contacts?

You could try making sure only one primary address is present per contact, to see if that fixes the original bug...

**Comment by Dillon-Brown** [comment]
Hi @tschiew, I'm unable to replicate this as a core issue. I suggest moving this to the [Community Forums](https://www.suitecrm.com/forum/suite-forum) for further assistance. Thanks.
