### ISSUE TITLE
Popup Studio and Calendar don't auto-close

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#3756]
#### Issue

When saving chaned labels in Studio, or when hovering over an event in the Calendar, a popup appears. This popup doesn't automatically disappear when expected.

#### Expected Behavior

Especially for Calendar events, I expect these popups to auto close when not hovering over the event anymore.

In Studio, this messages you get when saving changed labels, for example, used to be a message at the top of the screen that automatically disappear after a certain amount of time. Also, the screen isn't blocked, so you can continue working, so the work flow isn't interrupted.

#### Actual Behavior

Calendar event popups need a manual click on the close button to close.
Studio popups need a manual click on the close button to close, blocking the screen and all functions until you do so.

#### Steps to Reproduce

Calendar popups:

1. Create an event that appears on the Calendar
2. Go to the Calendar and hover over this event

Studio popups

1. Go to Labels of a module
2. Make a change and click save

#### Your Environment

* SuiteCRM Version used: 7.8.1 + SuiteP
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox & Chrome
* Environment name and version (e.g. MySQL, PHP 7): Php 5.6 & 7.0
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by ebogaard** [comment]
I can see this issue has been reported by someone else as well: #3564 
This issue is both about Calendar and Studio pop-ups, though.

**Comment by ebogaard** [comment]
Proposed two fixes to this issue, which are a modified source file and the related minified file.
This makes the Calendar popup auto-close when leaving the event with your mouse.

The Studio popup issue is still open.

**Comment by Dillon-Brown** [comment]
Hi @ebogaard have you made a pull request before? you can submit a PR to the SalesAgility SuiteCRM repo with your fix while referencing this issue in the title. Then we can label this issue as "Fix Proposed" and look at merging your fix into hotfix.

**Comment by ebogaard** [comment]
No, this is a first time PR. Hope I've done this right.
Let's see what happens ;-)

**Comment by fcorluka** [comment]
I just want to leave a comment, about code managing.
I have installed a fresh 'Version 7.10.15', and have this error. Been looking for days for a solution and this saved me. Why is this not in original CRM code, I don't know.
Please, please, please guys, put already all the fixes in the master code so that when I download a new version don't have to go into 2 years old GitHub post for the fix.

**Comment by ebogaard** [comment]
It looks like there's an error left in jssource/src_files/modules/Calendar/Cal.js at line 1085:
The old config ("{event: false},") is still there, making this an invalid json file. This will result in errors when recreating the minified files.

In the compressed file (modules/Calendar/Cal.js) the config is correct.
