### ISSUE TITLE
Resource calendar not accessible via ALL tab after upgrade from 7.9.0 to 7.9.1

### ISSUE THREAD

**Issue by maladrill** [salesagility/SuiteCRM#3757]
After upgrade from 7.9.0 to 7.9.1 Resource Calendar cannot be accesed via ALL tab in menu. When clicking Projects -> Resource Calendar (in side menu) everything is ok.

#### Actual Behavior
Click ALL tab and navigate to Resource callendar. You should see page with : {"content":"

As a first step I disabled AJAX in resource calendar. No change. 
I checked if resource calendar can be accesed via side menu in Projects module. It was.

In error log:
 PHP Notice:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' in /var/www/html/SuiteCRM-7.9.0/include/utils.php on line 3919, referer: http://mytestsuiteserver.ok/index.php?module=Project&action=index&parentTab=All

####  Steps to reproduce
- Fresh install 7.9.0
- install polish language pack
- repair and rebuild 
- upgrade to 7.9.1

Bug reproduces regardles of UI language used

#### Your Environment
* SuiteCRM Version used: 7.9.1 (upgraded from 7.9.0)
* Browser name and version: Chrome Version 58.0.3029.110 (64-bit), Firefox 53.0.3 (32-bit)
* Environment name and version: MySQL, PHP 7.1.5
* Operating System and version: centos-release-6-9.el6.12.3.x86_64

**Comment by Dillon-Brown** [comment]
@maladrill Resource calendar is working for me on 7.9.0 to 7.9.1 upgrade. Is this only a problem for you when upgrading 7.9.0 to 7.9.1? or does resource calendar also not work for you on a fresh 7.9.1 install.

**Comment by maladrill** [comment]
Resource calendar works fine as a module. I cannot navigate to it only when clicking through the ALL tab. It happened before when I upgraded fresh install to 7.8.5 but I did not have time to open the issue, and I can't remeber what version I used before upgrade.

What is interesting, in SalesAgility demo there is no link to resource calendar:
![suiteondemand](https://user-images.githubusercontent.com/12087022/27424945-157572ae-5737-11e7-8d5b-acc73018e47c.PNG)
where it should be:
![maladrill](https://user-images.githubusercontent.com/12087022/27425028-5cc60c22-5737-11e7-9c47-e9ae1edfb17f.PNG)

**Comment by Dillon-Brown** [comment]
@maladrill The resource calendar won't appear in the demo as it is a hidden field. It needs to be added through the admin panel's "Display Modules and Subpanels" so that would be unrelated to this issue.

Do you have any console logs when encountering this? or anything other than the PHP notice in your error logs? we can't seem to replicate this issue with fresh installs/upgrades.

**Comment by maladrill** [comment]
There is nothing in the console.
I made some checks - when I click on resource calendar the link is:
`myserverIP/index.php?module=Project&action=ResourceList&parentTab=All&ajax_load=1&loadLanguageJS=1`

Removing `&ajax_load=1` fixes the problem. Unfortunately there's nothing else in the logs I could help with. We can close it for now, and I will try to dig into the problem next week.

**Comment by Dillon-Brown** [comment]
@maladrill Will close the issue for now, please re-open if you make any progress or have any more info that helps with replication.
