### ISSUE TITLE
Import Progress bar

### ISSUE THREAD

**Issue by danieljsamson** [salesagility/SuiteCRM#376]
When importing records the progress bar doesn't move.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import Progress bar](https://trello.com/c/MM4vc4p0/151-import-progress-bar)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
