### ISSUE TITLE
7.9 Email composer document popup search 

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#3760]
#### Issue

When searching for a document using the email composer document popup. After selecting a document, the popup will close and will not be added to the email.

#### Expected Behavior

The selected document should be added to the email as an attachment.

#### Actual Behavior

The popup closes.

#### Steps to Reproduce

1. Open email composer in the email module
2. Click attach document
3. Search for an existing document
4. Click on the document name

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Mausino** [comment]
@Dillon-Brown yes we have same issue + we get pop up message: "Invalid email" after when we choose the record from filter(search) popup window in compose view of email. 

@PedroErnst you fixed many email issues with attachments + email addresses.. this is last one which remaining that will email module fully functional 👍

**Comment by Dillon-Brown** [comment]
No longer an issue
