### ISSUE TITLE
Only 1 theme SuiteP in 7.9.1,missing other themes

### ISSUE THREAD

**Issue by SonKai** [salesagility/SuiteCRM#3764]
#### Issue
Only 1 theme SuiteP provided in Admin->System->Themes, where are the others?

#### Expected Behavior
show all themes like : SuiteP SuiteR ...

#### Steps to Reproduce
1. login as admin
2. go to page : Admin -> System -> Themes

#### Your Environment
* SuiteCRM Version used: 7.9.1
* Browser name and version: all browser
* Environment name and version: php5.6

**Comment by likhobory** [comment]
https://suitecrm.com/forum/suggestion-box/13393-deprecation-of-suiter-suite7-themes-discussion-on-adopting-suitep
