### ISSUE TITLE
SuiteCRM sort badly by column 7.9.1

### ISSUE THREAD

**Issue by zden2k** [salesagility/SuiteCRM#3765]
#### Issue
SuiteCRM sort badly by column. 

#### Actual Behavior
When you click on item, the first sort will get ok. But at second click, which will sort in opposite direction, SuiteCRM sorts badly, because do nothing, but it should do ASC.

The problem is in SuiteCRM with some data. When I try it in your Demo, there is looking good.

We have different behavior across browsers. And we have different behaviour for different users. Bug is probably in wrong javascript code.

#### Expected Behavior
Sorting right.

#### Steps to Reproduce
1. sales, invoices, click date first time (that do DECS)
2. click second time (do notning, but it should do ASC)

#### Your Environment
* SuiteCRM Version used: 7.9.1 and 7.8.4
* Browser name: Across browsers randomly
* Environment name and version (e.g. MySQL, PHP 5): 
mysql 5.5.53, PHP 5.6.29-0+deb8u1
* Operating System and version (e.g Ubuntu 16.04): debian 8.7

**Comment by Dillon-Brown** [comment]
@zden2k Is there a particular browser you can replicate this on? sorting by date ASC and DESC is working for me on Firefox and Chrome on 7.9.1.

**Comment by zden2k** [comment]
user1:
Chromium - Verze 58.0.3029.110 Built on Ubuntu , running on Ubuntu 17.04 (64-bit) ..... OK
Chrome - Verze 55.0.2883.87, Ubuntu 17.04 (64-bit) ..... OK
Firefox - 54.0, Ubuntu 17.04 (64-bit) ..... OK

user2:
Chromium - Verze 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit) ..... BUG
Firefox 54.0, Ubuntu 16.04  (64-bit) ..... OK

user3:
Firefox - 54.0, Ubuntu 16.04  (64-bit) ..... BUG

user4:
Firefox - 45.9.0, running on Debian 8.6 (64-bit) ..... BUG
Chromium Version 53.0.2785.143 Built on 8.6, running on Debian 8.6 (64-bit) ..... OK

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this on 7.9.x and 7.8.4 using various browsers. Unless there is a member of the community who can replicate/confirm this I don't think we will be able to make much progress.

**Comment by Dillon-Brown** [comment]
Closed due to inability to replicate / inactivity.
