### ISSUE TITLE
Repair Inbound Email Accounts will remove your smtp login + password in 7.9.1

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3771]
#### Issue

When you Repair Inbound Email Accounts you get this issue

![chyba](https://user-images.githubusercontent.com/5773777/27449068-5a534928-5787-11e7-8875-969cf20b909e.png)

The system reset/remove your smtp login settings in Email Setting area.

This issue is older... 

#### Steps to Reproduce

1. Admin -> Repair --> Repair Inbound Email Accounts
2. Go to Admin --> Email Settings

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version: Chrome 60.x 64bit
* Environment name and version PHP 7.0.16, MySQL 5.6
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this. After repairing inbound email accounts my email settings appear unchanged. Is there any other info you could give that might help in replication?

**Comment by Mausino** [comment]
@Dillon-Brown  i am closing issue, because i can't also replicate the issue.. I will investigate what is the reason and if i find it, i will reopen the issue or create new one.

Thank your for your time :)
