### ISSUE TITLE
Select Subscribed Folder(s) dialogue form size is almost unusable

### ISSUE THREAD

**Issue by domtylerlovett** [salesagility/SuiteCRM#3772]
![select subscribed folder s dialogue form size](https://user-images.githubusercontent.com/22173864/27457453-bb031d42-579c-11e7-8b4c-6b1430dfb5c9.JPG)
#### Issue
The above described screen is sized in such a manner that only 3 rows are visible (of, potentially 100s in a typical email account), and the width of the ListView exceeds the parent form.

#### Expected Behavior
Show at least 20-30 rows at a time and/or make the form user-resizable or auto-resize based on browser internal window height.

#### Actual Behavior
As per Issue, above.

#### Possible Fix
As per Expected Behavior, above.

#### Steps to Reproduce
1. User Profile (via icon at top right)
2. Scroll to end and click Settings under Email Settings
3. Under any Personal Mail Account click the Edit icon (pencil)
4. Click the SELECT button to the right of "Monitored Folders: *"
5. Observe the issue defined above

#### Context
This makes it very awkward (almost unusable) to write instructions for customers' to setup emails when they are monitoring multiple folders from a list of many folders.
I think this should be High priority (as does everyone with their issues) because it makes this part of the system unusable for some.

#### Your Environment

* SuiteCRM Version used: 7.8.x 7.9.x (up to 7.9.1 tested)
* Browser name and version: Chrome (latest version)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Microsoft Windows 10

**Comment by Dillon-Brown** [comment]
@domtylerlovett Can't replicate with 7.8.3 to 7.9.1. 

![issue-3772](https://user-images.githubusercontent.com/26431166/27473805-5240550c-57f8-11e7-9823-9d32df75a75e.png)

Have you tried clearing the cache/repair + rebuild?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
