### ISSUE TITLE
Issues with sending email in 7.9.1

### ISSUE THREAD

**Issue by PhillyD1973** [salesagility/SuiteCRM#3773]
#### Issue

Upgraded from 7.8.4 directly to 7.9.1

Issues sending email when composing from scratch.

#### Expected Behavior
To field should populate when selecting a related account (I believe).

#### Actual Behavior
When composing an email from the "compose" option.

When relating to a contact, it is not populating the contacts email address.

#### Steps to Reproduce

1.  Compose email
2.  Select record to relate to (contact)

#### Your Environment

* SuiteCRM Version used:  7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome (MAC) Version 58.0.3029.110 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.4
* Operating System and version (e.g Ubuntu 16.04):  Unknown (hostgator)

**Comment by PhillyD1973** [comment]
To add more info.  I am seeing the following in the logs when attempting to do this.


`Thu Jun 22 18:17:01 2017 [277540][1][ERROR] fromUser: Conversion of   from user format m/d/Y H:i failed
Thu Jun 22 18:17:01 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:01 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:01 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] fromUser: Conversion of   from user format m/d/Y H:i failed
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] fromUser: Conversion of   from user format m/d/Y H:i failed
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates
Thu Jun 22 18:17:03 2017 [277540][1][ERROR] Unable to find relationship emails_email_templates`

**Comment by yourrfriend** [comment]
Same problem with same errors, after upgrading 7.9.1.

**Comment by pgorod** [comment]
The empty "From" problem is already in #3741. I don't know about the rest, but it could be related.

**Comment by Dillon-Brown** [comment]
@PhillyD1973 Can you separate these into separate issues? I'll raise the "To" field not being populated as a high priority here but if you could create a new issue for the redirection and duplicated body that would be great.

**Comment by PhillyD1973** [comment]
@Dillon-Brown Thanks for the note.  I have separated it into separate issues, my apologies.

The redirection thing.  I created a new issue.  Sorry, did you want me to add it to #3655 ?

Thanks a lot for your help.

**Comment by PhillyD1973** [comment]
Additional to this.

When trying to start an email by clicking on the email address in the contacts screen.  The same issue exists.

![image](https://user-images.githubusercontent.com/29067877/27503932-e1b8d004-584f-11e7-8502-8038d7e898fe.png)


Should this be a new issue?
