### ISSUE TITLE
Cannot delete email in 7.9.1

### ISSUE THREAD

**Issue by pichto** [salesagility/SuiteCRM#3774]
#### Issue

I can't see any option to delete emails.
#### Expected Behavior

The dropdown which shows options to reply, forward, etc. should also have a "delete" option in the email view.
Also, there should be such option in the list view in the bulk action dropdown.
#### Actual Behavior

The option is not present and therefore it's not possible to delete emails.
#### Steps to Reproduce

1. Go to "mail"
2. Select any email
3. click on the "bulk action" dropdown
4. no "delete" option present

#### Context

high priority
#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): opera 45.0.2552.898, chrome 58.0.3029.110 (64-bit), safari 10.1.1 (12603.2.4), firefox 54.0 (64bit)
* Environment name and version : PHP 5.6, MySQL, NGinx
* Operating System and version (e.g Ubuntu 16.04): Raspberry Pi 3, Debian Jessy

**Comment by Dillon-Brown** [comment]
@pichto have you imported the email? once you have imported there should be an option to delete in the detail view action menu.

![issue-3774](https://user-images.githubusercontent.com/26431166/27472635-fb18f6e8-57f3-11e7-924c-1de8a74e0dd2.png)

**Comment by pichto** [comment]
Hello @Dillon-Brown !

Thanks for your input. I tried what your proposed and, yes, the delete option shows up. So, i tried to import the mail (it worked) and then delete it... it worked in a way but not as expected!

The imported email was deleted but the corresponding email on the imap server stayed and was still visible in the listview.

So, my question is : how to delete an email on the imap server (it was real easy on 7.8.x versions) ?

**Comment by Dillon-Brown** [comment]
@pichto Currently there is no delete button for deleting an email from the IMAP server, just for deleting the imported email on the CRM. 

I've raised an issue for adding an IMAP delete button on the email detail view here: https://github.com/salesagility/SuiteCRM/issues/3727

**Comment by pichto** [comment]
@Dillon-Brown, thanks and sorry for the duplicate issue... i searched for an open issue but couldn't find it... will search better next time!

**Comment by jyotiraghav93** [comment]
deleting the imported emails on suitecrm from detailview can also delete the email on imap server using before_delete logic hook as ,

Add the before_delete logic hook in emails module,
File Name : custom/modules/Emails/logic_hooks.php
$hook_array['before_delete'] = Array();
$hook_array['before_delete'][] = Array(30, 'Delete the emails from crm to imap server', 'custom/modules/Emails/delEmailCls.php','delEmailCls', 'delEmailFunc');

Add below code in file custom/modules/Emails/delEmailCls.php,

class delEmailCls{
function delEmailFunc(&$bean,$event,$arguments){
require_once('modules/InboundEmail/InboundEmail.php');
$inbouneEmail = new InboundEmail();
$inbouneEmail->retrieve($bean->mailbox_id);
$uid = $bean->uid;
//Deleting the email on mail server also
$inbouneEmail->deleteMessageOnMailServer($uid);
}
}

It working fine :)
