### ISSUE TITLE
HTML Fields not being displayed

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#3775]
#### Issue

Raised by mjr1 on the forums: https://suitecrm.com/forum/suitecrm-7-0-discussion/14615-html-field-not-being-displayed#49514

#### Expected Behavior

HTML fields should be displayed and allow the user to edit

#### Actual Behavior

HTML fields appear blank

#### Steps to Reproduce

1. Create an HTML field in studio
2. Add the field to something like accounts editview
3. Enter an account -> editview
4. Field appears blank

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by manuagui** [comment]
Hi @Dillon-Brown! HTML fields are not stored in db by default? Or it has relation with this bug?

**Comment by gmiweb** [comment]
Bump...
Has this been resolved? I see it is still open status.

**Comment by mattlorimer** [comment]
Html fields are designed just to show pre defined html, not to be editable. If you need a html field you would use a text area and set it be html, which may not yet been achieved through studio as yet

**Comment by gmiweb** [comment]
Html fields are to show html. The are showing the string value of the html, not the html itself. The literal string is being shown on version 7.9.9

Before there was nothing being shown on Edit and DetailViews. The update now shows the literal string representation of the fields html.

Studio shows the HTML in the edit of the field as the display value of the HTML like you would in a web browser.





 Bryan Allen

**Comment by mattlorimer** [comment]
https://github.com/salesagility/SuiteCRM/issues/4957
