### ISSUE TITLE
Enhancement: Give the possibility to select more than one pdf template when "generate letter" is run

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#3776]
When generating a letter, instead of a pop up that allows to choose only one of the available templates, it would very useful that, next to the list there were checkboxes to allow the selection of one or more templates, so that one could generate more than one template at a time.
This enhancement has been requested in the Forum here: https://suitecrm.com/forum/suitecrm-7-0-discussion/14764-generate-multiple-pdf-templates-for-one-record-at-once

#### Expected Behavior

The pop up with the list of available pdf templates should have checkboxes so that one or more templates could be chosen and then, once the selection is done all the selected templates are used to generate the required documents at once.

#### Actual Behavior

Currently there is a pop up that allows the selection of only one pdf template, so, if more pdf's are required the action has to be repeated several times. and possibly the contact will receive several emails when only one should be sent.
![pdf_templates](https://user-images.githubusercontent.com/8026129/27485654-d65996fc-582d-11e7-9e1c-4b69e766ed4b.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancement: Give the possibility to select more than one pdf template when "generate letter" is run](https://trello.com/c/Lqo5USCp/194-enhancement-give-the-possibility-to-select-more-than-one-pdf-template-when-generate-letter-is-run)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
