### ISSUE TITLE
Compose email pop up window should be closed only by "X icon" in 7.9.1

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3778]
#### Issue

This is suggestion for composing of emails

The main problem for me (also my employees) is that exist only one way how you can close Email compose pop up window that you will click  out of pop up window area and it will close the compose email pop up window

Main problem is, when you are writing email.. you used template, relate to field.. you filled to, cc email addresses, subject + wrote many line in email body (you spent your time and energy ) and NOW YOU CLICK OUT OF POP UP WINDOW !!!

You get heart attak and you want destroy pc :D 👎  because ALL your work is LOST !!!!

#### Expected Behavior

Email pop up window should be closed only by close icon 
or
if you click out of pop up windows area, you must be warn if are  you sure to close compose email pop up window

![email_pop_up](https://user-images.githubusercontent.com/5773777/27499540-9c3042dc-5864-11e7-91c3-a2a2782a393f.png)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compose email pop up window should be closed only by "X icon" in 7.9.1](https://trello.com/c/owREBf2E/195-compose-email-pop-up-window-should-be-closed-only-by-x-icon-in-791)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Dillon-Brown** [comment]
@Mausino As per @pgorod request in #3802 i'm raising this as a bug.

**Comment by benjbt** [comment]
Is there a fix for this yet?
Still a problem in
Version 7.10.1
Sugar Version 6.5.25 (Build 344)

**Comment by pgorod** [comment]
@Dillon-Brown this makes people lose work they've done, so it deserves a Medium priority IMHO. Otherwise we'll just keep postponing it, and it's probably even easy to fix.
