### ISSUE TITLE
Studio - Drop down fields

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#378]
If the user creates a new field and tries to add a new dropdown, if they add and save options the dropdown is not set for the field and the default 'Elastic_boost_options' drop down is selected.

**Comment by grenness** [comment]
what are the default menu items for the Elastic_boost_options drop down - for those who were a bit quick editing this..?

**Comment by vladbar** [comment]
This issue seems to be fixed already (from version 7.5.3)

**Comment by willrennie** [comment]
Confirmed as resolved in the latest release.
