### ISSUE TITLE
Issue with return after sending an email

### ISSUE THREAD

**Issue by PhillyD1973** [salesagility/SuiteCRM#3781]
Upgraded from 7.8.4 directly to 7.9.1

Issues sending email when composing from scratch.

#### Issue
When hitting send.  The return doesn't take me back to the email list.  It returns with a blank page with an error.

#### Expected Behavior
Return to the email listing screen where I started.

#### Actual Behavior
When trying to send the email - it does actually send but then returns with :

{"data":{"type":"Email","id":"8267838a-7155-61cd-a0ba-594c4f8e5f3c","title":"Email sent","attributes":[],"relationships":[]}}

#### Steps to Reproduce

1. Compose email
2. Enter from address
3. Enter to address
4. Add text to body
5. Send email

#### Your Environment
*SuiteCRM Version used: 7.9.1
*Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (MAC) Version 58.0.3029.110 (64-bit)
*Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.4
*Operating System and version (e.g Ubuntu 16.04): Unknown (hostgator)

**Comment by pgorod** [comment]
[This thread](https://suitecrm.com/forum/developer-help/14937-suitecrm-email-subpanel-not-working#50100) has a similar issue, and some extra information. 

That user is using version 7.9.2. Is this PR here merged into 7.9.2 already? I suppose not.

**Comment by Dillon-Brown** [comment]
@pgorod Fix #3655 has been merged into 7.9.2.

**Comment by pgorod** [comment]
@Dillon-Brown thanks, but then it is strange in that thread I linked, someone with 7.9.2 is getting the same issue...
