### ISSUE TITLE
After upgrade email settings button is missing

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#3786]
After upgrading to 7.9.1 the settings button is missing on user preferences 

#### Issue
On the demo the user preference has the settings button in the profile
![image](https://user-images.githubusercontent.com/2706403/27523791-d2718c74-5a59-11e7-8205-c104d166c95f.png)
It is missing after our install
![image](https://user-images.githubusercontent.com/2706403/27528726-e823c98e-5a7b-11e7-99b4-4810dd429059.png)

#### Expected Behavior
the setting button be present after the install
#### Actual Behavior
the button is missing 

#### Steps to Reproduce

1.Go to profile settings
2. Email setting are not there

#### Context
Can not use the system after the upgrade.

#### Your Environment
Version 7.9.1
Sugar Version 6.5.24 (Build 509)
Sugar Version 6.5.24 (Build 509)
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Safari/602.1 but also test with Chrome/opera/ firefox (all the latest versions)
Environment name and version (e.g. MySQL, PHP 7):
MySQL PHP6.5
Operating System and version (e.g Ubuntu 16.04):
GNU/Linux

**Comment by Dillon-Brown** [comment]
@wanesmith What version did you upgrade to 7.9.1? and have you tried clearing the cache / repair + rebuild?

**Comment by wanesmith** [comment]
Yes I tried running every cache/repair after.

**Comment by Mausino** [comment]
@Dillon-Brown  could have this ticket something simillary by this issue #3771 

Why is the smtp name + password fullfiled by user name + pass ??? 

I expected that will shows empy fieds. Could it have something will browser autofill function in process in upgrade process ???

**Comment by Dillon-Brown** [comment]
@Mausino It does seem that the browser autofill replaces these fields with the saved login user/pass on the first visit when they are empty. However I can't replicate it replacing them when they are already filled and using repair inbound email.

**Comment by Dillon-Brown** [comment]
@walesz92 Can you tell me which version you upgraded to 7.9.1 with? It would also help to know if you have made customisation's or layout changes to user profile.

**Comment by wanesmith** [comment]
I upgraded from Version 7.8.3
Sugar Version 6.5.24 (Build 509)

**Comment by Dillon-Brown** [comment]
Can't seem to replicate upgrading from 7.8.3. It looks like the style is incorrect in your screenshots which would imply that this was a caching issue. Unless a member of the community can replicate/confirm this I don't think we will be able to make any more progress.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity / inability to replicate as a core issue. Please re-open if you learn more information.
