### ISSUE TITLE
Scheduling Bug - Log Call

### ISSUE THREAD

**Issue by selimerunkut** [salesagility/SuiteCRM#379]
When logging a new call, other calls that are older than 50+ days are not displayed in the "Scheduling" section.

For example current date time is 20.08.2015
calls with start date 09.10.2015 are displayed but calls with start date 10.10.2015 (and older) are not displayed as scheduled.

**Comment by paulgodley** [comment]
Hi @selimerunkut, I apologies about the delay with this issue being looked into.  I  have just been assigned this call and I will let you know when it is resolved.

**Comment by paulgodley** [comment]
Hi @selimerunkut, there is a setting in config.php called 'vcal_time'.  This is set to 2 by default and this is how many months in the future to pull calendar information up until.  So, if you change this to 12, this will show how all meetings scheduled within the next year.

Please note that as you increase this value, the response time may increase (as larger data sets are being transferred).  Hope this helps!

**Comment by JimMackin** [comment]
Closing pending input. Please comment or create a new issue if this is still an issue.
