### ISSUE TITLE
7.9.1 Disregard draft sends emails

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#3790]
#### Issue

After composing a draft email in the email module and clicking, disregard draft. The email is sent.

#### Expected Behaviour

The draft should be discarded and no email should be sent.

#### Actual Behaviour

Draft is kept and an email is sent instead.

#### Steps to Reproduce

1. Enter email module
2. Compose a new email and save as a draft
3. Enter drafts folder
4. Edit draft -> disregard draft

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by halest** [comment]
To me happens on chrome also

**Comment by pgorod** [comment]
This. Is. Really. Bad.

People can get into serious problems by sending emails unintentionally, or before proper consideration. Or at the precise moment when they decided, "no, I can't send this"...

**Comment by daniel-samson** [comment]
Hi everyone, I have made a pull request for this. Can you please test that this corrects the issue?

**Comment by pgorod** [comment]
I'm afraid I can't test because I can't send emails from 7.9.1... I'm still having difficulties with populating the "From" box. After adding inbound account, it populates with a single account, but it's not working to send email. I can't get another account to appear in that "From" box.

What _should_ appear there? Every public outbound account in the system, my personal outbound accounts, what? Thanks.

**Comment by halest** [comment]
Hey, I had to comment out a couple of functions regarding group email and private email accounts to get the from field to populate again. I'll test it as soon as I can.

**Comment by pgorod** [comment]
Ok that Issue is another one: #3741 
But if somebody adds information there that let's me test email sending, I'd be glad to test the fix in the current Issue. Thanks.

**Comment by halest** [comment]
@pgorod Hey, here's what I changed quick and dirty to populate the from field again:
In EmailsController.php I hardcoded the following:
`$isGroupEmailAccount = false;//$inboundEmail->isGroupEmailAccount();
 $isPersonalEmailAccount = true;//$inboundEmail->isPersonalEmailAccount();`

And in EmailUI.php I had to comment out line 230
`//$this->smarty->assign('signaturesAccountSettings'......`

**Comment by samus-aran** [comment]
This should be resolved in latest Release (7.9.2)

**Comment by isleshocky77** [comment]
@samus-aran This is happening for me while running on 7.9.7 and 7.9.8 from installed directly from source. Has this been reintroduced? Or do I need to do a specific "Repair operation". 

I attempted:
* Quick Repair and Rebuild
* Rebuild Minified JS Files
* Rebuild JS Compressed Files
