### ISSUE TITLE
7.9.1 Problems with Umlauts in E-Mail-Client

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3791]
#### Issue

Display names with umlauts are broken in the latest sCRM email-client:

The Array "$this->to_addrs_arr" contains:
` [0] => Array
        (
            [email] => xyz@abc.de
            [display] => nig
        )`

Where it should be "König". Strings are broken off after the Umlaut.

#### Expected Behavior

Umlaut display-names should be displayed

#### Actual Behavior

'nig' is shown where it should be "König". Strings are broken off after the Umlaut.

#### Possible Fix

Possible encoding issue. The E-Mail-Client settings are UTF8.

#### Steps to Reproduce

1. Receive Mail with umlaut-containing display name
2. Is is not shown correctly

#### Context

Medium Priority at least for German users

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP7
* Operating System and version (e.g Ubuntu 16.04): Windows Server 2008R2

**Comment by Mausino** [comment]
Hi @halest , are you talking abou this #3626 or ?

**Comment by halest** [comment]
That is also an issue I'm seeing but this one is specifically the whole string being cut off after the special characters. I'm not sure when it does this and when it does the strange encoding from #3262
