### ISSUE TITLE
Emails When deleted leaving table entrys 7.9.1

### ISSUE THREAD

**Issue by petedyer** [salesagility/SuiteCRM#3792]
#### Issue
When an imported email is marked as delete and then the scheduler prune is run the email in emails table is deleted BUT other tables such as folders_rel, emails_text, emails_email_addr_rel - the data is still there

#### Expected Behavior
When someone deletes an email then surely the corresponding data in the tables mentioned above should be deleted?
When looking at the db I can see the deleted flag is never is set to 1 only 0

#### Steps to Reproduce

1. Go into imported email
2. set it to be deleted
3. Look in db emails you will see the delete flag set to 1 this is correct
4. Look at corresponding tables folders_rel, emails_text, emails_email_addr_rel(may be more) - the related message body etc are all still set to delete flag 0
5. Run scheduler prune and you will see the email from emails table deleted but other entries in the table are left

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):mysql, php 7.1
* Operating System and version (e.g Ubuntu 16.04):Centos 7

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Emails When deleted leaving table entrys 7.9.1](https://trello.com/c/ayYVchXx/196-emails-when-deleted-leaving-table-entrys-791)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
