### ISSUE TITLE
7.9.1 No Way To delete Emails From List View

### ISSUE THREAD

**Issue by petedyer** [salesagility/SuiteCRM#3794]
#### Issue
Need to delete multiple emails from the list mode in the new emails module.

#### Expected Behavior
A button should be available to delete multi selected record like other modules

#### Actual Behavior
No button is present so only way to delete is to go into each actual imported record and delete(detailview).

#### Possible Fix
Button is required to delete multi selected records from list mode. Also why do we need to import to delete ?

#### Steps to Reproduce

1. Goto list mode
2. Multi select records
3. You will notice no delete button or action available

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [7.9.1 No Way To delete Emails From List View](https://trello.com/c/4G5Q1W2v/197-791-no-way-to-delete-emails-from-list-view)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
