### ISSUE TITLE
Issue on saving plain html code in email templates

### ISSUE THREAD

**Issue by squestel** [salesagility/SuiteCRM#3797]
#### Issue
I try to generate an email template from html/css code, on saving everything disappear

#### Expected Behavior
Of course I expect the html page to be saved properly and keeping the css like it's meant to be

#### Actual Behavior
I get a white page, like the default model

#### Possible Fix
I suggest that the html check doesn't reject a plain html code (<!DOCTYPE HTML>......)

#### Context
It's a high priority because we take our tme to make a complete html template for our emails, and suitecrm rejects it ! 

#### Your Environment
* SuiteCRM Version used: We use SuiteCRM 7.8.5 but it does that in previous versions too
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): I use Firefox but it does that on every browsers
* Environment name and version (e.g. MySQL, PHP 7): we use PHP 5.6 and MySQL
* Operating System and version (e.g Ubuntu 16.04): Windows 7,10 and Debian

**Would you please tell me where to modify the check system on click on the save button so it can accept my html content**

**Comment by Dillon-Brown** [comment]
@squestel I am unable to replicate this. Is there a specific example of html code that you could give?

**Comment by squestel** [comment]
I'm trying to attach a zip file containing the html code but it doesnt work, so I will paste the entire code here : 


`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <title>C'AIR'M d'EXELCIA</title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <!-- Web Font / @font-face : BEGIN -->
    <!-- NOTE: If web fonts are not required, lines 10 - 27 can be safely removed. -->

    <!-- Desktop Outlook chokes on web font references and defaults to Times New Roman, so we force a safe fallback font. -->
    <!--[if mso]>
        <style>
            * {
                font-family: sans-serif !important;
            }
        </style>
    <![endif]-->

    <!-- All other clients get the webfont reference; some will render the font and others will silently fail to the fallbacks. More on that here: http://stylecampaign.com/blog/2015/02/webfont-support-in-email/ -->
    <!--[if !mso]><!-->
        <!-- insert web font reference, eg: <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'> -->
    <!--<![endif]-->

    <!-- Web Font / @font-face : END -->

    <!-- CSS Reset -->
    <style type="text/css">

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        /* What it does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }

        /* What it does: Stops Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        /* What it does: Fixes webkit padding issue. Fix for Yahoo mail table alignment bug. Applies table-layout to the first 2 tables then removes for anything nested deeper. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }
        table table table {
            table-layout: auto;
        }

        /* What it does: Uses a better rendering method when resizing images in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }

        /* What it does: A work-around for iOS meddling in triggered links. */
        *[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
        }

        /* What it does: A work-around for Gmail meddling in triggered links. */
        .x-gmail-data-detectors,
        .x-gmail-data-detectors *,
        .aBn {
            border-bottom: 0 !important;
            cursor: default !important;
        }

        /* What it does: Prevents Gmail from displaying an download button on large, non-linked images. */
        .a6S {
            display: none !important;
            opacity: 0.01 !important;
        }
        /* If the above doesn't work, add a .g-img class to any image in question. */
        img.g-img + div {
            display:none !important;
           }

        /* What it does: Prevents underlining the button text in Windows 10 */
        .button-link {
            text-decoration: none !important;
        }

        /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
        /* Create one of these media queries for each additional viewport size you'd like to fix */
        /* Thanks to Eric Lepetit @ericlepetitsf) for help troubleshooting */
        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) { /* iPhone 6 and 6+ */
            .email-container {
                min-width: 375px !important;
            }
        }

    </style>

    <!-- Progressive Enhancements -->
    <style type="text/css">

        /* What it does: Hover styles for buttons */
        .button-td,
        .button-a {
            transition: all 100ms ease-in;
        }
        .button-td:hover,
        .button-a:hover {
            background: #0e93bb !important;
            border-color: #0e93bb !important;
        }

        /* Media Queries */
        @media screen and (max-width: 480px) {

            /* What it does: Forces elements to resize to the full width of their container. Useful for resizing images beyond their max-width. */
            .fluid {
                width: 100% !important;
                max-width: 100% !important;
                height: auto !important;
                margin-left: auto !important;
                margin-right: auto !important;
            }

            /* What it does: Forces table cells into full-width rows. */
            .stack-column,
            .stack-column-center {
                display: block !important;
                width: 100% !important;
                max-width: 100% !important;
                direction: ltr !important;
            }
            /* And center justify these ones. */
            .stack-column-center {
                text-align: center !important;
            }

            /* What it does: Generic utility class for centering. Useful for images, buttons, and nested tables. */
            .center-on-narrow {
                text-align: center !important;
                display: block !important;
                margin-left: auto !important;
                margin-right: auto !important;
                float: none !important;
            }
            table.center-on-narrow {
                display: inline-block !important;
            }

            /* What it does: Adjust typography on small screens to improve readability */
			.email-container p {
				font-size: 17px !important;
				line-height: 22px !important;
			}
        }

    </style>

    <!-- What it does: Makes background images in 72ppi Outlook render at correct size. --> 
    <!--[if gte mso 9]>
    <xml>
      <o:OfficeDocumentSettings>
        <o:AllowPNG/>
        <o:PixelsPerInch>96</o:PixelsPerInch>
     </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
    
</head>
<body width="100%" bgcolor="#0e93bb" style="margin: 0; mso-line-height-rule: exactly;">
    <center style="width: 100%; background: #0e93bb; text-align: left;">

        <!-- Visually Hidden Preheader Text : BEGIN -->
        <div style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;">
            Découvrez vite le C'AIR'M d'Exelcia
        </div>
        <!-- Visually Hidden Preheader Text : END -->

        <!--
            Set the email width. Defined in two places:
            1. max-width for all clients except Desktop Windows Outlook, allowing the email to squish on narrow but never go wider than 680px.
            2. MSO tags for Desktop Windows Outlook enforce a 680px width.
            Note: The Fluid and Responsive templates have a different width (600px). The hybrid grid is more "fragile", and I've found that 680px is a good width. Change with caution.
        -->
        
		
		<div style="max-width: 680px; margin: auto;" class="email-container">
            <!--[if mso]>
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="680" align="center">
            <tr>
            <td>
            <![endif]-->

            <!-- Email Header : BEGIN -->
            
			
			
			<table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">
                <tr>
                    <td style="padding: 10px 0; text-align: center">
                        
                    </td>
                </tr>
            </table>
            <!-- Email Header : END -->

            <!-- Email Body : BEGIN -->

            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;" class="email-container">

                <!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
					

					
					
					<div style="text-align: center;"><span style="font-family:open sans; font-size:10px; text-align:center"><a href="https://www.google.com" target="_blank">Afficher cet email dans votre navigateur</a></span></div>
                        <img src="http://i.imgur.com/gaNnjLH.png" aria-hidden="true" width="680" height="" alt="alt_text" border="0" align="center" class="g-img" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                        <img src="http://i.imgur.com/D6wlx75.png" aria-hidden="true" width="680" height="" alt="alt_text" border="0" align="center" class="g-img" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" >
                            <tr>
                                <td style="padding: 20px 20px 20px; text-align: center;">
                                    <h1 style="margin: 0; font-family: sans-serif; font-size: 200%; line-height: 27px; color: #005898; font-weight: bold;">Transformez vos passagers en clients !</h1>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 18px; line-height: 30px; color: #555555; text-align: center;">
                                    <p style="margin: 0;"><span style="color:#005898; font-weight: bold;"> C’AIR’M </span> est une solution CRM conçue spécialement pour les compagnies aériennes, afin d'améliorer l'expérience du passager et de le changer en client satisfait et régulier.



									<br><br>Basée sur les standards <span style="font-weight: bold;"> SugarCRM</span> et <span style="font-weight: bold;">SuiteCRM</span>, le <span style="color:#005898; font-weight: bold;"> C’AIR’M </span> permet d’avoir une vue à 360° du marché et 
									d’enrichir la connaissance client au fil de ses interactions avec la compagnie (via tous 
									les canaux de communications). <br><br>Le <span style="color:#005898; font-weight: bold;"> C’AIR’M </span> fournit automatiquement les dernières données sur vos clients, cette vision toujours " à jour " vous permettra 
									de personaliser vos offres et d'améliorer votre fidélisation client.</p>
                                </td>
                            </tr>
                          
						  <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto;">
                                        <tr>
                                            <td style="border-radius: 3px; background: #222222; text-align: center;" class="button-td">
                                                <a href="http://www.google.com" style="background: #005898; border: 15px solid #005898; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
												
                                                   

												   <span style="color:#ffffff;font-size:180%; font-weight: bold;" class="button-link"> &nbsp;&nbsp;&nbsp;&nbsp; Demander une démonstration gratuite &nbsp;&nbsp;&nbsp;&nbsp;</span>
                                                </a>
												
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>

                        </table>
                    </td>
                </tr>
                <!-- 1 Column Text + Button : END -->






				
				  <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                            
                            <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto;">
                                        <tr>
                                          
											
											
									<td style="border-radius: 3px; text-align: center;" ">
                                                <p style = " border: 2px solid #0E93BB; font-family: sans-serif; font-size: 13px; line-height: 1.5; 
												text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" >
                                                    <span style="color:#005898;font-size:180%; font-weight: bold;" > &nbsp;&nbsp;&nbsp;&nbsp;Fonctionnalités&nbsp;&nbsp;&nbsp;&nbsp;</span> </p>
                                                </a>
                                            </td>
											
											  
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>

                        </table>
                    
                </tr> 
				</td>
				</tr>
                <!-- 1 Column Text + Button : END -->
				
				
				
				
				
				
				
                <!-- 3 Even Columns : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff" align="center" height="100%" valign="top" width="100%" style="padding: 10px 0;">
                        <!--[if mso]>
                        <table role="presentation" aria-hidden="true" border="0" cellspacing="0" cellpadding="0" align="center" width="660">
                        <tr>
                        <td align="center" valign="top" width="660">
                        <![endif]-->
                        <table role="presentation" aria-hidden="true" border="0" cellpadding="0" cellspacing="0" align="center" width="100%" style="max-width:660px;">
                            <tr>
                                <td align="center" valign="top" style="font-size:0;">
                                    <!--[if mso]>
                                    <table role="presentation" aria-hidden="true" border="0" cellspacing="0" cellpadding="0" align="center" width="660">
                                    <tr>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                <img src="http://i.imgur.com/nYpf6k2.png" aria-hidden="true" width="200" height="" border="0" alt="Marketing " class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                               <h3 align="center">Marketing</br></br> </h3><p align="center" style="margin: 0;">Planifiez différentes actions marketing, suivez et d’analysez les résultats. 
</p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                 <img src="http://i.imgur.com/wXYbOI7.png" aria-hidden="true" width="200" height="" border="0" alt="Demandes et réclamations" class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                                <h3 align="center">Demandes et réclamations</h3><p align="center" style="margin: 0;">Améliorez la satisfaction de vos clients en industrialisant le traitement des demandes et des réclamations.</p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                <img src="http://i.imgur.com/jXHqqow.png" aria-hidden="true" width="200" height="" border="0" alt="Sales Forces Automation" class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                              <h3 align="center">Sales Forces Automation</h3>  <p align="center" style="margin: 0;">Optimisez les resulats de vos équipes en automatisant le cycle de vente .</p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    </tr>
                                    </table>
                                    <![endif]-->
                                </td>
                            </tr>
                        </table>
                        <!--[if mso]>
                        </td>
                        </tr>
                        </table>
                        <![endif]-->
                    </td>
                </tr>
                <!-- 3 Even Columns : END -->

                 <!-- 3 Even Columns : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff" align="center" height="100%" valign="top" width="100%" style="padding: 10px 0;">
                        <!--[if mso]>
                        <table role="presentation" aria-hidden="true" border="0" cellspacing="0" cellpadding="0" align="center" width="660">
                        <tr>
                        <td align="center" valign="top" width="660">
                        <![endif]-->
                        <table role="presentation" aria-hidden="true" border="0" cellpadding="0" cellspacing="0" align="center" width="100%" style="max-width:660px;">
                            <tr>
                                <td align="center" valign="top" style="font-size:0;">
                                    <!--[if mso]>
                                    <table role="presentation" aria-hidden="true" border="0" cellspacing="0" cellpadding="0" align="center" width="660">
                                    <tr>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                <img src="http://i.imgur.com/fI7nalU.png" aria-hidden="true" width="200" height="" border="0" alt="Interactions Clients" class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                                <h3 align="center">Interactions Clients</h3><p align="center" style="margin: 0;">Renforcez votre connaissance client grâce à une vue historisée des données transactionnelles et de vos interactions.</p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                <img src="http://i.imgur.com/bT8B5Zz.png" aria-hidden="true" width="200" height="" border="0" alt="Reporting" class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                              <h3 align="center">Reporting</h3>  <p align="center" style="margin: 0;">Paramétrez et éditez des rapports automatisés sur vos principaux KPI.</p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    <td align="left" valign="top" width="220">
                                    <![endif]-->
                                    <div style="display:inline-block; margin: 0 -2px; max-width:33.33%; min-width:220px; vertical-align:top; width:100%;" class="stack-column">
                                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                                            <tr>
                                                <td style="padding: 10px 10px;">
                                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%" style="font-size: 14px;text-align: left;">
                                                        <tr>
                                                            <td>
                                                                <img src="http://i.imgur.com/q4TtWzn.png" aria-hidden="true" width="200" height="" border="0" alt="Cross Canal" class="center-on-narrow" style="width: 100%; max-width: 200px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; padding-top: 10px;" class="stack-column-center">
                                                            <h3 align="center">Cross Canal</h3>    <p align="center" style="margin: 0;">Suivez vos clients sur tous les canaux : site web, appli mobile, call center, PNC, ATO/CTO... </p>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--[if mso]>
                                    </td>
                                    </tr>
                                    </table>
                                    <![endif]-->
                                </td>
                            </tr>
                        </table>
                        <!--[if mso]>
                        </td>
                        </tr>
                        </table>
                        <![endif]-->
                    </td>
                </tr>
                <!-- 3 Even Columns : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                            
                 <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto;">
                                        <tr>
                                            
													
									<td style="border-radius: 3px; text-align: center;" ">
                                                <p style = " border: 2px solid #0E93BB; font-family: sans-serif; font-size: 13px; line-height: 1.5; 
												text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" >
                                                    <span style="color:#005898;font-size:180%; font-weight: bold;" > &nbsp;&nbsp;&nbsp;&nbsp;Notre solution intègre les standards&nbsp;&nbsp;&nbsp;&nbsp;</span> </p>
                                                </a>
                                            </td>
											
											
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>

                        </table>
                    </td>
                </tr>
                <!-- 1 Column Text + Button : END -->

				<!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                      
                        <img src="http://i.imgur.com/uU9Z19v.png" aria-hidden="true" width="680" height="" alt="suite crm sugarcrm" border="0" align="center" class="g-img" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->
              
			  
			   <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" width="100%">
                            
                            <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; text-align: center;">
                                    
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto;">
                                        <tr>
                                            <td style="border-radius: 3px; background: #222222; text-align: center;" class="button-td">
                                                <a href="http://www.google.com" style="background: #005898; border: 15px solid #005898; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
                                                    <span style="color:#ffffff;font-size:180%; font-weight: bold;" class="button-link">&nbsp;&nbsp;&nbsp;&nbsp;Demander une démonstration gratuite&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>
							
							 <tr>
                                <td style="padding: 0 20px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <!-- Button : BEGIN -->
                                    <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto;">
                                        <tr>
                                            
													
									<td style="border-radius: 3px; text-align: center;" ">
                                                <p style = " border: 2px solid #0E93BB; font-family: sans-serif; font-size: 13px; line-height: 1.5; 
												text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" >
                                                    <span style="color:#005898;font-size:180%; font-weight: bold;" > &nbsp;&nbsp;&nbsp;&nbsp;Ils nous font confiance&nbsp;&nbsp;&nbsp;&nbsp;</span> </p>
                                                </a>
                                            </td>
											
											
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>

                        </table>
                    </td>
                </tr>

                        </table>
                    </td>
                </tr>
                <!-- 1 Column Text + Button : END -->

				<!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                      
                        <img src="http://i.imgur.com/Qihzgp2.png" aria-hidden="true" width="680" height="" alt="autres clients" border="0" align="center" class="g-img" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->
              
			  

			  
			  
			 
                
                
              

                

            </table>
            <!-- Email Body : END -->

            

            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div>

		

    </center>
            
			
			            <center>
                <br>
               
 
                
                <style type="text/css">
                    @media only screen and (max-width: 480px){
                        table#canspamBar td{font-size:14px !important;}
                        table#canspamBar td a{display:block !important; margin-top:10px !important;}
                    }
                </style>
            </center></body>
</html>`

**Comment by Dillon-Brown** [comment]
@squestel It seems to be saving correctly with that code, apart from some formatting issues that are due to  the issue here: https://github.com/salesagility/SuiteCRM/issues/3672

**Comment by squestel** [comment]
Here's what we get, on multiple instances : 
![expected_on_save](https://user-images.githubusercontent.com/29713538/27589505-af6e4be8-5b19-11e7-942d-46ec1ff1baf5.PNG)
![result_on_save](https://user-images.githubusercontent.com/29713538/27589506-af72dece-5b19-11e7-85a4-44cae3c85daa.PNG)

**Comment by squestel** [comment]
With that being said, would you please tell me which part of the php code I have to modify in order to bypass the html purifier.

Thanks

**Comment by janbarendse** [comment]
I also noticed that the htmlcode gets truncated to a certain amount of bytes, made my responsive html mail to fail.

**Comment by Dillon-Brown** [comment]
@janbarendse That sounds like a bug. Can you raise a new issue for it?

**Comment by Dillon-Brown** [comment]
@squestel From what I can see from your screenshots the issue is actually due to using the Mozaik editor, the html purifier won't be causing the template to appear blank. This is most likely due to making a change in Mozaik that caused the html code to be outside the mozaik "block". For existing templates you would want to use the Direct HTML editor that you can find under email settings in user profile.

**Comment by squestel** [comment]
Hi,

I'm not sure I understand what youre telling me to do, I actually tried to go to email parameters in the admin section, and uncheck all the tags, save and repair ( just in case) and I still get a blank page : 
![issue](https://user-images.githubusercontent.com/29713538/27647142-9ea1ac44-5bf8-11e7-8b0f-079ce730aa20.PNG)

**Comment by Dillon-Brown** [comment]
@squestel Hi, the option to change editors can be found under user profile here:

![github_editor](https://user-images.githubusercontent.com/26431166/27676458-e208ad86-5ca5-11e7-9a90-a15a64dd5077.png)

If you already have an HTML template you will want to use the "Direct HTML" option as using "Mozaik" will break the html.

**Comment by squestel** [comment]
Here's what I get on 7.8.5 version : 
![issue](https://user-images.githubusercontent.com/29713538/27689094-05c30bfe-5cab-11e7-9f26-3744dd06d68a.PNG)

**Comment by Dillon-Brown** [comment]
@squestel My apologies, I mistakenly thought you were on 7.9. I've created a fix here: #3817 that should have resolved email templates returning blank. However, it seems that the template code you provided is still causing issues, this may indeed be a seperate bug. I'll play around with it a bit and see if I can find out what exactly is going on.

**Comment by squestel** [comment]
Thanks for caring, unfortunately after doing your changes, and repairing, on two different instances, I still get a blank page ( at the repair i've been proposed to execute sql queries ).

**Comment by tlosio** [comment]
Hi,

I also  have the exact same problem, in our corporate we need to use our custom Html template for campaigns but that's not possible currently because the module mess up our template structure on saving. 
That's urgent we can't afford to lose our time doing back our template for productivity sake.

Would you please help me out.

Thanks in advance.

**Comment by Dillon-Brown** [comment]
@tlosio What version of SuiteCRM are you on? are you getting the same issue regarding a blank page or just template formatting?

**Comment by tlosio** [comment]
Thanks for answering, I actually recently upgraded to 7.8.5 but I used to get the same issue on 7.8.3.

On saving a complete html or ours, it gives me a blank page, and when taking off the "<!DOCTYPE> etc..." ( maybe <html> too ? ), we have a really strange display on saving because I saw that SuiteCRM adds new html tags ( ex : <tbody> ) so he plays around with my html code and that really sucks.

As I see, we seem to be a lot who complains about this thing on regarding SuiteCRM... Hope it will get fixed pretty soon....

**Comment by dl3737** [comment]
we have now vesion 7.9.12 and still have the same problem. I think it will not be solved!
although email template is very important in CRM programe.
