### ISSUE TITLE
7.9.1 - Attachments aren't in FORWARDED email, if exist in original email 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3798]
#### Issue

When you open email, same for imported emails.. and you'll send it, the attachment from original email weren't added and send email without them.

In compose view you see that weren't added 

#### Expected Behavior

Will resend original email with all attachments

#### Actual Behavior

Isn't working as expected

#### Steps to Reproduce

1. Open / Import email with attachments
2. Go to detalview of email
3. Forward this email 

#### Your Environment

* SuiteCRM Version used: SuiteCRM  7.9.1
* Browser name and version (e.g. Chrome 56.x 64bit
* Environment name and version: MySQL 5.6, PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by Mausino** [comment]
@Dillon-Brown @daniel-samson we applied this patch and isn't working for us... alos is probme if is email imported and also can't add attachment. :(

**Comment by Mausino** [comment]
@Dillon-Brown i wrote that it is not working... You are able to forward email, but without success that was added original attachment.. maybe some other users have other opinion...

**Comment by Dillon-Brown** [comment]
@Mausino Is there a particular email provider you are using to test this? it seems to be working on my end.
