### ISSUE TITLE
Double save required for Studio Layouts

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#380]
When saving a studio layout it seems to revert back to how it was before you changed it, so you have to change then Save&Deploy twice. Upon the first save&Deploy, it does update the Layout but simply shows you the previous one.

**Comment by darthtang** [comment]
I am unable to reproduce bug here. @willrennie have you been able to reproduce this bug?

**Comment by willrennie** [comment]
Yes, all studio issues are verified hence flagged with High Priority and Bug labels.
