### ISSUE TITLE
Add name of inboud email account name to email list view in  7.9.x

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3800]
#### Issue

Me, my employees and others are confused in which email accounts are ..... 
Adding the name of inboud email account will better for users to be not confused :)

![text](https://user-images.githubusercontent.com/5773777/27563265-ec0f79d0-5ad0-11e7-9fb9-a32591b3fa32.png)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add name of inbound email account name to email list view in 7.9.x](https://trello.com/c/UBLBTxcM/198-add-name-of-inbound-email-account-name-to-email-list-view-in-79x)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@Dillon-Brown created pull request #6734 which solved this suggestion. @samus-aran Should be this ticket open and add the milestone 7.10.12 ???
