### ISSUE TITLE
MySQL error on install due to column named 'manifest'

### ISSUE THREAD

**Issue by jrquint** [salesagility/SuiteCRM#3805]
#### Issue
Installer failed with error:  

Tue Jun 27 20:18:07 2017 [25744][-none-][FATAL] Error creating table: upgrade_history: Query Failed: CREATE TABLE upgrade_history (id char(36)  NOT NULL ,filename varchar(255)  NULL ,md5sum varchar(32)  NULL ,type varchar(30)  NULL ,status varchar(50)  NULL ,version varchar(64)  NULL ,name varchar(255)  NULL ,description text  NULL ,id_name varchar(255)  NULL ,manifest longtext  NULL ,date_entered datetime  NULL ,enabled bool  DEFAULT '1' NULL  , PRIMARY KEY (id),   UNIQUE upgrade_history_md5_uk (md5sum)) CHARACTER SET utf8 COLLATE utf8_general_ci: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'manifest longtext  NULL ,date_entered datetime  NULL ,enabled bool  DEFAULT '1' ' at line 1

#### Expected Behavior
Installer should create all tables and complete install process.

#### Actual Behavior
Installer fails with MySQL error seen above.  

#### Possible Fix

Use back-tics in MySQL column names in DB queries as is best practice:

CREATE TABLE upgrade_history (
  `id` char(36)  NOT NULL ,
`filename` varchar(255)  NULL ,
`md5sum` varchar(32)  NULL ,
`type` varchar(30)  NULL ,
`status` varchar(50)  NULL ,
`version` varchar(64)  NULL ,
`name` varchar(255)  NULL ,
`description` text  NULL ,
`id_name` varchar(255)  NULL ,
`manifest` longtext  NULL ,
`date_entered` datetime  NULL ,
`enabled` bool  DEFAULT '1' NULL  , PRIMARY KEY (id),   
UNIQUE upgrade_history_md5_uk (md5sum)) CHARACTER SET utf8 COLLATE utf8_general_ci

Or use a different column name than 'manifest' which is a reserved word in certain versions of MySQL 

#### Steps to Reproduce

1. Run SuiteCRM install.php using AWS Aurora (MySQL) as backend database server

#### Context

Cannot install software in our AWS environment. 

#### Your Environment
* SuiteCRM Version used: 7.9.1,  7.8.5 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7):  MySQL (AWS Aurora 5.6) PHP 7.0 
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04

**Comment by chris001** [comment]
Excellent bug find thank you.
This is another bug which can be solved by upgrading `DBManager` to use PDO.
#3325 
#3689 
@opravil-jan

**Comment by Dillon-Brown** [comment]
@jrquint This looks like an issue with AWS and not a specific issue with Suite. Further information here: https://forums.aws.amazon.com/thread.jspa?messageID=777400 I wouldn't consider this a core SuiteCRM bug as this should be fixed on their side to follow standards. If you disagree please re-open the issue. Thanks.
