### ISSUE TITLE
Report: Operator missing in conditions using  Multiselect field

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#3808]
#### Issue

When using a Multiselct field in the conditions there are only "equal to" and "not equal to" available.
but in case of an Multiselct field there must be also an option "Contains", because it is multiselect so the value could have more than one value: ie:  ^1^,^2^ 
#### Expected Behavior

Field should be searched for all possible combinations of selcted values.
#### Actual Behavior

only the objects are displayed where exactly one option is selected.

1. create multienum field in module with more values
2. create report - go to conditions and select the field you created before.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8x, 7.9

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Report: Operator missing in conditions using Multiselect field](https://trello.com/c/XlnPnt1n/199-report-operator-missing-in-conditions-using-multiselect-field)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Lehnerr** [comment]
Hi.
I found a simple solution for this problem.


in modules/AOR_Reports/controller.php

I changed :
           case 'multienum':
                $valid_opp = array('Equal_To', 'Not_Equal_To');
                break;

to            case 'multienum':
                $valid_opp = array('Contains');
                break;


            case 'multienum':
                $valid_opp = array('Value', 'Field', 'Multi');
to
            case 'multienum':
                $valid_opp = array('Value');

And it works as expected.
Can you change this in code or how can i do this in an upgrade save way?

**Comment by Lehnerr** [comment]
Pls consider it as an issue not as an suggestion.
