### ISSUE TITLE
Direct html content gets truncated - incomplete html

### ISSUE THREAD

**Issue by janbarendse** [salesagility/SuiteCRM#3811]
#### Issue
When entering plain html in email templates and saving it is loosing the last ~50 lines of html

#### Expected Behavior
Expect to paste a html mail, and have it render properly, without last bit being cut off.

#### Actual Behavior
Results in a html mail without a footer

#### Possible Fix
My workaround is now to minify, then it just fits into the field.

**Comment by ebogaard** [comment]
We solved this by changing email_templates.body and email_templates.body_html database columns from 'text' to 'mediumtext'.
That database field type has much more storage capacity for text (html).

@salesagility: I think it's a good idea to use a larger field type by default and I think this doesn't break things.

**Comment by janbarendse** [comment]
Great suggestion!

**Comment by chris001** [comment]
To do this manually you should be able to change the vardef then do a QRR (quick repair rebuild).
