### ISSUE TITLE
Duplicate attachements are sent

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#3818]
#### Issue

Sending an email with an attached file results in an email with two attachemt.

#### Expected Behavior

No duplicated attach should be received.

#### Actual Behavior

Two attachment are received even if only one was attached.

#### Steps to Reproduce

1. Go to compose mail
2. set the from account
3. set the to email email address
4. click on the button to attach a file
5. click on the send button

#### Context

Low priority

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version: Firefox 54.0.1
* Operating System and version: Windows 10 Pro

**Comment by aaniceto** [comment]
"Low Priority" seems a bit wrong to me.. this is really important. I just discovered this while sending emails (w/ attach.) to multiple contacts from SuiteCRM.

**Comment by KaKite** [comment]
I agree totally with aaniceto, it's a CRM, C for Contact... if the manner in which we communicate with our Contacts is comprised in such a manner that we as business owners look less than professional, the priority for repairing the problem is HIGH

**Comment by KaKite** [comment]
Try the attached js (in the zip file) - this file was edited from the original EmailsComposeView.js file posted on Github (the one that created the double attachment) The fix is NOT upgrade safe

Rename/backup your existing in SuiteRootFolder/modules/Emails/include/ComposeView/EmailsComposeView.js
Copy the EmailsComposeView.js to the directory
If it doesn't work, may need an Admin -> JS repair

EmailsComposeView.zip

[EmailsComposeView.zip](https://github.com/salesagility/SuiteCRM/files/1604611/EmailsComposeView.zip)

**Comment by markcrobinson55** [comment]
I installed the file as directed by KaKite, did the repair and a quick rebuild. No effect. Still double attachments.
Version 7.10.4
Sugar Version 6.5.25 (Build 344)

**Comment by pgorod** [comment]
@Dillon-Brown I'm afraid this is another one that needs re-opening (or making a new Issue)

**Comment by markcrobinson55** [comment]
Any updates, betas, or band-aids would be appreciated. Thank you.

**Comment by markcrobinson55** [comment]
Just installed 7.10.5 -- Still double attachments. 
Really crimps my style...

**Comment by markcrobinson55** [comment]
7.10.7 still duplicates attachments. Is there anyone tracking this bug?

**Comment by markcrobinson55** [comment]
Bump?
Am I the only one having this problem?

**Comment by markcrobinson55** [comment]
Help?

**Comment by Dillon-Brown** [comment]
Hi @markcrobinson55, I had a few tries at replicating this but so far it seems to be working correctly for me on 7.10.7. These were my steps:

1. Add personal inbound/outbound email account.
2. Compose email in the emails module.
3. Add a single attachment.
4. Send email.

Were you doing anything different when you were encountering this issue? I would also recommend running Rebuild Minified JS Files + Rebuild JS Grouping Files + Quick Repair and Rebuild.

**Comment by markcrobinson55** [comment]
Thank you! Knowing it's just me is all I need. Now that I know the problem is only mine I can figure out a way to fix it. I really appreciate the reply.

**Comment by ebogaard** [comment]
As we've been experiencing this in 7.10.9, I been investigating this issue a bit further.
It seems that duplicate attachments are sent in the following situations:
1. Compose email + attach file with alphanumeric name => single attachment
1. Compose email + attach file with name that contains '&' => single attachment
1. Compose email + select template with attached file with alphanumeric name => single attachment
1. Compose email + select **template with attached file with name that contains '&'** => **duplicate attachment** + '&' in name of attachment is presented as **'&amp;amp;'**, so some double html-encoding of the file name and no decoding seems to be happening.

So in many cases only a single attachment is sent, but in the important case when using pre-designed templates to send to customers, the issue happens.

**Comment by markcrobinson55** [comment]
I am seeing something different.
I click on a contact, click the email and the email compose screen comes up. I type a message and attach, this time, a file named test.jpg
I received a duplicate attachment.
A previous message here said that the problem could not be replicated, so I am trying a fresh install -- haven'y got the fresh install running yet.

**Comment by Mausino** [comment]
I tested what wrote @ebogaard and he is right :) only special symbols or predesigned templates has this issue. Problem is also that still insn't applied patch #5961 it is still not applied and i tested it only on Softacoulous SuiteCRM demo

**Comment by samus-aran** [comment]
Hey @Mausino When you say "predesigned templates" is that with the special symbols or without as I can't see in this thread that is another cause for this issue? Could you elaborate on that possibly? 

Hey @markcrobinson55 Did you round to testing on a fresh install? You think it could be only from the detailview and  using a predefined template as Mausino said?

**Comment by Mausino** [comment]
@samus-aran i will install fresh version of 7.11 RC at weekend and will test it..  with all options which was here wrotted.

**Comment by Mausino** [comment]
@samus-aran i think that this issue no longer persisting.

**Comment by samus-aran** [comment]
Thanks @Mausino! Anyone else experiencing just request to reopen
