### ISSUE TITLE
Cases missing from dashboard

### ISSUE THREAD

**Issue by tomglare** [salesagility/SuiteCRM#3832]
"Cases" assigned to current user are initially missing from the dashboard
#### Issue

Cases do not initially show up on the dashboard. After loading the "edit dashlet" form, it was apparent that the "My items only" box was not ticked, and that no options were selected from the "assigned user" dropdown. After ticking the box, the cases still did not appear, but eventually did after a user (not necessarily the current user) was selected from the dropdown.

What seems to happen is this: if there is NO user assigned from the drop-down list (which seems to be the case if you have not edited the dashlet before), then no cases will be displayed, whether you tick the "Only my items" checkbox or not. Once you have picked a user from the dropdown, then that user's cases are displayed. If you tick the "my items" checkbox, then this seems to override the "user dropdown" and display just the cases assigned to "me". So it seems there is a minor bug, in that the checkbox fails to work if there are no assigned users selected. On a secondary point, the relationship between the "Only my items" checkbox, and the "assigned users" dropdown is not intuitive - if it is working in the way I assume it is, then a helpful enhancement would be to make the "user dropdown" widget disappear when you click the checkbox. 

#### Expected Behavior

The default setup should be with the "Only my items" box ticked, and this should work whether or not any users have been assigned via the dropdown. Ideally, to avoid confusion, the "assigned user" dropdown should disappear if the "Only my items" box is ticked.

#### Actual Behavior

If no users are assigned via the dropdown, as is the case on a fresh installation, then no cases are displayed even if the "my items only" box is ticked

#### Steps to Reproduce

1.On a system with out-of-the-box Cases dashlet configuration, create some Cases
2.Go to Home page - Cases not displayed
3.Edit dashlet and tick "Only my items" - cases subsequently still not displayed
4.Edit dashlet and select (any) assigned user from the dropdown list (leave "my items" box still ticked)
5.Cases will subsequently be displayed

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

SuiteCRM version 7.4.3.

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.2
After adding the dashlet and creating new cases, the cases appear in the dashlet
please re-raise or get in touch if you are still having this issue
