### ISSUE TITLE
Print to PDF not visible in Suite R theme in 7.8.5.

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#3837]
The "Print to PDF" button is not visible in the "Edit" menu in the Suite R theme.

#### Issue
The menu item is actually there, but the text is not visible.  

may be related to issue [3578](https://github.com/salesagility/SuiteCRM/issues/3578)

#### Expected Behavior
"Print to PDF" should show in the menu

#### Actual Behavior
The menu item is there, but the text is not visible.

![image](https://user-images.githubusercontent.com/19225193/27868549-1038375c-616b-11e7-9a8f-209adefc1e84.png)

#### Your Environment

* SuiteCRM Version 7.8.5
* Chrome, Edge, Firefox
* PHP 5.6, MariaDB 5.5.52
* CentOS 7

**Comment by Dillon-Brown** [comment]
@cjmny Unable to replicate on 7.8.5. Have you tried repair+rebuild / clearing cache?

**Comment by cjmny** [comment]
I have done so many times and the problem persists.  It also now appears to be not visible in Suite 7 as well.  In Suite P the item is clearly there, but the label is invisible.
![suitepmenu](https://user-images.githubusercontent.com/19225193/28034759-2a3d173a-6580-11e7-9168-f51c8054e93f.png)

**Comment by Dillon-Brown** [comment]
@cjmny Have you checked to see if $app_strings['LBL_PRINT_AS_PDF'] = 'Print as PDF'; is present in (include/language/en_us.lang.php) ?

**Comment by sergtech** [comment]
I can confirm this issue exists. Upgraded from 7.7.8 to 7.8.5, and using php 7. Adding the label in the en_us.lang.php fixed the problem of the label visibility in all themes. I inserted it at line 3479, right after the LBL_PRINT_AS_PDF entry.

**Comment by Dillon-Brown** [comment]
Closing this as its not a core issue. LBL_GENERATE_LETTER was removed by #3591 and the metadata was changed to use LBL_PRINT_AS_PDF. You will need to check your customisations to determine where the code is looking for the old label. I suggest moving this to the [Community Forums](https://www.suitecrm.com/forum/suite-forum) for assistance. Thanks.
