### ISSUE TITLE
Variables are not working in mail

### ISSUE THREAD

**Issue by Mma2s** [salesagility/SuiteCRM#3839]
Dear reader, 

I'm currently working in SuiteCRM 7.9 I have a problem with the variables in the mail. 

#### Issue

When I setup an email and I expect to fill in the variable after I send the mail. So that I don't need to insert things like name adres etc. by myself.

#### Actual Behavior

When the mail is send it will send the variables not filled. Hope there is a solutions for this. 

Let me know!

Cheers!

**Comment by amariussi** [comment]
This seems to be a copy of another issue:
https://github.com/salesagility/SuiteCRM/issues/3731

There is already a fix for that issue:
https://github.com/salesagility/SuiteCRM/pull/3838

And there is a forum topic explaining how to appy it, in case:
https://suitecrm.com/forum/suitecrm-7-0-discussion/14964-how-does-one-install-a-hotfix
