### ISSUE TITLE
Studio layout view issue - Changing panel to tab

### ISSUE THREAD

**Issue by emcrobert** [salesagility/SuiteCRM#384]
When I try to change the display type dropdown to change a panel to a tab on the layout view in Studio I can't click to select it. However, if I use the arrow keys and enter I can change the value (maybe a javascript bug?). This occurs with Firefox (v40) and SuiteCRM 7.3

**Comment by vladbar** [comment]
It is a new bug with Firefox 40 which was reported a couple of weeks ago.
https://bugzilla.mozilla.org/show_bug.cgi?id=1194733
Basically, mouseup events do not work as they should.

There is a quick hack for this issue:
https://bug1194733.bmoattachments.org/attachment.cgi?id=8648486

Another solution is to roll back to Firefox 39,  install Firefox 40 Developer Edition or use Chrome.

The Firefox team is aware of this bug and they promised to fix it asap here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1194733

**Comment by CaptainChainsaw** [comment]
Firefox appear to have fixed this (Status:	VERIFIED FIXED):
https://bugzilla.mozilla.org/show_bug.cgi?id=1194733

**Comment by willrennie** [comment]
@CaptainChainsaw @vladbar @emcrobert can this issue be re-tested and verify if this still exists, or if the Firefox fix resolves your issue?

**Comment by willrennie** [comment]
Tested and working in Firefox.
