### ISSUE TITLE
Vertical scrollbar missing in Studio>Module>Layouts>Detail/Edit>View History>Preview

### ISSUE THREAD

**Issue by bunglex** [salesagility/SuiteCRM#3842]
#### Issue
When previewing the View History of an Edit or Detail View in Studio the preview window has an exaggerated width and does not have a vertical scrollbar.  As a result you cannot see the preview correctly, and therefore the restore function cannot be used with confidence.

#### Expected Behavior
The preview window should display the view with a vertical scrollbar, and have the same width as the active view in Studio.

#### Actual Behavior
The preview is displayed without a vertical scroll bar in Chrome and Explorer. So the layout cannot be viewed in full

#### Steps to Reproduce

1. Log in and navigate to Admin>Studio
2. Select any module from the module list
3. Navigate to the modules Layouts>Edit View to Layouts>Detail View.
4. Click View History and then Preview one of the entries
5. The resulting preview window appears, but does not have a vertical scrollbar.

![image](https://user-images.githubusercontent.com/4482918/27889456-74e5897e-61e4-11e7-9355-0b2a493c8b2e.png)

#### Context

Cant preview the history of a detail or edit view layout, and therefore the restore function is not workable.

#### Your Environment

* SuiteCRM Version used: Version 7.9.2  
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7.0.18-0ubuntu0.16.04.1 
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.2 LTS

**Comment by bunglex** [comment]
this issue seems to have resolved itself - not sure why, but possible due to lack of understanding on my part when making customisations

**Comment by johnM2401** [comment]
Hey, 
Just fyi, i've re-opened this issue as it seems like it still may be a valid issue in some versions.

I've given this a try in 7.12.2, and can still see this occurring:
![image](https://user-images.githubusercontent.com/13675281/151765652-f59c8bfb-fb37-4e78-a6fa-54fff6adc759.png)


If you have any idea what may have changed on your end, to potentially resolve this, then please let us know!

Thanks!
