### ISSUE TITLE
Pure text Mail template not filled in compose view

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3847]
#### Issue

If you have an email template with the "Text only" checkbox marked and choose the template in the compose-view, no text is filled.

#### Expected Behavior

Text is filled

#### Actual Behavior

No text is filled

#### Steps to Reproduce

1. Have a template with the "Text only" checkbox marked
2. Choose said template in compose view
3. Mail body is not filled

#### Context

Many of our templates are pure text and do not work now.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL 
* Operating System and version (e.g Ubuntu 16.04): Win Server 2008R2

**Comment by Dillon-Brown** [comment]
I'll raise this as a bug. As a workaround you can copy the plain-text into the html and then select "send in plain text" when composing the email. Currently the email template will only pull in the html to the email composer instead of the plain-text.

**Comment by halest** [comment]
@Dillon-Brown Thanks, I'll do that for now

**Comment by PedroErnst** [comment]
Unable to reproduce this on the current version

![image](https://user-images.githubusercontent.com/34056696/38428765-7608fdb0-39b4-11e8-8b16-9119c7fc6a94.png)

![image](https://user-images.githubusercontent.com/34056696/38428745-6a617848-39b4-11e8-8461-4578e7fa4bc4.png)

![image](https://user-images.githubusercontent.com/34056696/38428779-82d203ac-39b4-11e8-931c-0514d79ebe37.png)
