### ISSUE TITLE
Email Template: Variable merge works in body but not in subject

### ISSUE THREAD

**Issue by someguynamedphil** [salesagility/SuiteCRM#3849]
Installed the "merge issue hotfix" and now merging works in the email body great, but not in the subject field

#### Issue
Email template's variable tokens are displayed in both the subject field and the body. Merge happens correctly in the body, but the receiver will only see the variable in the subject field.

 
#### Expected Behavior
All variable tokens would be merged in both the body and the subject fields when sending.

#### Steps to Reproduce
1. create email template
2. add a variable to the subject and the same one in the body
3. in leads select the email template
4. click on send.

#### Your Environment
SuiteCRM Version used: 7.9.2
Browser name and version: Chrome & FIrefox
Environment name and version (e.g. MySQL, PHP 7.0): PHP 7.0 MySQL 5.1.73
Operating System and version (e.g Ubuntu 16.04): CENTOS 6.9 x86_64 kvm

**Comment by Dillon-Brown** [comment]
@someguynamedphil Can you update #3731 with this info so we can make a single issue for just "email template variables not populating"?. All the email template variable not populating issues should eventually be solved by #3838.

**Comment by someguynamedphil** [comment]
Hi Dillion

#3731 was fixed with the hot fix. I installed it and all the variables are merging now within the body of the email.

It’s just when they’re added into the subject field that they don’t merge into the email’s subject, but are merged into the email body of the same email.

So I think it’s a different issue - although I’ll install .2 and see if its fixed.


Thanks!

phil

- - - - - - - - - - -
Phil Emery, creative director
  
phil@focusedcreative.com  
(416) 534-4273

Focused Creative
Big Idea Marketing & Strategic Graphic Design

https://focusedcreative.com
LinkedIn: https:/focusedcreative.com/linkedin/
================================================

**Comment by Dillon-Brown** [comment]
@someguynamedphil #3838 has been updated to fix the variables not being replaced in the subject field. Let me know how you get on.

**Comment by ErinDunn** [comment]
Im having issues with using workflow to automatically fire off an email template using a task under targets as a trigger. The email template is supposed to replace $prospect_name with either the name or a blank if their is no value but I keep getting the variable name instead which means either the the task record isn't related to the target (which I have verified that it is) or the variable conversion isn't working for targets. I can say that the same workflow rule geared for applications works as it is supposed to by replacing $lead_name with the appropriate value. The above mentioned fix for 3838 and 3731 do not seem to solve this issue. I am running SuiteCRM v7.9.4 on Debian Jessie v8.
