### ISSUE TITLE
Creating new account causes Record to indefinitely load.

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#385]
Record continues to try to load until you move to another page. Record is fine to view afterwards. Pressing F5 sometimes brings you to the Loading page, sometimes brings you to view the record itself.

**Comment by JimMackin** [comment]
Possibly fixed by the removal of the linked in connector in 7.3.1.

**Comment by willrennie** [comment]
Confirmed as fixed in SuiteCRM 7.3.1
