### ISSUE TITLE
Adding new user problems - Fresh 7.9.1 & 7.8.5

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3850]
Couldn't find a previous issue.
#### Issue

Can't add new users with system-generated passwords.
1. Add users won't save until a password is manually set. No welcome email is sent to the new user.
2. Missing 'Forgot Password email' template
3. Missing 'System generated password' template (and others but not relevant here)
4. Forgot Password link missing from login screen and doesn't work because of missing template

All in all it is now very difficult to add a new user.
#### Expected Behaviour

In prior versions, you could add a new user with a system generated password. The new user would be sent an email and could log in and be required to change the password. No admin effort required.

#### Actual Behaviour

Now must create user with an admin-generated password. Need to email the user with the URL, user & password.

Just spotted that System-Generated Password feature and Forgot Password feature are disabled on fresh install. Without templates they may not work.

#### Possible Fix

1. Add essential templates to distro.
2. Enable System-generated password and Forgot Password features on new install.

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

High priority because adding user is important.
#### Your Environment

* SuiteCRM Version used: Fresh 7.9.1 & 7.8.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by nelem** [comment]
OK, I have enabled System Password, Forgot Password and created the templates by copying the templates from an old instance. Deleted and re-created the user which now saves but no 'System generated' email is sent.

Also, go to the user, and click 'Reset Password' and a dialogue box come up 'Provide both a User Name and an Email Address' but this is on the actual user whose password I am trying to reset. There are no fields to enter such information.

Suite 7 theme (in 7.8.5) doesn't have a button for the admin to force a rest of a user's password.

**Comment by Mausino** [comment]
@nelem could it have something with this #3852 ???

**Comment by nelem** [comment]
I don't think so because no email is sent at all. #3852 send an empty email. Not 100% sure.

**Comment by Dillon-Brown** [comment]
@nelem I'm unable to replicate these issues on 7.9.2 or 7.8.5. Templates are present and appear to be working correctly. Is there any further info you can give that might help with replication?

**Comment by nelem** [comment]
No templates were installed from a fresh install (not upgraded) of 7.8.5 nor 7.9.2. I can't really give any further insight because manually creating the templates enables the emails to be sent.

See #3864 for login problems for deleted & recreated users.

**Comment by Dillon-Brown** [comment]
Tried a few more times to replicate this. This doesn't appear to be a core issue. Unless another member of the community can replicate this then I don't think we can progress any further. Fresh install of 7.8.5:

Forgot password button:
![screenshot 75](https://user-images.githubusercontent.com/26431166/28351807-13c2c074-6c4a-11e7-8abd-1f1653a15d25.png)

System email templates:
![screenshot 76](https://user-images.githubusercontent.com/26431166/28351808-1603aa74-6c4a-11e7-857c-ac25aaf73202.png)

**Comment by nelem** [comment]
@Dillon-Brown Maybe the package has been refreshed? Anyway, if templates are there and forgot password dialogue is available, there's not a lot we can do and I don't want to waste your time. let's close it and I'll re-download the packages.
