### ISSUE TITLE
Address fields (auto generated) not displaying help

### ISSUE THREAD

**Issue by javitoron** [salesagility/SuiteCRM#3859]
#### Issue
You set a help text into help for address fields and this help is not displayed when you go into edit view.

#### Expected Behavior
The help texts you wrote should be displayed

#### Actual Behavior
No help is displayed

#### Steps to Reproduce
1. Go into Studio / Accounts / Fields
2. Edit Billing Street and Billing city. you set a help text into help for each field
3. Save and go to Accounts
4. Click new account
5. Place your mouse over these two fields.

#### Context
I wanted to show addresses format using this help
Medium priority

#### Your Environment
* SuiteCRM Version used: 7.9.2
* Chrome Version 59.0.3071.115 (64-bit)):
* MySQL, PHP 7
* Ubuntu 14.04.5

**Comment by javitoron** [comment]
Sorry I'm a newbie with github... I closed it by mistake... I was trying to raise the pull request to the salesAgility::master branch... not sure how this was closed...

**Comment by Dillon-Brown** [comment]
Hi @javitoron it looks like the merged PR is to your own fork and not SuiteCRM. To make a pull request to the right branch you are going to want to go onto your user profile -> personal SuiteCRM fork -> new pull request. Then select salesagility/SuiteCRM as the base fork and hotfix as the base. Make the head fork your own fork and the comparison the branch with the fix. Thanks for the contribution!

**Comment by javitoron** [comment]
Done! Thanks!!!
