### ISSUE TITLE
Error creating new target list

### ISSUE THREAD

**Issue by rufusjones** [salesagility/SuiteCRM#386]
When I attempt to create a new target list, I get the following error:

Error: Module TargetLists does not exist.
At this url:
/index.php?module=TargetLists&action=EditView&return_module=TargetLists&return_action=DetailView

When I change the URL as follows, everything works:
/index.php?module=ProspectLists&action=EditView&return_module=TargetLists&return_action=DetailView

Is the module just pointing to the wrong link?

**Comment by darthtang** [comment]
Was 'TargetLists" (/index.php?module=TargetLists) given to you by the system or did you type this in yourself?
It is because Module TargetLists does not exist.
in suite, the module file is called 'ProspectsList' not TargetListS

**Comment by darthtang** [comment]
If you were to go to the (on the browser...not in the file system) targetList module -> create. you will then see "index.php?module=ProspectLists&action=EditView&return_module=ProspectLists&return_action=DetailView" as the address for the page.

**Comment by willrennie** [comment]
@rufusjones can you detail the steps to replicate, and clarify if this is still an issue?

**Comment by willrennie** [comment]
Closing as there has been no response or steps to replicate detailed for 7 months. Please use the forums if you require further assistance: https://suitecrm.com/forum
