### ISSUE TITLE
Typo in modules/InboundEmail/InboundEmail.php

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3860]
in function savePersonalEmailAccount() line 2622:
variable $storedOptions should be $stored_options

**Note:** inconsistent convention for variable names, array keys and function names
e.g. 1. in function handleAutoresponse() of the same file, $storedOptions is used.
2. we see key 'only_since' and 'folderDelimiter'; in two different styles
3. handleAutoresponse() should be handleAutoResponse()

**Comment by Dillon-Brown** [comment]
Hi @HeroicHitesh, this has been resolved by #7959
