### ISSUE TITLE
Campaign is not working

### ISSUE THREAD

**Issue by Mma2s** [salesagility/SuiteCRM#3861]
I don't know if this problem is fixed already. But in SuiteCRM 7.9.2, the campaign module is not working properly. 

#### Issue
I can send normal mails trough contacts etc. But when I want to do an email campaign it doest send the email. Not even as a test. 

#### Expected Behavior
The emails should send to any mailadres. 

#### Actual Behavior
Nothing happens, no email is send.

**Comment by amariussi** [comment]
@Mma2s Could you please explain more in detail what you are experiencing please?

First start with the precise details of your system (OS, DB, PHP and their versions).

Then, please provide detailed information on your schedulers and your cron jobs: are the schedulers running properly, is the SuiteCRM cron job set up properly, what is the user running it and its group.

Are your permissions set correctly?

Is your SuiteCRM a lean install or is it an upgrade? Please provide details.

In case it's an upgrade (from which previous versions?) could you send Campaign emails before?

Please provide a full detailed step by step description on how to replicate your problem.

**Comment by Mma2s** [comment]
I'm downloaded the version form suitecrm.com I don't use cronjob myself.. Don't even know how to use that. 

The problem is that if I want to send an email from campaign module it does't work. Not even as a testmail. But, if I send an email from the contact/lead it works perfect. So I have no idea what went wrong.

I'm working from a macbook, don't know if that could make it any different.

**Comment by amariussi** [comment]
Please read the manual. You have to set the system before you start using it. Withouth setting up the SuiteCRM cron job it will not work.

Go to the SuiteCRM Forum and search for further instructions if the manual is not sufficient for you.

This is the wrong place to ask for help, since there is a dedicated forum.
