### ISSUE TITLE
Umlauts in signature lose encoding in compose-view

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3863]
#### Issue

If the mail signature contains Umlauts (as most German signatures do), they lose encoding in the compose view
`Herzliche Grüße` => `Herzliche GrÃ¼Ãe`

#### Expected Behavior
Encoding is kept

#### Actual Behavior
Encoding is lost

#### Possible Fix

Fix UTF-8 encoding?

#### Steps to Reproduce

1. Signature with Umlauts
2. Compose and Send
3. Umlauts are gone

#### Context

Inconvenient as we'll have to change all signatures on the system.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL 
* Operating System and version (e.g Ubuntu 16.04): Win 2008R2

**Comment by Mausino** [comment]
@halest we have same issue :) for slovak + german lang :D and yes, it's utf-8 issue for signtatures + we using TINY editor. I tested and issue also persist for HTML + Mozaik editors too
