### ISSUE TITLE
Non-admin users can inline edit another users data

### ISSUE THREAD

**Issue by javitoron** [salesagility/SuiteCRM#3867]
#### Issue
After creating a regular user I was checking that they could view details of the coworkers but they have no edit action, but then I realised that they can edit inline

#### Expected Behavior
They shouldn't be able to edit inline

#### Actual Behavior
When you double click in name field, ie., you get the input text and the submit button, and it actually save changes.

#### Possible Fix
Make as in account detailedView, if you have no access to edit inline edit does not respond.

#### Steps to Reproduce
1. Create a regular user (non-admin)
2. Go to users list
3. View a user
4. Double-click on name field

#### Context
Not sure but feels like a serious issue that people can edit another users details so I say this is a high priority one.

#### Your Environment
* SuiteCRM Version used: 7.9
* Browser name and version: Chrome Version 59.0.3071.115 (64-bit)
* Environment name and version MySQL, PHP 7
* Operating System and version Ubuntu 14.04.5

**Comment by pgorod** [comment]
I wonder if this is limited to the Users module or if it affects every other Security Settings restriction (user groups, roles, permissions). Maybe the inline edit is bypassing these security checks, which would be indeed a bad thing. I'm afraid I can't test this right now.

**Comment by javitoron** [comment]
Well, I limited this user's access to many modules using a role called "Owner only" as recommended in [this article](https://www.sugaroutfitters.com/docs/securitysuite/example-of-a-typical-setup).

And this user can't edit the role but he can remove it, gaining access to everything...

**Comment by pgorod** [comment]
@javitoron if that is the case, then this is the sort of thing that would have been better to report via the email security@suitecrm.com and not be in a public forum...
 
Although I guess it wasn't clear from the beginning how big a problem this really was, so I understand why you started this issue (and I thank you, of course). Let's hope this gets fixed ASAP.

**Comment by javitoron** [comment]
Yes, sorry about that, I wasn't sure if this was a real security issue, first time it was just about the details of users... now with the roles removing issue I see it's been scaled up... sorry...

**Comment by Dillon-Brown** [comment]
@javitoron Closing this as it relates to a high priority security issue. Our internal reference number for this issue is SCRMBT-18. Thank you for bringing this to our attention.

In future please report all security issues through the designated security email address: security@suitecrm.com
