### ISSUE TITLE
AOR doesn't work in SuiteCRM 7.2 and 7.3

### ISSUE THREAD

**Issue by mstsc-v** [salesagility/SuiteCRM#387]
Hi,

I have some reports created in my SuiteCRM and since I've updated to SuiteCRM 7.2.X I can't use the AOR Module.

This problems occurs

1- Some reports use date controls as conditions and when I select a date and I click in update, the report is generated, but items in any date are displayed (the condition aren't respected).

2- When I run a report and I click on next or prev button to navigate between pages, the report reset (a blank report are displayed).

I've updated to SuiteCRM 7.3 but the problem persists

Could anyone help me?

**Comment by willrennie** [comment]
Have you run a Quick Repair & Rebuild in Admin -> Repair after upgrading? Have you ensured permissions are set correctly? Are there any errors in your suitecrm.log file?

**Comment by willrennie** [comment]
Recommendations for further debugging/investigations provided. If you need further assistance please update with your status on this issue.

**Comment by mstsc-v** [comment]
Hi Will,

I've noticed that when I run a report, the start date that I set in the AOR Module are ignored:

Sep 8 12:10 PM GMT -3: I run a report to list calls between Aug 1 and Aug 31

and the log shows:

SELECT calls.id, name, reminder_time, description, date_start, status, parent_type, parent_id
                                FROM calls LEFT JOIN calls_users ON calls.id = calls_users.call_id
                                WHERE calls_users.user_id ='1'
                                    AND calls_users.accept_status != 'decline'
                                    AND calls.reminder_time != -1
                                        AND calls_users.deleted != 1
                                        AND calls.status = 'Planned'
                                    AND date_start >= '2015-09-08 15:10:38'
                                    AND date_start <= '2015-09-08 16:10:38'

All tries the log shows on date_start the actual date and time some hours in future (my timezone is gmt -3 it's 1:16 PM here).
