### ISSUE TITLE
English (GB) translation error

### ISSUE THREAD

**Issue by tomglare** [salesagility/SuiteCRM#3871]
#### Issue

Clicking on "delete" buttons in subpanels triggers the prompt "remove email address"
#### Expected Behavior

The prompt should simply read "Remove"
#### Actual Behavior

The prompt reads "remove email address"
#### Possible Fix

In the file "en_GB.lang.php", the labels LBL_ID_FF_ADD and LBL_ID_FF_REMOVE reference the text "Add Email Address" and "Remove Email Address" respectively - this should simply be changed to the generic "Add" and "Remove"
#### Steps to Reproduce

1. Click on any subpanel "delete" button (or the right hand part of the compound button)
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

SuiteCRM 7.4.3
Language pack en_GB

**Comment by horus68** [comment]
this is related to this fix - See https://github.com/salesagility/SuiteCRM/pull/3528
Note: it was "Remove" but changed to "Remove Email Address" in the most recent PR for it. 

```
'LBL_ID_FF_ADD' => 'Add Email Address'
'LBL_ID_FF_REMOVE' => 'Remove Email Address'
```
