### ISSUE TITLE
Can't rename a relationship in Studio

### ISSUE THREAD

**Issue by managume** [salesagility/SuiteCRM#3872]
#### Issue

Studio doesn't save the label value of a custom/builder relationship in Studio when I try to rename it.

#### Expected Behavior

When I edit the label value in Studio and click in Save and Deploy, the new value have to be saved and appear as new label value.
#### Actual Behavior

Despite I rename the label value and click in Save and Deploy, the changes appear in en_us.lang.php in custom/modules/mymodule/language but the new value is not showed in any view.
#### Possible Fix

![image](https://user-images.githubusercontent.com/4390275/28210040-d3166cae-6895-11e7-8e96-c4554949f684.png)

According to the SugarCRM language files hierarchy. Studio can't save and deploy when exists some file in `./custom/Extension/modules/<module>/Ext/Language/` that's compiled in `./custom/modules/<module>/Ext/Language/<language key>.lang.ext.php`.

So here my proposal:

>If the label we want to rename in Studio has an assignation in /custom/Extension/... we will need to change label value in `./custom/Extension/modules/<module>/Ext/Language/` and in `./custom/modules/<module>/Language/` as well.

#### Steps to Reproduce

1. Created a relationship in builder or custom 1:M between my module and Accounts

2. Go to Studio/My Module/Labels
![image](https://user-images.githubusercontent.com/4390275/28062463-4d5f32e4-662e-11e7-8a17-4e41bb207ae1.png)

3. Edit the relationship label value
![image](https://user-images.githubusercontent.com/4390275/28062498-6c2269c6-662e-11e7-800a-7b962a61f66d.png)

4. Click in Save and Deploy
![image](https://user-images.githubusercontent.com/4390275/28062512-79fd90de-662e-11e7-9cbd-79b603cbbce8.png)

5. Magic! It comes back to previous value
![image](https://user-images.githubusercontent.com/4390275/28062543-978e96ac-662e-11e7-8b42-2bc43051cb22.png)

#### Context

I have read several posts about this issue as:
1. https://www.suitecrm.com/forum/suitecrm-7-0-discussion/9847-accounts-relationships-problem-in-suitecrm-is-not-in-sugarcrm
2. https://suitecrm.com/forum/suitecrm-7-0-discussion/2562-renaming-relationship-label
3. https://suitecrm.com/community/forum/suitecrm-7-0-discussion/7124-renaming-relationship-label

Some provide temporaly solutions that do not work for me. Other ends with it's an not fixed bug of Sugar 6.5 core.  Also I tried to make a custom language file to override the previous one but didn't have effect as well.

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 59.0.3071.86 (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.15, MySQL 5.7.17
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.2

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.2
when I create the custom module, renaming the relationship label and saving & deploying doesnt change the label back to its default value
please re-raise or get in touch if you are still having this issue
