### ISSUE TITLE
7.9.2, Importing Leads, got "Undefined index: google_maps_api_key"

### ISSUE THREAD

**Issue by sasha2002** [salesagility/SuiteCRM#3877]
#### Issue

When try to import Leads from prepared csv got problem (NOTICE: [8] Undefined index: google_maps_api_key on line 356 in file /modules/jjwg_Maps/jjwg_Maps.php).
Normally is need to be imported.

#### Expected Behavior

Imported Leads from csv
#### Actual Behavior

NOTICE: [8] Undefined index: google_maps_api_key on line 356 in file /modules/jjwg_Maps/jjwg_Maps.php

#### Possible Fix

Commented line 356 and 18
#### Steps to Reproduce

1. Import Leads from csv

#### Context

medium priority
#### Your Environment

* SuiteCRM Version used: 7.9.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): ALL
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7, Apache2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1

**Comment by sergtech** [comment]
Found same issue on 7.8.5 with an import on a custom module. 
Fails after the import of 100. Attempting a re-import fails after 200 and so on. 
The module (and imported fields) has a relationship to the Accounts module.
Commenting out the lines (8 and 356 for me) stopped the import from completing at all.

**Comment by JamesRPAS** [comment]
Possible Fix:

Replace 
`$rev['google_maps_api_key']` 
on line 356 with 
`(isset($rev['google_maps_api_key'])?$rev['google_maps_api_key']:'')`

Doing this allowed me to import >100 leads.
