### ISSUE TITLE
Spam Folder in 7.9.x [Suggestion]

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3878]
#### Issue

We live in 21st century and daily everybody is getting many spam emails 💯 

Problem is that spam has own folder which i can't add into SuiteCRM emails...
Because when i get spam, my hosting put it into spam folder but i have only this 3 folders: Inbox, Sent, Trash :( The irony of life is that trash folder is not important becuse you can't delete emails in SuiteCRM :D

And the point is if are you working only with SuiteCRM emails you can lost many emails from your customers because were in spam folder :(

![spam](https://user-images.githubusercontent.com/5773777/28171786-dc7d81a8-67e9-11e7-8bd6-73630e818f21.png)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spam Folder in 7.9.x](https://trello.com/c/b3Krz4rR/210-spam-folder-in-79x)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
