### ISSUE TITLE
SMTP login + password in user profile 7.9.2

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3879]
#### Issue

I don't understand why have user in profile the smtp login + password, i think that there are missing those fields:

SMTP SERVER, 
SSL or TLS dropdown
SMTP port
SMTP custom name for user

![smtp](https://user-images.githubusercontent.com/5773777/28173127-ca11bb84-67ed-11e7-9501-84ebe25c3be8.png)

 if users need other fields to connnection on SMTP.. and own smpt also can add by EMAIL SETTINGS

![smtp2](https://user-images.githubusercontent.com/5773777/28173139-cf2b3f1e-67ed-11e7-9047-562b8db2f998.png)

Is this issue ? or had the @salesagility some plan with this fields?

#### Your Environment

* SuiteCRM Version used: Official SuiteCRM 7.9.2

**Comment by Dillon-Brown** [comment]
@Mausino This should be resolved by the already merged PR here: #3873
