### ISSUE TITLE
Users cannot inline edit on mobile

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#388]
Users cannot inline edit on mobile. It appears that mobile touch actions are not recognised and hence the user cannot inline edit on detail/edit view.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users cannot inline edit on mobile](https://trello.com/c/XWbFKyhp/150-users-cannot-inline-edit-on-mobile)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
