### ISSUE TITLE
How can i modify the version of generated pdf?

### ISSUE THREAD

**Issue by immhub** [salesagility/SuiteCRM#3882]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
@immhub it seems something went wrong when you were posting, only the title appears and nothing else. I guess the developers would have to go into a lot guessing work to fix the bug you're reporting with just this... :-)

**Comment by Dillon-Brown** [comment]
Please re-open if you are able to fill out the template. Thanks.
