### ISSUE TITLE
Changed version PHP from 7.0.16 to 7.1.6 down my site

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3899]
#### Issue

We changed the PHP versions from 7.0.16 to 7.1.6 and the site was down.. we investigate with hosting and here are the results:

<img width="474" alt="aaa" src="https://user-images.githubusercontent.com/5773777/28336777-8646cd44-6c03-11e7-8685-3292c59108e5.png">

#### Steps to Reproduce

1. Change the version PHP on 7.1.x from 7.0.x

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.2
* Browser name and version : Chrome 56.x 64bit
* Environment name and version : MySQL 5.6, PHP 7.0.16
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this in 7.9.x as a core issue. If this issue still exists and you can provide more information for us to proceed then it can be reopened. Thanks.
