### ISSUE TITLE
Pre-filled RELATE TO field in compose email pop up window isn't working for CASE in 7.9.x

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3906]
#### Issue

When you composing email in record in subpanel HISTORY in old email system 7.8.x was pre-filled the RELATE TO field by record name in case module.. now is it empty and must do this user and it consumes time :(

#### Expected Behavior

Will pre-filled RELATE TO field in compose window of email, when is email sending from case record

#### Actual Behavior

RELATE TO field is empty

#### Steps to Reproduce

1. Go to any case record
2. Click in History/Activity sub-panel button Compose Email
3. Look on RELATE to field in compose pop up window of email

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.2
* Browser name and version: Chrome 56.x 64bit
* Environment name and version: MySQL 5.6, PHP 7
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
@Mausino I'm unable to replicate on 7.9.2 or 7.9.3. Contacts->Activities->Compose email autopopulates the "Related To" field. Is there any more info you can give that might help with replication?

![contact](https://user-images.githubusercontent.com/26431166/28327210-aeb6d8a6-6bda-11e7-9e46-a236cef0af02.png)

**Comment by Mausino** [comment]
@Dillon-Brown you're right.. i tested it on official demo.. i fixed in my local something that work...
now only one module doesn't assign it automatically.. it's CASE module
Should i change this description in ticket  or for cases is irelevant ?

![cases_demo](https://user-images.githubusercontent.com/5773777/28336199-5222c736-6c01-11e7-9601-85729774d4d5.png)

**Comment by Dillon-Brown** [comment]
@Mausino I can replicate the "Related To" field not being auto-populated on cases. Can you change the title/description to just the "Cases" module? Thanks.

**Comment by Mausino** [comment]
@Dillon-Brown i changed title + description that will pass on CASE module 👍

**Comment by Mausino** [comment]
@salesagility @samus-aran tested on local instance and worked for months 👍

**Comment by Mausino** [comment]
The patch https://github.com/Dillon-Brown/SuiteCRM/commit/b58952041a83265c355855701584de665d527e41 is working and it's almost 1,5 year and still is sitting here. 

Should be this pach merged https://github.com/Dillon-Brown/SuiteCRM/commit/b58952041a83265c355855701584de665d527e41 and add to closest milestone ?

**Comment by Mausino** [comment]
@Dillon-Brown small issue.. proposed solution.. created pull request.. but it stucks here

Should be assigned pull request merged and should be issue added to next relase  ? :)

**Comment by Dillon-Brown** [comment]
@Mausino Appears to no longer be an issue, I can't replicate on demo.

**Comment by Mausino** [comment]
@Dillon-Brown tested and it's working 👍 sorry i didn't retest it again on latest version.
