### ISSUE TITLE
Choose editor in eMail-Compose-View?

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3913]
#### Issue

I was of the expression that choosing the eMail-editor in the profile should apply to the regular compose-view, too. It seems to only apply to the template-creation. Is that a bug? I'm being asked a lot about inserting links in the compose-view via the GUI but can't help out.
#### Expected Behavior

choosing the eMail-editor in the profile should apply to the regular compose-view
#### Actual Behavior

Only apply to the template-creation
#### Steps to Reproduce

1. Switch editors in profile
2. Compare E-Mail-Compose-View

#### Context

My would like more formatting options, especially links. I have sent them the html-format for inserting links but that is of course not a satifying solution.

#### Your Environment

* SuiteCRM Version used: 7.9.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP7
* Operating System and version (e.g Ubuntu 16.04): Win Server 2008R2

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Choose editor in eMail-Compose-View](https://trello.com/c/7JHlHV3s/211-choose-editor-in-email-compose-view)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
