### ISSUE TITLE
All archived mails show the same body

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3919]
#### Issue

After updating to 7.9.3 I cannot see archived mails. All of them show the same body and no recipient.
#### Expected Behavior

Look at archived mails
#### Actual Behavior

All archived mails show the same body
#### Steps to Reproduce

1. Open archived mail
2. Open another archived mail

#### Context

High priority as users have no access to archived mails

#### Your Environment

* SuiteCRM Version used: 7.9.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL 2014 PHP7
* Operating System and version (e.g Ubuntu 16.04): Win Server 2008R2

Error_log:
`Wed Jul 19 16:29:31 2017 [5272][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT emails.*, users.user_name as assigned_user_name
 FROM emails
 LEFT JOIN users ON emails.assigned_user_id=users.id 
WHERE emails.uid LIKE "158640" AND  emails.deleted=0 
 ORDER BY date_sent DESC::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name '158640'.`

**Comment by halest** [comment]
In my opinion this may stem from the fact that the created SQL query uses double quotes which on MSSQL compares to another column. My guess is it should work with single quotes.

**Comment by halest** [comment]
Oddly though, tunning the query without the where-condition gives me the mails, but the uid-column is NULL everywhere. 
Running it with the where-clause and changing the double to single quotes works but (correctly) gives me 0 results

**Comment by halest** [comment]
Okay, more info. I've jumped into SugarBean.php and extracted the $query, which is:
`SELECT emails.*, users.user_name as assigned_user_name
 FROM emails
 LEFT JOIN users ON emails.assigned_user_id=users.id 
WHERE mailbox_id = 'cf6ef38c-97bb-142b-cb98-5950ec069e73' AND uid = '158729' AND  emails.deleted=0 
 ORDER BY date_sent DESC`

So that looks okay but still, uid is NULL almost everywhere...

**Comment by halest** [comment]
Okay, more input. I've replaced the EmailsController.php with the one from 7.9.1 I had backed up and at least I can see the correct email body now. Though I still get no sender or recipient

**Comment by halest** [comment]
Replacing the whole mail folder with the 7.9.1 mail folder has the same result.
Interestingly it will load the first mail (minus sender and recipient) and afterwards will always show the same mail again and again

**Comment by halest** [comment]
@samus-aran or @Dillon-Brown Sorry to ping you directly but I don't know where else to look and haven't gotten any further in 24 hours

**Comment by Dillon-Brown** [comment]
Hi @halest we can replicate this on our side as well. I'll mark this as a high priority and we'll look to resolve it as soon as possible. Thanks

**Comment by halest** [comment]
@Dillon-Brown Thanks, that helps

**Comment by halest** [comment]
More input, I've restored the old db from 7.9.1 and it doesn't seem like the problem is on that end. Basically identical

**Comment by hinnerkweiler** [comment]
Same issue here. This seems not to be a DB issue at all.

After doing a "quick repair" in Admin section the first opened message becomes the body text for all later opened mails. Doing a "quick Repair" again changes that to the first opened Mail after that and so on.  Looks to me like a pointer issue or array not being correctly refreshed when opening another mail.

Knowing you guy hear that all the time. - A quick fix would be highly appreciated on this side :)
Hinnerk

**Comment by samus-aran** [comment]
Hi guys we are looking at this currently and hopefully get a resolve to you as soon as possible.  It sounds like a similar case we had before regards to caching.

**Comment by blloyd78** [comment]
I have upgraded my test instance to 7.9.4 and this problem is still present.

**Comment by halest** [comment]
That does not fix it for me. Anybody else more luck?

**Comment by blloyd78** [comment]
The proposed fix works for me after completing a 'repair and rebuild' operation. However, we're back to the issue with HTML emails not displaying correctly on the detail screen until the page is refreshed.

**Comment by halest** [comment]
Correction, after rebuilding twice and logging in again, it now shows the correct body. No Sender or recipient though, fields are empty

**Comment by Dillon-Brown** [comment]
Hi @blloyd78, Do you think you could do a fresh repair/rebuild, open a new archived email and check what tpl its using? It should either be emailDetailView.tpl or EmailsNonImportedDetailView.php.

**Comment by Dillon-Brown** [comment]
@halest I believe the missing sender/recipient is unrelated to the body issue.

**Comment by blloyd78** [comment]
How do I check which tpl is being used? I simply added the code alteration documented in fix #4009

**Comment by Dillon-Brown** [comment]
@blloyd78 You can look in cache/smarty/templates_c after applying the fix, repair/rebuild and clicking on a new archived email.

**Comment by blloyd78** [comment]
Both of the specified files are present in the folder.
