### ISSUE TITLE
Does anyone know how to get the group emails actually working? Are they broken?

### ISSUE THREAD

**Issue by jbeima** [salesagility/SuiteCRM#3922]
I have done a fresh install of 7.9.2. Then I read that the patch to 7.9.3 carried a bug fix for group emails so I confirmed the challenge still exists in 7.9.3.

Here is what happens and what I have done:

Do a clean install.

Then create 3 admin users. The only data I entered was their first and last names and their positions with the company.

Then I configured the Outgoing email account and made sure it was working. All good.

Then I logged in as each of the 3 admin users one by one and setup their individual private email accounts. All worked perfectly.

Then I logged back in as my initial admin user, went into the Admin - Inbound Email.

Under this menu I created a group email account and entered all the settings for the company "info" email account. All staff member read and respond to the "info" email account.

I then logged in as one of the Admin Users and went into their email. Via All - Email

At the top I clicked on the "gear" to edit the email settings. On the user page I went down and clicked on the "Settings" button in the Email Settings section.

On the Mail Accounts Tab the group info account appeared, and I checked the box.

The on the General Tab under Folder Management the "INBOX" for the Info account showed up.

I went back to "All - Email" and by clicking on the folder at the top this user can now switch between both INBOX and email accounts perfectly. Also the user can select who they want to compose the email from just fine.

NOW here is where the challenge happens.

When I logout and log in as the second user.

I go into All - Email... Click The Gear... Click the Settings Button...

On the Mail Accounts Tab the Info account shows up, so I can click it.

HOWEVER back on the General Tab the INBOX for the General Account does NOT show up.

I have confirmed this is the same for any other user on the system.

The INBOX for the Group Email account only shows up for One User.

How do we get the INBOX to he selected by all the users which have the Group account activated?

Is this a bug? Am I doing something wrong?

John Beima
CDCI Development Inc.
jbeima@cdcidevelopment.com

**Comment by jbeima** [comment]
I should have added.

The site is being run on a CentOS V:7.X web server with PHP V:7.1.6.

I am not sure if this is a PHP challenge, a CSS challenge, a JavaScript Challenge.

I am also using Google Chrome to access the site. Since I know THAT could be a factor as well.

**Comment by sergio91pt** [comment]
@jbeima What bug fix are you talking about?

You created a group email account, but the account is [not associated to a valid (group) user](https://github.com/salesagility/SuiteCRM/pull/3812#discussion_r126318550), so you probably can only open it with the account that created it due to #3719.

Right now you can't associate the account through the UI #3865, only manually through the database.

**Comment by jbeima** [comment]
@sergio91pt The inbox can be accessed by any ONE user on the system. As long as you deactivate it for the current user that has it.

So it has nothing to so with the user that created it. If you follow the steps I mentioned above I already mentioned I created it with Admin #01 and am using it under Admin #02.

However Admin #03 can not view any mail.

THE BUG:

The bug is, this is a group account, under Folder Manager the INBOX should show up to be selected, once the group account is activated under the mail accounts.

All three users have the group account activated/checked under the mail accounts tab.

The INBOX should be showing up in the Folder Manager for all three accounts, and it only shows up for one. Once it is selected.

If it is NOT selected, then any of the 3 admins can select it and it works fine.

Everyone should be able to select it.

**Comment by jbeima** [comment]
@sergio91pt - Bug #3865 is NOT effecting this since as I mentioned in my original post I am logging out and logging in as each user to edit that users settings.

I have already discovered this bug and was working around it.

As to bug #3719 I don't see this one. Each of my 3 users can ONLY select their own private email account. So I have never seen any traces of this.

**Comment by sergio91pt** [comment]
I'm a relatively new user to SuiteCRM. My take on group email accounts is that they need to be associated with a group user (the type that you cannot assign a password/login as), thus my reference to #3865. I may be wrong tough, the lack of/inconsistent ACL checks do not help to determine the intended way to use this feature.

When I said #3719, I meant to link to the PR/code change and not the issue itself, as a possible reason to why you could open the mailbox in the 1st account.

**Comment by pabaillon** [comment]
I have the same problem with group email. I can check it, but i can't see it...
![capture](https://user-images.githubusercontent.com/31985913/30852409-f8cfa4a6-a2ab-11e7-933f-08be5987475e.PNG)
![capture2](https://user-images.githubusercontent.com/31985913/30852418-fd1abad2-a2ab-11e7-8cce-9254d962473d.PNG)

**Comment by ppoudrier** [comment]
I also have the exact same problem. Only the admin user is able to select the group inbox, noone else.

**Comment by Dillon-Brown** [comment]
This issue should now be resolved. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
