### ISSUE TITLE
SuiteCRM 7.9.3 isn't saving UTF-8 characters on all modules

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#3923]
#### Issue

The UTF-8 characters in the text are removed on saving in all modules.
This bug is especially annoying creating email templates on campaigns module.

#### Expected Behavior

Saving an opportunity:
Opportunity name: Spanish = Español
Opportunity description: Vowels = aeiou | Vowels branded: áéíóú | Clay-colored thrush = Yigüirro

#### Actual Behavior

Saving an opportunity:
Opportunity name: Spanish = Espal
Opportunity description: Vowels = aeiou | Vowels branded: | Clay-colored thrush = Yigrro
#### Possible Fix

I tested on SuiteCRM 7.9.2 and backward and everything worked as expected, the bug was introduced on SuiteCRM 7.9.3

#### Steps to Reproduce

1. Create a new oportunity with any UTF-8 character on name, eg: Español
2. The UTF-8 character and the following non-UTF-8 character aren't save, eg: Espal (ño disappear)

#### Context

I was creating an email template on campaigns module with mozaik and notice how several characters dissapear

I then check in another instance with SuiteCRM 7.9.2, 7.9.1 and backward and the same text was saved without problem.

Then I check creating some opportunities, contacts, accounts, etc and the problem appears on every module.

You can check on a test enviroment with SuiteCRM 7.9.2 UTF works: `git reset --hard 084f2f3f1` 084f2f3f1
You can check on a test enviroment with SuiteCRM 7.9.3 UTF doesn't work: `git reset --hard 3daeb36ed` 3daeb36ed

#### Your Environment

* SuiteCRM Version used: 7.9.3
* Browser name and version: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Environment name and version:
  - mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
  - PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 (cli)
  - Apache/2.4.18 (Ubuntu)
- Operating System and version: 
  - Distributor ID: neon
  - Description: KDE neon User Edition 5.10
  - Release: 16.04
  - Codename: xenial

**Comment by javitoron** [comment]
This is a duplicate of #3903 and there is an easy fix there!

**Comment by cumanacr** [comment]
@javitoron thank you indeed commit 74a4c5583d2aa435081821272893eda54d56b42b fixed
