### ISSUE TITLE
7.9.4 creating an email from template removes associated attachements

### ISSUE THREAD

**Issue by workaholiker1** [salesagility/SuiteCRM#3925]
#### Issue
Creating an Email from Template doesnt take over the documents defined in template. No attachements are shown on the bottom and if email is send, it comes without any file attached. 

#### Expected Behavior
Documents shoud be automatically attached to an email

#### Actual Behavior
Documets are not getting automatically attached to an email created from an email template

#### Steps to Reproduce

1. create an email template
2. associate some documents with it
3. compose a new email, select the template created in step 1

**Comment by pgorod** [comment]
Can you check if the attachments get saved with the Template?

I mean, check whether the problem occurs _before_ any email sending attempt.

**Comment by rackgears** [comment]
This issue is annoying. Template with attachment doesn't really attach it on actual email. Please provide a patch that I can test any tell you if it works,

**Comment by jyotisinghraghav** [comment]
This can be solved by adding some sort of  attachment  code while selecting email template during composing mail.

Here is the file to update:-
File Path:- modules/Emails/include/ComposeView/EmailsComposeView.js
Line No. :-  Around '1270' 
Function : '$.fn.EmailsComposeView.onTemplateSelect ';

Code:-
  $.fn.EmailsComposeView.onTemplateSelect = function (args) {
     var confirmed = function (args) {
	var self = $('[name="'+args.form_name+'"]');
      $.post('index.php?entryPoint=emailTemplateData', {
        emailTemplateId: args.name_to_value_array.emails_email_templates_idb
      }, function (resp) {
		  console.log(resp);
		 var r = JSON.parse(resp);
      /**********************Start of attachment Part**********/
		for (i = 0; i < r.data.attachments.length; i++) {
              var id = r.data.attachments[i]['id'];
              var fileGroupContainer = $('<div></div>')
									.addClass('attachment-group-container')
									.appendTo(self.find('.file-attachments'));

			  var fileInput = $('<select></select>')
				.attr('style', 'display:none')
				.attr('id',  id)
				.attr('name', 'template_attachment[]')
				 .attr('multiple', 'multiple');
        
			  var fileOptions = $('<option></option>')
				.attr('selected', 'selected')
				.attr('value',  id)
				.appendTo(fileInput);
		
	          fileInput.appendTo(fileGroupContainer);
		 var fileLabel = $('<label></label>')
				.attr('for', 'file_' + id)
				.html('<span class="glyphicon glyphicon-paperclip"></span>')
				.appendTo(fileGroupContainer);
		
	var fileContainer = $('<div class="attachment-file-container"></div>');
          fileContainer.appendTo(fileLabel);
		   fileContainer.append('<span class="attachment-name"> ' + r.data.attachments[i]['name'] + ' </span>');
		
var removeAttachment = $('<a class="attachment-remove"><span class="glyphicon glyphicon-remove"></span></a>');
	 removeAttachment.click(function () {
                  fileGroupContainer.remove();
                  self.updateDocumentIDs();
                });
          fileGroupContainer.append(removeAttachment);
		}
		  /*****End of attachment part************/
		
		$(self).find('[name="name"]').val(r.data.subject);
        tinymce.activeEditor.setContent(r.data.body_from_html, {format: 'html'});
        tinymce.activeEditor.change();
	  });
      set_return(args);
    };

**Comment by jyotiraghav93** [comment]
Fixes #3925

**Comment by KaKite** [comment]
Fixes the attachment not being there however, all emails created from templates now have 2 of any attachment from the template?
