### ISSUE TITLE
Unused language strings - Part 2 (install)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3926]
See #2444 

'LBL_SYSOPTS_CONFIG'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L51

'LBL_MAKE_DIRECTORY_WRITABLE'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L55

'ERR_CHECKSYS_MYSQL_VERSION'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L67

'ERR_CHECKSYS_NO_SESSIONS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L68

'ERR_CHECKSYS_NOT_VALID_DIR'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L69

'ERR_CHECKSYS_PHP_UNSUPPORTED'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L75

'ERR_CHECKSYS_SESSION_SAVE_PATH_NOT_SET'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L80

'ERR_CHECKSYS_SESSION_SAVE_PATH_NOT_WRITABLE'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L81

'ERR_DB_ADMIN_MSSQL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L93

'ERR_DB_EXISTS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L96

'ERR_DB_LOGIN_FAILURE_MYSQL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L101

'ERR_DB_LOGIN_FAILURE_MSSQL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L102

'ERR_DB_OCI8_DB_NAME_INVALID'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L108

'ERR_DB_PASSWORD'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L109

'ERR_DB_USER'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L112

'ERR_LICENSE_MISSING'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L122

'ERR_LICENSE_NOT_FOUND'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L123

'ERROR_LICENSE_EXPIRED'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L148

'ERROR_LICENSE_EXPIRED2'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L149

'ERROR_VALIDATION_EXPIRED'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L152

'ERROR_VALIDATION_EXPIRED2'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L153

'LBL_CHECKSYS_CALL_TIME'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L161

'LBL_CONFIRM_DIRECTIONS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L194

'LBL_CONFIRM_LICENSE_TITLE'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L195

'LBL_DBCONF_HOST_PORT'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L211

'LBL_DBCONFIG_AUTO_DD'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L217

//'LBL_DBCONF_I18NFIX'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L221

'LBL_FTS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L222

'LBL_FTS_INSTALLED'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L223

'LBL_FTS_INSTALLED_ERR1'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L224

'LBL_FTS_INSTALLED_ERR2'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L225

'LBL_DBCONF_PRIV_PASS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L226

'LBL_DBCONF_PRIV_USER_2'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L227

'LBL_DBCONF_PRIV_USER_DIRECTIONS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L228

'LBL_DBCONF_PRIV_USER'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L229

'LBL_DISABLED_TITLE'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L240

'LBL_LICENSE_DIRECTIONS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L268

'LBL_LICENSE_DOWNLOAD_KEY'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L269

'LBL_LICENSE_EXPIRY'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L270

'LBL_LICENSE_NUM_USERS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L272

'LBL_LICENSE_OC_DIRECTIONS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L273

'LBL_LICENSE_OC_NUM'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L274

'LBL_LICENSE_OC'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L275

'LBL_LICENSE_TITLE'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L279

'LBL_LICENSE_USERS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L280

'LBL_PERFORM_LICENSE_SETTINGS'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L312

'LBL_STEP'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L364

'LBL_WELCOME_1'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L366

'LBL_WELCOME_2'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L367

'LBL_DBCONF_TITLE_USER_INFO_LABEL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L601

'LBL_DBCONFIG_MSG3_LABEL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L602

'LBL_DBCONFIG_MSG2_LABEL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L604

'LBL_DBCONFIG_B_MSG1_LABEL'
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L606

**Comment by Dillon-Brown** [comment]
@likhobory Haven't had time to check the rest but these strings are in use (built dynamically):

LBL_DBCONF_TITLE_USER_INFO_LABEL
LBL_DBCONFIG_MSG3_LABEL
LBL_DBCONFIG_MSG3
LBL_DBCONFIG_MSG2_LABEL
LBL_DBCONFIG_MSG2
LBL_DBCONFIG_B_MSG1_LABEL
LBL_DBCONFIG_B_MSG1

**Comment by likhobory** [comment]
@Dillon-Brown 
I wrote it as proposion, perhaps you or your colleagues will remove some strings from this list or add additional ones - the final decision should be from the developers.

**Comment by Dillon-Brown** [comment]
@likhobory :+1: Thanks for the contribution! I'll be making a single PR to address all of these issues so we can hopefully get all of your raised issues merged into the next release.
