### ISSUE TITLE
UPDATE of DEMO page

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#394]
Hello

Will it possilble to update the DEMO of SuiteCRM from 7.2.0 to 7.3.0 ???

http://demo.suiteondemand.com/index.php?module=Home&action=About

In new version of SuiteCRM are many issues, and i want (i think not only me butt all) test the functions on  new version of SuiteCRM 7.3 to be sure that same issues are in official demo too
.
Sorry for my english.

Regards Mikolaj

**Comment by willrennie** [comment]
Demo CRM updated

**Comment by Mausino** [comment]
Hi,

Today 29/8/2015 i
![demo](https://cloud.githubusercontent.com/assets/5773777/9563569/111a5c42-4e88-11e5-9d22-43eef8f23858.png)
 checked demo  page http://demo.suiteondemand.com/index.php?module=Home&action=About

and there is still version 7.2.0 and no latest version 7.3.1

Regards

Mikolaj
