### ISSUE TITLE
Html tags in the field of Status description of 'case' module

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#398]
HI,  

We fix to this issue like:

programmer did in this way

The problem with html tags is similar with this  https://suitecrm.com/forum/suitecrm-7-0-discussion/4274-html-tags-in-the-status-description-in-cases-module
![html_tags](https://cloud.githubusercontent.com/assets/5773777/9449561/8ffa6284-4aa3-11e5-93ed-9df87b9e6346.png)

They say that a solution is to disable tinymce editor in edit view

I've let the html editor in edit view as it is, but corrected description field when is shown in deatil view

for the this problem, the code changed in include/InlineEditing/inlineEditing.js is this:

if (typeof linkUrl === "undefined" ) {
                return false;
            }
            else if (linkUrl === "" ) {
                return false;
            }

so added this:

else if (linkUrl === "" ) {
                return false;
            }

Regards Miky

**Comment by shogunpol** [comment]
This looks like this fix #1935, may fix this issue.
