### ISSUE TITLE
contactlist as subpanel

### ISSUE THREAD

**Issue by burton1982** [salesagility/SuiteCRM#40]
Hi!
This is just a feature request, I would be nice If in Contacs, Accounts and Leads would be a subpanel "Contact List". This would be doing things, like connect a account with an Campagne, much easier. 
I just found a solution in German, but maybe you can build this in by default: 
http://forums.sugarcrm.com/f48/kontakte-einer-kampagne-zuordnen-und-doppelte-zuteilungen-vermeiden-58261/
http://forums.sugarcrm.com/f48/kontaktlisten-als-subpanel-bei-interessenten-kontakten-zielkontakte-einblenden-85403/#post296704

Have a nice day

**Comment by samus-aran** [comment]
Hi @burton1982  unfortunately the links are broken.

With the limited information we don't believe having a subpanel of all your related Contacts, Accounts, Leads in each of those modules would provide a great benefit to the users.  Having them segregated allows you to filter appropriately and clearly see the Account hierarchy.

Feel free to explain more and re-open but with the current information I will close this.
