### ISSUE TITLE
Alerts check caught in loop

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#400]
The alerts check periodically checks for new alerts. 
The result of this isn't checked. This means that if the users session expires this page will be loaded into the alerts div which loads the alert check which starts a chain of calls which slows down the browser.

The check shouldn't load the page if it's a login redirect. Even better would be to have a single instance of the update variable so that if the alerts javascript is accidentally loaded more than once the calls still only happen at the specified period.

**Comment by danieljsamson** [comment]
I will take a look at it.

**Comment by danieljsamson** [comment]
I added the fix into multiple alerts for 7.4.

**Comment by danieljsamson** [comment]
I have made a merge request for 7.3.2
