### ISSUE TITLE
Regex Detection Failure

### ISSUE THREAD

**Issue by ijdavie** [salesagility/SuiteCRM#402]
There is a number of different JS scripts which do not minify within SuiteCRM (using JS Groupings) . 

One that is known is sugarjs (http://sugarjs.com/). When minifying this js file, it appears to fail on a regex contained in the file. 

It may also be worth considering updating the minifier to a later version.

**Comment by Dillon-Brown** [comment]
This would be expected behaviour and wouldn't be considered a bug.
