### ISSUE TITLE
Umlaut in Contact Name gets removed in 7.9.3

### ISSUE THREAD

**Issue by rholighaus** [salesagility/SuiteCRM#4028]
When creating or editing a contact that contains an Umlaut character, that character is stripped.
#### Expected Behavior

I enter a contact with First Name: "Jürgen" Last Name: "Schmidt" and save. The record should be named "Jürgen Schmidt" and the database field first_name should contain "Jürgen".
#### Actual Behavior

The record is called "Jrgen Schmidt" and the database field first_name contains "Jrgen".
#### Possible Fix

This must have been introduced by a change from 7.9.2 to 7.9.3 - I cannot reproduce the bug on 7.9.2
#### Steps to Reproduce

1. Create a contact with an Umlaut character in the first name
2. Save
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by rholighaus** [comment]
If the first name is altered to contain the Umlaut character using MySQL client, it will be displayed correctly. If opening it in edit_view and saving, it will be stripped again.

**Comment by rholighaus** [comment]
Same issue in the Accounts module...

**Comment by rholighaus** [comment]
And cases. 

THIS IS A MAJOR PROBLEM GUYS!!!

**Comment by horus68** [comment]
I think this was already solved by version 7.9.4
see issue: https://github.com/salesagility/SuiteCRM/issues/3903

**Comment by rholighaus** [comment]
horus68 you are right - just installed 7.9.4 and the issue disappeared.
