### ISSUE TITLE
Index created for product lookup in Quotes module

### ISSUE THREAD

**Issue by rcairello** [salesagility/SuiteCRM#4030]
#### Issue
Misbehaving product lookup by name in Quotes module, due to very slow database performance when searching for products by name.

#### Expected Behavior
Product lookup should find exactly what´s been typed by the user ("product name LIKE '[typed_text]')

#### Actual Behavior
SuiteCRM / MySQL returns products that not match what the user typed in the product name field.

#### Possible Fix
The following MySQL index on [aos_products].[name] field DID SOLVE the problem:

        CREATE INDEX aos_products_idx_name
        ON aos_products (name ASC)
        COMMENT 'Improves performance during product lookup in quotes'

#### Steps to Reproduce
1. INSERT / create dummy products with similar names (our actual table has 513K records, of which 250k+ are not deleted - 'deleted = 0').

2. Create a Quote, and create a product line for it.

3. Click the "Product Name" field of the new product line, and start typing the beggining of the product name.

4. If you have several hundred records which start with the typed product name, some of the the matching ones won´t appear and, instead, you´ll get some products that DON´T match the (partially typed) product name you´re looking for.

#### Environment
* SuiteCRM Version: 7.9.x
* Browser: Chrome / Firefox (Windows andLinux)
* Environment: MySQL / Apache 
* Operating System and version: CentOS / 8GB RAM / 1TB HDD / Dedicated Physical Server

**Comment by pgorod** [comment]
Out of curiosity, how many products do you have in your database?
