### ISSUE TITLE
Module Builder editing module layout views dont work in SuiteCRM 7.9.4

### ISSUE THREAD

**Issue by jannepesonen** [salesagility/SuiteCRM#4032]
#### Issue

In Module Builder when click any module views (EditView, DetailView etc.) nothing happens.
Browser give these errors
Failed to load resource: the server responded with a status of 404 (Not Found)
/SuiteCRM/themes/SuiteP/css/studio.css.map
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
.../index.php?to_pdf=1&sugar_body_only=1&module=ModuleBuilder&MB=true&action=editLayout&view=editview&view_module=test&view_package=test

Dont know what is the problem but when copy old version 7.9.2 file from
SuiteCRM-7.9.2/modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php
and use it then it seems to work.

Well, this error still remains
Failed to load resource: the server responded with a status of 404 (Not Found)
/SuiteCRM/themes/SuiteP/css/studio.css.map

#### Your Environment

* SuiteCRM Version used: 7.9.4

**Comment by jannepesonen** [comment]
Old file is not so perfect solution,
all field names in Layout views seem to be "Modified By Name",
in Toolbox view field names is correct.
When you drag fields from toolbox to layout, deploy and go to studio where field names in layout is correct.

**Comment by Dillon-Brown** [comment]
@jannepesonen Unable to replicate on 7.9.4. Have you checked permissions?

**Comment by jannepesonen** [comment]
Dont believe its permissions issue. Install same way previous version and it works and when copy that 1 file 7.9.4 version almost works. Testing this MAMP in Mac where PHP version is 7.1.1 and CentOS where PHP version is 7.1.6.

**Comment by pgorod** [comment]
@Dillon-Brown I'm seeing this come up a lot in the forums (at least 3 or 4 people in this past week). I believe this is a real problem, although I don't know much about it... do you know of any change in the Module builder in 7.9.4? Or maybe as far back as 7.9.2 (if all the threads below are actually related)?

https://suitecrm.com/forum/suitecrm-7-0-discussion/15205-module-builder-won-t-work
https://suitecrm.com/forum/installation-upgrade-help/15157-unable-to-change-panel-to-tab-in-studio-after-upgrade-to-7-9-2
.. and more I can't find right now.

There are also a couple of people complaining about missing the assigned_to field in every module in Studio...

**Comment by fernengel** [comment]
The very same issue occurs for me.
MAMP on Windows 10. SuiteCRM Version 7.9.4 (Sugar Version 6.5.24 (Build 509)).
Fresh MAMP and SuiteCRM install, no fancy adjustments...

When clicking on any layout of any custom module in Module Builder then Chrome reports:
POST http://localhost/index.php?to_pdf=1&sugar_body_only=1&module=ModuleBuilder&…=editLayout&view=editview&view_module=Vertraege&view_package=Vertragliches 500 (Internal Server Error)

Then no more clicks are recognized within the Module Builder (e.g. trying to go to Fields)...I have to go back to Admin->Module Builder.

The issue also occurs for Firefox, but it doesn't report any errors in its console. It just doesn't work anymore like described above.

Thanks!

**Comment by pgorod** [comment]
Ok, I think I got this one nailed...

I can reproduce this bug in my 7.9.4. The error in the logs is this

```
[26-Jul-2017 13:00:17 Europe/Lisbon] PHP Fatal error:  Declaration of UndeployedMetaDataImplementation::getFileName($view, $moduleName, $packageName, $type = MB_BASEMETADATALOCATION) must be compatible with AbstractMetaDataImplementation::getFileName($view, $moduleName, $type = MB_CUSTOMMETADATALOCATION) in /var/www/html/modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php on line 49
``` 
The PR that changed this 23 days ago is #3685, specifically this commit https://github.com/salesagility/SuiteCRM/pull/3685/commits/0f2258314198062dfd6fc4f04a01c95668206c46

It adds a parameter `packageName` to the function in class `UndeployedMetaDataImplementation`, and amends a few things to match that change, but not the base class which this class extends, `AbstractMetaDataImplementation`.

So I made a PR #4047 to add that change there and tested accessing the layouts (they now work!), but please check whether this has any other implications that I might be missing. I am doing this without really understanding these classes and functions, and with limited PHP expertise...

**Comment by daniel-samson** [comment]
Can you please test my pull request #3918 ? - as this also fixes your issue.

**Comment by jannepesonen** [comment]
Yes #3918 seems to fix my Module Builder problem.
Still Safari show this 404 (Not Found) error ...studio.css.map.
But it seems to work anyway.

Thanks!

**Comment by cumanacr** [comment]
I tested @daniel-samson PR #3918 and it fixed the 500 (Internal Server Error) on Module Builder when I tried to edit any layout view on a SuiteCRM 7.9.4 instance

**Comment by sanchezfauste** [comment]
We have tested #4097 and it fixes this problem.
