### ISSUE TITLE
Upgrade on 7.9.4  Content in emails are same in body for all emails

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4035]
#### Issue

I tested it on official SuiteCMR 7.9.4.. we upgraded from version 7.9.2 to latest ... maybe has something with this issue #4033 but if email is not imported the sender,recipient, + other data are correct but the content in body isn't.

But if you IMPORT the email.. the body is showing correct, but the Subject,date sent, recipient + sender  fields are empty !!! 
![test3](https://user-images.githubusercontent.com/5773777/28518852-be485a0e-7069-11e7-9ca9-d9c73e8de6c8.png)

Problem is when i created personal (the group was not possible to test in official demo) and it shows me all emails.. but when i open email.. body is same for all emails...  

Same issue on our company SuiteCRM 7.9.4.. 

![test1](https://user-images.githubusercontent.com/5773777/28518435-28e39588-7068-11e7-8d34-a342f0fe4386.png)

![test2](https://user-images.githubusercontent.com/5773777/28518440-2c780396-7068-11e7-955d-6620e402731c.png)

It mega important for us to fix it.. because the emails are not usable in SuiteCRM

#### Expected Behavior

Should show for every email its content in body + for imported emails recipient, sender, subject + date sent information's

#### Actual Behavior

Email are not usable for this moment!

#### Steps to Reproduce

1. Create email account
2. Go to listview of emails
3. Open one or more emails

#### Your Environment

* SuiteCRM Version used: Official SuiteCRM 7.9.4
* Browser name and version : Chrome 56.x 64bit

**Comment by Dillon-Brown** [comment]
Hi @Mausino, there is a fix for this here #4009 let me know if this solves the issue on your end.

**Comment by Mausino** [comment]
@Dillon-Brown i applied this fix.. isn't working no imported emials (the body content) also isn't working for imported emails (the recipient, sender, subject, date sent).. i did not test for archived emails

**Comment by Dillon-Brown** [comment]
@Mausino Have you tried repair/rebuild and clearing cache?

**Comment by Mausino** [comment]
@Dillon-Brown i tested on edge + chrome and it's working 👍 only for imported emails still did not show the sender name
![test4](https://user-images.githubusercontent.com/5773777/28520192-cec4f536-706e-11e7-9c24-08f2388dc831.png)

**Comment by Dillon-Brown** [comment]
:+1: We'll address the sender name in #4033. Thanks for testing.

**Comment by scm1599** [comment]
Is there any news on this topic? I'm experiencing this severe Issue in v7.4.9.

Is there going to be a patch or will it be solved in the next release? By when is the next version going to be released?

**Comment by anjo03** [comment]
I have the same problem, and have tried QRR and manually clear the cache folder with rm -rf. Still the body of the first email being showed is "hanging"... Help!!

**Comment by scm1599** [comment]
Let us summarize;
The issue occurred first in 7.9.3

July 19, 2017: Bug opened
https://github.com/salesagility/SuiteCRM/issues/3919
High Priority, Resolved: Next Release

July 20, 2017: New release: 7.9.4
Bug not resolved

July 23, 2017: Same Bug opened under new number
https://github.com/salesagility/SuiteCRM/issues/4033
High Priority, Resolved: Next Release

Bottom line: The bug is addressed. We have to wait for the next release.

Big question: By when can we expect the next release?

**Comment by Mausino** [comment]
@pgorod we upgraded from 7.10.4 tp 7.10.6 and issue again persisting

In all emails no imported emails are same body as in first opened emails... did you saw some activity on forum ?? because i searched and didn't find nobody that complain in latest version

only it was issue reported, but was closed #5811

**Comment by pgorod** [comment]
@Mausino I admit I am currently confused about Email issues, but I don't thibk I've seen this in the forums recently, no.

Maybe @Dillon-Brown wants to reopen this if he can reproduce? Or should it be a new issue?

**Comment by Mausino** [comment]
@pgorod @PedroErnst  i checked the master branch and there is same issue as was fixed by https://github.com/salesagility/SuiteCRM/pull/4009/files

<span class="sugar_field" id="{{if empty($displayParams.idName)}}{{sugarvar key='name'}}{{else}}{{$displayParams.idName}}{{/if}}">{{$vardef.value}}</span>

**Comment by Dillon-Brown** [comment]
Hi guys, I've created a temporary fix here: #6021 if you need this resolved but i'll be looking at creating a proper more long-term fix with some acceptance testing so we don't come across this again.
