### ISSUE TITLE
AOW conditions now() does not trigger (but today does). 

### ISSUE THREAD

**Issue by VRedguard** [salesagility/SuiteCRM#4038]
If i put any AOW with Date equals NOW, and with a proc on scheduler, when it arrives on time, the AOW does not kick in. (does not process, nothing in audit, does not trigger, etc.)

Done. I Have only found AOW on change that would not trigger. 

#### Issue

Because it is something that does not work and should be working.

#### Expected Behavior

Kicks in.

#### Actual Behavior

Does not kick in.

#### Steps to Reproduce

1. Already included up to
2.
3.
4.

#### Context

I'd say medium to high. I use AOW a lot (and is one of the main reasons i have chosen SuiteCRM). 

#### Your Environment

* SuiteCRM Version used: 7.8.5 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1 mariadb
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by ChangezKhan** [comment]
Will need more details like, the AOW record details with screenshots if possible. Kindly provide that.

**Comment by VRedguard** [comment]
![capture d ecran 2017-07-26 a 08 39 13](https://user-images.githubusercontent.com/23078474/28621176-145d7198-71de-11e7-9fdd-c5d7d19fb0e7.png)
![capture d ecran 2017-07-26 a 08 38 49](https://user-images.githubusercontent.com/23078474/28621182-195697ec-71de-11e7-9a3d-90f5cb528b44.png)

[crm_07_24_17_DEBUG MODE.pdf](https://github.com/salesagility/SuiteCRM/files/1176558/crm_07_24_17_DEBUG.MODE.pdf)

**Comment by gunnicom** [comment]
I think for date fields "NOW" makes no sense. Only "TODAY" is correct. Now would give you a value like "2017-07-26 17:13:34", Today would be "2017-07-26" and the date would have the format "2017-07-26"
So "2017-07-26" == "2017-07-26" but "2017-07-26" != "2017-07-26 17:13:34"
This is just a quick guess.

**Comment by VRedguard** [comment]
Yes but a due date on a task has both a date and a time. I need this to work as well when a ticket is 2 hours old without being processed for example. There must a way to make an AOW with time, even more when an AOBH was created and allows you to do +2 business hours.

**Comment by VRedguard** [comment]
@Dillon-Brown @ChangezKhan data was provided.

**Comment by adriangibanelbtactic** [comment]
@VRedguard :  Please check issue: https://github.com/salesagility/SuiteCRM/issues/4043 and and pull request: https://github.com/salesagility/SuiteCRM/pull/4045 which should solve your issue.

Feedback on the original bug or pull request is welcome.

**Comment by VRedguard** [comment]
@adriangibanelbtactic I will be testing it thanks. If I do use AOBH, any clue how to modify the lines as well ?

**Comment by Dillon-Brown** [comment]
Closing in favour of #4043.
