### ISSUE TITLE
Unbale to assign a role in user management

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#4039]
#### Issue
Selecting a role from the bottom of user management does not add the role to the user.

#### Expected Behavior
The role should appear in the users role list

#### Actual Behavior
Nothing happens

#### Steps to Reproduce
1. Admin - User Management - Select a user
2. Expand Roles at bottom
3. Press Select button
4. Select a role from the list

#### Context
I was trying to assign a user to a role
Workaround is to open Roles and assign the user from there

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox / Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.X
* Operating System and version (e.g Ubuntu 16.04): Windows

**Comment by Dillon-Brown** [comment]
@davidyounger I'm unable to replicate on 7.9.4. Have you checked permissions / repair rebuild?

**Comment by Dillon-Brown** [comment]
Closed due to inability to replicate / inactivity.
