### ISSUE TITLE
'send Quote by Email' may send to wrong address

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#4053]
#### Steps to Reproduce
1. Select `Send Quote by Email` from a Quote
2. The system puts the contact assigned to the quote in the `To:`  field
3. Remove this address and put another one
4. Hit `Send`, and it will send the email to the original contact.

#### Context
Causes grief by sending email to a person whom you had just decided you should NOT be sending.

#### Your Environment
* SuiteCRM Version used: 7.9.4

**Comment by Dillon-Brown** [comment]
From what I can tell this issue seems to be larger than just sending quotes. The "Reply", "Reply All" and "Foward" appear to also send to the wrong address. The included PR should also fix this.
