### ISSUE TITLE
SuiteCRM crashing JSON ?? 

### ISSUE THREAD

**Issue by VRedguard** [salesagility/SuiteCRM#4054]
Notice: Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' occurred in /var/www/html/include/utils.php on line 3913 [2017-07-26 14:53:00] display_stack_trace caller, file: /var/www/html/include/utils.php line#: 3413
/var/www/html/include/utils.php[L:3913](:StackTraceErrorHandler)
/var/www/html/modules/SavedSearch/SavedSearch.php[L:108](:getJSONobj)
/var/www/html/include/SearchForm/SearchForm2.php[L:488](SavedSearch:getForm)
/var/www/html/include/SearchForm/SearchForm2.php[L:236](SearchForm:displaySavedSearch)
/var/www/html/include/MVC/View/views/view.list.php[L:273](SearchForm:display)
/var/www/html/include/MVC/View/views/view.list.php[L:189](ViewList:processSearchForm)
/var/www/html/include/MVC/View/views/view.list.php[L:290](ViewList:listViewProcess)
/var/www/html/include/MVC/View/SugarView.php[L:169](ViewList:display)
/var/www/html/include/MVC/Controller/SugarController.php[L:363](SugarView:process)
/var/www/html/include/MVC/Controller/SugarController.php[L:310](SugarController:processView)
/var/www/html/include/MVC/SugarApplication.php[L:105](SugarController:execute)
/var/www/html/index.php[L:52](SugarApplication:execute)
Notice: A non well formed numeric value encountered occurred in /var/www/html/include/ListView/ListViewSmarty.php on line 100 [2017-07-26 14:53:00] display_stack_trace caller, file: /var/www/html/include/utils.php line#: 3413

**Comment by VRedguard** [comment]
<img width="1222" alt="capture d ecran 2017-07-26 a 14 59 42" src="https://user-images.githubusercontent.com/23078474/28638520-192d9970-7213-11e7-807d-1a15a2a63012.png">

**Comment by pgorod** [comment]
@VRedguard why didn't you fill the entire Template for this Issue? Are we supposed to guess your SuiteCRM version, your PHP version, and what steps we should use to reproduce the problem, etc?

**Comment by VRedguard** [comment]
@pgorod  Because I work in a company relying on SuiteCRM with deals in millions yearly, and the system crashed for no reason, I was in a hurry and expected that someone might know quickly how to fix this, because it might have actually encountered it bfore. 

I have pulled back a backup of the files and everything work.

Thank you still for your understanding, empathy and how you address customers.
