### ISSUE TITLE
Creating Case from A contact record's subpanel doesn't send Automatic Email

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#406]
https://suitecrm.com/forum/suitecrm-7-0-discussion/6136-case-creation-auto-email
Creating a case and linking a Contact on the Case Record sends an Email.
Creating a case from the Contact's Record itself does not.

**Comment by darthtang** [comment]
This bug will persist if you create any case via a subpanel. 

Where i can see where the code fails, which ultimately will lead the system not to send an email is on line 366 in caseUpdatesHook.php

if($arguments['module'] != "Cases" || $arguments['related_module'] != "Contacts"){
            return;
        }

**Comment by darthtang** [comment]
removing line 369

if(!$bean->fetched_row){
         //   return;
        }

will allow for the email to be sent. However, testing must be made to make sure that this does not affect other parts of the system from i.e normal case creations, joomla portal case creations, check if accounts case quick create is functional etc etc.

**Comment by darthtang** [comment]
Should functionality be allowed where if a case is created from an Account. Should the account primary address be targeted for the email or the contacts within the Account? or neither? Code in the logic hook filters out only everything out apart from module related to contacts

**Comment by AlexNirW** [comment]
Hi darthtang,

in the AOP_Case_Updates/CaseUpdatesHook.php file, I tried to remove these lines
if(!$bean->fetched_row){
// return;
}
(which are 281 to 283 for me) 

A mail is now sent when I create a case from a contact but it's an empty mail. I also try to only comment the ligne "return" 
I'd like to have a mail sent when a ticket is created from a contact (not an account)

Regards,

Alex
