### ISSUE TITLE
Notes assigned to record (Case, Contact, Lead, Account, Target) will possible add as attachments into email when you're composing email 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4065]
#### Issue

We're suggesting, if has any record like Contact, Case, Account, Target, Lead some note assigned to it, will great if you are composing email or by relate to in compose view of email.. will possible fetch the notes assigned to record and will possible choose which i want add into email.

Now when you save any document like invoice under record, for example Contact.. you must first download this file into your computer and after add as attachment into emails.

This process also help better use the phone / tablet devices for working with emails.

Maybe when will @salesagility look on solution for issue #4050 will good think on this suggestion Nr.4065

#### Expected Behavior

I should choose which note assigned to record i will add to email as attachment.

#### Actual Behavior

You must first download file from note and after add as attachment into email

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notes assigned to record (Case, Contact, Lead, Account, Target) will possible add as attachments into email when you're composing email](https://trello.com/c/QqZ4z8p9/215-notes-assigned-to-record-case-contact-lead-account-target-will-possible-add-as-attachments-into-email-when-youre-composing-email)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@pgorod is possible in some way to vote for suggestion which community consider as best ???? in some mechanism where we can rate for suggestions ?

**Comment by pgorod** [comment]
On Trello there is a vote system. I just voted for this suggestion there :-)

However I wouldn't get my hopes up, I don't think anybody is keeping up with those vote counts. Anyway, the Trello site is not very frequented by the Community, so it wouldn't be very representative.

Occasionally there are Forum threads asking for suggestions or opinions, and there are Forum polls... but other than that...
