### ISSUE TITLE
Issue with Reports when using range filters (above and bellow) breaks pagination

### ISSUE THREAD

**Issue by mauriciocardenas** [salesagility/SuiteCRM#4069]
This happens in version 7.7.7 and the last version in the online demo site
#### Issue

Create a report and set amount as filter amounts above 25000 and bellow 50000 this breaks pagination. If I use just one filer the pagination works but the amount values are wrong.
#### Expected Behavior

To work with range filters not only for amount but for dates and all kind of information in a field.
#### Actual Behavior

The pagination breaks, and when it just use one filter the value is incorrect
#### Possible Fix

The most soonest version please this is critical for any company, even if I'm considering buy a subscription to be a pay user.
#### Steps to Reproduce

1. Create report 
2. Set filter of amount with above and bellow options and set a number as pibot 
3. Test the report
4. Do the same for just one filter of above or bellow

#### Context
 gigantly
 high

#### Your Environment
 lamp server
* SuiteCRM Version used: version 7.7.7 but it replicates in the last version 7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): google chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.3
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by Dillon-Brown** [comment]
@mauriciocardenas I'm unable to replicate this. Can you perhaps take a screenshot of the issue?

**Comment by mauriciocardenas** [comment]
Hello Dillon,

I have a video of this issue reproduced in SuiteCRM Demo Site.
https://drive.google.com/drive/folders/0B8axItbSu8rUOENvZFc2U3JUMVk?usp=sharing

Please let me know if you require additional information.

Best regards

**Comment by Dillon-Brown** [comment]
@mauriciocardenas Confirmed as a bug. Thanks for the help 👍

**Comment by mauriciocardenas** [comment]
Hello @Dillon-Brown,

Do I have to update in my server instance this modifications of the Template or this notifications are juts part of the fixing process. I'm a little confused.

Thanks

**Comment by Dillon-Brown** [comment]
Hi @mauriciocardenas. Those notifications are unrelated to your issue. The commit should have read #4096 but got accidentally linked to your issue #4069 due to a typo.
