### ISSUE TITLE
studio:not able to access

### ISSUE THREAD

**Issue by dvkesarwani** [salesagility/SuiteCRM#4073]
After Upgrading to suitecrm 7.9.4, i m not able to access studio from admin.

* SuiteCRM Version used:  7.9.4
* Browser name and version: All browsers
* Environment name and version : MySQL, PHP 7
* Operating System and version:Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Hi @dvkesarwani, I'm unable to replicate this on 7.9.4. If you receive more information or another member of the community can replicate. Please re-open the issue. Thanks.

For now we feel your question would be more suited to the [Community Forums](https://suitecrm.com/forum) someone will be able to help you with your issue there.
