### ISSUE TITLE
7.9.4 Unable to delete users due to missing "Delete" button

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4076]
#### Issue

Occasionally I am unable to delete a user from admin->user management->user detail-view due to a missing "Delete" button. First raised on the [Forums](https://suitecrm.com/forum/suitecrm-7-0-discussion/15324-deleting-a-user#51574).

#### Expected Behavior

The delete button should be available in detail-view bulk action drop-down.

#### Actual Behavior

Delete button is correctly missing from list-view but is also missing from detail-view bulk action drop-down.

#### Possible Fix

Possibly related to caching issues.

#### Steps to Reproduce

1. Go into admin panel.
2. Click user management.
3. Enter a users detail-view.
4. Actions menu "Delete" is missing.

#### Context

High priority

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Iwan2323** [comment]
Hi Dillon-Brown

![usr](https://user-images.githubusercontent.com/29030451/30056647-ad510348-925d-11e7-9fd4-433d3e7a5164.png)

there is no action for delete

**Comment by interbiznw** [comment]
any fix?

**Comment by Dillon-Brown** [comment]
Hi @Iwan2323, the "Mass Update" -> "Delete" option has been intentionally removed for security reasons. The "Delete" button, when not encountering this issue can be found by clicking on a user and entering the detail-view.

![screenshot 126](https://user-images.githubusercontent.com/26431166/30464159-c61df842-99c7-11e7-8873-2c4d2e841c51.png)

**Comment by Dillon-Brown** [comment]
@interbiznw Will need to a bit more investigation. This bug seems quite sporadic and can usually be removed by resetting permissions, clearing browser cache, and doing a repair/rebuild. As a workaround you should be to use the delete button in the employees module:

![screenshot 127](https://user-images.githubusercontent.com/26431166/30464210-173370e0-99c8-11e7-9b81-4a5a9358a70a.png)

**Comment by interbiznw** [comment]
This is happening to me on a fresh install

⁣Thanks, 
Jamie Owens 
Interbiznw.com ​

**Comment by Dillon-Brown** [comment]
This should be resolved by #4302. Closing this in favour of #4301.
