### ISSUE TITLE
Campaign mail are not sending automatically

### ISSUE THREAD

**Issue by Mma2s** [salesagility/SuiteCRM#4078]
Hi all,

I have some problems with the campaign emails. They are not sending automatically, I have to send via in the email queue. Also the send test mail function is not working. The mails are not trying to be send, and the Scheduler hasn't made a successful run yet.

I have set up my cron job as following: *    *    *    *    *     cd /Applications/MAMP/htdocs/SuiteCRM-7.9.2; php -f cron.php > /dev/null 2>&1  this was the cron settings given at scheduled tasks. 

I hope that some one could help me. that would be great!

I'm working with a Mac and with Mamp.

Thanks!

**Comment by boombata** [comment]
Hi, 

please make sure to run the cron from www-data
crontab -u www-data -e

https://github.com/salesagility/SuiteCRM/issues/2787
https://www.suitecrm.com/forum/installation-upgrade-help/12488-problem-with-permissions-before-upgrade

Regards,
BM

**Comment by Mma2s** [comment]
It gives me the following message: crontab: must be privileged to use -u

**Comment by boombata** [comment]
try : 
sudo crontab -u www-data -e

**Comment by Mma2s** [comment]
Then I get this: crontab: user `www-data' unknown

**Comment by Mma2s** [comment]
I have to say I'm not really formilaire with Linux

**Comment by boombata** [comment]
www-data user must be different on macs.
try :
sudo crontab -u _www -e

**Comment by Mma2s** [comment]
Now I can put a new cronjob hope that it works! thanks a lot for the help!

**Comment by Mma2s** [comment]
Hmm it's still not functioning

**Comment by horus68** [comment]
@Mma2s  I think this type of support (related with your own install) needs to be posted in Forum https://suitecrm.com/forum/index
Only after your problem is confirmed as an application problem you will create an Issue here. This will reduce the number of open issues on github.

Github is for testing solutions for problems with the application.
Help for own/specific installs should be posted via forum. 

So please create a forum post, link it here and close the issue.

**Comment by Mma2s** [comment]
Hi horus68,

I made an post on the forum, but no one responded there. So I tried it here.

**Comment by horus68** [comment]
if every post on forum without replies would ended here... this would be a bad forum!

Note: there are systems with statistics on github open issues and time taken to close them as a validation for software. So please close it (not that Salesagility has any good numbers on it!)

**Comment by horus68** [comment]
@Mma2s can you post the link to your forum topic?

**Comment by Dillon-Brown** [comment]
@horus68 I believe this is it here: https://suitecrm.com/forum/suitecrm-7-0-discussion/15335-campaign-mail-are-not-sending-automatically
