### ISSUE TITLE
Option "contains" not available in MultiSelect Field

### ISSUE THREAD

**Issue by fgiehlede** [salesagility/SuiteCRM#4084]
#### Issue
A user is not able to select the option "contains" in a multi select field in a report. The search condition is very complicated to use, when we want to search different values in this field.

#### Expected Behavior
It should be able to use "contains" for a multiselect field

#### Actual Behavior
We are not able to use "contains" as operator for a multiselect field in the report module

#### Steps to Reproduce
1) We have a multi select field with 3 options: A, B and C

2) We are now searching accounts with option B.

3) We must select any combination of A, B and C to find every account with the option B. Because we have only the option to search "value" for a multiselect field.

#### Context
-

#### Your Environment
SuiteCRM 7.8.3

**Comment by lazka** [comment]
I've created #6811 which allows "equal to +  one of" which translates to "contains at least one of the selected values". "not equal + one of" translates to "does not contain any of the selected values".
