### ISSUE TITLE
Save a call or task, etc... ends up sometimes in a blank page and no record.

### ISSUE THREAD

**Issue by zicrob** [salesagility/SuiteCRM#4087]
#### Issue

It happens about 3 times amongst 5
#### Expected Behavior

recording the task or so and display the next page
#### Actual Behavior

Nothing getsq recording and a blank page
#### Steps to Reproduce

Sounds unpredictable. Thought it was records done before update, but not.
1.The step is to try to save a modified record. Not a brand new 
2.
3.
4.

#### Context

I have to delete the bugging record and create another one, then modifying it with the midification

I'd say medium as there is a turn around, even if this is not handy.
#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 54.0.1 x64
* Environment name and version (e.g. MySQL, PHP 7):  
libmysql - 5.1.73 (Extension PHP : mysqli )
MySQL 5.5.51-38.2
PHPmyadmin 4.7.3.
Version Apache | 2.2.29
PHP | 5.6.30
* Operating System and version (e.g Ubuntu 16.04):
Linux  Version du noyau | 3.10.0-614.10.2.lve1.4.50.el6h.x86_64

**Comment by Dillon-Brown** [comment]
@zicrob I'm unable to replicate. Is this something you can replicate on the demo or just your instance?
https://suitecrm.com/demo

**Comment by zicrob** [comment]
Well, the demo is 7.9.3, not 7.9.4. This is not something I can replicate. It looks like it happens at random. I tried several test, to see if french characters are cause, but it is not the case. I can't find out what cause this.

**Comment by Dillon-Brown** [comment]
Closing this due to being unable to replicate this as a core issue. Please re-open if you learn more information. Thanks.
