### ISSUE TITLE
Home page breaks when adding a custom module dashlet

### ISSUE THREAD

**Issue by crmwa-marjhun** [salesagility/SuiteCRM#4089]
#### Issue

When I tried adding a custom module dashlet at home page, home becomes broken and i'm getting 500 error in console log
#### Expected Behavior

Adding custom module should not cause any issue
#### Actual Behavior

Home page breaks when adding custom module dashlet
#### Steps to Reproduce

1. Create a module via module builder and deploy
2. Go to homepage then create a dashlet using your newly deployed module

#### Context

It is crucial for as to track the progress/state of our items. 
Dashlets are commonly used on daily basis

#### Your Environment

* SuiteCRM Version used: Version 7.8.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome - Version 60.0.3112.90 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):  MySQL 5.7, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Amazon Linux AMI release 2017.03

**Comment by Dillon-Brown** [comment]
Hi @crmwa-marjhun, there is already a fix for this here: https://github.com/salesagility/SuiteCRM/pull/3836

**Comment by crmwa-marjhun** [comment]
Thanks! @Dillon-Brown
