### ISSUE TITLE
Wrong server name in link

### ISSUE THREAD

**Issue by zden2k** [salesagility/SuiteCRM#4091]
#### Issue
Hello, our instance of Suitecrm has problem, when a employee move up order they receives email: 'You may review this Quotes at: 
http://_/index.php?module=AOS_Invoices&action=DetailView&record=ee07441a-4335-82b8-c47d-59847f216112
Link has wrong server name with underscore.

#### Expected Behavior
Link should looks like http://<server_name>/index.php

#### Your Environment
Suitecrm 7.8.3.
Mysql 5.5.53-0
PHP 5.6.29
Ubuntu 16.04

**Comment by zden2k** [comment]
Sorry my fault, bad server siteurl variable filled in config.php. Fixed.

**Comment by daniel-samson** [comment]
@zden2k  Can you please close this issue?
