### ISSUE TITLE
Workflows - can we have a 'module' filter?

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#4093]
This is an enhancement request: I think the most important filter field in workflows is: "module"
We currently have 67 workflows implemented ad not being able to filter by module is making it a bit difficult to manage.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Workflows - can we have a 'module' filter?](https://trello.com/c/2IUEA7Xe/212-workflows-can-we-have-a-module-filter)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
