### ISSUE TITLE
Email compose pop up - 7.9.x - missing possibility for signature

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4095]
#### Issue

In old email system 7.8.x.. when you composed email, you were able to change signature, add signature into body when you wrote email.

Now it is not possible add signature by yourself in compose window... 

and as reported in #4075 when you have by default signature.. still after you use the template, it will overwrite your signature... 

#### Expected Behavior

User can manage its signatures.. could add it on reply to or forward action.. 

#### Steps to Reproduce

1. Go to email module
2. Compose email 
3. In pop up window you can't find  the signature section as was in 7.8.x

#### Your Environment

* SuiteCRM Version used: Official SuiteCRM 7.8.4

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email compose pop up - 7.9.x - missing possibility for signature](https://trello.com/c/jIrweKn3/213-email-compose-pop-up-79x-missing-possibility-for-signature)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
