### ISSUE TITLE
Colorpicker is not saving the value for Button color

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#410]
When i press Save after adding the color code, the value returns FFFFFF

![suitecrm_buttons](https://cloud.githubusercontent.com/assets/1594411/9507704/4926f896-4c50-11e5-85c0-b54fac4e8cbe.PNG)

**Comment by darthtang** [comment]
Hi @ghermans.

I am trying to reproduce the bug but i am unable to do so. 
I manually enter a hex colour into a text box and the hex value is the value expect!

If you could say what hex value you put in and where you put it would be great! :)

cheers!

Darren

**Comment by ghermans** [comment]
@darthtang thanks for investigating this bug.

When i enter button colour: 226FBC the value goes back to FFFFFF after saving it

**Comment by ghermans** [comment]
@darthtang 
![screenshot from 2015-08-27 16 28 02](https://cloud.githubusercontent.com/assets/1594411/9523155/e93cde80-4cd8-11e5-8b81-870b9acc15c5.png)
![screenshot from 2015-08-27 16 30 05](https://cloud.githubusercontent.com/assets/1594411/9523166/ee6f3272-4cd8-11e5-84da-16ba69fc1819.png)

**Comment by ghermans** [comment]
I also checked the config_override file 

The value for the button is $sugar_config['theme_settings']['SuiteR']['button'] = 'Save';
After replacing the value manually in the config_override file to 226FBC it works.

**Comment by darthtang** [comment]
I have found other bugs as well as your bug while messing around within this module. I will make fixing the bugs i find and your bug my priority for the time being.

Regards 

Darren

**Comment by darthtang** [comment]
@ghermans 
A fix has been made and a pull request made onto the latest hotfix! Thanks for the bug find :+1:

**Comment by ghermans** [comment]
Your fix has been tested and i can confirm that the issue is fixed
