### ISSUE TITLE
Sorting of fields in condition list

### ISSUE THREAD

**Issue by apoonawa** [salesagility/SuiteCRM#4107]
When creating a condition in the workflow module, fields are listed in no particular order. This makes it very difficult to find the field you are looking for. Specially when you have a lot of fields.
I have also proposed a fix for this issue below.

#### Issue

In Workflow Edit View, Field dropdown is not in alphabetical order.
#### Expected Behavior

Should be in alphabetical order
#### Actual Behavior

Field drop down is in some random order.
#### Possible Fix

Pull request included below.

#### Steps to Reproduce

1.Create New workflow
2.select module, Add a condition, 
3.Click on dropdown to select a Field.
4. Field dropdown is not in alphabetical order.

#### Context

It is very time consuming to find the correct field you need.

Medium Priority. This improves efficiency for users and limits mistakes.

#### Your Environment

* SuiteCRM Version used: 7.9.3 (this issue is in previous versions too)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sorting of fields in condition list](https://trello.com/c/iX811o11/217-sorting-of-fields-in-condition-list)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
