### ISSUE TITLE
Leads Primary Address Street form object field State not saving

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#411]
The Leads edit view field Primary Address Street displays a bunch of fields including State.
Works fine if I do not add the Primary Address state as an additional field on the form.
If however, I do add Primary Address State as an additional field, editing the state in the Primary Address Street object does not save the state.
Editing the Primary Address State directly does save the state.
I am guessing Suite is getting confused because there are 2 state objects on the form.

7.3.1
Windows
Apache

**Comment by willrennie** [comment]
You should simply add the 'Street' field to the edit and detail views, as this will add the address block. The fields are simply there as individual entities for the data to be saved in the database and for anyone who wishes to customise and grab those values, but there is code that triggers the address block when the street field is added to the view. I do not see this as a bug.
