### ISSUE TITLE
XSS problem in ajaxUI.js

### ISSUE THREAD

**Issue by jussirajaniemi** [salesagility/SuiteCRM#4112]
#### Issue

Login to demo service and open URL:
https://demo.suiteondemand.com/index.php?action=ajaxui&LicState=check#ajaxUILoc=javascript:alert(1)

#### Expected Behavior

Browser open JS alert which show number 1.

**Comment by Dillon-Brown** [comment]
Hi @jussirajaniemi. Please raise all security issues through security@suitecrm.com. Thanks.
