### ISSUE TITLE
Newsletter Campaigns: Chose which suppression list is populated upon recipient's unsubscribe action.

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#4113]
#### Feature Request

I'd like to be able to: 
- add multiple suppression lists to a newsletter campaign.
- choose which suppression list is populated upon the email recipient clicking on the unsubscribe link

(optional: allow for multiple suppression lists to be populated with the same users at the same time)

This would allow for much greater flexibility for more complex mass email campaigns.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Newsletter Campaigns: Chose which suppression list is populated upon recipient's unsubscribe action](https://trello.com/c/mJgGwnO0/218-newsletter-campaigns-chose-which-suppression-list-is-populated-upon-recipients-unsubscribe-action)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
