### ISSUE TITLE
Convert Lead: update campaign history and target list relationships

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#4114]
#### Feature Request

Currently there is an admin setting "Lead Conversion Options" that allows for copying or moving a Lead's related activities to its new Contact record upon Lead conversion.

I really miss the same thing to happen for:

- Campaign History
- Target List relationship.

i.e. if the "Lead Conversion Options" is set to "move", I'd expect SuiteCRM to also move the Campaign history to the new contact and (more importantly) to remove the lead from all target lists and instead add the new contact to the target lists the lead was previously part of.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Convert Lead: update campaign history and target list relationships](https://trello.com/c/fVLsk3c0/219-convert-lead-update-campaign-history-and-target-list-relationships)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
