### ISSUE TITLE
Placename/State lookup by postal code

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#4115]
#### Feature request

I just came across geonames.org, a free webservice with a whole range of APIs for geolocation stuff. I'd love to see the worldwide postal code lookup integrated into SuiteCRM! Example javascript code here:
http://www.geonames.org/export/ajax-postalcode-autocomplete.html

That way you could just enter a postalcode (from anywhere in the world) and the user would see the options available.
Of course it would be nice to be able to tweak it admin settings, i.e.:
- user name used for geonames.org (after registration on their site)
- possibly Narrowing down the countries to search in. Sometimes you might only need it for addresses in specific countries.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Placename/State lookup by postal code](https://trello.com/c/FAN0S20q/220-placename-state-lookup-by-postal-code)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
