### ISSUE TITLE
Email Not Working 7.9.4

### ISSUE THREAD

**Issue by mcmm1001** [salesagility/SuiteCRM#4117]
I have configured the outbound and inbound Email correctly and sent a Test email correctly. However whenever I compose a new email or even click on a contacts email address to send an email I get the following error message.

Error Sending Email. Please contact your administrator for assistance.

#### Expected Behavior
Send the Emails

**Comment by Dillon-Brown** [comment]
Hi @mcmm1001 This question may be more suited to the [url=https://www.suitecrm.com/forum/suite-forum]Community Forum[/url].

Unless you can provide more information I will be unable to replicate this issue.
