### ISSUE TITLE
TextArea fields scaling issue

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4125]
#### Issue

TextArea fields can be stretched off the page and under other fields

![field_scaling](https://user-images.githubusercontent.com/26431166/29407157-69b7b680-833b-11e7-9910-c41825d5080e.png)

#### Expected Behavior

Field should scale correctly

#### Steps to Reproduce

1. Adjust the size of a TexArea field 

#### Context

Low priority

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Kevconry** [comment]
Not able to replicate in 7.13.2
When trying to extend the text box, it only extends vertically and not horizontally
please re-raise or get in touch if you are still having this issue

**Comment by chris001** [comment]
This CSS fix from 2017 changed the `max-width` from `100%` to some fixed values, for example  `446px`, which broke "responsive layout".  It should be rewritten.
