### ISSUE TITLE
7.9.4 Email Display Name Doesn't Appear for Recipient

### ISSUE THREAD

**Issue by Garridus** [salesagility/SuiteCRM#4133]
When sending email from 7.9.4 the Display name does not display for the recipient of the email

#### Issue

When sending email from 7.9.4 the Display name does not display for the recipient of the email, e.g. When sending a message from Charlie Woodbridge <cwoodbridge@mail.com>, the recipient only see cwoodbridge@mail.com in from data.

From: <cwoodbridge@mail.com>
X-Google-Original-From: <cwoodbridge@mail.com>

However, if you send a test message from suitecrm, the display name is displayed for the recipient as per normal practice, e.g. when sending test message the recipient sees  in the From field.

From: SuiteCRM <cwoodbridge@mail.com>
X-Google-Original-From: SuiteCRM <cwoodbridge@mail.com>

Temporary solution
Change line 2718 in /var/www/html/modules/Emails/Email.php
$mail->FromName = $current_user->getPreference('mail_fromname');
for
$mail->FromName = 'your name'; //$current_user->getPreference('mail_fromname');

#### Expected Behavior

 display for the recipient of the email
#### Actual Behavior

not  display the recipient of the email
## Steps to Reproduce

1. Compose Email
2. Send Mail 
3.
4.

#### Context

HIGH priority
#### Your Environment

SuiteCRM Version used: 7.9.4
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Hi @Garridus, I've created a PR for this issue. If you would like to test it please make sure you also include: 

#4056 
#4059

Thanks for bringing this to our attention.
