### ISSUE TITLE
Installation with db-user "root" not possible

### ISSUE THREAD

**Issue by jerger** [salesagility/SuiteCRM#4135]
After having a fresh ubuntu & mariadb there is a db-user "root" configured. But installation only works with db-user "root@localhost".

#### Expected Behavior
Enable installation with user "root"

**Comment by pgorod** [comment]
DB User `root` works fine for me with MySQL.

Why did you omit the rest of the Issue template? Software versions are relevant for this case. And knowing exactly what you entered in the rest of the DB configuration screens.

**Comment by jerger** [comment]
Sorry for missing information:

#### Actual Behavior
I've to enter db-user "root" and db-host "localhost"

#### Possible Fix
Don't concat db-username & db-hostname for credentials

#### Steps to Reproduce
1. setup fresh ubuntu 16.04
2. install mariadb, enter root users password
3. install suite-crm-7.9.4
4. open in browser (install.php)

#### Your Environment
* suite-crm-7.9.4
* Mariadb, PHP 7
* Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Hi @jerger Thanks for the question! However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our  [Community Forum](https://suitecrm.com/forum). We will be able to help you with your issue there.
