### ISSUE TITLE
JSON_LOOSE_TYPE not defined

### ISSUE THREAD

**Issue by judgej** [salesagility/SuiteCRM#4136]
#### Issue
Went to Studio and got this error:

Notice: Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' in /.../include/utils.php on line 3990

#### Expected Behavior
No error.

#### Actual Behavior
The error

#### Possible Fix
I'm not sure where this was defined in the past, but I'm guessing it was in a library (perhaps PEAR) and is no longer there, Could not find its definition in the case or in the master branch git repository. It does not appear to have ever been a core PHP constant. The includes/JSON class does not even appear to accept a constructor now - it just contains static methods, so it possibly being instantiated incorrectly (and should probably should not be instantiated at all).

#### Steps to Reproduce
1. Installed fresh 7.9.4 on PHP 7.1
2. Go to admin->studio
3.
4.

#### Context
Just installing to try it out.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7): PHP7.1
* Operating System and version (e.g Ubuntu 16.04): CentOS

**Comment by judgej** [comment]
I amended this on the monstrous include/utils.php:

```php
/**
 * Singleton to return JSON object.
 *
 * @return JSON object
 */
function getJSONobj()
{
    static $json = null;

    if (!defined('JSON_LOOSE_TYPE')) {
        define('JSON_LOOSE_TYPE', null);
    }

    if (!isset($json)) {
        require_once 'include/JSON.php';
        $json = new JSON(JSON_LOOSE_TYPE);
    }

    return $json;
}
```

Then it appears as an error here:

> Notice: Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' in /.../suitecrm.acadweb.co.uk/include/ytree/Tree.php on line 76

Added the same hack there:

```php
    if (!defined('JSON_LOOSE_TYPE')) {
        define('JSON_LOOSE_TYPE', null);
    }
```

But as stated earlier, the real fix is probably to remove the constructor parameter completely, i.e. all instances of `JSON_LOOSE_TYPE` being used *anywhere*. A quick search gives me this:

```bash
        $json = new JSON(JSON_LOOSE_TYPE);
./modules/DynamicFields/templates/Fields/Forms/enum2.php
    $json = new JSON(JSON_LOOSE_TYPE);
./modules/DynamicFields/templates/Fields/Forms/dynamicenum.php
                $json = new JSON(JSON_LOOSE_TYPE);
./modules/Contacts/views/view.retrieveemail.php
        $json = new JSON(JSON_LOOSE_TYPE);
./modules/Documents/TreeData.php
$json = new JSON(JSON_LOOSE_TYPE);
./modules/MergeRecords/Step3.php
$json=new JSON(JSON_LOOSE_TYPE);
./modules/MergeRecords/Step1.php
        $this->json = new JSON(JSON_LOOSE_TYPE);
./include/ytree/Tree.php
        $json = new JSON(JSON_LOOSE_TYPE);
./include/utils.php
            $json = new JSON(JSON_LOOSE_TYPE);
./include/SugarEmailAddress/SugarEmailAddress.php
```

**Comment by ajiKMi** [comment]
Hi,
did you get a fix for the Bug?

**Comment by dflois** [comment]
A quick fix maybe add into include/JSON.php:
 if (!defined('JSON_LOOSE_TYPE')) {
    define('JSON_LOOSE_TYPE', null);
}

It works for me (version 7.9.5)
[client XXX.XXX.XXX.XXX:XXXX] PHP Notice:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' in /var/www/html/orng_suite/include/utils.php on line 3990
[client XXX.XXX.XXX.XXX:XXXX] PHP Notice:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' in /var/www/html/orng_suite/include/ytree/Tree.php on line 76

**Comment by cumanacr** [comment]
This bug is evolving like an evil pokemon, from Notice to Warning next one is Error  :grin:

`PHP Warning:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' (this will throw an Error in a future version of PHP) in /.../include/utils.php on line 3992, , referer: http://localhost/test/suitecrm/index.php?action=ajaxui`

I'm currently using SuiteCRM 7.9.6 with PHP 7.2.0RC3

btw @judgej did a great analysis
