### ISSUE TITLE
Meetings Scheduler Bar Issues

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#414]
If user is close to the bottom of the page and hovers over the scheduler bar, the popup displays underneath and is slightly cut off. Ideally it would display above the bar/mouse when there is limited space at the bottom of the screen.

**Comment by Mausino** [comment]
@samus-aran i saw the @Dillon-Brown #2720 

> Closed due to inactivity.

It's issue 3,5 year old. I looked on it and i don't see any problem there in 7.10.11 version
