### ISSUE TITLE
The word "View" used far too often in buttons

### ISSUE THREAD

**Issue by judgej** [salesagility/SuiteCRM#4141]
#### Issue
Many rows of buttons are just two long and cause scroll bars to appear where they do not need to. This can be avoided in many cases by removing the word "View" prefixed to many of those button labels. In the Module Builder, for example, we have "View Fields", "View Relationships", "View Layouts", "Vi...[off the screen]

From a UX POV it also makes the page harder to scan as all the buttons start with the same word - "View..." requiring you to take more time and effort to jump to the second word each time. Just "Fields", "Relationships", "Layouts", etc. would work here, be shorter, easier to scan, and actually *more correct* (for example, you must click in "View Fields" in order to **Create** a new field in the next screen. So it's not really about viewing fields - it's about *managing* fields.

#### Expected Behavior
Just simpler UX.

#### Actual Behavior
Cumbersome UX, harder to scan and read, slower to get around the navigation as a result.

#### Possible Fix
Tackle it one module at a time.

#### Steps to Reproduce
1. n/a
2.
3.
4.

#### Context
It's an annoyance that slows down the UX.

#### Your Environment

* SuiteCRM Version used: 7.8.something
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

I'll be happy to make some of these changes once I know it is accepted as an issue that needs fixing.

**Comment by pgorod** [comment]
@judgej is this only in Module Builder? If not, can you please be more specific about other places where you think this could be changed?

**Comment by judgej** [comment]
Yes I think you are right - only the Module Builder. Most other modules have simple actions under an "Actions" drop-down and they are all short (Edit, Delete, Duplicate, etc.)

**Comment by horus68** [comment]
@judgej Try to change the strings involved, make a test and submit a PR to Github.
For the ModuleBuilder the strings are located in \modules\ModuleBuilder\language\en_us.lang.php

```
    'LBL_HISTORY' => 'View History',
    'LBL_BTN_VIEW_LAYOUTS' => 'View Layouts',
    'LBL_BTN_VIEW_FIELDS' => 'View Fields',
    'LBL_BTN_VIEW_RELATIONSHIPS' => 'View Relationships',

```
On the other modules counted more then 100 "View ..." strings. 
Not all are the ones you point out being managing buttons not actually view buttons. 
So this should require a more detailed look.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The word "View" used far too often in buttons](https://trello.com/c/7va44Ol3/224-the-word-view-used-far-too-often-in-buttons)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
