### ISSUE TITLE
Email Address - "invalid" and "opt_out" options are lost

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#4145]
#### Issue
When setting a second (not primary) email address opted out or invalid in either account or a contact, any modification done on the record through "saveHTMLField" (detail view + inline edit) or through REST (v4_1) set_entry operations, will wipe out both of these flags on that email address. (If you edit the record in full edit mode or it the email is a primary email address this does not happen).

#### Expected Behavior
"opt_out" and "invalid" flags should be retained

#### Actual Behavior
"opt_out" and "invalid" flag values are lost and are set to "0" in the database

#### Steps to Reproduce
1.open an account in full edit mode add a a second(not primary) e-mail address and flag both the "Opted out" and "Invalid" options - save
2.Now in DetailView you can see that the email address is crossed out and has the "(Opted Out and Invalid)‎" note written next to it.
3. double click on any in-line editable field like "Description" modify its value and click the tick button to save the value
4.refresh the current DetailView page and you will see that the "(Opted Out and Invalid)‎" flags are gone

#### Context
I'd consider this a bug because it leads to loss of data and quite a serious one too because by losing the opt_out flag, opted out email address holders will receive campaign mails (...and will complain...)

#### Your Environment
* SuiteCRM Version used: Version 7.9.3  - Sugar Version 6.5.24 (Build 509) - tested on https://demo.suiteondemand.com

**Comment by Mausino** [comment]
Should it have sometihng with issue #603  ??? because same problem is there

**Comment by Mac-Rae** [comment]
Appears to have been resolved in 7.11.21 :+1:
