### ISSUE TITLE
Meetings Scheduler Bar Popup Hover Issues

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#415]
If the user hovers over a meeting in the scheduler bar, the popup shows. If the user moves the cursor away from the bar the popup is not closed. This means that on the Meetings popup via Calendar, if you switch tabs the popup stays on the screen even if you switch between multiple tabs. The user phsyically has to click to close 'x'.

**Comment by Dillon-Brown** [comment]
Unable to replicate. Popup does not appear when I change tabs.
