### ISSUE TITLE
Subsciptions missing Save/Cancel Buttons 7.8.5 ThemeP

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#4152]
#### Issue

The Buttons are missing in manage subscription page
![grafik](https://user-images.githubusercontent.com/16813374/29658071-f338f300-88b9-11e7-8d5d-d3c04fe22bf3.png)

#### Expected Behavior

Display Buttons
#### Actual Behavior

No Buttons available, unabel to save change
#### Possible Fix

Fix in Subscription.tpl
#### Steps to Reproduce

1.open Contact-> Manage Subscripitions

#### Your Environment

* SuiteCRM Version used: 7.8.5 ThemeP
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all Browsers
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Lowering priority. The buttons are actually present but their color matches the background.

**Comment by Dillon-Brown** [comment]
LTS - #4164
