### ISSUE TITLE
Can't export TargetList's contacts list

### ISSUE THREAD

**Issue by raeeskh90** [salesagility/SuiteCRM#4154]
Hello,

I visited target list detail view page and click on export button, I saw blank page and the records never export with me.
At first suitecrm.log file show me error : "unknow column parent_name in contacts_cstm table" so I alter the table by adding new column parent_name to contacts_cstm for time being.
After clicking again on export button of target list, i saw same blank page, i read suitecrm.log file again and it shows the following error:
MySQL error 1066: Not unique table/alias: 'contacts_cstm'. (see complete error below)

Could I change in suitecrm core files and give dynamic alias to contacts_cstm table in the query? Is it a bug? how to solve it?
I am using suitecrm version 7.8.3 with PHP Version 5.6.26, Linux

Here is the complete suitecrm.log file error currently:

Thu Aug 24 14:28:44 2017 [30780][1][FATAL] Query Failed: (SELECT contacts.id AS current_id,'Contacts' AS current_module,'gehoert_zu_kontakt_c' AS current_field,'Contacts' AS related_module,'contact_id_c' AS related_field,contacts_cstm.contact_id_c AS related_value,contacts.last_name AS related_label, contacts.first_name AS related_label1 FROM contacts JOIN contacts_cstm ON contacts_cstm.id_c=contacts.id
JOIN contacts_cstm ON contacts_cstm.id_c = contacts_cstm.contact_id_c
LEFT JOIN contacts ON contacts.id = contacts_cstm.contact_id_c WHERE contacts.id='58161319-31e8-bd31-98e9-58da30222bbf') UNION (SELECT contacts.id AS current_id,'Contacts' AS current_module,'gehoert_zu_kontakt_c' AS current_field,'Contacts' AS related_module,'contact_id_c' AS related_field,contacts_cstm.contact_id_c AS related_value,contacts.last_name AS related_label, contacts.first_name AS related_label1 FROM contacts JOIN contacts_cstm ON contacts_cstm.id_c=contacts.id
JOIN contacts_cstm ON contacts_cstm.id_c = contacts_cstm.contact_id_c
LEFT JOIN contacts ON contacts.id = contacts_cstm.contact_id_c WHERE contacts.id='b42ad26e-5dac-e364-2633-584735847a85'): MySQL error 1066: Not unique table/alias: 'contacts_cstm'
Thu Aug 24 14:28:44 2017 [30780][1][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.

Thank you.
Raees

**Comment by pgorod** [comment]
@raeeskh90 there is no column called `parent_name` in `contacts_cstm` by default. So you have that reference there because of some customization you made. 

You probably just need to fix that reference, whatever it is.

**Comment by Dillon-Brown** [comment]
Hi @raeeskh90 This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum).

I am unable to replicate this on 7.8.x. Please re-open if you are able to replicate this as a core bug. Thanks.
