### ISSUE TITLE
Cannot create new dashboard tabs 7.8.5 ThemeP

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#4159]
#### Issue

I cannot create a new dashboard in Home view in ThemeP  in Theme7 it works fine.

#### Expected Behavior

Tab should be created
#### Actual Behavior

No TAb is created
#### Steps to Reproduce

1.In Home click new Tab.
2.Enter a name and save.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actual FF and ie
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
@Lehnerr I'm unable to replicate this. What php version are you using? is this perhaps related to #4157

**Comment by Lehnerr** [comment]
Hi.
I'm runing it on ubunto 16.04( PHP v7.0.22-0ubuntu0.16.04.1).
I tested now: 
with chrome, result --> OK
ie11, result --> I have to refresh browser aftewards the cew created tab is there.
ff, result --> No tab is created.

So the problem is mainly in FF.

**Comment by Dillon-Brown** [comment]
Closing this in favour of #4157
