### ISSUE TITLE
SMTP Password form input fields contain a max length of 64 (should be larger)

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4173]
#### Issue

Currently all of the forms which ask for the SMTP Password contain an html validated limit of 64 characters. If you were to paste a password in that is 65 characters you would end up losing the last character of the password without knowing it.

This could lead to a lot of headache and thinking that SMTP and Email configuration on the CRM is just not working.

I have not been able to locate any RFC that states that a SMTP password should only be 64 characters. I have seen an RFC which says the local portion of an email should only be 64 characters, but that still wouldn't apply since a username can and is composed of a full email address a lot.

The bigger issue is that a very large email gateway gives out the SMTP password as an API key which is 70 characters long. It would not be possible to enter this into SuiteCRM and it would be really hard to track down the problem with it.

#### Expected Behavior

Be able to enter longer usernames and passwords than 64 characters in to the SMTP Configuration forms.

#### Actual Behavior

The input fields for SMTP configuration for Username and Password have a maxlength of 64 characters.

#### Possible Fix

Remove the `maxlength="64"` all together from `smtpuser` and `smtppass`. Or increase it's size. I recommend the former since I cannot track down what the correct size would be other than maybe something "sane" like 255.

#### Steps to Reproduce

1. Create an email account which has a password with a length of 65 characters
2. Fill out the email configuration and paste in your 65 character password
3. Click "Send Test Email"
4. Observe a SMTP connection error

In the background logs you'll actually see it says this is authentication error; however, a normal user would not know this.

#### Context

One of the larger email gateways are giving out 70 character smtp passwords. It took me debugging the php code to figure out that SuiteCRM was sending a truncated password to the server.

#### Your Environment

* SuiteCRM Version used: v7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 60.0.3112.101 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL Php 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by pgorod** [comment]
This might be a good time to recall this:

https://trello.com/c/uyjoqH7p/109-replace-crypt-calls-with-passwordhash
