### ISSUE TITLE
Error:SMTP connect() failed.

### ISSUE THREAD

**Issue by javi2491** [salesagility/SuiteCRM#4174]
I am try to config SMTP emails by dwfault, use gmail but get error

SuiteCrm version 7.9.4
PhpMailer 6

HELP I am new in this topic.
Error:SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by pgorod** [comment]
@javi2491 this looks like it should be [in the forums](https://suitecrm.com/forum/index), not here in GitHub... please close the issue here.
