### ISSUE TITLE
Bad <TAB> management in SuiteCRM Suite P Theme

### ISSUE THREAD

**Issue by Franchic2011** [salesagility/SuiteCRM#4177]
When filling an opportunity form, the TAB order is somewhat eratic.

Using the TAB key to navigate from a field to the next one does not always do what you are expecting it to do.

#### Steps to Reproduce
1. Create a new oppotunity
2. Fill the first field
3. Use the TAB key to enter the so colled next field
4. Repeat the operation until you have reached the end of the form

=> It appears that the field order is not respected

#### Your Environment
* SuiteCRM Version used: 7.9.2
* Browser name and version : Chrome V60.0.3112.113 (Build officiel) (64 bits)
* Environment name and version : MySQL, PHP 7
* Operating System and version : Linux (I don't know which distribution)

**Comment by Kevconry** [comment]
When tabbing through the fields on the view, it seems that the CRM is not 100% clear what field is being tabbed to.
(ie: When a Dropdown is tabbed to, nothing changes to visually indicate this, but it can be modified by Up/Down on the Keyboard)

However, as Tabbing does appear to move through the fields in the correct order (as of 7.13.2), we will close this issue.

But, if you feel this should be reopened, or you have further info, please get in touch!
