### ISSUE TITLE
SuiteP quickcreate forms not visible in mobile

### ISSUE THREAD

**Issue by rouhu** [salesagility/SuiteCRM#4180]
Quickcreate form is not visible in SuiteP theme and mobile browser. 

#### Issue
Mobile browsers do not display the quickcreate form when button "Create" pressed in subpanel.

#### Expected Behavior
Quickcreate form should appear

#### Actual Behavior
Nothing happens when button "create" pressed

#### Possible Fix
Probably javascript issue.

#### Steps to Reproduce
1. With mobile browser (chrome on Android) go to Accounts and detail view
2. Scroll down to Opportunities subpanel
3. Press CREATE -> no quickcreate form is displayed

#### Your Environment
* SuiteCRM Version used: 7.9.3
* Browser name and version : Chrome on mobile or developer extension on desktop chrome (on iPad browser it works ok.)

**Comment by pgorod** [comment]
I confirm this happens on 7.9.4.

The input boxes disappear at widths lower than 750px.

I did my tests on a contact, clicking `Add note` under `History` subpanel. The modal dialog box completely disappears when the browser window goes below that width, and comes back if I widen it again. Some CSS needs fixing...

@Dillon-Brown maybe this is a high priority?

**Comment by drosenfeldpositive** [comment]
I confirm this happens too on 7.9.5
