### ISSUE TITLE
InboundEmail::createAutoImportSugarFolder() not creating folder correctly

### ISSUE THREAD

**Issue by bdragon28** [salesagility/SuiteCRM#4182]
#### Issue

In a18ba8404cb3825968a5a5a149ca81a3d4a0a34e the behavior of SugarFolder::$new_with_id was changed, but InboundEmail::createAutoImportSugarFolder() was not updated to match, so it is unable to create new auto import folders. (it accidentally chooses the modify query instead of the create query)
This leaves groupfolder_id pointing to an invalid guid, causing problems auto importing emails for new group accounts.

#### Expected Behavior

Folders created when enabling auto import.

#### Actual Behavior

The folder guid is created but the record in the folders table never gets created.

#### Possible Fix

in InboundEmail::createAutoImportSugarFolder(), either change the $folder->new_with_id line to FALSE or rework the function to defer guid creation to the save() call. 

Additionally, perhaps augment modules/InboundEmail/Save.php to check whether $focus->groupfolder_id is valid when it is set inside the if( isset($_REQUEST['is_auto_import']) && $_REQUEST['is_auto_import'] == 'on' ) check so resaving accounts can clean up the damage.

#### Steps to Reproduce

1. Create a new group mail account, and enable the "Import Emails Automatically" option.
2. Send test mail to the account and run cron.
3. Observe the "[FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder" message in the log.

#### Context

I've been attempting to use the incoming email functionality but was tripping over this bug.

#### Your Environment

* SuiteCRM Version used: 7.9.4 + 0858ba15 hotfix
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox ESR 45.9.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Debian 8.8

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.10.1. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
