### ISSUE TITLE
Personal account not showing when composing new Email

### ISSUE THREAD

**Issue by jalongas** [salesagility/SuiteCRM#4188]
#### Issue

Hello, I was wondering if anything changed in the recent versions of the Software.
Prior 7.4.1, we were able to configure the system Outbound Email and then, send Emails as each user using that Account. 
As an example, in the previous Compose view for Emails (the Outlook like one), in "From" dropdown, we could see the following options:
- FirstName LastName &lt;myemail@domain.com&gt; - (System default)
- Group Inbound Email 1
- Group Inbound Email 2
- ...
- Group Inbound Email N

Now, we can't do this anymore it seems. When wee go to Compose new Email, the form that is being shown to the user only display the N Group Inbound Emails, but no "System default" one. 

Is there a fix for this or it is working in a different way now? 

#### Expected Behavior

1. Configure system Outbound Email 
2. Go to Emails > Compose
3. In From field, should appear the user email addres

#### Actual Behavior

1. Configure system Outbound Email 
2. Go to Emails > Compose
3. From field appears empty or filled with the Group Inbound Email accounts configured

#### Your Environment

* SuiteCRM Version used: 7.9.4

Thank you

**Comment by Dillon-Brown** [comment]
Hi @jalongas, you will need to have a personal inbound/outbound email configured in order for the "From" drop-down to be populated.
