### ISSUE TITLE
Quick form is not saving product in current category

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#419]
![screenshot from 2015-08-28 16 18 40](https://cloud.githubusercontent.com/assets/1594411/9548442/ca18b1be-4da0-11e5-96f3-0bcd0cc9fe8b.png)

![screenshot from 2015-08-28 16 19 07](https://cloud.githubusercontent.com/assets/1594411/9548444/ccf2ca64-4da0-11e5-869e-559315bf606e.png)

i also did this with "Is parent category" enabled, same issue.

**Comment by darthtang** [comment]
I can also confirm this bug 
@ghermans ... nice button colour!

I am currently working on your bug. Thanks for the bug find

**Comment by darthtang** [comment]
@ghermans 
I recently asked for a pull request. I have not fully fixed the problem. However i have made a small patch to partially solve the problem by adding a popup chooser to choose which product type it belongs to

cheers!
