### ISSUE TITLE
Scheduled Reports: Detail and Edit views are not populating fields correctly

### ISSUE THREAD

**Issue by bunglex** [salesagility/SuiteCRM#4194]
#### Issue

The Detail and Edit Views of a Scheduled Report are not displaying data correctly.

#### Expected Behavior

The Detail and Edit Views of a Scheduled Report should show the same data,

#### Actual Behavior

The Detail View does not display the recipients email address, and the Edit view does not show the time intervals correctly and defaults to monthly.

#### Steps to Reproduce

1. Create a New Scheduled report and fill in a recipients email address and set the frequency to daily at 6am (for example)
![aor_scheduled_report - create](https://user-images.githubusercontent.com/4482918/29990200-59e8208c-8f70-11e7-86c5-526419bfe1a4.JPG)

2. Save the new record and then open it's Detail View (note that the email address is blank)
![aor_scheduled_report - detail view](https://user-images.githubusercontent.com/4482918/29990201-59e9c3ba-8f70-11e7-81a1-3bfadec890a4.JPG)

3. Open the Edit View of the record (note that the email is set, but the time defaults to monthly).
![aor_scheduled_report - edit view](https://user-images.githubusercontent.com/4482918/29990202-59ed101a-8f70-11e7-8b31-bf5ce0386b4f.JPG)

#### Context

This can be quite confusing at first; my scheduled report was not being received and this bug was very distracting from the real issue,  as i thought the failure was due to the email address not being set in the record, when in fact the failure was in the email server.  

#### Your Environment

* SuiteCRM Version used: Version 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.18-0ubuntu0.16.04.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.2 LTS

**Comment by karan-dreambits** [comment]
Is this bug resolved ?

**Comment by intoxillusions** [comment]
has this been fixed? i have the same issue and can't get any scheduled reports to run...
