### ISSUE TITLE
case assignment don't work

### ISSUE THREAD

**Issue by centoasa** [salesagility/SuiteCRM#42]
As in "least busy" as in round robin, case assignament don't work, and cases will assign always to admin (first user of suite crm)

**Comment by andrea-gioia** [comment]
I have the same problem with Sugar CRM CE v-6.5.2. If it is not a bug what could be the problem? How I can solve it?

Thanks,
Andrea

**Comment by mattlorimer** [comment]
It is a bug in Sugar CE, but Suite replaces this with AOP case management which doesn't have this issue

**Comment by andrea-gioia** [comment]
Thank you for the prompt answer. What do you mean when you talk about Suite?is it the the enterprise version? could you provide anyway a link to "AOP case management" documentation? I connot find anything searching on google. Best regards, Andrea

**Comment by andrea-gioia** [comment]
Ok, I found it. It's suitecrm.com
I'll give a look to it. Thanks!

**Comment by mattlorimer** [comment]
You can find some docs on AOP here https://suitecrm.com/wiki/index.php/Userguides#Advanced_OpenPortal
Its a little out of date but it give you the general idea
