### ISSUE TITLE
Emails that I send via suiteCRM are not recorded anywhere

### ISSUE THREAD

**Issue by danicv94** [salesagility/SuiteCRM#4200]
#### Issue
When I send emails in suiteCRM it works because I receive those emails, but there are not recorded anywhere, not in suitecrm not in thunderbird and not even in webmail, I wonder if this is a bug or something that I'm doing wrong.

#### Expected Behavior
If I send emails they should be recorded everywhere (suitecrm, thunderbird, etc)

#### Actual Behavior
If you send a email in suiteCRM it sends the email, but it's not recorded anywhere.

#### Steps to Reproduce
1- Go to emails
2- Send an email
![issue1](https://user-images.githubusercontent.com/19204096/30058396-1b5b64be-923b-11e7-9ff0-0b58d6d2618a.png)

3- Go to the inbox to actually check that you receive the email.
![issue2](https://user-images.githubusercontent.com/19204096/30058422-347103e6-923b-11e7-855f-3596f5fa50af.png)

4- Go to your inbox.sent to see that the email you just send it's not there.
![issue3](https://user-images.githubusercontent.com/19204096/30058449-562a19a0-923b-11e7-8a0d-61f8883a4e6a.png)

#### Context
This bug has affected me pretty badly, because I don't know what emails I'm sending and what emails I'm not.
I feel this bug has medium priority.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 54.0.1
* Environment name and version (e.g. MySQL, PHP 7): Php 7.0.24
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by ErMaqui** [comment]
I can confirm this behavior appears also on 7.9.5-7.9.7

**Comment by ErMaqui** [comment]
Related with #336 and #4251.

**Comment by Dillon-Brown** [comment]
Hi @danicv94. This should be fixed with 7.9.x latest. You can see sent mails in the "Sent Email" folder in the email module list-view.

**Comment by RobRobM** [comment]
I am using 7.10.4 and still have this problem.
