### ISSUE TITLE
re-enabling legacy search 'enable_legacy_search' pop up doesn't save anymore column order in list view

### ISSUE THREAD

**Issue by jekopsen** [salesagility/SuiteCRM#4204]
In Account list view (url : /index.php?module=Accounts&action=index&parentTab=Sales)
If you click on button to change columns order (close to "select All" checkbox) of the list, it will be opened a popup . Then after changing column order If you try to save you get following error:

```

index.php?module=Accounts&action=index&parentTab=Sales:1233 Uncaught ReferenceError: listViewSearchIcon is not defined
at Object.save (index.php?module=Accounts&action=index&parentTab=Sales:1233)
at Object.onSaveClick (index.php?module=Accounts&action=index&parentTab=Sales:1196)
at HTMLButtonElement.onclick (index.php?module=Accounts&action=index&parentTab=Sales:1101)

```

To reproduce re-enable the legacy search insert the following array into your config.php
```
'enable_legacy_search' => 
  array (
    0 => 'Accounts',
  ),

```
Or within config_override.php
```
$sugar_config['enable_legacy_search'][] = 'Accounts';
```

You can fix it just removing the option in config.php or commenting out the $searchFormInPopup check into file .../include/SearchForm/tpls/footer.tpl .
changin this lines it works....
{*if $searchFormInPopup*}
{include file='include/SearchForm/tpls/footerPopup.tpl'}
{*/if*}

I have suite Version 7.9.4 (Sugar Version 6.5.24 (Build 509)).
Browser  Chrome Version 51.0.2704.63 (64-bit)):
Environment  MySQL, PHP 7.

**Comment by pgorod** [comment]
I also confirmed this bug on my system.

@gymad you might want to take a look at this.

**Comment by scm1599** [comment]
The same problem here

**Comment by zoltankocsardi** [comment]
It works under 7.9.10.

**Comment by PedroErnst** [comment]
Seems to work 7.10.3
