### ISSUE TITLE
Project Templates Task Drag/Drop Issue

### ISSUE THREAD

**Issue by BeWiseLLC** [salesagility/SuiteCRM#4205]
When creating tasks in Project Templates, they align out of order. The drag and drop functionality to reorder is not working.

#### Issue
I have been creating tasks for project templates. I created them in order of how they should be deployed, making sure the preceding tasks were also assigned. When I saved them, they were all out of order. I tried setting up a project using the template, thinking that it might sort itself out, but it did not. None of the tasks were assigned as intended. When I tried to drag/drop them to reorder them, they just pop back to their original order upon save. 

#### Expected Behavior
The drag/drop functionality should allow me to reorder the tasks to their intended position.

#### Actual Behavior
The cursor does not match the task being moved and when it finally says it is saving, it pops back to its original location

#### Steps to Reproduce
See images for example

#### Context
As we will be building out all of our jobs based on these templates, this is a crucial part of our business. These tasks will be assigned to multiple people and rely on being completed in a specific order.

#### Your Environment

* SuiteCRM Version used: 7.8.5, then in 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 60.0.3112.113 (64 bit), Safari Version 10.1.2 (12603.3.8)

**If you have further questions, please feel free to reach out directly - s.kurdakul@b-yy.com**

<img width="321" alt="01-drag-drop to reorder id 2" src="https://user-images.githubusercontent.com/31256092/30066195-29b086fe-9225-11e7-89d9-e56e5776ea1c.png">

<img width="322" alt="02-id 2 repositions back to original location" src="https://user-images.githubusercontent.com/31256092/30066197-29dbb522-9225-11e7-9b64-e0d54c23bbe4.png">

<img width="550" alt="03-error on project template tasks" src="https://user-images.githubusercontent.com/31256092/30066196-29bfd67c-9225-11e7-95f9-f4bab7f93668.png">

**Comment by BeWiseLLC** [comment]
Anyone looking at this? It is a pretty mission critical for my team that this is fixed.

**Comment by Dillon-Brown** [comment]
Hi @BeWiseLLC, I'm currently taking a look at fixing some of the issues in projects, project templates and gantt chart. I'll put up a PR that should address this in the next few days.

**Comment by BeWiseLLC** [comment]
@Dillon-Brown Hi there. I was just wondering if there was an ETA on when this might be addressed. It is a game-stopper for my team and is crippling our moving forward with efficiency.

Thanks so much for any information you may provide.

Kindest regards,
Sheri

**Comment by Dillon-Brown** [comment]
@BeWiseLLC There seems to be quite a large number of issues in project templates and project tasks. Have 12 fixed so far and should be able to get the rest resolved today.

**Comment by JamesRPAS** [comment]
I'm having the same issue now in 7.10-RC, but with a different console error:

![image](https://user-images.githubusercontent.com/15794190/35947714-570b0800-0cbd-11e8-87dd-027d133d632d.png)
