### ISSUE TITLE
bug in the email template

### ISSUE THREAD

**Issue by pokernet** [salesagility/SuiteCRM#4206]
#### Issue
include image in email template change the url to wrong format
and the include image do not showin the recive email client !!!
cnot include images in the email !

#### Expected Behavior
the send email getting no image in the email

#### Possible Fix
if you go to  campaign and include the image from the  campaign template then all OK.
you can see the  campaign add different url to the url field

#### Steps to Reproduce
1. create email template
2.include image from computer or from web url
3. save
4. go to email  campaign create new and select the new template make no changes
5. send  campaign

#### Context
the email i get have no image include

#### Your Environment

7.9.4 crm

Thanks
alex

**Comment by pgorod** [comment]
@Dillon-Brown  I believe this is a wider issue affecting all HTML editors.

It can be reproduced on the demo, in 7.9.5, in the Knowledge Base module, adding an image (drag-and-drop), hitting `Save` - it doesn't get saved.

**Comment by Dillon-Brown** [comment]
Unable to replicate with latest LTS. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
