### ISSUE TITLE
Cannot edit Layouts in Module Builder

### ISSUE THREAD

**Issue by willsowerbutts** [salesagility/SuiteCRM#4213]
#### Issue

I've created a new module but I cannot edit the Layouts. A PHP error is reported in the web server logs.

#### Expected Behavior

In the Module Builder, create a new Package, then a Module within that Package, then expand Layouts in the navigation tree and click on (eg) "EditView". I expect the view editor to appear.

#### Actual Behavior

Instead nothing happens and the following error is logged in the web server log file:
`[error] 3560#3560: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of UndeployedMetaDataImplementation::getFileName($view, $moduleName, $packageName, $type = MB_BASEMETADATALOCATION) must be compatible with AbstractMetaDataImplementation::getFileName($view, $moduleName, $type = MB_CUSTOMMETADATALOCATION) in /var/www/crm.eatworkart.com/modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php on line 49" while reading response header from upstream, client: 2001:8b0:3b1:beef:ca60:ff:fec2:b8cf, server: crm.eatworkart.com, request: "POST /index.php?to_pdf=1&sugar_body_only=1&module=ModuleBuilder&MB=true&action=editLayout&view=editview&view_module=Colours&view_package=WRS_TestPackage HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "crm.eatworkart.com", referrer: "https://crm.eatworkart.com/index.php?module=ModuleBuilder&action=index&type=mb"`

#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version: Chrome for Linux, 64-bit, Version 60.0.3112.113
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.26, PHP 7.0.19
* Operating System and version (e.g Ubuntu 16.04): Debian 9.1 "stretch"

**Comment by BeWiseLLC** [comment]
**Issue**
I am unable to edit layouts in the standard modules either.

**Actual Behavior**
I tried to add a custom field (dropdown) in the Email Templates module. I can see the field in the EditView, DetailView and the QuickView, but not in the live view. Also, the Sync to DetailView button does not save when checked.

![cannoteditlayouts 4213-comment](https://user-images.githubusercontent.com/31256092/30127212-6bdc21f4-930c-11e7-9e74-22d41f86070c.png)

**Your Environment**
SuiteCRM Version 7.9.4
Browser name and version: Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by willsowerbutts** [comment]
Just re-tested and confirmed this bug remains in the latest version I can download:

Version 7.9.6
Sugar Version 6.5.25 (Build 344)

**Comment by dflois** [comment]
Me neither

$suitecrm_version      = '7.9.6';
$suitecrm_timestamp    = '2017-10-03 17:00';
