### ISSUE TITLE
changing "Name Format" in User Interface not effective

### ISSUE THREAD

**Issue by jingkang99** [salesagility/SuiteCRM#4214]
Version 7.9.4
Sugar Version 6.5.24 (Build 509)

even changing the individual user's Name Display Format, it always shows
[Salutation] [First] [Last]
Dr. David Livingstone

config file seems right:
config_override.php:$sugar_config['default_locale_name_format'] = 'l f s';

seems cannot change the format

![image](https://user-images.githubusercontent.com/10793075/30127766-30df5ae2-92f5-11e7-9900-9cf5efeaebf4.png)

**Comment by Kevconry** [comment]
Can't replicate in 7.13.2,
After changing the name format the name format applies correctly
please re-raise or get in touch if you are still having this issue
