### ISSUE TITLE
PDF Templates shown with HTML tags

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4223]
#### Issue

Cleaning of HTML in all html fields results in showing text with html tags or even removing all text entirely. An example is given below for PDF templates.

#### Expected Behavior

HTML should be cleaned correctly and text displayed without HTML tags.

#### Actual Behavior

Text is shown with html tags or not at all.

#### Steps to Reproduce

1. Create a new PDF template.
2. Insert inside the body a simple "Hello"
3. Save the Template
4. Re-open the template
5. The body now shows `<p>Hello</p>`

#### Context

High priority. This will be resolved as soon as possible.

#### Your Environment

* SuiteCRM Version used: 7.8.6, 7.9.4, 7.9.5.
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Non browser dependent
* Environment name and version (e.g. MySQL, PHP 7): Non environment dependent
* Operating System and version (e.g Ubuntu 16.04): Non operating system dependent

**Comment by Cerothen** [comment]
Can confirm that this is happening for us as well.

Your Environment

- SuiteCRM Version used: 7.9.4 - 7.9.5.
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 61.0.3163.91
- Environment name and version (e.g. MySQL, PHP 7): PHP 5.6u30 OR PHP 7.1, MySQL 5.5
- Operating System and version (e.g Ubuntu 16.04): Debian 8.8 Server, Windows 7-10 Client

**Comment by aureh12** [comment]
quick fix: 

edit /modules/AOS_PDF_Templates/metadata/editviewdefs.php

 0 =>
                        array (
                            'name' => 'description',
                            'type' => 'text', // ADD THIS LINE
                            'label' => 'LBL_DESCRIPTION',
                        ),

**Comment by ChangezKhan** [comment]
Hey @aureh12 your solution worked, kindly create a PR for it ASAP, as this issue is of High Priority.

**Comment by Dillon-Brown** [comment]
This issue should be resolved by #4237
