### ISSUE TITLE
Bad data passed in; Return to Home when create relationship

### ISSUE THREAD

**Issue by noimang** [salesagility/SuiteCRM#4224]
#### Issue

I am using SuiteCRM 7.9.4, when I create relationship of custom module I received error message Bad data passed in; Return to Home
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.9.4. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
