### ISSUE TITLE
Themes Suite R Unable to change colour (Sometimes)

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#423]
It is very hard to describe this bug as the bug has a mind of its own of when i decides to turn up.

Basically if you go to themes -> Suite R -> change a couple of colour with the colour chooser -> save - > save.

Sometimes it wont save the change at all. sometimes it will. 

If anybody can elaborate on this and help to pinpoint this bug that would be great!

Regards 

Darren

**Comment by willrennie** [comment]
Have you ensured your permissions are set correctly in your config.php and on your SuiteCRM filesystem?

**Comment by darthtang** [comment]
'dir_mode' => 1517,
    'file_mode' => 420,

my permissions are enabled on the file system and the fault still stands
