### ISSUE TITLE
Hotfix behind master?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4235]
#### Issue

Hotfix branch is 5 commits behind master. 
See link: https://github.com/salesagility/SuiteCRM/compare/hotfix...master

#### Expected Behavior

Hotfix should be in sync or ahead master

![2017-09-11 11_24_51-salesagility_suitecrm at hotfix](https://user-images.githubusercontent.com/3055443/30270314-1226f978-96e4-11e7-8921-b53f9ebd6733.png)

**Comment by Dillon-Brown** [comment]
Hi Horus, will correct this shorty. Thanks.

**Comment by Dillon-Brown** [comment]
Will close this for now. It looks like there was some accidental merges into master which we will resolve at a later date. Thanks for bringing this to our attention.
