### ISSUE TITLE
Popup z-index issue on calendar

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4244]
#### Issue

The calendar color picker popup and schedular bar appear under the current popup.

#### Actual Behavior

![color_picker](https://user-images.githubusercontent.com/26431166/30323445-25dcd3c6-97b5-11e7-9666-8db8428bf55c.png)

#### Context

Medium

#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

**Comment by adzychester** [comment]
This is related, but not the same: https://github.com/salesagility/SuiteCRM/issues/5507

**Comment by Dillon-Brown** [comment]
No longer an issue on latest hotfix.
