### ISSUE TITLE
Run Email Reminder Notifications failed in CRON run

### ISSUE THREAD

**Issue by ruipeleja** [salesagility/SuiteCRM#4252]
#### Issue

I have updated my suitecrm from version 7.7.9 to new version 7.9.5.
this error "[FATAL] Job (Run Email Reminder Notifications) failed in CRON run" is registered in the logs every time cron is running.

#### Actual Behavior

[FATAL] Job (Run Email Reminder Notifications) failed in CRON run

#### Steps to Reproduce

1. execute cron.php

#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chrome
* Environment name and version (e.g. MySQL, PHP 7): Mysql
* Operating System and version (e.g Ubuntu 16.04): LINUX

**Comment by pgorod** [comment]
@ruipeleja this kind of thing belongs in the forums... maybe you can open a thread there?

Until you can be sure there is actually a SuiteCRM bug, and not just a configuration problem on your system, it's better to stay in the forums. I will help you out there. 

(it might help to post a larger chunk of the logs, near the time when the error occurs, to see what it was doing just before failing)

**Comment by Dillon-Brown** [comment]
Hi @ruipeleja  This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum).

I am unable to replicate this on 7.9.x. Please re-open if you are able to replicate this as a core bug. Thanks.
