### ISSUE TITLE
Unresolved address labels

### ISSUE THREAD

**Issue by FR-JS** [salesagility/SuiteCRM#4255]
#### Issue
Address fields referring to removed language strings (LBL_PRIMARY_STREET, LBL_ALT_STREET).
Seems to relate to #4026.

#### Expected Behavior
Language strings should be resolved.

#### Actual Behavior
Language strings not being resolved.

#### Possible Fix
In the file _include/SugarFields/Fields/Address/en_us.EditView.tpl_ replace
`{sugar_translate label='LBL_{{$key}}_STREET' module='{{$module}}'}`
with
`{sugar_translate label='LBL_STREET' module='{{$module}}'}`

#### Steps to Reproduce
1. Create or edit any record with an address field.

#### Your Environment
* SuiteCRM Version used: 7.9.5

**Comment by pgorod** [comment]
The fix should probably be reinstating all the strings in this format
`LBL_{{$key}}_STREET` that were removed.

@horus68 can you please check this out? I'm guessing these strings appeared to be unused because there was no direct reference to them, but in fact there are these indirect references...

**Comment by Dillon-Brown** [comment]
Thanks guys, that should be this issue resolved. I'm sure there may be a few more missing dynamic labels hanging around though... Hopefully this shouldn't occur again as we implement better detection for missing labels.

**Comment by FR-JS** [comment]
I did notice as well that other than a few presentational attributes and fixes there's no real difference between the _Address/EditView.tpl_ and _Address/en_us.EditView.tpl_ templates. Is it worth pushing the changes into the base template and removing the language specific version?

**Comment by Dillon-Brown** [comment]
@FR-JS From a quick look at the Edit and Detailview tpls you appear to be correct. Pushed a fix to the same PR. Thanks!

**Comment by FR-JS** [comment]
Did you still want a new issue for the template removal or hold off on it?

**Comment by Dillon-Brown** [comment]
@FR-JS Shouldn't be necessary. I've references this issue in the PR. Thanks.
