### ISSUE TITLE
'Sync to DetailView' no longer saving in fresh install of 7.9.5

### ISSUE THREAD

**Issue by cgrondin** [salesagility/SuiteCRM#4257]
#### Issue

After installing a fresh version of 7.9.5, I am no longer able to select the option to Sync to DetailView in the EditView layout screen. I've tried repair and rebuild, rebuilding JS files, etc. to see if that solves it. It does not, and this happens to all modules I have tried so far, so not localized to a single module.
#### Expected Behavior

Normal behavior in previous versions was to be able to check the box 'Sync to DetailView', which would copy across the layout changes from EditView to DetailView, and prevent edits to DetailView while this option was checked in EditView.
#### Actual Behavior

Upon checking the box for this option and saving, the confirmation response comes back like normal 'This operation has been completed successfully', but does not actually save the 'Sync to DetailView setting'.

No errors reported in the logs (suitecrm.log or the server error log) related to this issue.
#### Steps to Reproduce

1.Make adjustment to EditView in Studio
2.Check box for 'Sync to Detailview in Studio
3.Save & Deploy
4.

#### Context

This is affecting my ability to translate changes from EditView to DetailVie on all modules, which is a basic feature of this software that has been included as long as I can remember. I would list as High Priority, since it is a relatively basic and commonly used feature.
#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chome (Version 60.0.3112.113 (Official Build) (64-bit)) / Edge (Microsoft Edge 40.15063.0.0)
* Environment name and version (e.g. MySQL, PHP 7): MYSQL / PHP 7.0.23
* Operating System and version (e.g Ubuntu 16.04): CENTOS 7

**Comment by Dillon-Brown** [comment]
Unable to replicate on 7.9.5 / 7.8.6. Have you checked permissions + repair/rebuild?

**Comment by cgrondin** [comment]
Yes, I have checked permissions and performed the repair/rebuild. I do not have any errors in the log and have no idea what could be causing this.

**Comment by brogsitter** [comment]
Are you using the "save" button only or the "save and deploy" button? (just to make sure)

**Comment by cgrondin** [comment]
I'm using the save and deploy button lol, thanks for checking.

**Comment by Dillon-Brown** [comment]
Hi @cgrondin, This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum).

I am unable to replicate this on 7.9.x. If you are able to replicate this as a core issue and provide steps then this can be reopened. Thanks.
