### ISSUE TITLE
7.3.1  install php errors

### ISSUE THREAD

**Issue by leonschuiling** [salesagility/SuiteCRM#428]
i install it on a new server and get massive lines full of errors in the install.php

below is a copy

how to handle this?

seems like a bug to me

best regards

leon

Strict Standards: Declaration of SugarEmailAddress::save() should be compatible with SugarBean::save($check_notify = false) in /home/schuilin/public_html/Nick/CRM/include/SugarEmailAddress/SugarEmailAddress.php on line 1113

Strict Standards: Declaration of Person::create_export_query() should be compatible with SugarBean::create_export_query($order_by, $where) in /home/schuilin/public_html/Nick/CRM/include/SugarObjects/templates/person/Person.php on line 44

Strict Standards: Declaration of User::retrieve() should be compatible with Person::retrieve($id = -1, $encode = true, $deleted = true) in /home/schuilin/public_html/Nick/CRM/modules/Users/User.php on line 44

Strict Standards: Declaration of User::create_export_query() should be compatible with Person::create_export_query(&$order_by, &$where, $relate_link_join = '') in /home/schuilin/public_html/Nick/CRM/modules/Users/User.php on line 44

Strict Standards: Declaration of User::create_new_list_query() should be compatible with SugarBean::create_new_list_query($order_by, $where, $filter = Array, $params = Array, $show_deleted = 0, $join_type = '', $return_array = false, $parentbean = NULL, $singleSelect = false, $ifListForExport = false) in /home/schuilin/public_html/Nick/CRM/modules/Users/User.php on line 44

Strict Standards: Declaration of User::list_view_parse_additional_sections() should be compatible with SugarBean::list_view_parse_additional_sections(&$list_form) in /home/schuilin/public_html/Nick/CRM/modules/Users/User.php on line 44

Strict Standards: Declaration of Currency::retrieve() should be compatible with SugarBean::retrieve($id = -1, $encode = true, $deleted = true) in /home/schuilin/public_html/Nick/CRM/modules/Currencies/Currency.php on line 239

Strict Standards: Non-static method UploadStream::register() should not be called statically in /home/schuilin/public_html/Nick/CRM/include/entryPoint.php on line 184

Strict Standards: Non-static method SugarConfig::getInstance() should not be called statically, assuming $this from incompatible context in /home/schuilin/public_html/Nick/CRM/include/SugarLogger/LoggerManager.php on line 76

Strict Standards: Non-static method SugarConfig::getInstance() should not be called statically, assuming $this from incompatible context in /home/schuilin/public_html/Nick/CRM/include/SugarLogger/SugarLogger.php on line 121
Welcome to the SuiteCRM 7.3.1 Setup Wizard
SuiteCRM

Previous
Next
Choose your language:

Visit suitecrm.com | Support Forums | Installation Guide | License

Strict Standards: Non-static method LogicHook::initialize() should not be called statically in /home/schuilin/public_html/Nick/CRM/include/utils.php on line 301

**Comment by willrennie** [comment]
You need to suppress Strict Standards in your php.ini file and restart your apache web service.

**Comment by Danisan** [comment]
This is not a bug. Either change your PHP versión or change the log level
of the server to something not strict.
