### ISSUE TITLE
Cannot add Dashlet - 7.9.3-7.9.5

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#4280]
#### Issue

Clicking "Add Dashlet" gives absolutely no reaction, not in frontend nor in console. Tested 7.9.3 to 7.9.5 on Firefox and Chrome.
#### Expected Behavior

Dashlet Chooser should be shown
#### Actual Behavior

No reaction
#### Steps to Reproduce

1. Login
2. Click "Add Dashlet"
3. No reaction

#### Context

My users keep asking me when this feature is available again.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52, Chrome 62
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): MS 2012R2

**Comment by BeWiseLLC** [comment]
I was just able to do so using SuiteCRM Version 7.9.5 in my Safari 1.1.2 browser.

**Comment by halest** [comment]
@BeWiseLLC Thanks for your answer. I have investigated further and in the network analysis a request is sent which is responded with 200 and the Add-Dashlet HTML but nothing is shown in the frontend

**Comment by halest** [comment]
Same in Safari for me

**Comment by ajedvaj** [comment]
@halest are you trying to add dashlet for standard module or for custom module?

**Comment by halest** [comment]
@ajedvaj Thanks for your response. I do not even get to that point as the click on the "Add Dashlet" button itself has no effect. So any module really.

**Comment by ajedvaj** [comment]
@halest Oh, I understand. I don't have this issue on v7.9.4. on FF v57.
Since network shows that you get good response from server, maybe this will sound silly... but have you cleaned your browser cache?

**Comment by drosenfeldpositive** [comment]
Hi, 

This happens to me, only with custom modules.

If I check vthe apache error.log (in my case because i've apache web server), i get:

> PHP Parse error:  syntax error, unexpected '<', expecting identifier (T_STRING) in /var/www/html/crm/modules/OBJ_resultados/Dashlets/OBJ_resultadosDashlet/OBJ_resultadosDashlet.php on line 48, referer: http://crm.directo.com.ar/crm/index.php?module=Home&action=index

In my case, "OBJ_resultados" is my custom module.

So, the solution is:

Open file modules/CUSTOM_MODULE/Dashlets/CUSTOM_MODULEDashlet/CUSTOM_MODULEDashlet.php
Change 
`class <module_name > Dashlet`
to
`classCUSTOM_MODULE_NAMEDashlet`

For example, in my case i changed it to:
`class OBJ_resultadoDashlet`

**Comment by PedroErnst** [comment]
@halest 

Does the issue still persist for you?

**Comment by halest** [comment]
@PedroErnst Yes but I reactivated the old layout where it works so for now my users are happy with it

**Comment by Mac-Rae** [comment]
Appears to be sorted
