### ISSUE TITLE
Inline double click wipes and change data [Bug in demo]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4285]
#### Issue

When inline editing a field with more then one line (address) or more then one email address (opted out email) its automatically cleaned to a single line value, removing the opted out address or part of the street address

#### Expected Behavior

No data cleaned or automatically saved

#### Actual Behavior

This is an image from demo (accounts)
Before edit:
![2017-09-20 12_18_10](https://user-images.githubusercontent.com/3055443/30641242-3ecfa706-9dfe-11e7-962d-de350b8dddbb.png)

and after double click (each field is saved automatically)
![2017-09-20 12_19_24](https://user-images.githubusercontent.com/3055443/30641281-5ed93936-9dfe-11e7-80ee-8bda7ec52c5c.png)

#### Steps to Reproduce

1. Enter demo
2. Enter contacts or other module
3. Double click to edit an address filed with more then one line (or an email field with opted an opted out address)
4. Its automatically saved cleaning some data (making it one line only)

#### Context

Critical as it changes data without any action intended by user.

#### Your Environment

* SuiteCRM Version used: Tested in Demo version and local version 7.9.5 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
* Environment name and version (e.g. MySQL, PHP 7): Demo site / and PHP 7.0.11, Mysql 5.7.17
* Operating System and version (e.g Ubuntu 16.04): Demo site / and local windows 7 test system with Wamp

**Comment by Dillon-Brown** [comment]
Marking as a low priority for now. You should be able to refresh the page and have the other data re-appear.

**Comment by Kevconry** [comment]
Was able to replicate in 7.13.2

**Comment by pgorod** [comment]
These kinds of inline edits are not implemented. The inline edit code treats these as simple fields, and confusion ensues.

I don't think anybody will have the patience to implement this in 2024 with v8 already released.

A simpler fix would be to disable inline edit for these aggregate fields; at least the user experience would be more reasonable.

**Comment by pgorod** [comment]
This is probably the exact same issue that appears in many other complaints:

#2146 
#6735
#9762 

All of these are "compound" fields, with more than one part.

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
