### ISSUE TITLE
Parameter conditions on reports are not updated

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#4303]
#### Issue
On a report based on module quotes I defined a condition on the field Account as parameter.
If I click on the Update button the Account value is not updated, while it is correctly handled if the field is filled by the account search window.

#### Expected Behavior

I expect a row to be shown with the specified account but nothing happens.

#### Actual Behavior

The parameter is not used.
#### Steps to Reproduce

1. Create an account say "Account1";
2. Create a quote for Account1;
3. Click on create report on the report module;
4. Fill the Name field with "Test";
5. Fill "Report Modules" with "Quotes";
6. Drag the field "Quote number" on the right panel;
7. Click on "Conditions";
8. Drag the field "Account" on the right panel;
9. Click on parameter check box;
10. Save;
11. Fill the value field with the string Account1 and click update;

#### My Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version: Firefox 49.0.1
* Environment name and version: mysql  Ver 14.14, PHP 5.4.45
* Operating System and version: Debian wheezy

**Comment by Mausino** [comment]
@stenfalp because this issue, we're geting error 502. If you check the Parameter in Condition tab.. you can't do any work with all reports because it have influence on all and break the Report detail view in our case.

I am using version 7.11.2

**Comment by Dillon-Brown** [comment]
@Mausino I think that would be a separate issue (I'm not able to replicate). From my understanding this issue is just with "Select" fields like account name and assigned to which don't let you update through in-line editing or the reports update button by typing.
