### ISSUE TITLE
No invoice attached in mail 

### ISSUE THREAD

**Issue by pabaillon** [salesagility/SuiteCRM#4309]
#### Issue
When I whant to send an invoice pdf in the module invoice no padf attached

#### Expected Behavior
In the email module a invoice pdf should be attached in the mail.

#### Actual Behavior
The email was created whith the right title. but no pdf attached.

#### Steps to Reproduce

1. Go to invoice module
2. click on an invoice 
3. Click action ->email pdf

#### Context
I want to send an invoice by pdf as before 7.9

#### Your Environment

* SuiteCRM Version used: 7.9.4 - 7.9.5
* Browser name and version Firefox 55.0.3
* Environment name and version Mysql - php 7.1
* Operating System and version windows7

**Comment by blloyd78** [comment]
**Workaround**
Print invoice as PDF.
Attach PDF to email manually.

Not cool, but it works.
