### ISSUE TITLE
7.9.5 No Detailview in email module with some emails.

### ISSUE THREAD

**Issue by pabaillon** [salesagility/SuiteCRM#4315]
#### Issue
With some email when I click to see a detailview i 've got a blank page.

#### Expected Behavior
I should see the detailview of an email. Some emails work 

#### Actual Behavior
A blank page with menu

#### Steps to Reproduce

1. In the email module click on email.

#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version Firefox 55.03
* Environment name and version (e.g. MySQL, PHP 7): Mysql PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Windows 7 
![capture](https://user-images.githubusercontent.com/31985913/30873513-d1420414-a2ed-11e7-9ccb-3d1102052fc1.PNG)

**Comment by pgorod** [comment]
Blank screens usually have a FATAL PHP error recorded in the web server log (typically `php_errors.log`) and sometimes more useful info is found in `suitecrm.log`.

You should have started this in the forums, not here in Github; this basic triage and investigation should be done there, and only come here when you are sure there is a generic bug for everyone, and you have more precise technical info to add (e.g. log messages). Don't worry, if you start a thread I will help you out there.

**Comment by Dillon-Brown** [comment]
Hi @pabaillon, please reopen if you are able to replicate this as a core issue and provide steps. Thanks.
