### ISSUE TITLE
SQL injection in WebToPersonCapture.php

### ISSUE THREAD

**Issue by samplonius** [salesagility/SuiteCRM#4316]
#### Issue

This looks like an SQL injection vector via campaign_id

    if (isset($_POST['campaign_id']) && !empty($_POST['campaign_id'])) {
        //adding the client ip address
        $_POST['client_id_address'] = query_client_ip();
        $campaign_id = $_POST['campaign_id'];
        $campaign = new Campaign();
        $camp_query = "select name,id from campaigns where id='$campaign_id'";

campaign_id is not validated, so it could be a string.  And SQL bind params are not used.

#### Expected Behavior

Force $campaign_id to an int:

$campaign_id = (int) $_POST['campaign_id'];

Or better yet, use SQL bind param functions, and it is too easy to make mistakes with string interpolation.

#### Actual Behavior

Database can be accessed remotely, without a login

#### Possible Fix

See above

#### Steps to Reproduce

See above

#### Context

High

#### Your Environment

All

**Comment by Dillon-Brown** [comment]
Hi @samplonius, please raise all suspected security issues through the SuiteCRM securiity email security@suitecrm.com as explained in the README. Thanks.
