### ISSUE TITLE
Quick Create Plus on top-right 

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#433]
When hovering over the plus sign on the top-right of the responsive theme, the dropdown appears. Due to the gap between the top bar and the dropdown, the dropdown will sometimes disappear when moving cursor over the gap.

**Comment by vogelap** [comment]
That happens here too.

**Comment by ghermans** [comment]
+1, have the same issue here.

**Comment by horus68** [comment]
confirmed as an erratic behaviour

**Comment by digitalmcgrath** [comment]
I was having this issue as well. After upgrading to 7.3.1 it seems to have been fixed for me.

**Comment by ghermans** [comment]
Nope , i did a clean install from 7.3.1 and the issue is still there. tested with Chrome & Firefox

**Comment by digitalmcgrath** [comment]
This is strange... I have two installations on 7.3.1. One was an upgrade from 7.3 and the issue doesn't seem to be present. The other was a clean install and the issue is present. I am guessing this is still an issue and I have some anomaly going on with my upgraded version.

**Comment by vic-t** [comment]
+1, Firefox and Chrome on Windows, SuiteCRM 7.3.1.
