### ISSUE TITLE
Scheduled Reports Not Working No Email Sending Report

### ISSUE THREAD

**Issue by dezinstudioz** [salesagility/SuiteCRM#4341]
Scheduled Not Working not sending email no error log

#### Issue

I created the scheduled reports for daily send report to email account but no email at the scheduled times..
#### Expected Behavior

No Email Send at the scheduled time.
#### Actual Behavior

Send scheduled report email daily.

**Comment by pgorod** [comment]
@dezinstudioz you better open a thread in the Forums so we can help you configuring your system. "Doesn't work for me" is not a bug report, and Github is for bug reports, you come here when you are sure the problem affects everybody else, and you have technical information to provide. 

Don't worry I'll help you out in [the forums](https://suitecrm.com/forum). Thanks.
