### ISSUE TITLE
Workflow not working if set date format for user is d/m/Y

### ISSUE THREAD

**Issue by anhnhatuit** [salesagility/SuiteCRM#4346]
**Issue:**
I've create a workflow to modify record update i change any value in any module and i using date format is: d/m/Y. When i modify record then workflow not working, i found the issue bellow:

    $beanDateEnteredTimestamp = strtotime($timedate->asUser(new DateTime($timedate->fromDb($bean->date_entered))));
            $beanDateModifiedTimestamp = strtotime($timedate->asUser(new DateTime($timedate->fromDb($bean->date_modified))));
            $thisDateEnteredTimestamp = strtotime($this->date_entered);
            switch($this->flow_run_on){
                case'New_Records':
                    // it is an invalid bean if the user modify it now because the affection need on new records only!
                    if(!empty($bean->fetched_row) ||
                        $beanDateEnteredTimestamp < $thisDateEnteredTimestamp) {
                        return false;
                    }
                    Break;

if day of date created record > 12 example (13/01/2017) then $beanDateEnteredTimestamp will return false
and day date created of workflow <12 example (10/01/2017) then return valid value

=>  $beanDateEnteredTimestamp < $thisDateEnteredTimestamp is true then workflow will ignore.

**Possible Fix**

Because strtotime not support d/m/Y format then need change to a format strtotime support example: Y-m-d
Note: You can find the code in modules/AOW_Workflow/AOW_Workflow.php, check_valid_bean function
**Steps to Reproduce**
Config workflow:
 Create a workflow that triggers on save of a Cases
 Have this workflow set the assigned user is any user..
Test:
  Create new case.
 Go to detail case then case need assigned to a user.

**Context**

**Your Environment**

SuiteCRM Version used: 7.8.9
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by pgorod** [comment]
A couple of questions...

1. How _exactly_ did you configure your cron jobs to run?

2. You should have two `php.ini` in your system, one for the web server, one for the CLI. What setting do you have for `date.timezone` in each of them?

On my Ubuntu 16.04, the locations of these files is this
Web server `/etc/php/7.0/apache2/php.ini`
Command-line `/etc/php/7.0/cli/php.ini`

**Comment by anhnhatuit** [comment]
Hi Pgorod,
1. I'm not using scheduler to run workflow. I config run workflow when on save record.
2. The error occur when user set date format is 'd/m/Y' in (Profile > Advanced tab > Date format). My TimeZone working well.

if d > 12 then strtotime function will return false because strtotime not support format (d/m/Y).

Example:
I've 2 date bellow:

- Bean created record: 29/09/2017 then result of `strtotime($timedate->asUser(new DateTime($timedate->fromDb($bean->date_modified))));` is **false**.
- Workflow configuration created: 10/01/2017 then reuslt of `strtotime($this->date_entered);` is NOT false (Because it understand 10 is month).

The opertion `$beanDateEnteredTimestamp < $thisDateEnteredTimestamp` will return True then workflow action ignore but actual then  Bean date created > Workflow date created

Thanks!

**Comment by pgorod** [comment]
Well if you fixed it you can make a Pull Request with the fix :-)

**Comment by anhnhatuit** [comment]
Hi @pgorod ,

Yes, How to contribute my fixed code to SuiteCRM?

Thanks!

**Comment by pgorod** [comment]
There is some documentation here 

https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM

But that is the more powerful, more complex, `git` from the command-line approach.

If you only need to edit one file and are not familiar with `git`, you can try [this guide](https://help.github.com/articles/editing-files-in-another-user-s-repository/) to edit directly from GitHub website.

Don't forget to change to branch hotfix-7.8.x before starting the edit.

**Comment by anhnhatuit** [comment]
Hi @pgorod,

I got it, many thanks!

Thanks!
