### ISSUE TITLE
Update of JJWDesign-Google-Maps to version 2.1.20

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#435]
Hi,

can somebody update the module JJWDesign-Google-Maps from version 2.1.18 to version 2.1.20 ?

https://github.com/jjwdesign/JJWDesign-Google-Maps

There are 2 important thinks :) 

----------------------------------------------------------------------------------------------------------

Version 2.1.20 Changes 05/25/2015

Improvements:

1.) Removed Google Adsense Code! No more ad units.

Version 2.1.19 Changes 01/29/2014

Improvements:

1.) Revising List View Map Buttons to be built thru buildMyMenuItem() method
2.) Target new window/tab for Google directions
3.) InfoWindows: Adding basic Google Maps View link for address

--------------------------------------------------------------------------------------------------------

Regards

Mikolaj

**Comment by vogelap** [comment]
I agree! Please make the update if possible. Thanks.

**Comment by Mausino** [comment]
Did somebody update somewhere the code ???

**Comment by mattlorimer** [comment]
Yes it has been updated to the latest version
