### ISSUE TITLE
Notes related to given contact don't appear on his history subpanel

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#4351]
#### Issue

Notes created using the __Related To:__ field with Contacts module don't appear on the given contact history subpanel

#### Expected Behavior

When you see the __note__ detailview the contact appears and when you check the contact history subpanel note is there too

#### Actual Behavior

When you see the __note__ detailview the contact appears but when you check the contact history subpanel note doesn't show

#### Possible Fix

I think the problem is that history subpanel __is filtering out__ the notes when the related field has __parent module set to Contacts__ because it's assuming that notes already have a `contact_id` field that should be use to link notes and contacts.

imho there's three possible way to fix this:
1. Repair contacts subpanel to show notes when related to module is contacts.
2. Change the notes controller to copy `parent_id` to `contact_id` when `parent_type` is __Contacts__
3. Remove __Contact__ option from the __Related to:__ dropdown so users must use __Contact:__ field

#### Steps to Reproduce

I'm going to create an example with 3 notes and attached some images of it

1. Create a note with a contact and related to Accounts module, Note: __Bad Picture :(__
2. Create a note with a contact and without any relation, Note: __ok picture ¯\_(ツ)_/¯__
3. Create a note without a contact and related to Contacts module, Note: __Great Picture!__
4. You'll be able to see the __Bad Picture :(__ and __ok picture ¯\_(ツ)_/¯__ but not the __Great Picture!__ on the contact history subpanel and if you ask me, that is pretty sad

![selection-03-2017-09-30](https://user-images.githubusercontent.com/6874136/31051796-2cf153f2-a62f-11e7-8839-fe72896b928b.png)

![selection-05-2017-09-30](https://user-images.githubusercontent.com/6874136/31051795-2ce6caf4-a62f-11e7-8830-7c4ca2f4c962.png)

#### Context

I got a report of some missing notes from a client that use them to track several files on their contacts.

To fix it, I updated the notes table copying `parent_id` to `contact_id` when `parent_type` is set to __Contacts__

That took care of the problem in the meanwhile.

#### Your Environment

- SuiteCRM Version used: 7.9.5
- Browser name and version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Environment name and version:
  - mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
  - PHP Version 5.6.31-6+ubuntu16.04.1+deb.sury.org+1
  - Apache/2.4.18 (Ubuntu)
- Operating System and version:
  - Distributor ID: neon
  - Description: KDE neon User Edition 5.10
  - Release: 16.04
  - Codename: xenial

**Comment by vaudoin** [comment]
(Not sure if that's the best way to contribute...)

Possible Fix n°2 suggested by @cumanacr would be
**1- Update database**
UPDATE notes set parent_id = contact_id where parent_type = 'Contacts' and contact_id is not null

**2-Modify module/Notes/controller.php**
```
$GLOBALS['log']->debug('PERFORMING NOTES SAVE');

// 20171017 VAU GitHub Bug #4351 : Contacts notes do not appear in history
if (!empty($_REQUEST['parent_type']) && !empty($_REQUEST['contact_id']) && $_REQUEST['parent_type'] == 'Contacts'){
	$_REQUEST['parent_id'] = $_REQUEST['contact_id'];
}
```
