### ISSUE TITLE
Issue on "group user"

### ISSUE THREAD

**Issue by centoasa** [salesagility/SuiteCRM#4352]
Just create a group user, and every time I recall this group here the error:
Warning: Smarty error: unable to read resource: "modules/Users/tpls/DetailViewHeader.tpl" in /mydirectory/
![schermata 2017-10-01 alle 16 38 38](https://user-images.githubusercontent.com/5500935/31055691-0526370a-a6c7-11e7-8509-d408e37271d3.png)
htdocs/suitecrm/SuiteCRM-7.9.5/include/Smarty/Smarty.class.php on line 1094

**Comment by pgorod** [comment]
You need to check your permissions; but this is an issue for the forums, not for Github. Please close this thread here and open a thread in the forums.

Don't forget to include information about your OS, PHP version, SuiteCRM version...

**Comment by centoasa** [comment]
Sorry, close here and open on forum.
