### ISSUE TITLE
Suggestion - email to admin if new update exist (same as joomla)

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4354]
#### Issue

System by mail will notice admin if SuiteCRM has update. It simply send an email to admin and will notice his/her (or other users) that new update is available.

It's implement in joomla! and it's very practicable. I think that more of SuiteCRM instancies will actual if will the admins notice.

Also will nice.. if will in SuiteCRM change log.. that user will see that everybody in @salesagility working on this project.

People need more to see that many people hard working on better future of CRM world  

Please add your vote that you like it and will have more value for @salesagility team 👍

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - email to admin if new update exist (same as joomla)](https://trello.com/c/roINli1x/226-suggestion-email-to-admin-if-new-update-exist-same-as-joomla)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
