### ISSUE TITLE
Postfix dovecot using letsencrypt sends mail but fails when receiving 

### ISSUE THREAD

**Issue by mosesmwale** [salesagility/SuiteCRM#4359]
Am using Ubuntu 16.04.2 LTS

From mail.log
:connect from mail-io0-x22d.google.com[2607:f8b0:4001:c06::22d]
:Anonymous TLS connection established from mail-io0-x22d.google.com[2607:f8b0:4001:c06::22d]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
:NOQUEUE: reject: RCPT from mail-io0-x22d.google.com[2607:f8b0:4001:c06::22d]: 454 4.7.1 <admin@xxxxxxxxx.org>: Relay access denied; from=<xxxxxxxx@gmail.com> to=<admin@xxxxxxxx.org> proto=ESMTP helo=<mail-io0-x22d.google.com>
:disconnect from mail-io0-x22d.google.com[2607:f8b0:4001:c06::22d] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7

postconf -n 
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases
append_dot_mydomain = no
biff = no
broken_sasl_auth_clients = yes
disable_vrfy_command = yes
home_mailbox = Maildir/
inet_interfaces = all
inet_protocols = all
mailbox_size_limit = 0
mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
mydomain = mail.isoftcom.org
myhostname = mail.isoftcom.org
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
myorigin = /etc/mailname
readme_directory = no
recipient_delimiter = +
relayhost =
smtp_tls_note_starttls_offer = yes
smtp_tls_security_level = may
smtpd_banner = $myhostname ESMTP $mail_name
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtpd_helo_restrictions = reject_non_fqdn_helo_hostname,reject_invalid_helo_hostname,reject_unknown_helo_hostname
smtpd_recipient_restrictions = permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_sasl_auth_enable = yes
smtpd_sasl_local_domain =
smtpd_sasl_path = private/auth
smtpd_sasl_security_options = noanonymous
smtpd_sasl_type = dovecot
smtpd_tls_cert_file = /etc/letsencrypt/live/mail.isoftcom.org/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/mail.isoftcom.org/privkey.pem
smtpd_tls_loglevel = 1
smtpd_tls_received_header = yes
smtpd_tls_security_level = may
virtual_alias_maps = hash:/etc/postfix/virtual

dovecot -n
# 2.2.22 (fe789d2): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.4.13 (7b14904)
# OS: Linux 4.9.15-x86_64-linode81 x86_64 Ubuntu 16.04.2 LTS
auth_mechanisms = plain login
mail_location = maildir:~/Maildir
namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}
passdb {
  driver = pam
}
protocols = " imap pop3"
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}
service imap-login {
  inet_listener imap {
    port = 143
  }
}
service pop3-login {
  inet_listener pop3 {
    port = 110
  }
}
ssl = required
ssl_cert = </etc/letsencrypt/live/mail.isoftcom.org/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.isoftcom.org/privkey.pem
userdb {
  driver = passwd
}

where am i going wrong

**Comment by pgorod** [comment]
You're going wrong posting this here, instead of in [the forums](https://suitecrm.com/forum/)... :-)

If this is a request for help with your configuration, it belongs there. Here you just post bugs in the main product for the developers to look at.

**Comment by mosesmwale** [comment]
okay thanks
