### ISSUE TITLE
Duplicated language key - LBL_EDIT_FIELDS

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#436]
Duplicated language key but different value will be override when used:
https://github.com/salesagility/SuiteCRM/blob/master/modules/ModuleBuilder/language/en_us.lang.php

lines 379/381
'LBL_EDIT_FIELDS'=>'Edit Custom Fields',
'LBL_EDIT_FIELDS'=>'Edit Fields',

**Comment by likhobory** [comment]
There are much more duplications. See attachment:
https://yadi.sk/d/G782bzupir7Vb
