### ISSUE TITLE
Cannot use Dropdown Editor, javascript errors

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#4361]
I cannot use the dropdown editor, it does not load the javascripts properly, in fact it stops working after it encounters the error shown below.
The problem I cannot move or edit any of the fields in the dropdown editor.
It also does not matter whether you use Chrome or Firefox ... both have the same problems

#### Issue

Before I did this I used *all* of the js repair functions to make sure that I start with a clean sheet!
When selecting *ANY* (at least in my case) of the dropdowns on the left the following javascript errors below occur and basically stop the editing of anything as the javascript required for the dropdown stuff is not loaded properly:

error adding script  sugar_grp1.js:453:76
SyntaxError: expected expression, got '<'
Stack trace:
globalEval/<@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:445:141
globalEval@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:445:107
evalScript@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:452:6
updateContent@SUITECRM/modules/ModuleBuilder/javascript/ModuleBuilder.js?v=YgfFb8Znjg23F_OdH0Qfsg:601:17
handleTransactionResponse@SUITECRM/cache/include/javascript/sugar_grp1_yui.js?v=YgfFb8Znjg23F_OdH0Qfsg:55:4420
handleReadyState/this._poll[c.tId]<@SUITECRM/caache/include/javascript/sugar_grp1_yui.js?v=YgfFb8Znjg23F_OdH0Qfsg:55:3933
  sugar_grp1.js:453:111
Array [ "<script> 				$(function(){ 					$('…", "", " 				$(function(){ 					$('.editIma…", "	" ]  sugar_grp1.js:453:126
error adding script  sugar_grp1.js:453:76
SyntaxError: expected expression, got '<'
Stack trace:
globalEval/<@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:445:141
globalEval@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:445:107
evalScript@SUITECRM/cache/include/javascript/sugar_grp1.js?v=YgfFb8Znjg23F_OdH0Qfsg:452:6
updateContent@SUITECRM/modules/ModuleBuilder/javascript/ModuleBuilder.js?v=YgfFb8Znjg23F_OdH0Qfsg:601:17
handleTransactionResponse@SUITECRM/cache/include/javascript/sugar_grp1_yui.js?v=YgfFb8Znjg23F_OdH0Qfsg:55:4420
handleReadyState/this._poll[c.tId]<@SUITECRM/cache/include/javascript/sugar_grp1_yui.js?v=YgfFb8Znjg23F_OdH0Qfsg:55:3933
  sugar_grp1.js:453:111
Array [ "<script> addForm('dropdown_form'); …", "", " addForm('dropdown_form'); addToVal…", " " ]  sugar_grp1.js:453:126

#### Expected Behavior

I should be able to change the display fields or change the order of the dropdown items including custom items.

#### Actual Behavior

Cannot edit/change anything.

#### Possible Fix

I am not sure at all

#### Steps to Reproduce

1. Load the admin module (top right -> user -> Admin)
2. select "Dropdown Editor" (SUITECRM/index.php?module=ModuleBuilder&action=index&type=dropdowns)
3. open the javascript console (howto depends on the browser)
4. select any of the dropdowns 
5. see the errors in the console
6. click on any of the dropdown items or try to move them
7. does not work

#### Context

annoying as I can't delete, edit or move items

#### Your Environment

* SuiteCRM Version used: LATEST
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest firefox or chorme
* Environment name and version (e.g. MySQL, PHP 7): N/A 
* Operating System and version (e.g Ubuntu 16.04): N/A

**Comment by Dillon-Brown** [comment]
@jobst I'm unable to replicate in 7.9.6 or 7.8.7. Was this an upgrade or a fresh install? I'd check to see if this is a caching problem.

**Comment by jobst** [comment]
@Dillon-Brown this is a 7.9.6 install that comes from a very long path of upgrades (starting in 2003) and a move from SugarCRM to SuiteCRM about 2 years ago ....

I have had a look but I am at a loss on how to actually debug this, hence why I wrote "I am not sure at all" under "Possible Fix". I have never dug into this part of the CRM(s).

**Comment by gunnicom** [comment]
My findings:

SuiteCRM 7.8.24.
\modules\ModuleBuilder\views\view.dropdown.php
Line 73:
`$smarty->assign('editImage', SugarThemeRegistry::current()->getImage( 'edit_inline', '',null,null,'.gif',$mod_strings['LBL_EDIT'], true, '.gif'));`

In a working instance this assignment is:
`\"<img src=\\\"themes\\\/Suite7\\\/images\\\/edit_inline.gif?v=EqQwYjHBVLFFa39luHNiqg\\\"     alt=\\\"Bearbeiten\\\" \\\/>\"`

In the not working it is:
`<span  data-orig=\"edit_inline.gif\" class=\"spr_d6673cb7639876475ffc9e56aeb6bfdd\" title=\"Bearbeiten\"><\/span>`

Problem here is the missing quotes around the tag. Did not dig to that place yet.
I am right now looking in include\SugarTheme\SugarTheme.php function getImage(...), but maybe it is in the cache somewhere.
I for now do not understand why once i get a `<span>` and one time i get an `<img>`

**Comment by gunnicom** [comment]
Ok, as workaround you can edit config_override.php and edit:

$sugar_config['use_sprites'] = false;

Problem is that when using sprites the quotes are not added. I do not know how to change that in a safe way without breaking things somehwere else.
@Dillon-Brown Is this enough info that someone from salesagility can fix it? For me i can live with the workaround for now.

**Comment by Dillon-Brown** [comment]
@gunnicom That should be enough info to look into this further, thanks for the assistance.
