### ISSUE TITLE
Send Test Button without Label 7.9.5

### ISSUE THREAD

**Issue by rainolf** [salesagility/SuiteCRM#4364]
#### Issue

After creating Campaign, in Campaign Details View.
Selecting Action -> Send Test
The Send Test View does not have Send Label in Action Button
![send test](https://user-images.githubusercontent.com/2652556/31169555-4c9aafd8-a8f9-11e7-8f2f-83066691fa19.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by horus68** [comment]
Please edit your issue and enter your environment details (specially SuiteCRM version)

**Comment by horus68** [comment]
@Dillon-Brown confirmed in the demo version for 7.9.6
https://demo.suiteondemand.com

**Comment by Dillon-Brown** [comment]
I've gone ahead and fixed the missing label issue in #4241 but i'll create a new PR for @horus68's issue as it's present in both 7.9.x and 7.8.x. Thanks guys.
