### ISSUE TITLE
Unable to reset user password or send test email.  PHP Errors in Logs

### ISSUE THREAD

**Issue by laymonk** [salesagility/SuiteCRM#4365]
#### Issue
* This is a new deployment of v7.9.5 on ubuntu 16.04, using php7 (apache2 with php-fpm)

**cannot reset user password**
* I add a user, but no email is sent to them and I don't see any forms for setting a password.
* So, I edit user, and click the 'actions' dropdown, and then 'reset password'  and the system basically freezes .. until timing out (I see the timeout in the logs)
* I have repeatedly tried this since yesterday .. using various browsers (firefox, various chrome variants) and various OS desktops (debian, windows, osx) and this is consistent

**cannot send test email**
* I am not sure what the workflow for adding users is .. but guessed that the user creation form is possibly lacking password fields because it's email driven.
* So, given the above challenge with creating user accounts, I then proceeded to test that email sending is working .. 
* However, navigating to the email settings .. and trying to  send test email does not work .. 
  * using ssl fails, possibly expectedly since the ssl cert in use with suitecrm is still a self-generated one
  ```
  Error:SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
  ```
  * using TLS (this is expected to work), says 'performing task, one moment please' but nothing happens until it times out

**Errors in apache logs**
* Related to general theme/widget issues .. repeatedly, and flagging various widgets as one navigates the system
```
Got error 'PHP message: PHP Warning:  Declaration of SugarWidgetSubPanelEditSecurityGroupUserButton::displayDetail($layout_def) should be compatible with & SugarWidgetField::displayDetail($layout_def) in /var/www/include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php on line 0\nPHP message: PHP Warning:  Declaration of SugarWidgetSubPanelEditSecurityGroupUserButton::displayHeaderCell(&$layout_def) should be compatible with SugarWidgetField::displayHeaderCell($layout_def) in /var/www/suitecrm/include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php on line 0\nPHP message: PHP Warning:  Declaration of SugarWidgetSubPanelEditSecurityGroupUserButton::displayList(&$layout_def) should be compatible with SugarWidgetField::displayList($layout_def) in /var/www/suitecrm/include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php on line 0\n', referer: https://crm.example.com/index.php?module=EmailMan&action=config
```
* Possibly relating to the failure to send test email
```
[Wed Oct 04 11:40:30.672581 2017] [proxy_fcgi:error] [pid 463:tid 140005171185408] (70007)The timeout specified has expired: [client 192.168.10.67:57065] AH01075: Error dispatching request to : (polling), referer: https://crm.example.comt/index.php?module=EmailMan&action=config
```
#### Possible Fix
* I notice today there is a v7.9.6 and I am tempted to deploy that, but I see no direct confirmation in the [release notes](https://suitecrm.com/wiki/index.php/Release_notes_7.9.6) that the issues I'm seeing have been addressed
* My only previous experience of deploying SuiteCRM was better than this and was with the 7.8 LTS track, and I loved the option of being able to choose themes.  This is an option too, but I worry about the very long-term support of the 7.8 series 

#### Steps to Reproduce
* As described above 

#### Context
* Unable to add new users and thus unable to use the system

#### Your Environment
* SuiteCRM Version used: 7.9.5
* Browsers (variously on windows, debian jessie, osx sierra): 
  * Firefox ESR 52.3.0 (64-bit) .. 
  * Google Chrome 61.0.3163.100  (64-bit) .. 
  * slimjet & vivaldi (which are based on Chromium 59.x (64-bit))
* Environment:  Apache2.4 with php-fpm (php7), MySQL (MariaDB 10)
* Operating System and version: Ubuntu 16.04

**Comment by horus68** [comment]
Github is just for bugs on the core system. Please use the forum for issues related with your setup.
https://suitecrm.com/forum/index
Also take a look into the guide on User management:
https://suitecrm.com/wiki/index.php/Userguide#Managing_User_Accounts

**Comment by laymonk** [comment]
Million thanks for responding, @horus68  ..

But the issues I have seem to be around the core system, and I followed your deployment guide .. and the system does work, apart from these issues I have reported here.

Thanks for directing me to the userguide .. but what is described there does not look like what SuiteCRM 7.9.5 now looks like .. for example, there is now no 'Password' tab .. 

Please, can you point me to the milestones for the SuiteCRM 7.8 series ?  I think I will save time and re-deploy that, especially if it will be supported for a long time ..

**Comment by horus68** [comment]
There is a password tab on 7.9.x versio... you need to configure things first.
1- Enter Administrator / admin /

2- Enter "Password Management" / "Enable System-Generated Passwords Feature" (untick)
![suitecrm_password_system](https://user-images.githubusercontent.com/3055443/31181396-1e1bef58-a919-11e7-8d5b-f5fa10aaa764.png)


Then go to Administrator / Admin / User management / Edit
and the password tab is there!
![suitecrm_password_user](https://user-images.githubusercontent.com/3055443/31181440-3993e678-a919-11e7-99fb-a6a4f69fc377.png)


As you can see... forum questions first!
**Please close this issue**

And the download to update and all versions are here: https://suitecrm.com/download

**Comment by laymonk** [comment]
Thanks again, @horus68  .. 

Indeed, unchecking that option now offers a password tab for new accounts .. although it does not offer me a password tab for accounts already created.  For accounts already created, we still only have the  'actions tab' for managing them.  In any case, I can now at least get users on the system 

So, I believe my primary issue is SuiteCRM's failure to send emails.  Seems to fail silently, and there is no log I can identify that may help identify why it's failing .. any suggestions on how I could troubleshoot mailing issues.  I am the admin for the mail server, and it is in active use from other systems.  So, issue is not with mail server

I will close this issue .. and use the forum .. thanks for your support ..

**Comment by ftoledo** [comment]
I have similar issu . Just hang when resete user password.
I notice that disable my ipv6 stack just work again whitout delay.

Can i disable the use of ipv6 from suitecrm mailer?
