### ISSUE TITLE
files.md5 sets $md5_string_calculated but here $md5_string used

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#4367]
Dont know if this has any impact or if it is just deprecated, but looks wrong to me
$md5_string_calculated : https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/files.md5#L3
$md5_string : https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/ModuleInstall/ModuleScanner.php#L665

**Comment by pgorod** [comment]
@gunnicom how did you do those nice-looking code references? Cool! Can you share the source markdown, or point me to a tutorial? I searched but couldn't find it...

**Comment by horus68** [comment]
> how did you do those nice-looking code references? Cool! Can you share the source markdown, or point me to a tutorial? I searched but couldn't find it...
@pgorod 
1- Navigate to a file on Github
2- Click the line number (shift for more then one line)
It will change the browser URL
3- Copy the URL on the browser search bar
5- Past the URL into a message
6- Preview, submit, done!

**Comment by pgorod** [comment]
Oh, ok! I knew that feature (you taught it to me!) but I didn't realize it had been improved. Thanks!
