### ISSUE TITLE
PDF Template Editor Shows Only HTML

### ISSUE THREAD

**Issue by pstevens71** [salesagility/SuiteCRM#4375]
#### Issue
When you try and edit a previously created PDF template the editor only shows HTML.  You don't get the WYSIWYG editor.  I have tried this in the demo installation and can confirm that this is also a bug in the demo version.

Just to be clear this is not the same as #3934 

#### Expected Behavior
When you edit a PDF Template you should get the WYSIWYG editor to be able to edit the template.

#### Actual Behavior
The PDF Template editor only shows HTML and is difficult to edit the PDF  Template.

#### Possible Fix
??? Not a programmer, not sure.

#### Steps to Reproduce
1. Create a PDF Template (any one it doesn't matter).
2. Edit that template (or any existing template).
3. The editor will only show HTML.

#### Context
I think this is high priority as you will not be able to edit templates that you would likely be sending every day like quotes and invoices, etc.

#### Your Environment

* SuiteCRM Version used:  7.9.6 (also a problem in 7.9.5)
* Browser name and version Version 61.0.3163.100 (Official Build) (64-bit)
* Environment name and version MySQL and PHP 5.6
* Operating System and version : Uknown, but it happens on the demo version on SuiteCRM, so it's not a problem with my particular environment.
![pdf template editor]

(https://user-images.githubusercontent.com/29544935/31285505-7a7fcb04-aa89-11e7-8fe1-9c69ba1f3e53.jpg)

**Comment by rasheid** [comment]
I can verify this on 7.9.6. I am also having this issue

**Comment by centoasa** [comment]
Also for me!

**Comment by pstevens71** [comment]
Confirmed... applied fix 4417 and it works!  Thank you!

**Comment by centoasa** [comment]
with latest release 7.9.7 works well!

**Comment by javerrivas** [comment]
Hi,
I update to 7.9.7 Works but apears he simbol  Â  in the spaces.

Can you help us?  Thank you.
