### ISSUE TITLE
Compose email buttons & labels show 'undefined' after 7.8.7 upgrade

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#4379]
#### Issue
buttons in compose email client show labels 'undefined' - see screenshot. button icons are displaying correctly. 

#### Expected Behavior
Correct button labels are shown. 

#### Actual Behavior
Happens in both - when you invoke email composer from a lead/contact or from the email module.   

#### Possible Fix
unaware

#### Steps to Reproduce

1.invoke email composer from a lead/contact or from the email module.

#### Context
Users get quite confused as they dont know what buttons do. 

#### Your Environment

* SuiteCRM Version used: 7.8.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 11 and Chrome 61.
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.23, MySQL 5.6.37
* Operating System and version (e.g Ubuntu 16.04):  CentOS Linux release 7.4.1708

![pastedgraphic-2](https://user-images.githubusercontent.com/18371928/31318446-d9b9f05a-ac4a-11e7-95b1-60c9435bebea.png)

**Comment by pgorod** [comment]
I'm also seeing this in a 7.8.7 system. I searched for a relationship with our missing labels issue #4291, but I can't find it. It looks like this is caused by something else, unless I'm mistaken.

**Comment by Dillon-Brown** [comment]
@pgorod Should be unrelated to the label issue's as the label removal PR's are only in 7.9.x.

**Comment by evgu** [comment]
@gymad, tested. Fix resolved the issue on our CRM instance (7.8.7).
