### ISSUE TITLE
7.9.6 Cannot view account details

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#4380]
#### Issue
Clicking on account details returns an error:

#### Expected Behavior

The account detail should be displayed.

#### Actual Behavior

The following error message is displayed:
There was an error processing your request, please try again at a later time.
If this error persists, please have your administrator disable Ajax for this module

#### Steps to Reproduce

1. Go to the account module and click on any row on the name field.

#### Your Environment

* SuiteCRM Version used: 7.9.6
* Browser name and version:  Firefox/56.0
* Environment name and version: mysql 14.14, PHP 5.4.45
* Operating System and version: debian wheezy

**Comment by horus68** [comment]
@Dillon-Brown  Confirmed in the official demo. Note: it works if you click the grey pencil icon. Error fires if you click on the account name.
![accounts_issue4380](https://user-images.githubusercontent.com/3055443/31334380-086d4afa-ace6-11e7-8cd0-dc48c2cab749.png)

**Comment by Dillon-Brown** [comment]
Thanks @horus68. I'm still unable to reproduce this locally but i'll mark this as a high priority while we investigate.

**Comment by stenfalp** [comment]
Same problem on the Quotes module :(
