### ISSUE TITLE
Are these "<!--->" there for any purpose?

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#4387]
https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/themes/SuiteP/modules/Calendar/tpls/settings.tpl#L66

If it is an empty comment there is at least one dash missing. And if it is an empty comment, then it is not useful, as it is empty.
Or has it some purpose in the theme engine?
Or is it used for commenting the html inbetween two occurences of this?
Found them at some more places.

**Comment by Dillon-Brown** [comment]
@gunnicom No usage that I can see. Should be able to safely remove.

**Comment by gunnicom** [comment]
@Dillon-Brown As it is now, it does comment out the HTML in between two of these, like you can see in the file above.
What about this HTML within this comment?

**Comment by Dillon-Brown** [comment]
It looks like GitHub is marking the HTML between these two lines are commented but it shouldn't be. The comments are closed and the HTML is in use.
