### ISSUE TITLE
TinyMCE or SuiteCRM strips barcode tags in PDF-Templates

### ISSUE THREAD

**Issue by MaMuk** [salesagility/SuiteCRM#4389]
#### Issue
When editing a PDF Template in HTML mode, to add a` <barcode>` element it gets stripped.

#### Expected Behavior
Barcode tags are saved in the PDF templates

#### Actual Behavior
TinyMCE strips these tags, so that a barcode will generated when you use generate a PDF.

#### Possible Fix
Fix settings of TinyMCE to allow those tags to be saved. When you add the tags directly in the database, thus side stepping TinyMCE it works without problems. http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/TinyMCE/Modifying_the_TinyMCE_Editor/

Maybe it's not related to TinyMCE at all since there is similiar build in behavior in SuiteCRM itself:
see #3672

#### Steps to Reproduce
1. Create or Edit a PDF Template
2. Open the HTML view of the document body
3. Add a barcode tag to the source `<barcode code="978-0-9542246-0" type="ISBN" height="0.66" text="1" />`
4. Click Update

#### Your Environment
* SuiteCRM Version used: Version 7.9.5 
* Browser name and version: Firefox Nightly (58.0a1)
* Environment name and version: PHP Version 5.6.30-0+deb8u1, Mysql 5.5.55
* Operating System and version: Debian 9

**Comment by PedroErnst** [comment]
@MaMuk 

Added "barcode" as an allowed tag for TinyMCE

**Comment by chanml** [comment]
Hi, we still face this issue even though we are on suitecrm 7.11.18 and it still uses the older version of tinymce. But it works if barcode tag is updated directly into database.
![image](https://user-images.githubusercontent.com/885762/105136187-3755f180-5b2c-11eb-8123-25d36b629cdc.png)
