### ISSUE TITLE
Suggestion - new layout in studio for info icon on list view

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4391]
#### Issue

I suggest new layout in studio for each module.

We have editview, detailveiw, listview, popupview., filter, etc but info icon we can configure only by hardcode... 

I thing that will great help for each user which is using SuiteCRM because will add his/her additional data into info icon. And by admin will possible to choose which data will there in Studio for each module.

Please add your vote that you like it and will have more value for @salesagility team 👍 

![info_icon](https://user-images.githubusercontent.com/5773777/31353195-dc8ebf94-ad31-11e7-9d8d-e13ad88bf096.png)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - new layout in studio for info icon on list view](https://trello.com/c/PzeaS6Ni/227-suggestion-new-layout-in-studio-for-info-icon-on-list-view)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran I am asking again about look on this suggestion/enhacement

Reason is clear: Only 4 views you can't modify by SuiteCRM

1. Imported emials
2. Gantt view
3. Resource view
4. Infor icon popup

Why i am asking to info pop up view as important think on which we shouldn't forget?

Because, when you cant put all data to columns on listview the info icon is best choice to custom what type of informations you want see additionally 👍 It's great help to see more infomations that you didn't look on detailview of record but you see it in pop up window

Also will great if we can set the position of pencil and info icon on listview (will have own boxes in studio) as we can do this for edit + remove buttons for subpanels in studion-> module ->subpanels -> module from relationship

Here is example of last version SuiteCRM 
![2018-12-30_1821](https://user-images.githubusercontent.com/5773777/50549654-eb903100-0c60-11e9-912b-d07a2e9e1456.png)

**Comment by pgorod** [comment]
@Mausino I do like your idea but I'm afraid it is quite a task to dive into the complex Studio code and add a new view, and then change all the List views in the app to use that. It is feasible, of course, but takes quite some effort...
