### ISSUE TITLE
Suggestion - Map view upgrade 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4392]
What is problem in my company ???

that we need to see data on map.. is for us as breathing... we must visualize our data on maps.. because it's necessary... not only for me but also for others

Is it possible to add point A + B on map view from list view?

A. data filter (basic + advance)
B. column filter 

How can it work???.. I'm thinking on this way

A. user filter data and push search button in pop up window.. it will filter data and show on map (ans will show other icon where will clear (as in list view) that data was filtered

B: is possilbe show same columns on map view for datatable extension as we have in list view by default ???? will possible to change order of this columns as on listview?

Please add your vote that you like it and will have more value for @salesagility team 👍

![2017-10-09_2102](https://user-images.githubusercontent.com/5773777/31354153-91b9b100-ad35-11e7-8a4f-b89b4e9da3e0.png)

**Comment by horus68** [comment]
Maps needs a major re-work on features 👍 
1- Is SA going into that "road"?
2- Are they developing any new features? 
3- What features will they consider to be implemented if created by community?
4- Who have the knowledge to start coding some extra features?

**Comment by gunnicom** [comment]
5. Use something like [openlayers](https://openlayers.org/), so it would be easy to switch to openstreetmap.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - Map view upgrade](https://trello.com/c/R4hxvv1p/228-suggestion-map-view-upgrade)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - Map view upgrade](https://trello.com/c/R4hxvv1p/228-suggestion-map-view-upgrade)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
