### ISSUE TITLE
Unable to export large number of leads

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#4393]
#### Issue

Using SuiteCRM 7.8.6 - Unable to export large volume of leads. Exporting of  leads to excell works fine for small volumes, but not all leads. When I check "all" leads and "export," the browser page turns white and hangs every time. 

If you go to a module and select entire list without a filter in the search, the export fails with a database error. This occurs only if you have multiple pages in your list.

#### Expected Behavior

Export should work if entire list is selected.
#### Steps to Reproduce

1. Open leads module
2. Select all records
3. Export. If you have more than one page it will fail. With only one page it will work.

#### Your Environment

* SuiteCRM Version used: 7.8.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 56.0.1 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by gunnicom** [comment]
Maybe related:
https://github.com/salesagility/SuiteCRM/issues/3470

**Comment by dursuntosun** [comment]
My version is up to date. So this fix is allready applied.

**Comment by gunnicom** [comment]
That does not mean, that it may not be related. Same symptoms. Did you try the search for "%"?

**Comment by dursuntosun** [comment]
Yes, i try it but same result.

**Comment by pstevens71** [comment]
My guess is this is a function of your hosting.  Your probably running up against a few different things:
1. memory limit
2. timeout
3. Some hosting (godaddy) limit the number of database queries you can do at once.  I run into this when I'm trying to update too many records at once.

**Comment by dursuntosun** [comment]
But when i try it with account module, there is no problem. Only just leads module😂

**Comment by pstevens71** [comment]
That is puzzling, did you turn on error reporting?  If so what errors are displayed?

**Comment by dursuntosun** [comment]
When i check error log, there is no error. In the first page, there is no problem to export. When i try to export all records, there is no result just white page.
When i increase listview items per page from 50 to 500. I can export my records. I think the problem is other pages to export?

**Comment by gunnicom** [comment]
Did you check the apache error log or the suitecrm.log?

**Comment by dursuntosun** [comment]
I checked suitecrm.log, but there is no error. I could not check apache error yet.

**Comment by dursuntosun** [comment]
Sorry, this is my fault. I solve my problem.
