### ISSUE TITLE
Calendar ICAL URL ask for User / Password

### ISSUE THREAD

**Issue by leonardobarrientosc** [salesagility/SuiteCRM#4399]
#### Issue
If you copy the integration Ical URL and paste into Google Calendar "Add Calendar By URL" you get empty, debugging it with WGET i realized that username/password is required.

HTTP request sent, awaiting response... 401 not authorized
Username/Password Authentication Failed.

#### Expected Behavior
No auth should be required for Ical Integration URL.

#### Actual Behavior
HTTP request sent, awaiting response... 401 not authorized
Username/Password Authentication Failed.

#### Steps to Reproduce
1. Copy the ICAL Integration
2. Paste into wget URL
3. See the response

#### Your Environment
Ubuntu 14.04
php 7.0

**Comment by pgorod** [comment]
@Dillon-Brown other people are complaining in the forums, 
https://suitecrm.com/forum/installation-upgrade-help/16169-did-ical-sync-break-again-with-7-8-7-lts

it seems one of the recent security fixes made this link that should be public turn into a password-protected link...

**Comment by sanchezfauste** [comment]
We are experiencing the same problem since we upgraded to version 7.8.7. This is critical for us because most of our users have synchronized the SuiteCRM calendar with external systems.

**Comment by leonardobarrientosc** [comment]
Yes, i had to downgrade to 7.6.4 to keep it working. It’s a filter _check-auth issue

**Comment by timo12357** [comment]
I installed the patched HTTP_WebDAV_Server_iCal.php
Sync works but I cannot make scandinavian letters ÅåÄäÖö work, they are represented as ?????? in the calendar. The encoding direction in the adress:
http://myip/SuiteCRM/ical_server.php?type=ics&key=somekey&email=my.name@my.email.adress&encoding=iso-8859-1

Seems not to work anymore.

**Comment by daniel-samson** [comment]
@timo12357 Have you tried removing the encoding parameter in the url?

eg http://myip/SuiteCRM/ical_server.php?type=ics&key=somekey&email=my.name@my.email.adress

**Comment by timo12357** [comment]
Yes I have tried removing the encoding parameter. Unfortunately does not help.

**Comment by pgorod** [comment]
@Dillon-Brown is this supposed to be fixed in 7.9.7?

https://suitecrm.com/forum/suitecrm-7-0-discussion/16500-veiwng-calander-in-thunderbird#55604

Thanks!

**Comment by Dillon-Brown** [comment]
@pgorod This should be resolved in 7.9.7 and 7.8.8. There may be an issue with character encoding but so far we haven't been able to replicate it.
