### ISSUE TITLE
"Listview items per page" Admin setting affects API - max_results no longer working

### ISSUE THREAD

**Issue by JBrace1990** [salesagility/SuiteCRM#4400]
#### Issue

When using the REST API, you are unable to set max_results to return more (or less) items than the "Listview items per page" setting in System Settings.

#### Expected Behavior

max_results should modify how many items are returned from the API

#### Actual Behavior

API returns the amount set in "Listview items per page" admin setting

#### Steps to Reproduce

1. Set "Listview items per page" admin setting to any number (IE: 50)
2. Make an API call to get_entry_list at the instance: /service/v4_1/rest.php endpoint with max_results set to 1000.
3. See that only 50 items are returned

#### Context

This causes API calls requesting large amounts of data to take much longer, since you need to run 10 API calls instead of 1 to get 500 items

#### Your Environment

* SuiteCRM Version used: 7.8.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/a
* Environment name and version (e.g. MySQL, PHP 7): N/a
* Operating System and version (e.g Ubuntu 16.04): N/a

**Comment by PedroErnst** [comment]
As of SuiteCRM 7.9.7 I have tried reproducing this issue but no success. On my end I always get the amount of results requested as 'max_results', completely independent of the admin settings (as it should be).
