### ISSUE TITLE
On 7.8.7 LTS Workflow actions are not displayed on EditView

### ISSUE THREAD

**Issue by sanchezfauste** [salesagility/SuiteCRM#4401]
After upgrade from version 7.8.5 to 7.8.7 if you edit a workflow you are not able to see the actions correctly.

#### Issue
If you edit an existant workflow, the actions are not displayed.

#### Expected Behavior
![expected](https://user-images.githubusercontent.com/10921800/31430107-278cf6f2-ae70-11e7-9a0c-d9be7c1c9e4e.png)

#### Actual Behavior
![actual](https://user-images.githubusercontent.com/10921800/31430096-1d1b7bf8-ae70-11e7-8731-74a8786e9abc.png)

#### Possible Fix

We think that the problem is caused by: https://github.com/salesagility/SuiteCRM/commit/13950998affd26551c53013b841f976337cd543a#diff-751d02865d72a3296e3e35e2db56ad47R155

If you revert this line, all works as expected.

#### Steps to Reproduce

1. Create new workflow with almost one action.
2. Save the workflow.
3. Edit the previously created workflow.
4. See that the action is not displayed correctly.

#### Context
This bug appears after upgrade from v7.8.5 to v.7.8.7

#### Your Environment

* SuiteCRM Version used: LTS 7.8.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 61.0.3163.100 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1 and mysql  Ver 14.14 Distrib 5.5.57
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by sanchezfauste** [comment]
Thank you @Dillon-Brown, your PR has solved the problem.

**Comment by sanchezfauste** [comment]
This issue is also present in 7.9.6 version.

**Comment by tdseward** [comment]
Just Upgraded to 7.9.7 and this issue is still present. 

![workflow_edit_notviewable](https://user-images.githubusercontent.com/18446764/32248842-585e62e6-be5d-11e7-961c-dc1a9ed53a65.JPG)

**Comment by sanchezfauste** [comment]
Maybe you can try to repair JS files.

**Comment by tdseward** [comment]
Ok so I have repaired my JS files and the issue is still persistent on any of the workflows that were created during the time of the bad code. 

Are these just gone or is there a way to recover them? 

It does appear to work correctly on any newly created workflows. But editing any older ones the problem still exists.

**Comment by pstevens71** [comment]
This issue exists in 7.9.9 as well.  I also did a quick repair and rebuild.  Any new or edited record displays this problem.
I get  the following errors in console.  However, when I follow the URL's they work???
/index.php?module=AOW_WorkFlow&action=getModuleFieldType&view=DetailView&aow_module=AOS_Quotes&aow_fieldname=stage&aow_newfieldname=aow_conditions_value[0]&aow_value=Delivered&aow_type=Value&rel_field=AOS_Quotes Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I've checked the error logs and there is nothing about this event there.
