### ISSUE TITLE
Security: Ability to echo out config & other sensitive files as authenticated user

### ISSUE THREAD

**Issue by philsjh** [salesagility/SuiteCRM#4407]
#### Issue
A blind file_get_contents() print to the browser allows authenticated users to view potentially sensitive files such as the SuiteCRM config.

#### Expected Behavior
Local files should not be retrievable, and there should be a whitelist for URLs.

#### Actual Behavior
Local files get printed to the browser.

#### Possible Fix
Remove this functionality entirely, or figure out a better way of retrieving remote URLs.

#### Steps to Reproduce
Visit this URL on any SuiteCRM or SugarCRM site

https://suite-install-url/index.php?module=Connectors&action=CallRest&url=config.php

#### Context
Should be high priority as it allows low privileged users access to database credentials, private keys and some other sensitive info.

#### Your Environment
SugarCRM CE 6.5.24
SuiteCRM 7.8.7

**Comment by Dillon-Brown** [comment]
Hi @philsjh, please raise all suspected security issues through the SuiteCRM securiity email security@suitecrm.com as explained in the README. Thanks.

**Comment by philsjh** [comment]
Apologies - have reported now.

Thanks
