### ISSUE TITLE
uploads folder getting larger

### ISSUE THREAD

**Issue by hemanthvaddi** [salesagility/SuiteCRM#4411]
The 'uploads' folder is getting larger (like around 8GB)

#### Issue
The uploads folder if it can be changed to an s3 or EFS, it would be better. Is it possible to do so? If yes how? 

#### Possible Fix
The uploads folder can be changed to (or) replaced with an s3 or EFS

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

Low storage space.

High Priority

#### Your Environment

* SuiteCRM Version used: 7.6.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7):  MySQL 14.14 & PHP: 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.4

**Comment by Dillon-Brown** [comment]
Hi @hemanthvaddi,

This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum). We use GitHub primarily for the reporting of Core SuiteCRM bugs and leave general questions and setup specific issues to the forums.

Thanks.
