### ISSUE TITLE
Save or "save and create new" calls end most of time in a blank page and call not saved.

### ISSUE THREAD

**Issue by zicrob** [salesagility/SuiteCRM#4413]
After 7.9.5 update, "save" or "save and create new" calls end most of time in a blank page and call not saved. Most of time, an edited call can't be saved at all. I have to delete the record and create a new one which is saved normally.

#### Issue

It happens only when modifying the recorded call. Nex recors are saved.
#### Expected Behavior
The record should be saved. In the case of "close and create new, the modified record should be saved and a new one should display, ready to get modified.

#### Actual Behavior
The crm displays a blank page and the record can't be edited.

#### Steps to Reproduce
Create a record of the call category, save it. Then open it to modify and try to save.

1.
2.
3.
4.

#### Context
Calling customers. The "call" records are used as programmed call (as reminders). When the call is done, I open the record for editing, write down the result of the call in the detail case, and save it. Most of time using "save and create new" button.
as far as I'm concerned, this is high as it makes me lose lost of time while working.

#### Your Environment

* SuiteCRM Version used: 7.9.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 56.0 x64
* Environment name and version (e.g. MySQL, PHP 7): libmysql - 5.1.73-PHP 4.3.8
* Operating System and version (e.g Ubuntu 16.04): Linux

**Comment by pgorod** [comment]
Blank pages are usually PHP fatal errors, meaning you should have a message in your php_errors.log (or equivalent).

But you should be asking this in the forums, not here, so please close this issue and open a thread there:
https://suitecrm.com/forum

Thanks!
