### ISSUE TITLE
Can't print PDF Templates 7.9.6

### ISSUE THREAD

**Issue by davidbqzt** [salesagility/SuiteCRM#4414]
Can't print Quote to PDF Template, I got 500 Error
Seems to be related with issues 3738, 4223 or 4237

#### Issue
I had four PDF templates on SuiteCRM 7.9.4, works fine I can edit, create new ones and print quote to PDF, then I upgrade to 7.9.5, edit one PDF Template y found some of the behavior described on issues 4223 and 4237, even though I edit and print PDF Template, but one day the CRM stop printing and when I try to do it generates a 500 error, I'm on a hostgator hosting I can't see to much logs, SuiteCRM log didn't generate any error message when the print to PDF fails.

People on https://suitecrm.com/forum/installation-upgrade-help/15857-pdf-templates-no-longer-working?limitstart=0 says to has the same issue

#### Expected Behavior
Is expected to print the quote to PDF

#### Actual Behavior
500 Error occur, no suitecrm.log while reproducing the error, can't access php error.log or http error log

#### Steps to Reproduce
1. Create new PDF Template
2. Create quote
3. Print quote to PDF Template
4. Blank page or 500 Error

#### Context
This error is very serious as you can't quote your clients anymore, others user says can't print invoces too, so I suggest to give high priority to this issue.
I wait until 7.9.6 release, and upgrade from 7.9.5 to 7.9.6 and the bug persists

#### Your Environment
* SuiteCRM Version used: 7.9.5 and 7.9.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 61.0.3163.100 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.4.45
* Operating System and version (e.g Ubuntu 16.04): Linux 3.12.74-213.ELK6.x86_64, is a hosting so not sure wich kind of Linux is this.

**Comment by Dillon-Brown** [comment]
Hi @davidbqzt, i'm unable to replicate on 7.9.6 or 7.8.7. Have you double checked permissions?

**Comment by davidbqzt** [comment]
Hi @Dillon-Brown I've have check file permissions 3 times as instructed in https://www.suitecrm.com/forum/suitecrm-7-0-discussion/2316-undefined-popup and in SuiteCRM installation instructions, and no luck.

The problem started on 7.9.5, 7.8.7 was fine

**Comment by davidbqzt** [comment]
I've just upgrade to 7.9.7, the problem persist and I haven't noticed another problem, with some labels that appears as "undefined", started at least since 7.9.6, but I haven't paid attention to it.
I read forums, about file permissions and delete cache, and did all that forums says but no luck with any of these problems.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
