### ISSUE TITLE
Editing a PDF template returns a previousely saved BODY

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#4416]
Using a fresh install of SUitecrm Version 7.8.7 Sugar Version 6.5.25 (Build 344) and ubuntu 16LTS with apache and PHP7.0 : 

Creating a quote works fine using the default template for quote. I can generate a quote in an opportunity with "print PDF".
Then when I **edit** I get an empty body as pictured.
If I click on HTML : its empty.

The same issue applies when creating an INVOICE template

![bug-quotesuitecrm](https://user-images.githubusercontent.com/26340942/31582810-e1655a5e-b18d-11e7-90ea-38c5dbe34a8b.png)

**Comment by Dillon-Brown** [comment]
Hi @hubyhuby, I'm unable to replicate this on 7.9.x or 7.8.x. Have you double checked permissions / cache?

**Comment by hubyhuby** [comment]
dear @Dillon-Brown , thanks for your quick reply and for the great work on this marvelous project!
It is kind of a funky bug, today I am back trying editing...I push edit and whaou it s not empty...
BUT when 
1) I modify it let say add "hello"
2)Save
3)Look at the page after the save. And say haha it works...
4)EDIT again...I have the **previous** document **without** "hello" I just added!

Bug catchers do you hear me ;)

**Comment by Dillon-Brown** [comment]
Hmm, something definitely strange seems to be going on with caching. I was able to replicate this in 7.8.7 after a repair and rebuild, I thought this had already been fixed.... Will keep investigating. Thanks.

**Comment by hubyhuby** [comment]
thanks a lot @Dillon-Brown ,
chmoded the thing with  "sudo chmod -R 777" but it doesn t change anything.
Overall I am very satisfied with suitecrm, just this minor bug I have

**Comment by hubyhuby** [comment]
Just runned it with chromium and I have the same thing as with my firefox.

**Comment by hubyhuby** [comment]
Just updated to 7.8.8; it fixes the bug!
Thanks Dillon
