### ISSUE TITLE
SuiteP - Dashboard inside Dashboard - Double clicking Column Heading on Dashlet

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#442]
First, Go to Homepage by clicking the "SuiteCRM" on the top-left of the CRM.
Then, when double clicking on a Column's Heading on a Dashlet, i.e: "Name" or "Subject", It creates a 2nd Dashboard at that location. This 2nd dashboard seems to be a copy of the 1st, just on a smaller scale.

Additional Dashboards can be created by clicking on a Column Heading on a different Dashlet than the one originally used. 

Does not seem to occur in v7.2.2

**Comment by rhessus** [comment]
+1

**Comment by rhessus** [comment]
+1

**Comment by rhessus** [comment]
Same issue in v7.5.3

**Comment by rhessus** [comment]
Thanks @johnM2401 for the fix

**Comment by ijdavie** [comment]
This Pull Request fixes the issue with SuiteR but this issue still stands for SuiteP.

**Comment by shogunpol** [comment]
@johnM2401 , the issue has been tested on recent version SuiteCRM(7.7.7) and not appear in any theme, can you confirm is not an issue any  more, and if not appear can you close an issue.

**Comment by johnM2401** [comment]
Yep, Tried in all 3 themes, on multiple tabs, in 7.7.7.
No longer seems to be an issue.
