### ISSUE TITLE
Suggestion - Effective way to remove record from Target List if you're database is 100+

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4421]
This is suggestion.

I think that is necessary to add Target list  sub-module to each detail view of record as sub-panel which can be added to Target list.

Example:

In some target list you have 800 companies... and this target list is using to campaign. 
Only one way how you can remove this company from target list is go to account sub-panel and searching. There is no exist filter and if you set up 15 record max in sub-panel.. your can spend 54 times to click next records in sup-panel (800/15=54)

Suggestion: 

Add target list sup-panel to records in which can be sub-panel use or add filter button to each sub-panel  in target list that will easily to find record and remove it from target list sub-module.

Easy is select record.. Hard is find it and remove from Target list.

**Comment by pgorod** [comment]
@Mausino maybe you can try something like this:

http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Module_Framework/Subpanels/Examples/How_to_Add_a_Target_List_Subpanel_for_Leads_and_Contacts/

If that works correctly, and satisfies your needs (which I agree, are probably also the needs of many more people), we could try adding that into the product (not in custom dir).

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - Effective way to remove record from Target List if you're database is 100+](https://trello.com/c/3qMPrKsv/231-suggestion-effective-way-to-remove-record-from-target-list-if-youre-database-is-100)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
