### ISSUE TITLE
Undefined index: moduleList

### ISSUE THREAD

**Issue by johnbendi** [salesagility/SuiteCRM#443]
I'm getting this messages in nginx log:

```
Undefined index: moduleList in /usr/share/nginx/html/suitecrm/modules/AOW_WorkFlow/AOW_WorkFlow.php on line 89
```

what's the issue and how can I get rid of it?

**Comment by paulgodley** [comment]
Hi @johnbendi, I apologise for the delay on responding.  I have just been allocated this call and I will get back to you as soon as possible.  It looks like this may be the cron job causing this (as the arraylist may not be defined via the path the cron job takes).

**Comment by paulgodley** [comment]
Hi @johnbendi, can you please attach the log error with the surrounding entries (both proceeding and following)?

**Comment by paulgodley** [comment]
Alternatively, you could check that the  $app_list_strings['moduleList'] is not empty before the assignment on line 89 of AOW_Workflow.  To do this, simply wrap a check for !empty around the variable, as shown below:
`    function load_flow_beans(){
        global $beanList, $app_list_strings;

        
        if(!empty($app_list_strings['moduleList']))
        {
            $app_list_strings['aow_moduleList'] = $app_list_strings['moduleList'];

            if(!empty($app_list_strings['aow_moduleList'])){
                foreach($app_list_strings['aow_moduleList'] as $mkey => $mvalue){
                    if(!isset($beanList[$mkey]) || str_begin($mkey, 'AOW_')){
                        unset($app_list_strings['aow_moduleList'][$mkey]);
                    }
                }
            }

            $app_list_strings['aow_moduleList'] = array_merge((array)array(''=>''), (array)$app_list_strings['aow_moduleList']);

            asort($app_list_strings['aow_moduleList']);    
        }
        
    `

**Comment by JimMackin** [comment]
Closing pending input. Please comment or create a new issue if this is still an issue.
