### ISSUE TITLE
Usability / UX when editing field in detail view (contact, leads etc)

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#4430]
In suitecrm 7.8.8
The user experience for editing field in **detail view** is not very efficient.
1)Number of clicks is more important:
-In the old sugarcrm style :  1 click on the edit button + 1 click on the field + on click on save = 3 clicks
-In suitecrm: 2 clicks on the field (some times two times, because it s not always registered) + then one click to position where you wish to modify the field + one click to save +(sometimes you get the pop up save +1click) = 4 to 6 clicks

2) On description field it is not usable. Because when you hit ENTER you close the field instead of adding a line.

3)The edit icone on the right of a field doesn t apear all the time on my firefox 56 and chromium.
I think it apear on field I already double clicked.

4)this edit button seams to be not clickable. Is it normal ? In vtiger crm this icone works

**This is not an easy task. So here is food for thoughts :**

a) OVER a fields makes it editable

b) ONE click place your cursor where you clicked in this edited field. 
If it is a link you need to click on the side of the link or on the edit icone.

c)ONE click on the edit button edits the field (especially for "link fields")

d) Save the data by default when I click away from the field. + include an undo feature on the side of the field. In case it is a mistake save, we can revert to the previous state (if I load another page I cannot revert).

e) Enter doesn t save the field for descritpion fields and such (adress...)

PS: this is not important if you edit one contact per day.
But if you are in an average company working all day on the CRM, doing 100 edits per day...that s a top of the list feature :) After all the use of such system is interacting with a database.

**Comment by pgorod** [comment]
First of all, thanks for a thoughtful user experience/usability suggestion, I agree this is very important in a CRM.

A few comments:
- you can still use the SugarCRM style Edit button... 3 clicks. I think this has a hidden cost, not measurable by clicks: the cost of re-scanning the page to find your field, possibly in a different layout. I avoid the Edit screen whenever I can.
- we need to distinguish Inline Edit _bugs_ from design issues. I find it often fails (bugs), but I quite like the way it is designed. It was a killer feature when it came out.
- I don't think a simple Hover should trigger a field edit. It doesn't let you freely move your mouse around... it's too "nervous".
- a single-click triggering an inline edit is probably difficult to distinguish from a simple attempt to select some text from a field.
- I agree with making the Inline edit "pencil" icon clickable
- both this icon and then the "check" icon to commit the edit should be left-aligned, not right-aligned like they are now. They often appear so far away from the data that users don't even see them... I really should make a PR for this right away...
- you should tell your users to commit changes using the Enter key. That's by far the most efficient way (avoiding the confirmation pop-up), and practical when it's a text filed that you edited using the keyboard (less practical if it was a dropdown that you edited with your mouse).
- I like your idea of defaulting to a "save" when you click away from the field, but it does require the _Undo_ option which is harder to develop...
- also the issue with the multi-line fields (like description): that's unavoidable. You just need to teach people to use Shift-enter to make line-breaks.

**Comment by gunnicom** [comment]
I  count a double click as one action, not as two clicks.
For "I like your idea of defaulting to a "save" when you click away from the field, but it does require the Undo option which is harder to develop...", i am not sure about it. If you edit something by accident and click away, and so accidentally save it, that can lead to problems.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Usability / UX when editing field in detail view (contact, leads etc)](https://trello.com/c/CBwWl1gM/232-usability-ux-when-editing-field-in-detail-view-contact-leads-etc)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
