### ISSUE TITLE
PHP Fatal error when I try to edit or view subpanels on the modulebuilder

### ISSUE THREAD

**Issue by dflois** [salesagility/SuiteCRM#4431]
#### Issue
I can not edit or view subpanels on the modulebuilder. Whenever I press the link called Default placed on Available Subpanels folder, nothing happens

#### Expected Behavior
Edit or view subpanels on the modulebuilder.

#### Actual Behavior
I can not edit or view subpanels on the modulebuilder. Whenever I press the link called Default placed on Available Subpanels folder, nothing happens. The CRM add a fatal error in the error_log.

Thu Oct 19 17:58:24.551466 2017] [php7:error] [pid 12712] [client 10.100.32.46:64767] PHP Fatal error:  Class UndeployedSubpanelImplementation contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (AbstractMetaDataImplementation::getFileName) in /var/www/html/SuiteCRM/modules/ModuleBuilder/parsers/views/UndeployedSubpanelImplementation.php on line 52, referer: http://hostname/SuiteCRM/index.php?module=ModuleBuilder&action=index&type=mb

[Thu Oct 19 17:58:34.181583 2017] [php7:error] [pid 13800] [client 10.100.32.46:64774] PHP Fatal error:  Class UndeployedSubpanelImplementation contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (AbstractMetaDataImplementation::getFileName) in /var/www/html/SuiteCRM/modules/ModuleBuilder/parsers/views/UndeployedSubpanelImplementation.php on line 52, referer: http://hostname/SuiteCRM/index.php?module=ModuleBuilder&action=index&type=mb

#### Your Environment
PHP 7.1.9
SuiteCRM 7.9.7
CentOS 7

**Comment by pgorod** [comment]
I thought this was fixed already. But maybe there is a fix but it hasn't been merged yet? The only thing I'm sure of, is I've seen this before...

**Comment by pgorod** [comment]
Here: #4213

Are you sure you're on 7.9.7? Is your Issue different? Thanks.

**Comment by dflois** [comment]
![imagen](https://user-images.githubusercontent.com/19489692/31818499-bad1d8ea-b598-11e7-8e46-7f06a57130fd.png)

**Comment by dflois** [comment]
The issues #4213 and #4431 are related but differents. The scope for #4213 was all the layouts and the scope for this issue is only subpanels.

**Comment by pgorod** [comment]
I would take your word for it, no need for screenshots :-)

Are you a developer? Can you work out a solution from the previous fix in #4213? It seems like a parallel problem, in your case the function is named slightly differently (mentions `subpanel`).

**Comment by dflois** [comment]
I'll try it and I'll write the result when I get few minutes!

**Comment by dflois** [comment]
It works! 
Replace the definition for getFileName in _modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php_  with the defined functions _getFileName_ and _getFileNameInPackage_ from _modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php_

**Comment by pgorod** [comment]
Ok, cool! Do you want to make a PR for this?

https://help.github.com/articles/editing-files-in-another-user-s-repository/

make sure you switch to the `hotfix` branch before you start the edit to the file.
