### ISSUE TITLE
header images do not display correctly in PDF

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#4434]
#### Issue
Using a logo or a text in the header is something very common for a quote. Maybe 80% of the users.
Also it doesn t work.

#### Expected Behavior
When I put a header I expect it to be at the begining of my page.

#### Actual Behavior
My header is in the background of the exported PDF quote

#### Possible Fix
No idea

#### Steps to Reproduce

1.Open your quote template
2.add a text (and a logo optional) in the header field and SAVE
3.Export your PDF quote with "print PDF"
4. See the result in the PDF: the header is in the background

#### Context
Trying to make a quote

#### Your Environment
Ubuntu 16.04
apache 2.4
firefox and chrome
suitecrm 7.8.8

**Comment by hubyhuby** [comment]
I tried it with a much smaller logo and I get the same result as pictured previousely

**Comment by Dillon-Brown** [comment]
Unable to replicate with latest LTS. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.

**Comment by hubyhuby** [comment]
Dear @Dillon-Brown ,
I just upgrade to 7.8.18 and I get exactemmy the same bug.
Please reopen.
![screenshot at 2018-04-16 17-45-22](https://user-images.githubusercontent.com/26340942/38820442-386bedf4-419e-11e8-8cf4-f76593f30325.png)


Here is the code I have in my header section:
<p><img src="http://tooap.com/wp-content/uploads/2017/12/tooap-agence-digitale-logo.png" alt="" width="189" height="57" /></p>
