### ISSUE TITLE
Logging calls without Duration causes php to fail

### ISSUE THREAD

**Issue by JBrace1990** [salesagility/SuiteCRM#4440]
#### Issue

When editing an existing call, if duration is not set then it fails to save

#### Expected Behavior

Calls should not require duration to be set

#### Actual Behavior

Page dies and goes to a white screen

#### Possible Fix

change "isset" to "!empty"
file: modules/Calls/Call.php
line: 182

#### Steps to Reproduce

1. Create a new call, with no duration (optionally, hide duration field from edit view)
2. Edit the call
3. Save the call
4. End up at a white page

#### Context

Semi-High priority. Makes it impossible to save calls without a duration associated with it. 

#### Your Environment

* SuiteCRM Version used: 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
There is a decision to be made here
- either drop the requirement that the `Duration` field is mandatory
- or make it give a proper error when it is empty and somebody tried to save an edit, like it already does when you neglect to fill in the field when creating the record

**Comment by JBrace1990** [comment]
I really don't think the Duration field should be mandatory. If you want to include it, then you can, but for our usage it doesn't really matter.

At the least, the page shouldn't just die like that if it's empty. It needs a JS check if it'll be mandatory, but it really just needs a backend fix to prevent it from trying to make a date object from null.
