### ISSUE TITLE
WYSIWYG quick edit fails

### ISSUE THREAD

**Issue by JBrace1990** [salesagility/SuiteCRM#4441]
#### Issue

WYSIWYG quick edit does not work. Must edit the entire item to make it work.

#### Expected Behavior

Should be able to double click on a field to get a quick edit field that enables you to change it.

#### Actual Behavior

Throws a JS error (below) and gives a small textarea

`Uncaught TypeError: Cannot set property 'type' of undefined

    at eval (eval at globalEval (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:2), <anonymous>:3:8)

    at eval (<anonymous>)

    at Function.globalEval (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:2)

    at n.fn.init.domManip (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3)

    at n.fn.init.append (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3)

    at n.fn.init.<anonymous> (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3)

    at n.access (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:2)

    at n.fn.init.html (sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3)

    at onInlineEditDblClick (inlineEditing.js:146)

    at HTMLDivElement.<anonymous> (inlineEditing.js:198)

    (anonymous) @ VM38541:3
    globalEval @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:2
    domManip @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3
    append @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3
    (anonymous) @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3
    n.access @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:2
    html @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3
    onInlineEditDblClick @ inlineEditing.js:146
    (anonymous) @ inlineEditing.js:198
    dispatch @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3
    r.handle @ sugar_grp1_jquery.js?v=gqSBanP8qIf9dFJXIrh-iA:3`

#### Steps to Reproduce

1. Install plugin
2. Add plugin to a field in Calls
3. Create a new call with some text in the editor
4. Try yo quick edit after it is saved

#### Your Environment

* SuiteCRM Version used: 7.8.6 and 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome/Vivaldi
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.2
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
What is this "plugin" you mention?

Can you please also fill in the rest of the Issue template? We obviously need to know what version of SuiteCRM you're running, etc. Thanks.

**Comment by JBrace1990** [comment]
Updated.

Plugin is: https://suitecrm.com/index.php?option=com_mtree&task=viewlink&link_id=53&Itemid=1225

mPlugin Mentioned in tickets:
https://github.com/salesagility/SuiteCRM/issues/4436
https://github.com/salesagility/SuiteCRM/issues/241
