### ISSUE TITLE
EMAIL MODULE - Draft folder incorrectly identified

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#4442]
On Email module, since 7.9.5, the "draft" folder appears as configured "sent" folder in email configuration. For example, on my case, "draft" and "sent" appears as "INBOX.sent"

#### Expected Behavior
On folder list, the draft folder should be correctly identified.

#### Actual Behavior
On folder list, draft folder appears as the configured sent folder.

#### Steps to Reproduce
Configure a new personal or group email account.
Select on configuration a sent email folder.
Go to email module. Click on "Inbox" on the right to see other folders. "Drafts" have the name of the sent folder at right, as on the "sent" real folder.

#### Context
LOW PRIORITY. Folder appears incorrectly identified, but show different content.

#### Your Environment
* SuiteCRM Version used: 7.9.5 - 7.9.7
* Tested on IE11 / Edge / Firefox 56-57
* Nginx / MariaDB / PHP7.0

**Comment by Dillon-Brown** [comment]
This should be resolved with latest 7.9.x or 7.10.x. If you can still replicate please re-open and we can investigate further. Thanks.

**Comment by the-lost-sea** [comment]
Hello,

I have the same problem.
I am using version 7.11.6 on webserver on CentOS 7.6 with Apache 2.4.6 and PHP 7.2 and in a local environment with MAMP on Mac.
I have tried it with different mail servers and it is always shown to me as a INBOX.SENT but INBOX.DRAFTS appears correctly in mail apps and webmailer.
So I can not edit any drafts and can always work only with answer or forwarding mails.

Is it possible to solve this in the code?
I think it's better to be able to define the draft folder like the sent or trash folder.
