### ISSUE TITLE
entry_point_registry.ext.php file not being parsed

### ISSUE THREAD

**Issue by KaKite** [salesagility/SuiteCRM#4444]
#### Issue
When creating custom entrypoints as per the documentation at [https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Entry_Points/Creating_Custom_Entry_Points/index.html](url) the entrypoint does not work

#### Expected Behavior
When accessing the entrypoint via the URL the actions defined in the custom entrypoint should run

#### Actual Behavior
The end user is redirected to the index.php file, generally this means the entrypoint is not registered

#### Possible Fix
Not sure

#### Steps to Reproduce
1. Create a simple php file that echos Hello World
2. Save the file in the custom directory, named helloWorld.php
3. Create a php file with the following content 

```
<?php
$entry_point_registry['helloWorld'] = array(
	'file' => 'custom/helloWorld.php',
	'auth' => false
);
```
4. Save it in the custom/Extension/application/Ext/EntryPointRegistry folder as test_hello.php
5. Run an Admin Repair/Rebuild
6. Check the custom/application/Ext/EntryPointRegistry/entry_point_registry.ext.php file for the existence of your entry_point_registry['helloWorld'] listing
7. Enter the following URL [http://your suite installation/index.php?entryPoint=helloWorld](url)

#### Context
I am attempting to create an installable module for sale on the SuiteCRM Store. I have a number of entrypoints defined that add functionality to that module. I am trying to ensure I do NOT overwrite any existing customisations HOWEVER with this NOT working I am having to use the copy section of manifest.php to custom/include/MVC/Controller/entry_point_registry.php file which MAY cause me to overwrite someone elses customised file.

#### Your Environment

* SuiteCRM Version used: tested on Suite v7.8.7, 7.9.3, 7.9.4 and 7.9.6 
* Browser name and version Firefox 56.0.1 64bit and Firefox Developer Edition 57.0b9 64bit
* PHP 
* Linux shared hosting

**Comment by KaKite** [comment]
Overworked and underpaid.. apologies for posting

**Comment by bsailer** [comment]
Did you fix this issue?  I have the same one ...

**Comment by bsailer** [comment]
or to be more precise:  A rebuild does not add my new entryPoint to entry_point_registry.ext.php at all.
