### ISSUE TITLE
In 7.8.7. LTS Workflow actions are not working for modify record

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#4445]
#### Issue
In clean install 7.8.7 when I try to work with Project Task module in Workflow, and try in Actions to modify a record, I can't select any field. The same behavior is if any other module is selected. Other actions seem to work fine, just modify not. 
On 7.8.5, and on demo (7.9.7) works fine.

#### Expected Behavior
When selected action, there should be list of fields.
![github1](https://user-images.githubusercontent.com/19294358/31930696-eef27e9e-b8a0-11e7-84ea-2775294fbe56.png)

#### Actual Behavior
List of fields is empty.
![github2](https://user-images.githubusercontent.com/19294358/31930729-0b916b00-b8a1-11e7-8600-9f1b1ae26acb.png)

#### Possible Fix
Not known.

#### Steps to Reproduce

1.Open Workflow , select any module
2.In Actions select Modify Record
3.Click on Add Field
4.List of fields is empty

#### Context
With this issue, Workflows in 7.8.7. is not usable.

#### Your Environment
* SuiteCRM Version used: 7.8.7. LTS
* Browser name and version (Firefox for Linux 56.0 (64bit), Chromium (61.0.3163.100)):
* Environment name and version (MySQL, PHP 5.6):
* Operating System and version (Linux Mint 18.1 Serena):

**Comment by Dillon-Brown** [comment]
Hi @fcorluka, this should be fixed in 7.8.8 by this PR: #4405.
