### ISSUE TITLE
Ability to Group and Sort Report by Sales Stage's Probability

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4450]
Currently if you create a Report of Opportunities which is Grouped by Sales stage, the groups are not sorted in any particular order and the report does not follow the sorting field if given to the Sales Probability field.

#### Issue

Because of this the Groups are sorted in a completely random order. It does not follow the listing order in the `sales_stage_dom` or the ordering of the values `sales_probability_dom` or the actual values of the `sales_probability_dom`.

If you put a sort on the Sales Stage field you can get it sorted alphabetically, but this is not really helpful.

#### Expected Behavior

I would expect to be able to have a Report which shows Opportunities which is ordered by Sales Probability and Grouped by Sales Stage

#### Actual Behavior

Actualy behavior are the Sales Stages are randomly ordered

#### Steps to Reproduce

1. Create a new report
2. Add field for Sales Stage
3. Add field for Sales Probability
4. Select "Main Group" as "Sales Stage"
5. Select "Sort Ascending" next to "Probability (%)"

#### Context

Can't give my sales team a pipeline report which is grouped by sales stage and sorted by probability.

#### Your Environment

* SuiteCRM Version used: 7.9.4

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to Group and Sort Report by Sales Stage's Probability](https://trello.com/c/uGsweHOo/234-ability-to-group-and-sort-report-by-sales-stages-probability)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
