### ISSUE TITLE
Being abble to remove all alerts (notifications) in one action

### ISSUE THREAD

**Issue by vaudoin** [salesagility/SuiteCRM#4453]
#### Issue
The alert module is quite helpfull (bell at top right corner) but it is not possible to remove with one click the full list of alerts. That could be quite long to remove them if you have 10 or more alerts.

#### Expected Behavior
When clicking on the bell an action could appear with "Remove all" on top of the notification list.

#### Actual Behavior
Not possible to remove all at once. Each alert needs to be removed one by one (click on the cross).

#### Your Environment
* SuiteCRM Version used: 7.9.5
* Browser name and version : Firefox and Chrome

**Comment by Dillon-Brown** [comment]
Hi @vaudoin, thanks for the suggestion! this feature has actually already been completed and merged in #4151 and is scheduled for the 7.10 release. You can checkout the feature/alerts branch if you want to try it out.

**Comment by vaudoin** [comment]
OK thanks @Dillon-Brown. Sorry for duplicate.
