### ISSUE TITLE
Quotes Module's Bug

### ISSUE THREAD

**Issue by uvainternational** [salesagility/SuiteCRM#4455]
#### Issue

After adding a new filed to the layout through Studio to Quotes, the Overview, Quote To and Other tabs are missing from the detailview even thought the new file was deleted from the layout later.
#### Expected Behavior

The tabs are not supposed to be missing.
#### Actual Behavior

After adding the new field, the Overview, Quote To and Other tabs are missing from the detailview.

#### Steps to Reproduce

1.  Create a quote and go to detailview
2.  Add a new field and add it to the layout
3.  Go back to detailview and refresh, the Overview, Quote To and Other tabs are missing.
4.

#### Your Environment

* SuiteCRM Version used: 7.9.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 61.0.3163.100 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Linux

**Comment by uvainternational** [comment]
Anyone having the same issue? No field can be added, move and removed from Quote module in Studio or Metadata editviewdefs.php or else the tabs will be gone missing even undo the changes made.

**Comment by bech-t** [comment]
I've got the same issue. 
When you add a field to module Quotes, you must add it to EditView and then to DetailView **without using** "COPY FROM EDITVIEW". 
If you did it it will break the Tab / Panel of DetailView as they are specific to EditView.

**Comment by Dillon-Brown** [comment]
Unable to replicate with latest LTS. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
