### ISSUE TITLE
Problem Saving Roles when there are more than 110 modules

### ISSUE THREAD

**Issue by petermjakob** [salesagility/SuiteCRM#4456]
I am using the version of software for SuiteCRM 7.8.1 and am having a problem with assigning permissions on Roles.
If I create a new Role and then try and set the permissions it works fine until I have more that 110 modules in the system. What is happening is that the IMPORT permission on the 110th module will not save nor will any permissions from that point onward. If I rename any modules to change the order it still fails at the 110th module. Existing Roles that had permissions after that point are read and displayed correctly but cannot be changed. When I create a brand new Role it creates all the records in the acl_roles _actions table up to the same point of failure. It then just stops creating records. This looks to be some sort of limit in Saving a permission.

**Comment by Mausino** [comment]
@petermjakob sometime must the SuiteCRM go behind the limits :) we have only 47 modules :D good to know that something happens after when you cross the line of 100 🥇

**Comment by petermjakob** [comment]
Ok - so we figured out the issue.  The php.ini file has a setting for **max_input_vars = 1000**
That is the limit we were hitting.  Once increased I could set permissions in the Role array as expected.
