### ISSUE TITLE
PostgreSQL database support

### ISSUE THREAD

**Issue by opravil-jan** [salesagility/SuiteCRM#4462]
Hello,

I run into spicecrm (http://www.spicecrm.io/) which implements postgresql support from this repository https://github.com/postgraphql/postgraphql. I would be great if SuiteCRM implemented the support too.

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by shayneoneill** [comment]
Whats the progress on this?

**Comment by gunnicom** [comment]
https://github.com/salesagility/SuiteCRM/pull/7757
