### ISSUE TITLE
Case description doesn't display UTF-8 (non-ASCII) characters

### ISSUE THREAD

**Issue by rholighaus** [salesagility/SuiteCRM#4463]
#### Issue

The DetailView of a case with non-ASCII characters that have been entered using TinyMCE will not display these characters.

default_charset is set to UTF-8 in php.ini, HTML source code of DetailView shows that the page is coded in UTF-8, too.

#### Expected Behavior

The characters should be displayed correctly in DetailView.
#### Actual Behavior

The characters are displayed as � instead.
#### Steps to Reproduce

![screenshot 2017-10-30 at 01 05 24 pm](https://user-images.githubusercontent.com/3057224/32170188-f2ad8fa6-bd73-11e7-9e39-46595796847f.png)
![screenshot 2017-10-30 at 01 11 50 pm](https://user-images.githubusercontent.com/3057224/32170199-fad88fe6-bd73-11e7-94af-b8b5cb4fc0df.png)

1. Create a new case
2. Enter non-ASCII characters (e.g. Umlaut characters) in the description field
3. Save
4. Check the DetailView of the case just saved.
#### Your Environment

* SuiteCRM Version used: Version 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari, Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.58, PHP 7.0.24
* Operating System and version (e.g Ubuntu 16.04): Debian 8.9

**Comment by pavithra06** [comment]
Hi rholighaus
Please use the below line in custom/modules/Cases/view.detail.php or modules/Cases/view.detail.php
"$this->bean->description = html_entity_decode($this->bean->description);" inside the display function.

Thanks,
Pavithra

**Comment by rholighaus** [comment]
Hi, I've added custom/modules/Cases/view.detail.php (and did a quick repair):

```
<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class shk_CasesDetailView extends ViewDetail
{
    public function display()
    {
          $GLOBALS['log']->debug('CASESVIEW: before html_enitity_decode: description=' . $this->bean->description);
          $this->bean->description = html_entity_decode($this->bean->description);
          $GLOBALS['log']->debug('CASESVIEW: after html_enitity_decode: description=' . $this->bean->description);

        // definitely need to call the parent method
        parent::display();
    }
}
?>
```
Unfortunately, no change in behaviour. I don't think my script is being executed, however, as non of the log file entries appear.

What am I doing wrong?

**Comment by pavithra06** [comment]
Hi rholighaus,
use this below code instead of your code,

<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class CasesViewDetail extends ViewDetail
{
    public function display()
    {
          $GLOBALS['log']->debug('CASESVIEW: before html_enitity_decode: description=' . $this->bean->description);
          $this->bean->description = html_entity_decode($this->bean->description);
          $GLOBALS['log']->debug('CASESVIEW: after html_enitity_decode: description=' . $this->bean->description);

        // definitely need to call the parent method
        parent::display();
    }
}
?>

Thanks

**Comment by rholighaus** [comment]
Hi pavitrha06,

You may want to mark code as code in the editor to make it easier to read and to show the line breaks. 

I've altered view.detail.php and tried it both in custom/modules/Cases/views as well as in modules/Cases/views.  It has read and execute permission for www-data and reads as follows:

```
<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class shk_CasesDetailView extends ViewDetail
{
    public function display()
    {
        debug('CASESVIEW: before html_enitity_decode: description=' . $this->bean->description);
        $this->bean->description = html_entity_decode($this->bean->description);
        $GLOBALS['log']->debug('CASESVIEW: after html_enitity_decode: description=' . $this->bean->description);
        // definitely need to call the parent method 
        parent::display();
    }
}
?>
```


Unfortunately, neither of the scripts seems to get fired, at least there are no log file entries even though logging is in debug mode (I see lots of other DEBUG messages). 

If you have any idea what I may have done wrong please let me know.

I have added some debugging code into my after_retrieve logic_hook, which actually DOES write debug message and results in the following output:

```
Fri Nov  3 12:33:54 2017 [65226][e0c73158-1a04-7c79-cfce-51cc3a3e4eb6][DEBUG] CASE-VIEW: description after retrieve=&lt;p&gt;This is a test - here are the Umlaut characters:&lt;/p&gt;
&lt;p&gt;ä lower cae a umlaut&lt;/p&gt;
&lt;p&gt;ö lower case o umlaut&lt;/p&gt;
&lt;p&gt;ü lower case u umlaut&lt;/p&gt;
&lt;p&gt;Ä upper case A umlaut&lt;/p&gt;
&lt;p&gt;Ö upper case O umlaut&lt;/p&gt;
&lt;p&gt;Ü upper case U umlaut&lt;/p&gt;
&lt;p&gt;ß sharp s&lt;/p&gt;
Fri Nov  3 12:33:54 2017 [65226][e0c73158-1a04-7c79-cfce-51cc3a3e4eb6][DEBUG] CASE-VIEW: html_entity_decode(description)=<p>This is a test - here are the Umlaut characters:</p>
<p>ä lower cae a umlaut</p>
<p>ö lower case o umlaut</p>
<p>ü lower case u umlaut</p>
<p>Ä upper case A umlaut</p>
<p>Ö upper case O umlaut</p>
<p>Ü upper case U umlaut</p>
<p>ß sharp s</p>
```

This shows to me that html_entity_decode WOULD do what it should do but something must f**k with the charset in the SuiteCRM code either before or after as the UTF-8 Umlaut characters get altered to �, which is also shown in the page source (screenshot only as I can't cut&paste Safari source code):

<img width="756" alt="screenshot 2017-11-03 at 12 44 56 pm" src="https://user-images.githubusercontent.com/3057224/32372375-d6b61fb0-c094-11e7-9d81-9ab643fc7b7c.png">

**Comment by pavithra06** [comment]
Hi rholighaus,

sorry for inconvenient,

use this below code instead of your code,

`<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class CasesViewDetail extends ViewDetail
{
    public function display()
    {
          $GLOBALS['log']->debug('CASESVIEW: before html_enitity_decode: description=' . $this->bean->description);
          $this->bean->description = html_entity_decode($this->bean->description);
          $GLOBALS['log']->debug('CASESVIEW: after html_enitity_decode: description=' . $this->bean->description);

        // definitely need to call the parent method
        parent::display();
    }
}
?>`

please change your class name because you have mentioned "shk_CasesDetailView" which was mismatched should be replaced by CasesViewDetail I hope this will work better.

**Comment by rholighaus** [comment]
Hi pavithra06,

I have found out that two other scripts from an extension that are located in custom/modules/Cases/views prevent my script to be fired.

I'll check with the vendor of the extension to fix this.

Without those other scripts, your work-around does the trick.

**Comment by PedroErnst** [comment]
Cannot reproduce this in the current version

![image](https://user-images.githubusercontent.com/34056696/38426667-2da3b7ae-39af-11e8-9be0-84ff7ee62cd9.png)
