### ISSUE TITLE
HTML entities in addresses display encoded

### ISSUE THREAD

**Issue by FR-JS** [salesagility/SuiteCRM#4469]
#### Issue
When HTML entities are are used within addresses they are displayed in encoded on the detail views.

#### Expected Behavior
The HTML entities should be displayed in their human readable form.

#### Actual Behavior
HTML entities remain encoded.

#### Possible Fix
The fields given to the address template /include/SugarFields/Fields/Address/DetailView.tpl are encoded and as each field is rendered it is passed through the escape modifiers for 'htmlentitydecode' and 'html'.

Following the code through I noticed that in the Smarty escape modifier the character set used ISO-8859-1 yet the system is set to UTF-8. Also, not sure if it's worth adding the ENT_HTML5 flag to the html entity calls to allow `&apos;` to be used instead of `&#039;`

#### Steps to Reproduce
1. Create an Account
2. Enter `King's Lynn Café ">` in to each line of the address
3. Save

#### Your Environment
* SuiteCRM Version used: 7.9.7

**Comment by PedroErnst** [comment]
@FR-JS Thanks for bringing this up.

I cannot seem to reproduce this, I'm following your steps and in detailview the address shows fine.

![screenshot from 2018-02-08 15-12-29](https://user-images.githubusercontent.com/34056696/35980377-800d5bd4-0ce2-11e8-914c-de1a031f0b84.png)

Is there anything I'm missing or did this get fixed already?

Tested on 7.8.13 and 7.9.12

**Comment by FR-JS** [comment]
I'll take a look and see. It may have been secretly fixed in one of the minor updates.

**Comment by FR-JS** [comment]
Just did a fresh install of 7.9.7 and updated through each release to 7.9.10 where the issue was resolved.
Looks like my initial assumption was wrong and the issue was the strings were being double encoded.

**7.9.9**
`<input type="hidden" class="sugar_field" id="billing_address_street" value="King&amp;#039;s Lynn Café &amp;quot;&amp;gt;">`

**7.9.10**
`<input type="hidden" class="sugar_field" id="billing_address_street" value="King&#039;s Lynn Café &quot;&gt;">`

Looks like the issue has been resolved.
