### ISSUE TITLE
Relations not working on Report module.

### ISSUE THREAD

**Issue by daniprados** [salesagility/SuiteCRM#4478]
**Issue**

On report based module I created a report  for Meetings with a relation with accounts in order to get the number of meetings that a  user had done per account.

**Expected behavior**

A list of accounts with the number of meetings.

**Actual behavior.**

I obtain a empty list.

**Steps to Reproduce**

1. Create report
2. Choose meetings as main module.
3. Add Account as field.
4. Check group ckeckbox
5. Add Account as field again.
6. Select function Qty
7. Add condition Assigned to equal to and user.
8. Save

**My Enviroment**

SuiteCRM Version used: 7.9.5
Environment name and version: mysql Ver 14.14, PHP 5.6.32
Operating System and version: Ubuntu 16.04   5.7.20-0ubuntu0.16.04.1

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.9.10. Please re-open if this is still an issue you can replicate.
