### ISSUE TITLE
Required field not effect when create quick meeting in calendar interface

### ISSUE THREAD

**Issue by dinhhaidang** [salesagility/SuiteCRM#4483]
He there,

When I create quick meeting in calendar interface, require field not effect so that system still allow create. But in case full form interface, require field is effective.
Please help me how to customize effective in case create quick meeting.
Version 7.9.7
Sugar Version 6.5.25 (Build 344)

Thank so much!

**Comment by afrugone** [comment]
Is this problem be solved in Version 7.10?

**Comment by TB-effective** [comment]
Why was this closed? The referenced commit has nothing to do with the issue, which persists to this day.

Can be easily reproduced on demo.suiteondemand.com (Version 7.11.18 Sugar Version 6.5.25 (Build 344) at time of writing):

1. Go to calendar
2. Click in calendar to create new meeting
3. Click Save (without filling in required field "Subject")

Expected result: Validation warning for empty mandatory field(s)

Actual result: Meeting is created with no subject.

Let me know if I should open a fourth issue about this (in addition to this one, #2510, and #2645).
