### ISSUE TITLE
reply or forward email: body empty

### ISSUE THREAD

**Issue by centoasa** [salesagility/SuiteCRM#4486]
As I say on this post:
https://suitecrm.com/forum/suitecrm-7-0-discussion/16482-reply-or-forward-email
when I reply or forward an email, the message body is empty.
There isn't the message I would reply or forward, so I think this is a bug.

suitecrm 7.9.7
all browser
apache +mysql server

**Comment by Mausino** [comment]
could it be part of problems like #4110 if you imported email look if you have this patch #3617

**Comment by centoasa** [comment]
The issue happens (for me) not when import, but when reply or forward email.

**Comment by PedroErnst** [comment]
Cannot replicate on current version
