### ISSUE TITLE
Bug on Scheduler.php . Wrong minutes getter used.

### ISSUE THREAD

**Issue by cherrador** [salesagility/SuiteCRM#4496]
#### Issue
I notice my php error logs were filling up with this warning on multiple line numbers on the same range:
A non-numeric value encountered in /crm/modules/Schedulers/Scheduler.php on line 423

Basically the issue show up when the variables `$currentMin` and `$startMin' are being used.

#### Expected Behavior
No warnings. Scheduler properly executed.

#### Actual Behavior
I have not done full trace of what problems this could be causing, but I guess that the scheduler is not using the current "now" minutes for the calculation of the scheduler.

#### Possible Fix
I traced the reason of the problem and it's because it's using the wrong getter for minutes. From the class 'SugarDateTime' the correct way to get the minutes is using the getter 'min'.

However these two lines are found on the Scheduler.php
```
402  $currentMin = $timedate->getNow()->minute;
417  $startMin = $timedate->fromDb($focus->date_time_start)->minute;
```

Instead they should say:
```
402  $currentMin = $timedate->getNow()->min*1;
417  $startMin = $timedate->fromDb($focus->date_time_start)->min*1;
```

The multiplication by 1 is optional, just  to make the result numeric instead of the by default string.

#### Steps to Reproduce
1. Activate the scheduler
2. Send all the PHP warnings to be saved on a file.
3. Review the warnings file after the scheduler is executed.

#### Context
We are trying to certify the SuiteCRM to run on PHP 7.1, but we have found already a lot deprecated warnings and a lot of unchecked variables. So far we are ignoring the ones that do not affect the behavior, but this one could cost somebody head, if the schedule is not properly executed on time.

I will suggest to be medium priority.

#### Your Environment
* SuiteCRM Version used: 7.8.5 (because we need themes).
* Browser name and version: Irrelevant
* Environment name and version:  PHP 7.1.10
* Operating System and version : Windows Server 2016

**Comment by cherrador** [comment]
After testing all cases, additional of the previous changes, if the multiplication by 1 is implemented then lines 403-405 are not required anymore. The code looks like this:
```
403 if(substr($currentMin, 0, 1) == '0') {
404    $currentMin = substr($currentMin, 1, 1);
405 }
```
Because `$currentMin` is numeric already, executing these lines could cause problems if the minutes is already `0` it will end up with a empty string, which will start triggering warnings again.

My suggestion is to remove those 3 unnecessary lines of code.

**Comment by pgorod** [comment]
@cherrador can you make a Pull Request with these changes? If you don't have local git install, you can do it more easily here from GitHub: 

https://help.github.com/articles/editing-files-in-another-user-s-repository/

Just make sure you change branch to `hotfix-7.8` before starting the edit. Thanks!

**Comment by cherrador** [comment]
@pgorod not sure if I did it right. Because this error is not particular to only 7,8. I did it on the `hotfix` branch. If that is not the correct way to do this. let me know and I will pull the request on the correct branch.
