### ISSUE TITLE
Quotations & email - Unable to find relationship emails_email_templates

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#4497]
#### Issue
Similar to #3654
When using the "Email Quotation" action from the Quotes detail view:
![bug_01](https://user-images.githubusercontent.com/939888/32516870-83c5f5e4-c3e3-11e7-922f-6e75d41547e4.png)

we get the compose email view, but the Quotation is not pasted in the body of the email

![bug_00](https://user-images.githubusercontent.com/939888/32516888-91042546-c3e3-11e7-9375-40ce64ae1fac.png)

The same happens if you select "Email PDF", no PDF is attached.

The logs contain this:

![bug_02](https://user-images.githubusercontent.com/939888/32517190-6eb33828-c3e4-11e7-9a78-047f7c63d555.png)

#### Expected Behavior
Option should work as in previous versions.

#### Actual Behavior

No quotation is inserted in email body or attached 

#### Steps to Reproduce   

1. Create a Quotes Email Template (in PDF Templates module) if you don't have one yet
2. Create a Quote and Save it
3. From the Detail view of that Quote, select action Email Quotation from drop-down action menu
4. Email has no quotation inserted in body or attached

#### Your Environment

* SuiteCRM Version used: 7.9.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 5.6
* Environment name and version (e.g. MySQL, PHP 7): Apache 2.4, PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Abuelodelanada** [comment]
Hi @daniel-samson @Dillon-Brown  you fixed bug #3654 in PR #3748

This is quite similar, and in a moment I thought I was using a version without this fix.

**Comment by Dillon-Brown** [comment]
Confirmed on 7.9.7.

**Comment by Abuelodelanada** [comment]
@Dillon-Brown The relationship's name is defined as "emails_email_templates"  and should be: "email_email_templates".

With this change SuiteCRM find the relationship, but the following appears in the log:

  `Thu Nov  9 17:43:53 2017 [3072][1][ERROR] Warning: Multiple links found for relationship email_email_templates within module Emails

  Thu Nov  9 17:43:53 2017 [3072][1][FATAL]  Query Failed: SELECT email_email_templates_idb id FROM email_email_templates  WHERE email_email_templates.email_email_templates_ida = '51496dc6-5da3-4d7f-d055-5a04bed94b90' AND email_email_templates.deleted=0: MySQL error 1146: Table 'suitecrm.email_email_templates' doesn't exist`

And no Quotation is inserted in the body email.....I continue with the debugging...
