### ISSUE TITLE
Sorting subpanel

### ISSUE THREAD

**Issue by mr-terrific** [salesagility/SuiteCRM#4501]
#### Issue
When you click on anything to sort by in a subpanel, the results are out of order.

![suitecrm_bug_subpanel_sort](https://user-images.githubusercontent.com/33308618/32580218-54d9951e-c538-11e7-8fb0-e8b72a89948f.png)

#### Expected Behavior
The order of column after sorting should still be the same

#### Actual Behavior
When you sort a column in a subpanel, the data is out in order

#### Possible Fix
-

#### Steps to Reproduce

1. Navigate to Accounts
2. Sort the quotes subpanel by title

#### Your Environment

* SuiteCRM Version used: Version 7.8.8
Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 5.6.37 MySQL Community Server (GPL) and PHP Version 7.0.25
* Operating System and version (e.g Ubuntu 16.04): CentOS Linux release 7.4.1708 (Core)

**Comment by gunnicom** [comment]
Can you try this patch:
https://github.com/ale26/SuiteCRM/commit/bc56c77b766086ec766df1a31a4994fb309a9664
Had the same Problem here: https://github.com/salesagility/SuiteCRM/issues/3460

**Comment by mr-terrific** [comment]
Hi, the fix is working. 

Thank you :)
