### ISSUE TITLE
Getting Cross-Origin Request Blocked Error On SuiteCRM 7.9.7 Download

### ISSUE THREAD

**Issue by mohamedalijinna** [salesagility/SuiteCRM#4505]
**Getting Cross-Origin Request Blocked Error On SuiteCRM 7.9.7 Download**

#### Issue
I just registered myself to download the latest SuiteCRM 7.9.7 from https://www.suitecrm.com. I came to https://www.suitecrm.com from google search. After registration I clicked latest version download link and get nothing. I inspected the page with Developer console and Found that the page has Cross-Origin Request Blocked Error, Which was not let me to download. 

#### Expected Behavior
It should download when I click the SuiteCRM 7.9.7 download link.

#### Actual Behavior
I was trying to download the SuiteCRM 7.9.7. But it wasn't

#### Possible Fix

I just simply removed the www from https://www.suitecrm.com and again done the same thing with https://suitecrm.com. It was perfect I got what I want. 

I suggest you to please fix the Cross-Origin Request Blocked Issue. I am a techie and was manage to download. But If someone who have no idea on this issue, Surely they will disappointed. 

I hope you will fix this as soon as you can.

Thanks!

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.

**Comment by Deepak-1111** [comment]
Dear Friends,I need help regarding populating the data to dropdownlist from Database?
Please help me out:
deepak.ahirwar@kserve.co.in
Whats App number:+8097932986
