### ISSUE TITLE
Home guides style not loading properly when acessed from menu

### ISSUE THREAD

**Issue by allysonsouza** [salesagility/SuiteCRM#4507]
#### Issue
When acessed from menu All > Home, the guides tabs are not styled.

#### Expected Behavior
The tabs should have their style the same way when we first log in the system or access clicking in the house icon.

#### Actual Behavior
![image](https://user-images.githubusercontent.com/2000638/32695472-9f857f5c-c744-11e7-8724-7a7e5e54d823.png)

#### Steps to Reproduce
1. Access the system go to some section and then click or All > Home

#### Your Environment
SuiteCRM Version 7.9.7
Chrome  61.0.3163.100 64 bits
PHP7, MySQL 5.6
Ubuntu 64 bits

**Comment by Dillon-Brown** [comment]
Hi @allysonsouza, I'm unable to replicate this on 7.9.7. Have you tried repair + rebuild and clearing cache?

**Comment by allysonsouza** [comment]
Hi @Dillon-Brown,

I tried now and this don't fix the problem. I don't know exactly if there's something more to reproduce or if it's happening only in my install, any suggestions to debug it?

**Comment by willrennie** [comment]
I've not been able to replicate this issue in the latest SuiteCRM releases and notice this issue is logged for 7.9.x which is no longer supported. If this is still an issue for you, please update the issue thread.
