### ISSUE TITLE
Upgrade of TinyMCE to latest 4.7.x version 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4511]
In SuiteCRM we are using TinyMCE Version: 3.5.12 (2016-10-31)

The latest version 4.7.1    https://www.tinymce.com/download/ 

There is huge different between version 3.x and 4.x 

Our old one:
![tiny3](https://user-images.githubusercontent.com/5773777/32756158-f501e73c-c8d8-11e7-98e4-c884507dcfa8.png)

New one:
![tiny4](https://user-images.githubusercontent.com/5773777/32756163-faf71c34-c8d8-11e7-918c-f91959329370.png)

Issues which are maybe related to old version #4389 #3672 #4463

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade of TinyMCE to latest 4.7.x version](https://trello.com/c/Fg0RHkYB/236-upgrade-of-tinymce-to-latest-47x-version)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran i saw on roadmap https://suitecrm.com/roadmap/  that the one of point of 7.11 relase will

> Libraries
Update all third party libraries (that are required)

Now is there relase 4.9.2 https://www.tiny.cloud/get-tiny/self-hosted/ or we can stay on latest 3+ version (3.5.12) Also soon will relased version 5+

With version tinyMCE 3.5.12 we have cca 9 tickets https://github.com/salesagility/SuiteCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tinymce

Some news what @salesagility is planning?

**Comment by Dillon-Brown** [comment]
@Mausino Had a quick look at this, should be fairly simple to implement. I've gone ahead and created a PR for email templates but will need to check all the other areas that use TinyMCE as it looks like we have multiple instances of TinyMCE with various version numbers.

**Comment by Mausino** [comment]
@Dillon-Brown great news 👍 when you done the clean up with this editor on one place, it will great to move forward with latest vendor technologies included in SuiteCRM. 

I very like that i can learn how you did the changes in folders and here is see how profesional the team of @salesagility is. Like to see separate folders for api, tests, lib, build etc...

Should you want create new folder on front line of folders with filename "vendor" ? as i saw in your pull request, where will all vendors applications ?

![2019-01-01_1312](https://user-images.githubusercontent.com/5773777/50572750-873bb180-0dc7-11e9-847a-0af47e3fd1f1.png)
![2019-01-01_1312_001](https://user-images.githubusercontent.com/5773777/50572751-87d44800-0dc7-11e9-861b-12984fcab6b5.png)

**Comment by Mausino** [comment]
@Dillon-Brown thank you for upgrade

@samus-aran should it get label with 7.11 Milestone?

**Comment by Dillon-Brown** [comment]
@Mausino You actually don't need to create the vendor folder as it will be done automatically when running the command ```composer install```. Although you only need to do this when pulling down straight from GitHub as we include the vendor folder in the installers + upgradepacks.

**Comment by Mausino** [comment]
@Dillon-Brown thank you for your answer.

Should i create new ticket for clean request which will refer on your commnet that

> Unfortunately I won't have time to remove the multiple other tiny_mce packages still included in SuiteCRM before 7.10.11

which will refer that need to find and clear unsing parts of old TinyMCE and users which will have developer skills maybe create pull reqest for it if will see that this need to be done. 

What do you think?
