### ISSUE TITLE
Body Text is not display

### ISSUE THREAD

**Issue by Nitin-Thakkar** [salesagility/SuiteCRM#4530]
**Issue**

When you import any email, it doesn't show you the body text

![mailissue](https://user-images.githubusercontent.com/33724178/32895212-4b464f9c-cb05-11e7-9820-fb5a4d5df4de.png)

**Expected Behavior**

Will show the body text (the most important part of the emails)

**Steps to Reproduce**

1. Import email
2. Open imported email and look to body section
3. Context

**Your Environment**

SuiteCRM Version used: SuiteCRM 7.9.4
Browser name and version : Version 61.0.3163.100 (Official Build) (64-bit)
Environment name and version: MySQL 5.6 / PHP 7.0.16
Operating System and version: Win 8.1 Enterprise

Please help me out

Thanks in advance

**Comment by pgorod** [comment]
Is it the same as this #4110?

If so, it should be solved in the most current version.

**Comment by Nitin-Thakkar** [comment]
Hi pgorod,

Thank you for your replay

it is a little bit different than #4110.

Here only one user is using that account at a time. still, it is not showing body content

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.10.x. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
