### ISSUE TITLE
Enhancement or Bug?

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#454]
When in the editView of an Account. Navigate to the 'Annual revenue' and 'employees' field. Both are capable of taking letters as their values. 

Would the reason for this be that you could input, for example , "99 million' as employees or annual revenue?

If that isnt the case, it would be nice that if it would check for a number input and make sure that the input is a number then prompt user for correction of fields if not a number

Cheers 

Darren

**Comment by willrennie** [comment]
Yes, it's intended to be used as you expect. It's not a currency field.
