### ISSUE TITLE
Language files for 7.10 - Code Format

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4542]
#### Issue

With the release of 7.10 alpha version I was quite negatively surprised on the work not done on language files. There are some big PR waiting to be merged related to language clean up and code formatting issues. Same goes for minor issues on languages.
See issues: https://github.com/salesagility/SuiteCRM/issues?q=is%3Aissue+is%3Aopen+label%3Alanguage .

Also:
- The file \include\language\en_us.lang.php in SuiteCRM-7.10.0-beta zip was reformatted but unused strings has been included again. So the reformatting was done on top of an old version!
See unused strings here: https://github.com/salesagility/SuiteCRM/issues/4029
- As it is now I will not update this file into Crowdin for translation to avoid roll back translations.

#### Expected Behavior

Fix the "include" language file. This is a big and relevant file so please get it right: format and strings!
Also reformat language strings accordingly the code format rules set up by salesagility
See: Coding Standards for SuiteCRM https://suitecrm.com/wiki/index.php/Coding_Standards

#### Context

7.10 was supposed to be a clean start for language files. Is there any plan to fix this for 7.10 version or it will be moved for another future version?

#### Your Environment

* SuiteCRM Version used: 7.10 (zip released today from github says "SuiteCRM-7.10.0-beta" but file code says $suitecrm_version      = '7.10 alpha';)

**Comment by Dillon-Brown** [comment]
Hi @horus68, I'll be taking another look at languages this week. We should be able to get the missing labels and formatting PR's merged and i'll work on new PR's for 7.8.x. Thanks!
