### ISSUE TITLE
Email Address disappeared everytime we save a lead.

### ISSUE THREAD

**Issue by ziaoulhoque** [salesagility/SuiteCRM#4543]
Hi

#### Issue
If we open a lead and it has an email. After update some of the lead information when I save the lead it automatically remove email address and email field shows **--None--**

#### Expected Behavior
It suppose to keep email address as it is. And even if there is no email address, it should not allow to save it as it is a mandatory field.

#### Actual Behavior
Alternatively it remove email address from the lead.

#### Changes done by me
I have updated Suite CRM version 7.8.8 and also change PHP 5.6 to PHP 7

#### Your Environment

* SuiteCRM Version used: Version 7.8.8 - Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 56.0.2 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by ziaoulhoque** [comment]
Hi. I have check in Safari Browser (in my iPad) and it has no issue. Would someone please help?

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.10.x. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
