### ISSUE TITLE
README file easier to find for developers / installers from source

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4548]
Would like to have some documentation in the source that tells how to install and build from source which is easy to find.

#### Issue

Can we add some more information about getting the code up and running from source into either the README in root, or into CONTRIBUTING in .github or somewhere else?

##### Docs

I would think maybe a best option would be to add a docs/ directory to root and symlink some of those file from there. Searching in the .github directory is not immediately apparent.

Having:

* /docs/README.md
* /docs/DEVELOP.md[/li]
* /docs/CONTRIBUTING.md
* /README.md -> docs/README.md
* /.github/CONTRIBUTING.md -> ../docs/CONTRIBUTING.md

may be a bit easier to find and digest.

##### Develop / Build

Some things that I had a hard time finding or still haven't found are

 * Build instructions (i.e. checkout, composer install,)
 * Style Build instructions (i.e. ```./vendor/bin/pscss -f compressed themes/SuiteP/css/style.scss >  themes/SuiteP/css/style.css``` [Source](https://suitecrm.com/forum/suite-themes/16394-css-style-css-tidyup-with-glossary-chapters-and-notation#55478)
* Javascript build instractions, I still haven't found what you guys are doing for the build step of your javascript files... not sure if it's just the link in the "Repair" section of admin committed

#### Expected Behavior

Instructions of building from source should be somewhere in the source code

#### Actual Behavior

Have to search issues/PRs/External Docs/Forums to find full build instructions

#### Possible Fix

Add a ```docs/BUILD.md``` or ```docs/DEVELOP.md``` or update the ```/README.md``` file to include this information

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [README file easier to find for developers / installers from source](https://trello.com/c/1PAJetBI/237-readme-file-easier-to-find-for-developers-installers-from-source)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by isleshocky77** [comment]
@salesagility @Dillon-Brown @PedroErnst  It looks like with the new subthemes that the process for compiling scss has changed. I don't see any documentation or process anywhere (wiki, forum, github) on how to compile the new themes after changes.
