### ISSUE TITLE
SuiteCRM 7.10 beta - group email account issue + css issues

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4551]
#### Issue

![2017-11-20_1832](https://user-images.githubusercontent.com/5773777/33032395-660ed05a-ce21-11e7-8a5c-237b9e78d5dd.png)

1. i want configure after fresh installation the New group email account but i got this error

Inbound Email cannot function without the IMAP c-client libraries enabled/compiled with the PHP module. Please contact your administrator to resolve this issue.
+ i can't also set up the email for account for user because issue  IMAP c-client libraries enabled/compiled

What is this ??? how can i solve it if is fresh new installation :(

2. Sentence: Inbound Email Disabled in in grey #f5f5f5 color which is invisible
    Buttons: default height + color is wrong 

#### Expected Behavior

Should without problem use the group email account

#### Steps to Reproduce

1. Install fresh new SuiteCRM 7.10
2. Try to set up the group email account

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.10 beta
* Browser name and version: Chrome 56.x
* Environment name and version : MySQL 5.6, PHP 7.1.9 xamp
* Operating System and version : Win 10 home

**Comment by gymad** [comment]
1. Your error message appears when imap_open() function isn't available. It means your IMAP extension doesn't enabled or compiled properly but it is a basic requirement for CRM. 
You have to compile PHP with --with-imap[=DIR] , where DIR is the c-client install prefix
or on Windows systems (for e.g. XAMPP) you should enable the `extension=php_imap.dll` in your php.ini. Can you please check your settings are correct?

**Comment by Mausino** [comment]
@gymad tonigt or tomorrow i will work on my business pc.. and i let you know.. because i must install new fresh version, i had problem with 2 auth. verification and this block my login to test version of SuiteCRM.
