### ISSUE TITLE
SuiteCRM 7.10 beta - Refined SuiteP theme - to much space above header

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4553]
#### Issue

Hi, on screen you can see that is to much place above headers of each sections in list view, detailview or editview. I marked those areas with red.

![2017-11-20_1808](https://user-images.githubusercontent.com/5773777/33033971-abf81de2-ce26-11e7-8aca-04eb21575731.png)
![2017-11-20_1807](https://user-images.githubusercontent.com/5773777/33033974-ad6064b4-ce26-11e7-9b9d-74988bc4fad1.png)

I very like the new refined SuiteP theme :)

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.10 beta
* Browser name and version: Chrome 56.x
* Environment name and version : MySQL 5.6, PHP 7.1.9 xamp
* Operating System and version : Win 10 home

**Comment by pgorod** [comment]
I installed 7.10 beta but I'm not seeing any changes in the theme. I've logged in and out, checked the profile theme options, the Admin / Themes options, and tried all sorts of Rebuilds. Is there anything else I should be doing in order to see a new theme spacing?

**Comment by gunnicom** [comment]
The ListView is much better now. Though the Detailview uses still too much space.
As Example for a contact in DetailView 6 normal rows, 1 address row and 1 row with two email addresses:

Suite7 Theme height: about 300px
SuiteP Theme heigth: about 525px

That is about 75% more horizontal space used.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM 7.10 beta - Refined SuiteP theme - to much space above header](https://trello.com/c/9jroX3Y2/230-suitecrm-710-beta-refined-suitep-theme-to-much-space-above-header)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
