### ISSUE TITLE
SuiteCRM 7.10 beta - composer.lock has been removed and ignored

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4555]
It looks like the _composer.lock_ file was removed and added to _.gitignore_ during the Codeception Feature branch.  I've never seen a project do this. Is there a valid reason for not having the _composer.lock_ file not part of the source? It is a way to make sure that the correct dependencies are being used with the current code. I can see for making more open dependencies in the _composer.json_ file, but I can't see not having _composer.lock_ file.  It appears it was done without any type of comment on other than the commit message saying "Codeception: Updating travis ci configuration"

#### Issue

When installing the project you get the latest version of every dependency instead of having an intended version which is known, developed, and tested against.

This is also much slower than already knowing the correct versions.

#### Expected Behavior

When installing from _composer_ there should be a _composer.lock_ file with the intended versions of dependencies.

#### Actual Behavior

When installing the project you get the latest version of every dependency instead of having an intended version which is known, developed, and tested against.

#### Possible Fix

Remove _composer.lock_ from _.gitignore_ and commit the current _composer.lock_ file after running _composer install_

#### Steps to Reproduce

1. Checkout Source
2. run _composer install_
3. notice checking for entire dependency graph

**Comment by Dillon-Brown** [comment]
This was an intentional removal. We don't need auto-generated files like composer.lock in the repo.

**Comment by isleshocky77** [comment]
Was there any type of research or anything you guys looked at to come up with that decision? I haven't heard of projects not committing the .lock file. 
One of the first things I ran across was this : 
https://m.dotdev.co/why-the-composer-lock-file-matters-c8d1e1488be7
And
https://www.engineyard.com/blog/composer-its-all-about-the-lock-file

But I'm having a hard time tracking down anyone talking about discarding the .lock file. 

Once again, I don't mean to come off as a pain.. just wondering your motives behind it as I didn't see a pr or issue about removing it.

**Comment by isleshocky77** [comment]
@Dillon-Brown , sorry, forgot to mention @ you. I know you said that's mainly what you guys monitor.

**Comment by Dillon-Brown** [comment]
@isleshocky77 This was more of a design decision that doesn't have a "Correct" answer on whether to include/exclude composer.lock. When we create release packages for download they already contain a snapshot of the vendor folder which would be the guaranteed working version the same as if you were using composer.lock. If you are pulling off of GitHub we would want you to use absolute latest dependencies so that if any issues do arise you can let us know about them so we can fix it.

Thanks for the question! let me know if you need further info.

**Comment by horus68** [comment]
@isleshocky77 I can agree with you. A project needs to be neutral on the way people uses the software. Users need to be able to control things in a neutral way.
As for the actual project there should be a middle ground on the production requirements for a release and the public project. 
So there should be a way using github system to allow both uses.
Will this require too much work?

**Comment by Dillon-Brown** [comment]
@isleshocky77 @horus68 I agree that having composer.lock in master and the tags is a reasonable request. We'll discuss this further before a decision is made for master/tags. Thank you for the continued discussion, we really appreciate it.
