### ISSUE TITLE
SuiteCRM 7.9.4 Workflow email action will not save the recipient

### ISSUE THREAD

**Issue by mattds91** [salesagility/SuiteCRM#4557]
#### Issue
I am trying to create a workflow that will send an email on case creation. The action should be Send Email, To, email, <email address>. I've had this working on 7.9.4 but on 7.9.6 it will not save email address(es) that I enter. I click save to save the workflow and go back to edit, then there are no email addresses listed. 

#### Expected Behavior
Should save the email address(es) entered and the workflow should trigger when a case is created. 

#### Actual Behavior
Email address entered is not saved, and since the action doesn't actually do anything without an email address the workflow is never triggered. 

#### Possible Fix
Not sure, my point of view looks like a bug with version 7.9.6

#### Steps to Reproduce

1.  Create a new workflow
2.  Set action to "Send Email"
3.  Specify an email address or User
4.  Click save, then edit the workflow again and email address will be gone.

#### Context
I need emails on case creation, case closure, and case updates. I created the case creation workflow and noticed the issue when testing it. 

#### Your Environment

* SuiteCRM Version used: 7.9.6
* Browser name and version:  Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6.32
* Operating System and version (e.g Ubuntu 16.04): CentOS

My site is hosted by siteground
Related issue on SuiteCRM forum:
https://suitecrm.com/forum/suitecrm-7-0-discussion/16559-workflow-email-action-not-saving

**Comment by mattds91** [comment]
Turns out, if I enter the email addresses and save it, they are used in the workflow. However, when I go back and edit they are not listed anymore. This means every time I edit the workflow I need to re-enter the desired email addresses. Also, I know others are having this issue - it was first posted about on the SuiteCRM forum.

**Comment by Mausino** [comment]
@mattds91 why you closed the issue if issue is persisting?

If is not issue but suggestion.. @Dillon-Brown will mark it as suggestion.. 

@mattds91 should you also add link where inf forum is the discussion about this issue ?

**Comment by mattds91** [comment]
Sorry, It's my first time posting an issue here on github and clicked the wrong button to comment. Reopening now

**Comment by gymad** [comment]
I can not recreate this issue. Trying in 7.9.6 and 7.9.7. Did you try to run a quick repair and please also check the file permission.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity. Please re-open if you have further information that can help us to progress with this issue. Thanks.
