### ISSUE TITLE
No htlm editor in Email / Settings / Signature

### ISSUE THREAD

**Issue by itngineering** [salesagility/SuiteCRM#456]
Hi,
no html editor appears in Emails / Settings / Signature
Only text is possible.
Fix for this?

Thanks
![emails_no_html_editor](https://cloud.githubusercontent.com/assets/14231355/9809657/f1cb3f1a-5872-11e5-9a41-f6bcab3a36ca.png)

Version 7.3.1
PHP 5.44
Apache 2.2

**Comment by Sid6555** [comment]
Any update on this bug.
