### ISSUE TITLE
SuiteCRM 7.10 beta - installation wizard alert suggestion

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4562]
#### Issue

Warning message/alert must be on top of wizard if something wrong.

Let's say that you install the fresh new SuiteCRM and you filled all sections like.. demo data, smtp, logo etc. 

But you missing something and page height is big.. you need scroll if because many inf showed. But you missed some required file like database name. 

You press Next button and scroll you up and nothing happend.. You start of thinking why it is wrong.. It this installation crap of software.. you start to search and after above the next button you fill find that you forgot something...  i never saw the warning message in bottom page 👎 

![2017-11-21_1729](https://user-images.githubusercontent.com/5773777/33084482-69845310-cee2-11e7-9800-b7a3abc6f09d.png)

#### Expected Behavior

i am expecting the alert message for bootstrap also on top of wizard

#### Steps to Reproduce

1. Install SuiteCRM 7.10 beta
2. Don't fill required field
3. Go to next button an push it
4. Try to find the warning message :D

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.10 beta
* Browser name and version: Chrome 56.x
* Environment name and version: MySQL 5.6, PHP 7.1.9
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM 7.10 beta - installation wizard alert suggestion](https://trello.com/c/t8MxYXM9/238-suitecrm-710-beta-installation-wizard-alert-suggestion)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
