### ISSUE TITLE
SuiteCRM 7.10 beta - unnecessary buttons + calendar suggestions

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4563]
#### Issue

Hi, why we need buttons/menu in actions for things which are showing?

1. If you are in Giant view of project.. why do you need this Giant button or see it in menu... ??
 - should show only buttons which we really need ?

![2017-11-21_1741](https://user-images.githubusercontent.com/5773777/33084963-92d1d53e-cee3-11e7-8d6e-79938e00ffd9.png)

2. why we have not in sidebar of call/meeting/task modules the menu CALENDAR... why i must find in main menu calendar and see my taks/meetings/call by graphic way ?
- should be easier if will possible in modules like calls/meetings/tasks find menu CALENDAR (as we have for example in project resource calendar) and show it in calendar.

User save the many time if doesn't will need to find the calendar module... 

![2017-11-21_1746](https://user-images.githubusercontent.com/5773777/33085351-c0f80d7e-cee4-11e7-85a3-11258c13b7a6.png)

#### Expected Behavior

I am expecting for all modules which have spec. view as Projects, 

1. If i am in giant view in project i don't need Giant view button.. if i am in detail view i don't need Detail view button
2. Will more UX if will user find on sidebar calendar module for calls/meetings/tasks

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.10 beta
* Browser name and version: Chrome 56.x
* Environment name and version: MySQL 5.6, PHP 7.1.9
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM 7.10 beta - unnecessary buttons + calendar suggestions](https://trello.com/c/E01fJDLS/239-suitecrm-710-beta-unnecessary-buttons-calendar-suggestions)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
