### ISSUE TITLE
SuiteCRM 7.10 beta - "Save columns as" + Reset button for choose columns pop up window suggestion

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4566]
Will great if will possible create also filter for columns. 

If record has many data (fields) you can't put it all in on list view.. will it big mess.. but you should create filter for column like Financial, Basic, Modified, Industry etc

and you will see the column of sort of data which are you interesting of.. maybe you want see only names + phone numbers + email address .. sometimes you want only see to which user are records assigned, who modified records, when was created and modified and to which group.

Choose your columns that you create custom list view.. but you will able to save this list-views.

Also will great if will user reset the columns to default list view which are setting up by admin in studio for each module.  The best will add RESET button to choose columns pop up window.

**Comment by Mausino** [comment]
We added it and employees love it.. only missing also "Save columns as" that we can have filter also for any order of columns in listview

![2018-01-05_1513](https://user-images.githubusercontent.com/5773777/34612690-0d015d7e-f22b-11e7-896c-7a3e61659d15.png)

**Comment by pgorod** [comment]
@Mausino when you say you added it and your users loved it, does that mean you already have this code and you're going to contribute a PR? :-)

**Comment by Mausino** [comment]
@pgorod with github pull request i have not experience.. + others which are more experienced also have problems :) i can ask my developer to add me changes and i will add here the changed files or something like that. If somebody copy and paste to pull request, i have any problem with it. :)

**Comment by pgorod** [comment]
If you don't want to go into the Git details I suggest this, using only the web interface here on GitHub:

- fork the SuiteCRM project into your own GitHub area
- ask your developer to change the files there on some new branch
- tell us about it when it's ready. Even if you don't do the PR yourself, we can have a look at the code and play with it, and then we'll what's next.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM 7.10 beta - "Save columns as" + Reset button for choose columns pop up window suggestion](https://trello.com/c/XsUGioo5/240-suitecrm-710-beta-save-columns-as-reset-button-for-choose-columns-pop-up-window-suggestion)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
