### ISSUE TITLE
Suitecrm DATE Parameter not working properly

### ISSUE THREAD

**Issue by karthik5595** [salesagility/SuiteCRM#4567]
I need to create report like new customers to be filtered with some between date interval.
while i'm not passing parameter its working fine. but using parameter to filter with dates its having some issues??
![condition](https://user-images.githubusercontent.com/33372200/33115860-8d15cab0-cf88-11e7-8b76-7539ec5e1138.png)

#### Issue

The date format can be changed to some other format.
![updatecmd](https://user-images.githubusercontent.com/33372200/33116057-4798a3bc-cf89-11e7-8e8a-014b0db9fc1f.png)
![result](https://user-images.githubusercontent.com/33372200/33116056-475c0d80-cf89-11e7-801f-0c26870fda9e.png)

#### Expected Behavior

Need to filter between 01-11-2017 to 23-11-2017

#### Actual Behavior

The date format changed into 11-01-2017  and another date box shows empty result.

#### Steps to Reproduce

1.change date format in your parameter to 23.12.2023
2.Go to report, still seems to work
3.Press "update", parameter field gets empty, result is unfiltered

#### Your Environment

* SuiteCRM Version used:7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chrome Version 62.0.3202.94 (Official Build) (32-bit)
* Environment name and version (e.g. MySQL, PHP 7):MySQL :5.7.14 PHP:5.6.25
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by PedroErnst** [comment]
This has been fixed in newer versions.
