### ISSUE TITLE
suggestion: Enable WF priority or sequence

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#4591]
#### Suggestion

It would be great if I could define with which sequence multiple workflows fire, in such instances where multiple workflows get triggered for one and the same record (i.e. the workflow criteria of multiple workflows are met at the same time for the same record).

See here for more details:
https://suitecrm.com/forum/suitecrm-7-0-discussion/16418-workflow-sequence-when-multiple-workflows-fire-on-same-record

#### Expected Behavior

When multiple workflows run on the same record and event, the sequence with which they fire should be determined by the user.

#### Actual Behavior

When multiple workflows run on the same record and event, the sequence with which they fire is determined by the respective workflow ID.
The sequence with which Workflows fire, that run on the same record, is defined by the ID of the workflow.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [suggestion: Enable WF priority or sequence](https://trello.com/c/RRQFy7nA/241-suggestion-enable-wf-priority-or-sequence)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
