### ISSUE TITLE
HTML Fields Not Displaying

### ISSUE THREAD

**Issue by mjrcrm** [salesagility/SuiteCRM#4598]
Issue:

HTML field only showing HTML markup in Edit View and not displaying anything in Detail View.

Expected Behavior:

Enter Default HTML in Studio. HTML Field displayed to user in edit or detail view.

SuiteCRM Version: 7.9.9 Build 344.

Google Chrome is up to date
Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by Dillon-Brown** [comment]
Unable to replicate with 7.10.x. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
