### ISSUE TITLE
Identical file names in folder

### ISSUE THREAD

**Issue by vic-t** [salesagility/SuiteCRM#460]
Certain (language) folders under the modules directory contain file names that Eclipse on Windows considers to be the same (such as fr_FR.* and fr_fr.*).

I'm not sure if that's necessary but it's screwing up my Eclipse/Egit configuration since Eclipse cannot see the double but Egit can.  

I did a diff on some of the files, they seem to be identical. Maybe you could remove one of the two? 

Otherwise I'd be happy for pointers how to deal with this in my situation. 

Thanks, 
Vic

**Comment by horus68** [comment]
related: https://github.com/salesagility/SuiteCRM/issues/488

Note: those language files (without language packs) should simply be deleted!
They are available when a language pack is installed
