### ISSUE TITLE
There's no `session.save_path` with Redis

### ISSUE THREAD

**Issue by skynet** [salesagility/SuiteCRM#462]
This is wrong. I have Redis setup to handle sessions. There's no `session.save_path` with Redis.

```
SuiteCRM relies upon PHP sessions to store important information while connected to this web server. Your PHP installation does not have the Session information correctly configured. 

A common misconfiguration is that the 'session.save_path' directive is not pointing to a valid directory. 

Please correct your PHP configuration in the php.ini file located here below.
/usr/local/lib/php.ini
```

**Comment by chris001** [comment]
Note, Sugar was first released in 2004.  Redis first release came along in 2009 when Sugar was already at version 5.
I agree tho, it's time to make SuiteCRM Redis-aware, and take full advantage of the improved session handling technology.
You should fork the SuiteCRM code, modify the session handler code to work with either Redis or regular PHP session.save_path, and make a pull request.  It's sure to be accepted.

**Comment by skynet** [comment]
Will do!

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [There's no `session.save_path` with Redis](https://trello.com/c/288ZR8D9/177-there-s-no-session-save-path-with-redis)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
