### ISSUE TITLE
Share button which gives url to object without "ajax"

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4620]
It would be nice to have a share action button on the top of all detail views. It would give you an option of different ways to share the object. But the first and most important one would be to copy/paste the url to the object without all of the "ajax information".

e.g. https://suitecrm.example.org/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DLeads%26offset%3D6%26stamp%3D1512153296023515600%26return_module%3DLeads%26action%3DDetailView%26record%3D0e97-8733-044e TURNS INTO https://suitecrm.example.org/index.php?index.php?module=Leads&action=DetailView&record=0e97-8733-044e

#### Issue

Currently if you attempt to share or bookmark a link from an object page the url contains all of the ajax information in the url rather than a clean short precise url.

#### Expected Behavior

urls of objects should have a clean short intelligible url

#### Actual Behavior

Currently the url contains all of the garbage of the ajax system.

#### Possible Fix

A share button which shows the link without the ajax information
#### Context

I want to share a url with someone for an object in the system. It's long and easily mangled.

#### Your Environment

Version 7.9.7
Sugar Version 6.5.25 (Build 344)

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Share button which gives url to object without "ajax"](https://trello.com/c/tNMoOu6y/242-share-button-which-gives-url-to-object-without-ajax)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
