### ISSUE TITLE
SuiteCRM 7.8.8 LTS navigation button email

### ISSUE THREAD

**Issue by centoasa** [salesagility/SuiteCRM#4621]
Versione 7.8.8
Sugar Versione 6.5.25 (Build 344)
FIRST:
![schermata 2017-12-02 alle 09 27 49](https://user-images.githubusercontent.com/5500935/33513469-c6ecd55e-d743-11e7-8249-a5f79a3e10d9.png)
The navigation button very often disappear, so I can't get an older email.
Thank you
AFTER:
![schermata 2017-12-02 alle 09 33 46](https://user-images.githubusercontent.com/5500935/33513480-fb792296-d743-11e7-9d38-dbfb603ef190.png)

**Comment by dursuntosun** [comment]
When i try this, it is solved. I m using 7.8.9 LTS With Suite7.
#listViewDiv .pagination {
margin-bottom: 10px;
**margin-top: 0;** // add this
}

**Comment by hubyhuby** [comment]
I have this issue to in 7.8.8; updating to 7.8.10 didn t resolved it.
I personaly have never seen the menu at all at the bottom, either in chrome or firefox under windows or Linux.
On firefox linux at least I can t see it with either of the 3 themes.
