### ISSUE TITLE
in detail/edit view AOS_Quotes date_entered and date_modified displayed in wrong way if format is dd/mm/yyyy

### ISSUE THREAD

**Issue by jekopsen** [salesagility/SuiteCRM#4623]
In detail/edit view on AOS_Quotes module the "date_entered"  and "date_modified" fields are displayed wrongly if user format is set to dd/mm/yyyy. 

#################################################
To reproduce:
1) Try to set in yours user localization preferences date format as dd/mm/yyyy
2) The edit a quote in ad day between 1 and 12 and a different month (Eg: for 1st Dec 2017)

3) Then you will see in edit/detail view date_modified as 12/01/2017.
4) I'm expecting to view 01/12/2017.

#################################################
I have suite Version 7.9.4 (Sugar Version 6.5.24 (Build 509)).
Browser Chrome Version 51.0.2704.63 (64-bit)):
Environment MySQL, PHP 7.

**Comment by ChangezKhan** [comment]
Can you provide details such as what values are there in database for date_entered and date_modified columns before you get this error and after this error?

**Comment by PedroErnst** [comment]
Not able to reproduce this on either 7.8.12 or 7.9.11

Setting date format to dd/mm/yyyy

Editing a quote on 7 february

![screenshot from 2018-02-07 10-25-33](https://user-images.githubusercontent.com/34056696/35911391-982dc2ae-0bf1-11e8-899b-32c57bed69f8.png)

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
