### ISSUE TITLE
Why do we have to change "date.timezone" in php.ini

### ISSUE THREAD

**Issue by skynet** [salesagility/SuiteCRM#463]
```
[FATAL] Configuration variable date.timezone is not set, guessed timezone UTC. Please set date.timezone="UTC" in php.ini!
```

This should be a local option not a php.ini option.

**Comment by skynet** [comment]
PS: Looks like this idiotic error code comes from SugarCRM. And it seems that we have to live with stupidity from v6. They may have fixed this in v7. Is there any serious commitment to build a better version of SugarCRM or just trying to piggy back on something that was built and left defective by others?

**Comment by chris001** [comment]
The catch is, there are other PHP libraries, used by Sugar and Suite, such as PHPMailer, and the cron job which calls Sugar Scheduler from a separate cli environment, which read the date.timezone offset from their PHP runtime environment, not from Sugar/Suite's local config.php.
Further complicating matters, there are some popular PHP execution modes which do not use a local copy of php.ini in the local web application directory, for security reasons these execution modes use only the global php.ini file associated with the user login account..Many installations use this execution mode. So you're still back to that limitation of having to set that timezone offset in the php.ini used by the php interpreter.
Anyway, agreed that it would be nicer to have all the settings contained locally.
If you can improve the code, by all means..

**Comment by skynet** [comment]
:+1:
