### ISSUE TITLE
email variables are not filled properly in email template... 

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#4636]
Using email template in any of the process that we would benefit from such an interresting feature; When we send an email and would like to add variables from the menu they do not get fulfilled.
This problem has been reported really often in the forum but I believe no one  reported here.

how to replicate, simply build an email template and insert variables, 99% of them won't work when you are sending emails...  the variable will not be filled up.

It would such a nice feature to bring to life...

**Comment by pgorod** [comment]
I confirm this is a very common complaint. It is a reasonably important issue, since some people end up sending ugly email to their customers...

**Comment by Dillon-Brown** [comment]
Hi @bmwtourer, do you have an example of some email variables that aren't working? the few I tried seemed to successfully populate.

**Comment by bmwtourer** [comment]
Hello
It seems to work for accounts and contacts but it stops there
it would make sense that we could use it for cases and opportunities as well.
The fact that many information or "possibilities" are presented (while it does not work) confuse the user...
just testing for opportunities
opportunity name:$opportunity_name
assigned username: $opportunity_assigned_user_name
for cases
Case subject: $acase_name
case description :$acase_description
assigned to user name:$acase_assigned_user_name
Case number:$acase_case_number
Case status:$acase_status
Case state: $acase_state
Case account Name:$acase_account_name
not sure if the next one make sense, but i tried it anyway...
case updated threated;$acase_aop_case_updates_threaded

**Comment by Dillon-Brown** [comment]
@bmwtourer What version of SuiteCRM are you using? I've tried replicating this on 7.9.7 but so far all the mentioned variables are working as expected.

**Comment by bmwtourer** [comment]
oops forgot to mention... 7.8.8  updated last weeked from 7.8.6

**Comment by Dillon-Brown** [comment]
It looks like this may be related to #3838 which was merged into hotfix and not hotfix-7.8.x. I'll mark this as a high priority bug while I investigate but it looks like this may be a simple case of copying the 7.9.x fix over to 7.8.x. Thanks for the assistance!

**Comment by bmwtourer** [comment]
thank you!
