### ISSUE TITLE
7.10 Beta2 repeatedly asks for expired password replacement

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#4639]
#### Issue
When I log in, after my password is accepted, I always get this screen:

![image](https://user-images.githubusercontent.com/15945027/33713266-809fdc4c-db42-11e7-8cfe-9b029efd5f70.png)

Note that this is not my log in screen, I'm past that at this point. It's inside the CRM, I have the menus, but I'm asked to replace my expired password.

It doesn't matter if I use the same password or a new one, and it doesn't matter if's a simple or complex password.

After putting in the new password, I can use the CRM correctly. When I need to log in again, though, I am always taken to that same screen.

There should be some message - either accept the old password for good, or tell me why not and force me to provide a valid one.

#### Steps to Reproduce
1. Log in to the CRM. 
2. I am unsure as to what exact circumstances cause the message to be shown to me... I am not told the reason for expiry... and it's expired even if it's a new password just recently created.

#### Your Environment

* SuiteCRM Version used: 7.10-beta2, upgraded from previous versions, not freshly installed. I had this behaviour already in Beta1
* Browser name and version: Firefox 56
* Environment name and version: MySQL 5.7, PHP 7.0
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
I believe this is related to the default password expiration set in the config. We'll need to change the default to something reasonable but you can change it manually as a temporary workaround.

**Comment by Mausino** [comment]
Yes.. this is part of issue which i reported, @pgorod please look on #4552 if it solves your issue ticket

**Comment by pgorod** [comment]
This is not solved in Beta3. And it happens to all users I tried, not just one. Probably the same issue as #4722.

**Comment by pgorod** [comment]
This is a test system that I've been successively upgrading. I don't remember exactly where I started, maybe 7.8.something, but it's been getting every small upgrade since. 

In this case, I believe the issue was introduced upgrading from 7.9.x to 7.10 Beta1. 

I believe 7.9 was at version 7.9.7 when the Beta1 came out?...

**Comment by daniel-samson** [comment]
There is a work around.

- Go to Admin
- Go to Password management
- change the expires
- click save

This should get rid of the issue in the mean time.

**Comment by liquidocelot** [comment]
The Password Management screen only has and expiry setting under the "Enable System-Generated Passwords Feature". There is not a work around to stop this from happening if you don't use that.

**Comment by pgorod** [comment]
@liquidocelot make sure you're on 7.10 Beta if you're following this issue here.

If you have a similar problem on 7.9.x or 7.8.x then follow #4722

**Comment by liquidocelot** [comment]
I'm on Version 7.10 beta-2

**Comment by pgorod** [comment]
Try Beta3, I think there's a difference on the Settings screen so you can use the workaround like I did.

But what really intrigues me is why this is happening to us, it doesn't seem to happen to everybody...

**Comment by liquidocelot** [comment]
Haha, just upgraded to beta 3 and it still doesn't have the setting. And now the who thing is missing the majority of  images and checkboxes.
![image](https://user-images.githubusercontent.com/3066743/34222219-6e9936c2-e580-11e7-9f5c-71434568f782.png)

**Comment by pgorod** [comment]
You can try a Quick Repair and Rebuild, or deleting `cache/themes`. If the problem persists, or if it is appearing elsewhere in your system, I would say you have Linux permissions problems.

**Comment by pgorod** [comment]
Just as an update, it seems this is in fact related to #4722 and the solution is to completely remove the SuitePImproved package from Module Loader.
