### ISSUE TITLE
Create Project from Project Templates start date issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#464]
Hi, 

If you wan create project from project template, and you will not fill the start day

http://screencast.com/t/lqCa6veNUB

which is not requered, it shows you this fatal error:

Fatal error: Call to a member function format() on a non-object in /home/unterkun/public_html/a_sub/crm/modules/AM_ProjectTemplates/controller.php on line 36

and project was not created.

I think, that need to set up as default day the "today" when was project created if user doesn't fill the start day.

Mikolaj

**Comment by darthtang** [comment]
I have now rectified the problem. 

Thanks for the bug find!

**Comment by shogunpol** [comment]
@Mausino , the issue has been tested in recent version of SuiteCRM(7.7.4), and it not appear.
Can you confirm is this still an issue on recent version of SuiteCRM?
Thanks for contribution.

**Comment by Mausino** [comment]
@shogunpol i can confirm that issue is not apear

**Comment by pgorod** [comment]
I am getting this on 7.11.5, start date is not required, and creating the Project (from the project template) without a start data gives a fatal:

```php
Sat Sep 28 11:08:22 2019 [21544][1][INFO] Query Execution Time:0.00079488754272461
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP Notice:  Undefined variable: startdate in /var/www/html/modules/AM_ProjectTemplates/controller.php on line 191
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP Stack trace:
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   1. {main}() /var/www/html/index.php:0
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   2. SugarApplication->execute() /var/www/html/index.php:54
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   3. AM_ProjectTemplatesController->execute() /var/www/html/include/MVC/SugarApplication.php:113
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   4. AM_ProjectTemplatesController->process() /var/www/html/include/MVC/Controller/SugarController.php:373
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   5. AM_ProjectTemplatesController->handle_action() /var/www/html/include/MVC/Controller/SugarController.php:468
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   6. AM_ProjectTemplatesController->do_action() /var/www/html/include/MVC/Controller/SugarController.php:494
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP   7. AM_ProjectTemplatesController->action_create_project() /var/www/html/include/MVC/Controller/SugarController.php:525
```

```php
[28-Sep-2019 11:08:22 Europe/Lisbon] PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /var/www/html/modules/AM_ProjectTemplates/controller.php:196
Stack trace:
0. include/MVC/Controller/SugarController.php(525): AM_ProjectTemplatesController->action_create_project()
1. include/MVC/Controller/SugarController.php(494): SugarController->do_action()
2. include/MVC/Controller/SugarController.php(468): SugarController->handle_action()
3. include/MVC/Controller/SugarController.php(373): SugarController->process()
4. include/MVC/SugarApplication.php(113): SugarController->execute()
5. index.php(54): SugarApplication->execute()
6. {main}
  thrown in /var/www/html/modules/AM_ProjectTemplates/controller.php on line 196
```
The code in the PR doesn't seem to have been merged... #474

**Comment by Mausino** [comment]
@Dillon-Brown should look on this and should you merge the #474

**Comment by Dillon-Brown** [comment]
@Mausino Worth looking into at the very least, those PHP fatals are definitely an issue. I'm wondering if the logic here was that you should be able to create a project from a template without a start date. I do see that project module itself has start date and end date field marked as required though so I don't see any issue with a PR that adds these as required to project templates.

**Comment by Mausino** [comment]
We implemented too much PR's which weren't merged yet. and sometimes is very hard to compare our system with fresh official installation.. because our system is the mix of official an unofficial PR's and plus with our own code. 

@Dillon-Brown before the "revolution" of **milestones**... now the **sprints** the communication with community was frozen or very unclear. it's very old issue :) and the level of code or communication in this project SuiteCRM is +100 levels better as before when the issue was reported 🥇

**Comment by pgorod** [comment]
The `required` fields should definitely be consistent across the several screens that allow a record to be created. We've had this problem before with some other modules (maybe Tasks, I don't remember) where the creation from the Pop-up allowed a blank field, and it would break somewhere else, where the required field was expected to exist.

This should even be checked at an object layer, not on screens. The Bean shouldn't save without a required field...

But for this one, I guess we can just label this `Fix proposed` and merge the existing PR...

**Comment by Kevconry** [comment]
Can't replicate in 7.13.1, please re-raise or Get in touch if you are still having this issue

**Comment by johnM2401** [comment]
Closing issue, Looks like the Project *can* now be saved without a FATAL error, using the steps provided, in 7.13.1

However, as @pgorod noted, the "Start Date" should ideally be required on this popup, to stay consistent with the Projects Module.

Perhaps this may be worth raising as its own separate issue?

Thanks!
