### ISSUE TITLE
Continuous Reloading of dashboard, and empty sidebar

### ISSUE THREAD

**Issue by ITTEKS** [salesagility/SuiteCRM#4647]
Hi Guys,

I have installed fresh SuiteCRM on Nginx server. I'm facing two problems with it, as soon as I login to the SuiteCRM, it continuously reloads the page after 2 seconds. The second issue is that the left side bar is completely empty.

I would appreciate help in this regard, as I did a search for this issue on google there was number of people with the same problem but I could not find any solution for it.

 Thanks

**Comment by pgorod** [comment]
@ITTEKS Hi, welcome to SuiteCRM. I can try helping you with this issue, but we shouldn't be doing this here on GitHub. Please close this issue and open a thread on the Forums instead:

https://suitecrm.com/forum

Thanks, see you there

**Comment by ITTEKS** [comment]
Hi pgorod, 

I would really appreciate your help with this, I have already opened one up on https://suitecrm.com/forum, I have had no replies for it at all. I have been losing my hair over this trying to figured it out. Please see the link below this is where I opened up a thread there 2 days ago.

https://suitecrm.com/forum/suitecrm-7-0-discussion/16945-continuous-reloading-after-login-empty-side-bar
