### ISSUE TITLE
PROCESS_OUTPUT Error message: Full stop or Ellipsis?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4657]
#### Issue

the language file modules/Administration/language/en_us.lang.php
has 2 strings with double ending dots.
Should this be changed to 1 dot (full stop, period) or 3 dots (Ellipsis)?

https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Administration/language/en_us.lang.php#L898-L899
    'LBL_PROCESS_OUTPUT_CLEANUP_ERROR' => "Unable to cleanup output file. Please check permission..",
    'LBL_PROCESS_OUTPUT_WRITE_ERROR' => "Unable to write output file. Please check permission..",

#### Context

This will be very different in translations!

**Comment by Dillon-Brown** [comment]
Looks like it should probably be a full stop. Well spotted!
