### ISSUE TITLE
Ability to create / edit object's "Created By" "Date Created" using API

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4661]
#### Issue

Need the ability to create an object with a specific "Date Created" (date_entered) and "Created By" value using the API. It appears both v4 and v8 of the API do not allow you to do this.

#### Context

The API is being used to integrate two systems together. Currently there is no way to backport data or create data using the API on a timeline with the other system being the system of record. You also cannot specify which user created the record as only one user is used for the API credentials.

#### Your Environment

* SuiteCRM Version used: 7.10-dev

**Comment by Mausino** [comment]
@isleshocky77  i saw somewhere the pull request on this... but can't find it now..

**Comment by Dillon-Brown** [comment]
The assigned user is something we are looking at whereas the date_modified is a suggestion.
