### ISSUE TITLE
Email through 'Bulk Action' on multiple selected contacts not populating 'To:' field

### ISSUE THREAD

**Issue by e-reeley** [salesagility/SuiteCRM#4662]
#### Issue
When using the bulk action option to 'Email' multiple 'Contacts' in the 'Contacts' module, the 'To:' field is not being populated with these addresses, the field remains empty.

#### Expected Behavior
If multiple are selected then this should populate the 'To:' filed with the corresponding email addresses.

#### Actual Behavior
When this is carried out, the field remains empty.

#### Steps to Reproduce

1. Select the 'Contacts' module
2. Select multiple or one of the rows using the checkbox at the left hand side
3. Under 'Bulk Action' Select Email
4. See that the 'To:' field remains empty

#### Context
Medium Priority

#### Your Environment

* SuiteCRM Version used: 7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium Version 62.0.3202.94
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by cutleron** [comment]
This isn't fixed in my 7.10, Chrome, MySQL PHP 7. @Dillon-Brown ?
