### ISSUE TITLE
Continuous reloading after login & empty side bar

### ISSUE THREAD

**Issue by ITTEKS** [salesagility/SuiteCRM#4663]
Hi Guys,

I have installed fresh SuiteCRM on Nginx server. I'm facing two problems with it, as soon as I login to the SuiteCRM, it continuously reloads the page after 2 seconds. The second issue is that the left side bar is completely empty.

I would appreciate help in this regard, as I did a search for this issue on google there was number of people with the same problem but I could not find any solution for it.

Thanks

**Comment by horus68** [comment]
Duplicated from https://github.com/salesagility/SuiteCRM/issues/4647
