### ISSUE TITLE
Custom Imap Folders

### ISSUE THREAD

**Issue by miquelangeld** [salesagility/SuiteCRM#4664]
#### Issue
SuiteCRM is unable to monitor folders inside INBOX

#### Expected Behavior
The expected behaviour is to see a folder tree:
INBOX
     -->FOLDER A
     -->FOLDER B
     -->FOLDER ...

#### Actual Behavior
When I select folders inside INBOX to be monitored in the folders list show one empty folder with the names of selected folders separated by commas
INBOX,FOLDER A,FOLDER B, FOLDER...

#### Steps to Reproduce
1. Configure an Imap Account
2. Select folders inside MAILBOX to be monitored
3.
4.

#### Context
I'm affected since I updated to 7.9.X, now we updated to  7.9.7

#### Your Environment

* SuiteCRM Version used: 7.9.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any browser
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Mausino** [comment]
yes... @javitoron this problem is in core.. when you choosing the 3 folders when you creating the imap connection. there are only Inbox, Sent, Trash... nothing more

**Comment by miquelangeld** [comment]
Prefect, thanks. I'll wait for the fix release.
