### ISSUE TITLE
I don't get any notifications for my tasks, calls or emails

### ISSUE THREAD

**Issue by benromero** [salesagility/SuiteCRM#467]
The notification icon shows 0 always. And It says: This information is not available.

I use SuiteCRM with the Spanish language.

**Comment by rcairello** [comment]
Same thing here.

**Comment by daniel-samson** [comment]
At the moment, the notification icon will only work on meetings and calls. Further changes are coming to alerts for 7.4. But in the mean time. Do you have desktop notifications set up in your browser? Are you receiving any alerts?
