### ISSUE TITLE
Flex relate field issue, data now shown on Edit and Detail View.

### ISSUE THREAD

**Issue by khan01** [salesagility/SuiteCRM#468]
Adding a flex relate field as mentioned below does not show data on Edit and Detail Screens. Although the data values are saved correctly, parent_id also gets populated correctly in Edit View but Parent Name text box does not get its value. 
Same issue on Detail View, module name is shown correctly but the value is not being pulled up.

http://developer.sugarcrm.com/2011/05/16/howto-create-a-flex-relate-for-other-modules/

**Comment by mattlorimer** [comment]
Please ask support questions on the [forum](https://suitecrm.com/forum/index)
