### ISSUE TITLE
Contact s Email addresses are deleted when saving the parent Account

### ISSUE THREAD

**Issue by napalmCore** [salesagility/SuiteCRM#4695]
When creating a new workflow which modify realted contacts on Account save, when triggering the workflow by Editing Any Account i noticed that all contacts related to that Account have lost their email addresses.  

#### Expected Behavior
Should save the related contacts without deleting the emails addresses

#### Actual Behavior
After the workflow is triggered When Saving an Account the contacts related to the Account lose their emails addresses.

#### Steps to Reproduce
1. create new workflow
2. Define WorkFlow Module as: Account
3. Define Run as: Only on save
4. Define Run On as: Modified Records
5. Create New Conditions on Any Account s field
6. Create New Action Modify record
7. Select record Type as Contacts.
8. Save the workflow
8. Go to any Account which has related Contacts .
9. Edit the Account and hit save
10. Expect that all the related contacts will lose their email addresses.
 

#### Context
https://demo.suiteondemand.com/index.php

#### Your Environment
https://demo.suiteondemand.com/index.php

**Comment by PedroErnst** [comment]
Can confirm this happens, I'm going to look into it.

**Comment by PedroErnst** [comment]
Wasn't able to reproduce this on the current 7.9.8 version on localhost.

The version for demo.suiteondemand.com is 7.9.7, and there it does happen every time.

**Comment by PedroErnst** [comment]
Still happens in 7.10.
