### ISSUE TITLE
Happiness Question (translation issue)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#4699]
'LBL_HAPPINESS_QUESTION'
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/language/en_us.lang.php#L75

'LBL_HAPPINESS'
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/SurveyResponses/language/en_us.lang.php#L72

Tell me some additional information about these labels please (for a quality translation).

**Comment by horus68** [comment]
its from a new module for Surveys, I believe its to be used as a label for the fields to Rating Levels of Satisfaction in a Survey.

The general idea: Rating and Ranking Levels of Satisfaction in Your Survey
https://www.snapsurveys.com/blog/rating-and-ranking-levels-of-satisfaction-in-your-survey/

**Comment by pgorod** [comment]
You know an open-source project is mature when contributors open issues asking, **what is happiness?** Now there's a question we must all ask ourselves often. If we only knew the answer to that one... everybody wants it and no one knows exactly what it is...

:-)

**Comment by horus68** [comment]
> everybody wants it and no one knows exactly what it is...
This is usually the case in some projects... Devs makes a PR promising some new feature but, being undocumented, nobody knows what it does and how to test it!
Very satisfied (not) :)
