### ISSUE TITLE
SuiteCRM 7.9.8 Inbound email with a hyphen in the name will not display emails

### ISSUE THREAD

**Issue by Cheezecake245** [salesagility/SuiteCRM#4718]
#### Issue

Need to setup an inbound gmail account with a hyphen in the domain name (example@my-domain.com) that's been giving me trouble.

#### Expected Behavior

Show emails from hyphenated gmail domain in the imap view

#### Actual Behavior

 I tried everything I could find. Outbound works, inbound shows it works, cron jobs are running, then shows no emails. I can see the emails in the sql database, they just aren't showing in the list. Then I tried a different gmail account that ends in @gmail.com and it works fine. I can see all the emails and interact with the imap server, mark things as read and unread and whatnot. Tried another @gmail address and it worked fine too. Then setup another instance of SuiteCrm on another fresh machine, and got the same result, inbound works for @gmail accounts, but not for the hyphened email. Only thing in the SuiteCrm.log is [12748][1][FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder.

#### Steps to Reproduce

1. add hyphenated domain name email to the inbound email.
2.run cron job
3.no emails ;(

#### Context

This is keeping my client with hyphenated domain name from receiving emails within SuiteCrm

#### Your Environment

* SuiteCRM Version used: 7.9.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.1.29-MariaDB,Apache/2.4.29 (Win32) OpenSSL/1.0.2n PHP/7.1.12
* Operating System and version (e.g Ubuntu 16.04):  tested on Windows 10 Pro 64bit, Windows Server 2013

**Comment by PedroErnst** [comment]
Investigating this issue I came across a small bug in the InboundEmail class, which a priori didn't seem to have any connection to this, but after fixing it I was able to retrieve the emails from a hyphenated domain address where before I wasn't getting any return.

After fixing this apparently unrelated bug I have not been able to reproduce this issue anymore.

**Comment by Cheezecake245** [comment]
This has solved my issue as well, thank you!

**Comment by horus68** [comment]
@Cheezecake245 please reopen this. Even if your issue is solved it is not implemented in code yet (PR merged). Usually issues are only closed if created by mistake or when a PR is merged (and it can be done automatically or by hand)
