### ISSUE TITLE
After upgrade to 7.9.8 no emails are shown on my inbox module

### ISSUE THREAD

**Issue by ohadranen** [salesagility/SuiteCRM#4746]
#### Issue

The connection to my gmail works, I can also view my gmail sent items using suitecrm email module, but when accessing the inbox I get:
"You currently have no records saved. CREATE or Import one now." although I have plenty of emails on my inbox.
Viewing sent email folder works, but no emails on inbox.
Other users inbox works as well.
I've tried removing the email settings and recreating it with no luck.
No errors on any log.

#### Expected Behavior

View the list of emails in my inbox 

#### Actual Behavior

Getting: "You currently have no records saved. CREATE or Import one now." 

#### Steps to Reproduce

1. Just go to suitecrm email module.
2.
3.
4.

#### Context

high priority, can'y use the email module

#### Your Environment

* SuiteCRM Version used:
7.9.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Version 63.0.3239.84 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
PHP 7.0.25
mysql  Ver 14.14 Distrib 5.5.58

* Operating System and version (e.g Ubuntu 16.04):
amazon-linux-ami/2017.09

**Comment by PedroErnst** [comment]
Thank you for bringing this up.

Which version of SuiteCRM were you using before?

When you say 'Other users inbox works as well' do you mean other folders, or another users inbox?

**Comment by pichto** [comment]
Hi there!

Same problem. Upgraded from 7.9.7 to 7.9.8 and now the email module doesn't show any emails... just nothing!!

Need a fix ASAP!

**Comment by PedroErnst** [comment]
I've been looking into it and I believe this is fixed in #4731 (and the same underlying issue as #4718)

**Comment by jbnl** [comment]
I have this problem with the latest build. When I e-mail myself on the e-mail address SuiteCRM sees the e-mail, creates a case etc. But when I visit the E-mail tab it only shows: You currently have no records saved. CREATE or Import one now.

Latest version of OSX, Safari
 
SuiteCRM:
Version 7.10.4
Sugar Version 6.5.25 (Build 344)

**Comment by fcorluka** [comment]
I have a fresh installation of 7.10.7 and have the same issue!
I thought the is a problem in my code (error in .zip) so I went into SuiteCRM DEMO, and there is the same issue. I will try fix, but it I believe this needs to be fixed ASAP because this way seems that Email module is broken.

I have tested FIX (on 7.10.7) and this code is inside but not working.

Please OPEN issue.
