### ISSUE TITLE
"Performing Task" dialogue never closes on the first update to a case 

### ISSUE THREAD

**Issue by davenz** [salesagility/SuiteCRM#475]
The server is running SuiteCRM 7.3.1 on Ubuntu 14.04, on a private network. The client is running Firefox v40, Ubuntu 14.04, on the same network.

To reproduce:

1) Create and save a new Case
2) Perform an update to the case, and click Save. The update is successfully saved, but the "Performing Task" dialogue never closes and must be manually dismissed:
![suitecrm-caseupdateissue-1](https://cloud.githubusercontent.com/assets/3925818/9975691/b3ec5c4e-5f19-11e5-829f-f7afb88f1a77.png)

Note that subsequent case updates are fine: the "Performing Task" dialogue appears briefly and then disappears as expected:
![suitecrm-caseupdateissue-2](https://cloud.githubusercontent.com/assets/3925818/9975692/ccb393c8-5f19-11e5-8322-bb3290a5030c.png)

**Comment by ghermans** [comment]
This has been reported weeks ago https://github.com/salesagility/SuiteCRM/issues/332

**Comment by Mausino** [comment]
I think, that this problem is relate with  #473
