### ISSUE TITLE
Project Tasks validation error due to wrong date format

### ISSUE THREAD

**Issue by edvineshagh** [salesagility/SuiteCRM#4751]
#### Issue

Unable to update existing project task when the form contains the field "Due date" because the form defaults to YYYY-MM-DD date format (as appose to MM/DD/YYYY)

#### Expected Behavior

The Project Task "Due date" field should be in format of MM/DD/YYYY
Thereby, allowing the user to save the form.
Currently, the user must update Due date field on every save operation.

#### Actual Behavior

On first time edit, user enters a valid format date (e.g. MM/DD/YYYY); however, when view the project task, the invalid date format is rendered (e.g. YYYY/MM/DD).  Furthermore, when the user edits the form, the invalid date format is used to prepopulate the due date; thus, resulting in a client side validation error.

#### Steps to Reproduce

1. Navigate to Admin -> Studio -> Project Tasks -> Layouts -> Edit View
2. Add a New Row
3. Add Due Date field into the new row
4. Save & Deploy changes
5. Navigate to ALL -> Projects
6. Edit (or create) a project
7. Edit (or create) a project task
8. Populate project task Due date field
9. Save changes
* Notice that the "Due date" field format is YYYY-MM-DD as appose to MM/DD/YYYY
10. Edit project task by selecting Actions -> Edit
11. Attempt to save without making any changes
* You will receive the following validation error: "Invalid Value: Due Date"
12. To save changes as a work-around, enter update the field value to MM/DD/YYYY format.
13. goto step 9

#### Context

This should be considered low-to medium error level.
The user has a workaround, but due date must be edited on every instance, which can lead to invalid data entry.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

SuiteCRM installation Version 7.9.7
Sugar Version 6.5.25 (Build 344)

**Comment by pavithra06** [comment]
Hi @edvineshagh 
you can remove this line **'rel_field' => 'time_due'** from **vardefs.php** file inside of **ProjectTask** module folder.
Its working good.

**Comment by edvineshagh** [comment]
Thanks for the feedback pavithra.
I first copied & update then updated /custom/modules/ProjectTask/vardefs.php
Next, I removed vardefs, and modified the original file /modules/ProjectTask/vardefs.php
But, the issue persists for me
...
        'date_due' => array(
            'name' => 'date_due',
            'vname' => 'LBL_DATE_DUE',
            'type' => 'date',
       //     'rel_field' => 'time_due',
            'audited' => true
        ),
 ...

Thanks,
Edvin

**Comment by pavithra06** [comment]
Hi @edvineshagh 
Can you please do "Quick repair and rebuild" in admin page and clear your browser history. It's may be working.

**Comment by edvineshagh** [comment]
Hi pavithra,

It appears that "Quick repair and rebuild" did the trick.

I'm not sure how to proceed since my original goal was to report the issue so that it is addressed in the main trunk (if not already addressed).

Please let me know if you think the issue should be closed.

Thanks,
Edvin
