### ISSUE TITLE
All Day tasks do not appear in Week calendar view when 'time slots' option disabled

### ISSUE THREAD

**Issue by vanosg** [salesagility/SuiteCRM#4753]
#### Issue
When adding all-day tasks to the calendar (no set start or stop time), they do not appear in the 'week' view if the "Display time slots in Day and Week views" option is not checked. These tasks appear in Monthly view.

#### Expected Behavior
By disabling the "Display time slots in Day and Week views" I would expect all day tasks (things that do not fall within a timeslot) to be displayed in the calendar week view, similar to the monthly view.

#### Actual Behavior
In order to view an all-day task, I have to enable the "Display time slots in Day and Week views". In my case, I have to specify a 1 hour time block in the display options of the settings, to minimize the screen real-estate the calendar takes up with empty time blocks. 

#### Possible Fix
Allow (or add an option) to display all-day tasks without requiring the hourly timeslots for the day to be displayed.

#### Steps to Reproduce

0. Ensure Calendar has "Display time slots in Day and Week views: " checked
1.  Activities->Calendar, Create Task
2. Create a Task called My Project Task, specify a due date for this week and specify Related to: Project Task, 
3. Confirm My Project Task is listed on calendar week view
4. Go to Calendar Settings, uncheck "Display time slots in Day and Week views: "; return to Calendar week view
5. Confirm empty block where My Project Task was previously listed
6. Enter Calendar Monthly view
7. Confirm My Project Task again appears in block

#### Context
I have several tasks due on any day- not associated with any particular time block. Particularly on my dashboard, a week view without hourly time blocks takes up an appropriate, minimal amount of space on the screen, so I can see what is available. Enabling the hourly blocks to see the task pushes other dashlets off the screen. 

#### Your Environment

* SuiteCRM Version used:  Version 7.9.7, Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.1 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): mariadb 10.2.11, php7
* Operating System and version (e.g Ubuntu 16.04): ubuntu 16.04

Thank you!

**Comment by PedroErnst** [comment]
Should be fixed now.
