### ISSUE TITLE
Upgrade script language file needs an update

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4756]
#### Issue

The language file included in the SuiteCRM upgrade script needs an update
- reformat code
- revise links (`sugarforge.org`)
- remove double spaces in sentences
- copyright info missing
- remove ending `?>`

#### Expected Behavior

Also note that the upgrade process can be easily localized in many languages as requested here https://github.com/salesagility/SuiteCRM/issues/3103 (includes PR for translations)

#### Possible Fix

File is not in github, so its not possible to suggest any PR

**Comment by Dillon-Brown** [comment]
Will take a look at this for 7.10.

**Comment by horus68** [comment]
Not ready for the RC ZIP

**Comment by Dillon-Brown** [comment]
Should be fixed in 7.10.
