### ISSUE TITLE
SuiteCRM 7.10 beta-3 Installation crash, vendor/autoload.php missing

### ISSUE THREAD

**Issue by tim1mw** [salesagility/SuiteCRM#4757]
#### Issue
A clean install of SuiteCRM 7.10 beta-3 crashes at the very first step with a blank page. 

#### Expected Behavior
The install page should show!

#### Actual Behavior

Blank page with the following error in the server log:

PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/include/entryPoint.php on line 70
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='/var/www/html/include/..:.:/usr/share/php') in /var/www/html/include/entryPoint.php on line 70

#### Possible Fix

Comment out the require_once() call.

#### Steps to Reproduce

1 - Unzip SuiteCRM 7.10 Beta 3 installer and access the URL in a web browser

#### Context

I've worked my way around this, but a non-programmer would not be able to, so should be high priority.

#### Your Environment
* SuiteCRM Version used: 7.10 Beta 3
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Debian 9

**Comment by samus-aran** [comment]
Installer Package updated :+1:
