### ISSUE TITLE
Pop-up and desktop notifications only work when the Dashboard is not in focus 

### ISSUE THREAD

**Issue by davenz** [salesagility/SuiteCRM#476]
As posted on the forums (at https://suitecrm.com/forum/suitecrm-7-0-discussion/6041-desktop-notifications#22582):

The server is running SuiteCRM 7.3.1 on Ubuntu 14.04, on a private network. The client is running Firefox v40, Ubuntu 14.04, on the same network.

If the Dashboard is in focus at the time the notification is due, you **won't** receive a notification in either style (pop-up or desktop). 

To reproduce:

Under the SuiteCRM user preferences, enable desktop notifications. You should observe a prompt, and a confirmation message on accepting, respectively:
![suitecrm-notifications-2](https://cloud.githubusercontent.com/assets/3925818/9975770/9d1506c6-5f1c-11e5-93b6-ae5be872e08b.png)
![suitecrm-notifications-3](https://cloud.githubusercontent.com/assets/3925818/9975771/9d3fda0e-5f1c-11e5-85c0-e3266ff95c60.png)

Create your meeting accordingly, with the desired pop-up advance notification setting. As long as you've navigated away from the Dashboard, you should observe the desktop notification when the reminder is due:
![suitecrm-notifications-4](https://cloud.githubusercontent.com/assets/3925818/9975774/a457c158-5f1c-11e5-9a5a-f7d581a6f719.png)

Note that this itself doesn't appear to be persistent and will disappear after about five seconds.

In SuiteCRM, you'll observe the same notification prompt:
![suitecrm-notifications-5](https://cloud.githubusercontent.com/assets/3925818/9975776/abe79696-5f1c-11e5-9e15-3d459b5b20bf.png)
![suitecrm-notifications-6](https://cloud.githubusercontent.com/assets/3925818/9975777/abf04e58-5f1c-11e5-824a-ac9d0e2bcae4.png)

By comparison, with desktop notifications disabled, this is what the traditional pop-up looks like (again, you won't observe this if you're on the Dashboard):
![suitecrm-notifications-11](https://cloud.githubusercontent.com/assets/3925818/9975778/b66d2d6a-5f1c-11e5-96b0-ea5b9c643292.png)

Summary: notifications should work irrespective of what page is in focus.

**Comment by danieljsamson** [comment]
I saw your post on the forum and i have been working  on a fix for version 7.4. Alerts will now be persistant.

**Comment by davenz** [comment]
Great, thanks for the fix Daniel! :)

Cheers, 
Dave
