### ISSUE TITLE
Supported Browser version info

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4760]
#### Issue

this is a language string info from the file /include/language/en_us.lang.php
Is this an updated info? 
`WARN_BROWSER_VERSION_WARNING' => '<b>Warning:</b> Your browser version is no longer supported or you are using an unsupported browser.<p></p>The following browser versions are recommended:<p></p><ul><li>Internet Explorer 10 (compatibility view not supported)<li>Firefox 32.0<li>Safari 5.1<li>Chrome 37</ul>',`

https://github.com/salesagility/SuiteCRM/blob/5b3eeb843089279bcb4abea37f3361ec123be4b0/include/language/en_us.lang.php#L1720

#### Possible Fix

Maybe not using recommended for a specific version number but instead say "minimum version"

#### Your Environment

* SuiteCRM Version used: latest from github

**Comment by pgorod** [comment]
May I add that the function that triggers that warning is VERY outdated when compared to what our [Compatibility Matrix](https://suitecrm.com/wiki/index.php/Compatibility_Matrix) says:

https://github.com/salesagility/SuiteCRM/blob/5b3eeb843089279bcb4abea37f3361ec123be4b0/jssource/src_files/include/javascript/sugar_3.js#L189-L218

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
