### ISSUE TITLE
AOR treeview -  tooltip issue (7.10b3)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#4766]
Subj.

![default](https://user-images.githubusercontent.com/5983672/34245537-54f36902-e63b-11e7-939c-8781a324b568.png)

**Comment by PedroErnst** [comment]
Hello,

Please tell how to reach this issue in simple steps in order to fix it ASAP. 

Thank you!

**Comment by likhobory** [comment]
![default](https://user-images.githubusercontent.com/5983672/34251222-71dba808-e650-11e7-8fa1-642428cdbd5f.png)

Drag your cursor over fields area and this message will appear as tooltip.
