### ISSUE TITLE
System Settings

### ISSUE THREAD

**Issue by tien002** [salesagility/SuiteCRM#477]
In the admin section, when clicking on "System Settings" UI no longer appears after upgrading to V7.3.1

**Comment by willrennie** [comment]
Is this still an issue? Most likely permissions or environment, or the upgrade did not run successfully.

**Comment by tien002** [comment]
Issue caused by me trying to lock down site by removing "install" folder after installation. Looks like this folder contains files for more than just the installation process. By reinstating the folder, things started to work again.
