### ISSUE TITLE
Clear html in PDF template

### ISSUE THREAD

**Issue by general03** [salesagility/SuiteCRM#4781]
#### Issue
When I put ```<input type="checkbox" >``` inside content of my PDF template this HTML will be clear

#### Expected Behavior
Keep HTML

#### Actual Behavior
Clean HTML

#### Steps to Reproduce

1. Add ```<input type="checkbox" >``` inside content of PDF template
2. Try to export a PDF

#### Your Environment

* SuiteCRM Version used: 7.9.8
* Browser name and version : Chrome Version 63.0.3239.84 (Build officiel) (64 bits)
* Environment name and version : PHP 7.1
* Operating System and version : Ubuntu 14.04

**Comment by PedroErnst** [comment]
Thanks for reporting this. It's fixed now.

**Comment by general03** [comment]
Thanks to the fix, but you push the code only on hotfix 7.8.x and not on 7.9.x ?

**Comment by PedroErnst** [comment]
I think these changes will be merged into 7.9.x as well.

@Dillon-Brown knows best.

**Comment by Dillon-Brown** [comment]
@general03 hotfix-7.8.x will be merged into hotfix-7.9.x and then develop to ensure that any fixes are included in all versions. The idea being that if you have a fix that is relevant for 7.8.x, 7.9.x and 7.10 you only need to create a single PR to the hotfix-7.8.x branch.

**Comment by general03** [comment]
Thanks for explanation @Dillon-Brown
