### ISSUE TITLE
Security Group selection only works for AJAX disabled modules

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#4783]
#### Issue
In Security Groups Settings you can check "Use Creator Group Select".
If checked, on record create you should be able to select the groups if the creator is member of multiple groups. The selection box only appears on ajax disabled modules.

#### Expected Behavior
Selection Box should appear with ajax enabled modules, too.

#### Actual Behavior
No selection box on create record.

#### Steps to Reproduce

1. Add a user to more than one group
2. Check "Use Creator Group Select" in Security Suite settings.
3. Create a new record in an ajax enabled module (Notes, Tasks, Contacts ...)
4. No selection box appears
5. Disable ajax for that module
6. Create a new record
7. Selection for groups appears on bottom of page

#### Your Environment
* SuiteCRM Version used: 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 63
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Server: Ubuntu 16.04, Client Windows 7

**Comment by pgorod** [comment]
Here's a preliminary look at the flow of the relevant code:

It seems this function is called in an after-save hook:
https://github.com/salesagility/SuiteCRM/blob/master/modules/SecurityGroups/AssignGroups.php#L7

Then this sets a `securitygroups_popup` array in the $SESSION variables, which seems to be picked up at this other function called `popup_onload` which launches the pop-up:

https://github.com/salesagility/SuiteCRM/blob/master/modules/SecurityGroups/AssignGroups.php#L64

This comment in that function references the problem:

https://github.com/salesagility/SuiteCRM/blob/master/modules/SecurityGroups/AssignGroups.php#L102-L103

So it's a know issue, but one that would be nice to be able to overcome....

**Comment by gunnicom** [comment]
> So it's a know issue, but one that would be nice to be able to overcome....
Yes. Or if not at least gets documented.

**Comment by Mausino** [comment]
Maybe the solution of this bug is in your ticket #4565

**Comment by gunnicom** [comment]
@Mausino When i understand your bug, you already assigned the groups. This issue here is that if you create a new record no select box would appear to choose the assigned group.

**Comment by zoltankocsardi** [comment]
It works for me [at the top :)]

![selection_013](https://user-images.githubusercontent.com/19221984/35868230-d4f00e02-0b53-11e8-8ea2-dc85990d2608.png)

**Comment by pgorod** [comment]
@zoltankocsardi just checking, have you tried it in 7.8? That's what the original bug report was for...

**Comment by zoltankocsardi** [comment]
@pgorod yes, I've checked it under 7.8.8

**Comment by gunnicom** [comment]
I will retry tomorrow and close here if it appears to be gone.

**Comment by gunnicom** [comment]
Seems to not happen anymore, i will close this for now.
