### ISSUE TITLE
Selected security groups not saved when "Use Creator Group Select"

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#4784]
#### Issue
Prerequisite:
In Security Groups Settings you can check "Use Creator Group Select".
If checked, on record create you should be able to select the groups if the creator is member of multiple groups. The selection box only appears on ajax disabled modules.

If now you select groups, the new record don't get assigned to any security group.
Of course it gets assigned if overwritten by "Inherit from Created By User" or "Inherit from Assigned To User", but you can not use the selection you want.

#### Expected Behavior
Selection Box should save the security group for the newly created record.

#### Actual Behavior
No security group memberships get saved.

#### Steps to Reproduce

1. Add a user to more than one group
2. Check "Use Creator Group Select" in Security Suite settings.
3. Create a new record in an ajax _disabled_ module (Notes, Tasks, Contacts ...)
4. Create a new record
5. Choose the security groups at the bottom
7. Save
8. Check record. No security groups are attached to that record.

#### Your Environment
* SuiteCRM Version used: 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 63
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Server: Ubuntu 16.04, Client Windows 7

**Comment by PedroErnst** [comment]
I'm not able to reproduce this. 

I checked "Use Creator Group Select" and unchecked both "Inherit from Creator" and "Inherit from Assigned".

When creating a contact and selecting any of the available test groups 

![screenshot from 2017-12-28 11-39-18](https://user-images.githubusercontent.com/34056696/34409766-d92bc84e-ebc3-11e7-8c3f-88d925e8c797.png)

They get correctly attached to the record.

![screenshot from 2017-12-28 11-40-46](https://user-images.githubusercontent.com/34056696/34409790-f8ec3eac-ebc3-11e7-9c40-c837743cf2f9.png)

**Comment by gunnicom** [comment]
@PedroErnst Thx, i will check on a fresh installation then. Maybe some custom module is interfering.

**Comment by gunnicom** [comment]
Ok, i tested it and found it to be a custom module that was disabling the liogic hook.
My fault. Sorry to take your time.

**Comment by PedroErnst** [comment]
No problem at all, glad it is solved!
