### ISSUE TITLE
403 Error Upon Survey Submission 

### ISSUE THREAD

**Issue by Glen206** [salesagility/SuiteCRM#4789]
After selecting the submit button on a test survey I was sent to the thank you page at /modules/Surveys/Entry/Thanks.php

![image](https://user-images.githubusercontent.com/2359340/34389401-648cdbc0-eb07-11e7-825d-acd52b9d96b2.png)

Double  
#### Expected Behavior
Should be shown a thank you page

#### Actual Behavior
Get a 403 Forbidden message

#### Possible Fix
Not Sure

#### Steps to Reproduce
1. Create a survey
2. Take the Survey
3. Hit The submit button

#### Your Environment
SuiteCRM  7.10.0. beta-3
Chrome (64-bit)):
MySQL, PHP 7
Centos

**Comment by Glen206** [comment]
I have the folders below set to 775 and files in them set to 755
SurveyQuestionOptions
SurveyQuestionsResponses
SurveyQuestions
SurveyResponses
Surveys

on another note but related, I do get the proper message when I close the survey and then try to take it again. I get the message telling me the survey is now closed

**Comment by pgorod** [comment]
Permissions don't mean anything by themselves. You have to check also the ownership, and match both with your web server user.

I try accessing this on my system directly and it worked fine. Can you try directly accessing the file by typing in your browser

`http://www.yourserver.com/modules/Surveys/Entry/Thanks.php`

Lastly, check if you have any .htaccess file denying access (you could have some long-forgotten rule like `entry*` that happens to block this).

**Comment by Glen206** [comment]
Thanks for the clue, it was in the .htaccess file with this line in it:

RedirectMatch 403 /+(soap|cache|xtemplate|data|examples|include|log4php|metadata|modules)/+.*\.(php|tpl)

once I removed modules, it works fine.

**Comment by pgorod** [comment]
Well, then that needs attention because that's the default rule that the SuiteCRM installer writes...

So this _is_ a bug that needs fixing.

**Comment by pgorod** [comment]
Well, then that needs attention because that's the default rule that the SuiteCRM installer writes...

https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=RedirectMatch+modules&type=

So this _is_ a bug that needs fixing.

**Comment by PedroErnst** [comment]
This should fix the issue without having to modify the htaccess file.
