### ISSUE TITLE
Survey Feedback

### ISSUE THREAD

**Issue by Glen206** [salesagility/SuiteCRM#4790]
I had an opportunity to put a survey together and use all the fields, this is some feedback after using it.

1) It's a little confusing at first as to what the "satisfied, Neither, dissatisfied" fields were for but after a created survey with every field in it, I see that they are for the matrix question.

![image](https://user-images.githubusercontent.com/2359340/34389773-a09f0f3c-eb09-11e7-9e72-4bd08a0a1c48.png)

2) It would be nice if there was a redirect field so the creator of the survey could send users to any url after the user clicks the submit button.

3) It would be nice if there was a text box that allowed you to present a message to the survey taker right under the title of the survey. The current description field is for internal use from what I can tell.

4) It would be nice if we could pick where the logo goes, left, Center, right. As it is now it is kind of left justified but depending on the screen size it dosen't line up with the left border of the survey. The top and bottom padding of the logo should be increased as well.

5) in conjunction with a redirect after a person has taken a survey. It would also be nice to be able to place a personalized URL to redirect if the the survey is closed as well.

This really is a nice clean and simple to use survey tool and looking forward to implement with Automation

**Comment by pgorod** [comment]
@Glen206 I was trying to test Surveys but I got lost. How exactly do you use this new feature?

I tried creating a Survey, what's next? Do I need a Campaign? Is there a special template to send the Survey URL or do I need to create one?

**Comment by Glen206** [comment]
@pgorod I did not set up an campaign, I just used the created link that was created after setting up the survey. 

![image](https://user-images.githubusercontent.com/2359340/34420052-5874795a-ebd5-11e7-9dd7-e21c6bf593c6.png)

**Comment by pgorod** [comment]
Oh... I don't get any URL there. It shows empty. Maybe that's another bug...

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Survey Feedback](https://trello.com/c/8AvFOERn/243-survey-feedback)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
