### ISSUE TITLE
7.10 Beta-3 - Installation failure missing required file

### ISSUE THREAD

**Issue by Mark-Keating** [salesagility/SuiteCRM#4811]
When doing a fresh install, an erroneous required file stops installation.

#### Issue

When doing a fresh install of SuiteCRM 7.10-Beta 3 installation stops with a blank screen.
the required file and directory do not exist /vendor/autoload.php'

File: incluude/entryPoint.php
Line 70: require_once $BASE_DIR.'/vendor/autoload.php';

#### Expected Behavior
Install should complete.

#### Actual Behavior
Install stops with a blank screen

#### Possible Fix
Solution is to remove the line.

#### Steps to Reproduce
on a clean machine, install, insuring that the install directory is empty

#### Context

Priority is high, as its simple and stops install
 
#### Your Environment

* SuiteCRM 7.10-Beta-3
* Browser name and version: Firefox/Chrome
* Environment name and version (e.g. MySQL, PHP 7): MYSQL PHP 7
* Operating System and version (e.g Ubuntu 16.04): Mint 18.02

**Comment by PedroErnst** [comment]
Thanks for reporting this, this same issue has come up before #4757 and is supposed to be fixed.

Have you downloaded the installer package just now?
