### ISSUE TITLE
Bug: Invoice Module: Date select field displaced by product

### ISSUE THREAD

**Issue by spongioblast** [salesagility/SuiteCRM#4817]
#### Issue
If in the invoice module, custom date select fields are created below the product / line items, the date select is precisely displaced by the amount of space needed for the products / line items. See screenshots.
It seems that the first time the date window is called, its location is saved for future calls. So if I select all the line items first, then select a date location it is perfect. If I remove some line items then, then the date pop up is below where it should be.

#### Expected Behavior
The date picker popup is always in the correct place, regardless of the amount of products above.

#### Actual Behavior
The date picker seems to have its position fixed the first time a date is selected. If then more product lines are added, the picker is displaced by the amount of displacement from the extra space needed by the new product lines.

#### Your Environment
Version 7.9.7
Sugar Version 6.5.25 (Build 344)

#### Screenshots:
[Number 1](http://www.depilrobot.com.br/temptodelete/ghi1.png)
[Number 2](http://www.depilrobot.com.br/temptodelete/ghi2.png)

**Comment by pgorod** [comment]
This is confirmed to be reproducible in the live demo.

**Comment by PedroErnst** [comment]
Thanks for reporting this. Should be fixed now!
