### ISSUE TITLE
7.10 beta 3 [suggestion] Choose signature in compose email window as in old 7.8.x version

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4818]
#### Suggestion

The only way how to change singature is that you must go to user settings and to settings of email accounts. 

#### Actual Behaviour

It is not possible to choose singature as was in old type of email system 7.8.x

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
