### ISSUE TITLE
7.10 beta 3 [Suggestion] Anonymous Usage Statistics

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4823]
#### Suggestion

It will nice if will the developmnet team + community info about versin of instacies + php version like Joomla!

https://developer.joomla.org/about/stats.html

#### Expected Behavior

More info, better decisions :)

**Comment by horus68** [comment]
Joomla does that using a plugin activated in the core.
Note that it can be disabled at any time, even before installing the system!

**Comment by Mausino** [comment]
@horus68 yes, i know, but users which want to sending us anonymous data will use it and help us to see on what the SuiteCRM mainly running + maybe in future will possible send crash or log info.... 

I know that user must agree with term and conditions of sending this data. And it good idea have this in install wizard.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [7.10 beta 3 [Suggestion] Anonymous Usage Statistics #4823](https://trello.com/c/7JSJl7Wi/245-710-beta-3-suggestion-anonymous-usage-statistics-4823)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
