### ISSUE TITLE
7.10-beta-3 - missing decorations on elements

### ISSUE THREAD

**Issue by Mark-Keating** [salesagility/SuiteCRM#4824]
Following a new installation, when popup's open an alert window the X to close is missing.
 
#### Expected Behavior
Decorations should display properly

#### Actual Behavior
Decorations are there and operate, only they are not visible

#### Steps to Reproduce

1. Open module builder.
2. create test module
3. click on view fields
4. notice missing decorations as show in screen shot below of 7.8.7(top) vs 7.10.0 Beta 3(below)

#### Your Environment

* SuiteCRM Version used: 7.10.0 Beta 3
* Browser name and version:  Firefox Quantum 57.0.3 *(64 bit)
* Environment name and version: MySQL, PHP 7):
* Operating System and version: Linux Mint 18.2

![missing widgets](https://user-images.githubusercontent.com/34941779/34495921-558c1bbe-efc5-11e7-8cc9-db948f063942.png)

**Comment by e-reeley** [comment]
Hi @Mark-Keating ,

Thank you for raising this issue, I am just working on a fix at the moment.

Thanks.

**Comment by e-reeley** [comment]
@Mark-Keating ,

I have a fix for these issues, I am just generating a PR at the moment.

Thanks again for raising the issue.
