### ISSUE TITLE
I can't drag any condition on Reports.

### ISSUE THREAD

**Issue by take4tuz** [salesagility/SuiteCRM#4825]
#### Issue

On editing a report, I can drag&drop fields.
But I can't drag any condition I dropped.
I can't drag&drop parenthesis,neither.

I upgraded & downgraded many times, and I found the related source code.

OK: SuiteCRM 7.8.8
NG SuiteCR 7.8.9

I might be a bug on ”modules/AOR_Reports/tpls/EditViewFooter.tpl”.
I roll-backed this source code from 7.8.9 to 7.8.8 , and Quick-repair.
It seems working fine!

#### Expected Behavior

I can drag&drop any condition and parenthesis.

#### Actual Behavior

I can't drag&drop any condition and parenthesis.

#### Possible Fix

related:
https://github.com/salesagility/SuiteCRM/commit/ac3f39dc7df235c22da38cf634c8b3749a9e76a2

OK: SuiteCRM 7.8.8
NG SuiteCR 7.8.9

I might be a bug on ”modules/AOR_Reports/tpls/EditViewFooter.tpl”.
I roll-backed this source code from 7.8.9 to 7.8.8 , and Quick-repair.
It seems working fine!

#### Your Environment

* SuiteCRM Version used: 7.8.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any
* Environment name and version (e.g. MySQL, PHP 7): php7.0
* Operating System and version (e.g Ubuntu 16.04): any

**Comment by PedroErnst** [comment]
Thanks for reporting this, and great job finding the actual problem!

I think this fixes the issue, I've tested on Chrome and Firefox.
