### ISSUE TITLE
7.10-beta-3 - Invalid html with compose email widgets

### ISSUE THREAD

**Issue by jneto81** [salesagility/SuiteCRM#4826]
#### Issue
in 
include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
the call of function populateComposeViewFields

```
$button = $emailUI->populateComposeViewFields() . $app_strings['LBL_COMPOSE_EMAIL_BUTTON_LABEL'];
```
generate invalid html link.
Example of the html result:

```
  <li>
<a href="javascript:void(0);"  onclick=" $(document).openComposeViewModal(this);" data-module="Accounts" data-record-id="111c0ec7-6698-db7a-06c9-5a3d7b1669c9" data-module-name="DD Furniture Inc"  data-email-address="the60@example.net">Compose Email
    </li>
 
```
the `<a> `element is not closed

Other calls of populateComposeViewFields() in other files have the same issue.

populateComposeViewFields() just returns  the a tag open.  

#### Possible Fix
after adding the missing close tag, the problem is solved.

```
$button = $emailUI->populateComposeViewFields() . $app_strings['LBL_COMPOSE_EMAIL_BUTTON_LABEL'] . "</a>" ;
```
but it requires update several files that are using the populateComposeViewFields function

#### Context
Sometimes the email compose modal open in my subpanels when clicking in other actions. Hard the reproduce. 
 
####  Environment
* SuiteCRM 7.10 beta 3

**Comment by PedroErnst** [comment]
Thanks for reporting this and also for providing a fix.

**Comment by jneto81** [comment]
Hello , just check 
#https://github.com/PedroErnst/SuiteCRM/commit/50d2f3257fead6b5181e6ac1785105f54bf68c7a

and there are other files to update/fix.
The list of files i found:

include/ListView/ListViewDisplay.php
include/generic/SugarWidgets/SugarWidgetSubPanelEmailLink.php
include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
modules/Users/User.php

**Comment by PedroErnst** [comment]
Yes thanks @jneto81 I found the same usages.

The two files that use this function and I didn't change are already adding the closing tag (User.php and SugarWidgetSubPanelEmailLink.php).
