### ISSUE TITLE
7.10-Beta-3 - List "Roles by User" closes display immediately

### ISSUE THREAD

**Issue by Mark-Keating** [salesagility/SuiteCRM#4836]
#### Issue
When in Admin and under the Roles, picking "List Roles by User" shows a pick list then selecting one displays the role but instantly reverts back to the user selection list, not allowing time to see it. 

#### Expected Behavior
Should present information and stay, not performing an instant redirect back to user list selection.

#### Actual Behavior
All works correctly, but redirects back immediately to previous screen.

#### Possible Fix
remove redirect

#### Steps to Reproduce

1. as an Admin select Admin 
2.Select Role Administration
3.Select user from list
4.watch it present then clear

#### Context

cant read it fast enough,  wanted to view the role for a user

low priority unless you rally want to know what that users role is.

#### Your Environment

* SuiteCRM Version used: 7.10-Beta 3
* Browser name and version: FireFox Quantun Version 57.0.3 (64-bit)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Linux Mint 18.3

**Comment by e-reeley** [comment]
Hi @Mark-Keating ,

Thanks for raising this issue, I  am looking into it now.

Thanks.
