### ISSUE TITLE
Reversions in the include language file?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4839]
#### Issue

There are too many differences in the /include/language/en_us.lang.php between the latest branch (develop / staging/7.10 and hotfix)
Note: those differences are not related to formatting clean up (All files compared has the formating revised) or new strings as the ones for Survey module.
This is related to strings that was removed in latest versions that are added back.

Develop and staging are closer to each other but the different strings are a reversion of previous deleted strings. I think this happen after some merge was done from a file not updated after hotfix but from an old master branch (but with code format revised), so many strings was added back.

Develop: https://github.com/salesagility/SuiteCRM/blob/develop/include/language/en_us.lang.php
Staging: https://github.com/salesagility/SuiteCRM/blob/staging/7.10/include/language/en_us.lang.php

I consider the Hotfix as the cleaner file, where some old string was removed (and its the reference for Crowdin)
Hotfix: https://github.com/salesagility/SuiteCRM/blob/hotfix/include/language/en_us.lang.php

Now the question @Dillon-Brown is the reversion on developer branch an intended reversion or just an error?

#### Possible Fix

Revise the developer branch

#### Context

Allow 7.10 translations ready to deploy

**Comment by Dillon-Brown** [comment]
@horus68 I've put up a PR that should resolve this. We'll need to thoroughly check that none of the removed strings are actually in use before it can be merged though.
