### ISSUE TITLE
7.9.8 All inbound accounts are showing in folder management of each user email settings

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4842]
#### Issue

I am not sure from which version was this problem created.. but after upgrade to 7.9.8 we see all personal and group inbound email accounts in folder management of personal email settings

![2018-01-04_1521](https://user-images.githubusercontent.com/5773777/34567773-e43454ea-f163-11e7-9e3b-47965ec79134.png)

#### Expected Behavior

User should see only own email accounts

#### Actual Behavior

User sees all inbound emails

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.8
* Browser name and version: Chrome 56.x
* Environment name and version:  MySQ 5.6, , PHP 7.2
* Operating System and version: Windows Home 10

**Comment by Mausino** [comment]
:D after upgrade on 7.9.12 issue again persisting.... for few days we will update on 7.9.13 and let you know if issue persisting in newest version

**Comment by outlawbl** [comment]
I am still having same problem on Version 7.10.7, Sugar Version 6.5.25 (Build 344). Any solutions?
