### ISSUE TITLE
No related to field in workflows

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#4843]
Issue
You cannot ad related to field to workflows

Expected Behavior
Should be able to creater workflow with related to field

Actual Behavior
Field isnt listed.

Your Environment
SuiteCRM Version used: 7.9.8
Browser name and version: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
Operating System and version (e.g Ubuntu 16.04): CentOS

**Comment by PedroErnst** [comment]
Hello @AdminPL , thanks for bringing up this issue.

In order to be able to fix this as soon as possible, please provide us a little more detail:

Which module is the workflow related to?
Which field exactly are you trying to add?
Do you want to add this field to Conditions or Actions or both?

**Comment by AdminPL** [comment]
_Which module is the workflow related to?_

Every i checked ( occasion, invoices and my custom module )

_Which field exactly are you trying to add?_

Assinged User, related to - owner

_Do you want to add this field to Conditions or Actions or both?_

Both

**Comment by PedroErnst** [comment]
@AdminPL 

I'm afraid I'm not quite understanding the issue. I don't really know what field you are trying to add.

Please provide a **detailed** step by step instructions on how to reproduce this problem. 

See here a good example of an unambiguous bug report: #4813

**Comment by AdminPL** [comment]
If you're trying to create workflow with condition like:

If owner ( assigned to ) field is user "x" you can't do it cause it's not listed. There are fields created by, modified by but no assigned, can't really say it more clear.

**Comment by PedroErnst** [comment]
You mean this?

![screenshot from 2018-01-04 15-25-27](https://user-images.githubusercontent.com/34056696/34570389-88ce6ba4-f163-11e7-9979-0896a378853f.png)

**Comment by AdminPL** [comment]
Thanks for help ! I see, it's been moved cause i used to have workflows working on 7.9.7 an in this one it's changed.

**Comment by PedroErnst** [comment]
Glad to be of assistance.

**Comment by AdminPL** [comment]
If you could help me find a logic hook with this situation in this patch i would be greatfull.

To my sales team i've made a workflow which using round robin was giving occasions create by specific user to random user in seurity group sales team. How do i achieve this on patch 7.9.8 ?

**Comment by PedroErnst** [comment]
This is something to take to the forums at https://suitecrm.com/forum/index . Thanks!

**Comment by AdminPL** [comment]
Im keeping this ticket open - chceked on folder version field should be in place anyway. Right now worfklows are basicly usless in terms of sales automatization process.

More problems connected with this 
https://suitecrm.com/forum/suitecrm-7-0-discussion/17172-creating-a-workflow-to-assign-user-from-a-role-o-group-with-random-or-round-robin-strategy

**Comment by Dillon-Brown** [comment]
Closing this in favour of #4850 just to keep things clearer. You can follow along there. Thanks.
