### ISSUE TITLE
cannot install SuiteCRM due to DB connection error

### ISSUE THREAD

**Issue by schel4ok** [salesagility/SuiteCRM#4859]
#### Issue
The provided database host, username, and/or password is invalid, and a connection to the database could not be established. Please enter a valid host, username and password.
Screenshots attached.
https://cloud.mail.ru/public/CjbH/EXdr4SR1c
https://cloud.mail.ru/public/5W9z/RMhdPMWSu

I did clone of SuiteCRM master version and followed [SuiteCRM Installation Guide](https://suitecrm.com/wiki/index.php/Installation)

Problem with DB connection exists only with SuiteCRM.
I have successfuly installed SugarCRM 6.5.
`Root `and `ipopov `users created in phpmyadmin. Passwords have been checked twice.

Simple script to check connection with DB is working well. Doing this I see name of tables from DB test.
```
$mysqli = new mysqli("localhost:3307", "ipopov", "12345", "test");
$query = "SHOW TABLES";
if ($result = $mysqli->query($query)) {
    while ($row = $result->fetch_row()) {
        printf("%s <br />\n", $
    $result->close();row[0]);
    }
}
$mysqli->close();
```

That's why I don't believe it is server related problem.

#### Steps to Reproduce
1) Copying SuiteCRM files to web server and set permissions. 
In my system there is no `ApacheUser.ApacheGroup` and instead `www-data:www-data` there is `http:http`
```
root@DSHome:/volume1/web# git clone https://github.com/salesagility/SuiteCRM.git crm                             
root@DSHome:/volume1/web# chgrp ApacheUser.ApacheGroup crm -R
chgrp: invalid group: ‘ApacheUser.ApacheGroup’
root@DSHome:/volume1/web# cd crm
root@DSHome:/volume1/web/crm# sudo chown -R http:http .
root@DSHome:/volume1/web/crm# sudo chmod -R 755 .
root@DSHome:/volume1/web/crm# sudo chmod -R 775 cache custom modules themes data upload
chmod: cannot access ‘cache’: No such file or directory
root@DSHome:/volume1/web/crm# sudo chmod -R 775  custom modules themes data upload
```
2) Create crm database in phpmyadmin.
3) Start installation http://192.168.88.90/crm/install.php
4) Then I got error on the page and I found following errors in sugarcrm.log file
```
Sun Jan  7 23:28:28 2018 [4860][-none-][FATAL] Could not connect to DB server localhost as root. port 3307: No such file or directory
Sun Jan  7 23:59:50 2018 [26270][-none-][FATAL] Could not connect to DB server localhost as root. port 3307: No such file or directory
Mon Jan  8 00:02:51 2018 [26270][-none-][FATAL] Could not connect to DB server localhost as root. port 3307: No such file or directory
Mon Jan  8 00:05:11 2018 [26270][-none-][FATAL] Could not connect to DB server localhost as root. port 3307: No such file or directory
Mon Jan  8 00:05:23 2018 [26270][-none-][FATAL] Could not connect to DB server localhost as ipopov. port 3307: No such file or directory
```
This should mean that either I use wrong password, username or DB host address, but I checked that here `$mysqli = new mysqli("localhost:3307", "ipopov", "12345", "test");`
So I am completely lost.

#### Your Environment

* SuiteCRM Version used:  7.9.8
* Browser name and version: Firefox Quantum 57.0.4 (64-бит)
* Environment name and version: PHP 7.0.24, MariaDB 10
* Operating System and version:  Linux DSHome 3.10.102 #15217 SMP Wed Dec 20 17:38:04 CST 2017 x86_64 GNU/Linux synology_bromolow_3615xs

**Comment by Dillon-Brown** [comment]
Hi @schel4ok  We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our  [Community Forum](https://suitecrm.com/forum). We will be able to help you with your specific issue there. Thanks.

**Comment by pgorod** [comment]
@schel4ok you don't need to retype all this in the forums, just link to this page and I will answer you there.
