### ISSUE TITLE
Suite 7.8.7 Marketing Email Name from and to addresses are overwritten

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#4867]
#### Issue

I want to send an email campaign with a other email address as which is defined in system.
So I created new Campaign of type Email and in "Marketing Email Name" -Settings I changed following fields: From Name, From Address , Reply To Name and REply to Address.

All of the fields are stored correctly in DB.

Then I send out the test email and the fields get changed to the values of the system Settings and mails are also sent with the data of the system settings.

This also happens when I send the email.

 
#### Expected Behavior

Mail should be send with the data I entered and schould not be reverted back.

#### Actual Behavior

fields are changed through the send process.
#### Steps to Reproduce

1.Create new Campaign and change the mentioned fields in the creation process.
2.Send test of Campaing.
3.
4.

#### Context

For my customer it is an critical bug

#### Your Environment

* SuiteCRM Version used: 7.8.7
* Environment name and version (e.g. MySQL, PHP 7): MYsql, php7.0
* Operating System and version (e.g Ubuntu 16.04): Ubunto 16.04

**Comment by pgorod** [comment]
I believe this is a duplicate (more or less) of #4479

When that fix was made by @gymad, there were extensive changes to the handling of the "from" and "name" fields.

Now the question is: exactly in which versions is that fix included? I would say probably 7.8.9... it would be nice if you guys could test it and check if everything is alright now.

**Comment by ReggaePanda** [comment]
i had this issue in version 7.8.9 and now in version 7.8.10.

<img width="776" alt="bildschirmfoto 2018-01-12 um 20 33 54" src="https://user-images.githubusercontent.com/2183135/34892026-01537ac2-f7d8-11e7-81e8-2baf3c75290c.png">

there are three errors
1. it didn't save my changes
2. name and address are reversed
3. in German language the help text overlays the input fields

<img width="783" alt="bildschirmfoto 2018-01-12 um 20 37 35" src="https://user-images.githubusercontent.com/2183135/34892161-81054f16-f7d8-11e7-8d6d-a5b69d18ab8d.png">

**Comment by ReggaePanda** [comment]
@pgorod i had this issue in version 7.8.9 and now in version 7.8.10.

<img width="776" alt="bildschirmfoto 2018-01-12 um 20 33 54" src="https://user-images.githubusercontent.com/2183135/34892026-01537ac2-f7d8-11e7-81e8-2baf3c75290c.png">

there are three errors
1. it didn't save my changes
2. name and address are reversed
3. in German language the help text overlays the input fields

<img width="783" alt="bildschirmfoto 2018-01-12 um 20 37 35" src="https://user-images.githubusercontent.com/2183135/34892161-81054f16-f7d8-11e7-8d6d-a5b69d18ab8d.png">

**Comment by pgorod** [comment]
I'd heard about that one [here](https://suitecrm.com/forum/feedback/17023-7-9-8-missing-required-field-from-email-address-in-campaign-module).

Also similar to #4883

**Comment by ReggaePanda** [comment]
@pgorod compose email works in 7.8.10. it is possible that my issue is a new one

**Comment by ReggaePanda** [comment]
thomething here looks inverted
https://github.com/salesagility/SuiteCRM/blob/a501db76b422a78db30b11a62242e83ca2dfe733/modules/OutboundEmailAccounts/OutboundEmailAccounts.php#L180-L181

**Comment by pgorod** [comment]
@ReggaePanda yep, that looks like the bug.

**Comment by ulfgebhardt** [comment]
https://github.com/salesagility/SuiteCRM/pull/4934

**Comment by ReggaePanda** [comment]
#issuecomment-357367003 #4934 should fix

I think this fix the the initial address and name are correct.
But changes are not saved

**Comment by horus68** [comment]
> name and address are reversed
see this issue: https://github.com/salesagility/SuiteCRM/issues/4942

**Comment by cwonsey** [comment]
I have this same issue, campaign emails are not allowing me to specify the From/Reply to parameters and are using my bounce-back email account for replies.  I am using version 7.9.14, so what happened to the fix?

**Comment by dursuntosun** [comment]
I have the same issue but when I go back to marketing in Campaign the fields are not saved. My version is 7.8.18 LTS. This is critical issue for my customers 🙄

**Comment by pgorod** [comment]
@Dillon-Brown this might need reopening? High priority, I would say.
