### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by apmuthu** [salesagility/SuiteCRM#488]
SuiteCRM/custom/Extension/application/Ext/Language/fr_FR.AdvancedOpenSales.php
and
 SuiteCRM/custom/Extension/application/Ext/Language/fr_fr.AdvancedOpenSales.php
are present.
Delete the former as most files are named with the language portion in lowercase.

**Comment by horus68** [comment]
related: https://github.com/salesagility/SuiteCRM/issues/460

**Comment by shogunpol** [comment]
@apmuthu , French pack is not an integrated product of SuiteCRM, it is company who do translations for SuiteCRM, with they own GitHub issues facility, you can raise issue under:
https://crowdin.com/project/suitecrmtranslations
Also person to give you best advise is @horus68 
Thanks for your contribution.

**Comment by horus68** [comment]
fr_FR are from the actual language pack
fr_fr are files released with Old SuiteCRM (not a complete language pack) and are safe to be deleted.
Uninstall french language and all will be away
Then install only the more recent pack
