### ISSUE TITLE
Detail view of no imported email is different as imported + missing time unit + atttachments

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4881]
#### Issue

If you compare the detail view of imported and no imported email that you will see that no imported are hardcoded view and this make problem mainly for attatchments.7

I see that email has in list view attachment, want look on email and know what type or name or how many are... and sometimes i want download it and look on them before import. But is not possible in this detailview.. 

You don't see info like:

* How many attachments, name or name of attachment or type
* Email was flagged or not
* Date created is without time unit.. should use instead of it the Date Sent and is on bottom of email... why ? normaly this is important information and it is in top of window

And why is there Forward button if you don't know if what attachment is there :D  ,??,

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.8
* Browser name and version: Chrome 56.x
* Environment name and version:  MySQ 5.6, , PHP 7.2
* Operating System and version: Windows Home 10

**Comment by Dillon-Brown** [comment]
@Mausino Agreed
