### ISSUE TITLE
7.9.8 Can't switch between email accounts on email list view

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4882]
#### Issue

This is weird issue.. sometimes appears and sometimes not :(

Many time happens that if you configure email accounts in user profile settings, you are not able after to switch between email accounts on list view.

We tried by folder icon or Inbox button but after when we choosed other email address... it still shows us same email address list on list view inbox.  We tried to go of email settings and we tried to change primary email address. Also doesn't help us with it

#### Possible Fix

 This is working for us:

Go to email module listview
Click on filter icon 
First click on Clear button in popup window (without it will not working)
Click on search button in pop up :) 
Now you are able via Inbox button or folder icon choose other email account

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.8
* Browser name and version: Chrome 56.x
* Environment name and version:  MySQ 5.6, , PHP 7.2
* Operating System and version: Windows Home 10

**Comment by Dillon-Brown** [comment]
This should be fixed in 7.10.1. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
