### ISSUE TITLE
7.9.8 Personal inboud email account:  Different "from" in setting as in compose email window

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4883]
#### Issue

In setting of email account is possible to set up  from which email email will send the email.. 
![2018-01-09_1248](https://user-images.githubusercontent.com/5773777/34721058-87010ef8-f541-11e7-9ff9-522374e2a90f.png)

but in compose view is showing wrong email address

![2018-01-09_1246](https://user-images.githubusercontent.com/5773777/34721077-9c0d7cc8-f541-11e7-891a-cb648a5f0eb7.png)

Compose view is customised by our company.. but issue is marked by arrows

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.8
* Browser name and version: Chrome 56.x
* Environment name and version:  MySQ 5.6, , PHP 7.2
* Operating System and version: Windows Home 10

**Comment by pgorod** [comment]
What version of SuiteCRM is this on?

**Comment by Mausino** [comment]
@pgorod sorry if forgot on this part.. i filled it now into main description
