### ISSUE TITLE
Outlook Plugin not working when LDAP Authentication enabled

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#489]
When enabling ldap authentication login for the outlook plugin does not work.
It does work for my admin account, as this account is not authed over LDAP.
All normal user accounts do not work.

**Comment by gunnicom** [comment]
Additional info:
In modules\Users\authentication\LDAPAuthenticate\LDAPAuthenticateUser.php , function authenticateUser
When i log in normal through web interface, the $password variable seems filled with the clear text password, whereas if the outlook plugin tries to login it is an md5 sum.

**Comment by willrennie** [comment]
Please post this on the Outlook Plugin GitHub issue list, so that we can fix for the next phase: https://github.com/salesagility/SuiteCRM-Outlook-Plugin
