### ISSUE TITLE
Language values used in the code should be listed or removed

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4890]
#### Issue

its stated in a comment that a language value is used in the code
`'LBL_NEWSLETTER_FORENTRY' => 'NewsLetter',`
/modules/Campaigns/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/master/modules/Campaigns/language/en_us.lang.php#L152

See: `https://github.com/salesagility/SuiteCRM/pull/4855#discussion_r160206344 `
> so it would likely cause issues removing it or even translating it. The code would need to be address not to read the value from here then it should be omitted.

#### Expected Behavior

Language values should all be just text to be translated.

#### Possible Fix

Quick fix: I need a list of strings not to be translated so they be hidden from Crowdin
Proper fix: change code and remove those strings from language files

#### Context

language values ends up being translated to many languages and alphabets.

**Comment by pgorod** [comment]
@horus68 sorry this is not related to the current topic, but just as a way to mention you

Can you please have a look at this issue in the Forums?

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27393-tax-rate-in-pdf-quotes-always-shows-0-a-bug#89294

Do you think that is coming from the language files? Or is it a bug in the way SuiteCRM handles the number formats in different languages?
