### ISSUE TITLE
Support pthreads

### ISSUE THREAD

**Issue by burton1982** [salesagility/SuiteCRM#49]
Can you make use of pthreads (PHP) in suitecrm? This would be make SuiteCRM a lot fast if you do for example a big "mass update" or running log queries.

Have a nice day!

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support pthreads](https://trello.com/c/2cN2gVti/167-support-pthreads)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
