### ISSUE TITLE
Install Error on SuiteCRM 732hotfix

### ISSUE THREAD

**Issue by apmuthu** [salesagility/SuiteCRM#490]
![suitecrm_732hotfix_install_error](https://cloud.githubusercontent.com/assets/2995044/9989037/033159ee-6073-11e5-91c7-754dbbf28556.png)
![aor_report php_lines_84_to_89](https://cloud.githubusercontent.com/assets/2995044/9989045/0dd19ff8-6073-11e5-8e56-ff26b31d28e0.png)

**Comment by horus68** [comment]
related: https://github.com/salesagility/SuiteCRM/issues/488

Note: those language files (without language packs) should simply be deleted.~
They are available when a language pack is installed
