### ISSUE TITLE
SugarFields Address language files for View.tpl

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4920]
#### Issue

2 language files has been added back today to SuiteCRM 7.8.10 and 7.9.9 in include\SugarFields\Fields\Address

I have two questions before adding them back to the Crowdin translation project:
1- Actuality its not clear for me why this are language files as there is nothing to translate
2- Also why are there some differences between the language file and the code file?

See: DetailView.tpl  / en_us.DetailView.tpl

**Note** the code file has `html_entity_decode` and the language file has  `htmlentitydecode` ignoring that it was previously been changed to `html_entity_decode` by https://github.com/salesagility/SuiteCRM/pull/1095

**and this ones**: EditView.tpl / en_us.EditView.tpl
(it has differences mainly in single/double quotes and some IF code)

**Comment by horus68** [comment]
@Dillon-Brown any direction for me to apply to Crowdin language packs?

**Comment by Dillon-Brown** [comment]
@horus68 I've fixed the code difference in #5476 but apart from that nothing else will need done translation wise. These files have nothing to translate (They are just here to fix #4868 when they got accidentally removed).

**Comment by horus68** [comment]
@Dillon-Brown for a merge?
