### ISSUE TITLE
For long usernames search box will be partly hidden by alert-nav

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#4921]
See unmerged and without explanation closed PR: https://github.com/salesagility/SuiteCRM/pull/995

**Comment by e-reeley** [comment]
I'll just take a look into this one! Do you happen to know if this is persistant with all versions at all?

Thanks.

**Comment by gunnicom** [comment]
Definitely still a problem in 7.8.9 Suite7 theme. So it should be in every version till then. 
7.9 has deprecated Suite7 so of course no problem there.

**Comment by e-reeley** [comment]
Perfect, it seems to be from 7.8.* so ill look for a fix here and should be able to carry it forward.

**Comment by gunnicom** [comment]
Typed "123456789" and as you see, the "1" is overlayed by the icon.
![grafik](https://user-images.githubusercontent.com/550251/34878434-7568e8f8-f7aa-11e7-8d37-644456782c13.png)

**Comment by e-reeley** [comment]
Hi @gunnicom 

Sorry for the dely, I have a fix.

Just making the PR now.

Thanks again for reporting this bug!
