### ISSUE TITLE
7-10 Beta-2 Tasks are not showing the "Related To" on all records since upgrade 

### ISSUE THREAD

**Issue by liquidocelot** [salesagility/SuiteCRM#4933]
While testing beta-2 I found a bug where the Tasks in list view and in the dashboard only show the first records "Related to" clickable link and the rest are blank. On each page the first record is intact but the others are missing the link to the account

#### Issue
The Tasks module is not showing the "Related to" account name on the records below the first.

#### Expected Behavior
Before the update the list of Tasks showed the account link on each record fine.

#### Actual Behavior
When you view the list of tasks there is no way to quickly view the name of the account.

![image](https://user-images.githubusercontent.com/3066743/34892170-e2421100-f79d-11e7-8545-37458f3a78fd.png)

When I scan the error log I see this.

![image](https://user-images.githubusercontent.com/3066743/34892211-057de36a-f79e-11e7-8204-9967cccd2351.png)

#### Possible Fix
Not sure

#### Steps to Reproduce
1. Just go to Tasks list view

#### Context
This is a real pain to workflow because it slows things down.

#### Your Environment

* SuiteCRM Version used: 7.10 Beta 2
* Browser name and version: Chrome Version 63.0.3239.132 (64-bit)
* Environment name and version: MySQL, PHP 7.2
* Operating System and version: CentOS release 6.9 (Final)

**Comment by PedroErnst** [comment]
Hello @liquidocelot , thanks for bringing this up.

This problem has been solved in more recent 7.10 beta releases, in #4681 to be precise.

In the current beta 4 it looks like this.

![screenshot from 2018-01-15 16-37-15](https://user-images.githubusercontent.com/34056696/34952857-02958988-fa13-11e7-9add-7ab83c12e245.png)

**Comment by liquidocelot** [comment]
I don't see how to fix it , sorry.
