### ISSUE TITLE
Name and address fields labels switched?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#4942]
#### Issue

The key and value do not match
in /modules/OutboundEmailAccounts/language/en_us.lang.php
```
    'LBL_SMTP_FROM_NAME' => '"From" address',
    'LBL_SMTP_FROM_ADDR' => '"From" name',
```
https://github.com/salesagility/SuiteCRM/blob/master/modules/OutboundEmailAccounts/language/en_us.lang.php#L103

Note: Maybe related to a fix https://github.com/salesagility/SuiteCRM/pull/4934/files

#### Possible Fix

```
    'LBL_SMTP_FROM_NAME' => '"From" name',
    'LBL_SMTP_FROM_ADDR' => '"From" address',
```

#### Your Environment

* SuiteCRM Version used: Master or Develop branch in github

**Comment by pabaillon** [comment]
With this fix i have "Error:Invalid address: (punyEncode) " when i test the email adress.

**Comment by gruentee** [comment]
I can confirm the error @pabaillon mentioned.

**Comment by horus68** [comment]
@gruentee The fix only changed the language value label, not even the key. No code changed.
So you need to open a new issue for your problem.
(I think there as been a change on PR related with the emails fields)
