### ISSUE TITLE
getFileName function in AbstractMetaDataImplementation in 7.9.9

### ISSUE THREAD

**Issue by gray1st** [salesagility/SuiteCRM#4962]
The above function tries to pull back $this->_packageName however this isn't referenced anywhere else in the script.

This seems to cause an error in the ModuleBuilder

Fatal error: Uncaught Error:Cannot access private property UndeployedMetaDataImplementation::$_packageName

Referenced Lin 432

**Comment by PedroErnst** [comment]
Thanks @gray1st for reporting this.

Please describe the precise steps you took to reach that error, that should help us fix it swiftly.

Thanks!

**Comment by gray1st** [comment]
From within ModuleBuilder I'm trying to edit a relationships

Admin
Module Builder
Select Custom Module
Relationships
Change 'Type'
Press 'Save'
**ERROR**

:)

**Comment by PedroErnst** [comment]
Which version of SuiteCRM are you using?

**Comment by gray1st** [comment]
7.9.9

**Comment by PedroErnst** [comment]
Thanks, that should be fixed now!

**Comment by gray1st** [comment]
Where can I download the fix from? Is there a Pull Request?

**Comment by PedroErnst** [comment]
Now there is :)

**Comment by pgorod** [comment]
There's a very similar (but not quite the same) case here:

https://suitecrm.com/suitecrm/forum/suitecrm-beta/17411-change-dashlet-error
