### ISSUE TITLE
Suggestion - AOR missing summary line

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#4963]
While using AOR there is no way to see sum of all records while having more than 1 page of data unless you export it to pdf or email.

#### Expected Behavior
It would be nice if in AOR there was additional line showing sum from all pages, example when i select sum of amount in raport of open occasion connected to specifi user i would like to see in 1st page total from all pages.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - AOR missing summary line](https://trello.com/c/zYt0lGTR/258-suggestion-aor-missing-summary-line)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
