### ISSUE TITLE
[suggestion] Grouping Project Tasks

### ISSUE THREAD

**Issue by gboban** [salesagility/SuiteCRM#4966]
Adding groups for Project Tasks, so project tasks can be grouped and sorted by those groups.

For example, when having larger number of tasks inside project, it would be beneficiary to be able to group tasks according to corresponding project phases - initiation, planning etc. Or use some other grouping.

Currently, Project Tasks can not be grouped/nested, nor Project Tasks containing other tasks can be created.

* SuiteCRM Version used: 7.8.5

**Comment by Mausino** [comment]
@gboban great idea :) every advance project task programs have this function 👍 and if @salesagility do this improvment... it moves project management in SuiteCRM on new level

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[suggestion] Grouping Project Tasks](https://trello.com/c/VQ37mCxO/254-suggestion-grouping-project-tasks)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
