### ISSUE TITLE
Inline editing issue after case update

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#497]
Hi,
I you update case and you want update some row in detailview of case, it is not working,
But if you refresh page and you will try again, it is working fine.

Miky

**Comment by samus-aran** [comment]
@Mausino Do you mean when you update the case's log via the DetailView, you are then unable to inline edit other fields?

**Comment by Mausino** [comment]
After update on 7.5.2 the issue was fixed :) thanks
