### ISSUE TITLE
History module - delete emails

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#498]
Hi, 

if i try delete email from history module which i replied, i got this error 

http://screencast.com/t/KkxG7C6m7f

With "Sent" emails from crm are any problem to delete them in module history, but if i reply to email, and this email i want delete from this module, i got this issue.

I hope, that i explained in normal way :)

Miky

**Comment by shogunpol** [comment]
@Mausino , the issue has been tested on recent version of SuiteCRM(7.7.4), and not appear.
Can you replicate this issue in recent version of SuiteCRM?
Thanks for your contribution.

**Comment by Mausino** [comment]
Hi, i can confirm that issue was resolved :)
