### ISSUE TITLE
Missing link to import campaigns

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#4981]
#### Issue
There should be a link to "Import Campaigns" on the sidebar (and on the action menu on top), when inside the Campaigns module.

#### Actual Behavior
No link available: the only way to be able to Import a Campaign is when the list view is empty (no Campaigns created yet), through the message `You currently have no records saved. CREATE or Import one now.`

If I click on that Import link I am taken to the Campaign import screen. However after creating the first Campaign that message goes away and there's no way left to Import.

#### Possible Fix
This is just speculation, but I wonder if this could be related to the number of items on the sidebar? There are many items there, for the Campaigns module... maybe it simply runs out of space and hits some limit.

#### Steps to Reproduce
1. On a system with at least one Campaign created,
2. Go to the Campaigns module
3. Try to find a way to import campaigns, there is none

#### Context
User complaint in [forums](https://suitecrm.com/forum/suitecrm-7-0-discussion/17368-no-import-campaign-link-after-create-one).

#### Your Environment
* SuiteCRM Version used: live demo, 7.9.9
It would be interesting to check also 7.8.x

**Comment by PedroErnst** [comment]
Added!
