### ISSUE TITLE
7.9.9 Studio / issue after save function / screen is overlay by shadow layer

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4983]
#### Issue

After upgrade on 7.9.9 we are getting issue in studio.

Any action which we done is overlayed and it is not possible to click on x which is on popup message window.

You must refresh page if you want continue... and this is problem mainly for listview if you're changing the% of fields... becase after you lost you value for  % field in listview

![2018-01-18_1631](https://user-images.githubusercontent.com/5773777/35106175-d4d53266-fc6d-11e7-9456-97419966de2f.png)

#### Steps to Reproduce

1. Go to studio
2. Layers
3. List view / detailview / or etc.
4. Push any  save button

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.9
* Browser name and version : Chrome 54.x
* Environment name and version: MySQL 5.6, PHP 7.2
* Operating System and version: Win 10 Pro

**Comment by e-reeley** [comment]
Hi, 

Thank you for raising this issue! 

I think I have previously mad a PR that should solve this issue, I could link it here if that helps?

Thanks again.

**Comment by Mausino** [comment]
@e-reeley it will nice if you put it here

**Comment by e-reeley** [comment]
@Mausino 

Sorry for the delay, I believe this should help out with your issue:
https://github.com/salesagility/SuiteCRM/pull/4965

Thanks.
