### ISSUE TITLE
Unable to display relationships in Studio

### ISSUE THREAD

**Issue by muesliflyer** [salesagility/SuiteCRM#4985]
When I click at Studio -> Modules -> [any module] -> relationships, this Notice pops up many times:
___ **Notice: Undefined index: LBL_NO_SUBJECT in <path to>\modules\Emails\email.php on line 3085**

#### Issue
This happens probably because the set of relationships is empty.
It seems to be a bug as the code on line 3085 references an array index that isn't there.

#### Expected Behavior
The browser should show an empty list of relationships as well as buttons to create relationships.
I am surprised that the Email module is being used when displaying relationships in a module

#### Actual Behavior
A box pops up that shows the Notice many times over.

#### Steps to Reproduce

1. Invoke Admin -> Studio -> Modules
2. Open a module in the treeview in the sidebar
3. Click at relationships
![lbl_no_subject](https://user-images.githubusercontent.com/8150112/35110283-b26be14c-fc78-11e7-9b47-93672265d520.png)

#### Context
* The bug seems to make it impossible to define relationships in Studio.
* Medium priority
* A possibly related issue is: https://suitecrm.com/forum/feedback/17135-lbl-no-subject-in-email-php#57494

#### Your Environment
* SuiteCRM Version used: 7.9.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.4 64bit
* Environment name and version (e.g. MySQL, PHP 7): 
** Xampp 7.1.1
** PHP 7.1.1
** MySQLi Server Info: 5.5.5-10.1.21-MariaDB
** Apache 2.4.25

* Operating System and version (e.g Ubuntu 16.04): Windows 10 Version 1709

**Comment by PedroErnst** [comment]
Thanks for reporting this @muesliflyer 

This fix should resolve the issue.

In the meantime, if you want to avoid seeing all these PHP Notices, you might want to consider turning PHP error reporting off in your XAMPP installation.

**Comment by muesliflyer** [comment]
Thanks PedroErnst for the quick turnaround! Will the fix be included in the next release after 7.9.9?

I don't like suppressing the Notices because they tend to point to bugs or things that are not thought out clearly. No out-of-sight out-of-mind :)

I am a newbie and am trying to find out if suiteCRM is ready for operational use by our marketing person. She is using an older version of SugarCRM but is not too happy about it (slowness).

**Comment by PedroErnst** [comment]
@muesliflyer Yes, it will normally be present in all future releases. That includes the 7.8 long term support and 7.9.x as well as the upcoming 7.10 versions.
