### ISSUE TITLE
Importing Many-to-Many relationship

### ISSUE THREAD

**Issue by mustafa-taheri** [salesagility/SuiteCRM#4988]
#### Issue
 I have created two custom modules and set many-to-many relationship between them.

#### Expected Behavior

I have downloaded the import template and try to upload the records but unable to find field name to relate/map the record with second custom module

#### Context
Please also suggest any alternative or whether this is possible in other CRM version or not. Will need this on PRIORITY

#### Your Environment

* SuiteCRM Version used: Version 7.6.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 63.0.3239.132 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Dillon-Brown** [comment]
Hi @mustafa-taheri  If you still need help with this issue then I would suggest going to the [Community Forum](https://suitecrm.com/forum). We will be able to help you with your specific issue there. Thanks.
