### ISSUE TITLE
inline editing - clicking on multiple items and not filling anything in

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#499]
a good example would be if you went to an account detail view->more information. And then if you just start double clicking everything, the fields values will swap over and change when they are not supposed to. I also do not get any warning messages that my changes are being saved or not saved.

**Comment by willrennie** [comment]
This has been fixed as far as I'm aware as you get a popup if you try to navigate away from a field without saving inline editing changes. Can you confirm?
