### ISSUE TITLE
email sending issue after upgrade 7.9.9

### ISSUE THREAD

**Issue by dipenpatel235** [salesagility/SuiteCRM#4995]
![capture](https://user-images.githubusercontent.com/8135097/35207048-c08a8a1c-ff66-11e7-84be-c8e9542965d9.PNG)
#### Issue

email sending issue after upgrade 7.9.9
#### Expected Behavior

Email sending failed getting php mailer related error
#### Actual Behavior

must me email send successfully 

[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP Stack trace:, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   1. {main}() /var/www/html/sc/index.php:0, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   2. SugarApplication->execute() /var/www/html/sc/index.php:52, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   3. SugarApplication->loadUser() /var/www/html/sc/include/MVC/SugarApplication.php:93, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   4. AuthenticationController->__construct() /var/www/html/sc/include/MVC/SugarApplication.php:119, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   5. AuthenticationController->getAuthController() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:64, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP Warning:  Declaration of LDAPAuthenticateUser::loadUserOnLogin($name, $password) should be compatible with SugarAuthenticateUser::loadUserOnLogin($name, $password, $fallback = false, $PARAMS = Array) in /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 52, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP Stack trace:, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   1. {main}() /var/www/html/sc/index.php:0, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   2. SugarApplication->execute() /var/www/html/sc/index.php:52, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   3. SugarApplication->loadUser() /var/www/html/sc/include/MVC/SugarApplication.php:93, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   4. AuthenticationController->__construct() /var/www/html/sc/include/MVC/SugarApplication.php:119, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   5. AuthenticationController->getAuthController() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:64, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config
[Mon Jan 22 13:28:07 2018] [error] [client 123.201.177.59] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67, referer: https://my.local.host/sc/index.php?module=EmailMan&action=config

#### Possible Fix

something phpmailer related code
#### Steps to Reproduce

1. admin
2. email setting
3. fill settings and save it
5. send test mail custom email server with tls
6. get phpmailer related error when click on send
7. change password  and send test mail - it will work
8. but we will again send test mail without change password so it is getting fail.

below is screenshot
 

#### Context

Yes not able to reach to client

High
#### Your Environment

Version 7.9.9
Sugar Version 6.5.25 (Build 344)
PHP 7
centos 7 64 bit
apache2

**Comment by pgorod** [comment]
@dipenpatel235 have you created a thread with this in the forums? That is the correct place to troubleshoot specific cases with specific installations. 

You should only open an Issue here after you've gone through some basic troubleshooting and concluded you have found a bug to report to developers.

Please close this issue and open a thread there, I'll help you out in the forums.

**Comment by dipenpatel235** [comment]
ok
thanks
