### ISSUE TITLE
please log ip adress

### ISSUE THREAD

**Issue by burton1982** [salesagility/SuiteCRM#50]
Hello!

Please support to log the IP Adress in the logfile. We can use this for fail2ban.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [please log ip adress](https://trello.com/c/Kitczaee/166-please-log-ip-adress)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
