### ISSUE TITLE
[language] Hard coded messages in SugarAuthenticate (ver. 7.10RC)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5003]
self::addFactorMessage('Two Factor Authentication failed');
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php#L287

self::addFactorMessage('Two factor authentication code sent.');
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php#L301

self::addFactorMessage('Two factor authentication code sending error.');
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php#L309

die("Your session was terminated due to a significant change in your IP address.  <a href=\"{$sugar_config['site_url']}\">Return to Home</a>");
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php#L405

Email Code: <input type="text" name="factor_token"> <input type="submit" value="Send">
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Users/authentication/SugarAuthenticate/FactorAuthEmailCode.tpl#L46
Use 'FactorAuthEmailCode' label instead.

**Comment by horus68** [comment]
@gymad

**Comment by Dillon-Brown** [comment]
Most of these should already be resolved but I've put up a PR that should get the rest. Thanks.
