### ISSUE TITLE
Suggestion - Increase input maxlength during setup

### ISSUE THREAD

**Issue by J4C0814N** [salesagility/SuiteCRM#5012]
#### Issue
When setting up an instance as an Azure App Service with hosted MySQL database the requirements for the connection by MS are longer than the allowed characters of the input fields on the configuration page of the setup wizard.
Microsoft requires the username to match the pattern `[username]@[dbname]-mysqldbserver`
Without adding a username or database name the character length is already at 15.

#### Expected Behavior
No (or more reasonable) character length restriction on input fields

#### Actual Behavior
DB Username field is limited to 16 characters

#### Possible Fix
Increase the fields `maxlength` attribute to a higher value (32/64/100) or remove the restriction entirely. 

#### Steps to Reproduce
1. Perform a clean install
2. At the configuration step select "Provide existing user" from the drop down
3. Attempt to put in more that 16 characters into input fields

#### Context
It was simple to get around using the browser developer tools, but would be nice to not have to.
This is probably a low priority issue.

#### Your Environment
* SuiteCRM Version used: 7.9.9
* Environment name and version (e.g. MySQL, PHP 7): 
Azure App Service (Windows Server 2016, MySQL 5.7.21, PHP 7.0)

**Comment by PedroErnst** [comment]
Thanks @J4C0814N for reporting this.

I think the best idea is no limit, since it is impossible for us to know what the exact limitation of the DB will be considering that different engines have different limitations.
