### ISSUE TITLE
Operation dialog background covers window (z-index issue)

### ISSUE THREAD

**Issue by nsrosenqvist** [salesagility/SuiteCRM#5013]
#### Issue
When you use one of the editors for more advanced system configuration then the operation dialog ends up hidden behind the background shadow container. I'm not able to continue without either deleting the html node from the inspector or reloading the page.

![screenshot-2018-1-25 suitecrm](https://user-images.githubusercontent.com/1303475/35371225-ad02fd60-01f7-11e8-9001-b8817647a9a1.png)

#### Expected Behavior
The background shadow should be behind the window.

#### Actual Behavior
It's in front of the window.

#### Possible Fix
Correct the z-index.

#### Steps to Reproduce
1. Go to Administration > Module Builder
2. Perform an operation and the dialog shows up

#### Context
I'm unable to configure the CRM for our organization.

#### Your Environment
* SuiteCRM Version used: Version 7.9.9 - Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.4 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 x64

**Comment by Dillon-Brown** [comment]
Duplicate #4983
