### ISSUE TITLE
[language] Hard coded messages in opt in (ver. 7.10RC)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5016]
You have confirmed that your email address "{$FOCUS->email_address}" has been opted in
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/include/EntryPointConfirmOptIn.tpl#L3

 Unable to confirm email address
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/include/EntryPointConfirmOptIn.tpl#L7

echo 'Success';
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Campaigns/WebToPersonCapture.php#L298

echo("Success");
https://github.com/salesagility/SuiteCRM/blob/v7.10-RC/modules/Campaigns/CaptchaValidate.php#L66

**Comment by horus68** [comment]
@daniel-samson can you take a look into this?

**Comment by horus68** [comment]
@daniel-samson Hard coded messages should be marked as BUG low level as it breaks translation functionality!

**Comment by horus68** [comment]
@Dillon-Brown also a go for a merge?
