### ISSUE TITLE
Saving Photo on Employees Module

### ISSUE THREAD

**Issue by ijdavie** [salesagility/SuiteCRM#5017]
#### Issue

Most of the issues appear to have been resolved from #582, however if you add the image (photo) field to the employees edit and detail view you will find that you can view it fine however it appears that the editview whe saved will not save the image uploaded. 

#### Expected Behavior

Expected to save image from both employee and user record.  
#### Actual Behavior

currently only works from users record.

#### Steps to Reproduce

1. add photo field to edit and detail view. 
2. save photo via employees record 
3.
4.

#### Your Environment

* SuiteCRM Version used: hotfix-7.8.x branch
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome
* Environment name and version (e.g. MySQL, PHP 7): php71, mariadb 
* Operating System and version (e.g Ubuntu 16.04): ubuntu

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
