### ISSUE TITLE
Quick Create button don't respect renamed modules settings

### ISSUE THREAD

**Issue by nsrosenqvist** [salesagility/SuiteCRM#5019]
#### Issue
The labels for the items in the Quick Create menu don't respect the configuration made in the renamed modules settings. I renamed "Leads" to "Applications" and it's displayed properly in the navigation but not in the Quick Create dropdown.

![screenshot-2018-1-25 applications suitecrm](https://user-images.githubusercontent.com/1303475/35385014-edcd8ee4-022b-11e8-82d1-61ba80cb49f3.png)

#### Expected Behavior
Every instance of the module name should be renamed.

#### Actual Behavior
Not all instances are renamed (hard coded?)

#### Possible Fix
...

#### Steps to Reproduce
1. Rename a module that has an action listed in the Quick Create button
2. Compare navigation labels with Quick Create dropdown labels

#### Context
It's inconsistent and having two separate terminologies is confusing for the users of the system.

#### Your Environment
* SuiteCRM Version used: Version 7.9.9 - Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.4 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 x64

**Comment by kdjmonaghan** [comment]
Hello,

Yes, you're correct here - renaming modules does not reflect on the Quick Create bar as it doesn't follow the naming of the modules according to the language file.

The quick create file actually follows a different subset of language strings that aren't edited by Module Rename (his is an oversight, and can be easily, manually, edited until a real fix is put in place).

Unfortunately at the moment there's no automated way to update the listings to be whatever you need them to be, though, you can copy the following variables:

```
$app_strings['LBL_QUICK_ACCOUNT'] = 'Create Account';
$app_strings['LBL_QUICK_CONTACT'] = 'Create Contact';
$app_strings['LBL_QUICK_OPPORTUNITY'] = 'Create Opportunity';
$app_strings['LBL_QUICK_LEAD'] = 'Create Lead';
$app_strings['LBL_QUICK_DOCUMENT'] = 'Create Document';
$app_strings['LBL_QUICK_CALL'] = 'Log Call';
$app_strings['LBL_QUICK_TASK'] = 'Create Task';
```

And place them anywhere into the following file from the root of your SuiteCRM installation (if you're using a different language from en_us, please add it in that appropriate language in the same structure as the file below):

```
/custom/include/language/en_us.lang.php
```

Renaming the values of the variables will then reflect your quick create menu, for example, in your query you raised you changed leads. Adding this line to the en_us.lang.php file will update the quick create list for creating a lead to "Create Application":

```
$app_strings['LBL_QUICK_LEAD'] = 'Create Application';
```

I'll look into adding to the ```RenameModules.php``` class to handle the quick create menu  when I find some time - as I agree, it is an oversight these are also not changed, especially when the referenced strings only have one occurrence of use (the header).

**Comment by Dillon-Brown** [comment]
Duplicate #716
