### ISSUE TITLE
7.9.9 - Undefined when importing contacts

### ISSUE THREAD

**Issue by mat8iou** [salesagility/SuiteCRM#5025]
#### Issue
Pop up that just says "Undefined" with a Cancel and OK button appears when importing contacts with the option to  "Create new records and update existing records" checked.

The message comes up the moment the Next button is presssed

The problem occurs in an identical way on the official demo site.

#### Expected Behavior
Dialogue should indicate what the issue is that you are to respond to, rather than saying Undefined.

#### Actual Behavior
Text on the pop up says "Undefined"

#### Steps to Reproduce
1. Go to Contacts
2. Choose Import
3. Select a CSV file
4. Check "Create new records and update existing records"
5. Click the Next button

#### Context
Imports are not refreshing the existing contacts, but instead creating new ones - It is unclear if this is related to the message / warning being given in this popup.

#### Your Environment

* SuiteCRM Version used: 7.9.9
* Browser name and version: Chrome 63.0.3239.132 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Centos
![screen shot 2018-01-25 at 14 52 46](https://user-images.githubusercontent.com/35808167/35399075-5a2f62d8-01eb-11e8-9284-0e57501b7bec.png)

**Comment by salesagility-davidthomson** [comment]
This appears to be due to the language 
cache/modules/Import/language/en_us.lang.php
not being loaded into js namespace
SUGAR.language.languages
Undefined appears lots of times when the button text is updated using ajax as this needs the SUGAR.Lanugage functions.
I have seen it on publish / un publish as well as other places. I don't think that 
https://github.com/salesagility/SuiteCRM/pull/4317
will fix all the issues.

**Comment by salesagility-davidthomson** [comment]
@Dillon-Brown I've created a pull request https://github.com/salesagility/SuiteCRM/pull/5141 for hotfix-7.8.x branch. This fixes this issue as well as a lot of other ones regarding undefined labels in the import module and others. It should also sort the issue that you fixed.

**Comment by mrbarletta** [comment]
@salesagility-davidthomson  - question, why did you change the
` $_REQUEST['module'] ` to ` $_REQUEST['modulename']` ??

That broke the existings .htaccess rules. :(

**Comment by salesagility-davidthomson** [comment]
@mrbarletta the reason is in the description for the pull request https://github.com/salesagility/SuiteCRM/pull/5141
To sumarise is the htaccess rule was trying to load a module instead of the intended accesspoint. 
Can you submit a new issue if this has broken the application?

**Comment by mrbarletta** [comment]
Thanks @salesagility-davidthomson  - 

The existent .htaccess didn't got updated using the upgrade installer to reflect this change.

Is this an issue with your change that should have included the .htaccess upgrade or something from my end?
