### ISSUE TITLE
suitecrm7.9 contact  not added after upgrade 7.9 using rest api Oauth key

### ISSUE THREAD

**Issue by dipenpatel235** [salesagility/SuiteCRM#5033]
hello...
upto 7.6 veersion from mine plugin to using Oauth key contact was auto added.
But after upgrade 7.9 not able to seen thoes added contact in suitcrm contact list.
i can also seen getting EntryPoint request receive in crm server but not seen that contact. 

#### Expected Behavior
Must be seen added contact in contact list

#### Actual Behavior
ationController.php:64, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&action=DetailView&record=f24bfcc7-948c-6871-09dd-53afba9f31fd
[Thu Jan 25 14:41:45 2018] [error] [client 203.88.150.42] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&action=DetailView&record=f24bfcc7-948c-6871-09dd-53afba9f31fd
[Thu Jan 25 14:41:45 2018] [error] [client 203.88.150.42] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&action=DetailView&record=f24bfcc7-948c-6871-09dd-53afba9f31fd
[Thu Jan 25 14:41:45 2018] [error] [client 203.88.150.42] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&action=DetailView&record=f24bfcc7-948c-6871-09dd-53afba9f31fd
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP Stack trace:, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   1. {main}() /var/www/html/sc/index.php:0, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   2. SugarApplication->execute() /var/www/html/sc/index.php:52, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   3. SugarApplication->loadUser() /var/www/html/sc/include/MVC/SugarApplication.php:93, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   4. AuthenticationController->__construct() /var/www/html/sc/include/MVC/SugarApplication.php:119, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   5. AuthenticationController->getAuthController() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:64, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73
[Thu Jan 25 14:43:05 2018] [error] [client 203.88.150.42] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67, referer: https://my.suitecrm.host/sc/index.php?module=OAuthKeys&offset=1&stamp=1516859696007483100&return_module=OAuthKeys&action=EditView&record=4e6c0624-211f-6a44-7213-53afbad46c73

#### Possible Fix

if rest api content changed.

#### Context

mine live site contact not added in crm 

High
#### Your Environment

PHP 7
suitecrm Version 7.9.9
Sugar Version 6.5.25 (Build 344)

**Comment by dipenpatel235** [comment]
input: 
<?php
$crm_url = "https://my.suitecrm.host/sc/index.php?entryPoint=API";
$post = "FirstName=Demo&LastName=Sem&Email=demo9@construct.my.id&OperationSubType=NEW&SegmentType=Segment1&OperationType=CONTACT&ConsumerKeyName=ContactSegment1&ConsumerKey=xxxxhj-xx3kj-ddfr34-xxexwf&ConsumerSecret=XXXXXXXXXXXXXXXXXXXXXXXXXXX";

 $curl = curl_init();
 curl_setopt($curl, CURLOPT_URL, $crm_url);
 curl_setopt ($curl, CURLOPT_POST, TRUE);
 curl_setopt ($curl, CURLOPT_POSTFIELDS, $post);
 curl_setopt($curl, CURLOPT_TIMEOUT, 1);
 curl_setopt($curl, CURLOPT_HEADER, 0);
 curl_setopt($curl, CURLOPT_RETURNTRANSFER, false);
 curl_setopt($curl, CURLOPT_FORBID_REUSE, true);
 curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 1);
 curl_setopt($curl, CURLOPT_DNS_CACHE_TIMEOUT, 10);
 curl_setopt($curl, CURLOPT_FRESH_CONNECT, true);
 $data = curl_exec($curl);
 curl_close($curl);
echo $data;
?>


output :
1

error in log:

[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP Warning:  Declaration of LDAPAuthenticateUser::authenticateUser($name, $password) should be compatible with SugarAuthenticateUser::authenticateUser($name, $password, $fallback = false) in /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 52
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP Stack trace:
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   1. {main}() /var/www/html/sc/index.php:0
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   2. SugarApplication->execute() /var/www/html/sc/index.php:52
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   3. SugarApplication->loadUser() /var/www/html/sc/include/MVC/SugarApplication.php:93
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   4. AuthenticationController->__construct() /var/www/html/sc/include/MVC/SugarApplication.php:119
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   5. AuthenticationController->getAuthController() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:64
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP Warning:  Declaration of LDAPAuthenticateUser::loadUserOnLogin($name, $password) should be compatible with SugarAuthenticateUser::loadUserOnLogin($name, $password, $fallback = false, $PARAMS = Array) in /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 52
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP Stack trace:
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   1. {main}() /var/www/html/sc/index.php:0
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   2. SugarApplication->execute() /var/www/html/sc/index.php:52
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   3. SugarApplication->loadUser() /var/www/html/sc/include/MVC/SugarApplication.php:93
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   4. AuthenticationController->__construct() /var/www/html/sc/include/MVC/SugarApplication.php:119
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   5. AuthenticationController->getAuthController() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:64
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   6. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/AuthenticationController.php:101
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   7. LDAPAuthenticate->__construct() /var/www/html/sc/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticate.php:61
[Sat Jan 27 14:51:34 2018] [error] [client 198.245.60.150] PHP   8. require_once() /var/www/html/sc/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php:67

**Comment by Dillon-Brown** [comment]
This should be fixed in 7.10.1. Please re-open if this is still an issue you can replicate and we can investigate further. Thanks.
