### ISSUE TITLE
Spots Module: 'Save' not working in SuiteCRM 7.8.10, Suite 7 theme. 

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#5043]
#### Issue
When editing a spots report, 'Save' and 'Save and Continue' buttons are not working in SuiteCRM 7.8.10, Suite 7 theme. Even clicking in the name of the report and then hitting enter on the keyboard does not save the report. 

Playing with the report, pivotong data, and the reports filters works fine. It is just it can not be saved. 

#### Expected Behavior
Spots Reports can be saved using 'Save' and 'Save and Continue' buttons . 

#### Actual Behavior
Spots Reports can NOT be saved using 'Save' and 'Save and Continue' buttons . 

#### Steps to Reproduce
1. Go to a spot report.
2. Make changes to the report
3. Try to save using 'Save' and 'Save and Continue' buttons . 

#### Context
This impacts us as we can not update Spots reports. We have also tried 'Quick Repair and Rebuild'

#### Your Environment
* SuiteCRM Version 7.8.10
* Theme: Suite 7. 
* Browser: Tested in both Safari 11.0.2 and Chrome 63.0.3239. 
* MySQL 5.6.39, PHP PHP 7.0.25
* OS CentOS Linux 7.4

**Comment by adminibt** [comment]
Similar problem here: SuiteCRM 7.8.10, Suite P
Firefix 58: "Save" does nothing
IE 11: "Save" works
