### ISSUE TITLE
AOS_products returns all records in globla search

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#5046]
#### Issue

Added Products module  to globlal search
AOS_products reporting all records in globla search "use basic search"

#### Expected Behavior

must report only the search

#### Actual Behavior

reports all records

#### Possible Fix

adding unified_search= true to var def ? 
 https://developer.sugarcrm.com/2010/09/23/adding-custom-modules-to-global-search/
#### Steps to Reproduce

1.add products to global search
2.do a global search
3.click on "use basic search"
4.go down to products sections

#### Context

priority= medium

#### Your Environment

* SuiteCRM Version used: 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP7
* Operating System and version (e.g Ubuntu 16.04):16.04

**Comment by PedroErnst** [comment]
Hello @boombata 

I'm unable to reproduce this on version 7.8.12

I have multiple products

![screenshot from 2018-02-06 11-55-12](https://user-images.githubusercontent.com/34056696/35858518-a4f93760-0b34-11e8-8e1f-f1cd76690299.png)

I added Products to global search

![screenshot from 2018-02-06 11-55-02](https://user-images.githubusercontent.com/34056696/35858528-a92aeb8a-0b34-11e8-8fa0-2835c10834ab.png)

I search, and only the matching results show

![screenshot from 2018-02-06 11-54-51](https://user-images.githubusercontent.com/34056696/35858531-ac598000-0b34-11e8-8979-574be7a1e9ec.png)

Am I missing something?

**Comment by boombata** [comment]
Thank you for testing , that is exacly what i'm doing. I then must go to the logs and will revert to you as soon as possible.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
