### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by robov** [salesagility/SuiteCRM#5050]
During installing 7.9.10 I get on the process of installing demo data
Warning: Base directory /var/www/html/include/HTMLPurifier/standalone/HTMLPurifier/DefinitionCache/Serializer does not exist, please create or change using %Cache.SerializerPath in /var/www/html/include/HTMLPurifier/HTMLPurifier.standalone.php on line 15279

After that when I go to login I get:

Fatal error: Uncaught Exception: Could not connect to the database. Please refer to suitecrm.log for details. in /var/www/html/include/utils.php:1762 Stack trace: #0 /var/www/html/include/database/MysqliManager.php(290): sugar_die('Could not conne...') #1 /var/www/html/include/database/DBManagerFactory.php(147): MysqliManager->connect(Array, true) #2 /var/www/html/include/entryPoint.php(179): DBManagerFactory::getInstance() #3 /var/www/html/index.php(47): require_once('/var/www/html/i...') #4 {main} thrown in /var/www/html/include/utils.php on line 1762

**Comment by robov** [comment]
even without demo data...
I still get
Fatal error: Uncaught Exception: Could not connect to the database. Please refer to suitecrm.log for details. in /var/www/html/include/utils.php:1762 Stack trace: #0 /var/www/html/include/database/MysqliManager.php(290): sugar_die('Could not conne...') #1 /var/www/html/include/database/DBManagerFactory.php(147): MysqliManager->connect(Array, true) #2 /var/www/html/include/entryPoint.php(179): DBManagerFactory::getInstance() #3 /var/www/html/index.php(47): require_once('/var/www/html/i...') #4 {main} thrown in /var/www/html/include/utils.php on line 1762


When at the same time the actual database is filled

**Comment by pgorod** [comment]
Hi. This is better suited to [the Forums](https://suitecrm.com/suitecrm/forum), not here on Github. Please close this, and open a thread there and I will be glad to help you. Include more information about your set up, please (PHP version, OS, database, ...)

Also please check the contents of `install.log` and make sure you set permissions correctly before beginning.

**Comment by robov** [comment]
SOURCE OF PROBLEM:
Apparently the database credentials were not written to config_override during the install
