### ISSUE TITLE
SuiteCRM 7.10-RC - History Sub-panel is empty in Opportunities and Cases

### ISSUE THREAD

**Issue by ProactiveCareSoultions** [salesagility/SuiteCRM#5053]
#### Issue
The Sub-panel is empty

#### Expected Behavior
There should bbe notes

#### Actual Behavior
Empty Nothing showing up

#### Steps to Reproduce
Click a Opportunity or a Case
Click History in the sub-panel

#### Context
Need to see the content
High

#### Your Environment

* SuiteCRM Version used: 7.10RC
* Chrome Version 63.0.3239.140 (Official Build) (64-bit)
* MySQL, PHP 7
* Chrome OS Version 63.0.3239.140 (Official Build) (64-bit)

**Comment by pgorod** [comment]
I can confirm this in my 7.10RC installation.
