### ISSUE TITLE
Broken HTML in new module dialog in module builder

### ISSUE THREAD

**Issue by michalhudecek** [salesagility/SuiteCRM#5054]
Clicking on New module in Module Builder shows a broken dialog with an error and broken HTML . No way to continue.

The gray overlay is probably caused by https://github.com/salesagility/SuiteCRM/issues/4983. 
The error shown is probably related to https://github.com/salesagility/SuiteCRM/issues/4139

**The broken HTML is however a separate bug.**

![image](https://user-images.githubusercontent.com/1215304/35480114-ff9a0cdc-0407-11e8-9928-438c3fa2b0c8.png)

**Comment by pgorod** [comment]
@michalhudecek thanks for the bug report, but please do fill in the entire issue template. How can we even begin to take a look at this without having any idea what your version of SuiteCRM is? Or your PHP, etc.?

**Comment by michalhudecek** [comment]
**SuiteCRM**
Version 7.9.10
Sugar Version 6.5.25 (Build 344)

**PHP 7.1.13** 

Windows 10, Google Chrome 63

I would test the issue in your online demo but I don't see admin options there.

**Comment by pgorod** [comment]
There is a live demo with admin access here:

https://www.softaculous.com/demos/SuiteCRM

But it is still on 7.9.9 and this bug doesn't show there.

I have a 7.9.10 (PHP 7.0) and I get the grey overlay bug, but not the broken HTML. Can you try a few Repairs from Admin / Repair? Javascript stuff, etc.

**Comment by michalhudecek** [comment]
I tried all the possible repairs and it is still happening. I have Czech language enabled if it is relevant.

![image](https://user-images.githubusercontent.com/1215304/35484084-042d71d8-044b-11e8-9b4f-85e77a24539f.png)

**Comment by michalhudecek** [comment]
This was a clean installation, I haven't done anything besides hiding some modules in **Display Modules and **Subpanels** , editing items in **Dropdown Editor** and adding new fields in **Studio** for Clients and Contacts modules. Apart from that I recently upgraded to 7.9.10. I have never tried Module Builder before though so I do not know if it was working before the upgrade or not.

**Comment by michalhudecek** [comment]
I tried a **clean installation of LTS version - SuiteCRM 7.8.12 LTS and I have the same issue right at the start** without changing anything. 

It's the same server with PHP 7.1.13. Can someone test it with this particular version?

![image](https://user-images.githubusercontent.com/1215304/35688261-136cb48c-0771-11e8-91d8-baa9035aaf00.png)

**Comment by Dillon-Brown** [comment]
@michalhudecek Have you tried the proposed fix here? #5056

**Comment by michalhudecek** [comment]
@Dillon-Brown Yes, that helps. Is the fix coming to LTS version as well? 7.9.X versions seem to be very buggy.

**Comment by Dillon-Brown** [comment]
@michalhudecek Yes, this issue will be fixed in both 7.9.x and 7.8.x LTS.
