### ISSUE TITLE
7.10RC - Cases Threads Not Updating Again

### ISSUE THREAD

**Issue by Glen206** [salesagility/SuiteCRM#5062]
When I updated a case thread, the updated note was not added to the thread, even though a "processing" dialogue box appeared then went away.

I had this issue in a prior release 7.9.8 before and this symptom was resolved be deleting the cases folder content in custom/modules/cases/metadata.

I tried this method again but to no avail.

Can someone else verify if this happening in their 7.10RC version. 

This was working in 7.1.0 Beta1 for me.

#### Expected Behavior
updated note should appear in the case thread.

#### Steps to Reproduce
1. Create a case
2. type in a note into the case thread
3. click save

**Comment by edmondklai** [comment]
I am using 7.10RC, I cannot seem to produce the same result.  When I type text in "Update Text", Save.  Case notes are updated to Case Updates Thread.

**Comment by pgorod** [comment]
Same here as @edmondklai, it works well.

**Comment by Dillon-Brown** [comment]
Unable to replicate on 7.10-RC. Please reopen if you learn more information that could help us to replicate. Thanks.
