### ISSUE TITLE
[suggestion] currency symbol behind the amount

### ISSUE THREAD

**Issue by gboban** [salesagility/SuiteCRM#5063]
Lots of the currency symbols should be behind the amount.

It would be great if currency symbol placement could be changed on the per currency basis and then properly handled by format_place_symbol function in modules/Currencies/Currency.php

Example:
Amount in US dollars should be displayed as $100 but for Danish or Norwegian krone or Croatian kuna amount should be displayed as 100 Kr or 100 Kn (with a space after amount and before currency symbol.

* SuiteCRM Version used: 7.8.7

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[suggestion] currency symbol behind the amount](https://trello.com/c/REznkSEO/255-suggestion-currency-symbol-behind-the-amount)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
