### ISSUE TITLE
[Suggestion] Collapsed active/with records subpanels - other color of header text or background

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5064]
#4706

When some collapsed subpanels have records.. will nice if will the color of header or background other as grey... user will know that there are records...  it helps to faster orientations if some user using only collapsed subpanels which are not grouped by menu (also will great for user which have grouped subpanels)

For activity subpanel i am suggesting other color like green.. because you will on first look know that there are active tasks/calls/meetings

![2018-01-30_1145](https://user-images.githubusercontent.com/5773777/35562254-196c8c3c-05b3-11e8-860e-72d9b60e7639.png)

**Comment by PedroErnst** [comment]
Yes, absolutely agree.

I would go another step and actually display the number of records after the name.

ACTIVITIES (0)
ACTIVITIES (5)
ACTIVITIES (25)
ACTIVITIES (100+)

The required COUNT query is not that expensive that it would be noticeable in the load times, and it would save quite a bit of time for the users.

**Comment by Mausino** [comment]
@PedroErnst should you add the link on your pull request for COUNT query ?

**Comment by PedroErnst** [comment]
@Mausino I have a PR for this? I don't think so...

**Comment by Mausino** [comment]
@PedroErnst sorry... i thinked that you created some function abou you wrote 

"The required COUNT query is not that expensive that it would be noticeable in the load times, and it would save quite a bit of time for the users."  

and i can't found it... but i know that is not created yet :)

**Comment by Mausino** [comment]
The main point was fixed in #5577 

Thanks to @PedroErnst
