### ISSUE TITLE
Can't login on SuiteCRM and access demo on revamped official site

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5075]
#### Issue

I can login to official forum on www.suitecrm.com but cant login to demo... there is only register form and any login or sign page. 

#### Expected Behavior

Can access demo page and log in to demo of SuiteCRM

![2018-02-01_1641](https://user-images.githubusercontent.com/5773777/35687400-e6da912a-076e-11e8-9e91-d0f3997c2334.png)

**Comment by Dillon-Brown** [comment]
Hi @Mausino, I'll look into this, in the meantime you can use a direct link to the demo as a workaround: https://demo.suiteondemand.com

Thanks!

**Comment by horus68** [comment]
Also this one (including administration area access): 
https://www.softaculous.com/demos/SuiteCRM

**Comment by Mausino** [comment]
@Dillon-Brown @PedroErnst  thank you that you fixed custom demo pop up window on official site
