### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by digitalplayer-steemit** [salesagility/SuiteCRM#5082]
Hello

My name is Michael Asumcinei and I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by horus68** [comment]
Translations are already done using Crowdin Platform here:
https://crowdin.com/project/suitecrmtranslations

Utopian.io users are also using Crowdin for translations. See: https://steemit.com/crowdin/@horus68/utopian-io-translations-using-crowdin

**Comment by samus-aran** [comment]
Thanks @horus68 for that! 👍
