### ISSUE TITLE
AOR - assigned user as main group problem and ID instead of name

### ISSUE THREAD

**Issue by ghost** [salesagility/SuiteCRM#5091]
Issue

When you create report and set Main group to "assigned user" group is shown in report's as many times as number of record included in group, for example if group of invoices realted to certain user has 3 invoices group will be shown 3 times.

Another problem group name is user ID instead name

![bez tytulu](https://user-images.githubusercontent.com/30261902/35825470-38681dc4-0ab6-11e8-92d2-f8dedc1808fd.png)

Your Environment
SuiteCRM Version used: 7.9.11
Browser name and version Chrome Version 51.0.2704.63 (64-bit))
Environment name and version MySQL, PHP 7.1
Operating System and version Ubuntu

**Comment by AdminPL** [comment]
Anyone ?

**Comment by AdminPL** [comment]
Problem still existis on 7.9.13

**Comment by AdminPL** [comment]
7.10.1 problem still exists, problem makes reports with Man Group practicly usless

**Comment by serhiisamko091184** [comment]
No longer an issue in the latest version (7.14.3). 

Thanks!

Regards,
Serhii
