### ISSUE TITLE
AOR - missing between date parameter 

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#5092]
Not sure if it's bug so I'm adding as a suggestion.

While trying to set specific date range in report , example account edited between 01/02/2018 and 05/02/2018 you have to add 2 parameters and set one as greater or equal to 01/02/2018 and second one as less or equal to 05/02/2018. 

In searching engine you can pick option between which makes it easier and gives more possibilites.
![image](https://user-images.githubusercontent.com/30261902/35826044-df1dc672-0ab7-11e8-9dcc-f92b38f3c8e8.png)

Right now if you wanna change report to show for example this week you have to delete one of paramters or set both to equal to this week.

**Comment by jannepesonen** [comment]
Reports conditions date fields you can choose Period type and there is a few set of periods.
There you can select e.g. this week.

But I think there is a bug,
https://github.com/salesagility/SuiteCRM/issues/5129

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AOR - missing between date parameter](https://trello.com/c/66XkWihe/256-aor-missing-between-date-parameter)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
