### ISSUE TITLE
Case module layouts inconsistent

### ISSUE THREAD

**Issue by Mark-Keating** [salesagility/SuiteCRM#5094]
Summary:
The defaults for the Case's module have be amiss for a long time, ver 7.8 and up, where the programmed additions and variations on the cases have resulted in various different presentations.
These can not be fixed in studio, and as a default is not very good.
 
Not Seen:  not seen in current list

Security Risk: No
#### Issue

The programmed additions into the cases is different between create/edit/display and quickcreate where fields most notably "description" is not usable in the create, cannot display as full width in  display and in edit mode both description and resolution are switched to HTML fields, with the data still just a text area.

Trying to adjust in studio presents some odd results , and is not fixable without going in and hacking code. 

#### Expected Behavior
The default as shipped should be a consistent working clean presentation.

#### Actual Behavior
Different behavior between functions

#### Steps to Reproduce
1. Install new version
2.create case (notice that description is unavailable)
3.display case (notice that fields are half width - description/resolution) 
4.edit case      ( notice that description/resolution are presented as html fields (in db is html)

#### Context

use the cases "as is" for cases, but it is not very presentable.

#### Your Environment

* SuiteCRM Version used: 7.10 RC - Feb 5th 2018
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FireFox 64 bit 
* Environment name and version (e.g. MySQL, PHP 7): mysql php7
* Operating System and version (e.g Ubuntu 16.04): Linux Mint

Shot of Create:
![screenshot from 2018-02-05 15-21-28](https://user-images.githubusercontent.com/34941779/35827882-a0292ee2-0a8b-11e8-81eb-e0446d96030d.png)

Shot of Display
![screenshot from 2018-02-05 15-23-13](https://user-images.githubusercontent.com/34941779/35827696-01cad1ce-0a8b-11e8-94fb-1cc61fe05f98.png)

Shot of Quick create
![screenshot from 2018-02-05 15-22-13](https://user-images.githubusercontent.com/34941779/35827743-2d9ea1ae-0a8b-11e8-9e73-4edd53d11c48.png)

Shot of Edit
![screenshot from 2018-02-05 15-23-57](https://user-images.githubusercontent.com/34941779/35827660-e654c6c0-0a8a-11e8-8245-e15329ef4b49.png)

**Comment by PedroErnst** [comment]
Thanks @Mark-Keating for bringing this up.

I went with the logic that if the field type is text, than it should behave as such and removed the html editor altogether.

**Comment by aarondglover** [comment]
The proposed Fix https://github.com/salesagility/SuiteCRM/pull/5100

Does make the description field appear again, however the TinyMCE HTML/Rich Editor is no longer on this field.

Many cases are automatically generated from HTML Emails and now those render as <p> and other HTML tags. It would be good if the TinyMCE Editor would work rather than just making it a plain text field

**Comment by PedroErnst** [comment]
#5100 is closed.

The fix that was merged for this issue is #5672

**Comment by aarondglover** [comment]
Hi @PedroErnst 
I am a little confused which case I should be commenting on.

Fix https://github.com/salesagility/SuiteCRM/pull/5672 seems to work perfectly for creating a new case. 

When creating a new case the wysiwyg editor appears.
The wysiwyg editor also appears when editing a case.

The wysiwyg editor DOES NOT appear if you use the "Save and Continue" or Navigate Next/Previous Buttons.

Should a new bug be created or does it belong here?

**Comment by PedroErnst** [comment]
Hello,

I'm not too sure myself, but possibly since this one is closed it would be better to open a new issue, as this one might get buried.
