### ISSUE TITLE
Multiple Relationships from one module to another

### ISSUE THREAD

**Issue by ijdavie** [salesagility/SuiteCRM#51]
Say you have relationships between Opportunities to Users but have 7 -8 relationships (1 user - Many Opportunities all the same)

when the second relationship is created the label from the first is recreated into the second language file, When the third relationship is created then the first and second label is recreated into the third language file and so on. 

when the label is recreated it defaults back to the original value (In this case its "User"). This stops the labels from being updated in studio and resets all the labels to the end user.

**Comment by willrennie** [comment]
Fix is now in master.
