### ISSUE TITLE
Export cvs / Download PDF in Reports

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#510]
Hi,

If i update via PARAMETERS (via update button) my report record in Report module, it shows filtered report (the list of results), but if i want download it in pdf or export in cvs this filtered result, it download/export it in default configuration as was the report configured in edit view. Only one possibility how download/export the filtered report is edit report in edit view and i must save it and after i can export it (that in export/donwload pdf i will have filtered results), and again need to go to edit view, change value in parameters and again i muss save it and after i have changed results for export/download it.

Miky

**Comment by ecovantage** [comment]
Is this the same as Issue 201 ? 
https://github.com/salesagility/SuiteCRM/issues/201

**Comment by Mausino** [comment]
Thanks @ecovantage & @mattlorimer
