### ISSUE TITLE
Duplication of AOR reports removes fields and conditions from parent record

### ISSUE THREAD

**Issue by mugge6** [salesagility/SuiteCRM#5109]
#### Issue
Duplication of an existing AOR report removes all fields and conditions from parent record.

#### Expected Behavior
Duplication of an existing AOR report shouldn't affect parent record, from which the duplicate will be created.

#### Actual Behavior
New Report is working fine, but initial report lost all fields and conditions.

#### Possible Fix
Didn't investigate into this issue.

#### Steps to Reproduce
1. Create a new AOR report (cases)
2. Add some fields
3. Add some conditions
4. Save newly created report
5. Duplicate this report from detail view
6. Save duplicated report with new name
7. Check fields and conditions from initial report. They are gone.

#### Context
Workaround is not duplicating reports. Instead create always a new one.

#### Your Environment
* SuiteCRM Version used: 7.9.11
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1

**Comment by PedroErnst** [comment]
Thanks @mugge6 

Unfortunately I'm not able to reproduce this at all.

Duplicating a report A duplicates all conditions and fields on report B, leaving A as before.

Editing any of the fields/conditions on report B does not affect A at all.

SuiteCRM version 7.9.11

![screenshot from 2018-02-06 13-18-02](https://user-images.githubusercontent.com/34056696/35861641-8b3a96f0-0b40-11e8-85c5-be4d8156ce32.png)

![screenshot from 2018-02-06 13-18-27](https://user-images.githubusercontent.com/34056696/35861643-8edc92a4-0b40-11e8-828b-a5ff694baac7.png)

**Comment by mugge6** [comment]
After drill down this issue, it seems to working on a fresh installation from SuiteCRM 7.9.11.

After installing latest version SecuritySuite (SuiteCRM_7.9.11_SecuritySuite_v3.1.5.zip) my described issue above is reproducible.

I will create an issue on the SugarOutfitters page.

I'll closed this issue.

**Comment by gunnicom** [comment]
I remember there was a similar issue some time ago. I do not remember when, and if it only affected the charts of a report. I will update if i find something.

**Comment by gunnicom** [comment]
Found it: https://github.com/salesagility/SuiteCRM/issues/1489

**Comment by mugge6** [comment]
Found the problem based on the hint to #1489 - thanks to @gunnicom 

The reason why this problem only occurs together with SecuritySuite is, that the pre_save function from SugarController calls the save method from the SecuritySuite class SugarFieldAdditionalusers. This call creates a new GUID if there is no bean id set. Later in the save method from the AOR_Report class on line 111 there is a check if there is already an GUID set or not. Only if there is no GUID set, the post request IDs from condition and field will be unset.

As far as I can see the fix will work with a simple check on the POST vars if it's a duplicate save or not.

File: modules/AOR_Reports/AOR_Report.php
Line: 111

Existing code:
`if (empty($this->id)) {`

Proposed solution:
`if (empty($this->id) || (isset($_POST['duplicateSave']) && $_POST['duplicateSave'] == 'true')) {`

With this fix, the charts will work as well without the change from #1489.

**Comment by sanchezfauste** [comment]
I confirm that with the plugin SecuritySuites installed this error occurs when duplicating Contracts, Invoices and Quotes.

**Comment by sanchezfauste** [comment]
Adapting the fix proposed by @mugge6 for the AOS_Contracts module, works correctly.

I think that this fix would have to be adapted at least in the following modules: AOS_Contracts, AOS_Invoices, AOS_Quotes, AOR_Reports, AOW_Workflow.
