### ISSUE TITLE
URL Field - Default URL not being used to populate field

### ISSUE THREAD

**Issue by mjrcrm** [salesagility/SuiteCRM#5110]
#### Issue
In Studio
- create an URL field
- populate the Default URL with an URL
- Save field and add it to an Edit and Detail View
- Call up an appropriate CRM record. The URL field will be blank and will only contain an URL once a user has entered a new URL.

#### Expected Behavior
- The Default URL should be displayed. The user should be able to edit it or insert a different URL, but the field should not be empty.

#### Environment
- Tested in multiple versions of Suite. Behavior confirmed again in 7.9.10.

**Comment by e-reeley** [comment]
Hi @mjrcrm 

Just as I had a version of 7.9.11 open I thought that I would test this issue in that instance.

It seems to populate the default URL as expected in this version, so if it is an issue previous then a fix must have been added in in the most recent update.

Ill double check with a previous version and report back.

Thanks for raising the issue.

**Comment by PedroErnst** [comment]
@mjrcrm Are you talking about newly created records or about existing records?

Default values will only be applied to newly created records. I've just tried this with an URL field and it works fine.

If when you say 'Call up an appropriate CRM record' you mean an existing record that was created before the default value was defined, of course it won't have the URL. That's not how default values work, and it would be outright dangerous to have them work this way (think the amount of data you could inadvertently overwrite).

What you want to do in this case is most likely run a Mass Update.

**Comment by mjrcrm** [comment]
You are correct and I apologize for my error. When I do create a new record the default value is displayed.

I had wrongly assumed that since this was a new field that the default value would show for existing records as well.

Please therefore close this case.
