### ISSUE TITLE
Create new calendar entrie doesn't works

### ISSUE THREAD

**Issue by supercrypt** [salesagility/SuiteCRM#5125]
#### Issue

When creating entries in our calendar it seems doesn't show up in the view.

#### Expected Behavior
An new entrie should be visible in the calendar.

#### Actual Behavior

At the moment an calendar entrie doesn't show up in the list. The php.log and suitecrm.log not showing anything so far.
![calendarbug1](https://user-images.githubusercontent.com/36037249/35924454-6d101428-0c23-11e8-8324-5804723763d9.png)
![calendarbug2](https://user-images.githubusercontent.com/36037249/35924465-70c3c6be-0c23-11e8-82fa-215528b1a37f.png)

#### Steps to Reproduce
1. Go to SuiteCRM -> All -> Calendar
2. Create new a Activity at any day and hour
3. Fill in something as Subject
4. Save

#### Your Environment

* SuiteCRM Version used:  7.8.11 (LTS)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 59 beta
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Debian 8.10

**Comment by Dillon-Brown** [comment]
Hi @supercrypt, this is fixed in v7.8.12 (LTS) and v7.9.11. Thanks.
