### ISSUE TITLE
Importing a contact throws NOTICE and interrupts importing

### ISSUE THREAD

**Issue by labcerouno** [salesagility/SuiteCRM#5130]
Hi devs! I ran into this issue and posted in the forums.  Community leader Pedro Rodrigues instructed me to get to the right contact which threw this notice and then post here. 

#### Issue
Importing a certain contact throws a notice an interrupts importing, even if notices are disabled in php.ini.

> NOTICE: [8] Trying to get property of non-object on line 428 in file /var/www/html/suitecrmgcoop/modules/Contacts/Contact.php

The CSV with the contact was exported from SuiteCRM v. 7.6.3

#### Expected Behavior
Import successfully or show the field with error.

#### Actual Behavior
The contact is imported correctly, but at the end of the importing process or (if the number of contacts is greater than 100) at the end of a block, the notice above appears, interrupting the import process.

#### Possible Fix
Actually, a workaround: Do not map campaign_id when importing.

#### Steps to Reproduce
1. Go to contacts
2. Go to Import Contacts
3. Select this CSV: [contacts_test.zip](https://github.com/salesagility/SuiteCRM/files/1704652/contacts_test.zip)
4. Do not map lead_source and birthdate fields (as this line doesn't have it)
5. Import 

#### Context
It interrupts an importing process without showing where is the problem. Normally, lines with problems show error messages with the specific field in trouble and the list of unimported registers. This should be high priority as it breaks importing functionality. 

#### Your Environment
* SuiteCRM Version used: 7.9.11. Tested local and on demo.suiteondemand.com
* Chrome Version 63.0.3239.132 64 bits
* Environment name and version: Percona Server 5.7.19-17 (MySQL) , PHP 7.0.22
* Operating System and version: Ubuntu 17.04

**Comment by PedroErnst** [comment]
@labcerouno Thanks for reporting this.

Funnily enough I can't reproduce this on my environment, but I can see it on suiteondemand happening exactly as you describe.

I'm not entirely sure that the Notice is what is actually interrupting the import process, but if it is the fix I just pushed should solve it.

Can you maybe test it and let me know if it works?

**Comment by pgorod** [comment]
@PedroErnst while you're looking at Import code you might want to check out this Issue #1976, it came up in the forums again this week. Thanks!
