### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Petrouchka** [salesagility/SuiteCRM#5148]
Link is broken in about page 'see screenshot). The text is OK but the link is broken (https://suitecrm.com/community/partners).

SuiteCRM version 7.9.11.
![capture du 2018-02-08 18-39-30](https://user-images.githubusercontent.com/3955499/35988818-d2d8b7a6-0cff-11e8-8a2a-54d91382afec.png)

**Comment by horus68** [comment]
This is due the new site redesign. It should be solved in 2 ways:
- fix the file
/modules/Home/About.php
https://github.com/salesagility/SuiteCRM/blob/2e1122effe9684c524dcc9e21b77d1eba45b4787/modules/Home/About.php#L119

- in the actual site: implement a redirect for this link (to keep the link working on old SuiteCRM instances)

@Dillon-Brown  In the language files there is also a broken (it goes to the front page not to the forum):
http://suitecrm.com/index.php/forum/index
See Language files: install and Upgrade
So make this also a redirect in the actual site.

**Comment by Dillon-Brown** [comment]
I've fixed the link to the forums in #5153. Will take a look at the "https://suitecrm.com/community/partners" link.

**Comment by horus68** [comment]
@Dillon-Brown great! 
Dont forget the upgrade script language file (not available in a git repository)
