### ISSUE TITLE
Detail View Created Date same in all records

### ISSUE THREAD

**Issue by aureh12** [salesagility/SuiteCRM#5149]
#### Issue

Modify detailviewdefs.php for any module and to have simple entries like this:

`
0 => 'date_entered',
1 => 'date_modified',
`

#### Expected Behavior

It should display the record date_entered and date_modified from the database.

#### Actual Behavior

All records display the same date.
It looks like a date is cached once somewhere and displayed on all records.

It was discussed there:
https://community.sugarcrm.com/thread/18788#comment-76366
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/5675-custom-module-date-entered-bad-format

#### Possible Fix

No idea.

#### Steps to Reproduce

1. Modify detailviewdefs.php of any module
2. Make sure the entry is in its most simple way: 0 => 'date_entered',
3. Comment any CustomCode like  'customCode' => '{$fields.date_entered.value}',
4. Repair and rebuild

#### Context

Custom modules built with Module Builder for instance will display wrong dates.
It can be solved by changing the view definition like this:
`          0 =>
                 array (
                        'name' => 'date_entered',
                        'label' => 'LBL_DATE_ENTERED',
                        'customCode' => '{$fields.date_entered.value}',
                ),
          1 =>
                 array (<br>
                        'name' => 'date_modified',
                        'label' => 'LBL_DATE_MODIFIED',
                        'customCode' => '{$fields.date_modified.value}',
                ),`

#### Your Environment

* SuiteCRM Version used: 7.9.11

**Comment by PedroErnst** [comment]
Thanks for reporting this @aureh12 

My question: Why would you want to do this?

According to the official [SuiteCRM developer documentation](https://suitecrm.com/wiki/index.php/Developer_Guide#detailviewsdefs.php) the correct way to do it is like

```
    array (
              'name' => 'date_entered',
              'customCode' => '{$fields.date_entered.value} {$APP.LBL_BY} {$fields.created_by_name.value}',
          ),
```

**Comment by aureh12** [comment]
Hello.




It's not that I want to do it, but:




1/ every module created in builder and deployed will have a view definition without custom code by default




2/ a custom code should be only used when you want to customize, it should not be the default




What do you think?




Aurélien







From: PedroErnst


Sent: Friday, February 9, 17:54


Subject: Re: [salesagility/SuiteCRM] Detail View Created Date same in all records (#5149)


To: salesagility/SuiteCRM


Cc: aureh12, Mention






Thanks for reporting this @aureh12


My question: Why would you want to do this?


According to the official SuiteCRM developer documentation the correct way to do it is like


array ( 'name' => 'date_entered', 'customCode' => '{$fields.date_entered.value} {$APP.LBL_BY} {$fields.created_by_name.value}', ),

**Comment by PedroErnst** [comment]
@aureh12 

1. Maybe I am missing something... I create a module in builder and deploy it. This is the result:

![screenshot from 2018-02-09 10-25-14](https://user-images.githubusercontent.com/34056696/36023206-93d6ce1a-0d83-11e8-8bcc-9f42dbca6ce7.png)

![screenshot from 2018-02-09 10-25-26](https://user-images.githubusercontent.com/34056696/36023208-9651a3cc-0d83-11e8-85fb-6931e374f71c.png)

It looks fine to me?
If you are getting a different outcome please let me know the exact steps so I can try to reproduce it.

2. You have a point, but again, refer to the documentation. If the documentation says to do it a certain way, and it works that way, then I still think it's working as intended.

**Comment by aureh12** [comment]
You are right. I wa maybe too fast.
Module Builder create the view definition in the proper way.
