### ISSUE TITLE
Cut down on sugar in your diet

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5160]
#### Issue

Example:
SuiteCRM/modules/Help/index.php
`<strong>Stay tuned </strong>for an upcoming release of <A href="http://www.sugarcrm.com">SugarCRM</A>!`
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Help/index.php#L51

#### Expected Behavior

Sugar references should be reduced to the copyright only

#### Context

Related to some URL fixed in #5153:
Maybe some wide clean up on Sugar leftovers should also be... Suite!

**Comment by horus68** [comment]
Some more to the list:
include/export_utils.php
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/include/export_utils.php#L770

/modules/UpgradeWizard/uw_utils.php
https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/modules/UpgradeWizard/uw_utils.php#L3804


include/ListView/ListViewSubPanel.php
https://github.com/salesagility/SuiteCRM/blob/5b3eeb843089279bcb4abea37f3361ec123be4b0/include/ListView/ListViewSubPanel.php#L163

include/ListView/ListView.php
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/include/ListView/ListView.php#L225


include/MySugar/retrieve_dash_page.php
https://github.com/salesagility/SuiteCRM/blob/cdabd015b3728ec8a7a5483f6294b9de9d7a769d/include/MySugar/retrieve_dash_page.php#L105
and 
https://github.com/salesagility/SuiteCRM/blob/cdabd015b3728ec8a7a5483f6294b9de9d7a769d/include/MySugar/retrieve_dash_page.php#L120

modules/UpgradeWizard/uw_utils.php
https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/modules/UpgradeWizard/uw_utils.php#L3804


install/install_utils.php
https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/install/install_utils.php#L2051


install/register.php
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/install/register.php#L67

and
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/install/register.php#L72


ModuleInstall/PackageManager/PackageManagerDisplay.php
https://github.com/salesagility/SuiteCRM/blob/2e1122effe9684c524dcc9e21b77d1eba45b4787/ModuleInstall/PackageManager/PackageManagerDisplay.php#L241-L243

modules/Home/TrainingPortal.php
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/modules/Home/TrainingPortal.php#L63

modules/Administration/SupportPortal.php
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/modules/Administration/SupportPortal.php#L59

modules/Home/Dashlets/RSSDashlet/RSSDashlet.php
https://github.com/salesagility/SuiteCRM/blob/9dec1a80e84424fdfbc5e742474b79507a7d1bf3/modules/Home/Dashlets/RSSDashlet/RSSDashlet.php#L51

modules/UpgradeWizard/SILENTUPGRADE.txt
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/modules/UpgradeWizard/SILENTUPGRADE.txt#L93

soap.php
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/soap.php#L62

service/core/SugarSoapService.php
https://github.com/salesagility/SuiteCRM/blob/932b87108edc154dd3c9c86b57ceaa24acd40835/service/core/SugarSoapService.php#L51

**Comment by pgorod** [comment]
Remember there's more outdated SugarCRM stuff here: #3855
