### ISSUE TITLE
Send notification from assigning user [text improvements required]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5163]
#### Issue

Requesting a better wording to this string:
LBL_NOTIFY_SEND_FROM_ASSIGNING_USER
modules/EmailMan/language/en_us.lang.php
    'LBL_NOTIFY_SEND_FROM_ASSIGNING_USER' => 'Send notification from assigning user\'s e-mail address',

https://github.com/salesagility/SuiteCRM/blob/5b3eeb843089279bcb4abea37f3361ec123be4b0/modules/EmailMan/language/en_us.lang.php#L108

#### Possible Fix

I'm not an english speaker but mybe adding a THE as in `from THE assigning ` ?!

#### Context

Found some contradictory translations!

**Comment by pgorod** [comment]
I suggest simply

"Send notification from the email address of the assigning user"
