### ISSUE TITLE
Scheduler Job dropdown menu missing labels

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5165]
#### Issue

Scheduler Job dropdown menu missing labels
![2018-02-09 20_35_21-suitecrm](https://user-images.githubusercontent.com/3055443/36052402-7bef07ec-0de5-11e8-8ab3-c103ccc4b3ce.png)

#### Expected Behavior

Pending menu needs to have labels for the options
(all options are from default schedulers)

#### Actual Behavior

Label for URL item is visible. All the other options are there but blank.

#### Steps to Reproduce

1. Admin / Schedule
2. Open Schedule / Edit
3. See Job pending menu: only URL is visible

#### Context

I need to know the options to choose!

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.11 and SuiteCRM 7.10.RC2 -
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Windows 10 32bit - Chrome / Firefox
* Environment name and version (e.g. MySQL, PHP 7):  apache 2.4.18 / PHP Version 7.0.11 / mysql 5.7.17
Also tested in softaculus demo (7-9-11)

**Comment by horus68** [comment]
This is fixed in the language files (I need to find the exact fix in some issue posted here) but it was just missing labels that I implemented it some time ago.
Note that the menu can overlap the field at the right.
So to avoid this this filed should be the single field in this line
![2018-02-09 22_47_53-suitecrm php7](https://user-images.githubusercontent.com/3055443/36053939-bd7df0c8-0deb-11e8-840e-7803aef0b115.png)

**Comment by horus68** [comment]
This is the issue where the fix was discussed https://github.com/salesagility/SuiteCRM/issues/4291#issuecomment-349289904

I will create a PR for this

**Comment by KaKite** [comment]
Hey, I'm having the same problem except my Job dropdown lists **ONLY** URL and a single blank entry beneath it. I have updated my /modules/Schedulers/language/en_us.lang.php file using #5171 and it has all the required entries, Admin -> Repair -> QRR and no changes. 

I have also tested the loading of the language file by deleting all the OOTB entries (out of the box labels) and running an Admin -> Repair -> QRR. All the job labels in the Schedulers list view disappeared as expected. When I put the OOTB entries back and ran the QRR they reappeared BUT none of these actions filled the entries in the Job drop down box

The job labels I have in the language file are as follows:
//jobstrings
    'LBL_REFRESHJOBS' => 'Refresh Jobs',
    'LBL_POLLMONITOREDINBOXES' => 'Check Inbound Mail Accounts',
    'LBL_PERFORMFULLFTSINDEX' => 'Full-text Search Index System',
    'LBL_RUNMASSEMAILCAMPAIGN' => 'Run Nightly Mass Email Campaigns',
    'LBL_POLLMONITOREDINBOXESFORBOUNCEDCAMPAIGNEMAILS' => 'Run Nightly Process Bounced Campaign Emails',
    'LBL_PRUNEDATABASE' => 'Prune Database on 1st of Month',
    'LBL_TRIMTRACKER' => 'Prune Tracker Tables',
    'LBL_TRIMSUGARFEEDS' => 'Prune SuiteCRM Feed Tables',
    'LBL_SENDEMAILREMINDERS' => 'Run Email Reminders Sending',
    'LBL_CLEANJOBQUEUE' => 'Cleanup Job Queue',
    'LBL_REMOVEDOCUMENTSFROMFS' => 'Removal of documents from filesystem',
    'LBL_AODOPTIMISEINDEX' => 'Optimise Advanced OpenDiscovery Index',
    'LBL_AODINDEXUNINDEXED' => 'Index unindexed documents',
    'LBL_POLLMONITOREDINBOXESAOP' => 'AOP Poll Monitored Inboxes',
    'LBL_AORRUNSCHEDULEDREPORTS' => 'Run scheduled reports',
    'LBL_PROCESSAOW_WORKFLOW' => 'Process AOW Workflow',
    'LBL_SCHEDULER_TIMES' => 'Scheduler Times',

This is a CLEAN installation of 7.10.9

**Comment by KaKite** [comment]
I did a diff --brief -Nr dir1/ dir2/ on an old 7.8.8 Schedulers folder that I know works against the 7.10.9 installation that wasn't working and came up with 20 odd files that are different. As a quick test I copied the 7.8.8 Schedulers folder to the 7.10.9 installation and the Jobs drop-down is now working correctly. Will try some individual file compares to see if there is anything other than the language strings that could be causing my problem
