### ISSUE TITLE
Dashlets

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5168]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by horus68** [comment]
@likhobory can you close this one? You posted a complete issue on the same subject.
