### ISSUE TITLE
Email inline editing does not work properly (ver. 7.10-RC-2)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5173]
Subj.  The same result in the DetailView.
![default](https://user-images.githubusercontent.com/5983672/36065921-5038f41e-0eb2-11e8-9055-bed5706784a8.png)

**Comment by PedroErnst** [comment]
@likhobory 

I think this might be fixed already. Right now for me it seems to work on the latest develop branch.

**Comment by likhobory** [comment]
Yes, it works, but in ListView after inline editing the hyperlink format is changed and indicator is not displayed until you refresh the page.

![default](https://user-images.githubusercontent.com/5983672/36385846-dec79782-15a4-11e8-8ebe-01986c5a38b2.png)

**Comment by PedroErnst** [comment]
@likhobory 

Ok thanks for the feedback, I'm on it.

**Comment by connorshea** [comment]
Was this fix ever backported to 7.10? I'm on 7.10.16 and I see the same issue.

1. Go to a list view where the items have emails
2. Double-click to inline-edit
3. Save the email.
4. The email cell is now a bunch of HTML data attributes, like in this issue's screenshot.

**Comment by likhobory** [comment]
The same issue in ver. 7.11.4
> Subj. The same result in the DetailView.

> ![default](https://user-images.githubusercontent.com/5983672/36065921-5038f41e-0eb2-11e8-9055-bed5706784a8.png)

@Dillon-Brown reopen this issue please.

**Comment by connorshea** [comment]
Any ideas on where to look RE: a fix for this? I assume it's the JavaScript screwing up somewhere but I don't know how to debug that.

**Comment by connorshea** [comment]
This is what I get when inline-editing and then hitting save:

<img width="321" alt="Screen Shot 2019-06-05 at 4 09 00 PM" src="https://user-images.githubusercontent.com/2977353/58993951-413aad80-87ac-11e9-9096-235e40b2a1eb.png">

I used the Firefox Debugger to determine that the `setValueClose()` function in `inlineEditing.js` causes the problem. 

```js
function setValueClose(value){
    $.get('themes/'+SUGAR.themes.theme_name+'/images/inline_edit_icon.svg', function(data) {
        // Fix for #3136 - replace new line characters with <br /> for html on close.
        value = value.replace(/(?:\r\n|\r|\n)/g, '<br />');

        $(".inlineEditActive").html("");
        $(".inlineEditActive").html(value + '<div class="inlineEditIcon">' + inlineEditIcon + '</div>');
        $(".inlineEditActive").removeClass("inlineEditActive");
    });

    buildEditField();
}
``` 

This is the value of the `value` parameter after its gone through the regex in `setValueClose()`:
```
<a class=\"email-link\" href=\"mailto:email@email.com\"<br /> onclick=\"$(document).openComposeViewModal(this);\"<br /> data-module=\"Contacts\" data-record-id=\"25d980a3-67c6-0767-b002-588264d47f59\"<br /> data-module-name=\"Name\" data-email-address=\"email@email.com\"<br /> >email@email.com</a>
```

I think, because the `<br/>` has a `>` in it, the HTML that's output closes the `a` tag at the first linebreak, i.e. the HTML treats `<a class=\"email-link\" href=\"mailto:email@email.com\"<br />` as an anchor tag.

If you look at the HTML in the browser inspector, I think it pretty much proves it:

![Screen Shot 2019-06-05 at 4 13 55 PM](https://user-images.githubusercontent.com/2977353/58994225-fff6cd80-87ac-11e9-8536-4e30697af9fc.png)

**Comment by connorshea** [comment]
So, there are a few ways we can solve this:

- Remove the regex that replaces linebreaks with `<br>`s. This would cause the issue in #3136 to regress, unfortunately.
- Fix the regex so linebreaks inside of a different HTML attribute wouldn't be inserted. Using regex to parse HTML is a nightmare, but it is technically doable.
- Convert the `value` into an HTML Element and then use `innerText()` to determine where we should be replacing the linebreaks (to prevent linebreaks from being replaced inside of another HTML tag).
- Figure out how to remove the linebreaks from the response from saveFieldHTML (The URL is `http://localhost/index.php?module=Home&action=saveHTMLField&field=email1&current_module=Contacts&id=351711e9-516f-2bc2-5dfe-58826d64c7bc&value=email@email.com&view=index&parent_type=&to_pdf=true`)

The HTML seems like it's coming from `modules/Emails/EmailUI.php`:

https://github.com/salesagility/SuiteCRM/blob/736dff06bd54e259a20153ce464bb795e170f2af/modules/Emails/EmailUI.php#L438-L444

We could just remove the linebreaks and make that line really long to fix the problem, but I think that's probably a pretty bad fix. We could also just strip out the linebreaks in there if we wanted to, which might be a better idea.

**Comment by connorshea** [comment]
I made a fix for this: https://github.com/connorshea/SuiteCRM/commit/b9bbc0ad07f8cc853a9b44a9002b746194e69618

I'll open a PR tomorrow.

**Comment by likhobory** [comment]
Partially fixed. The issue persists if the user tries to open another record without closing the current one (for example, if the first record has been opened by mistake).

1. Open some list view with emails
2. Double-click to inline-edit
3. Double-click on another record to inline-edit
