### ISSUE TITLE
Report - Missing Drop Box Field for Equal to Value on create report

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#5183]
When creating a report with two or more conditions, the second condition will not have a data entry field for the And Equal to Value.

#### Issue
If you duplicate a report and wish to change some of the conditions, it is expected that the data entry field for an "Equal to"/"Greater than"/etc. will have a condition select box.

For example, in the following screenshot you can see the Call Status Equal to Value has a drop allowing selection of Held, Planned, Not Held.
<img width="904" alt="screen shot 2018-02-12 at 11 09 33" src="https://user-images.githubusercontent.com/3494567/36106956-ae0040cc-0fe6-11e8-9da5-f381558955a1.png">

In the following screenshot you can see that the drop box is missing.
<img width="904" alt="screen shot 2018-02-12 at 11 09 15" src="https://user-images.githubusercontent.com/3494567/36107056-f4a88f8e-0fe6-11e8-81db-c1fc58a4bec5.png">

#### Expected Behavior
You should be able to have a drop down for the Value condition.

#### Actual Behavior
See above illustrations

#### Possible Fix
It appears that if you use this condition first on a new report, the drop down box does appear as it should.

#### Steps to Reproduce
1. Create a report using Report Module Call.
2. Add First Name + Last Name as fields
3. In the conditions tab, add Call End Date Greater Than or Equal to: Value: and select a date
4. Add a condition, Call Status / Equal to / and no drop down selection box.

#### Context
I was trying to identify contacts who haven't been contacted in a certain period of time.  Without the Call/Held condition, the report will not function.

I've found a workaround by creating reports from scratch but the report should be able to be duplicated and then modified without losing dialog or drop downs.  That new report has to use the Status / Equal to / as the first condition.  Sometimes the drop down will appear, sometimes not.

#### Your Environment
* SuiteCRM Version used: 7.9.12
* Browser name and version: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* Environment name and version:  mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2; PHP 7.0.27-0+deb9u1;
* Operating System and version: Debian 9.

**Comment by bunk3m** [comment]
This issue is also in SuiteCRM v 7.9.11.

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.2
after creating and duplicating a report, a dropdown is visible 
if you are still having this issue, please re-raise or get in touch
