### ISSUE TITLE
Email subject notifications: reduce size, remove SuiteCRM word

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5185]
#### Issue

Why is the notifications alerts have `SuiteCRM` word in the subject?
Take this subject: `<p>SuiteCRM Account - {ACCOUNT_NAME}</p>` it follows the pattern `Originated from - ABOUT `. But what do we want to see first in a notification email subject: the SuiteCRM brand or the account name? It should be the inverse as in `ABOUT - Originated from`.
And how many people in an organization will ask _what is this SuiteCRM thing_?

Special motivation:
- In mobile the subject line of any email needs to have the most relevant words in the beginning so we can see it in small screens or notifications screen/popup.
- No need to change translations when implementing systems by using neutral texts (as this information is to be translated)? 

Subject lines are in this file: 
https://github.com/salesagility/SuiteCRM/blob/master/include/language/en_us.notify_template.html

#### Expected Behavior

Notifications with short and neutral subjects

#### Actual Behavior

Some examples from /include/language/en_us.notify_template.html
```
<!-- BEGIN: Meeting_Subject -->
<p>SuiteCRM Meeting - {MEETING_SUBJECT}</p>
```
```
<!-- BEGIN: Account_Subject -->
<p>SuiteCRM Account - {ACCOUNT_NAME}</p>
```

```
<!-- BEGIN: Task_Subject -->
<p>SuiteCRM Task - {TASK_SUBJECT}</p>
```

#### Possible Fix

Remove SuiteCRM from the subject field. Example:
From
```
<!-- BEGIN: Meeting_Subject -->
<p>SuiteCRM Meeting - {MEETING_SUBJECT}</p>
```
to 
```
<!-- BEGIN: Meeting_Subject -->
<p>Meeting - {MEETING_SUBJECT} - CRM</p>
```
**or even better to:**
`<p>{MEETING_SUBJECT} - Meeting</p>`

Because it will be better in mobile and users don't even need to know what a CRM is (its an english abbreviation), they just need to know they have a meeting notification, so they need to open the email notification!

#### Context

- I often see this `SuiteCRM Meeting` translated as  `Meeting of the SuiteCRM`
This is not a _Meeting of the SuiteCRM_, is a _Meeting notification sent by the CRM_
- In mobile the subject line of any email needs to have the most relevant words in the beginning so we can see it in small screens or notifications popup.
- Neutral translations (no brand name) will avoid that system managers need to change translations from in the xx_xx.notify_template.html

**Comment by Mausino** [comment]
@horus68 i am currently translating it into slovak, and if i don't use SuiteCRM work in translation.. will it good ?? or should i waiting when will this ticket solved ???

![2018-02-16_0728](https://user-images.githubusercontent.com/5773777/36296120-ed5f10a6-12eb-11e8-837f-7551ca96e405.png)

**Comment by Mausino** [comment]
+ one more qustion on you guys @horus68 @likhobory 

In slovak, czech and russian + other languages we have male + female vers :D and in my case i have only women which using SuiteCRM  and the translate in slovak lang is

<0>{ASSIGNER}</0> has assigned an Account to <0>{ASSIGNED_USER}</0>  
<0>{ASSIGNER}</0> priradil Klienta <0>{ASSIGNED_USER}</0>

and verb "priradil" is in male but we also have for female "priradila"  :)

do you thing, that in future will SuiteCRM have option if user is Men or Woman ? or it is sish (thin ice) theme ???

**Comment by likhobory** [comment]
I add the ending in brackets for female as a compromise solution.
<b>{ASSIGNER}</b> has assigned an Account to <b>{ASSIGNED_USER}</b>
<b>{ASSIGNER}</b> назначил(а) контрагента пользователю <b>{ASSIGNED_USER}</b>

> do you thing, that in future will SuiteCRM have option if user is Men or Woman ? or it is sish (thin ice) theme ???
It would be nice, but I do not think that it will be done, too much work ..

**Comment by horus68** [comment]
> @Mausino  i am currently translating it into slovak, and if i don't use SuiteCRM work in translation.. will it good ?? or should i waiting when will this ticket solved ???

You can translate the way you prefer, no need to wait for this report!

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
