### ISSUE TITLE
Report Module - Conditions - Date Pop-up or manual entry not functioning

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#5186]
The date pop-up box is partially hidden on the Report:Conditions detail
#### Issue
When adding a Condition which needs to evaluate a date, the date pop-up box doesn't function.  While there is part of a dialog box and the select calendar icon, the pop-up won't work.  It is not possible to manually enter the date in the partial dialog box.

#### Expected Behavior
You should be able to select the date condition using the pop-up box or by entering the date in the dialog box.
See image below.  Note the partial dialog box under the second condition.  The calendar icon doesn't enable the calendar pop-up
<img width="895" alt="screen shot 2018-02-12 at 13 26 19" src="https://user-images.githubusercontent.com/3494567/36112948-38987d28-0ff9-11e8-955c-ec0036466695.png">

#### Actual Behavior
Unable to get the pop-up box to function or add a date in the dialog box.  So the condition doesn't work in the report.

#### Possible Fix
None so far.

#### Steps to Reproduce
1. Create a report using Contacts module.
2. Add First Name + Last Name in the Fields
3. In conditions add Calls:Status:Held (if possible - sometimes the pop-up box for Status isn't shown)
4. Add second condition Calls:Start Date: Greater than:Value and try to click on the calendar icon or add date in text box.

#### Context
I am unable to create reports with date conditions.

#### Your Environment
* SuiteCRM Version used: 7.9.12
* Browser name and version:Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): mysql Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2; PHP 7.0.27-0+deb9u1;
* Operating System and version (e.g Ubuntu 16.04):Debian 9.

**Comment by bunk3m** [comment]
This issue is also in SuiteCRM 7.9.11.

**Comment by Dillon-Brown** [comment]
Hi @bunk3m, I'm unable to replicate on 7.8.13 or 7.9.12. Have you tried checking permissions / running a repair + rebuild?

**Comment by bunk3m** [comment]
Hi @Dillon-Brown .  Yes, I have done the repair + rebuild a few times over the past days as I've tested both v7.9.11 and v7.9.12.   When I did the v7.9.11 to v7.9.12 upgrade a few days back, the permissions were checked OK.

Is there a way to share the report?

**Comment by Kevconry** [comment]
was not able to replicate in 7.13.1
when attempting to add a date via typing it in or through the calendar, the date is added successfully 
Please re-raise or get in contact if you are still having this issue
