### ISSUE TITLE
Case Descriptions Always Being Set to NULL

### ISSUE THREAD

**Issue by stancel** [salesagility/SuiteCRM#5188]
#### Issue
We use the Cases module to deal with customer support issues. While working there we noticed that we cannot save any description into the Cases' "Description" text box. We have tried this with the AJAX turned on and off for this module but it is the same behavior. 

When editing the case the TinyMCE editor is loaded. We type something in it and it shows up in the TinyMCE editor but upon saving it saves the cases.description = null. We also updated a case description manually in the database, then went to that case in the UI. It did display the text there. However, when we edited the case it would always save the value of cases.description = null whether or not we updated that field.

#### Expected Behavior
The description field in the cases module should save the inputted values correctly and be able to display the previously saved values when viewing that case.

#### Actual Behavior
Nothing is saved in that field and there is nothing of value in the error logs (apache, php or suitecrm logs). The only thing that I see that was relatively recent in the suitecrm.log file was this:
[ERROR] Unable to find relationship emails_email_templates

#### Steps to Reproduce
1. Create a new case in the Cases module
2. Fill in any applicable values and make sure to put a value into the description field
3. Save the new case
4. Notice that the values you put into the case description do not save but others fields have. The value that you put into the description field is not displayed when viewing the record. If you check the corresponding record in the database you will find that the cases.description field is null.

#### Context
This bug is keeping us from effectively using the Cases module to support our customer. To us it is a high priority issue.

#### Your Environment

* SuiteCRM Version used: Version 7.9.12
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Verion 63.0.3239.132 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.21, PHP 7.0.15
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Hi @stancel, I'm not able to replicate this on 7.9.12. Have you tried checking permissions / running repair + rebuild?

**Comment by stancel** [comment]
Thanks for responding Dillon. We found the issue in a CaseSaveHook that we had implemented. Closing this issue.
