### ISSUE TITLE
Attachement in detail view of non imported email doesn't show

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5190]
#### Issue

If you see in list view of email that email has attachment.. and you look on this email in detail view.. you are not able see its attachment.. 

only one way is import this email and after you will able get this attachment as note in subpanel history

#### Expected Behavior

User should be able to see the name of attachment and will also available on click download this attachment before of import process.

#### Actual Behavior

You don't know what is in email ... best situation is if you find in body text like.. more in attachment :D and you are not able to see or download it.

#### Steps to Reproduce

1. Listview
2. Look on email which has attachment 
3. Look on his detal view (must be not imported)

#### Your Environment

* SuiteCRM Version used: 7.9.12
* Browser name and version : Chrome 64.x
* Environment name and version: MySQL 5.6, PHP 7.2
* Operating System and version: Win 10 Pro

**Comment by Mausino** [comment]
@Dillon-Brown i think that is a bug, not suggestion

**Comment by Mausino** [comment]
@samus-aran @Dillon-Brown should be this ticket label as issue.. Becuse if big fail if you have list of emails.. you'll see on list view that has it the attachments and when you click on this record you go inside and you can't see the attachments.. 

Every email client has this option.. And not every email must be imported to system and this is big problem that for example you got some email from new client with attachments but you must first create lead or contact that you can import emial that you able to see the attachments. Big fail is if in attachments are nothing e.g. (unimportant things like images from signatures)

Now my employees using on same time roundcube to see the attachment and download it. 
On old 7.8 LTS version wasn't this problem.

**Comment by Dillon-Brown** [comment]
@Mausino Agreed

**Comment by Dillon-Brown** [comment]
Interestingly enough I can't actually get the attachment icon to appear in the list-view.... I'll put up a fix for this and then take a look at adding this to the detail-view.
