### ISSUE TITLE
Notification icon double in Suite7 theme

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#5191]
#### Issue

When i upgrade my suitecrm to 7.8.13, notification icon is shown double.
![screenshot_2](https://user-images.githubusercontent.com/22373035/36139990-b7e836a6-10b0-11e8-8e22-02726863fee6.png)

#### Expected Behavior

It should be there like this;
![screenshot_1](https://user-images.githubusercontent.com/22373035/36140026-dc16074c-10b0-11e8-8594-397359b613f9.png)

#### Steps to Reproduce

1. Upgrade Suitecrm to 7.8.13 LTS
2. Select Suite7 theme
3. Look at the top bar.

#### Your Environment

* SuiteCRM Version used: 7.8.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by e-reeley** [comment]
Hi @dursuntosun 

Sorry to see this issue.

Just before we look into seeing why this has happened, would you be able to confirm that a Repair and Rebuild was carried out on upgrade and also reset the cache just in case?

I tried to replicate this one and couldn't, so hopefully this resolves the issue. 

Please feedback and we can assist if this doesn't resolve the issue!

Thanks for raising this.

**Comment by dursuntosun** [comment]
Yes, Repair and Rebuild was carried out on upgrade. But i could not reset my cache. How to reset it, just delete cache folder?

**Comment by e-reeley** [comment]
Yeah, within the browser. Just in the case that it’s holding a previous css from somewhere. 

It may not be what is causing the issue, but certainly ensures if it is an issue or just mixed up files.

**Comment by dursuntosun** [comment]
Yes, sure I delete all browser cache and try it all browser

**Comment by e-reeley** [comment]
How did you get on with that, did it make any difference at all? 

Thanks.

**Comment by dursuntosun** [comment]
No difference, I live with it.

**Comment by e-reeley** [comment]
I wouldn’t if it is an issue :)

I had tried with an updated version of what you are using which we have planned to release soon. 

If you keep an eye out for that then there may have been something added in which fixes this issue, I can keep you up to date?

Thanks again!

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
