### ISSUE TITLE
Nothing to translate - Empty language files to be removed?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5195]
#### Issue

1- Is there any reason for 2 empty translations files?
See 
/modules/MySettings/language/
/modules/ResourceCalendar/language/

2- Related issue https://github.com/salesagility/SuiteCRM/issues/4920 but for non empty files with noting to translate:
/include/SugarFields/Fields/Address/en_us.DetailView.tpl
/include/SugarFields/Fields/Address/en_us.EditView.tpl

#### Possible Fix

Delete files

#### Context

Reduce house keeping on translation project?

**Comment by cameronblaikie** [comment]
hi @horus68 , These files are necessary you need a language file for every module. There are a bunch of dynamic includes like this: include "modules/$module/language/en_us.lang.php";

**Comment by cameronblaikie** [comment]
@horus68 Actually thinking about this we might be able to wrap the dynamic includes with file_exists, not sure how much work this would be though

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
