### ISSUE TITLE
Importing Contacts saves every contacts email as the first email in the csv.

### ISSUE THREAD

**Issue by rokacom** [salesagility/SuiteCRM#5197]
There was the same issue in a previous version, but users reported it to be fixed.  I confirmed it was not in version 7.9.9, then I upgraded to 7.9.12 and the issue appeared.

#### Issue

When importing contacts via the "Import Contacts" method each contact is saved with the first line's email address. The same email address is saved for more than the correct contact.

#### Expected Behavior

The correct email should be saved in each contact.

#### Actual Behavior
When importing a csv with the following contents.

Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3

When imported It adds the records as follows
First Name       Last Name    Email
First1                 Last1            test1@domain.com
First2                Last2            test1@domain.com
First3                Last3            test1@domain.com

#### Possible Fix
Unknown

#### Steps to Reproduce

1. Go to Contacts List
2. Click on Import Contacts
3. Import a file with the following information

Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3

4. Look at the contacts. Each contact will have the same email address.

#### Context

We cannot import our contacts into a new installation.

#### Your Environment

* SuiteCRM Version used: 7.9.12. (It was working in 7.9.9 before I upgraded)
* Browser name and version Firefox 58.0.2 (64-bit) On Mac
* Environment name and version  PHP 7 
* Operating System and version: Ubuntu 16.04

**Comment by sasha2002** [comment]
Same here with Leads

**Comment by horus68** [comment]
Related: https://github.com/salesagility/SuiteCRM/issues/5200
