### ISSUE TITLE
Error in Import after upgrading to SuiteCRM 7.8.12

### ISSUE THREAD

**Issue by psatasiya** [salesagility/SuiteCRM#5198]
I have upgraded to SuiteCRM 7.8.12 and then getting this error while importing records in Account module, I have not checked for other modules. Before upgrade(7.7.2), import was working.

I'm getting this error 

`NOTICE: [8] Uninitialized string offset: 0 on line 156 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 1 on line 157 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 2 on line 158 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 3 on line 159 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 0 on line 156 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 1 on line 157 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 2 on line 158 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 3 on line 159 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 0 on line 156 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset: 1 on line 157 in file /var/www/html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php
NOTICE: [8] Uninitialized string offset:..................... `

Can I have some suggestion on this?

Thanks

**Comment by psatasiya** [comment]
I have disabled AOD from admin panel and it's working now.

**Comment by horus68** [comment]
@psatasiya Please reopen as there is a bug somewhere (system is trying to start indexing before import is finished)
At least some message needs to be created in future versions to be available before importing.

**Comment by Petrouchka** [comment]
I upgraded SuiteCRM from version 7.10.7 to version 7.10.8. Now, my server crashes when I'm using it, the file error_log is growing more than 200 Mo (!) with the same error in it, repeated thousang of times PHP Notice:  Uninitialized string offset: 7 in /home/numopenf/public_html/crm/modules/AOD_Index/Lib/Zend/Search/Lucene/Storage/File.php on line 201

**Comment by pgorod** [comment]
This could be a corrupted AOD Index, maybe the solution is simply to restart the indexing.

There is more information about this here

https://pgorod.github.io/Reindex-AOD/

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
