### ISSUE TITLE
DB-mismatch on MSSQL Server

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#5199]
After installing suitecrm 7.8.13 I run Quickrepair and got Database missmatch on some fields. After executing the sql-statements and runnig quickrepair again. the same fields are displayed again.
#### Issue

/* Table : am_tasktemplates */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - milestone_flag -  ROW [name] => 'milestone_flag'  [type] => 'bit'  [len] => '1'  [default] => '0'  */
/* VARDEF - milestone_flag -  ROW[required] => ''  [name] => 'milestone_flag'  [vname] => 'LBL_MILESTONE_FLAG'  [type] => 'bit'  [massupdate] => '0'  [default] => '0'  [no_default] => ''  [comments] => ''  [help] => ''  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [unified_search] => ''  [merge_filter] => 'disabled'  [len] => '255'  [size] => '20'  [dbType] => 'bool'  */
 ALTER TABLE am_tasktemplates DROP CONSTRAINT DF__am_taskte__miles__34B3CB38 ALTER TABLE am_tasktemplates ALTER COLUMN [milestone_flag] bit NULL ;
 ALTER TABLE am_tasktemplates ADD   DEFAULT '0' FOR milestone_flag ;
/* INDEXES */
/* Table : jjwg_maps */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - distance -  ROW [name] => 'distance'  [type] => 'real'  [len] => '4'  */
/* VARDEF - distance -  ROW[required] => ''  [name] => 'distance'  [vname] => 'LBL_DISTANCE'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Distance'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => '1'  [reportable] => '1'  [len] => '9,4'  [size] => '20'  [precision] => '4'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_maps ALTER COLUMN [distance] float(9) NULL ;
 ;
/* INDEXES */
/* Table : jjwg_markers */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - jjwg_maps_lat -  ROW [name] => 'jjwg_maps_lat'  [type] => 'real'  [len] => '4'  [default] => '0.00000000'  */
/* VARDEF - jjwg_maps_lat -  ROW[required] => ''  [name] => 'jjwg_maps_lat'  [vname] => 'LBL_JJWG_MAPS_LAT'  [type] => 'float'  [massupdate] => '0'  [default] => '0.00000000'  [comments] => ''  [help] => 'Latitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '10,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  */
 ALTER TABLE jjwg_markers DROP CONSTRAINT DF__jjwg_mark__jjwg___35A7EF71 ALTER TABLE jjwg_markers ALTER COLUMN [jjwg_maps_lat] float(10) NULL ;
 ALTER TABLE jjwg_markers ADD   DEFAULT '0.00000000' FOR jjwg_maps_lat ;
/*MISMATCH WITH DATABASE - jjwg_maps_lng -  ROW [name] => 'jjwg_maps_lng'  [type] => 'real'  [len] => '4'  [default] => '0.00000000'  */
/* VARDEF - jjwg_maps_lng -  ROW[required] => ''  [name] => 'jjwg_maps_lng'  [vname] => 'LBL_JJWG_MAPS_LNG'  [type] => 'float'  [massupdate] => '0'  [default] => '0.00000000'  [comments] => ''  [help] => 'Longitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '11,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  */
 ALTER TABLE jjwg_markers DROP CONSTRAINT DF__jjwg_mark__jjwg___369C13AA ALTER TABLE jjwg_markers ALTER COLUMN [jjwg_maps_lng] float(11) NULL ;
 ALTER TABLE jjwg_markers ADD   DEFAULT '0.00000000' FOR jjwg_maps_lng ;
/* INDEXES */
/* Table : jjwg_address_cache */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - lat -  ROW [name] => 'lat'  [type] => 'real'  [len] => '4'  */
/* VARDEF - lat -  ROW[required] => ''  [name] => 'lat'  [vname] => 'LBL_LAT'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Latitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '10,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_address_cache ALTER COLUMN [lat] float(10) NULL ;
 ;
/*MISMATCH WITH DATABASE - lng -  ROW [name] => 'lng'  [type] => 'real'  [len] => '4'  */
/* VARDEF - lng -  ROW[required] => ''  [name] => 'lng'  [vname] => 'LBL_LNG'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Longitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '11,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_address_cache ALTER COLUMN [lng] float(11) NULL ;
 ;
/* INDEXES */

#### Expected Behavior

No mismatches schould be displayed in Quick repair. 
#### Steps to Reproduce

1. install Suitecrm 7.8.13 on obunto/debian and use  MSSQL Database
2.Run Quickrepair
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):  php7.0 and mssql -Driver (https://github.com/Microsoft/msphpsql )
MSSQL Server (Microsoft SQL Server 2014 - 12.0.2269.0 (X64))
* Operating System and version (e.g Ubuntu 16.04):ubunto 16.04  or Debian 9

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
