### ISSUE TITLE
Same email in Import Leads after upgrading to SuiteCRM 7.8.12

### ISSUE THREAD

**Issue by sasha2002** [salesagility/SuiteCRM#5200]
#### Issue

After you import new Leads, the Lead email address is the same.
#### Expected Behavior

Each Lead have it's own email
#### Actual Behavior

Wed Feb 14 09:43:15 2018 [20663][1][ERROR] Index doesn't exists in the specified directory.
Wed Feb 14 09:43:16 2018 [20663][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:43:16 2018 [20663][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:43:16 2018 [20663][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:43:16 2018 [20663][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:43:16 2018 [20663][1][ERROR] Index doesn't exists in the specified directory.
Wed Feb 14 09:50:52 2018 [20661][1][ERROR] File upload://IMPORT_Lead_1-0 cannot be touched
Wed Feb 14 09:50:52 2018 [20661][1][ERROR] File upload://import/dupes_1.csv cannot be touched
Wed Feb 14 09:50:52 2018 [20661][1][ERROR] File upload://import/dupesdisplay_1.csv cannot be touched
Wed Feb 14 09:50:52 2018 [20661][1][ERROR] File upload://import/errorrecords_1.csv cannot be touched
Wed Feb 14 09:50:52 2018 [20661][1][ERROR] File upload://import/errorrecordsonly_1.csv cannot be touched
Wed Feb 14 09:50:56 2018 [20708][1][FATAL] Caught error: stat(): stat failed for upload/import/status_1.csv
Wed Feb 14 09:50:56 2018 [20708][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Wed Feb 14 09:50:56 2018 [20708][1][ERROR] File upload://import/status_1.csv cannot be touched
Wed Feb 14 09:51:19 2018 [20664][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:51:19 2018 [20664][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:51:19 2018 [20664][1][ERROR] Unable to get proper side for link contact
Wed Feb 14 09:51:19 2018 [20664][1][ERROR] Unable to get proper side for link contact
#### Steps to Reproduce

1. Create a list of Leads
2. Import it
3. Got all imported Leads have same email

#### Your Environment

* SuiteCRM Version used: Version 7.9.12 | Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All Browsers
* Environment name and version (e.g. MySQL, PHP 7): 
PHP : PHP 7.0.27-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 14:12:46) ( NTS )
MySQL : 5.6.36-82.0 - Percona Server
Tried PHP 5.6 same bug.
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Duplicate #5197
