### ISSUE TITLE
Opt In checkbox is allways visible (7.10-RC-2)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5201]
Quote from [this](https://suitecrm.com/wiki/index.php/Release_notes_7.10-RC2-Guide) guide:

> Once Opt In settings have been selected:
> 
>     An additional Opt In checkbox will be visible in Detail and Edit views for email address fields in Contacts, Leads and Targets.

Opt In settings is **disabled** in the Admin  Email Settings.

#### Expected Behavior
An additional Opt In checkbox is NOT visible.

#### Actual Behavior
An additional Opt In checkbox is still visible.

**Comment by horus68** [comment]
To @salesagility : that guide should be made a normal tutorial, not just on release notes!

**Comment by likhobory** [comment]
By the way, this guide should be updated, information about the missing Opt In template is outdated.

> The Confirmed Opt In default template is not included in this release and requires users to create this...

**Comment by samus-aran** [comment]
Thanks for this @likhobory, we'll define this as a bug.
@horus68 - We are moving away from the WIKI asap and the RC2 was in between this - the User Guide will include this and the other new features.

**Comment by PedroErnst** [comment]
@likhobory 

On the current develop (7.10) branch it seems to work a expected, with disabled Opt in the checkbox doesn't show.

![screenshot from 2018-02-16 10-07-07](https://user-images.githubusercontent.com/34056696/36302671-2dc540f6-1301-11e8-8499-965a5c593cf7.png)

**Comment by likhobory** [comment]
Thanks, confirmed.
