### ISSUE TITLE
Replace ajaxui url scheme with just javascript location api or clean urls

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#5213]
#### Issue

Currently every page link and click goes to something like `/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3DDetailView%26record%3D0031A0abcde0W2clQAC`

This makes sharing links extremely annoying and difficult as sometimes the links are cut off and other times the other user gets errors about security warnings.

In this day and age we can change the location to be the direct url of the page you're on after the case.

#### Expected Behavior

url should be nice and clean like `/index.php?module=Contacts&action=DetailView&record=0031A000020W2clQAC`

#### Actual Behavior

url always has the ajaxui action and looks like `/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3DDetailView%26record%3D0031A0abcde0W2clQAC`

#### Possible Fix

* Use javascript after the fact to replace the url in the browser
* Update the linking system to have nice clean urls in the first place

#### Steps to Reproduce

1. Open a record
2. Click to another record
3. Look at URL (it's a mess)
4. Share with someone (more often than not it will result in an error for being cut-off or for a csrf error)

#### Context

How do you share records with co-workers quickly?

#### Your Environment

* SuiteCRM Version used: 7.9.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL, php 5.6
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Kevconry** [comment]
wasnt able to replicate in 7.13.1
after clicking the link once it has been shared, the page is displayed successfully and does not produce an error
please re-raise or get in touch if you are still having this issue

**Comment by pgorod** [comment]
This is not a matter of errors, it's a suggestion for a cleaner URL scheme.

Anyway, it might just as well be closed, I guess this won't change for v7, as it approaches end of life, and it does not apply to v8, which has its own (cleaner) URL scheme.
