### ISSUE TITLE
7.10 RC2 Studio ProjectTaskTemplate Module Layout Error

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5214]
#### Issue

Getting ERROR using Studio for ProjectTaskTemplate Module
Changing Layouts PopUpView PopUp ListView

ERROR LOG:

[15-Feb-2018 00:33:13 UTC] PHP Fatal error:  Uncaught Error: Cannot access protected property DeployedMetaDataImplementation::$_history in beta/modules/ModuleBuilder/parsers/views/PopupMetaDataParser.php:210
Stack trace:
#0 beta/modules/ModuleBuilder/controller.php(812): PopupMetaDataParser->handleSave()
#1 beta/include/MVC/Controller/SugarController.php(523): ModuleBuilderController->action_popupSave()
#2 beta/include/MVC/Controller/SugarController.php(491): SugarController->do_action()
#3 beta/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
#4 beta/modules/ModuleBuilder/controller.php(108): SugarController->process()
#5 beta/include/MVC/Controller/SugarController.php(373): ModuleBuilderController->process()
#6 beta/include/MVC/SugarApplication.php(109 in beta/modules/ModuleBuilder/parsers/views/PopupMetaDataParser.php on line 210
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10 RC2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariahDB  PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS7 64-bit

**Comment by PedroErnst** [comment]
This has been addressed in #5086
