### ISSUE TITLE
Edit Call: Additional details popup is empty

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#5244]
#### Issue

When editing a call, in the Scheduling section you can hover over the names of the meeting attendees a popup surfaces with additional details for that person.

This popup is now empty after an upgrade from 7.8.6->7.8.13.

#### Expected Behavior

The popup should contain prmary_address, etc. from the Contact record. 

#### Actual Behavior

The popup is empty.

#### Possible Fix

In file modules/Meetings/jsclass_scheduler.js
`$.each(arguments,function(index,value){eval(value[0]) ....`
was changed to
`$.each(arguments,function(index,value){SUGAR.util.evalScript(value[0]) ....`

I.e. replacement of `eval()` with `SUGAR.util.evalScript()`.

Restoring the `eval()` call fixes the problem. Also replacing it with SUGAR.util.globalEval() also works. I'm not qualified to know exactly which is better or why.

P.S. Why is that source file so badly formatted? 

#### Steps to Reproduce

1. Edit a call
2. Hover over one of the meeting attendees
3. The popup is empty.

#### Your Environment

* SuiteCRM Version used: 7.8.13
* Browser name : Chrome: Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by PedroErnst** [comment]
@nelem 

It seems originally the eval() was replaced because of security implications.
I'm looking into this.
