### ISSUE TITLE
Always display email address using mailto protocol instead javascript

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#5247]
#### Issue

Currently if you use the internal email system then email addresses displayed within the system have a link with `javascript:void()`.  This is done so that javascript can decide to how to handle the link (i.e. open up using `mailto` protocol or open up using the internal email system).

The problem is that there is no way to quickly right click and hit copy email address in most browsers and a lot of the times trying to select the whole email before copying is hard.  Even the ability to double click on the cell containing the word cannot be done since in most case this actually opens the field for editing.

The link for all emails should still be the normal `mailto` protocol  (e.g. `href="mailto:john@example.org"`) while javascript is used to intercept the event and either allow the click to happen opening an external email composer or not allow the event to happen and instead open the internal email composer.

The benefit of this is that one could simple right click and choose to "copy email address" in most modern browsers.

#### Expected Behavior
Right clicking on an email address link should allow me to "copy email address"

#### Actual Behavior

Right clicking on an email address has no option to "copy email address" since the link is to `javascript:void()`

#### Possible Fix

* Change all email addresses to display with `href="mailto:john@example.org"`
* Update javascript functionality to listen for click and either allow to continue for external email composer or cancel even and transfer to internal email composer. 

#### Steps to Reproduce

1. Have internal email composer enabled
2. Go to lead/contact/account with an email address field
3. Right click on email address in order to "copy email address"
4. Note that the option does not exist

#### Context

Would like to continue to use the internal email composer but quickly have the ability to copy an email address.

#### Your Environment

* SuiteCRM Version used: 7.9.14
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 63.0.3239.132
* Environment name and version (e.g. MySQL, PHP 7): MySql 5.6.33 php 5.6.33
* Operating System and version (e.g Ubuntu 16.04): Mint

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Always display email address using mailto protocol instead javascript](https://trello.com/c/H687ONI2/252-always-display-email-address-using-mailto-protocol-instead-javascript)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
