### ISSUE TITLE
"Undefined error" after upgrade to 7.8.15

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#5248]
#### Issue

When i edit layout of some modules in studio, there are "undefined" fields. And also when i save layout, there is an undefined pop up window.

![screenshot_1](https://user-images.githubusercontent.com/22373035/36368324-c252ab88-1567-11e8-9a02-5e9304adc0dd.png)

![screenshot_2](https://user-images.githubusercontent.com/22373035/36368329-c69f2c8e-1567-11e8-9ac0-418297105911.png)

#### Steps to Reproduce

1. Open studio
2. Change any module layout
3. Save.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by e-reeley** [comment]
Hi @dursuntosun 

Sorry to see this, I can't seem to replicate this issue on a fresh install of 7.8.15, so I'm just going to ask a couple of questions to see if we can work out why this has happened.

Is this a fresh install of 7.8.15?
If it is an upgrade, was a Repair and Rebuild carried out afterwards, just to ensure everything is built as it should be?
Also, is there anything in the log?

Thanks for raising this issue.

**Comment by e-reeley** [comment]
Sorry, I was not able to recreate this issue following the 7.8.12 -> 7.8.15 upgrade on clean installs.

Just to be safe, would you be able to rebuild the htaccess file through the admin and repair process.

This may not be the issue, but may help narrow down why this is happening. 

Thanks.

**Comment by dursuntosun** [comment]
Yes, it ok now. After rebuild the htaccess file through the admin and repair process. Thank you.

**Comment by e-reeley** [comment]
Ah good to hear!
