### ISSUE TITLE
[language] OAuth2: The label LBL_REDIRECT_URL  does not have a value.

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5249]
Please add the corresponding line to /modules/OAuth2Clients/language/en_us.lang.php.

**Comment by horus68** [comment]
Fixed here: https://github.com/salesagility/SuiteCRM/pull/5321
`'LBL_REDIRECT_URL' => 'Redirect URL'`

**Comment by likhobory** [comment]
Thanks.
