### ISSUE TITLE
MSSQL double quotes error

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#5250]
I have a setup an inbound email and one user is receiving it.
When this user is viewing his list of emails it shows it correctly but a strange and Fatal error is reported.

[FATAL] Query Failed:SELECT emails.*, users.user_name as assigned_user_name
FROM emails
LEFT JOIN users ON emails.assigned_user_id=users.id
WHERE emails.uid LIKE "1" AND emails.deleted=0
ORDER BY date_sent DESC::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name '1'.

I have run the same query against database and it has incorrect syntax because it should have only '' and not "" after like operator.

Also same problem (**double quotes instead of single quotes**) arises around emails/folders like this one:
[FATAL]  Query Failed:SELECT * FROM folders WHERE parent_folder = "9b95b99e-8737-beca-b3c0-58b69f5ee376"::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name '9b95b99e-8737-beca-b3c0-58b69f5ee376'.

or the other one

[FATAL]  Query Failed:SELECT * FROM folders WHERE folders.id LIKE "" OR folders.parent_folder LIKE ""::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]An object or column name is missing or empty. 

Version 7.9.7
SQL Server 2016. Build Version: 13.0.1601.5

**Comment by vmijalkovic** [comment]
Just tested with 7.9.14 as well...Same problem...

**Comment by vmijalkovic** [comment]
And with 7.10...still the same..FATAL Error logged, but it actually retrieves all emails and it looks normal except this error being logged

**Comment by zoltankocsardi** [comment]
@vmijalkovic I've tested it on 7.10 and it worked for me.

**Comment by vmijalkovic** [comment]
@zoltankocsardi it works for me as well but logs FATAL error. Actually I must say I am surprised that a list of emails is correctly retrieved knowing that the same query produces error when run against database using SQL Server Management Studio.
