### ISSUE TITLE
7.8.15 - Undefined when importing contacts

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#5251]
#### Issue

Pop up that just says "Undefined" with a Cancel and OK button appears when importing contacts with the option to "Create new records and update existing records" checked.
![screenshot_3 copy](https://user-images.githubusercontent.com/22373035/36369818-c83065a8-156d-11e8-822c-75dca0d292a5.png)

#### Steps to Reproduce

1. Go to Contacts
2. Choose Import
3. Select a CSV file
4. Check "Create new records and update existing records"
5. Click the Next button

#### Your Environment

* SuiteCRM Version used: 7.8.15
 *Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by dursuntosun** [comment]
When apply this patch #4317, it was solved.

**Comment by Dillon-Brown** [comment]
Should be unrelated to #4317 as that was just a workaround. The real issue was solved in #5141 and #5225 which may require a rebuild of .htaccess

**Comment by dursuntosun** [comment]
if i dont patch #4317, no solution for me.

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
