### ISSUE TITLE
7.8.15 undefined labels  in quote item lines

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#5255]
#### Issue

upgraded from 7.8.8 to 7.8.15 , now when creating a quote, the labels in lint items are "undefined" 

#### Expected Behavior

correct labels should be displayed

#### Actual Behavior

see attached screenshot
#### Steps to Reproduce

1. create a quote
2.add a group
3.add product line
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): 7
* Operating System and version (e.g Ubuntu 16.04): ubuntu 16.04
![undefined labels](https://user-images.githubusercontent.com/8605061/36380979-7a7ab2f2-1584-11e8-99f1-6e4bdcb212b4.PNG)

**Comment by e-reeley** [comment]
Hi @boombata 

Sorry to see this, I'm just going to make a couple checks to help us see what is causing this issue.

Would you be able to ensure that you run the following in the crm:

1) Repair and Rebuild
2) Repair htaccess file

Both found in the admin and repair file.

Thanks for reporting the issue.

**Comment by boombata** [comment]
Hi @e-reeley 
yes both repairs have been run. 
thank you.

**Comment by e-reeley** [comment]
@boombata 

Thats good, has that helped at all or are we still in the same issue? :)

Thanks.

**Comment by boombata** [comment]
sorry no help, problem still persists :)

**Comment by e-reeley** [comment]
Okay, ill take a look into this :) Ill keep you posted!

Thanks again.

**Comment by e-reeley** [comment]
I downloaded a fresh install of 7.8.8, upgraded to 7.8.15 and this does not seem to be an issue for me.

Was it okay before the upgrade? :) 

Thanks.

**Comment by boombata** [comment]
yes

**Comment by boombata** [comment]
tried a JS language rebuild but did not help. i'm going through the logs to find something revelent.

**Comment by e-reeley** [comment]
Perfect, anything that can maybe put us on the right line or maybe try and spot why my instance is different.

Thanks.

**Comment by boombata** [comment]
cannot find anything from the logs, it is like the jslanguage cache is not received by the browser (if i understood how it works) in the quote only the line items do no have labels, all other parts of the quote is ok including group label.

**Comment by boombata** [comment]
yesterday i forget to say that i already re-applied chmod and chown like specified in installation doc followed by a quick repair and rebuild but it did not help 

I don't think it is linked but in case... missing this line in .htaccess compared to previous version: 
RedirectMatch 403 (?i)/+custom/+blowfish
and ifmodule is present twice like this: 

`<IfModule mod_rewrite.c>
    Options +FollowSymLinks
    RewriteEngine On
    RewriteBase /
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&module=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&module=$1&lang=$2 [L,QSA]
</IfModule>
<FilesMatch "\.(jpg|png|gif|js|css|ico)$">
        <IfModule mod_headers.c>
                Header set ETag ""
                Header set Cache-Control "max-age=2592000"
                Header set Expires "01 Jan 2112 00:00:00 GMT"
        </IfModule>
</FilesMatch>
<IfModule mod_expires.c>
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType text/javascript "access plus 1 month"
        ExpiresByType application/x-javascript "access plus 1 month"
        ExpiresByType image/gif "access plus 1 month"
        ExpiresByType image/jpg "access plus 1 month"
        ExpiresByType image/png "access plus 1 month"
</IfModule>
# BEGIN SUGARCRM RESTRICTIONS
RedirectMatch 403 (?i).*\.log$
RedirectMatch 403 (?i)/+not_imported_.*\.txt
RedirectMatch 403 (?i)/+(soap|cache|xtemplate|data|examples|include|log4php|metadata|modules)/+.*\.(php|tpl)
RedirectMatch 403 (?i)/+emailmandelivery\.php
RedirectMatch 403 (?i)/+upload
RedirectMatch 403 (?i)/+cache/+diagnostic
RedirectMatch 403 (?i)/+files\.md5$
<IfModule mod_rewrite.c>
    Options +FollowSymLinks
    RewriteEngine On
    RewriteBase /
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]
</IfModule>
# END SUGARCRM RESTRICTIONS
`

**Comment by boombata** [comment]
@e-reeley ,   still having undefined labels in quotes lines items,

What i did so far 

- Set the following permissions on the SuiteCRM directory(Linux):

    sudo chown -R www-data:www-data .
    sudo chmod -R 755 .
    sudo chmod -R 775 cache custom modules themes data upload config_override.php

- .htaccess rebuild, (is is set with: RewriteBase /)
- quick repair and rebuild 
-Rebuild Javascript Languages
- cleared browser cache (also tried from other pc and navigators) 
- used navigator debuger and confirmed it get data to https://crm.mydomain.com/cache/jsLanguage/en_us.js?v=BYrfiJ2bM90xSDUXVDWBfg  (i changed the variable to past it here) 
- in the answer from en_us.js?v=BYrfiJ2bM90xSDUXVDWBfg there is no "add service" nor "add product" translations. 
- i deleted /cache/jsLanguage/en_us.js re recreate it, but did not help. 
- looked at upgrade log, no error reported. 
- run first step of upgrade wizzard to check if all files files permission are well set, all is ok. 

not sure if it could be linked but, I have some custom fields in the quote modules and custom en_us.lang.js for AOS_Quotes containing only the new fields translations. these fields were added from studio last year.

do you have other ideas while i continue my investigations ? 

Thank you very much.

**Comment by boombata** [comment]
@e-reeley Got it fixed !! 

there is a problem with this https://github.com/salesagility/SuiteCRM/pull/5141

the rebuild htaccess file  is adding 2 mod_rewrite.c to .htaccess see attached file. (or keeping the one you add before upgrade)

in the first one the rewrite parameter got "module" parameter but in the second it send "modulename"
[htaccess.txt](https://github.com/salesagility/SuiteCRM/files/1740611/htaccess.txt)
 parameter as expected by the PR 5141.

deleted the first one with "module" parameter (the one outside BEGIN SUGARCRM RESTRICTIONS)
run quick repair.

**Comment by e-reeley** [comment]
Hi @boombata 

Sorry for the late response, Im happy to hear that you managed to spot the issue :D 

It now seems to be behaving as it should?

Thanks again for raising the issue and helping with a solution to this issue.

**Comment by boombata** [comment]
Hi @e-reeley

Yes it is behaving as it should now. 

It could be good to rework modules\Administration\UpgradeAccess.php to remove  mod.rewrite.c from old content (line 88).

Thanks for your help.
