### ISSUE TITLE
New 7.10 Studio Undefined Messages & Error Condition

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5266]
#### Issue

The new 7.10 Upgrade from 7.10 RC2 worked OK. Thank you for the progress.
I'm still working with the install but have found Studio  Problems where changes to Account Module apply OK but display "Undefined" Messages. Change to Popup get tghe same error message I reported for 7.10RC:
[20-Feb-2018 03:22:30 UTC] PHP Fatal error:  Uncaught Error: Cannot access protected property DeployedMetaDataImplementation::$_history in  public_html/beta/modules/ModuleBuilder/parsers/views/PopupMetaDataParser.php:210
Stack trace:
#0  public_html/beta/modules/ModuleBuilder/controller.php(812): PopupMetaDataParser->handleSave()
#1  public_html/beta/include/MVC/Controller/SugarController.php(523): ModuleBuilderController->action_popupSave()
#2  public_html/beta/include/MVC/Controller/SugarController.php(491): SugarController->do_action()
#3  public_html/beta/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
#4  public_html/beta/modules/ModuleBuilder/controller.php(108): SugarController->process()
#5  public_html/beta/include/MVC/Controller/SugarController.php(373): ModuleBuilderController->process()
#6  public_html/beta/include/MVC/SugarApplication.php(109 in  public_html/beta/modules/ModuleBuilder/parsers/views/PopupMetaDataParser.php on line 210
#### Steps to Reproduce

1.Use Studio for Account Module to make Layout Changes
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: new 7.10 Upgrade from 7.1RC2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariahDB
* Operating System and version (e.g Ubuntu 16.04): CentOS 7 64-bit

**Comment by dursuntosun** [comment]
Would you be able to rebuild the htaccess file through the admin and repair process.

**Comment by goingsmart** [comment]
I rebuilt htaccess as requested. Unfortunately, No change in Studio issues.
The top of the Studio left and right collapsible panels say undefined
Anything else for me to do?

**Comment by e-reeley** [comment]
Hi @goingsmart 

Sorry to see this issue.

Im not sure if this will help, but im sure this is related PR: [#5252](https://github.com/salesagility/SuiteCRM/pull/5252).

Also. after your repair of the htaccess file, was a repair and rebuild carried out and clearing the cache within the browser, just in the case that something was stored before the repair.

Thanks for raising this issue.

**Comment by goingsmart** [comment]
Both  my new 7.10  problems have been resolved.
=========
Studio "undefined" was fixed by rebuilding htaccess, then doing Quick Repair and Rebuild; then clearing Browser history
=========
Studio "Popup" FATAL Error was fix to modules/ModuleBuilder/parsers/views/PopupMetaDataParser.php
line 210
 $this->implementation->getHistory()->append($file);
=========
Thanks for the rapid response AND Thanks for 7.10
