### ISSUE TITLE
7.8.15 - "Failed to retrieve data" error in studio

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#5267]
#### Issue

When i edit some modules layout field name in studio, there is an error which is "Failed to retrieve data".
![screenshot_1](https://user-images.githubusercontent.com/22373035/36410405-e778bf96-1621-11e8-8349-e42dfd35d143.png)

#### Steps to Reproduce

1. Open Admin > Studio
2. Select layout edit for any module
3. Edit some field name
4. See result

#### Your Environment

* SuiteCRM Version used: 7.8.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by e-reeley** [comment]
Hi @dursuntosun 

Thanks for raising this issue, I'm just making a pr for this. 

Thanks again.

**Comment by dursuntosun** [comment]
Thanks. it is working good now :)

**Comment by e-reeley** [comment]
Glad to hear, no problem!

Thanks for raising the issue!
