### ISSUE TITLE
Sales Funnel Feature

### ISSUE THREAD

**Issue by dipenpatel235** [salesagility/SuiteCRM#5274]
Sales funnel is main required chart feature for sales.
Here i have attached example of sales funnel also so may be you get idea. this screen shot taken from another crm.
![sales_funel](https://user-images.githubusercontent.com/8135097/36423008-496e307c-1664-11e8-9818-9b7f64c8e5ff.PNG)

#### Issue
not get idea about sales team
#### Expected Behavior
by watching sales funnel get idea about sales achievement and how far from target

#### Actual Behavior
not available sales funnel graph type
#### Possible Fix
need to implement graph type

#### Context

- not getting idea about sales performance

-High

#### Your Environment
* SuiteCRM Version used : 7.9
* Environment name and version : Mysql ,Php 7
* Operating System and version : centos 7 64 bit

**Comment by horus68** [comment]
In the home screen you can add a dashlet / Chart with pipeline chart... only its a bar chart!
Also requested here: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/10399-my-pipeline-not-showing-funnel

![pipelinechart](https://user-images.githubusercontent.com/3055443/36424836-a9ce1518-163c-11e8-953a-685e4d7d7d22.png)

Related: There is this video to create a report using funnel report
https://www.youtube.com/watch?v=KbubAo6tc8U

**Comment by dipenpatel235** [comment]
yes that is there but just not funnel view related only...
funnel view is better for check result.

yes i have also read it was before but not now somehow removed..

so can u give me that patch so i can add that funnel view ?

Thanks

**Comment by horus68** [comment]
I can't help you. 
Related: There are also this PR to implement 2 additional charts but it was now closed without beeing merged https://github.com/salesagility/SuiteCRM/pull/3552

**Comment by dipenpatel235** [comment]
ok...then i am waiting for merge if any one do that
thanks

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sales Funnel Feature](https://trello.com/c/dPu249l5/251-sales-funnel-feature)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by horus68** [comment]
I don't think this is should be tagged as a suggestion. It was a chart type available before, then removed (or just changed into a bar chart)

**Comment by samueltoniello** [comment]
Why do they remove something thats so basic for sales bussines? Is there any plugin or something to resolve this? No one?
