### ISSUE TITLE
7.8.15 - my open case dashlet view icon not pointing to case module

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#5278]
#### Issue

in home "my open case dashlet"  when i click on the eye logo to see the case it sends me to a blank page. 

the link is: 
https://crm.mydomain.com/index.php?action=DetailView&module=Users&record=ab8d8f2a-8c35-0245-c843-5a4bfd517ea3&offset=1&stamp=1519141293032446900&return_module=Home

The module in the link must be cases.
https://crm.mydomain.com/index.php?action=DetailView&module=Cases&record=ab8d8f2a-8c35-0245-c843-5a4bfd517ea3&offset=1&stamp=1519141293032446900&return_module=Home

after several tests it appears that the link module is equal to the last displayed column  of the dashlet. if it is "case status" the link is good, but if it is assigned user the link will point to user module. if the last column is "account name" then the link module is account.

#### Expected Behavior

the link module must be always cases no matter of last column.

#### Steps to Reproduce

1. create a my open case dashlet
2. add account name on last column
3. click the eye logo to see the detailview of the case
4.

#### Your Environment

* SuiteCRM Version used:7.8.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):7
* Operating System and version (e.g Ubuntu 16.04):ubuntu 16.04

**Comment by boombata** [comment]
include\Dashlets\DashletGenericDisplay.tpl line 196 to be changed from 

                <a title='{$viewLinkString}' href='index.php?action=DetailView&module={$params.module|default:$pageData.bean.moduleDir}&record={$rowData[$params.parent_id]|default:$rowData.ID}&offset={$pageData.offsets.current+$smarty.foreach.rowIteration.iteration}&stamp={$pageData.stamp}&return_module=Home&return_action=index' title="{sugar_translate label="LBL_VIEW_INLINE"}">{sugar_getimage name="view_inline.png" attr='border="0" ' alt="$alt_view"}</a>
	
to

                <a title='{$viewLinkString}' href='index.php?action=DetailView&module={$pageData.bean.moduleDir}&record={$rowData[$params.parent_id]|default:$rowData.ID}&offset={$pageData.offsets.current+$smarty.foreach.rowIteration.iteration}&stamp={$pageData.stamp}&return_module=Home&return_action=index' title="{sugar_translate label="LBL_VIEW_INLINE"}">{sugar_getimage name="view_inline.png" attr='border="0" ' alt="$alt_view"}</a>

not sure if it can have a side effect to other dashlets , i can send a PR.

**Comment by boombata** [comment]
https://github.com/salesagility/SuiteCRM/pull/5320

**Comment by Dillon-Brown** [comment]
#5605
