### ISSUE TITLE
7.10: doesn't remember subpanel open/close status

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#5280]
#### Issue

SuiteCRM 7.10 no longer remembers Subpanel open/close status.
See also 
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/17814-suite-p-does-it-remember-whether-subpanels-are-open-or-closed#60168

#### Expected Behavior

User opens a record of any module e.g. Contacts (DetailView). All Subpanels are closed.
User opens first two subpanels.
User loads another record of same module, e.g. Contacts (DetailsView)
User sees first two subpanels open upon loading the page.

#### Actual Behavior

User opens a record of any module e.g. Contacts (DetailView). All Subpanels are closed.
User opens first two subpanels.
User loads another record of same module, e.g. Contacts (DetailsView). All Subpanels are closed.

#### Possible Fix

Dunno. I see no messages in Browser Console or suitecrm.log.

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 64.0.3282.167 (Official Build) (64-bit) for Mac OS
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP
* Operating System and version (e.g Ubuntu 16.04): Mac OS (same behavior on live Demo)

**Comment by gunnicom** [comment]
Is this related, or duplicate?
https://github.com/salesagility/SuiteCRM/pull/3573
https://github.com/salesagility/SuiteCRM/issues/2767
