### ISSUE TITLE
Can't change theme style (7.10)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5281]
#### Issue
Can't change theme style if default language is NOT English.

#### Expected Behavior
Style combobox is visible in user profile.

#### Actual Behavior
Style combobox is NOT visible in user profile.

#### Steps to Reproduce

1. Install some langpack, tested with [Russian](https://github.com/likhobory/SuiteCRM7RU) and [Portuguese](https://crowdin.com/project/suitecrmtranslations/pt-PT#) languages
2. Go to admin panel and change default language in Locale 
3. Try to change theme style in user profile

#### Your Environment

* SuiteCRM Version used: 7.10.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF (latest) and MS Edge
* Environment name and version (e.g. MySQL, PHP 7): MySQl 5.5.59,  PHP 5.5.9-1ubuntu4.22
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by horus68** [comment]
@likhobory been there... see this PR https://github.com/salesagility/SuiteCRM/issues/5175

**Comment by likhobory** [comment]
@horus68  I saw it, but  this issue appeared **after** that PR has been merged into master branch. 
I think this is another issue: in this case, you might use english language, but **change** the default language to another one and this is enough for the issue appearance.

![default](https://user-images.githubusercontent.com/5983672/36446767-660c273c-1693-11e8-8845-8d6c9eca59b4.png)

Can you confirm it?

**Comment by horus68** [comment]
Its working fine for me (PHP7) - double check if the changed file in your system is the same as the online version
![templates](https://user-images.githubusercontent.com/3055443/36451520-38352b92-1689-11e8-9a0d-8d52e7821093.png)

**Comment by likhobory** [comment]
The same result after QRR.
@horus68 Please **change you default language** in Admin->Locale to Portuguese and check result in Layout Options.

![default](https://user-images.githubusercontent.com/5983672/36468475-642db2e4-16db-11e8-9e6c-56e2ac62474f.png)

**Comment by horus68** [comment]
Confirmed! If you change the default language (not just login with that language) the menu to change 

To reproduce:
Note: you can use english language to login and test!
1- Install a language pack
2- Go to Admin / Locale
3- Set default language to the installed language in 1
![select_tempaltes_1](https://user-images.githubusercontent.com/3055443/36473929-f106665e-16ed-11e8-94e8-2c5be43fc003.png)
4- Go to Administrator menu / Profile/ / Layout options
the templates menu is gone!
![select_tempaltes_2](https://user-images.githubusercontent.com/3055443/36474031-32dc9b16-16ee-11e8-9e41-b3b7b5b24922.png)

@PedroErnst @Dillon-Brown its a bug!

**Comment by PedroErnst** [comment]
I'm on it
