### ISSUE TITLE
SuiteP dusk theme button background color

### ISSUE THREAD

**Issue by noelhunter** [salesagility/SuiteCRM#5283]
#### Issue

The background color of the navbar buttons is set to color-28, which provides almost no contrast.  

#### Expected Behavior

background color should provide enough contrast for a person with normal vision to see the buttons

#### Actual Behavior

buttons are white on off white
#### Possible Fix

color-4 would background the buttons with the same color as used in the menus

#### Steps to Reproduce

1. Set theme to suitep
2. under profile, layout, choose Dusk
3. view the navigation bar buttons for home, profile, etc, see that they are white images on off-white background
4.

#### Context

Cannot roll out this theme without manually changing css

#### Your Environment

* SuiteCRM Version used:
7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Version 64.0.3282.167 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
apache, mysql 7, php 7
* Operating System and version (e.g Ubuntu 16.04):

Ubuntu 16.04

**Comment by daniel-samson** [comment]
FYI - am working on this issue in my pr #5273

**Comment by Mausino** [comment]
@Dillon-Brown if this issue was solved in your pull request #5273 from March 2018 and merged into hotfix. 

Should be closed as solved ? I looked on dusk theme and i think this problem in't apear in 7.10.11

**Comment by Dillon-Brown** [comment]
@Mausino Yes, I think this one is resolved. Thanks!
