### ISSUE TITLE
Module Builder menu - undefined labels

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5284]
#### Issue

Module Builder menu shows undefined labels (for Help / Packages). 
Using english language / version 7.10.0.
See details in pics below.

#### Expected Behavior

Ok - Module builder - Softaculus demo - Version 7.9.12
![modulebuilder_softaculus](https://user-images.githubusercontent.com/3055443/36452504-c563a3e2-168c-11e8-8041-e905a7b1df14.png)

#### Actual Behavior

Undefined labels - Module builder - (english language) - version 7.10.0
![modulebuilder_local](https://user-images.githubusercontent.com/3055443/36452497-bed495a4-168c-11e8-912f-1f6f448799f6.png)

#### Steps to Reproduce

1. Admin menu
2. Module Builder

#### Context

Bug, low

#### Your Environment

* SuiteCRM Version used: version 7.10.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): apache 2.4.18 / PHP Version 7.0.11 / mysql 5.7.17
* Operating System and version (e.g Ubuntu 16.04): Windows 10 - 32 bit - local Wamp

**Comment by likhobory** [comment]
Can't confirm, tested with En/Ru/Pt langpacks on FF, Chrome and IE/Win7.

![default](https://user-images.githubusercontent.com/5983672/36469618-b9511406-16df-11e8-88ed-60b9007b00fd.png)

•SuiteCRM Version used: 7.10.0
•Environment name and version (e.g. MySQL, PHP 7): MySQl 5.5.59, PHP 5.5.9-1ubuntu4.22
•Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by horus68** [comment]
I hate this kind of errors!
I can't understand a system built in a way that allows so many problems with language files!

**Comment by horus68** [comment]
Fixed after several repairs:
- Rebuild .htaccess File (even if mine is not a linux system)
- Rebuild Javascript Languages
- Rebuild JS Compressed Files
- Rebuild Minified JS Files
- Quick Repair and Rebuild (to end up in glory!)
(this happened on an instance upgraded from 7.9 to 7.10
