### ISSUE TITLE
Empty help message when creating user

### ISSUE THREAD

**Issue by Pawes** [salesagility/SuiteCRM#5286]
#### Issue
When creating a user and clicking the exclamation mark next to "Module Menu Filters" an empty help message is displayed:
![emptyhelp](https://user-images.githubusercontent.com/15903729/36468295-23618c10-16e3-11e8-9edf-93bb76d15dfe.png)

#### Expected Behavior
Provide the user with a description of what this function does.

#### Actual Behavior
Shows an empty help box.

#### Steps to Reproduce
1. Click create user
2. Click Layout Options
3. Click the exclamation mark next to the text "Module Menu Filters"

#### Your Environment

* SuiteCRM Version used: 7.10

**Comment by horus68** [comment]
Confirmed. Also happens in Own Profile Edit (same help icon)
![2018-02-21 11_06_22-inicio](https://user-images.githubusercontent.com/3055443/36477046-be78004e-16f7-11e8-875e-90a01f676ac4.png)

**Comment by ChangezKhan** [comment]
@horus68, may I know what should be the help text?
