### ISSUE TITLE
Profile Edit - Large empty space

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5289]
#### Issue

There is a large empty space in Profile Edit / Advanced tab. Is there a reason for this?

#### Actual Behavior

See pic:
![blankspace_profile](https://user-images.githubusercontent.com/3055443/36476716-92bfd752-16f6-11e8-9134-da141ae88ef6.png)

#### Steps to Reproduce

1. Edit User profile
2. Advanced tab

#### Your Environment

* SuiteCRM Version used: 7.10.0 (local) and 7.9.12 (softaculus demo)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome

**Comment by Kevconry** [comment]
was able to replicate in 7.13.1

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
