### ISSUE TITLE
opencart so page builder error, can not save changes. i got error as Notice: A non well formed numeric value encountered in 

### ISSUE THREAD

**Issue by Weroxweb** [salesagility/SuiteCRM#5292]
#### Issue
opencart so page builder error, can not save changes.
 i got error as Notice: A non well formed numeric value encountered in admin/view/template/extension/module/so_page_builder/shortcodes-func.php

**Comment by PedroErnst** [comment]
Hello @Weroxweb 

Thanks for reporting this.
For us to be able to help we need a few more details.
It would be great if you could fill out **all** of the fields in the github issue template.

Thank you!

**Comment by PedroErnst** [comment]
Also, the file you mentioned does not exist in this repository.

If you are using 3rd party plugins you should provide all details about those as well.

**Comment by yasser4ever1** [comment]
Hello, i am facing the same problem i wish anyone help please it's urgent and i am unable to downgrade to php 7.0 to bypass this problem and now i can't make any updates

Notice: A non well formed numeric value encountered in /admin/view/template/extension/module/so_page_builder/shortcodes-func.php on line 187Warning: Cannot modify header information - headers already sent by (output started at /admin/controller/startup/error.php:34) in /system/library/response.php on line 36
