### ISSUE TITLE
swagger.json getting error - needs to be updated

### ISSUE THREAD

**Issue by dipenpatel235** [salesagility/SuiteCRM#5304]
not able to generate php client using swagger.json file getting error

#### Issue
Errors
Hide
Schema error should NOT have additional properties
additionalProperty: components
Jump to line 0
Schema error at swagger
should be equal to one of the allowed values
allowedValues: 2.0
Jump to line 1
Schema error at paths['/api/v8/modules/viewed'].get.responses['200']
should NOT have additional properties
additionalProperty: description, headers
Jump to line 18
Parser error bad indentation of a mapping entry
Jump to line 19
Schema error at paths['/api/v8/modules/viewed'].get.responses['200'].headers
should be object
Jump to line 21
Schema error at paths['/api/v8/modules/favorite'].get
should have required property 'responses'
missingProperty: responses
Jump to line 24
Schema error at paths['/api/v8/modules/meta/list'].get.responses['200']
should NOT have additional properties
additionalProperty: description, headers
Jump to line 32
Schema error at paths['/api/v8/modules/meta/list'].get.responses['200'].headers
should be object
Jump to line 35
Schema error at paths['/api/v8/modules/meta/menu/modules'].get
should have required property 'responses'
missingProperty: responses
Jump to line 38
Schema error at paths['/api/v8/modules/meta/menu/filters'].get
should have required property 'responses'
missingProperty: responses
Jump to line 42
Schema error at paths['/api/v8/modules/{module}'].get.responses
should NOT have less than 1 properties
limit: 1
Jump to line 48
Schema error at paths['/api/v8/modules/{module}'].get.responses
should NOT be valid
Jump to line 48
Schema error at paths['/api/v8/modules/{module}'].post.responses
should NOT have less than 1 properties
limit: 1
Jump to line 52
Schema error at paths['/api/v8/modules/{module}'].post.responses
should NOT be valid
Jump to line 52
Schema error at paths['/api/v8/modules/{module}/viewed'].get.responses
should NOT have less than 1 properties
limit: 1
Jump to line 57
Schema error at paths['/api/v8/modules/{module}/viewed'].get.responses
should NOT be valid
Jump to line 57
Schema error at paths['/api/v8/modules/{module}/favorites'].get.responses
should NOT have less than 1 properties
limit: 1
Jump to line 62
Schema error at paths['/api/v8/modules/{module}/favorites'].get.responses
should NOT be valid
Jump to line 62
Schema error at paths['/api/v8/modules/{modules}/meta/language'].get.responses['200']
should NOT have additional properties
additionalProperty: description, headers
Jump to line 69
Schema error at paths['/api/v8/modules/{modules}/meta/language'].get.responses['200'].headers
should be object
Jump to line 72
Schema error at paths['/api/v8/modules/{modules}/meta/attributes'].get
should have required property 'responses'
missingProperty: responses
Jump to line 75
Schema error at paths['/api/v8/modules/{modules}/meta/menu'].get
should have required property 'responses'
missingProperty: responses
Jump to line 79
Schema error at paths['/api/v8/modules/{modules}/meta/view'].get
should have required property 'responses'
missingProperty: responses
Jump to line 83
Schema error at paths['/api/v8/modules/{modules}/{id}'].get
should have required property 'responses'
missingProperty: responses
Jump to line 87
Schema error at paths['/api/v8/modules/{modules}/{id}/relationships/{link}'].get
should have required property 'responses'
missingProperty: responses
Jump to line 91
Schema error at securityDefinitions['suitecrm_api_auth']
should have required property 'tokenUrl'
missingProperty: tokenUrl
Jump to line 95
Schema error at securityDefinitions['suitecrm_api_auth'].type
should be equal to one of the allowed values
allowedValues: basic, apiKey
Jump to line 96
Schema error at securityDefinitions['suitecrm_api_auth'].flow
should be string
Jump to line 97
Schema error at securityDefinitions['suitecrm_api_auth'].flow
should be equal to one of the allowed values
allowedValues: implicit, password, application, accessCode
Jump to line 97
#### Expected Behavior

when swagger.json file content paste on swagger editor so it must able to generate php client.

#### Actual Behavior
getting above error thats why not able to generate php client
#### Possible Fix
don't know

#### Steps to Reproduce
1. copy swagger.json content from lib/API/v8/swagger.json file to https://editor.swagger.io
2. then u get error right side

#### Context

yes. because i am not able to generate client for rest api to sync contact from 3rd party

High

#### Your Environment

* SuiteCRM Version used:7.10.0
* Environment name and version : MySQL, PHP 7
* Operating System and version : Centos 7

**Comment by PedroErnst** [comment]
@dipenpatel235 

Currently https://editor.swagger.io does not support swagger 3.0, only 2.0

I think they're working on this.

**Comment by PedroErnst** [comment]
@dipenpatel235 

Here are the [OpenAPI 3.0 specifications](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)

**Comment by dipenpatel235** [comment]
Yes I know it is based on openapi 3.

But see in json file mention swagger3.0
So swagger 3.0 is not supported version.

So my intence is how you have tested by using that file and generated
client code ?

Thanks

**Comment by PedroErnst** [comment]
I don't know what you mean by Swagger 3.0 not being a supported version? 

It's not supported by that one site that you mentioned.

Here is an official list of tools OpenAPI 3.0 compliant tools:

https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md

**Comment by dipenpatel235** [comment]
See here in attached screenshot i have open swagger.json file and look  red
highlighted .

That swagger 3.0 is no one editor supporting.

Let me know if you have now cleared or not.

Thanks

**Comment by daniel-samson** [comment]
During the development of the REST API, i used a json schema to swagger converter. I did use any particular editor. The trouble with swagger is that it doesn't support some of the features in the JSON Schema.

This is something we will need to look into.

**Comment by Dillon-Brown** [comment]
Closed as irrelevant for v8.0 now with V8
