### ISSUE TITLE
Activities summary in unsorted order

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#5305]
#### Issue

Viewing the activities summary shows the history in the wrong order. 

#### Expected Behavior

Should be chronologically by date descending.

#### Actual Behavior

It is effectivly in database order.

#### Possible Fix

In file include/utils.php function array_csort() around line 1870

replace:
    `$arrayMultiSortParameters[] = $argsShifted;`
with
    `$arrayMultiSortParameters[] = &$argsShifted;`

 The list is actually sorted but the result is never propagated out of the function.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.15

**Comment by PedroErnst** [comment]
Seems to be ordering the Tasks in Activities by Due Date. I guess this is good?

![image](https://user-images.githubusercontent.com/34056696/37960479-a948d65a-31ad-11e8-90df-e0944b352adf.png)

**Comment by pgorod** [comment]
I wonder if this issue is a duplicate, maybe already fixed somewhere else. I remember seeing this before, though I can't find it now...

**Comment by nelem** [comment]
Does it also sort Calls and Emails chronologically?

**Comment by nelem** [comment]
Does it also sort Emails and Calls chronologically?

**Comment by nelem** [comment]
This is still a problem in 7.8.27. The suggested fix still works. The arrays need to be passed by reference to array_multisort() but the indirect call though call_user_func_array() hides that. 

This is noticed in Emails when they are imported out of sequence. The line is 1785 in 7.8.27.

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
