### ISSUE TITLE
System email templates unable to Save content

### ISSUE THREAD

**Issue by dl3737** [salesagility/SuiteCRM#5306]
#### Issue:  I create a new email template.
After saving everything is lost.
Even if I edit an existing email template, the content will disappear
recently I tried "Forgot Password email", but unfortunately I get this message: "No email template is selected for the email containing the password that will be sent to the user. Please select an email template in the Password Management page. "
I have "Forgot Password email" in my email templates and also in database. it's all right

![new-template](https://user-images.githubusercontent.com/19924265/36504799-fedf608c-1751-11e8-8831-7791d5e57521.jpg)
![result-after-save](https://user-images.githubusercontent.com/19924265/36504813-0527a80a-1752-11e8-9e34-4921fc0e1a1c.jpg)
![db-result-after-save](https://user-images.githubusercontent.com/19924265/36504826-0dfbcc68-1752-11e8-974b-beb28c4b82ec.jpg)

#### Your Environment

* SuiteCRM Version used:7.9.14
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

![pv](https://user-images.githubusercontent.com/19924265/36504384-9e8bc73a-1750-11e8-888b-381493a2d653.jpg)
![pv-](https://user-images.githubusercontent.com/19924265/36504388-a4594caa-1750-11e8-877a-e88a6d0765fa.jpg)
![pv-db](https://user-images.githubusercontent.com/19924265/36504391-a99a6690-1750-11e8-9ce8-9f403fa8d342.jpg)

**Comment by Dillon-Brown** [comment]
@dl3737 Have you checked permissions and done repair + rebuild? I can't seem to replicate on 7.9.x.

**Comment by dl3737** [comment]
Hello Dillon,
Actually, it has started with e-mail templates.
When I create a new template and click Save, all text and images are deleted and a blank page saved. also Email templates after the change will not be saved.
I changed all 3 editor (mozaik, tinymce, etc?) Options,but with all the same problem.
I also tried with PHP 5.6 or 7 and 7.2.
I've changed some permissions to 775 but I'm not sure if I changed the right folders or files

thank you


![bild1](https://user-images.githubusercontent.com/19924265/36550934-c4ce80b2-17f6-11e8-8879-e8bb9c3aa527.jpg)
![bild2](https://user-images.githubusercontent.com/19924265/36550941-c7fcc334-17f6-11e8-8c3f-a817e397b483.jpg)
![new-template](https://user-images.githubusercontent.com/19924265/36551063-07c688f6-17f7-11e8-9143-93b8800b7a55.jpg)
![result-after-save](https://user-images.githubusercontent.com/19924265/36551071-0b12c646-17f7-11e8-8793-e557bb32f9bf.jpg)

**Comment by samus-aran** [comment]
Hi @dl3737 Do you have any fatal errors with this on your server logs or SuiteCRM logs?

**Comment by dl3737** [comment]
I have now submitted an email template and sent by mail to reconstruct the errors. hier ist die error file log:

Mon Feb 26 21:45:29 2018 [25656][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:34 2018 [26152][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:36 2018 [26275][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:47 2018 [26882][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:47 2018 [26893][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:50 2018 [26882][1][ERROR] Unable to find relationship emails_email_templates
Mon Feb 26 21:45:50 2018 [26882][1][FATAL] Email delivery FAILURE:Array
(
    [date_entered] => 2018-02-26 20:42:09
    [date_modified] => 
    [user_id] => 1
    [id] => 418
    [campaign_id] => 7e9cfa08-7e15-041e-bba6-5a89ad9cb6b6
    [marketing_id] => 81cfafe5-d913-bccf-df64-5a9470e016a7
    [list_id] => f18deea6-a01b-d24f-22e5-5a83fe9b509e
    [send_date_time] => 2018-02-26 10:00:00
    [modified_user_id] => 
    [in_queue] => 0
    [in_queue_date] => 
    [send_attempts] => 0
    [deleted] => 0
    [related_id] => 53f74c7a-b2bc-0879-4f95-5a83fd6f2fad
    [related_type] => Accounts
)

Mon Feb 26 21:45:51 2018 [27063][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:52 2018 [27063][1][FATAL] Slow Query (time:0.48458099365234
SELECT * FROM fields_meta_data WHERE  custom_module='EmailMan' AND  deleted = 0)
Mon Feb 26 21:45:56 2018 [27201][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:45:58 2018 [27255][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:46:02 2018 [27500][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!
Mon Feb 26 21:46:15 2018 [28095][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Paris. Please set date.timezone="Europe/Paris" in php.ini!

**Comment by dl3737** [comment]
Hier ist the server log
![log](https://user-images.githubusercontent.com/19924265/36695309-38cc0596-1b41-11e8-9540-3aa066187f03.jpg)

**Comment by Mausino** [comment]
@dl3737 are you using SecuritySuite extension 3rd extension ?

**Comment by dl3737** [comment]
I do not think so but I'm not sure. I use chrome as a browse with default setting.

thank you

**Comment by dl3737** [comment]
Hi,
as information for you:
I can create, save and send the PDF templates. absolutely no problem

Thank you

**Comment by pgorod** [comment]
@dl3737 do you still have this problem? 

If you specify a template **type**, instead of leaving it as **`None`**, does it fix the problem?

**Comment by Kevconry** [comment]
wasnt able to replicate in 7.13.1
after editing an email template then saving and going back to the edit view of the template, the view is saved
please re-raise or get in touch if you are still having this issue
