### ISSUE TITLE
Notification alert dialogue keeps poping up even after repetated ok clicks

### ISSUE THREAD

**Issue by vladimirpekez** [salesagility/SuiteCRM#5308]
#### Issue

Notification alert dialogue keeps poping up even after repetated ok clicks.

#### Expected Behavior

Notification browser alert dialogue should be closed if clicked ok.

#### Actual Behavior

Notification alert dialogue keeps poping up even after repetated ok clicks.

#### Steps to Reproduce

1. Schedule call or meeting
2. Wait for given set time, browser alert popup will appear
3. Click ok to close alert popup, popup will close but another will appear
4. Step 3 will be repeated many times

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

SuiteCRM Version 7.9.12 (upgraded from 7.9.2)

**Comment by vladimirpekez** [comment]
[https://ibb.co/cw0Bkx](url)

**Comment by vladimirpekez** [comment]
[https://preview.ibb.co/i6NP5x/Capture.png](url)

**Comment by Dillon-Brown** [comment]
@vladimirpekez I'm fairly sure this has already been fixed. What version of SuiteCRM are you running?

**Comment by vladimirpekez** [comment]
Hi Dillon

Instance is upgraded to 7.9.12 and this behavior is reproduced on 7.9.12.

Vladimir

**Comment by Admoneo** [comment]
I am using 7.10.2 and Chrome and still the same behavior.

**Comment by vladimirpekez** [comment]
@Admoneo - thanks for bug reproduction confirmation - I hope @Dillon-Brown and SuiteCRM guys will fix it soon.

**Comment by Kevconry** [comment]
Wasnt able to replicate in 7.13.1
After scheduling a call and receiving the notification, the browser notification only appears once 
if you are still having this issue, please re-raise or get in touch
