### ISSUE TITLE
Data fields: Tab order and Z cross in detail or edit views

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5310]
#### Issue

There must be an order for data fields in detail and edit views so it feels comfortable to read the fields content by "regular" desktop browser users with 2 columns layout but also for those using tabs to move into fields (as in screen readers used by blind and vision impaired people).
Fields are usually
- left to right and a Z cross (two columns)
- there can be also areas grouping related fields in two columns.

Both cases require to be tested in single column layouts (as in mobile).

In SuiteCRM there isn't a proper fields layout as sometimes fields are apart each other even if they look grouped. So this needs to be fixed.

#### Expected Behavior

The main point is: the related info needs to be next to each other, as in
- first name / last name 
- phone 1 / phone 2 / phone 3 /
- IM type / IM name

#### Actual Behavior

Using SuiteP on 7.10.0 screens for examples:

**Profile screen:**
First and last name needs to be in the same line. Now the status info is in the middle (tab order)!
![fields_profile1](https://user-images.githubusercontent.com/3055443/36534172-aea90c32-17bd-11e8-8636-855e93118919.png)

In the second form (employee info) fields are Z cross but phones are only in right column. So it is actually ordered as Work phone / Department / Mobile / Reports to / Other phone. IM and address are ok.
![fields_profile2](https://user-images.githubusercontent.com/3055443/36534196-c2a19b96-17bd-11e8-9d5f-f3aab3b74f9f.png)

**Employee screen**
First name / last name is OK but "Title / Department / Reports to" needs to be in sequence, not in the same column. 
Phones are mixed up, mostly on the right column but Home phone is on the left. IM and address are ok.
![fields_employee](https://user-images.githubusercontent.com/3055443/36534500-9c6b362a-17be-11e8-969b-b73791a74611.png)
Note: If you want to group related fields it must be done in a different way! 
Even if this looks visually ok for you in a desktop, try it in a single column format (see below in the context topic)

**Contacts screen**
Primary address and other Address are correctly placed in groups, tab order is ok (it moves top/bottom  in a group then into the other group).
No issues here... **the pic its just to praise the work well done**! That's the way to group fields and to have a proper tab order.
![fields_contacts](https://user-images.githubusercontent.com/3055443/36534467-880f8fe6-17be-11e8-8b12-c26e50296165.png)

#### Possible Fix

Reorder layout fields in template views (edit and detail).
Please verify layouts in 1 column (its a mess!)

#### Context

Bug low for mobile and Screen reader accessibility.
Even when it looks ok for your setup, always test in a single column view. 
See profile screens with error caused by fields not placed in proper order: (screen reader will read something like "First name John / Status Active / Last name Doe" when the proper order should be 
"First name John / Last name Doe"
![fields_profile1_singlecol](https://user-images.githubusercontent.com/3055443/36533572-d9eb91c8-17bb-11e8-8a49-183fcc088891.png)

![fields_profile2_singlecol](https://user-images.githubusercontent.com/3055443/36533578-de6ff770-17bb-11e8-835c-f3a3f045e30e.png)

#### Your Environment

* SuiteCRM Version used: 7.10.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome

**Comment by Kevconry** [comment]
was able to replicate in 7.13.1

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
