### ISSUE TITLE
No CASE number when receiving inbound emails for new Cases

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#5315]
#### Issue
When trying to retrieve the case record a new bean is created instead of retrieving that one that already exists which removes the case number which is assigned in the db I believe. The issue it caused me was not being able to reply to case created emails to update a case.  

#### Expected Behavior
When sending case created emails the outbound email is sent with case number eg: CaseSubject [CASE:7835]

#### Actual Behavior
Email is sent but has no case number eg: CaseSubject [CASE: ]

#### Possible Fix

At line 2800 in modules/InboundEmail/InboundEmail.php & line 106 in modules/InboundEmail/AOPInboundEmail.php

            $c->save(true);
            $caseId = $c->id;
            $c = new aCase();
            $c->retrieve($caseId);
            if($c->load_relationship('emails')) {
                $c->emails->add($email->id);
            }
to 
            $c->save(true);
            $c->retrieve($c->id);
            if($c->load_relationship('emails')) {
                $c->emails->add($email->id);
            }

#### Steps to Reproduce

1. Set up email template that uses the case number
2. Set up to send email on case creation
3. Make case
4. Check history subpanel for emails sent

#### Context

 low/medium priority

#### Your Environment

* SuiteCRM Version used: 7.8.8
* Browser name and version: Chrome Version 64.0.3282.140
* Environment name and version: MYSQL PHP 7
* Operating System and version: Ubuntu 16.04

**Comment by PedroErnst** [comment]
@JackBuchanan 

Thanks for reporting this issue. It should be fixed in the next release.

**Comment by mattlorimer** [comment]
@JackBuchanan where is your fix??
