### ISSUE TITLE
Reports sort by formatted date rather than actual date

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#5317]
#### Issue

If your report includes a date column as the date is formatted in the report, then the report data sorts by the user's formatted date. E.g. in the UK, I get
01/01/17
01/01/18
02/01/17, etc.

#### Expected Behavior

The report should sort by the actual date.
01/01/17
02/01/17
01/01/18, etc.

#### Actual Behavior

It sorts by formatted date.

#### Possible Fix

In AOR_Reports line 1235
replace
```
                        if ($field->sort_by != '') {
                                $query['sort_by'][] = $select_field . " " . $field->sort_by;
                        }

```with
```
				if ($field->sort_by != '') {
					// If the field is a date, sort by the natural date and not the user-formatted date
					if ($data['type']=='date' || $data['type']=='datetime')
					{
						if ((isset($data['source']) && $data['source'] == 'custom_fields')) {
							$date_field = $this->db->quoteIdentifier($table_alias . '_cstm') . '.' . $field->field;
						} else {
							$date_field = $this->db->quoteIdentifier($table_alias) . '.' . $field->field;
						}
						$query['sort_by'][] = $date_field . " " . $field->sort_by;
					}
					else
					{
						$query['sort_by'][] = $select_field . " " . $field->sort_by;
					}
				}

```
#### Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug include code to reproduce, if relevant -->
1. Create a report showing a date
2. Format that date to non-ISO format
3. Select sort by the date
4. View the report

#### Context
<!--- How has this bug affected you? What were you trying to accomplish? -->
<!--- If you feel this should be a low/medium/high priority then please state so -->

#### Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* SuiteCRM Version used: 7.8.15

**Comment by PedroErnst** [comment]
Hello @nelem 

Thanks for reporting this.

I'm trying to reproduce this with the Birthdate field on Contacts module (date type field).
It's working as it should for me.

![screenshot from 2018-02-26 11-22-07](https://user-images.githubusercontent.com/34056696/36667871-4e2f7ecc-1ae7-11e8-95a7-c2ad3ffaa16d.png)

Can you provide a few details about your environment, maybe screenshots, and most importantly your SuiteCRM version?

**Comment by nelem** [comment]
Hi @PedroErnst SuiteCRM was/is 7.8.15. You do need to format the field using one of the localized formats to get the stringy sorting. Thanks for doing the PR. :-) Will this PR make it into the 7.8.x LTS branch, too?
I notice the way you have avoided checking for custom fields again.

**Comment by PedroErnst** [comment]
Yes this should end up in the LTS branch.
