### ISSUE TITLE
7.10 Studio Layout Cannot Change Panel Names

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5319]
#### Issue

Final 7.10 does not support changing the Panel Name. Also, the Collapse Button does not exist for Add New Panel. Adding/Changing new  Fields works OK. 
#### Steps to Reproduce

1.Use Studio Layout to add new panel.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: Final 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): Mariah DB, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Apache2

**Comment by goingsmart** [comment]
UPDATE:

Issue is only RENAME PANEL
Collapse Button shows up after DEPLOY

**Comment by goingsmart** [comment]
UPDATE2

I have done RENAME with 7.10 RC2 Clicking on the "Pencil" in the Panel Name Box, but now the "Pencil" looks faded and Click does not work using the general area of the "Pencil"

**Comment by goingsmart** [comment]
UPDATE3
The Field names cannot be changed as well as the Panel Names.  There is an unattached Collapse Button  in middle on right side that floats with the slider.

**Comment by e-reeley** [comment]
Hi @goingsmart 

Sorry for the late response, I believe that I made a PR previously that fixes this issue. It just hasn't been merged yet.

Please could you try [#5271](https://github.com/salesagility/SuiteCRM/pull/5271) and let us know how you get on?

Thanks for raising this issue.

**Comment by edmondklai** [comment]
It was functional on 7.10-RC2 and I confirmed that the same bug exists on 7.10.  Applying #5271 fixes the issues, please merge for the next release.

**Comment by e-reeley** [comment]
Hi @edmondklai 

Thank you for confirming this. We will look to merge this fix.

Thanks again.

**Comment by goingsmart** [comment]
FIX WORKS, THX
