### ISSUE TITLE
[suggestion] Request for Russian SuiteCRM Forum

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5324]
See #5169

@pgorod 
Can you add another 3 categories suggested by @horus68:
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/11486-request-for-russian-suitecrm-forum?limitstart=0#39337
If you agree, I'ill translate them into Russian.

**Comment by pgorod** [comment]
@likhobory this started from a suggestion horus68 made via email. However I have plans to take the Community to a better place, with modern Forum software with tons of great features. That's a big project, it won't happen tomorrow, but it's the next thing I'll be focusing on after the new Documentation site.

So I don't want to work on the current Forums now, I think they are heading for extinction if my new project goes well. I am not a fan of multiplying Forums, and currently I think there are too many, needlessly.

I had this discussion about the Russian forum internally and we decided on using a single Forum for Russian, initially. If in a few months the new project isn't operational, or if your Forum is too confusing with too much activity, we can add more Forums then.

I hope you don't mind.

**Comment by likhobory** [comment]
@horus68,  special thanks !!
@pgorod 
OK.
But is it possible to divide this topic into several, it contains many different questions:
https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/59

**Comment by pgorod** [comment]
Do you want to try dividing it?

After all, **you are the moderator** there, right? 👑 

(congratulations on your new role)

(and many thanks for your continued help and valuable contribution)

**Comment by likhobory** [comment]
ok, thank you for your trust, Il try to do that..

Please replace this forum comment

> Use this forum for any issue related to SuiteCRM that you want to discuss in Russian. 

with this one

> Пока что все вопросы, касаемые SuiteCRM, собираем здесь.

**Comment by likhobory** [comment]
> Do you want to try dividing it?

Done.
But there is a small forum bug with topics/replies quantity:

![default](https://user-images.githubusercontent.com/5983672/36616936-a854f780-18f6-11e8-89d4-d28831019754.png)

**Comment by pgorod** [comment]
That bug seems solved, maybe it only recalculates the sums every once in a while.

Thanks for all the hard work dividing the thread, the Russian forum is starting to look good!

**Comment by likhobory** [comment]
Thanks, works as expected.

**Comment by varianceinfotech** [comment]
SuiteCRM Dynamic Panels New Functionality

We are exited to announce two new functionalities of Dynamic Panels which are
Add multiple records for single module.
Dynamic Panels effect trigger based on user type and their role
Add multiple records for single module

Now you can add multiple records for single module.
You can have look at this image : Multiple Records for single module. https://prnt.sc/l99z5e

Dynamic Panels effect trigger based on user type and their role
You can now manage Dynamic Panels Hide/Show depending on User Type and their Roles.
If login user's type and roles matched with configuration of dynamic panels then only you can able to see effect of Dynamic panels.
You can have look at this image: Dynamic Panels effect based on user type and thier role. https://prnt.sc/l9a07z
You can have a look at this link for more information click here https://www.varianceinfotech.com/suitecrm-powerpanels-fields.html
You can buy it from Here : Dynamic Panels https://store.suitecrm.com/addons/dynamic-panels

**Comment by pgorod** [comment]
@varianceinfotech what does this have to do this issue??? Please delete your comment, and don't post any publicity stuff here on Github. You can do it on the Forums, as long as it is relevant to the post, and you don't do it too much.
