### ISSUE TITLE
Should custom/**/ really be in .gitignore?

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5326]
In [this commit](https://github.com/salesagility/SuiteCRM/commit/dc8996600c73fb174c68e68a3144e54b549d44a3#diff-a084b794bc0759e7a6b77810e01874f2) we added this to `.gitignore`:

`custom/**/`

In the forums a user [complains](https://suitecrm.com/suitecrm/forum/developer-help/17903-all-new-custom-files-being-ignored-by-git).

I'm not sure of the implications of this, because I guess it depends on people's workflows on their own forked repos, but I guess it wouldn't hurt to leave this out so that customizations can naturally be worked with there, without any further changes to `.gitignore`.

So I just ask - why was this inserted, and does it really need to be there?

Maybe this was just an accidentally committed change.

Version: SuiteCRM 7.10

**Comment by mattlorimer** [comment]
We don't accept custom overrides into the main project, if you are doing a custom project, you would use a different gitignore. This gitignore is purely for core SuiteCRM development, so it is a valid addition
