### ISSUE TITLE
SuiteCRM 7.10 - Subject broken in Notes detail view

### ISSUE THREAD

**Issue by dvaldes** [salesagility/SuiteCRM#5327]
#### Issue
Notes Module

In list view, all **notes** subject lines are seen and link to the detail of the note. When in the detail of the note, the subject does not appear. This happens when viewing all notes or when notes are linked to other modules.

If a new subject is typed in the subject line of the detail screen it will override the original subject in the list view, but still does not appear in the detail screen.

This appears to be a bug since the condition also exists on the SuiteCRM online demo as well as my own installation.

#### Expected Behavior
The subject should appear in both list view and detail view.

#### Your Environment
* SuiteCRM Version 7.10
* Chrome and Firefox

Screen shot below is from the demo site:

![notesexample](https://user-images.githubusercontent.com/36819118/36643593-a228061a-1a1b-11e8-9828-1dc3c0aa78a9.png)

**Comment by samus-aran** [comment]
Thank you for raising this and we will look at this for the upcoming releases.

**Comment by e-reeley** [comment]
Hi @dvaldes 

Thanks for raising this issue, I have linked this issue in a PR which should solve this.

Thanks again.

**Comment by pgorod** [comment]
Just a note: this affects other modules as well. So any recent complaints about missing subject fields in several modules should benefit from this fix. Thanks
