### ISSUE TITLE
Google Map GeoCoding is not working with proxy server

### ISSUE THREAD

**Issue by anhnhatuit** [salesagility/SuiteCRM#5328]
#### Issue
When I enabled for my proxy server then google geocoding is not working...

#### Expected Behavior
Need support working when user update Proxy server configuration in Admin > System Settings > Proxy

#### Your Environment

* SuiteCRM Version used: 7.8.8, 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Fix here #5331
