### ISSUE TITLE
7.10 Studio Undefined

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#5329]
#### Issue
Use Studio to edit a form (detail view or edit view, probably others).
Undefined displayed in many places.

#### Expected Behavior
Should have text as usual

#### Actual Behavior
Undefined displays on screen, also undefined in popup after you save it.

#### Steps to Reproduce
1. Upgraded from 7.9.x to 7.10
2. Studio - Accounts - detail view or edit view
3.
4.

#### Context
I could still udpate form but it was annoying

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by e-reeley** [comment]
Hi @davidyounger 

Thank you for raising this issue.

Just as test would you be able to rebuild the htaccess file found in the admin panel.

After this, try a repair and rebuild and reset the browser cache. 

Then hopefully this should repair the undefined labels.

Please let us know how you get on.

Thanks.

**Comment by davidyounger** [comment]
Thank you.
That fixed the problem.
Cheers
David Younger
Founder
[https://docs.google.com/uc?export=download&id=0BxFGhxL-9ealTWxwT2Z2R3BHaEk&revid=0BxFGhxL-9ealQVY0RzR2VnF6T0tZdDJpUlRYZTNGSTN0SEdRPQ]

| t. +61 2 9690 3888
| e. david@<mailto:david@>theservicemanager.com<http://theservicemanager.com/>
| w. www.<http://www.ramprfid.com/>theservicemanager.com<http://theservicemanager.com/>
| a. Suite 2a, 199 Regent St, Redfern, NSW 2016




This e-mail message and any attachments contain information that is confidential and may be subject to legal privilege. If you are not the intended recipient, you must not peruse, use, pass on or copy this message or any attachments. If you have received this e-mail in error, please notify us by return e-mail and erase all copies of this message including any attachments. Thank you.

**Comment by e-reeley** [comment]
That's great to hear! 

Thank you for raising this with us!

Thanks again, Ellis.
