### ISSUE TITLE
Encoding issue with umlauts on email update in case

### ISSUE THREAD

**Issue by mugge6** [salesagility/SuiteCRM#5339]
#### Issue
If I send an email from outlook with umlauts to create or update a case, then the encoding of the text is wrong.

#### Expected Behavior
Encoding should be right.

#### Actual Behavior
Currently it looks like:
![grafik](https://user-images.githubusercontent.com/16953779/36682201-c8e87406-1b1a-11e8-99a3-66a2f49a8a6b.png)

#### Possible Fix
Looks like the issue starts with the commit:
https://github.com/salesagility/SuiteCRM/commit/34236b845dbb8347d3c8118effb8e1837c692710 

After calling parseDescription() in modules/AOP_Case_Updates/AOP_Case_Updates.php (Line 117 ff.) the description text is HTML decoded and it will be saved into the DB. The issues is caused within the DOM manipulation inside the parseDescription function.
```
public function save($check_notify = false)
    {
        $this->name = SugarCleaner::cleanHtml($this->name);
        $this->parseDescription();
        parent::save($check_notify);
```
If I replace `$this->parseDescription();` with `$this->description = SugarCleaner::cleanHtml($this->description);` everything works fine.

#### Steps to Reproduce
1. Send an email with umlauts to the SuiteCRM inbox to create a new case
2. Go to the new created case
3. Check case updates for correct encoding

#### Context
Has to be fixed, otherwise the case updates are wrong encoded.

#### Your Environment
* SuiteCRM Version used: 7.9.14
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1

**Comment by sanchezfauste** [comment]
I have the same issue. The fix works fine for me.
