### ISSUE TITLE
Suggestion - Case update: preview of email before sent to contact

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5340]
We are suggesting add some function to case module, like checkbox where user can choose if want after save of case update to confirm preview of email before it will send. In this pop up window will possible change e.g. Subject, body, template, or email addresses.

The reason is simply... we which are using other language as English in our communication (Slovak, German, Czech) and still using checkbox "Internal" because we want send to our customer email in slovak or other language..  i posted ticket for case template for more languages #472 before few years

and will great if we will have possibility to fix or add some text to emails before will send to contact or add/send to more contacts (accounts/contacts/leads/targets)

 User which wan't to preview email, let unchecked checkbox..

@likhobory @horus68 is other possibility to send email to client in other languages from case if you has clients from more countries ???

**Comment by horus68** [comment]
Can't help as I'm not using email with SuiteCRM system
(Reason: emails must be only in a single email server and can't be replicated)

**Comment by likhobory** [comment]
We also use an external Email clients.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion - Case update: preview of email before sent to contact](https://trello.com/c/wH7tUmxO/249-suggestion-case-update-preview-of-email-before-sent-to-contact)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
