### ISSUE TITLE
Studio Panel Name Edit Buttons Do Not Work

### ISSUE THREAD

**Issue by AdrianoABC** [salesagility/SuiteCRM#5342]
#### Issue
When you access studio for layout customization, when you insert a new panel and edit its name, the change (pencil) button does not work, preventing you from changing the panel name. The same happens with the fields, preventing changes of their names directly in "layout".
Note: I am currently using a custom theme with a pt_BR translation package, but I also encounter the same problem with the original theme and en_US.

#### Expected Behavior
 Execute change the name of the panels and fields within the layout in studio. 

#### Steps to Reproduce

1. Go to Studio (any module);
2. Enter layout and click "Edit" or "Detail";
3. Try changing the name of some field through the pencil;
4. Please add a new panel and try changing its name.

#### Your Environment
* SuiteCRM 7.10:
* Chrome and Firefox (64-bit)):
* MySQL 5.6, PHP 7:

Screen shot:

![do not work](https://user-images.githubusercontent.com/36868034/36713123-bc97a154-1b6a-11e8-8dac-bec0ebcd6aee.jpg)

**Comment by Mausino** [comment]
@AdrianoABC this issue is persisting in earlier versions like 7.9.x or 7.8.x

**Comment by pgorod** [comment]
Sorry, but I guess this is a duplicate of #5267

But then the good news is that there is already a fix! #5271

**Comment by AdrianoABC** [comment]
Perfect.I had not found this solution before, thank you, really #5271  works.
