### ISSUE TITLE
Mismatch between Security Groups and Security Suite names in Administration

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5343]
#### Issue

 On image you can see the mismatch between Security Groups and Security Suite in Administration

![2018-02-27_1121](https://user-images.githubusercontent.com/5773777/36726622-c1291522-1bba-11e8-98f9-f9541be47d5e.png)

@horus68 is this original translation issue/mistake ?

#### Your Environment

* SuiteCRM Version used: 7.9.14 https://www.softaculous.com/demos/SuiteCRM
* Browser name and version: Chrome 64.x

**Comment by horus68** [comment]
I'm not involved with english language but it looks Security Suite its the original module name. Maybe it was renamed to Security Groups? There is also a _Security Suite Group Management_
The term _Security Suite Settings_ is from modules/Administration/language/en_us.lang.php
```
    'LBL_MANAGE_SECURITYGROUPS_TITLE' => 'Security Suite Group Management',
    'LBL_MANAGE_SECURITYGROUPS' => 'Security Suite Group Editor',
    'LBL_CONFIG_SECURITYGROUPS_TITLE' => 'Security Suite Settings',
    'LBL_CONFIG_SECURITYGROUPS' => 'Configure Security Suite settings such as group inheritance, additive security, etc',

```
https://github.com/salesagility/SuiteCRM/blob/c6bece6ab3acd29365f5fc663ba8f3cc359a986b/modules/Administration/language/en_us.lang.php#L880-L883


Security Groups Management is present in several other files as in _LBL_SECURITYGROUPS_SUBPANEL_TITLE_
_

**Comment by Mausino** [comment]
@horus68 thank you
@Dillon-Brown @samus-aran  what is right.. Security Groups or Security Suite  ???

i discussed about it with @pgorod in forum https://goo.gl/QJCHkY

**Comment by eggsurplus** [comment]
Sorry for the confusion here. SecuritySuite should be the overall solution of which Security Groups are a part of. Changing it to SecuritySuite Settings in the title seems to be the best path forward.

**Comment by horus68** [comment]
@Dillon-Brown for a merge?
