### ISSUE TITLE
Campaign Wizard Marketing Tab: Name values entered are ignored 

### ISSUE THREAD

**Issue by ZenSysAdmin** [salesagility/SuiteCRM#5348]
#### Issue
When I travel through the campaign wizard and end up on the marketing tab where I enter values for "from name", "from address", "reply-to-name" etc., then go to the next tab (summary) and finally jump back to the marketing tab all the values I typed in before are replaced by some kind of default values. For example the value for item "From Name"  is set to system while the value I typed in before was a valid last and first name.
#### Expected Behavior
The values which were typed in before should still be there when navigating back to the marketing tab.

#### Actual Behavior
The values are obviously replaced by some default values.

#### Steps to Reproduce
See attached 
[github-SuiteCRM-CampaignWizzardIssue.pdf](https://github.com/salesagility/SuiteCRM/files/1763255/github-SuiteCRM-CampaignWizzardIssue.pdf)

#### Context
While setting up a test campaign in the new SuiteCRM Version.

#### Your Environment
* SuiteCRM Version used: 7.10
* Browser name and version: Firefox 58.0.2 (64-bit) ; Microsoft Edge 41.16299.248.0
* Environment name and version: Apache/2.4.29 (Unix) PHP/7.2.2
* Operating System and version: Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64

**Comment by Bud985** [comment]
Hi, concerning this issue we are experiencing this problem: in the marketing tab we select our rebounds account to handle possible rebounds and we specify different names and email addresses in the fields "From to" and "Reply to". When sending the email however, these settings are not applied and the same email address is used for the rebounds, the "From to" and the "Reply to" fields.

We are using the latest stable release v7.9.15.

**Comment by boombata** [comment]
same issue here with 7.8.15

**Comment by boombata** [comment]
This is due to this case  #4479
and this  https://github.com/salesagility/SuiteCRM/pull/4641

looks like it is now forced to use the outbound from / reply to avoid web server rejecting from not matching address. that is problematic for my sales that want to send campaigns with the email addresses.

**Comment by boombata** [comment]
updated my previous comment with a possible workaround

**Comment by boombata** [comment]
Tested and it works. I would say that this is the way it works now. 

1- select the bounce account (this is the reply to address) 
2- select outbound account (this is the from adress
if your user needs to us their account as from address, they must go to collaboration -> emails -> settings -> and add his outgoing smtp server setting
they will be able to select their account as from address. 

Will send a PR later to make those field read only to avoid confusion.

**Comment by Bud985** [comment]
The situation is even worst with the last update (v7.9.16).
Now also the selection of an existing email template is not working anymore (I will open a separate incident for this).
However, please consider to fix the "From to" and "Reply to" problem with a high priority. Campaigns are an essential tool of every CRM software and if they do not work correctly the entire software loses a lot of its potential.

**Comment by pgorod** [comment]
Note that while #4479 stated that `From` and `From name` fields need to exist so they can properly match the account, it is still useful for many people to be able to use different values when sending a campaign, even if they _don't_ match the account. 

If you use your own SMTP server you can be more permissive than Gmail :-) and sometimes different Campaigns prefer to send with different sender details.

So @boombata this is why those fields shouldn't be hidden in the Campaign screens - you should be able to override your account settings.

Of course, if you put in values and they are used incorrectly, then that is a bug :-(

**Comment by dursuntosun** [comment]
My version is 7.8.18 LTS, i m waiting for solution for this. I m changing this fields on database. But not good solution.

**Comment by Kevconry** [comment]
Wasn't able to replicate in 7.13.1
After entering details in the marketing section, then pressing next, then navigating back to marketing, the information is not changed
If you are still having this issue, please re-raise or get in touch
