### ISSUE TITLE
UTF8 Characters are not displayed correctly after upgrade to 7.10

### ISSUE THREAD

**Issue by sm4x** [salesagility/SuiteCRM#5358]
#### Issue
After upgrading from 7.9.14 to 7.10, UTF8 characters like "ö,ü,ä,ß" are not saved and displayed correctly anymore. This affects this affects all fields in tables contacts, users etc.

#### Expected Behavior
Characters should be saved correctly

#### Actual Behavior
In the mentioned tables entries like "Krüger" will become "KrÃ¼ger"

#### Possible Fix
Strings can be fixed directly on database level and are displayed correctly afterwards.
UPDATE `DB3279832`.`users` SET `first_name` = 'Jörg', `last_name` = 'Krüger' WHERE `users`.`id` = '2a835bb9-6776-25d4-f019-5a953062611c';

I followed https://github.com/salesagility/SuiteCRM/issues/3192 and patched MysqlManager and MySQLiManager accordingly before reinstall, but problem persists.

#### Steps to Reproduce

1. Installed a new instance of 7.9.14 - works
2. Dropped database on server
3. Installed a new instance of 7.10 - characters are saved incorrectly

#### Context
Priority: medium

#### Your Environment

* SuiteCRM Version used: 7.10 
* Browser name and version: Chrome and Firefox, several versions
* Environment name and version
    * Server: rdbms via TCP/IP
    * Server type: MySQL
    * Server version: 5.6.37-log - Source distribution Protocol version: 10
    * Server charset: UTF-8 Unicode (utf8)
    * Server connection collation: utf8mb4
* Webserver
    * Apache/2.4.29 (Unix)
    * Database client version: libmysql - 5.5.52
    * PHP extension: mysqli
* PHP
    * PHP Version 7.2.1

**Comment by Dillon-Brown** [comment]
@sm4x Is this still an issue for you on 7.10.1? I'm unable to replicate locally or on the [demo.](https://demo.suiteondemand.com) All the fields in contacts and users seem to be displaying correctly.

**Comment by sm4x** [comment]
@Dillon-Brown My guess is this has to do with the server connection collation, which is utf8mb4. I am not experiencing this behavior on other instances.

**Comment by VWT4** [comment]
Hello, I have exactly the same issue to report. Since 7.10 there is a problem with the charset when saving new data containing German digits (ä, ü, ö, ß etc.). I always have to correct them directly in the database. In 7.9.14 everything works fine without this problem. It is the same database.
