### ISSUE TITLE
Language keys - Cut down on sugar in your diet - part II

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5360]
#### Issue

Strings, with almost a single usage, that should be edit to remove the Sugar term from the key part:
```
LBL_SUGAR_FIELDS_STAGE
LBL_SUGAR_SCHEDULER_TITLE
LBL_SUGAR_SCHEDULER
LBL_SUGAR_UPDATE_TITLE
LBL_SUGARFEED_SETTINGS
LBL_SUGARFEED_SETTINGS_DESC
LBL_SUGARPORTAL
LBL_SUGAR_DOCUMENT
LBL_SUGAR_LOGIN
LBL_EC_SUGARFEEDS
LBL_OOTB_SUGARFEEDS
LBL_TRIMSUGARFEEDS
LBL_VIEW_SUGAR_FIELDS
LBL_EMAIL_SUGAR_FOLDER
LBL_DBCONF_SUGAR_DB_USER
LBL_SITECFG_SUGAR_UP_DIRECTIONS
LBL_SITECFG_SUGAR_UP
LBL_DIAGNOSTIC_GETSUGARLOG
LBL_DIAGNOSTIC_SUGARLOG
LBL_QR_CBOX_CLEARSUGARFEEDCACHE
LBL_QR_CLEARSUGARFEEDCACHE
ML_SUGAR_KB
ML_SUGAR_DZ
SUGARPDF_BASIC_SETTINGS
SUGARPDF_ADVANCED_SETTINGS
SUGARPDF_LOGO_SETTINGS
SUGARPDF_BASIC_SETTINGS
SUGARPDF_ADVANCED_SETTINGS
SUGARPDF_LOGO_SETTINGS
LBL_DASHLET_SUGAR_NEWS
LBL_DASHLET_DISCOVER_SUGAR_PRO
LBL_SITECFG_SUGAR_UP_DIRECTIONS
LBL_SITECFG_SUGAR_UP
LBL_SITECFG_SUGAR_UPDATES
LBL_EMAIL_ARCHIVE_TO_SUGAR
LBL_EMAIL_SUGAR_FOLDER
```
And some arrays on the include file
```
'SugarFeed' => 'SuiteCRM Feed',
'SugarFavorites' => 'SuiteCRM Favorites',
'Sugar' => 'SuiteCRM',       
'sugar' => 'SuiteCRM Email Client',
'Sugar' => 'SuiteCRM',

```
Note: the values on the strings are ok, just the key part needs a fix!

#### Context

You need to eat with your own FORK. :)  Related to the "Cut down on sugar in your diet" https://github.com/salesagility/SuiteCRM/issues/5160

#### Your Environment

* SuiteCRM Version used: Hotfix

**Comment by likhobory** [comment]
> SUGARPDF_BASIC_SETTINGS
> SUGARPDF_ADVANCED_SETTINGS
> SUGARPDF_LOGO_SETTINGS
> SUGARPDF_BASIC_SETTINGS
> SUGARPDF_ADVANCED_SETTINGS
> SUGARPDF_LOGO_SETTINGS

Advanced PDF Settings been used in SugarCRM PRO and do not used neither in Sugar CE nor in Suite.
Are all these labels and SugarpdfSettings.tpl  file are really needed or can be removed?
See #2468
https://github.com/salesagility/SuiteCRM/blob/v7.7.4/modules/Configurator/language/en_us.lang.php#L224-L413

**Comment by samus-aran** [comment]
Hi @horus68 @likhobory. Thats it merged into hotfix. Have a wee gander at the nightly.suiteondemand.com instance if you see anything obviously wrong with removing these references :)
