### ISSUE TITLE
[docs] Wrong information in the documentation (Upgrading SuiteCRM)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5384]
https://docs.suitecrm.com/admin/installation-guide/3.upgrading/

Quote1 from the first paragraph:
> There is currently no silent upgrade path available for SuiteCRM.

Quote2 from the upgrade considerations:
> Use the Silent Upgrade method through the command line interface...

**Comment by pgorod** [comment]
Thanks @likhobory. Can you please open this issue in the Documentation bug tracker instead?

https://github.com/salesagility/SuiteDocs/issues

... and close this one here? Thanks!

**Comment by likhobory** [comment]
ok, see https://github.com/salesagility/SuiteDocs/issues/37
