### ISSUE TITLE
My Filters doesn`t show up on Project Tasks

### ISSUE THREAD

**Issue by artjomsmorscakovs** [salesagility/SuiteCRM#5392]
#### Issue
When I make a filter on Project Tasks and then want to save it, My Filters doesn`t show up

#### Expected Behavior
My Filters must appear

#### Actual Behavior
My Filters select doesn`t show up

#### Steps to Reproduce
1. Go To Projects module and then click Project Tasks
2. Filter using any field (e.g. Assigned to)
3. Save filter as Name (name it the way you like)
4. My Filters doesn`t show up

#### Context
Unable to save filters in Project Tasks
The same is reproducable in https://demo.suiteondemand.com
#### Your Environment

* SuiteCRM Version used: Version 7.9.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 62.0.3202.75 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL: 5.5.56-2.el7, php: 5.4.16-42.el7
* Operating System and version (e.g Ubuntu 16.04): ‪CentOS Linux 7.4.1708 (Core)‬

**Comment by pstevens71** [comment]
Thank you!!! This one has been bugging me for years!  I just applied the fix and confirm it works!
