### ISSUE TITLE
mail_smtppass too small

### ISSUE THREAD

**Issue by herrt** [salesagility/SuiteCRM#5396]
#### Issue
mail_smtppass is defined to be 100 chars long. If you enter a longer password SuiteCRM renders a blank page.

#### Expected Behavior
Present an error message.

#### Possible Fix
a) Check password length before submitting form
b) Enable longer passwords

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS (Looks like mail_smtppass has been changed to 255 chars). Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
