### ISSUE TITLE
Print as PDF not working

### ISSUE THREAD

**Issue by maarisk** [salesagility/SuiteCRM#5399]
Invoice Print as PDF is not bringing up PDF template selection as well as does not produce PDF for download on SuiteCRM version 7.10.1

#### Issue

1. Open prepared invoice
2. From Actions select Print as PDF

#### Expected Behavior
PDF template selection is shown

#### Actual Behavior
PDF template selection is not shown

#### Steps to Reproduce
1. Open prepared invoice
2. Select Actions -> Print as PDF

#### Context
Cannot send PDF invoices to customers

#### Your Environment

* SuiteCRM Version used: 7.10.1 (upgraded from 7.9.10 -> 7.10 beta 2 -> 7.10 final -> 7.10.1)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 11.0.3 (13604.5.6)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1, MySQL 5.7.19
* Operating System and version (e.g Ubuntu 16.04): macOS High Sierra 10.13.3

**Comment by Dillon-Brown** [comment]
@maarisk I'm unable to replicate on 7.10.1. Are you getting any errors in the logs/console?

**Comment by maarisk** [comment]
There are no errors in suitecrm.log on the server, but Safari gives this javascript error:

[Error] ReferenceError: Can't find variable: showPopup
	onclick (Script Element 10:1)

**Comment by ApatheticCosmos** [comment]
Try repairing your JS from the Admin>Repair menu. I had an issue with conditions in reports not working that was fixed by that. It was giving me a JS error in console as well.
https://github.com/salesagility/SuiteCRM/issues/5419

**Comment by maarisk** [comment]
Repair of JS files as well as restart of the browser helped. Not development bug.

**Comment by ApatheticCosmos** [comment]
It is, however, most likely an upgrade bug. I'm not sure how the devs want to handle that.
