### ISSUE TITLE
Background image in PDF

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#54]
Background image in mPDF doesn't show when the PDF is printed/generated.

**Comment by recci** [comment]
There are two problems here, first generatePdf.php does not convert &#039; (apostrophes) which is needed when using background-image. But even after solving that issue the mPDF generator class still does no parse the background-image like: background-image: url('themes/Suite7/images/blur-background09.jpg')

**Comment by darthtang** [comment]
What is mPDF?

**Comment by JimMackin** [comment]
mPDF is the library that the PDF Templates in SuiteCRM uses: http://www.mpdf1.com/mpdf/index.php

**Comment by darthtang** [comment]
cheers!  Didn't do a Google search ....AGAIN..as per!

**Comment by EZS-JD** [comment]
I could really use this.

**Comment by darthtang** [comment]
http://mpdf1.com/manual/index.php?tid=384 some light reading if you are interested

**Comment by darthtang** [comment]
http://stackoverflow.com/questions/20828776/mpdf-full-page-background also

**Comment by EZS-JD** [comment]
I managed a workaround with position absolute and negative z-index value. But I might have another look... thanks for this.

**Comment by darthtang** [comment]
No problem!

**Comment by paulgodley** [comment]
I have added the following html surrounding the template body and this issue appears to have been resolved:
`<div style="height: 2475px; width: 3525px; padding: 9px; background: url('include/images/1.gif');">
...body of template...
</div>`

**Comment by JimMackin** [comment]
Marking as resolved. If this still causes issues please let us know.
