### ISSUE TITLE
7.10.1 Undefined Studio Labels

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5400]
#### Issue

1) Studio shows "Undefined" in some Labels 
2) Home Page shoes  "Base Implementation Error" messages pertaining to missing HTML associated with missing Email Addresses metadata.
These conditions also existed for 7.10

#### Expected Behavior

Proper Labels should display
#### Possible Fix

Rebuild new HTACCESS, Quick Repair and Rebuild and clearing Browser does not fix problem. 
#### Steps to Reproduce

1. Open Home Page for "Base Implementation Error"
2. Go to Studio for "Undefined"
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariahDB, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS7 64-bit

**Comment by e-reeley** [comment]
Hi @goingsmart 

Thank you for raising the issue, for the Base Implementation Error, are you referring to the field displayed in the side bar?

Thanks again.

**Comment by goingsmart** [comment]
Correct, the Base Implementation Error shows in the left rail (left side bar).

Also, the "undefined" shows in many places (not just Studio.

**Comment by Dillon-Brown** [comment]
@goingsmart The "Base Implemetation" issue should be resolved with #5411. However the "undefined" issue should already be resolved in 7.10.1. Did you use the 7.10.1 installer or one of the upgrade packs?

**Comment by goingsmart** [comment]
used upgrade from 7.10 to 7.10.1.

Since I'm not in production with this instance can wait to use upgrade from 7.10.1 to 7.10.2

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
