### ISSUE TITLE
REST Api v8: Empty Related Fields in Record List

### ISSUE THREAD

**Issue by eagarao** [salesagility/SuiteCRM#5405]
When retrieving list of records via **/api/v8/modules/<module_name>**, related fields are empty.
i.e.: 
When calling /api/v8/modules/Opportunities, account_name and account_id fields are empty.

#### Issue
When retrieving list of records via **/api/v8/modules/<module_name>**, related fields are empty. 

#### Expected Behavior
Upon calling record list endpoint, related fields should also be retrieved.

#### Actual Behavior
Related fields are empty when calling record list endpoint.

#### Possible Fix
Update /lib/API/v8/Library/ModulesLib.php. In **generatePaginatedModuleRecords** method, add **$moduleBean->fill_in_additional_detail_fields()** inside the **foreach ($moduleList['list'] as $moduleBean)**

#### Steps to Reproduce
1. Call api **/api/v8/modules/Opportunities**
2. Check related fields like account_name and account_id.

#### Context
Related fields should also be returned on the record list api endpoint.
This could be in medium priority since it sin't critical.

#### Your Environment
* SuiteCRM Version used: v10.0
* Browser name and version: Google Chrome - Version 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version: PHP 5.5.38, Mysql 5.5
* Operating System and version: CentOS 6.5

**Comment by daniel-samson** [comment]
The v8 API is defined by the JSON API specification. The related fields must be passed via the relationships object, inside the data object.

Please refer to this example:
http://jsonapi.org/format/1.0/#crud-updating-resource-relationships

**Comment by eagarao** [comment]
Hi @daniel-samson ,

Yes, there's a route for retrieving related records. What I'm referring here are the fields that gets their values from the **fill_in_additional_detail_fields()** method. In the old API version, the **get_entries** endpoint, records retrieved are looped to retrieved individual additional bean data. On this new api, fetching of additional data is not included.

Regards!

**Comment by samus-aran** [comment]
duplicate ticket of https://github.com/salesagility/SuiteCRM/issues/7094
v8 is deprecated but we will apply the fix for V8
