### ISSUE TITLE
My Contracts - Dashlet can not be sorted (ascending to descending)

### ISSUE THREAD

**Issue by MTet** [salesagility/SuiteCRM#5406]
#### Issue
If I want to sort my contracts within the my contracts dashlet by name ascending, I click at the "name" --> this works.
If I click at the "name" again, nothing changes, no descending order.
The bug is also at the online-demo.

#### Expected Behavior
If I click on a column-header of the "my contracts" dashlet, it should change sort order from ascending to descending, and back if I click again.

#### Actual Behavior
Only sort ascending.

#### Possible Fix

It should work like the other dashlets.

#### Steps to Reproduce

1. Add the "My Contracts"-Dashlet.
2. Have >1 Contracts shown.
3. Click on a header-column...sort order will change to ascending.
4. Click on the header-column again...sort order will not change to descending.

#### Context

Our sales-team want to check the contracts with different sort orders to see where an action is required.

#### Your Environment

* SuiteCRM demo and our local instance

**Comment by e-reeley** [comment]
Hi @MTet 

Thank you for raising this issue.

I was looking on version 7.10.2 and I cannot replicate this issue.

Which version were you testing this on? If it was a previous version to 7.10.2 then this issue may be resolved.

Thanks again.

**Comment by Dillon-Brown** [comment]
@e-reeley Try with contracts dashlet in the demo: https://demo.suiteondemand.com/index.php?module=Home&action=index

**Comment by e-reeley** [comment]
Ah, comparing the demo site with mine I noticed something.

I can reproduce the error if the dashlet is on the CRM Dashboard, but on a created tab it seems to work okay.

Thanks!
