### ISSUE TITLE
SuiteP- Filter popup window on listview for mobiles/tablets - can't search or close it

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5409]
#### Issue

The issue is simply... The pop up window on listview is not adjustable to screen... you are not able to see second part of pop up window where is Search button or Close icon.

![2018-03-06_1138](https://user-images.githubusercontent.com/5773777/37028080-8c0aedd8-2133-11e8-8981-57adcbe8688c.png)

#### Expected Behavior

User should be available to search or filter on mobile or tablets

#### Steps to Reproduce

1. Open the suitecrm on mobile/tablet (or resize the browser window)
2. Go to listview
3. Push filter icon
4. Try to close this pop up window or search something

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.9.14 Official demo
* Browser name and version : Chrome 64.x

**Comment by Mausino** [comment]
@pgorod did you find some complaining on it in forum? because i did not :(

**Comment by pgorod** [comment]
No, this is the first time I'm seeing this.

**Comment by Mausino** [comment]
@Dillon-Brown we will test it again and let you more info.. we are fighting now with official demo.. can't login there as in posted ticket by me #5437

Soon let you know our test results :)

**Comment by Mausino** [comment]
Thanks for your help guys 👍 it was an issue in our instance
