### ISSUE TITLE
Tasks dashboard module not show Related To

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#5415]
#### Issue
On Dashboard, module Tasks doesn't show the Related to field on some rows.

The first row, show the related to without problems. But second rows and others, show only a space (&nbsp;) and the link to the account or module assigned to the task, and not the name.

#### Expected Behavior
Name of the related to field should be show correctly on all rows.

* SuiteCRM Version used: 7.10.1

**Comment by Dillon-Brown** [comment]
Duplicate of #5330
