### ISSUE TITLE
Some emails break page layout

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#5416]
#### Issue
Some emails break HTML layout of the page, and doesn't show the "send" button and others.
The original email are sent from CRM version 7.9.11. Apparently, 

#### Expected Behavior
![imagen](https://user-images.githubusercontent.com/8928758/37041322-3fc454ae-215c-11e8-9fc7-813658c4dd19.png)
Email HTML code should not affect the layout of the page.

#### Actual Behavior
![imagen](https://user-images.githubusercontent.com/8928758/37041256-115dee90-215c-11e8-8171-f948f73cc471.png)
HTML from email broke layout of page, and lower menu does not appear.
Problem are on <input> tag, "value" field. These field are enclosed on apostrophes, and other apostrophes inside the email content are not escaped or deleted. This break the page layout.

![imagen](https://user-images.githubusercontent.com/8928758/37042336-8479983c-215e-11e8-9030-f735e3a3bfee.png)
On this image, can see the <input> tag, marked as red (because are broken html)

![imagen](https://user-images.githubusercontent.com/8928758/37042379-9b9496a2-215e-11e8-805f-e9354e2ef6cd.png)
On this another image, you can see the apostrophe who are creating the problem.

#### Steps to Reproduce
Send a email with a apostrophe on email HTML source.
Try to reply these email.

#### Context
HIGH priority. Email replies cannot be send with this bug.

#### Your Environment
* SuiteCRM Version: 7.9.11 - 7.9.15 - 7.10.1 (Tested on these versions).
* Browser: Verified on Chrome and Firefox.
* Environment name: PHP 7.2.

**Comment by Dillon-Brown** [comment]
Resolved in 7.10.4: #5629
