### ISSUE TITLE
Module jjgw_Maps doesn't show Cluster icons

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#5417]
#### Issue
jjgw module use markercluster addon for unify closer markers. But these module are loading cluster icons from a unavailable location.
﻿Location loading from markercluster addon are: //google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png

Google code doesn't host this project anymore. Now the project are hosted on github: https://github.com/googlemaps/v3-utility-library/tree/master/markerclustererplus

#### Expected Behavior
Icons for clustered markers should be show on map.

#### Possible Fix
Update the library from new upstream, or save icons on the SuiteP theme and load it from them.

#### Your Environment
* SuiteCRM Version: 7.10.1

**Comment by ErMaqui** [comment]
That's duplicated with #5356 and the released fix #5357, but, maybe updating library are a good option and not change only the address of the image.

**Comment by Dillon-Brown** [comment]
Should be fixed here as well #1777. Will need to re-assess before merging.
