### ISSUE TITLE
Report Module - Unable to set any conditions

### ISSUE THREAD

**Issue by ApatheticCosmos** [salesagility/SuiteCRM#5419]
#### Issue

THIS IS AFTER AN UPGRADE FROM 7.8.11 TO 7.10.1
Clicking on fields on add them to Conditions does not have any effect.

#### Expected Behavior

Clicking on fields should add them to Conditions
#### Actual Behavior

No output in log files.
#### Steps to Reproduce

1. Create a report
2. Click on the 'Conditions' tab
3. Click on a field to try to add it to Conditions
4.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version: Chrome 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.0.33-MariaDB, PHP 7.0.25-0ubuntu0.16.04.1
* Operating System and version: Ubuntu 16.04

**Comment by ApatheticCosmos** [comment]
It's impossible to show this as a screenshot, so here's a screencast:
[vokoscreen-2018-03-06_15-33-24.mkv.zip](https://github.com/salesagility/SuiteCRM/files/1786651/vokoscreen-2018-03-06_15-33-24.mkv.zip)

**Comment by Dillon-Brown** [comment]
I can replicate that dragging a field onto conditions does not seem to work but clicking to add is working for me on 7.10.1. Are you able to replicate this issue on the [demo](https://demo.suiteondemand.com/index.php)? user/pass = will

**Comment by vmijalkovic** [comment]
Same here. 7.10
Drag and drop is not working but clicking does..

**Comment by ApatheticCosmos** [comment]
Clicking works on the Demo site, but not on my instance. 
Also, reports set up with conditions before the upgrade do not show their conditions, although they are still used when running the report.
There appears to be a Javascript error when clicking on a field to add a condition. The console prints out:
Uncaught TypeError: Cannot read property 'appendChild' of null
    at insertConditionHeader (conditionLines.js:427)
    at insertConditionLine (conditionLines.js:472)
    at loadConditionLine (conditionLines.js:248)
    at Object.<anonymous> (AOR_Report_Before.js:264)
    at Function.each (sugar_grp1_jquery.js:2)
    at Object.<anonymous> (AOR_Report_Before.js:263)
    at executeItem (sugar_grp1.js:478)
    at Object._doWhenCheck (sugar_grp1.js:478)
    at q (sugar_grp1.js:866)

**Comment by ApatheticCosmos** [comment]
Doing a repair of the JS files has fixed this issue.

**Comment by ApatheticCosmos** [comment]
Perhaps I should not have closed the issue, in case it's a bug in the upgrade process?

**Comment by breeblebrax** [comment]
Version 7.10.2
Sugar Version 6.5.25 (Build 344)

Cannot click on the field or drag and drop it.
Windows - Chrome Version 65.0.3325.181 (Official Build) (64-bit)

I reproduced what the previous user did in the video.  Same behavior.
This is a recent upgrade from 7.9.7 to 7.10.2

I tried JS repair to fix the issue prior to the last test effort.
