### ISSUE TITLE
Emails Module: Inbound Settings Layout, Date Sent and Draft Sending

### ISSUE THREAD

**Issue by eagarao** [salesagility/SuiteCRM#5420]
When sending an email from SuiteCRM, **date_sent** is not being recorded.
When saving the email as **Draft**, there's no option to send the mail.
Broken layout for email settings.

#### Issue
When sending an email from SuiteCRM, **date_sent** is not being recorded.
Saved **Draft** emails, don't have option to for sending.
Broken layout for email settings.

#### Expected Behavior
When an email is sent, **date_sent** is not populated.
When email is saved as **Draft**, there's an option to send it.

#### Actual Behavior
When email is sent, date_sent is empty in DB.
When email is saved as **Draft**, there's no option for sending it.

#### Steps to Reproduce
1. Configure inbound email 
2. Compose and send an email, check record in database, date_sent is empty.
3. Compose an email and save as **Draft**. Open email record, no option to send it.

#### Context
This is High priority. 
Emails module is not working as expected.

#### Your Environment
* SuiteCRM Version used: v7.10.1
* Browser name and version: Google Chrome - Version 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version: PHP 5.5.38, Mysql 5.5
* Operating System and version: CentOS 6.5

**Comment by Dillon-Brown** [comment]
Hi @eagarao.

1. "date_sent". I can replicate.
2. "When email is saved as Draft, there's an option to send it". Click on the email draft to enter the detail-view and then click on "Actions" -> "Send".
3. "Broken layout for email settings". Where were you able to see broken style? this appears correctly for me locally on the [demo](https://demo.suiteondemand.com/index.php). user/pass = will

**Comment by Dillon-Brown** [comment]
Hi @eagarao, I actually don't think this is an issue. When looking at this previously I hadn't realised that the date created field has the functionality you are looking for. This field pulls date sent from the imap server for all emails in every folder.
