### ISSUE TITLE
Incorrect email shown ( multiple view's ) 7.10.1

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#5422]
#### Issue
After upgrading form 7.10 to 7.10.1 there are several issuess realted with email field.

1. In account list view email are shown twice:

![image](https://user-images.githubusercontent.com/30261902/37088173-c5999b98-21fc-11e8-912e-b3362c545fe0.png)

2. When creating relation between account and user email while looking at account -> subpanel for contacts main email form account is shown instead of actuall contact email.

![image](https://user-images.githubusercontent.com/30261902/37088343-508dfb54-21fd-11e8-8d52-a1346fd89680.png)

#### Context
I'm using backup copy of CRM in version 7.9.14, due to many problems which occured after upgrading to 7.10.x I've even set all permission to 777, compared files from 7.10 pure installation with my after upgrade but no effect. Tried on different browers and platforms Windows, Android, MacOS, Firefox, google chrome bu no effect.

In logs i get error's propably not related with issue:

Wed Mar  7 11:48:17 2018 [1472][68d92b56-f55c-b8ac-d3e1-583be9227722][ERROR] fromUser: Conversion of 2018-03-07 10:48:17 from user format d/m/Y H:i failed

Wed Mar  7 11:48:17 2018 [1472][68d92b56-f55c-b8ac-d3e1-583be9227722][ERROR] Unable to load related bean by id

Wed Mar  7 11:34:35 2018 [27444][68d92b56-f55c-b8ac-d3e1-583be9227722][ERROR] fromString: Conversion of 16/01/2018 15:17 from string failed: DateTime::__construct(): Failed to parse time string (16/01/2018 15:17) at position 0 (1): Unexpected character

With enabled error display:
Notice: Array to string conversion occurred in /var/www/crm.fortecait.pl/include/formbase.php on line 209 [2018-03-07 12:02:56] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/formbase.php[L:209](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/formbase.php[L:219](:getGetToForm)
/var/www/crm.fortecait.pl/include/MassUpdate.php[L:94](:getAnyToForm)
/var/www/crm.fortecait.pl/include/ListView/ListViewDisplay.php[L:240](MassUpdate:getDisplayMassUpdateForm)
/var/www/crm.fortecait.pl/include/ListView/ListViewSmarty.php[L:293](ListViewDisplay:display)
/var/www/crm.fortecait.pl/include/MVC/View/views/view.list.php[L:251](ListViewSmarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/views/view.list.php[L:354](ViewList:listViewProcess)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:207](ViewList:display)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Notice: Array to string conversion occurred in /var/www/crm.fortecait.pl/include/formbase.php on line 209 [2018-03-07 12:02:56] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/formbase.php[L:209](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/formbase.php[L:219](:getGetToForm)
/var/www/crm.fortecait.pl/include/MassUpdate.php[L:94](:getAnyToForm)
/var/www/crm.fortecait.pl/include/ListView/ListViewDisplay.php[L:240](MassUpdate:getDisplayMassUpdateForm)
/var/www/crm.fortecait.pl/include/ListView/ListViewSmarty.php[L:293](ListViewDisplay:display)
/var/www/crm.fortecait.pl/include/MVC/View/views/view.list.php[L:251](ListViewSmarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/views/view.list.php[L:354](ViewList:listViewProcess)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:207](ViewList:display)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)

#### Your Environment
* SuiteCRM Version used: 7.10.1 
* Browser name and version (e.g. Chrome 64.0.3282.186 
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version CentOS

**Comment by VWT4** [comment]
Unfortunately, I have to confirm that issue. The same behavior is also evident in my installation. Since the update to 7.10. The update to 7.10.1 did not fix it.

**Comment by AdminPL** [comment]
Are you also having problem with missing action menu on main page and not working ajax ?

**Comment by it7baptiste** [comment]
Hello guys,

I had the same problem,

I've search a bit and finally find a way to fix it quickly,

On modules/Emails/EmailUI.php : 

Line 486 & 487 delete the </a> closure and comment return $emailLink 
Line 551 comment //$emailLink .= '</a>';  

http://prntscr.com/iqvmgn
http://prntscr.com/iqvk49

Looks like there is a confusion with multiple return and close </a> balise in the function,

Not really sure about this fix, but it's working for me and the popup modal to send mail works,

Regards,
B.

**Comment by it7baptiste** [comment]
Hello,

I had the same problem,

On modules/Emails/EmailUI.php line 486,

Original : http://prntscr.com/ir0kvv
Modify : http://prntscr.com/ir0l3i

Looks like there is a problem with the value genereated $myBean->{$emailField} on module leads links only.

Regards,
B.

**Comment by mrbarletta** [comment]
For all of you having the same issue it is due to a listviewdef.php change made a few month ago.

So you have to update your custom/modules/Leads/listviedef.php as shown in the commit:

https://github.com/salesagility/SuiteCRM/commit/57912ad71e0ea44c094581127f1a1dcb4e2bced1#diff-6ed04ad7e04a71b7df46e69d8b20e0ca

Please, don't do what @it7baptiste did, it will remove the HREF for the email.

**Comment by AdminPL** [comment]
Confirmed. 

custom/modules/Accounts/metadata/listviewdefs.php

change line:
'customCode' => '{$EMAIL1_LINK}{$EMAIL1}</a>',

to:
 'customCode' => '{$EMAIL1_LINK}',

**Comment by AdminPL** [comment]
Just to clarify it resolves first problem.  incorrect emails are still shown under account view related with contact.

**Comment by belzebub40k** [comment]
Did you also adjust _custom/modules/Contacts/metadata/listviewdefs.php_?

I adjusted Accounts and Contacts and for the the Emails are correct.

**Comment by AdminPL** [comment]
I did but still emails shown are main email account instead showing contacts actual main email

**Comment by jbrveen** [comment]
Those commits do not work for me. In the Accounts it's giving all the same mail addresses in the Contacts Listview, however, the contacts detailview give the right mailadress. And sometimes at Cases it's not showing a mail address at all. See screenshots. 
<img width="890" alt="screen shot 2018-04-11 at 19 04 03" src="https://user-images.githubusercontent.com/27926713/38634869-1292a81c-3dc4-11e8-922b-989156caa708.png">
<img width="924" alt="screen shot 2018-04-11 at 19 08 48" src="https://user-images.githubusercontent.com/27926713/38634871-12aae09e-3dc4-11e8-960f-5285ff35bed4.png">

**Comment by jbrveen** [comment]
A quick check btw shows that it is indeed showing the mail adress from the Relation instead of the primary mail address from the contact.

**Comment by mrbarletta** [comment]
@jbrveen  - thats issue # 2 which I didn't address, there is another issue open for that.

**Comment by gfeser** [comment]
This bug appeared after upgrade to 7.10.4.
The link has got an additional tag /a in the tail.
`<a href="mailto:an@mail.org">an@mail.org</a>an@mail.org</a>`

**Comment by gfeser** [comment]
pgorod: Yes, it's no bug in this case. Yes, I saw warnings, but did not give them due attention.

**Comment by javitoron** [comment]
@mrbarletta And where can I find that issue?? I'm having the same problem but I can't find a solution... thanks!

**Comment by mrbarletta** [comment]
@javitoron - #5516  I think thats the one
