### ISSUE TITLE
Ajax interface not working on main page / missing add dashlet button

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#5423]
#### Issue
On main page i can't edit view by moving widgets or add dashlet due to lack of add button
Problems started after upgrade form 7.9.14 to 7.10 and still not working on 7.10.1

When i enable error display i only see, but propably not related with this bug.
![image](https://user-images.githubusercontent.com/30261902/37089178-fbd16a58-21ff-11e8-88bb-7b8b92f0d256.png)

Notice: Trying to get property of non-object occurred in /var/www/crm.fortecait.pl/modules/Reminders/Reminder.php on line 326 [2018-03-07 12:04:14] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/Reminders/Reminder.php[L:326](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/javascript/jsAlerts.php[L:56](Reminder:addNotifications)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:223](jsAlerts:__construct)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Notice: Trying to get property of non-object occurred in /var/www/crm.fortecait.pl/modules/Reminders/Reminder.php on line 326 [2018-03-07 12:04:14] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/Reminders/Reminder.php[L:326](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/javascript/jsAlerts.php[L:56](Reminder:addNotifications)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:223](jsAlerts:__construct)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Notice: Trying to get property of non-object occurred in /var/www/crm.fortecait.pl/modules/Reminders/Reminder.php on line 326 [2018-03-07 12:04:14] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/Reminders/Reminder.php[L:326](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/javascript/jsAlerts.php[L:56](Reminder:addNotifications)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:223](jsAlerts:__construct)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Notice: Trying to get property of non-object occurred in /var/www/crm.fortecait.pl/modules/Reminders/Reminder.php on line 326 [2018-03-07 12:04:14] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/Reminders/Reminder.php[L:326](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/javascript/jsAlerts.php[L:56](Reminder:addNotifications)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:223](jsAlerts:__construct)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)

#### Your Environment
SuiteCRM Version used: 7.10.1
Browser name and version (e.g. Chrome 64.0.3282.186
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version CentOS

**Comment by pgorod** [comment]
Does this still happen in 7.10.3?

**Comment by AdminPL** [comment]
unfortunately yes - in this month i moved to new server with latest apache and php supported by suitecrm but no change. If i can be any help just point me in the right direction

**Comment by AdminPL** [comment]
![image](https://user-images.githubusercontent.com/30261902/38302546-6342f3c8-3803-11e8-9b07-2846b8536002.png)

**Comment by pgorod** [comment]
Weird, maybe you can try clearing browser cache, and deleting `cache/themes` directory on the server.

Also a few repairs from `Admin / Repair`. The QR&R, anything javascript related, and repair Dashlets.

**Comment by AdminPL** [comment]
Did everything no effect.

**Comment by pgorod** [comment]
Have you tried a different browser?

Also check a few the answers here
https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font

(especially the one with 10 points, if you are using `nginx`)

**Comment by AdminPL** [comment]
I did check also on safari, internet explorer, MS edge, mobile opera and on different operating systems - no effect. I've been strugling with this for many hours - most of obvious solutions i've already check.
I even serached forum and found problem relate with mine, but nothing usefull https://suitecrm.com/suitecrm/forum/suite-themes/11743-actions-button-label-missing-in-suitep#62227

**Comment by gunnicom** [comment]
Did you check your file permissions on the server?

**Comment by AdminPL** [comment]
Which one do you recomend? Right now i set everything:


sudo chown -R www-data:www-data .
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php

**Comment by gunnicom** [comment]
This is what i use:
`sudo chmod -R 775 cache custom data modules upload && sudo chmod 664 config.php && sudo chown www-data:www-data * -R`

**Comment by AdminPL** [comment]
No change.

**Comment by AdminPL** [comment]
When i turn on display error i see:
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php on line 342 [2018-04-06 12:50:30] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.phpL:342
/var/www/crm.fortecait.pl/modules/Home/index.phpL:236
/var/www/crm.fortecait.pl/modules/Home/views/view.list.phpL:52
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.phpL:207
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.phpL:432
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.phpL:375
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.phpL:109
/var/www/crm.fortecait.pl/index.phpL:52
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php on line 488 [2018-04-06 12:50:30] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.phpL:488
/var/www/crm.fortecait.pl/modules/Home/index.phpL:238
/var/www/crm.fortecait.pl/modules/Home/views/view.list.phpL:52
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.phpL:207
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.phpL:432
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.phpL:375
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.phpL:109
/var/www/crm.fortecait.pl/index.phpL:52

**Comment by pgorod** [comment]
@AdminPL you didn't tell us your PHP version yet, did you? 

This function is only deprecated in PHP 7.2, I guess that's what you're using...

**Comment by AdminPL** [comment]
"unfortunately yes - in this month i moved to new server with latest apache and php supported by suitecrm but no change. If i can be any help just point me in the right direction" 

Yes right now it's 7.2 but 7.0 also didn't work.

**Comment by pgorod** [comment]
I am running out of ideas to help you.... :-(

**Comment by AdminPL** [comment]
I've upgraded to 7.10.4

When i turn on tracking errors, no change - still missing buttons and ajax interface is not working.
Can't drag nad drop any items on main page:

Ajax is enabeld in system settings for all module and works fine in other modules.
In system logs there are no errors related, i've got no idea what can be missing.

I've done fresh installation on the same server an eveything works fine, so I exported all customizations and imported them into new installation, but.... 3 custom modules did not import. 



/var/www/crm.fortecait.pl/include/clean.php[L:46](:require_once)
/var/www/crm.fortecait.pl/include/entryPoint.php[L:102](:require_once)
/var/www/crm.fortecait.pl/index.php[L:47](:require_once)
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php on line 269 [2018-04-10 09:48:49] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:269](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1490](Smarty_Compiler:_compile_file)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1423](Smarty:_compile_source)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1255](Smarty:_compile_resource)
/var/www/crm.fortecait.pl/include/Sugar_Smarty.php[L:151](Smarty:fetch)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1107](Sugar_Smarty:fetch)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:800](Smarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:199](SugarView:displayHeader)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Unknown Error (8192): The each() function is deprecated. This message will be suppressed on further calls occurred in /var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php on line 559 [2018-04-10 09:48:49] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
[L:](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:559](:each)
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:312](Smarty_Compiler:_compile_tag)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1490](Smarty_Compiler:_compile_file)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1423](Smarty:_compile_source)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1255](Smarty:_compile_resource)
/var/www/crm.fortecait.pl/include/Sugar_Smarty.php[L:151](Smarty:fetch)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1107](Sugar_Smarty:fetch)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:800](Smarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:199](SugarView:displayHeader)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php on line 269 [2018-04-10 09:48:49] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:269](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1490](Smarty_Compiler:_compile_file)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1423](Smarty:_compile_source)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1868](Smarty:_compile_resource)
/var/www/crm.fortecait.pl/cache/smarty/templates_c/%%F9^F94^F946E606%%header.tpl.php[L:4](Smarty:_smarty_include)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1257](:include)
/var/www/crm.fortecait.pl/include/Sugar_Smarty.php[L:151](Smarty:fetch)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1107](Sugar_Smarty:fetch)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:800](Smarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:199](SugarView:displayHeader)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php on line 269 [2018-04-10 09:48:49] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:269](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1490](Smarty_Compiler:_compile_file)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1423](Smarty:_compile_source)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1868](Smarty:_compile_resource)
/var/www/crm.fortecait.pl/cache/smarty/templates_c/%%F9^F94^F946E606%%header.tpl.php[L:14](Smarty:_smarty_include)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1257](:include)
/var/www/crm.fortecait.pl/include/Sugar_Smarty.php[L:151](Smarty:fetch)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1107](Sugar_Smarty:fetch)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:800](Smarty:display)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:199](SugarView:displayHeader)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
   ADMINISTRATOR      SPRZEDAŻ      WSPARCIE      DZIAŁANIA      WSZYSTKO   Utwórz    
Wyszukaj...
    Marcin Rosiński 
PANEL KONFIGURACYJNY
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php on line 269 [2018-04-10 09:48:49] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/include/Smarty/Smarty_Compiler.class.php[L:269](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1490](Smarty_Compiler:_compile_file)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1423](Smarty:_compile_source)
/var/www/crm.fortecait.pl/include/Smarty/Smarty.class.php[L:1262](Smarty:_compile_resource)
/var/www/crm.fortecait.pl/include/Sugar_Smarty.php[L:151](Smarty:fetch)
/var/www/crm.fortecait.pl/modules/Administration/index.php[L:159](Sugar_Smarty:fetch)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:840](:include_once)
/var/www/crm.fortecait.pl/include/MVC/View/views/view.classic.php[L:74](SugarView:includeClassicFile)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:207](ViewClassic:display)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)

**Comment by pgorod** [comment]
I opened an Issue for the deprecation error you're getting: #6513

This Issue seems to be specific to your system, do you want to keep it open? Perhaps you can just try to apply the fix for #6513 when one appears. It's your call.

**Comment by samus-aran** [comment]
The issues regarding to the create_function has been resolved since 7.10.5+ please try it out and let us know if we need to reopen this.
