### ISSUE TITLE
No action menu links on sidebar for some modules and languages - 7.10.1

### ISSUE THREAD

**Issue by clementnadeauludifrance** [salesagility/SuiteCRM#5430]
#### Issue
After an upgrade from 7.9.12 to 7.10.1, for some modules and languages (excluding English), missing action menu links on sidebar (Create, View, Import, etc.)

#### Expected Behavior
Presence of action links to all languages and all modules

#### Actual Behavior
For some modules and languages (excluding English), missing action menu links on sidebar
- in English, there are action menu links on sidebar for all modules : it's ok
- in French (not tested other alternative languages), there are action menu links on sidebar for some modules, but missing for other modules
Examples : 
-- Contacts module : action menu links displayed
-- Calls module : no action menu links (not possible to create new call for example)
div id="actionMenuSidebar" is emply

This problem has appeared since the update

#### Steps to Reproduce
1. Loggued to french version, go to Contacts module : action menu links : OK
2. Loggued to french version, go to Call module : no action menu links : KO
3. Loggued to english version, go to Contacts module : action menu links : OK
4. Loggued to english version, go to Call module : action menu links : OK

#### Your Environment
* SuiteCRM Version used: 7.10.1 / French language pack : last version from crowdin
* Browser name and version : Google Chrome Version 64.0.3282.186 (Build officiel) (64 bits)
* Environment name and version : PHP 7.1.8
* Operating System and version : Ubuntu 14.04.5 LTS‬

**Comment by horus68** [comment]
Also posted here: https://github.com/salesagility/SuiteCRM/issues/5424
(I had not tested this yet)

**Comment by clementnadeauludifrance** [comment]
You're right, sorry, i searched badly
