### ISSUE TITLE
Can't sort Accounts / Leads by primary email address

### ISSUE THREAD

**Issue by bmd-benita** [salesagility/SuiteCRM#5434]
#### Issue
In accounts list and leads list page, all fields could be sorted. But, we can not sort Accounts by email address. 

#### Expected Behavior
User could sort leads / accounts by email address

#### Actual Behavior
There are sort icons in all fields. But, we can not find it in email address field.

#### Steps to Reproduce
1. Click Leads (or Accounts) menu
2. List page displayed to the user (all fields could be sorted except email address)

#### Context
There is a requirement that user should be able to sort leads and accounts by email address. 

#### Your Environment
* SuiteCRM Version used: 7.8.5
* Browser name and version: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MariaDB 10
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Xenial64

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't sort Accounts / Leads by primary email address](https://trello.com/c/X6plTzvJ/247-cant-sort-accounts-leads-by-primary-email-address)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
