### ISSUE TITLE
Global Search for Accounts / Leads Phone Number

### ISSUE THREAD

**Issue by bmd-benita** [salesagility/SuiteCRM#5435]
#### Issue
Our user could find accounts / leads from many fields. But, they can not find accounts / leads by phone number (mobile, office, fax, etc)

#### Expected Behavior
User could find accounts / leads by phone number in global search

#### Actual Behavior
User gets empty result when he / she wants to find accounts / leads by phone number

#### Steps to Reproduce
1. There are accounts / leads that has been created in suitecrm
2. User fill the correct phone number in search box that located in top menu bar
3. User get empty result 

#### Context
Our outbound call agent can not find leads / accounts by phone number from global search. 

#### Your Environment
* SuiteCRM Version used: 7.8.5
* Browser name and version: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MariaDB 10
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Xenial64

**Comment by Dillon-Brown** [comment]
@bmd-benita Are you sure that you are entering the phone number exactly as it appears on the record? I can't seem to replicate on latest 7.8.x LTS:

![lead_phone](https://user-images.githubusercontent.com/26431166/37144173-26dcbe7c-22b5-11e8-9c13-1af486654a39.png)

**Comment by bmd-benita** [comment]
Yes. Here are the screenshots:

![screenshot-10 10 10 10-2018 03 09-09-42-34](https://user-images.githubusercontent.com/17718038/37187800-8a61745a-237e-11e8-9153-1719f73d3da4.png)

![screenshot-10 10 10 10-2018 03 09-09-43-33](https://user-images.githubusercontent.com/17718038/37187816-9936c412-237e-11e8-92f5-e94ecc83e15f.png)

![screenshot-10 10 10 10-2018 03 09-09-44-12](https://user-images.githubusercontent.com/17718038/37187819-9d3b349e-237e-11e8-9192-1fb95cf46bf8.png)

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
