### ISSUE TITLE
Can't log into official SuiteCRM demo

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5437]
#### Issue

Hi, the login data are:
name: will
pass: will

https://demo.suiteondemand.com/

I tried in icognito.. in chrome/mozilla... but i still get error that login credentials are wrong

![2018-03-08_0936](https://user-images.githubusercontent.com/5773777/37141179-8614c228-22b4-11e8-862b-b2cc57fb88e8.png)

@daniel-samson @pgorod 

Do you have same issue or maybe i am inapt :(

**Comment by samus-aran** [comment]
Thanks for raising this @Mausino We're looking into it :+1:

**Comment by CamoMacdonald** [comment]
@Mausino This issue has now been resolved and you should be able to login as expected
