### ISSUE TITLE
PDF report not showing image in the image field instead it shows a small red x

### ISSUE THREAD

**Issue by alimanziw** [salesagility/SuiteCRM#5441]
#### Issue
lam using Suitcrm version 7.10.1
l have created products with 3 image fields on each, 
I then want to generate a PDF report with the product details including the images.

#### Expected Behavior
A report with a list of products including the images as shown in the LIST VIEW
#### Actual Behavior
Product details shown but no images, instead it shows a small red x or a link is shown

#### Steps to Reproduce

1. create product with image fields
2. create a new report which includes the image fields
3. under the actions menu, select download PDF
4. view the pdf report, no images are shown but a small red X

#### Your Environment

* SuiteCRM Version 7.10.1 installed on localhost XAMP
* Chrome and Firefox:
* MySQL, PHP 5.6 
* Windows Operating System

**Comment by alimanziw** [comment]
**Issue**
l created products with 3 image fields on each, then want to generate a PDF report with the product details including the images.
**Expected Behavior**
A report with a list of products including the images as shown in the LIST VIEW
Actual Behavior
product details shown but no images, instead a small red x or a link is shown

Possible Fix
Steps to Reproduce

**Comment by horus68** [comment]
To clean up this issue topic I think you should edit your first post and fill up all the requested details. Then delete the second post (will do the same for this one!)
