### ISSUE TITLE
LBL_UW_START_DESC2 - code or normal words?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5444]
#### Expected Behavior

The string LBL_UW_START_DESC2 in modules/UpgradeWizard/language/en_us.lang.php includes a text enclosed by a pre tag  `<pre>composer update</pre>`. Is this to be translated or is code to be executed afterwards?
`'LBL_UW_START_DESC2' => 'Note: We highly recommend that you create a copy of the SuiteCRM instance you use in production, and test the upgrade package before deploying the new version. If you have changed the "composer.json" file, please run <pre>composer update</pre>, after the upgrade process has completed.',
`
https://github.com/salesagility/SuiteCRM/blob/c6bece6ab3acd29365f5fc663ba8f3cc359a986b/modules/UpgradeWizard/language/en_us.lang.php#L180

#### Actual Behavior

If plain text it should not be inside pre tag has it looks strange as it breaks the sentence:
![composer_update](https://user-images.githubusercontent.com/3055443/37157879-de1f44c0-22e1-11e8-86d3-6b9091fa0c0e.png)

#### Steps to Reproduce

1. Enter Admin / upgrade
2. Its the first screen

#### Context

not sure if this should be translated

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): 7.10.0
* Operating System and version (e.g Ubuntu 16.04): Windows 10, Wamp

**Comment by Dillon-Brown** [comment]
@horus68 You would want to translate "composer update". It should visually stand apart from the rest of the text as it's a command to be run after the upgrade.

**Comment by horus68** [comment]
That will be a problem for translators!

**Comment by horus68** [comment]
@Dillon-Brown We need at least a better wording: 
- where to run the command and how.
- Also the command should be in the end of the string, after a <br/> so it not breaks into the middle of a sentence on translations (the visual in LTR and non latin languages is very strange).

**Comment by horus68** [comment]
@Dillon-Brown just waiting for a merge
