### ISSUE TITLE
Import From .CSV issue popped up 7.9.12

### ISSUE THREAD

**Issue by rciv** [salesagility/SuiteCRM#5445]
#### Issue

I imported targets in 7.9.11, worked fine (from a .csv).  Upgraded to 7.9.12, deleted the targets and tried to import as leads, no error but it gave everyone the same email address (tried importing back into targets, same problem).  Restored 7.9.11 from backup.  Importing leads worked just fine.

Don't have much more info, just something I came across.

fyi

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.9.11 & 7.7.12
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 63.0.3239.132
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):  Windows 10 1709

**Comment by QuickCRM** [comment]
With 7.8.16 and 7.9.15, importing
first_name;last_name;email1
first_name1;last_name1;email1@test.com
first_name2;last_name2;
first_name3;last_name3;email3@test.com
first_name4;last_name4;
first_name5;last_name5;email5@test.com

creates record where empty emails are replaced by previous email, i.e.

last_name1: email1@test.com
last_name2: email1@test.com
last_name3: email3@test.com
last_name4: email3@test.com
last_name5: email5@test.com

Seems to work fine in 7.10.1

**Comment by Dillon-Brown** [comment]
Hi @rciv, this was fixed in [v7.9.13](https://docs.suitecrm.com/admin/releases/#anchor-7.9.13). If you can replicate this on versions later than 7.9.13 we can re-open. Thanks.

**Comment by QuickCRM** [comment]
Hi,

This is not properly fixed:

With 7.8.16 and 7.9.15, importing
first_name;last_name;email1
first_name1;last_name1;email1@test.com <mailto:email1@test.com>
first_name2;last_name2;
first_name3;last_name3;email3@test.com <mailto:email3@test.com>
first_name4;last_name4;
first_name5;last_name5;email5@test.com <mailto:email5@test.com>
creates records where empty emails are replaced by previous email, i.e.

last_name1: email1@test.com <mailto:email1@test.com>
last_name2: email1@test.com <mailto:email1@test.com>
last_name3: email3@test.com <mailto:email3@test.com>
last_name4: email3@test.com <mailto:email3@test.com>
last_name5: email5@test.com <mailto:email5@test.com>
Seems to work fine in 7.10.1

—
support@quickcrm.fr
www.quickcrm.fr/mobile <http://www.quickcrm.fr/mobile>
Visit our FAQ <http://www.quickcrm.fr/mobile/en/content/16-faq>

**Comment by QuickCRM** [comment]
This issue is fixed in 7.10.1 but not in 7.8.16 LTS.
As this is LTS, I would expect that to be fixed.

importing
first_name;last_name;email1
first_name1;last_name1;email1@test.com
first_name2;last_name2;
first_name3;last_name3;email3@test.com
first_name4;last_name4;
first_name5;last_name5;email5@test.com
creates records where empty emails are replaced by previous email, i.e.

last_name1: email1@test.com
last_name2: email1@test.com 
last_name3: email3@test.com
last_name4: email3@test.com
last_name5: email5@test.com
