### ISSUE TITLE
File in user module not looking for custom sugar helper plugin

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#5446]
#### Issue

In the user module folder there is a file UserViewHelper.php. On line 555 in this file the code attempts to load the smarty plugin sugar_help. It loads the default without checking to see if there is a custom plugin first. However, later code will check the custom folder to see if the plugin exists. This means that both default and custom function will be attempted to be loaded and cause an error for re declaring the same class.

#### Expected Behavior

UserViewHelper should be looking for the custom plugin first before loading the default

#### Actual Behavior

UserViewHelper declares the default plugin first on line 555

#### Possible Fix

Check for the custom plugin before loading the default plugin

#### Steps to Reproduce

1. Copy the file function.sugar_help.php (include/Smarty/plugins) into the custom folder (custom/include/Smarty/plugins)
2. Go to a user profile and attempt to go to the edit view
3. You run into a re declare error

#### Context

I needed to override the default sugar_help smarty plugin to customize tool tips. This work perfectly on other pages I have tried so far. However, when trying to the load the user edit view page, I found that UserViewHelper loads the default plugin first, without checking for a custom plugin.

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 63.0.3239.132
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by pgorod** [comment]
@wiatrp please test the proposed fix #5458. Thanks!
