### ISSUE TITLE
Custom subpaneldefs on overriding core subopaneldefs

### ISSUE THREAD

**Issue by eagarao** [salesagility/SuiteCRM#5447]
Custom subpaneldefs on overriding core subopaneldefs.

#### Issue
custom/<module>/metadata/subpaneldefs.php isn't being recognized. CRM still uses the one in <module>/metadata/subpaneldefs.php directory.

#### Expected Behavior
The custom subpaneldefs should override the core def.

#### Actual Behavior
Even though, an existing custom subpaneldefs.php is present, the system still uses the cure subpaneldefs.

#### Steps to Reproduce
1. Create a custom subpaneldefs (you can just copy from the core like in modules/Accounts/metadata/subpaneldefs.php and remove other panels) 
2. Set correct permissions
3. Do a Quick Repair and Rebuild
4. Check subpanels

#### Context
This is a medium priority. 
This feature should be fixed since most customers want to hide subpanels in a certain module.
Note that the one in Admin page is for displaying/hiding subpanels globally.

#### Your Environment
* SuiteCRM Version used: v7.10.1
* Browser name and version: Google Chrome - Version 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version: PHP 5.5.38, Mysql 5.5
* Operating System and version: CentOS 6.5

**Comment by bdejin** [comment]
I suffered hours on this and got frustrated. Fortunately found the workaround:

Edit the file \include\SubPanel\SubPanelDefinitions.php, add below 2 lines after line 790:
if (file_exists ( 'custom/modules/' . $this->_focus->module_dir . '/metadata/subpaneldefs.php' ))
                require ('custom/modules/' . $this->_focus->module_dir . '/metadata/subpaneldefs.php') ;

this will check if the custom subpaneldefs.php file exist and load it if yes.

Hope this helps and the developer can pickup and fix this.

Regards,
Dejin

**Comment by pgorod** [comment]
@eagarao sorry, I hadn't seen this issue before.

If I understand correctly, there is good reason not to pick up that custom file. I think you should be doing the customizations in a different place, using the Extension mechanism:

https://docs.suitecrm.com/developer/extension-framework/#_standard_extensions

specifically, the LayoutDefs extension which you should create in `custom/Extension/modules/Accounts/Ext/Layoutdefs/<any_name>.php`, see an example here:

http://urdhva-tech.com/blogs/add-custom-subpanel-in-accounts-module

You can also use the same mechanism to `unset` parts of the array and remove elements.

The advantage of the Extensions mechanism is that many different "players" can make changes to the same items. So you can have an add-on adding a field, then your own customizations changing an attribute, or more, and the QR&R will consolidate everything into `custom/<module>/Ext/Layoutdefs/layoutdefs.ext.php` which is what will actually be loaded by the system.

I hope this works well for you. It will be upgrade-safe. If so, please close the issue. Thanks!

**Comment by eagarao** [comment]
Hi @pgorod  ,

I know that we can utilize the Extension framework. 
However, I believe that this should be used to target specific subpanels. 
For instance, you need to unset or override a subpanel. 

In my case, I do not only need to remove some subpanels, but I also need to change the order of the subpanels. Having the custom/module/<module>/metadata/subpaneldefs.php would be helpful in this scenario. SugarCRM before Sugar7 reads this file.

Regards!
