### ISSUE TITLE
Campaign Emails Don't Send (test or otherwise)

### ISSUE THREAD

**Issue by VivaLaPanda** [salesagility/SuiteCRM#5459]
#### Issue
I have a SuiteCRM installation running 7.10.1. I have been testing the campaign features and ran into an issue where I cannot send email from campaigns. Sending test emails through the preconfigured outgoing mail account works fine in all other places, but when I either wait for a scheduled email and hit "Send Marketing Email as Test", the page reloads but no email sends.

#### Expected Behavior
No email is sent, and no errors appear on the page or in the logs.

#### Actual Behavior
Nothing is written to the logs and the page simply reloads. The request to the server and subsequent redirect/301 occurs and no errors are sent with the response. I have tried several outgoing mail accounts and nothing appears in the sent and Google doesn't report any security or signin warnings.

Tried:

* Changing crontab a few times, and manually running the cron.php
* Recreating the outgoing email account from scratch
* Several different outgoing emails
* Several different targets

#### Possible Fix
n/a

#### Steps to Reproduce

1. Unsure how it started. It was working fine and then stopped overnight
2. Once the issue occurs, simply try clicking "Send Marketing Email as Test" in the wizard or Actions > Send Test in the campaign email page.
3. Check sent folder of relevant account

#### Context

This is medium priority for us, as we are not yet using the Campaign feature in production, but it essentially makes the feature useless.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 64.0.3282.167 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by stefanomarty** [comment]
I can confirm the issue is still present in 7.10.2
Here's the FATAL error in php_errors.log:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to EmailTemplateParser::__construct() must implement interface EmailInterface, instance of Prospect given, called in /opt/SuiteCRM/modules/EmailMan/EmailMan.php on line 982 and defined in /opt/SuiteCRM/modules/EmailTemplates/EmailTemplateParser.php:102
Stack trace:
#0 /opt/SuiteCRM/modules/EmailMan/EmailMan.php(982): EmailTemplateParser->__construct(Object(EmailTemplate), Object(Campaign), Object(Prospect), 'https://...', '...')
#1 /opt/SuiteCRM/modules/EmailMan/EmailManDelivery.php(258): EmailMan->sendEmail(Object(SugarPHPMailer), '2', true)
#2 /opt/SuiteCRM/include/MVC/View/SugarView.php(817): include_once('/opt/SuiteCRM/m...')
#3 /opt/SuiteCRM/include/MVC/View/views/view.classic.php(74): SugarView->includeClassicFile('modules/EmailMa...')
#4 /opt/SuiteCRM/include/MVC/View/SugarView.php(207): ViewClassic->display()
#5 /opt/SuiteCRM/include/MVC/Controller/SugarController.php(432): SugarView->process()
#6 /opt/SuiteCRM/include/MVC/Controller/SugarCon in /opt/SuiteCRM/modules/EmailTemplates/EmailTemplateParser.php on line 102
```
Looks like something's wrong with parameter **Object(Prospect)** passed by /opt/SuiteCRM/modules/EmailMan/EmailMan.php on line 982 to /opt/SuiteCRM/modules/EmailTemplates/EmailTemplateParser.php

Unfortunately, this is blocking the Campaign module from sending out the emails, making it actually useless.

**Comment by pgorod** [comment]
The code that recently touched that line is this commit by @Dillon-Brown 
https://github.com/salesagility/SuiteCRM/commit/3e5a4fa5ccca2ef82dbdf66e21f0ac69841d5154

Do you get this error only when sending to "prospects" (which means: "targets"), or also if you attempt to send to Contacts or Leads?

**Comment by Admoneo** [comment]
Same problem here on 7.10.2, Debian, MySQL , PHP7.0

**Comment by Admoneo** [comment]
Tested campaigns send to contacts (removed all targets and leads)
No change, same php error in the log!

**Comment by pgorod** [comment]
@Admoneo is that with Dillon's fix, or without? Please try the fix if you haven0t already.

**Comment by Admoneo** [comment]
Didn't notice the fix before.
That was without the fix.
I am testing the fix right now.

**Comment by stefanomarty** [comment]
I've just applied the fix and tried to send the "test" emails on my last campaign: the emails are sent, and it looks like everything's fine. I checked php_errors.log, and the previous errors are gone (I still have some other errors, but that's a different story, they're not related to the Campaign module. Will open a new issue later).

I'm planning to launch the real campaign tonight, will post feedback tomorrow, in the meantime thanks for you efforts and for the quick fix!

**Comment by Admoneo** [comment]
I can confirm the error is gone from php error log.
However my installation emails didn't go out until I manually forced the campaign queue emails in admin.
I think I have seen posts about this and will have to further investigate.

**Comment by 1kidvidiot** [comment]
This bug cost me about 25 hours and as a result have removed from 3 customers networks. Waste of time, they will never use it again. Bugs have consequences, makes it look shoddy, buggy crapware

**Comment by 1kidvidiot** [comment]
Giving open source a bad name.

**Comment by 1kidvidiot** [comment]
didnt figure it wouldnt work until had already trained clients on it since the email and contact section sent emails. no matter what, campaigns will not send emails in any mode. this bug cost me $$ in time lost as well as customers.

**Comment by pgorod** [comment]
@1kidvidiot I'm sorry to hear that. Can you please point me to the Forums topic where you tried to troubleshoot it? I'd like to review it. There are several email and campaigns bugs out there and I need more detailed information to be able to figure out which exact issue you ran into. Thanks.
