### ISSUE TITLE
Cant edit Labels in List Views

### ISSUE THREAD

**Issue by it7baptiste** [salesagility/SuiteCRM#5461]
#### Issue
I have recently update two SuiteCRM installation from 7.9X to 7.10.1 without problems, i was trying to change fields name of the account view list to match better with the usage that we need, and i got a white page with json broken : http://prntscr.com/ip4gf6 instead of the edit form.

I've try with a new complete installation too, to be sure it wasn't come from upgrading stuff.

#### Expected Behavior
The form to edit the field label is not showing and nothing happens in the error logs.

#### Actual Behavior
Nothing is writing on the logs, if I refresh my page to try to have again my view list page, i'm redirected to the CRM Home, if i go again on the layout view list of the accound module, the view is now completely empty, but i can restore it with the restore default button.

#### Possible Fix
Not sure but what i can see on the broken json makes me thinking about something wrong in addslashing/protecting chars

#### Steps to Reproduce
1. Go on Admin > Studio > Accouts > Layouts > List View
2. Click on Pen Icon of the "Name" Field to edit him
3. Then you should have the broken json page

#### Context
I was trying to adapt labels name of the account view list to make it match better with our usage, not a huge bug but a bit annoying for customization.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 64.0.3282.167 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by edmondklai** [comment]
I have the same issue.
