### ISSUE TITLE
Click outside of the email window will delete the email without warning suite 7.10.1

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#5463]
This is a feature request for the email pop up compositor.
Writing an email can take a long time, loosing an email you have been writting for 30 minutes is something terrible in your day. THerefore you want to limite the chances to delete your email while writing it.

#### Issue
When you are writing an email in "pop up mode" a simple one click outside the composer will delete your message. (Refresing the window will do the same)

#### Expected Behavior
A click ouside the "pop up window" of the composer will fire a message "Do you really want to delete this message ?  YES NO "

#### Actual Behavior
You loose your email and start over.

#### Possible Fix
A click ouside the "pop up window" of the composer will fire a message "Do you really want to delete this message ?  YES NO "
(In case of window refresh or closing tab we could fire the same message )

#### Steps to Reproduce
1. View a contact with an email
2.Click on the email to get the popup composer
3.Click outside the composer
4. The composer closes

#### Your Environment

* SuiteCRM Version used: 7.10.1
https://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3Dindex%26parentTab%3DSales
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox quantum

**Comment by Dillon-Brown** [comment]
Fixed here: #5914
