### ISSUE TITLE
Usage of the word DROP [Language issue]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5468]
#### Issue
How should we translate the term `Drop parenthesis`: to delete/remove or to place/include a parenthesis?
Can someone include a screen or situation where this is used? 

The string is from modules/AOR_Reports/language/en_us.lang.php
```
    'LBL_ADD_CHART' => 'Add chart',
    'LBL_ADD_PARENTHESIS' => 'Drop parenthesis',
```
and used in  modules/AOR_Reports/tpls/EditViewFooter.tpl
```
            <table id="aor_condition_parenthesis_table">
                <tbody id="aor_condition_parenthesis_btn" class="connectedSortableConditions">
                <tr class="parentheses-btn"><td class="condition-sortable-handle">
                    <span title="{$MOD.LBL_ADD_PARENTHESIS}">( ... ) {$MOD.LBL_ADD_PARENTHESIS}</span>
                    </td></tr>
                </tbody>
            </table>
```
https://github.com/salesagility/SuiteCRM/blob/c6bece6ab3acd29365f5fc663ba8f3cc359a986b/modules/AOR_Reports/tpls/EditViewFooter.tpl#L83

#### Context

Transtaltors are taken opposite directions on the translation. I think there is also a problem when the value says `Drop` but the key says Add ( `LBL_ADD_PARENTHESIS`). So there are some doubts if the programmers realize that when using that key they want to say "to remove"!
Either way, the key or the value should be changed to make this clear!

#### Your Environment

* SuiteCRM Version used: All

**Comment by Dillon-Brown** [comment]
Context:
![context](https://user-images.githubusercontent.com/26431166/37276874-fd1971ec-25da-11e8-8aee-0e47f3e21b4b.png)

I think changing the LBL to be LBL_DROP_PARENTHESIS would make the most sense here.

**Comment by horus68** [comment]
@Dillon-Brown But is the value DROP used as in "DRAG and DROP" or as in "REMOVE"?
The actual wording also needs to be changed so translators don't make errors when translating
Note: almost all of us did translated this as "Remove" but a translator has now alerted it must be translated as to "include" the parenthesis!
(I actually haven't find a way to use this in the reports and to see how it works!)

**Comment by Dillon-Brown** [comment]
@horus68 The value DROP is used as in "REMOVE". I don't think it's actually working on reports at the moment due to an issue with drag and drop. Do you have a preference for renaming the label to make this clearer to translators?

**Comment by horus68** [comment]
I'm not an english speaker but for translators it would be better to be something like: 
`'LBL_REMOVE_PARENTHESIS' => 'Remove parenthesis',`

**Comment by Pawes** [comment]
I think that the word "drop" _is_ referring to drag-and-drop. If you try to drag the text "drop paranthesis" in the LTS version's Report module you can place them in the conditions list:
![dragndrop](https://user-images.githubusercontent.com/15903729/37392607-e1bf07d2-276e-11e8-959b-1c37258b4f77.png)
So I don't think it should be renamed "remove". Perhaps it should be called "place parenthesis" with an added title attribute that explains to the user that it should be dragged into the conditions list.

**Comment by horus68** [comment]
@Dillon-Brown this also waiting for a merge
