### ISSUE TITLE
Fillers Cause Spacing Issues on the DetailView when they are left of a Field

### ISSUE THREAD

**Issue by jshwhitlow** [salesagility/SuiteCRM#5477]
#### Issue
When you go into Studio for any module, put a field on the right, a filler on the left and the publish those changes, the field will not be on the right. Instead it will be on the left and will have some weird spacing.

#### Expected Behavior
The field should be on the right with correct spacing. It should appear exactly how it saved in Studio.

#### Actual Behavior
(Pictures listed below)

#### Possible Fix
You can fix this issue by going to themes/SuiteP/include/DetailView/tab_panel_content.tpl

On Lines 204-206, below is the listed code, commenting this code out resolves the spacing dilemma.

```
{{if $fieldCount==0}}
        <div class="clear"></div>
{{/if}}
```

I can see this was changed here on this commit: https://github.com/salesagility/SuiteCRM/commit/6026dc2

In reference to this spacing issue: https://github.com/salesagility/SuiteCRM/issues/1931

Although, I am unable to reproduce the problem listed in that issue by commenting out this code.

#### Steps to Reproduce
1. Go to Studio for any module
2. Within any panel or tab, add a field on the right, but not left (leave a filler on the left)

![screen shot 2018-03-12 at 8 26 41 am](https://user-images.githubusercontent.com/17415608/37284728-0f5aa20c-25d3-11e8-8cd2-46eb8bcc9836.png)

3. Save and publish and go to the DetailView only

![screen shot 2018-03-12 at 8 27 08 am](https://user-images.githubusercontent.com/17415608/37284732-162cfeea-25d3-11e8-8639-c8a58156f971.png)

#### Context
I was simply trying to add a field on the right, but not the left. I feel this is a medium priority fix ONLY because it should be very easy to fix the issue.

#### Your Environment
* SuiteCRM Version used: 7.10.1
* Browser name and version: Chrome 64.0.3282.186 (64-bit)
* Environment name and version: PHP Version 7.0.10, MySQL Version 5.6.28
* Operating System and version: macOS Sierra Version 10.12.3

**Comment by aureh12** [comment]
Please fix this bug. Thanks
