### ISSUE TITLE
AOW - 'Any Change' on Audit Enabled field won't fire 

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#548]
Workflow used to test this was: 
Accounts > Name >	Equal To	> Any Change
But seems to occur on most uses of Any Change on an Audit Enabled field.

If field is Audit Enabled
Workflow would not fire when field's value was changed.
After disabled Auditing on the field
Workflow would successfully fire when field's value was changed.

**Comment by johnM2401** [comment]
Sorry, Forgot to check for duplicate issues before posting. Hadn't noticed Matt's:
https://github.com/salesagility/SuiteCRM/issues/195

**Comment by websolprov** [comment]
You find any fix for this johnm2401?
