### ISSUE TITLE
PDF Template - Total price and total price usdollar print mixup

### ISSUE THREAD

**Issue by ajedvaj** [salesagility/SuiteCRM#5491]
#### Issue

We have PDF template which needs to output line items total price in both invoice currency and default currency.
They need to be in order first default currency, than the invoice currency ($aos_products_quotes_product_total_price_usdollar - $aos_products_quotes_product_total_price)

However we get the following output:
![pdf-error](https://user-images.githubusercontent.com/18736912/37337148-b79c386e-26b3-11e8-8eea-4dad1234fa69.png)

#### Expected Behavior

It should print out both usdollar field and regular field in that order.
#### Actual Behavior

It prints only regular fields first occurrence and doesn't print the rest. 

#### Steps to Reproduce

1. Create PDF Template which prints first $aos_products_quotes_product_total_price_usdollar and after $aos_products_quotes_product_total_price field
2. Create Invoice in some currency
3. Print PDF

#### Your Environment

* SuiteCRM Version used: 7.8.X
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 58, Chrome 64.0.32...
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7, PHP 7.1, PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu  16.04, Mint 17.1, Mint 18

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
