### ISSUE TITLE
Navigate in different page don't work after modify collumn

### ISSUE THREAD

**Issue by Mika67** [salesagility/SuiteCRM#5495]
#### Issue

In the Contacts list, when we add or delete collumn : it's impossible to navigate at the different page (Button Previous/ Next)

#### Expected Behavior

After the modification of collumn , possibility of navigate in different pages from contacts table with the buttons.

#### Actual Behavior

Impossible to navigate next or previous in the table. 

When we log us of a other PC or web browser, we have ever the same problem.
#### Possible Fix

The only fix is try with a other user.
#### Steps to Reproduce

1. In contacts list (Support -> Contacts)
2. Add a collumn with the "Collumn Chooser button"
![collumn choise](https://user-images.githubusercontent.com/10249090/37353845-8a579b14-26e0-11e8-9843-ebbc82a7d93b.png)
3.Try to navigate in the different page
![next previous](https://user-images.githubusercontent.com/10249090/37354030-f51c797e-26e0-11e8-8613-6d031e76fea8.png)

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 58.0.2
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.27 MySQL 15.1 5.5.56-MariaDB
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by javitoron** [comment]
It happens in accounts, documents and custom modules as well. And you can't sort by column.

**Comment by sguilly** [comment]
Fix by : apply a 'My filter' and remove it

But the bug is present if you add a column from the view

Seems to work when the conumn is adding by the studio

**Comment by Mika67** [comment]
@sguilly What do you mean with the studio ?

**Comment by sguilly** [comment]
You could setup columns displayed in the contact list view with the studio module 'admin menu) and the navigation work fine.

But, if you add a collumn with the "Collumn Chooser button" in the contact list view then the navigation is broken.

**Comment by lee1974** [comment]
I have this problem also, on previous version of suitecrm, both upgraded and also tried fresh install.

Originally thought it was because i have migrated from early version of sugarcrm.

However have tried installing a fresh install of 7.9.16 and I experience the same issue.

SuiteCRM version: 7.9.16
OS: windows 7, xampp, php version 7 (have tried php version 5.6.8 also same issue)
client windows 7, browser: many browsers tried, all have same issue.

**Comment by chogori92** [comment]
Same problem here!

**Comment by chogori92** [comment]
Commenting out modifications from fix #4197 in include/MVC/View/views/view.list.php seems to solve the problem.

**Comment by samus-aran** [comment]
@chogori92 @Mika67 @sguilly @lee1974 @javitoron 
There is a fix proposed, are you able to test this and confirm it is a successful fix. :+1:

**Comment by awakenweb** [comment]
Same issue here on 7.10.4, I tested the proposed fix and the problem is still occuring.
The list is stuck on the second page of the result set, until a filter is applied and reset.

**Comment by PedroErnst** [comment]
Please test #6117 and see if it solves the issue, thanks.

**Comment by awakenweb** [comment]
@PedroErnst I just tested it and everything works fine now.
Many thanks for finding a solution.
