### ISSUE TITLE
SuiteCRM 7.10.1 Stoped after Creating the database...DONE

### ISSUE THREAD

**Issue by praction1988** [salesagility/SuiteCRM#5496]
#### Issue
I am deploying SuiteCRM 7.10.1 on our new web-server. But it stooped after a specific task(Creating the database crm on 192.168.23.100:3306...done), 

#### Expected Behavior
It should be continue or through an error if there is an issue with deployment

#### Actual Behavior

no file suitecrm.log like that. because no error observer. 

Suite CRM- SuiteCRM 7.10.1
PHP Version:- PHP 7.0.28
MySQL :- NDB Cluster 5.7
OS- CentOS Linux release 7.4.1708 (Core)
Browser : tested with chrome, Firefox and IE

Attaching screenshot for more reference
![suite crm](https://user-images.githubusercontent.com/37348394/37366725-a94901e4-272f-11e8-94a4-6f5ae074dd22.PNG)
.

**Comment by praction1988** [comment]
As per the logs it is looking for (installerHook: Could not find custom/install/install_hooks.php)

I download that version from Suitecrm Download page. How that file can miss.
[install.log](https://github.com/salesagility/SuiteCRM/files/1811999/install.log)
 

I am attaching the logs for more info.

**Comment by pgorod** [comment]
That message `(installerHook: Could not find custom/install/install_hooks.php)` is not an error. It's just saying that there are no custom hooks.

I've seen some people on the forums recently saying they can only get the installer to connect to the database correctly if they create a Suitecrm database manually, add an admin user, and then run the installer. This shouldn't be necessary, though. I think it happens to MariaDB users. Maybe this MySQL NDB is also different for some reason.

**Comment by praction1988** [comment]
So What can be reason over this. I have try this. but at-least it should through an error that what is happening.

**Comment by highplainsdesignstudio** [comment]
It looks like you're having problems with permissions in the log as well. Do you have the permissions set up for the install?

**Comment by praction1988** [comment]
Dear, 
Thanks for your suggestion. 
Yes I have proper permission on web root 755. Selinux is disabled. other application on this WebsServer working fine.   

No Issue found with this.

**Comment by praction1988** [comment]
Dear Team I try with &. 7.10.2 but same result...

[root@web1 SuiteCRM-7.10.2]# more /var/www/crm.praction.in/public_html/install.log

2018-03-17 05:57:05...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:14...Begin System Check Process *************
2018-03-17 05:57:14...XML Parsing Support Found
2018-03-17 05:57:14...MBString Support Found
2018-03-17 05:57:14...ZIP Support Found
2018-03-17 05:57:14.../custom directory and subdirectory check passed
2018-03-17 05:57:14...cache directory and subdirectory check passed
2018-03-17 05:57:14.../module  directory and subdirectory check passed
2018-03-17 05:57:14.../upload directory check passed
2018-03-17 05:57:14.../zip check passed
2018-03-17 05:57:14...PCRE version check passed
2018-03-17 05:57:14...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:14...php.ini location found. /etc/php.ini
2018-03-17 05:57:14...Outputting HTML for System check
2018-03-17 05:57:14...No Errors were found *************
2018-03-17 05:57:15...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:22...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:58:34...Begin DB Check Process *************
2018-03-17 05:58:34...testing with mysql:mysqli
2018-03-17 05:58:34...Basic form info is valid, continuing Process.
2018-03-17 05:58:34...Testing user account...
2018-03-17 05:58:34...Connection made using  host: 192.168.23.100:3306, usr: praction
2018-03-17 05:58:34...SUCCESS:: no errors detected!
2018-03-17 05:58:34...End DB Check Process *************
2018-03-17 05:58:35...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:58:35...calling handleSugarConfig()
2018-03-17 05:58:35...calling handleHtaccess()
2018-03-17 05:58:35...calling handleDbCreateDatabase()
2018-03-17 05:58:36...looping through all the Beans and create their tables
2018-03-17 05:58:36...processing table acl_actions
2018-03-17 05:58:37...creating table acl_actions
2018-03-17 05:58:37...creating Relationship Meta for ACLAction
2018-03-17 05:58:37...processing table acl_roles
2018-03-17 05:58:37...creating table acl_roles
2018-03-17 05:58:37...creating Relationship Meta for ACLRole
2018-03-17 05:58:37...processing table relationships
2018-03-17 05:58:38...creating table relationships
2018-03-17 05:58:38...creating Relationship Meta for Relationship
2018-03-17 05:58:38...processing table leads

no error not installation complete

**Comment by highplainsdesignstudio** [comment]
Is the database created? What happens when you revisit the site afterwards? Do you get an http error? Or, does it return to the install screen, or is it broken at all?

**Comment by praction1988** [comment]
HI ,

Yes Database is already created. and I am able to perform all action from this host in database. 
Install window freeze on same window. 
If we revisit the site we are getting http 500 error. It did not return on install screen. 
If we are going forcefully on install screen. 
![image](https://user-images.githubusercontent.com/37348394/37556978-2318efda-2a2c-11e8-91df-9d7d106ddba9.png)
 

[root@web1 public_html]# more install.log

2018-03-17 05:57:05...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:14...Begin System Check Process *************
2018-03-17 05:57:14...XML Parsing Support Found
2018-03-17 05:57:14...MBString Support Found
2018-03-17 05:57:14...ZIP Support Found
2018-03-17 05:57:14.../custom directory and subdirectory check passed
2018-03-17 05:57:14...cache directory and subdirectory check passed
2018-03-17 05:57:14.../module  directory and subdirectory check passed
2018-03-17 05:57:14.../upload directory check passed
2018-03-17 05:57:14.../zip check passed
2018-03-17 05:57:14...PCRE version check passed
2018-03-17 05:57:14...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:14...php.ini location found. /etc/php.ini
2018-03-17 05:57:14...Outputting HTML for System check
2018-03-17 05:57:14...No Errors were found *************
2018-03-17 05:57:15...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:57:22...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:58:34...Begin DB Check Process *************
2018-03-17 05:58:34...testing with mysql:mysqli
2018-03-17 05:58:34...Basic form info is valid, continuing Process.
2018-03-17 05:58:34...Testing user account...
2018-03-17 05:58:34...Connection made using  host: 192.168.23.100:3306, usr: praction
2018-03-17 05:58:34...SUCCESS:: no errors detected!
2018-03-17 05:58:34...End DB Check Process *************
2018-03-17 05:58:35...installerHook: Could not find custom/install/install_hooks.php
2018-03-17 05:58:35...calling handleSugarConfig()
2018-03-17 05:58:35...calling handleHtaccess()
2018-03-17 05:58:35...calling handleDbCreateDatabase()
2018-03-17 05:58:36...looping through all the Beans and create their tables
2018-03-17 05:58:36...processing table acl_actions
2018-03-17 05:58:37...creating table acl_actions
2018-03-17 05:58:37...creating Relationship Meta for ACLAction
2018-03-17 05:58:37...processing table acl_roles
2018-03-17 05:58:37...creating table acl_roles
2018-03-17 05:58:37...creating Relationship Meta for ACLRole
2018-03-17 05:58:37...processing table relationships
2018-03-17 05:58:38...creating table relationships
2018-03-17 05:58:38...creating Relationship Meta for Relationship
2018-03-17 05:58:38...processing table leads
2018-03-17 15:14:22...installerHook: Could not find custom/install/install_hooks.php
[root@web1 public_html]# more suitecrm.log
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 1146: Table 'crm.currenc
ies' doesn't exist
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL]  Query Failed: SELECT * FROM fields_meta_data WHERE  custom_module='Users' AND  deleted = 0: MySQL error 1146: Table 'crm.fields_meta_data' doesn't e
xist
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL]  Query Failed: SELECT * FROM fields_meta_data WHERE  custom_module='Employees' AND  deleted = 0: MySQL error 1146: Table 'crm.fields_meta_data' doesn
't exist
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL]  Query Failed: SELECT * FROM fields_meta_data WHERE  custom_module='UserPreferences' AND  deleted = 0: MySQL error 1146: Table 'crm.fields_meta_data'
 doesn't exist
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL]  Query Failed: SELECT * FROM fields_meta_data WHERE  custom_module='Administration' AND  deleted = 0: MySQL error 1146: Table 'crm.fields_meta_data'
doesn't exist
Sat Mar 17 20:40:40 2018 [25612][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 1146: Table 'crm.config' doesn't exist
Sat Mar 17 20:42:16 2018 [25317][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 1146: Table 'crm.currenc
ies' doesn't exist
Sat Mar 17 20:42:16 2018 [25317][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 1146: Table 'crm.config' doesn't exist
[root@web1 public_html]# more sugar
sugarcrm.log        sugar_version.json  sugar_version.php
[root@web1 public_html]# more sugarcrm.log
Sat Mar 17 11:28:38 2018 [25365][-none-][FATAL] Error creating table: leads: Query Failed: CREATE TABLE leads (id char(36)  NOT NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modi
fied_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,salutation varchar(255)  NULL ,first_name varchar(10
0)  NULL ,last_name varchar(100)  NULL ,title varchar(100)  NULL ,photo varchar(255)  NULL ,department varchar(100)  NULL ,do_not_call bool  DEFAULT '0' NULL ,phone_home varchar(100)  NULL ,phone_m
obile varchar(100)  NULL ,phone_work varchar(100)  NULL ,phone_other varchar(100)  NULL ,phone_fax varchar(100)  NULL ,primary_address_street varchar(150)  NULL ,primary_address_city varchar(100)
NULL ,primary_address_state varchar(100)  NULL ,primary_address_postalcode varchar(20)  NULL ,primary_address_country varchar(255)  NULL ,alt_address_street varchar(150)  NULL ,alt_address_city var
char(100)  NULL ,alt_address_state varchar(100)  NULL ,alt_address_postalcode varchar(20)  NULL ,alt_address_country varchar(255)  NULL ,assistant varchar(75)  NULL ,assistant_phone varchar(100)  N
ULL ,converted bool  DEFAULT '0' NULL ,refered_by varchar(100)  NULL ,lead_source varchar(100)  NULL ,lead_source_description text  NULL ,status varchar(100)  NULL ,status_description text  NULL ,r
eports_to_id char(36)  NULL ,account_name varchar(255)  NULL ,account_description text  NULL ,contact_id char(36)  NULL ,account_id char(36)  NULL ,opportunity_id char(36)  NULL ,opportunity_name v
archar(255)  NULL ,opportunity_amount varchar(50)  NULL ,campaign_id char(36)  NULL ,birthdate date  NULL ,portal_name varchar(255)  NULL ,portal_app varchar(255)  NULL ,website varchar(255)  NULL
 , PRIMARY KEY (id),   KEY idx_lead_acct_name_first (account_name, deleted),   KEY idx_lead_last_first (last_name, first_name, deleted),   KEY idx_lead_del_stat (last_name, status, deleted, first_n
ame),   KEY idx_lead_opp_del (opportunity_id, deleted),   KEY idx_leads_acct_del (account_id, deleted),   KEY idx_del_user (deleted, assigned_user_id),   KEY idx_lead_assigned (assigned_user_id),
 KEY idx_lead_contact (contact_id),   KEY idx_reports_to (reports_to_id),   KEY idx_lead_phone_work (phone_work),   KEY idx_leads_id_del (id, deleted)) CHARACTER SET utf8 COLLATE utf8_general_ci: M
ySQL error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 14000. This includes storage overhead, check the manual. You have to change some columns to
 TEXT or BLOBs
[root@web1 public_html]#

**Comment by highplainsdesignstudio** [comment]
Delete your database in PHPMyadmin (if you are using that) and recreate it using the correct collation. Then, retry the install using the new database. 
![db_collation](https://user-images.githubusercontent.com/26129966/37560014-ec8653bc-29f5-11e8-95bf-e733bdcca2a8.JPG)

Or else, here is a link to manually create the database with the proper character set and collation.
[https://dev.mysql.com/doc/refman/5.7/en/charset-database.html](url)

**Comment by praction1988** [comment]
HI All,

suitecrm by default using  CHARACTER SET utf8 COLLATE utf8_general_ci: because of this it is not able to create tables in the database. 

you can see the database CHARACTER SET utf8 COLLATE utf8_general_ci: is already set.

mysql> use praction_care
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8                     | utf8_general_ci      |
+--------------------------+----------------------+
1 row in set (0.00 sec)

mysql>


I want to use CHARACTER SET latin1 COLLATE latin1_swedish_ci; from suitecrm side, 




mysql> CREATE TABLE leads (id char(36)  NOT NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modified_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,salutation varchar(255)  NULL ,first_name varchar(100)  NULL ,last_name varchar(100)  NULL ,title varchar(100)  NULL ,photo varchar(255)  NULL ,department varchar(100)  NULL ,do_not_call bool  DEFAULT '0' NULL ,phone_home varchar(100)  NULL ,phone_mobile varchar(100)  NULL ,phone_work varchar(100)  NULL ,phone_other varchar(100)  NULL ,phone_fax varchar(100)  NULL ,primary_address_street varchar(150)  NULL ,primary_address_city varchar(100)  NULL ,primary_address_state varchar(100)  NULL ,primary_address_postalcode varchar(20)  NULL ,primary_address_country varchar(255)  NULL ,alt_address_street varchar(150)  NULL ,alt_address_city varchar(100)  NULL ,alt_address_state varchar(100)  NULL ,alt_address_postalcode varchar(20)  NULL ,alt_address_country varchar(255)  NULL ,assistant varchar(75)  NULL ,assistant_phone varchar(100)  NULL ,converted bool  DEFAULT '0' NULL ,refered_by varchar(100)  NULL ,lead_source varchar(100)  NULL ,lead_source_description text  NULL ,status varchar(100)  NULL ,status_description text  NULL ,reports_to_id char(36)  NULL ,account_name varchar(255)  NULL ,account_description text  NULL ,contact_id char(36)  NULL ,account_id char(36)  NULL ,opportunity_id char(36)  NULL ,opportunity_name varchar(255)  NULL ,opportunity_amount varchar(50)  NULL ,campaign_id char(36)  NULL ,birthdate date  NULL ,portal_name varchar(255)  NULL ,portal_app varchar(255)  NULL ,website varchar(255)  NULL  , PRIMARY KEY (id),   KEY idx_lead_acct_name_first (account_name, deleted),   KEY idx_lead_last_first (last_name, first_name, deleted),   KEY idx_lead_del_stat (last_name, status, deleted, first_name),   KEY idx_lead_opp_del (opportunity_id, deleted),   KEY idx_leads_acct_del (account_id, deleted),   KEY idx_del_user (deleted, assigned_user_id),   KEY idx_lead_assigned (assigned_user_id),   KEY idx_lead_contact (contact_id),   KEY idx_reports_to (reports_to_id),   KEY idx_lead_phone_work (phone_work),   KEY idx_leads_id_del (id, deleted)) CHARACTER SET utf8 COLLATE utf8_general_ci;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 14000. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
mysql>
mysql>
mysql>
mysql> CREATE TABLE leads (id char(36)  NOT NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modified_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,salutation varchar(255)  NULL ,first_name varchar(100)  NULL ,last_name varchar(100)  NULL ,title varchar(100)  NULL ,photo varchar(255)  NULL ,department varchar(100)  NULL ,do_not_call bool  DEFAULT '0' NULL ,phone_home varchar(100)  NULL ,phone_mobile varchar(100)  NULL ,phone_work varchar(100)  NULL ,phone_other varchar(100)  NULL ,phone_fax varchar(100)  NULL ,primary_address_street varchar(150)  NULL ,primary_address_city varchar(100)  NULL ,primary_address_state varchar(100)  NULL ,primary_address_postalcode varchar(20)  NULL ,primary_address_country varchar(255)  NULL ,alt_address_street varchar(150)  NULL ,alt_address_city varchar(100)  NULL ,alt_address_state varchar(100)  NULL ,alt_address_postalcode varchar(20)  NULL ,alt_address_country varchar(255)  NULL ,assistant varchar(75)  NULL ,assistant_phone varchar(100)  NULL ,converted bool  DEFAULT '0' NULL ,refered_by varchar(100)  NULL ,lead_source varchar(100)  NULL ,lead_source_description text  NULL ,status varchar(100)  NULL ,status_description text  NULL ,reports_to_id char(36)  NULL ,account_name varchar(255)  NULL ,account_description text  NULL ,contact_id char(36)  NULL ,account_id char(36)  NULL ,opportunity_id char(36)  NULL ,opportunity_name varchar(255)  NULL ,opportunity_amount varchar(50)  NULL ,campaign_id char(36)  NULL ,birthdate date  NULL ,portal_name varchar(255)  NULL ,portal_app varchar(255)  NULL ,website varchar(255)  NULL  , PRIMARY KEY (id),   KEY idx_lead_acct_name_first (account_name, deleted),   KEY idx_lead_last_first (last_name, first_name, deleted),   KEY idx_lead_del_stat (last_name, status, deleted, first_name),   KEY idx_lead_opp_del (opportunity_id, deleted),   KEY idx_leads_acct_del (account_id, deleted),   KEY idx_del_user (deleted, assigned_user_id),   KEY idx_lead_assigned (assigned_user_id),   KEY idx_lead_contact (contact_id),   KEY idx_reports_to (reports_to_id),   KEY idx_lead_phone_work (phone_work),   KEY idx_leads_id_del (id, deleted)) CHARACTER SET latin1  COLLATE latin1_swedish_ci;
Query OK, 0 rows affected (1.79 sec)

mysql>


You can check, i Just change CHARACTER SET and COLLATE and its done.

So there is any way that suitecrm go for CHARACTER SET latin1  COLLATE latin1_swedish_ci....


Thanks in Advance....

**Comment by pgorod** [comment]
@praction1988 can this issue be closed? Did you manage to install successfully?

**Comment by Dillon-Brown** [comment]
Will close for now, let me know if you are still encountering this issue and we can re-open. Thanks.
