### ISSUE TITLE
Headers in Reports design are undefined

### ISSUE THREAD

**Issue by goltra** [salesagility/SuiteCRM#5498]
When I acces to report designer I only see "undefined" in header as you can see in the picture. I'm using default languaje (English US).
I have Spanish installed too I happen the same.

![screen shot 2018-03-14 at 11 04 48](https://user-images.githubusercontent.com/1634767/37395858-950f7e9a-2777-11e8-8439-55948374e067.png)

**Comment by Pawes** [comment]
Did you try to rebuild the .htaccess as this user did #5298?

**Comment by goltra** [comment]
@Pawes Yes I did but I have the same result..

**Comment by Pawes** [comment]
Okay, did you also do a repair and rebuild + cleared your browser cache? I believe some of the language strings are in JavaScript files so the part about browser cache is also important.

**Comment by goltra** [comment]
@Pawes I did. Also I tried to access with other browser I never acceded to that website .. Anything can I try?

**Comment by goltra** [comment]
@Pawes I have seen I have some 403 refering to domain.com/cache/jsLanguage/AOR_Conditions/
I see jsLanguage have 770 .. but cache have 777 .. how can I prevent this?

Thanks.

**Comment by Pawes** [comment]
I don't know that specific problem, but your file permissions should be set like this according to the [SuiteCRM documentation](https://docs.suitecrm.com/admin/installation-guide/downloading--installing/):
```
    sudo chown -R www-data:www-data .

    sudo chmod -R 755 .

    sudo chmod -R 775 cache custom modules themes data upload config_override.php
```

Also you should check if your .htaccess file has any duplicate lines. There has been a bug earlier where it specifically duplicates the lines: 

```
<IfModule mod_rewrite.c>
    Options +FollowSymLinks
    RewriteEngine On
    RewriteBase /YOURURL
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]
</IfModule>
```
see isssue #5255 for more info.

**Comment by goltra** [comment]
oh, I haven't seen this .. I apply this and now seems is working fine..
thanks
