### ISSUE TITLE
Too many error Strict standards on master branch, is it normal

### ISSUE THREAD

**Issue by FHenry** [salesagility/SuiteCRM#55]
And on fatal on install process ather click on next (choose english, click next)

( ! ) Fatal error: Call to a member function error() on a non-object in /home/bobby/Eclipse/workspace/SuiteCRM/include/utils/sugar_file_utils.php on line 87
Call Stack
#	Time	Memory	Function	Location
1	0.0001	235008	{main}( )	../install.php:0
2	0.0089	3584256	require_once( '/home/bobby/Eclipse/workspace/SuiteCRM/jssource/minify.php' )	../install.php:69
3	0.0092	3613568	ConcatenateFiles( )	../minify.php:62
4	0.0093	3649256	mkdir_recursive( )	../minify_utils.php:142
5	0.0094	3650792	sugar_mkdir( )	../dir_inc.php:119

**Comment by fengsaofly** [comment]
I also met this kind of issue.Did you find a solution ? I did't find any installation guides.
this is what i met:
![image](https://cloud.githubusercontent.com/assets/4738938/9159587/ffba85be-3f5d-11e5-987a-c48f2d16156d.png)

it's not authority problem because I have changed dir authority to 777.

**Comment by willrennie** [comment]
Has this been improved in the latest releases? We have implemented fixes which resolve a lot of the strict standard errors.
