### ISSUE TITLE
Calendar Display Issue on Dashboard

### ISSUE THREAD

**Issue by murdal** [salesagility/SuiteCRM#550]
Displaying the side-bar on the dashboard is causing the Calendar to scramble, hiding the side-bar fixes the issue.

![calendardashlet](https://cloud.githubusercontent.com/assets/7024475/10394205/72eebbdc-6e8d-11e5-9cf5-9ae5379546bf.png)

**Comment by mattlorimer** [comment]
duplicate of #160
