### ISSUE TITLE
Personal Inbound Mail Account Load Error

### ISSUE THREAD

**Issue by kiril-vidi** [salesagility/SuiteCRM#5506]
When going to edit a user's inbound mail account, the Mail Accounts list does not load and instead shows "Data Error". 

#### Expected Behavior

The list of inbound email accounts load properly.

#### Actual Behavior

'Data Error' shows up in place of the list.

`Wed Mar 14 20:33:53 2018 [6558][3ebec55f-57cc-1bcd-8bbd-5a8bade8c046][FATAL]  Query Failed: INSERT INTO folders(id, name, folder_type, parent_folder, has_child, is_group, is_dynamic, dynamic_query, assign_to_id, created_by, modified_by, deleted) VALUES('3bec673b-67c1-45dc-0410-5aa987cea41f', 'SuiteCRM (Kiril's Group Email)', 'inbound', '', 1, 0, 1, '', '', '3ebec55f-57cc-1bcd-8bbd-5a8bade8c046', '3ebec55f-57cc-1bcd-8bbd-5a8bade8c046', 0): MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's Group Email)', 'inbound', '', 1, 0, 1, '', '', '3ebec55f-57cc-1bcd-8bbd-5a8bad' at line 1`
`Wed Mar 14 20:34:36 2018 [6534][3ebec55f-57cc-1bcd-8bbd-5a8bade8c046][FATAL] field_defs should be an array`
`Wed Mar 14 20:34:41 2018 [6534][3ebec55f-57cc-1bcd-8bbd-5a8bade8c046][FATAL] Exception handling in /var/www/html/suitecrm/include/MVC/Controller/SugarController.php:402`
`Wed Mar 14 20:34:41 2018 [6534][3ebec55f-57cc-1bcd-8bbd-5a8bade8c046][FATAL] Exception in Controller:  SugarFolder::retrieveFoldersForProcessing() Cannot Retrieve Folders - Please check the users inbound email settings.`

#### Possible Fix

Having an apostrophe in the name of the first item in the Mail Accounts list causes the above query to fail and error out. The inbound account 'seems' to save fine as you can go back and edit/load it in other modules if it's a group account. Either validate text fields on save to inform the user that certain characters are not allowed, or fix the query to allow for certain characters.

#### Steps to Reproduce

1. Create a new inbound email (doesn't matter if it's personal, group, etc.) with an apostrophe in the name.
2. Go to Mail Accounts tab under the email settings in any user's profile
3A. If that new inbound email is the only one they have access to, the bug should occur.
3B. If they have an active email already or the apostrophe email is not first in the list, then set the apostrophe email as the active one and deactivate all other emails.
4B. Refresh the page and go back to the Mail Accounts tab, the bug should occur.

#### Context

The problematic inbound account can be removed if it's a group email, but you have to go into the InboundEmail module.
Not sure if can be removed if it's a personal inbound account due to needing that list to load to be able to delete it. (Unfamiliar with SuiteCRM so there may be potentially a module I'm not thinking of to access personal inbound accounts.)
Detrimental due to shutting down all inbound email functionality for user(s) affected by it.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome the problematic inbound account
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): OSX High Sierra

**Comment by fcorluka** [comment]
I am in 7.10.7 version and must say Email and Inbound accounts are horrible.

1. view all emails -- NOT WORKING, must be something in search
2. set up SUPPORT inbound (group email, auto import, auto case creation) -- NOT SHOWN ANY EMAIL, no cases
3. set up PERSONAL inbound (only auto import) -- NOW I see all personal emails, some of my SUPPORT email and for some cases are created ,,, send new email - email is shown case not created
4. created new user -- NO EMAILS SHOWN, can not select any inbound mail accounts (the problem from this thread: ' Exception in Controller: SugarFolder::retrieveFoldersForProcessing() Cannot Retrieve Folders - Please check the users inbound email settings.')

I am not sure what was done to emails, but this is no good.

**Comment by code-ph0y** [comment]
Hi @kiril-vidi,

I have now supplied a fix for the issue you were experiencing (#6603), could you please test the fix has rectified the issue, as there were a lot of changes made for the fix, could you give the folders a good test also.

If there are any issues with the fix please let me know on the same post.

Thanks.
