### ISSUE TITLE
z-index error in studio

### ISSUE THREAD

**Issue by adzychester** [salesagility/SuiteCRM#5507]
#### Issue

This exists in the demo. The issue is detailed here: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/17281-screen-greyed-out-on-save-cannot-click-close-button#61904

Video of issue: https://youtu.be/jqW4BvYFGcs

#### Expected Behavior

The ability to close the dialog box is blocked by the z-index of the overlay

#### Actual Behavior

Overlay blocks mouse interaction on the screen

#### Possible Fix

remove the overlay completely

#### Steps to Reproduce

Seee Video: https://youtu.be/jqW4BvYFGcs

#### Your Environment

SuiteCRM 7.9.9
CLOUDLINUX 6.9 vmware v68.0.23
MySQL 5.6.36-cll-lve - MySQL Community Server (GPL)
PHP 7.0
Apache 2.4

This is happening in the SuiteCRM demo and in every browser

**Comment by Dillon-Brown** [comment]
@adzychester This should be fixed. I'm unable to replicate on hotfix or hotfix-7.9.x. Just as a temporary workaround you can right click on the page, inspect element and delete the element allowing you to then interact with the page.
