### ISSUE TITLE
Upgrade phpMailer to 6.x

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5508]
The phpMailer package we use in SuiteCRM is from the stale branch, 5.2. It is only compatible with PHP 5.0 - 7.0, is no longer being supported for feature updates, and will only be receiving security updates from now on. 

To upgrade, their Readme says

> The biggest changes are that source files are now in the `src/` folder, and PHPMailer now declares the namespace `PHPMailer\PHPMailer`. This has several important effects – read [the upgrade guide](https://github.com/PHPMailer/PHPMailer/tree/master/UPGRADING.md) for more details.

It demands a minimum PHP version of 5.5, but so do we, so that's not a problem.

We should go for the latest, 6.0.3, or at least 6.0.2 since that includes a fix specifically requested by me to their developer.

**Comment by connorshea** [comment]
@Dillon-Brown @samus-aran as mentioend here https://github.com/PHPMailer/PHPMailer/releases/tag/v5.2.27, the 5.2 branch of PHPMailer will only be maintained until the end of December 2018.

We should upgrade to 6.0 asap.

**Comment by Mausino** [comment]
@Dillon-Brown thanks for upgrade 
@samus-aran should it get label 7.11 Milestone? 
@pgorod should you plesea assign here the issues of users which will solved by upgrade that they should be closed or tested when stable relase 7.11 will created?

**Comment by pgorod** [comment]
I don't think there are any issues to be solved by this. It's just a matter of keeping up with the latest versions, so that we get all the bugfixes and especially, the security fixes.
