### ISSUE TITLE
Custom related fields' labels reset to default

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#551]
Hi,

My custom related field labels constantly revert back to default after Repair&Rebuild

http://screencast.com/t/wFq44X6lh0

I found the something on forum, but it doesn't help us.

https://suitecrm.com/forum/suitecrm-7-0-discussion/2562-renaming-relationship-label

Miky

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran 

This patch is working and was also assessed by other user.. should you merge it and shoud it be part of next milestone like 7.10+ and 7.11.1 ?

**Comment by Dillon-Brown** [comment]
@Mausino I'll take a look at creating some duplicate PR's for the other branches so we can get this merged in. Thanks!
