### ISSUE TITLE
7.10.2 Undefined Labels

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5513]
#### Issue

Studio still displays undefined labels in many places (same as 7.10.1)
Main panels show undefined in spinning ajax message
rebuilt htaccess, did quick rebuild and cleared browser cache after running upgrade from 7.10.1 to 7.10.2
#### Expected Behavior

Should display label in context.
#### Actual Behavior

displays undefined as label name
#### Steps to Reproduce

1. Use Studio
2.
3.
4.

#### Context

Started in 7.10.1
#### Your Environment

* SuiteCRM Version used: 7.10.2 (uggrade from 7.10.1 to 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest chrome
* Environment name and version (e.g. MySQL, PHP 7): LAMP PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS 7 64=bit

**Comment by samus-aran** [comment]
Hi @goingsmart 
Can you show a copy of your htaccess to confirm that it did rebuilt correctly?

**Comment by goingsmart** [comment]
found error in my htaccess settings (not SuiteCRM)
