### ISSUE TITLE
Email shown is not the good one

### ISSUE THREAD

**Issue by Fred5550** [salesagility/SuiteCRM#5516]
In the account module, contact subpage, email shown is the email from the account and not from contact.

Versions 7.10, 7.10.1, 7.10.2

**Comment by Fred5550** [comment]
https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18107-problems-with-version-7-10-1

**Comment by AdminPL** [comment]
Added this bug 10 days ago
https://github.com/salesagility/SuiteCRM/issues/5422

**Comment by samus-aran** [comment]
Resolved see #5422
