### ISSUE TITLE
Emails - attachments are being removed when selecting a template

### ISSUE THREAD

**Issue by jbrveen** [salesagility/SuiteCRM#5520]
#### Issue
When I click on Compose E-mail, I add an attachment and afterwards I select a template, the selected attachment is being removed. 

This happens in any case - when I create a new email, add an attachment and select a template, the attachment is removed. When I click on "Send a PDF" from invoiced and/or quotas, the attachment is there, after I select the template *poof* the attachment is gone. 

This happens whether the template contains an attachment or not

#### Expected Behaviour
It should leave the attachment in it's place. When the template contains an attachment, it should keep the manually selected attachment(s) (or the automatically added attachment from the function Send a PDF) ánd the attachment in the template. If the template doesn't contain an attachment, it should keep the manually selected attachment(s) or the automatically added attachment from the function Send a PDF. 

#### Actual Behaviour
It removes any existing attachment in the mail. It's like the "OK" gives a clean all attachments function before it loads the template. This clean all attachment function shouldn't exist at all. 

#### Possible Fix
Remove the clean all attachment function. I'm no programmer but I think I traced the issue back to  /modules/Emails/include/ComposeView/EmailsComposeView.js. This javascript does something with attachment after pushing OK when a template is selected

FYI I installed a clean instance of 7.8.17 (where this works perfectly fine) and also a clean instance of 7.10.2 (where this problem occurs). 

#### Steps to Reproduce

1. Compose e-mail
2. Add attachment
3. Select template
4. *poof* attachment gone

#### Context
High priority! I can't send invoices and/or quotas anymore with the selected template. This means a tremendous manual amount of work. 

#### Your Environment
* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any, 64 bit
* Environment name and version (e.g. MySQL, PHP 7): 
Env1. MariaDB 10.2, PHP7.2, Nginx 1.12.2, on Debian 9.4 
Env2. MariaDB10.0.32 PHP 5.6.33 and Nginx 1.10.3 on Debian 8.10

**Comment by PedroErnst** [comment]
@jbrveen 

Thanks for reporting this. I'm going to have a look.

**Comment by jbrveen** [comment]
@PedroErnst - this commit fixes the delete of the attachment but it causes another problem with attachment

Scenario 1: Not selecting a mailtemplate - attachments gets send. 
Scenario 2: Selecting a mailtemplate without attachment in template - attachments gets send.
Scenario 3: Selecting a mailtemplate with attachment in template - the attachment from the mailtemplate gets send. **The original attachment doesn't.** 

In all scenario's I can see all the attachments in the composer. So that works. However, in scenario 3 the original attachment doesn't get send, although it shows in the composer. 


Mailtemplate contains no attachment -

**Comment by ebogaard** [comment]
To fix the missing original attachment, I commentend out "ignoreParentAttachments", around row 1241:

```
      if (!isDraft) {
        $('<input>')
          .attr('type', 'hidden')
//          .attr('name', 'ignoreParentAttachments')
          .attr('value', '1')
          .appendTo($('.file-attachments'));
```

Not sure if this has any negative consequences, so just as a reference for others.
