### ISSUE TITLE
7.10.2 Setup SMTP Not Working

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5522]
#### Issue

ADMIN  Email Setup SEND TEST EMAIL not working (also issue in 7.10.1):

Send Test Email  Error:SMTP Error: Could not authenticate.

Also, setting Port gets overridden:

Set SMTP Port 465 SSL = None,  gets resets to SSL

ERROR LOG:
Fri Mar 16 15:45:38 2018 [941][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not authenticate.
Fri Mar 16 15:45:38 2018 [941][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not authenticate.
Fri Mar 16 15:45:38 2018 [941][1][ERROR] send: PHPMailer Exception: { <strong>SMTP Error: Could not authenticate.</strong><br />

#### Expected Behavior

Test Email should get sent.

This worked for this instance under 7.10.0 (upgraded starting with each release from 7.10 Beta)
#### Steps to Reproduce

1. ADMIN go to Email Settings
2.Send Test Email
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.2 (upgrade from 7.10.1)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): LAMP PHP 7.2
* Operating System and version (e.g Ubuntu 16.04):CentOS 7 64-bit

**Comment by highplainsdesignstudio** [comment]
Getting the same problem. I just did a fresh install of Version 7.10.2 Sugar Version 6.5.25 (Build 344). I am using Gmail to try to send a test email but getting:
`Sat Mar 17 05:57:14 2018 [19496][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not connect to SMTP host.`

I've made sure that the account and password is correct. I'm also using the 'admin' user account in the SuiteCRM installation.

**Comment by pgorod** [comment]
Don't you get a link in the message box that tells you there was an error, to "Show full SMTP log"? If you do, what does that show?

You can also uncomment this line:
https://github.com/salesagility/SuiteCRM/blob/master/include/SugarPHPMailer.php#L446

To get more information into the log. Raise your log level to DEBUG (or change that line to make the log level FATAL) to make sure you see it.

**Comment by goingsmart** [comment]
I do not get a link on Message Box to "Show full SMTP log" 
My Message Box: Send Test Email Error:SMTP Error: Could not authenticate.
ERROR LOG:
Fri Mar 16 15:45:38 2018 [941][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not authenticate.
Fri Mar 16 15:45:38 2018 [941][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not authenticate.
Fri Mar 16 15:45:38 2018 [941][1][ERROR] send: PHPMailer Exception: { SMTP Error: Could not authenticate.

**Comment by goingsmart** [comment]
I got the FULL SMTP LOG from Outbound Email Settings. is my problem due to my server timeout?

3: Connection: opening to mail.patientpathscloud.net:465, timeout=300, options=array (
)
3: Connection: opened
2: SERVER -> CLIENT: 
1: SMTP NOTICE: EOF caught while checking if connected
3: Connection: closed
3: SMTP Error: Could not authenticate.
3: SMTP Error: Could not authenticate.

**Comment by goingsmart** [comment]
This ERROR using port 465 and SSL:
3: Connection: opening to ssl://mail.xxxxx:465, timeout=300, options=array (
)
3: Connection: opened
2: SERVER -> CLIENT: 220-cloud1.xxxxxx.world ESMTP Exim 4.89_1 #1 Sun, 18 Mar 2018 22:38:37 -0700 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.

1: CLIENT -> SERVER: EHLO www.xxx.net

2: SERVER -> CLIENT: 250-cloud1.yyyyy.world Hello www.zzz.net [68.169.nn.nnn]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250 HELP

1: CLIENT -> SERVER: AUTH LOGIN

2: SERVER -> CLIENT: 334 VXNlcvvvvvXWU6

1: CLIENT -> SERVER: ---obfuscated---
2: SERVER -> CLIENT: 334 UGFzc3dvcmQ6

1: CLIENT -> SERVER: ---obfuscated---
2: SERVER -> CLIENT: 535 Incorrect authentication data

1: SMTP ERROR: Password command failed: 535 Incorrect authentication data

3: SMTP Error: Could not authenticate.
1: CLIENT -> SERVER: QUIT

2: SERVER -> CLIENT: 221 cloud1.xxxx.world closing connection

3: Connection: closed
3: SMTP Error: Could not authenticate.

**Comment by goingsmart** [comment]
MY BAD... the PWD and SMTP Settings I used were incorrect. 
THX. for responding.

7.10.2 is GREAT.
