### ISSUE TITLE
suitecrm logo changes not working from admin panel 

### ISSUE THREAD

**Issue by kanagaraj1305** [salesagility/SuiteCRM#5530]
#### Issue
suitecrm logo changes not working from admin panel

#### Expected Behavior
While uploading logo image in system settings in admin panel, it should be change in immediately.

#### Actual Behavior

While uploading logo image in system settings in admin panel, alert message is throwing invalid format png or jpg. But i am uploading png and jpg image only.

#### Possible Fix
include/utils.php file, check verify_uploaded_image function.
find given below code,
if (substr_count('..', $path) > 0 || ($ext !== $path && !isset($supportedExtensions[strtolower($ext)])) ||
            !in_array($filetype, array_values($supportedExtensions))
    ) {
        return false;
    }

command above the line,
replace the given below line,

if (!in_array($filetype, array_values($supportedExtensions))) 
	{
        return false;
	}

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 52.6.0
* Environment name and version (e.g. MySQL, PHP 7): PHP 7 AND Mysql 10.1.25-MariaDB
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by pgorod** [comment]
That condition might need to be fixed, but it shouldn't be dropped - it looks like a security verification.
