### ISSUE TITLE
Upgrading from 7.10.x to 7.10.2

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#5533]
#### Issue

I was trying to upgrade from 7.10.1 to  7.10.2 with this package:

https://suitecrm.com/files/161/SuiteCRM-7.10-Upgrades/252/SuiteCRM-Upgrade-7.10-to-7.10.2.zip

And the following message appears:

> The uploaded file is not compatible with this version of SuiteCRM: 6.5.25

In the manifest.php of the package:

```
  'acceptable_sugar_versions' => 
  array (
    'exact_matches' => 
    array (
      0 => '6.5.20',
      1 => '6.5.21',	
      2 => '6.5.22',
      3 => '6.5.23',
      4 => '6.5.24',
    ),
```

And in config.php I have these versions:

```
  'sugar_version' => '6.5.25',
  'suitecrm_version' => '7.10.1',

```
#### Expected Behavior

Upgrading without problem or a warning message because this is not the right place to do it.

#### Steps to Reproduce

1. Download upgrade package [from 7.10.x to 7.10.2](https://suitecrm.com/files/161/SuiteCRM-7.10-Upgrades/252/SuiteCRM-Upgrade-7.10-to-7.10.2.zip)
2. Upload it with "Module loader"
3. You will see the message: "The uploaded file is not compatible with this version of SuiteCRM: 6.5.25"

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 59
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0, MySQL 5.6
* Operating System and version (e.g Ubuntu 16.04): Debian 9

**Comment by Pawes** [comment]
@Abuelodelanada You should not be using the "Module loader" to upgrade SuiteCRM. Instead use the [Upgrade Wizard](https://docs.suitecrm.com/admin/installation-guide/using-the-upgrade-wizard/)

**Comment by Pawes** [comment]
@Abuelodelanada Ahh okay. I don't know what causes that that :)
