### ISSUE TITLE
SOAP web service calling function that does not exist

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#5534]
#### Issue

I run into this problem after making a REST call to method `set_relationships`. SoapHelperWebService.php, in the function `new_handle_set_relationship` is trying to call the function `getRelatedFields()` after loading a relationship. Loading the relationship calls `load_relationship()` in SugarBean.php. `load_relationship()` uses the class Link2.php, then the webservice tries to call `getRelatedFields()` from this class. Link.php contains `getRelatedFields()` but Link2.php does not. At some point the function was removed.

#### Expected Behavior

The function should be called

#### Actual Behavior

No function exists and I get a 500 internal error

#### Possible Fix

Add the function to Link2 or make an adjustment to the web service code

#### Steps to Reproduce

1. Make a rest call to the `set_relationships` method
2. Receive 500 internal error

#### Context

I was attempting to relate users to another module and cannot without adding in the function to Link2.php

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 65.0.3325.162 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySql, PHP 7
* Operating System and version (e.g Ubuntu 16.04):  Windows 10

**Comment by Dillon-Brown** [comment]
@wiatrp This should be fixed in 7.10.x latest. See #5325.
