### ISSUE TITLE
Datepicker (Calendar) not showing up in Mass Update

### ISSUE THREAD

**Issue by nejck-ikservis** [salesagility/SuiteCRM#5539]
#### Issue
When trying to Mass Update a Call or Ticket or anything that contains a date, there should be a datepicker (Calendar), that opens on a click of a button. Currently the button is there (not colored), but it doesn't do anything.

#### Expected Behavior
Click of a button should open a Calendar where we can pick date.

#### Actual Behavior
Click of a button doesn't do anything.

#### Possible Fix
Probably there is a mistake in calling Calendar javascript.

#### Steps to Reproduce
Calls->Select one or more->Bulk Action->Mass Update

#### Context
It should be an easy fix... Entering date in input works and saves, so it's only a Calendar popup issue.

#### Your Environment
* SuiteCRM Version used: 7.10.1 & 7.10.2
* Browser name and version: ALL
* Environment name and version: MySQL, PHP 7
* Operating System and version: Ubuntu 16.04

**Comment by AdminPL** [comment]
Confirmed on 7.10.2
