### ISSUE TITLE
GDPR: opt-in/opt-out action history

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#5549]
#### Suggestion

It seems SuiteCRM (7.10) currently does not save the date and time and trigger of the Opt-Out action. And it does not retain the opt-in history once opt-out is activated. This is not ideal for GDPR compliance.

Ideal in my view would be to track every opt-in and opt-out action separately (e.g. in its own table) with dates and times and action trigger source (CRM-user, customer-action). This would allow for GDPR compliant proofs by the data controller of what consent actions the customer has triggered over time. A customer could opt-in and opt-out multiple times, and it would be ideal to be able to reconstruct this action history.
see e.g. https://www.mailjet.com/gdpr/consent/#store-consent

This way the opt-in / opt-in status could be simplified in email_addresses table, probably only requiring one column (empty, single opt-in, opt-in confirmation pending, opt-in confirmed, opt-out) , leaving the full action history details to a separate table with the full compliance history for all email addresses.

As a first step I'd like to see:
- the addition of a column (in table email_addresses) – something like opt_out_date – to track when the opt-out trigger was set.
- the addition of a column (in table email_addreses) – something like opt_out_source – to track who triggered the opt-out setting (CRM user, or customer by clicking email-opt-out link)
- not deleting the opt-in history once opt-out is selected. Instead making the opt-in status dependent on opt_out column = 0 (opt-in data relevant) or = 1 (all opt-in data irrelevant). 

This would allow for at least tracking the history of the last opt-in and opt-out action.

#### Your Environment

* SuiteCRM Version used: 7.10.0

**Comment by samus-aran** [comment]
Hi @EZS-JD 
Thanks for your feedback!
Regards to the opt in/opt out they are being recorded on a separate email audit table (email_addresses_audit) in the database (we are looking to making this visible on GUI). This will record any changes made to the email address including, opt out, opt in and status of the confirm opt in and date modified and who applied it. This is based off the existing auditing functionality of other modules/fields and it was introduced 7.10.2.

I would suggest to upgrade and let us know that this meets your needs and we'll provide more details on the GUI to view those changes.

**Comment by EZS-JD** [comment]
Ah so I wasn't dreaming when I thought I had read something about making this visible in the GUI!
Very good news.

I had troubles getting 7.10.2 running for a while (works now), but will gladly test when you have the GUI-solution implemented!
