### ISSUE TITLE
generateJsonApiException() does not accept PHP Errors thrown by Slim

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#5555]
#### Issue

The Slim API framework potentially throws [PHP Errors](http://php.net/manual/en/class.error.php). (See, `Slim/App.php::handlePhpError()`) These make their way to the `ApiController::generateJsonApiExceptionResponse` function. This function type-hints an `\Exception` class. PHP throws a fatal error when an Error object is passed. 

#### Expected Behavior
When an error occurs, the details should be logged and a proper response should be returned

#### Actual Behavior
There is a 500 error

#### Possible Fix
`generateJsonApiExceptionResponse` should accept a `/Throwable` rather than an `/Exception` - both classes have the same API.

#### Steps to Reproduce
1. Authenticate with the v8 API
2. Send a POST to /api/v8/modules/Notes with the following body:
```json
{
  "data": {
    "type": "Notes",
    "id" : "123456789",
    "attributes": {
      "name": "test",
      "portal_flag" : 0
    }
  }
}
```
3. Due to a separate bug in 7.10.2 this will cause an error.
4. 500 error is returned. Nothing is logged to `suitecrm.log`.

#### Context
This should be a medium priority because it is an easy fix and it is important to log relevant errors. 

#### Your Environment
* SuiteCRM Version used: 7.10.2
* SuiteCRM API used: v8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7): PHP7, LAMP stack.

**Comment by daniel-samson** [comment]
As of SuiteCRM 7.10 - This was done intentionally. Throwable is only available in PHP 7 and above. We needed to be able to support PHP 5.5.9 and above. Exception is the base class for all Exceptions in PHP 5, and the base class for all user exceptions in PHP 7.

**Comment by tsummerer** [comment]
Ok. I suppose that makes sense. 

Would you be willing, then, to remove the Type hint? It's definitely going to throw a 500 error on PHP7 which is neither helpful nor proper. The error doesn't even get logged to the PHP log OR the suite log because `generateJsonApiExceptionResponse` doesn't get run due to the unaccepted type.

**Comment by zoltankocsardi** [comment]
@tsummerer we've changed the behavior of the API and working on it to make it better.
Could you test it in this branch please? #5806
The methods of sending calls have been changed as well, but there is a documentation for them [ https://github.com/salesagility/SuiteDocs/pull/90 ]

Thank you!
