### ISSUE TITLE
v8 API fails to throw 400 error when 'include' parameter is passed

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#5573]
#### Issue

The JSON API states:

> If an endpoint does not support the include parameter, it MUST respond with 400 Bad Request to any requests that include it.

Currently if you make a `GET` request to `/api/v8/modules/{module}/{id}?include={relationship}` there is neither a 400 error nor the included records. 
 
ModuleController.php is missing a single line of code which would enable the 400 error. 

```php
public function getModuleRecord(Request $req, Response $res, array $args)
{

  ######
  ##
  ##  There is currently no code which would set a value to " $query "
  ##
  ##  This line should be added :
  ##  $query = $req->getQueryParams();
  ##
  ######
    if(isset($query['include'])) {
        throw new BadRequest(
            '[ModuleController] [include query param is not implemented]', ExceptionCode::API_NOT_IMPLEMENTED
        );
    }

    if(isset($query['filter'])) {
        throw new BadRequest(
            '[ModuleController] [filter query param is not implemented]', ExceptionCode::API_NOT_IMPLEMENTED
        );
    }
```

#### Expected Behavior

When the `include` parameter is sent, either related records should be included OR a 400 error should be thrown

#### Actual Behavior

The response is identical to if the request did not include the `include` parameter

#### Possible Fix

Add this line to the `getModuleRecord` function:
`$query = $req->getQueryParams();`

#### Steps to Reproduce

1. Authenticate via v8 API
2. `GET` to`/api/v8/modules/Accounts/{id}?include=created_by_link `

#### Context

The Suite developer documentation alludes to the ability to use the 'include' functionality. But the application does not support it. 

#### Your Environment

* SuiteCRM Version used: 7.10.2
* SuiteCRM API used: v8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):na
* Environment name and version (e.g. MySQL, PHP 7): PHP7, LAMP

**Comment by samus-aran** [comment]
1. Investigate if relevant to V8

**Comment by Dillon-Brown** [comment]
No longer an issue in V8
