### ISSUE TITLE
Suitecrm Upgradation Help

### ISSUE THREAD

**Issue by jyotiraghav93** [salesagility/SuiteCRM#5575]
I need one urgent help and suggestion.

I have suitecrm version 7.7.6 having sugar version 6.5.24, this sugar version has some sort of vulnerabilities.

I would like to upgrade this sugar version from 6.5.24 to 6.5.26, remember CRM is SUITECRM.

Please let me know which upgrade package will be needed for this with download path.

**Comment by pgorod** [comment]
This is already being answered in the Forums, we should close this issue here. Thanks

https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18362-suitecrm-upgradation

**Comment by jyotiraghav93** [comment]
But I need the solution , how to upgrade this?

**Comment by pgorod** [comment]
@jyotiraghav93 trust me, you can close this Issue here (this is to report bugs to developers, the Forums are for discussions).

You will get your answer pretty soon in the Forums, I assure it is being dealt with. I'm just double-checking a few things. Thanks
