### ISSUE TITLE
Cannot enable ajax on module after disabling

### ISSUE THREAD

**Issue by ApatheticCosmos** [salesagility/SuiteCRM#5585]
#### Issue

If I disable ajax on a module, like 'Leads', I cannot enable it again by removing it from the list. When I drag a module from the disabled side to the enabled side, then save, it's back in the disabled side after leaving the 'Configure Ajax User Interface' page and returning to it.

#### Expected Behavior

I should be able to drag a module from the disabled side, and it should remain there after saving.

#### Steps to Reproduce

1. Go to the Administration page, then 'System Settings', and click the 'Configure AJAX User Interface' link
2. Drag the Leads module from the enabled side to the disabled side.
3. Save.
4. Go back to the main Administration page, then 'System Settings', and click the 'Configure AJAX User Interface' link
5. Drag the Leads module back to the enabled side.
6. Save.
7. Go back to the main Administration page, then 'System Settings', and click the 'Configure AJAX User Interface' link
8. Note that Leads is back on the Disabled side.

#### Context

I cannot enable Ajax on a module where it was previously disabled.

#### Your Environment

* SuiteCRM Version used: 7.10.1 (Clean Test Server)
* Browser name and version: Chrome 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.0.33-MariaDB, PHP 7.0.25-0ubuntu0.16.04.1
* Operating System and version: Ubuntu 16.04

**Comment by PedroErnst** [comment]
Thanks @ApatheticCosmos for reporting this.

I'm looking into it.

**Comment by PedroErnst** [comment]
@ApatheticCosmos 

Yes understood. 
The PR will be tested by someone on our team and if it passes it will be merged up into 7.10 as well in the next release.
