### ISSUE TITLE
Admin - Studio - Select Module - Labels

### ISSUE THREAD

**Issue by gray1st** [salesagility/SuiteCRM#5590]
When trying to change a label description, it doesn't matter which Module is selected, the same Labels are returned.

First Options are LBL_LOADING, LBL_HIDEOPTIONS, LBL_DELETE etc etc.

Version 7.10.2

**Comment by e-reeley** [comment]
Hi @gray1st 

Thanks for raising this issue, I believe this is the fix for the issue that you have mentioned [#5519](https://github.com/salesagility/SuiteCRM/pull/5519). This should be in the next release, or you can add it in if you would like it before.

Thanks again.
