### ISSUE TITLE
Can No Longer Assign Existing Client Contact to a Case (7.10.2)

### ISSUE THREAD

**Issue by stancel** [salesagility/SuiteCRM#5598]
#### Issue
Since upgrading to version 7.10.2, we are unable to assign existing contacts to a case. The UI option to create a contact is still there, but the UI option (down arrow) to select an existing contact is now missing. This is actually happening for all related modules, but for us the most pressing need is in the Cases module.

#### Expected Behavior
As in previous versions of SuiteCRM, there should be a UI option (down arrow) to the right of the "Create" button that opens a UI menu to search for and add an existing contact.

#### Actual Behavior
There is no UI option and no way to do it now except manually adding the records in the database. There are no errors thrown in the log.

#### Possible Fix
Re-add the down arrow to the right of the "Create" button in the UI for all related modules.

#### Steps to Reproduce
1. Open a case, go into the detailed view of that case
2. Scroll down to the related modules (below "Case Updates)
3. Expand the "Contacts" option to try and add an existing contact
4. Observe that there is no longer a way to do so, you can only create a new contact here
![suitecrm-missing-ui-option](https://user-images.githubusercontent.com/1058532/37911292-aa6a4e90-30dd-11e8-8777-055b3ceae6c8.png)

#### Context
We believe this should be a high priority bug as it affects many different parts of the application, not just Cases. Adding existing contacts to a case just happens to be a need that is very important to our organization and is affecting our ability to properly provide support.

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 65.0.3325.181
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by stancel** [comment]
Thank you @e-reeley. I have tried the "Quick Repair and Rebuild" option many times since we moved to 7.10.2. I thought that would be enough, but when I saw your response I tried all of the other "Rebuild *JS*" options in the Repair menu. Not sure which one worked but after they all completed and I did a hard refresh, the issue was resolved. Thank you very much for your time in responding and helping with the issue. Will close it now.

**Comment by e-reeley** [comment]
You're welcome @stancel !

Id like to think that it was potentially the Js repair that has done the trick, and then clearing the cache would have insured that you were not using anything that was potentially out of date.

Thanks for letting us know!
