### ISSUE TITLE
Make our upgrade packs from SugarCRM allow upgrades from 6.5.26

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5599]
#### Issue
See https://suitecrm.com/suitecrm/forum/installation-upgrade-help/10398-new-migration-pack-from-sugar-ce-to-suite-7-6?start=30#62575

Users trying to upgrade/migrate from SugarCRM 6.5.26 get an error from our upgrade package.

This is just a matter of updating our manifest/config file that checks versions. It's the last time we need to do it, there will be no further SugarCRM CE versions beyond 6.5.26, ever :-)

**Comment by dekelb** [comment]
SugarCRM removed all of their code from github, so the test (that probably requires the original code from SugarCRM repository) will fail.
Check here: https://github.com/sugarcrm/sugarcrm_dev

**Comment by pgorod** [comment]
@dekelb why do you think that code is necessary for us? We're just checking the version number in our installer, that's all (to my knowledge).

**Comment by dekelb** [comment]
If the test only checks version numbers (and not actual upgrade) it should pass, however if this is the case I really think the test is problematic and will not really give what you are looking for.

Anyway - I only added my two cents here.

**Comment by pgorod** [comment]
The issue of SugarCRM 6.5.25 versus 6.5.26, as it exists inside SuiteCRM code, is a bit intricate. You can read my explanations here: 
https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18362-suitecrm-upgradation

But the bottom line is, we don't need the changes they made in that upgrade, we have rolled our own, which will override theirs when you upgrade to SuiteCRM.

Actually the whole concept of "there's a SugarCRM version inside a SuiteCRM version" is about to disappear...

**Comment by pgorod** [comment]
Let's get rid of this, shall we?

https://github.com/salesagility/SuiteCRM/blob/master/modules/Home/About.php#L58

**Comment by gitbnw** [comment]
Just fyi - some vulnerability scanning software still picks up the Sugar CRM version and flags those 6.5.24 security issues.
