### ISSUE TITLE
"Eye" icon fails to display contacts detail from Dashlet

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5603]
#### Steps to Reproduce
1. Home screen, click Add Dashlet
2. Select `My Contacts` dashlet
3. On one of the displayed Contacts, click the Eye icon on the right
4. Blank screen!

`suitecrm.log` shows this:

```
Mon Mar 26 19:17:02 2018 [1049][1][FATAL] Exception handling in /var/www/html/include/MVC/Controller/SugarController.ph$
Mon Mar 26 19:17:02 2018 [1049][1][FATAL] Exception in Controller: Error retrieving record. This record may be deleted $
Mon Mar 26 19:17:02 2018 [1049][1][FATAL] backtrace:
#0 /var/www/html/modules/Users/views/view.detail.php(204): sugar_die('Error retrievin...')
#1 /var/www/html/include/MVC/View/SugarView.php(207): UsersViewDetail->display()
#2 /var/www/html/include/MVC/Controller/SugarController.php(432): SugarView->process()
#3 /var/www/html/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#4 /var/www/html/include/MVC/SugarApplication.php(109): SugarController->execute()
#5 /var/www/html/index.php(52): SugarApplication->execute()
#6 {main}
```

This is the link for that icon:
`http://10.0.0.200/index.php?action=DetailView&module=Users&record=2c613c05-58c7-bdca-0157-5a61bfb52394&offset=1&stamp=1522088560097903700&return_module=Home&return_action=index`

If I change the `module=Users` to `module=Contacts`, it works.

#### Expected Behavior
We should be taken to that Contact's detail view.

#### Environment
* SuiteCRM Version: 7.10.2, both on my test system and on the live demo

Maybe it's a good idea to check the link formation in the other Dashlets also...

**Comment by boombata** [comment]
Same than #5278

**Comment by boombata** [comment]
https://github.com/salesagility/SuiteCRM/pull/5320
