### ISSUE TITLE
PHPMailer - Error:SMTP Error: Could not connect to SMTP host - Issue - Version 7.9.16

### ISSUE THREAD

**Issue by donawick** [salesagility/SuiteCRM#5604]
#### Issue 
Our SMTP server worked and sent email notifications until we recently upgraded our server and I exhausted all of the known solutions that I can find.

#### Expected Behavior
It should send out notifications to our workers when files are uploaded or tasks are created via workflow.

#### Actual Behavior
The smtp says it cannot connect to host and does not send any emails. Logs aren't very helpful.

using gmail/smtp.gmail.com

Mon Mar 26 13:56:45 2018 [30644][5a39dda2-856b-c1a6-6342-5947fd70e0d0][FATAL] Notifications: error sending e-mail (method: smtp), (error: SMTP Error: Could not connect to SMTP host.)
Mon Mar 26 13:57:43 2018 [30788][f17c4352-fd31-c5bd-ee64-5aa69e323859][FATAL] Notifications: error sending e-mail (method: smtp), (error: SMTP Error: Could not connect to SMTP host.)

#### Possible Fix
I have tried the following solutions
- enable SMTP authentication with SMTPAuth
- made sure openssl is enabled & no firewall is blocking 587
- hardcoded the host/port/login information
- made sure certificate is not expired
- "Allow less secure apps" setting enabled
-  SMTPDebug = 2 done
- everything on this list https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**-** I've tried it locally, this works and sends the email notification like it should. I'm just not sure of what the issue _could_ be. Obviously it has something to do with out server, right?

#### Steps to Reproduce
Can only be produced on our server.

settings as follows:

FROM Name: SugarCRM Admin
FROM Address: no-reply@domain.com

SMTP Mail Server: smtp.gmail.com
SMTP Port: 587
SMTP Type
Enable SMTP over SSL or TLS?: tls
Use SMTP Authentication: Yes
Gmail Email: email@gmail.com
Gmail Password: xxxxxxxxxxx

#### Context
This issue has affected our daily business and I believe it is a medium priority issue since it is not necessarily a bug directly with SuiteCRM but perhaps our server. It did not happen until the most recent upgrade.

#### Your Environment
* SuiteCRM Version used: Version 7.9.16 (Sugar Version 6.5.25 (Build 344))
* Chrome & Safari (current release (64-bit)):
* Environment (MySQL, PHP 7):
* Ubuntu 16.04

**Comment by pgorod** [comment]
In 7.9.16, if I'm not mistaken, you already have the "Full SMTP log" available in the error message dialog box, when you send the test email. Can you post that log please?

Also, uncomment this line:
https://github.com/salesagility/SuiteCRM/blob/7.9.x/include/SugarPHPMailer.php#L425

and change that `debug` to `fatal`, then send a test email. Check the suitecrm.log to see if the data being used when contacting the server is what you're expecting or not.

**Comment by donawick** [comment]
Here is the log @pgorod, thanks for the help but I don't think the logs are very good -

Tue Mar 27 10:32:13 2018 [17596][942ded19-33b4-9bf7-3c1e-59d674226d27][FATAL] PHPMailer Send Function: { FromName: SugarCRM Admin From: no-reply@domain.net Host: smtp.gmail.com UserName: email@gmail.com }
Tue Mar 27 10:32:14 2018 [17596][942ded19-33b4-9bf7-3c1e-59d674226d27][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not connect to SMTP host.
Tue Mar 27 10:32:14 2018 [17596][942ded19-33b4-9bf7-3c1e-59d674226d27][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not connect to SMTP host.
Tue Mar 27 10:32:17 2018 [17322][f17c4352-fd31-c5bd-ee64-5aa69e323859][FATAL] Slow Query (time:2.4777579307556)

**Comment by pgorod** [comment]
I am talking about the extended log when you sent the test email, see my beautiful artistic hand-drawing below :-)

![image](https://user-images.githubusercontent.com/15945027/37975210-b5df349e-31d6-11e8-959b-be615f24350a.png)

Anyway, from what I see in your log, you are trying to use a different `From address` which doesn't match your Gmail user name. Gmail doesn't like that, I think that's why your not getting it to send.

**Comment by donawick** [comment]
Great drawing skills! Unfortunately mine does not have that option. 
![screen shot 2018-03-27 at 11 01 20 am](https://user-images.githubusercontent.com/17842174/37975915-4eaf47e6-31ae-11e8-8b24-1035d0395f64.png)

I have tried switching the FROM address to the same as gmail with no avail. It worked when we were on 7.7.9 and stopped once we upgrade to 7.9. Same server. :/

**Comment by pgorod** [comment]
It's after that screen - you fill in an address to send, send it, and when it gives a server error, it shows the button to see the Full SMTP log...

**Comment by donawick** [comment]
Sorry, I should have just sent the error message. 
![screen shot 2018-03-27 at 11 18 33 am](https://user-images.githubusercontent.com/17842174/37976918-9c274882-31b0-11e8-8792-f14458273557.png)

**Comment by pgorod** [comment]
I can't understand how 7.9.16 shows that message. It should let you click to see a full SMTP log. You don't have any custom code for `SugarPHPMailer.php`, I suppose?

Since you seem to appreciate my art, please have a look at the ~~screenshots~~ paintings here #5376 and tell me which screen you used to start the test? Does it make a difference if you use the other one? Thanks

**Comment by donawick** [comment]
It looks more like the 2nd screen (I'm using Admin->Email Settings under Outgoing Mail Configuration)

There shouldn't be any reason that the module isn't updated, but maybe that's the case.

Version 7.9.16
Sugar Version 6.5.25 (Build 344)

![screen shot 2018-03-27 at 11 40 07 am](https://user-images.githubusercontent.com/17842174/37978258-a504371e-31b3-11e8-8caa-dd1f1a06f6c9.png)

**Comment by pgorod** [comment]
I don't think you interpreted my art correctly, which is ok, since real art is open to several interpretations. :-)

My screens are both on the User profile, yours is in Admin / Outbound Email. 

But I also get a Full SMTP Log button there, so it seems our systems are different for some reason. I'm scratching my head over this one.

Do you want to try setting up the Email from the user profile to see if it makes a difference?

**Comment by donawick** [comment]
That's odd. I can see the full log when doing it from my user profile...

Here is the attempt -

`3: Connection: opening to ssl://smtp.gmail.com:465, timeout=300, options=array (
)
3: Connection: opened
2: SERVER -> CLIENT: 220 smtp.gmail.com ESMTP u133sm541382ywu.46 - gsmtp

1: CLIENT -> SERVER: EHLO http://66.76.123.XXX:9090

2: SERVER -> CLIENT: 501-5.5.4 HELO/EHLO argument "http://66.76.123.XXX:9090" invalid, closing
501-5.5.4 connection.
501 5.5.4  https://support.google.com/mail/?p=helo u133sm541382ywu.46 - gsmtp

1: SMTP ERROR: EHLO command failed: 501-5.5.4 HELO/EHLO argument "http://66.76.123.XXX:9090" invalid, closing
501-5.5.4 connection.
501 5.5.4  https://support.google.com/mail/?p=helo u133sm541382ywu.46 - gsmtp

1: CLIENT -> SERVER: HELO http://66.76.123.XXX:9090

2: SERVER -> CLIENT: 
1: SMTP ERROR: HELO command failed: 
3: SMTP Error: Could not authenticate.
1: SMTP NOTICE: EOF caught while checking if connected
3: Connection: closed
3: SMTP Error: Could not authenticate.`

**Comment by pgorod** [comment]
Ok, now we're getting somewhere!

See https://stackoverflow.com/questions/35783718/phpmailer-smtp-notice-eof-caught-while-checking-if-connected

**Comment by pgorod** [comment]
When you're finished solving the SMTP error, you might want to check your files against this PR which introduced the `Full SMTP Log Feature`: 
https://github.com/salesagility/SuiteCRM/pull/5077/files
and make sure you don't have customized versions of these files in `custom` directory.

**Comment by donawick** [comment]
Hmm, no luck yet. I've tried all of those... Do you think you could glance at my files and maybe offer some insight? (SugarPHPMailer.php & class.phpmailer.php)

https://pastebin.com/7bs03jD9

https://pastebin.com/t4XbrZpQ

It has to be something stupid that I'm missing.

**Comment by pgorod** [comment]
Those files look fine, if any one could be wrong it would likely be this one: 
`modules/OutboundEmailAccounts/OutboundEmailAccounts.php`

But it could be a bug, this is new code. Maybe there's something special about your case.

However, this issue with the files is only relevant to understand why the Full log isn't showing. But I guess that is not so important now, the big question is whether you were able to sort out your SMTP configurations and send email?

**Comment by donawick** [comment]
I was not able to send an email. The log shows the same error after trying different configurations. Even when trying to use ssl instead of tls.

**Comment by pgorod** [comment]
I see two possibilities: 

1. If there is a SuiteCRM bug, it has to be a UI bug making your settings not being passed correctly into phpMailer. This can easily be verified (or ruled out) by setting the values directly in the file and seeing if it solves the problem: 

https://github.com/salesagility/SuiteCRM/blob/7.9.x/include/SugarPHPMailer.php#L420-L424

You can add more values for the port, the authentication, etc. You can check a working Gmail example [here](https://github.com/PHPMailer/PHPMailer/blob/5.2-stable/examples/gmail.phps).

You can also simply print out more values into the logs to see if SuiteCRM is passing everything correctly.

2. If you rule that out, then it's likely a bug in your configuration. Sometimes these things get really tricky with DNS problems or certificate issues. In this case, you can ask for help at the [PHPMailer GitHub](https://github.com/PHPMailer/PHPMailer/issues/1388): if you open an Issue there with a full log, usually you will get excellent advice.

**Comment by donawick** [comment]
@pgorod Thanks for all the help. I will give both of those a try
