### ISSUE TITLE
Undefined variable $new_confirmed_opt_in

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5607]
#### Issue
In this file
https://github.com/salesagility/SuiteCRM/blob/master/include/SugarEmailAddress/SugarEmailAddress.php

the variable `$new_confirmed_opt_in` is undefined in some code-paths, but still assigned to another variable.

#### Steps to Reproduce
This might have other manifestations, but it was discovered in a forum thread mentioning Target imports.
https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18394-7-10-2-targets-import-error-new-confirmed-opt-in

#### Context
Given the other problems popping up in Email lately, with the same characteristic of having different behaviours for Admins and non-Admins, I would give this high priority to make sure we don't have any holes in this code.

#### Your Environment
* SuiteCRM 7.10.2
* PHP 7.0

**Comment by ittrium79** [comment]
I have 2 versions of SuiteCRM ( 7.10 and 7.10.2) on my cloud server (PHP 7.2.2), but this error during import i get **only on 7.10.2** (no matter admin or manager login).
I compare files SugarEmailAddress.php from 7.10 and 7.10.2 SuiteCRM and see the difference.
Variable $new_confirmed_opt_in was added in 7.10.2 version, but there is no implementation of it in method AddUpdateEmailAddress()  (line 1200)
So I just add the line  
$new_confirmed_opt_in = 0; 
And it's work fine for me.
