### ISSUE TITLE
Wrong JS File referenced in Contacts DetailViewDefs

### ISSUE THREAD

**Issue by jshwhitlow** [salesagility/SuiteCRM#5613]
#### Issue
Wrong file is referenced in modules/Contacts/metadata/detailviewdefs.php on line 151

Currently it says: 

```
'includes' => 
      array (
        0 => 
        array (
          'file' => 'modules/Leads/Lead.js',
        ),
      ),
```

#### Expected Behavior

It should say:

```
'includes' => 
      array (
        0 => 
        array (
          'file' => 'modules/Contacts/Contact.js',
        ),
      ),
```

#### Actual Behavior
Wrong JS file is loaded

#### Possible Fix
```
'includes' => 
      array (
        0 => 
        array (
          'file' => 'modules/Contacts/Contact.js',
        ),
      ),
```

#### Steps to Reproduce
1. Navigate to modules/Contacts/metadata/detailviewdefs.php on line 151
2. Look at code

#### Context
I was making some changes in my custom detailviewdefs.php and noticed that, I went back to ensure it wasn't just my instance and saw it was a SuiteCRM bug.

#### Your Environment
* SuiteCRM Version used: 7.10.1
* Browser name and version: 65.0.3325.181 64-bit
* Environment name and version: MySQL 5.7, PHP 7.1.12
* Operating System and version: macOS Sierra 10.12.3

**Comment by PedroErnst** [comment]
@jshwhitlow
