### ISSUE TITLE
API v8 filtering custom field

### ISSUE THREAD

**Issue by daniel-samson** [salesagility/SuiteCRM#5618]
#### Issue

See https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18407-api-filter-by-custom-field

when making a call like:
``` GET api/v8/modules/Accounts?filter[Accounts.firm_id_c]=[eq]12345678```

#### Expected Behavior

The SQL query should use accounts_cstm instead of accounts

#### Actual Behavior

suitecrm.log reports:
```
Error running count query for Account List:  Query Failed:  SELECT count(*) c FROM accounts  LEFT JOIN accounts_cstm ON accounts.id = accounts_cstm.id_c   LEFT JOIN  users jt0 ON accounts.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON accounts.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON accounts.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0  LEFT JOIN  accounts jt3 ON accounts.parent_id=jt3.id AND jt3.deleted=0

 AND jt3.deleted=0  LEFT JOIN  campaigns jt4 ON accounts.campaign_id=jt4.id AND jt4.deleted=0

 AND jt4.deleted=0 where (accounts.firm_id_c = 1) AND accounts.deleted=0: MySQL error 1054: Unknown column 'accounts.firm_id_c' in 'where clause'
```

#### Possible Fix

Fix FilterInterpreter::getFilterByAttributes() to check the if the field is the custom version and handle it accordingly

#### Steps to Reproduce

1. Set up api v8
2. make call`GET api/v8/modules/Accounts?filter[Accounts.firm_id_c]=`[`[eq`]`]12345678`
#### Context

high priority - there is no work around.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): na
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9 / Maria DB / Apache
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04

**Comment by w-** [comment]
Hi. I'm interested in this fix. Is there a page I can visit to learn that the release schedule is?

**Comment by w-** [comment]
sweet looks like it made it into 7.10.3

**Comment by mellkior** [comment]
Not working in 7.11.0
