### ISSUE TITLE
Emails truncated after apostrophes when hit Reply or Forward (SuiteCRM 7.10.2)

### ISSUE THREAD

**Issue by tech-ch1** [salesagility/SuiteCRM#5627]
There seems to be a problem in the email parser.
Emails with apostrophe are rendered properly, but on reply/forward, quoted mails are truncated.
This issue may be related to #5628 

#### Issue
- On a user account synced with an Imap mailbox (user@example.org)
- Using an external client, send an email to user@example.org with subject "Bla" and body "There is an apostrophe in this email. That's unfortunate."
- Using the user account, open the email and try to reply to it or to forward it.

#### Expected Behavior
- Quoted text should be "There is an apostrophe in this email. That's unfortunate."

#### Actual Behavior
- Quoted text is "There is an apostrophe in this email. That"

#### Context
After upgrading suitecrm to 7.10.2, tried to forward a mail. Raised a lot of issues, this is one (an other is that any click on Attach document/Attach file/Save draft/etc. actually sends the mail instead of doing what it's supposed to do, see #5628 .)
I feel this should be a high priority issue.

#### Your Environment
* SuiteCRM Version used: 7.10.2
* Browser name and version: Firefox 58, 59 and Chrome 65
* Environment name and version: MariaDB 10.0.32, PHP 5.6.33
* Operating System and version: Debian 8.10 (Jessie)

**Comment by PedroErnst** [comment]
Thanks for reporting this @tech-ch1 

This issue should be fixed with commit c8809c2c4abe646de064703884ff61d9ca223d67
