### ISSUE TITLE
API V8 Logout Function

### ISSUE THREAD

**Issue by brendanbell** [salesagility/SuiteCRM#5638]
#### Issue

With the new version of the API V8, there is no logout function available. I believe that previous versions of the API did offer this function.

This is not a high priority as the API token issued has a built in timeout value. So in some ways this negates the need for a logout.

The only case I could see for this may be where you have the API being called over and over to say synchronize data. This could cause lots of session tokens to be generated and then having to be managed by the suite application until expiration.

If the logout option was available, the calling client could tear down the session on completing the request, meaning more resources are available to suitecrm.

**Comment by zoltankocsardi** [comment]
@brendanbell we've changed the behavior of the API and working on it to make it better.
Could you test your problem in this branch please? #5806
The methods of sending calls have been changed as well, but there is a documentation for them [ https://github.com/salesagility/SuiteDocs/pull/90 ]

In your case this could be {{suitecrm.url}}/V8/logout.

Thank you!
