### ISSUE TITLE
7.10.1 - API V8 offsets for pagination are incorrect 

### ISSUE THREAD

**Issue by w-** [salesagility/SuiteCRM#5643]
#### Issue
On 7.10.1 consuming the JSON API to do simple list operations, it appears that pagination is incorrectly implemented.

As a specific example, i'm sending a GET request for all accounts that were modified after 2018-02-01
`api/v8/modules/Accounts?filter[Accounts.date_modified]=[[gte]]2018-02-01&fields[Accounts]=name`

I'll receive in the response
```
{
    "links": {
        "self": "<baseUrl>api/v8/modules/Accounts?filter%5BAccounts.date_modified%5D=%5B%5Bgte%5D%5D2018-02-01&fields%5BAccounts%5D=name%2C&page%5Boffset%5D=0",
        "next": "<baseUrl>/api/v8/modules/Accounts?filter%5BAccounts.date_modified%5D=%5B%5Bgte%5D%5D2018-02-01&fields%5BAccounts%5D=name%2C&page%5Boffset%5D=1",
        "last": "<baseUrl>/api/v8/modules/Accounts?filter%5BAccounts.date_modified%5D=%5B%5Bgte%5D%5D2018-02-01&fields%5BAccounts%5D=name%2C&page%5Boffset%5D=3"
    },
    //.....data with 100 records
    "meta": {
        "offsets": {
            "current": 0,
            "count": 3
        },
        //...        
    },
    //..

```

From here it if we look at `meta.offsets`, it appears that offsets is analogous to a "page" and that we have a total of 4 pages (0-based-page-index). (i.e. we got back 100 records so it is unlikely that the server is reporting only a total of 3 records)

The next page can be retrieved from `links.next` and if we scrutinize the query params, we control what page we want via the `page[offset]` query param.

#### Expected Behavior
When I make a request to the URL in `links.next` I expect to get a the next page of results. i.e. if on `offset=0` I got records 1-100, I expect `offset=1` to give me records 101-200.

#### Actual Behavior
following `links.next` i get 100 records back but they are records 2-101. i.e. `page[offset]` does in fact work exactly as you expect offset to work except everything leading up to this point makes you believe that `offset` is analogous to page. 

Also there is no way to jump to the next "page" of records. The consumer must calculate this themselves and there is also no way of knowing if we have exhausted all pages besides making a request and testing if `data` is null.

Generally we should be able to determine these using `links.next`

#### Possible Fix
I tried to look at the code but am too tired. It must be how we are  calculating stuff here
https://github.com/salesagility/SuiteCRM/blob/master/lib/API/v8/Controller/ModuleController.php#L368

IMHO, keeping the literal meaning of offset is fine, we just need to fix them to be consistent with the intention.

#### Steps to Reproduce
1. make a get request where expected results is > 100
2. observer `links` and `meta.offsets` values

#### Context
High Priority. Basic Functionality
I now have to implement my own workaround for paging.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): unknown

**Comment by zoltankocsardi** [comment]
@w- Could you test this in the same branch I've mentioned before please? #5806
You could use "page" => ?page[size]=4&page[number]=4

Thank you!

**Comment by w-** [comment]
Hi Zoltan,

I took your branch 
https://github.com/zoltankocsardi/SuiteCRM/tree/feature/refactor-api

and have it deployed in our dev env.
![image](https://user-images.githubusercontent.com/357317/39807790-6bce5c34-53a7-11e8-97af-9474624d22a8.png)

It doesn't look like anything has changed? I still am seeing the same issues. 

We have a local repo of suitecrm we maintain. I took the latest from your branch above and copied it over our existing repo. I can see your code changes in the source.
Is there something else I need to do?

**Comment by samus-aran** [comment]
@w- (btw <3 your avatar)
Few things to to when you pull down Zoltan's branch is to update composer and rebuild your htaccess (which you discussed previously) which you can do via the Admin Panel > Repair > rebuild htaccess (makes it easier to do there than manually).
