### ISSUE TITLE
Version 7.10.3 patch incompatible with version 7.10.2

### ISSUE THREAD

**Issue by edmondklai** [salesagility/SuiteCRM#5645]
#### Issue
Version 7.10.2 has a Sugar version of 6.5.25 (Build 344).  Manifest version only goes up to 6.5.24.

#### Expected Behavior
Patch should work

#### Actual Behavior
Error message: The uploaded file is not compatible with this version of SuiteCRM: 6.5.25

#### Possible Fix
Add 6.5.25 in the manifest. 

#### Steps to Reproduce
Upload 7.10.3 patch from 7.10.2 instance

**Comment by gunnicom** [comment]
Related: https://github.com/salesagility/SuiteCRM/issues/5599

**Comment by samus-aran** [comment]
@edmondklai The upgrade packs have been updated. Thanks for raising this! Make a comment if the issues hasn't been resolved and the issue will be re-opened.
