### ISSUE TITLE
Popup view does not look for custom popup picker

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#5655]
#### Issue

The MVC view `view.popup.php` does not search for a custom popup picker before loading it around line 224.

#### Expected Behavior

The view should search for a custom popup picker before loading the default popup picker

#### Actual Behavior

The view loads the default popup picker without looking for the custom popup picker

#### Possible Fix

Search for a custom popup picker first

#### Steps to Reproduce

1. Add a `Popup_picker.php` file to any module in custom code
2. Load a popup. In this case, I am using a custom Audit module/popup for the view change log.
3. The base popup picker code is used

#### Context

I need to customize my view change log and tried to load custom popup picker code for the Audit module. Instead, I now need to load a custom `view.popup.php` in my custom Audit code in order to load this popup picker

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):

**Comment by edmondklai** [comment]
I think this might be related.  When changing the Popup Search for a module in Studio, the changes doesn't get pick up.  Changes in the Popup ListView get pick up.

**Comment by PedroErnst** [comment]
@wiatrp 

Thanks for reporting this. It is now changed.
