### ISSUE TITLE
When I go to Users ListView, multiple empty records are created in the database

### ISSUE THREAD

**Issue by crespo5** [salesagility/SuiteCRM#5657]
#### Issue

I am since 2 months developing a project over suitecrm, I 've detected some littles bugs and I've fixed them, but now I 've detected a several bug, I think. Every time that I list some modules like Users, in the email_addresses are added a lot of new empty rows. I tested it in a clear version of suiteCRM and it still appear, I hope that you conside to fix it. While I will try to find the origin of the bug and solve it to my version of the project.
#### Actual Behavior

Multiple empty records in `email_addresses` table.
#### Possible Fix

I dont know yet.
#### Steps to Reproduce

1. Go to users ListView
2. See the `email_addresses` table in the database
3. Look at the multiple empty records!

#### Context

I see the production database and now have around 16000 useless rows.
#### Your Environment

* SuiteCRM Version used: 7.10.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): In all browsers
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.21-0 &&  PHP 7.0.28
* Operating System and version (e.g Ubuntu 16.04): Ubuntu0.16.04

**Comment by crespo5** [comment]
Hello again, I debugged the code and I think that the problem cames from the class MailUI.php in these functions: getEmailAddressConfirmOptInTick  &&  getEmailAddressConfirmOptInTick

Please see the code and repair it! I can't allow 1.000+ new daily records in my client db!

**Comment by anhnhatuit** [comment]
Hi @crespo5 ,

Have you customized any logic hook on Users module? I'm using v7.10.2, I have reproduced as your describe. However, I not found any empty record in email_addresses table.

Thanks,
Nhat

**Comment by crespo5** [comment]
Hello @anhnhatuit ,

Yes, I customized the logic hooks of Users module but this not de problem. Now I install the lastest version available in your webpage (clean) and I have the same bug. But I watched in the ListView of Employees module. Now I go to reproduce it.

First we watch the table, email_addresses , and we only have the admin email.

![image](https://user-images.githubusercontent.com/32954108/38447077-b21b0630-39fb-11e8-8f77-ef91d4995c2d.png)

And now we execute a small script that refresh the page for example... ten times in one second.

`setInterval(function(){
  location.reload()
}, 100);`

And now we go back to email_address table and a lot of new empty records are created!

![image](https://user-images.githubusercontent.com/32954108/38447285-b15c48fc-39fc-11e8-99e0-01e982024b79.png)
![image](https://user-images.githubusercontent.com/32954108/38447296-c249be1a-39fc-11e8-952a-ea574d0250f9.png)

**Comment by anhnhatuit** [comment]
It's strange. Actually, I've seen some empty records in email_addresss table. Next, I clean all empty records and try reproduce. However, I not found any empty records created in email_addresses table after reproduce.

**Comment by crespo5** [comment]
In the latest version of SuiteCRM, empty records are created all the time ... you yourself even have detected empty records in your database.. I hope you fix it soon

**Comment by crespo5** [comment]
Hello @anhnhatuit ,

I tested your patch in my clean version and it works perfectly, it doesn't create new records anymore. Later I patched my customized version and it works perfectly yet. I hope that these modifications don't affect other functions of the program.

Thanks you.
