### ISSUE TITLE
Drop parenthesis does not work in 7.10.x

### ISSUE THREAD

**Issue by LEAP-nishit** [salesagility/SuiteCRM#5661]
#### Issue

When creating conditions the drop parenthesis does nothing.  

![example](https://user-images.githubusercontent.com/9854372/38360494-ad49f5ba-390d-11e8-9e49-b26bd304d632.gif)

#### Expected Behavior

Allow the use of parenthesis to group conditions. 

#### Actual Behavior

Nothing happens 
#### Steps to Reproduce

1. Go to report module
2. Create condition
3. Try to add parenthesis 

#### Context

Unable to create condition unless they are very basic. 
#### Your Environment

* SuiteCRM Version used: 7.10.3
* Browser name and version: Firefox 59.0.2 and Chrome 65.0.3325.181
* Environment: suiteondemand.com

**Comment by PedroErnst** [comment]
@LEAP-nishit 

Thanks for reporting this. The issue should be fixed now.

**Comment by MarathonMax** [comment]
so without upgrading I can't work around this issue, right? we have a self hosted SUITECRM server and I can't ask my IT guys to do this upgrade (well not just yet anyways).

**Comment by PedroErnst** [comment]
Maybe you could apply the fix from #5667 directly. The changes are very small and localized.

I definitely would recommend trying it in a test environment first though.

**Comment by MarathonMax** [comment]
Hmmm, I reading this post (https://github.com/salesagility/SuiteCRM/pull/5667) but I don't get how to apply the fix. I am a geek (a super geek!) but not an IT guy.

**Comment by PedroErnst** [comment]
On that page you have a tab called `Files changed`.  

Basically all you have to do is look at the line numbers, then find those same files in your installation and change the lines in question to match the changed ones.

But yes, there is a small chance to introduce bugs this way. The safe way is to use the upgrade pack to the most recent version.
