### ISSUE TITLE
Icon issues in Email Template attachments

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5665]
1. Attachment icon does not exist

2.  Document icon is deprecated (sugar_document.png)

![default](https://user-images.githubusercontent.com/5983672/38410576-9d5ee658-398d-11e8-84aa-d6eb8c8f6dac.png)

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by likhobory** [comment]
It's not that important, but deprecated icon  (sugar_document.png) is still present, it would be nice to update it.

![изображение](https://user-images.githubusercontent.com/5983672/62379132-03a99500-b54f-11e9-887c-4f919875be1b.png)

**Comment by Dillon-Brown** [comment]
Agreed, there are a few other missing and outdated icons in the admin page and studio/module builder that we should definitely clean up at some point as well.
