### ISSUE TITLE
Can't edit Email draft

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5679]
#### Issue
Saved text is not displayed in Edit View.

#### Steps to Reproduce

1. Type some text in new Email and save it in the draft folder
2. Select draft folder and open saved record.
3. Try to edit saved draft: Email body is empty

#### Your Environment

* SuiteCRM Version used: 7.10.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF (latest)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by Dillon-Brown** [comment]
Looks like it's an issue on 7.10.3 but it's been fixed in latest hotfix.

**Comment by likhobory** [comment]
>  it's been fixed in latest hotfix
Confirmed.
