### ISSUE TITLE
Contacts relationship to Accounts

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#568]
If I were in account(X) and added contact(Z) via the subpanel. Navigate to the detail view of the contact and you will see that it is related to it. Navigate to the detail view of account(x) and you can see that it has contact(Z) related to it.

If i were in account(Y) and then added contact(Z) via the subpanel there is a problem

The problem is that account (X) and(Y) both say that they contain contact(Z). However now, if you navigate to the detail view of the contact....it says it is related to account (Y) only. 

Perhaps display a warning message informing the user that contact is already associated to another account and ask user if they want to add the contact to the account anyways? Also show more than one account that a contact is related to? or not? 

Cheers

**Comment by samus-aran** [comment]
I would argue that OTB the Account Name is visible on the Contact list when selecting via the subpanel so in theory the user should really see that the contact is already related to an account.

However, there is nothing stopping a user from adding a contact to multiple accounts - but I don't think there should be.

On the list view it shows both relationships for the single contact identifying they are related to more than one account.
