### ISSUE TITLE
SuiteR Responsive Theme navigation bar

### ISSUE THREAD

**Issue by Eve-APG** [salesagility/SuiteCRM#569]
On very narrow screens (<340 px wide), typically on phone screens, the navigation bar gets on 2 rows instead of one, so that the search buttons and the menu buttons get on the main page, on top of the page content.

![suite_mobile_menu_bug](https://cloud.githubusercontent.com/assets/15142161/10514521/749c57da-734e-11e5-9cdb-8b37837def2d.png)

**Comment by willrennie** [comment]
Resolved in 7.5.1 release.
