### ISSUE TITLE
API V8 - Class 'SuiteCRM\\LangException' not found

### ISSUE THREAD

**Issue by w-** [salesagility/SuiteCRM#5691]
#### Issue

attempting to call the API with a query to a custom field after upgrade to 7.10.3 from 7.10.1 and I get a HTTP500.
In the suitecrm.log file i get this 
```
PHP Fatal error:  Class 'SuiteCRM\\LangException' not found in /var/www/html/lib/API/v8/Exception/ApiException.php on line 56
```

When I look at the source t looks like `use LangException` was introduced in this commit.
https://github.com/salesagility/SuiteCRM/commit/08cbb48538505d91d8a2351a6a70178e713aa53d

However, even in the tip of `master` I don't see any file called LangException inside of `lib` 

In fact I can't find the file LangException anywhere. I can't imagine this didn't fail when it was tested before release, so I must be doing something wrong. 

Can someone please help point me in the correct direction?

#### Expected Behavior
API should work.

#### Actual Behavior
I get this error
```
PHP Fatal error:  Class 'SuiteCRM\\LangException' not found in /var/www/html/lib/API/v8/Exception/ApiException.php on line 56
```

but no file `LangException` lives at /lib

#### Steps to Reproduce
1. Install 7.10.3
2. attempt api call querying a custom field.
3. get http500. look in suitecrm.log

#### Your Environment

* SuiteCRM Version used: 7.10.3  (upgraded from 7.10.1)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04):

**Comment by gymad** [comment]
If you have a SuiteCRM v7.10.3, it should contains a `LangException.php` in the `include` folder. Can you please check if it's exists and also the `composer.json` `'autoload'` part has a reference for the `include` folder? then you can run `composer update` command.

**Comment by w-** [comment]
Thank you for the prompt response @gymad 

My sys admin upgraded the system to 7.10.4. So i'm no longer able to test the 7.10.3 version.
In the 7.10.4 version I now get the error below. I'm suspecting something happened during the upgrade that is causing files to be missing (?)
I'm waiting to get access to this new instance now so that i can peek around the logs.

If you happen to know where i might look for this error, any information would be appreciated.

One other fact I'd like to communicate is that before and after the upgrade my sys admin is running repair and rebuild from the admin interface.


```{

        {
            "code": 0,
            "title": "Generate JSON API Response exception detected: InvalidArgumentException: Invalid HTTP status code (0)",
            "status": 400
        },
        {
            "id": "1",
            "links": {
                "about": null
            },
            "status": "200",
            "code": 0,
            "title": "JSON API Error",
            "detail": "JSON API Error occured.",
            "source": {
                "pointer": null,
                "parameter": null
            },
            "meta": {
                "about": "Exception",
                "class": "RuntimeException",
                "code": 0
            }
        }
    ],
```

**Comment by w-** [comment]
Ok. i must've mis read the error the first time around. I read it as if SuiteCRM had an error generating the JSON Error response. 

I'll update later today, but it seems like this is likely resolved.

**Comment by w-** [comment]
Ok. We can close this. It's resolved. 

Cheers,
