### ISSUE TITLE
Inbound email - IMAP folder list always empty

### ISSUE THREAD

**Issue by iacovlev-pavel** [salesagility/SuiteCRM#5694]
#### Issue
Inbound email - folder list always empty.
![sc01](https://user-images.githubusercontent.com/1787775/38560808-2a4ff77e-3cdf-11e8-803e-07b9fba88692.png)

#### Expected Behavior
IMAP Folder list is displayed in the dropdown.
![sc02](https://user-images.githubusercontent.com/1787775/38560945-7a563f08-3cdf-11e8-905a-b5fee566f617.png)

#### Actual Behavior
IMAP Folder list is empty

#### Possible Fix
The problem is in this line of code:
https://github.com/salesagility/SuiteCRM/blob/master/modules/InboundEmail/InboundEmail.php#L3167
this returns an empty string.
If I change `UTF7-IMAP` to `UTF7` this works as expected, I am not sure if this is a complete fix.

#### Steps to Reproduce
Add a new Inbound Email from gmail using IMAP.
This works on some other servers we have, so I think it's either OS or PHP related.

#### Context
Medium priority

#### Your Environment
Ubuntu: 16.04
SuiteCRM: Version 7.10.4
Sugar Version: 6.5.25 (Build 344)
PHP: 7.0.28-0ubuntu0.16.04.1

**Comment by Mausino** [comment]
@iacovlev-pavel @cscottiw do you have this issue in latest version 7.10.11 ?? because i tested it on my instance + softacolous demo and there was worked with any problem.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
