### ISSUE TITLE
Create Lead, First name and Title fields swapped

### ISSUE THREAD

**Issue by berijan** [salesagility/SuiteCRM#5697]
#### Issue

Just started to use suiteCRM and tried to create a Lead and then found the fields "First Name" and "Title" are swapped.

First Name; has a dropbox where You can select Mr, Ms, Mrs etc and in the web page source code it says field="first_name"

Title field has a text box

These fields are swapped. 

...//index.php?module=Leads&action=EditView&return_module=Leads&return_action=DetailView

#### Expected Behavior

The Field with Lead text "Title" should have the dropdown to select Mr, Ms, Mrs etc and use <div class="col-xs-12 col-sm-4 label" data-label="LBL_TITLE"> data.

The field First Name should have a textbox and be using <div class="col-xs-12 col-sm-2 label" data-label="LBL_FIRST_NAME">

#### Actual Behavior

Wrong fields are just for entering data 

#### Possible Fix

Update code with correct fields and connection to them

#### Steps to Reproduce

1. 
/index.php?module=Leads&action=EditView&return_module=Leads&return_action=DetailView

2. First Name field web soure code
<div class="col-xs-12 col-sm-12 edit-view-row-item">
<div class="col-xs-12 col-sm-2 label" data-label="LBL_FIRST_NAME">
First Name:</div>
<div class="col-xs-12 col-sm-8 edit-view-field " type="varchar" field="first_name" colspan="3">
<select name="salutation" id="salutation">
<option label="" value="" selected="selected"></option>
<option label="Mr." value="Mr.">Mr.</option>
<option label="Ms." value="Ms.">Ms.</option>
<option label="Mrs." value="Mrs.">Mrs.</option>
<option label="Miss" value="Miss">Miss</option>
<option label="Dr." value="Dr.">Dr.</option>
<option label="Prof." value="Prof.">Prof.</option>
</select>
&nbsp;<input tabindex="0" name="first_name" id="first_name" size="25" maxlength="25" type="text" value="">
</div>

</div>

3. Title field web soure code
<div class="col-xs-12 col-sm-6 edit-view-row-item">
<div class="col-xs-12 col-sm-4 label" data-label="LBL_TITLE">
Title:</div>
<div class="col-xs-12 col-sm-8 edit-view-field " type="varchar" field="title">
<input type="text" name="title" id="title" size="30" maxlength="100" value="" title="">
</div>

</div>

4.

#### Context

Enter data for a new lead

High prio since i suspect

![lead title](https://user-images.githubusercontent.com/38256779/38569325-3a63cc9c-3ceb-11e8-81f9-95fe5f9bc554.jpg)
![lead firstname](https://user-images.githubusercontent.com/38256779/38569326-3a850466-3ceb-11e8-8273-eefcbcad6109.jpg)

 data to be corrupt otherwise

#### Your Environment

* SuiteCRM Version used:
I'm using Version 7.10.4
Sugar Version 6.5.25 (Build 344)

* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Google Chrome Version 65.0.3325.181 (Officiell version) (64 bitar)

* Environment name and version (e.g. MySQL, PHP 7):
MySQL, PHP 7

* Operating System and version (e.g Ubuntu 16.04):
Hosted web hotel

**Comment by Dillon-Brown** [comment]
This doesn't look like a bug. There are two separate ID's here: "salutation" and "first_name" both contained in the same row. Both appear to be assigned correctly when creating a lead.
