### ISSUE TITLE
Small UI mis-alignments

### ISSUE THREAD

**Issue by evanevgram** [salesagility/SuiteCRM#5703]
#### Issue
In version 7.10.4 there's a few style differences and icon misalignment's and such in the theme. See the attached screenshot for a few highlighted. eg. dropdown icon on filters dropdown, red cross on going behind the fields list icon, the bulk action dropdown button being bigger than the 2 next to it and also different font variation, underlining of field sorting and icon seems odd and icon misalignment etc.  

![align](https://user-images.githubusercontent.com/38280904/38617476-113555ee-3d8f-11e8-8509-4737e63461b4.jpg)

#### Context
Issue is not a deal breaker and doesn't stop actual use of the system, but doesn't look very polished or professional.

#### Your Environment
Issue is found on https://demo.suiteondemand.com

**Comment by jsamelko** [comment]
Likewise here - the list view screens seem to be the worst, filter/selection/bulk buttons top and bottom are different sizes and text/icons are mismatched/misplaced. There's also an issue with the sidebar spacing in all modules where the 'View' and 'Import' buttons appear to overlap slightly and/or loose border formatting (this is primarily in Firefox):

![capture](https://user-images.githubusercontent.com/20054982/38650384-206e1592-3e2e-11e8-8610-d509f2a6bfe7.PNG)

As with the comment above, there's also some odd spacing between fields when in a detail view, appears that different field types have different spacing/padding?: 

![capture2](https://user-images.githubusercontent.com/20054982/38650873-dcdfa63a-3e30-11e8-806b-1f447f70e657.PNG)


* SuiteCRM Version used: 710.2
* Browser name and version: Firefox 59.0.2 (64bit), Edge 41.16299.371.0
* Environment name and version: MySQL Server 5.7 / PHP 4.7.4
* Operating System and version: Ubuntu 16.04 LTS

**Comment by odairbourscheidt** [comment]
In smaller screen results, such I use Ex: 1366X768 or 1440x900, the icons of the user and pending tasks are totally misaligned. 

[Look here](https://partnerpro-my.sharepoint.com/:o:/r/personal/odair_lidercrm_com/_layouts/15/WopiFrame.aspx?sourcedoc=%7B5577417f-b403-4565-b4f5-62a0b67dbe69%7D&action=default)
