### ISSUE TITLE
7.10.4 - Conditions in reports don't working

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5705]
#### Issue

You can't move the field to condition in reports 

Look on videoscreen https://www.screencast.com/t/eUXSfUqG

On forum other users have same problem: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18229-i-can-no-longer-create-conditions-in-reports

#### Expected Behavior

You should choose or create your own conditions

#### Actual Behavior

Before upgrade to 7.10 it was worked, and you are able see old conditions which you should remove from conditions, but you are not able to add new one to old report records or new one

#### Possible Fix

no idea

#### Steps to Reproduce

1. Crete report
2. To to condition tab
3. Try to create new condition

#### Your Environment

* SuiteCRM Version used: Official demo 7.10.4
* Browser name and version Chrome 65.x

**Comment by PedroErnst** [comment]
I think this is fixed in #5667

**Comment by Mausino** [comment]
@PedroErnst when we applied patch #5667 everything is working fine

**Comment by PedroErnst** [comment]
I think the PR was merged into hotfix the day after 7.10.4 was released. Look forward to see these changes in 7.10.5 :+1:

**Comment by Mausino** [comment]
I am closing the issue because was fixed in 7.10.5 and doen't appear anymore. 

@Dillon-Brown do you think that i can did reaserch at free time ??? and looks for other issues if were not missed and still are open but the solotion is far applied in SuiteCRM. I am rechecking now all my older tickets.
