### ISSUE TITLE
7.10.4 - Checkboxes are missing in downloaded PDF from Reports

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5706]
#### Issue

If you have in report checkboxes.. there are missing in downloaded PDF 

I have in two columns the checkboxes, in both are not showing

![2018-04-11_1558](https://user-images.githubusercontent.com/5773777/38621796-e486d140-3da1-11e8-8cc2-96eb320f8380.png)

![2018-04-11_1600](https://user-images.githubusercontent.com/5773777/38621802-e9e7cd60-3da1-11e8-9e2c-53273ef1ad76.png)

#### Steps to Reproduce

1. Create report where will checkbox field type
2. Download report to PDF

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version Chrome 65.x

**Comment by PedroErnst** [comment]
Thanks @Mausino I remember something similar not long ago with checkboxes in pdf format... I'll have a look.

I think maybe it would be good to hide those personal details from the screenshots, it looks like live data?

**Comment by ChangezKhan** [comment]
Hi folks, as @PedroErnst mentioned, there is definitely an issue with css. If you comment out this line `$pdf->WriteHTML($stylesheet, 1);`, available in `controller.php` file of `AOR_Reports` module, then you'll get to see checkboxes in report. Now, I am also trying to figure out the exact cause of this and possible solution.
