### ISSUE TITLE
Wrong path to milestone image

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5709]
Subj.

![default](https://user-images.githubusercontent.com/5983672/38637407-ba856820-3dd3-11e8-9553-6a60d5a516b4.png)

#### Your Environment

* SuiteCRM Version used: 7.10.4

**Comment by gagandeepp** [comment]
Is this still valid?
Then assign it to me

**Comment by pgorod** [comment]
No need to assign, just go ahead and make a PR. Thank you!
