### ISSUE TITLE
Dashlets not showing all columns until refresh in Responsive theme

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#571]
Browsers: Chrome 46.0.2490.71 (64-bit); Firefox 40.0.3
SuiteCRM 7.3.1 - SuiteCRM Responsive Theme
Debian 7; PHP 5.4.45; Zend Engine v2.4.0 with XCache v2.0.0; mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.2; Apache v2.2.22 

When returning to the Sales:Home; Marketing:Home etc. pages, the Dashlets (set up 2 side-by-side) do not show all the columns.  Occasionally on a refresh of the screen the missing/hidden columns will become visible.  

If you click on the Dashlet Edit on a Dashlet not showing all columns, then click on OK to close the edit dialog box, the correct number of columns is now shown.  

The missing columns can also be shown by refreshing (circle icon on dashlet) the Dashlet.

This screenshot shows the default view each time you go to the Sales:Home etc.
<img width="522" alt="screen shot missing columns" src="https://cloud.githubusercontent.com/assets/3494567/10523730/ea448f84-7349-11e5-951c-ba4a737362e3.png">

This shows which columns were missing/hidden until doing a refresh of the Dashlet.
<img width="521" alt="screen shot after refresh" src="https://cloud.githubusercontent.com/assets/3494567/10523731/ea4b7b50-7349-11e5-8058-10325b5fa3cd.png">

I believe that the correct behaviour for the Dashlet is to show the columns that you've set every time and not just after clicking the refresh or edit buttons.  This didn't happen in the default theme.

**Comment by willrennie** [comment]
This is not a bug. This is to do with your screen resolution, and the footables functionality being actioned at a specific resolution/screen size. Click the '+' icon to see all of the fields.

**Comment by bunk3m** [comment]
Thanks Will.
I'm using a retina screen MBP with 2880 x 1800 resolution so I'm curious to know what type of screen resolution is needed to see more columns on the dashlet??

I can't find this "+" icon either.  We talking about the same version here?
