### ISSUE TITLE
7.10.4 Dusk theme optimization

### ISSUE THREAD

**Issue by acoolov** [salesagility/SuiteCRM#5710]
Colors and spaces were better overall in 7.10 than in the later verions.

1. Overall the theme became even more squeezed to point where the list view lines are too tiny. 7.10 was perfect! 
2. Spaces between fields in modules became super tiny. Some fields started to blend with each other, some have tiny gaps, one different from another. Does not look professional. 7.10 was perfect!
3. Top right corner icons - Create, Search, Notifications, Profile are now crazy off the alignment. Especially the profile icon is now far off because of the profile name that appeared under it after 7.10.1. I tried all my computers and even your demo site. The icons are very miss-aligned. 7.10 was perfect!
4. Create button and all other buttons/menus that are orange color used to have white font, now it's black. White looked much much better in 7.10. Again 7.10 was perfect!

7.10.4
www.photobox.co.uk/my/photo/full?photo_id=500715710488
www.photobox.co.uk/my/photo/full?photo_id=500715709771

7.10
www.photobox.co.uk/my/photo/full?photo_id=500715709951
www.photobox.co.uk/my/photo/full?photo_id=500715709936

**Comment by samus-aran** [comment]
Hi @acoolov - I mentioned the issue with the images on the forum[ post.](https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18322-7-10-2-please-stop-changing-the-theme-again-and-again#63676)
We can't see the screenshots but you are able to upload them via github rather than using photobox.

**Comment by acoolov** [comment]
![7-10 screenshot](https://user-images.githubusercontent.com/38298689/38705083-5f10513c-3e76-11e8-943d-0367deb9fc60.jpg)
![7-10-4 screenshot](https://user-images.githubusercontent.com/38298689/38705084-5f210090-3e76-11e8-80d4-d8433dcb34dc.jpg)
![7-10-4 screenshot 2](https://user-images.githubusercontent.com/38298689/38705085-5f34a834-3e76-11e8-801f-473c3a3962cb.jpg)
![7-10 screenshot 2](https://user-images.githubusercontent.com/38298689/38705086-5f468090-3e76-11e8-9856-83f3d8dec0b1.jpg)

Here are the pictures I tried to attach in my above post.

**Comment by MTet** [comment]
I got the same problem, the grey background overlap. It always happens when looking at the line items of the detailview of a quote or contract. 
I posted this and more details in the forum: https://suitecrm.com/suitecrm/forum/developer-help/18807-show-borders-between-line-items-in-detailview
