### ISSUE TITLE
Oauth2 not working in 7.10.4 

### ISSUE THREAD

**Issue by LEAP-nishit** [salesagility/SuiteCRM#5711]
#### Issue

There are two issues here.

The first is on a clean instance of SuiteCRM the only Grant that seems to be generated is Client credential even though Password Grant is selected. 

Using the Client credential does not seen to work and results in the following error. Here is a response from Postman.  

![data](https://user-images.githubusercontent.com/9854372/38661053-d4433266-3e72-11e8-9435-3b8770778ed8.png)

#### Expected Behavior
Oauth2 authorization should work. 

#### Actual Behavior
Server responds as `unsupported_grant_type`. 

#### Steps to Reproduce

Issue 1
1. On clean instance of Suite 7.10.4 go to admin page -> OAuth2 Clients and Tokens
2. New Password Client
3. Enter name and secret and save. 
4. Notice that it shows as  `Allowed Grant Type:Client Credentials`

Issue 2.
1. On clean instance of Suite 7.10.4 go to admin page -> OAuth2 Clients and Tokens
2. Create new Client credentials client
3. Enter name and secret and save. 
4. Use client_id and secret and post to api/oauth/access_token? with parameters descried in [documentation ](https://docs.suitecrm.com/developer/api/version-8/configure-authentication/)

#### Context

Unable to interact from external application with CRM, an advertised feature that does not work. 

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser: Firefox 59.0.2 and Chrome 65.0.3325.181
* Environment name and version (e.g. MySQL, PHP 7): 
    * MariaDB 10.0.34
    * php: PHP 7.0.28
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.4 LTS

**Comment by zoltankocsardi** [comment]
@LEAP-nishit we've changed the behavior of the API and working on it to make it better.
Could you test your problem in this branch please? #5806
The methods of sending calls have been changed as well, but there is a documentation for them [ https://github.com/salesagility/SuiteDocs/pull/90 ]

Also, if you are using Postman, there is an easier way to get access token.

![](http://pix.toile-libre.org/upload/original/1525254837.png)

Thank you!

**Comment by prasadh13** [comment]
Even I am facing the same issue. How to setup using postman? I am unable to generate a new access token using postman. An example would be great.
Thanks!

**Comment by gymad** [comment]
Hi, in my case I successfully set up the postman and using Password type and Client Credential auth also using the fallowing steps:

**Comment by gymad** [comment]
Hey, in my case I successfully set up the postman and using Password and Client Credentials auth also, using the fallowing steps in my SuiteCRM instance folder:
```
$ openssl genrsa -out Api/V8/OAuth2/private.key 2048
$ openssl rsa -in Api/V8/OAuth2/private.key -pubout -out Api/V8/OAuth2/public.key
$ sudo chmod 600 Api/V8/OAuth2/p*.key
$ sudo chown www-data:www-data Api/V8/OAuth2/p*.key
```
also you will need an OAuth2 Client, call the URL: 
`{Your-SuiteCRM-URL}/index.php?module=OAuth2Clients` and add a new Client, for e.g:
![image](https://user-images.githubusercontent.com/13831178/45421448-f78dbe00-b684-11e8-9368-2e32c92e0ad4.png)
Postman settings:
Authorization -> Get New Access Token
![image](https://user-images.githubusercontent.com/13831178/45421502-2441d580-b685-11e8-8045-23d4e6f38f4f.png)
Click: Request Token
![image](https://user-images.githubusercontent.com/13831178/45421534-3f144a00-b685-11e8-9eae-cea465d25466.png)
Click: Use Token

I hope it's helps

Reference to the doc site: https://docs.suitecrm.com/developer/api/version-8/configure-suitecrm/
probably needs some update..
