### ISSUE TITLE
Alerts in the menu bar are not displayed with Night theme colour

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5712]
Subj.

![default](https://user-images.githubusercontent.com/5983672/38667909-761b465a-3e4b-11e8-810d-0efe5cc3871e.png)

#### Your Environment

* SuiteCRM Version used: 7.10.4

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by likhobory** [comment]
@Dillon-Brown 
I can replicate this issue  (ver. 7.11.7, Debian9/php 7.2)

**Comment by Dillon-Brown** [comment]
Confirmed latest hotfix (I must have no fully cleared my cache). Thanks!
