### ISSUE TITLE
7.8.16 Inbound Emails Not Importing From Time to Time

### ISSUE THREAD

**Issue by vkathirvel** [salesagility/SuiteCRM#5716]
#### Issue

We use SuiteCRM's Emails module to pull emails from our multiple Gmail accounts. This usually works fine. Occasionally and more recently, the Emails interface does not show any new emails. This lasts maybe 24 hrs and the emails start flowing in without any manual push. It seems like as if something clogs up and stops the emails from coming into the system.

#### Expected Behavior

Emails come into Gmail. They show as unread. These emails are pulled into SuiteCRM. Once pulled in, Gmail shows the emails as read. We can then access the emails in SuiteCRM and reply from here.

#### Actual Behavior

Emails come into Gmail. They are sitting as unread. The emails do not appear within SuiteCRM. However, checking the email_cache table, I see the emails there. Looks like they have been pulled into email_cache, but not into the next emails and emails_text tables.

The logs have no errors!

There are no issues with outgoing emails.

#### Possible Fix

Could this be related to the number of emails? We have about 20K emails inside the email_cache table.

#### Context

I'd like to pitch this as a high priority. The team here use SuiteCRM emails as the daily sales workflow and the emails not coming in puts the breaks on their workflow. Yes, they can check the emails via Gmail and then reply via SuiteCRM. Not ideal though.

#### Your Environment

* SuiteCRM Version used: 7.8.16
* Browser name and version: Google Chrome 65.0.3325.181 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.1.31-MariaDB, PHP 7.0.29
* Operating System and version (e.g Ubuntu 16.04): Not sure

**Comment by bmwtourer** [comment]
I experienced many issues like this since a very (I mean very) long time...
Note that I am monitoring about 10 different email addresses with the crm/case creation/assignation.
I found out that one of my mailbox had more than one thousand deleted emails in there,  so I removed them (cleaned up) and now the process is much more fluent.  I also discovered this morning what I think to be a bug that  report on #6494

**Comment by vkathirvel** [comment]
I have narrowed the issue to the scheduler locking up.

Check Inbound Mailboxes (function::pollMonitoredInboxesAOP) was sitting as running. I can see that this remains locked until the job timeout. Why it was locked up, I do not know, but releasing the job has started pulling the emails now.

Might be useful setting a short timeout via config_override.php
$sugar_config['jobs']['timeout'] = 3600;

**Comment by vkathirvel** [comment]
The reason for the scheduler getting stuck could be down to one email that came in with a future date. In email_cache, there was one email with 2023 as the sent year. I wonder if this triggered the lock. Could be that some emails have dates set in the near or far future causing this. Just a theory.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
