### ISSUE TITLE
Impossible to PATCH AOS_ modules via v8 API

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#5723]
#### Issue

V8 Api will not allow updates to various modules - namely the AOS_ modules (Products, Quotes, etc).

`ModuleController::updateModuleRecord` throws an error if `$bean->save()` does not return a truthy result. 

The AOS modules extend the `Sugarbean::save()` method. They call the `parent` method, but they do _not_ **return** it. Therefore, their `save()` method always returns `null`. 

#### Expected Behavior

PATCH to `/api/v8/modules/AOS_Products/{id}` with appropriate body should return a 200 response

#### Actual Behavior

A 400 error is returned:
```json
{
    "errors": [
        {
            "code": 8000,
            "title": "[SuiteCRM] [API] [SuiteCRM] [API] [ModuleController] [Unable to update record]",
            "status": 400
        }
    ],
    "meta": {
        "suiteapi": {
            "major": 8,
            "minor": 0,
            "patch": 0,
            "stability": "ALPHA"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

#### Possible Fix

EITHER: The AOS records should be updated to reflect the rest of the application:
```php
class AOS_Products extends AOS_Products_sugar {

    ...

    function save($check_notify=false){
        ...
        return parent::save($check_notify);  // existing code lacks the 'return'
    }

    ...
}
```

OR:
The ModuleController should not have this useless check:
```php
// ModuleController::updateModuleRecord
try {
    ## REMOVE THIS IF STATEMENT ##
    if (empty($sugarBean->save())) {
        throw new ApiException('[ModuleController] [Unable to update record]');
    }
} catch (Exception $e) {
    throw new ApiException($e->getMessage(), $e->getCode(), $e);
}
```

#### Steps to Reproduce

1. Find an existing AOS Product 
2. Using the v8 API, attempt to edit a field in it

#### Context

I am trying to perform CRUD operations on CRM records from an external system using the API

The issue is especially annoying because the records **do** get updated despite the error message

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7): LAMP with PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16

**Comment by zoltankocsardi** [comment]
@tsummerer Pleaswe, could you test this here #5806 as well as I've mentioned before?
There is a beanAliases.php [ Api/V8/Config/services/beanAliases.php ] for mapping bean names.

Thank you!
