### ISSUE TITLE
Map Area - Import Option Fails : An Error has occurred

### ISSUE THREAD

**Issue by brendanbell** [salesagility/SuiteCRM#5724]
#### Issue
When attempting to import Map Areas a dialog box appears with the words "An Error has occurred". No other information is provide to screen.

#### Expected Behavior
Open a step to select a file to import

#### Actual Behavior
When you select the Import Option, the dialogue appears.

I have checked in the apache logs. Nothing Found.
In the suitecrm.log the following message is found:

`Mon Apr 16 13:54:02 2018 [17124][4bf7ecd0-321c-b9b5-6ae8-5ac85ecf5643][FATAL] Exception handling in /var/www/suitecrm-production/include/MVC/Controller/SugarController.php:402
Mon Apr 16 13:54:02 2018 [17124][4bf7ecd0-321c-b9b5-6ae8-5ac85ecf5643][FATAL] Exception in Controller: There is no action by that name: Step1
Mon Apr 16 13:54:02 2018 [17124][4bf7ecd0-321c-b9b5-6ae8-5ac85ecf5643][FATAL] backtrace:
#0 /var/www/suitecrm-production/include/MVC/Controller/SugarController.php(553): sugar_die('There is no act...')
#1 /var/www/suitecrm-production/include/MVC/Controller/SugarController.php(1088): SugarController->no_action()
#2 /var/www/suitecrm-production/include/MVC/Controller/SugarController.php(465): SugarController->handleActionMaps()
#3 /var/www/suitecrm-production/include/MVC/Controller/SugarController.php(373): SugarController->process()
#4 /var/www/suitecrm-production/include/MVC/SugarApplication.php(109): SugarController->execute()
#5 /var/www/suitecrm-production/index.php(52): SugarApplication->execute()
#6 {main}
`

#### Possible Fix
Seems to be missing the Step to start the selection of a file to load.

#### Steps to Reproduce
1. Open the Map Area option from the menu
2. Select the Import option from the Right Hand menu.
3. A message box appears

#### Context

Trying to Import some map area data.

Low, priority, I can work around  this.

![suite-error-1](https://user-images.githubusercontent.com/1163263/38789593-a1941dee-417e-11e8-8ea4-9241f713e3ba.png)

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ChangezKhan** [comment]
@brendanbell , can you share url, when you click on "Import" button? I am sure, issue with url. I just want to confirm.
