### ISSUE TITLE
V8 API does not allow Models to have a 'type' field.

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#5725]
#### Issue

Several stock modules (such as Cases, Products, and Alerts) have a "type" field. The V8 API does not return this field in `GET` requests and completely fails during `POST` requests. 

#### Expected Behavior

When I do a `GET` to the Case/Alert/Product/etc module, I should be able to see the Type field for the various records. 

When I do a `POST` to create a Case/Alert/Product/etc with a value in the `type` field, the value should be persisted and returned.

#### Actual Behavior

During a GET, the 'type' field is not included in the `attributes`

During a POST, the following error is returned:
```json
{
    "errors": [
        {
            "code": 8010,
            "title": "[SuiteCRM] [API] [InvalidJsonApiResponse]  The property data is not defined and the definition does not allow additional properties",
            "detail": "Unable to validate the Json Api Payload Response",
            "source": {
                "pointer": ""
            },
            "status": 400
        }
    ],
    "meta": {
        "suiteapi": {
            "major": 8,
            "minor": 0,
            "patch": 0,
            "stability": "ALPHA"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

#### Possible Fix

I can't quite understand the problem - maybe something about how `schema.json` is configured?

#### Steps to Reproduce

GET:
1. Using Suite's GUI, create a Case record. Be sure to set a 'type'. Make note of the ID.
2. Using the v8 API, perform a GET to `api/v8/modules/Cases`. Note that the type attribute is not returned

POST:
1. Using the v8 API, attempt to create a Case with the following body:
```json
{
  "data": {
    "type": "Cases",
    "attributes": {
      "type": "user",
      "name" : "test",
      "account_name" : "test",
      "case_number" : 0
    }
  }
}
```
2. The record will be created (without a type), and an error is returned

#### Context

I'm trying to create Alerts and Products (which have a type field) via the API, but am unable to. 

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7): LAMP PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16

**Comment by tsummerer** [comment]
Ah nice. Sorry I missed that. @PedroErnst 

Forgive me for being a noob, but what are the social norms here - should I close this Issue? 
Is there anything I can do to influence the PR to be approved?
Thanks

**Comment by PedroErnst** [comment]
@tsummerer 

Absolutely not a problem, welcome aboard. There wasn't an issue open for this so I think it's correct to leave it open.

Also, the PR is not yet tested and assessed, maybe the proposed solution is not entirely satisfactory after all.

Once a PR is merged that solves this issue it will be closed automatically.
