### ISSUE TITLE
[language] Workflow module: Related module name is not translated  (Send Email action)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5728]
Subj.

#### Steps to Reproduce

1. Select some non-English langpack and login into system (tested with ru/pt languages)
2. Create some workflow record with Send Email action
3. Choose Related field as  types of recipient

![default](https://user-images.githubusercontent.com/5983672/38804030-9f1d84a6-4179-11e8-819a-4b2c51339feb.png)

#### Your Environment

* SuiteCRM Version used: 7.10.4

**Comment by PedroErnst** [comment]
@likhobory 

Thanks for pointing this out!
