### ISSUE TITLE
Password Security Settings - not all options are validated in 7.10.4

### ISSUE THREAD

**Issue by OlaInk** [salesagility/SuiteCRM#5731]
As SuiteCRM administrator, I want to mark all checkboxes in Password Security Settings in administration panel to manage password's requirements.
![image](https://user-images.githubusercontent.com/38221633/38805787-6bad3a96-4177-11e8-8a26-dc5e1259650c.png)

#### Issue

In Administration panel --> Password Managment --> Password Security Settings I marked all checkboxes and in field "Password minimum length" i wrote value "8". I saved this settings. Next I was trying to change password of one of users in his profile. I wrote short (4 letters) password that contains only lowercase letters. I was trying to save this settings.
![image](https://user-images.githubusercontent.com/38221633/38806580-0024c750-417a-11e8-99e2-a882636af036.png)

#### Expected Behavior
 Kind of notice/warning about lack of: uppercase, number, special characters and  min. 8 letters (according to current admin settings).

Additionally: when user resets his/her password, there should be also a validation that  complies with current admin settings.

#### Actual Behavior

I have only 2 warnings about new password:
1. About lack of lowercase/uppercase
2. Lack of number 
![image](https://user-images.githubusercontent.com/38221633/38806634-25b9918a-417a-11e8-8d21-a630788e63dc.png)
There is no warning about special character and minimum length.

Additionally, when I was trying to reset my password (according to Enable Forgot Password feature), there was no validation of password requirements, when I was setting new password after reset. So for example I set new password that contains only 3, lowercase letters.

#### Context

 
I think it's kind of bug with high priority, especially beacuse of RODO.
#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version : Chrome Version 65

**Comment by samus-aran** [comment]
Thanks for raising that @OlaInk 
I would 'technically' categorise this as two bugs one for being the validation on the user profile and one for the forgotten password.
However, back to the issues - can you confirm if you provide Uppercase characters & numbers when the password management settings have all four options selected that it passes successfully?

**Comment by OlaInk** [comment]
Yes, I can confirm that  when I wrote 1 uppercase and 1 number, saving of the new password was possible.
