### ISSUE TITLE
Just Installed and white page after login

### ISSUE THREAD

**Issue by RoyBellingan** [salesagility/SuiteCRM#5732]
Setup is completed without any problem, I than press next, perform login and white page...
The content of the page is https://gist.github.com/RoyBellingan/41991c4caeecd9a3a383c9ca21544b8d

Some cached file are loaded (the js) and than, after... about 2 seconds a call to
https://it2.seisho.us/index.php?module=Alerts&action=get&to_pdf=1
That receive as response 
 lost password

If I try to log intentionally with a wrong password happens the same... It does not matter if I use a non existent user

There is totally zero in the loggig (php is with E_ALL)

If I log the SQL this is what I got -> https://gist.github.com/RoyBellingan/6e4531e3443a5082b4128dad4c1d4f83

When I perform the "full" login instead sql log is -> https://gist.github.com

So it looks like it does not even try to check if that user exist or not... On this server I can not install xdebug to create a stack trace, I will now try and see on another machine.

No idea what to check next...

#### Steps to Reproduce
just go on https://it2.seisho.us/index.php and login with whatever

#### Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version Firefox 59, chromium 65
* Environment name and version : nginx 1.11.4 + phpfpm 7.0.14 + mariadb 10.2.13
* Operating System and version : suse 42.1

**Comment by horus68** [comment]
Please use the forum for problems related to your own install and setup.
It can be permissions, ownership, mariadb compatibility or other issue.
Enter here: https://suitecrm.com/suitecrm/forum/installation-upgrade-help

Github is to be used only when a bug is detected and can be replicated by more than one user.
