### ISSUE TITLE
7.10.4 Login screen lost password lost

### ISSUE THREAD

**Issue by Mark-Keating** [salesagility/SuiteCRM#5738]
On the main login screen the "lost password" function does not appear.

#### Issue

Lost password functionality missing, significant support issue

#### Expected Behavior

On invalid password should show "lost password"  that can be used to recover password by user.

#### Actual Behavior

Nothing

#### Possible Fix

re-enable function on login screen.

One noticeable thing on 7.8 is that when the lost password button is clicked the additional fields appear below the current screen and depending on the screen size it looks like nothing happens. On clicking the "lost password" button the screen should scroll to display the fields as new users don't thing it does anything while it actually does, they just have to scroll down a bit. 

#### Steps to Reproduce

1. put in valid user
2. put in bad password
3. look for "Lost Password" URL
4. call for help

#### Context

High priority for large sites, 

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FireFox 64 latest(linux)
* Environment name and version (e.g. MySQL, PHP 7): yes
* Operating System and version (e.g Ubuntu 16.04): yes

**Comment by PedroErnst** [comment]
Hi @Mark-Keating 

I can't seem to reproduce this, unless I'm missing something.

Introduce bad password:

![image](https://user-images.githubusercontent.com/34056696/38879655-caf4c16a-425b-11e8-854e-33127ed7217f.png)

Click forgot password link

![image](https://user-images.githubusercontent.com/34056696/38879683-df572882-425b-11e8-9bc8-408dbe5c2b50.png)
