### ISSUE TITLE
SuiteCRM Unable to login due to password change box

### ISSUE THREAD

**Issue by gray1st** [salesagility/SuiteCRM#5743]
I'm using the Uninvention appliance which has left me somewhat limited as to what I can do..  SuiteCRM users authentication is linked to our Active Directory, which initially worked fine.. However, we are now getting the password change box, but when inputting the password and new password it doesn't change. instead the error... Incorrect current password for [user]. Re-enter password information...

Any ideas, as at present no-one can login to CRM... And i'm guessing its a change in the Admin section that is required.

**Comment by willrennie** [comment]
I would advise you contact the Univention team directly or visit our forums/support pages for this request as this is not a bug specific to the core application.
