### ISSUE TITLE
7.10.4 Default Icons not shown

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#5747]
#### Issue

For some reason the CSS didn't compile completely/correctly and in 7.10.4 the Default Icons are not shown in Subpanels. 

This affects instances that have custom modules. 

I've tried hard resets, etc. 

The default icon is set in `suitepicon.scss` with this rule:
```scss
[class*="suitepicon-module"]:before,
.suitepicon-module- {
    @extend .suitepicon-module-default;
}
```

If you search within the compiled css (`/themes/SuiteP/css/Day/style.css`) for the string "`[class*="suitepicon-module"]:before`" you will not find anything.  This leads me to believe that it did not compile correctly. 

#### Expected Behavior

Custom modules should display the default icon (3d cube) in Subpanels

#### Actual Behavior

Custom modules have no icon

#### Possible Fix

It seems that this commit compiled the problematic css 7cbcec156d13d2446177d9e4049c925443db64ac
#### Steps to Reproduce

1. Install a custom module into Suite 7.10.4
2. Go to a module that has a relationship with this custom one
3. Check if the subpanel has an icon

#### Context

My instances have several custom modules. The subpanel list looks funny when several of them have no icons. 

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): LAMP PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubunto 16

**Comment by topesantos** [comment]
I had the same problem and I changed (not upgrade safe) \include\ListView\ListViewData.php:
++611
        //$jscalendarImage ='<span class="suitepicon suitepicon-action-info" title="'.$app_strings['LBL_ADDITIONAL_DETAILS'].'"></span>';
        $jscalendarImage = SugarThemeRegistry::current()->getImageURL('info_inline.gif');
++616
				//. " style='position: relative;'>$jscalendarImage</span>";
				. " style='position: relative;'><img vertical-align='middle' class='info' border='0' alt='".$app_strings['LBL_ADDITIONAL_DETAILS']."' src='$jscalendarImage'></span>";

++651
	            //$extra .=  "<a title=\'{$app_strings['LBL_EDIT_BUTTON']}\' href={$results['editLink']}><span class=\'suitepicon suitepicon-action-edit\'></span></a>";
	            $extra .=  "<a title=\'{$app_strings['LBL_EDIT_BUTTON']}\' href={$results['editLink']}><img style=\'margin-left: 2px;\' border=\'0\' src=\'".SugarThemeRegistry::current()->getImageURL('edit_inline.png')."\'></a>";

++656
	        //$extra .= (!empty($results['viewLink']) ? "<a title=\'{$app_strings['LBL_VIEW_BUTTON']}\' href={$results['viewLink']}> <span class=\'suitepicon suitepicon-action-view-record\'></span></a>" : '');
	        $extra .= (!empty($results['viewLink']) ? "<a title=\'{$app_strings['LBL_VIEW_BUTTON']}\' href={$results['viewLink']}><img style=\'margin-left: 2px;\' border=\'0\' src=".SugarThemeRegistry::current()->getImageURL('view_inline.png')."></a>" : '');

++661
            	//$extra .=  "<a title=\'{$app_strings['LBL_ADDITIONAL_DETAILS_CLOSE_TITLE']}\' href=\'javascript: SUGAR.util.closeStaticAdditionalDetails();\'> <span class=\'suitepicon suitepicon-action-clear\'></span></a>";
            	$extra .=  "<a title=\'{$app_strings['LBL_ADDITIONAL_DETAILS_CLOSE_TITLE']}\' href=\'javascript: SUGAR.util.closeStaticAdditionalDetails();\'><img style=\'margin-left: 2px;\' border=\'0\' src=\'".SugarThemeRegistry::current()->getImageURL('close.png')."\'></a>";

++666
            //$extra .= "',".$closeVal.")\"' class='info suitepicon suiteicon-action-info'>";
            $extra .= "',".$closeVal.")\" src='".SugarThemeRegistry::current()->getImageURL('info_inline.png')."' class='info'>";

**Comment by willrennie** [comment]
@tsummerer is this issue still valid for you in the latest releases? Updating due to issue being stale but do not want to close if this is still valid.

**Comment by tsummerer** [comment]
No. I have not seen the issue past 7.10.4
