### ISSUE TITLE
Deploy module changes from studio not applied immediately   

### ISSUE THREAD

**Issue by joseasrocha** [salesagility/SuiteCRM#575]
If we go to Studio, add some fields to a module, Accounts for example, and we customize a layout, even when we press "Save & Deploy", the changes are not applied.

The only way I could get them applied was by a "System Check" from the "Upgrade Wizard"

**Comment by darthtang** [comment]
https://github.com/salesagility/SuiteCRM/issues/380

**Comment by joseasrocha** [comment]
Thanks @darthtang

**Comment by darthtang** [comment]
No worries!
