### ISSUE TITLE
7.10.2 - API V8 Error running count query for OAuth2Tokens List (MSSQL)

### ISSUE THREAD

**Issue by lucas7793** [salesagility/SuiteCRM#5752]
#### Issue
Connecting to the API with grant_type client_credentials is possible, fails with grant_type password. All required parameters are set for the POST request.

#### Expected Behavior
Should return an access token to access the API.

#### Actual Behavior
Does return an error: 
`{
"errors": [
  {
"code": 1,
"title": "Database failure. Please refer to suitecrm.log for details.",
"status": 400
}
],
"meta": {
"suiteapi": {
"major": 8,
"minor": 0,
"patch": 0,
"stability": "ALPHA"
}
},
"jsonapi": {
"version": "1.0"
}
}`

According to the suitecrm.log there seems to be an error with the double quotation marks of the column access_token with MSSQL server. The value of access_token should be in single quotation marks.

Error log states:
`Thu Apr 19 12:02:24 2018 [25][1][FATAL] Error running count query for OAuth2Tokens List:  Query Failed: SELECT count(*) c FROM oauth2tokens   LEFT JOIN  users jt0 ON oauth2tokens.modified_user_id=jt0.id
AND jt0.deleted=0
AND jt0.deleted=0  LEFT JOIN  users jt1 ON oauth2tokens.created_by=jt1.id AND jt1.deleted=0
AND jt1.deleted=0  LEFT JOIN  oauth2clients jt2 ON oauth2tokens.client=jt2.id AND jt2.deleted=0
AND jt2.deleted=0  LEFT JOIN  users jt3 ON oauth2tokens.assigned_user_id=jt3.id AND jt3.deleted=0
AND jt3.deleted=0 where (access_token = "5029648bc2e7c4e57cd02f2a5af39d9a379a1de5e20f4498fbf9482c581eaa643aa1082c6ca1d0b2") AND oauth2tokens.deleted=0::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Ungültiger Spaltenname '5029648bc2e7c4e57cd02f2a5af39d9a379a1de5e20f4498fbf9482c581eaa643aa1082c6ca1d0b2'.
Thu Apr 19 12:02:24 2018 [25][1][FATAL] [ERROR] Database failure. Please refer to suitecrm.log for details.`
SQL Server Error messages states:
"Invalid column name : 5029648bc2e7c4e57cd02f2a5af39d9a379a1de5e20f4498fbf9482c581eaa643aa1082c6ca1d0b2"

#### Steps to Reproduce

1. Sending a POST request to /api/oauth/access_token with all required parameters
2. As answer the message above will be returned

#### Context

It's not possible to access the API with grant_type password.

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 65.0.3325.181
* Environment name and version (e.g. MySQL, PHP 7): MSSQL 12.0.5579.0,  PHP 7.0.27
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by lucas7793** [comment]
The same error also seems to appear if the access token is successfully requested with `grant_type` `client_credentials`.

Requesting `/api/v8/modules/meta/list` is returning the following message:
`{
"error": "unknown_error",
"message": "Database failure. Please refer to suitecrm.log for details."
}`
`suitecrm.log` shows the same error as in the inital post.

**Comment by zoltankocsardi** [comment]
@lucas7793 we've changed the behavior of the API and working on it to make it better.
Could you test it in this branch please? #5806 
The method of sending a call has been changed as well, but there is a documentation of these changes [ https://github.com/salesagility/SuiteDocs/pull/90 ]

Thank you!

**Comment by lucas7793** [comment]
@zoltankocsardi I could not make it work with these changes, it only returned a blank page? Maybe I did something wrong.

But I tried something else to make it work and that was a change back to PHP 5.6. Changed the db_manager from SqlsrvManager back to FreeTDSManager, and the access to the API is possible without SQL errors.
