### ISSUE TITLE
Single Opt In status not being saved

### ISSUE THREAD

**Issue by e-reeley** [salesagility/SuiteCRM#5753]
#### Issue

Single opt in status not being saved when a record is created or update on the system. If a record is being updated, for example in the contacts module. and an email address is added or already exists, and the user selects the 'Opt In' check box, this status will not save.

This issue also therefor impacts the ability to send Confirm Opt In bulk action emails within the list views.

#### Expected Behavior

When the 'Opt In' checkbox is selected, this status should save and remain persistent, and also be visible with the detail view, list view, edit view etc.

#### Actual Behavior

The status for being 'Opt In' is not saved, and therefor the record is not stored as being opt in, and within the edit view, the box is unchecked as before.

#### Steps to Reproduce

1. Have the system set up with confirmed opt in functionality,
    1.1. Navigate to the admin panel,
    1.2. Select 'Email Settings',
    1.3. Under the 'Email Options' panel, use the drop down box for 'Opt In Settings' and select Confirmed 
           Opt In,
    1.4. Save the settings,
2. Create a record or modify an existing record inside the Contacts module, can also be done with 
    Targets and Leads,
3. Beside the 'Email Address' field, select 'Opted In'. Save this record,
4. See that in the detail view, it is not shown that the record is Opt In,
5. Navigate to the list view. See that there is no indication of this record being 'Opt In',
6. If you navigate back to the edit view, the 'Opt In' checkbox will be unchecked.

#### Context

This impacts the 'Opt In functionality within the system. The bulk actions 'Send confirm Opt In' will not be possible, any way to find opt in records will not be possible.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by pgorod** [comment]
@e-reeley you might want to check out this tip here #5678, it's also related to Confirmed Opt-in (though it's not strictly related to this, it seems to be a display bug)

**Comment by Joao-Magalhaes** [comment]
In version 7.10.5 i created custom\modules\EmailMan\Save.php and added
#NKA guardar as opções de opt-in
$sugar_config[ 'email_enable_confirm_opt_in' ] = $_POST[ 'email_enable_confirm_opt_in' ];
$sugar_config[ 'email_enable_auto_send_opt_in' ] = $_POST[ 'email_enable_confirm_opt_in' ];
$sugar_config[ 'email_confirm_opt_in_email_template_id'] = $_POST[ 'email_template_id_opt_in' ];
$sugar_config[ 'system_email_templates' ][ 'confirm_opt_in_template_id' ] = $_POST[ 'email_template_id_opt_in' ];
#NKA

just before

ksort($sugar_config);
write_array_to_file('sugar_config', $sugar_config, 'config.php');

**Comment by Kristianostman** [comment]
@Joao-Magalhaes I do not have any Save.php! Should that be part of 7.10.5? You write that you created this file, but also that you added your code "just before" ksort.... so as I understand it you did have Save.php since before?? Could you please clarify.

**Comment by Joao-Magalhaes** [comment]
@Kristianostman: 
I copy modules\EmailMan\Save.php to custom\modules\EmailMan\Save.php. Then, changed this new file, adding the code:
#NKA guardar as opções de opt-in
$sugar_config[ 'email_enable_confirm_opt_in' ] = $_POST[ 'email_enable_confirm_opt_in' ];
$sugar_config[ 'email_enable_auto_send_opt_in' ] = $_POST[ 'email_enable_confirm_opt_in' ];
$sugar_config[ 'email_confirm_opt_in_email_template_id'] = $_POST[ 'email_template_id_opt_in' ];
$sugar_config[ 'system_email_templates' ][ 'confirm_opt_in_template_id' ] = $_POST[ 'email_template_id_opt_in' ];
#NKA

just before

ksort($sugar_config);
write_array_to_file('sugar_config', $sugar_config, 'config.php');

**Comment by Kristianostman** [comment]
@Joao-Magalhaes I do not have such file to copy (modules\EmailMan\Save.php ) . May I have a corrupt set of files after upgrade within Suite Admin?

**Comment by Kristianostman** [comment]
@Joao-Magalhaes I need to inform also that I have done the quite complex upgrade process from Sugar CE 6.5.14 to 7.10.5 (via several upgrades in between of course, all according to upgrade instructions). So if this file is something that has to be present it may of course be that some of the upgrade packages that should have had this file simple did not have it.

**Comment by Kristianostman** [comment]
@Joao-Magalhaes I checked the clean install package SuiteCRM 7.10.5 and the Save.php file is not there.

**Comment by Joao-Magalhaes** [comment]
This is the “custom” file

 

Best regards, 
João Magalhães 
Managing Partner 

Skype: nka-joaomagalhaes 
Email: joao.magalhaes@nka.pt <mailto:joao.magalhaes@nka.pt %0b%0b>  

NKA – New Knowledge Advice Lda 
Tel  + 351 253 278 646 |  Fax +351 253 276 154 
www.nka.pt <http://www.nka.pt/> 

 <https://www.facebook.com/pages/NKA-New-Knowledge-Advice-Lda/189197804479572>    <http://www.linkedin.com/pub/nka-new-knowledge-advice-lda/42/602/113>    <https://twitter.com/NKA_Lda> 

 

De: Kristianostman <notifications@github.com> 
Enviada: 23 de maio de 2018 09:04
Para: salesagility/SuiteCRM <SuiteCRM@noreply.github.com>
Cc: Joao-Magalhaes <joao.magalhaes@nka.pt>; Mention <mention@noreply.github.com>
Assunto: Re: [salesagility/SuiteCRM] Single Opt In status not being saved (#5753)

 

@Joao-Magalhaes <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJoao-Magalhaes&data=02%7C01%7C%7C4d68507d785b4435528f08d5c083bef2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636626594422927491&sdata=jqcX89P2Q5fwwdQlOrl3DQQh9DVy0KklxZDkjeeXtEY%3D&reserved=0>  I do not have such file to copy (modules\EmailMan\Save.php ) . May I have a corrupt set of files after upgrade within Suite Admin?

**Comment by Kristianostman** [comment]
@Joao-Magalhaes anyhow, I do not get the Opt-in checkbox to remain checked with this fix made in function action_Save as you describe above.
