### ISSUE TITLE
v.7.10.4 API8 HTTPS Run Issues

### ISSUE THREAD

**Issue by goingsmart** [salesagility/SuiteCRM#5758]
#### Issue

I may have missed something, but my TEST setup for the standard API8 gets 500 Errors running in HTTPS environment due to unsecure/conflicting embedded URL links in many areas. 
#### Expected Behavior

Should run in secure environment.
#### Actual Behavior

500 ERROR

#### Possible Fix

Please advise, is there another code set that should be used or are there change guidelines to modify the code. THX 
#### Steps to Reproduce

1. Run TEST.html or EXAMPLE.html under HTTPS.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): Mariah DB, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS 7 64bit

**Comment by samus-aran** [comment]
That was a pretty vague explanation I'll be honest :smile: Are you calling the API via HTTPS or what? I don't know what you are referring to in regards to embedded URLs... where? <_<

**Comment by goingsmart** [comment]
AS I recall, running the SuiteCRM provided TEST.html and EXAMPLE .html in the API library gets 500 ERROR because the links in the HTML are calling HTTP: not HTTPS. This may be deprecated code that is not supposed to be runnable?

I will not be working with the API further until 7.11 so you may want to close this and I will let you know if I have any issues with 7.11?
