### ISSUE TITLE
HTML field shown as text box 7.10.4

### ISSUE THREAD

**Issue by anasnajj** [salesagility/SuiteCRM#5766]
#### Issue
when create HTML field using Module Builder or studio , the field on detail view or edit view its show as text box only .. 

#### Expected Behavior
the field should display HTML tinymce editor

#### Actual Behavior
the field shown as text box no editor

#### Steps to Reproduce
1.Create HTML field using Module builder or studio on any custom module
2. add the field to edit or detail view
3.redeploy module
4.create new record you will see the field as text box

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser :Chrome Version 65 (64-bit)):
* Environment :MySQL, PHP 7
* Operating System and version :Redhat 7

**Comment by anasnajj** [comment]
Any update

**Comment by PedroErnst** [comment]
See #5945 

You will not see tinymce in your html, they are display only fields and not meant to be changed.

What you likely want is a textarea field, and then in the vardefs you can enable tinymce.

Maybe in the future this will be available in Studio but for now that's the only way to achieve what you're trying to do.

**Comment by anasnajj** [comment]
Dear Billon i didn't got your point, but in suitecrm version before 7.10.4 its working fine , 
see attached file for sample from version 7.8.5
![image](https://user-images.githubusercontent.com/6379281/40672120-87b0fe14-6376-11e8-81be-86125f8d3313.png)
