### ISSUE TITLE
Lead Detail View is showing Email address twice

### ISSUE THREAD

**Issue by rokacom** [salesagility/SuiteCRM#5767]
The Detail view of Leads shows the email fields twice back to back. 

#### Issue
When viewing details view of leads with email as a column, the email field shows the same email address back to back.  Once as a Link and the second time as just text. Screenshot below.

#### Expected Behavior
The Detail view should only show the email address (as a link is fine).

#### Actual Behavior
Displays both emails as shown below:
![screen shot 2018-04-21 at 1 29 38 pm](https://user-images.githubusercontent.com/8582012/39087186-79528f28-456b-11e8-803e-bfa4faa58e6f.png)
#### Possible Fix
NA
#### Steps to Reproduce

1. Create Lead with an Email address 
2. Click on "Leads" in sales menu item to show detail view of leads
3. Add Email as a column if it is not there already.

#### Context
This is NOT a critical bug.  I consider it a UI artifact.  It does not affect my ability interact with leads.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Mac Firefox Latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Server is Ubuntu 16.04  - fully updated

**Comment by techurbanist** [comment]
We've had the same issue using the upgrade release from 7.9.x to 7.10.4

**Comment by topesantos** [comment]
Copy modules/Leads/metadata/listviewdefs.php to custom/modules/Leads/metadata/listviewdefs.php
and change
'customCode' => '{$EMAIL1_LINK}{$EMAIL1}</a>',
to
'customCode' => '{$EMAIL1_LINK}</a>',

**Comment by willow9886** [comment]
We saw the same behavior on leads dashlet. Applied the same fix with success.

**Comment by pgorod** [comment]
@willow9886 on which version did you get this?
