### ISSUE TITLE
Missing tasks when Create Project from Project Template

### ISSUE THREAD

**Issue by FarmerFran** [salesagility/SuiteCRM#5768]
When creating projects using the "Create Project" drop down next to the Edit button on the screen for that Project Template. Project Template includes 41 tasks. Only 18 or 19 of these get created each time. I get the same results when using the Copy All Tasks with Resources checkbox or using shift-select to highlight all 41 tasks (all tasks are shown in this list) in the dialogue box.

It takes 8 to 10 minutes to create the project each time. Same results in Chrome, IE, and Firefox.

SuiteCRM Version 7.8.10, Sugar Version 6.5.25 (Build 344)
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Internet Explorer 11.0.9600.18977
Firefox Quantum 59.0.2 (64-bit)

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
