### ISSUE TITLE
Cannot customize check boxes as SuiteP overrides my CSS

### ISSUE THREAD

**Issue by rebbieboi** [salesagility/SuiteCRM#5781]
#### Issue
I have two problems here:
1.) check.png cannot be found in the cache folder thus the checkboxes for SuiteP are not displayed.
2.) SuiteP overrides my changes to the checkbox.

#### Expected Behavior
Added this to CSS:

input[type="checkbox"]{
            width: 30px; /*Desired width*/
            height: 30px; /*Desired height*/
            cursor: pointer;
            -webkit-appearance: none;
            appearance: none;
        }

Expected checkbox gets bigger

#### Actual Behavior
Checkbox duplicates to fill in the extra width. I now have 1 and 1/4 checkbox and you can select either of them which is weird since there is only one input in the code.

#### Possible Fix
Clear SuiteP CSS and re apply my CSS?

#### Steps to Reproduce
Create a tpl with a checkbox and add some CSS to improve it.

#### Context
I can't update my checkbox also the 404 for the check.png is annoying as well.

#### Your Environment
Version 7.10.2
Sugar Version 6.5.25 (Build 344)

**Comment by pgorod** [comment]
I believe your issue would be better off in the forums. This is to report bugs to the developer team.

Please close this issue and start a thread in the forums, I will help you out there. Thanks

**Comment by rebbieboi** [comment]
Alright, Thank you. But won't this be considered a bug for themes? Though I'm not sure this is the place for it.

**Comment by pgorod** [comment]
Sometimes the things in the forums end up reported here - but first I have to check you're doing the changes in the right files, that you understand how SuiteCRM files are customized, how CSS is generated from SASS, etc. That is the preliminary work that is better suited to the forums. Thanks! :-)

**Comment by rebbieboi** [comment]
Just posted on the forums. :)

**Comment by rebbieboi** [comment]
https://suitecrm.com/suitecrm/forum/suite-themes/18766-checkboxes-are-not-being-displayed-in-suitep#64450
