### ISSUE TITLE
Send Test Email use the email for Test as Sender (not only Receiver)

### ISSUE THREAD

**Issue by glebret** [salesagility/SuiteCRM#5785]
### Issue
The email address writen in the send test email is also used as the sender email

#### Issue
In the profile section, when setting a new email account (external), you can test your credential with 'send test email'.
A new windows ask you 'Email Address For test' and you can enter whom will received the test email.
SuiteCRM will then send the email to this address with also this adress as sender

#### Expected Behavior
The test email should be send with the from address of the profile

#### Actual Behavior
The 'From' and 'To' fields are filled with the email address choosen for the test
For example : the username is Eric (his email address in the profile is eric@host.com)
From : Eric <**guillaume@host.com**>
To : guillaume@host.com

This should be 
From : Eric <**eric@host.com**>
To : guillaume@host.com

#### Steps to Reproduce

1.  In Profile, go to email settings, and click on the SETTINGS button
2. In the Mail Accounts Tab, Add/Modify a Outgoing SMTP Servers
3. Click on the Send Test Email Button
4. Fill with a recipient address to receive the test email
5. Check the header of the received email

#### Context
This behaviour is not good when you use a external service for your transactionnal email (as mailjet) which check the autorized sender email...
low priority

#### Your Environment

* SuiteCRM Version used: Version 7.10.4 Sugar Version 6.5.25 (Build 344)
* Chrome version Version 65.0.3325.181 (Build officiel) (64 bits)

**Comment by Mausino** [comment]
@glebret @Dillon-Brown i tested on 7.10.11 and it's working fine

I configured outgoing emial account as info@... and Email to notify was my personal emial.. and it worked great :) without issue

But i found another one by testing.. let me know if need to create new issue or can stay here 

**In editview of outbound email i was able sent the test email but when i tried on detail view i got this issue**

![2018-12-29_0127](https://user-images.githubusercontent.com/5773777/50531396-4282f280-0b09-11e9-88da-f1d0eaeedce4.png)

**Comment by pgorod** [comment]
@Mausino if you un-comment this line

https://github.com/salesagility/SuiteCRM/blob/master/include/SugarPHPMailer.php#L457

and try the email sending from the two different situations, do you see a difference there?

This looks like a DNS resolution error, can you ping that host by name from your server command-line?

However I can't explain why the host would resolve when sending email from one screen, and not from the other. That would look like a bug.

**Comment by Mausino** [comment]
@pgorod for sure that we understand one to other... 
i created gif to be clear 👍 I will test your solution tomorrow because i am too busy for other work. Please let me know if you think same as your wrote above :)

![email_error](https://user-images.githubusercontent.com/5773777/50539749-aba84b80-0b85-11e9-8189-e603fd5a9922.gif)

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
