### ISSUE TITLE
First Line of products-listview is ordered wrong

### ISSUE THREAD

**Issue by MTet** [salesagility/SuiteCRM#5793]
#### Issue
First Line of products-listview is ordered wrong. 
![grafik](https://user-images.githubusercontent.com/37102661/39309108-804b7c22-4967-11e8-8f94-656bc69f9022.png)

#### Expected Behavior
The first line of the listview should start with a productname with "A...." not with "F....." like in our case.

#### Actual Behavior

The first line of the listview starts ordered (ASC) by productname shows a product with starting with "F.....", not with "A....". All other lines are ordered correct.

#### Steps to Reproduce

1. Open "Products" (listview)
2. click on columnheader productname for sorting asc
3. the first line will be ordered wrong

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FireFox and Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Win Server + IIS

**Comment by MTet** [comment]
Error occurs also at contracts-listview.

**Comment by PedroErnst** [comment]
Thanks @MTet for reporting this.

A priori I'm not able to reproduce this.

![image](https://user-images.githubusercontent.com/34056696/39570582-a8dc320e-4ec0-11e8-86df-e892d92fbb9c.png)

Do you have a language pack installed?
Any customizations?
Do the names contain any special characters? (shouldn't affect but just in case)
Is this the first page of listview?

**Comment by MTet** [comment]
German language pack is installed.
Special character used: ( , ) -
The error occurs always only on the first page of the listview.

**Comment by PedroErnst** [comment]
Interesting, thanks for the details. I'll try to reproduce again.

**Comment by PedroErnst** [comment]
Still no luck on my side... 

![image](https://user-images.githubusercontent.com/34056696/39584745-162b0446-4eeb-11e8-84b2-5d3fae8cc15c.png)

**Comment by MTet** [comment]
I updated to 7.10.6 and also the language pack. Now the bug is fixed 👍
