### ISSUE TITLE
No packaged installs, apt-repository, or any facilities for automated installs/updates.

### ISSUE THREAD

**Issue by fake-name** [salesagility/SuiteCRM#5795]
I'm attempting to install a new instance of SuiteCRM into a clean VM.

To my utter astonishment, there appears to be **no** packaged versions of the application available. I have not been able to find any apt-repositories, PPAs, or even just bare `*.deb`/`*.rpm` packages. The only install procedure appears to be "download this zip folder of PHP files".

There doesn't even seem to be a install script!

..... *what?* 

If for no other reason then security, having some mechanism for automatic updates is critical. 

Is the install process made more difficult then is necessary to try to drive people to opening support contracts?

**Comment by gunnicom** [comment]
For php application it is quite normal that there are no .deb packages. And even if there are, often the packages are more outdated and got more security flaws than using the updater of the software itself.

**Comment by fake-name** [comment]
> For php application it is quite normal that there are no .deb packages. 

Thats..... *horrible*. 

> And even if there are, often the packages are more outdated and got more security flaws than using the updater of the software itself.

So build the packages using a CI system.

> updater of the software itself.

Also known as "a buggier reimplementation of `apt-get` or your package manager of choice". Also, *there's a built-in updater?

**Comment by pgorod** [comment]
There are some mechanisms, there is a silent installer (I'm not sure if there is a silent upgrader). They are not very polished but some people are using them.

I also frequently deploy from git, it's not fully automatic but it isn't far from automatic. Clone, set permissions, run installer, then you can push everything back up to git and use it as an installed version (but care must be taken with several aspects, see below).

There are specific reasons why SuiteCRM is not straightforward to deploy automatically: it is an app that changes itself, writes itself, when you change stuff in Studio or Module builder. There's a nice blog post here

http://blog.indrek.io/articles/version-control-and-deployment-practices-for-sugarcrm/

this will give you an idea of the challenges.

That said, this is a Community and if somebody can make progress in this front, we will all benefit. I agree it would be nice to do something more in this regard.

**Comment by chris001** [comment]
Here's a script to prepare the input parameters and run the "silent install" from the command line:
http://www.jsmackin.co.uk/suitecrm/suitecrm-command-line-install/
