### ISSUE TITLE
Error while installing from master branch

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#580]
I got this error:

![error_install](https://cloud.githubusercontent.com/assets/939888/10590588/e300960a-7687-11e5-95c5-c86c69b08496.png)

In sugarcrm.log:

Mon Oct 19 17:32:25 2015 [8748][-none-][FATAL] Error creating table: leads: Query Failed: CREATE TABLE leads (id char(36)  NOT NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modified_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,salutation varchar(255)  NULL ,first_name varchar(100)  NULL ,last_name varchar(100)  NULL ,title varchar(100)  NULL ,photo varchar(255)  NULL ,department varchar(100)  NULL ,do_not_call bool  DEFAULT '0' NULL ,phone_home varchar(100)  NULL ,phone_mobile varchar(100)  NULL ,phone_work varchar(100)  NULL ,phone_other varchar(100)  NULL ,phone_fax varchar(100)  NULL ,primary_address_street varchar(150)  NULL ,primary_address_city varchar(100)  NULL ,primary_address_state varchar(100)  NULL ,primary_address_postalcode varchar(20)  NULL ,primary_address_country varchar(255)  NULL ,alt_address_street varchar(150)  NULL ,alt_address_city varchar(100)  NULL ,alt_address_state varchar(100)  NULL ,alt_address_postalcode varchar(20)  NULL ,alt_address_country varchar(255)  NULL ,assistant varchar(75)  NULL ,assistant_phone varchar(100)  NULL ,converted bool  DEFAULT '0' NULL ,refered_by varchar(100)  NULL ,lead_source varchar(100)  NULL ,lead_source_description text  NULL ,status varchar(100)  NULL ,status_description text  NULL ,reports_to_id char(36)  NULL ,account_name varchar(255)  NULL ,account_description text  NULL ,contact_id char(36)  NULL ,account_id char(36)  NULL ,opportunity_id char(36)  NULL ,opportunity_name varchar(255)  NULL ,opportunity_amount varchar(50)  NULL ,campaign_id char(36)  NULL ,birthdate date  NULL ,portal_name varchar(255)  NULL ,portal_app varchar(255)  NULL ,website varchar(255)  NULL ,   NULL ,   NULL ,   NULL ,   NULL  , PRIMARY KEY (id),   KEY idx_lead_acct_name_first (account_name, deleted),   KEY idx_lead_last_first (last_name, first_name, deleted),   KEY idx_lead_del_stat (last_name, status, deleted, first_name),   KEY idx_lead_opp_del (opportunity_id, deleted),   KEY idx_leads_acct_del (account_id, deleted),   KEY idx_del_user (deleted, assigned_user_id),   KEY idx_lead_assigned (assigned_user_id),   KEY idx_lead_contact (contact_id),   KEY idx_reports_to (reports_to_id),   KEY idx_lead_phone_work (phone_work),   KEY idx_leads_id_del (id, deleted)) CHARACTER SET utf8 COLLATE utf8_general_ci: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL ,   NULL ,   NULL ,   NULL  , PRIMARY KEY (id),   KEY idx_lead_acct_name_fi' at line 1

**Comment by ghermans** [comment]
Did you
* Follow the installation doc on https://suitecrm.com/wiki/index.php/Installation
* Set post_max_size to at least 60MB
* Set upload_max_filesize settings to at least 60MB
* Set max_input_time to a large number
* Set memory_limit to 256MB

?

**Comment by Abuelodelanada** [comment]
Yes, and I have all this values in /etc/php5/apache2/php.ini.

The problem in when creating leads table, look:

http://linkode.org/YyntL6xFjU05t5M8zDRhx7

The are many NULL as field name :-/

**Comment by willrennie** [comment]
Was this a fresh install? Can you provide details on version, environment etc?
