### ISSUE TITLE
Workflow bug - One field - any change - triggered by any field

### ISSUE THREAD

**Issue by acoolov** [salesagility/SuiteCRM#5803]
#### Issue
It seems like there is a bug in the workflow, because I have never made this one work no matter what version i am on. And pgr confirmed I need to open an issue here. This is very a very important feature of the workflow that needs to work properly.

When I create a workflow for cases, tasks, and other modules. I need a few workflows that get triggered only when one specific field was modified. For example, date or description or user assigned to.

I create a workflow, repeated runs, only on save.
Condition - Field - User Assigned to - Any change 

#### Expected Behavior
This is supposed to trigger ONLY when an assigned user was changed.

#### Actual Behavior
Triggers if any of the fields were modified. And actually triggers even when nothing was modified, just save the record again, and it still triggers that workflow.

#### Possible Fix
Not sure what the possible fix is, but we absolutely need this feature to work! This has not been working for a long time. 

#### Context
Absolutely HIGH priority!
I'm trying to create a few notifications that get triggered only when a specific field was modified. 
When a new user is assigned, the new user will get an email notification (not a default notification)
When the date was changed, the assigned user will get a custom notification about the new date etc.

#### Your Environment
Does not work in any of the versions I tested. Confirmed by other users as well.
Here is my forum post
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18783-workflow-notification-when-one-field-was-changed

If this is fixed, I will be beyond thankful!

**Comment by PedroErnst** [comment]
Originates from #4779, I'm working on a fix
