### ISSUE TITLE
double variable declaration ($listView)  in the function declaration (testScenarioViewFileTestModule) 

### ISSUE THREAD

**Issue by lpmop** [salesagility/SuiteCRM#5805]
I run 
> time codecept run |tee /var/www/\`date +%Y-%m-%d-%H-%M-%S\`.log

and have response 

`Codeception PHP Testing Framework v2.4.1
Powered by PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
PHP Fatal error:  Redefinition of parameter $listView in /var/www/SuiteCRM/tests/acceptance/Core/FileModuleCest.php on line 83
`

https://github.com/salesagility/SuiteCRM/blob/a7d82492759dbfd66852a56195207acc913f4cd9/tests/acceptance/Core/FileModuleCest.php#L83-L88

`php -v -> PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
`

**Comment by PedroErnst** [comment]
@lpmop 

I think this is fixed in the current version. Can you confirm please?

**Comment by lpmop** [comment]
yes :) 👍
