### ISSUE TITLE
email: header is different but content of the message is the same for each email

### ISSUE THREAD

**Issue by Nebukadnezar01** [salesagility/SuiteCRM#5811]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Hi @Nebukadnezar01, would you be able to fill out the GitHub template? we won't be able to progress with this without further details. Thanks.

**Comment by Nebukadnezar01** [comment]
Hi, I am sorry for this. Tried to delete the message but could not find out how :(
I will close the topic now.

**Comment by Mausino** [comment]
@Nebukadnezar01 i had same issue as you when i upgraded to latest version of SuiteCRM

please change this in your code and this will solve your issue https://github.com/salesagility/SuiteCRM/pull/4009/files
