### ISSUE TITLE
CASES Module - Description Field (with wysiwig editor) Not Visible When Save and Continue or Navigate to Next/Previous

### ISSUE THREAD

**Issue by aarondglover** [salesagility/SuiteCRM#5815]
#### Issue

The Cases Module Description Field (with wysiwig editor) is Not Visible When Save and Continue or Navigate to Next/Previous. 

#### Expected Behavior
The Description with the wysiwyg editor SHOULD appear if you use the "Save and Continue" or Navigate Next/Previous Buttons

#### Actual Behavior

Bug Fix #5672 seems to work perfectly in addressing the problem of the Description field not appearing when "CREATING" a new case. 

- The wysiwyg editor appears when creating a case
- The wysiwyg editor also appears when editing a case.

However;

The Description (with wysiwyg editor) DOES NOT appear if you use the "Save and Continue" or Navigate Next/Previous Buttons

#### Possible Fix

It could be a similar timing issue addressed by fix #5672 however needs to be called from a different point.

#### Steps to Reproduce

1. You must have more than 1 Case in the Module
2. Edit a Case
3. Press the Save and Continue button (or Next/Previous) buttons
4. The Description field is missing.

#### Context

This bug is affecting my support engineers workflow as the ability to review multiple cases is slowed dramatically. They need to return to the list of cases and select them individually rather than simply using the Save and Continue button.

This is a high priority bug for my engineers but I do not know how this sits in the rest of the priorities. I am hopeful that it is a similar fix as was done in Fix #5672 will address this.

#### Your Environment

* SuiteCRM Version used: 7.8.18
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 68.0.3409.2 (Official Build) dev (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):

**Comment by PedroErnst** [comment]
Thanks @aarondglover for the detailed report. I've pushed a commit which I think fixes this particular issue,  if you try it please let me know if it works for you.
