### ISSUE TITLE
User photo and activitystream photo

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#582]
After adding the **"Photo" field** by use of the SuiteCRM Studio to the User->DetailView and User->EditView on a clean SuiteCRM (7.3.1) installation and uploading a user photo resulted in the following:

User->EditView: Uploading the image
![bildschirmfoto 2015-10-20 um 10 58 16](https://cloud.githubusercontent.com/assets/15199551/10602996/1bcd8896-771c-11e5-822a-4bce3a6a1621.png)

User->DetailView
![bildschirmfoto 2015-10-20 um 10 58 39](https://cloud.githubusercontent.com/assets/15199551/10603052/50a3cba2-771c-11e5-97c3-9045d815f35f.png)

User->EditView: Clicking on the image link
![bildschirmfoto 2015-10-20 um 10 58 52](https://cloud.githubusercontent.com/assets/15199551/10603102/7b2c35e4-771c-11e5-995a-220aa78560d7.png)

-> results in
![bildschirmfoto 2015-10-20 um 11 20 01](https://cloud.githubusercontent.com/assets/15199551/10603119/8f217dde-771c-11e5-9c37-f280678e31b8.png)

Checking all the permissions (Linux) and changing the /upload/ folder to 775 did not fox the problem.
Afterwards, the sugarcrm.log printed the following error:
_Query Failed: SELECT photo FROM users LEFT JOIN users_cstm cstm ON cstm.id_c = users.id WHERE users.id= '1': MySQL error 1146: Table 'suitecrm_clean.users_cstm' doesn't exist_

Creating the users_cstm table in the suitecrm database and doing a quick repair and rebuild fixed that issue.

Now the test picture ist shown in the DetailView
![bildschirmfoto 2015-10-20 um 11 25 00](https://cloud.githubusercontent.com/assets/15199551/10603247/454ee768-771d-11e5-8e2d-23e98af8a45d.png)

Issue: Trying to change the image does not update the photo field.
-> Only by manually removing the image in the upload folder and "removing" the image in the GUI lets a user upload a different image.

Additionally the **activitystream** doesn't load the appropriate user image, just displaying a placeholder.
![bildschirmfoto 2015-10-20 um 11 29 31](https://cloud.githubusercontent.com/assets/15199551/10603352/de1301fa-771d-11e5-9c67-114eab6c5150.png)

Looking into the native SuiteCRM code in the _SugarFeed module -> SugarFeed.php -> fetchReplies()_ it appears that there are still issues, i.e. the _user->picture_ field does not exist in SuiteCRM.
![bildschirmfoto 2015-10-20 um 11 37 21](https://cloud.githubusercontent.com/assets/15199551/10603590/21424246-771f-11e5-9dbe-51c67b5d002e.png)

SuiteCRM Version: 7.3.1

**Comment by jobvector** [comment]
is planned with which release this issue will be solved?

**Comment by jshwhitlow** [comment]
@jobvector were you able to get a fix for this problem, or have they patched this bug? I ran into this issue recently and was looking for a fix to the problem.

**Comment by jobvector** [comment]
@jshwhitlow 
tested it on SuiteCRM 7.6.6 some problems were fixed and photo upload and changing it are possible but the uploaded photo is still not shown in the activity stream or employees modul (DetalView)

**Comment by ijdavie** [comment]
I will close this issue as most issues have been solved with a previous release, there is one know issue still outstanding which can be found in issue #5017
