### ISSUE TITLE
Calendar ICAL URL still asks for User / Password

### ISSUE THREAD

**Issue by RobRobM** [salesagility/SuiteCRM#5820]
After a clean install of suitecrm 7.10.4 on a clean Ubuntu server 17.10 system the iCal link for displaying the the calendar in an external program or in browser needs username and password.

#### Issue
Username and password of the user do not authenticate.

#### Expected Behavior
The server should not ask for username and password or should authenticate

#### Actual Behavior
when using the iCal link from the user profile in a browser:

**SOMEIP/suitecrm/ical_server.php?type=ics&key=SOMEKEY&email=robert@USEREMAIL.COM**

Username and password are asked to authenticate and supplying them does not authenticate.

The fact that username and password kept getting asked let me to check the log and the following fatal error is displayed:
`[FATAL] ambiguous user email address`

After disabling authentication in ./modules/iCals/HTTP_WebDAV_Server_iCal.php (line 207-213)
The **ical_server.php** was accessible but did not work in any program. After closer inspection the user in the ical file is not (in this case) **Robert** but **Administrator**:

BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
X-WR-CALNAME: **Administrator** (SugarCRM)
PRODID:-//SugarCRM//SugarCRM Calendar//EN
BEGIN:VTIMEZONE

#### Possible Fix
I got things working by replacing **email** in the iCal-link to **user_name**

SOMEIP/suitecrm/ical_server.php?type=ics&key=SOMEKEY&**user_name=robert**

Now the **ical_server.php** reads:

BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
X-WR-CALNAME:**Robert** (SugarCRM)
PRODID:-//SugarCRM//SugarCRM Calendar//EN
BEGIN:VTIMEZONE
.....

This works even after re-enabling iCal authentication in ./modules/iCals/HTTP_WebDAV_Server_iCal.php

#### Context
For a new user this was a $|@#$ to figure out. I can see no fault in the suitecrm settings I used. Everything is working, e-mail etc. If it is me, please let me know. 

#### Your Environment

* SuiteCRM Version used: 7.10.4 
* Browser name and version: Firefox 59.0.2 (64-bits)
* Environment name and version: mysql-5.7 php7.1
* Operating System and version: Ubuntu 17.10

**Comment by pgorod** [comment]
Exact same title as this one #4399

But I'm not sure exactly _how_ fixed that really was. It seems something was still missing.
