### ISSUE TITLE
Report does not display data if Format Options is used with Ordering

### ISSUE THREAD

**Issue by Vinedine** [salesagility/SuiteCRM#5828]
If a report is created with a date field with group by, Format Options and Ordering then no data is visible and a FATAL error is created in log file.

![image](https://user-images.githubusercontent.com/19403380/39629044-2fcdae6a-4fab-11e8-816f-c54775841332.png)

If Ordering is removed then the report works and data is displayed

#### Issue

Error in log file is following;

`[32528][1][FATAL]  Query Failed: SELECT DATE_FORMAT(`aos_invoices`.invoice_date,'%Y') AS 'Invoice_Date0', `aos_invoices`.currency_id AS 'aos_invoices_currency_id', SUM(`aos_invoices`.total_amt) AS 'Total1', SUM(`aos_invoices`.tax_amount) AS 'Tax2', SUM(`aos_invoices`.total_amount) AS 'Grand_Total3', SUM(`aos_invoices_cstm`.payment_value_c) AS 'Payment_Value4', COUNT(`aos_invoices`.id) AS 'Count5' FROM `aos_invoices` LEFT JOIN `aos_invoices_cstm` `aos_invoices_cstm` ON `aos_invoices`.id = `aos_invoices_cstm`.id_c  WHERE ( `aos_invoices`.status != 'Cancelled' ) AND  aos_invoices.deleted = 0  GROUP BY DATE_FORMAT(`aos_invoices`.invoice_date,'%Y'), `aos_invoices`.currency_id, `aos_invoices`.currency_id, `aos_invoices`.currency_id, `aos_invoices`.currency_id ORDER BY `aos_invoices`.invoice_date DESC LIMIT 0,20: MySQL error 1055: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'bluff.aos_invoices.invoice_date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

As you can see group by uses **DATE_FORMAT(`aos_invoices`.invoice_date,'%Y')** but Order by uses **`aos_invoices`.invoice_date**

#### Expected Behavior

If a Data Field has Group By, Format Options and Ordering then the correct data should be displayed

#### Actual Behavior

No data was displayed see comments above

#### Possible Fix

No fix at this time.  Just a work around to remove ordering.

#### Steps to Reproduce
1. Create a report where there is a data field with group by and Format Options set to a value and Ordering.
2. Run the report
3. No data is displayed

#### Context

There is a workaround so it is not critical.  But workaround does not display the data correctly.

#### Your Environment
* SuiteCRM Version used: Version 7.10.4
* Environment name and version: MySQL, PHP 7

**Comment by PedroErnst** [comment]
Hello @Vinedine 

I'm trying to reproduce this, but it seems to work for me.

![image](https://user-images.githubusercontent.com/34056696/40541042-2dcd7560-6012-11e8-9215-18dc445cd11c.png)

Gives this result:

![image](https://user-images.githubusercontent.com/34056696/40541065-40bf261e-6012-11e8-8a9b-aef84c93c93a.png)

Maybe I'm missing something?

**Comment by ChangezKhan** [comment]
I am also not able to recreate the same in 7.10.4 and 7.10.7. Kindly update the issue.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
