### ISSUE TITLE
Undefined function minify_css() in block.minify.php

### ISSUE THREAD

**Issue by LuminisIndia** [salesagility/SuiteCRM#5832]
There was a FATAL error observed as:
Fatal error:  Uncaught Error: Call to undefined function minify_css() in /home2/luminisi/public_html/SuiteCRM/include/Smarty/plugins/block.minify.php:15 (or 18th line)

[Reference:](https://suitecrm.com/suitecrm/forum/developer-help/18942-call-to-undefined-function-minify-css)

There was no previous reference of this issue on this repository or SuiteCRM forums before, thus had to dig out the culprit code.  

Issue
This function was not allowing us to create or select the target list from a subpanel and was resulting a huge functionality built by us going absolutely hay-wired.  The function minify_css() in line 15 of block.minify.php, definitely looks like some sort of coding leftover. This file is a recent inclusion in SuiteCRM/include/Smarty/plugins/. 

Only the developer of this file could confirm -- whether it is a minor bug or essential piece of code. However, as of now minify_css() is surely an undefined function.

Possible Fix
Deleting the line 15: 
return '<' . $matches[1] . ' style=' . $matches[2] . minify_css($matches[3]) . $matches[2];
Replacing with line 15:
return '<' . $matches[1] . ' style=' . $matches[2] . $matches[3] . $matches[2];

Context
https://suitecrm.com/suitecrm/forum/developer-help/18942-call-to-undefined-function-minify-css#65304

Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version  : 66.0.3359.139 (Official Build) (64-bit)
* Environment name and version: MySQL, PHP 7.1:
* Operating System and version : Linux

**Comment by Dillon-Brown** [comment]
Fix here: #5707

**Comment by LuminisIndia** [comment]
Dear Dillon-Brown,

It seems that you have missed the point.  I have already upgraded to the version 7.10.4 on date: 2-May-2018, means only after you merged the commit.  The problem I am pointing is the function minify_css () in line 15 of block.minify.php.  Kindly have a closer look and suggest us!

**Comment by Dillon-Brown** [comment]
@LuminisIndia 7.10.4 was released on the 9th Apr while the commit that fixes this issue was merged on the 25th Apr so it shouldn't be included in 7.10.4. The minify_css function is defined further down in the file in latest hotfix here: https://github.com/salesagility/SuiteCRM/blob/hotfix/include/Smarty/plugins/block.minify.php

Undefined in 7.10.4:
https://github.com/salesagility/SuiteCRM/blob/v7.10.4/include/Smarty/plugins/block.minify.php

Have you double checked that file in your instance to see if the function is present?

**Comment by LuminisIndia** [comment]
@Dillon-Brown May be I have missed some point made by you.  I have just attempted by copying the hotfix suggested by you.  It seems to work perfectly as of now.  Thank you very much for giving time & attention!
