### ISSUE TITLE
Email Settings & Fail send email

### ISSUE THREAD

**Issue by ijdavie** [salesagility/SuiteCRM#5853]
#### Issue

It appears that if a SMTP server does not use a email address as the username, the system is able to send a test email via the test option, however once saved and a user tried to send a email via the emails module it will fail with the following error message. 

SugarPHPMailer encountered an error: Invalid address:  (punyEncode) <Username>

From what can be seen the username is trying to be validated as a email address. 
#### Expected Behavior

services like sendgrid should allow sending of email addresses. 

#### Actual Behavior

Email not sent error logged in suitecrm.log file. 

#### Steps to Reproduce

1. setup sendgrid
2. use as email credentials 
3. try and send a email via emails module. 
4.

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome
* Environment name and version (e.g. MySQL, PHP 7): php 7.2
* Operating System and version (e.g Ubuntu 16.04): ubuntu

**Comment by pgorod** [comment]
@ijdavie where exactly did you configure the SMTP Server? If it was in the User profile, please tell me also which of the two screens shown here #5376 you used. Thanks!

**Comment by ijdavie** [comment]
@pgorod It was within the Email settings within the admin panel. (The test settings worked) however when trying to send via the emails module it failed.

**Comment by samus-aran** [comment]
@ijdavie The fix provided we have done our own manual test and can send using a username with a system outbound account if we have a personal inbound linked to it.

Let us know if this isn't the case.

**Comment by salesagility-davidthomson** [comment]
I can confirm that  isleshocky77  https://github.com/salesagility/SuiteCRM/issues/5908 does indeed happen when installed on 7.10.2 as tested by me. 
The email settings disappear and do not display even after reentering them.
It is possible however to continue using the settings when sending mail as this continues to work.
I also have to point out that after merging this fix you also need to rebuild using composer.

**Comment by LionelBino** [comment]
This happen too in 7.9.17

**Comment by Dillon-Brown** [comment]
Hi guys, taking a look at hopefully getting the related PR #6017 merged in. Would anyone be able to assist with testing? just a simple confirmation that it works for you would be greatly appreciated.
