### ISSUE TITLE
Multiple pages PDF from reports when Total of field is selected

### ISSUE THREAD

**Issue by fantazijka** [salesagility/SuiteCRM#5856]
#### Issue
When creating a report with Total sum, or count of some field you get pdf with multiple pages - report table is broken.
In PDF the first page is ok, but the others each contains only one row from report table. Sometimes it can be PDF of 150pages (mostly blank).

#### Expected Behavior
exported PDF should have unbroken table, which continues on next page

#### Actual Behavior
exported PDF has first page ok, but the report table brokes on other pages - one row of table is displayed on one page, or it isn't displayed at all.
total row is either on the last page, or is missing.

#### Possible Fix
no idea

#### Steps to Reproduce
1. create a report
2. add some fields
3. set Total of one field - sum or count
4. generate PDF export

#### Your Environment
* SuiteCRM Version used: Official demo 7.10.4

**Comment by st-ives** [comment]
Also experiencing this issues. On version 7.10.4

**Comment by raptr569** [comment]
Just found this issue version 7.10.6; release notes for 7.10.7 don't mention a fix either.

**Comment by tunafixes** [comment]
Hi, have some problem for any report with a sum or group function. First page ok all the others are blank. One page for each additional record.
I'm using SuiteCrm Version 7.10.4
Sugar Version 6.5.25 (Build 344).

**Comment by ChangezKhan** [comment]
Hi folks, can you please provide steps in detail?

**Comment by ChangezKhan** [comment]
I have checked with SuiteCRM 7.8.18 and it is working fine. But with online suitecrm demo it has issues.

**Comment by tunafixes** [comment]
Hi,
It worked for me.

Thanks,
Rui palma

**Comment by pgorod** [comment]
@ChangezKhan is it possible that this fix is causing this regression bug?

https://suitecrm.com/suitecrm/forum/feedback/24368-problem-in-the-report-module-with-columns-width-in-the-total-row-of-a-report-table
