### ISSUE TITLE
Error on workflow datetime fields operations if admin date format is not m/d/Y

### ISSUE THREAD

**Issue by sanchezfauste** [salesagility/SuiteCRM#5869]
Error on workflow datetime fields operations if admin date format is not `m/d/Y`.

#### Issue

If admin (user with `id=1`) date format is set to 23/12/2010, datetime field operations of workflow actions swap the month and day of the resulting date.

#### Expected Behavior

The resulting date must be correct.

#### Actual Behavior

Month and day of resulting date are swapped.

#### Possible Fix

I will submit a PR later.

#### Steps to Reproduce

1. Go to the preferences of admin user (user with `id=1`).
2. Change `Date Format` setting to `23/12/2010`.
3. Create the following workflow:
![1](https://user-images.githubusercontent.com/10921800/39999448-6d0361b8-5789-11e8-9101-b447775c8b0b.png)
![2](https://user-images.githubusercontent.com/10921800/39999451-6e98bf28-5789-11e8-9c3b-0a1aede1c737.png)

4. Create new Task record with `Date Start = 01/02/2018 10:00` and `Due Date = 01/02/2018 12:00`.
5. Wait until the workflow is triggered.
6. See that `Date Start` of previously created Task is modified to `02/01/2019 11:00` and `Due Date` is modified to `02/01/2020 11:00`. This is not correct.

#### Context

I'm trying to increment 12 months the date of a tasks using a workflow. This workflow worked correctly with previous versions of SuiteCRM.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.8.18 LTS
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 66.0.3359.139 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): mysql  Ver 14.14 Distrib 5.7.22, PHP 7.0.28-0ubuntu0.16.04.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.4 LTS

**Comment by pgorod** [comment]
@sanchezfauste can you please take a look at this thread in the Forums?

https://suitecrm.com/suitecrm/forum/advanced-opensales-workflow-portal-support/20769-workflow-on-leads-behaviour

It is a similar problem with date formats in Workflow, but here it seems to affect the execution of the Workflow (the date error is while each record is being considered to apply the Workflow).

Maybe you can help? Thanks

**Comment by sanchezfauste** [comment]
Hi @pgorod ,

I've been doing some tests and I have not been able to reproduce the error. This is the workflow that I created:

![screenshot_2018-11-02 suitecrm](https://user-images.githubusercontent.com/10921800/47931057-05fe9600-dece-11e8-9a0c-542cffe6ad4f.png)

Am I missing something?

I've also tryed to replicate this: https://suitecrm.com/suitecrm/forum/advanced-opensales-workflow-portal-support/20769-workflow-on-leads-behaviour#73604, but works correctly for me using SuiteCRM 7.8.23.

**Comment by sergtech** [comment]
> Am I missing something?

Hi, sanchezfauste.

You're missing the "condition" compared to my thread from the suitecrm forums. My condition that fails is 
"Leads" "Name" "Contains" "String". But the "String" has to be the start of the string in order for it to not be processed. So, if the lead "Name" is "Kirk" and we search for "Kirk", it fails, but if the search is for "irk" it works.

I am not certain that the two issues are related; however I have seen some weirdness with the date-related workflow triggers in some of the CRM systems I manage;
