### ISSUE TITLE
Module Builder Disappears

### ISSUE THREAD

**Issue by idfbobby** [salesagility/SuiteCRM#587]
After a fresh install, if you choose Repair and Rebuild, Module Builder disappears and is no longer an option.

**Comment by paulgodley** [comment]
I have just tried a fresh install of 7.4.  When I run the Repair and Rebuild, the module builder option is still available (under developer tools).  Can you please tell me which version of SuiteCRM you are running so that I can try and replicate the issue you are experiencing?

**Comment by willrennie** [comment]
@idfbobby did you see the response from @paulgodley ?
