### ISSUE TITLE
ReferenceError: Can't find variable: YAHOO

### ISSUE THREAD

**Issue by ysilvela** [salesagility/SuiteCRM#5888]
In the STEP 2/2 when click on "Next" button nothing happends but in the javascript console appears this message:
ReferenceError: Can't find variable: YAHOO

SuiteCRM 7.10.4

**Comment by horus68** [comment]
Same in here: https://github.com/salesagility/SuiteCRM/issues/5532
and a related one:
https://github.com/salesagility/SuiteCRM/issues/3822

**Comment by Dillon-Brown** [comment]
@ysilvela Have you tried checking permissions? this should have been fixed by #5523
