### ISSUE TITLE
Need help regrading the mysql boolean query parsing

### ISSUE THREAD

**Issue by jyotiraghav93** [salesagility/SuiteCRM#5889]
Hi,

I have a boolean search kind of queries used for the recruitment purpose,
Example,
(asynchronous NEAR:10 "crystal reports")
(modif* NEAR:15 (triggers AND "stored procedures"))
(automation NEAR:15 python AND jabber)

I am working on Mysql & PHP,
what will be the mysql query for getting these search results using full text search?

**Comment by pgorod** [comment]
Is this even related to SuiteCRM? How?

Even if it is, ask about it in the Forums - here you're just supposed to report bugs.
