### ISSUE TITLE
JSON API Error when query Tasks via api

### ISSUE THREAD

**Issue by stefankugler** [salesagility/SuiteCRM#5896]
#### Issue
I get an API error when I try to access /api/v8/modules/Tasks. Other Modules work as expected.

#### Expected Behavior
Get json-data containing all Tasks

#### Actual Behavior
`
suitecrm.log:
Thu May 17 22:04:13 2018 [3418][1][FATAL] [SuiteCRM] [API] [Unable to convert datetime field using SugarBean] "time_due"
Thu May 17 22:04:13 2018 [3418][1][FATAL] [ERROR] [Invalid Payload Response]{"links":[],"data":[],"errors":[{"id":"1","links":{"about":null},"status":500,"code"n: 8","source":{"pointer":null,"parameter":null},"meta":{"about":"Exception","class":"SuiteCRM\\API\\v8\\Exception\\ApiException","code":8025,"langMessage":null:0,"stability":"ALPHA"}},"jsonapi":{"version":"1.0"}}
`

API response:
`
{
	"links": [],
	"data": [],
	"errors": [
		{
			"id": "1",
			"links": {
				"about": null
			},
			"status": 500,
			"code": 8025,
			"title": "JSON API Error",
			"detail": "Api Version: 8",
			"source": {
				"pointer": null,
				"parameter": null
			},
			"meta": {
				"about": "Exception",
				"class": "SuiteCRM\\API\\v8\\Exception\\ApiException",
				"code": 8025,
				"langMessage": null
			}
		},
[...]
`

#### Possible Fix
[API] [Unable to convert datetime field using SugarBean] "time_due"

#### Steps to Reproduce

1. Request OAUTH2-Token
2. Send GET-Request: http://crmhost/suite-test/api/v8/modules/Tasks

#### Context

I tried to query several Modules to create a custom export for a self-hosted calendar. Notes and Calls work as expected.

#### Your Environment

* SuiteCRM Version used: 7.10.4 fresh installation
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Insomnia and php/curl
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.29
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04 fresh installation

**Comment by stefankugler** [comment]
The vardef-declaration of the task-module may cause the error:
https://github.com/salesagility/SuiteCRM/blob/c6bece6ab3acd29365f5fc663ba8f3cc359a986b/modules/Tasks/vardefs.php#L92
There is no "time_due" field in the table "task" (only in the module Project Tasks).

The API works as expected fter commenting out L92 to L101 and doing a quick repair.

**Comment by PedroErnst** [comment]
Hi @stefankugler 

Thanks for pointing this out.

`time_due` on Tasks is a non-db field, so it not being in the db is correct. 

But there seems to be a bug when the API retrieves the field.
