### ISSUE TITLE
Activity steam: elapsed time calculated wrong for "yesterday"

### ISSUE THREAD

**Issue by stefankugler** [salesagility/SuiteCRM#5897]
#### Issue
New activites are listed with elapsed time to creation date (eg. 10 minutes, 3 days). Elapsed days are calculated with `$days = floor( $hours / 24);`. That may be wrong for display "yesterday" with `if($days == 1)`. 
An activity created on 2018-05-16 16:00 is displayed 2018-05-18 10:00 with "yesterday".

https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/modules/SugarFeed/SugarFeed.php#L439
https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/modules/SugarFeed/SugarFeed.php#L446
https://github.com/salesagility/SuiteCRM/blob/00260c72a12f79e280ea1beb4241d03c9d39681d/modules/SugarFeed/SugarFeed.php#L461

#### Expected Behavior
Display "yesterday" only for activites created/modified "the day before". "23 hours ago" may also be "the day before", but that is not wrong.

#### Actual Behavior
"Yesterday" is displayed, if the activity was created between 24 and 47 hours ago.

#### Possible Fix
Dont't calculate difference between days with `$days = floor( $hours / 24);`. This may be wrong. Calculations for hours/weeks done this way are also affected, but that is not a big issue.
Maybe use the PHP DateTime-library (diff).

#### Steps to Reproduce

1. Create a new activity (eg. in the afternoon) and have a look the day after tomorrow in the morning.

#### Context

May be just an unaestetic issue.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 59, Chrome 66
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.29
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04 fresh installation

**Comment by PedroErnst** [comment]
Thanks for reporting this @stefankugler 

I did consider changing the calculation, but I thought it would be more consistent to just say 1 day ago for any news between 24 and 47 hours old.

This is the way many similar online systems manage this kind of data (github included), I think it makes more sense taking into account that users may be in different timezones.
