### ISSUE TITLE
[Bug] Currency symbol for currency field in popup opened from subpanel select action is always default currency

### ISSUE THREAD

**Issue by gboban** [salesagility/SuiteCRM#5906]
Currency symbol for currency field in popup opened from subpanel select action is always default currency.

#### Issue
If you add "Grand Total" (total_amount) field to listview in AOS_Quotes, amout will be displayed in list view and in list in popup which is opened from subpanel (from related module) using "select" action.

In list view ("View Quotes") currency will be displayed properly, but in list in popup, default currency would be used.

#### Expected Behavior
Currency for the amount field should be used in accordance with currency used in quote same as it is displayed in list view ("View Quotes"). 

#### Steps to Reproduce
1. Ensure that you have more than one currency (Admin -> currencies)
2. Add total_amount field to listview in studio
3. Create quote using currency that is not default
4. Go to related module - for example Accounts and open an existing record
5. Under Quotes subpanel choose "select" action
6. Check the currency for the total amount - currency for the total amount will be default currency instead one selected when creating a quote

#### Your Environment

* SuiteCRM Version used: 7.8.12
* Browser name and version: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Linux Mint

**Comment by Dillon-Brown** [comment]
Confirmed in latest 7.10.x
