### ISSUE TITLE
SMTP Server not configured after upgrading to 7.10.5

### ISSUE THREAD

**Issue by stefanomarty** [salesagility/SuiteCRM#5908]
#### Issue

After upgrading to 7.10.5 I see this note whenever I enter the crm as admin:
**Note: To send record assignment notifications, an SMTP server must be configured in Email Settings.**

If I click on the Email Settings link, I find empty SMTP Server fields. After filling data and saving, the Note is still there:
<img width="593" alt="schermata 2018-05-21 alle 18 23 33" src="https://user-images.githubusercontent.com/3297621/40319231-b589b3e4-5d27-11e8-8b65-3ecb2d579c5c.png">

If I click again, the SMTP fields are still empty:
<img width="907" alt="schermata 2018-05-21 alle 18 50 40" src="https://user-images.githubusercontent.com/3297621/40319365-3733913a-5d28-11e8-9bf9-6008d678e274.png">

If I try to send an email, it is sent without any error (just like the SMTP Server credentials were there).

I checked the outbound_table with phpMyAdmin, and the record is actually there.

**Comment by isleshocky77** [comment]
I have a similar issue; however, when clicking on the link I get a blank white page as if it was erroring.

**Comment by isleshocky77** [comment]
Seems this may be related to #5853 #5899

**Comment by AdrianoABC** [comment]
The same problem in 7.10.5 I reported [here](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19163-email-sending-settings#66326). After saving the fill in the Edge browser, it worked normally. It is not a solution to the problem, but it may indicate the path.

**Comment by Kristianostman** [comment]
Same problem after upgrade to 7.10.5. Is this just a bug with the saving of the email settings, or is it elsewhere? I mean is it possible to manually set the settings, in the db or some configuration file??

**Comment by stefanomarty** [comment]
Well I think it's elsewhere, as stated [here](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19163-email-sending-settings#66340).

I checked the database table with phpMyAdmin, and the SMTP data is actually there.

Did you try sending an email from a user account? I tried that, and the email is sent correctly in my system, so the data is saved in the DB, even it it doesn't show up in the CRM page.

**Comment by Kristianostman** [comment]
System emails seem to work, so email settings are stored yes. So in the best case this error message does not really affect anything.

**Comment by poynter2** [comment]
+1

**Comment by isleshocky77** [comment]
I just wanted to chime in that I actually tested the #5899 PR hoping it would solve this issue and it did not.

**Comment by pgorod** [comment]
Daniel Samson is looking into this issue, so I expect a fix will come soon. It ties with other issues also (confirmed opt in bugs)

**Comment by AdrianoABC** [comment]
PS: (Description) The message requesting the email configuration remained when saved with the opt in boxes checked and disappeared when unchecked, but when accessing the configuration there was no data there. Now after this suggested change in forum is ok.

**Comment by samus-aran** [comment]
Hey @isleshocky77 @pgorod @AdrianoABC 
@daniel-samson is aware of the issue and yes he is looking at it, but just to clarify this doesn't tie in with the confirmed opt in bugs - they are a separate issue. Thanks for your cooperation!

**Comment by benhalverson** [comment]
@Dillon-Brown 
I think I have a similar issue. I posted my question here https://suitecrm.com/suitecrm/forum/installation-upgrade-help/19250-email-settings-not-being-saved

Here's my error log. I am using version 7.10.5 and php 7.1
``` 
Sat May 26 02:47:15 2018 [950327][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
Sat May 26 02:47:32 2018 [950327][1][FATAL] Mysqli_query failed.
Sat May 26 02:47:32 2018 [950327][1][FATAL]  Query Failed: DESCRIBE versions: MySQL error 1146: Table 'SuiteCRM-db1.versions' doesn't exist
Sat May 26 02:47:32 2018 [950327][1][FATAL] Mysqli_query failed.
Sat May 26 02:47:32 2018 [950327][1][FATAL]  Query Failed: SHOW INDEX FROM versions: MySQL error 1146: Table 'SuiteCRM-db1.versions' doesn't exist
Sat May 26 02:47:32 2018 [950327][1][FATAL] Mysqli_query failed.
Sat May 26 02:47:32 2018 [950327][1][FATAL]  Query Failed: select * from versions: MySQL error 1146: Table 'SuiteCRM-db1.versions' doesn't exist
Sat May 26 02:54:02 2018 [1005862][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
```

**Comment by pgorod** [comment]
@benhalverson you can try the fix that is already proposed: https://github.com/salesagility/SuiteCRM/pull/5933/files

You don't have to change all those 5 files to try it, just make the changes in the first file and ignore the 4 that are in the `tests` directory.
