### ISSUE TITLE
Upgrade to 7.3.2 and now receive a missing require_once 

### ISSUE THREAD

**Issue by bickart** [salesagility/SuiteCRM#591]
I am receving an error saying that Failed opening required Zend/Search/Lucene/Storage/File/Filesystem.php

There is not a Zend/Search directory

**Comment by mattlorimer** [comment]
Zend/Search should be here:-

modules/AOD_Index/Lib/Zend/Search, 

maybe it should be in the Zend folder, but the include path is being changed to use it, are the files there for you?

**Comment by willrennie** [comment]
Hi Jeff, did you get a chance to read the comment from @mattlorimer ? Are you still receiving the error?
