### ISSUE TITLE
After upgrade from 7.9.9 to 7.10.5 all activity stream items say "0 seconds ago"

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#5918]
#### Issue

After upgrade from 7.9.9 to 7.10.5 all activity stream items say "0 seconds ago"

#### Expected Behavior

Should have correct time since the item was created

#### Actual Behavior

Only shows "0 seconds ago"

#### Steps to Reproduce

1. Upgrade from 7.9.9 to 7.10.5
2. Look on home page
3. Look at items created before upgrade as well as ones after

#### Context

Don't know when the activity is form

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 66.0.3359.170
* Environment name and version (e.g. MySQL, PHP 7): MySql , PHP 5.6.x
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by isleshocky77** [comment]
It looks like this comes from the following commit 13bacd7b818106ff919b4ab9666581ec1b41dba8

Checking for is `isset($GLOBALS['timedate']->getNow()->ts)` returns false even though there is a value there.

**Comment by pgorod** [comment]
Someone [on the Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19273-activity-stream-7-10-5#67314) says

> I had the same issue after upgrading to 7.10.5 ( 0 seconds everywhere). Updating to 7.10.6 did not solve the situation. Instead, my activity stream show 2526 weeks and 6 days ago to all activities.

**Comment by RegHal** [comment]
We just upgraded to Version 7.10.7
Sugar Version 6.5.25 (Build 344)
And we have the same problem... How can we solve this?
Thanks!

**Comment by Dillon-Brown** [comment]
Hi @RegHal, you can either wait until the next release or manually implement the changes in #6033.

**Comment by pgorod** [comment]
Maybe this needs reopening - I am getting this problem in 7.11.5. I tried only with chat entries.

- Administrator always sees "0 seconds", both for his own entries in chat, and for other people's

- other user sees correct times printed

**Comment by RegHal** [comment]
Hello,
In the version 7.10.16, I don’t have this problem in the activity stream.
Regards,
Regine



      Régine Hallet
      Sales Assistant
[cid:imageb844bb.PNG@5aa664c6.4b87da4b]<http://www.finalyse.com>
FINALYSE Group
Boulevard Bischoffsheim 33 - B-1000 Brussels - T +32 2 880 85 85
www.finalyse.com<http://www.finalyse.com> [cid:image2966b5.PNG@6cf768b1.4a887677] <https://twitter.com/FinalyseGroup>  [cid:image58f13f.PNG@404334e4.46b0795f] <https://www.linkedin.com/company/20783/admin/>



The information in this email is confidential and is intended solely for the addressee. If you have received it by mistake please notify the sender and delete it immediately. Any disclosure, copying, distribution or use of it is prohibited. Emails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with Finalyse by email is taken to accept these risks. Our Privacy and Cookies Handling Policy is available here<http://www.finalyse.com/other-pages/privacy-cookies-handling/>.
Consider the environment - please do not print this email unless you really need to.

**Comment by holdusback** [comment]
Hey everyone, 

in 7.11.6 I have negative time. 

For exemple an item created on the 12/07/2019 at 15:02 say in the activity stream :

**In Google Chrome as Admin :** 

-15 Heures -2 Minutes plus tôt

**In Firefox as a simple user :** 

3 jours plus tôt


So it work great in firefox with simple user, but not in Google Chrome as Admin ...

**Comment by pgorod** [comment]
I am also seeing what @holdusback describes (in 7.11.6)

**Comment by RegHal** [comment]
Strangely enough, I don’t see this in 7.10.16, in Google Chrome, as Admin.



      Régine Hallet
      Sales Assistant
[cid:image1f934b.PNG@1daf35a0.4499a990]<http://www.finalyse.com>
FINALYSE Group
We've moved!  New address:
The Artist - Avenue des Arts 9 - B-1210 Brussels  - T +32 2 880 85 85
www.finalyse.com<http://www.finalyse.com> [cid:image9ff6ef.PNG@7fd51de9.4a887568] <https://twitter.com/FinalyseGroup>  [cid:image44bfbe.PNG@40a8d4ea.43be763f] <https://www.linkedin.com/company/20783/admin/>



The information in this email is confidential and is intended solely for the addressee. If you have received it by mistake please notify the sender and delete it immediately. Any disclosure, copying, distribution or use of it is prohibited. Emails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with Finalyse by email is taken to accept these risks. Our Privacy and Cookies Handling Policy is available here<http://www.finalyse.com/other-pages/privacy-cookies-handling/>.
Consider the environment - please do not print this email unless you really need to.

**Comment by holdusback** [comment]
Still got this issue in 7.11.8
Some Example :
-1 Heures -29 Minutes plus tôt
2562 semaines et 2 jours plus tôt (It was like 2 weeks ago, so its bugged)

Only for admin, like I & @pgorod said before, it work great for user but not for admin.

**Comment by Dillon-Brown** [comment]
New issue here: #8004
