### ISSUE TITLE
Reopen https://github.com/salesagility/SuiteCRM/issues/5696

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#5922]
https://github.com/salesagility/SuiteCRM/issues/5696 is not fixed.

**Comment by Dillon-Brown** [comment]
@gunnicom Was this after an upgrade or are you testing on one of the branches? I can't seem to replicate.

**Comment by david-pili** [comment]
Updated to 7.8.19 Repair and rebuild. I've got problems with reports in general. Now it's hit or miss on either date-time combo pulling up correctly on reports with multiples. I'll test on a new install tomorrow and see if I can replicate.

**Comment by gunnicom** [comment]
Still not fixed in 7.8.20 for date parameters in dashlets.

**Comment by gunnicom** [comment]
And i can replicate this on the demo instance, so bug is in 7.10.x, too.
- Create Report
- Add date_created as condition twice, one as "greater than" one as "Less than or equal" , both as value
- Check parameter checkbox
- Add Dashlet -> Report
- try to change the parameter
Now you can see the bug.

**Comment by Dillon-Brown** [comment]
Confirmed, thanks.
