### ISSUE TITLE
Workflow with condition <date.field> <comparison> Today failing

### ISSUE THREAD

**Issue by maarisk** [salesagility/SuiteCRM#5927]
#### Issue
Workflow condition to select invoices with Due Date less than Today not selecting records for processing in 7.10.5

#### Expected Behavior
Records are selected and defined action perfomed on selected records

#### Actual Behavior
No records are selected and suitecrm.log having:

WHERE aos_invoices.status = 'Unpaid' AND aos_invoices.due_date < aos_invoices.today AND accounts.billing_address_country = 'Latvija' AND NOT EXISTS (SELECT * FROM aow_processed WHERE aow_processed.aow_workflow_id='b68e5ec5-16e6-cdeb-41b2-5aff1b6a808c' AND aow_processed.parent_id=aos_invoices.id AND aow_processed.status = 'Complete' AND aow_processed.deleted = 0) AND aos_invoices.deleted = 0 : MySQL error 1054: Unknown column 'aos_invoices.today' in 'where clause'
Wed May 23 18:51:00 2018 [47036][1][FATAL] Mysqli_query failed.
Wed May 23 18:51:00 2018 [47036][1][FATAL]  Query Failed: SELECT aos_invoices.id AS id, accounts.id AS 'accounts_id' FROM aos_invoices LEFT JOIN accounts accounts ON aos_invoices.billing_account_id=accounts.id AND accounts.deleted=0

#### Possible Fix
None

#### Steps to Reproduce

1.
2.
3.
4.

#### Context
Reminder e-mails about overdue invoices are not being sent

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): macOS 10.13.4

**Comment by tstanczyk** [comment]
The same can be observed with workflow condition using NOW Please find the example below.
error found in suitecrm.log:
Query Failed: SELECT calls.id AS id, leads.id AS 'leads_id' FROM calls LEFT JOIN calls_leads ON calls.id=calls_leads.call_id AND calls_leads.deleted=0 LEFT JOIN leads leads ON leads.id=calls_leads.lead_id AND leads.deleted=0
 WHERE calls.status = 'Planned' AND calls.date_start > DATE_ADD(calls.now, INTERVAL + 6 month) AND (leads.status = '' OR leads.status = 'New' OR leads.status = 'Assigned' OR leads.status = 'In Process') AND calls.parent_type = 'Leads' AND NOT EXISTS (SELECT * FROM aow_processed WHERE aow_processed.aow_workflow_id='eac28575-ece8-25ed-b98c-55a912fab1e3' AND aow_processed.parent_id=calls.id AND aow_processed.status = 'Complete' AND aow_processed.deleted = 0) AND calls.deleted = 0 : MySQL error 1054: Unknown column 'calls.now' in 'where clause'

and a screen of the workflow settings:
![image](https://user-images.githubusercontent.com/26766556/40492592-19c5ae4e-5f71-11e8-9166-4b7b0e4bcf0a.png)


We find the same (<module_table>.now column missing) error for every workflow using Now as a basis for date comparison, so i think it is a global problem regarding sql query preparation.

**Comment by HVStechnik** [comment]
I can confirm this issue. I'm running into the same MySQL error, when comparing a Date or DateTime field with NOW() or TODAY(). Both are appended to the table name, which results in the error.

**Comment by PedroErnst** [comment]
I've found the issue, it should be fixed by the above commit.

If you have the time and energy to test it please let me know if it works as expected.

**Comment by HVStechnik** [comment]
I've tested the above commit. It solves the issue and is working as expected.
Many thanks for the prompt support!
