### ISSUE TITLE
lawful basis language update

### ISSUE THREAD

**Issue by vonsch76** [salesagility/SuiteCRM#5930]
Please update and clarify the GDPR related language strings. 

Stings like 

$app_list_strings['lawful_basis_sources']['given_to_user']

have vague meaning can hardly be understood as user consent given - which likely is the meaning if I'm not mistaken. 

#### Context
SutieCrm 7.10.5

**Comment by horus68** [comment]
Just for context, the "Given to User" is an option on GDPR lawful basis source (the question is what is this!)

On the meaning, I'm not sure but it looks like this:
- Question? How did you informed user on the legal system on GDPR? 
- Reply: by email / by phone / a partner company / or directly handled to the user (as in a paper document)
 
```
//GDPR lawful basis source options
$app_list_strings['lawful_basis_source_dom'] = array(
    '' => '',
    'website' => 'Website',
    'phone' => 'Phone',
    'given_to_user' => 'Given to User',
    'email' => 'Email',
    'third_party' => 'Third Party',
);
//End GDPR lawful basis source options
```
https://github.com/salesagility/SuiteCRM/blob/bb0f2ddb22921d7301abb82a3735d015c8422327/include/language/en_us.lang.php#L2140-L2149

**Comment by likhobory** [comment]
Agree, write please some explanations about this line for quality translation.

**Comment by vonsch76** [comment]
@Horus68 Thanks, then completely misunderstood.

**Comment by pgorod** [comment]
@vonsch76 you can close the Issue if you feel it's solved.

**Comment by horus68** [comment]
@pgorod I'm not sure if this is the way it is to be used! That's why i made a mention above to e-reeley
