### ISSUE TITLE
7.10.5 - OAuth2Tokens Subpanel in Module OAuth2Clients results in DB failure using MSSQL

### ISSUE THREAD

**Issue by lucas7793** [salesagility/SuiteCRM#5931]
#### Issue

Database failure will be shown when trying to open subpanel "Active OAuth2Tokens" in module OAuth2Clients.
This error arise from wrong keywords for MSSQL server queries. 
Error in Log:
```
Thu May 24 12:02:12 2018 [47][1][FATAL] Error 1 running count query for OAuth2Clients List:  Query Failed:( SELECT count(*) c FROM oauth2tokens  INNER JOIN  oauth2clients oauth2tokens_rel ON oauth2tokens.client=oauth2tokens_rel.id AND oauth2tokens_rel.deleted=0

 where ( oauth2tokens.client=N'd4e2ffed-9b9b-9368-4752-5ad8544a559a' AND token_is_revoked = false AND (refresh_token_expires > NOW() OR refresh_token_expires IS NULL)) AND oauth2tokens.deleted=0 )::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]'NOW' wird nicht als Name einer integrierten Funktion erkannt.
```

#### Expected Behavior

The active OAuth2Tokens should be shown in the subpanel.

#### Actual Behavior

DB Failure message will be shown in the subpanel.

#### Possible Fix

Changing the query in modules/OAuth2Tokens/metadata/subpanels/default.php
from
`'where' => 'token_is_revoked = false AND (refresh_token_expires > NOW() OR refresh_token_expires IS NULL)',`
to
`'where' => 'token_is_revoked = 0 AND (refresh_token_expires > GETDATE() OR refresh_token_expires IS NULL)',`
removes the error.

#### Steps to Reproduce

1. Go to Admin->OAuth2Clients
2. Open Subpanel "Active OAuth2Tokens"

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 66.0.3359.181
* Environment name and version (e.g. MySQL, PHP 7): MSSQL 12.0.5579.0, PHP 7.0.27
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by lucas7793** [comment]
Great, the issue with the datetime has been resolved. Another problem in the same query is the value of `token_is_revoked`. When using `false`, the error is still there -> it has to be checked for `0` in MSSQL.

**Comment by PedroErnst** [comment]
@lucas7793 

Thanks for pointing that out. I've updated the query in my last commit. Please let me know if there are any issues!

**Comment by lucas7793** [comment]
@PedroErnst 
Perfect, with this change it is working fine!
