### ISSUE TITLE
Global search showing duplicates

### ISSUE THREAD

**Issue by st-ives** [salesagility/SuiteCRM#5939]
#### Issue
Global search showing duplicate accounts. When I click on either it is the same account. Therefore same account is just showing up twice.

#### Expected Behavior
Account should only appear once.

#### Actual Behavior
Account appears twice

#### Steps to Reproduce
Type an account name in global search. It will appear twice at times. Not always. it is random.

#### Context
It is confusing our sales team. 

#### Your Environment
* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Google Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MariaDB
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Mausino** [comment]
@st-ives should you add some screens ? What type of search are you using ?  Are you searching via ADVANCED OPENDISCOVERY ?

**Comment by PedroErnst** [comment]
Hello @st-ives 

Have you added any new fields to Accounts module?

**Comment by likhobory** [comment]
Confirmed in 7.10.5

AOD is enabled, the result appears twice for Contact and Leads modules, but not for Surveys module.
Lawful Basis fields has been added to Contact module.

![default](https://user-images.githubusercontent.com/5983672/40533493-a81d67be-600b-11e8-8bad-9ecf79201893.png)

**Comment by st-ives** [comment]
Yes, there are custom fields inside the Account module.

AOD is also enabled for me. 

I even tried removing the Accounts module from the Global Search, however, I am still seeing the duplicate Accounts. Therefore the Global Search function seems to be broken.

I can't post screenshots as there is sensitive client information in the results.

**Comment by pstevens71** [comment]
I can confirm I'm also having this issue.  The exact same account appears twice.  If you click on either, it's the same account.

**Comment by pgorod** [comment]
I'm trying this, but I can't reproduce. I tried with several searches but my Accounts only ever appear once...

**Comment by marbanas** [comment]
I have the same issue with leads.

**Comment by samus-aran** [comment]
Hi folk would be great to try and replicate this.

What is unique about that record that either you are: searching a particular term, or custom fields, OR custom relationships.

**Comment by pgorod** [comment]
I suggest the following procedure for whoever has this bug:

Put your log level at DEBUG so that the SQL Queries are logged. Then grab the actual query that was used for the search and go play with it in phpMyAdmin, try some changes and simplifications until you understand what is causing the duplication. 

My guess is that it's one of the JOINS that is not joining like expected, because of some peculiarity in your case: a custom table, an extra relationship, etc. For example, if a Contact belongs to two Accounts, which is possible, but that peculiar case was never tested properly.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
