### ISSUE TITLE
7.10.5 upgrade Wizard not working

### ISSUE THREAD

**Issue by Kristianostman** [salesagility/SuiteCRM#5941]
#### Issue
The upgrade wizard is not working in 7.10.5. 

#### Expected Behavior
The Upgrade Wizard should start.

#### Actual Behavior
The main frame is left blank, please see video. https://drive.google.com/file/d/1Knyf58R5_de7bVnKxtwZFohj3lTWJ_Cu/view

#### Possible Fix
NA

#### Steps to Reproduce
1. Go to Admin
2. Click "Upgrade Wizard"

#### Context
Since there are a lot of bugs in 7.10.5 and we can expect an upgrade soon it is very critical to get this working.

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 66.0.3359.181 (64-bit)):
* Environment name and version: MySQL, PHP 7:

**Comment by PedroErnst** [comment]
Hello @Kristianostman 

This sounds like a very serious issue, but does not happen in my environment.

Could you please provide some more details about your environment?
Is this an upgraded instance or a fresh install?
What does your SuiteCRM log say?
What does your PHP log say?

Thanks!

**Comment by Kristianostman** [comment]
MariaDB 10.2.8, PHP 7.1.17, Apache 2.4.6, OS Rel 7.5
In the PHP log is nothing found related to this, only regarding the other bug related to SMTP server.
PHP is excecuted via PHP-FPM.

From the sugarcrm.log nothing found related to this, though from upgradeWizard.log are these three lines generated each time I try to go to the module UpgradeWizard:
Fri, 25 May 2018 12:26:51 +0300 [UpgradeWizard] - setting session variables...
Fri, 25 May 2018 12:26:51 +0300 [UpgradeWizard] - Upgrade Wizard At Layout Commits
Fri, 25 May 2018 12:26:51 +0300 [UpgradeWizard] - Layout Commits about to show selection table

This is an upgrade instance, gone through all steps from Sugar CE Version 6.5.24 (Build 509) to current Suite CRM Version 7.10.5 - Sugar Version 6.5.25 (Build 344)

In version 7.10.4 the UpgradeWizard was still working.

**Comment by pgorod** [comment]
This discussion should be in the Forums, not here. It's user-specific (as far as we know).

**Comment by Kristianostman** [comment]
@pgorod Ok, but how could I know it is user specific in advance...

**Comment by pgorod** [comment]
It's always a good idea to start in the Forums, where you can get initial help diagnosing, and then move to Github only when you're certain it is a bug for the developers to look at.

**Comment by Mausino** [comment]
@Kristianostman i think.. the best will if you close this issue, create post on forum and when you will relevavant info how reproduce issue or what is the main problem which is creating this issue, you are able to open this ticket again and put here the detail for developers

**Comment by Kristianostman** [comment]
Ok, closing issue meanwhile I am trying in the Forum

**Comment by thomashallam** [comment]
Also experiencing this same issue in 7.10.6 - did you find a resolution? 

Permissions up from 755 using
sudo chmod -R 775 cache custom modules themes data upload config_override.php upgradeWizard.log

Ta

**Comment by mattlorimer** [comment]
Likely a cache issue from a previous incomplete/failed upgrade, check in the cache folder if the is a an upgrade folder, deleting it may solve this issue. Otherwise check the php error log.
