### ISSUE TITLE
"undefined" labels in invoice lines

### ISSUE THREAD

**Issue by goltra** [salesagility/SuiteCRM#5942]
In version 7.10.5 when you try to add lines to invoice you see "undefined" text y labels.
![image](https://user-images.githubusercontent.com/1634767/40530050-9ea7fb9a-5ff7-11e8-82b3-17dc0bb1aa3d.png)

**Comment by PedroErnst** [comment]
Hello @goltra 

Thanks for reporting this.

I am not able to reproduce this from the information you have given. Please do fill the issue template and include all relevant details.

Also, maybe do try a repair and rebuild, and repairing javascript language files.

**Comment by pgorod** [comment]
Is this is a new installation? Do you see more `undefineds` in other screens? normally these are just Linux permissions issues, so check them and reset them if necessary.

**Comment by goltra** [comment]
Right, that was a permission error. I don't know why I have 775 at jsLanguages but 755 at AOS_inovoices Thanks..
