### ISSUE TITLE
Accounts & Contacts variables are not being parsed/populated by Email Template

### ISSUE THREAD

**Issue by LuminisIndia** [salesagility/SuiteCRM#5944]
I have created a target list containing contacts.  Then set an email campaign which includes this target list.  The email template used in this campaign is having this at the top of body text:
![image](https://user-images.githubusercontent.com/12472827/40549963-745ee150-6056-11e8-8b24-33f4fc87c90c.png)

**Issue**
You can see that the template includes variable or custom fields from both contacts and accounts modules.  When the campaign is being triggered by the schedular, the following errors:
`Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $contact_first_nameÂ  could not be parsed, because attribute first_nameÂ  does not set in contact bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $contact_middle_name_cÂ  could not be parsed, because attribute middle_name_cÂ  does not set in contact bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_name could not be parsed, because attribute name does not set in account bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_billing_address_city could not be parsed, because attribute billing_address_city does not set in account bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_billing_address_state could not be parsed, because attribute billing_address_state does not set in account bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_name could not be parsed, because attribute name does not set in account bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_billing_address_city could not be parsed, because attribute billing_address_city does not set in account bean

Thu May 24 08:25:48 2018 [229486][1][FATAL] Variable $account_billing_address_state could not be parsed, because attribute billing_address_state does not set in account bean

Expected Behavior
I hope these variables should have populated properly.

#### Actual Behavior
the one space after each 'contacts' variable is being considered as a character Â and causing error/problem.  However, the 'accounts' variables are not being parsed

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* Environment name and version : PHP 7.1

**Comment by samus-aran** [comment]
@LuminisIndia Have you had an update that a fix has been proposed here: https://github.com/salesagility/SuiteCRM/pull/5964
Are you able to test this and let us know if this resolves your issues :+1:
