### ISSUE TITLE
Incorrect data at field "status" in "Cases" module after use "mass update" -> close/open

### ISSUE THREAD

**Issue by barmix** [salesagility/SuiteCRM#5949]
#### Issue

We have problem after use 'mass update' function to change state of case to closed (open) for cases group in ListView of module 'Cases'. We got incorrect data at fields 'status' and our custom field named 'subtype_c' (is child of 'type'). Look at screenshots.

#### Expected Behavior

That fields should display they actual data

#### Actual Behavior

![1527256526310](https://user-images.githubusercontent.com/37634944/40608883-a4d75fd0-6275-11e8-94f4-ff8ad532be26.jpg)
![1527257061145](https://user-images.githubusercontent.com/37634944/40608893-ab187adc-6275-11e8-86b2-7d16405ecb97.jpg)
We use SuiteCRM v7.7.4. Know this is an old version. But i'm set an experiment with this demo:
https://www.softaculous.com/demos/SuiteCRM
which use 
![1527501133990](https://user-images.githubusercontent.com/37634944/40609266-caad84a4-6276-11e8-8c82-78530e344fa7.jpg)

and got this bug too:
![1527262415696 1](https://user-images.githubusercontent.com/37634944/40609231-b3c5d1c4-6276-11e8-9295-75887ff35f07.jpg)

In DetailedView fields show the correct data. 
Incorrect in ListView only. 
Standard way to change state through the EditView passes without problems.
Nothing in logs.
Original post on forum:
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19241-some-trouble-with-mass-update-at-cases-module#66663

#### Possible Fix

Something wrong with mass update function and child dropdowns (DynamicDropdown)

#### Steps to Reproduce

1. Create account (or use existing) 
2. Create a case from account
3. Change this case state to 'closed' with mass update in list mode
4. Change this case state to 'open' with mass update
5. Look for some bugs in status
6 etc. Create custom field with DynamicDropdown type. See how it value will change after mass updates.

#### Your Environment

* SuiteCRM Version used: 7.7.4 (7.10.5 - webdemo)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Mozilla 59.02
* Environment name and version (e.g. MySQL, PHP 7): MySQL
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.2

**Comment by pgorod** [comment]
I also confirmed this in 7.10.5.

**Comment by barmix** [comment]
Ok. It works fine! This solves the problem with "status". With our custom fields I will solve the problem myself, who is interested in how to search on the forum. Thanks to all.
Can be closed
