### ISSUE TITLE
Report totals calculated incorrectly when dealing with multi-currencies

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#5956]
#### Issue

When running a report using the Grand Total field on the invoices table, the SUM function calculates incorrectly at the bottom of the page if there are multiple currencies in use.

#### Expected Behavior

The SUM function should sum all Grand Total values in the home currency

#### Actual Behavior

Grand Total values are displayed in home currency in the report lines, but the SUM function uses the foreign currency value instead.

See screenshots. Invoice 985 is for £300 GBP, issued in Euros as €343.19. The line item for invoice 985 in the report is correct (£300), but the Grand Total Sum has calculated using the Euro value instead.

Invoice 985:
![screen shot 2018-05-29 at 23 52 42](https://user-images.githubusercontent.com/17355746/40690175-9e7d7326-639d-11e8-9b82-2d74e532afcf.jpg)

Report output:
![screen shot 2018-05-29 at 23 51 51](https://user-images.githubusercontent.com/17355746/40690136-691b66b6-639d-11e8-864f-bca5f73987f8.jpg)

#### Possible Fix

None

#### Steps to Reproduce

1. Issue an invoice in a foreign currency
2. Create a report based on the Invoices table. Make sure to include the Grand Total value in the selected fields.
3. Add the SUM function on the Grand Total field
4. The SUM value at the bottom of the page will be incorrect because it is using foreign currency values

See the screenshot for report setup:
<img width="1394" alt="screen shot 2018-05-30 at 00 00 27" src="https://user-images.githubusercontent.com/17355746/40690084-1b6410b2-639d-11e8-911b-0eb605f2e388.png">

#### Context

It is currently impossible to trust any calculated values using the report engine. For me this is a big deal as I rely on SuiteCRM for accounts info and income projections. Medium priority?

#### Your Environment

* SuiteCRM Version used: 7.8.19
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 10
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by PedroErnst** [comment]
Hi @blloyd78 

Thanks for reporting this.

I've had a look, there seems to be a field you can add to the report from the Invoices module called Grand Total (Default Currency), which does what you are asking for.

![image](https://user-images.githubusercontent.com/34056696/41772660-69397e40-7611-11e8-84db-f9e9f3160ac0.png)

Let me know if this isn't what you mean.

**Comment by blloyd78** [comment]
Thanks @PedroErnst - I think you nailed it. Please close this bug report - the issue was actually user error. Sorry.

**Comment by alfoncastellote** [comment]
This bug also happen with report based on oppotunities, but the opportunities module hasnt the "Grand Total (default currency) field...
Any idea?

Thanks
