### ISSUE TITLE
Fatal error when attaching Document to Email Template

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#5958]
#### Issue

When trying to attach a Document to an Email Template, the following appears in suitecrm.log:

`Wed May 30 11:04:22 2018 [2617][1][FATAL] Exception handling in /media/datos/trabajos/SuiteCRM710/include/MVC/Controller/SugarController.php:402
Wed May 30 11:04:22 2018 [2617][1][FATAL] Exception in Controller: There is no action by that name: AttachDocuments
Wed May 30 11:04:22 2018 [2617][1][FATAL] backtrace:
#0 /media/datos/trabajos/SuiteCRM710/include/MVC/Controller/SugarController.php(553): sugar_die('There is no act...')
#1 /media/datos/trabajos/SuiteCRM710/include/MVC/Controller/SugarController.php(1088): SugarController->no_action()
#2 /media/datos/trabajos/SuiteCRM710/include/MVC/Controller/SugarController.php(465): SugarController->handleActionMaps()
#3 /media/datos/trabajos/SuiteCRM710/include/MVC/Controller/SugarController.php(373): SugarController->process()
#4 /media/datos/trabajos/SuiteCRM710/include/MVC/SugarApplication.php(109): SugarController->execute()
#5 /media/datos/trabajos/SuiteCRM710/index.php(52): SugarApplication->execute()
#6 {main}`

#### Expected Behavior

This should not be happening ;-)

#### Possible Fix

The js function callback calls docUpload() in modules/Emails/javascipt/Email.js

This function perform a asyncRequest to a non defined action (AttachDocuments) in EmailTemplates module:

`
	var url ='index.php?module=EmailTemplates&action=AttachDocuments';
	YAHOO.util.Connect.asyncRequest('POST', url, callback,null);
    //AJAX call ends`

#### Steps to Reproduce

1. Edit an Email Template
2. Attach a Document
3. See SuiteCRM log

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 60
* Environment name and version (e.g. MySQL, PHP 7): PHP7, MySQL 5.7
* Operating System and version (e.g Ubuntu 16.04): Debian 9 and Ubuntu 18.04

**Comment by belchfireid** [comment]
Having a similar problem on attaching document to Email Templates (for campaigns)
Error log
Mon Aug  6 17:11:13 2018 [18324][2ffab69f-3637-e0c1-bac6-51256403d2c0][FATAL] Exception in Controller: There is no action by that name: AttachDocuments
```
Mon Aug  6 17:11:13 2018 [18324][2ffab69f-3637-e0c1-bac6-51256403d2c0][FATAL] backtrace:
#0 /volume1/web/sugarcrm/include/MVC/Controller/SugarController.php(553): sugar_die('There is no act...')
#1 /volume1/web/sugarcrm/include/MVC/Controller/SugarController.php(1088): SugarController->no_action()
#2 /volume1/web/sugarcrm/include/MVC/Controller/SugarController.php(465): SugarController->handleActionMaps()
#3 /volume1/web/sugarcrm/include/MVC/Controller/SugarController.php(373): SugarController->process()
#4 /volume1/web/sugarcrm/include/MVC/SugarApplication.php(109): SugarController->execute()
#5 /volume1/web/sugarcrm/index.php(52): SugarApplication->execute()
#6 {main}
```
SuiteCRM 7.10.7
Firefox 61
PHP 5.6, MariaDB10
OS: Synology  Linux Diskstation 3.10.105

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
