### ISSUE TITLE
Workflow case update action email fails to related field contacts:contact - no way to figure out why

### ISSUE THREAD

**Issue by elsaadj** [salesagility/SuiteCRM#5966]
#### Issue
Workflow on "case update" modules, when case updated the actions is to send email to (To, Related Field, Contact: Contact) and another email to (To, Related Field, Users: Assigned to). The email to Assigned to works but the email to contact fails. No errors or tracing in the logs. We only see failed in the workflow processing audit.

#### Expected Behavior
The action is to send email to case update related field contact.

#### Actual Behavior
Failed in the workflow processing audit. no way to find why.

#### Possible Fix
None

#### Steps to Reproduce
1. create account and contact
2. create workflow module case update, on record save, any case update, action email related field contacts:contact
3. create case on that account and update the case
4. workflow shows failed

#### Context
Need to send email with case updated to account contact.
This major as it silently fails and no way to figure it out.

#### Your Environment
mysql Ver 14.14 Distrib 5.7.22,
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
server version: Apache/2.4.18 (Ubuntu)
Description:	Ubuntu 16.04 LTS
Browser Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by PedroErnst** [comment]
Hi @elsaadj 

What's your SuiteCRM version?

**Comment by elsaadj** [comment]
Version 7.10.3
Sugar Version 6.5.25 (Build 344)

**Comment by PedroErnst** [comment]
Thank you for the feedback. 

Otherwise, you mention there is nothing in the logs. I'm assuming you turned them up to at least Error level, or even Warn?
Also, did you check the php error logs?

Also, there have been a considerable number of bugfixes in both the WF module and the Emails module since v 7.10.3. If you have the chance to safely upgrade to 7.10.7 that might just solve the issue.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
