### ISSUE TITLE
I cannot go to next page for Products List View on 7.10.6

### ISSUE THREAD

**Issue by alexwang2013** [salesagility/SuiteCRM#5970]
After I changed [ Listview items per page ] in System Settings page. The user cannot navigate to next page in Products List View. While the Administrator can navigate to Next page in Products List View.

**Comment by Dillon-Brown** [comment]
@alexwang2013 What version of SuiteCRM were you testing on? I can't seem to replicate on 7.10.5/7.8.19 either by increasing or decreasing the Listview items per page. Do you have anything in your suitecrm logs or the console?

**Comment by alexwang2013** [comment]
@Dillon-Brown Thanks for your quick reply. 

The version of SuiteCRM here is Version 7.8.16.

this is browser console output
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "/themes/SuiteR/css/colourSelector.php".
VM357 index.php:594 Resource interpreted as Document but transferred with MIME type image/gif: "/index.php?entryPoint=getImage&imageName=blank.png".
DevTools failed to parse SourceMap: /jquery.qtip.min.js.map
```

and there is no special in suiteCRM logs file.

**Comment by alexwang2013** [comment]
@Dillon-Brown 
after I upgrade to 7.10.6, it is the same issue.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
