### ISSUE TITLE
SuiteCRM as a Composer package

### ISSUE THREAD

**Issue by kfb-ts** [salesagility/SuiteCRM#5976]
Hello

I'd like SuiteCRM to work as a Composer package. I'm willing to actually work on that i.e. contribute.
Would you at all be interested in going into that direction? Are you already working towards that? Not that I waste my time with this.

Sadly the current plans for SuiteCRM don't really seem quite transparent, so it's difficult to get a grasp on what functionality you're already working on in that direction (e.g. single entry point, routing), how much backwards compatibility to core code changes you actually want to provide and so on.
Is there a way to get to that information?

**Comment by Dillon-Brown** [comment]
Hey @kfb-ts, apoligies that this got lost in the backlog without an answer..... For information on what features are currently being developed (Aside from watching the develop branch) the best place would be the main suitecrm.com site which has our plans for Suite8. Alternatively you could look at the announcements board of the forums or join us on [Gitter](https://gitter.im/suitecrm/Lobby). 

Atm SuiteCRM as a composer package is not in our short term plans. It's definitely something i'd love to see though!

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SuiteCRM as a Composer package](https://trello.com/c/VTPwvXjd/259-suitecrm-as-a-composer-package)
