### ISSUE TITLE
quotes, error in product_qty

### ISSUE THREAD

**Issue by mcarop** [salesagility/SuiteCRM#598]
hello, please check my Post and comments in:

https://suitecrm.com/forum/suitecrm-7-0-discussion/6799-quotes-error-in-product-qty

thanks.

**Comment by paulgodley** [comment]
Can you please take a screen shot of your settings under Admin->Local and attach it to this issue post?

**Comment by mcarop** [comment]
dears, my settings...
thanks...

![settings-crm](https://cloud.githubusercontent.com/assets/15343823/11041669/f2b5aaac-86f1-11e5-9ad9-8187c364cf74.png)

**Comment by paulgodley** [comment]
Hi there, can you please click on your Admin->Locale settings (example below) and send them over?
![suitecrm 2015-11-10 08-54-53](https://cloud.githubusercontent.com/assets/9193412/11058173/c3187ae4-8788-11e5-9c5e-9df5a7184eb0.png)

**Comment by mcarop** [comment]
jojo, sorry.
when i change the dot and comma occurs same problem.
i have 3 suitecrm facilities and in all is the same.
thank you
 
![local](https://cloud.githubusercontent.com/assets/15343823/11061870/dabc97ac-8788-11e5-985d-4c0ca67a6e1f.png)

**Comment by paulgodley** [comment]
Hi there.  I have installed a clean version of 7.3.1 and set my decimal / thousand separators to be the same as yourself.  This gives me the output below.
![bug598investigation](https://cloud.githubusercontent.com/assets/9193412/11094041/6a4b517c-8885-11e5-8aeb-c8f89656458b.png)
I will have a look through the code to see what could possibly be setting this incorrectly for yourself.  In the meantime, could you please try a clean install of the newest version of SuiteCRM and let me know if you still experience the same problem?

**Comment by mcarop** [comment]
hello.
ok, look my picture.
 
i need work with no decimals.

I make a clean install and is the same

thanks for your help.
![user pref](https://cloud.githubusercontent.com/assets/15343823/11096246/daf9793e-8877-11e5-9347-7da2f7c55e38.png)

**Comment by paulgodley** [comment]
Perfect, thank you for that.  I have been able to reproduce the issue my side (as shown below).  This happened when I changed the  Currency Significant Digits field to 0.  I will keep you updated as to the fix.
![598recreated](https://cloud.githubusercontent.com/assets/9193412/11096670/3a814d12-8893-11e5-8ae4-0004ae733c53.png)

**Comment by mcarop** [comment]
Perfect... ;)

**Comment by mcarop** [comment]
sorry,

it's posible work with decimals in quantity and Currency Significant Digits field to 0??

So far we can not make quote 1.5m of cable (example).

understands?

*is one or two, but no 1,5... when Currency Significant Digits field to 0
*is 1,5 when Currency Significant Digits field to 1+

perhaps, it is the standard and I'm wrong.

Thank you.

**Comment by paulgodley** [comment]
Hi there.  I have had a test and it seems that to use decimals for quantity, you would need to have currency significant digits set to greater than 0.  This will allow you to have 1.5m of cable without it rounding up to 2m.  I am currently working on a fix to the original issue of the zeros being removed from the end of the quantity and I will update you when this is done.

**Comment by paulgodley** [comment]
Hi there, I have tested this and if you have Currency Significant Digits field set to 0, you cannot use 1.5 for quantity (it will round up to 2).

**Comment by paulgodley** [comment]
Hi @willrennie as per @mcarop's comment, can you please advise if this fix is in version 7.4.3?

**Comment by mcarop** [comment]
Dear paulgodley, now this error ocurrs when print to pdf.
pdf not show 0.

**Comment by paulgodley** [comment]
Hi @mcarop, can you please log this as a separate github issue and we will look into it for you?  Please attach a screen shot (if possible) of the error message that you are receiving.
