### ISSUE TITLE
Bounced Emails are not processed properly in SuiteCRM 7.10.5

### ISSUE THREAD

**Issue by LuminisIndia** [salesagility/SuiteCRM#5980]
When the Email Campaign is executed, it does not process the bounced email in appropriate manner.  

#### Issue
The campaign sent/attempted 534-emails.  There were 66-emails which were returned with the message: "A message that you sent could not be delivered to one or more of its   recipients. This is a permanent error."  However, 2-issues were presented:
1.  All these 66-emails were returned to the email ID which was, e.g. info@yourdomain.com, configured as 'From' & 'Return To' email address.  Note:  The emails were sent via the outbound system account, which was same as info@yourdomain.com.  I believe that these emails should have returned to the email id, 'bounces@yourdomain.com' which was pre-configured as ID meant for bounced emails.
2.  None of these 66-emails which returned were lodged as Bounced Emails in the STATUS REPORT of the campaign.
![image](https://user-images.githubusercontent.com/12472827/40873051-ea6fb5ba-6676-11e8-9740-ed7424ac92a1.png)

#### Expected Behavior
These 66-emails should have been considered/recorded as bounced emails appropriately, based upon the error code these emails generated.  For examples:
452  1-Email
550  9-Emails
554  7-Emails
550 5.1.1 1-Email
550 5.1.10  1-Email
550 5.7.1  4-Emails
550-5.1.1  7-Emails
550-5.2.1  25-Emails
550-5.2.2  4-Emails
(No code)  7-Emails

The summary compiled of all emails which returned is attached herewith:
[TEMP1.xlsx](https://github.com/salesagility/SuiteCRM/files/2064866/TEMP1.xlsx)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:  7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Latest
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7.1
* Operating System and version (e.g Ubuntu 16.04):

**Comment by LuminisIndia** [comment]
Dear Team,

Yesterday I did make a partial re-run of the above-mentioned email campaign.  I wish to inform you that this time it has collected 8-emails marked as 'Bounced Messages: Others'
![image](https://user-images.githubusercontent.com/12472827/40911693-260d05cc-680d-11e8-8af9-9b0e87eddbc9.png)

Kindly take into consideration w.r.t. about issue.

With thanks,

RK

**Comment by lazka** [comment]
I've created a fix for this: #6505

**Comment by samus-aran** [comment]
This is now a duplicate and this issue supersedes this.
If able @LuminisIndia Can you assess the proposed pull request that would be great to progress it!
