### ISSUE TITLE
Error when calling API - access token

### ISSUE THREAD

**Issue by namgivu** [salesagility/SuiteCRM#5986]
I follow [this guide](www.vultr.com/docs/how-to-install-suitecrm-on-ubuntu-16-04) and get our SuiteCRM running [here](159.65.2.33)
Though I calling to **POST /api/oauth/access_token** as [guided here](docs.suitecrm.com/developer/api/version-...gure-authentication/) I get error saying that the endpoint is not available on my server

> The requested URL /api/oauth/access_token was not found on this server

I use Postman to make the request as attached snapshot.
Please guide me how to get API working.

![selection_226](https://user-images.githubusercontent.com/1185192/40922598-d5f84332-683c-11e8-8633-1b23040a5f99.png)

ps. I also post on [our forum](https://suitecrm.com/suitecrm/forum/developer-help/19362-error-when-calling-api)

**Comment by Mausino** [comment]
@namgivu in version 7.10+ is supported only v8 api

**Comment by prasadh13** [comment]
Were you able to resolve this? In my case, there is no lib/API folder path as described in the documentation.

**Comment by samus-aran** [comment]
Check if your htaccess has correctly set up the API route i.e. domain/api/ etc etc

@prasadh13 If there is no lib/API folder then it seems that it hasn't downloaded everything.
