### ISSUE TITLE
Workflow condition bug in 7.10.5

### ISSUE THREAD

**Issue by ghost** [salesagility/SuiteCRM#5990]
#### Issue
I'm using workflows to keep planned calls related to owner of opportunity.
Config of workflow:
![image](https://user-images.githubusercontent.com/30261902/41025124-6a77a02c-6971-11e8-87b6-88d47dc82460.png)

I want only  planned calls to change owner with opportunity owner change, so i set two condtions.
1. Owner of call is different from owner of opportunity
2. Call status equals planned

I don't want historical recored to be changed do keep history who made contact with client. 

#### Expected Behavior
Workflow should change owner only in calls which status equals = planned and owners are different in opportunity and call.

#### Actual Behavior
Workflow seems to ignore second codnition and changes owner of every call related with opportunity.

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version: Chrome Version 67.0 (64-bit)
* Environment name and version: PHP 7.2, MySQL
* Operating System and version: CentOS

**Comment by AdminPL** [comment]
I tried Fix/5803 workflow any change related #5818 i hoped it may be related but no change.

**Comment by cjmny** [comment]
I can confirm this bug in 7.10.6 as well.  When you are using workflows to trigger followup emails, this is a huge issue.

**Comment by SinergiaCRM** [comment]
Hi @jack7anderson7, this issue is similar to https://github.com/salesagility/SuiteCRM/issues/8682, and is closed. Is this issue also solved?

Thanks

**Comment by jack7anderson7** [comment]
Hi @SinergiaCRM, 

After testing on the latest version (7.14.2) I am unable to replicate this issue. So I can confirm that it is resolved. I will close this as a result.

Thanks,
Jack
