### ISSUE TITLE
Footer Header and page section PDF templates : a line is added  after each save

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#5992]
#### Issue

Each time you SAVE a PDF template it adds the following line to the FOOTER HEADER and the PAGE itself section.
This makes the footer shift UP each time you save.
![image](https://user-images.githubusercontent.com/26340942/41034300-6f10bd2c-6989-11e8-8b72-fae95d087ade.png)

#### Expected Behavior
FOOTER should remain unmodified

#### Possible Fix
Workaround, each time you save you have to delete those lines

#### Steps to Reproduce

1.Open a previous template
2.save it
3.open it
4.looka at the footer section

#### Your Environment
PHP 7.0
Ubuntu 16.04
Version 7.8.18

**Comment by PedroErnst** [comment]
Hi @hubyhuby 

I'm unable to reproduce this on Chrome.
Which browser do you use?

**Comment by hubyhuby** [comment]
Hi @PedroErnst ,
I am on Firefox 60.0.2 / Ubuntu 18.04

**Comment by PedroErnst** [comment]
Thanks, I just tried FF and same result, no duplicated tags.

Do you use Selenium at all?
Does the same thing happen if you go to https://demo.suiteondemand.com and follow the steps?

**Comment by hubyhuby** [comment]
Ho @PedroErnst ,
I actually use Selenium with geko driver on another project.
But when the bug arrive I am not piloting FF with selenium, I am just using my CRM .
Not sure how it could interfer with Suite CRM...

**Comment by hubyhuby** [comment]
It looks you are right, it s using selenium in the background piloting ANOTHER FF that bleeds into the regular FF ... Very strange... It seems  without Selenium running it works.
We can close this bug and reopen it if needed.
