### ISSUE TITLE
Adding a picture in PDF template adds a blank page

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#5993]
#### Issue
When adding a picture and centering it a blank page is generated at the end of the exported PDF

#### Possible Fix
None. After trying 20 times I couldn t find a workaround

#### Steps to Reproduce
1.Open a template
2.Add at picture and center it
3.Print to PDF 
4. The pdf has a blank page at the end

#### Your Environment
Ubuntu 16.04
Firefox
Suite crm 7.8.16

**Comment by Pawes** [comment]
I just posted a somewhat related issue #5994. Is the image you are trying to add by any chance a SVG file?

**Comment by hubyhuby** [comment]
In fact this is a side effect of this bug : 
I adds a blank page because the page is field with div div
https://github.com/salesagility/SuiteCRM/issues/5992
