### ISSUE TITLE
[7.10.4-7.10.6] Contact & Lead edit incorrect labels for address

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#5996]
#### Issue
From v7.10.4 to present 7.10.6 the address labels in the edit detail view say "LBL_PRIMARY_STREET:" and "LBL_ALT_STREET:" instead of "Address" or "Street".
#### Expected Behavior
Should have the correct label

#### Actual Behavior
See screenshot
<img width="1097" alt="screen shot 2018-06-06 at 21 30 51" src="https://user-images.githubusercontent.com/3494567/41073546-c8647f88-69d1-11e8-901f-c0505cde9722.png">

#### Steps to Reproduce
1. Create new Lead or Contact. You'll see the wrong label part way down the data entry screen.

#### Context
Hasn't affected performance but it is sloppy to show the field name.

#### Your Environment

- SuiteCRM Version used: 7.10.4-7.10.6
- Browser name and version: Current Firefox 60.0.1 
- Environment name and version (e.g. MySQL, PHP 7): mysql Ver 15.1 Distrib 10.1.26-MariaDB, PHP 7.0.27
- Operating System and version (e.g Ubuntu 16.04): Debian 9 (current)

**Comment by Dillon-Brown** [comment]
@bunk3m I'm not able to replicate on 7.10.6. Have you tried a repair and rebuild?

**Comment by bunk3m** [comment]
@Dillon-Brown, I did the Repair & Rebuild on 7.10.4 and continued to have the problem.

After receiving your note, I did it again with 7.10.6 and it appears to have fixed the problem.

Now I'm left scratching my head why it didn't work the last time...
