### ISSUE TITLE
Workflow error in cutom module

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#5997]
#### Issue
I've created custom module based on document to store generetaed pdf exported from invoice module.
Number of invoice is equal to number of document so i made a workflow to copy number from invoice to my custom module field.

After patch 7.10.4 ( not sure ) workflow stopped working.

![image](https://user-images.githubusercontent.com/30261902/41088931-fec862c8-6a40-11e8-9ab6-fe7be0a15bb1.png)

#### Expected Behavior
Workflow should change document number if it's different from invoice number.

#### Actual Behavior
No change of field only error:

Thu Jun  7 08:44:05 2018 [3421][1][FATAL]  Query Failed: SELECT aos_invoices.id AS id FROM aos_invoices LEFT JOIN fv_fakturyzyskowe_aos_invoices_c ON aos_invoices.id=fv_fakturyzyskowe_aos_invoices_c.fv_fakturyzyskowe_aos_invoicesaos_invoices_idb AND fv_fakturyzyskowe_aos_invoices_c.deleted=0

LEFT JOIN fv_fakturyzyskowe fv_fakturyzyskowe_aos_invoices ON fv_fakturyzyskowe_aos_invoices.id=fv_fakturyzyskowe_aos_invoices_c.fv_fakturyzyskowe_aos_invoicesfv_fakturyzyskowe_ida AND fv_fakturyzyskowe_aos_invoices.deleted=0
LEFT JOIN fv_fakturyzyskowe_cstm fv_fakturyzyskowe_aos_invoices_cstm ON fv_fakturyzyskowe.id = fv_fakturyzyskowe_aos_invoices_cstm.id_c  WHERE fv_fakturyzyskowe_aos_invoices_cstm.numer_c != aos_invoices.number AND aos_invoices.id = '8a6d2301-5b93-2c5a-c425-5b17c0bdb4e6' LIMIT 0,1: MySQL error 1054: Unknown column 'fv_fakturyzyskowe.id' in 'on clause'
Thu Jun  7 08:44:05 2018 [3421][1][FATAL]  Get One Failed:SELECT aos_invoices.id AS id FROM aos_invoices LEFT JOIN fv_fakturyzyskowe_aos_invoices_c ON aos_invoices.id=fv_fakturyzyskowe_aos_invoices_c.fv_fakturyzyskowe_aos_invoicesaos_invoices_idb AND fv_fakturyzyskowe_aos_invoices_c.deleted=0

LEFT JOIN fv_fakturyzyskowe fv_fakturyzyskowe_aos_invoices ON fv_fakturyzyskowe_aos_invoices.id=fv_fakturyzyskowe_aos_invoices_c.fv_fakturyzyskowe_aos_invoicesfv_fakturyzyskowe_ida AND fv_fakturyzyskowe_aos_invoices.deleted=0
LEFT JOIN fv_fakturyzyskowe_cstm fv_fakturyzyskowe_aos_invoices_cstm ON fv_fakturyzyskowe.id = fv_fakturyzyskowe_aos_invoices_cstm.id_c  WHERE fv_fakturyzyskowe_aos_invoices_cstm.numer_c != aos_invoices.number AND aos_invoices.id = '8a6d2301-5b93-2c5a-c425-5b17c0bdb4e6': MySQL error 1054: Unknown column 'fv_fakturyzyskowe.id' in 'on clause'

#### Context
Bug is extremly annoying and cost a lot of work to workaround. 

#### Your Environment
*SuiteCRM Version used: 7.10.6
Browser name and version: Chrome Version 67.0 (64-bit)
Environment name and version: PHP 7.2, MySQL
Operating System and version: CentOS

**Comment by cjmny** [comment]
@PedroErnst I've been working on a full report for this, but in the meantime I can confirm as well.  It looks like if there is a Custom Module involved in the "where" clause, the syntax of the column names is incorrect (see my comment on #5990 ).  A similar issue that I've been having a much harder time grabbing diagnostics for is the Workflow executing when one of many conditions is true, regardless of the other conditions.  That needs a bit more of a workup though.

**Comment by AdminPL** [comment]
PedroErnst 

I'm trying to do better every time. In this case i can not think of any more information than there is in this ticket. No additional actions or anything i could be missing. It's just workflow which should copy value of one integer filed to antoher in custom module. 

Fields are both identicial parameters and in the past it worked.

Relation between modules is many to many. But I tried in non production system with one to many with no difference.
