### ISSUE TITLE
Dashlet Page Scroll

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#600]
Changing the page inside of a Dashlet causes it to load the entire dashboard inside the dashlet instead of the new page.

![bildschirmfoto 2015-10-27 um 16 08 03](https://cloud.githubusercontent.com/assets/15199551/10762254/9a820334-7cc5-11e5-9591-88f931214d3a.png)
![bildschirmfoto 2015-10-27 um 16 08 22](https://cloud.githubusercontent.com/assets/15199551/10762259/9f3c099c-7cc5-11e5-83e0-05489f2a4e3d.png)
![bildschirmfoto 2015-10-27 um 16 08 33](https://cloud.githubusercontent.com/assets/15199551/10762265/a29f4a40-7cc5-11e5-9c9b-92b6243490c2.png)

Tested on a clean install, version 7.3.1

**Comment by simbanic** [comment]
One possible reason for it is - url of dashlet pagination. MySugar.php response with entire home page in place of particular dashlet.

**Comment by willrennie** [comment]
This should be fixed in 7.4.3 onwards. Can you confirm?

**Comment by Mausino** [comment]
@willrennie  we tested this this issue and it's resolved (7.4.3) on our system

**Comment by samwhatley** [comment]
I'm not sure this is fully fixed, certainly on my system which is running 7.7.2.

It seems to depend what the URL of the dashboard is. Issue #442's commit solves the problem by changing the Home link to "index.php?module=Home&action=index", but if you land on the homepage through typing the address directly and then paginate through results, then it loads the dashboard inside a dashlet again.

**Comment by jobvector** [comment]
Can confirm it: changing the page inside of a Dashlet causes this issue #442
Can be replicated with the activity stream dashlet.

**Comment by jobvector** [comment]
seems to be fixed with 7.7.4 Suite P theme (tested for "My Calls" & "Activity Stream" Dashlets)
