### ISSUE TITLE
Dashlet "My Activity Stream" save settings is not working

### ISSUE THREAD

**Issue by Referro** [salesagility/SuiteCRM#6005]
#### Issue
The dashlet "My Activity Stream" on the dashboard is not able to be changed. Click on the pencil icon in the dashlets header and try to change settings. If you click on "Save", nothing happens.
Browser console reports:
"ReferenceError: promptAuthentication is not defined"

#### Expected Behavior
The expected behavior should be that you are able to edit the dashlets options (for instance only viewing opportunities and leads in the feed).

#### Actual Behavior
The dashlet "My Activity Stream" is not able to be changed what it is showing. Browser console reports "ReferenceError: promptAuthentication is not defined".

#### Possible Fix
Probably a javascript file is not included or the function has been deprecated but not yet removed from this dashlet.

#### Steps to Reproduce

1. Open SuiteCRM dashboard, make sure the dashlet "My Activity Stream" (in the dashlets menu it is placed under "Tools") is available on the dashboard
2. Click the pencil icon in the dashlets header bar
3. Try to make changes and click save
4. Notice that nothing happens (view your browsers console to see the error notice).

#### Context

One of our customers wants to see the activity stream of only leads and opportunities, but is unable to.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox Quantum 60.0.2 (64-bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, 10.0.35-MariaDB - MariaDB Server
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by pgorod** [comment]
I can't reproduce this on my 7.10.10, it se4ms to work well.

Is this still a problem for you? Thanks.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by timo-ecm2** [comment]
Hoi Referro & Dillon-Brown, yes indeed I can replicate this issue in SuiteCRM v7.11.22 Sugar Versie 6.5.25 (Build 344). 



![Naamloos](https://user-images.githubusercontent.com/51777898/135085260-b0293f5a-8346-441f-8806-052491497f46.png)

**Comment by timo-ecm2** [comment]
Hoi Referro & Dillon-Brown, yes I can replicate this issue inVersie 7.11.23 Sugar Versie 6.5.25 (Build 344). Soon I will
