### ISSUE TITLE
Assigned-to column empty on Emails Module

### ISSUE THREAD

**Issue by labcerouno** [salesagility/SuiteCRM#6008]
If you add the Assigned-to column to the Emails list view, it won't show nothing in this column.

#### Issue
When checking inbox on Emails Module, we can add the column "Assign to", that should show the usernames whose messages have already been imported and assigned to. But this field appears empty for all imported messages.

![2018_06_08_16_28_39_3b_optic_crm](https://user-images.githubusercontent.com/2539666/41177160-67c309b0-6b39-11e8-8a0c-013ca7cd6264.png)

#### Expected Behavior
The messages already imported must show the username which they were assigned to.

#### Actual Behavior
Assigned-to column is empty. Logs won't show any error related to this issue.

#### Steps to Reproduce
1. Go to Emails modules
2. Import any message and assign it to an user
3. Back to inbox view
4. Click "Column selector" button
5. Drag and drop "Assigned to" rectangle to the upper list (it will turn green)
6. Save changes

#### Context
We are migrating from Gmail to SuiteCRM Emails module. One of the most used features in Gmail is the Labels feature, which allows our Sales Team to assign messages to different sellers.  The message assignment in Suite is a perfect replacement for this feature. For our company this can save a great amount of time.

#### Your Environment
* SuiteCRM Version used: 7.10.6
* Browser name and version: Chrome 66.0.3359.117 (64-bits) / Firefox 59.0.2 (64-bits)
* Environment name and version: PHP 7.0 FPM, Percona Server 5.6
* Operating System and version: Ubuntu 17.10

**Comment by Abuelodelanada** [comment]
I can reproduce this bug in 7.10.7
