### ISSUE TITLE
Choose Targets Campaigns error last step

### ISSUE THREAD

**Issue by maverikmaverik** [salesagility/SuiteCRM#6025]
#### Steps to Reproduce

The error is when you create a **Newsletter campaign** with both version 7.10.5 and 7.10.6

1. **Launch wizard** -> step **Target Lists** -> select **Target**
2. Next step **Templates**, back to step previous, loses the target list and appears in the list of new target lists that I have not created.
3.  In the step **Send Email and Summary**, as it loses the target lists, Choose Targets with red blade 

![screenshot_0](https://user-images.githubusercontent.com/40229134/41338670-2214f4ec-6ef3-11e8-9d47-4468d1814396.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40229134/41338691-308f995a-6ef3-11e8-89ea-6d445ac31cf2.jpg)
![screenshot_3](https://user-images.githubusercontent.com/40229134/41338714-4124a3e6-6ef3-11e8-9c12-9c4aabb9a606.jpg)
![screenshot_5](https://user-images.githubusercontent.com/40229134/41338720-4554e912-6ef3-11e8-8a3a-29412ab82fbe.jpg)
![screenshot_6](https://user-images.githubusercontent.com/40229134/41338734-4c9a8c72-6ef3-11e8-8316-9ce6743873af.jpg)
![screenshot_7](https://user-images.githubusercontent.com/40229134/41338739-4e835956-6ef3-11e8-8dd6-d730dd9d020b.jpg)

#### Context

**suiteCRM forum**
[TOPIC: Choose Targets Campaigns error last step](https://suitecrm.com/suitecrm/forum/gestion-de-errores/19478-choose-targets-campaigns-error-last-step#67586)

I tried it in the official demo with Newsletter type.

It is clearly a bug as you highlighted.

1. If you navigate back no target list remains selected.
2. However if you exit from the creation of the Campaign and go to the list view, then select the campaign, in Edit view all available target lists are selected.

This a very dangerous and nasty bug, high priority

This is a **critical issue** because if one does't realise the problem he may end up sending a newsletter to all atrget lists created in the system and this is really unwanted and against **GDPR**

#### Your Environment

* SuiteCRM Version used: 7.10.5 and 7.10.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all browsers
* Environment name and version (e.g. MySQL, PHP 7): Mysql an php7
* Operating System and version (e.g Ubuntu 16.04): Centos

**Comment by pgorod** [comment]
Possibly related (but I am not sure it is):

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19488-error-adding-target-lists-to-a-newsletter-campaigns

**Comment by maverikmaverik** [comment]
No is the same problem, the one you mention is another that is not solved either, but it is independent of this other one.

**Comment by ApatheticCosmos** [comment]
That javascript error is being triggered by line 294 in modules/Campaigns/tpls/WizardCampaignTargetListForNonNewsLetter.tpl
`document.getElementById('no_targets').style.display = 'none';`
'no_targets' is not in the DOM.

Why is the file named 'ForNonNewsLetter'? We're creating a newsletter... Is it using the wrong template?

**Comment by gymad** [comment]
@ApatheticCosmos - Thank you for the very well detailed issue report. I found a possible fix for this issue, can you please confirm if it's works now?

**Comment by ApatheticCosmos** [comment]
@gymad It now has
`[Campaign Header> [Subscriptions> [Templates>
`at the top instead of 
`[Campaign Header> [Target List> [Templates>`
and the javascript error is gone.

There is also a note on the Subscriptions page that says:

> Each campaign requires target lists for subscription, unsubscription and test. When a list is not specified, an empty target list will be created on save.

I think this is the proper behavior, but @maverikmaverik should test in his environment to make sure it's fully working.

**Comment by maverikmaverik** [comment]
Produces a new error, it is not correct.

![screenshot_1](https://user-images.githubusercontent.com/40229134/41457908-6869de60-7085-11e8-8211-aacc336ccc27.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40229134/41457909-6884b87a-7085-11e8-9e92-d3726d5e9c08.jpg)
![screenshot_3](https://user-images.githubusercontent.com/40229134/41457910-689f6288-7085-11e8-980d-d49778c78a8f.jpg)

**Comment by maverikmaverik** [comment]
It is not closed, it has not been resolved yet.

I do not know why it's closed

**Comment by maverikmaverik** [comment]
It is not closed, it has not been resolved yet.

I do not know why it's closed

**Comment by samus-aran** [comment]
@maverikmaverik It appears you had closed it (perhaps by mistake?) looking at the activity stream.
Are you able to provide some logs to identify that 500 error. I suspect it could be permissions, did you reapply correct permissions when you applied the file changes from the proposed pull request?

@gymadarasz Can you assist and help out.

**Comment by maverikmaverik** [comment]
themes permisos 775

**Comment by samus-aran** [comment]
@maverikmaverik logs?
That would give a more accurate description of causing a 500.

**Comment by maverikmaverik** [comment]
error_log and suitecrm_log do not give any

![screenshot_4](https://user-images.githubusercontent.com/40229134/41468390-1cf4623c-70aa-11e8-9283-73f7a5be6f75.jpg)

**Comment by gymad** [comment]
@maverikmaverik we can not replicate the blank screen, I assume there is a mistake in your colourSelector.php but it seems correct in the current branch, however 500 server error means something wrong in the server itself (like file permission) or it could be a syntax or parse error in the php interpreter. You can look into your apache log to find an error message (using the correct php.ini settings)

**Comment by maverikmaverik** [comment]
When the next release?

Thank you

**Comment by maverikmaverik** [comment]
I'm trying the campaigns again, it's impossible to create a campaign, this option does not work, version 7.10.6 - 7.10.7

In the last step follows the Choose Targets error and it is selected. It can be seen in the images.

Click on Choose Targets goes to the Subscriptions step and 2 TARGETS LIST appear that I have not created, see images.

Now you go to TARGETS LIST option and have automatically created 2 targets list that I had not created:

1 - CAMPAING NEWSLETTER TEST Unsubscription List
2 - CAMPAING NEWSLETTER TEST Test List

Thank you

**Comment by jfd118** [comment]
I am using V7.10.7 and the same problem occurs when creating an email campaign.   The "Target List" not select error appears.

**Comment by mcolangelo** [comment]
I am using 7.10.8 and have the same issue.  I can execute a test email, but I am manually selecting the Send Test action button and then selecting my email campaign which will send successfully at that time.  


![image](https://user-images.githubusercontent.com/10851516/45825559-85d6f500-bcc0-11e8-932d-726beaae7f58.png)


![image](https://user-images.githubusercontent.com/10851516/45825610-a010d300-bcc0-11e8-9b3f-ca984943c82e.png)
