### ISSUE TITLE
"Send Confirm Opt In Email" is missing in contact's action menu 

### ISSUE THREAD

**Issue by mbennoer** [salesagility/SuiteCRM#6028]
#### Issue
In the official documentation, a feature is described to send/resend confirmation emails through a contact's action menu (Send Confirm Opt In Email). This menu item is not present.

![send_conf_man](https://user-images.githubusercontent.com/40206475/41349138-308eff60-6f0f-11e8-868d-53d8eae5f419.png)

In the bulk action menu at contact list view, the menu item is present as described.

#### Expected Behavior
Menu item "Send Confirm Opt In Email" should be present as described

#### Actual Behavior
Menu item "Send Confirm Opt In Email" is missing

#### Steps to Reproduce

1. Activate Confirmed Opt In procedure in email settings
2. Edit contact details and tick "Opted in"
3. Open Action menu in contact details
4. The menu item "Send Confirm Opt In Email" is missing

#### Context
Since there is a workaround available (send from bulk action), priority is rather low. However, sending the mail from the contact's action menu would be much faster and more convenient, when adressing single contacts.

#### Your Environment
* SuiteCRM Version used: 7.10.4
* Browser name and version: Chrome Version 67.0.3396.79 (64-bit)
* Environment name and version: MySQL, PHP7, Bitnami-Stack
* Operating System and version: CentOS 7

**Comment by Dillon-Brown** [comment]
@mbennoer Have you tried on 7.10.6? so far I haven't been able to replicate this.

**Comment by mbennoer** [comment]
@Dillon-Brown Okay, thank you for your feedback. I'll ask our admin to update to 7.10.6 and take a look at it again.

**Comment by mbennoer** [comment]
Good Morning, @Dillon-Brown, just tested in 7.10.6. and cross-checked with another browser (Firefox 60.0.2), menu item is still missing in our installation, weird.

**Comment by gremlinuk** [comment]
Any progress on this? I'm seeing the same thing on 7.10.11 - the option shows on bulk and also on targets, but not on contacts or leads.

**Comment by gremlinuk** [comment]
Yes it is - in fact its been working fine until recently, plus the functionality works for other areas - looks like one of the recent updates have broken it for me.

An interesting thing i've also spotted is that i don't see a single ticks now anywhere either (opted in but not confirmed) either in detail or list view - only when its confirmed when 2 ticks appear.

**Comment by likhobory** [comment]
Try to do 'Quick Repair and Rebuild'.

**Comment by gremlinuk** [comment]
Tried that too :)

**Comment by Mausino** [comment]
Same problem in my case also. Didn't test on fresh installation.  I have version 7.10.11
....
![2018-12-14_1614](https://user-images.githubusercontent.com/5773777/50011222-cd1d0b00-ffbb-11e8-9f16-39643ae54de2.png)
....
![2018-12-14_1616](https://user-images.githubusercontent.com/5773777/50011227-d1492880-ffbb-11e8-8107-370e8216d6e6.png)
....
![2018-12-14_1616_001](https://user-images.githubusercontent.com/5773777/50011231-d4441900-ffbb-11e8-9b29-4071271985a3.png)

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
