### ISSUE TITLE
AOR Reports entering a date parameter with Period operator type results in empty page and php fatal error.

### ISSUE THREAD

**Issue by maclordaj** [salesagility/SuiteCRM#6036]
#### Issue

While viewing any AOR Reports, an empty page will result when entering Date as parameter and updating.
Other parameter types such as Field and Date may not work correctly.
After checking logs and some debugging, what happens is that a PHP fatal error occurs because the period value is being removed by code introduced in the latest changes to aor_utils.php file. 
#### Expected Behavior

When choosing a date period parameter, results should appear filtered by the selected criteria.
#### Actual Behavior

After pressing update an empty content page will result.
PHP Error logs will show there was a fatal error:
`PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /bitnami/suitecrm/modules/AOR_Reports/AOR_Report.php:1803
#### Possible Fix

The issue actually begins in modules/AOR_Reports/aor_utils.php: 106
The parameter value is sent to a function called fixUpFormatting which does not seem to expect values such as 'today','yesterday', etc... for date/datetime fields.
Using the value directly from the $_REQUEST object as it was before "fixes" the issue for this type of parameter, but I guess the use of the fixUpFormatting function is there for some other reasons.
#### Steps to Reproduce

1. Create a new report with any module (e.g. Cases), with any fields (e.g. Account Name) and with at least one condition checked as a parameter using a date field (e.g. Date created). Save the report.
2. In the report view, choose any operator, Period type and any value for the date field parameter.
3. Press update.
4. Observe empty page instead of results.

#### Context

Reports using date periods as parameters will initially load, but won't work anytime the Update button is pressed. I also believe this affects other types of date parameters such as Date and Field. If the type is chosen as Value it seems to work correctly.
#### Your Environment

* I was able to reproduce this bug using the current demo site with SuiteCRM 7.10.6
* SuiteCRM Version used: 7.10.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari Version 11.0.2 (13604.4.7.1.3)

**Comment by Glen206** [comment]
This is still present in 7.10.7

**Comment by jpjanze** [comment]
This is still present in 7.10.10

Any progress on this? temporary solution? advice?

**Comment by Mausino** [comment]
@jack7anderson7 if is it duplicate... of which issue ticket ?

**Comment by jack7anderson7** [comment]
Hi there @Mausino, 

Sorry my mistake thought I came across another issue similar but it appears I can't find one to match.

**Comment by aureh12** [comment]
This is still present in 7.11.0
