### ISSUE TITLE
AOR Reports - Issue with related records in reports

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#6037]
#### Issue
Report will return no records if either the report fields or conditions have a record from a related module.
E.g. If the report module is Contacts and the report field is Contacts:Email Address the report will return no records.
![image](https://user-images.githubusercontent.com/32680276/41463799-b7786738-708f-11e8-9743-68d2fd6ac029.png)

#### Expected Behavior
The report should return first name, last name and contacts email address.

#### Actual Behavior
Report return no records.
SQL Error: Unknown column 'contacts.email_address' in 'field list'.

#### Possible Fix

Issue is when saving conditions and fields in AOR_Condition.php and AOR_Field.php
Issue may be when module_path is encoded.
$postField[$i] = base64_encode(serialize(explode(":", $postField[$i])));

In previous versions: $postField[$i] = 'email_address'
In 7.10.6:  $postField[$i] = ':email_address'
Colon appear to be added twice.

#### Steps to Reproduce

1. Create new AOR Report
2. Make the report module Contacts
3. Choose a related record to contacts like email
4. Run Report

#### Context

Medium priority. 

#### Your Environment

* SuiteCRM Version used: 7.10.6
* Browser name and version: Chromium Version 66.0
* Environment name and version: MySql - PHP 7.1
* Operating System and version: Ubuntu 16.04

**Comment by Pawes** [comment]
Confirmed on demo site.
I can't even show the first name of the contacts of each account.

I really think this should be a high priority as people might have set up reports to indicate to them whether or not they need to follow up on something (a bug, a lead, etc.) and the fact that reports just comes back empty will lead them to think that they are all good. Also since there is no error message users will only notice it if they run a check separate from the reports module.

**Comment by Pawes** [comment]
After some additional digging I got it working.
There are two ways of adding a related module, in the Reports module. One that returns nothing and results in the unknown column error and one that actually works:

The first  way of adding a related bean (**DOESN'T WORK!**):

You EXPAND the Accounts bean, push the Contacts bean inside it and then choose the desired fields from the Fields list.
![not_working](https://user-images.githubusercontent.com/15903729/42087053-55a85700-7b95-11e8-97af-1a606d6c980c.PNG)


The second way (**WORKS**):
You find and push the related bean at the same level as your "primary" bean and then choose the fields from the list.
![working](https://user-images.githubusercontent.com/15903729/42086975-0cc9a46c-7b95-11e8-9225-1a9814223e86.PNG)

I don't know why there are two ways, but as long as they are there they both ought to be working. However, until it is fixed (or removed) just use the second option. 
Also AFAIK, there is no way to tell which method has been used once the related bean's field is added to the report.

**Comment by pgorod** [comment]
@Dillon-Brown I just ran into this issue in the Forums, and I tried it in my 7.10.7 and it is in fact, broken :-(

The trick that @Pawes explains above didn't work for me, maybe I am not doing it correctly, or maybe I should try starting a whole new Report instead of editing one.

I suspect this commit, because it touches the code specifying the table and the field in the condition: https://github.com/salesagility/SuiteCRM/commit/1dd78bc7d08f3224ae0492c35c5d7a8bde7a0504#diff-8e013a786969a1b4bcb7b18a3cfb35db

The error I'm getting for a Report joining Opportunities and Contacts (and comparing their account names, which generates another join) is this:

```
Wed Jul 25 16:25:20 2018 [9646][1][FATAL]  Query Failed: SELECT `opportunities`.name AS 'Opportunity_Name0', `opportunities`.description AS 'Description1', `opportunities:contacts`.first_name AS 'First_Name2', `opportunities:contacts`.last_name AS 'Last_Name3', `opportunities`.id AS 'opportunities_id', `opportunities:contacts`.id AS 'opportunities:contacts_id', `accounts`.id AS 'accounts_id' FROM `opportunities` LEFT JOIN opportunities_contacts `opportunities|opportunities:contacts` ON `opportunities`.id=`opportunities|opportunities:contacts`.opportunity_id AND `opportunities|opportunities:contacts`.deleted=0

LEFT JOIN contacts `opportunities:contacts` ON `opportunities:contacts`.id=`opportunities|opportunities:contacts`.contact_id AND `opportunities:contacts`.deleted=0
LEFT JOIN accounts_contacts `opportunities|accounts` ON `opportunities`.id=`opportunities|accounts`.contact_id AND `opportunities|accounts`.deleted=0

LEFT JOIN accounts `accounts` ON `accounts`.id=`opportunities|accounts`.account_id AND `accounts`.deleted=0
 WHERE ( `accounts`.id = `accounts`.account_name ) AND  opportunities.deleted = 0  LIMIT 0,20: MySQL error 1054: Unknown column 'accounts.account_name' in 'where clause'
```
It should be `accounts.name` and not `accounts.account_name`...

**Comment by belchfireid** [comment]
We're having the same problem on 7.10.7, and the workaround above does not work. Any non-trivial report will not run, not just the examples here.

Here, I'm merely trying to get a count of contacts that were associated with each active campaign. Even if this isn't quite the relationship to use, I should see something other than an sqli error.  Ultimately, we're trying to generate a report of contacts for follow ups. This is pretty fundamental to a sales team, and I'd rate it as a high priority bug.
```
Sun Aug  5 13:05:35 2018 [5027][2ffab69f-3637-e0c1-bac6-51256403d2c0][FATAL] Mysqli_query failed.
Sun Aug  5 13:05:35 2018 [5027][2ffab69f-3637-e0c1-bac6-51256403d2c0][FATAL]  Query Failed: SELECT `campaigns`.name AS 'Name0', COUNT(`campaigns:contacts`.id) AS 'ID1', `campaigns`.id AS 'campaigns_id',  AS 'campaigns:contacts_id' FROM `campaigns`  LEFT JOIN prospect_list_campaigns `campaigns:contacts`_plc ON `campaigns:contacts`_plc.campaign_id = `campaigns`.id
 LEFT JOIN prospect_lists_prospects `campaigns:contacts`_plp ON `campaigns:contacts`_plp.prospect_list_id = `campaigns:contacts`_plc.prospect_list_id AND `campaigns:contacts`_plp.related_type = 'Contacts'
 LEFT JOIN contacts `campaigns:contacts` ON `campaigns:contacts`.id = `campaigns:contacts`_plp.related_id AND `campaigns:contacts`.deleted=0
 WHERE ( `campaigns`.status = 'Active' ) AND  campaigns.deleted = 0  LIMIT 0,50: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS 'campaigns:contacts_id' FROM `campaigns`  LEFT JOIN prospect_list_campaigns `' at line 1
```

**Comment by belchfireid** [comment]
Update: maybe this will help debug. The problem appears to be sticky. 
1. Create a report with one condition and one field - works
2. Add a field - quits working
3. Delete the field that was just added, presumably returning to condition 1. - report doesn't run.  In my latest test case, no error shows up in the log.

**Comment by belchfireid** [comment]
Another example
`MySQL error 1054: Unknown column 'campaign_log.last_name' in 'field list'`

the query should be something like: 
`campaign_log:targeted_user.last_name`

The intermediate field gets dropped when constructing the query.  I'm not sure this precisely the correct query.

**Comment by jack7anderson7** [comment]
Hi there @belchfireid,

I am unable to replicate this on my local or on the live demo, can you inform me if this is still an issue for you?

**Comment by belchfireid** [comment]
Hi Jack,
I’m jammed this week, but can probably retest next week.

I’ve been able to work around it for most of the reports I need by restricting the Fields:Module to the Report Module.  Any reports that are more complex than that we have been able to work around by exporting to Excel or just gave up.

Note that I’m using 7.10.7.

Steve
--
Steve Johnson
Extensible Labs
steve@extensiblelabs.com   208.991.2821
7154 W. State St., Ste 254, Boise, Idaho  83714

**Comment by lazka** [comment]
I've opened a PR for this: #6745
