### ISSUE TITLE
Labels edition lost when patching to 7.10.x

### ISSUE THREAD

**Issue by jperez-murcia** [salesagility/SuiteCRM#6051]
Functional system running a 7.9.x SuiteCRM. Applied upgrade "SUITECRM-7.9.X-TO-7.10.6".

#### Issue
On "Module Builder", labels editing functionality is now lost; just anything appear on screen when selected, except for the "language" dropdown.

#### Expected Behavior
The "labels" editing screen should appear

#### Actual Behavior
Nothing appear

#### Possible Fix
Unknown

#### Your Environment
* SuiteCRM Version used: 7.9.7
* Browser name and version: Firefox 60.0.2
* Environment name and version: Apache 2.4.6, PHP 7.1.18, MySQL 5.7.18
* Operating System and version: CentOS 7

**Comment by novakda** [comment]
I'm having the same problem.  On any custom created object in Module Builder, the Labels section is always blank.  
![2018-10-16_23-02-27](https://user-images.githubusercontent.com/1312650/47065480-f37b2180-d197-11e8-8564-f9744edf4313.png)

Note the dropdown that usually displays "Frequently-used fields" and "All fields" has no options here.  No labels are displayed.  When deployed, the same object does show everything expected.

The same object as viewed in Studio:
![studio2018-10-16_23-06-35](https://user-images.githubusercontent.com/1312650/47065546-3b9a4400-d198-11e8-8005-ad31841bc72a.png)

This is a fresh install of v7.10.9 using Nginx on Ubuntu LTS 16 on Virtualbox.  

The only change I've made to source is the hotfix described here: https://github.com/salesagility/SuiteCRM/pull/6324/files 

Diagnostic file:
[801798b6-bae2-2701-4018-5bc6d1c9e75b.zip](https://github.com/salesagility/SuiteCRM/files/2486020/801798b6-bae2-2701-4018-5bc6d1c9e75b.zip)

**Comment by Dillon-Brown** [comment]
Seems to be related to this commit in 7.10.3: https://github.com/salesagility/SuiteCRM/pull/5519/commits/09a53a816925e4eb937e093b7f1bed683afc99c1

**Comment by JanSiero** [comment]
The dropdown for "frequently used labels" / "all labels" is only populated in Studio, not in Module Builder, this has always been the case. It therefore has no relation to the missing labels.

My fix for the missing labels #8570 also makes sure that this dropdown is only shown when it contains values.
