### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function iconv() - CREATE TARGET, LIST,CAMPAING ...

### ISSUE THREAD

**Issue by maverikmaverik** [salesagility/SuiteCRM#6059]
#### Issue

This error occurs in different options, it is an error of the Lucene module.

Error when creating a new **targets lis**t and also when **creating a new campaign**, I suppose that it will give an error in all the options that load this module.

#### Expected Behavior

It is produced this error:

**Fatal error:** Uncaught Error: Call to undefined function iconv() in /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/Lib/Zend/Search/Lucene/Field.php:222 Stack trace: #0 /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/Lib/Zend/Search/Lucene/Index/SegmentWriter/DocumentWriter.php(131): Zend_Search_Lucene_Field->getUtf8Value() #1 /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/Lib/Zend/Search/Lucene/Index/Writer.php(244): Zend_Search_Lucene_Index_SegmentWriter_DocumentWriter->addDocument(Object(Zend_Search_Lucene_Document)) #2 /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/Lib/Zend/Search/Lucene.php(1410): Zend_Search_Lucene_Index_Writer->addDocument(Object(Zend_Search_Lucene_Document)) #3 /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/AOD_Index.php(310): Zend_Search_Lucene->addDocument(Object(Zend_Search_Lucene_Document)) #4 /home/admin/domains/grupo-omnimedia.com/public in /home/admin/domains/grupo-omnimedia.com/public_html/suitecrm/modules/AOD_Index/Lib/Zend/Search/Lucene/Field.php on line 222

#### Steps to Reproduce

1. create a new TARGET or TARGETS LIST
2. or too create a new CAMPAING
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all browser
* Environment name and version (e.g. MySQL, PHP 7): PHP7 mysql 
* Operating System and version (e.g Ubuntu 16.04): Centos
![screenshot_1](https://user-images.githubusercontent.com/40229134/41667413-39659790-74ad-11e8-8dcf-d3e2c2e6f732.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40229134/41667414-39885a14-74ad-11e8-8ea0-574105813ce6.jpg)
![screenshot_3](https://user-images.githubusercontent.com/40229134/41667415-39d6c47e-74ad-11e8-961a-8df536605bb0.jpg)
![screenshot_4](https://user-images.githubusercontent.com/40229134/41667416-3a0713b8-74ad-11e8-9e0e-b6f8d844e1e3.jpg)
![screenshot_5](https://user-images.githubusercontent.com/40229134/41667418-3a451e92-74ad-11e8-9ac4-701b872cb250.jpg)

**Comment by maverikmaverik** [comment]
The Campaigns option has many errors and it is impossible to create a new complete NEWLETTER CAMPAIGN.

**Comment by Dillon-Brown** [comment]
Hi @maverikmaverik, icov is a PHP extension. You just need to uncomment it in your php.ini.

**Comment by maverikmaverik** [comment]
I have php7 and the php iconv extension is installed so I miss that error, it has to be for another reason.

**Comment by pgorod** [comment]
Cam you please go in `Admin / Diagnostic tool` and run `phpinfo()` from there?

This will let you examine the effective modules being loaded, because sometimes things are configured in one php.ini but it is not the correct one, and this helps to determine exactly what is loaded.

**Comment by maverikmaverik** [comment]
All ok
![screenshot_2](https://user-images.githubusercontent.com/40229134/41722380-aba476d0-7568-11e8-9464-0a05bbd9fc36.jpg)

**Comment by pgorod** [comment]
You have to click the "Download diagnostic file" at the bottom, download it, unzip it, open phpinfo output in a web browser, examine your effective loaded modules.

**Comment by maverikmaverik** [comment]
php7 iconv  is by default, 

You don't have to install the extension to part because it is already included in php7

**Comment by pgorod** [comment]
I know that, but you say you're getting `Fatal error: Uncaught Error: Call to undefined function iconv()` which seems to suggest otherwise. You're not the only person on the Internet with this incoherence on PHP 7.0. 

I'm trying to help you but if you feel you have a better way of diagnosing the problem, go ahead, explore it, and then tell us the results.

**Comment by mattlorimer** [comment]
Either your iconv is not enable and/or not installed or there is something wrong with your setup, 
but if your are not using the AOD search functionality, just go to Admin->AOD Settings and disable AOD

**Comment by maverikmaverik** [comment]
Disabled AOD
![screenshot_9](https://user-images.githubusercontent.com/40229134/41768781-8797ed8a-760d-11e8-8335-a94f7ec53416.jpg)

At the moment no error.
