### ISSUE TITLE
Error 500 colourSelector.php

### ISSUE THREAD

**Issue by maverikmaverik** [salesagility/SuiteCRM#6060]
#### Issue

[**TOPIC FORUM #68081**](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19560-error-500-colourselector-php#68081)

I have the latest version 7.10.7 installed and allo permissions are correct:

sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php

All pages gives error 500 (Failed to load resource: the server responded with a status of 500 Internal Server Error) when loading the file colorSelector.php in the line:

  <link rel = "stylesheet" type = "text / css" href = "themes / SuiteP / css / colorSelector.php">

It does not give error to open, because it does not get to load it, I have even deleted the code and left it blank and keeps giving error.

Tthe tag HTMLt uses is: <link rel = "stylesheet" type = "text / css" ... to open a stylesheet when open src is a php file, could be the problem??
![screenshot_1](https://user-images.githubusercontent.com/40229134/41668062-cbcc76f2-74ae-11e8-8963-2f9d9fc4c687.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40229134/41668063-cbec9414-74ae-11e8-9b86-ded07aac2853.jpg)

I have searched the forum and github but I can not find any solution.

#### Steps to Reproduce

1. Any page that tries to open the file colourselector.php gives error 500 for example login
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): ALL
* Environment name and version (e.g. MySQL, PHP 7): PHP7 mysql
* Operating System and version (e.g Ubuntu 16.04):Centos

**Comment by pgorod** [comment]
@maverikmaverik please don't double-post, here and on the Forums... it's confusing enough as it is...

And this one is clearly for the Forums. You should only post on GitHub when you are sure it's a bug for the developers to fix. All these issues that can be just on your installation should be dealt with outside Github. Please close this issue now (and others of the same nature).
