### ISSUE TITLE
Why phpinfo as a language string?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6061]
#### Issue

phpinfo - Outputs information about PHP's configuration. But whi is it in a language string to be translated?

`'LBL_DIAGNOSTIC_PHPINFO' => 'phpinfo()',`
https://github.com/salesagility/SuiteCRM/blob/81a0321fcbbb9a8275cea9556f582172599e5355/modules/Administration/language/en_us.lang.php#L223

#### Expected Behavior

Shouldn't be available to translators!

Else it should be rewritten
Note there is a related (proper) string: 
`'LBL_DIAGNOSTIC_GETPHPINFO' => 'Getting phpinfo()',`

**Comment by pgorod** [comment]
It shows on this screen (Admin / Diagnostic tool):

![image](https://user-images.githubusercontent.com/15945027/41673774-d8200304-74b5-11e8-9cf5-1434d52c3d38.png)

I guess it's a string just for consistency with the other options...

I guess it could be expanded to something like `Output from phpinfo()` if that sounds better.
