### ISSUE TITLE
Match records

### ISSUE THREAD

**Issue by nzi200779** [salesagility/SuiteCRM#6073]
Is is possible to have an automatic matching of records captured in different modules. It would be similar to duplicate management but not exactly the same,

I for example want to match a record of a client opportunity that is Selling shares, to a similar one that wants to Buy shares. to clarify further see example below

Opportunity 1: A client wants to sell shares in the organisation (this already exists in the system)
When a different client captures Opportunity 2 (looking to but shares in any organisation) on Save the system searches based on some search configuration and presents results as a normal search would.

Option2: 
Create a search filter for a Opportunities Module
Automatically(schedule somehow) to have the filter run after Save of every new Opportunity record.

Is that possible? If so how do I go about doing it. Please keep in mind Im not very technical.

**Comment by PedroErnst** [comment]
Hello @nzi200779 

Welcome to Github. This is a place for developers to meet and "discover, share, and build better software" (From the description of the page.)

What you are looking for is most likely the [forums](https://suitecrm.com/suitecrm/forum/index), where you will find help in achieving what you want.

**Comment by nzi200779** [comment]
My apologies.

Thank you
