### ISSUE TITLE
SuiteCRM 7.10.3 - Can't create new user

### ISSUE THREAD

**Issue by gcommit** [salesagility/SuiteCRM#6075]
#### Issue
Users are not able to create new user, since there is not "create" button or something similiar. Only cloning the admin user and rename it is creating new users. 

#### Expected Behavior
Users should be able to create new users without using some "hacks" via cloning or special URL paths

#### Actual Behavior
Users are not able to create new user, since there is not "create" button or something similiar.

#### Possible Fix
Bring the create button back

#### Steps to Reproduce
1. Create a SuiteCRM instance
2. Login
3. Go to "Admin" 
4. Go to User Management
5. try to create a user

#### Context
We can't use the SuiteCRM in that way, since we can't create new users.

#### Your Environment
* SuiteCRM Version used: 7.10.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 11.1, Chrome 67.0.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by PedroErnst** [comment]
Hi @gcommit 

You mean this button?

![image](https://user-images.githubusercontent.com/34056696/41841473-449975bc-7860-11e8-811e-861eec9aee54.png)

Either this is fixed in the current version 7.10.7, or maybe this issue is related to some configuration on your side, or something else?

**Comment by gcommit** [comment]
Yes, i don't see any of these Buttons in 7.10.3. I will check if it is fixed in the Update

**Comment by gcommit** [comment]
this issue is fixed. Thank you !
