### ISSUE TITLE
Currency issue in Listview

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#609]
Hi

In Listview instead of symbol of Euro € it show us the "-99" and if i want inline edit it in Listview, it first shows you the normal dropdow, where you can choose the currency, but after save icon it shows you there empty field (space)

Miky

**Comment by samus-aran** [comment]
Can't replicate the -99 currency issue.  How did you add the Euro icon via the Admin Area > Locale or Currencies?  Is a screenshot possible to show the dropdown field on the inline edit via ListView?

**Comment by Mausino** [comment]
I hope, that help you this video http://screencast.com/t/oqXKxwaH

**Comment by mattlorimer** [comment]
List view shows the 'key' instead of the 'value' for the  currency dropdown

**Comment by salesagility-davidthomson** [comment]
fix proposed here
https://github.com/salesagility/SuiteCRM/pull/6079
