### ISSUE TITLE
SuiteCRM 7.8.20 Print Case list shows nothing but number.

### ISSUE THREAD

**Issue by mbates14** [salesagility/SuiteCRM#6101]
When showing/viewing all cases, if you try to print only the ID is shown.

Glad the URL bug is fixed, but this bug remains. SuiteR we use. Suite7 is a bit dated so we dont use it, and SuiteP is an ugly hot mess so we don't use that one either. 

Clicking view all cases and hitting Ctrl-P to print produces the bug. Only shows the case numbers. nothing else!

**Comment by mbates14** [comment]
To add to this, if I go into my print dialog and turn margins "off" from default, everything shows up. 

So something with the margins in the CSS file I guess?

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
