### ISSUE TITLE
Is not posible to update a case with multiple lines of text using HTML editor

### ISSUE THREAD

**Issue by sanchezfauste** [salesagility/SuiteCRM#6107]
#### Issue

If you add a case update using HTML editor only the first line will be saved.

This sometimes also happens when the customer replies the case by email.

#### Expected Behavior

All the HTML code must be stored in the case update.

#### Actual Behavior

Only the first line is stored.

#### Possible Fix

This line of code is removing the lines below first line:
https://github.com/salesagility/SuiteCRM/blob/207f5f65d260b842b8883e591783608ec758b28d/modules/AOP_Case_Updates/AOP_Case_Updates.php#L153

#### Steps to Reproduce

1. Edit existing case.
2. Add some text on 'Updates - Text'. IMPORTANT: add more than one line of content.
![pre](https://user-images.githubusercontent.com/10921800/42079283-8a96ec08-7b7f-11e8-9769-2dd24e018574.png)
3. Save the changes.
4. See that only the first line is stored.
![post](https://user-images.githubusercontent.com/10921800/42079290-8d69638e-7b7f-11e8-8fbb-729ba051d7ca.png)

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 67.0.3396.87 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.27 and mysql-server 5.5
* Operating System and version (e.g Ubuntu 16.04): Debian 9

**Comment by e-reeley** [comment]
Hi @sanchezfauste ,

Thanks for this detailed report! 

I have made a PR which I believe fixes this issue.

Thanks again,
Ellis.

**Comment by sanchezfauste** [comment]
Thanks @e-reeley , your PR solves the issue.
