### ISSUE TITLE
Google Maps Geocoding API Key NOT added to the call when Geocoding Addresses

### ISSUE THREAD

**Issue by markbond1007** [salesagility/SuiteCRM#6108]
#### Issue

More of an issue than a bug, caused by Googles recent update. All the JS files appear to have the key added, but the PHP call to do the geocoding doesnt.

#### Expected Behavior

When running the Geocode process from the Admin Interface, all addresses for relevant modules should be provided with Geocoding data

#### Actual Behavior

On a brand new IP I ran geocode (with a valid Google Key), not all data was geocoded. After this using the quick Test Geocode on an address tells me I am over quota (on an account that has billing enabled etc. at google).

#### Possible Fix

To fix you need to go to modules/jjwg_Maps/jjwg_Maps.php go to line 933 (ish) in the function getGoogleMapsGeocode
replace:
`if (!empty($this->settings['geocoding_api_secret'])) { $hash = md5($address.$this->settings['geocoding_api_secret']); $request_url .= '&hash='.urlencode($hash); }`

with:

`$request_url.="&key=".urlencode($this->settings['google_maps_api_key']);`

#### Steps to Reproduce

1.Install new version of SuiteCRM on a new IP
2.Get an API key and set-up billing with google (for maps api)
3.using the test/sample data, go to the admin interface and geocode the addresses
4.Not all addresses will get coded
5. Use the Quick test method in the admin interface to receive a message regarding being over quota.

#### Context

Medium Priority, using this for a client, however have fixed this locally.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7.0-fpm
* Operating System and version (e.g Ubuntu 16.04): Debian stretch

**Comment by horus68** [comment]
@markbond1007 you need to submit your PR to SuiteCRm git (branch hotfix
https://github.com/salesagility/SuiteCRM/tree/hotfix

**Comment by markbond1007** [comment]
@horus68 well I hav added the pull request, although the commit instructions specifically say if the problem is in both hotfix and hotfix-7.8 to add to hotfix-7.8 so maybe the instructions need updating as well.

**Comment by horus68** [comment]
You are right, Its ok to make the pull request against hotfix-7.8
