### ISSUE TITLE
Mass Update for description field type

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#612]
It would be a nice feature to extend the mass update functionality to other fields in particular the description field (type: text/text area)

**Comment by jobvector** [comment]
and the checkbox fields

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mass Update for description field type](https://trello.com/c/8GZGKg8d/141-mass-update-for-description-field-type)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
