### ISSUE TITLE
New Calendar Meeting - Search to add participants no longer works after 7.8.20 upgrade.

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#6121]
When adding a new calendar meeting, the search to add participants no longer works after a 7.8.20 upgrade. Tried by clicking 'Search' button and by pressing 'Enter' on keyboard. 

#### Possible Fix
Resolve JS error messages observed in browser console. Related to jsclass_async.js and sugar_grp1.js. Issue is observed after we upgrading to SuiteCRM 7.8.20, so could be related to the upgrade. 

See attaches screenshots. 
![browsererrors](https://user-images.githubusercontent.com/18371928/42268153-1ad6d52c-7f7b-11e8-81b5-6d7eb008c008.png)
![newmeetingmodal](https://user-images.githubusercontent.com/18371928/42268154-1af42cc6-7f7b-11e8-9f24-8e36574e323a.png)

#### Steps to Reproduce
1. Go to calendar. 
2. Click into calendar to add a new meeting. 
3. Search for name to add to meeting in new-meeting modal pop-up. 

#### Environment
* SuiteCRM v. 7.8.20
* Theme: Suite 7 
* Browser name and versionL Safari 11.1 and on MS Edge latest. 
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.30, MySQL 5.6.40
* Operating System and version (e.g Ubuntu 16.04): CentOS Linux 7.5

**Comment by evgu** [comment]
@salesagility, could someone triage this please? It's been 14 days since sibmission. Sincere thanks.

**Comment by Dillon-Brown** [comment]
Hi @evgu, I wasn't able to replicate this upgrade from 7.8.19 to 7.8.20. Have you tried running Rebuild Minified JS Files and Rebuild JS Grouping Files?

**Comment by evgu** [comment]
Hi @Dillon-Brown, I ran Rebuild Minified JS Files and Rebuild JS Grouping Files, but issue is still there. See browser console errors attached. 
![screen shot 2018-07-19 at 14 37 39](https://user-images.githubusercontent.com/18371928/42945960-ab032744-8b61-11e8-871e-071d0122e08c.png)

**Comment by evgu** [comment]
@Dillon-Brown, could you please suggest next steps for locating the issue?

**Comment by evgu** [comment]
We have now upgraded to 7.10.x and no longer have this problem. As noone else replicated this issue on 7.8.20, I would suggest to close this ticket.
