### ISSUE TITLE
Cannot access API after clean Install of crm v7.8.2 on MAMP

### ISSUE THREAD

**Issue by prasadh13** [salesagility/SuiteCRM#6123]
#### Issue
The forum website is down so I am reporting it here. 
I did a clean install on MAMP. I am able to reach port 80 from the browser. However, the JSON API is not reachable. I ran the swagger.json with Postman to test the connection and it returned a 404 error. Upon inspecting and scanning the resources and the documentation, I figured out there is no /lib/API/ folder path. I am able to reach the swagger file with the absolute file path on the server.

#### Expected Behavior
Should return the swagger documentation
#### Actual Behavior
The requested URL /site2/api/v8/swagger.json was not found on this server.

#### Steps to Reproduce
Do a clean install and try connecting to the JSON API

#### Context
I am trying to connect using the JSON API.

#### Your Environment
* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 67.0.3396.99
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MySQL
* Operating System and version (e.g Ubuntu 16.04): MacOS Sierra v10.12.6

**Comment by pgorod** [comment]
There is no such thing as v8 API on SuiteCRM v 7.8.2.

You need to use the v4 API, or switch to SuiteCRM 7.10.x.

**Comment by prasadh13** [comment]
Yes. I figured that out. Thanks for closing the issue and the reply!
