### ISSUE TITLE
7.8.20 error 500 after upgrade 

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#6124]
#### Issue

7.8.20 error 500 after upgrade 
#### Expected Behavior

no error accessing the crm
#### Actual Behavior

Error 500 when accessing suitecrm after 7.8.15 to 7.8.20 upgrade
#### Possible Fix

upgrade introducing an error in .htaccess , this is an exctract of resulting htaccess, as you can see the opening FilesMatch in on the sameline than END SUGARCRM RESTRICTIONS. and causing error 500

```
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]
   RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&module=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&module=$1&lang=$2 [L,QSA]
</IfModule>
# END SUGARCRM RESTRICTIONS<FilesMatch "\.(jpg|png|gif|js|css|ico)$">
        <IfModule mod_headers.c>
                Header set ETag ""
                Header set Cache-Control "max-age=2592000"
                Header set Expires "01 Jan 2112 00:00:00 GMT"
        </IfModule>
</FilesMatch>
```
also these 2 lines should be deleted based on this issue: https://github.com/salesagility/SuiteCRM/issues/5255

   RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&module=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&module=$1&lang=$2 [L,QSA]

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): ubuntu 16.04

**Comment by pgorod** [comment]
I believe this is solved now, right? If so, please close the issue. Thanks!
