### ISSUE TITLE
Non breaking space in language string value

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6125]
#### Issue

Is there a reason for those spaces in some language string values? 

modules/Studio/language/en_us.lang.php
`'LBL_DELETE_MODULE' => 'Remove&nbsp;module<br />from&nbsp;filter',`
https://github.com/salesagility/SuiteCRM/blob/481cfd2b3dded08c0d9287294b70468934350d4d/modules/Studio/language/en_us.lang.php#L117

Also note the `Ctrl-click&nbsp;to&nbsp;select` ) in:

\include\language\en_us.lang.php
`'LBL_SEARCH_HELP_TEXT' => '<p><br /><strong>Multiselect controls</strong></p><ul><li>Click on the values to select an attribute.</li><li>Ctrl-click&nbsp;to&nbsp;select multiple. Mac users use CMD-click.</li><li>To select all values between two attributes,&nbsp; click first value&nbsp;and then shift-click last value.</li></ul><p><strong>Advanced Search & Layout Options</strong><br><br>Using the <b>Saved Search & Layout</b> option, you can save a set of search parameters and/or a custom List View layout in order to quickly obtain the desired search results in the future. You can save an unlimited number of custom searches and layouts. All saved searches appear by name in the Saved Searches list, with the last loaded saved search appearing at the top of the list.<br><br>To customize the List View layout, use the Hide Columns and Display Columns boxes to select which fields to display in the search results. For example, you can view or hide details such as the record name, and assigned user, and assigned team in the search results. To add a column to List View, select the field from the Hide Columns list and use the left arrow to move it to the Display Columns list. To remove a column from List View, select it from the Display Columns list and use the right arrow to move it to the Hide Columns list.<br><br>If you save layout settings, you will be able to load them at any time to view the search results in the custom layout.<br><br>To save and update a search and/or layout:<ol><li>Enter a name for the search results in the <b>Save this search as</b> field and click <b>Save</b>.The name now displays in the Saved Searches list adjacent to the <b>Clear</b> button.</li><li>To view a saved search, select it from the Saved Searches list. The search results are displayed in the List View.</li><li>To update the properties of a saved search, select the saved search from the list, enter the new search criteria and/or layout options in the Advanced Search area, and click <b>Update</b> next to <b>Modify Current Search</b>.</li><li>To delete a saved search, select it in the Saved Searches list, click <b>Delete</b> next to <b>Modify Current Search</b>, and then click <b>OK</b> to confirm the deletion.</li></ol><p><strong>Tips</strong><br><br>By using the % as a wildcard operator you can make your search more broad. For example instead of just searching for results that equal "Apples" you could change your search to "Apples%" which would match all results that start with the word Apples but could contain other characters as well.</p>',`
https://github.com/salesagility/SuiteCRM/blob/hotfix/include/language/en_us.lang.php#L1875

#### Possible Fix

If not required, they should be removed. If required they should have a notice so translators do not remove them!

#### Your Environment

* SuiteCRM Version used: Latest Hotfix from Git

**Comment by horus68** [comment]
@Dillon-Brown no reply on this?

Why the need for non-breaking spaces in a language string? What will happen if someone do not use spaces code but actual spaces?
Also not that a nearby string uses an escaped single quote and that should not happen in language values.

```
    'LBL_RENAME_TAB_WELCOME' => 'Click on any tab\'s Display Value in the table below to rename the tab.',
    'LBL_DELETE_MODULE' => 'Remove&nbsp;module<br />from&nbsp;filter',
```

**Comment by Dillon-Brown** [comment]
@horus68 If they aren't required we should definitely remove them (I don't see why they would be). We'll need to find out where each of these strings appears on the page and test first though.
