### ISSUE TITLE
If field value contains single quote, on each save CRM will treat this field as a changed

### ISSUE THREAD

**Issue by re8260** [salesagility/SuiteCRM#6126]
#### Issue
If field value contains single quote, on each save CRM will treat this field as a changed even if the value was not changed.

#### Expected Behavior
If value was not changed, nothing should happen.

#### Actual Behavior
1. Run all Workflows with condition Any Change on this field.
1. Add new line to bean change log, same value before and after
![image](https://user-images.githubusercontent.com/18328936/42324296-8107921e-806b-11e8-8cc8-72d93390700f.png)
![image](https://user-images.githubusercontent.com/18328936/42324326-94ec0ec2-806b-11e8-8e21-5afde0077abf.png)

#### Possible Fix
The problem happen because the prev value from $bean->fetched_row['name'] in encoded as html and actual value is not encoded so they will nevet be same : `R'oman` vs `R&#039;oman`
![image](https://user-images.githubusercontent.com/18328936/42323745-dddb149a-8069-11e8-8c4f-657f9dd50f62.png)

#### Steps to Reproduce

1. Create Account with  single quote in name
2. Create WorkFlow with condition AnyChange on Account name field
3. Open and save bean with chnages
4. in result, new line will be added to change-log and Workflow will be trigger

#### Context
[lint to test Workflow 89c58469-90fc-c629-a607-5b3e14312651](https://demo.suiteondemand.com/index.php?module=AOW_WorkFlow&action=DetailView&record=89c58469-90fc-c629-a607-5b3e14312651)
[link to test account bean 3dedfaf4-8387-91ce-7113-5b3e0c9f6119](https://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DAccounts%26action%3DDetailView%26record%3D3dedfaf4-8387-91ce-7113-5b3e0c9f6119) 

high priority

#### Your Environment
Demo Envierment Version 7.10.7
https://demo.suiteondemand.com

**Comment by gunnicom** [comment]
Maybe this one:
https://github.com/salesagility/SuiteCRM/pull/1094

**Comment by re8260** [comment]
@gunnicom thsnks.
This fix change-log issue but not Workflow.

**Comment by gunnicom** [comment]
Ah, i missed the workflow part in your report. Ok, then these are two bugs.

**Comment by re8260** [comment]
@gunnicom 
MR that fix WF: https://github.com/salesagility/SuiteCRM/pull/6128

**Comment by re8260** [comment]
@Dillon-Brown this MR https://github.com/salesagility/SuiteCRM/pull/6128 relate to the same issue but it even more important and critical
