### ISSUE TITLE
Question: Accounts, removing an email address doesn't re-number all form fields

### ISSUE THREAD

**Issue by Jorilx** [salesagility/SuiteCRM#6129]
Using the Accounts module, when you have an account with multiple email addresses and you delete one, the `removeEmailAddress` function from `SugarEmailAddress.js` performs a "renumbering" of the form fields to ensure there are no gaps. This function touches every related field (`emailAddressN`, `emailAddressPrimaryFlagN`...) **except** `emailAddressIdN`, so that for example, given this initial situation:

```
Accounts0emailAddress0 = test1@email.com
Accounts0emailAddressId0 = [some UUID]
Accounts0emailAddress1 = test2@email.com
Accounts0emailAddressId1 = [another UUID]
```
if I delete the first email, upon submitting the form the server receives:
```
Accounts0emailAddress0 = test2@email.com
Accounts0emailAddressId1 = [another UUID]
```
I'd expect the "Id" field to be shifted to 0 too (`Accounts0emailAddressId0`), is this a bug or by design?

(Context: I'm writing an integration module between SuiteCRM and our ERP)

SuiteCRM 7.10.6

**Comment by cameronblaikie** [comment]
Hi @Jorilx 
To answer your question this is by design.
