### ISSUE TITLE
Calls Module -> Log Call creates indefinite number of reminders

### ISSUE THREAD

**Issue by LongLane** [salesagility/SuiteCRM#6130]
#### Issue

This applies to using the Calls module on a standalone basis, not by selecting 'Log Call' in a sub-panel.
When opening up the Calls module and then clicking 'Log Call', the form will be populated with an infinite number of default reminder, potentially eating up all the memory. This makes the stand-alone form useless. They only way to abort is to press cancel.
#### Expected Behavior

There should be only one reminder as with the sub-panel behaviour
#### Actual Behavior

An indefinite amount of reminders get added one after the other.

#### Steps to Reproduce

See above
1.
2.
3.
4.

#### Context

I wanted to add calls directly through the Calls module

low to medium as it works through the sub-panels
#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 11.1.1
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.2.5
* Operating System and version (e.g Ubuntu 16.04): Mac OS 10.13.5

**Comment by PedroErnst** [comment]
Thanks @LongLane for reporting this.

Can't seem to reproduce this on Chrome or Firefox. 
Maybe Safari related?

Is there any kind of useful error message showing in your JS console?

**Comment by LongLane** [comment]
Thanks Pedro. I went back into Safari now based on your note and tried to replicate the issue but was not successful. Apple in the meantime has released further updates which might have resolved the issue on the browser side.
