### ISSUE TITLE
Issue with DetailView of Email module on 7.10.7 xampp

### ISSUE THREAD

**Issue by jamiemurray** [salesagility/SuiteCRM#6131]
DetailView of email module shows the raw php code on Xampp on windows 

#### Issue
Since upgrading... detailview of an email is broken on xampp using windows (have not tested on linux)

#### Expected Behavior
When clicking into the detailview of an email... the email content should display

#### Actual Behavior
The raw php code is displayed.

#### Possible Fix
I fixed by reverting change made on modules/emails/vardefs.php with commit a60c60f1 and running quick repair

#### Steps to Reproduce
Upgrade on windows xampp to v 7.10.7 from previous version and go to detailview of any outbound or inbound email

#### Your Environment
Suite: 7.10.7 upgrade from 7.10.6
Windows 10 XAMPP PHP 7

**Comment by countrypark** [comment]
Hi, the fix mentioned above resolved the broken page issue, however it brought back issue [#4035](https://github.com/salesagility/SuiteCRM/issues/4035) - Upgrade on 7.9.4 Content in emails are same in body for all emails."

**Comment by samus-aran** [comment]
Hi everyone! @countrypark and @jamiemurray We have proposed a fix in this Pull Request. Are you able to test it and confirms that it works for you, that would be most helpful!

https://github.com/salesagility/SuiteCRM/pull/6194

**Comment by jamiemurray** [comment]
I shall test this morning and let you know

**Comment by jamiemurray** [comment]
[#6194](https://github.com/salesagility/SuiteCRM/pull/6194) resolves the issue.
