### ISSUE TITLE
Feat: Page break in HTML wysiwig fields

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#6136]
Page break icone /feature is not available in HTML wysiwig fields.
It is usefull for example when using this field to generate a quotation through "export as PDF template".
For example the description of your offer.
This button exist in template /PDF creation, but not in custom HTML wysiwig fields.

Today using Suitecrm 7.8.20 in order to have a proper presentation for a quote or another document you need to do the following 10 to 20 times :  
- Look where you want a page break
-Evaluate the number of enter needed  ( to make a title begin at the top of a page for ex)
-Input those enters
-Print as PDF 
-Visualise the output
-Add some enters if missing some...
- Print as PDF ...
-Do this for each page break needed..

Doing this defeates the idea of wysiwig if you need page breaks or pagination in general...

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by hubyhuby** [comment]
This is the view of an added HTML field in a quote. There is no line break : 
![image](https://user-images.githubusercontent.com/26340942/52525394-6f4e2c00-2ca9-11e9-8075-4d5b8597974a.png)

WHich is activated for example in Wysiwig from template module here:

![image](https://user-images.githubusercontent.com/26340942/52525423-cf44d280-2ca9-11e9-974e-f77d3c880a8d.png)

Suite crm : Version 7.8.20

**Comment by cameronblaikie** [comment]
Hi there,
I am unable to replicate this issue. Please let me know if this is still an issue you can replicate and we will investigate further. 
Thanks.

**Comment by hubyhuby** [comment]
Dear @cameronblaikie ,
So you have tried to set a custom HTML field somewhere in your CRM....and you have the **page break button** ?
Please send us a picture, and on wich version you are .
