### ISSUE TITLE
Switch from league/url to league/uri due to deprecation

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#6140]
#### Issue

```
$ composer install
Loading composer repositories with package information
Package league/url is abandoned, you should avoid using it. Use league/uri instead.
```

#### Expected Behavior

Not use deprecated software

#### Actual Behavior

Using deprecated software

#### Possible Fix

Switch the composer dependency to league/uri and test to make sure there are no issues.

#### Steps to Reproduce

1. Checkout repo
2. Run `composer install` or `composer update`
3.
4.

#### Context

Don't want to see deprecation warnings or have software which may have security issues.

#### Your Environment

* SuiteCRM Version used: 7.10.7

**Comment by connorshea** [comment]
Any progress on this? league/url has been EOL'd for over three years now.

**Comment by Dillon-Brown** [comment]
@connorshea Updated my PR to pass Travis. Just needs code-review + assessed and it can be merged in.
