### ISSUE TITLE
API Client_credentials grant no refresh_token returned on auth

### ISSUE THREAD

**Issue by asuitecrm** [salesagility/SuiteCRM#6141]
#### Issue
API auth by Client credentials Grant does not return refresh_token
#### Expected Behavior
refresh_token should be returned in response

#### Actual Behavior
Only acces_token is returned in response.

#### Steps to Reproduce
1. Create 2 users grants : Password Grant and Client credentials Grant
2. Request a token using Postman for Client credentials Grant type: 
![image](https://user-images.githubusercontent.com/41069922/42519602-4a85ee58-845c-11e8-84d4-bb70c699a2f8.png)
Request a token via curl:
![image](https://user-images.githubusercontent.com/41069922/42520151-7a065bbc-845d-11e8-8c9f-3d70cf5af75d.png)
3.Request a token for Password grant type:
Curl:
![image](https://user-images.githubusercontent.com/41069922/42520450-315eaa12-845e-11e8-9995-b405b5919443.png)
#### Context
For every query to the API, using the grant_type: client_credentials, a new access_token is generated after expiration time. I'm not receiving the refresh_token in API response

#### Your Environment

* SuiteCRM Version used:Version 7.10.7 Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Postman, Burp, etc.
* Environment name and version (e.g. MySQL, PHP 7): LAMP 
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by asuitecrm** [comment]
As per the Oauth2 documentation:
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/ClientCredentialsGrant.php
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/PasswordGrant.php

for beginners your documentation is very confusing !

![image](https://user-images.githubusercontent.com/41069922/42816706-98fe7430-89c3-11e8-8b83-67993359ceb7.png)

Please remove this as it shows refresh_token returned for the client_credentials grant type and refresh_token is not implemented in Oauth2 for this grant

**Comment by gymad** [comment]
modification needed in doc site at https://github.com/salesagility/SuiteDocs/blob/6e4d21355d1fa3a1a6a648d1e5dd85a14f5d0c22/content/developer/API/version-8/Configure%20Authentication.adoc

**Comment by samus-aran** [comment]
1. Investigation
2. Implementation
3. Refresh the documentation
