### ISSUE TITLE
Unable to load custom logic file: include / SugarSearchEngine / SugarSearchEngineQueueManager.​php

### ISSUE THREAD

**Issue by belchfireid** [salesagility/SuiteCRM#6147]
#### Issue
Error log reports:
Unable to load custom logic file: include / SugarSearchEngine / SugarSearchEngineQueueManager.​php

#### Expected Behavior
No error present

#### Actual Behavior
No visible effect
Slows PHP process response time down significantly.  For example, on some actions, fixing this reduced user response time from 17 sec to 10 sec.

#### Possible Fix
This is an old Sugar bug still present in Suite CRM
https://community.sugarcrm.com/thread/19024 

> I found numerous lines in the LogicHooks that try to call this method in this file, so rather than deleting all of them I created a new file 'include/SugarSearchEngine/SugarSearchEngineQueueManager.php' that is basically empty. Not exactly the way I want to code, but it is better than getting an error for something that is not there.
> 
> Mine looks like this and stops that error message from being thrown:
> 

```
<?php
// filename = include/SugarSearchEngine/SugarSearchEngineQueueManager.php
class SugarSearchEngineQueueManager {  function populateIndexQueue()  {     } } ?>

```   

#### Steps to Reproduce
Seems to only be present when upgrading from SugarCRM. We recently updated from SugarCRM 6.5.18 to SuiteCRM.

#### Context
This has a surprising effect on performance with a relatively slow server.  This may not be all that visible on hosted services (e.g. AWS).

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version: Firefox and Safari, no difference in results
* Environment name and version: Maria DB, PHP 5.5
* Operating System and version: Synology Linux

**Comment by pgorod** [comment]
> I found numerous lines in the LogicHooks that try to call this method in this file

Can you be specific and provide a list?

Thanks for reporting this.

**Comment by belchfireid** [comment]
Sorry, that was a quote from the link that provided the fix.
I did a quick on my system and found instances in: /custom/Extension/application/Ext/LogicHooks
logichooks.ext.php
SugarFTShooks.php

I do not guarantee these are all the instances.

**Comment by pgorod** [comment]
I don't think this is a bug, these are left-overs from SugarCRM. Our installer can't guess to what extent you've made customizations in `custom` folder, and can't go around editing the files you have there. So you're left to doing your own analysis, or you get these problems and fix them as they come :-)

In my 7.10.7 there is no reference to `SugarFTShooks` anywhere. I'd say that file is safe to remove, and any lines describing `SugarFTShooks` hooks is safe to comment out.

**Comment by belchfireid** [comment]
AFAIK, this wasn't done by us.  The only customization we have is login audit, which doesn't use this. 

What should we do with logichooks.ext.php?

**Comment by belchfireid** [comment]
Thanks.
Just for the record, I got the directory wrong above. Logichooks.ext.php is in 
custom/application/Ext/LogicHooks

It is an auto-generated file. Taking out SugarFTShooks and performing a Repair cleans it up.
