### ISSUE TITLE
API v8: "[Unable to convert datetime field using SugarBean]" on update

### ISSUE THREAD

**Issue by Jorilx** [salesagility/SuiteCRM#6148]
I think there's a problem when using the new API to update beans that have NULL datetimes: if I create an email address leaving "confirm_opt_in_date" empty, when I try to PATCH the address, I get an `[Unable to convert datetime field using SugarBean] "confirm_opt_in_date"` error inside suitecrm.log.

Steps to reproduce:

1. Get an API token (of course)
2. Create an EmailAddress
```
POST v8/modules/EmailAddresses
{'data': {'attributes': {'email_address': 'test@test.com',
                         'email_address_caps': 'TEST@TEST.COM'},
                         'type': 'EmailAddresses'}}

```
(returns the created ID)
3. Update the EmailAddress
```
PATCH v8/modules/EmailAddresses/496d18ba-e2b5-2b7a-313c-5b4851c15a2f
{'data': {'attributes': {'email_address': 'test2@test.com',
                         'email_address_caps': 'TEST2@TEST.COM'},
                         'type': 'EmailAddresses'}}

```
4. Check suitecrm.log
```
[FATAL] [SuiteCRM] [API] [Unable to convert datetime field using SugarBean] "confirm_opt_in_date"
```

I think the problem is that during a PATCH operation SuiteCRM fetches the record from DB and when converting it to a bean it converts NULL datetimes to empty strings, that DateTimeConverter doesn't know how to handle.

#### Possible Fix
Maybe lib/API/JsonApi/v1/Resource/SuiteBeanResource.php line 119 should be changed like this?
```
-            if ($definition['type'] === 'datetime' && isset($sugarBean->$fieldName)) {
+            if ($definition['type'] === 'datetime' && isset($sugarBean->$fieldName) && $sugarBean->$fieldName !== "") {

```

SuiteCRM 7.10.6, MariaDB 10.2.16, PHP 7.0.30, Ubuntu Trusty

**Comment by Dillon-Brown** [comment]
No longer an issue in V8.
