### ISSUE TITLE
Email Compose feature from listview

### ISSUE THREAD

**Issue by jyotiraghav93** [salesagility/SuiteCRM#6151]
I need the way to compose an email,from list view, directly under the Contact or Account it concerns

**Comment by Mausino** [comment]
@jyotiraghav93 here is the way how do this. Please close the ticket. 

![suitecrm_demo](https://user-images.githubusercontent.com/5773777/42700097-05783fdc-86c3-11e8-9d33-7dd01aee9ba5.gif)
