### ISSUE TITLE
AOR_Reports: Special Character are not exported correctly

### ISSUE THREAD

**Issue by fgiehlede** [salesagility/SuiteCRM#6161]
Special characters like ' or ß will not be exported correctly. In Report (CSV) the character will be exported as html entity (like `&#039;`),
#### Issue
Reports that containing accounts or contacts with special characters like ß or ' will be not exported correctly

#### Expected Behavior
The special characters should be exported correctly in CSV.

#### Actual Behavior
Special characters like ' or ß will not be exported correctly. In Report (CSV) the character will be exported as html entity (like `&#039;`),

#### Steps to Reproduce
1. Create Company with the character '
2. Create report that contains the company
3. Export the report
4. Open CSV

#### Your Environment
SuiteCRM 7.10.7
MariaDB
Apache
![report1](https://user-images.githubusercontent.com/30693152/42763794-5354876c-8914-11e8-99c7-398eb2402e4a.png)
![report_csv](https://user-images.githubusercontent.com/30693152/42763795-537452cc-8914-11e8-8521-7d01f14a272c.png)

**Comment by PedroErnst** [comment]
Thanks for bringing this up @fgiehlede 

Feel free to test #6168 if you have the time.
