### ISSUE TITLE
PDF Template Discount Percentage is not formatted nicely

### ISSUE THREAD

**Issue by nsoftwarespencer** [salesagility/SuiteCRM#6162]
#### Issue

This is the exact issue described here: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/6902-discount-field-as-percentage 

Basically a line item has a discount of 20 Percent however on the PDF the discount shows as "20.00". 

I could not find it as an existing bug.

#### Expected Behavior

A 20% discount shows as "20%"

#### Actual Behavior

A 20% discount shows as "20.00"

#### Steps to Reproduce

1. Create a line item with a 20% discount
2. Apply a PDF template which makes use of this discount
3. Inspect the discount in the PDF

#### Context

I have already applied the fix suggested in the forum to modify the if statement to:

`if($repl_arr['aos_products_quotes_discount'] == 'Pct' || $repl_arr['aos_products_quotes_discount'] == "Percentage")`

And to append the percentage symbol:

`$value=rtrim(rtrim(format_number($value), '0'),$sep[1]) . $app_strings['LBL_PERCENTAGE_SYMBOL'];`

This is not a priority for me but I would like to see support for this added to a future version so I can remove my local changes.

#### Your Environment

* SuiteCRM Version used: 7.9.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by PedroErnst** [comment]
Thanks for pointing this out @nsoftwarespencer
