### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by mono59** [salesagility/SuiteCRM#6169]
Good afternoon!

In version 7.10.2, when creating a user, in the "Layout Options" tab I put a checkmark in the "Group tabs of sub-panels:".
But at the entrance under the new (created) user - this tick flies.
Prompt, someone faced this? Or where to look for default values ​​under the user profile?

Thank you.

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all
* Environment name and version (e.g. MySQL, PHP 7): ms sql 2016+php 7.2 
* Operating System and version (e.g Ubuntu 16.04): debian 9

**Comment by Mausino** [comment]
@mono59 Please provide some screenshots, that will more understandable.

**Comment by mono59** [comment]
in the video archive with a script problems



[2018-08-02_11h59_08.zip](https://github.com/salesagility/SuiteCRM/files/2252818/2018-08-02_11h59_08.zip)

**Comment by Mausino** [comment]
@mono59 in your video i don't see nothing bad... any issue... problem is that you're missing the upgrade.. because in latest version 7.10.7 below the display modules are those options

Sort module alphabetically
Subpanel Tab
Show collapsed subpanel hint

I thing that you don' have any issue only you misunderstand some processes... 

Please close the ticket.. this is the thema/question for [forum](https://suitecrm.com/suitecrm/forum/suite-forum), where many users can manage it with you. Without clear description it doesn't belong to this place.

**Comment by mono59** [comment]
@Mausino 
Мне жаль, что вы не являетесь специалистом и не в состояние понять описание проблемы.
Пожалуйста , если вы не пони маете о чём речь - не пишите сюда больше.
Спасибо.

**Comment by horus68** [comment]
@mono Actual version is 7.10.7 so please upgrade your version before opening issues here.

GITHUB is not a forum for individual problems, issues are for problems already reproduced by others. The forum is for raising problems or to get help using the system.

Note:
You replied using a different language from your question. Please stay with english (and I'm not an English user too!
On your reply contents: You got a proper reply from an user (a plain user like me but with given proof of knowledge on SuiteCRM), asking you to move the question to the SuiteCRM forum https://suitecrm.com/suitecrm/forum/index 
Why didn't you liked it?

Using Google translate I found your reply as rude and not acceptable 
```
I'm sorry that you are not a specialist and can not understand the problem description.
Please, if you do not understand what it means - do not write here anymore.
Thank you.
```
You must use english when people reply to your english question!

**Comment by sbebbers** [comment]
I have the same issue.

According to the Debug, there is an issue with creating some Javascript objects here:

https://github.com/salesagility/SuiteCRM/blob/master/modules/Users/tpls/EditViewFooter.tpl#L579

Both are not showing anything.

Related Javascript errors are happening in:

https://github.com/salesagility/SuiteCRM/blob/master/jssource/src_files/modules/Users/UserEditView.js#L385

Please see screen shot.

![usermanagement-suitecrm](https://user-images.githubusercontent.com/24898357/45889179-ac2b8c00-bdb7-11e8-99cc-7195c89b5e59.png)

**Comment by samus-aran** [comment]
Looks like its a unique javascript issue and this is usually caused by javascript customisations or issue with cache. As suggested please jump onto the forums and follow normal steps to identify the core issue if there is one. Thanks everyone.

**Comment by samus-aran** [comment]
@mono59 
It has already been addressed by fellow community members but I'm only reiterating - we are here to help and when we ask for more information we are assisting with explaining the processes of the community. Please be cooperative and respectful of others.
