### ISSUE TITLE
In Wizard editing existing campaing moving from "Templates" to "Marketing" to "Send Email ..." creates new entry under marketing

### ISSUE THREAD

**Issue by jobst** [salesagility/SuiteCRM#6172]
#### Issue

If you forgotten something (e.g. a tracker) or re-edit a template to add/delete/move text, than move from "Templates" to "Marketing" to "Send Email ..." creates new EMPTY entry under marketing.

#### Expected Behavior

In Wizard moving from "Templates" to "Marketing" to "Send Email ..." should NOT create new EMPTY entry under marketing, but simply keep the original entry as this is an EDIT not CREATING.

#### Actual Behavior

In Wizard moving from "Templates" to "Marketing" to "Send Email ..." creates new EMPTY entry under marketing as the "Marketing Email Name" is empty when editing an EXISTING campaign.
The entry is visible in the campaing overview with EMPTY marketing name.

#### Possible Fix

In Wizard moving from "Templates" to "Marketing" fill out the marketing name from the ORIGNAL (the campaign you are currently editing), this will stop creating a new marketing entry.

#### Steps to Reproduce

1. open wizard
2. use next to move from "Templates" to "Marketing" to "Send Email ..."
3. go to the campaign (the one you just edited) overview 
4. look under "email marketing"
5. there is a new entry

#### Context

It does not really as the campaing still works as the new entry is appened and the email sending uses the first entry, **BUT**  it adds an entry in the DB and its confusing in the overview and one does not know whether there is an error.

#### Your Environment

* SuiteCRM Version used: 7.9.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7): N/A
* Operating System and version (e.g Ubuntu 16.04): N/A

**Comment by PedroErnst** [comment]
Hi @jobst 

Thanks for reporting this.

If you get a chance to test the fix in the PR above please let me know if it works for you.

**Comment by jobst** [comment]
@PedroErnst I went back today (sorry been really busy) and the "Remove" was there today. I tested it in Firefox and Chrome and it's there in both. I have no clue why it did not work for two days, but today it does.

**Comment by jobst** [comment]
@PedroErnst the fix works for me, thanks.
