### ISSUE TITLE
7.8.20 Case updates display problems

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#6174]
#### Issue

when a customer answering to a case with HTML email with attachment the display of case updates is having  problems, the current message <div> is not being closed leading to next message included into the same message box as follow
![image](https://user-images.githubusercontent.com/8605061/42887932-6134eafe-8aa7-11e8-9589-5193754aceb4.png)

#### Expected Behavior

message box should be closed no matter of message content or attachment. 

#### Steps to Reproduce

1. still trying to reproduce the problem, will update as soon as possible , but opening the issue already in case you know this problem already. 
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): php 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by boombata** [comment]
I think problem is linked to the way email is saved to AOP_Case_update. 
module/AOP_Case_Updates/CaseUpdateshook.php in function saveEmailUpdate($email) , Line 261
$caseUpdate->description = $updateText;

If I'm not wrong there is no SugarCleaner::cleanHtml call before has it is done when you manually entering a case update . if received email is malformed or truncated then it breaks case update display.

**Comment by boombata** [comment]
Hi, has this problem been fixed into another reported issue   ?

**Comment by pgorod** [comment]
I don't think there has been any work on this.

Can you provide a specific email that causes this behavior? Something we could use to reproduce the issue here?

**Comment by cameronblaikie** [comment]
Hi @boombata , 
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. 
Thanks.
