### ISSUE TITLE
Fatal error: Call to a member function call_custom_logic() on boolean 

### ISSUE THREAD

**Issue by ftoledo** [salesagility/SuiteCRM#6178]
This error raise when undo a cases import process.

**Comment by PedroErnst** [comment]
Filling out the template with (at least) your environment details and steps to reproduce would be very helpful.

**Comment by pgorod** [comment]
I tried reproducing this and it worked well for me on 7.10.7 (import cases, undo at the end). Nothing in the logs.

I suggest closing this Issue, such an incomplete report is not useful at all and should be discouraged...
