### ISSUE TITLE
FP_event Email Invite Template dropdown populates with email_templet_list

### ISSUE THREAD

**Issue by dslad** [salesagility/SuiteCRM#6179]
#### Issue

In the Events module, email invites cannot be generated as the template dropdown is not correctly populated.

#### Expected Behavior

I would expect this dropdown to populate with a list of email templates.

#### Actual Behavior

But it populates with the single item "email_templet_list" (which cannot be selected and saved).

#### Steps to Reproduce

This can be reproduced on the [demo site](https://demo.suiteondemand.com/) 
1. Login
2. Select menu item "All"->"Events"
3. Create Event named e.g. "test" and save
4. Click "Email Invite" tab
5. Double-click "Email Invite Template" field

#### Context

This is preventing usage of email invites in the Events module.

#### Your Environment

* SuiteCRM Version used: 7.10.7 on Sugar Version 6.5.25 (Build 344)
* Browser name and version: Chrome 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.2.7-1+ubuntu14.04.1+deb.sury.org+1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

![image](https://user-images.githubusercontent.com/41398718/42910873-e61cfb38-8ae0-11e8-82aa-78841931bf89.png)

**Comment by kierenj** [comment]
This still doesn't work for me: I get an inline dropdown, but it instead only has *categories* of email template. I need to use the full Edit function to be able to select an actual template.
