### ISSUE TITLE
Feature Request: Export contact as vcard

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#6189]
Normally I will import from vcards but today I wanted to share a contact outside of our organization.  I can't find a option or ability to export a vcard of a contact or lead.

I think it would be really useful to help speed up work if available.

**Comment by pgorod** [comment]
I delved a bit in to this issue about a year ago and I found that the vCard appears to the right of the "Name" field, but not in "First Name" and "Last Name" fields.

If I'm not mistaken, the most recent SuiteCRM's use the First/Last name pair on the Detail view of contacts. You can always go into Studio to change the fields displayed. 

But maybe this could be added somewhere by default.

**Comment by bunk3m** [comment]
I now see that there is a vcard icon to the right of the Name field for Leads.

But that Name field isn't available by default in the Contacts view.  :-( 

Yes, I suppose that I can go into the Studio to change the layout and see if I can add it to the Contacts view.

**Comment by bunk3m** [comment]
Thanks @pgorod 
I rejigged the Contacts layout to include "Name" and removed "First Name" & "Last Name".  Now I have the export as vcard option available!  Great!

**Comment by quazgar** [comment]
I'm sorry, I can't find the export option on the demo page (demo.suiteondemand.com), is this implemented just in some development version at the moment?

**Comment by pgorod** [comment]
@quazgar you can find on the Leads Detail view, for example, like this:

![image](https://user-images.githubusercontent.com/15945027/48439114-708cbd00-e77d-11e8-8b3d-c5e9d0acb535.png)

But in Contacts, the `Name` field is split in to two fields, `First name` and `Last name`. So the vcard export icon doesn't appear. You can go in Studio and edit the detail view to show the complete `Name` field instead.

This demo allows admin access (so you can try Studio):
https://www.softaculous.com/demos/SuiteCRM

**Comment by pgorod** [comment]
@bunk3m maybe we can close this Issue? I am not sure it is necessary to do anything else... some people will prefer the name split in two fields, other people will prefer a single field, and anybody can change the layout in Studio.

So I suppose this issue was helpful to clarify things, but no longer needs to be open, do you agree? Thanks.

**Comment by bunk3m** [comment]
@pgorod Sounds OK.  Perhaps this information should be put in the documentation so everyone can find it easily.  It isn't intuitively obvious, so people like me will think it is a bug.  But if we can find it in the docs, then we can figure out how to get what we want in the layout.

**Comment by likhobory** [comment]
@bunk3m 
@pgorod 
I think this is a good clarification, I'll add this information to the Russian section.

**Comment by pgorod** [comment]
@quazgar the live demos refresh (reinstall) themselves every hour, if you have the bad luck of going there during the refresh, you get errors. 

@bunk3m I agree about the Docs, can you do it please? Everybody can contribute! :-)

Thanks @likhobory!

(I can't close the issue, only the owner or one of the admins here can.)

**Comment by bunk3m** [comment]
@pgorod I might be able to but I figured this out around when I posted this in the summer.  Now I can't remember what I did.  Any my SCRM has the customization already.  Not sure what I did.

I'll see what I can do.  Where would I post this if I can figure out what I did?

**Comment by pgorod** [comment]
Thanks. Never mind, I already added a short notice about this to the Documentation. I used @likhobory's sentence (through Google Translate) :-)
