### ISSUE TITLE
Workflow condition don't run if there is a multiselect dropdown condition

### ISSUE THREAD

**Issue by indigo21** [salesagility/SuiteCRM#6198]
Issue

Whenever I tried to add a multi select dropdown in the condition of the workflow and set "equal to" and  "one of" to run on new records, the workflow is not working. Without this, it is working fine.

Also tried it in https://www.softaculous.com/demos/SuiteCRM and I can confirm that the issue exists.

Steps
1. Create a workflow run on new records -> module: Meetings
2. contacts lead source equal to one of

* SuiteCRM Version 7.9.12
* Google Chrome Version 67.0.3396.99
* MySQL, PHP 7

**Comment by cameronblaikie** [comment]
Hi @indigo21 , 
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. 
Thanks.

**Comment by willrennie** [comment]
@indigo21 just to follow up, SuiteCRM 7.9.x is no longer supported so I would suggest you upgrade to SuiteCRM 7.10.x LTS and ensure this functionality is now working. If you feel it is still a valid bug, please update with screen shots of your workflow configuration and detailed steps to reproduce.
