### ISSUE TITLE
Unable to print PDF of module

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#620]
I came across this bug buy forking the master. then cloning.

go through the installation as normal. 

print a pdf of a quote or any module....it will then blank screen.

Could somebody confirm this bug? 

Problem is caused by empty field def names 

version 7.4

**Comment by darthtang** [comment]
else {
                    if(empty($field_def['name'])){
                        continue;
                    }

at line 44 of template parser will get round the problem but this is not ideal

**Comment by darthtang** [comment]
To note. I cant print the pdf after a refresh of the blank page. Again...not ideal

**Comment by JimMackin** [comment]
Seems to be related to the inline editing flags set on some of the jjwg_maps fields causing malformed vardefs.

**Comment by tegersow** [comment]
Is there any way to solve this problem? because after upgrading our 7.3.x to 7.4 all pdf and email to pdf is broken

**Comment by gymad** [comment]
We don't recreate the problem, I suggest clear the cache and do a quick repair.

**Comment by adriangibanelbtactic** [comment]
1) We have found the same problem. When you try to print a pdf it shows a blank page.

2)
As other have found out we have found the problem on: https://github.com/salesagility/SuiteCRM/blob/aad227325a9238e9e916f6d6401b34aca703300a/modules/AOS_PDF_Templates/templateParser.php#L46-L48

So from:
```
                else {
					$repl_arr[$key."_".$field_def['name']] = $focus->$field_def['name'];
				}
```
we have done a workaround into:
```
                else {
                    if (isset($field_def['name'])) {
                      $repl_arr[$key."_".$field_def['name']] = $focus->$field_def['name'];
                    }
                }

```

3) If you want to see the php error when the blank page appears you need to comment this line: https://github.com/salesagility/SuiteCRM/blob/aad227325a9238e9e916f6d6401b34aca703300a/modules/AOS_PDF_Templates/generatePdf.php#L30 .

4) Related to what @JimMackin says we have noticed these apache errors when entering into the Detailview page (where the generate PDF button is):

```
[Fri Dec 04 15:49:40.531839 2015] [:error] [pid 13880] [client 1.2.3.4:50002] PHP Notice:  Undefined index: enable_line_editing_detail in /var/www/html/include/DetailView/DetailView2.php on line 76, referer: http://crm.mydomain.com/index.php?action=ajaxui
```
We also see:
```
[Fri Dec 04 15:42:34.950574 2015] [:error] [pid 29883] [client 1.2.3.4:49670] PHP Notice:  Undefined index: enable_line_editing_list in /var/www/html/include/ListView/ListViewSmarty.php on line 109, referer: http://crm.mydomain.com/index.php?action=Login&module=Users
```
if it helps.

I don't think it has something to do with the forementioned jjwg_maps fields but I'm not confident on 100% on my thought. Please see (5) in this same message.

5) Upon further debug the problem when processing this (print_r output) : $focus->$field_def : 
```
   [lhs_module] => Contacts
    [lhs_table] => contacts
    [lhs_key] => id
    [rhs_module] => Notes
    [rhs_table] => notes
    [rhs_key] => parent_id
    [relationship_type] => one-to-many
    [relationship_role_column] => parent_type
    [relationship_role_column_value] => Contacts
```
as you can there is no 'name' key there.

Where does it come from?

You just need to check:
```
modules/Contacts/vardefs.php
```
file after the upgrade which has this additional lines:
```
       'contact_notes_parent' => array('lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'Notes',
            'rhs_table' => 'notes',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
                        'relationship_role_column'=>'parent_type',
            'relationship_role_column_value'=>'Contacts'
        ),
```
both inside its relationships array and outside of it.

In other of our installations (and in upstream too: https://github.com/salesagility/SuiteCRM/blob/aad227325a9238e9e916f6d6401b34aca703300a/modules/Contacts/vardefs.php ) this code is only found inside the relationship array and not outside of it.

So I guess removing the wrong code there (yes, we are sometimes forced to edit vardefs.php manually and errors hapen).

I'll give you feedback later if this was the cause of our problem or not.

6) We upgraded from Sugarcrm 6.5.20 to Suitecrm 7.3.2 version. So the bug can be found at 7.3.2. After realising (5) I'll do more tests and I will tell you if it's a problem on how the relationships are dealt on this code... or... if it's a fault of us editing vardefs.php (probably the latter one). In that case this would be an invalid bug.

7) The error appeared also when using an empty crm (no actual fields but just text labels on it).

8) We debug the problem with:
```
$GLOBALS['log']->fatal("key: ".$key." field_def". print_r($field_def,TRUE). " focus->field_def ". print_r($focus->$field_def,TRUE)) ;
```
or if you need more detail:
```
$GLOBALS['log']->fatal("key: ".$key." field_def". print_r($field_def,TRUE). " focus->field_def ". print_r($focus->$field_def,TRUE) . "focus: ". print_r($focus,TRUE)) ;
```
just before this line: 
https://github.com/salesagility/SuiteCRM/blob/aad227325a9238e9e916f6d6401b34aca703300a/modules/AOS_PDF_Templates/templateParser.php#L47.

And, yes, do not forget to comment the php error as I explain in (3) just to make your debugging eassier.

**Comment by adriangibanelbtactic** [comment]
I confirm it.

So let's summarize it.

1) We also had this problem.
2) What was our problem ?
During an upgrade we probably edited at hand:
```
modules/Contacts/vardefs.php
```
where we added these lines
```
       'contact_notes_parent' => array('lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'Notes',
            'rhs_table' => 'notes',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
                        'relationship_role_column'=>'parent_type',
            'relationship_role_column_value'=>'Contacts'
        ),
```
as duplicates outside the relationship array.

3) How can you debug how your vardef wrong array portion is ?

You need to add:
```
$GLOBALS['log']->fatal("key: ".$key." field_def". print_r($field_def,TRUE). " focus->field_def ". print_r($focus->$field_def,TRUE)) ;
```
or if you need more detail:
```
$GLOBALS['log']->fatal("key: ".$key." field_def". print_r($field_def,TRUE). " focus->field_def ". print_r($focus->$field_def,TRUE) . "focus: ". print_r($focus,TRUE)) ;
```
just before this line: 
https://github.com/salesagility/SuiteCRM/blob/aad227325a9238e9e916f6d6401b34aca703300a/modules/AOS_PDF_Templates/templateParser.php#L47.

Then after that reproduce the error (Blank page when trying to print it) and check your sugarcrm.log for fancy print_r output where the culprit lines will appear.

4) Hopefully this will help @darthtang on debugging his problem. Maybe the commit he used from master has a wrong vardef definition somewhere and that needs to be fixed after all.

**Comment by jshwhitlow** [comment]
Why has this issue not been looked at yet and closed? I was having this same issue and can find dozens of threads and questions where it is asked. I solved it by adding the same correction in /modules/AOS_PDF_Templates/templateParser.php on line 47
```
else if (isset($field_def['name'])) {
                      $repl_arr[$key."_".$field_def['name']] = $focus->$field_def['name'];
                    }
```

It needs to check that the property isn't empty, or in my case 'null'. Whenever a null field is created in studio (A frequent problem) then this issue occurs.

You can recreate this problem simply by going in the code and intentionally adding a null field, then create a PDF Template and try to Generate the Letter.

I am running SuiteCRM 7.5.1.

**Comment by hubyhuby** [comment]
Might be correclated with some issues I have in 7.8.8, sometime "print pdf" doesn t work after changing a template. I have to delete all the templates ...sometimes restarting the web browser works
https://suitecrm.com/forum/installation-upgrade-help/16286-pdf-template-pagebreak-disapearing-after-upgrade-to-7-8-8#54836

**Comment by Jason-Dang** [comment]
This is can no longer be replicated in 7.8.x. There is a check in place to ensure that the each field in the field def array is set and not empty.
