### ISSUE TITLE
SMTP Problem.

### ISSUE THREAD

**Issue by jacentys** [salesagility/SuiteCRM#6201]
#### Issue

SuiteCRM dosn't send mail notification. For example when user created.

#### Expected Behavior

I want send mail within SuiteCRM and get notification from SuiteCRM

#### Actual Behavior

1. SMTP created and checked (I can send test mail wthout any problem)
2. Mail notification dosn't work (for example on creating user)

In log I find something like this:
Wed Jul 25 13:30:45 2018 [2457][1][ERROR] Email address save error
Wed Jul 25 13:30:45 2018 [2457][1][ERROR] Unable to find relationship.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Linux (I don't know chow to check version.

**Comment by pgorod** [comment]
Hi @jacentys I have answered you on the Forums, so we'll close this issue here, if you don't mind.

This is adequate for the Forums, as we help you check your configs etc., only after you are sure this is a bug that needs to be reported to the developers, then you report here. Thanks.
