### ISSUE TITLE
Export PDF in reports with sum row have many blank pages!

### ISSUE THREAD

**Issue by xanthos84** [salesagility/SuiteCRM#6203]
#### Issue

If you make a report and export it as a PDF and it contains a sum row from a float field,
the exported PDF file has many blank pages.

#### Expected Behavior
You should get a PDF with all records and one last sum row.

#### Possible Fix
cant say how to fix.

#### Your Environment
* SuiteCRM Version used: latest 7.10.7

* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): opera/chrome
* Environment name and version (e.g. MySQL, PHP 7): bitnami image
* Operating System and version (e.g Ubuntu 16.04): bitnami image

**Comment by ChangezKhan** [comment]
This issue is similar to #5856

**Comment by ChangezKhan** [comment]
This issue #5856 is solved and delivered with version 7.10.8. Kindly check once again and close this issue.

**Comment by samus-aran** [comment]
Will close due to inactivity. Thanks everyone!
