### ISSUE TITLE
Syntax error in _AddJobsHere.php causes scheduled report not to render properly

### ISSUE THREAD

**Issue by rahulner** [salesagility/SuiteCRM#6204]
#### Issue
Syntax error in _AddJobsHere.php causes scheduled report not to render properly

#### Expected Behavior
Emailed report should be shown with proper width.

#### Possible Fix
/modules/Schedulers/_AddJobsHere.php line no 787
line no 787 , remove last }

```
Current:
border-bottom: 2px solid black};
Fix: 
border-bottom: 2px solid black;
```
#### Steps to Reproduce
 
1. Run any scheduled report and check the content in email.

**Comment by samus-aran** [comment]
Thanks @rahulner for your contribution, we have created a Pull Request and now applying tests to confirm that it is successful.

**Comment by samus-aran** [comment]
Hi @rahulner Are you able to test the proposed fix. We have but wanted to ensure that you can apply it to your instance immediately.
