### ISSUE TITLE
Seval bugs when host is running php 5.5.27

### ISSUE THREAD

**Issue by Dafnie** [salesagility/SuiteCRM#621]
The following bugs has been found when installing SuiteCRM v7.3 - 7.4 via Softaculous or manual at the host hostinger.dk.
- All popup message display 'undefined'
- Can not edit dashlets
- Can not add dashlet
- Can not add meeting from calendar module

Hostinger config:
Apache-version	2.4.12
PHP-version	5.5.27
Browser: Chome 46.0, Explorer 9 and Firefox

When shifting to php 5.3 everything work, but it is not possible to shift to php 5.3 any more.
The problem is the same for the host meebox.net.

Any plans for upgrading til newer php?

**Comment by willrennie** [comment]
The CRM should work on PHP 5.5 without issue. Can you confirm the installation was successful, that the correct permissions have been set and that the .htacess 'RewriteBase' value points to the correct directory the CRM is located within?

**Comment by Dafnie** [comment]
Greetings,

Tanks for the reply.
Yes I can confirm that installation was successful and the .htaccess point
at the correct directory. The installation was made with softaculous from
my host.
Well i gave up and our company have switched to EspoCRM.

EspoCRM is very fast, but we are missing some of the features from
SuiteCRM.

2016-01-22 21:27 GMT+01:00 Will Rennie <notifications@github.com>:

> The CRM should work on PHP 5.5 without issue. Can you confirm the
> installation was successful, that the correct permissions have been set and
> that the .htacess 'RewriteBase' value points to the correct directory the
> CRM is located within?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/salesagility/SuiteCRM/issues/621#issuecomment-174037378>
> .
>



-- 

Med venlig hilsen


*[image:
https://docs.google.com/uc?export=download&id=0Bxm2SlpPeEnVZjdKbHJzVzdBNk0&revid=0Bxm2SlpPeEnVbFptY1hTSmEvb09xSGswL1dOZ1YyNk5zcjQ0PQ]*





*  Carsten Gjedde*
  Ejendomsmægler MDE







mobil: 22757425

email: cg@sommerhusmaegleren.nu


*SommerhusMægleren Odsherred*
Asnæs Lyngvej 12
4550  Asnæs
