### ISSUE TITLE
PDF Reports not working (not opening)

### ISSUE THREAD

**Issue by mahmoudrashwan** [salesagility/SuiteCRM#6216]
i'm using suitecrm 7.10.7,
i try to download a report from (download pdf) from menu action in report, but when i try to open pdf file (which i downloaded),  i found an error message: (the file either not a suppported file type or because the file has been damaged).

#### Issue
I use some entires in Arabic language, and i changed product-category to assets category, then i entered some categories in it with arabic language.

1. when i try to export a report with all categories in excel, the arabic characters  seems wrong formated like (ط«ظ„ط§ط¬ط§طھ),

2. then i tried to download report as pdf from (action menu), when i try o open downloaded pdf i get this message: (the file either not a suppported file type or because the file has been damaged).

3. i tried to download a new report pdf but in english entries, same issue and cant open pdf file
![error pdf](https://user-images.githubusercontent.com/41969465/43480635-222a5db4-9504-11e8-85e2-928b17541f06.PNG)
![capture](https://user-images.githubusercontent.com/41969465/43480636-226682da-9504-11e8-9b05-0e4a7444f7e7.PNG)
![error arabic char](https://user-images.githubusercontent.com/41969465/43480637-22a3c51e-9504-11e8-9ea9-c5b3f42b7115.PNG)

**Comment by andreabia** [comment]
maybe you have the wrong error_reporting on you php.ini.
try to set error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED

**Comment by mahmoudrashwan** [comment]
@andreabia  
thanks for reply, i didn't understand what you refer to!!
what's the relation between setting error in php.ini and (corrupt pdf export)
i mean my issue is any report.pdf file not opening with the above error in first screenshot

**Comment by andreabia** [comment]
in your second screenshot there is a E_NOTICE warning... this mean you have not the correct  settings.
`error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED`

**Comment by mahmoudrashwan** [comment]
@andreabia 
thaaaaaaaaaaaaaaaaaaaanks aloooooooot boss :)
I opend report.pdf with note++ and deledted all error (it was more than 1400 line of errors)
then i recopied folder aor_reports, 
then edited the php.ini with ur solution (error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED)
and file i made a quick repair 
and all working gooood.

would you mind if you help me in my other issue, i posted it 1 hour ago

**Comment by mahmoudrashwan** [comment]
my other issue 
make fields editable once in cases #6226 
https://github.com/salesagility/SuiteCRM/issues/6226
