### ISSUE TITLE
make fields editable once in cases 

### ISSUE THREAD

**Issue by mahmoudrashwan** [salesagility/SuiteCRM#6226]
#### Issue
i try to make some fields in case non editable Once saved the case, which mean:
-- when the user create case can edit any field, but once the case created the user can not be able to edit specific fields (description, subject, type, etc).

-- and once the state changed to (closed) the user can't reopen the case or made a button called (close) to close the case and made the hole case cant be reopen,
or at least the user cant change the state again to open.

-- and what can i do, if i want to made above condition for certain users) (admins can apply the restrictions above)

#### Context

high priority

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version: OPERA 48.0.2685.35 (PGO) (64-bit)
* Environment name and version: WAMP SERVER  3.0.6 64 BIT
* Operating System: windows 8.1 X64

**Comment by mahmoudrashwan** [comment]
@andreabia
i will be grateful if you can help me in the above issue

**Comment by PedroErnst** [comment]
This can be done through custom code.

**Comment by mahmoudrashwan** [comment]
@PedroErnst any suggest also, to how can i write this custom code

**Comment by PedroErnst** [comment]
Sure, have a look at this https://docs.suitecrm.com/developer/
