### ISSUE TITLE
Import Emails Automatically on group Inbound account mark emails as seen

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#6230]
#### Issue

When you check "Import Emails Automatically" in group email account, the incoming mails are marked as read (seen).
This issues start in this [forum post](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/10601-gmail-iamp-suitecrm-email-mark-as-read)

#### Expected Behavior

Not to mark emails as read (seen)

#### Actual Behavior

The mails are marked as read

#### Possible Fix

The are some ideas in the [forum post](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/10601-gmail-iamp-suitecrm-email-mark-as-read) but do not works

#### Steps to Reproduce

1. Create a group Mail Account 
2. Check the option: Import Emails Automatically
3. Go to Emails module
4. Verify incoming mails are imported but marked as read

#### Context

In groups that manage an email account you do not know if someone read the mails because every mail is marked as seen

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 60
* Environment name and version (e.g. MySQL, PHP 7): PHP7, MySQL 5.7
* Operating System and version (e.g Ubuntu 16.04): Debian 9 / Ubuntu 16.04

**Comment by tstanczyk** [comment]
I just observed the described behaviour in 7.11.3.
