### ISSUE TITLE
The method getNewMessageIds() do not always execute the right query

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#6231]
#### Issue

Doing some research to solve #6230 I figured out that the `function pollMonitoredInboxesAOP()` calls the function `$aopInboundEmailX->getNewMessageIds()` in modules/Scheduler/_AddJobsHere.php (line 572)

```
                if (!$aopInboundEmailX->isPop3Protocol()) {
                    $newMsgs = $aopInboundEmailX->getNewMessageIds();
                }
```

This function is not defined in the `class AOPInboundEmail()`, it's defined in it's parent `class InboundEmail()`

And this function executes a SQL sentence:

`SELECT last_run FROM schedulers WHERE job = \'function::pollMonitoredInboxes\'`

As we have scheduled the function pollMonitoredInboxesAOP this query returns no record.

```
mysql> SELECT last_run FROM schedulers WHERE job = 'function::pollMonitoredInboxes';
Empty set (0.00 sec)

mysql> SELECT last_run FROM schedulers WHERE job = 'function::pollMonitoredInboxesAOP';
+---------------------+
| last_run            |
+---------------------+
| 2018-08-08 19:30:01 |
+---------------------+
1 row in set (0.00 sec)
```

#### Expected Behavior

The query should return the last_run of the scheduled task.

#### Actual Behavior

The query returns no record.

#### Possible Fix

The getNewMessageIds() method should execute the query 
`SELECT last_run FROM schedulers WHERE job = "{$this->job_name}"`

And the property $job_name should be setted up in each class.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 61
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Assessed
