### ISSUE TITLE
Campaign: viewed emails count

### ISSUE THREAD

**Issue by Viktor31291** [salesagility/SuiteCRM#624]
Hello!

I've notice that in Suitecrm 7.3.2, when sending email on @gmail and @yandex the count status of viewed emails doesn't work. When I send the email to MS Outlook domain it works fine. Please provide the decision.

Thanks1

**Comment by samus-aran** [comment]
@paulgodley Did you make a pull request for this commit?

**Comment by paulgodley** [comment]
Hi @samus-aran, I think that the commit had the wrong bug id.  I do not remember sorting this.

**Comment by Mausino** [comment]
@salesagility @salesagility the issue ticket is very old and it's very jard to test it.  It was in version 7.3 and now we will have 7.11

It should be closed issue. If will have @Viktor31291 same problem in version 7.10+ should add comment here with better description.
