### ISSUE TITLE
Cannot set up Outgoing Emails in SuiteCRM

### ISSUE THREAD

**Issue by razdavid** [salesagility/SuiteCRM#6245]
#### Issue
I cannot send test emails, nor can I send normal emails via cases. 

#### Expected Behavior
I should be able to send test emails and emails successfully.

#### Actual Behavior
Every time I try to send a test email, the system enters a sort of loop and stops working for a few minutes. The screen is as depicted in the following screenshot: 
![capture](https://user-images.githubusercontent.com/42437600/44204841-a3122400-a154-11e8-9214-e64c9ddb29b9.PNG)

I checked the suitecrm.log file and it throws the following errors. These are the first records in the log file on a fresh installation, in which I only tried to set up the outgoing emails.

`Tue Aug 14 16:04:18 2018 [22770][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
Tue Aug 14 16:08:47 2018 [27679][1][FATAL] log call at: modules/EmailMan/tpls/config.tpl:444 - styleChecked is not set
Tue Aug 14 16:14:08 2018 [28867][1][FATAL] SugarPHPMailer encountered an error: An outgoing mail server is not configured to send emails. Please configure an outgoing mail server or select an outgoing mail server for the mail account that you are using in Settings >> Mail Account.
Tue Aug 14 16:14:08 2018 [28867][1][FATAL] SugarPHPMailer encountered an error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Tue Aug 14 16:14:08 2018 [28867][1][FATAL] SugarPHPMailer encountered an error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Tue Aug 14 16:14:08 2018 [30369][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [30369][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [30829][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [30829][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [31490][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [31490][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [32400][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [32400][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [33004][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [33004][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [33055][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [33055][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away
Tue Aug 14 16:14:08 2018 [33092][-none-][FATAL] Mysqli_query failed.
Tue Aug 14 16:14:08 2018 [33092][-none-][FATAL] Retrieving record by id users:1 found  Query Failed: SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1: MySQL error 2006: MySQL server has gone away`

If I try to go to the homepage of the CRM while the system is not working, then Google Chrome displays the following error: 

`Database failure. Please refer to suitecrm.log for details.
Fatal error: Uncaught Exception: Database failure. Please refer to suitecrm.log for details. in /homepages/12/d574299968/htdocs/crm.fst.eu/include/utils.php:1772 Stack trace: #0 /homepages/12/d574299968/htdocs/crm.fst.eu/include/database/DBManager.php(353): sugar_die('Database failur...') #1 /homepages/12/d574299968/htdocs/crm.fst.eu/include/database/DBManager.php(328): DBManager->registerError('Retrieving reco...', 'Retrieving reco...', true) #2 /homepages/12/d574299968/htdocs/crm.fst.eu/include/database/MysqliManager.php(177): DBManager->checkError('Retrieving reco...', true) #3 /homepages/12/d574299968/htdocs/crm.fst.eu/include/database/MysqlManager.php(285): MysqliManager->query('SELECT users.* ...', true, 'Retrieving reco...') #4 /homepages/12/d574299968/htdocs/crm.fst.eu/data/SugarBean.php(4545): MysqlManager->limitQuery('SELECT users.* ...', 0, 1, true, 'Retrieving reco...') #5 /homepages/12/d574299968/htdocs/crm.fst.eu/include/SugarObjects/templates/person/Person.php(113): SugarBean->retrieve('1', true, true) #6 / in /homepages/12/d574299968/htdocs/crm.fst.eu/include/utils.php on line 1772`

When I try to access the home page while the system has stopped working via Firefox, I get the following message: 
"The page you are looking for is temporarily unavailable.
Please try again later.
7e4fa823992b1f03151dde95dd308218 c4b6d5027001898977bba4efe0feef50 c2aa62d488296e248a11a46a04633429 "

#### Possible Fix
I read through a few related posts, such as [this one](https://github.com/salesagility/SuiteCRM/issues/4146), where someone suggests to not use special characters for the email password. My password initially contained special characters but now it only contains letters and numbers. However this hasn't solved the issue.

#### Steps to Reproduce
1. Log into a fresh installation of suiteCRM (in my case https://crm.finestories.eu/)
2. Set up Outgoing Email settings in admin, following the instructions provided by 1and1: ![capture2](https://user-images.githubusercontent.com/42437600/44204902-cccb4b00-a154-11e8-9f58-07252ced41a6.PNG)
3. Insert all SMTP detail and click *Send test email*
4. See message *Performing Task: One moment please...* and nothing else.

#### Context
The first time I installed suiteCRM was on PHP 5.6, however I later upgraded to the latest PHP version (7.2) and I reinstalled suiteCRM thinking that it might solve the problem. Unfortunately it didn't.
I also successfully tried to connect with the provided SMTP details via tools like pingability.com/smtptest.jsp and www.smtper.net/, however, according to the .log file the issue is that SMTP connect failed.

#### My Environment
SuiteCRM Version used: 7.10.7
Installed on 1and1 (Italy) shared server.
Tried with both Google Chrome Version 68.0.3440.106 (Official Build) (64-bit) and Firefox Quantum 61.0.2 (64-bit)
Server type: MySQL
Server version: 5.5.60-0+deb7u1-log - (Debian)
PHP 7.2
Web server: Apache/2.2.22
Operating System Windows 10 Home

Please help me understand how to fix this issue and thank you for your time.

**Comment by Dillon-Brown** [comment]
Hi @razdavid, this looks like an issue with your hosting. In particular, "MySQL server has gone away". I would try adjusting the max_allowed_packet in the MySQL config, that usually sorts out the mysql server has gone away issue.

**Comment by razdavid** [comment]
Hello @Dillon-Brown!
Thank you very much for your answer! I checked max_allowed_packet in MySQL and, as displayed in the below screenshot, it seems to be 10MB. Would that be enough? What value would you suggest to set up?
![image](https://user-images.githubusercontent.com/42437600/44206674-de175600-a15a-11e8-9f73-f52c9a32b6ed.png)

**Comment by Dillon-Brown** [comment]
@razdavid It's a safe value to change as the extra memory is allocated only when needed. I'd try set it at something like 128M.

**Comment by razdavid** [comment]
@Dillon-Brown, thanks for the suggestion! I've been trying to change this variable unsuccessfully, since I can't locate the my.ini file on the shared hosting, nor have I the SUPER privileges needed to perform the following query: set global max_allowed_packet=128M. I'm currently in contact with their support to overcome this. I'll let you now as soon as I news.

**Comment by razdavid** [comment]
@Dillon-Brown, I spoke with their support and they suggested me to research if the my.ini file could be created "ad hoc", however they said it's possible that the hosting package I'm currently using does not allow me to radically intervene on the variables (it also doesn't include root access), therefore they suggest to switch to a server package.
Now I will try to create a server locally and install phpmyadmin on my computer, to see if I could then overcome the initial issue of sending out email with SuiteCRM.
Will keep you updated.

**Comment by razdavid** [comment]
@Dillon-Brown after contacting the 1and1 support, plus some online research I understand that I need to use a VPS with root access in order to manipulate the variables of MySQL.
Meanwhile, I also searched for some alternatives and I created a database with https://www.freemysqlhosting.net/, the max_allowed_package in this case is 16M, and I don't have the privileges to edit that. I reinstalled SuiteCRM and I used the new database for the installation. 
Unfortunately the behavior of SuiteCRM is the same when I try to send a test email, however the .log file does not include any mention to MySQL in this case:

`Fri Aug 17 17:33:44 2018 [26596][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
Fri Aug 17 17:34:03 2018 [28053][1][FATAL] log call at: modules/EmailMan/tpls/config.tpl:444 - styleChecked is not set
Fri Aug 17 17:39:15 2018 [29678][1][FATAL] SugarPHPMailer encountered an error: An outgoing mail server is not configured to send emails. Please configure an outgoing mail server or select an outgoing mail server for the mail account that you are using in Settings >> Mail Account.
Fri Aug 17 17:39:15 2018 [29678][1][FATAL] SugarPHPMailer encountered an error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Fri Aug 17 17:39:15 2018 [29678][1][FATAL] SugarPHPMailer encountered an error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Fri Aug 17 17:39:41 2018 [34937][1][FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set
Fri Aug 17 17:39:43 2018 [35003][1][FATAL] log call at: modules/EmailMan/tpls/config.tpl:444 - styleChecked is not set`

Do you have an idea what the issue might be and how I could solve it?

**Comment by willrennie** [comment]
Closing this issue as it is specific to hosting/configuration and not a core SuiteCRM bug. I would suggest you take this one over to the forums and request further assistance from the community there.

**Comment by fredericgrither** [comment]
Hello,

I encounter the same issue. My request to 1and1 support answers that shared servers are unable to send emails.
The technician said the solution is to use PHP mailer instead of SMTP server or rent a dedicated server instead of shared one.
