### ISSUE TITLE
7.10.7 every Outbound Mail has FromName = "Root User" 

### ISSUE THREAD

**Issue by xanthos84** [salesagility/SuiteCRM#6249]
#### Issue

Every setup outbound mail sends the mail as "Root User",
outbound mail adress is correct. but the name is always "Root User" as defined in
\include\phpmailer\class.phpmailer.php
code line #79

`public $FromName = 'Root User';`

#### Expected Behavior
The $FromName variable should be overwritten by the defined Name in the application email settings like the From Mail Adress (which is correct).

#### Actual Behavior
If you do a test send mail out - the 
$FromName  gets overwritten correctly, so the Name is correct.
But if you do send out a mail from within the application, like from a contact person (click on the email) - the $FromName gets not overwritten.

#### Possible Fix
dont know.

#### Steps to Reproduce
Setup Outbound Email with SMTP
Create a Contact with an Email Adress
Click on the Email adress so the email send form gets opened.
Fill out everything (From: field is correct with email&name)
Receive the email, and see the Name is "Root User"

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome/opera
* Environment name and version (e.g. MySQL, PHP 7): Bitnami

**Comment by Mausino** [comment]
@xanthos84 same issue also in our instance 7.10.7

**Comment by Dillon-Brown** [comment]
Fix here: #6015
