### ISSUE TITLE
Default values do not show on fields

### ISSUE THREAD

**Issue by robfunk** [salesagility/SuiteCRM#6250]
When creating new fields in Studio, there is an option of adding a 'default value', however the field just shows up as blank, the default value does not appear on the layout.

I am using the latest version of Suite CRM.

**Comment by serhiisamko091184** [comment]
Hello @javitoron,

I would like to clarify as I'm using the last version of SuiteRM 7 (7.14.3), I'm afraid I can't replicate the issue. 
Is this still the issue on your end? 

Regards,
Serhii

**Comment by robfunk** [comment]
This was 6 years ago, I dont use it anymore

**Comment by serhiisamko091184** [comment]
Thanks for your quick reply, I'm closing this as fixed. 

Thanks a lot! 

Regards,
Serhii
