### ISSUE TITLE
Seemingly redundant code logs: [FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set

### ISSUE THREAD

**Issue by vladimirpekez** [salesagility/SuiteCRM#6255]
#### Issue
Entering Administration causes following fatal line to be logged:
[FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set

#### Expected Behavior
There should be no fatal errors,

#### Possible Fix
I see MY_FRAME is not used anywhere throughout codebase, so lines 51-56 in modules/Administration/index.tpl should be removed:

{if isset($MY_FRAME)}
    {$MY_FRAME}
{else}
    {log msg="MY_FRAME is not set"}
{/if}

#### Steps to Reproduce
1. Login as admin
2. Go to Administration
3. Check sugarcrm log

#### Your Environment
* SuiteCRM Version used: 7.10.7.
* Browser name and version Latest Chrome Version 64-bit
* Environment name and version PHP 7.1
* Operating System and version: CentOS

**Comment by Dillon-Brown** [comment]
Fixed here #6097

**Comment by vladimirpekez** [comment]
Thanks @Dillon-Brown and hope to see it included into 7.10.x branch soon.
