### ISSUE TITLE
PHP error when editing layouts through studio

### ISSUE THREAD

**Issue by cogscape** [salesagility/SuiteCRM#6261]
#### Issue
When attempting to change the title label of a new panel through studio (Studio -> Users -> Layout -> EditView) a php error pops-up pointing to an error in one of the core files.

#### Behavior
Instead of showing a text-field to edit the title label, a php error appears and blocks further usage of the page (also cannot save the recent edits to the view).

#### Possible Fix
Issue easily fixed by adding two closed brackets '**()**' before the closing bracket of the _init_ function definition on line 80 of file _root\modules\ModuleBuilder\views\view.property.php_ (the same file towards which the php error points to).
Example of the corrected line 80:
`function init($bean = NULL, $view_object_map = Array())`

#### Steps to Reproduce

1. Open Users edit view layout through studio;
2. Drag a new panel from into the layout;
3. Click on the edit button (pencil) to change the title/label of the panel;
4. An error pop-up should appear.

#### Context
I assume this would be a low-priority bug as it only affects graphical users and can easily be handled or
bypassed by a programmer of any level (text editors automatically point the syntax error). Furthermore, it does not affect the creation of the label itself, yet only editing it's title label.

#### Your Environment

* SuiteCRM version 7.10.7
* Firefox Quantum 61.0.2 (64-bit).
* Running on PHP version 7 with MySQL on top of Apache.
* Operating system: Windows 10 (64-bit).

**Comment by pgorod** [comment]
Maybe something is wrong with your installation.

On my 7.10.7 (running on Ubuntu) your steps to reproduce don't give any error, it works well. 

And the line you mention seems to be already corrected in 7.10.7:

https://github.com/salesagility/SuiteCRM/blob/master/modules/ModuleBuilder/views/view.property.php#L80

**Comment by cogscape** [comment]
Yes, you are right - the problem was with my own installation. SuiteCRM did not have the appropriate write permissions in C:/Program Files(x86) and therefore resulted in various errors, all traced to semantic issues like the one above, however most of the CRM worked properly. 
All of this was solved by moving SuiteCRM to the root folder of a freshly installed XAMP, this time on the non-restricted D:/ partition followed by a 'Quick repair and rebuild' and rebuilding the javascripts.

I still do not know how write permissions can affect the source code of files other than those in cache and the ones created dynamically, however I suppose this issue should be referenced somewhere so as to help users who encounter a similar issue.

**Comment by pgorod** [comment]
I don't know if that is the cause of these problems, but I do know that Windows does some funny things with its "special directories". So if a program writes to "Program Files", but it is a 32-bit program, it goes into "Program Files (x86)". Similar things happen in the registry with "WOW3264" nodes, etc. This might confuse some of the code. 

Anyway, it's much less tested. If SuiteCRM is not as well tested in Windows as it is in Linux, much more so if it is running in a special directory like "Program Files" which is not where you're supposed to put web apps.
