### ISSUE TITLE
 The image is broken --> See screenshot

### ISSUE THREAD

**Issue by trunghieu321** [salesagility/SuiteCRM#6264]
#### Context
This is a bug core on SuiteCRM version 10.4, It related to module Alerts, Please check again.

#### Your Environment

* SuiteCRM Version used: 10.4
 This is a image bug of core --> See screenshot
![screenshot_1](https://user-images.githubusercontent.com/23078282/44638332-868dab80-a9e0-11e8-8a6e-abcb3786f97e.png)
- The image is broken --> See screenshot
![screenshot_2](https://user-images.githubusercontent.com/23078282/44638333-868dab80-a9e0-11e8-8b33-6aee04f6a036.png)

* Browser Chrome
* Environment name and version (e.g. MySQL, PHP 7.1):

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.10 version and advise upgrading to that if you still find this an issue.

**Comment by connorshea** [comment]
@cameronblaikie I'm pretty sure this issue still exists. I'm on 7.10.18 and the issue still occurs

<img width="156" alt="Screen Shot 2019-07-29 at 4 18 08 PM" src="https://user-images.githubusercontent.com/2977353/62086704-78619400-b21c-11e9-863f-53dca664ccac.png">

<img width="618" alt="Screen Shot 2019-07-29 at 4 18 55 PM" src="https://user-images.githubusercontent.com/2977353/62086755-97f8bc80-b21c-11e9-9c28-bf28ab5f1af1.png">

As of the latest commit on hotfix-7.10.x, the line shown in this issue still has an `s` appended to the module name:

https://github.com/salesagility/SuiteCRM/blob/a11f1504e463c38797727dfce7fd67788985b1d6/modules/Alerts/templates/default.tpl#L25

As far as I can tell, all target modules seem to be plural already, so this shouldn't be necessary (and it also doesn't take into consideration the various English words which don't pluralize simply with an `s` appended, e.g. millenium => millenia or deer => deer).

**Comment by connorshea** [comment]
It should probably return a span with an icon class based on the module name, like `<span class="suitepicon suitepicon-module-leads"></span>`
