### ISSUE TITLE
YUI mixed content for https issue #719 not fixed

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#6271]
https://github.com/salesagility/SuiteCRM/issues/719 seems to be not fixed.
For me it looks like https://github.com/salesagility/SuiteCRM/commit/6b8300989ddab3cd5e0900c63dc4273251f73cce was never merged.

**Comment by Dillon-Brown** [comment]
Have you checked that you have the code in this PR? #5523

**Comment by gunnicom** [comment]
Ah ok. I will check that. Now i saw that this was my sugar instance that is not updated to an actual version. Sorry, i close this for now.
