### ISSUE TITLE
PT-BR language don't work

### ISSUE THREAD

**Issue by darouca** [salesagility/SuiteCRM#6279]
Hi,

I installed SuiteCRM 7.10. It worked all
But, when I install PT-BR language, the system don't work more.

I follow this link:
https://sites.google.com/site/translatingsuitecrm/faq/install-new-languages

What can I do?

Tks.

**Comment by Dillon-Brown** [comment]
Hi @darouca, this looks like an issue with the language pack itself and not SuiteCRM. You can fix it manually by going to line 258 and adding in the missing comma after 'LBL_CREATE' => 'Create'

Otherwise you will need to wait until its fixed on the translators side @horus68

**Comment by horus68** [comment]
done!

**Comment by darouca** [comment]
Hi.

Thank you so much @Dillon-Brown and @horus68 .
The new version of the translation work very well.

Tks.
