### ISSUE TITLE
Master branch Readme file needs to be updated

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6283]
#### Issue

The readme.md master file needs to be updated with the fixes done in the hotfix branch.
This because its content is the info visible to users when entering SuiteCRM Git page and there is a broken URL in the master branch but already fixed in the hotfix branch.

So please merge 
https://github.com/salesagility/SuiteCRM/blob/hotfix/README.md
into
https://github.com/salesagility/SuiteCRM/blob/master/README.md
... even if the master branch is not planed to be changed so soon!

#### Actual Behavior
Error in the link to "Roadmap" in
"View the Community Roadmap here and get involved"

#### Possible Fix

Merge the changes from Hotfix
https://github.com/salesagility/SuiteCRM/blob/hotfix/README.md

**Comment by Dillon-Brown** [comment]
Issue resolved, thanks!
