### ISSUE TITLE
Indentation spaces in language values - 'Install' language file

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6286]
#### Issue

the file /install/language/en_us.lang.php as some language strings using too many spaces for text indentation in values with html code. Some lines has 23 spaces in a row (some even in the end of the line!).

#### Context

For translators that is not a proper setting,as it makes hard to have a proper translation in Crowdin (it requires the same amount of spaces in translation as in source string).
So the strings values should be cleaned up a little bit, with more compact display

#### Actual Behavior

see this strings:
- REQUIRED_SYS_COMP_MSG
- REQUIRED_SYS_CHK_MSG
- REQUIRED_INSTALLTYPE_MSG
- LBL_SESSION_ERR_DESCRIPTION

example:
REQUIRED_SYS_CHK_MSG
https://github.com/salesagility/SuiteCRM/blob/207f5f65d260b842b8883e591783608ec758b28d/install/language/en_us.lang.php#L333-L350

example in Crowdin:
![2018-09-06 09_56_36-microsoft edge](https://user-images.githubusercontent.com/3055443/45146674-3d491300-b1bb-11e8-9513-cd4c8b6a5325.png)

#### Possible Fix

clean up indentation with fewer spaces.

#### Your Environment

* SuiteCRM Version used: all versions

**Comment by asha15** [comment]
@horus68  shall i work on this?

**Comment by pgorod** [comment]
@asha15 yes, thank you!

**Comment by horus68** [comment]
@asha15 go for it, please!

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
