### ISSUE TITLE
sort not working on accounts / SuiteCRM 7.10.7

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#6288]
Sort and pagination did not work on accounts module. No errors registered on log.

From some time ago (I think since 7.10.7 update, or after it) accounts module does not work correctly. I cannot sort results or paginate.

I have one custom field I think it's the problem. Field is named "brand_name_c". I've work correctly with this field added, but, at the moment I've tried to sort from this field these error appears:

(note: Field is added on list view as Available).

When I enter on Accounts: Apparently, list has been ordered by brand_name_c DESC.
When I try to select any other field to order, or try to go to next page. List is apparently ordered by brand_name_c ASC.
Really, list is not ordered on any case. Showed rows didn't have any information on this field, even when I know I have some rows with this field populated (checking on database, Accounts have 532 regs and I have populated 175 brand_name_c).

As a check:
  All register on accounts table are on accounts_cstm too. On the affected field, I have 175 registers with value, all others are null.

#### Context
I cannot work with accounts if I can't paginate.

#### Possible workaround
If I can reset my user to don't sort by this field, I can restore working. 

#### Your Environment
Bug has been tested on multiple navigators (internet explorer, edge, chrome, safari, firefox)

**Comment by ErMaqui** [comment]
After test with other user, the problem didn't appear. Problem are related with the order I think.

**Comment by pgorod** [comment]
@Dillon-Brown I suggest closing this one in favor of #6298 which has more complete technical information.

@ErMaqui I thank you for reporting this (you were the first one, the other Issue came later). Please follow this discussion in Issue #6298.
