### ISSUE TITLE
In latest 7.10.7 version Pdf is not being generated from invoices and quotes

### ISSUE THREAD

**Issue by MMuzaffar** [salesagility/SuiteCRM#6289]
After upgradation from 7.9.4 to 7.10.7 pdf generation stopped working from invoice and quote modules. Although it was working fine in old 7.9.4 version.
In latest release 7.10.7,  create a quote/invoice and create a quote sample/ invoice sample pdf template and try to generate pdf from their detail view actions buttons it takes long time and after that html error 500 or something like this shows.

**Comment by pgorod** [comment]
This is the forum thread: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/20332-upgrade-to-7-10-7-pdf-gerneration-error

Relevant information from there:

Commenting out these three lines in `modules\AOS_PDF_Templates/generatePdf.php` seems to solve the issue:
```
if (!isset($_REQUEST) || empty($_REQUEST) || !isset($_REQUEST) || empty($_REQUEST)) {
die('Error retrieving record. This record may be deleted or you may not be authorized to view it.');
}
// $state = new \SuiteCRM\StateSaver();
// $state->pushErrorLevel();
error_reporting(0);
require_once('modules/AOS_PDF_Templates/PDF_Lib/mpdf.php');
require_once('modules/AOS_PDF_Templates/templateParser.php');
require_once('modules/AOS_PDF_Templates/sendEmail.php');
require_once('modules/AOS_PDF_Templates/AOS_PDF_Templates.php');
// $state->popErrorLevel();

global $mod_strings, $sugar_config;
```

@MMuzaffar, can you please tell us your Operating system and PHP version? Thanks!

@gymad you might want to take a look at this.

**Comment by MMuzaffar** [comment]
@pgorod Yes sure.
I am using 64bit WAMP Server in my local machine. I have upgraded my PHP version from 5.6.25 to 7.0.10. So I am using PHP 7.0.10 right now.
Thanks

**Comment by Dillon-Brown** [comment]
Hi @MMuzaffar, so far i'm unable to replicate this. Do you see anything in your SuiteCRM or PHP error logs? I would also potentially try removing the slash in $state = new \SuiteCRM\StateSaver(); to $state = new SuiteCRM\StateSaver();

**Comment by MMuzaffar** [comment]
Hi @Dillon-Brown 
This line is causing problem.
$state->popErrorLevel();
This is the error i am getting.
Fatal error:  Maximum execution time of 120 seconds exceeded in E:\wamp64\www\SuiteERP1\modules\AOS_PDF_Templates\templateParser.php on line 132

[11-Sep-2018 14:25:41 UTC] PHP Stack trace:

[11-Sep-2018 14:25:41 UTC] PHP   1. {main}() E:\wamp64\www\SuiteERP1\index.php:0

[11-Sep-2018 14:25:41 UTC] PHP   2. SugarApplication->execute() E:\wamp64\www\SuiteERP1\index.php:52

[11-Sep-2018 14:25:41 UTC] PHP   3. SugarController->execute() E:\wamp64\www\SuiteERP1\include\MVC\SugarApplication.php:109

[11-Sep-2018 14:25:41 UTC] PHP   4. SugarController->process() E:\wamp64\www\SuiteERP1\include\MVC\Controller\SugarController.php:373

[11-Sep-2018 14:25:41 UTC] PHP   5. SugarController->handleEntryPoint() E:\wamp64\www\SuiteERP1\include\MVC\Controller\SugarController.php:465

[11-Sep-2018 14:25:41 UTC] PHP   6. require_once() E:\wamp64\www\SuiteERP1\include\MVC\Controller\SugarController.php:1014

[11-Sep-2018 14:25:41 UTC] PHP   7. templateParser::parse_template() E:\wamp64\www\SuiteERP1\modules\AOS_PDF_Templates\generatePdf.php:135

[11-Sep-2018 14:25:41 UTC] PHP   8. templateParser::parse_template_bean() E:\wamp64\www\SuiteERP1\modules\AOS_PDF_Templates\templateParser.php:44  
-----------------------------------------------------------------------------------------------------------
If I remove this line:
$state->popErrorLevel();
pdf generating fine.

**Comment by gymad** [comment]
Hi @MMuzaffar I wandering how long does it take to generate the pdf for you if you remove the error reporting. Technically It should not have to change the behavior, the original issue is "Fatal error: Maximum execution time of 120 seconds exceeded", If you switch off the error reporting level and using only the `error_reporting(0);` the only different is you don't see it in the log. Also question how difficult is your pdf?

**Comment by MMuzaffar** [comment]
Hi @pgorod,
If I remove this line:
$state->popErrorLevel();
pdf file generates in few seconds. 
With that line file never generate.
pdf is simple default quote/ invoice pdf.

**Comment by pgorod** [comment]
@MMuzaffar does this still happen in the latest SuiteCRM version, or can we close the issue?
