### ISSUE TITLE
undefined variable in InboundEmail

### ISSUE THREAD

**Issue by lserni** [salesagility/SuiteCRM#6290]
https://github.com/salesagility/SuiteCRM/blob/15c094c4bca49a4ea75daa37cbc91336552c4dfa/modules/InboundEmail/InboundEmail.php#L6121

The variable "$inboundEmail" should perhaps be "$this" ?

Plus, but I might well be mistaken, the two public variables

   public $InboundEmailCachePath;
    public $InboundEmailCacheFile = 'InboundEmail.cache.php'

seem not to be in use anywhere. The first is assigned in the constructor, but never used?

**Comment by Dillon-Brown** [comment]
Fixed here: https://github.com/salesagility/SuiteCRM/commit/d83d8fc5ddedd9595c0d1eb543a641b43a63a2f0
