### ISSUE TITLE
Wrong replacement to work around Slim\\Uri::createFromEnvironment() ?

### ISSUE THREAD

**Issue by lserni** [salesagility/SuiteCRM#6293]
https://github.com/salesagility/SuiteCRM/blob/15c094c4bca49a4ea75daa37cbc91336552c4dfa/lib/API/core/app.php#L56

The line above seems to be a kludge to ensure that the Uri component of the Slim module, used by OAuthServer, used by the API v8 interface, correctly decode the request path (for example "oauth/access_token").

The point where this issue comes out is in the vendor\slim\slim\Slim\Http\Uri.php, line 203:

        // parse_url() requires a full URL. As we don't extract the domain name or scheme,
        // we use a stand-in.
        $requestUri = parse_url('http://example.com' . $env->get('REQUEST_URI'), PHP_URL_PATH);

I have encountered a problem with one hosting service where $_SERVER['PHP_SELF']  during an Apache rewrite was *not* populated with the correct information, but the script, after the redirect, saw itself (which is after all defensible, if you think about it).

As far as I can understand the RFCs and the PHP documentation, the path information seeked by SuiteCRM API *SHOULD* always be present in PATH_INFO, while the naked file path SHOULD always be supplied in SCRIPT_FILENAME in full form.

Therefore, the modified syntax below should work as before when Apache goes out of its way to supply the path information, and should work correctly when it doesn't.

    $_SERVER['REQUEST_URI'] = substr($_SERVER['SCRIPT_FILENAME'], strlen($_SERVER['DOCUMENT_ROOT'])-1) . $_SERVER['PATH_INFO'];
    // $_SERVER['REQUEST_URI'] = $_SERVER['PHP_SELF'];

Another, better way to do this would be to change the checking logic in lib\API\OAuth2\Middleware\ResourceServer.php at line 81, and possibly elsewhere, but that's much more work:

    if (!in_array($request->getUri()->getPath(), self::$ROUTES_EXEMPT_FROM_AUTH)) {

**Comment by samus-aran** [comment]
@lserni v8 is deprecated so please test the later V8 if this is still an issue. If it is then please open a new ticket and provide steps on how to reproduce so we can investigate. Thanks.
