### ISSUE TITLE
Unable to change mail_sendtype to sendmail?

### ISSUE THREAD

**Issue by mphilipps** [salesagility/SuiteCRM#6297]
hi
#### Issue
I just installed 7.8.20 and started configuring it. While there are plenty of email related settings on administration page I can't find one to change the mail_sendtype. Given that there is a field for it in the database, there are several bug reports regarding the use of sendmail and explicit checks on whether it is SMTP or not.

#### Expected Behavior
I would like for suite CRM to use the local mailserver to send it's mails. Just like every other application. It should have to use it's own SMTP implementation and with that be dependant on whether the mail server is running at the moment or not.

#### Actual Behavior
The configuration page always assumes that you want to use SMTP.

#### Context
I am trying configure suitecrm to sendout mails when necessary. 

#### Your Environment

* SuiteCRM Version used: 7.8.20 (LTS)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 60.1.0esr (64bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, php7
* Operating System and version (e.g Ubuntu 16.04): Debian Stretch

**Comment by pgorod** [comment]
Thanks @mphilipps, I took up your suggestion [here](https://github.com/salesagility/SuiteDocs/issues/138). If you can give us a hand writing the Documentation yourself, even if it's just a start, feel free to edit the Docs site.

You can close this Issue here if that's ok with you. Thanks.
