### ISSUE TITLE
Not all imported targets are added to target list for large imports for 7.10.7

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6300]
#### Issue
Same issue related to #3534
I tried it with [nightly demo](https://nightly.suiteondemand.com) site but same result.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 62 - 64 bit
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by cameronblaikie** [comment]
hi @dursuntosun  could you provide logs as that was closed due to inactivity /unable to replicate. if you could replicate it then could you please provide steps in your template so we can try replicate the issue. Cheers,

**Comment by cameronblaikie** [comment]
@dursuntosun  Could you check your logs and report any errors when the import failed too.

**Comment by dursuntosun** [comment]
My CRM is new installation and latest version.
My log is;
`Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-0 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://import/dupes_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://import/dupesdisplay_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://import/errorrecords_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://import/errorrecordsonly_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-1 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-2 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-3 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-4 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-5 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-6 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-7 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-8 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-9 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-10 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-11 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-12 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-13 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-14 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-15 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-16 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-17 cannot be touched
Tue Sep 25 10:36:01 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://IMPORT_Prospect_da3eef35-49a1-d2f7-c023-5ba4d03fc82f-18 cannot be touched
Tue Sep 25 10:36:35 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][FATAL] Caught error: stat(): stat failed for upload/import/status_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv
Tue Sep 25 10:36:35 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Tue Sep 25 10:36:35 2018 [27524][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] File upload://import/status_da3eef35-49a1-d2f7-c023-5ba4d03fc82f.csv cannot be touched
Tue Sep 25 11:07:42 2018 [27525][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] Unable to get proper side for link assigned_user_link
Tue Sep 25 11:07:42 2018 [27525][da3eef35-49a1-d2f7-c023-5ba4d03fc82f][ERROR] Unable to get proper side for link assigned_user_link`

**Comment by dursuntosun** [comment]
These are my steps;
1)
![screenshot_1](https://user-images.githubusercontent.com/22373035/46001350-bb5e5280-c0b3-11e8-9a51-9e58efeff466.png)
2)
![screenshot_2](https://user-images.githubusercontent.com/22373035/46001368-c9ac6e80-c0b3-11e8-8903-62ea39810fef.png)
3)
![screenshot_3](https://user-images.githubusercontent.com/22373035/46001381-ce712280-c0b3-11e8-9543-33a5d29e096e.png)
4)
![screenshot_4](https://user-images.githubusercontent.com/22373035/46001390-d29d4000-c0b3-11e8-9d95-e0fbcb0ce2d8.png)
5)
![screenshot_5](https://user-images.githubusercontent.com/22373035/46001402-d761f400-c0b3-11e8-8623-2cb540b7332b.png)
6)
![screenshot_6](https://user-images.githubusercontent.com/22373035/46001412-dcbf3e80-c0b3-11e8-9caf-a662737791de.png)

**Comment by dursuntosun** [comment]
After changing value of **max_input_vars** in php.ini file, my problem is solved. Thank you.
