### ISSUE TITLE
Reports - "Add to target list" doesn't work when "Group" is checked for a field

### ISSUE THREAD

**Issue by satnav** [salesagility/SuiteCRM#6308]
#### Issue
I have tried making a report with multiple fields. If at least one of those fields has the "Group" box checked, then when you click "Add to target list" and select a target list, it doesn't get populated. There is no feedback as to why it doesn't get populated.

Here is a link to the forum discussion if you are interested: https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/20299-adding-reports-to-target-list-not-working

#### Expected Behavior
I'm not sure if this is the expected behaviour, as I'm not exactly sure what "Group" does, but ideally the report should add to the target list with group checked or it should give the user feedback as to why this isn't possible.

#### Actual Behavior
Once you select a target list and navigate to the target list detail view, there are no records present in any sub-panel. (For example, if you add a contacts report to a target list, there is nothing present under the contacts sub-panel for that target list, assuming there was nothing there in the first place.)

In the error.log there is this line repeated multiple times which appeared around the same time:
> PHP Warning: Illegal string offset '' in /var/www/html/suitecrm/modules/AOW_WorkFlow/aow_utils.php on line 517, referer: http://<my domain>/suitecrm/index.php?action=ajaxui

However I doubt this is related to the issue.

#### Possible Fix
If you untick the Group checkbox for all fields, the report populates the target list properly

#### Steps to Reproduce
I was able to reproduce this on the nightly demo: https://nightly.suiteondemand.com
1. Create any kind of report
2. Add a couple of fields to the report (make sure there are actually results for the report)
3. Check the "Group" checkbox for at least one of the fields
4. Click Save
5. Click Actions
6. Click Add to Target List
7. Create a new target list (you can use an existing one but it will be less confusing if you use a new one)
8. Click on the target list you just created (and the popup should disappear)
9. Navigate to Targets - Lists
10. Click on the target list you added the report to
11. Expand the sub-panel relating to the report type, and there should be nothing there

#### Context
It was a bit frustrating not knowing why it wasn't working, especially with no feedback. If someone has Group checked on a report, and they trust that it's being added to a target list properly, that might end up being a lot of work they have to re-do. I'm thinking this might be a medium priority?

#### Your Environment
* SuiteCRM Version used: 7.10.7
* Browser name and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Environment name and version: MySQL, PHP 7.2
* Operating System and version: Ubuntu 16.04

**Comment by ChangezKhan** [comment]
This issue is somewhat similar to #4123. Kindly check this issue.
