### ISSUE TITLE
Cannot create contact via the Archiving email sub panel

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#631]
If you navigate to an account -> history sub panel -> archive email -> create a contact via the "Select button".(Note the account information should be filled in)

You will not be able to save/ create the contact even if the account information is filled. The system will tell you that it cannot match to an Account.

**Comment by samus-aran** [comment]
There is no account_id being passed to the vardefs as the request only includes the account_name.  Within the PopUpQuickCreate needs to include a reference to account_id using the supplied account_name.

**Comment by samus-aran** [comment]
This is fixed (awaiting assignment) - passing the account_id to the QuickCreate form via Popup parameters within Email module.

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4)and it appears this has been fixed in previous commit.
