### ISSUE TITLE
Empty collapsed activities/history subpanels is always shown as a subpanels with some records

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#6320]
Subj.

1. Open users profile and enable Show collapsed subpanel hint option on layout options tab
2. Create any record with activities or history subpanel and open it in Detail View
3. Go to activities or history subpanel and check the result

#### Your Environment

    * SuiteCRM Version used: 7.10.8, clean installation with demo db
    * Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF latest, IE11
    * Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1ubuntu4.25, MySQL 5.5.61
    * Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by Mausino** [comment]
@Dillon-Brown should it be added to milestone 7.10.10 ??? as we see that was merged and will in next release.

**Comment by Dillon-Brown** [comment]
@Mausino Hmm, from what I can see this one should have already been closed since it was included in the 7.10.9 release. I'm not sure why GitHub didn't pick that up.

**Comment by Dillon-Brown** [comment]
Ah nevermind, I was looking at #6310, yes this should be in 7.10.10
