### ISSUE TITLE
Quick radius map + Geocode test issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#6326]
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18315-google-api-key-maps#62368

We have same issue as rbug user on forum. 
The maps is showing correctly but geocoding isn't working
If we use insted Berlin, Germany the GPS like 52.518214 13.461785 we got same issue... 

![2018-09-19_1304](https://user-images.githubusercontent.com/5773777/45749671-a9d8fe80-bc0c-11e8-84da-5148d60d1829.png)

![attachment1](https://user-images.githubusercontent.com/5773777/45749596-67172680-bc0c-11e8-9722-51b379e0de63.JPG)

Our company live on maps... they are key to work with data... this problems with geocoding paralyze our company :(

#### Actual Behavior

Geocoding isn't working correctly

#### Steps to Reproduce

1. Maps -> Quick Radius Map
2. Address
3. Choose moduel
4. See the results on Map

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version: Chrome 56.x
* Environment name and version MySQL 5.6, PHP 7.2
* Operating System and version Win 10

**Comment by Dillon-Brown** [comment]
Hi @Mausino, I've pushed a fix to #6333, would you be able to confirm if this resolves the issue for you?

**Comment by Mausino** [comment]
@Dillon-Brown  thank so much :) in our case it solves the problem

**Comment by Mausino** [comment]
Here small info if you're starting using google maps as company 🥇 

![2018-09-24_2355](https://user-images.githubusercontent.com/5773777/45981860-ca62e780-c056-11e8-9ba5-90896cd95bd5.png)
