### ISSUE TITLE
Broken UI after 7.10.9 upgrade

### ISSUE THREAD

**Issue by maarisk** [salesagility/SuiteCRM#6331]
#### Issue
During upgrade screen becomes like attached. After upgrade has been completed, browser refresh and repairs do not help.

#### Expected Behavior
No UI issues

#### Actual Behavior
<img width="1575" alt="screenshot 2018-09-19 at 21 30 32" src="https://user-images.githubusercontent.com/15897145/45773800-f1cf4400-bc53-11e8-9116-9be172be64f1.png">

#### Steps to Reproduce

1. SuiteCRM version 7.10.7
2. Download and upload in Upgrade Wizard version 7.10.9
3. Run upgrade wizard

#### Your Environment

* SuiteCRM Version used: 7.10.7 to 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62 (64bit) & Safari 12.0 (64bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.9.x, PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): macOS 10.13.4

**Comment by dursuntosun** [comment]
Did you check permissions?

**Comment by criterion9** [comment]
I had a similar issue a couple upgrades ago and found that doing a fresh unzip exactly matching the version number into the themes directory cleared up all the UI issues.

**Comment by maarisk** [comment]
Environment restore from backup and upgrade once again afterwards worked as expected.
