### ISSUE TITLE
ChangePassword.php - syntax error missing curly braces

### ISSUE THREAD

**Issue by rainolf** [salesagility/SuiteCRM#6338]
#### Issue
in ChangePassword.php(modules/Users/ChangePassword.php) currently the code at line 70:
  if(empty($ut))
        SugarApplication::redirect('index.php?module=Users&action=Wizard');
    }

#### Expected Behavior
Should be:
  if(empty($ut)) **{**
        SugarApplication::redirect('index.php?module=Users&action=Wizard');
    }

#### Actual Behavior
suitecrm.log reports:
PHP ParseError:  syntax error, unexpected '}'
No way to load the page correctly

#### Possible Fix
  if(empty($ut)) {
        SugarApplication::redirect('index.php?module=Users&action=Wizard');
    }

#### Your Environment

* SuiteCRM Version used: 7.10.8 and 7.10.9

**Comment by pgorod** [comment]
@rainolf do you want to do a Pull Request?

For simple edits, this method is very easy and doesn't require a local git repo, or any git knowledge:

https://help.github.com/articles/editing-files-in-another-user-s-repository/

Just navigate to the file in our repo, in the `hotfix` branch, and click the "pencil" icon to edit it:
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Users/ChangePassword.php
