### ISSUE TITLE
"Users may send as this account's identity: " settings check box selection is not saved.

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6342]
#### Issue
When i select "Users may send as this account's identity: "  check box, it does not saved.

#### Expected Behavior
It should be saved.

#### Steps to Reproduce

1. Open Admin Page
2. Open Email Settings Page
3. Select "Users may send as this account's identity: " check box
4. Save
5. Look at again this settings.

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
Hi @dursuntosun Wasn't able to replicate this issue on 7.10.10. Please ask to re-open if still an issue and if so please supply either debug logs (suitecrm.log) or PHP log in case there is anything else at play here.
