### ISSUE TITLE
Enum and multienum fields are not translated in campaigns

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#6345]
Enum and multienum fields of Contacts/Leads/Accounts are not translated in campaigns

This issue was solved in the past but was reintroduced now that class EmailTemplateParser is used instead of parse_email_template

#### Issue

On a side note, even though I didn't test it, it is likely that dates will be displayed in database format/

#### Expected Behavior

enum fields should be translated using $app_list_strings

#### Actual Behavior

The field value in the database is displayed

#### Possible Fix

Fix EmailTemplateParser/parseVariables
... or also add parse_email_template after parseVariables call in EmailMan.php

#### Steps to Reproduce

1- Change to another language, or, in english, go to Dropdown editor and change label of Mr. to Mister in salutation_dom,
2- create a template and insert contact salutation
3- In email sent by a campaign using that template, you will see Mr. and not Mister or whatever translation you used.

#### Your Environment

* SuiteCRM Version used: 7.10.7, 7.10.8, 7.10.9, 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): not significant
* Environment name and version (e.g. MySQL, PHP 7):not significant
* Operating System and version (e.g Ubuntu 16.04):not significant

**Comment by mbennoer** [comment]
Same bug is already discussed here: #5771
