### ISSUE TITLE
From sender UFT-8 issue of special characters in compose email

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#6353]
#### Issue

If you compose email and you're choosing from name, you will see if you have special characters the issue in some letters.

![2018-09-25_1436](https://user-images.githubusercontent.com/5773777/46014999-5ade0e00-c0d1-11e8-883e-fc6c98949415.png)

#### Expected Behavior

Shoud be there Lucia Bodnárová

#### Actual Behavior

There is Lucia Bodn?rov?

#### Steps to Reproduce

1. Create name of email address with special characters

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and Version 69.0.3497.100 (Official Build) (64-bit) Chrome
* Environment name and version MySQL 5.6 PHP 7.2
* Operating System and version Win 10 Home

**Comment by dursuntosun** [comment]
#6340

**Comment by Mausino** [comment]
@dursuntosun thanks.. closing the issue while it's duplicate
