### ISSUE TITLE
Subpanels are not pulling related data

### ISSUE THREAD

**Issue by ismailzafar** [salesagility/SuiteCRM#6355]
#### Issue

Tasks module has 1 to many relation with activities and notes module. Subpanels are visible in taskedit view but I am not able to select or create notes/activities in subpanles.

#### Expected Behavior

After adding or creating any item in subpanel should be shown in subpanels.

#### Actual Behavior

After clicking on saving button nothing happen.
#### Steps to Reproduce

1. Navigate to admin studio.
2.  Under tasks select relations.
3. Create tasks relation to notes and activities. It should be 1 to many.
4.  Now subpanels will be visible. Edit subpanels.
5. Edit tasks.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
Please fill in the versions in the template. Don't assume your issue is reproducible, we need to check that, and we're better off trying that using your exact versions of SuiteCRM and PHP, at least. Thanks.

**Comment by samus-aran** [comment]
Hi @ismailzafar 
I have performed the same steps as yourself and was able to add new tasks & notes to both the newly added subpanels Activities & History.

Please feel free to ask this to be re-opened with additional information i.e:
- Do you have any customisations (apart from the studio changes)
- What do your logging say? suitecrm.log or PHP error.log
