### ISSUE TITLE
duplicate record including relationships

### ISSUE THREAD

**Issue by DevTestCRM** [salesagility/SuiteCRM#6358]
while creating duplicate record the new record don't pull information/record which are related to that Record

 * SuiteCRM Version 7.9.0 Sugar Version 6.5.24 (Build 509)
* Environment name and version (e.g. MySQL, PHP 7):

**Comment by cameronblaikie** [comment]
hi @DevTestCRM could you please test it on a later version as it looks like your only on 7.9.0.
cheers,
