### ISSUE TITLE
Reports module: items in the Treeview display lang. label 

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#636]
1- Enter with your language 
2- Open Reports Module / Create a report (DetailView)
3- For modules choose BUGS or USERS
4- Unfold the tree view

Take a close look: 
Some items in the Treeview are displayed in English or contain lang. label 

reported at forum:
#15284 - https://suitecrm.com/forum/international-language-support/3898-language-strings-issues#15284

French language
![2015-11-10 12_48_07-000378-creer rapports suitecrm74test](https://cloud.githubusercontent.com/assets/3055443/11062794/e983e850-87a9-11e5-8a41-ad22339d7b63.png)

Russian
![reports](https://cloud.githubusercontent.com/assets/3055443/11062813/0b4156c6-87aa-11e5-80bc-83045a000f21.png)

**Comment by horus68** [comment]
Update: It also happens for the english language
See pic from the official SuiteCRm demo
![2015-12-09 21_08_15-000439-create reports suitecrm](https://cloud.githubusercontent.com/assets/3055443/11698896/0d38bd04-9eb9-11e5-8b41-194c554f51e7.png)

**Comment by horus68** [comment]
closed by mistake!

**Comment by Dillon-Brown** [comment]
Issue should now be resolved.
