### ISSUE TITLE
"Create Scheduler" broken - no Jobs to select

### ISSUE THREAD

**Issue by akarasev** [salesagility/SuiteCRM#6364]
#### Issue

It looks as a regression. In version 7.10.9, on `Create Scheduler` form `Job` select field has no options neither built-in nor custom (except for `URL` item).

#### Expected Behavior

Version 7.10.9 has a list of built-in jobs in `Job` select field on `Create Scheduler`.

#### Actual Behavior

Nothing suspicious into `suitecrm.log`, but actual `Job` select field contains only one option - `URL`.

#### Possible Fix

It seems to appear into 7.10.8 or 7.10.9 version.

#### Steps to Reproduce

1. $ s2i build https://github.com/salesagility/SuiteCRM.git --ref v7.10.9 centos/php-71-centos7 suitecrm
2. $ docker run --name mariadb -e MYSQL_USER=suitecrm -e MYSQL_PASSWORD=suitecrm -e MYSQL_DATABASE=suitecrm -e MYSQL_ROOT_PASSWORD=root -p "3306:3306" -d mariadb:10.2
3. $ docker run -d --name suitecrm -p 8080:8080 suitecrm
4. Go to http://localhost:8080/ and set up a new SuiteCRM instance (using Wizard with `suitecrm` DB)
5. Log in as administrator
6. Go to Administrator -> Admin -> Scheduler -> Create Scheduler -> click on `Job` field
7. Bug - no jobs to select.

#### Context

All of built-in schedulers seem to be work fine, but it is impossible to create a new one.

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 62.0.3202.75 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1, MariaDB 10.2
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by mserge** [comment]
Fix helped for our setup
