### ISSUE TITLE
Why /custom/** pattern should be ignored?

### ISSUE THREAD

**Issue by erop** [salesagility/SuiteCRM#6369]
https://github.com/salesagility/SuiteCRM/blob/9f621efbe855d5b74c74e9677f55db2c389b1e8e/.gitignore#L99

**Comment by Dillon-Brown** [comment]
Hi @erop, this is ignored as we don't accept custom overrides into the main project, if you are doing a custom project, you would use a different gitignore.

**Comment by erop** [comment]
OK! But this in fact confuses "external" developer. And it seems reasonable to use custom/ directory as "temporary" it needed for "internal" development and being cleaned after "temporary" phase and transferred into "main" source tree (modules/, include/, etc.)
