### ISSUE TITLE
Missing opening brace

### ISSUE THREAD

**Issue by lserni** [salesagility/SuiteCRM#6370]
https://github.com/salesagility/SuiteCRM/blob/9f621efbe855d5b74c74e9677f55db2c389b1e8e/include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php#L58

I think the above "if" line should read

     if (!$layout_def['EditView']) {

to avoid a PHP syntax error when parsing the file.

**Comment by pgorod** [comment]
Thanks @lserni but that is already fixed in one of the commits that went into `hotfix`branch:

https://github.com/salesagility/SuiteCRM/blob/hotfix/include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php#L58

You can close the Issue, this will be in the next versions. Thanks.
