### ISSUE TITLE
Unable to GET deleted records through API

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#6379]
#### Issue

The REST API does not provide a way to access soft-deleted records. 

The code sort of exists, but there's no way to access it. (see samples below)

#### Expected Behavior

If an API request has the `deleted` flag set to `1`, then deleted records should be included in the response

#### Actual Behavior

The flag is ignored and only non-deleted records are returned.

In `lib/API/v8/Library/ModulesLib.php` under the `getModuleList` function, the following code exists:
```php
protected function getModuleList(Request $req, \SugarBean $module, array $args = array())
    {
        /** @var array $page */
        $page = $req->getParam('page');

        // Order by (sorting)
        $orderBy = $this->getSorting($req);

        // Pagination (offset)
        $currentOffset = isset($page['offset']) ? (integer)$page['offset'] : -1;

        // Pagination (page limit)
        $limit = isset($page['limit']) ? (integer)$page['limit'] : -1;

        // Maximum results (-1 === Unlimited)
        $maximumResults = -1;

        // Show deleted results
        $show_deleted = 0;
        if (isset($filter['deleted'])) {
            $show_deleted = (integer)$filter['deleted'];
        }
```
Under "Show deleted results", you'll notice that the `$filter` variable is never defined. So of course the `isset` condition will always return false. 

The `$show_deleted` variable is later passed to the `get_list` function. Due to the code above, it is always false. 

#### Possible Fix

Consider adding a 'deleted' flag. In which case you would refactor to something like this:
```
if ( $req->getParam('deleted')){
   $show_deleted = (integer) $req->getParam('deleted');
}
```
Alternatively, refactor further and pull it from the `filters` parameter. 

#### Steps to Reproduce

1. Start with a Suite instance with Demo Data (or create a few records)
2. Delete a record
3. Perform a GET to the corresponding module (`/api/v8/modules/[MODULE]?deleted=1`) with the `deleted` flag set

#### Context

An external connector may need to know if a record is deleted. This can be important if two systems are trying to stay in sync. 

The functionality should either be added, or the code cleaned up.

#### Your Environment

* SuiteCRM Version used: I confirmed in 10.7, and the code appears to be the same in 10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7): LAMP with PHP 7
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Assessed :+1:
