### ISSUE TITLE
Cannot see attachments in email in suitecrm 7.10.9

### ISSUE THREAD

**Issue by mirkococco** [salesagility/SuiteCRM#6384]
#### Issue
In detailview of the email I cannot see the attachment 

#### Expected Behavior
see the attachment belonging to the email

#### Actual Behavior
the attachment icon is shown in the listview but not in the email 

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by mirkococco** [comment]
Thanks for your reply Pavitha-selvam, I took a look at the subpannels and I've noticed that there is no attachment subpannel in the email, instead I see 2 invoice subpannels, I have no idea why. Is it possible to replace this or add a new attachment subpannel? Thanks again. Mirko

**Comment by pavithra-selvam** [comment]
can you send us any screenshot, it will very helpful to refer this.

**Comment by mirkococco** [comment]
<img width="1040" alt="screen shot 2018-10-08 at 11 44 00" src="https://user-images.githubusercontent.com/26064789/46602422-72b18b00-caf0-11e8-8a5a-ea05c7eadb75.png">
I's Dutch, facturen means ivoices and this is of course the subpannel page of emails in studio 
regards
Mirko

**Comment by mirkococco** [comment]
<img width="542" alt="screen shot 2018-10-08 at 11 54 09" src="https://user-images.githubusercontent.com/26064789/46602576-e3f13e00-caf0-11e8-886e-a8d2e19d779d.png">
I see the label in the field page (has attachments) but it does not appear in the subpannels

**Comment by mirkococco** [comment]
<img width="1026" alt="screen shot 2018-10-08 at 12 00 50" src="https://user-images.githubusercontent.com/26064789/46602899-d7211a00-caf1-11e8-8da6-62839b965d2a.png">
This is what I see in relations but I cannot modify the fields

**Comment by pgorod** [comment]
Can you try logging in using the default English language, to see if the problem remains the same?

**Comment by mirkococco** [comment]
The problem remains the same in both languages, is it an idea to make a new subpannel to see if that can work as a work around?

**Comment by mirkococco** [comment]
tried to create a new relation... doesn't seem to work :-(

**Comment by mirkococco** [comment]
Still no solution for this problem?

**Comment by samus-aran** [comment]
Hi there, my concern is that you are missing alot of other relationships / subpanels in your Studio > Emails > subpanels (see my attached). I believe there is some customisations at work here as as default you don't have a relationship between emails and invoices. I would suggest moving this to the forums for more specialised help.
![suitecrm](https://user-images.githubusercontent.com/4041275/49299850-a1c4f700-f4b8-11e8-8d27-6e7d9c65bd53.png)
