### ISSUE TITLE
3 modal opens when clicking on "Compose Email" under Activities subpanel

### ISSUE THREAD

**Issue by rajkumargohan** [salesagility/SuiteCRM#6386]
#### Issue
3 modal opens when clicking on "Compose Email" under Activities subpanel

#### Expected Behavior
Single modal should open

#### Actual Behavior
3 modal opens. Due to this, JS error occurs. Due to JS error, not able to relate module

#### Possible Fix
For a workaround, I have replaced the **button** variable in **display** function from Version 7.10.7
File - include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php

#### Steps to Reproduce
1. Loing to the CRM
2. Go to the Leads module
3. Click on a record and go to detail view
4. Click "Compose email" under Activites subpanel.

#### Context
Not able to send mail from detail view.

#### Your Environment
* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MySQL
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

**Comment by dursuntosun** [comment]
It is same as #6351
