### ISSUE TITLE
Amount not updating via Inline Editor module Opportunities

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#639]
When you navigate to the Opportunities ListView, click on the Inline Editor for Amount.  Enter a different amount to the current amount and click the inline save (or return).  The amount field will display the previous amount, be missing decimal points if the number was .00 and does not display the currency selected.

**Comment by samus-aran** [comment]
1.The default display field in Opportunities ListView is amount_usdollar.  When it is being saved the amount field overwrites it by default (via EditView and DetailView Inline EditView).  Need to either adjust to overwrite amount when required or change the ListView field requested.

**Comment by Dillon-Brown** [comment]
Issue has been resolved.
