### ISSUE TITLE
Changing Managing Folders Has No Effect

### ISSUE THREAD

**Issue by JuiceSantos** [salesagility/SuiteCRM#6392]
Inbound email shows "INBOX" folder despite changing it to another folder.

#### Issue
Inbound email shows "INBOX" folder despite changing it to another folder.

#### Expected Behavior
Mails shown in the folder will correspond with your selected folder.

#### Actual Behavior
Mails shown in the folder corresponds with your inbox.

#### Possible Fix
Don't know.

#### Steps to Reproduce
1. Create a new Inbound email account (used gmail)
2. Select a different monitoring folder by clicking"Select" (e.g. "Support")
3. Check inbox by clicking Emails and select the new created email.
4. Note that the shown emails does not correspond with your selected folder, but with your inbox folder.

#### Context
I wanted to set one general mail address with the sub folders "Support", "Marketing"  and "Sales". So I created three different inbound emails using the same email, but a different monitored folder. All three inbound emails are showing it's inbox folder. Medium Priority since there is an easy workaround for this.

#### Your Environment
* SuiteCRM Version used: 7.10.9
* Browser name and version: Version 69.0.3497.100 (Official Build) (64-bit)
* Environment name and version: 10.0.36-MariaDB, PHP 7.2
* Operating System and version: Debian 8

**Comment by samus-aran** [comment]
@JuiceSantos Are you able to help us test this proposed fix out? That would be much appreciated :+1:

**Comment by JuiceSantos** [comment]
@samus-aran Applying the fix proposed in #6407 worked like a charm.

**Comment by Dillon-Brown** [comment]
@Mausino Yes it should, thanks! still getting into the habit of setting the milestone label.
