### ISSUE TITLE
AOPInboundEmail Fatal error since upgrading to 7.10.9

### ISSUE THREAD

**Issue by hcv-target** [salesagility/SuiteCRM#6400]
#### Issue
Each CRON run of scheduled job Check Inbound Mailboxes leads to a PHP Fatal error

#### Expected Behavior
Incoming group accounts should be polled for new messages, and cases created for each new message.

#### Actual Behavior
I don't have log access on the IMAP server for the incoming account, so I can't verify whether the account is being polled, but previously, each message would be polled and marked as read in the account - this is not happening now. Each run throws the following error in php error.log:

`PHP Fatal error:  Uncaught Error: Call to a member function retrieve() on null in /path/to/suitecrm/modules/InboundEmail/AOPInboundEmail.php:71
Stack trace:
#0 /path/to/suitecrm/modules/Schedulers/_AddJobsHere.php(616): AOPInboundEmail->handleCreateCase(NULL, '93c537db-fe25-7...')
#1 /path/to/suitecrm/modules/SchedulersJobs/SchedulersJob.php(539): pollMonitoredInboxesAOP(Object(SchedulersJob))
#2 /path/to/suitecrm/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
#3 /path/to/suitecrm/include/SugarQueue/SugarCronJobs.php(231): SugarCronJobs->executeJob(Object(SchedulersJob))
#4 /path/to/suitecrm/cron.php(98): SugarCronJobs->runCycle()
#5 {main}
  thrown in /path/to/suitecrm/modules/InboundEmail/AOPInboundEmail.php on line 71`

suitecrm.log:

Tue Oct  9 13:25:04 2018 [14346][1][ERROR] Pop error level. Try to remove the error_reporting() function from your code.
Tue Oct  9 13:25:04 2018 [14346][1][FATAL] *** FOLDERS: addBean() got empty bean - not saving
Tue Oct  9 13:25:04 2018 [14346][1][FATAL] Job a0a49f47-3960-3427-c038-5bbce4a82334 (Check Inbound Mailboxes) failed in CRON run

#### Steps to Reproduce
1. Upgraded SuiteCRM 7.10.7 to 7.10.9
2. Send message to incoming email account expecting a new case to be generated
3. No case is generated, inbox is not read (yes, have checked account settings, which connect successfully) (yes have also checked that CLI php has imap module installed).
4. There is no step 4

#### More info
It seems clear to me that the method AOPInboundEmail->handleCreateCase() is expecting an argument but getting NULL as its first arg, but I haven't gone deeply enough into the code to know. I did have a look at a previous version of this method (used to be in custom/modules) and it seems this most recent version has been refactored somewhat. What success could be had overriding the current version with the older custom/modules module?

#### Context
We're now unable to auto-create cases from incoming emails

#### Your Environment
* SuiteCRM Version used: 7.10.9
* Not browser-related, server issue
* MySQL 5.7, PHP 7.0-fpm (matching CLI version used for cron job), Apache 2.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.05 LTS

Thanks for any insight you can give!

**Comment by hcv-target** [comment]
I'm running the latest release, 7.10.9. @JackBuchanan Are you saying I would need to install the latest git build, revert the PR, and follow your steps above to fix? Or will this be fixed on the next production release? Our use case depends entirely on auto-generation of cases from email. 

By the way, the mailbox in question does not have any unread messages. Is this PR the only vector for this bug?

Thanks for your help.

**Comment by JackBuchanan** [comment]
If there is no unread emails in your mailbox it is possible there might be a different PR causing this issue in your case. 
If you don't wish to revert the whole PR removing '$isGroupFolderExists' from if ($aopInboundEmailX->returnImportedEmail($msgNo, $uid, false, true, $isGroupFolderExists)) in modules/Schedulers/_AddJobsHere.php on line 605 should have the same effect as the full PR revert.

**Comment by hcv-target** [comment]
Thanks, @JackBuchanan. I've reverted all changes from #6237 and no joy. The error persists.

Any other idea what's causing this?

**Comment by Dillon-Brown** [comment]
This should be fixed by #6441

**Comment by hcv-target** [comment]
@Dillon-Brown @JackBuchanan I've installed 7.10.10 and can confirm this issue is fixed. Thanks!
