### ISSUE TITLE
After updating Gender shows as gender_list

### ISSUE THREAD

**Issue by corrilan** [salesagility/SuiteCRM#6413]
#### Issue
I have updated SuiteCRM from version 7.6.6 to 7.8.22 and then to 7.10.9.
After the update process I have noticed that for all contacts, Gender is now listed as "gender_list" and the drop down box does not list Male and Female.

#### Expected Behavior
I would have expected the Gender to be Male or Female as before the updates.

#### Actual Behavior
Gender all changed to "gender_list".
Drop down selection box does not list Male and Female, only gender_list.

#### Steps to Reproduce
1.  View contact details for a random person.
2.  Look at the persons gender.  (shows as gender_list on my system)
3.  Try changing the gender.  (drop down only contains gender_list on my system)

#### Context
Low priority.

#### Your Environment
* SuiteCRM Version used:  After upgrade from 7.6.6 to 7.8.22, then immediately to 7.10.9
* Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) - also tried in Firefox Quantum 62.0.3 (64-bit)
* mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
* Apache/2.4.18 (Ubuntu)
* PHP 7.2
* Ubuntu Linux 16.04 LTS 64-Bit

**Comment by pgorod** [comment]
Hi, is this a custom field? I don't think we have a Gender field in Contacts...

**Comment by pgorod** [comment]
Ok, but then that sounds like you just need to correct your setup of your custom field (look in `custom/modules/Contacts`), so I would say it is not an issue for Github.

It might be better to close this Issue here, and if you still need help then please open a new thread on the Forums and I will help you out there.

**Comment by corrilan** [comment]
Thanks for pointing me in the right direction, I will close the bug report.
