### ISSUE TITLE
solution proposed: used of reserved mssql keyword in query, crash business hours module

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#6419]
environment:
IIs with mssql database engine
php 7.x
just upgraded from suitecrm 7.8.13 to 7.8.22

module affected : business hours.
if you try to update and save (even with no modification, you will get 
Manage Business Hours
"Database failure. Please refer to suitecrm.log for details".

indeed log shows:
"Sat Oct 13 16:21:11 2018 [2796][15e590af-c6c8-457e-2731-4c0f0456dd5a][FATAL] Error inserting into table: aobh_businesshours: Query Failed:INSERT INTO aobh_businesshours (id,name,date_entered,date_modified,modified_user_id,created_by,deleted,opening_hours,closing_hours,open,day)
					VALUES (N'51022bf9-dcfb-741b-ce9f-5bc2530e987b','',CONVERT(datetime,N'2018-10-13 20:21:11',120),CONVERT(datetime,N'2018-10-13 20:21:11',120),N'15e590af-c6c8-457e-2731-4c0f0456dd5a',N'15e590af-c6c8-457e-2731-4c0f0456dd5a',0,'9','17',1,N'Monday')::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near the keyword 'open'.
Sat Oct 13 16:21:11 2018 [2796][15e590af-c6c8-457e-2731-4c0f0456dd5a][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.
"
I copied the query to my favorite mssql  studio and tried to run the query, same error.
Since "open" is a reserve Mssql keyword it can not be used for a column name like we have in aobh_businesshours

the solution is to put the column name between square brackets. like 
INSERT INTO aobh_businesshours (id,name,date_entered,date_modified,modified_user_id,created_by,deleted,opening_hours,closing_hours,**[**OPEN**]**,day)
  	VALUES (N'51022bf9-dcfb-741b-ce9f-5bc2530e987b',
  '',
  CONVERT(datetime,N'2018-10-13 20:21:11',120)
  ,CONVERT(datetime,N'2018-10-13 20:21:11',120),
  N'15e590af-c6c8-457e-2731-4c0f0456dd5a',
  N'15e590af-c6c8-457e-2731-4c0f0456dd5a',0,'9','17',1,N'Monday')

I ran the updated query from my sql studio and ran ok...

**Comment by pgorod** [comment]
What if our code would always escape column names properly, both in MySQL and MSSQL? There are several issues of this sort, they would all be solved.

**Comment by gymad** [comment]
Hi @bmwtourer, can you please share the "backtrace" info notes in the log after the "Exception in Controller" line. It would be very helpfull to see which part of the code cause the wrong behaviour.
Thanks

**Comment by Dillon-Brown** [comment]
Hi guys, I've created a fix for this issue. Would someone be able to confirm it works on MSSQL?
