### ISSUE TITLE
Javascript errors when using apostrophe [Language]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6439]
#### Issue

There has been a report form a translator claiming that some strings gives error if using apostrophe (when using catalan translation).

include/language/en_us.lang.php
`    'ERR_SQS_NO_MATCH_FIELD' => 'No match for field: ',`

And /modules/Administration/language/en_us.lang.php 
`    'MI_REDIRECT_TO_UPGRADE_WIZARD' => 'Selecting this patch will redirect you to the Upgrade Wizard to perform the necessary system checks. Do you wish to continue?',
`
#### Expected Behavior

Translations shouldn't fire errors when using apostrophe in values

#### Actual Behavior

Example:
English source: include/language/en_us.lang.php
`    'ERR_SQS_NO_MATCH_FIELD' => 'No match for field: ',`

Translation for Catalan language:
`No s'han trobat coincidències per al camp: `
See live at: https://crowdin.com/translate/suitecrmtranslations/442/engb-ca#2570

Downloaded from crowdin as:
`    'ERR_SQS_NO_MATCH_FIELD' => 'No s\'han trobat coincidències per al camp: ',`

#### Your Environment

* SuiteCRM Version used: Version 7.10.9
* Browser name and version: IE 11.0.9600.19078 / Google Chrome 69.0.3497.100 and 70.0.3538.67
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6 and 7.1  / MySQL 5.6.41
* Operating System and version (e.g Ubuntu 16.04): Windows 8.1 Pro

**Comment by itmarcanals** [comment]
SuiteCRM: Version 7.10.9
Browser: Google Chrome 69.0.3497.100 and 70.0.3538.67
Browser: IE 11.0.9600.19078
PHP 5.6 and 7.1
MySQL 5.6.41
Client SO: Windows 8.1 Pro

**Comment by pgorod** [comment]
Sorry, I don't understand, where are the apostrophes in those strings?

Or do you mean that the apostrophes are only added in the translation?

**Comment by itmarcanals** [comment]
@pgorod All apostrophes in the translation.

**Comment by itmarcanals** [comment]
For example when go to mail receive this error:
Uncaught SyntaxError: missing ) after argument list - in line 1925 of index.php

And line 1925:
addToValidateBinaryDependency('MassUpdate', 'assigned_user_name', 'alpha', false, 'No s'han trobat coincidències per al camp: Assignat a:','assigned_user_id');

A text "No s'ha trobat" is correct but middle apostroph (i think) not have \ before it.

Thanks!

**Comment by itmarcanals** [comment]
In language file i think is correct:
Line 1462
'ERR_SQS_NO_MATCH_FIELD' => 'No s\'han trobat coincidències per al camp: ',

Thanks!

**Comment by pgorod** [comment]
That does NOT look correct. If you use `'` inside the string, you need to change the outside quotes to `"`. 

Alternatively, you could escape the apostrophe with `\'`

@horus68 doesn't Crowdin do this automatically, isn't it aware of the need to escape apostrophes?

**Comment by itmarcanals** [comment]
@pgorod i see now in reply that not see \ before ' but in language file this is it.
`'ERR_SQS_NO_MATCH_FIELD' => 'No s\'han trobat coincidències per al camp: ',`

**Comment by pgorod** [comment]
Ah, ok. And where do you go in the app (which screen, which button) to see that string breaking SuiteCRM?

**Comment by itmarcanals** [comment]
When enter into collaboration and then mail.

**Comment by pgorod** [comment]
I can't reproduce this. I changed the `ERR_SQS_NO_MATCH_FIELD` string in the original  `include/language/en_us.lang.php` to include a `\'s` and I go the Emails screen and nothing wrong happens.

Any ideas? Can anybody else reproduce?

**Comment by itmarcanals** [comment]
i think not explain well or not understand totally.
see attached files and if you need is possible to send login data for testing.

![chrome debug](https://user-images.githubusercontent.com/6404137/47502692-bdf5c880-d868-11e8-9268-cb067cdee62d.png)
![chrome source](https://user-images.githubusercontent.com/6404137/47502693-bdf5c880-d868-11e8-9660-a146969c1954.png)
![chrome url](https://user-images.githubusercontent.com/6404137/47502694-bdf5c880-d868-11e8-8056-d91846798c9d.png)

**Comment by pgorod** [comment]
Ok, I can see that faulty code rendering in my system too. But I see it only on the Developer Console, I don't get any symptoms, nothing visible on screen.

This is old code, it is coming from here:
https://github.com/salesagility/SuiteCRM/blame/master/include/MassUpdate.php#L1157

But that whole MassUpdate section... I can't find a way to display it on the screen, it seems to be hidden... permanently.

**Comment by itmarcanals** [comment]
For see symptom when put Catalan language with apostrophe and go to mail don't appear any item in From drop-down for example, some loading layers and others messages fail... if you need search and document some of this.

I see code, 5 years old but not is normal that this process not escape a string or process it when import language file to $app_strings array.

Something go wrong, all apostrophes strings in Catalan fail.

What is a better method for resolve this? you are in the way?

Thanks @pgorod !!

**Comment by adriangibanelbtactic** [comment]
#### Steps to Reproduce

1. Edit: `modules/Administration/language/en_us.lang.php` so that:
```
'MI_REDIRECT_TO_UPGRADE_WIZARD' => 'Selecting this patch will redirect you to the Upgrade Wizard to perform the necessary system checks. Do you wish to continue?',
```
gets modified into:
```
'MI_REDIRECT_TO_UPGRADE_WIZARD' => 'Selecting this patch will redirect you to the Upgrade Wizard to perform the necessary system\' checks. Do you wish to continue?',
```

2. Admin. Repair. Quick Repair and Rebuild. Logout. Login
3. Admin. Module Loader

#### Expected Behavior
Module Loader should show installed modules.

Html that is parsed by the web browser should contain:
```
tmpNodeRelease.onCheckClick = function(){this.uncheck();if(confirm('Selecting this patch will redirect you to the Upgrade Wizard to perform the necessary system\' checks. Do you wish to continue?')){location.href = 'index.php?module=UpgradeWizard&action=index'}};
```
#### Actual Behavior
Module Loader shows an empty space where the installed module list usually are.

Javascript log says:
```
index.php?module=Administration&action=UpgradeWizard&view=module:1660
Uncaught SyntaxError: missing ) after argument list
```
Html that is parsed by the web browser contains:
```
tmpNodeRelease.onCheckClick = function(){this.uncheck();if(confirm('Selecting this patch will redirect you to the Upgrade Wizard to perform the necessary system' checks. Do you wish to continue?')){location.href = 'index.php?module=UpgradeWizard&action=index'}};
```

#### Possible Fix

The part of suitecrm which parses:
```
ModuleInstall/PackageManager/tpls/PackageManagerScripts.tpl
```
should not try to parse:
```
\`
```
on its javascript translations.

Please note that the part of suitecrm which parses translations into something else than javascript should parse it (as I guess it's the default behaviour).

#### Feeback

Does anyone know where the tpl parsing is handled by suitecrm?
Or maybe advices any other fix?

Thank you.

**Comment by pgorod** [comment]
The parsing is handled by the Smarty engine.

I guess if Javascript translated strings need to be handled differently, then it would have to occur at the moment when the `assign`s are being done, when sending the data over to Smarty.

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
