### ISSUE TITLE
Campaigns Wizard - EMail Template "Assigned to" issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6445]
#### Issue
When i use Campaign Wizard and create template in wizard, There is no record for "Assigned to" field. 

#### Expected Behavior
It should be recorded Assigned to field in Email template when it will be created in Wizard.

#### Steps to Reproduce

1. Create Campaign Wizard
2.  Select NEWSLETTER
3. Create a brand new template in Templates section
4.  After Save, No Assigned to user.

#### Your Environment

* SuiteCRM Version used: 10.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62.0.3 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by dursuntosun** [comment]
Is it possible to look at this 🤔

**Comment by pgorod** [comment]
Sorry, I need to understand this better... you want the Assigned to user in the Campaign, or in the Email Template record, or in the contents of the email when the campaign is executed?

Does it make a difference if you create the template first, in Email Templates, and only then start the Campaign Wizard, and select that pre-existing Template?

**Comment by samus-aran** [comment]
Would the solution (which need to be added) be to automatically assign the current user for creating the template via the wizard? I think that would be the best bet. But @pgorod is right that is a workaround.

**Comment by dursuntosun** [comment]
This is what i did;
1)
![screenshot_1](https://user-images.githubusercontent.com/22373035/49732382-924f6600-fc8f-11e8-91d4-4542038aa480.png)
2)
![screenshot_2](https://user-images.githubusercontent.com/22373035/49732383-92e7fc80-fc8f-11e8-81a4-05145d9de189.png)
3)
![screenshot_3](https://user-images.githubusercontent.com/22373035/49732384-92e7fc80-fc8f-11e8-8d80-4b245d14e94d.png)
4)
![screenshot_4](https://user-images.githubusercontent.com/22373035/49732385-92e7fc80-fc8f-11e8-8cf7-bb524cfde457.png)
5)
![screenshot_5](https://user-images.githubusercontent.com/22373035/49732386-92e7fc80-fc8f-11e8-9964-f150969e2e26.png)

**Comment by dursuntosun** [comment]
Is it really difficult to correct this :(
