### ISSUE TITLE
After upgrade from 7.10.x to 7.10.10 - Wrong version info

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6446]
#### Issue
After upgrade, version info is not changed.

#### Expected Behavior
It should be 7.10.10

#### Possible Fix
Change suitecrm_version.php file like this;
$suitecrm_version      = '7.10.10';

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62.0.3 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): Php 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
Hi @dursuntosun 
I've just checked the upgrade packs and they do contain the latest suitecrm_version 7.10.10 file. Can you confirm that the upgrade pack you had downloaded (and when was it) does in fact NOT have the 7.10.10 suitecrm_version?

**Comment by dursuntosun** [comment]
Yes, when i check it, contain the latest suitecrm_version 7.10.10 file. But I don't know why it doesn't updated?

**Comment by samus-aran** [comment]
Hi @dursuntosun Try fixing the format on that file to correct the timestamp to 
$suitecrm_timestamp = '2018-10-25 17:00:00'; and see if that works.

**Comment by Dillon-Brown** [comment]
Timestamp has now been updated in all upgrade packs.
