### ISSUE TITLE
AOR - "Update" button not detecting the MultiSelect values

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#645]
Add a MultiSelect field to Accounts.
Create report with the MultiSelect field as a condition
Report shows correct results initially.

If you then press "Update", It won't detect the value chosen for the Condition. The following occurs:
If Condition is "Equal To" a value, it returns an empty set.
If Condition is "Not Equal To" a value, It appears to return all records.

See Forum Post: https://suitecrm.com/forum/suitecrm-7-0-discussion/6969-possible-bug-in-aor-reports#25203
For some additional Details.

**Comment by Mausino** [comment]
:+1:  same issue

**Comment by vladbar** [comment]
@samus-aran This issue is already fixed.

**Comment by Dillon-Brown** [comment]
No longer an issue.
