### ISSUE TITLE
Cases description lines breaks removed on edit

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#6458]
#### Issue

when a case description has multi lines  , editing the case will strip out the break line
#### Expected Behavior

lines breaks should remain.
#### Actual Behavior

all lines appear has a single line
#### Steps to Reproduce

1. create a case 
2. in detail view, double click description field to do an inline edit and create a 2 lines description 
![image](https://user-images.githubusercontent.com/8605061/47795798-6c938080-dd23-11e8-89d5-4ccadcd98bd2.png)

3. go to edit view , only one line visible
![image](https://user-images.githubusercontent.com/8605061/47795870-8df46c80-dd23-11e8-8dcc-9acc51712b14.png)

4.

#### Context

this is major because this behavior also happens for cases created by email2case then in example,  our user want to close the case , they edit the case , change state and status to closed and save 
because of this,  contact is receiving a close notification whith a poor formed description (his email without lines break) , later it is impossible to read case description correctly.
#### Your Environment

* SuiteCRM Version used: 7.8.20 but also reproduced on suitecrm demo site
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): firefox latest + chrome latest
* Environment name and version (e.g. MySQL, PHP 7): 7 
* Operating System and version (e.g Ubuntu 16.04): ubuntu 16.04

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by ftoledo** [comment]
Hi all i can replicate under 7.11.13
