### ISSUE TITLE
Cannot save user trough code

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#6465]
#### Issue
If there are custom fields in Users module, and you want to set and save this fields through the code, new value for a field is saved but users email address is deleted.

UPDATE TEST:
This was discovered during testing of my scheduler which searches for all free users (custom field under Users) and gets first free and assigns him to Case.
Today I tried to see where and when exactly I lose email, and this is ENIGMA (I tried to log every possible logic_hook action).
I set up users email (user->Edit->input email->Save) --> before and after save are fine
I call the scheduler.
Scheduler gets user bean --> inside there is no email (email1 field is empty).
Save user: before save, after save all say that email is empty.
Before_relationship_add, after_relationship_add, before_relationship_delete are never excecuted on user. In table 'email_addr_bean_rel' connection between my user and email address is deleted.

So, does anyone have an idea why when I search and get user he lost his email address without a trace?

#### Expected Behavior
Upon save, only new vale should be changed.

#### Actual Behavior
There is a part of code (from SUGAR) that destroys email adrress for user:
include/SugarObjects/templates/person/Person.php  --> save function
if ($ori_in_workflow === false || !empty($override_email)) {
            $this->emailAddress->saveEmail(
                $this->id,
                $this->module_dir,
                $override_email,
                '',
                '',
                '',
                '',
                $this->in_workflow
            );
        }
 

#### Possible Fix
Fix is to change IF part to:
if ($ori_in_workflow && !empty($override_email)) {
but then is not possible to change mail under Admin->Users.

#### Steps to Reproduce
1. In logic hook modify one field of user bean and call save()
2. Look in Admin-> Users is the change
3. Search for users email address -- mail is gone
4.

#### Context
I can not save user through the code, including scheduler actions. 

#### Your Environment

* SuiteCRM Version used: 7.8.23
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Firefox
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Linux Mint 18.1

**Comment by samus-aran** [comment]
Would this resolve your issue?
https://github.com/salesagility/SuiteCRM/pull/6410

**Comment by willrennie** [comment]
@fcorluka did you see @samus-aran latest comment?

**Comment by fcorluka** [comment]
I have seen it, but I am not sure that this will help me.

Because both changes I can not found in my code (either function name, either code).
I am on version 7.8.27.

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
