### ISSUE TITLE
Wrong WHERE composition upon NULL precondition in Company

### ISSUE THREAD

**Issue by lserni** [salesagility/SuiteCRM#6468]
https://github.com/salesagility/SuiteCRM/blob/475f732cef5b0e02b0f7208446c40b5a985aa406/include/SugarObjects/templates/company/Company.php#L195

This line:
    if ($where !== '') 

requires a strict inequality with the empty string, but in some cases a NULL precondition is passed, thereby failing the test. As a consequence, `WHERE ($where)` results in WHERE (), which is invalid SQL and crashes the export.

I suggest changing the above line to

    if (!empty($where))

to catch these edge cases.

**Comment by lserni** [comment]
As a side note, a similar code, but with a loose match instead of a strict match, is to be found in person/Person.php. Here, the looseness of the match avoids troubles, but here also an explicit emptiness check would perhaps be better.

**Comment by pgorod** [comment]
@lserni it really helps if you fill in the Issue template. We'd like to know your version of SuiteCRM, at the very least, and the steps to reproduce are obviously needed here. Are we supposed to guess how you get to that line of code?

Please say, which module, which screen, which button, and what data you put in to make a difference to that WHERE condition. Thanks.

**Comment by lserni** [comment]
Sorry for the long delay...

Installed a new SuiteCRM:

    Versione 7.11.0
    Sugar Versione 6.5.25 (Versione 344)

and created a new table "Unita_Locale", then entered a few records.

Then tried to export the whole table by opening the module, choosing "Select ALL" checkbox, then "Multiple Actions" > Export, got an error ("Database error, check the log for details"), and log says,

Mon Jan 21 16:05:32 2019 [15102][1][FATAL] Mysqli_query failed.
Mon Jan 21 16:05:32 2019 [15102][1][FATAL] Errore di esportazioneUNITA_unita_locale: <BR>.SELECT
					unita_unita_locale.*,
					email_addresses.email_address email_address,
					'' email_addresses_non_primary, users.user_name as assigned_user_name ,unita_unita_locale_cstm.catasto_particella_c FROM unita_unita_locale LEFT JOIN users
					ON unita_unita_locale.assigned_user_id=users.id  LEFT JOIN email_addr_bean_rel on unita_unita_locale.id = email_addr_bean_rel.bean_id and email_addr_bean_rel.bean_module = 'UNITA_unita_locale' and email_addr_bean_rel.deleted = 0 and email_addr_bean_rel.primary_address = 1 LEFT JOIN email_addresses on email_addresses.id = email_addr_bean_rel.email_address_id  LEFT JOIN unita_unita_locale_cstm ON unita_unita_locale.id = unita_unita_locale_cstm.id_c WHERE () AND  unita_unita_locale.deleted=0  Query Failed: (same query as above redacted): MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND  unita_unita_locale.deleted=0' at line 5
