### ISSUE TITLE
repointing the upload_dir does not recognize the upgrade directory

### ISSUE THREAD

**Issue by sefarsi** [salesagility/SuiteCRM#6469]
#### Issue
Module Load is missing the Install/uninstall/disable buttons from each of the packages.

We modified the config.php files (yes, we really should have used the over ride file instead), but we repointed upload_dir to another location /suitecrm/upload a partition that provided us with more space. Our attachments were referenced with no issue, but what was the issue is that the Module Loader Uninstall/Disable buttons for each package was not found.

So, I had to recreate the /upload folder and copy over the upgrade recursively and then the Module Loader functioned properly

#### Expected Behavior
We should see all the buttons as usual.

#### Actual Behavior
We just saw the loaded packages, but no buttons to install/uninstall/disable the packages.

#### Possible Fix
In the config.php, we had set the upload_dir to another location. We decided to recreated the /upload folder and move back the upgrade directory and all its subdirectories and files. The buttons then appeared.

#### Steps to Reproduce
1. Set the new upload_dir eg /suitrecrm/upload
2. or move all the files  folders from /upload to /suitecrm/upload
The buttons will not appear in Module Loader.

#### Context
We need to create more space for our growing attachments, so that is why we created another partition.

#### Your Environment
SuiteCRM 7.10.7
I don't think the other details are relevant.

**Comment by willrennie** [comment]
I have tested this and this is not an issue in 7.8.x, 7.10.x or 7.11.x. The removal of the buttons is most likely that the reference is not there in the database, or the path to your upload directory is not correctly specified in your config.php
