### ISSUE TITLE
Upgrade always re-adds some default email templates

### ISSUE THREAD

**Issue by lazka** [salesagility/SuiteCRM#6471]
#### Issue

Every time I upgrade from some 7.10.x to the newest version these following email templates are re-added, so they exist multiple times:

* "New account information"
* "Reset your account password"
* "Two Factor Authentication Code"

#### Expected Behavior

No changes to the email templates

#### Actual Behavior

Three new email templates get created

#### Steps to Reproduce

1. Have a 7.10.9 install
2. Download the 7.10.x-to-7.10.10 upgrade package
3. Follow upgrade wizard in the admin section

**Comment by willrennie** [comment]
@lazka I downloaded a fresh 7.10.9 and upgraded to 7.10.15 and did not experience this issue. Further detailed steps and screen shots etc. would be great to have here, before closing as a non-issue as if there is a valid bug I want to make sure we catch it. Thanks.

**Comment by lazka** [comment]
OK, thanks for testing, I'll give it another try.

**Comment by willrennie** [comment]
@lazka no problem, let me know how it goes!

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
