### ISSUE TITLE
suitecrm.com is down

### ISSUE THREAD

**Issue by FloppyKing** [salesagility/SuiteCRM#6478]
suitecrm.com isn't loading correctly.  It just says "Error establishing a database connection".  Sorry if this isn't the correct place to report this.  I wasn't sure who/where else to report it.

The company I work for is currently looking for a replacement CRM software to replace our aging goldmine software and i was hoping to find out more info on the official website, but it appears to be down.

**Comment by mattlorimer** [comment]
Thanks, we are working to restore the site, will hopefully be back up soon
