### ISSUE TITLE
email templates: inserting images in mozaik broken since 7.10.10

### ISSUE THREAD

**Issue by lazka** [salesagility/SuiteCRM#6484]
#### Issue

1) Open template editor (mozaik)
2) Right click, insert image
3) Select image on local disk

Expected:

4) Source gets filled out

Actual:

4) Nothing happens

#### Possible Fix

I've bisected this to e840ea8968caf5c27bd
Reverting this commit on top of 7.10.10 makes things work again.

**Comment by pgorod** [comment]
Thanks @lazka. 

@QuickCRM do you understand why this is happening?

**Comment by QuickCRM** [comment]
No, I don't know what happens
The change we made was only for when editor was not mozaik (attachments were not saved due to a javascript error - the mozaik variable was not defined in that case).

**Comment by jack7anderson7** [comment]
Hi @lazka,

I've found a  possible work around this for the time being, if you insert a URL in the source that links to a possible google image, when on the image open the image up into a new tab and copy the URL(make sure the URL ends in a file format, ideally a picture) from there and post it in the source and the image should then appear in the email template.
![example1github](https://user-images.githubusercontent.com/44227185/49647170-86f30500-fa19-11e8-9fd2-08297fde75b6.png)

![githubexample 2](https://user-images.githubusercontent.com/44227185/49647174-878b9b80-fa19-11e8-9096-cea5b7239dea.png)

![example 3github](https://user-images.githubusercontent.com/44227185/49647171-86f30500-fa19-11e8-8ecb-fa48540d0fb5.png)
![example 4](https://user-images.githubusercontent.com/44227185/49647172-878b9b80-fa19-11e8-990b-ae1bf95d2fbe.png)

![example 5](https://user-images.githubusercontent.com/44227185/49647173-878b9b80-fa19-11e8-9bb2-d9e9cd6c66fa.png)

**Comment by lazka** [comment]
I've opened a PR for this: #6757
