### ISSUE TITLE
Select Delegates disappears after invite with no delegates

### ISSUE THREAD

**Issue by tgessner** [salesagility/SuiteCRM#6500]
#### Issue

On an event page, there is a select delegates "button" at the top of the delegates list. When there are not delegates in the list, selecting "Invite" will return with the message all delegates have been invited however the "Select Delegates" button has disappeared.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
@tgessner this sort of question doesn't belong here, but rather in the Forums:

https://suitecrm.com/suitecrm/forum

Please go there and ask your questions after reading the Guidelines:

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18836-guidelines-to-post-in-these-forums

I will help you out in the Forums. Thanks.

**Comment by tgessner** [comment]
This isn't a question. I am reporting behaviour I think is incorrect

**Comment by pgorod** [comment]
Yes, but I wasn't able to reproduce it, so I am inclined to think it is only happening in your installation. But I don't know yet, we'll have to see in more detail.

It is common for this sort of thing to require some triage work, check your installation, ask you about your logs, etc. When it is more confirmed, and there is more (and better) technical information, you report it on GitHub. Thanks for understanding.

**Comment by tgessner** [comment]
Ok, that explains it. Thank you. I will see what I can isolate and provide more detail.

Tim
