### ISSUE TITLE
How to select a user as a delegate on an event

### ISSUE THREAD

**Issue by tgessner** [salesagility/SuiteCRM#6501]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by samus-aran** [comment]
This is best suited for the forums.

https://suitecrm.com/suitecrm/forum

Please go there and ask your questions after reading the Guidelines:

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18836-guidelines-to-post-in-these-forums
