### ISSUE TITLE
Multiple bounce handling problems

### ISSUE THREAD

**Issue by lazka** [salesagility/SuiteCRM#6504]
#### Issue

* Imported bounce emails are not always linked with the campaign logs
* Imported bounce emails are not detected as hard bounces
* Marking emails as invalid based on hard bounces doesn't work

Related issues: #5980, #5898, #1578

#### Expected Behavior

When SuiteCRM fetches a bounce email over IMAP it should show up in the
campaign stats and on hard bounces it should mark the email as invalid.

#### Actual Behavior

Even though there is a proper bounce email imported it doesn't show up in the
campaign stats and on hard bounces the email address isn't marked as invalid.

#### Possible Fix

I've opened the PR #6505 to fix this

#### Steps to Reproduce

1. Set up bounce handling in SuiteCRM
2. Create campaign and add a contact with a non-existing email address
3. Send a campaign email
4. Watch the bounce inbox and wait until the email is read
5. Check the the campaign stats

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 63
* Environment name and version (e.g. MySQL, PHP 7): PHP7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by samus-aran** [comment]
Ideally you would relate the PR to close all the other (now) duplicate issues without having to create this new one. 
I'll mark the other issues are duplicates and this supersedes this. Thanks for the contribution!

**Comment by lazka** [comment]
> Ideally you would relate the PR to close all the other (now) duplicate issues without having to create this new one.

OK, I'll do that in the future!

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by personman** [comment]
What's the current status of this, @lazka? Do you expect your fixes to be merged soon? If not, do you have a fork with this merged in? Thanks!

**Comment by lazka** [comment]
I don't know the merge-status of this, but the SuiteCRM devs have been very active in getting my proposed fixes merged so far, so I'm hopeful :)

btw. you can append ".patch" to the PR url to get a git patch file you can apply locally: https://github.com/salesagility/SuiteCRM/pull/6505.patch
