### ISSUE TITLE
Filter Issue on List View

### ISSUE THREAD

**Issue by jack7anderson7** [salesagility/SuiteCRM#6512]
This, as shown in the screenshot, 
![error1 711](https://user-images.githubusercontent.com/44227185/48768761-e929d700-ecb1-11e8-9148-0661ced262ae.png)

shows the user an icon with a cross in the corner indicating that the user has made a filtered search when such a search has not been made. This also, when hovered over, reveals the code that is used for the icon to display the filtered search.

This is considered an issue as it suggests that the user has searched for something when they haven't. Secondly, when hovering over the icon it reveals code to the user, which shouldn't happen.

Expected Behaviour
The expected behaviour would be that the icon doesn't actually appear unless a filtered search has been made.

Actual Behaviour
When clicking on the icon it disappears from the page however always appears when going from a home page to a list view. When searching with a filter it appears as expected and when deleted disappears as expected. 

Possible Fix

#### Your Environment

* SuiteCRM Version used: 7.8.8(also tested on 7.10 and 7.8.9)
* Browser name and version (e.g. Chrome Version 70.0.3538.77 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
@jack7anderson7 how do you get this to happen? I just went on the [live demo](demo.suitecrm.com), clicked Accounts to see the list view, and there is no X in the filter button. Do I need to do something else?

**Comment by jack7anderson7** [comment]
1. Start at home
2. Go to the Sales drop-down menu.
3. Select accounts.
After this the icon should appear next to the filter icon, hope this helps, if not let me know.

**Comment by pgorod** [comment]
You can try those steps yourself at the live demo, it doesn't reproduce. I suspect this could be simply a corrupted filter in the specific user profile, I've seem similar issues before.

It's better to triage these things in the forums before coming here with a bug report...

Please try it in the live demo, and try also a different user in your server, and let me know how it goes. Thanks.

**Comment by Dillon-Brown** [comment]
Interesting, I'm able to replicate this locally as well but not on demo. I suspect this is due to us frequently switching branches in a dev environment than an actual core bug.
