### ISSUE TITLE
Gridlayout parser doesn't respect fillers in layouts

### ISSUE THREAD

**Issue by JanSiero** [salesagility/SuiteCRM#6516]
#### Issue
Invocation of the grid layout parser that writes view layouts disrespects (filler) elements. For instance: when installing or uninstalling a module that has a one-to-many relation to a parent module, then the editview, detailview and quickcreateview of the parent module are rewritten. When these views contain (filler) elements, these elements are then gone.

#### Expected Behavior
When views are modified due to installing related modules, then the (filler) elements of the views of the parent module are not removed.

#### Actual Behavior
The (filler) elements of the views of the parent module are removed on installing or uninstalling a related module

#### Possible Fix
See related pull request

#### Steps to Reproduce
1. Open Studio and modify the Accounts editview so that it contains (filler) elements:
![image](https://user-images.githubusercontent.com/3467391/48785102-55253300-ece4-11e8-98bd-287bfd964815.png)
2. Save and Deploy the editview
3. Open Module Builder, create a new package, a new module with a many-to-one relation to Accounts
3. Deploy this module
4. Check the Accounts editview: the (filler) elements are gone, the fields that were next to the filler elements now occupy two columns
![image](https://user-images.githubusercontent.com/3467391/48785633-66227400-ece5-11e8-9bfe-1dc659248f94.png)

#### Context
* Bug is an issue when writing module code that modifies existing views, for example to add fields to these views
* Bug is also an issue when installing modules that relate to other modules, as these overwrite the views of the parent module

#### Your Environment
* SuiteCRM Version used: 7.10.7 (but applies to all versions)

**Comment by dursuntosun** [comment]
When i try fix, i could'nt see any change.🤔 I did repair

**Comment by JanSiero** [comment]
Hi dursuntosun,

Can you write the exact steps what you did when you tried the fix?

**Comment by dursuntosun** [comment]
Hi,
Changed file according to your fix and then repair.

**Comment by JanSiero** [comment]
Hi,
I think you misunderstood the bug issue. Are we talking about the same bug?

* Did you read the bug description and the _Steps to reproduce_?
* Were you able to reproduce the bug before applying the fix (follow all steps of _Steps_to_reproduce_)?
* Did you, after applying the fix, create a layout with (filler) elements and then again follow these same steps?

There is no need to do any "Quick Repair and Rebuild" to reproduce the bug or after applying the fix.
