### ISSUE TITLE
Task List View is blank

### ISSUE THREAD

**Issue by NiallBrookes** [salesagility/SuiteCRM#6520]
#### Issue
When I create a new task and then try to view all the tasks that have been created by clicking view tasks on the left hand panel the page is just blank. If I search for the task I have just created using the global search I am able to find the new created task so I know the tasks are successfully creating.
I have attached an image below of the screen I am getting when clicking view tasks.
![view tasks page](https://user-images.githubusercontent.com/45173757/48897975-689ae000-ee43-11e8-94a9-2e6983410502.JPG)

#### Expected Behavior
When clicking view tasks I should see a list view of all tasks that have been created.

#### Actual Behavior
When clicking view tasks I get a blank screen.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version Google Chrome Version 70.0.3538.102 (Official Build) (32-bit)
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7.2.12
* Operating System and version (e.g Ubuntu 16.04): Windows server 2016

**Comment by cameronblaikie** [comment]
Hi there,
I've been unable to replicate this on my local dev environment and tested this on the demo.suiteondemand.com instance. Perhaps can you try repair & rebuild, or refresh your cache? If the Tasks List View is still not appearing, either check in your suitecrm.log or PHP logs for any obvious errors. Do you have any additional customisations on the Task List that may cause this?
