### ISSUE TITLE
[language] Hard coded messages in Elasticsearch

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#6540]
An error has occurred while performing the search. Your query syntax might not be valid.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L117

Unable to find the requested SearchEngine. Try performing the search again.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L119

Failed to connect to the Elasticsearch server.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L121

An error internal to the Search has occurred.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L123

An unknown error has occurred while performing the search.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L125

Contact an administrator if the problem persists. More information available in the logs.
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/SearchThrowableHandler.php#L171

ms
https://github.com/salesagility/SuiteCRM/blob/develop/lib/Search/UI/templates/search.results.tpl#L75

Search Interface
https://github.com/salesagility/SuiteCRM/blob/develop/modules/Administration/Search/view.tpl#L50

**Comment by pgorod** [comment]
While somebody is fixing this, please improve this string also:

https://github.com/salesagility/SuiteCRM/blob/develop/modules/Administration/language/en_us.lang.php#L972

The `Wrapper` is a programming concept, it shouldn't be in the UI, much less on a help string.

This probably isn't worth a separate Issue and PR so I put it here.
