### ISSUE TITLE
email templates 7.10.10 tinymce: images button missing

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#6544]
As my customer has handling problems with the ugly Mozaik editor they want to switch to tinymce editor.
After switching they are missing the images - Button.

#### Issue
Images Plugin is not initalized, and so it is missing in the Browser.
#### Expected Behavior
Images Button should be there

#### Actual Behavior

no images Button.
#### Possible Fix

Enabel Plugin in  include\SuiteEditor\SuiteEditorConnector.php
add image and imagetools in  Line 78   plugins: ['code', 'table', 'link', 'image', 'imagetools'],
#### Steps to Reproduce

1. switch to TinyMCE -Editor in Profile
2. create new email Template
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actual FF, Chrome and Edge
* Environment name and version (e.g. MySQL, PHP 7): 7.1
* Operating System and version (e.g Ubuntu 16.04): ubunto16.04

**Comment by jack7anderson7** [comment]
Hi there @Lehnerr,

I am unable to replicate the problem you are having, would you be able to provide some screenshots so I could see if I can help anymore in anyway?

**Comment by Lehnerr** [comment]
Hi here is the screeenshot where no Image Button:
![no_image-button](https://user-images.githubusercontent.com/16813374/49163416-516d5e00-f32d-11e8-9397-f7e75a70c38e.jpg)

After enabling it it is there:
![with_image-button](https://user-images.githubusercontent.com/16813374/49163508-88437400-f32d-11e8-828f-57b6d0e6a4ef.jpg)

**Comment by Lehnerr** [comment]
It is part of [#6545](https://github.com/salesagility/SuiteCRM/issues/6545)
