### ISSUE TITLE
Apostrophe not displaying correctly in Description text field - Calls/Tasks

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#655]
Navigate to a Call/Task (either existing or create new) and add a few apostrophes.  Save the record and view the description field on the DetailView.

The apostrophes have converted into [&#]039;

Reference from forums: 
https://suitecrm.com/forum/suitecrm-7-0-discussion/6984-not-displaying-apostrophe-properly

**Comment by johnM2401** [comment]
Worth mentioning that this also happens with Double Quotes.

" is converted into &quot;

This occurs in a few other places. (e.g; Account Billing Address, Project Issue Description field)
These all seem to be Text Areas, so the issue might just lie with the "TextArea" field type.

**Comment by samus-aran** [comment]
The Smarty template is escaping all of the html using the 'html' option (see below), need to either remove that or review the best way forward.
{$fields.description.value|escape:'htmlentitydecode'|escape:'html'|url2html|nl2br}
