### ISSUE TITLE
 SuiteCRM 7.10.10 Case description not saving when AJAX is disabled 

### ISSUE THREAD

**Issue by lhsatsuma** [salesagility/SuiteCRM#6570]
#### Issue
In Case module, the description field (tinyMCE) it's not saved.

#### Expected Behavior
The description field should be saved and displayed in Detail View.

#### Actual Behavior
When saving the Case, the description content (tinyMCE) it's not send on POST.

#### Steps to Reproduce

1. Create a Case record.
2. Type anything in description field.
3. Save.

#### Context

TinyMCE it's not sending description content when Ajax it's disabled.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 70.0.3538.110 (32 Bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.37 PHP: 7.0 Apache: 2.4.27
* Operating System and version (e.g Ubuntu 16.04): Bitnami (Debian 8).

**Comment by lw9474** [comment]
We have the same issue on a fresh test install.  I was going to open a case but I had not yet had a chance to do it today.  Thanks.

**Comment by samus-aran** [comment]
This is *only* if the Ajax has been disabled? Just so we can accurately try and replicate this.

**Comment by lw9474** [comment]
My ajax is ENABLED.  Straight up fresh install 7.10.10
THX

**Comment by lhsatsuma** [comment]
@samus-aran Yes, only when Ajax has been disabled.

**Comment by lw9474** [comment]
Do I need to set up an account or is there a user name password for the demo?

**Comment by samus-aran** [comment]
@lw9474 It's the same as the demo data from a fresh install. Try "will" or "sally" for both the username and password.

**Comment by lw9474** [comment]
Getting ready to try that.
While I was waiting I did it one more time.
Here you go.

https://www.useloom.com/share/f317bd06c71f447780549f28d3fd4388

**Comment by samus-aran** [comment]
Ahhha ok, so your steps are from a subpanel from another module and not from the module itself. Btw loved your video 😄

**Comment by lhsatsuma** [comment]
My problem it's from the module itself...

**Comment by lhsatsuma** [comment]
@lw9474 Please create another issue for this case specific..

**Comment by samus-aran** [comment]
I did change the name but didn't consider that the AJAX and the subpanel full form maybe two separate issues. @lhsatsuma are you able to confirm that when your AJAX is disabled you can't update or save the description via a direct path to cases i.e. Home > All > Cases > Create Case ( or an existing Case ). If not then we'll sperate these issues out.

**Comment by samus-aran** [comment]
Yeah agreed @lw9474 and @lhsatsuma  I'll revert the title and ask @lw9474 to create that new issue but you may reference this ticket for our comments as additional info 👍

**Comment by samus-aran** [comment]
Thanks for confirming! I too tested this and able to replicate.. I'll update the title and state it's specific to ajax

**Comment by lhsatsuma** [comment]
Using the fix #6570 when editing a case already created it's not showing the tinyMCE description case.

![image](https://user-images.githubusercontent.com/44283104/50014497-43654180-ffab-11e8-8b07-ef3130a8a69e.png)

**Comment by samus-aran** [comment]
Hi @lhsatsuma We haven't see this issue from our testing. Is that on the full Edit View?

**Comment by lhsatsuma** [comment]
@samus-aran I used the fix #6613 of @GFanta with new commit and it works now. Thanks for the support.
