### ISSUE TITLE
Get Count of all Records in Modules

### ISSUE THREAD

**Issue by Sandeep023** [salesagility/SuiteCRM#6575]
#### Issue
I want the count of all records in any module
Is There any way of getting the count using api v8

**Comment by samus-aran** [comment]
This is really a question for the forums. The GitHub issue tracker is for issues. Have a look at the documentation e.g. here https://docs.suitecrm.com/developer/api/version-8/json-api/#_page
That described how you can you use the links and pages to calculate how many records are in the database with calls. But there is no direct single call for the number of records.

Hope that helps.
