### ISSUE TITLE
Email addresses not populated correctly 7.8.23

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#6591]
When a user tries to compose mail, he chooses from all email addresses which are prepopulated in FROM drop-down.
But different values are populated for CREATE (only 1 = users) and REPLY (all available).

#### Issue
I have several INBOUND and OUTBOUND email accounts and want to see them in FROM field when creating an email.

Problem 1: OUTBOUND mail are of non-use, FROM is populated only with INBOUND addresses
Problem 2: when I select email and then REPLY, I can see all of the addresses, but when I click COMPOSE I can see only users email (logged in user)

#### Expected Behavior
All the time all of the addresses should be in FROM field.

#### Possible Fix
Debuging gets me to file:
modules/Emails/javascript/EmailUICompose.js

When action REPLY is called, addresses are populated in line 2071:

 if (composePackage.fromAccounts != null && composePackage.fromAccounts.status) {
		var addressFrom = document.getElementById('addressFrom' + SE.composeLayout.currentInstanceId);
		        SE.util.emptySelectOptions(addressFrom);
		        var fromAccountOpts = composePackage.fromAccounts.data;
		        console.log(fromAccountOpts); 
		        for(i=0; i<fromAccountOpts.length; i++) {
		              var key = fromAccountOpts[i].value;
		              var display = fromAccountOpts[i].text;
		              var opt = new Option(display, key);
		              if (fromAccountOpts[i].selected) {
		              	opt.selected = true;
		              }
		              addressFrom.options.add(opt);
		      }
            }

When action CREATE / COMPOSE is called addresses are populated in line 2290 (only 1 email address):
var addressFrom = document.getElementById('addressFrom' + idx);
        if (addressFrom.options.length <= 0) {
        	SE.util.emptySelectOptions(addressFrom);
	        var fromAccountOpts = SE.composeLayout.fromAccounts;
	        for (id = 0 ; id < fromAccountOpts.length ; id++) {
	              var key = fromAccountOpts[id].value;
	              var display = fromAccountOpts[id].text;
	              var is_default = false;
	              if(key == SUGAR.default_inbound_accnt_id)
	              	is_default = true;
	              var opt = new Option(display, key);
	              addressFrom.options.add(opt);
	              addressFrom.options[id].selected = is_default; //Safari bug new Option(x,y,true) does not work.
	        }
        }

#### Steps to Reproduce
1. Set up few inbound group mail accounts, and activate them
2. Go in Email 
3. Find old email and click REPLY -- in FROM there are all email addresses
4. Click on COMPOSE -- only 1 email address

#### Context
This is showing in different versions of CRM, as I can tell by issues and comments.

#### Your Environment

* SuiteCRM Version used: 7.8.23. LTS
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 63.0.3, Chrome Version 70.0.3538.110 (Official Build) Built on Ubuntu
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.24, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Linux Mint 18.1

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
