### ISSUE TITLE
Role management - missing names of columns

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#6606]
#### Issue

Does somebody know what means second and third column in role management ? Mimimum are missing column names there and maybe after i will know more what is the sense of this colums.

Will great if we will also column for inline edit.. because now you can it set up only for field inside the studio management

![2018-12-12_1628](https://user-images.githubusercontent.com/5773777/49880412-64535880-fe2c-11e8-86e9-6873f12f1e94.png)

#### Steps to Reproduce

1. Go to Admin area
2. Role management
3. Create/Edit role

#### Your Environment

* SuiteCRM Version used: 7.10.11
* Browser name and version Chorme 71 64-bit
* Environment name and version MySQL 5.6, PHP 7.3
* Operating System and version Win 10 Home

**Comment by pgorod** [comment]
It works fine for me

![image](https://user-images.githubusercontent.com/15945027/49886398-6ff54e00-fe31-11e8-83d5-5fd9222373af.png)

It seems you have two extra columns that shouldn't be there. 

Maybe this is a Language Pack issue? Can you please try with English language?

**Comment by Mausino** [comment]
@pgorod it's wird.. maybe is the carry-over (remnant) from 
SecuritySuite - Enhanced SuiteCRM Teams  because the collums remain to see Admin area or create the record.. will look on it our developer... 

![2018-12-12_1903](https://user-images.githubusercontent.com/5773777/49889615-47c21b00-fe42-11e8-9867-e00ad7d8aac0.png)

+ yes, i am using english as default language...
