### ISSUE TITLE
Pagination not working in SuiteCRM REST API v8

### ISSUE THREAD

**Issue by rigalpatel001** [salesagility/SuiteCRM#6608]
Pagination not working in SuiteCRM REST API v8

#### Issue
I am trying to get records form leads modules i have used pagination parameter in get request but it 's not working.
 `uri: 'http://example.com/api/v8/modules/Leads?page[number]=3&page[size]=100`

I have also tried page limit but still not working . only **20** records display i have console response but not getting **total-pages** meta.

#### Expected Behavior

Total pages meta  and links meta should display in Json results.
`{
    "meta": {
        "total-pages": 54
    },
    "data": [
        {
            "type": "Account",
            "id": "e6e0af95-4772-5773-ae70-5ae70f931feb",
            "attributes": {
                "name": "",
                "account_type": ""
            },
            "relationships": {
                "AOS_Contracts": {
                    "links": {
                        "related": "/V8/module/Accounts/e6e0af95-4772-5773-ae70-5ae70f931feb/relationships/aos_contracts"
                    }
                }
            }
        }
    ],
    "links": {
        "first": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=1",
        "prev": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=2&page[size]=1",
        "next": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=4&page[size]=1",
        "last": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=54&page[size]=1"
    }
}`

#### Actual Behavior

below meta not found in json result and only 20 records return.
`{
    "meta": {
        "total-pages": 54
    },`

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (Google chrome 70.0.3538.110 (Official Build) (64-bit)):
* Environment name and version ( MySQL  Ver 14.14 Distrib 5.7.24, PHP 7.2.10):
* Operating System and version (e.g Ubuntu 18.10):

**Comment by isleshocky77** [comment]
Just a heads up, I had originally +1'd this; however, in `/Api/V8` (the new V8 API) I now have pagination working as `7.11.3`.

There are some caveats

1. The total-pages are off fixed by #7144
2. The links returned are incorrect #7095 which is fixed by  #7165
3. The `meta` data is not always returned. You must provide the request with a `page[number]` or `page[size]` in order for `link` and `meta` to be returned - I would prefer that the request always return this data.
