### ISSUE TITLE
Inbound email - IMAP in Mailclient will not show folder or contents

### ISSUE THREAD

**Issue by michaelhaf** [salesagility/SuiteCRM#6623]
Hello,

using Version SuiteCRM 7.10.11 its possible to setup Inbound email per profile fully, but when accessing these 3 folders: INBOX, Trash, send from the mailclient throught its button it will not show folder or contents instead there is this erro coming:

![suitee-imap-error](https://user-images.githubusercontent.com/45918149/50055140-e0121580-014a-11e9-8930-6bd88479084e.PNG)

--> Error. There are no folders available. Please check your e-mail settings.

#### Expected Behavior
When Mailclient is opened it will show the latest results from the INBOX and these are visible and importable. When clicking on the Folderbutten the desired Folder should be opend and all mails schould be visible.

#### Your Environment
* SuiteCRM Version used: 7.10.11
* Browser Chrome today Version; Firefox today Version
* Environment : Ubuntu 16.04 LTS x64, MySQL, PHP 7
* php-imap ist installed and ready to use

**Comment by pgorod** [comment]
Can you please check your logs for messages?

Both suitecrm.log and php_errors.log, or whatever your web server log is called.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
