### ISSUE TITLE
Document link to other modules is not correctly deleted

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#6628]
When a relationship is created between Documents and another module and the document is deleted, the link field to the other module is not set to deleted.

#### Issue

If a one to many relationship is created between Documents and Accounts(or other module) and a document is added to the account via a relate field, if the document is deleted from the documents module the link to the account still remains.

#### Expected Behavior

Both the document and link should be set to deleted.

#### Actual Behavior

Only the document is deleted.

#### Steps to Reproduce

1. Go to Studio->Documents->Relationships
2. Create one to many to Accounts
3. Add relate field in Accounts' edit view
4. Go to Accounts module and add document via relate field
5. Go to Documents module and delete document 
6. The document will be deleted as expected but if you go to the joining table - documents_accounts_1_c - in the database and check the link it will not be set to deleted

#### Context

If you have the document name in the listview columns this can lead to what appears as duplicate record when in fact the are the same records and are unable to be merged together.

#### Your Environment

* SuiteCRM Version used: 7.10.11
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium Version 71.0.3578.80
* Environment name and version (e.g. MySQL, PHP 7):MySQL - PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 (64-bit)

**Comment by samus-aran** [comment]
Pull Request is here https://github.com/salesagility/SuiteCRM/pull/6629
