### ISSUE TITLE
LBL_AOP_CASE_UPDATES - issue after rename it

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#663]
After rename of it,  it will break case update function 

When we renamed the LBL_AOP_CASE_UPDATES in studio in detailview or editview, function was not worked correctly in case module.

**Comment by CaptainChainsaw** [comment]
What version of SuiteCRM are you using?  This may already have been fixed but is still an issue in older versions of Suite.  I've tried replicating this issue as I understand it and it seems to work for me.  Please see the screenshot below.

![case-update-issue](https://cloud.githubusercontent.com/assets/3913259/12484520/a2970756-c052-11e5-8e12-87c9a70cc015.png)

**Comment by Mausino** [comment]
Hi, yes, this issue was fixed in older versions...  now i close this the issue. Thanks for your support :) :+1:
