### ISSUE TITLE
Add task to clean cache dir to RoboFile.php

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#6648]
#### Issue

This issue starts thanks to the debate in #6605 where we conclude that it is better to use [Robo](https://robo.li/) instead of [Makefile](https://www.gnu.org/software/make/manual/make.html)

We should have common and useful tasks that can be runned from the console, like for example a task to clean cache directory.

#### Expected Behavior

It would be great to clean cache directory by running

`$ ./vendor/bin/robo clean:cache`

#### Actual Behavior

We do not have a way to clean cache directory from the console.

**Comment by Abuelodelanada** [comment]
Hi @pgorod 

Do you think we can have this simple PR merged? 

I see it as the tip of the iceberg to start adding more useful task to RoboFile.php

**Comment by connorshea** [comment]
Should this issue be closed now?

**Comment by Abuelodelanada** [comment]
Sorry @pgorod !! I did not know the workflow! Now it's open again ;-)
