### ISSUE TITLE
Save Project Tasks as Hours sets End Date incorrectly

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#669]
When a user creates a Project Task via the Gantt View the duration (if set to hours) will add hours to the start date exactly to the time the task was set (using date modify).  This causing incorrectly days being calculated from the incorrect end_date.

Is this a possibility to add a feature to set the start and end times that the calculations can work within? i.e. the user can define a 'working' day time range?

Reference from forums:

https://suitecrm.com/forum/suitecrm-7-0-discussion/7041-work-time-resources-projects

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
