### ISSUE TITLE
Typo in key - LBL_ORIGINAL_MESSAGE_SEPERATOR

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6691]
#### Issue

It looks like a typo in the language key and 2 code files:

`'LBL_ORIGINAL_MESSAGE_SEPERATOR' => '---',`
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Emails/language/en_us.lang.php#L373

and related
$mod_strings['LBL_ORIGINAL_MESSAGE_SEPERATOR']
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Emails/EmailsController.php#L886-L891

It was added here:
Adding LBL_ORIGINAL_MESSAGE_SEPERATOR
https://github.com/salesagility/SuiteCRM/commit/8e9c0b67626dc8260e5d4f0d28a0b31baeeb5e4f

#### Expected Behavior

"separator" not "seperator"

#### Actual Behavior

See also file modules/Emails/metadata/composeviewdefs.php for
`<button class="vertical-seperator">`
added here https://github.com/salesagility/SuiteCRM/pull/3307

#### Your Environment

* SuiteCRM Version used: hotfix

**Comment by ognjen-petrovic** [comment]
Hello,

I could resolve this one.
