### ISSUE TITLE
Determining latest LTS Release

### ISSUE THREAD

**Issue by mphilipps** [salesagility/SuiteCRM#6706]
hi,
I am trying to write a monitoring check that determines whether I am running the latest LTS version. However there doesn't appear to be a public api for that (something like: http://api.wordpress.org/core/version-check/1.1/ ).
While digging around trying to find a good solution (one that isn't parsing https://suitecrm.com/download-suitecrm-lts/ ), I noticed that according to the SuiteCRM Release Cycle ( https://suitecrm.com/lts/ ), indicates that the 7.10.x branch is an LTS branch and has left the develop/Release phase.

So what is the latest LTS version?

**Comment by Abuelodelanada** [comment]
Hi @mphilipps 

The latest LTS version is 7.10.11

https://github.com/salesagility/SuiteCRM/releases/latest

**Comment by mphilipps** [comment]
So the website is out-of-date?

https://suitecrm.com/download-suitecrm-lts/

**Comment by Abuelodelanada** [comment]
So it seems .... 7.8.x is the old LTS branch

**Comment by Dillon-Brown** [comment]
Hi @mphilipps, @Abuelodelanada is correct in saying 7.10.11 is the latest LTS version. This isn't super clear on the downloads page but 7.8.x and 7.10.x are LTS versions and both are currently receiving updates.

**Comment by mphilipps** [comment]
Ok, I assume I should upgrade to 7.10.x before the old LTS branch suddenly stops receiving updates.

**Comment by Dillon-Brown** [comment]
If you don't have a specific reason to be on the 7.8.x branch and want to be on the latest LTS release cycle then yes.
