### ISSUE TITLE
Subpanel labels are defaulting to LBL_ with more relationship to custom moduel

### ISSUE THREAD

**Issue by DemonBob** [salesagility/SuiteCRM#671]
Custom Modules: 

Customers
Equipment
Notes

Customer and Equipment both have a relationship of One to Many Notes. Once I activate the second relationship, atleast one subpanel name is 'LBL_MECHX_NOTES_MECHX_CUSTOMERS_FROM_MECHX_NOTES_TITLE'. I've tried on a fresh install, and another customer module named Contacts. 

I have ran every repair in the repair menu between each install.

**Comment by ijdavie** [comment]
Hi @DemonBob, 

This sounds like the same issue as #551
