### ISSUE TITLE
Version 7.10.11 Re: Fix #719 YUI https mixed content

### ISSUE THREAD

**Issue by tradenet** [salesagility/SuiteCRM#6721]
Version 7.10.11
Sugar Version 6.5.25 (Build 344)
This is a new install and I am still getting mixed content using HTTPS. It doesn't appear to be fixed.

_Originally posted by @tradenet in https://github.com/salesagility/SuiteCRM/pull/5523/comment#issuecomment-451606504_

**Comment by willrennie** [comment]
@tradenet Please can you construct and detail your issue using the issue template that is provided. Providing the description for your bug, context, steps to reproduce etc. We will then assess your issue further. There have been various fixes for the HTTPS mixed content so we would ideally like to know the specifics of where you are encountering these errors to ensure fixes have been correctly applied and have not regressed.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity
