### ISSUE TITLE
Email Style Issue - Black screen

### ISSUE THREAD

**Issue by cameronblaikie** [salesagility/SuiteCRM#6729]
After sending email, screen progressively ends up as a black screen.

#### Issue

When sending an email a popup appears to tell you that the email has sent but if you hit enter the screen progressively gets darker as you keep hitting enter. With every press of the enter key, the email gets sent that amount of times.

#### Expected Behavior

Should only let you hit the send button once and then wait for the popup to close before you can send another one.

#### Actual Behavior

the screen darkens with every enter key pressed.
![1](https://user-images.githubusercontent.com/42933743/50770956-fd855b80-1280-11e9-9166-d631e3254008.png)

#### Steps to Reproduce

1. Go to emails
2. Compose an email
3. Then when the popup appears saying "Email sent" start pressing the Enter key 

#### Your Environment

* SuiteCRM Version used: (7.10.10)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mausino** [comment]
@cameronblaikie this is Mac OS + which version? because on Win 10 home with latest chrome i did not have same problem
