### ISSUE TITLE
'Pipeline by sales stage' dashlet chart not working after 7.8.24 update

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#6736]
After upgrade from 7.8.20 to 7.8.24, ' Pipeline By Sales Stage' dashlet chart is no longer working. The following error is logged in the CRM log: 

```
[27833][1][FATAL]  Query Failed:   SELECT opportunities.sales_stage,
                        count(*) AS opp_count,
                        sum(amount_usdollar/1000) AS total
                        sum((amount_usdollar*1)/1000) AS total
                    FROM users,opportunities   WHERE opportunities.date_closed >= '2018-01-01' AND opportunities.date_closed <= '2019-12-31' AND opportunities.assigned_user_id = users.id  AND opportunities.deleted=0  WHERE opportunities.date_closed >= '2018-01-01' AND opportunities.date_closed <= '2019-12-31'  SELECT opportunities.sales_stage,
                        count(*) AS opp_count,
                        sum(amount_usdollar/1000) AS total
                        sum((amount_usdollar*1)/1000) AS total
                    FROM users,opportunities   WHERE opportunities.date_closed >= '2018-01-01' AND opportunities.date_closed <= '2019-12-31' AND opportunities.assigned_user_id = users.id  AND opportunities.deleted=0  GROUP BY opportunities.sales_stage: **MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sum((amount_usdollar*1)/1000) AS total
                    FROM users,opportunit' at line 4**

```

#### Possible Fix
FIX SQL query errors. 

#### Steps to Reproduce
1. Observe CRM log files 'tail -f suitecrm.log'
2. Add dashlet chart 'Pipeline by sales stage' on homescreen.  
3. See SQL error logged. Error reappears every time chart is refreshed. 

#### Context
Key momepage chart not working.  

#### Environment Tested
* SuiteCRM Version used: 7.8.24
* Browser name and version: Safari 12.0.2
* Environment: LAMP. PHP 7.0.33, mysqld  5.6.42 
* OS: CentOS Linux release 7.6.1810 (Core)

**Comment by willrennie** [comment]
Confirmed as a bug in 7.8.x. Works as expected in 7.10.x and 7.11.x

**Comment by Mausino** [comment]
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL. Should it be closed.

**Comment by evgu** [comment]
@Dillon-Brown @Mausino we upgraded to 7.10.x long time ago. #6736 is no longer an issue for us.

**Comment by Mausino** [comment]
@evgu should you close this issue if is not actual ?

**Comment by evgu** [comment]
@Mausino, Apologies, I wasn't sure if I am allowed to or not as usually @Dillon-Brown triages all tickets. It is closed now.
