### ISSUE TITLE
REPORTS NOT WORKING

### ISSUE THREAD

**Issue by nathancani** [salesagility/SuiteCRM#674]
Hello, 

Since upgrading to 7.4.1 ; The reports functionality seems to of stopped working in regards to the Export Functionality;

I click the export button or download pdf; It fails

Only within the Reports Module; If i export from Accounts List View; It is fine

**Comment by mattlorimer** [comment]
you may need to clear your browser cache, as this has been slightly altered in 7.4.1

**Comment by nathancani** [comment]
Hi Matt; Thanks for your response;

I did try this twice however

Just did a quick repair and rebuild and a cache check again;

Now started working;

Strange ...
