### ISSUE TITLE
Suitecrm 7.3.2 Calendar entries are not displayed

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#675]
There is a known bug with the security suite plugin where the calendar entries are not displayed, because the calendar tries to fetch too many entries,; see:
https://www.sugaroutfitters.com/support/securitysuite/653

Solution:
on or around line 187 in modules/Calendar/CalendarActivity.php
change: 
$where = self::get_occurs_until_where_clause($meeting->table_name, $meeting->rel_users_table, $view_start_time, $view_end_time, 'date_start', $view);

to: 

$where = self::get_occurs_within_where_clause($meeting->table_name, $meeting->rel_users_table, $view_start_time, $view_end_time, 'date_start', $view);

I would recommend to add the code change to the suitecrm calendar core module.

**Comment by jobvector** [comment]
it generates also a huge performance boost if the user has hundreds (or thousands) of entries

**Comment by armadillotec** [comment]
I can confirm this bug!
