### ISSUE TITLE
Removing composer.lock in travis?

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#6759]
In the `.travis.yml` there are these lines:

https://github.com/salesagility/SuiteCRM/blob/80e9e484f7c00340a67a65efbf82aca2e3d5d141/.travis.yml#L60-L62

This means the tests can fail whenever a package within the ranges defined by the `composer.json` is updated, without any change in the SuiteCRM codebase. Is there a specific reason we do this in CI? It doesn't seem like a good idea, and doesn't really test the actual behavior of the code that you'd get by installing SuiteCRM locally, since Composer installs versions based on the lockfile.

**Comment by Dillon-Brown** [comment]
@connorshea Not sure why this was done, It can probably be removed.
