### ISSUE TITLE
Upgrade Zip missing for 7.10.12

### ISSUE THREAD

**Issue by mphilipps** [salesagility/SuiteCRM#6760]
hi,
According to https://docs.suitecrm.com/admin/releases/#anchor-7.10.12 there is new release with a link to https://suitecrm.com/download/ , however there I can only find upgrades to 7.10.11.

Also https://suitecrm.com/download-latest-pre-release-suitecrm/ leads to a 404.

**Comment by jack7anderson7** [comment]
Hi @mphilipps, on the page https://suitecrm.com/download/ - there is a link at the top of the page entitled "Latest LTS Version" and if you click that link it takes you to this page. - https://suitecrm.com/download-suitecrm-lts/

**Comment by mphilipps** [comment]
Yes, but I want to upgrade from 7.10.11 to 7.10.11 so I clicked on the upgrade link. That one takes me to https://suitecrm.com/upgrade-suitecrm/ which is missing 7.10.12.

![missing_version](https://user-images.githubusercontent.com/17722151/51176070-4a3de780-18bc-11e9-8c79-7b3348843800.png)

**Comment by Mausino** [comment]
@Dillon-Brown @jack7anderson7 @salesagility as @mphilipps wrote on 

Uprgade page aren't latest upgrade packages for 7.10.12, 7.8.25, 7.9.18 and latest 7.11 version

Also if you click on Latest PRE-RELASES menu you get 404 error page

**Comment by pgorod** [comment]
I think this is now working.

**Comment by code-ph0y** [comment]
Hi @mphilipps, 

I have now updated the site (https://suitecrm.com/upgrade-suitecrm) with the upgrade packages. 

Let us know if you run into any other issues,

Thanks.

**Comment by mphilipps** [comment]
@code-ph0y Thank you, the Update applied flawless.
