### ISSUE TITLE
Settings : "Display actions within menus" does'nt work for Subpanels

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6763]
#### Issue

"Display actions within menus" does'nt work for Subpanels after update from 7.10.9 to 7.10.12.
![image](https://user-images.githubusercontent.com/22373035/51225793-4ada8a80-195d-11e9-91d5-830485f1d5a6.png)

![image](https://user-images.githubusercontent.com/22373035/51225828-88d7ae80-195d-11e9-912b-2404eb43da1e.png)
#### Expected Behavior

It should be like this
![image](https://user-images.githubusercontent.com/22373035/51225793-4ada8a80-195d-11e9-91d5-830485f1d5a6.png)
#### Steps to Reproduce

1. Open "System Settings"
2. Uncheck "Display actions within menus"
3. Look at any modules action menu for page view and subpanel
4. See result

#### Your Environment

* SuiteCRM Version used: 7.10.12
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 64.0.2 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by dursuntosun** [comment]
This is related to #6533

**Comment by ugod** [comment]
Same in System Version 7.10.13 (LTS)
