### ISSUE TITLE
Email view not working after upgrade from v.7.10.11 to 7.10.12

### ISSUE THREAD

**Issue by michelhcote** [salesagility/SuiteCRM#6767]
We've installed v.7.10.12  
The ListViewDataEmails.php wasn't displaying the emails and the only option was to CREATE or upload.  When clicking on CREATE we would get the following msg:

> Error: File [modules/Home/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.

We had to remove from lines 145 up to 161 and put back the v.7.10.11 code for it to work, we now have this code and everything works fine: 

 

            {
        $inboundEmailID = $currentUser->getPreference('defaultIEAccount', 'Emails');
        $id = $folder->getId();
        if (!empty($id)) {
            $inboundEmailID = $folder->getId();
        }
        $isValidator = new SuiteValidator();
        if ($inboundEmailID && !$isValidator->isValidId($inboundEmailID)) {
            throw new SuiteException("Invalid Inbound Email ID" . ($inboundEmailID ? " ($inboundEmailID)" : ''));
        }

_Originally posted by @michelhcote in https://github.com/salesagility/SuiteCRM/commit/729e22a3b184be59fdf0a04108293583f6240d2e#commitcomment-31947648_

**Comment by michelhcote** [comment]
I also noted these other 2 issues, can't go back to previously configured Inbound Email in ADMIN menu and the INBOX button is not available any more as in v7.10.11 when going into view email.

![image](https://user-images.githubusercontent.com/46033872/51264998-b5072580-1985-11e9-82b1-ec15484c7c00.png)

_______________________________
Missing INBOX Button



![image](https://user-images.githubusercontent.com/46033872/51265157-2050f780-1986-11e9-89fa-2eae2b03472a.png)

**Comment by ambroserinald** [comment]
Hello @cameronblaikie,

I'm also facing the same issue after the 7.11.0 upgrade.

SuiteCRM details:
Version 7.11.0
Sugar Version 6.5.25 (Build 344)


![image](https://user-images.githubusercontent.com/46783064/51323284-2e377300-1a81-11e9-8189-647875102129.png)


If we try clicking the Import, this happens:-

![image](https://user-images.githubusercontent.com/46783064/51323347-5f17a800-1a81-11e9-998f-562784585729.png)

Please help to resolve the issue.
Thanks.

**Comment by michelhcote** [comment]
Hello @cameronblaikie ,

Here are my logs 
 `Thu Jan 17 09:36:38 2019 [790703][1][FATAL] Error: File [modules/Home/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.`

**Comment by Mausino** [comment]
@Dillon-Brown should it get milestone number + some labels? i think is very important issue... which is making the email module unusable. 

Also will great if other will test the patch which i created by this comment https://github.com/salesagility/SuiteCRM/commit/729e22a3b184be59fdf0a04108293583f6240d2e#commitcomment-31947648 of @michelhcote

**Comment by Dillon-Brown** [comment]
@Mausino Looking into it, so far I haven't been able to replicate though. I do see the bug

> Error: File [modules/Home/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.

but that's only when I don't have emails setup properly.

**Comment by michelhcote** [comment]
@Dillon-Brown The error message occurs when you click on CREATE which I can undertand could be a setup problem. 

The issue without the code change is that it's impossible to see the emails in the INBOX, it only gives us the choices to CREATE or Import Emails when in fact we already have an inbox with emails.  There is no need  need to CREATE or Import emails as per presented without the code change.

**Comment by Dillon-Brown** [comment]
@michelhcote This is what I see on 7.11.0 with a personal inbound and outbound:

![screenshot](https://user-images.githubusercontent.com/26431166/51399637-52a55500-1b3e-11e9-8855-0382bd0b6380.png)

Have you tried Rebuild Minified JS Files + Rebuild JS Grouping Files + Quick Repair and Rebuild and then a hard browser refresh? I would also try deleting the email account and re-adding it.

My only other thought is that something is going wrong when you have pre-existing email accounts and then upgrade.

**Comment by Mausino** [comment]
@Dillon-Brown in our case the issue only for users appear. The admin could use the email listview and send emails.... This pull request which i created is solving issue with listview (on your screen i see admin) and problem with email little bit continue.. 

(you can set up in profile settings primary email + default suitecrm will default client and by this if admin allowed use main SMTP for all users, you should in compose email choose FROM dropdown the value with your name and will send email in your name by default setting of SMTP ( like your name is example@example.com and defualt SMTP is info@example.com) and this isn't working still. you should use only default SMTP of SuiteCRM (e.g. info@example.com) because if you use yours primary email from settings you got error that you must contact adminstrator if you push send button. )

**Comment by michelhcote** [comment]
@Dillon-Brown I tried what you recommended but it didn't work.

> Rebuild Minified JS Files + Rebuild JS Grouping Files + Quick Repair and Rebuild and then a hard browser refresh

I've also created another email account with no luck.  Same issue.

**Comment by Dillon-Brown** [comment]
@michelhcote @Mausino Thanks for the assistance guys, i'll take a deeper look into this.
