### ISSUE TITLE
list veiw showing 404

### ISSUE THREAD

**Issue by luvmuzak** [salesagility/SuiteCRM#6789]
having issues after installing suitecrm version 7.8.24 and above.

on all my view list (modules), i can only view the next page after the initial view list page . Any other page after that ,it shows me 404 ( server not found).
i get this in my error log:
PHP Warning:  Invalid argument supplied for foreach() in /home/tglobaln/public_html/suite/include/MVC/View/views/view.list.php on line 87

**Comment by Dillon-Brown** [comment]
Hi @luvmuzak,

This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum) as i'm not able to replicate it as a core SuiteCRM issue. This sounds like it's potentially an issue with your .htaccess, i'd suggest going into the admin panel and running "Rebuild .htaccess File". 

Thanks.
