### ISSUE TITLE
order_by DESC does not work via webservice

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#68]
http://forums.sugarcrm.com/f6/need-help-how-sort-records-order_by-descending-order-84127/

**Comment by shogunpol** [comment]
I tried this with: get_entry_list, and works with ASC and DESC, can you confirm which API call this is referring to as this link does not work any longer.

regards Jerzy

**Comment by willrennie** [comment]
Has been tested with the API get_entry_list and order by asc/desc is working as expected in the latest version.
