### ISSUE TITLE
product_discount generated wrong in template

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#680]
When I use 'Print as PDF' with, for example, a quote, the $aos_products_quotes_product_discount variable can be shown wrongly in certain cases.

This happens if you use an amount, not a percentage, and this amount is higher than '999'.
When you, for example, give a discount of '1.234', the resulting value in the generated template is '1,23'.
It doesn't matter if the decimal separator used is a comma or a dot; I've seen this with both configurations.
I've seen this in the separate plug-in v5.3.3 and, just tried it, in the public SuiteCRM demo, which is on SuiteCRM 7.3.1.

**Comment by samus-aran** [comment]
Hi there, I don't understand the issue - is it possible to take screenshots of where this is happening?

**Comment by ebogaard** [comment]
![thousands-separator-issue](https://cloud.githubusercontent.com/assets/4035997/11363353/a83e0a92-9299-11e5-9288-f5f5c9dfbacf.png)

In the image attached, you can see (part of) the line items above and the generated PDF below.
As you can see, in the line item, the amount is shown correctly as 1.234,00 (one thousand two hundred and thirty four Euro). The generated PDF shows 1,23 (one Euro and twenty three cents1), which is incorrect.

Hope this clarifies things.

**Comment by samus-aran** [comment]
Yes it does, thanks for this.

**Comment by gokhanerdogdu** [comment]
Hello,

This problem still exists in 7.7.1. I changed the below line in TemplateParser.php and it solved the problem.

Delete: $value=currency_format_number($value,$params = array('currency_symbol' => false));
Add: $value = $value;

FYI.

**Comment by veryszhang** [comment]
This is indeed a bug.  After the $aos_products_quotes_product_discount has been formatted with "currency_format_number" function, it is already a right currency format.  However, it has been formatted AGAIN.

1) $value = currency_format_number("1999",$params = array('currency_symbol' => false));  // right result "1,999.00"

2) $value = currency_format_number("1,999.00",$params = array('currency_symbol' => false)); //error result "1.00"

So, the second formatting is completely redundant.

**Comment by Dillon-Brown** [comment]
This should no longer be an issue as discounts are rounded to two decimal places.
