### ISSUE TITLE
Elasticsearch: Elastic index name is hardcoded in code

### ISSUE THREAD

**Issue by dawid-zaroda** [salesagility/SuiteCRM#6800]
#### Issue
I want to have many SuiteCRM instances integrated with one Elasticsearch instance (eg. on development server). Now it's not possible, because are SuiteCRM instances uses the same index name: *main*

#### Expected Behavior

Index name should by configurable (config.php) or should be available to override upgrade-safe way (custom directory).

#### Actual Behavior

Index name is hardcoded in two PHP classes: *lib\Search\ElasticSearch\ElasticSearchEngine.php* and *lib\Search\ElasticSearch\ElasticSearchIndexer.php* and setIndex is never used anywhere.

#### Possible Fix

System should pick index name from config.

#### Your Environment

* SuiteCRM Version used: 7.11.0
* Browser name and version: Google Chrome 71.0.3578.98 64-bit
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7.1, Elasticsearch 5.6.13
* Operating System and version: Ubuntu 16.04.4

**Comment by pgorod** [comment]
@dawid-zaroda thanks for all these Issues you're reporting, very useful.

Can you make a Pull Request with this enhancement? Are you a developer (or can you get one in your organization to help with this)? Thanks.
