### ISSUE TITLE
Bad link on Download page

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#6819]
#### Issue
https://suitecrm.com/download/ -> 3) Get Started! -> "Installation manual" link is bad

#### Expected Behavior
The link should be to this page:
https://docs.suitecrm.com/admin/installation-guide/downloading-installing/

#### Actual Behavior
It linked to the not existed page:
https://docs.suitecrm.com/admin/installation-guide/downloading--installing/

#### Possible Fix
Remove the double dash

#### Context
It's pretty important, especially for first time installations.

**Comment by cameronblaikie** [comment]
Hi @bdcomp 
Link has been Fixed
