### ISSUE TITLE
Theme settings for supbanels menu + icons

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#682]
1. We can't set the color (in theme settings) of icons for subpanels, because if i set it like white, it will not see the pencil for inline editing or other icons 

2. We can´t configure the color of menu for subpanel dropdowns (+ dropdown in listview), because it's using color of buttons menu in theme settings.

![accounts](https://cloud.githubusercontent.com/assets/5773777/11223907/9755604e-8d72-11e5-9288-fa89e5afad5a.png)

**Comment by ghermans** [comment]
+1

**Comment by recci** [comment]
I fixed this issue as part of a clients project The issues is that the Action menu button Css should be separated out from the button css in themes/SuiteR/css/colourSelector.php. 

![screenshot from 2016-03-24 11 22 00](https://cloud.githubusercontent.com/assets/5599247/14016276/074d6448-f1b7-11e5-9186-02b8d82b96c5.jpg)

![screenshot from 2016-03-24 11 21 48](https://cloud.githubusercontent.com/assets/5599247/14016288/130234b2-f1b7-11e5-840c-07e9362cfabc.jpg)

See my pull request for this issue.
