### ISSUE TITLE
Rest Api /api/oauth/access_token URL Not found

### ISSUE THREAD

**Issue by avinash969** [salesagility/SuiteCRM#6820]
I installed suite CRM using this [https://www.tecmint.com/install-suitecrm-in-centos-and-ubuntu/]

My Instance is up and running. When I try to access /api/oauth/access_token I am getting URL not found.
web URL for login is working. 
Web URL is : http://ip-address/suitecrm
Complete Url for rest endpoint  is http://ip-address/suitecrm/api/oauth/access_token.

Is there anything wrong in the URL I am trying to access or did I miss some configuration for rest endpoints.

The version of Suite CRM is: 7.10.11

**Comment by helgebe** [comment]
https://suitecrm-docs.netlify.com/developer/api/api-8/#_suitecrm_api_requirements
You need https and keys
https://docs.suitecrm.com/developer/api/version-8/json-api/#_before_you_start_calling_endpoints

Try these steps, and also check that the apache mod_rewrite is working and .htaccess is read.
 from .htaccess:
 RewriteRule ^Api/access_token$ Api/index.php/access_token [L]

or i think you could reach it from https://ip-address/suitecrm/Api/index.php/access_token just for the testing
