### ISSUE TITLE
7.11 Global Search takes you to Dashboard

### ISSUE THREAD

**Issue by mcianchi** [salesagility/SuiteCRM#6824]
Hello everyone, we have updated our server from version 7.10.11 to version 7.11.00 The global search now does not give any results and simply returns to the Dashboard.
In the Account section, once the list appears, if we select the next page button, a warning appears: "Warning: Invalid" supplied for foreach () in /var/www/html/include/MVC/View/views/view.list. php online 157 ".
Within the opportunities, if we select a contact, it is inserted correctly, but this page reports this warning "Warning: Declaration of the SugarWidgetSubPanelEditRoleButton :: displayList ($ layout_def) should be compatible with SugarWidgetField :: displayList (& $ layout_def) in / var /www/html/include/generic/SugarWidgets/SugarWidgetSubPanelEditRoleButton.php online 0 ". Is there a solution to these problems, especially for global research?

Thank you in advance.
Environment
* SuiteCRM Version used: 7.11.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version: MySQL, PHP 7.2
* Operating System and version: Debian 9.7:

**Comment by Dillon-Brown** [comment]
Hi @mcianchi, those are just PHP notices and can be safely ignored. You can disable these from appearing by modifying your php.ini error_reporting. 

For the global search issue, have you checked the Search Settings? you may need to go into admin -> Search Settings and select Basic + Advances search.

**Comment by mcianchi** [comment]
Hi Dillon,
 
Thanks for the reply.
 
I tried setting in the "Search Setting"  with Basic + Advanced, but when trying to find a customer the CRM always brings me back to the dashboard. 
 
I then tried to set basic again and everything worked fine. At this point if I configure basic or basic + advanced all work regularly.
 
Tnks.
 
Michele Cianchi   
CEO
 
Cell.: +39 348 5863623
Skype: mcianchi
Email: m.cianchi@securcrea.com
 
Securcrea s.n.c.
di Cianchi e Burgassi
Via Bicocchi, 12
58022 – Follonica (GR)
P.IVA: 01564970539
Tel./Fax +39 0586 1713210
Tel./Fax +39 0171 1723180
Pec: securcrea@pec.securcrea.com
Web: http://www.securcrea.com
 
 
 
AVVISO DI RISERVATEZZA: 
Il testo e gli eventuali documenti trasmessi contengono informazioni riservate al destinatario indicato. La seguente e-mail è confidenziale e la sua riservatezza è tutelata legalmente dalla normativa nazionale ed europea di cui al D.lgs. 196/2003 e al Reg. UE 679/2016 in materia di protezione dei dati personali. La lettura, copia, od altro uso, divulgazione o riproduzione non autorizzati o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono rigorosamente vietate. Qualora abbiate ricevuto questo documento per errore siete cortesemente pregati di darne immediata comunicazione al mittente ai numeri qui indicati e di provvedere immediatamente alla sua distruzione
 
 
Da: Dillon Brown <notifications@github.com> 
Inviato: giovedì 24 gennaio 2019 15:50
A: salesagility/SuiteCRM <suitecrm@noreply.github.com>
Cc: mcianchi <m.cianchi@securcrea.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [salesagility/SuiteCRM] 7.11 Bugs and wornings (#6824)
 
Hi @mcianchi, those are just PHP notices and can be safely ignored. You can disable these from appearing by modifying your php.ini error_reporting.
For the global search issue, have you checked the Search Settings? you may need to go into admin -> Search Settings and select Basic + Advances search.

**Comment by Dillon-Brown** [comment]
@mcianchi Confirmed as a bug, looks like the configuration value for global search isn't set until you go to that screen and save. I'll fix this in the upgrade packs for the next release. Thanks!
