### ISSUE TITLE
Cache composer packages on Travis CI

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#6829]
#### Issue
The current Travis config doesn't cache composer packages.

#### Expected Behavior
Travis CI jobs would cache composer packages so they wouldn't need to be installed on every CI run.

#### Actual Behavior
Composer packages are reinstalled for every CI job.

#### Possible Fix
Cache Composer packages in CI, as described [here](https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/).

This needs #6770 before it can be done.

This should be added to the `.travis-ci.yml`:

```yml
cache:
  directories:
    - $HOME/.composer/cache/files
```

See also: https://docs.travis-ci.com/user/caching/

#### Steps to Reproduce
1. Look at any Travis CI job
2. Note that Composer needs to install all its dependencies fresh with every job

e.g. https://travis-ci.org/salesagility/SuiteCRM/jobs/483990444

#### Context
This causes the Travis CI jobs to take longer than it otherwise would. On a randomly selected job, it took 137 seconds to install the relevant packages (after looking at a few others, it looks like package install time usually varies between 60 seconds and 120ish seconds), I imagine with the packages cached (assuming no new packages are added in the given commit) each job could save between 1 and 2 minutes. As more packages are added, the amount of time saved will increase.

**Comment by connorshea** [comment]
@Dillon-Brown I was told to ping you :)

**Comment by Dillon-Brown** [comment]
@connorshea Good idea, I'll see about getting #6770 merged. Thanks!
