### ISSUE TITLE
Demo of SuiteCRM - update to 7.4.1

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#683]
Will it possible to update the DEMO of SuiteCRM from 7.3.1 to 7.4.1 ???

http://demo.suiteondemand.com/index.php?module=Home&action=About

In the new version of SuiteCRM are many issues. I think, that not only me but all want test the functions of the new version of SuiteCRM 7.4.1 to be sure that the same issues are in official demo (not only in their versions of SuiteCRM on localhosť/web).
![demo_suite](https://cloud.githubusercontent.com/assets/5773777/11224472/715b7e52-8d75-11e5-80e8-6df2e7083ff9.png)

**Comment by bpabiszczak** [comment]
Like this?: 

1. Repo: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer
2. Demo: https://gitdeveloper.yetiforce.com/

We can send you the script.

**Comment by bpabiszczak** [comment]
503 Service Temporarily Unavailable

**Comment by Mausino** [comment]
![demo](https://cloud.githubusercontent.com/assets/5773777/11278175/0a04a5a0-8eea-11e5-826d-74f78866249a.png)

**Comment by Mausino** [comment]
Thanks :+1:  now the demo is working fine and it's update to version 7.4.1
