### ISSUE TITLE
Quick Radius Map Display failing to display results in Firefox/Chrome

### ISSUE THREAD

**Issue by fataugie** [salesagility/SuiteCRM#6831]
#### Issue

If I try to view a quick radius map using either Mozilla or Chrome, I can't get the page  to load. The same map will load fine using Internet Explorer. 

#### Expected Behavior
Should be displaying a map, pins for locations within the radius initially submitted, and a details view with relevant information (name, address, phone, etc.)

#### Actual Behavior
With Chrome and Mozilla, the page blinks and returns to the entry page resetting all the options back to blank address, default search radius and the default search module (Accounts).  So, in other words, no details view, no map, nothing.  And it doesn't matter which module I select....they all act the same.  No final view of mapping or list details...just goes back to the entry page for Quick Radius Map . 

#### Possible Fix
Unknown

#### Steps to Reproduce

Using the Quick Radius maps page-
1. Enter address, select module to apply search to, and change default radius (if desired)
2. Hit search
3. wait.....
4. Observe the failed display if using Firefox/Chrome
4a. Observe correct display if using Internet Explorer

#### Context
We use this module extensively for telemarketing call list generation.  We decide on a local to target and say show us all possible leads in a geographic area.  Creating the list using different browsers would be beneficial and helpful

#### Your Environment

Server Environment - 
* SuiteCRM Version used: 7.10.12
* Environment name and version: PHP 7.2, MariaDB 10.1, Nginx
* Operating System and version: Ubuntu 18.04-LTS
=============================
Client Environment - 
* *Browser name and version: This occurs both in Mozilla Firefox 64.0.2 and in Chrome 71.0.3578.98.  
However, Internet Explorer 11 works fine.
* OS's tried - Windows 7 x64 and Windows 10 x64

**Comment by willrennie** [comment]
@fataugie Are you able to provide further details? Was this working and then stopped working? Did you upgrade or make any changes? Do you have a valid API key in your Geocode Settings in Admin? I have tested the Quick Radius Map functionality and it rendered maps successfully for me in both Chrome and Firefox browsers.
