### ISSUE TITLE
Wrong link on homepage

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#6847]
#### Issue
https://suitecrm.com/ -> SalesAgility logo (bottom of page, under "The driving force behind SuiteCRM") -> Empty page

#### Expected Behavior
The link should probably be to this page:
https://suitecrm.com/about/about-us/salesagility/

#### Actual Behavior
It linked to an empty page:
https://suitecrm.com/about/

#### Possible Fix
Update the link

#### Context
The expected link is available from:
1. Top Menu -> About -> About us -> SalesAgility
2. Bottom Menu -> About -> SalesAgility

**Comment by Dillon-Brown** [comment]
Updated, Thanks!
