### ISSUE TITLE
module document missing files

### ISSUE THREAD

**Issue by hturkoz** [salesagility/SuiteCRM#685]
SuiteCrm 7.4.1 Can't attach SuiteCrm Documents to Email

-> Go to email module
-> compose a email
-> click Attach
-> Select Document from SuiteCRM. (not local machine)
-> Blank Page

FIX : find missing files and put in modules/documents directory 

popup_picker.html
popup_picker.php
popup.php

Regards

**Comment by hturkoz** [comment]
duplicate with https://github.com/salesagility/SuiteCRM/issues/679

Just to know : why change path of these files ?

Regards

**Comment by mattlorimer** [comment]
it was mostly duplicating functionality, and causing issues with studio
