### ISSUE TITLE
Wrong size of 7.11.x-to-7.11.1 upgrade package

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#6871]
#### Issue
https://suitecrm.com/upgrade-suitecrm/
7.11.x-to-7.11.1 upgrade package is described with wrong size.

#### Expected Behavior
The description is correct.

#### Actual Behavior
The actual size is 29.6 MB while it described as 18.71 MB.

#### Possible Fix
Update the description.

#### Context
Downloaded several times with Firefox and Chrome.

**Comment by Dillon-Brown** [comment]
Hi @bdcomp, this should now be resolved. Thanks!

**Comment by bdcomp** [comment]
Hi @Dillon-Brown, all the text of 7.11.x-to-7.11.1 upgrade package box, is now underlined...

**Comment by Dillon-Brown** [comment]
@bdcomp Hmm, I'm not seeing this:

![screenshot](https://user-images.githubusercontent.com/26431166/52119300-90ab7a00-2610-11e9-9f1a-739f09cf7e5e.png)

Which browser are you using?

**Comment by bdcomp** [comment]
![screenshot_2019-02-01 upgrade suitecrm - suitecrm](https://user-images.githubusercontent.com/6454391/52119407-aa08f200-2621-11e9-90b3-3e0562186466.png)

Firefox 65.0 64bit, Kubuntu 18.04.01 64 bit
