### ISSUE TITLE
Installation and upgrades files checksums not provided

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#6872]
#### Issue
Checksums for installation and upgrades files not provided on https://suitecrm.com/download/ or easy accessed from this page.

#### Expected Behavior
Checksums for all installation and upgrades files should be provided on https://suitecrm.com/download/ (and related pages, for other versions and upgrades).

#### Actual Behavior
Checksums not provided.

#### Possible Fix
Checksums alongside Size and Format for each file.

#### Context
Checksums available only on https://sourceforge.net/projects/suitecrm/files/ (i icon for each file). Pretty hard to find...

**Comment by pgorod** [comment]
@bdcomp Why is this important to you?

Zip files typically give errors when unzipping, if they are incomplete or corrupted. So in the rare cases where this happens, you will just get a message pointing you to the need to download again.

**Comment by bdcomp** [comment]
Hi @pgorod, I still have an issue upgrading from 7.11.0 to 7.11.1 (https://suitecrm.com/suitecrm/forum/installation-upgrade-help/21687-7-11-0-7-11-1-upgrade-fail).
Yesterday I spend some several long minutes to just be sure there is no problem with the downloaded upgrade package...

As a simpler and fixed resolution (than the proposed possible fix that require an update for every release and file), a link to SourceForge with proper description, including the word "checksums", may be added to the SuiteCRM download pages.

**Comment by pgorod** [comment]
I like this suggestion of just adding a link, it's simple, easy to do and helpful.

For your own problem, remember you have the option of running a zip check using any Zip software outdoor. It's a good thing to try when you suspect a problem with the download.

Thanks

**Comment by pribeiro42** [comment]
@pgorod don't forget that file checksums are an easy way to tell if the download was tampered in some way...

**Comment by Dillon-Brown** [comment]
Put up a fix for the built-in MD5 array checksum functionality, I'll also look at adding a checksum to the download page on the main site for the next release.

**Comment by bdcomp** [comment]
Upgrade files still don't have checksum.

**Comment by Dillon-Brown** [comment]
@bdcomp Good point, I'll make sure to add that into the release process for 7.11.7. Thanks.
