### ISSUE TITLE
Email Address Removed if email is forwarded using outlook

### ISSUE THREAD

**Issue by g-fantini** [salesagility/SuiteCRM#6882]
Email Address Removed if email is forwarded using outlook

#### Issue

If an email is forwarded using outlook, in the email body the email address of the original sender is removed from the email. 
The image below shows in the first part the actual email body, while the second what is expected.
![image](https://user-images.githubusercontent.com/32967023/52130682-c3666a00-2632-11e9-884a-770108314ad8.png)
#### Expected Behavior

 The email address of the original sender should be visible
#### Actual Behavior

 The email address of the original sender is not visible

#### Possible Fix

PR #6883 Created
#### Steps to Reproduce

1.Forward an email using Outlook
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Assessed :+1:
