### ISSUE TITLE
Typo in manifest.php of 7.11.x-to-7.11.1 upgrade package

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#6891]
#### Issue
There is a typo in manifest.php, line 56, of 7.11.x-to-7.11.1 upgrade package and an upgrade can't  be completed.

#### Expected Behavior
'from_dir' => 'SuiteCRM-Upgrade-7.11.x-to-7.11.1',

#### Actual Behavior
'from_dir' => 'SuiteCRM-Upgrade-7.11-x-to-7.11.1',

#### Possible Fix
Change a dash to dot before the letter x.

#### Context
Thanks for the forum user asimolin for finding this typo.

I and several other people can't complete an upgrade:
1. https://suitecrm.com/suitecrm/forum/installation-upgrade-help/21687-7-11-0-7-11-1-upgrade-fail
2. https://suitecrm.com/suitecrm/forum/installation-upgrade-help/21700-problem-upgrading-from-7-11-0-to-7-11-1

If this is the reason for an upgrade fails, this issue should be a high priority.

**Comment by Dillon-Brown** [comment]
Hi @bdcomp, this has now been resolved. Thanks.
