### ISSUE TITLE
'MySettings' is not defined in $beanList

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#690]
We have many times this issue ('MySettings' is not defined in $beanList) if i want sort by some records in subpanels:

For example now in History subpanel:

![history](https://cloud.githubusercontent.com/assets/5773777/11253181/5227d114-8e3a-11e5-8fff-1b405ef2f067.png)

But when i refresh the page and try again sort by some value (like subject or name) it is working without problem. Could you hep us ?

**Comment by willrennie** [comment]
I cannot replicate your issue in a fresh install of SuiteCRM. Please post this question in the forums: https://suitecrm.com/forum/index, with details on your CRM/environment versions and full details on the process you are following. If it is identified as a core bug, we can re-open the issue.
