### ISSUE TITLE
In Campaign view status page, row is out of box

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6904]
#### Issue

It was fixed before, but it comes back again in new version
![screenshot_1](https://user-images.githubusercontent.com/22373035/52406300-6a894c80-2ade-11e9-8942-3f216e050320.png)

#### Possible Fix

Fixed #2341

#### Steps to Reproduce

1. Open campaign view status page
2. Look at the box.

#### Your Environment

* SuiteCRM Version used: 7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 65
* Environment name and version (e.g. MySQL, PHP 7): Php 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by dursuntosun** [comment]
When i check 7.11.2, the problem exist for this version?

**Comment by Dillon-Brown** [comment]
@dursuntosun I can't seem to replicate. It's working for me on the demo also:

https://demo.suiteondemand.com/
User: will
Pass: will

Have you checked that your instance has the code changes in #6906?

**Comment by dursuntosun** [comment]
> 
> 
> @dursuntosun I can't seem to replicate. It's working for me on the demo also:
> 
> https://demo.suiteondemand.com/
> User: will
> Pass: will
> 
> Have you checked that your instance has the code changes in #6906?

Yes, when i check upgrade package, the code does not changed. How can i control it via demo site. I could not create campaign?

**Comment by Dillon-Brown** [comment]
@dursuntosun If you get to step 3 of a campaign you can hit cancel and it will create it even if you don't have things like emails setup, that's normally how I create one for testing on demo. I've checked the upgrade packs on sourceforge and suitecrm.com and they do seem to contain this code.

Potentially something went wrong when you were downloading, we did update the packs to remove the /vendor/elasticsearch tests for issue #6978. I would re-try the upgrade and see if the code gets updated.
