### ISSUE TITLE
File OAuth2Tokens/metadata/editviewdefs.php is Missing 

### ISSUE THREAD

**Issue by djeraseit** [salesagility/SuiteCRM#6915]
Fatal error is being thrown in the logs, also checked github on here and the file is missing

#### Issue
Fri Feb  8 07:08:10 2019 [8415][1][FATAL] Error: File [modules/OAuth2Tokens/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.

#### Expected Behavior
File should be present
#### Actual Behavior
suitecrm.log is showing this error
#### Possible Fix
Add the file
#### Steps to Reproduce
1. Create or Edit Oauth2 Token

#### Context
Low bug but easy fix. Causes fatal error.
#### Your Environment

* SuiteCRM Version used: Latest

**Comment by yogeshbhade20** [comment]
@djeraseit Where did you find the editviewdefs.php file for OAuth2Tokens modules ?

can you share it with me ?

**Comment by cameronblaikie** [comment]
Hi @djeraseit 

I have created a fix for this issue if you could try out and see how it works for you?

Thanks
