### ISSUE TITLE
Exporting Hebrew Reports results in Gibberish

### ISSUE THREAD

**Issue by Mayansis** [salesagility/SuiteCRM#6917]
#### Issue
Exporting reports with Hebrew characters to Excel results in "Gibberish" / No-meaning words characters in Excel.

#### Expected Behavior

After clicking "Export" on a report with Hebrew characters, excel report would be in proper Hebrew, and look the same as it looks on the report. 

#### Actual Behavior

After clicking "Export" on a report, an excel with gibberish words comes out. 

#### Possible Fix
A module that you install on your computer/excel and translates it to proper Hebrew

#### Steps to Reproduce

1. Click "Export" on a report on SUITECRM with Hebrew Characters
2. Open the Excel File
3. See a lot of gibberish and no-meaning words in Excel (that's not hebrew) 

#### Context

Users usually export Hebrew reports and that's making life hell for them. Medium priority. 

#### Your Environment

*Version 7.8.5
Sugar Version 6.5.24 (Build 509)
* Chrome Version 51.0.2704.63 (64-bit)
* Windows 10
![image](https://user-images.githubusercontent.com/47449166/52477108-74c44d00-2ba9-11e9-9bcb-73279af1487e.png)

**Comment by Dillon-Brown** [comment]
Hi @Mayansis, this doesn't look like a core SuiteCRM issue:

![test_csv](https://user-images.githubusercontent.com/26431166/52478681-0e85fd00-2b9e-11e9-8d76-77d91d903fbf.png)

The csv is getting exported correctly from SuiteCRM but improperly imported to excel:

https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-csv-file-of-hebrew-language/8963c913-fb3d-4f22-866e-d373366ba196
