### ISSUE TITLE
Detailview of Emails - Links issues

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#692]
1. Reported  #686 

2. Is it possible to assign Email to other user ? 

3. The issue of related link. Need to be linked on module (this email on image was imported via Emails box)

![user](https://cloud.githubusercontent.com/assets/5773777/11266328/190789aa-8ea4-11e5-9d37-bdd0bccdf4bf.png)

**Comment by samus-aran** [comment]
1 and 3 should be resolved from the latest fix.

2. Not by default no.  You can extend the Emails module to appear in Studio and create a one to many relationship if you desire but there is no logic that will link the two toegther automatically.  With regards to showing a link in the DetailView for the email addresses to their corresponding Contact/Account this is not in the system currently so this will need to be considered.
