### ISSUE TITLE
Verbose logs for popErrorLevel

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#6921]
I am not quite sure why these two function are pushing out logs at warn/error levels. It just feeds the logs with repetitive useless messages in prod.

https://github.com/salesagility/SuiteCRM/blob/master/include/StateSaver.php#L302-L329

**Comment by Dillon-Brown** [comment]
Agreed, we really need to take a proper look at the logging. The warn/errors are quite excessive.

**Comment by pgorod** [comment]
Just a tip: if possible, none of our log messages should include the words `error`, `warning` etc in them. This makes _grepping_ for messages troublesome.

So a string about `error_reporting` will come up in a grep for `error` even if it is a warning or notice message - not good.

**Comment by isleshocky77** [comment]
Just noting here that (I believe) this issue is about the non-stop outputting of

```
Wed Mar 13 12:13:46 2019 [1642][1][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Wed Mar 13 12:13:46 2019 [1642][1][ERROR] Pop error level. Try to remove the error_reporting() function from your code.
```

It looks like there are couple of places that modules (recently) have set `error_reporting()` which shouldn't be.
