### ISSUE TITLE
problems on the Projet taks

### ISSUE THREAD

**Issue by ballapd** [salesagility/SuiteCRM#695]
Hello, 

when I want to create a Project Task, I pull the button "Create" the following will appear on the address bar: 
http://MYWEBSITE/suitecrm/index.php

**Comment by samus-aran** [comment]
Hi there, if you have any troubleshooting questions please register and post on our forums.  We usually tend to keep documented bugs on Github just to ensure you get the right help.

https://suitecrm.com/forum/index

**Comment by willrennie** [comment]
As @samus-aran stated, your question should be asked on our support forums: https://suitecrm.com/forum/index
