### ISSUE TITLE
Fail to create mail record / editviewdefs.php] is missing

### ISSUE THREAD

**Issue by 3dsup** [salesagility/SuiteCRM#6951]
Hello
I have clean install of SUITECRM
Version 7.11.1
Sugar Version 6.5.25 (Build 344)
and I have the following problem with suitecrm: 

------ If I go to emails from any menu--------------

EMAILS
You currently have no records saved. CREATE or Import one now.    ---- This all seem correct so far 

--------- This all seem correct so far, but when I press CREATE -------------------

Error: File [modules/Home/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.

------------If I press Import---------------

Imports aren't set up for this module type
Try Again

----------------------------------------------

I have checked the info posted here http://github.com/salesagility/SuiteCRM/issues/6767
but didn't really found any solution that works for me
I am running 

PHP Version 7.2.14

System	Linux s 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
Build Date	Jan 20 2019 00:19:35
Configure Command	'./configure' '--prefix=/opt/alt/php-fpm72/usr' '--with-config-file-path=/opt/alt/php-fpm72/usr/php' '--with-config-file-scan-dir=/opt/alt/php-fpm72/usr/php/php.d' '--with-zlib=/usr' '--enable-mbstring' '--enable-zip' '--enable-bcmath' '--enable-pcntl' '--enable-ftp' '--enable-exif' '--enable-calendar' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--with-tidy' '--with-curl' '--with-iconv' '--with-gmp' '--with-pspell' '--with-gd' '--with-jpeg-dir=/usr' '--with-freetype-dir=/usr' '--with-png-dir=/usr' '--enable-gd-native-ttf' '--enable-gd-jis-conv' '--with-zlib-dir=/usr' '--with-xpm-dir=/usr' '--with-openssl' '--with-pdo-mysql=mysqlnd' '--with-gettext=/usr' '--with-bz2=/usr' '--with-recode=/usr' '--with-mysqli' '--enable-soap' '--enable-phar' '--with-xsl' '--with-xmlrpc' '--with-kerberos' '--enable-posix' '--enable-sockets' '--with-pcre-regex' '--with-libdir=lib64' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--enable-intl' '--with-icu-dir=/usr' '--enable-fpm' '--enable-opcache'
Server API	FPM/FastCGI
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/opt/alt/php-fpm72/usr/php
Loaded Configuration File	/opt/alt/php-fpm72/usr/php/php.ini
Scan this dir for additional .ini files	/opt/alt/php-fpm72/usr/php/php.d
Additional .ini files parsed	/opt/alt/php-fpm72/usr/php/php.d/apcu.ini, /opt/alt/php-fpm72/usr/php/php.d/ioncube.ini, /opt/alt/php-fpm72/usr/php/php.d/opcache.ini
PHP API	20170718
PHP Extension	20170718
Zend Extension	320170718
Zend Extension Build	API320170718,NTS
PHP Extension Build	API20170718,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	enabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	disabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip, upload
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
Zend logo This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.4, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.14, Copyright (c) 1999-2018, by Zend Technologies
Configuration
apcu
APCu Support	Enabled
Version	5.1.12
APCu Debugging	Disabled
MMAP Support	Enabled
MMAP File Mask	no value
Serialization Support	php
Build Date	Jan 20 2019 00:22:05
Directive	Local Value	Master Value
apc.coredump_unmap	Off	Off
apc.enable_cli	Off	Off
apc.enabled	On	On
apc.entries_hint	4096	4096
apc.gc_ttl	3600	3600
apc.mmap_file_mask	no value	no value
apc.preload_path	no value	no value
apc.serializer	php	php
apc.shm_segments	1	1
apc.shm_size	32M	32M
apc.slam_defense	On	On
apc.smart	0	0
apc.ttl	0	0
apc.use_request_time	On	On
apc.writable	/tmp	/tmp
bcmath
BCMath support	enabled
Directive	Local Value	Master Value
bcmath.scale	0	0
bz2
BZip2 Support	Enabled
Stream Wrapper support	compress.bzip2://
Stream Filter support	bzip2.decompress, bzip2.compress
BZip2 Version	1.0.6, 6-Sept-2010
calendar
Calendar support	enabled
cgi-fcgi
php-fpm	active

-----------I believe the problem is in the suiteCRM code or the missing files are missing for real. I am not code writer but if someone is willing to help I will implement some changes if that would be the solution or if there would be update that would fix this issue if it's common I will wait for it

Thank you

**Comment by Dillon-Brown** [comment]
Hi @3dsup, this is an issue but it shouldn't actually effect anything aside from showing this message. When you have an inbound email account setup then you will no longer see the "CREATE or import now" option and will instead see a list-view populated with emails.

This is happening as a standard list-view expects you to be able to create/import records with an edit view but you obviously can't create/send emails until you have a mail account setup.

**Comment by 3dsup** [comment]
Yes it is all working now.
It seem like bug, yes.
Thank you!
