### ISSUE TITLE
Emails can't be answered after import

### ISSUE THREAD

**Issue by dfdezm** [salesagility/SuiteCRM#6962]
I am using version 7.10.11. Once an email appears in the history of an account, ACTIONS button does not show the options to reply or interact with the email. 

#### Issue
Users can't reply emails once they are imported and accessible in the HISTORY subpanel. The list of options in the ACTION button are very limited:
![image](https://user-images.githubusercontent.com/47668682/52866137-5973b780-313e-11e9-952f-db3ec1a46349.png)
But they can be imported an answered directly from the EMAILS module list view (BEFORE they are imported)
Other than that, all users are able to send new emails, receive, import...

#### Expected Behavior
To be able to Reply or Forward the email:
![image](https://user-images.githubusercontent.com/47668682/52866194-79a37680-313e-11e9-9979-6be253723b60.png)

#### Actual Behavior
It is not possible to resend or reply to emails after they are imported.
![image](https://user-images.githubusercontent.com/47668682/52866137-5973b780-313e-11e9-952f-db3ec1a46349.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment
SuiteCRM Version 7.10.12
Sugar Version 6.5.25 (Build 344)
Windows

**Comment by Mausino** [comment]
@dfdezm I tested this issue on 7.11.2 and it's working for me.

![2019-03-06_0028](https://user-images.githubusercontent.com/5773777/53844703-de682900-3fa6-11e9-937a-4335b43ef25e.png)

**Comment by Dillon-Brown** [comment]
Hi @dfdezm, I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate on the latest versions and we will investigate further. Thanks.
