### ISSUE TITLE
studio layouts new panel and new row not working.

### ISSUE THREAD

**Issue by zhaoxiong123** [salesagility/SuiteCRM#6969]
studio layouts new panel and new row not working. version is 7.11.1

**Comment by zhaoxiong123** [comment]
the chrome and safari both not working

**Comment by zhaoxiong123** [comment]
![xnip2019-02-19_18-03-57](https://user-images.githubusercontent.com/3273395/53006759-cf468e80-3470-11e9-86ee-dc5bd43953e3.jpg)

**Comment by cameronblaikie** [comment]
Hi there @zhaoxiong123 
I have tested this and I replicate this, both 'New Panel' and New Row' work for me. Could you fill the template out with detail so we can test this further?

**Comment by zhaoxiong123** [comment]
I am use the master brache, not found console js error...

**Comment by zhaoxiong123** [comment]
i'm so sorry , this question is my fault ， i think the new panel and new row button only for click ^_^

**Comment by zukijuki** [comment]
Hi @zhaoxiong123 

Could you tell me what's the solution for this?

Thank You in Advance...
