### ISSUE TITLE
Can't create new user in 7.11.1 - asks for confirmation password

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#6970]
#### Issue

Cannot create a new User because the UI says "Please enter your password confirmation." No passwords fields are shown and the user should be given a system-generated password.

#### Expected Behavior

The user should be a system-generated password and be required to change it on first login.

#### Actual Behavior

UI says "Please enter your password confirmation."

#### Steps to Reproduce

1. Fresh install of 7.11.1
2. Try to add a new user.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 72.0.3626.109 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7.25-0ubuntu0.18.04.2 (Ubuntu) & PHP 7.2.15-0ubuntu0.18.04.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by Dillon-Brown** [comment]
Hi @nelem, this should be resolved with #6779.

**Comment by nelem** [comment]
The confirmation password can, in fact, be added on the password tab and the user can be created. The first password is already set but can only be seen as dots. You just need to replace both passwords.

IIRC, in 7.8.x, creating a new user set a system-defined password rather than an explicit password. It also set the system_password flag to force the user to change it on first login.

**Comment by Dillon-Brown** [comment]
Closing in favour of #6997
