### ISSUE TITLE
Currency conversion error - calculated fields (workflow)

### ISSUE THREAD

**Issue by DominiekL** [salesagility/SuiteCRM#6972]
I have created a very simple workflow ("Calculated Fields") on opportunities > For us, the "weighed value" of an opportunity = the amount on this opportunity * probability and has been set up as follows:

![img1](https://user-images.githubusercontent.com/10184706/53032218-b89f3800-346e-11e9-97c3-2dc4eabc2d27.png)
![img2](https://user-images.githubusercontent.com/10184706/53032240-c359cd00-346e-11e9-8e54-dbfcc123d1b3.png)

Euro has been set up as base currency in our system. When I create an opportunity in Euro, the above set up logic is triggered correctly:

![img3](https://user-images.githubusercontent.com/10184706/53032250-c785ea80-346e-11e9-990a-7effc759aea0.png)

But, when I try to create an opportunity in USD, the calculated value misbehaves in a very optimistic way:

![img4](https://user-images.githubusercontent.com/10184706/53032300-e3898c00-346e-11e9-87a8-7645f729a2e0.png)

Did I do something wrong with my workflow setup, or did I discover a glitch in SuiteCRM?

Oh yes, before you ask it: yes, I think I have set up the currency conversion correctly...

![img5](https://user-images.githubusercontent.com/10184706/53032358-0025c400-346f-11e9-8487-8d2d5dd4d61b.png)

#### Your Environment

* SuiteCRM Version used: 7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 65.0.1
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):

**Comment by DominiekL** [comment]
Update: it seems it has to do with formatting. When I take " " instead of "." as separator for thousand, and "." instead of "," as separator for decimals, everything works fine...

**Comment by TelevicDominiek** [comment]
After some further testing: if I leave the 1000s separator blank (" "), everything works fine (no matter if I use , or . as decimal separator). The system seems to mess up when a combination of . and , is used.

**Comment by cameronblaikie** [comment]
Hi @DominiekL , 
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. 
Thanks.
