### ISSUE TITLE
Imported Email "Date Sent/Received" is incorrect

### ISSUE THREAD

**Issue by srobinet** [salesagility/SuiteCRM#6973]
#### Issue
After adding the "Date Sent/Received" column in the Studio so I can see the date sent/received in Email details (e.g. the detail view of an imported email attached to a project) the date is incorrect.  For example, the date may appear as "02/11/2019" when in reality the email was sent "12/22/2018".  An interesting fact is once I do a rebuild then refresh the email details page, the date is correct, but then that date is displayed for EVERY email detail page afterwards.

#### Expected Behavior
The correct date sent/received to be displayed for the email.

#### Actual Behavior
The date sent/received value is incorrect, apparently random, until a rebuild, then the dates are correct for one email but that date then propagates to every other email.

#### Possible Fix

Not sure but seems to be a caching or stale value issue of some kind.

#### Steps to Reproduce

Make sure you've used Studio to add the Date Sent/Received row to the Email Details view.
1.  Import an email from, say, Dec 10 2018 and attach it to a project (though it doesn't seem to matter what record it is related to)
2. Go to the project History and click the email to view its details
3. The date will be something apparently random
4. In a separate page, do a Quick Rebuild
5. Refresh the email details view and note the Date Sent/Received is now correct (Dec 10 2018)
6. Go to another imported email and note the Date Sent/Received is the SAME date as the one in step 5.

#### Context

Low priority, but it does cause issues with the staff that the emails are "dated wrong" (they really aren't, the value is correct in the db)

#### Your Environment

* SuiteCRM Version used: 7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.60, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Centos 7.2.12

**Comment by ralfhauser** [comment]
we have the same problem with
Version 7.10.7
Sugar Version 6.5.25 (Build 344)

**Comment by srobinet** [comment]
Is there documentation available about how the Studio Builder works in conjunction with collecting the values for each field to be displayed?  If I could figure out a place to start, I'd be up for trying to track this down.

**Comment by srobinet** [comment]
I can see in the cached template why it is doing what it is doing:

*./cache/themes/SuiteP/modules/Emails/EmailsDetailView.tpl*
```
<div class="col-xs-12 col-sm-10 detail-view-field " type="datetime" field="date_sent_received" colspan='3' >

{if !$fields.date_sent_received.hidden}
{counter name="panelFieldCount" print=false}


{assign var="value" value=12/20/2018 }
<span class="sugar_field" id="{$fields.date_sent_received.name}">{$value}</span>
{/if}
```

As can be seen the value is being hard-coded.  Changing `2018-05-10` to `$fields.date_sent_received.value` solves the problem; at least until the cache is updated.  Then it'll be a different hard-coded date.  

I'm not sure where the code responsible for generating this cache file resides to further diagnose the issue.  I'll keep looking but if anyone has some insight, it'd be much appreciated!

**Comment by srobinet** [comment]
This section of code might have something to do with it?  It's populating the 'date_formatted_value' element :
https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/include/SugarFields/Fields/Datetime/SugarFieldDatetime.php#L204-L214

Then, as a result that value is used in the tpl file and ends up in the cache:
https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/include/SugarFields/Fields/Datetime/DetailView.tpl#L46-L54
