### ISSUE TITLE
Error workflow  module Notes

### ISSUE THREAD

**Issue by felvas** [salesagility/SuiteCRM#6974]
#### Issue

I have created a workflow to notify me when a note meets three conditions. When it runs in the suitecrm log, the following appears:

Tue Feb 19 20:00:18 2019 [9804][1][FATAL]  Query Failed:  SELECT  notes.* ,notes_cstm.consecutivo_oferta_c,notes_cstm.estado_c,notes_cstm.note_id_c,notes_cstm.publicacion_c,notes_cstm.servicio_c,notes_cstm.tipo_c,notes_cstm.tipo_oferta_c,notes_cstm.vigencia_c , jt0.user_name assigned_user_name , jt0.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod , jt1.user_name modified_by_name , jt1.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt2.user_name created_by_name , jt2.created_by created_by_name_owner  , 'Users' created_by_name_mod , LTRIM(RTRIM(CONCAT(IFNULL(contacts.first_name,''),' ',IFNULL(contacts.last_name,'')))) contact_name , contacts.assigned_user_id contact_name_owner  , 'Contacts' contact_name_mod, jt4.name remplaza_oferta_c  FROM notes  LEFT JOIN notes_cstm ON notes.id = notes_cstm.id_c   LEFT JOIN  users jt0 ON notes.assigned_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON notes.modified_user_id=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON notes.created_by=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0  LEFT JOIN  contacts contacts ON notes.contact_id=contacts.id AND contacts.deleted=0

 AND contacts.deleted=0 LEFT JOIN notes jt4 ON notes_cstm.note_id_c = jt4.id AND jt4.deleted=0  where (parent_type = 'Emails' AND parent_id = 'adbecb82-612f-816b-1620-579bbed8faf7') AND notes.deleted=0: MySQL error 1052: Column 'parent_type' in where clause is ambiguous

#### Expected Behavior

you must execute the workflow

#### Actual Behavior

does not trigger the workflow action and throws error 

Tue Feb 19 20:00:18 2019 [9804][1][FATAL]  Query Failed:  SELECT  notes.* ,notes_cstm.consecutivo_oferta_c,notes_cstm.estado_c,notes_cstm.note_id_c,notes_cstm.publicacion_c,notes_cstm.servicio_c,notes_cstm.tipo_c,notes_cstm.tipo_oferta_c,notes_cstm.vigencia_c , jt0.user_name assigned_user_name , jt0.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod , jt1.user_name modified_by_name , jt1.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt2.user_name created_by_name , jt2.created_by created_by_name_owner  , 'Users' created_by_name_mod , LTRIM(RTRIM(CONCAT(IFNULL(contacts.first_name,''),' ',IFNULL(contacts.last_name,'')))) contact_name , contacts.assigned_user_id contact_name_owner  , 'Contacts' contact_name_mod, jt4.name remplaza_oferta_c  FROM notes  LEFT JOIN notes_cstm ON notes.id = notes_cstm.id_c   LEFT JOIN  users jt0 ON notes.assigned_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON notes.modified_user_id=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON notes.created_by=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0  LEFT JOIN  contacts contacts ON notes.contact_id=contacts.id AND contacts.deleted=0

 AND contacts.deleted=0 LEFT JOIN notes jt4 ON notes_cstm.note_id_c = jt4.id AND jt4.deleted=0  where (parent_type = 'Emails' AND parent_id = 'adbecb82-612f-816b-1620-579bbed8faf7') AND notes.deleted=0: MySQL error 1052: Column 'parent_type' in where clause is ambiguous

#### Context

High priority

#### Your Environment
SuiteCRM: Versión 7.8.26  -- Sugar Versión 6.5.25 (Compilación 344)
Google Chrome Versión 70.0.3538.77 (Build oficial) (64 bits)
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2018-10-10T18:59:25
mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Ubuntu 18.04.2 LTS

**Comment by willrennie** [comment]
@felvas Please can you construct and detail your issue using the issue template that is provided. Providing the description for your bug, context, steps to reproduce etc. We will then assess your issue further.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity
