### ISSUE TITLE
Hosting company is blocking ports because of YamlRunnerTest.php

### ISSUE THREAD

**Issue by LuminisIndia** [salesagility/SuiteCRM#6978]
I got the following email from hostgator that there are some unwanted files in cache of suitecrm.

Issue
`Dear Customer,

As provider of Shared Hosting services, we monitor the usage of all our customers to ensure that our Quality of Service is not adversely affected. Our goal is to ensure that one customer should not affect all the other customers on the same server.

As part of our routine monitoring, we have observed that some of the files hosted on this server belonging to luminisindia.com hosted under your account, has some malicious files hosted. In order to prevent blacklisting of our service with various service providers, we have blocked outbound port 80, 443, 587 and 465 for this domain name as a precautionary measure. Here are the details of the files that were detected to be malicious.

/home/luminisi/public_html/SuiteCRM/cache/upgrades/temp/0n48Sr/SuiteCRM-Upgrade-7.10.x-to-7.11.1/vendor/elasticsearch/elasticsearch/tests/Elasticsearch/Tests/YamlRunnerTest.php /home/luminisi/public_html/SuiteCRM/cache/upgrades/temp/6L7azM/SuiteCRM-Upgrade-7.10.x-to-7.11.1/vendor/elasticsearch/elasticsearch/tests/Elasticsearch/Tests/YamlRunnerTest.php /home/luminisi/public_html/SuiteCRM/cache/upgrades/temp/LQNCgU/SuiteCRM-Upgrade-7.10.x-to-7.11.1/vendor/elasticsearch/elasticsearch/tests/Elasticsearch/Tests/YamlRunnerTest.php /home/luminisi/public_html/SuiteCRM/cache/upgrades/temp/XX0wpX/SuiteCRM-Upgrade-7.10.x-to-7.11.1/vendor/elasticsearch/elasticsearch/tests/Elasticsearch/Tests/YamlRunnerTest.php /home/luminisi/public_html/SuiteCRM/vendor/elasticsearch/elasticsearch/tests/Elasticsearch/Tests/YamlRunnerTest.php

We have currently altered the permissions of the files so that they become immutable. This means you will not be able to read or write to the file.

We strongly suggest you to scan all the above listed files for any vulnerabilities. If the files are part of some plugins of your CMS, then we suggest you to update the plugin to the latest version or contact the plugin developer directly.

Please treat this as an alert to take immediate action and remove the malicious file(s) within the next 48 hours. If we detect malicious files in your account again, we will be taking strict action against the domain which might cause disruption of the service
`

#### Steps to Reproduce

1.
2.
3.
4.

#### Context
This issue has been raised at forums: [https://suitecrm.com/suitecrm/forum/feedback/21635-hosting-company-detects-php-exe-globals-malware-in-suitecrm-file](url)

#### Your Environment

* SuiteCRM Version used: 7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 72.0.3626.109 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL and PHP 7.1
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
@Dillon-Brown I believe this issue is caused by not using `--no_dev` when running composer to install/update packages. 

The problematic file is in a `tests` directory which should not be there when we're just using ElasticSearch.

But can we make this less dependent on that flag? Can we make `composer` default to `--no-dev`? Or specify in our composer.json that `elasticsearch` is always `--no-dev` regardless of command-line flags?

**Comment by Dillon-Brown** [comment]
@pgorod The --no-dev flag shouldn't matter here. That flag only specifies which packages to pull down and  skip installing packages listed in require-dev. Since elasticsearch is under "require" this file is always going to be pulled down.

**Comment by Dillon-Brown** [comment]
I've updated the upgrade packs and installer to exclude this file but there's nothing stopping someone from running a `composer install --no-dev``` and re-downloading this file....
