### ISSUE TITLE
Editing records from Dashlet 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#698]
If you edit records from Dahhlets (via pen icon), 

and it takes you into the editview of record, and after save button take you back to dashlet :) 

that it's ok, but after delete or cancel button take you to listview of records. and this is weird behavior :-1:  i think, that will great, if it takes you back to dashlets view again (after cancel or delete)

**Comment by JimMackin** [comment]
Duplicate of #893.
