### ISSUE TITLE
Can not query any standard fields using get_entry_list using REST 4.1 API

### ISSUE THREAD

**Issue by apoonawa** [salesagility/SuiteCRM#6988]
if you try to submit a get_entry list request via REST 4.1 API and include a WHERE clause, any clause including a standard field fail.  
Have noticed this behavior in the latest release.

#### Issue

When submitting a 'get_entry_list' request via REST 4.1 API,
For example if you query "first_name = 'John'" it returns nothing even though the record exists..
However, if you create a custom field "fname_c" and query "fname_c = 'John'", it works as expected.
This is true for all standard fields, including last_name, birthdate, email1 etc. None of them work.
#### Steps to Reproduce

1.
2.
3.
4.

#### Context

We recently tried updating and we heavily use REST 4.1 API with other software that interacts with SuiteCRM. I think it is a high priority.

#### Your Environment

* SuiteCRM Version used:
7.11.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Chrome
* Environment name and version (e.g. MySQL, PHP 7):
MySql php 7
* Operating System and version (e.g Ubuntu 16.04):
Centos 5

**Comment by ChangezKhan** [comment]
@apoonawa I tried the same and I am able to fetch the details properly. Kindly share your request in detail. This is my request 


    $get_entry_list_parameters = array(
        //session id
        'session' => $session_id,

        //The name of the module from which to retrieve records
        'module_name' => 'Leads',

        //The SQL WHERE clause without the word "where".
        'query' => "leads.first_name = 'Sohan'",

        //The SQL ORDER BY clause without the phrase "order by".
        'order_by' => "",

        //The record offset from which to start.
        'offset' => 0,

        //A list of fields to include in the results.
        'select_fields' => array(
            'id',
            'first_name',
            'last_name',
        ),

        //A list of link names and the fields to be returned for each link name.
        'link_name_to_fields_array' => array(),

        //The maximum number of results to return.
        'max_results' => '',

        //If deleted records should be included in results.
        'deleted' => 0,
    );

    $result = call('get_entry_list',$get_entry_list_parameters);

    echo "<pre>";print_r($result);echo "</pre>";
 

I think issue must be with your where query. Kindly check that and let me know if you need any help.

**Comment by Dillon-Brown** [comment]
Unable to replicate on latest hotfix/LTS
