### ISSUE TITLE
Exporting reports to excel and not CSV

### ISSUE THREAD

**Issue by Mayansis** [salesagility/SuiteCRM#6989]
Hi,

I can only export reports to CSV. How do I export reports to XLSX (Excel document)?

Thanks in advance

#### Your Environment
*Version 7.8.5
Sugar Version 6.5.24 (Build 509)

* Chrome Version 51.0.2704.63 (64-bit)
* Windows 10

**Comment by Dillon-Brown** [comment]
Hi @Mayansis, you can only export reports as a PDF or CSV however you can simply take the CSV and import it to excel to convert it:

https://www.ablebits.com/office-addins-blog/2014/05/01/convert-csv-excel/

This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum). We use GitHub primarily for the reporting of Core SuiteCRM bugs and leave general questions and setup specific issues to the forums.

Thanks.
