### ISSUE TITLE
[FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder

### ISSUE THREAD

**Issue by afnieves** [salesagility/SuiteCRM#6994]
[FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder
#### Issue
suitecrm.log filling up with this error message.
#### Expected Behavior
This should not happen a typo in the module is causing error.

#### Possible Fix
include/SugarFolders/SugarFolders.php
line 663
from  
if (empty($this->id)) {
to this
if (empty($bean->id)) {

This corrects the problem I tested it in 7.11.2 and 7.10.13

#### Your Environment
* SuiteCRM 7.10.13:
* Browser name and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Environment name and version MySQL , PHP 7): PHP 7.2.15, MYSQL 5.7.25
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04.2 LTS

**Comment by pgorod** [comment]
I agree there is a problem there, and I understand that the change you propose removes the error message. 

But I am not sure that is the correct fix. Testing for `$this->id` and for `$bean->id` are different things, and maybe that's what the original developer intended. That code has been like that for a _long_ time.

Possibly the problem comes from an earlier stage, when the Folder should be defined (and get an `id`) but for some reason, doesn't get filled properly. Note that the error message points exactly to that, not to some problem in the bean: `addBean() is trying to save to a non-saved or non-existent folder`.

**Comment by afnieves** [comment]
public function addBean(SugarBean $bean)
    {
        if (empty($bean->id) || empty($bean->module_dir)) {
            $GLOBALS['log']->fatal("*** FOLDERS: addBean() got empty bean - not saving");
            return false;
        }

        if (empty($bean->id)) {
            $GLOBALS['log']->fatal("*** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder");
            return false;
        }
     $guid = create_guid();

        $query = "INSERT INTO `folders_rel` " .
            "(`id`, `folder_id`, `polymorphic_module`, `polymorphic_id`, `deleted`) VALUES (" .
            $this->db->quoted($guid) . ", " .
            $this->db->quoted($this->id) . ", " .
            $this->db->quoted($bean->module_dir) . ", " .
            $this->db->quoted($bean->id) . ", 0)";

        return $this->db->query($query);
    }

$bean is passed into the function the first test passes the second test always fails using $this->id because is was always NULL.  The create_guid() is now working aswell.

**Comment by afnieves** [comment]
I just looked again the folder_id in folders_rel table is empty so it is still not right.

**Comment by pgorod** [comment]
Are you using a debugger? What is in the previous level in the stack frame, in the function that calls that one? Is the folder object properly initialized?

**Comment by afnieves** [comment]
Hi @pgorod 

What I am able to find out it looks like when the new inbound group account is created
the wrong guid is assigned to inbound_email.groupfolder_id and the folders.is_group is not being set to 1.  I have an old account in that does not produce FATAL FOLDERS error.  Here are the entries to the newly created account.  I manually change the inbound_email.groupfolder_id to match the guid and the errors stop.

Inbound email ID 
9fc6e330-0c4b-849d-e41d-5c76268ac294
Inbound email group folder ID
904f806a-879a-179b-a092-5c7626731acd

The above is change to match the correct folder guid of below and it stops errors

Folder ID for INBOX
9fc6e330-0c4b-849d-e41d-5c76268ac294
Folders(sub) for same account
draft (folder type)
ID: ad01a2a2-d1eb-7659-5925-5c7626c9a8f5 
Parent ID: 9fc6e330-0c4b-849d-e41d-5c76268ac294
sent (folder type)
ID: ad4bf252-41cd-096a-7a78-5c762652f002
Parent ID: 9fc6e330-0c4b-849d-e41d-5c76268ac294
archived (folder type) 
ID: ad884a1a-af1e-a594-9aef-5c762683ce12
Parent ID: 9fc6e330-0c4b-849d-e41d-5c76268ac294
NAME (no folder type)
ID: addea404-de85-226e-d139-5c7626a0a8c7

**Comment by pgorod** [comment]
So can you get us a list of "steps to reproduce" just for that part of the bug? Wrong GUID in folder creation?

Then I would ask @Dillon-Brown if he can perhaps take a look?

**Comment by afnieves** [comment]
1. Setup new instance 
2. Create a new inbound group email account.
3. Review the database records created.
select id, groupfolder_id from inbound_email;
+--------------------------------------+--------------------------------------+
| id                                   | groupfolder_id                       |
+--------------------------------------+--------------------------------------+
| 9fc6e330-0c4b-849d-e41d-5c76268ac294 | 9fc6e330-0c4b-849d-e41d-5c76268ac294 |
+--------------------------------------+--------------------------------------+
1 row in set (0.00 sec)
select id, folder_type, parent_folder from folders;
+--------------------------------------+-------------+--------------------------------------+
| id                                   | folder_type | parent_folder                        |
+--------------------------------------+-------------+--------------------------------------+
| 81f64625-91a9-7bcc-da8f-5c76f7b05360 | archived    | 9fc6e330-0c4b-849d-e41d-5c76268ac294 |
| 87037287-a18b-e830-e5c9-5c76f7c8b9fb | draft       | 9fc6e330-0c4b-849d-e41d-5c76268ac294 |
| 9fc6e330-0c4b-849d-e41d-5c76268ac294 | inbound     |                                      |
| e73709cc-120a-0206-0b4c-5c76f7408496 | sent        | 9fc6e330-0c4b-849d-e41d-5c76268ac294 |
+--------------------------------------+-------------+--------------------------------------+
4 rows in set (0.00 sec)


4. The above is how it looks and no errors when I forced groupfolder_id to match and set is_group to 1 on inbound folder.

This will show a working set or records.

SELECT ie.id, ie.groupfolder_id, f.id, f.folder_type, f.is_group 
FROM inbound_email ie 
LEFT JOIN folders f
ON ie.groupfolder_id = f.id;

**Comment by riotctrl** [comment]
So is the solution to make the id and the group id the same?

| id | groupfolder_id |
+--------------------------------------+--------------------------------------+
| 9fc6e330-0c4b-849d-e41d-5c76268ac294 | 9fc6e330-0c4b-849d-e41d-5c76268ac294 |

Please advise im getting 50k lines in my log every day because of this.

**Comment by jurgenhaas** [comment]
I have applied the changes suggested by @afnieves and the errors are gone from the logs but it doesn't show me any emails from group accounts in the UI.

**Comment by riotctrl** [comment]
> I have applied the changes suggested by @afnieves and the errors are gone from the logs but it doesn't show me any emails from group accounts in the UI.

Then this isnt a solution then?

**Comment by jurgenhaas** [comment]
I can't tell for sure if the issues are related. It could still be that email from group accounts are not loaded is caused by something else. But my guess is that the "fix" above avoids the error log entires but doesn't solve the problem.

**Comment by riotctrl** [comment]
I have 50k worth of error log lines.. so if this is the solution i want to know for sure.

**Comment by Chabi01** [comment]
Hi,
Same issue on my side here : trying to upgrade from 7.11.10 to 7.11.12 via Admin generate the error.
I get : 
Tue Mar 10 18:13:02 2020 [17531][1][FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder
I can't update Suitecrm...
Thanks for the help and ideas :)
Xavier

**Comment by aimran50** [comment]
I am seeing the same error logs in version 7.11.12 .

**Comment by Chabi01** [comment]
Hi,
On my side, impossible to upgrade the CRM. I had to reload a previous backup with no solutions to upgrade correctly.
I also use the help of my hoster who tried to help me directly (he tried to upgrade on a "copy" made from my own install : no more success on his side with the whole ressource from an host to check if this was the reason...)

Maybe in a future upgrade, maybe not, but unable to get any information to try to correct this issue on my side.

Xavier

**Comment by alexiscviurb** [comment]
Hi, I have the same issue with my installation in SuiteCRM version 7.11.10.
I believe this problem is the same as that reported in #4182

**Comment by pgorod** [comment]
@alexiscviurb is your problem also manifesting itself as an inability to upgrade, like @Chabi01? Or is it the FATAL error in the logs?

And this thing you mention about #4182, why do you say that? If you are seeing that bug, please update the other issue with "steps to reproduce" on the latest 7.11.x. Thanks for your help!

**Comment by alexiscviurb** [comment]
Hi @pgorod ! My problem is reported in the logs.

When I register a new inbound email account and mark the option of auto import, the folder for receiving the emails is not created. If you edit the receipt account, deselecting the option, saving, editing again and checking the option, the folder is created.

**Comment by Chabi01** [comment]
Hi, is there some news on this ? I would like to upgrade to 7.11.13 as i saw this last version correct some critical points...
How can i solve this ?
Could i try this : install a new instance of Suitecrm (via Softaculous for example) and then import the database from the 7.11.10 in the last version ? Is there difference in the databases from 7.11.10 and 7.11.13 ?
Thanks for the help, i'm quite worried with the "critical fixes"...
Xavier

**Comment by Chabi01** [comment]
Hi,
Is anybody have a clue on this ? 
If I cant upgrade, is there a possibility to reinject the existing database from 7.11.10 to the 7.11.13 ? 
Is there difference in the database for these 2 versions ?
Please give me some answer : again, i see "critical issues" are corrected in the 7.11.13 and i cant keep a tool with "critical issues"...
Thanks for any help on these questions :)
Xavier

**Comment by chris001** [comment]
Clearly, the bug is: "When I register a new inbound email account and mark the option of auto import, the folder for receiving the emails is not created."  So the code must be updated to create the folder, when you register a new inbound email account.

**Comment by Chabi01** [comment]
Hi Chris001.
Ok... even if I dont really understand what i can do with your information to allow me to upgrade : do you say "you have to wait an next upgrade" ?
If so, is there a way to upgrade manually : copy all the files, upgrade the database running manually the queries in the database ?
Thanks for your help :)
Xavier

**Comment by pgorod** [comment]
@Chabi01 you should just open a thread on the Forums with your Upgrade issue, it should be possible to get you through the upgrade. I recently worked on two upgrader issues so I know that code well by now.

**Comment by Chabi01** [comment]
Thanks :)
I will !
Best regards,
Xavier

**Comment by chris001** [comment]
If the code isn't able to be updated directly from the github repo, by doing a git command at the command line it might crash the application, then it should be made to be able to do this cleanly without crashing and work right. This would save many users time and work around installation package or installer code issues. You would know which version / branch you were running, with a higher degree of certainty.  Am I right?

**Comment by pgorod** [comment]
If you unzip any upgrade package and see all the scripts that get executed pre and post install, you'll see that simply pulling files from Git isn't a sufficient replacement.

I'd love to see better deployment options, but it _will_ take quite a lot of work. You'd have to replicate the executable parts somehow. For example: placing files in a certain directory would cause a scheduler to pick them up, execute them, and then remove them.

I'm all for it, but I see this as a sizeable project, not a simple thing at all...

**Comment by teix4603** [comment]
Following on afnieves solving advices and comments, I did the following and solved the issue. A correction of the bug still has to be made in the code but as long as you don't create a new group email the situation is solved.

//Put log error level to "DEBUG" to see where to problem comes from 

//We find in the log the id of the Group Email making errors
Sun Feb  7 16:08:09 2021 [62076][1][DEBUG] *********** InboundEmail doing dupe check.
Sun Feb  7 16:08:09 2021 [62076][1][INFO] Query:SELECT count(emails.id) AS c FROM emails WHERE emails.message_id = 'a83274e06a599fb1731a4640bde62728' and emails.deleted = 0
Sun Feb  7 16:08:09 2021 [62076][1][INFO] Query Execution Time:0.00019001960754395
Sun Feb  7 16:08:09 2021 [62076][1][DEBUG] InboundEmail found a duplicate email with ID (a83274e06a599fb1731a4640bde62728)
Sun Feb  7 16:08:09 2021 [62076][1][INFO] InboundEmail found a duplicate email: <1612457951929.a7d5ea6f-649b-4bcf-8029-c52e9ec45583@bf01x.hubspotemail.net>
Sun Feb  7 16:08:09 2021 [62076][1][INFO] Query:SELECT id from emails WHERE message_id ="a83274e06a599fb1731a4640bde62728"AND mailbox_id = "da8e17fa-f5ae-f5bd-839e-601e5e698aea"
Sun Feb  7 16:08:09 2021 [62076][1][INFO] Query Execution Time:0.00015783309936523
Sun Feb  7 16:08:09 2021 [62076][1][FATAL] *** FOLDERS: addBean() is trying to save to a non-saved or non-existent folder

// We set the Group Email to group Email where it is not correctly Set
UPDATE folders set is_group = 1 WHERE id = 'da8e17fa-f5ae-f5bd-839e-601e5e698aea' OR parent_folder = 'da8e17fa-f5ae-f5bd-839e-601e5e698aea' 

// We set the correct groupfolder_id
UPDATE inbound_email SET groupfolder_id='da8e17fa-f5ae-f5bd-839e-601e5e698aea' WHERE id = 'da8e17fa-f5ae-f5bd-839e-601e5e698aea' and groupfolder_id = 'd925c8e2-cb98-5e34-fecb-601e5ef57b76'
