### ISSUE TITLE
Thunderbird plug in by OPacus can not save emails to SuiteCRM

### ISSUE THREAD

**Issue by smokinjo** [salesagility/SuiteCRM#6995]
#### Issue
Since upgrading from 7.10.4 to 7.10.13, the opacus plug in no longer works for archiving emails to SuiteCRM.  I contacted the developpers and they found what seems to be a bug/issue.

#### Expected Behavior
The email is saved to a clients file in Suite CRM.

#### Actual Behavior
An error says log in credentials do not work.

#### Possible Fix

Upon exchanges with the developpers, they note:

The code is trying to log an object but as a string
Line 4736 of modules/Emails/Email.php

#### Steps to Reproduce

It happens when the latest version of the opacus thunderbird plug in is used.

#### Context

Medium, as it blocks all use of the plug in.

#### Your Environment

* SuiteCRM Version used:    7.10.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Fire fox v64
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7, MySQL
* Operating System and version (e.g Ubuntu 16.04): DEbian 9.x - Stretch

**Comment by Dillon-Brown** [comment]
Hi @smokinjo, this was fixed in v7.10.14.

Issue: #6916
Fix: #6922
