### ISSUE TITLE
7.11.2 Opportunity: Find Duplicates has limited option compared to other modules

### ISSUE THREAD

**Issue by parkerauk** [salesagility/SuiteCRM#7000]
#### Issue
Merging Opportunities is harder now there are fewer options to filter duplicate records on. In particular Name field is absent.

#### Expected Behavior
Consistent filtering across modules for finding duplicate records. At least to include Name field

#### Actual Behavior

Three random fields are now available to filter on.

#### Possible Fix
Add Name field (and others dropped from previous releases)

#### Steps to Reproduce
1. Open any Opportunity
2. Select Duplicates
3. Observe the restricted list of filter options

**Comment by willrennie** [comment]
Hi @parkerauk I'm unable to replicate this issue in a core 7.11.2 install. I get the options in the attached image when using the 'Find Duplicates' functionality.
![screenshot from 2019-03-01 17-14-01](https://user-images.githubusercontent.com/5641419/53654346-767fae80-3c45-11e9-9c3e-9475840fe060.png)

**Comment by parkerauk** [comment]
Will,


Interesting,


I get this


[cid:fdd16db3-6f91-4b48-9956-64ec39f187af]


For me there is no option to Match based upon the default of "Name", Nor "Type" from your list.


I wonder what determines if a field is to be used for duplicate selections?


Just to prove that it is an isolated issue everything works fine for Accounts


[cid:c09a9bf1-9f01-44f4-921c-c29eddc2e0aa]





________________________________

**Comment by samus-aran** [comment]
Hey @parkerauk unfortunately we can't see your uploads. Are you able to do that again?
I too am unable to replicate this on demo.suiteondemand.com but just to provide a bit of troubleshooting perhaps check if that field has been disabled for "Merge Filter" or if there is any customisations made to that field setting ['merge_filter'] in the vardefs?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity
