### ISSUE TITLE
7.11.2 upgrade vs installation version mis-match

### ISSUE THREAD

**Issue by tmuras** [salesagility/SuiteCRM#7001]
#### Issue
When downloading latest version of SuiteCRM from https://suitecrm.com/download - SuiteCRM 7.11.2, what you get is (as per suitecrm_version.php):

```
$suitecrm_version      = '7.11.2';
$suitecrm_timestamp    = '2019-02-19-17:00:00';

```

While when upgrading, using SuiteCRM-Upgrade-7.11.x-to-7.11.2 from https://suitecrm.com/upgrade-suitecrm, you get:

```
$suitecrm_version      = '7.11.2';
$suitecrm_timestamp    = '2019-02-20-17:00:00';
```

The resulting source code between those 2 is quite different, mainly because of the new package versions in vendor.

I would expect the upgrade and new installations to match each other. I do not see the version in the upgrade in the git repository:

```
$suitecrm_timestamp    = '2019-02-19-17:00:00';
```

**Comment by Dillon-Brown** [comment]
Hi @tmuras, I agree the timestamp should match whats in master. The issue here was that the 7.11.2 installer was built one day before the upgrade packs and was using ```composer update --no-dev``` instead of ```composer install --no-dev```.

This will be resolved in the next release. Thanks!

**Comment by nenorojas** [comment]
@Dillon-Brown Hi Dillon, would you know when is the next suitecrm release? Will it be 7.11.3 or will be version 8 directly?

**Comment by Dillon-Brown** [comment]
Hi @nenorojas, I don't have an exact date but there should be another minor release of 7.11.x + LTS fairly soon, before 8.0.x.
