### ISSUE TITLE
When using Double Quotes (") in the Quotes Line items they get replaced with &

### ISSUE THREAD

**Issue by kwonghk** [salesagility/SuiteCRM#7005]
#### Issue
When I am typing a Line item and want to reference a file/email/something with "" (i.e. please refer to document "document24.pdf") the first time I enter it, it will be saved correctly. If I return and edit the Quote, the Editor will replace the "double quote" symbol with `&quot;` in the Editor. 

If I didn't notice this change, and press save again, the double quote symbol is now saved as & and my exported PDF will be substituted with &

#### Expected Behavior
Try to parse the `&quot;` back to " correctly so I don't have to keep remembering to update those when I change something else with the Quotes. 

#### Actual Behavior
The &quot; becomes just & after save, making my line items marked with & instead of "

#### Steps to Reproduce

1. Create a new Quote
2. Add a line item and include something like "test" in the line item text box. 
3. Save the Quote, View the Line items. It displays the quote marks correctly. 
4. Edit the Quote. Change something else like Date or price. Notice the line item has replaced the " with `&quot;`
5. Press save again. Now look at Line items. The `&quot;` is now changed to just `&`. 
6. Edit the Quote again. The line item now just has the `&` inplace of the original `"`

#### Context
Just makes it a cumbersome to remember to correct `"` marks every time I update or change a quote

#### Your Environment
* SuiteCRM 7.10.x
* Firefox/Chrome browser
* CentOS 7.x 64bit PHP 71, httpd 2.2
* CentOS 7.x

**Comment by Dillon-Brown** [comment]
Hi @kwonghk, this was resolved in SuiteCRM v7.10.4 here: #4230.
