### ISSUE TITLE
PDF Templates still using old 3.5.x TinyMCE instead of lastest one

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#7007]
#### Issue

In PDF Template you'll see the old TinyMCE editor.... but in system was update to last one.
For example, the Email Templates using the latest one. 

#### Expected Behavior

Can use latest TinyMCE

#### Actual Behavior

There is old one. 

#### Your Environment

* SuiteCRM Version used: 7.11.2 Official Demo
* Browser name and version : Chorme 72.x

**Comment by Dillon-Brown** [comment]
I think this is a duplicate of your other issue #7007 :)
