### ISSUE TITLE
When new user accesses for the first time he is prompted to confirm time zone

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#7011]
#### Issue

When new user accesses SuiteCRM he has to go through a wizard to confirm or edit some of his settings.

After finishing the to run the wizard, as soon as he clicks on any link in SuiteCRM he is redirected to a window prompting to confirm his timezone:
![2019-03-02_125957](https://user-images.githubusercontent.com/8026129/53681582-e6e10b00-3ceb-11e9-8568-9765b2fa5398.jpg)

Unless this a an explicitly wanted behaviour, this should not happen because the wizard has just requested for a few settings, including the timezone.

When the user saves the timezone from this screen the issue is resolved.

When finishedfor the first time he is prompted to confirm time zone
#### Expected Behavior

After running the wizard upon first login the screen prompting to confirm the timezone should not appear.

#### Actual Behavior

Nothing in the logs.
When a user logins for the first time he is first guided through a wizard to modify/edit/confirm his settings.
After the wizard is finished and the user clicks on any action, he is redirected to a window prompting to confirm the timezone.

#### Steps to Reproduce

1. Log in as admin and create a new user, then log out
2. Log in as the new user
3. At first log in the new user will have to go through a wizard to confirm/edit/modify his own settings: go through the whole wizard
4. After the wizard has run: click on any action in SuiteCRM
5. A window prompting to confirm timezone appears instead of the desired action window
6. After the user confirms the timezone he will not be prompted again. If he doesn't confirm it he will be prompted again

#### Context

Low priority but needs to be corrected

#### Your Environment

* SuiteCRM Version used: 7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): latest Chrome version
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1, MySQL
* Operating System and version (e.g Ubuntu 16.04): CentOS

**Comment by ChangezKhan** [comment]
@amariussi well, there are a couple of issues I found.

1. When you save all the details entered in wizard view, it doesn't actually get updated in DB. Update query gets executed, but wizard form details never gets updated. Only old contents gets updated.
2. After passing through wizard view, updation to '**user_preferences**' table doesn't work, hence '**ut**' column doesn't get update and hence you see '**Confirm TimeZone**' screen again.
