### ISSUE TITLE
Installation process of SuiteCRM-7.11.2 fails to create table outbound_email

### ISSUE THREAD

**Issue by Bcadej** [salesagility/SuiteCRM#7029]
#### Issue
The installation process of fresh (new) SuiteCRM-7.11.2 instance (to empty directory and new empty database) goes well without any errors displayed during and at the end of the installation process. After the installation process is finished and go to the CRM’s URL you get the error “Database failure. Please refer to the suitecrm.log for details.”

#### Expected Behavior
After the installation process is finished, go to the CRM’s URL and be able to log in.

#### Steps to Reproduce
1. Unzip SuiteCRM-7.11.2 to an empty folder.
2. Create new database.
3. Go to the required URL.
4. Go through the installation process.
5. Visit the URL of SuiteCRM.

#### Context
This should be high priority because no new installation can be made.

#### Your Environment
* SuiteCRM Version used: SuiteCRM-7.11.2
* SuiteCRM Version used: SuiteCRM 7.10.14 LTS
* Browser name and version: all
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2.15
* Operating System and version: CentOS 7

#### Attached log files

[SuiteCRM-7.11.2 error.log](https://github.com/salesagility/SuiteCRM/files/2941807/SuiteCRM-7.11.2.error.log)
[SuiteCRM-7.11.2 install.log](https://github.com/salesagility/SuiteCRM/files/2941808/SuiteCRM-7.11.2.install.log)
[SuiteCRM-7.11.2 suitecrm.log](https://github.com/salesagility/SuiteCRM/files/2941809/SuiteCRM-7.11.2.suitecrm.log)

**Comment by pgorod** [comment]
Let's keep treating this issue in the Forums until we are certain it's not just a problem in your installation (I think it is):

https://suitecrm.com/suitecrm/forum/installation-upgrade-help/22026-after-suitecrm-7-11-2-fresh-install-get-database-failure
