### ISSUE TITLE
Workflow Module - Start with operator not working

### ISSUE THREAD

**Issue by pavithra-selvam** [salesagility/SuiteCRM#7030]
Workflow module

#### Issue
 Workflow module - contains , start with and end with operator not working in all versions. 

#### Steps to Reproduce

1.Create workflow
2.add condition and select operator is any one like start with,end with or contains.

#### Your Environment
SuiteCRM Version: 7.9.7
PHP: 7

**Comment by pavithra-selvam** [comment]
i found solution for this can you please test and is it okay can you please commit to your next release.
in modules/AOW_WorkFlow/AOW_WorkFlow.php file can you please repleace these lines.
 **case "Starts_With" : return strrpos($var1,$var2, -strlen($var1));
 case "Ends_With" : return strpos($var1,$var2,strlen($var1) - strlen($var2));**
insted of 
**case "Starts_With" : 
                $length = strlen($var2);
                return (substr($var1, 0, $length) === $var2);
case "Ends_With" : 
                $length = strlen($var2);
                if ($length == 0) {
                    return true;
                }
                return (substr($var1, -$length) === $var2);**

**Comment by pgorod** [comment]
@pavithra-selvam thanks for that. 

Do you want to try and make a Pull Request? For such a simpe change, it's easy to do from Github web interface.

Just go here (notice that I selected the branch for you):
https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/modules/AOW_WorkFlow/AOW_WorkFlow.php

And click the ✏️ icon to edit the file, then save your changes and write up the text for the PR. I can help you if you run into problems. Thanks!

**Comment by pavithra-selvam** [comment]
@pgorod ,
Thanks for your help, i followed your instruction and updated file. is everything fine or need to change anything?.
Thanks!

**Comment by pgorod** [comment]
When you edit the file, Github automatically forked the SuiteCRM repo into your own Github area, and created a commit there. Then you were given the option to create a Pull Request (asking the SuiteCRM maintainers to integrate your patch), but it seems you didn't finish that step.

The full process is described here:
https://help.github.com/en/articles/editing-files-in-another-users-repository

You don't have to repeat everything, you can just go here
https://github.com/salesagility/SuiteCRM/compare/hotfix-7.10.x...pavithra-selvam:patch-1?expand=1

and start the PR. Thanks

**Comment by pavithra-selvam** [comment]
@pgorod 
Thanks for your help pgorod.. I created pull request.
Thanks!
