### ISSUE TITLE
Email body blank when sent as plaintext only

### ISSUE THREAD

**Issue by mattscooter** [salesagility/SuiteCRM#7054]
#### Issue
Some non imported emails are showing a blank body in the detail view even though they have a body when viewed in my usual email client. 

#### Expected Behavior
When viewing emails in the detail view the body should be displayed.

#### Actual Behavior
When the email is sent as plain-ASCII only and has no HTML component nothing is displayed in the body text.  :(

I am also seeing the following entry in the error_log which I think is related:
PHP Notice:  Undefined property: stdClass::$parts in /web/modules/InboundEmail/InboundEmail.php on line 3974

#### Possible Fix
I have done some debugging into the issue and looks like the root cause is that the description field is not defined in the metadata for the non imported detail view.

If you look at line 5642 of the returnNonImportedEmail function in /web/modules/InboundEmail/InboundEmail.php  you can see that it is checking if the 'description' field is in $fields_selected.  These $fields_selected are ultimately defined by the metadata of the non imported detail view in /modules/Emails/metadata/nonimporteddetailviewdefs.php.

When I add a new metadata entry below the description_html field I am now seeing the body of the email as expected. 
This is what I have added around line 120 of /modules/Emails/metadata/nonimporteddetailviewdefs.php:

`
array(
    'body' => array(
        'name' => 'description',
        'label' => 'LBL_BODY'
     ),
),
`

I am not sure if this is the correct fix for this problem and would appreciate if someone more knowledgeable than me could advise if there are any unintended side effects of this fix. 

#### Steps to Reproduce
1. Send an email with plaintext only to an email inbox 
2. Open the detail view from the email list.
3. See that the email has no body

#### Context
Without the fix in place this is causing issues in my logged emails as anyone that is sending as plaintext only is not getting the body of the email, which is the most important part!

#### Your Environment
I am running in a shared environment managed by CPanel with the following versions:
SuiteCRM v7.11.2
PHP - v7.1.26
MariaDB - 10.2.22
Browser - Firefox - 65.0.2 (64-bit)

**Comment by graze1234** [comment]
I think this bug has reopened in v 8.2.2? I'm trying to send plaintext email and getting no text sent through in the email body - I've tried the fix the OP offered editing nonimporteddetailviewdefs.php in suitecrm/public/legacy/modules/Emails/metadata - but on initial test it's not made a difference, I suspect there's a file I've not yet found that superceded the legacy modules folder
