### ISSUE TITLE
Inline Editing Display Error in Documents Module

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#706]
In the documents module (clean install without modifications) , when i change the field of the "related document" field (relationship) and save it, a white space is displayed. When i refresh the page i see the correct entry. 
Before:
![related document before](https://cloud.githubusercontent.com/assets/15199551/11372083/dd04a40c-92cb-11e5-9282-a1e50c2342e5.png)
Edit:
![related document edit](https://cloud.githubusercontent.com/assets/15199551/11372087/e4b06e48-92cb-11e5-9eed-cd600506608a.png)
After:
![related document after save](https://cloud.githubusercontent.com/assets/15199551/11372108/fabf0956-92cb-11e5-94c4-fda0a83132b5.png)

**Comment by Mausino** [comment]
Same issues are, when you add some module or new fields via Studio and it saves the blank value after inline editing (in detailview or listview).  

When user edit via editview, it saves the information correct :+1:

**Comment by jobvector** [comment]
Fixed on the 7.5.1: The user name in Related Document appear correctly.

**Comment by jobvector** [comment]
Fixed on 7.5

**Comment by jobvector** [comment]
it works, thx for the fix
