### ISSUE TITLE
Module Loader is blank 

### ISSUE THREAD

**Issue by P-Flores** [salesagility/SuiteCRM#7063]
I'm trying to upload the spanish language for the CRM, but Module Loader page is blank:
![image](https://user-images.githubusercontent.com/16752260/54465678-5c1bf980-474a-11e9-9244-e6aa02063ce3.png)

I've been following this tutorial, but it didn't work 100% (at least the following message disappeared: Upload stream is blocked by Suhosin, please add "upload" to suhosin.executor.include.whitelist (See suitecrm.log for more information)): https://fiwicorp.com/2016/04/module-loader-blocked-by-suhosin-and-screen-in-upgrade-wizard-is-blank/

Version 7.10.14
Sugar Version 6.5.25 (Build 344)

I hope you can give me some help.

**Comment by pgorod** [comment]
This is a support issue, you should be opening this in the Forums, not here.

Please close this issue here and start a new thread there, I will help you out.

https://forum.suitecrm.com/
