### ISSUE TITLE
Api V8 Logout requires POST instead of GET - Documentation incorrect

### ISSUE THREAD

**Issue by patrickstump** [salesagility/SuiteCRM#7078]
The Documentation for the API V8 logout function is incorrect.
The Documentation is located at [Developer Guide > API Versions > API-Version-8  > JSON API -> Logout](https://docs.suitecrm.com/developer/api/version-8/json-api/#_logout).

#### Issue
There are two issues:
1. Rest method only works with a POST, GET returns error. Documentation shows a GET
2. API path is incorrect. The documentation shows a path of """/V8/logout""" where the path with a post that works is """/Api/V8/logout"""

#### Expected Behavior
Update Documentation to show the correct path and REST method.

#### Actual Behavior
When you use the Method (GET) and path provided an error or 404 response is received.

#### Possible Fix
Either update documentation with the working REST method and path, or change code to implement the new path and GET method.

#### Steps to Reproduce
1. Call GET {{your-SuiteCRM-url}}/V8/logout 
2. Receive Error
3.Call POST {{your-SuiteCRM-url}}/Api/V8/logout
4. Receive success

#### Context
This may not be a high priority as the token will expire, but for security reasons logging out removes the ability for an attacker to hijack the token.  Too high volume api calls could result in a large number of sessions that aren't needed.

#### Your Environment

* SuiteCRM Version used: 7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (Latest)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB and PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by Dillon-Brown** [comment]
Hi @patrickstump, this looks to be a documentation issue. Can you raise this in the [SuiteDocs ](https://github.com/salesagility/SuiteDocs/issues) repo? thanks!
