### ISSUE TITLE
API documentation appears to show incorrect path.

### ISSUE THREAD

**Issue by patrickstump** [salesagility/SuiteCRM#7079]
Most of the documentation under [Developer Guid > API Versions > API-Version-8 > JSON API
](https://docs.suitecrm.com/developer/api/version-8/json-api/) shows the api path as just /V8/*.
This appears to be incorrect from what I can see in the code.

Looking in the rewrite rules in .htaccess it only show /Api/*
"""
    --------- DEPRECATED --------
    RewriteRule ^api/(.*?)$ lib/API/public/index.php/$1 [L]
    RewriteRule ^api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    -----------------------------

    RewriteRule ^Api/access_token$ Api/index.php/access_token [L]
    RewriteRule ^Api/V8/(.*?)$ Api/index.php/V8/$1 [L]
    RewriteRule ^Api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
"""
#### Expected Behavior
Documentation should show "/Api/V8/..."

#### Actual Behavior
Documentations shows api as /V8/* Missing the /Api/V8
#### Possible Fix
Update Documentation
#### Steps to Reproduce

1. Not Applicable.

#### Context
This took me a while to figure out what was wrong with my code trying to access the new api.
So time wasted. Once if found the /Api portion, it appears to be working well.

#### Your Environment

* SuiteCRM Version used:7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (latest)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB and PHP 72
* Operating System and version (e.g Ubuntu 16.04): ubuntu 18.04

**Comment by isleshocky77** [comment]
It appears whole new "V8" API was added for some reason.  I'm trying to track down related commits, issues, and PRs now.

* a29cc3a54b2d486d3a0ea5de4c6f1b445a3cc418 
  * This is a large commit with only a message saying "new api init" and no PR or Issue attached.

**Comment by Dillon-Brown** [comment]
Closing this in favour of #7083, see comment here: https://github.com/salesagility/SuiteCRM/issues/7083#issuecomment-475127884. Although feel free to raise an issue on the doc site [repo](https://github.com/salesagility/SuiteDocs/issues) while this is looked into on the SuiteCRM side. Thanks!

**Comment by patrickstump** [comment]
Will Do. Thanks.
