### ISSUE TITLE
v8 no longer working  (v8 vs V8) /api vs /Api

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#7083]
#### Issue

It appears at some point between v7.10.7 and v7.11.2 that the API for v8 was refactored killing off the old functionality of the new v8 Api.  

What happened?  
Where is this documented?
Why was it decided to differentiate between two APIs as V8 and v8 when they apparently have different functionality?

#### Expected Behavior

* #7101 `POST https://suitecrm.example.org/api/oauth/access_token` is now dead.  
  * It appears 59a76f1 deletes the whole lib/API/public directory while putting in .htaccess that the urls are deprecated.
* `POST https://suitecrm.example.org/Api/access_token` is not one-to-one with api/oauth/access_token as `scopes` is not supported.  
* #7174 `GET https://suitecrm.example.org/api/v8/modules/meta/list` is now dead
  * It appears this functionality wasn't even built into the new "V8"
* #7175 `GET https://suitecrm.example.org/api/v8/modules/Accounts/meta/language` is now dead
  * It appears this functionality wasn't even built into the new "V8"
* `GET https://suitecrm.example.org/api/v8/swagger.json` no longer returns a correct [list of resources](https://docs.suitecrm.com/developer/api/version-8/getting-available-resources/)

#### Related Commits, Issues and PRs

* 59a76f1
* a29cc3a
* #4634
* #7079

#### Context

I had built infrastructure out using the new v8 API and it's all now broken with what it looks like no way to fix it as the new v8 doesn't have all the previous functionality.

#### Your Environment

* SuiteCRM Version used: 7.11.2

**Comment by Dillon-Brown** [comment]
Just adding this in for context:
- New API added in [7.10](https://docs.suitecrm.com/admin/releases/7.10.x/#_7_10_0):
- API refactored (Path changed from [lib/API/v8](https://github.com/salesagility/SuiteCRM/tree/v7.10.9/lib/API/v8) to [Api/V8](https://github.com/salesagility/SuiteCRM/tree/v7.10.10/Api/V8)) in [7.10.10](https://docs.suitecrm.com/admin/releases/7.10.x/#_7_10_10
):

The documentation should have two separate links under [V8 API](https://docs.suitecrm.com/developer/api/version-8/):
- V8 7.10 to 7.10.9 now deprecated [docs](https://docs.suitecrm.com/developer/api/version-8/json-api-dep/)
- V8 7.10.10 and above [docs](https://docs.suitecrm.com/developer/api/version-8/)

I agree that something seems wrong here though, at the very minimum the doc site needs to be updated.

**Comment by patrickstump** [comment]
I filed a ticket in salesagility/SuiteDocs#253 in reference to their API path documentation being incorrect with what works currently.  When this is resolved, please comment what the final api path should be.
