### ISSUE TITLE
Start supporting MySQL 8

### ISSUE THREAD

**Issue by jshwhitlow** [salesagility/SuiteCRM#7092]
#### Issue
SuiteCRM currently doesn't support MySQL 8

#### Expected Behavior
SuiteCRM should be able to run off of MySQL 8

#### Actual Behavior

SuiteCRM currently doesn't support past MySQL 5.7 according to your compatibility matrix, no actual testing has been performed attempting to upgrade to MySQL 8 to see the affects of doing so.

#### Context

I have a stored procedure that I need to update using MySQL 8's new 'common table expressions' that will take my stored procedure from 25 seconds down to less than 1 second, creating great performance improvement for us. Unfortunately, I can't do that because the server is still using MySQL 5.7 which is being capped by what SuiteCRM can support.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Environment name and version: PHP 7.1, MySQL 5.7, Ubuntu 18.04.01 (On Server)
* Operating System and version: macOS Mojave 10.14 (local machine)

**Comment by pgorod** [comment]
Related: #6046

**Comment by lazka** [comment]
Maybe related: #7107

**Comment by lazka** [comment]
(I've created #7124 so we at least start testing with MySQL 5.7 for starters)

**Comment by ericgr** [comment]
This would be useful so we could take advantage of the great pricing for managed databases on Digital Ocean, which only supports MySQL 8.

**Comment by jan-waterdrop** [comment]
any news?

**Comment by pgorod** [comment]
We're one step closer, since #6046 got fixed in the brand new versions 7.10.28 / 7.11.16...

I think that was the major blocker (prevented installation), but maybe only now we will find out the other blockers...
