### ISSUE TITLE
EditView is hardcoded into the _get_form method

### ISSUE THREAD

**Issue by ildarius** [salesagility/SuiteCRM#7093]
If we define a custom action inside a widget like

class somewidget {
  function display() {
    $additionalFormFields['action']        = 'SOME_UNIQUE_ACTION';
  }
}

The _get_form method will overwrite it on line 207 of 
/include/generic/SugarWidgets/SugarWidgetSubPanelTopButton.php

with 
        
        $formValues['action'] = "EditView";

and then further down with

        // fill in additional form fields for all but action
        foreach ($additionalFormFields as $key => $value) {
            if ($key != 'action') {

So it's doing it on purpose, but unclear why. Result is that users can't point to a custom view from within the top button of a subpanel, which is not ideal.

**Comment by samus-aran** [comment]
Can't you just extend this SugarWidget within custom folder and edit that? I guess the idea here is do you want to custom view for all Top Buttons or just unique for a particular place.. Else just move it into the custom folder or create a new SubPanelTopButton.
https://github.com/salesagility/SuiteCRM/blob/master/include/generic/SugarWidgets/SugarWidgetSubPanelTopButton.php#L245

I don't think this is somethign we'll fix. There is ways to extend this to suit your needs using the custom/extension framework :) Feel free though to provide a core change.

**Comment by ildarius** [comment]
That's a good point, I didn't think about extending that file. Thank you
