### ISSUE TITLE
Api relationship links are missing the /Api and start with /V8

### ISSUE THREAD

**Issue by patrickstump** [salesagility/SuiteCRM#7095]
Returned record data from the Api V8 returns relationship links that start with /V8 which is not working.  If /Api is added to the beginning of the link, the record is retrieved correctly.
#### Issue
The relationship section of records called via the API V8 is returning an non-working link.
The example link returned for the following example:
Account "test account" has a contact "test contact".
Via /Api/V8/module/Accounts returns a record with the relationship section for contacts as such:
```
"Contacts": {
                    "links": {
                        "related": "/V8/module/Accounts/6add770a-7f5d-28c3-1304-5c91070821a3/relationships/contacts"
                    }
```
The link does not work in 7.11.2.  If a /Api is added to the front for  
`/Api/V8/module/Accounts/6add770a-7f5d-28c3-1304-5c91070821a3/relationships/contacts`
the link works.
#### Expected Behavior
Have the relationship return a valid link.

#### Actual Behavior
The api returns a relationship with an invalid relationship link missing the `/Api`.

#### Possible Fix
Unknown
#### Steps to Reproduce

1. Create an Account "test account"
2. Create a contact in "test account" called "test contact"
3. Call the Api for "test account" `/Api/V8/module/Accounts/` 
4. Find the resulting section in "relationships" for "Contacts" and see that the link shows:
```
"Contacts": {
                    "links": {
                        "related": "/V8/module/Accounts/6add770a-7f5d-28c3-1304-5c91070821a3/relationships/contacts"
                    }
```
where the url starts with /V8 and does not work.

#### Context
I am having to shim my code to either add the "/Api" or detect if it isn't there.

#### Your Environment

* SuiteCRM Version used:7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Postman
* Environment name and version (e.g. MySQL, PHP 7): Mysql php7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by PedroErnst** [comment]
Hi @patrickstump

I think the base url for the API contains the `/Api` part, that's why it's not included here.
So the base url for the API would be `https://mydomain.com/Api` - and then all other routes would go after to this.

**Comment by patrickstump** [comment]
Thanks @PedroErnst. Is that documented someplace and I just missed it?  If that is the case then the ticket should probably be to document that better.

**Comment by isleshocky77** [comment]
According to the [Guzzle explanation of RFC 3986](http://docs.guzzlephp.org/en/stable/quickstart.html#making-a-request), those links should either be full absolute paths (e.g. `https://suitecrm.com/Api/V8/module`) OR root relative paths (e.g. `https://suitecrm.com/Api/V8/module`) OR completely relative paths (e.g. `V8/modules`)

I give the following code as an example

```php
<?php
$client = new Client([
    'base_uri' => 'https://crm.example.org/Api/',
]);


$url = 'V8/module/Notes?page[size]=20';
do {
    try {
        $response = $client->request('GET', $url, ['debug'=>true]);
    } catch (Exception $e) {
        throw $e;
    }

    $body = json_decode((string)$response->getBody());
    
    
    $data = $body->data;
    // Do something with data

    $url = property_exists($body, 'links')
            && property_exists($body->links, 'next')
            && !is_null($body->links->next) ? $body->links->next : null;
} while ($url);
```

Due to the way the links are coming back, this is throwing a 404 as it gets rid of the path part of the `base_uri` which is "Api".

P.s. if you notice the checks needed for `links`, can we just always include `meta` and `links`?

**Comment by patrickstump** [comment]
Sorry not to be dense here... but is the fix to stay with the /V8 and make /Api part of the base uri?
