### ISSUE TITLE
7.11.2 - Case creation email not being mail-merged

### ISSUE THREAD

**Issue by cartbar** [salesagility/SuiteCRM#7097]
#### Issue

When I send an email to SuiteCRM, the case is created, but the automatic email that is sent in reply contains field names, rather than the data that the fields contain.

#### Expected Behavior

The "Case Creation" email template contains:

`
Hi $contact_first_name $contact_last_name,

We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
Status	$acase_status
Reference	$acase_case_number
Description	$acase_description
`

I would expect that the sender should receive an email that looks like:

`
Hi Fred Bloggs,

We've received your case Test Case (# 1) on 25/03/2019
Status	Pending
Reference	1
Description	Test Description
`

#### Actual Behavior

The email received by the sender contains the email template, without any changes.

#### Possible Fix

The problem appears to be in the modules/InboundEmail/AOPInboundEmail.php, method handleCreateCase(), from line 176.  The email template is retrieved, but the body is not processed in any way.  It should probably use something like the populateTemplate() method in modules/AOP_Case_Updates/AOP_Case_Updates.php

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
SuiteCRM Version 7.11.2   
Sugar Version 6.5.25 (Build 344)

**Comment by willrennie** [comment]
I've tested this functionality in 7.10.14(latest 7.10 release), 7.11.2(latest 7.11 release) and also specifically testing the 7.10.9->7.11.2 upgrade process and then tested the functionality post upgrade. I'm not experiencing the errors you are. The email functionality is working as expected and data is passed to my templates successfully. Can you confirm this is a clean CRM install without customisations to any of the cases and/or email functional areas?

**Comment by cartbar** [comment]
Hello.

To reproduce, create an inbound email account with "Create Case From Email" enabled and with "New Case Auto-Reply Template" set to "Case Creation":

![Inbound Email](https://user-images.githubusercontent.com/16174661/55008031-4cb56f80-4fd8-11e9-85a7-58b5b8ca1cf4.png)

Then send an email to that address (the email should come from an address that does not have a Contact for it in the CRM, otherwise the email will be generated in a different way, via a logic hook).

When the Scheduler runs the "Check Inbound Mailboxes" job, it calls the pollMonitoredInboxesAOP() method in modules/Schedulers/_AddJobsHere.php, which calls handleCreateCase() in modules/InboundEmail/AOPInboundEmail, which reads the EmailTemplate, but does not preprocess it before sending it.

**Comment by willrennie** [comment]
@cartbar I think your comment here is valid for your other issue and not this issue. I've tested this functionality in 7.10.14(latest 7.10 release), 7.11.2(latest 7.11 release) and also specifically testing the 7.10.9->7.11.2 upgrade process and then tested the functionality post upgrade. I'm not experiencing the errors you are. The email functionality is working as expected and data is passed to my templates successfully. Can you confirm this is a clean CRM install without customisations to any of the cases and/or email functional areas?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity
