### ISSUE TITLE
AOP creating 2 emails on case creation

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#71]
AOP creates 2 identical emails on creation of a case from the Joomla portal.

**Comment by darthtang** [comment]
Is this bug reproduced when the user send a case for the FIRST time? I only got this bug to happen for my first ever case submitted but not my other cases .

**Comment by darthtang** [comment]
I am going into joomla portal

Then create case

then adding a case 

I only receive one email. 

If somebody can reproduce the bug please let me know and i will try and fix it

**Comment by shogunpol** [comment]
There is no issue described by "darthtang", in the recent versions of Joomla and SuiteCRM. 
When case is created, receive two emails:
- one - From CRM about created case on CRM;
- two - email about receiving your case.

**Comment by willrennie** [comment]
Cannot be replicated, most likely fixed in latest version of AOP joomla component or within the SuiteCRM application itself.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Importing list items when creating through studio](https://trello.com/c/kJyFEfOt/132-importing-list-items-when-creating-through-studio)
