### ISSUE TITLE
Suggestion for Basic Search enhancement

### ISSUE THREAD

**Issue by mnheia** [salesagility/SuiteCRM#7103]
#### Issue
Basic Search does not return data for example opportunities when for example typing SuiteCRM in the search form.

#### Expected Behavior
Basic Search should return data.

#### Actual Behavior
Basic Search does not return data.

#### Possible Fix
When adding % as a wildcard search form provides data. For example %SuiteCRM%.

#### Steps to Reproduce
1. Login to SuiteCRM
2. Input an opportunity name for example SuiteCRM

#### Context
We have been trying to find all the opportunities with SuiteCRM in the name. As CRM is commonly used by sales department we believe that search should already include % as a wildcard for better search capabilities.

Since this could be clearly documented (or maybe it already is and someone should just read the documentation) this a low priority enhancement suggestion.

#### Your Environment
* SuiteCRM version 7.11.2

**Comment by danci1973** [comment]
At the very least some hints and examples should be shown (on mouse-over or similar).

**Comment by gody01** [comment]
+1

**Comment by gunnicom** [comment]
You know about the config?

'search_wildcard_infront' => true,
