### ISSUE TITLE
API module relationship link on custom module points to module name not field name in vardefs.php

### ISSUE THREAD

**Issue by patrickstump** [salesagility/SuiteCRM#7121]
When calling the `/Api/V8/module/CUSTOMMODULENAME` the resulting links in the relationship section are incorrect and do not work for the relationships to other custom modules in the package.
It appears they are linking to the module name and not the related field listed in the custom module's relationship file.

##### Custom Module
Using the Module builder we created a custom module package.  Inside of that , there are two objects Wallets and Transactions. Through the gui module builder we created the relationship on the Transaction object to be a many to one relationship with Wallets. I.e. Many Transactions to one Wallet.

That created a relationship with the name "module_transactions_module_wallet".
##### Calling the API
When trying to find the Transaction Id associated with the wallets, we use the api call:
`/Api/V8/module/Module/Wallets` or `/Api/V8/module/Module/Wallets/380af771-bc86-aa45-fbe5-5c9110500074`
The following under relationships is returned:

```
 "relationships": {
                "ModuleTransactions": {
                    "links": {
                        "related": "/V8/module/Module_Wallet/380af771-bc86-aa45-fbe5-5c9110500074/relationships/module_transactions"
                    }
```
##### Bad Link
Knowing there is an issue with link missing /Api we call ```/Api/V8/module/Module_Wallet/380af771-bc86-aa45-fbe5-5c9110500074/relationships/module_transactions```

The link provided returns
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Cannot load relationship module_transactions for Module_Wallet module"
    }
}
```
##### Good Link
If instead we call:
`/Api//V8/module/Module_Wallet/380af771-bc86-aa45-fbe5-5c9110500074/relationships/module_transactions_module_wallet
`
We receive a correct response:
```{
    "data": [
        {
            "type": "Module_Transactions",
            "id": "ac5fc53f-4d2e-04ee-d1dc-5c9aa4226794",
            "links": {
                "self": "/V8/module/Module/Transactions/ac5fc53f-4d2e-04ee-d1dc-5c9aa4226794"
            }
        },
```
For the correct response we had to use the relationship field name, not the module name.

#### Expected Behavior
The link returned in relationships should work, weather changed to the proper module name or the relation ship name.  I.e. I don't know if the issue is in the Api or in the module builder.

#### Actual Behavior
Described above.  Sends a link to the module name, which does not return correctly.

#### Possible Fix
I've spent a few hours searching through code trying to determine if this should be calling the module name and it figure out the right field, or if the api should return the field name.
I'm not sure what the proper way should be, nor can I find where the issue lies.

#### Steps to Reproduce

1. Use Module Builder to create "new package" named "Module"
2. Create Module called "Wallets"
3. Create Module called "Transactions"
4. In Transactions Module -> Relationships create a many to one relationship with Many transactions to one Wallet.
5. Deploy package
6. Call API at `/Api/V8/module/Module/Wallets`
7. Look in relationships section of return for the Transactions relationship.
8. Prepend "/Api" to the link for relationships to Transactions and call the link, which will be something like `/Api/V8/module/Module_Wallet/{wallet_id}/relationships/module_transactions`
9. Receive error.

#### Context
Not sure if we should right our code to ignore this section and just call the code we know to work, i.e. the proper field name.  In the short term we have to hard code the method to get the working response.

### Your Environment

* SuiteCRM Version used: 7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Postman
* Environment name and version (e.g. MySQL, PHP 7): Mariadb and Php 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by PedroErnst** [comment]
Hi @patrickstump , thanks for reporting this!
Could you test the above fix and see if it works for you?
Thanks!

**Comment by patrickstump** [comment]
@PedroErnst  thanks!. I'll try to test it in the next two days.  Thanks!

**Comment by patrickstump** [comment]
@PedroErnst Sorry for the delay. I just confirmed this fix does work.  Thank you!
Not sure of the protocol. Do I close this now that I confirmed the proposed fix worked or does the person who merges it in fix it?

**Comment by Dillon-Brown** [comment]
Hi @patrickstump, you can leave it open. Once a linked "Fix Proposed" PR gets merged and the next release is published, the issue will automatically be closed.

**Comment by patrickstump** [comment]
@Dillon-Brown Thank you.
