### ISSUE TITLE
Cannot Edit Project Tasks from Gant Chart View

### ISSUE THREAD

**Issue by newsat11** [salesagility/SuiteCRM#7122]
#### Issue
Once a task has been created, it cannot be edited from the Gant chart. 

#### Expected Behavior
When a user selects a task, a modal should open with the configuration information that has already been entered ready to edit.

#### Actual Behavior
When selecting the link in the task name column, the modal for task appears, but users cannot use the mouse to edit any of information. The tab sequence works correctly, but nothing can be clicked with the mouse.

No error is documented in the logs.

#### Possible Fix
The issue might be related to the modals z--index. It appears an overlay appears when the task is selected, but the overlay is also displaying in a higher index position than the modal.

#### Steps to Reproduce

1. Create a Project
2. Create a Project Task
3. View the project's Gant view
4. Select the link for the task from the Gant chart.

#### Context

Low Priority - the tasks can still be edited from the details view of the project, so the priority is low. When managing a project, the Gant view provides the easiest way edit tasks in direct relation to a timeline. This bug prevents me from doing that.

#### Your Environment

* SuiteCRM Version used: 7.8.27
* Browser name and version: Version 73.0.3683.86 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Linux Red Hat CentOS

**Comment by willrennie** [comment]
We have tested this issue and cannot replicate the bug in a fresh 7.8.27. Is this a fresh install? Have you made any changes? Are you able to provide a recording or even a set of screen shots? Does this happen in all browsers?

**Comment by newsat11** [comment]
After some additional testing I was unable to reproduce the error using the default theme, and if that's what you are using for test, I doubt you would see it either. If you use the Suite 7 or Suite R theme you should be able to reproduce the error. Please let me know if you cannot replicate it and I will perform a screen capture. I'm pretty sure you'll be able to find it, as I was able to reproduce it on my test and production server.

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
