### ISSUE TITLE
Maps SWF export buttons not working under SSL

### ISSUE THREAD

**Issue by markbond1007** [salesagility/SuiteCRM#7128]
#### Issue

When displaying anything on a jjwg Map, there are Copy/CSV/etc. buttons under the map to export the data lists. If you have suite crm under an SSL/HTTPS url, these buttons do not work (tested in Chrome here). Google Chrome gives a mixed content warning (loading http over an https page). This is due to the jjwg_Maps/view/view.map_markers.php have a hard coded link to  http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf in it.

#### Expected Behavior

The SWF file should load correctly and clicking the buttons should provide a download option.

#### Actual Behavior

Clicking the buttons in most cases does nothing, although the Print button sometimes works.

#### Possible Fix

replace the url with a hard coded https one or detect the current Status etc.

#### Steps to Reproduce

1. Go to Maps
2. Create a Map with entries
3. Click CSV button under the map
4.

#### Context

One of our customers is trying to export the results of searching in this way.

#### Your Environment

* SuiteCRM Version used: 7.11.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 73.0.3683.86 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Debian 9

**Comment by willrennie** [comment]
Also related to #6208

**Comment by holdusback** [comment]
Same here, in the latest version 7.11.5.

Btw, when you click on an entry on the map, the two link are broken "view on Google Maps" and "Get direction"

It give you a 404 Google Error.

Im trying to fix everything in the /custom/ directory, but it should be better to fix thoses small bugs in the main dir.

I also get a 404 error on a CSS file : 
GET https://XXXXX.com/cache/themes/SuiteP/css/style.css net::ERR_ABORTED 404

**Comment by emcquaid** [comment]
> This is due to the jjwg_Maps/view/view.map_markers.php have a hard coded link to http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf in it.
> 
> Possible Fix
> replace the url with a hard coded https one or detect the current Status etc.

Replacing the link on line 740 of modules/jjwg_Maps/view/view.map_markers.php with the hardcoded https link does fix this issue for me on Chrome.  I have not tested on other browsers.

Tabletools 2.2.4 is out, should it be:
`                "sSwfPath": "https://cdn.datatables.net/tabletools/2.2.4/swf/copy_csv_xls_pdf.swf"
`
