### ISSUE TITLE
Changes in Studio do not make an override file.

### ISSUE THREAD

**Issue by jack7anderson7** [salesagility/SuiteCRM#7133]
When making changes in studio SuiteCRM doesn't make override files
#### Issue

When making changes in studio SuiteCRM doesn't make override files.
#### Expected Behavior

When changing a field in Studio after saving it should create an override file, in the same way subpanels do.
#### Actual Behavior
After saving, Studio writes to sugarfield_<field_name>.php 

#### Steps to Reproduce

1. Navigate to Studio
2. Make change to field
3. Save Change
4. Check filename

#### Context
When making custom fields via code this can affect how Studio saves changes
#### Your Environment
* SuiteCRM Version used: 7.10.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by willrennie** [comment]
@jack7anderson7 can you provide some context on this? The override files are definitely created so it would be good to understand the logic behind the renaming.
