### ISSUE TITLE
Module Loader in version 7.8.28 returns "invalid package" when uploading new package

### ISSUE THREAD

**Issue by gboban** [salesagility/SuiteCRM#7136]
When uploading new module in Module Loader, in SuiteCrm v7.8.28 I get "Invalid Package" message.

Same package can successfully be uploaded and installed in version 7.8.23.

#### Issue
Uploading module in Module Loader in 7.8.28 results with "Invalid Package". Same package can be installed on SuiteCRM v7.8.23. Tried with several packages including translations package from https://crowdin.com/project/suitecrmtranslations/hr#

#### Expected Behavior
Package should be successfully uploaded and installed.

#### Steps to Reproduce

1. Go to Admin->Maodule Loader
2. Click on "choose file"
3. Select any package you have on file system
4. Click "UPLOAD"

#### Context
This should be high priority since it is not possible to use additional packages in SuiteCRM.

#### Your Environment
* SuiteCRM Version used: 7.8.28

**Comment by Dillon-Brown** [comment]
Hi @gboban, is this happening with a specific language pack? I've tried a few on 7.8.28 but I haven't been able to replicate this issue. Have you tried checking permissions?

**Comment by gboban** [comment]
I deleted everything, reinstalled Suite CRM 2.8.28. Now it works.

Problem was with several packages, not jus mentioned language package.

I guess this issue can be closed.
