### ISSUE TITLE
Link security group from user name in workflow uses users.id instead of security group id

### ISSUE THREAD

**Issue by Chris8080** [salesagility/SuiteCRM#7137]
![2019_04_03__crm_workflow_secgroup](https://user-images.githubusercontent.com/3712952/55443323-d40c6f80-55e4-11e9-8043-c7b03d26985c.jpg)

#### Issue

When saving a record, I'd like to assign several security groups to it via a workflow.
So I create the action: Modify Record and add 3 relationships.
1. Manager (relate field, module users)
2. Manual value for testing
3. Assigned to / created by

#### Expected Behavior

2 and 3 work just fine and the correct Sec Groups are assigned.
2 obviously, since it's manually picked.
3 maybe because there is a build in mapping from Assigned to, to the Sec Group?

In the workflow, when I select field for the Sec Group relation, I get a list of all user fields of my current record. That seems to be start of the problem.

#### Actual Behavior

1 is not being assigned.
Looking into the error log, I see:
`SELECT securitygroups.* FROM securitygroups  WHERE securitygroups.id = '2b0135cb-180a-28a4-d0b7-5c629d0b2dfa' AND securitygroups.deleted=0`
This ID is a user ID and I can find it in users table. So it will always return 0 records from the database.

#### Possible Fix

How is Assigned to correctly mapped to the security groups? Same way would probably be good for any user field.

#### Steps to Reproduce

1. Install Version 7.8.7
2. Create users, Sec Groups for each individual user
3. Create workflow which adds the sec group of the user and the manager / another related user field

#### Your Environment

* SuiteCRM Version used: Version 7.8.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 73.0.3683.86 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL , PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by willrennie** [comment]
@Chris8080 please can you provide more detailed information on your issue. What module is your workflow running on? What is your exact user and group set up? For your second relationship, you set the relationship to be 'Field = Manager'. Where is that Manager field stored? What data does it store? If you can provide further detailed information, I can work on replicating your exact configuration and identifying if there is a bug in the Security Groups functionality. Thanks.

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.
