### ISSUE TITLE
EmailMan sendEmail missing restricted_addresses check

### ISSUE THREAD

**Issue by zpangrsic** [salesagility/SuiteCRM#7138]
#### Issue
When scheduling a NewsLetter Campaign to send emails and the Campaign contains target list type 'Suppression list by Email Addresses' the list is not checked and sends emails to receipents regardles if a record with same email address is inside the suppression list.

#### Expected Behavior
Receipents inside campaign should be cross checked if the receipents email is inside suppression list and should be blocked from sending.

#### Actual Behavior
Receipent receives the email from campaign regardless if the same email address is inside target list type 'suppression list by email address'.

#### Possible Fix
The issue is inside EmailMan module - EmailMan.php 
After line [EmailMan.php:946](https://github.com/salesagility/SuiteCRM/blob/6208631608d207b85c00186b498a7c2bcf00278d/modules/EmailMan/EmailMan.php#L946)
It should contain the following code:

```php 
if (isset($this->restricted_addresses) && isset($this->restricted_addresses[$lower_email_address]))
{
    $this->set_as_sent($lower_email_address, true, null, null, 'blocked');
    return true;
}
```

#### Steps to Reproduce
1. Create campaign
2. Add 'default' and 'suppression list by email addresses' target list 
3. Schedule campaign
4. Check campaign log

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version: Chrome Version 73.0.3683.86 (64-bit)
* Environment name and version: MSSQL, PHP7
* Operating System and version: Ubuntu 16.04

**Comment by willrennie** [comment]
Tested and confirmed this sends the email, even if a record with the same email address is in a list that should Suppress by Email Address. Nice find!

**Comment by apexred** [comment]
Tested and confirmed here also (both newsletter and email campaign types.)  Well done.

**Comment by pgorod** [comment]
@Dillon-Brown maybe this can get a `Fix proposed` label since it has instructions on how to fix, even if it is not a complete PR...

Another [user on the Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19715-campaign-email-suppression-list#85332) confirms this works.

**Comment by Dillon-Brown** [comment]
@pgorod Done, I can shove up a PR when I have a minute.
