### ISSUE TITLE
RIVA connector not working

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#7140]
#### Issue
I am trying to connect Riva cloud service to CRM (7.10.14) and get an error when contacts are being synced.

#### Expected Behavior
If connection is OK, contacts and other records should sync without problem.

#### Actual Behavior
I got error:
There is an error in XML document (1, 926)

#### Steps to Reproduce
If using Riva or some other connecting services, try to sync contacts.

#### Context
I know this isn't direct CRM issue, but it is issue with CRM API-s SOAP service.
Full stack trace is:
`System.InvalidOperationException: There is an error in XML document (1, 926). ---> System.InvalidCastException: Cannot assign object of type SugarCrm.Soap.error_value to an object of type SugarCrm.Soap.v4_1.error_value. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read100_modified_relationship_result() at System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(String name, String ns, Boolean elementCanBeType, String& fixupReference) at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read215_Item() at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall) at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters) at SugarCrm.Soap.v4_1.sugarsoap.get_modified_relationships(String session, String module_name, String related_module, String from_date, String to_date, Int32 offset, Int32 max_results, Int32 deleted, String module_user_id, String[] select_fields, String relationship_name, String deletion_date) at Omni.Connection.SugarCrm.c.a(sugarsoap A_0, String A_1, String A_2, DateTime A_3, DateTime A_4, String A_5, Int32 A_6, Int32 A_7, String[] A_8, Int32 A_9) at Omni.Connection.SugarCrm.j.a(String A_0, String A_1, DateTime A_2, DateTime A_3, String A_4, Int32 A_5, String[] A_6) at Omni.Connection.SugarCrm.j.a(CrmObjectTypes A_0, DateTime A_1, DateTime A_2, Boolean A_3, String[] A_4, Int32 A_5, Int32 A_6, Boolean A_7, List`1 A_8, Boolean A_9) at Omni.Connection.SugarCrm.j.a(CrmObjectTypes A_0, DateTime A_1, DateTime A_2, Boolean A_3, Int32 A_4, Int32 A_5, List`1 A_6, Boolean A_7) at Omni.Connection.SugarCrm.j.a(CrmObjectTypes A_0, Boolean A_1, DateTime A_2, DateTime A_3, Boolean A_4) at Omni.Connection.SugarCrm.u.GetUpdatedObjects(DateTime pollFromUtc, aj metadataStore) at Omni.Sync.Crm.t.abq(Int64 A_0) at Omni.Sync.Crm.a2.abq(Int64 A_0) at Omni.Sync.q.a(Boolean& A_0) at Omni.Sync.q.yn() at Omni.Sync.Crm.t.yn() at Omni.Sync.Crm.Exchange.i.m.c(t A_0, m A_1) at Omni.Sync.Crm.Exchange.i.m.d() at Omni.Sync.Crm.Exchange.i.m.h() at Omni.Sync.Crm.Exchange.i.m.ae6() at Omni.Sync.Crm.Exchange.i.ay() at Omni.Riva.Modules.CrmEx.z.k6() at Omni.Riva.Modules.CrmEx.z.kc() at Omni.Riva.Modules.CrmEx.o.kg() at Omni.Scheduling.b.b(Object A_0)    Caller: at Omni.Scheduling.b.b(Object A_0) at Omni.Threading.Internal.m.g() at Omni.Threading.Internal.m.m() at Omni.Threading.h.a(m A_0) at Omni.Threading.h.c() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart() Inner:`

#### Your Environment

* SuiteCRM Version used: 7.10.14
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0, MySQL 5.7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by willrennie** [comment]
I would recommend that you contact RIVA CRM support directly regarding this issue and/or post on the forums to ensure that your configuration is correct and that there is no set up or versioning issues before ruling this as a bug within the SuiteCRM core API.

**Comment by fcorluka** [comment]
Well, @willrennie, I have contacted Riva support, that is the reason I am posting an issue here, because they told me the ERROR in not on their side but on CRM.
As I can not found anywhere in the code where this error is produced, I hoped that someone had some idea. I also posted on the forum, but gut 0 response.
