### ISSUE TITLE
Campaign view status page - Subpanel issue

### ISSUE THREAD

**Issue by dtosun61** [salesagility/SuiteCRM#7150]
#### Issue

When i set my user prefences to "Show collapsed subpanel hint",  subpanel of Campaign view status page is not seen well.
![Screenshot_1](https://user-images.githubusercontent.com/22373035/55629416-d543c500-57bb-11e9-9555-386b2899a1ea.png)

![Screenshot_2](https://user-images.githubusercontent.com/22373035/55629426-d8d74c00-57bb-11e9-9c88-f19c10976849.png)

#### Expected Behavior

It should be looks like others.
#### Steps to Reproduce

1. Open user preferences Layout Options
2. Select "Show collapsed subpanel hint" 
3. Open Campaign view status page page
4. Look at the subpanels

#### Your Environment

* SuiteCRM Version used: 7.10.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by willrennie** [comment]
@dursuntosun I don't get this exact issue but definitely display issues with this functionality so marking as a bug. Attached is what I see in my test of 7.10.15
![Screenshot from 2019-04-05 14-16-29](https://user-images.githubusercontent.com/5641419/55630379-75462200-57ad-11e9-92bc-b1da4383bc4d.png)
![Screenshot from 2019-04-05 14-15-24](https://user-images.githubusercontent.com/5641419/55630380-75462200-57ad-11e9-9475-defb1d5af530.png)

**Comment by ebogaard** [comment]
This is fixable by changing the following file: modules/Campaigns/SubPanelViewer.php

Change (row 100):
```
$subpanel_object->display();
```

To:
```
$countOnly = isset($_REQUEST['countOnly']) && $_REQUEST['countOnly'];
$subpanel_object->display($countOnly);
```

**Comment by chris001** [comment]
@ebogaard 
Can you make a new Pull Request with your fix?
