### ISSUE TITLE
Subject variables not replaced in 7.8.28

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#7155]
Variable substitution does not work in 7.8.28 LTS, seems its not mapping the $templateData['subject'] back to `$this->name`.

https://github.com/salesagility/SuiteCRM/blob/ec1ebdaf9eff4d6e02423c007a1b37fa8383c619/modules/Emails/Email.php#L567-L597

#### Your Environment
* SuiteCRM Version used: 7.8.28

**Comment by tsmgeek** [comment]
Ive also noticed that this section of the code does not include the custom Modules we have.
Doing my previous fix is more like how SuiteCRM is now while adding our custom module in the code below also works, but I am not sure the difference.

https://github.com/salesagility/SuiteCRM/blob/ec1ebdaf9eff4d6e02423c007a1b37fa8383c619/modules/Emails/Email.php#L521-L539

**Comment by cameronblaikie** [comment]
Hi there, We've just tested this by the following steps,
1. Add personal email 
2. Create an email template with variable name in subject and body
3. Then compose an email using the template I just made.
4. send and viewed the email.

When I viewed the email the right name appeared from the variable.

As we can't replicate your issue could you please provide us with further steps that could lead us in the right direction to replicate your problem and fix it. If you could please fill out the template for the issue provided and use as much detail as you can to help us resolve your issue quicker. 
thanks,
