### ISSUE TITLE
Slow SQL query in include/SugarFolders/SugarFolders.php causing slow emails interface in 7.10.x (and 7.11.x)

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#7156]
Our 'emails' table has over 90'000 rows of data. When opening SuiteCRM email client it takes a considerable amount of time to load. Further investigation points to function getCountUnread() in include/SugarFolders/SugarFolders.php. If I bypass the SQL code and immediately return '0' instead, then email interface works fine. 

Further investigation pointed to the amount of time the SQL query took to run. I have also done the usual clear browser cache, repair-rebuild, and done optimise/check table in MySQL.  

Testing this on a vanilla instance with demo data, this issue is not happening due to the very few records in the 'emails' DB  table.  

#### Expected Behavior
SQL query should take less time and SuiteCRM email interface should load within seconds. 

#### Actual Behavior
Slow query reported in SuiteCRM.log. 
Email interface can take up to 30 seconds to load.  

#### Possible Fix
Improve SQL code in getCountUnread(), or remove it altogether if the return value of this function is unused. 

#### Steps to Reproduce
1. Ensure DB table 'emails' has 90k+ rows of data. Enable Error level logging from admin interface.   
2. Open SuiteCRM emails interface. 
3. Observe slow loading times and slow queries reported in suitecrm.log. 

#### Context
We upgraded from 7.8.27 to 7.10.15 and now staff can not efficiently attach emails due to slow loading emails interface. It really impacts their ability for productive work and they waste a lot of time trying to attach emails to records.    

#### Your Environment
* SuiteCRM Version used: 7.10.15. 
* Browser name and version: Safari v12. Edge latest. Chrome. 
* Environment name and version: MySQLd  5.6.43, PHP 7.2.16
* Operating System and version: CentOS 7.6

**Comment by evgu** [comment]
![Screenshot 2019-04-04 at 07 59 41](https://user-images.githubusercontent.com/18371928/55688925-5cd53380-5976-11e9-9ce5-dffbef8b0837.png)
![Screenshot 2019-04-03 at 17 37 47](https://user-images.githubusercontent.com/18371928/55688926-5cd53380-5976-11e9-9354-4dcdeddf2b0c.png)
![Screenshot 2019-04-03 at 17 48 53](https://user-images.githubusercontent.com/18371928/55688927-5cd53380-5976-11e9-8ccc-ed7510f0af12.png)

**Comment by Mausino** [comment]
@evgu I full agree with you... if the database becomes bigger, the performance goes down. Our user hate loading of imported or non imported emails because it takes many time and is unusable... but if we want have the overview about our communication, we must use import function and spend too many our time on loading of emails which loading is maybe 10 times slower as in external program like Thunderbird etc.

**Comment by gunnicom** [comment]
Can you post the full query that is executed?

**Comment by evgu** [comment]
`SELECT 
    COUNT(*) c
FROM
    emails
        JOIN
    emails_text ON emails.id = emails_text.email_id
WHERE
    emails.deleted = 0
        AND emails.type NOT IN ('out' , 'draft')
        AND emails.status NOT IN ('sent' , 'draft')
        AND emails.id IN (SELECT 
            eear.email_id
        FROM
            emails_email_addr_rel eear
                JOIN
            email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id
                AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba'
                AND eabr.bean_module = 'Users'
        WHERE
            eear.deleted = 0)
        AND emails.status = 'unread';`

**Comment by gunnicom** [comment]
@evgu Can you try to compare to following query (If it has the same output, and how fast it is):
```
SELECT COUNT(*) c 
FROM emails  
  JOIN emails_text 
    ON emails.id = emails_text.email_id 
	AND emails.deleted = 0 
    AND emails.type NOT IN ('out' , 'draft') 
    AND emails.status NOT IN ('sent' , 'draft') 
	AND emails.status = 'unread'
  JOIN emails_email_addr_rel eear ON emails.id=eear.email_id AND eear.deleted = 0
  JOIN email_addr_bean_rel eabr 
	ON eabr.email_address_id = eear.email_address_id 
	AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba' 
	AND eabr.bean_module = 'Users';
```

**Comment by evgu** [comment]
Old query takes 22 sec to run. 
Your new query - 0.13 sec (130 ms). 

There is difference in the counts returned!
Old query c=1964, 
New Query c=1976.

**Comment by gunnicom** [comment]
I do not use email in Suite here, so i can not really test further why the query gives a different result. It is really easier to debug if you have the data, and not just the theory in your head.
But maybe that helps someone else to investigate further.
Additionally you can look in your slow-query.log and see if the old query uses temporary tables (it sure does), and if it uses disk or RAM for them. If they get written to disk maybe increasing your tmp table size may already help.

**Comment by evgu** [comment]
@gunnicom Do you know what the return result from this query is consequently used for in SuiteCRM 7.10 & 7.11? I do not see these numbers displayed anywhere in the emails interface. Is this SQL query (and function) obsolete by any chance?

**Comment by gunnicom** [comment]
@evgu No, as i do not use email in Suite, i never really looked at that code.

**Comment by Abuelodelanada** [comment]
> SELECT COUNT(*) c FROM emails JOIN emails_text ON emails.id = emails_text.email_id WHERE emails.deleted = 0 AND emails.type NOT IN ('out' , 'draft') AND emails.status NOT IN ('sent' , 'draft') AND emails.id IN (SELECT eear.email_id FROM emails_email_addr_rel eear JOIN email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba' AND eabr.bean_module = 'Users' WHERE eear.deleted = 0) AND emails.status = 'unread';

Hi, can you execute the following and paste the result?

```SQL
EXPLAIN SELECT COUNT(*) c 
FROM emails JOIN emails_text ON emails.id = emails_text.email_id 
WHERE emails.deleted = 0 AND emails.type NOT IN ('out' , 'draft') AND emails.status NOT IN ('sent' , 'draft') AND emails.id IN (SELECT eear.email_id FROM emails_email_addr_rel eear JOIN email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba' AND eabr.bean_module = 'Users' WHERE eear.deleted = 0) AND emails.status = 'unread';
```

**Comment by evgu** [comment]
@Abuelodelanada this SELECT query still takes 23 seconds to run. Our emails table has 95k rows.  
EXPLAIN SELECT results are:  
<img width="1200" alt="Screenshot 2019-06-25 at 16 50 19" src="https://user-images.githubusercontent.com/18371928/60108793-87f74400-9769-11e9-825d-e52eef0d0d98.png">

**Comment by Abuelodelanada** [comment]
Oh, that query is ugly.... please one more EXPLAIN:

```sql
EXPLAIN SELECT eear.email_id
     FROM emails_email_addr_rel eear
     JOIN email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id
     AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba'
     AND eabr.bean_module = 'Users'
     WHERE eear.deleted = 0
```

I think may be we can add some index in DB to improve query performance

**Comment by evgu** [comment]
@Abuelodelanada This select takes 50ms to run.  
EXPLAIN SELECT is 
![Screenshot 2019-06-25 at 17 05 31](https://user-images.githubusercontent.com/18371928/60109997-a5c5a880-976b-11e9-99d0-b9c7ece27c3c.png)

Let me know if you want me to test new indexes, which columns, and what index type?

**Comment by Abuelodelanada** [comment]
@evgu improving queries performance is sometimes quite a craftsman work.
Please let's try this index:

``` SQL
ALTER TABLE emails ADD INDEX idx01 (deleted, type, status, id);
```

After that re execute this:

```SQL
EXPLAIN SELECT COUNT(*) c 
FROM emails JOIN emails_text ON emails.id = emails_text.email_id 
WHERE emails.deleted = 0 AND emails.type NOT IN ('out' , 'draft') AND emails.status NOT IN ('sent' , 'draft') AND emails.id IN (SELECT eear.email_id FROM emails_email_addr_rel eear JOIN email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba' AND eabr.bean_module = 'Users' WHERE eear.deleted = 0) AND emails.status = 'unread';
```

**Comment by evgu** [comment]
Added index and ran SELECT query few times. SELECT now takes 28sec to complete, which is worse that without the new index. 
Explain select is: 
![Screenshot 2019-06-26 at 10 41 43](https://user-images.githubusercontent.com/18371928/60165151-1d90e300-97ff-11e9-841a-f4f89260b491.png)
![image](https://user-images.githubusercontent.com/18371928/60165655-f4248700-97ff-11e9-95fc-1725b2bc682f.png)

**Comment by Dillon-Brown** [comment]
Have you tried the proposed fix? #7460. We could look at improving the performance of this query but it doesn't appear to be used so imo it should just be deprecated and removed.

**Comment by evgu** [comment]
@Dillon-Brown @Abuelodelanada pls see my initial description of this bug - key questions it if the return value of getCountUnread() is actually used anywhere in the code or not? Was it used anywhere in the older major SuiteCRM releases, as otherwise it is quite strange someone put it there? 

We have been running with a temp fix since April to overcome the slow SQL query - an early 'return 0' before SQL query gets hit - see below. So far no issues. 

Suggest someone more skillful than me verify if fucntion getCountUnread() is used anywhere and perhaps remove it altogether if unused. 

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/18371928/60167303-21266900-9803-11e9-9225-a87b2729d239.png">

**Comment by evgu** [comment]
@Dillon-Brown just reviewed proposed fix #7460 - it achieves a similar result to our temp fix I described above. So this issue #7156 can be closed in that pull request.

**Comment by Abuelodelanada** [comment]
@evgu I would like to try the creation of other indexes... and it is complex doing via github comments.

May you dump `emails`, `emails_text`, `email_addr_bean_rel` and `emails_email_addr_rel` tables? With this dump I'll be able to reproduce your situation.
You can email me (jose AT gcoop DOT coop) the link for downloading the dump. 

Despite of the fact that may be there is other solutions, I think we are missing some index in the tables.

**Comment by evgu** [comment]
@Abuelodelanada unfortunately I can not provide a dump, as tables contain business emails.

**Comment by Abuelodelanada** [comment]
> @Abuelodelanada unfortunately I can not provide a dump, as tables contain business emails.

Oh ok, I understand.

I am looking at an instance with +30.000 rows in emails and the EXPLAIN it is much better than yours:

```SQL
mysql> EXPLAIN SELECT COUNT(*) c FROM emails JOIN emails_text ON emails.id = emails_text.email_id  WHERE emails.deleted = 0       AND emails.type NOT IN ('out',                           'draft')       AND emails.status NOT IN ('sent',
         'draft')       AND emails.id IN     (SELECT eear.email_id      FROM emails_email_addr_rel eear      JOIN email_addr_bean_rel eabr ON eabr.email_address_id = eear.email_address_id      AND eabr.bean_id = 'aaae9982-f28a-4455-2723-5ccac3334ba'      AND eabr.bean_module = 'Users'      WHERE eear.deleted = 0)   AND emails.status = 'unread';
+----+-------------+-------------+------------+--------+-----------------------------------------+----------------------+---------+--------------------------------+------+----------+----------------------------+
| id | select_type | table       | partitions | type   | possible_keys                           | key                  | key_len | ref                            | rows | filtered | Extra                      |
+----+-------------+-------------+------------+--------+-----------------------------------------+----------------------+---------+--------------------------------+------+----------+----------------------------+
|  1 | SIMPLE      | eabr        | NULL       | ref    | idx_email_address_id,idx_bean_id        | idx_bean_id          | 411     | const,const                    |    1 |   100.00 | Start temporary            |
|  1 | SIMPLE      | eear        | NULL       | ref    | idx_eearl_email_id,idx_eearl_address_id | idx_eearl_address_id | 108     | suitecrm.eabr.email_address_id |   19 |    10.00 | Using where                |
|  1 | SIMPLE      | emails      | NULL       | eq_ref | PRIMARY                                 | PRIMARY              | 108     | suitecrm.eear.email_id         |    1 |     5.00 | Using where; End temporary |
|  1 | SIMPLE      | emails_text | NULL       | eq_ref | PRIMARY                                 | PRIMARY              | 108     | suitecrm.eear.email_id         |    1 |   100.00 | Using index                |
+----+-------------+-------------+------------+--------+-----------------------------------------+----------------------+---------+--------------------------------+------+----------+----------------------------+
4 rows in set, 1 warning (0.00 sec)
```
Despite of the fact you have +90.000 emails rows, there is not so much data. The queries show behave the same

In this instance we are using a newer MySQL (Percona) version:
`Server version: 5.7.26-29 Percona Server`


Here you have the indexes in that instance:

```SQL
mysql> show index in emails;
+--------+------------+---------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table  | Non_unique | Key_name            | Seq_in_index | Column_name      | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------+------------+---------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| emails |          0 | PRIMARY             |            1 | id               | A         |       29426 |     NULL | NULL   |      | BTREE      |         |               |
| emails |          1 | idx_email_name      |            1 | name             | A         |        3960 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_message_id      |            1 | message_id       | A         |       29431 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_email_parent_id |            1 | parent_id        | A         |         104 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_email_assigned  |            1 | assigned_user_id | A         |           5 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_email_assigned  |            2 | type             | A         |          11 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_email_assigned  |            3 | status           | A         |          11 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails |          1 | idx_email_cat       |            1 | category_id      | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
+--------+------------+---------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
8 rows in set (0.00 sec)
```



```SQL
mysql> show index in emails_text;
+-------------+------------+---------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table       | Non_unique | Key_name            | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------------+------------+---------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| emails_text |          0 | PRIMARY             |            1 | email_id    | A         |       30301 |     NULL | NULL   |      | BTREE      |         |               |
| emails_text |          1 | emails_textfromaddr |            1 | from_addr   | A         |        2755 |     NULL | NULL   | YES  | BTREE      |         |               |
+-------------+------------+---------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.00 sec)
```

```SQL
mysql> show index in email_addr_bean_rel;
+---------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table               | Non_unique | Key_name             | Seq_in_index | Column_name      | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| email_addr_bean_rel |          0 | PRIMARY              |            1 | id               | A         |      689528 |     NULL | NULL   |      | BTREE      |         |               |
| email_addr_bean_rel |          1 | idx_email_address_id |            1 | email_address_id | A         |      663578 |     NULL | NULL   |      | BTREE      |         |               |
| email_addr_bean_rel |          1 | idx_bean_id          |            1 | bean_id          | A         |      608826 |     NULL | NULL   |      | BTREE      |         |               |
| email_addr_bean_rel |          1 | idx_bean_id          |            2 | bean_module      | A         |      667058 |     NULL | NULL   | YES  | BTREE      |         |               |
+---------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.00 sec)
```


```SQL
mysql> show index in emails_email_addr_rel;
+-----------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                 | Non_unique | Key_name             | Seq_in_index | Column_name      | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-----------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| emails_email_addr_rel |          0 | PRIMARY              |            1 | id               | A         |     1304459 |     NULL | NULL   |      | BTREE      |         |               |
| emails_email_addr_rel |          1 | idx_eearl_email_id   |            1 | email_id         | A         |      721256 |     NULL | NULL   |      | BTREE      |         |               |
| emails_email_addr_rel |          1 | idx_eearl_email_id   |            2 | address_type     | A         |     1304488 |     NULL | NULL   | YES  | BTREE      |         |               |
| emails_email_addr_rel |          1 | idx_eearl_address_id |            1 | email_address_id | A         |       65400 |     NULL | NULL   |      | BTREE      |         |               |
+-----------------------+------------+----------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.00 sec)
```

**Comment by pgorod** [comment]
See this new PR ☝️ for further improvements. It would be great if more people could help test it. Thanks

**Comment by evgu** [comment]
Is this planned for LTS 7.10.23 and release date please? I would only be able to test it against a copy of our production pre and post upgrade and provide you with the MySQL query timings.

**Comment by pgorod** [comment]
@evgu no, 7.10.23 is about to come out (any day now) so this won't be included. I don't know when it will be merged, actually having it tested more widely, beforehand, would be a significant factor to help getting it merged sooner. 

But ok, if you can only test it in production, I can understand you would prefer to wait.

In case you want to (very carefully) try the changes manually, here they are: https://github.com/salesagility/SuiteCRM/pull/8534/files
