### ISSUE TITLE
Upgrad to 7.11.3 version email body is empty

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7166]
#### Steps to Reproduce

1. 7.1.2 upgrade to 7.11.3
2. config inbound email
3. get email
4. view email detail, body is empty

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Hi @cekowu, I've pushed a fix here: #7171.

**Comment by cekowu** [comment]
thanks
