### ISSUE TITLE
Field Indented on Detailview when by itself on panel Suite7 & SuiteR

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#717]
If field is by itself in a panel, and takes up the whole row, like so:
![screenshot from 2015-11-26 14 25 33](https://cloud.githubusercontent.com/assets/13675281/11425023/aebe3066-9449-11e5-8ac7-48a8350dba58.png)

It shows up  more indented than other fields on the Detailview, like so:
![screenshot from 2015-11-26 14 27 04](https://cloud.githubusercontent.com/assets/13675281/11425047/d8416480-9449-11e5-8d45-7c515f3f6a38.png)

Have tested this with a few field types; iframe, Textarea, textfield, the E-mail Addresses field.
All have the same result.

**Comment by samus-aran** [comment]
Only seen in Suite7 & SuiteR
