### ISSUE TITLE
/Api/V8 needs the ability to return a list of modules

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#7174]
#### Issue

In `v4` and `/api/v8` you had the ability to get a list of all available modules.  Currently this functionality is missing from `/Api/V8`. It is a major blocker for plugin integrations which need to provide the user with a choice of modules they can connect to.

**Note** I'm splitting this issue off from #7083

#### Expected Behavior

Call `/Api/V8/modules` (or something else) and receive a list of available modules.

#### Actual Behavior

This functionality is missing.

#### Possible Fix

`/api/v8/` used the path `/modules/meta/list`

#### Context

Unable to list modules for integrations

#### Your Environment

* SuiteCRM Version used: 7.11.3

**Comment by Jason-Dang** [comment]
Currently looking at this.

**Comment by isleshocky77** [comment]
> Currently looking at this.

As in building it, or looking for the missing functionality?

**Comment by Jason-Dang** [comment]
I’ll be replicating the functionality with any appropriate adjustments as the implementation will likely differ from the old v8. Same for retrieving a list of module fields too.

**Comment by cameronblaikie** [comment]
Assessed :+1:
