### ISSUE TITLE
/include/SugarTheme/SugarThemeRegistry.php not created for 7.10.15 upgrade from 7.8.x

### ISSUE THREAD

**Issue by deuks** [salesagility/SuiteCRM#7191]
#### Issue
When upgrading from 7.8.x to 7.10.15 using the upgrade package, a fatal error occurs right after uploading the upgrade package.

#### Expected Behavior
Should continue to pre-flight check

#### Actual Behavior
html 500 err. Error logs state that they are missing SugarThemeRegistry.php (path in title).  File is found to be missing.  Problem doesn't occur when doing any other upgrade (moving from 7.8.x to 7.10.14 then moving from 7.10.14 to 7.10.15)

#### Possible Fix
Make sure SugarThemeRegistry.php is being included in the upgrade package, or created if it is a created file

#### Steps to Reproduce
1. Upgrade Crm to 7.8.27
2. Go to upgrade wizard
3.Choose file 7.8.x to 7.10.15.zip upgrade
4.Upload Package
5.Sometimes breaks immediately, sometimes breaks when you hit next to continue to pre-flight check

#### Context
Not a huge priorty since it isn't security related but without my old upgrade package (7.8.x to 7.10.14) I wouldn't be able to upgrade. Medium severity

#### Your Environment

* SuiteCRM Version used: 7.8.27
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome newest version
* Environment name and version (e.g. MySQL, PHP 7): MariaDB, PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04 LTS

**Comment by Dillon-Brown** [comment]
Hi @deuks, this should now be resolved. The issue here was actually that the file did, in fact, exist which resulted in a fatal PHP error due to a timing issue with sugartheme requires. This has been updated so that these files won't get copied over until the rest of the upgrade is complete. Let me know if you run into any further difficulties, thanks!.
