### ISSUE TITLE
Body are disappear when composing emails in 7.11.3

### ISSUE THREAD

**Issue by theehob** [salesagility/SuiteCRM#7202]
SuiteCRM Version 7.11.3
Sugar Version 6.5.25 (Build 344)
Centos 7
Php 7.2.16
10.1.38-MariaDB - MariaDB Server

When composing an email the Body area appears just for 1 second, then disappear.I can not write anything in the body of any email, so I cannot use the email module of the system

I have tried composing emails with the admin account and with a regular user account, same problem.

I am able to send and receive, import, etc perfectly with both admin and regular user accounts.

Please, I need help to solve this problem!

<img width="943" alt="Capture" src="https://user-images.githubusercontent.com/29521520/56300163-70fdfb00-6103-11e9-9fb7-d1310281e466.PNG">

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
