### ISSUE TITLE
Reminders Query error in log

### ISSUE THREAD

**Issue by tmaine** [salesagility/SuiteCRM#7210]
Getting this error in the SuiteCRM.log file over and over.

Fri Apr 19 06:52:11 2019 [7740][aca0ddaa-1095-e071-ee6e-5c45c9441fb4][FATAL]  Query Failed: SELECT  reminders.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , N'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , N'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , N'Users' assigned_user_name_mod FROM reminders   LEFT JOIN  users jt0 ON reminders.modified_user_id=jt0.id AND jt0.deleted=0
 AND jt0.deleted=0  LEFT JOIN  users jt1 ON reminders.created_by=jt1.id AND jt1.deleted=0
 AND jt1.deleted=0  LEFT JOIN  users jt2 ON reminders.assigned_user_id=jt2.id AND jt2.deleted=0
 AND jt2.deleted=0 where (reminders.popup = 1 AND (reminders.date_willexecute = -1 OR reminders.date_willexecute BETWEEN  AND )) AND reminders.deleted=0::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AND'.

* SuiteCRM Version 7.11.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Using Chrome version  73.0.3683.103 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):
MS SQL Server 2014
PHP 7.2.7
* Operating System and version (e.g Ubuntu 16.04):
Windows Server 2008 R2 Standard Service Pack 1 Build 7601

**Comment by pgorod** [comment]
@cameronblaikie I believe this is already fixed and the issue can be closed...
