### ISSUE TITLE
aCJK

### ISSUE THREAD

**Issue by dimpleliang** [salesagility/SuiteCRM#7211]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Hi @dimpleliang, please fill out the template and we can re-open or create a new issue and fill out the template there. Thanks!
