### ISSUE TITLE
7.11.3 version, can't import email address field when import leads data

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7212]
#### Steps to Reproduce

1. download leads template
2. fill leads data include email address
3. import data base on steps
4. studio ->leads-> layout ->listview, display "email address"
5. Email address is empty, Actually original data include it.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Hi @cekowu 

I have followed your steps and I cannot replicate this issue you are having. 
If you could test this on Version 7.11.4 to see if you are still getting this issue, if you are please let us know by commenting back.

Thanks,

**Comment by cekowu** [comment]
Thanks. I check in 7.11.4, it is ok now.
