### ISSUE TITLE
Responsive theme glitch

### ISSUE THREAD

**Issue by markbegbie** [salesagility/SuiteCRM#724]
For some browser window widths all buttons in the menu bar, other than the CRM name which links only to the front page, disappear.  When the browser is wider the full set appears, when it is narrower the hamburger menu appears in place of the CRM name.  This stumped me when I unplugged from desktop monitor.  Reloads did nothing, and it was only by chance a window resize gave me functionality back.

Screen grab attached.

<img width="1099" alt="screen shot 2015-11-28 at 10 41 34" src="https://cloud.githubusercontent.com/assets/16057567/11451456/c326ebda-95be-11e5-94aa-092f8f335f8f.png">

Suite 7.3.2 hosted on SA and accessed with Firefox 42.0 on Mac OsX El Cap.

**Comment by markbegbie** [comment]
Sorry, forgot to add Suite 7.3.2 hosted on SA and accessed with Firefox 42.0 on MacOs El Cap.

**Comment by mattlorimer** [comment]
981px - 991px
