### ISSUE TITLE
Upgrade stuck on "Upgrade Scripts in Progress" till timeout

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#7242]
#### Issue
Upgrade of SuiteCRM 7.11.3 to 7.11.4 stuck on "Upgrade Scripts in Progress" till browser error "The connection was reset" (probably because of some timeout).

#### Expected Behavior
The last steps of upgrade should be completed successfully.

#### Actual Behavior
Browser error "The connection was reset".

upgradeWizard.log last rows:
> Wed, 01 May 2019 09:48:29 +0300 [UpgradeWizard] - Cleaning up the session.  Goodbye.
> Wed, 01 May 2019 09:48:29 +0300 [UpgradeWizard] - at unlinkUWTempFiles()

#### Possible Fix
Restarting Apache after browser error.

#### Steps to Reproduce
1. Admin -> Upgrade Wizard
2. Uploading 7.11.X-TO-7.11.4 file
3. Completing (successfully) all the steps till "Upgrade Scripts in Progress"

#### Context
1. Although the error, the upgrade looks like been applied successfully, at least per About menu and working SuiteCRM (after Apache restart).
2. This issue observed on each 7.11 point release.
3. Next upgrade not possible till all cache/upgrades/temp directory are cleaned.
4. If relevant, Apache:
> Max Requests -> Per Child: 0 - Keep Alive: on - Max Per Connection: 100
> Timeouts -> Connection: 300 - Keep-Alive: 5

#### Your Environment
* SuiteCRM Version used: 7.11.3 (before upgrade)
* Browser name and version: Firefox 66.0.3 (64-bit)
* Environment name and version: MySQL 5.7.26-0ubuntu0.18.04.1, PHP 7 7.2.17-0ubuntu0.18.04.1, Apache 2.4.29, localhost
* Operating System and version: Kubuntu 18.04.2 (64-bit)

**Comment by stenfalp** [comment]
I had the same issue. Solved cleaning the aformentioned directory.

**Comment by bdcomp** [comment]
Just to confirm that it's still not fixed in the just released 7.11.7

**Comment by bjoern86** [comment]
Same here with update to 7.11.8

**Comment by bunglex** [comment]
same for me upgrading from 7.11.11 to 7.11.12
