### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uid' of undefined Since 7.11.4

### ISSUE THREAD

**Issue by holdusback** [salesagility/SuiteCRM#7244]
#### Issue
Since 7.11.4 I got a looping error (more than 1K error in less than a minute in the console).
Every time a go to module like Account, Lead, Contact etc ... In the listview sometime, and in detailview a lot of time : 
Uncaught TypeError: Cannot read property 'uid' of undefined

From /SuiteCRM/cache/include/javascript/sugar_grp1.js

#### Possible Fix

Line 322 : 
sugarListView.get_num_selected=function(){var selectCount=sugarListView.get_checks_count();if(selectCount>0)
return selectCount;return 0;}

Change to : 
sugarListView.get_num_selected=function(){var selectCount=$("input[name='selectCount[]']:first");if(selectCount.length>0)
return parseInt(selectCount.val().replace("+",""));return 0;}

I've just take the line from a backup before update, compare the two file, only this line changed, I've c/c the line from my backup to my actual SuiteCRM website, and for now I dont get the error.

#### Steps to Reproduce
Just update to 7.11.4

#### Your Environment

* SuiteCRM Version used: Last : 7.11.4
* Browser name : Last chrome Version

**Comment by holdusback** [comment]
Still the same issue in 7.11.5

Fixed it the same way as 7.11.4 !

**Comment by angar321** [comment]
I am also seeing this after updating to 7.11.6

About to try the fix suggested above

**Comment by holdusback** [comment]
Look like ave been fixed in 7.11.7 ? Run the new version for like 10 min, didnt had the error in the console.

**Comment by Dillon-Brown** [comment]
Closing in favour of #7626
