### ISSUE TITLE
Forking for Blockchain Integration - Call for Collaboration

### ISSUE THREAD

**Issue by jollysean** [salesagility/SuiteCRM#7247]
Hye Folks,

We are midwest based blockchain integrators. And we are planning to integrate Blockchain with CRM for contracts and financials. Ideally, I love the SuiteCRM package.
Any collaborators can connect with me at prabhat@solyd.tech

Is there any prior attempts or PR in this regard? What do you think?

Best Regards,
Prabhat

**Comment by Dillon-Brown** [comment]
Hi @

This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum). We use GitHub primarily for the reporting of Core SuiteCRM bugs and leave general questions and setup specific issues to the forums.

Thanks.
