### ISSUE TITLE
[language] Unused language strings in ver. 7.11.4 (Administration) 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#7254]
These unused strings have been already removed earlier (https://github.com/salesagility/SuiteCRM/commit/37c91292dc99ded80572b882181, https://github.com/salesagility/SuiteCRM/commit/d9a2f73386cdd5ecad11b8), but reappeared in ver. 7.11.4

['LBL_FTS_SETTINGS']
['LBL_FTS_SETTINGS_DESC']
['LBL_GLOBAL_TEAM_DESC']
['LBL_GLOBAL_TEAM_SELECT']
['LBL_GLOBAL_TEAM']
https://github.com/salesagility/SuiteCRM/blob/v7.11.4/modules/Administration/language/en_us.lang.php#L250-L254

['LBL_UPDATE_CHECK_AUTO']
['LBL_UPDATE_CHECK_MANUAL']
https://github.com/salesagility/SuiteCRM/blob/v7.11.4/modules/Administration/language/en_us.lang.php#L535-L536

['LBL_JJWG_MAPS_ADMIN_DONATE_TITLE']
['LBL_JJWG_MAPS_ADMIN_DONATE_DESC']
https://github.com/salesagility/SuiteCRM/blob/v7.11.4/modules/Administration/language/en_us.lang.php#L795-L796

['LBL_AOP_OPENING_DAYS']
['LBL_AOP_OPENING_HOURS']
['LBL_AOP_CLOSING_HOURS']
https://github.com/salesagility/SuiteCRM/blob/v7.11.4/modules/Administration/language/en_us.lang.php#L859-L861

**Comment by asha15** [comment]
@likhobory  So do we need to remove this from 7.11.4?

**Comment by Dillon-Brown** [comment]
Hi @asha15, from a quick look it seems like these strings are in both ```hotfix-7.10.x``` and ```hotfix```. If you were interested in working on this I would make the removal PR to the ```hotfix-7.10.x``` branch which will later on get merged into ```hotfix```. Thanks!

**Comment by asha15** [comment]
@Dillon-Brown I have worked on the issue. Kindly request you to remove the string from the ```hotfix-7.10.x```  branch, so i can send a PR
