### ISSUE TITLE
7.11.4 v8 api can't work

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7265]
#### Steps to Reproduce

1. Upgrade to 7.11.4 version
2. {host}/SuiteCRM/Api/access_token?response_type=JSON
3. After upgrade ,response 500 error
4. Open debug mode，error:
   
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Including module specific hook file for custom/modules
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Including Ext hook file for custom/application
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/slim.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/controllers.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/factories.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/globals.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/helpers.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/middlewares.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/params.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/services.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/validators.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/services.php
Tue May  7 09:44:01 2019 [24429][-none-][DEBUG] Custom file is not exists: custom/application/Ext/Api/V8/beanAliases.php

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cekowu** [comment]
I have fixed it

**Comment by Samurais** [comment]
Can you describe how to fix this problem? Thanks.

**Comment by rashaqqel** [comment]
how was this fixed?
