### ISSUE TITLE
Email Template selection in email module is not working for 7.10.16

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#7271]
#### Issue

Selecting email template when composing the email, it does not work. There is no action.
#### Expected Behavior

It should be working like expected.
#### Actual Behavior

There is no log. I tried it new installation of SuiteCRM
#### Steps to Reproduce

1. Open email module
2. Compose
3. Select email template
4. There is no action when template selected.

#### Context

medium priority
#### Your Environment

* SuiteCRM Version used: 7.10.16
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 66.0.5 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04

**Comment by dursuntosun** [comment]
Other selections are also not working.

**Comment by Dillon-Brown** [comment]
@dursuntosun Which other selectors? can you raise them here too? thanks.

**Comment by dursuntosun** [comment]
![image](https://user-images.githubusercontent.com/22373035/57444706-6c87b680-7259-11e9-9041-56ec5b153fc7.png)

**Comment by Mausino** [comment]
@Dillon-Brown here is gif screen what @dursuntosun thinked. My position of fields were changed but same problem is on fresh installation. 

![compose_email_issue](https://user-images.githubusercontent.com/5773777/57447722-fafb3880-7257-11e9-9922-8229c158ed27.gif)

**Comment by kunsirat-kps** [comment]
I have the same problem here. Both email template and relate to could not be loaded to compose modal after selected. Please provide some suggestion or fix this bug as soon as possible.

My Environment:
SuiteCRM Version used: 7.11.4
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 73.0.3683.86 (64-bit)
Environment name and version (e.g. MySQL, PHP 7): PHP 7.2
Operating System and version (e.g Ubuntu 16.04): Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

**Comment by Mausino** [comment]
@kunsirat-kps @dursuntosun 

I've reverted this file to previous version (before upgrade) and seems that is working now :
jssource/src_files/include/javascript/popup_helper.js

**Comment by dursuntosun** [comment]
@Mausino, which version talking about?

**Comment by Mausino** [comment]
@dursuntosun i upgraded from 7.11.3 to 7.11.4. 
I took whole file from previous version and patches it by it. It is fast solution... sorry i haven't time to look on side effects, priority was that it is working again.. will look on it at weekend :)

**Comment by kunsirat-kps** [comment]
@Mausino If there are any side effects please inform on this post too. Thank you so much.

**Comment by dursuntosun** [comment]
When i tried fix, it is working now. But i could not know side effects?

**Comment by kikobar** [comment]
Upgraded to 7.11.5 and I still experience this issue.

**Comment by markaz32** [comment]
I have the same problem with 7.11.4 and 7.11.6. I have tried change both popup_helper.js files from previous versions of SuiteCRM, performed quick R&R and JS Repair. No matter which browser I use from any workstation, I cannot get an email template to propogate into email selection.  

I host multiple SuiteCRM instances for multiple companies with builds ranging from 7.11.4 to 7.11.6. None work, all of them once worked.  What is the solution?

**Comment by Mausino** [comment]
@kikobar please upgrade to latest version 7.11.6 and let us know if working :)

**Comment by markaz32** [comment]
@Mausino I have just done myself done that to try and fix same problem.  I have multiple instances of 7.11.4 not working.  I have upgraded 2 instances to 7.11.6. one worked after multiple attempts at quick R&R plus JS Repair.  The other has not.  I have no idea why. I even copied the two popup_helper.js files between the two and made repairs.

Still second instance not working,  I have 5 x instances total to fix. All other on 7.11.4 and broken.

**Comment by markaz32** [comment]
I can confirm it works once browser cache is deleted.

**Comment by Mausino** [comment]
@Mac-Rae 👍

**Comment by kikobar** [comment]
I upgraded to 7.11.6 and I can confirm that now it works well :)
Thanks!

**Comment by jr-clark** [comment]
Running a fresh install of :

Version 7.11.6  
Sugar Version 6.5.25 (Build 344)

This problem appears to be resolved when using the latest versions of firefox/chrome, but the problem still occurs in IE11 and Edge.

After selecting a template and hitting the OK button, nothing happens. No template data is loaded. The debug console in IE11/Edge breaks at line 1334/1335 EmailsComposeView.js with an error.

**Comment by markaz32** [comment]
@jr-clark I just tried the same and you are correct. I even deleted all history and still it does not work in IE11. Does work in Opera and Chrome

**Comment by jr-clark** [comment]
Is the process to reopen this issue or should a new issue be created?

**Comment by samus-aran** [comment]
I would suggest open a new one specific to Edge :)
