### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7272]
This issue is for reporting any flaky tests people run into. Hopefully, if we start reporting flaky tests we can find common sources of flakiness and start getting rid of them.

Please comment with a link to the test case, the PR and/or commit the test was run on, and the Travis CI job where it failed if you run into a flaky test :)

Template:

```
- Commit/PR: LINK_TO_COMMIT_OR_PR 
- Test case: [`TEST_FILE_PATH:TEST_NAME`](https://github.com/salesagility/SuiteCRM/blob/COMMIT_SHA/TEST_FILE_PATH)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/JOB_ID
- Branch: BRANCH_NAME
- Details: 
```

Inspired by the process described in https://samsaffron.com/archive/2019/05/15/tests-that-sometimes-fail

**Comment by connorshea** [comment]
- PR: https://github.com/salesagility/SuiteCRM/pull/7262
- Test case: [`tests/acceptance/modules/AOR_Reports/AOR_ReportsCest.php:testScenarioDeleteRecordFromDetailView`](https://github.com/salesagility/SuiteCRM/blob/3a1b2ba1f92a158f328f3ef8c7ce9a41cfcecba3/tests/acceptance/modules/AOR_Reports/AOR_ReportsCest.php#L283)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/529848382
- Branch: `hotfix-7.10.x`
- Details: It succeeded on PHP 5.6 through 7.1, but failed on 7.2.

**Comment by connorshea** [comment]
- Commit: https://github.com/salesagility/SuiteCRM/commit/9215d2d4024bb75697f7a10fa43e75ab04964385
- Test case: [`tests/acceptance/Core/IssueModuleCest.php:testScenarioViewRecordFromListView`](https://github.com/salesagility/SuiteCRM/blob/3a1b2ba1f92a158f328f3ef8c7ce9a41cfcecba3/tests/acceptance/Core/IssueModuleCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/542691310                                                                                                                                                                                                                                                                                                                                 - Branch: hotfix-7.10.x
- Details: Failed on 5.5, passed on all others.

**Comment by connorshea** [comment]
- PR: https://github.com/salesagility/SuiteCRM/pull/7345
- Test case: [`tests/acceptance/Core/CompanyModuleCest.php:testScenarioViewCompanyTestModule`](https://github.com/salesagility/SuiteCRM/blob/be18dabe7c7eb417d0ec428f0faacce05f3d54e8/tests/acceptance/Core/CompanyModuleCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/542804172
- Branch: hotfix-7.10.x
- Details: Failed on PHP 7.1, passed on others.

**Comment by connorshea** [comment]
- Commit: https://github.com/salesagility/SuiteCRM/commit/2c69befeb17ea68bfc3733dd18d52fe4d08f08b9
- Test case: [`tests/acceptance/modules/Users/UsersCest.php:testShowCollapsedSubpanelHint`](https://github.com/salesagility/SuiteCRM/blob/2c69befeb17ea68bfc3733dd18d52fe4d08f08b9/tests/acceptance/modules/Users/UsersCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/542791172
- Branch: hotfix-7.10.x
- Details: Failed on PHP 7.1, passed on others.

**Comment by connorshea** [comment]
- Commit: https://github.com/salesagility/SuiteCRM/commit/2c69befeb17ea68bfc3733dd18d52fe4d08f08b9
- Test case: [`tests/acceptance/Core/ModuleBuilderFieldsCest.php:testScenarioAddHtmlField`](https://github.com/salesagility/SuiteCRM/blob/2c69befeb17ea68bfc3733dd18d52fe4d08f08b9/tests/acceptance/Core/ModuleBuilderFieldsCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/542791170
- Branch: hotfix-7.10.x
- Details: Failed on PHP 7.0, passed on others.

**Comment by connorshea** [comment]
- PR: #7345
- Test case: [`tests/acceptance/Core/IssueModuleCest.php:testScenarioViewIssueTestModule`](https://github.com/salesagility/SuiteCRM/blob/c0fb6f166d274cdd434cded829d0ad9a415cedc1/tests/acceptance/Core/IssueModuleCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/542804174
- Branch: hotfix-7.10.x
- Details: Failed on PHP 7.3, passed on others.

```
  [Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"css selector","selector":".listViewBody"}
```

**Comment by connorshea** [comment]
- PR: https://github.com/salesagility/SuiteCRM/pull/7378
- Test case: [`tests/acceptance/modules/Accounts/AccountsCest.php:testScenarioCreateAccountChild`](https://github.com/salesagility/SuiteCRM/blob/83ba237a4eb48255b1e9e6eb62e37c2a046a4406/tests/acceptance/modules/Accounts/AccountsCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/544636987 / https://travis-ci.org/salesagility/SuiteCRM/jobs/544636988
- Branch: master
- Details: Failed on PHP 7.0 and 7.1, passed on others.

```
1) AccountsCest: Create an Account
 Test  tests/acceptance/modules/Accounts/AccountsCest.php:testScenarioCreateAccountChild
                                                                                                                                                                                                                                                                                                                                   
  [Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"css selector","selector":".listViewBody"}
  (Session info: headless chrome=75.0.3770.80)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.15.0-1028-gcp x86_64)  
                                                                                                                                                                                                                                                                                                                                   
Scenario Steps:
 11. $I->waitForElementVisible(".listViewBody",120) at tests/_support/Step/Acceptance/ListView.php:50
 10. $I->click("Accounts","#toolbar.desktop-toolbar  > ul.nav.navbar-nav > ...") at tests/_support/Step/Acceptance/NavigationBarTester.php:96
 9. $I->waitForElementVisible("#toolbar.desktop-toolbar  > ul.nav.navba...",120) at tests/_support/Step/Acceptance/NavigationBarTester.php:95
 8. $I->click("All","#toolbar.desktop-toolbar  > ul.nav.navbar-nav > li.top...") at tests/_support/Step/Acceptance/NavigationBarTester.php:93
 7. $I->wait(1) at tests/_support/Step/Acceptance/NavigationBarTester.php:92
 6. $I->waitForElementVisible("#toolbar.desktop-toolbar  > ul.nav.navbar...",30) at tests/_support/Step/Acceptance/NavigationBarTester.php:91
```

**Comment by connorshea** [comment]
I think most of these should be fixed by #7417, except maybe the `AORReportsCest` failure. :D It's still useful to catalogue these if they happen in the future, though, so I don't know if we should close this issue when that PR is merged?

**Comment by connorshea** [comment]
- Commit/PR: https://github.com/salesagility/SuiteCRM/pull/7472/commits/e58e8594bb8e76e9ae9342a7bf61e54104cc85db
- Test case: [`tests/acceptance/modules/Home/HomeCest.php:testCreateChartsDashlet`](https://github.com/salesagility/SuiteCRM/blob/7f0e592de77c3ab1e122c19696d6747ce417dae4/tests/acceptance/modules/Home/HomeCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/550447955
- Branch: hotfix-7.10.x
- Details: Failed on PHP 5.6, all other versions passed

Screenshot left by acceptance test: https://www.simpleupload.co.uk/uploads/YjbP0HomeCest.testCreateChartsDashlet.fail.png
![image](https://user-images.githubusercontent.com/2977353/60127255-f7126f80-974c-11e9-9364-fd1baad7f1b3.png)

It seems to be pretty rare.

Error message:
```
1) HomeCest: Create a chart dashlet on the dashboard
 Test  tests/acceptance/modules/Home/HomeCest.php:testCreateChartsDashlet
                                                                                                                                                                                                                                                              
  [Facebook\WebDriver\Exception\ElementNotVisibleException] element not visible
  (Session info: headless chrome=75.0.3770.100)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-101-generic x86_64)  
                                                                                                                                                                                                                                                              
Scenario Steps:
 18. $I->click("All Opportunities By Lead Source By Outcome") at tests/acceptance/modules/Home/HomeCest.php:52
 17. $I->click("#chartCategory") at tests/acceptance/modules/Home/HomeCest.php:51
 16. $I->waitForElementVisible("#chartCategory") at tests/acceptance/modules/Home/HomeCest.php:50
 15. $I->click("Add Dashlets","#tab-actions > .dropdown-menu") at tests/_support/Step/Acceptance/DetailView.php:26
 14. $I->waitForElementVisible("#tab-actions > .dropdown-menu") at tests/_support/Step/Acceptance/DetailView.php:24
 13. $I->click("ACTIONS","#tab-actions") at tests/_support/Step/Acceptance/DetailView.php:23
#1  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:110
#2  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
#3  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:535
#4  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
#5  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/RemoteWebElement.php:82
#6  Codeception\Module\WebDriver->click
#7  /home/travis/build/salesagility/SuiteCRM/tests/_support/_generated/AcceptanceTesterActions.php:606
#8  /home/travis/build/salesagility/SuiteCRM/tests/acceptance/modules/Home/HomeCest.php:52
#9  HomeCest->testCreateChartsDashlet
```

**Comment by connorshea** [comment]
- Commit/PR: https://github.com/salesagility/SuiteCRM/commit/ba1f514841a4d421c850aedc0d55cc3b939bb548 
- Test case: [`tests/acceptance/modules/Cases/CasesCest.php:testScenarioCreateCase`](https://github.com/salesagility/SuiteCRM/blob/ba1f514841a4d421c850aedc0d55cc3b939bb548/tests/acceptance/modules/Cases/CasesCest.php)
- Travis CI job: https://travis-ci.org/salesagility/SuiteCRM/jobs/552757011
- Branch: hotfix-7.10.x
- Details: Fails on PHP 5.5, passes on all others.

![image](https://user-images.githubusercontent.com/2977353/60533982-144fbc80-9cbe-11e9-8616-1ff5a1c05682.png)

```
1) CasesCest: Create a case
 Test  tests/acceptance/modules/Cases/CasesCest.php:testScenarioCreateCase
                                                                                                                                                                                                                                                                                                                                     
  [Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"css selector","selector":".detail-view"}
  (Session info: headless chrome=75.0.3770.100)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-101-generic x86_64)  
                                                                                                                                                                                                                                                                                                                                     
Scenario Steps:
 55. $I->waitForElementVisible(".detail-view") at tests/_support/Step/Acceptance/DetailView.php:35
 54. $I->click("Save") at tests/_support/Step/Acceptance/EditView.php:22
 53. $I->executeJS("window.scrollTo(0,0); return true;") at tests/_support/Step/Acceptance/EditView.php:21
 52. $I->seeElement("#assigned_user_name") at tests/_support/Step/Acceptance/Cases.php:33
 51. $I->executeJS("tinyMCE.activeEditor.setContent("TinyMCE Content Test");") at tests/_support/Step/Acceptance/Cases.php:31
 50. $I->selectOption("#status","Duplicate") at tests/_support/Step/Acceptance/Cases.php:29
#1  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:102
#2  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
#3  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:535
#4  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:176
#5  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/WebDriverExpectedCondition.php:186
#6  Facebook\WebDriver\WebDriverExpectedCondition::Facebook\WebDriver\{closure}
#7  /home/travis/build/salesagility/SuiteCRM/vendor/facebook/webdriver/lib/WebDriverWait.php:67
#8  Codeception\Module\WebDriver->waitForElementVisible
#9  /home/travis/build/salesagility/SuiteCRM/tests/_support/_generated/AcceptanceTesterActions.php:2386
#10 /home/travis/build/salesagility/SuiteCRM/tests/_support/Step/Acceptance/DetailView.php:35
```

**Comment by connorshea** [comment]
Another instance of the CasesCest failure, with the same details except it was on PHP 7.2 and this is the screenshot:

![image](https://user-images.githubusercontent.com/2977353/60534318-be2f4900-9cbe-11e9-8517-cb4dd535a796.png)

**Comment by pgorod** [comment]
Every time I see this Issue I have a vision of this in my mind
![image](https://user-images.githubusercontent.com/15945027/61639413-52277b80-ac93-11e9-8ca4-07f411aa9d88.png)

**Comment by connorshea** [comment]
@Dillon-Brown are you aware of any tests that are still flaky at the moment? I haven't seen any recently.
