### ISSUE TITLE
Case suggestions from KB are not displayed

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#728]
- For the current moment when the case subject is for example "name servers" you will get all suggestions with the article name "name servers"
![default](https://cloud.githubusercontent.com/assets/1594411/11500046/f3646eb2-982a-11e5-8afd-429a2ab4437f.png)

- When the case subject is for example "Howto change the name servers" you will not get any suggestions.
![no_suggestions](https://cloud.githubusercontent.com/assets/1594411/11500024/c045de3a-982a-11e5-89a1-f3dc84c0917e.png)

- Also when you click on edit you first need to type a space or remove some word from the subject text field before you get the suggestions lists.
Don't know if their is still a possibility for change request on this, if so, i would suggest to change the suggestions to typeahead field.

**Comment by ghermans** [comment]
- For the current moment when the case subject is for example "name servers" you will get all suggestions with the article name "name servers"
![default](https://cloud.githubusercontent.com/assets/1594411/11500046/f3646eb2-982a-11e5-8afd-429a2ab4437f.png)


- When the case subject is for example "Howto change the name servers" you will not get any suggestions.
![no_suggestions](https://cloud.githubusercontent.com/assets/1594411/11500024/c045de3a-982a-11e5-89a1-f3dc84c0917e.png)


- Also when you click on edit you first need to type a space or remove some word from the subject text field before you get the suggestions lists.
Don't know if their is still a possibility for change request on this, if so, i would suggest to change the suggestions to typeahead field.

**Comment by Mausino** [comment]
:+1:
