### ISSUE TITLE
Top of dashlets being cut off by nav bar

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#7284]
#### Issue

The top of dashlets are being cutoff by the navbar on chrome. This only happens on specific display settings with any dashlet except the first dashlet at the top of the page. This occurs in `MySugar.js` in the `configureDashlet` function. The if statement around line 203 calculates if a newTop is needed and will calculate the top (in my case) to -90px which cuts off the dashlet. 

This does not happen on Firefox.

![dashletCutoff](https://user-images.githubusercontent.com/7209185/57721795-f4930500-7639-11e9-9ef3-5114184f4ab3.png)

#### Expected Behavior

The dashlet should not be cut off

#### Actual Behavior

The dashlet gets cut off

#### Possible Fix

My quick fix was to just subtract 50 from the newTop calculation. I don't know what an actual fix should look like though. 

#### Steps to Reproduce

1. Windows 10 display settings > Advanced scalling settings: This must be set to 125%
2. Screen resolution: 1920 x 1080
3. Open chrome to the dashboard page
4. The first dashboard will open fine, all other dashboards will open with the top cut off by the navbar

#### Your Environment

* SuiteCRM Version used: 7.10.2
* SuiteCRM Theme used: SuiteP
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome version 74
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): windows 10

**Comment by gunnicom** [comment]
Duplicate?
https://github.com/salesagility/SuiteCRM/issues/5695

**Comment by wiatrp** [comment]
Possibly. #5695 says SuiteP theme is not affected though and I am using SuiteP with my setup. I just updated the issue to include that.
