### ISSUE TITLE
Emails 'Bulk Action' is disabled after upgrade to 7.10.16

### ISSUE THREAD

**Issue by kikobar** [salesagility/SuiteCRM#7298]
#### Issue
After upgrading to version 7.10.16 the 'BULK ACTION' button of the email inbox is disabled, so it is not possible to import multiple emails from the Inbox view.
Additionally, I am not able to open any email except from the 'default' Inbox account. If I chose a different folder on the default account or any folder of the other accounts the emails won't open, and therefore they won't be possible to imported individually either.

#### Expected Behavior
After selecting one or multiple messages in the inbox view, the 'bulk action' button should become available for choosing an action (ie. import).

#### Actual Behavior
After selecting one or multiple messages in the inbox view, the 'bulk action' button remains disabled (grayed out and not available for clicking)

#### Steps to Reproduce

1. Navigated to activities/emails
2. Select a few emails using the tick-box on the left

#### Your Environment

* SuiteCRM Version used: 7.10.16
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 66.0.5 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.6 LTS

**Comment by blloyd78** [comment]
This bug is still present in 7.10.17

**Comment by kikobar** [comment]
This bug is still present in 7.11.5

**Comment by blloyd78** [comment]
I have installed and tested the 7.10.19 upgrade and can confirm that the 'Bulk Action' is still disabled.

Please re-open and review this issue.

**Comment by kikobar** [comment]
@blloyd78 this was fixed in 7.11.7

**Comment by blloyd78** [comment]
I cleared cache as instructed and this happened: 

![Screenshot 2019-08-04 at 08 32 21](https://user-images.githubusercontent.com/17355746/62420953-84bd7500-b692-11e9-90cb-839a5722d291.png)

The dashboard is similarly blank. 
![Screenshot 2019-08-04 at 08 33 48](https://user-images.githubusercontent.com/17355746/62420963-9a329f00-b692-11e9-95f5-b0bf26a6935e.png)
