### ISSUE TITLE
Scheduled Reports ignoring Time Zone setting

### ISSUE THREAD

**Issue by jwkramer61** [salesagility/SuiteCRM#7305]
#### Issue
When scheduling a report, the scheduled launch time must be in GMT in order for it to run at the correct time.

#### Expected Behavior
Report Scheduler should use the timezone setting to get the correct launch time.

#### Actual Behavior
Report runs using GMT. No errors are logged since the report runs correctly, just at the wrong time.

#### Possible Fix
unknown

#### Steps to Reproduce
1. Schedule a report.

#### Context
Scheduling a report using GMT will cause issues with Daylight Savings Time. In regions that use DST, the offset adjustment to GMT will change +/- 1 hour based upon current DST offset.
Medium Priority

#### Your Environment

* SuiteCRM Version used: v7.11.4
* Chrome Version Version 74.0.3729.169 (Official Build) (64-bit)
* Environment name and version: MySQL, PHP 7.3.5
* Operating System and version: Windows Server 2012 R2 & IIS v8.5.9600.16384

Attachments:
Current report scheduler in sync with local time
![scheduler2](https://user-images.githubusercontent.com/50463174/58182249-43b0e980-7c7b-11e9-9962-5a6e4a93233b.jpg)

Report being scheduled to run at 14:05 (current system time 10:01)
![scheduler3](https://user-images.githubusercontent.com/50463174/58182400-883c8500-7c7b-11e9-9a9a-cf085187791e.jpg)

Report right after it runs (4 hours in the future)
![scheduler5](https://user-images.githubusercontent.com/50463174/58182541-c639a900-7c7b-11e9-9b19-85e096ff315c.jpg)

Received e-mail
![scheduler6](https://user-images.githubusercontent.com/50463174/58182575-db163c80-7c7b-11e9-8423-e4524944c27e.jpg)

Administrator User Timezone setting
![scheduler7](https://user-images.githubusercontent.com/50463174/58182661-06992700-7c7c-11e9-998e-6b980ac915d1.jpg)

PHP.INI timezone setting
![scheduler8](https://user-images.githubusercontent.com/50463174/58182689-19abf700-7c7c-11e9-8da0-b2d1ea0d1dee.jpg)

CRON.BAT PHP launch with "-c" switch set
![scheduler9](https://user-images.githubusercontent.com/50463174/58182847-5546c100-7c7c-11e9-92ea-20e4d9622d28.jpg)

**Comment by pgorod** [comment]
I've seen more people complaining about this recently. Is this is a new issue or was it like this before?

**Comment by jwkramer61** [comment]
we have only been using product for a month or so, and are in fact still migrating from Salesforce. Wish I could be more help, but I'm not sure if it is a new issue or not.

**Comment by samus-aran** [comment]
This is technically a duplicate but since it is newer we'll close the older one & reference it here.
https://github.com/salesagility/SuiteCRM/issues/1744

**Comment by jwkramer61** [comment]
> This is technically a duplicate but since it is newer we'll close the older one & reference it here.
> #1744

I actually saw that other issue - I do not believe they are exactly the same. The older issue seems like it was an asthetic issue with displayed times. This issue is a functional one. The reports are not running at the correct time. In addition, if you are located in an area that uses Daylight Savings Time, the offset will change +/- 1 hour, which physically changes the time when your reports run. This is more than just asthetics... Thanks!

**Comment by samus-aran** [comment]
Thanks for that :+1: . Ideally resolving the time saved of UTC would be standardised (and following the conventional way of doing it) so that when the user views the time it will be formatted as expected using the overlay of the timezone like other date/datetime fields across other parts of the application. so its like a killing two bugs with one fix :+1:

**Comment by Lehnerr** [comment]
Pls fix it.
 I found out that there is a mix of the timezones which is retouned from functions.
As workaround I changed following in modules\AOR_Scheduled_Reports\AOR_Scheduled_Reports.php and now it works as expected:
`    public function shouldRun(DateTime $date)
    {
        global $timedate;
        if (empty($date)) {
            $date = new DateTime();
        } 
        //date is at system timezone
        $date->setTimezone(new DateTimeZone("UTC"));
        $cron = Cron\CronExpression::factory($this->schedule);
        //cron returns UTC Time
        if (empty($this->last_run) && $cron->isDue($date)) {
            return true;
        }
        $lastRun = $timedate->fromDb($this->last_run);
        $lastRun->setTimezone(new DateTimeZone("Europe/Berlin"));
        $next = $cron->getNextRunDate($lastRun);
        //next returns system timezone   
         $next->setTimezone(new DateTimeZone("UTC"));
        if ($next < $date) {
            return true;
        }
        return false;
    }
}`

**Comment by pgorod** [comment]
This can be closed now, right?

**Comment by mattlorimer** [comment]
Yes, this is fixed in the current release.
