### ISSUE TITLE
API v8 not working on php-fcgid - Missing /api/.htaccess

### ISSUE THREAD

**Issue by adriangibanelbtactic** [salesagility/SuiteCRM#7306]
#### Issue

Accesing /Api/access_token according to https://docs.suitecrm.com/developer/api/version-8/json-api/#_authentication does not return access token.

#### Expected Behavior
The access token should be returned when proper client_id and client_secret is sent.

#### Actual Behavior
The access token is not returned.
404 is found on the apache logs.
The text returned is:
```
No input file specified.
```

#### Possible Fix
One needs to add an specific .htaccess to the /Api folder. That .htaccess was previously in the git repo and can be found at: https://github.com/salesagility/SuiteCRM/blob/a29cc3a54b2d486d3a0ea5de4c6f1b445a3cc418/Api/.htaccess on commit https://github.com/salesagility/SuiteCRM/commit/a29cc3a54b2d486d3a0ea5de4c6f1b445a3cc418 .

#### Steps to Reproduce
This is a php example call to access Accesing /Api/access_token according to https://docs.suitecrm.com/developer/api/version-8/json-api/#_authentication .
```
<?php

$token_url = 'https://crm.dominio.com/Api/access_token';
$module_url = 'https://crm.dominio.com/Api/V8/module/';
$client_id = '12345678-1ab123456-9585-777778888999';
$client_secret = 'MYSECRET';
$ch = curl_init();
$header = array(
    'Content-type: application/vnd.api+json',
    'Accept: application/vnd.api+json'
 );
$postStr = json_encode(array(
    'grant_type' => 'client_credentials',
    'client_id' => $client_id,
    'client_secret' => $client_secret
));
curl_setopt($ch, CURLOPT_URL, $token_url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
curl_setopt($ch, CURLOPT_POSTFIELDS, $postStr);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
$output = curl_exec($ch);
$out = json_decode($output,true);
print_r ($output);
print_r ($out);
?>
```

#### Context
I was trying to use v8 API to obtain data from CRM
I think this is a medium priority issue which might be hidden to some final users which have updated from earlier SuiteCRM versions where this /Api/.htaccess is carried around.

#### Additional details
I suspect this issue also happens to users that do not use fcgid. As I said before this issue should be triggered if /Api/.htaccess is not found.

#### Your Environment
* SuiteCRM Version used: 7.10.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Non relevant
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.32-0ubuntu0.16.04.1 , MySQL 5.7.23-0ubuntu0.16.04.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by adriangibanelbtactic** [comment]
I should write down that prior to these tests I applied this pull request : https://github.com/salesagility/SuiteCRM/pull/7173 .
I'm not sure if it's compulsory so that everything works ok on fcgid but having it applied does not make any harm on a fcgid setup.

So just add this experience as if https://github.com/salesagility/SuiteCRM/pull/7173 has been additionally been tested.

**Comment by connorshea** [comment]
I think I'm running into this same issue while trying to setup API tests on GitLab CI :) `/Api/access_token` returns a 404 error, and I don't have fastCGI set up.

**Comment by connorshea** [comment]
Using the htaccess file from the mentioned commit causes a 500 error in CI upon requesting the access_token route.

**Comment by pgorod** [comment]
Is this still an issue on the latest version?

**Comment by filev-svt** [comment]
In my opinion, this is somehow linked to the #8251 issue. 

The version I use is 7.10.10 and I had similar problems with "No input file specified" until I tried getting the access token from /Api/index.php/access_token - that surprisingly worked just fine and I got the token successfully. However, when I tried a sample request with the Bearer token specified all responses I got from Api/index.php/V8/module/Accounts were 401s with "Access token could not be verified" message. 

When I tried the Api/V8/module/Accounts URL I got the "No input file specified" again. 

I also had the index.php file missing in lib/API/V8. I pulled the current master content of the Api folder and lib folder, but that doesn't seem to fix anything.

**Comment by tsitle** [comment]
@adriangibanelbtactic For testing my proposed fix for this issue in PR-8486 I also tried your PHP code and it worked for me. Since I'm using a self-signed certificate for SSL I added a few options to yours:
```
// for self-signed certificates only: ignore SSL verification errors
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```
Maybe this is useful for others, too.

**Comment by mounirawy** [comment]
I am having the same issue with the latest version and the latest stable version on nginx siteground what should I do please help
