### ISSUE TITLE
Duplicating the Accounts - Member Of Field Help

### ISSUE THREAD

**Issue by BzerkSkemer** [salesagility/SuiteCRM#7330]
#### Issue

Unable to find how to duplicate the Member Of section in the Accounts Fields / Relationships
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Hi there @BzerkSkemer 

This is more for our forms which can be found here - https://suitecrm.com/suitecrm/forum/
Also, have a look at the documentation site as it may help with what you are having trouble with. 
https://docs.suitecrm.com/admin/administration-panel/studio/

In future coukld you please detail more information when listing an issue, there is a template which can guide u on what information goes where.

Thank you,
