### ISSUE TITLE
Upgrade to 7.10.x - Lato font files empty

### ISSUE THREAD

**Issue by mattf10** [salesagility/SuiteCRM#7331]
Similar to this issue:  https://github.com/salesagility/SuiteCRM/issues/5915

#### Issue
Use upgrade wizard to upgrade to latest version and the SuiteP Lato font files are overwritten with empty files.  This folder:  /themes/SuiteP/fonts/

#### Expected Behavior
Fonts files should not be replaced, or replaced with files that contain data.

#### Actual Behavior
Font files are overwritten with empty files.

#### Possible Fix
Tried setting font file permissions to 440 before upgrade.  This stopped the upgrade wizard from proceeding since there were files without write permissions.

#### Steps to Reproduce

1.  Admin -> Upgrade Wizard
2. Upgrade to latest version of 7.10 
3. Clear cache.  Fonts no longer loaded, so pages don't display correctly

#### Context
This has happened with every upgrade since I moved from 7.8.x to 7.10.x

#### Your Environment

7.10.16
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
Happens on two different servers - one Ubuntu 18.04 / PHP 7.2 / nginx and the other Ubuntu 16.04 / PHP 7.1 / Apache

**Comment by cameronblaikie** [comment]
Hi there, this is a bug and we will update the current release packages and those going forward.

**Comment by Dillon-Brown** [comment]
Pack updated, I actually only managed to find this issue in the 7.10.x to 7.10.17 upgrade. Should now be fixed on all future upgrade packs. Thanks!
