### ISSUE TITLE
Removing a link to G+ from website

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteCRM#7335]
#### Issue
As G+ is closed for good, a link this pages should be removed.

#### Expected Behavior
No link to G+

#### Actual Behavior
A link to G+ on footer of https://suitecrm.com (and all/most site pages).

#### Possible Fix
Remove this bad link from all site pages.

#### Context
Google+ was shut down for business use and consumers on April 2, 2019.

**Comment by jasonappah** [comment]
I'll go ahead and remove it.

**Comment by jasonappah** [comment]
Never mind, looks like the links have already been removed. Would someone like to close this issue?
