### ISSUE TITLE
Saving Meetings with reminders

### ISSUE THREAD

**Issue by gregsoper** [salesagility/SuiteCRM#734]
It is no longer possible to save either a new or an edited meeting when a reminder is set - either save or save and send email

**Comment by gregsoper** [comment]
This is fixed by setting reminder defaults in user settings .. but would not be an issue if a reminder was defaulted on creation if no user settings had been created.

**Comment by willrennie** [comment]
This has been fixed, tested and confirmed to work in the latest versions of 7.6 and 7.7. Please comment if there are any further issues.
