### ISSUE TITLE
Meeting reminer alerts

### ISSUE THREAD

**Issue by gregsoper** [salesagility/SuiteCRM#735]
When creating a reminder, neither email nor popup is defaulted. This creates an red alert in the dialogue box. Either reminder or email should be default.

When creating a second reminder, if neither the email or the popup alert is selected, the red alert is displayed in all meeting reminder dialogue boxes. It should only display in the dialogue box that the error occurs in. See attached.
![reminders](https://cloud.githubusercontent.com/assets/10279184/11497131/d158ae9e-980e-11e5-9fcf-67f683a2727c.png)

**Comment by mattlorimer** [comment]
check your user settings for default reminders

**Comment by gregsoper** [comment]
OK .. that sorted it .. but this will create issues as it is 
non-intuitive - at least one reminder ought to be defaulted?

greg

On 12/01/2015 09:44 AM, Matt Lorimer wrote:
>
> check your user settings for default reminders
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/salesagility/SuiteCRM/issues/735#issuecomment-160913106>.
>

-- 

Greg Soper
Managing Director
SalesAgility - SuiteCRM and SugarCRM Consultants and Developers
E-Mail: greg.soper@salesagility.com
Web: http://www.salesagility.com
Offices:
London: 53 Chandos Place, Covent Garden, London WC2N 4HS || Phone: +44 
(0)203 5151 499
Manchester: 4th Floor, 59 Piccadilly, Manchester M1 2AQ || Phone: +44 
(0)161 9876 499
Stirling: The Steeple, Stirling FK8 1DT || Phone: +44 (0)1786 585 499
Registered in Scotland: Company No: 364788
This email, including any attachments, is confidential. If you are not 
the intended addressee, please notify the sender immediately by email 
and delete this email completely from your system, you must not 
disseminate, copy, distribute or disclose the contents of this email. 
Emails could be intercepted, corrupted, lost, delayed or contain 
malicious components. Therefore the sender does not accept any liability 
or responsibility for any loss or damage incurred whatsoever. Personal 
opinions and views expressed in this email may not necessarily reflect 
the official opinions and views of the Company.



.

**Comment by willrennie** [comment]
Fix confirmed in SuiteCRM 7.5.
