### ISSUE TITLE
Space Between Bulleted List Added After Upgrade

### ISSUE THREAD

**Issue by zbennett2019** [salesagility/SuiteCRM#7354]
Our PDF Template contains **$aos_products_standard_config_c**  and before there were not spaces between each element in the list. After upgrading to the latest SuiteCRM version, each time we create a quote via PDF we're getting spaces between each line in the list which is taking up too much room. 

#### Expected Behavior
There should not be a space between each element in the list.

#### Actual Behavior
There is a space added between each element/line in the list.

#### Steps to Reproduce
1.Create a PDF template with the following code

<tr>
<td style="width: 10%;"> </td>
<td style="width: 75%;">$aos_products_standard_config_c</td>
<td style="width: 1%;"> </td>
<td style="width: 1%;"> </td>
<td style="width: 3%;"> </td>
<td style="width: 10%;"> </td>

2.  Go to "Quotes" and "Print As PDF"

#### Context
This is affecting our sales potentially by preventing us from achieving the design we want on quotes for customers

#### Your Environment

Version 7.11.4
Sugar Version 6.5.25 (Build 344)
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
MySQL , PHP 7
Linux

**Comment by pgorod** [comment]
What is `$aos_products_standard_config_c`? Is it a custom field you created? What does it contain, and what field type is it?

**Comment by zbennett2019** [comment]
No it is a field in the CRM under Products -> Standard Configuration. It contains the standard options that come on the machines we sell. 

I put a screenshot here: https://imgur.com/a/A8ZhQzp

**Comment by zbennett2019** [comment]
Also, this is the source code for the field.

**Comment by zbennett2019** [comment]
Also this is the source code for the field:

<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>Standard configuration:</p>
<ul>
<li>X,Y,Z axis C3 ballscrews</li>
<li>Network and USB</li>
<li>Y axis slideway covers</li>
<li>X,Y axis ballscrew covers</li>
<li>Rotary Table</li>
<li>Coolant system</li>
<li>Centralized automatic lubrication system</li>
<li>Electric box heat exchanger</li>
<li>Portable MPG Handwheel</li>
<li>Halogen work light</li>
<li>Alarm light</li>
</ul>
</body>
</html>

**Comment by pgorod** [comment]
@zbennett2019 actually that field doesn't show in my test system, and it doesn't show in the online demo, I really think you are talking about some customization that was made in your company. The suffix `_c` also indicates that, that is how custom fields are named.

If that is the case I think you will have to try solving this within your company also...

**Comment by cameronblaikie** [comment]
Hi there,

We believe that this is a custom field as we can see there is "_c" at the end which happens when you create your own custom field. It would be a good idea to speak to whoever created this custom field to try to resolve it with them, if not you can raise this issue on our forms which I will link below for you. I am now going to close this issue but feel free to open this again if it becomes a core issue.

Forms link - https://suitecrm.com/suitecrm/forum/index

thanks,
