### ISSUE TITLE
Home module index page loading bad MySugar file location

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#7357]
#### Issue

In `modules/Home/index.php` at the bottom there is an error with one of the file paths loading `MySugar.tpl`. The last else statement attempts to load `custom/themes/[theTheme]include/MySugar/tpls/MySugar.tpl`. It's missing a '/' right before include. 

It should look like `custom/themes/[theTheme]/include/MySugar/tpls/MySugar.tpl`

Also, I don't see how this specific file would ever be hit. The preceding file it tries to load is `include/MySugar/tpls/MySugar.tpl` which is included by default in SuiteCRM. Is this intended?

#### Expected Behavior

Needs to load correct file

#### Actual Behavior

Tries to load file that doesn't exist

#### Possible Fix

Add a '/' to the beggining of the string that starts at 'include'

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
Nice catch, it seems to come from this 2016 commit:
https://github.com/salesagility/SuiteCRM/commit/05ca8a035e0e298e6cc399eeb82685104384e4e6#diff-4f57712e4559feea5a2c13bf6597f2a3
