### ISSUE TITLE
Open Backlog - Sprint 12 Planning [7.8.x EOL]

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#7358]
Hey Community!

A big thanks for participating in the 7.8.x EOL (End of Life) discussion (#7294 & [forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/24652-suitecrm-7-8-x-reaching-its-end-of-life)) and sharing your thoughts and challenges you face in taking that step from 7.8.x and adopting one of the later versions.

We reviewed the points you all made and broke them down into actionable tasks – though some are too far reaching and will have to be recorded as suggestions for the future. But thankfully much of a feedback we feel can be allocated either within the core team or by community members if able.

In order to help achieve some of the points raised we are designating Dillon & Cameron from the core team for the duration remaining until 7.8.x End of Life has been reached – a couple of sprints from now till end of June.

We also want to introduce a concept we have been mulling about for a while which is to introduce a more direct way to highlight issues into upcoming sprints by setting up pre-sprint backlog.

If you are aware of how Agile works then this is VERY loosely based on this methodology. So simply, prior to an upcoming period of a development cycle, we’ll open up a time limited issue labelled as ‘discussion’ that will ask the community to reference certain existing Github issues that they would like to nominate to be included in the two week sprint (if possible).
As we don’t want to overload a single sprint with issues we will review the proposed issues based on the severity of the bug (high/medium/low); focus and how complex the issues are.

The goal we want to achieve here is to have an easier and clearer way to identify publicly the communities’ priorities and how do these issues affect users’ day to day lives.
We hope that combined with our own backlog internally we can collaborate together and schedule issues that would satisfy and have a high impact to the SuiteCRM community needs.

Though we do need to set the expectations that time is limited to 2 week sprints so if an issue isn’t completed in that sprint it can be re-nominated for the next sprint.

We also encourage ownership of these bugs and their bug fixes (like above). We’ll identify what issues can we tackle and others we suggest community members can address in order to get them into that release.

We are adding new milestone EOL to include issues that we can confirm need to be addressed before the 7.8.x end of life 

We are also added new labels “Help Wanted” and “Good First Issue” to help on boarding.

So the mains concepts that people raised that they would like to be seen addressed in 7.10.x+ in order to upgrade are mostly about; Emails; Theme and Misc (things that are singular).

Please see the latest post of the assessment and initial allocation of these issues (see comment below).
https://github.com/salesagility/SuiteCRM/issues/7358#issuecomment-502428584
If you wish to see the [history of this post](https://help.github.com/en/articles/tracking-changes-in-a-comment) then you can do so via the "Edited On" link next to my post's timestamp.

We’ve initially identified some that the core team can tackle and have already estimated the effort involved. Anything marked as just Community we offer this up for the Help Wanted label and the items that are Core/Community are those that can be picked up by either! P.S I couldn’t find all Github issues so just comment on which issue links up with an item above.

What we propose then is that in the comments identify bugs, by linking them, that fall under the above themes that you would like to nominate for the upcoming sprint. Feel free to add your suggestions why and even severity of how it impacts your work.

I look forward to seeing how this process will be refined :+1:

**Comment by samus-aran** [comment]
In no special order, and definitely not a complete list, these are some people who have made past contributions or participated in the Pull Request Party. We'd love to hear from you on the discussion linked above.

@horus68
@ApatheticCosmos
@mikebeck
@amariussi
@likhobory
@urdhvatech 
@Mausino 
@jakubpas
@JanSiero 
@lazka
@jsamelko 
@adriangibanelbtactic 
@ChangezKhan 
@Abuelodelanada 
@hieuhoanghd 
@LionelBino
@vladbar 
@sanchezfauste 
@adamjakab 
@isleshocky77 
@anhnhatuit 
@ghermans 
@eggsurplus 
@javitoron 
@sathishsengodan 
@jobst 
@bluquet 
@connorshea 
@gitbnw 
@604media 
@kelly-walker
@hubyhuby

**Comment by hubyhuby** [comment]
Emails Test Coverage issue is here:  https://github.com/salesagility/SuiteCRM/issues/7299

Thanks this sprint looks really great ! Focusing on important stuffs.

**Comment by mcarpenterjr** [comment]
Really excited for the suite team on this, glad to see this level of dedication! I'm guessing if an item doesn't have an issue associated with it we should create one?

**Comment by samus-aran** [comment]
@mcarpenterjr Yeah that would be much appreciated. Not all will have a single issue, (for example the email bugs) but if we can try and bring these together then we can physically assign them out and obviously when PRs are created they reference something tangible.

So like, if you feel like ref issues that already exists then please do so and we will pre-assess if they are achieving in the sprint. e.g

> At our company, we found these issues a real hindrance for x, y, or z reasons
https://github.com/salesagility/SuiteCRM/issues/7156
https://github.com/salesagility/SuiteCRM/issues/6973

Like that...

**Comment by Abuelodelanada** [comment]
Hi @samus-aran,

This is a great initiative!

We have opened some issues and PR that, in our particularly case, will help us a lot in order to develop solutions over 7.10.x. In some of them, we worked a lot.

We wrote these solutions to satisfy our clients needs, and we would love to see these in 7.10.x. Anyway I am not sure these issues/PR can match with the main idea of this backlog.

#3007
#6602
#6672
#7235 

Some of them were abandoned, and now need more work.

**Comment by samus-aran** [comment]
Thanks Jose.

Anyone else, want to help out by identify issues?

I've had a quick look and listed some of the issues we see people want to include.. So others agree?
Would love to see people confirm that we are on the right track.

Emails:
#6866
#7298
#7186
#7298

**Comment by ebogaard** [comment]
We're having issues with auto imported e-mails gone missing + setting deleting 'delete from server':
#6534

Also filed an easy to implement usability improvement to the Calendar by auto-hiding pop-ups after x seconds:
#3756

**Comment by Mausino** [comment]
I give it here what i found...

#7071 (Reply to or Reply to All adding attachment from original email. This should do only Forward function)
#6992 (Group Email Inbox accounts doesn't respect reply as option in admin)
#6968 + it's similar duplicates #5520 + #5552 + #2174  + #6968 (if your template has attachment, isn't added into email if you create it from template by yourself or system itself)
#6470 ( Inline image not shown in received/sent email)
#4881 (Detail view of no imported email is different as imported + missing time unit + attachments)
#7249 (Admin user cannot edit another user's Mail Accounts)

+
this issue move the security management of SuiteCRM on new level..  but in't in sprint
#6657 (Security Groups - any fields for edit, detail or listview)

**Comment by pgorod** [comment]
I opened #7373 about the Theme padding/spacing

**Comment by connorshea** [comment]
Custom icons break when upgrading to 7.10: https://github.com/salesagility/SuiteCRM/issues/5440

I can open a new issue with more info if we want, since that one isn't very detailed. Essentially, when #5273 was merged, the old style of icons was removed in favor of SVG icons. Unfortunately, there was no mention of how to customize the icon font (mostly I'm interested in adding new icons), so I'm not sure what the upgrade path here is supposed to be.

I guess this is related to the better theme documentation?

And of course my pet project of improving the test suite :) #7344

**Comment by pgorod** [comment]
Hey everyone. @connorshea is asking for our feedback regarding test suite use. It's slightly off-topic here but I'd like to ask everyone to head over to that issue and take a minute to answer his survey. Thanks Connor and thanks everyone!

https://github.com/salesagility/SuiteCRM/issues/7344#issuecomment-501835767

**Comment by samus-aran** [comment]
Hello Everyone!

Thanks again for your feedback and referencing the Github issues to help us identify what you feel are your priorities and the issues that are affecting yours & the community's’ daily lives using SuiteCRM. 

If you haven’t seen already I had updated the first post with the Github issues that anyone who commented had identified (if I have missed any prior to this post then just holler). 

Ideally this would’ve been planned and executed prior to the sprint (we are slightly behind to get back with the below) but that is something we can pre-empt in the coming weeks. So, during our sprint planning we reviewed each one and assessed them based on the following criteria: whether the issue is actually a suggestion; whether the issue is code or documentation; whether the issue would be a breaking change; whether the issue could be tackled by either core or community members; & whether the issue could be tackled within a single sprint.
Based on these assessments we tried to identify our own measure of priority & complexity and that helped us understand what we should tackle first & what we could request help with by fellow developers & users in the community.

We then allocated each item into a sprint (12, 13) as a very simple baseline on what could be tackled first whilst trying to provide a reasonable distribution of tasks across the sprints for both  core team & community. So I do stress this is flexible, if anyone wants to tackle anything that has “Help Wanted” on the issue within a sprint please don’t feel you can’t just because it isn’t in the current sprint. :+1: Some items are spread across two sprints because either of it complexity &/or should always be continuous (like test coverage).

Please see the issues below and their allocations...

Concept | Actionable Task | Github Issue | Assigned | Complexity | Sprint | Comment
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- 
Emails | ~~Delete Emails~~ | #3727 | Core | 12 | Needs Review | 
Emails | See Attachments on Non Imported Emails | #5190 | Core | High | 12 |
Emails | Can’t filter on multiple Inboxs/Folders | #7279 | Core | High | 12, 13 | 
Emails | Test Coverage | #7299 | Core/Community | Medium | 12, 13 | 
Emails | Attachments Should not be Sending on Reply | #7071 | Community | Low | 12 | 
Emails | Group Email Accounts Not Respecting Reply to Admin restriction | #6992 | Core | Medium | 12 | 
Emails | Attachments Not being Sent (multiple areas) | #6968, #5520, #5552, #2174 | Core/Community | High | 12, 13 | 
Emails | Inline Images not shown in received/sent Emails | #6470 | Core/Community | Medium | 12, 13
Emails | Differences between Imported/Non Imported Email Views | #4881 | Core | Medium | 12, 13 | 
Emails | Admin can not edit User's Mail Accounts | #7249 | Community | Medium | 12 | 
Emails | Auto Importing Not Working | #6866, #6534 | Core | Medium | 12 | 
Emails | ~~Bulk Actions is disabled~~ | #7298 | Core | Low | 12 | Done
Emails | Incoming IMAP mail issues | #7186 | Community | Medium | 12, 13 | Needs help troubleshooting
Themes | Update documentation on customising Themes | #5440 | Core | Low | 12, 13 | 
Themes | Add in Max 3 columns Support | #3310 | Core/Community | Medium | 13 | 
Themes | Reduce Padding Edit/Detail/List | #7373 | Core/Community | Low | 13 | 
Themes | List View: Mirror Subpanels + on smaller screens |  | Core  | Medium | 13 | 
Misc | Confirm that issue was resolved regarding ElasticSearch issue on shared hosting |  | Core | Medium | 12 | 
Misc | Update documentation that Shared Hosting should be OK with ElasticSearch | | Core | Low | 12, 13 | 
Misc | Include a Composer section in Documentation | | Core/Community | Low | 12, 13 | 
Misc |  Create a Migration Guide to help others to upgrade | | Core/Community | Low | 12, 13 | Lets make a group discussion for this 
Misc | Create a new Mobile View editable by Studio | Suggestion | Community | - | - | No plans for this on the 7.x roadmap
Misc | Update documentation to state that GDPR is not mandatory option | | Core | Low | 12 | 
Misc | Support KReporter | Suggestion | Community | - | - | No plans for this on the 7.x roadmap
Misc | Develop PRs | #3007, #6602, #6672 | Community | - | - | 
Misc | Popup Studio and Calendar don't auto-close | #3157 | Core/Community | Low | 12, 13 | 
Misc | housekeep session files | #3157 | Core | Medium | 12, 13 | 
Misc | Security Suite enhancements | #6657 | Community | - | - | No plans for this on the 7.x roadmap
Misc | Test Suite Improvements | #7344 | Core/Community | Medium | 12, 13 | 

As I said, anything that has Core/Community is up for grabs by anyone, the core team will only tackle them IF we have time and no one in the community has picked them up. And same goes for those identified as Community… Though we also wanted to encourage ownership of these so we won’t touch them unless we feel they can’t progress without our intervening.

We have already begun to allocate the above issues out to their specific sprints with aim to show  what is currently being worked upon and those issues that need to be tested, reviewed and successfully merged in.

https://github.com/salesagility/SuiteCRM/projects/6
https://github.com/salesagility/SuiteCRM/projects/7

Just to re-iterate from my earlier posts, that the core team do have other tasks that may not be identified in the above sprints and these are usually from our own internal backlog i.e. improving the release process, CI/CD tools (Travis 😢 ), security patches etc so that accounts for our some ‘slack’ visible in the public sprints.

Now this is all well and good to start, but I guess the underlying part here we need is your help. We, the core team will strive to achieve, at a minimum, what as has been allocated to us, but we would love to see others in contributing to complete this EOL. Any sort of participation would be grand: developing a fix for the above issues, testing any Prs, providing your feedback, help troubleshoot, write up documentation! ANYTHING as long as we are working together to make a successful upgrade that those will feel confident to jump up to the latest versions of SuiteCRM.

Lets do this !😄

**Comment by samus-aran** [comment]
@Mausino Are you able to create an Issue specifically for the "List View: Mirror Subpanels + on smaller screens"? That would be much appreciated.

**Comment by Abuelodelanada** [comment]
Hi @samus-aran 

I forgot three issues that would be great to tackle in this or the following sprints:

#3438 ( Related to #6604 )
#5958

**Comment by samus-aran** [comment]
@Abuelodelanada Lets not add too much what is already added unless the Community are willing to jump on them.
I'm happy to have a note of this for the next sprint (13) but the whole point of this planning is not to overload and have a cut off so not to encourage scope creep. There will always be things that would be nice to add in, but we need to leave space for things that *have* to be shove in due to critical/security issues. :+1:

**Comment by Abuelodelanada** [comment]
I agree with you @samus-aran I just posted this issues in order to not forget about it.

**Comment by samus-aran** [comment]
Hey Everyone!

Just to remind the community if you are available to help test or develop some of these sprint tasks that are in the [TO DO & REVIEW](https://github.com/salesagility/SuiteCRM/projects/6) especially if anyone in our partners & development community able to jump on any of the "Help wanted" items.
We've had help from @604media who tackled a sprint task - so thanks for that :+1: 
@connorshea for help on the automated testing (and lots of other dev tools) :+1:
@ebogaard for partially helping out with Calendar Popups :+1: 

Just mention ourselves and we can assign a task to yourself :D 

https://github.com/salesagility/SuiteCRM/projects/6

**Comment by samus-aran** [comment]
Sprint has ended... See Review https://github.com/salesagility/SuiteCRM/issues/7499
