### ISSUE TITLE
Update php-saml to fix security issues

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#7368]
#### Issue
This is a bit curious situation: actually the files of two versions of the php-saml library are available within the SuiteCRM folders:
1. Version 2.11 in "modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/"
2. Version 3.x in "vendor/onelogin/php-saml/"

Only version 2.11 is actually used and this is an old version.
Since then, several security issues have been found and repaired. See the relevant project: https://github.com/onelogin/php-saml/releases

#### Expected Behavior
I expect that security fixes of external libraries are incorporated in SuiteCRM.

#### Actual Behavior

What I can see, is that in march of 2018, a commit was done to move the php-saml library to composer: https://github.com/salesagility/SuiteCRM/commit/abb424a6a426428dd75ff0212719c1804ef2cb97
This broke the saml login, as necessary further changes weren't implemented, so the old library was loaded again. See commit: https://github.com/salesagility/SuiteCRM/commit/ed170bdff68bd742fd78328c37836b2895106579
(Row 45 in modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php)

#### Possible Fix

To fix the security issues, I see two options:
1. upgrade to v2.15. This is the quickest, short time fix now, but makes upgrading in the future more time consuming.
2. upgrade to the newest v3.x using composer and integrate this library properly. Initially, this has a higher impact but saves time later on.

Extra benefit: this upgrade might fix issue #6524 as well

**Comment by lazka** [comment]
I've already opened a PR for this #6850

**Comment by ebogaard** [comment]
Closing as a duplicate of #6850
