### ISSUE TITLE
Make SuiteP more compact

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#7373]
## Issue
This is to address the spacing and padding that some users feel is excessive in SuiteP, when compared to SuiteR Theme which is about to be deprecated as [7.8.x reaches EOL](https://github.com/salesagility/SuiteCRM/issues/7358).

## Goals to balance
- We want more data to fit the screen, and we want the important parts of records to show immediately and be visible without scrolling
- BUT we also want to keep the theme usable in mobile, without a mouse, and handling screens with your fingers requires larger padding.

## Metrics to compare between themes

I propose that we compare SuiteP, side-by-side, with SuiteR, for common laptop and desktop viewport sizes, and try to get similar values on both themes for:

**Generic**:
• number of visible recents/favourites listed on the sidebar
• height of navigation top menu
• height of buttons
• height of items in list-boxes 
• height of items in drop-downs

**Home**: 
• number of visible dashlet items on home screen

**List view**: 
• number of visible lines before scrolling

**Detail view and Edit views**: 
• number of visible fields on view; and at what screen height does the first row of fields show (i.e. are we wasting space on the top?).

**Calendar**:
• number of visible time slots in the calendar

**Comment by connorshea** [comment]
Heh, this is funny because we've been upgrading from 7.9 to 7.10 and I feel like 7.10 SuiteP is _too_ compact. It squishes things down a lot.

**Comment by pgorod** [comment]
That makes sense because there was some attempt to address this request for a more compact theme, going from 7.9 to 7.10.

There is no one-size-fits-all and people have different tastes for spacing. Ideally we would make it configurable, like two modes (compact/wide). But I am not sure how big a task that would be...

**Comment by pgorod** [comment]
Whoever works on this, please have a look also at #5703.

Many of the things described there (including comments) are probably already fixed, but maybe something is missing still. It would be nice to be able to close that issue after working on this one.
