### ISSUE TITLE
7.11.5 Login page header has " XXXXXXXX..= XXXXXXX..."

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7383]
#### Issue

7.11.5 Login page header has " XXXXXXXX..= XXXXXXX..."
#### Steps to Reproduce

1. Open login page
2. Show missing info "    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" in page header

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cekowu** [comment]
The page code:
`From: <Saved by Blink>
Subject: CRMSYN
Date: Fri, 13 Jun 2019 01:23:06 -0000
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="----MultipartBoundary--QMTiJz5W6mJC6BWXcpg7ESMNdqxaPzyOyu9kNkjphf----"

------MultipartBoundary--QMTiJz5W6mJC6BWXcpg7ESMNdqxaPzyOyu9kNkjphf----
Content-Type: text/html
Content-ID: <frame-15-b62b9a63-d2b8-4dea-ba94-48bb1ef2a8d5@mhtml.blink>
Content-Transfer-Encoding: quoted-printable
Content-Location: http://nex.synnex-china.com/SuiteCRM-DEV/index.php?action=Login&module=Users

<!DOCTYPE html><html lang=3D"en_us" class=3D"yui3-js-enabled"><head><meta h=
ttp-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8">
    <link rel=3D"SHORTCUT ICON" href=3D"http://nex.synnex-china.com/SuiteCR=
M-DEV/themes/SuiteP/images/sugar_icon.ico?v=3D9W9bas3qY8iOvvOmDiL-6Q">
   =20
   =20
    <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge">
    <meta name=3D"viewport" content=3D"user-scalable=3Dno, initial-scale=3D=
1, maximum-scale=3D1, minimum-scale=3D1">
    
    <link href=3D"http://nex.synnex-china.com/SuiteCRM-DEV/themes/SuiteP/cs=
s/normalize.css" rel=3D"stylesheet" type=3D"text/css">
    <link href=3D"http://nex.synnex-china.com/SuiteCRM-DEV/themes/SuiteP/cs=
s/fonts.css" rel=3D"stylesheet" type=3D"text/css">
    <link href=3D"http://nex.synnex-china.com/SuiteCRM-DEV/themes/SuiteP/cs=
s/grid.css" rel=3D"stylesheet" type=3D"text/css">
    <link href=3D"http://nex.synnex-china.com/SuiteCRM-DEV/themes/SuiteP/cs=
s/footable.core.css" rel=3D"stylesheet" type=3D"text/css">
    <title>CRMSYN</title>

    
    
    
       =20
   =20






   =20
   =20
   =20
   =20
            
            <link rel=3D"stylesheet" type=3D"text/css" href=3D"http://nex.s=
ynnex-china.com/SuiteCRM-DEV/include/javascript/qtip/jquery.qtip.min.css"><=
link rel=3D"stylesheet" type=3D"text/css" href=3D"http://nex.synnex-china.c=
om/SuiteCRM-DEV/index.php?action=3DLogin&amp;module=3DUsers"><link rel=3D"s=
tylesheet" type=3D"text/css" href=3D"http://nex.synnex-china.com/SuiteCRM-D=
EV/include/javascript/jquery/themes/base/jquery.ui.all.css"><link rel=3D"st=
ylesheet" type=3D"text/css" href=3D"http://nex.synnex-china.com/SuiteCRM-DE=
V/cache/themes/SuiteP/css/Dawn/style.css?v=3D9W9bas3qY8iOvvOmDiL-6Q">
    <link rel=3D"stylesheet" type=3D"text/css" href=3D"http://nex.synnex-ch=
ina.com/SuiteCRM-DEV/themes/SuiteP/css/colourSelector.php">
   =20
   =20
   =20
</head><body>


    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'&gt;








<div class=3D"p_login">

	<div class=3D"p_login_top">
	=09
		<a title=3D"SuiteCRM" href=3D"http://www.suitecrm.com/">SuiteCRM</a>
	=09
	</div>
   =20
    <div class=3D"p_login_middle">
       =20

    <div id=3D"loginform">
       =20
        <form class=3D"form-signin" role=3D"form" action=3D"http://nex.synn=
ex-china.com/SuiteCRM-DEV/index.php" method=3D"post" name=3D"DetailView" id=
=3D"form" autocomplete=3D"off">
            <div class=3D"companylogo"><img src=3D"http://nex.synnex-china.=
com/SuiteCRM-DEV/themes/default/images/company_logo.png?v=3D9W9bas3qY8iOvvO=
mDiL-6Q" alt=3D"SuiteCRM" style=3D"margin: 5px 0;"></div>`

**Comment by cameronblaikie** [comment]
Hi there, 
A possible fix for this:
1. To to Admin.
2. Go to rebuild.
3. Then Rebuild the following - 
· Quick Repair and Rebuild
· Rebuild .htaccess
· Rebuild Relationships
· Rebuild Minified JS Files 
·Repair JS Files

If this does not work for you then comment back and we will look further into this.

Thanks,

**Comment by cekowu** [comment]
I check it,  and it is always exists, but I found the issue happened when  through other appache httpd proxy, cross-domain issue.  I check the  code ,and don't find it, when will be added the "xxxx..=xxx.."?

**Comment by cekowu** [comment]
iframe tag is unclose , leads this issue

`<body onMouseOut="closeMenus();">
--
  |  
  |  
  | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'></iframe>`

**Comment by pgorod** [comment]
This is some customization you made to the code, or some proxy configuration you made.

Definitely not a SuiteCRM bug, and this Issue should be closed.

Please open a thread in the Forums and I can try helping you out there. Thank you.

https://suitecrm.com/suitecrm/forum

**Comment by samus-aran** [comment]
@cekowu Yeeeeah that looks custom. No where in the core is there a reference of that making that many Xs. 
Has the instance got any customisations? I would definitely suggest that you open up this as a forum thread due to the customisations as this doesn't look like a core issue.

Look at /themes/SuiteP/tpls/header.tpl as that is where 

`<iframe id='ajaxUI-history-iframe' src='index.php?entryPoint=getImage&imageName=blank.png' title='empty'
            style='display:none'></iframe>
<input id='ajaxUI-history-field' type='hidden'>`
Appears.

**Comment by cekowu** [comment]
@samus-aran No customization in code, we only configure proxy for CRM instance

**Comment by cekowu** [comment]
If remove these code, the issue will disappear,  so I think it is a SuiteCRM bug in code.

` <iframe id='ajaxUI-history-iframe' src='index.php?entryPoint=getImage&imageName=blank.png' title='empty' style='display:none'></iframe>`

**Comment by samus-aran** [comment]
Then I suggest you see why that URL gives back XXXXX. It's a blank.png so perhaps your proxy isn't happy with it.

**Comment by cekowu** [comment]
@samus-aran , it is very strange, I remove  blank.png, only with this iframe tag, the issue will appear except remove iframe tag,  I check crm code ,and don't find back "xxxxx" in code.
`<iframe id='ajaxUI-history-iframe' style='display:none'></iframe>`

**Comment by samus-aran** [comment]
What does your error log say on the browser? When you are on the page (Ctrl+Shift+J in Firefox, or F12 in Chrome, for example) see if there is anything related to that iframe.. e.g. unable to identify mime type

**Comment by cekowu** [comment]
I open by chrome and F12, the Iframe is incomplete, prefix is replaced by ""XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'>"
So we can see the missing header,  I think There is a hidden logic  iframe will be replaced in some cases.

"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'></iframe>"

**Comment by samus-aran** [comment]
@cekowu I'll be honest I am completely stumped by this. I can only think that the code has been corrupted when it was pulled down. I can only suggest that you confirm that the header.tpl & _head.tpl are 'complete'. 
My other suggest is perhaps ask on the forums if anyone else had this issue.
