### ISSUE TITLE
Update button clears DateTime parameter in Reports Module

### ISSUE THREAD

**Issue by Mac-Rae** [salesagility/SuiteCRM#7396]
#### Issue

When using any DateTime field (I used date created) as a parameter within a report any time you hit the update button the fields will be cleared and the change will not be reflected within the report output

#### Expected Behavior

The update button should change the query reflecting the change in the outputted data

#### Actual Behavior

The button upon being pressed clears the parameters shown.

#### Steps to Reproduce

1. Create or open a report with a DateTime field as a parameter
2. See that the date set within the edit view will display data
3. See that after changing the date selected within the DateTime field is removed when hitting update and that no data is displayed within the report output

#### Context

Low priority as you can work around this by entering edit view and updating field there

#### Your Environment

* SuiteCRM Version used: Visible in 7.8.30, 7.10.15, 7.11.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 74.0.3729.157 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Mariadb 10.2, PHP71
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 LTS

**Comment by pribeiro42** [comment]
This happens also in 7.10.17

**Comment by markbond1007** [comment]
@Mac-Rae I can confirm that the fixed above applied to 7.11.5 does fix this issue.
