### ISSUE TITLE
API-Version 8 does not support grant_type of refresh_token for refreshing access_tokens

### ISSUE THREAD

**Issue by solrevdev** [salesagility/SuiteCRM#7397]
#### Issue

I am unable to use the API once the `access_token` has expired and cannot use a `refresh_token` to extend API use. 

The documentation does not explain how to handle token expiry but does tease the use of refresh_tokens. 

> "refresh_token : an encrypted payload that can be used to refresh the access token when it expires." 

#### Expected Behavior

I think the documentation should explain how we are supposed to manage our accces_tokens when they expire. 

Perhaps it should show an example or provide a workaround option perhaps or creating a new access_token every API call?

#### Actual Behavior

I am testing out the API in both Postman and via a Google Apps Script and so far I can obtain an `access_token` and then fetch a list of accounts using that acces_token but I am a bit stuck on how to handle the access_token expiring. 

Reading the docs and doing a google It seems that I should be exchanging a `refresh_token` for another access_token. 

So I have stopped using the `client_credentials` grant_type which does not return one and instead am successfully using `password` but I now do not know what to do with this `refresh_token` 

I did try the following : 

```shell
curl --request POST \
  --url 'https://{removed}/Api/access_token?access_token={access_token_removed}' \
  --header 'Accept: */*' \
  --header 'Cache-Control: no-cache' \
  --header 'Connection: keep-alive' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --header 'Host: {host_removed}' \
  --header 'Postman-Token: {token_removed}' \
  --header 'User-Agent: PostmanRuntime/7.15.0' \
  --header 'accept-encoding: gzip, deflate' \
  --header 'cache-control: no-cache' \
  --header 'content-length: 896' \
  --data 'grant_type=refresh_token&refresh_token={token_removed}&client_id={removed}&client_secret={removed}'
```

However, this does not seem to be supported 

```text
{
    "error": "unsupported_grant_type",
    "message": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check the `grant_type` parameter"
}
```

#### Steps to Reproduce

See above but basically:

1. Get an access_token and a refresh_token
2. Try to use it after it expires
3. Try and exchange the refresh_token for a new access_token

#### Your Environment

* SuiteCRM Version used: Version 7.11.5
* Environment name and version (e.g. MySQL, PHP 7): Apache and MySQL (RDS)
* Operating System and version (e.g Ubuntu 16.04): ubuntu 16.04 bitnami build

**Comment by icircletech** [comment]
I am having the same issue. 

It looks like SuiteCRM uses a vendor package to handle OAuth2. 

I searched their package for issues with refresh tokens, and found this currently open case.

Could this be related to the issue? 

https://github.com/thephpleague/oauth2-client/issues/775

I haven't had much time to dig in and look at it, but If someone does that would be very helpful. I will see what I can find when I get a chance. Thank you in advance.

**Comment by icircletech** [comment]
For the Package "League/Oauth2-Server" I noticed in the Docs the following:

-It does NOT show a "refresh_token" property in the grant type "Client Credentials" authorization server response. (https://oauth2.thephpleague.com/authorization-server/client-credentials-grant/) 

-It DOES show a "refresh_token" property in the grant type "Password" authorization server response. (https://oauth2.thephpleague.com/authorization-server/resource-owner-password-credentials-grant/)

I think this is the reason that the refresh_token does not work using the  "Client Credentials" grant type.

**Comment by charlesdsmith** [comment]
How do I actually use the refresh token to refresh the access token? I'm lost here

**Comment by gsqvared** [comment]
> How do I actually use the refresh token to refresh the access token? I'm lost here

Sorry for reopening if closed. I believe the answer can be found here: 
https://github.com/salesagility/SuiteCRM/pull/8051

Testing now.
