### ISSUE TITLE
Email buttons stack in theme

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#74]
https://suitecrm.com/index.php?option=com_kunena&view=topic&catid=10&id=2009&Itemid=1136

Bug and possible fix suggested.

**Comment by willrennie** [comment]
Need to re-work the structure that creates the buttons. Appears to be buttons within a table which cannot be displayed in-line simply through a CSS workaround.

**Comment by shogunpol** [comment]
In the Current version of SuiteCRM problem doesnt exsist any more.

**Comment by willrennie** [comment]
Issue resolved in later releases.
