### ISSUE TITLE
Managing Delegates Removes main windows Scrolling

### ISSUE THREAD

**Issue by markbond1007** [salesagility/SuiteCRM#7409]
#### Issue

In the Events window if you Manage Acceptances (accepted/declined invited/not invited/etc.) After carrying out the action as the sub-panel reloads it removes all scrolling from the main window. I have tried removing AJAX from the Events module which has no effect.

#### Expected Behavior

Should reload either the page or the panel without affecting the main window scrolling.
#### Actual Behavior

The delegate is correctly updated as is the sub-panel, but the scroll capability of the main window is completely lost, giving the impression that the window has frozen.

#### Steps to Reproduce

1. Create an Event
2. Add delegates to the event
3. try to Set them as invited or attended
4. click create note/attachment or something at the bottom of your screen and see no scrolling.

#### Your Environment

* SuiteCRM Version used: 7.11.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrom
* Environment name and version (e.g. MySQL, PHP 7): PHP7.1 Mariadb
* Operating System and version (e.g Ubuntu 16.04): Debain Stretch

**Comment by pgorod** [comment]
I could also reproduce this on Firefox (latest).
