### ISSUE TITLE
Email status Issue (SENT/READ)

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#741]
When i relate emal from My sent Emails to some other module, i have instead "Sent" status in history subpanel  (which i'm expecting) the status "Read".

More in this video: http://screencast.com/t/SgkMgJUA1YX

Thanks

**Comment by willrennie** [comment]
The video shows the 'Read' status, as I would expect, in the subpanel through your video. I don't see that there is a bug here. I would recommend that you post your issue on the forums: https://suitecrm.com/forum/index so that we can investigate further.

**Comment by Mausino** [comment]
@willrennie  but i don't see there logic, if was email sent from CRM and in related module is showing like read... Hi can the next user know that was sent if has READ status ? Same read status will have email when you receive it from somebody....  but one was sent and one received... but both will have READ status... i don't see there logic. It is only my opinion :)

**Comment by Mausino** [comment]
@mattlorimer @gymad @samus-aran can you review my answer and open this issue report ?
