### ISSUE TITLE
Acceptance tests need to clean up after themselves

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7419]
#### Issue
This is part of #7344, but it's a big enough problem that I figured opening a separate issue was warranted.

Essentially, the acceptance test suite leaves behind a bunch of files locally that cause the test behavior to differ if you do multiple runs on the same CRM.

#### Expected Behavior
The acceptance tests wouldn't pollute the state of my CRM and I would be able to re-run the test suite without any differences in the test results.

#### Actual Behavior
The acceptance tests create modules and files locally that aren't cleaned up. Then, when we re-run them they exhibit different behavior. 

#### Possible Fix
Does Codeception have a before/after hook for tests? We could save the current file list in `before` and delete any files created since then in the `after` hook. Unfortunately I assume there are tests that implicitly rely on each other so this may not be a simple fix :/

#### Steps to Reproduce
1. Clone the repository
2. Set the test suite up.
3. Run the acceptance suite locally.
4. Run it again, note that the results differ (assuming the first run actually got far enough to create modules, etc.)

#### Context
I need to be able to run the test suite locally because debugging issues with the test failures in CI is miserable. I have no choice but to wait 20-30 minutes between every change to see if it was effective in fixing the issue.

#### Your Environment
* SuiteCRM Version used: 7.10.16
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 67
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave (10.14.5)

**Comment by samus-aran** [comment]
Something I think we could do as immediate quick wins - removing the randomised data and have just test data that is set throughout. We want things to be random in the future but this will require a step by step process to refactor existing tests.
The 'flaky' tests PR we have is a great 'lets look here first' to rewrite those acceptances tests then we can process more with making the others stateless.

**Comment by connorshea** [comment]
@samus-aran Could you clarify what you mean by 'test data that is set throughout'? I want to make sure we're on the same page :)

I'm with setting static data that gets created and then deleted per-test with factories.

But I'd probably recommend against having a 'seed dataset' that persists across every test. The biggest issue with that being that it makes the 'seed data' hard to modify, because the test logic starts relying on parts of the seed data that it shouldn't assume is immutable - e.g. the number of users that exist, the properties of a specific user with id 1, the leads assigned to a given user, etc. So when you go to add a new user, or change a lead that's used in another test, those changes can cause unrelated test failures and make the test data difficult to work with.

There was a similar problem with the GitLab test suite, where there was a git repo that was used for testing, and if that repo was modified in any way it would cause tests to fail.

**Comment by samus-aran** [comment]
Yeah when I meant throughout I only mean throughout the individual tests. Not just data injected at the beginning of the test suite but as you clearly defined that each test contains its isolated data (not randomised).  I do believe we are on the same page ;)

**Comment by connorshea** [comment]
Tests that I've confirmed **do not** output files (at least, files that aren't ignored by the git repo):

- [x] tests/acceptance/modules/AM_Project_Templates/AM_Project_TemplatesCest.php
- [x] tests/acceptance/modules/AOK_KnowledgeBase/AOK_KnowledgeBaseCest.php
- [x] tests/acceptance/modules/AOK_Knowledge_Base_Categories/AOK_Knowledge_Base_CategoriesCest.php
- [x] tests/acceptance/modules/AOR_Reports/AOR_ReportsCest.php
- [x] tests/acceptance/modules/AOS_PDF_Templates/AOS_PDF_TemplatesCest.php
- [x] tests/acceptance/modules/AOS_Product_Categories/AOS_Product_CategoriesCest.php
- [x] tests/acceptance/modules/AOS_Products/AOS_ProductsCest.php
- [x] tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
- [x] tests/acceptance/modules/Accounts/AccountsCest.php
- [x] tests/acceptance/modules/Activities/ActivitiesCest.php
- [x] tests/acceptance/modules/Calendar/CalendarCest.php
- [x] tests/acceptance/modules/Calls/CallsCest.php
- [ ] tests/acceptance/modules/Campaigns/CampaignsCest.php - I had an error with the CampaignsCest when running it locally, could be old data causing the test to fail?

```
1) CampaignsCest: Create non-email campaign
 Test  tests/acceptance/modules/Campaigns/CampaignsCest.php:testScenarioCreateNonEmailCampaign
                                                                                                                                                                                                                               
  [Facebook\WebDriver\Exception\TimeOutException] Waited for 10 secs but text 'You have no associated targets in your selected target list(s) for this campaign. You can populate your list after finishing.' still not found  
```

- [x] tests/acceptance/modules/Cases/CasesCest.php
- [x] tests/acceptance/modules/Contacts/ContactsCest.php
- [x] tests/acceptance/modules/Contracts/ContractsCest.php
- [x] tests/acceptance/modules/Documents/DocumentsCest.php
- [x] tests/acceptance/modules/EmailMan/EmailManCest.php
- [x] tests/acceptance/modules/EmailTemplates/EmailTemplatesCest.php
- [x] tests/acceptance/modules/Emails/EmailsCest.php
- [x] tests/acceptance/modules/FP_Event_Locations/FP_Event_LocationsCest.php
- [x] tests/acceptance/modules/FP_Events/FP_EventsCest.php
- [x] tests/acceptance/modules/History/HistoryCest.php
- [x] tests/acceptance/modules/Home/HomeCest.php
- [x] tests/acceptance/modules/Invoices/InvoicesCest.php
- [x] tests/acceptance/modules/Leads/LeadsCest.php
- [x] tests/acceptance/modules/Meetings/MeetingsCest.php
- [x] tests/acceptance/modules/Notes/NotesCest.php
- [x] tests/acceptance/modules/Opportunities/OpportunitiesCest.php
- [x] tests/acceptance/modules/Projects/ProjectsCest.php
- [x] tests/acceptance/modules/Quotes/QuotesCest.php
- [x] tests/acceptance/modules/Spots/SpotsCest.php
- [x] tests/acceptance/modules/Surveys/SurveysCest.php
- [x] tests/acceptance/modules/TargetLists/TargetListsCest.php
- [x] tests/acceptance/modules/Targets/TargetsCest.php
- [x] tests/acceptance/modules/Tasks/TasksCest.php
- [x] tests/acceptance/modules/Users/UsersCest.php
- [x] tests/acceptance/modules/jjwg_Address_Cache/jjwg_Address_CacheCest.php
- [x] tests/acceptance/modules/jjwg_Areas/jjwg_AreasCest.php
- [x] tests/acceptance/modules/jjwg_Maps/jjwg_MapsCest.php
- [x] tests/acceptance/modules/jjwg_Markers/jjwg_MarkersCest.php

So actually I think the `modules/*` tests are all perfectly fine, it's just the `Core/*` tests that leave files behind.

**Comment by connorshea** [comment]
- BasicModuleCest fails when I try to run it, but I think that might be because I've already tried running it before and forgot about it. So I assume this is a case of a module being impossible to re-run.
- FileModuleCest creates a ton of stuff in the `modules/Test_FileTestModule/` directory, and does not dispose of it. It also can't be run more than once, especially if you delete the files it created.
- CompanyModuleCest fails, I don't know if I've run it before?
- IssueModuleCest creates a bunch of files in `modules/Test_IssueTestModule/` and fails on a re-run.
- PersonModuleCest: same as previous, `modules/Test_PersonTestModule/`
- SaleModuleCest: same as previous, `modules/Test_SaleTestModule/`
- ModuleBuilderFieldsCest: same as previous, `modules/Test_TestModuleFields/` and also sets the `OAUTH2_ENCRYPTION_KEY` in `Api/Core/Config/ApiConfig.php`.

**Comment by connorshea** [comment]
It seems like vfsStream should allow us to handle the file creation problems: https://github.com/bovigo/vfsStream

Is there a reason we don't use it for this yet? What do we use it for right now?

**Comment by connorshea** [comment]
There are files in `custom/modulebuilder/builds/` and `custom/modulebuilder/packages/` that need to be removed after the tests in `tests/acceptance/Core/*` are run.

`custom/application/Ext/Include/modules.ext.php` also needs to be cleaned up to remove references to the old `modules/` files, I'm not sure if deleting the file entirely is safe.

And then the files mentioned in my previous comment.

Cache files may also need to be cleaned out.

**Comment by connorshea** [comment]
I've got this working locally, I've added hooks at the start and end of the acceptance tests that'll delete the module files automatically. 🎉

**Comment by pgorod** [comment]
As a rule of thumb, anything under a directory named `/Ext/` can be deleted, and will be recreated by the next QR & R. This is the stuff that is aggregated from several files in all the variations of the Extension Framework mechanism.

If anyone knows of an exception to this rule, please let me know.

**Comment by connorshea** [comment]
This is now resolved 👍
