### ISSUE TITLE
Reports Dashlet Has a thin black border around the records

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#742]
Posted by Amariussi: https://suitecrm.com/forum/suite-themes/7262-reports-dashlet-css-bug#26137

![2015-12-01_162105](https://cloud.githubusercontent.com/assets/13675281/11530116/c49a0870-98e9-11e5-8677-24119ba8dd62.jpg)

Reports Dashlet appears to have a thin black border around the Records.

**Comment by CaptainChainsaw** [comment]
This has already been fixed:
https://github.com/salesagility/SuiteCRM/pull/861
