### ISSUE TITLE
Accept status is not showing on the meetings subpanels. Version 7.4.3

### ISSUE THREAD

**Issue by recci** [salesagility/SuiteCRM#743]
Meetings subpanels for Contacts, Users, Leads does not show the accept status. Status is updated in the database just does not display.  I have first noticed this in 7.4.3 but most likely affects earlier version also.

**Comment by ghermans** [comment]
+1

**Comment by recci** [comment]
Anybody have any idea when this last worked?

**Comment by recci** [comment]
Was working in 7.1.2 but not 7.2.2
