### ISSUE TITLE
Issue - Database failure caused by multiple browser tabs

### ISSUE THREAD

**Issue by TelevicDominiek** [salesagility/SuiteCRM#7446]
One of our users had, on a daily basis, issues with corrupted data. More specifically: when he opened a lead, he got a pop-up that looks as follows:

![image](https://user-images.githubusercontent.com/47784717/59904638-5a766780-9404-11e9-862e-cd3018aa0d95.png)

We found rather quick a solution to get rid of this issue --> the user had to empty all history, cookies etc. in his browser. But after a couple of hours, the issue came back.

At least, we found the root cause: this user was used to work with "a lot of open browser tabs". He goes to SuiteCRM in the morning and opens all the tasks, opportunities, ... he wants to work on during that day. At the end of the day, all his browser tabs should be closed.

So I guess there is some kind of conflict (AJAX?) occurring when the user opens SuiteCRM in multiple tabs (maybe the server doesn't know to which browser session it should send its answers).

![image](https://user-images.githubusercontent.com/47784717/59904814-ca84ed80-9404-11e9-8d6a-4a64d8f0e4d1.png)
Running on an Azure Server

**Comment by Dillon-Brown** [comment]
Hi @TelevicDominiek, are you able to see anything in the suitecrm.log that might be related to this issue? I can't seem to replicate (Although not too surprising as this looks pretty specific).

**Comment by TelevicDominiek** [comment]
Hi, I think you might close this ticket as duplicate of #7483 and #7267. Same error message in the log as mentioned in that earlier ticket. Thanks guys!
