### ISSUE TITLE
Send Emails From User Account

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7454]
Hi,

I have set up Outbound Email accounts for each user, based on user email address. 

However, users cannot send emails from their email addresses, they get this error "Error Sending Email. Please contact your administrator for assistance."

As an administrator, I do not know what to do because on the Outbound email settings or an User Account, I do not see an option to link a user with Outbound Email settings.

**Comment by dursuntosun** [comment]
Same issue as #7407
