### ISSUE TITLE
Returning list of modules with Api calls not working

### ISSUE THREAD

**Issue by JuiceSantos** [salesagility/SuiteCRM#7468]
#### Issue

According to the [release notes](https://docs.suitecrm.com/admin/releases/7.11.x/) a bug has been fixed (#7174) such that Api/V8 is now able to return a list of modules. So I upgraded to 7.11.5, but I was unable to get a list.

#### Expected Behavior

`Get {some domain}/Api/V8/meta/modules` should return a list of modules.

#### Actual Behavior

`Get {some domain}/Api/V8/meta/modules` returns `NULL`.

#### Possible Fix

There seems to be a difference between the [7.11.5 source code](https://github.com/salesagility/SuiteCRM/archive) and its release on https://suitecrm.com/download, for example the Api/V8/Controller/MetaController.php is missing from the release. After updating the files as shown in the commits from #7277, the access log shows `"GET /Api/V8/meta/modules HTTP/1.1" 500 1851 "-" "-"` whereas the error log had no corresponding logs. I will inspect this more once ~~I have hosted suite crm locally~~ I'm back home.

#### Steps to Reproduce

1. Host the latest suite crm (locally) from https://suitecrm.com/download/ and configure it
2. Get a valid access token.
3. Make the following Api request: `Get {your domain}/Api/V8/meta/modules`  with said access token

#### Context
Once someone downloads our trial, we want to add him automatically in suite crm. 

#### Your Environment

* SuiteCRM Version used: 7.11.5
* Browser name and version: Opera Version 60.0.3255.170
* Environment name and version: 10.0.36-MariaDB, PHP 7.2
* Operating System and version: Debian 8

**Comment by lazka** [comment]
Same 500 error with 7.10.x
