### ISSUE TITLE
SuiteCRM Autopopulate Fields Extension New Updates

### ISSUE THREAD

**Issue by varianceinfotech** [salesagility/SuiteCRM#7489]
Suitecrm extension release updates
#VIPL Team updates new feature in #SuiteCRM Autopopulate Fields Extension With new updates, We can able to autopopulate all kinds of SuiteCRM fields like Related Field, Dropdown, Checkbox, Radio, etc . For More Information: https://bit.ly/2V39i3y

**Comment by samus-aran** [comment]
Whao, not cool.
This is not an extension platform or a social media channel. Go make your announcements elsewhere.
