### ISSUE TITLE
Installation failed to the last step

### ISSUE THREAD

**Issue by copyyour** [salesagility/SuiteCRM#7490]
hello
Every time I install to the last step, I stop when I start creating databases and tables. I queried the database and created the library I named, but I didn't create any one. I changed a lot of environments and didn't know where the problem was. There are no records for suitecrm.log at the same time.
I hope to get help, thank you very much

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 75.0.3770.100 (64-bit)):
* Environment name and version (e.g. MySQL 5.7  , PHP 7.2 ):
* Operating System and version (e.g Ubuntu 18):

**Comment by Dillon-Brown** [comment]
Hi @copyyour 

This question may be more suited to the [Community Forums](https://www.suitecrm.com/forum/suite-forum). We use GitHub primarily for the reporting of Core SuiteCRM bugs and leave general questions and setup specific issues to the forums.

Thanks.
