### ISSUE TITLE
7.11.5 Role Can't select user and security

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7507]
#### Issue

 Role Can't select user and security
#### Steps to Reproduce

1. Create role
2. select users
3. can't select user

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Hi there,
we have replicated this and can confirm that it is an issue. The work around for this is to go to users and then assign the user to the Role. Another work around is to upgrade to the newest 7.11.x (7.11.6) which this issue is fixed.

thanks,

**Comment by cameronblaikie** [comment]
Hi there,
This issue is fixed in the 7.11.6 if you can upgrade that will resolve your issue.

Thanks,

**Comment by cekowu** [comment]
@cameronblaikie I upgrade to 7.11.6, it is ok now. Thanks.
