### ISSUE TITLE
Find and Replace Extension from SuiteCRM

### ISSUE THREAD

**Issue by varianceinfotech** [salesagility/SuiteCRM#7508]
#SuiteCRM #extension #plugin #addon #Find #Replace

Ever needed to change a term or name across one or more records? It is a painful process that requires going into each record, editing, finding each field that may have that value, replacing, saving, going to the next record, etc.
With Find and Replace it can be done in seconds all from the list view. Select which records to edit then run the Find and Replace tool.

Benefits :

1. Find and Replace extension helps users to find specific word or value of particular field and replace it module wise.
2. Find and Replace extension also helps users to find and replace to multiple records in list module listing screen.

Explore more at https://lnkd.in/fyqsxiz 

Watch demo at https://lnkd.in/f9GQskB

You can buy from SuiteCRM Store: https://bit.ly/2x1GUB3

See you in my next post with an another amazing SuiteCRM extension !!

**Comment by samus-aran** [comment]
Ok. Last warning @varianceinfotech If you are caught advertising on this platform again we will ban you from this repo. That doesn't bode as someone trying to be a respectable third party provider who can't be respectful of the community/repo.
