### ISSUE TITLE
After upgrade to 7.11.6 system info (about) states version 7.11.7 would be installed

### ISSUE THREAD

**Issue by bjoern86** [salesagility/SuiteCRM#7521]
After upgrade to 7.11.6 system info (about) states version 7.11.7 would be installed

**Comment by samus-aran** [comment]
This has been resolved - this was due to the packages being incorrect. Please see the forums for steps to resolve this 
https://suitecrm.com/suitecrm/forum/announcements/26612-suitecrm-7-11-6-7-10-18-7-8-31-maintenance-patch-now-available?start=%1$d
Thanks!
