### ISSUE TITLE
List View: Collapasible columns on smaller screens

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#7522]
#### Issue

As raised in Sprint Discussion (forums) and a reason for not upgrading to 7.10.x (#7358. This is a enhancement to the ListView to allow users using the mobile view not to lose visibility on list view data due to smaller screens.

As a User I wish to see all my selected columns via the ListView within Smaller screens by means of the same mechanism in subpanels view in smaller screens.

There will be the ability to hide/show columns that have been collapsed due the screen resolution. The smaller the screen width the reduced number of 'visible' columns as seen with the other columns overflow into the collapsible table.

This must be operation on all supported browsers and sub themes (Dusk etc). This also not cause any regression issues on the desktop width resolution.

Current Solution:

![Screenshot_2019-07-05 Accounts » SuiteCRM Demo](https://user-images.githubusercontent.com/4041275/60712864-d5b14080-9f0f-11e9-8e81-a5f3e4963d45.png)
The user can not see additional columns

Proposed Solution:

![Screenshot_2019-07-05 B H Edwards Inc » Accounts » SuiteCRM Demo](https://user-images.githubusercontent.com/4041275/60712893-e366c600-9f0f-11e9-9dbc-ccdeecb3198d.png)
![Screenshot_2019-07-05 B H Edwards Inc » Accounts » SuiteCRM Demo(1)](https://user-images.githubusercontent.com/4041275/60712906-e8c41080-9f0f-11e9-9e81-afc1f101f037.png)

#### Possible Fix

Replicate the same functionality in subpanels list view in global list view.

**Comment by samus-aran** [comment]
Hey @Mausino I couldn't find an issue you created, is this description clear and satisfy your original suggestion?

**Comment by Mausino** [comment]
@samus-aran yes you did 😉
