### ISSUE TITLE
Add support for Database Migrations

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7534]
#### Issue

Essentially, because we didn't have a better solution to the problem, we've modified `QuickRepairAndRebuild.php` to run this query every time a repair is run. This is fine-ish on its own, but if we want to do further cleanup of the database table customizations we've made, a lot of problems can be introduced. Namely, this runs every time a repair is run. If we have a dozen or two dozen of these, repairs start taking longer.

```php
// Remove columns from cstm tables for the fields that were created in fields_meta_data
public function removeBadFieldMetaDataRecords()
{
    global $db;
    $removeFieldQuery = "DELETE FROM fields_meta_data WHERE id IN('Accountscust_type_c', 'Accountsmfg_indctr_c', 'Accountspop_code_c')";
    $db->query($removeFieldQuery);
    $removalArray = array('cust_type_c', 'mfg_indctr_c', 'pop_code_c');
    foreach ($removalArray as $column) {
        $showColumnsQuery = "SHOW COLUMNS FROM accounts_cstm LIKE '$column'";
        $showColumnsResult = $db->query($showColumnsQuery);
        $exists = $db->fetchRow($showColumnsResult);
        if ($exists) {
            $columnRemoveQuery = "ALTER TABLE accounts_cstm DROP COLUMN $column";
            $db->query($columnRemoveQuery);
        }
    }
}
```

What I'd like to see is a migrations system similar to the ones provided by [Rails ActiveRecord](https://guides.rubyonrails.org/active_record_migrations.html), [Laravel](https://laravel.com/docs/5.8/migrations), or [Doctrine](https://www.doctrine-project.org/projects/doctrine-migrations/en/2.1/reference/migration-classes.html#migration-classes).

Essentially, all three create 'migration' files which run SQL scripts. They're used to keep database migrations defined explicitly via code, and only ever need to be run once for a given application. They use timestamps (e.g. `20180601193057`) and a `migration_version` table to determine what migrations need to be run (e.g. we have a migration titled 20190709xxxx, which means it was created today, and if it's not listed in the `migration_version` table, we need to run it. If it is in the table, we don't need to run it again.).

They provide the ability to define both `up` and `down` behaviors, to allow reverting a given migration.

Right now, vardefs handle everything for the user when repairing. However, to my knowledge the vardefs system has a few downsides in terms of things it can do for the user automatically:

- There's no way to delete a column.
- There's no way to delete a table.
- There's no way to rename a table.
- There's no way to rename a column.
- There's no way to move a column from one table to another.

All of these things would need to be done manually either via raw SQL or via Studio, and when you have multiple sites (dev, test, staging, production) where these need to be run manually (or hacked in), it becomes very difficult to change the database schema.

### Problems

There are a number of problems I see with introducing this system.

- The system will need to be made to be compatible with the existing vardefs system.
- It needs to be compatible with the existing SuiteCRM upgrades system.
- It requires quite a bit of engineering work to make this happen. Adding Doctrine (or some other package like it) may be an easier means of adding this system, but since we already have a DB system, adding Doctrine probably wouldn't be pretty.
- Probably a variety of other problems I'm not thinking of.

**Comment by gunnicom** [comment]
I do not think this is a good idea. There are rarely any benefits for most of the people, but adding that addtional complexity has too many risks.

**Comment by connorshea** [comment]
The problem is some specific cases where the existing vardefs system isn't able to handle the kind of database migrations we want to do, e.g. delete a column, move columns between tables, rename columns, and rename/delete tables.

**Comment by gunnicom** [comment]
Deleting columns should be manual in my opinion. Some people like to not delete data before shure it can be deleted. 
And i repeat my self. What you want to have can be extremely complex operations. Not worth it in my opinion.
