### ISSUE TITLE
Issue: 500 error when creating a project task for a project with no end date

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#754]
Call to a member function format() on boolean in /modules/ProjectTask/updateProject.php on line 22
Workaround was to require the start date and end date in the project

**Comment by vjaro** [comment]
Sorry the fields in concern were modified in studio to be not required. Closing this ticket.

**Comment by ventoh** [comment]
I had the same problem and thought it was a bug. Anyway, i think the code in custom/modules/ProjectTask/updateProject.php must fixed with a check on empty var to prevent this issue.
if(!empty($project->estimated_end_date))  at line 22
I made myself in my code, but i think will be useful as default
