### ISSUE TITLE
use correct login image on install.php 

### ISSUE THREAD

**Issue by mcarpenterjr** [salesagility/SuiteCRM#7547]
Install.php references the image sugrcrm_login.png which does not exist. The correct image should be suitecrm_login.php.

This was fixed in #249 but seems to have regressed.

**Comment by cameronblaikie** [comment]
Closing as this is a duplicate of this issue ()

**Comment by mcarpenterjr** [comment]
Someone should take a look at this, at some point, and decide if this should also be refactored to include just one suite logo or two.
