### ISSUE TITLE
AOR Reports - Mysqli_query failed when execute Report as normal User

### ISSUE THREAD

**Issue by fgiehlede** [salesagility/SuiteCRM#7552]
#### Issue

The Report will return no records if either the report fields links to record from a related module like accounts to contacts. The report show no entries when a normal user execute the report. As a sysadmin user i can read and execute the report and the report will show the entries

![report](https://user-images.githubusercontent.com/30693152/61036110-b52e2e00-a3c8-11e9-82be-ed8d9888a8dd.png)

#### Expected Behavior
The report should return the same behavior like when i execute the report as a sysadmin user.

#### Actual Behavior
The report show no entries when a normal user execute the report. As a sysadmin user i can read and execute the report and the report will show the entries. When i remove the field of the related module contacts (Firmen:Kontakte:Nachname (lastname of the contact), the report doesnt crash and return its value.

SuiteCRM.log:

Thu Jul 11 10:27:41 2019 [21169][2e369ef6-4154-0bc5-5416-592e72a1c5fd][INFO] Query:SELECT `accounts`.name AS 'Name0', `accounts_cstm`.sapmd_name2_c AS 'Name21', `accounts:contacts`.last_name AS 'Nachname2', `accounts`.id AS 'accounts_id', `accounts:contacts`.id AS 'accounts:contacts_id' FROM `accounts` LEFT JOIN `accounts_cstm` `accounts_cstm` ON `accounts`.id = `accounts_cstm`.id_c LEFT JOIN accounts_contacts `accounts|accounts:contacts` ON `accounts`.id=`accounts|accounts:contacts`.account_id AND `accounts|accounts:contacts`.deleted=0  LEFT JOIN contacts `accounts:contacts` ON `accounts:contacts`.id=`accounts|accounts:contacts`.contact_id AND `accounts:contacts`.deleted=0  AND ( contacts.assigned_user_id ='2e369ef6-4154-0bc5-5416-592e72a1c5fd'  or  EXISTS (SELECT  1                   FROM    securitygroups secg                           INNER JOIN securitygroups_users secu                              ON secg.id = secu.securitygroup_id                                 AND secu.deleted = 0                                 AND secu.user_id = '2e369ef6-4154-0bc5-5416-592e72a1c5fd'                           INNER JOIN securitygroups_records secr                              ON secg.id = secr.securitygroup_id                                 AND secr.deleted = 0                                 AND secr.module = 'Contacts'                        WHERE   secr.record_id = `accounts:contacts`.id                                AND secg.deleted = 0) )  WHERE accounts.deleted = 0  AND ( accounts.assigned_user_id ='2e369ef6-4154-0bc5-5416-592e72a1c5fd'  or  EXISTS (SELECT  1                   FROM    securitygroups secg                           INNER JOIN securitygroups_users secu                              ON secg.id = secu.securitygroup_id                                 AND secu.deleted = 0                                 AND secu.user_id = '2e369ef6-4154-0bc5-5416-592e72a1c5fd'                           INNER JOIN securitygroups_records secr                              ON secg.id = secr.securitygroup_id                                 AND secr.deleted = 0                                 AND secr.module = 'Accounts'                        WHERE   secr.record_id = accounts.id                                AND secg.deleted = 0) )  LIMIT 0,100
Thu Jul 11 10:27:41 2019 [21169][2e369ef6-4154-0bc5-5416-592e72a1c5fd][FATAL] Mysqli_query failed.

#### Steps to Reproduce

1. Create Report with Modul Accounts
2. Take one field of account and a related modul like contacts
3. Login as normal user with no admin rights
4. Report does not return entries

#### Your Environment

* SuiteCRM Version used: 7.10.16 LTS
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 67.0.4 (64-Bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.1.26, php 7.0
* Operating System and version (e.g Ubuntu 16.04): debian 9

**Comment by pgorod** [comment]
It seems this fix creates a small regression related to custom fields:

https://github.com/salesagility/SuiteCRM/issues/8334#issuecomment-569423334
