### ISSUE TITLE
single quote in PDF template rendered as little square

### ISSUE THREAD

**Issue by ventoh** [salesagility/SuiteCRM#756]
Already noticed in the forum https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/5074-aos-pdf-template-charset-encoding-issue

**Comment by CaptainChainsaw** [comment]
Example invoice screenshot after fix applied:

![apostrophe-github-issue-756](https://cloud.githubusercontent.com/assets/3913259/12649705/a95fe686-c5d7-11e5-83c4-9a7e5f179f33.png)
