### ISSUE TITLE
MS SQL Query Error

### ISSUE THREAD

**Issue by ericgullickson** [salesagility/SuiteCRM#757]
When trying to export the import opportunity template I get a database error. I have a custom one-to-one relationship setup between the users module and opportunities module. This seems to create an issue with the opportunities.user_id_c column being duplicated in the query. Here is the query that shows in the suitecrm.log file. This is running on Server 2012 R2 IIS8 and SQL 2014. 

SELECT
                                opportunities.*,
                                accounts.name as account_name,
                                users.user_name as assigned_user_name ,opportunities_cstm.cd_estimated_gp_c,opportunities_cstm.cd_opp_id_c,opportunities_cstm.jjwg_maps_address_c,opportunities_cstm.jjwg_maps_geocode_status_c,opportunities_cstm.jjwg_maps_lat_c,opportunities_cstm.jjwg_maps_lng_c,opportunities_cstm.user_id_c, opportunities_cstm.user_id_c, LTRIM(RTRIM(ISNULL(relJoin1.first_name,'')+' '+ISNULL(relJoin1.last_name,''))) cd_opp_architect_c  FROM opportunities LEFT JOIN users
                                ON opportunities.assigned_user_id=users.id LEFT JOIN accounts_opportunities
                                ON opportunities.id=accounts_opportunities.opportunity_id
                                LEFT JOIN accounts
                                ON accounts_opportunities.account_id=accounts.id  LEFT JOIN opportunities_cstm ON opportunities.id = opportunities_cstm.id_c  LEFT JOIN users relJoin1 ON opportunities_cstm.user_id_c = relJoin1.id AND relJoin1.deleted=0 where 
            (accounts_opportunities.deleted is null OR accounts_opportunities.deleted=0)
            AND (accounts.deleted is null OR accounts.deleted=0)
            AND opportunities.deleted=0 ORDER BY opportunities.name 

```
        SELECT TOP 5 * FROM
                            (
                                SELECT
                            opportunities.*,
                            accounts.name as account_name,
                            users.user_name as assigned_user_name ,opportunities_cstm.cd_estimated_gp_c,opportunities_cstm.cd_opp_id_c,opportunities_cstm.jjwg_maps_address_c,opportunities_cstm.jjwg_maps_geocode_status_c,opportunities_cstm.jjwg_maps_lat_c,opportunities_cstm.jjwg_maps_lng_c,opportunities_cstm.user_id_c, opportunities_cstm.user_id_c, LTRIM(RTRIM(ISNULL(relJoin1.first_name,'')+N' '+ISNULL(relJoin1.last_name,''))) cd_opp_architect_c  , ROW_NUMBER()
                                OVER (ORDER BY opportunities.name) AS row_number
                                FROM opportunities LEFT JOIN users
                            ON opportunities.assigned_user_id=users.id LEFT JOIN accounts_opportunities
                            ON opportunities.id=accounts_opportunities.opportunity_id
                            LEFT JOIN accounts
                            ON accounts_opportunities.account_id=accounts.id  LEFT JOIN opportunities_cstm ON opportunities.id = opportunities_cstm.id_c  LEFT JOIN users relJoin1 ON opportunities_cstm.user_id_c = relJoin1.id AND relJoin1.deleted=0 where 
        (accounts_opportunities.deleted is null OR accounts_opportunities.deleted=0)
        AND (accounts.deleted is null OR accounts.deleted=0)
        AND opportunities.deleted=0 
                            ) AS a
                            WHERE row_number > 0
```

**Comment by ChangezKhan** [comment]
I am not able to re-create the same issue on SuiteCRM 7.8.2 with MSSQL 2008. Kindly confirm if the issue is still persists.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
