### ISSUE TITLE
Optimize include language file

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#7578]
#### Issue

The biggest language file is include/language/en_us.lang.php  with 172 kb

#### Expected Behavior

A clean and smaller file

#### Actual Behavior

Its a long file, with lots of empty space, no indent style... its time to clen it up and save some bytes!

#### Possible Fix

Clean up non required blank lines, use a single indent rule, separate the different arrays style... and so on!
This needs to be done by Sales Agility devs!

#### Context

As long as the edits do not change the contents (key / value) you can change the order of the strings, this will not cause issues to language files being translated via Crowdin!

**Comment by Dillon-Brown** [comment]
@horus68 I believe the indent style should be correct on hotfix-7.10.x and hotfix. I can look at further cleaning up this file and other language files though, perhaps adding no blank lines in language files to our coding standards.

**Comment by pgorod** [comment]
The blank lines contain information - they act as separators between blocks, improving readability. I wouldn't remove them unless they pose a problem. Do they?

**Comment by pgorod** [comment]
About the main problem, the file size: how can this be reduced? Maybe many of those strings really belong in specific module files, instead of here in the generic file. but it's risky to start moving them around...

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
