### ISSUE TITLE
AOR_Report javascript Uncaught ReferenceError: moduleFieldsPendingFinishedCallback is not defined

### ISSUE THREAD

**Issue by cherrador** [salesagility/SuiteCRM#7589]
Any AOR_Report that has parameters will show this javascript error when the browser DevTools is open.

#### Issue
When this error happens any process on the javascript chain is aborted. Sometimes could go unnoticed, but sometimes some of the parameters do not work.

#### Expected Behavior
The browser DevTools should not have errors and finish the rest of the code.

#### Actual Behavior
The browser Devtools show this error and a chain of scripts that have been aborted.
```
Uncaught ReferenceError: moduleFieldsPendingFinishedCallback is not defined
    at testModuleFieldsPendingFinished (conditionLines.js:319)
    at Object.success (conditionLines.js:367)
    at Object.handleTransactionResponse (sugar_grp1_yui.js?v=yY0BqtbsPwJL6Y6XgcOzmg:109)
    at sugar_grp1_yui.js?v=yY0BqtbsPwJL6Y6XgcOzmg:109
```
#### Possible Fix
This variable (function) is only defined at Edit mode at the EditViewFooter template. But the global way it's tested, it will create ReferenceError. A good practice test will be by modifying the file /modules/AOR_Conditions/conditionLines.js at line 319

from:
```javascript
if (moduleFieldsPendingFinishedCallback) {
```

to:
```javascript
if (typeof moduleFieldsPendingFinishedCallback == "function") {
```
or at least to the proper global version:
```javascript
if (window.moduleFieldsPendingFinishedCallback) {
```

#### Steps to Reproduce
1. Create an AOR_Report.
2. On the 'Conditions' tab, add conditions that has tick on the 'parameter' check box.
3. Open the browser DevTools (F12).
4. Open the report on view mode, it will have the ReferenceError.

#### Context
Almost randomly, the last parameter does not work properly. Reloading a couple of times the error is passed to a different parameter.

#### Your Environment
* SuiteCRM 7.8.30:
* Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Apache 2.4.39, PHP 7.1.30, MySQL 8.0.15
* Windows 2016 Server

**Comment by Dillon-Brown** [comment]
Fixed here: #5667

**Comment by cherrador** [comment]
Hi @Dillon-Brown this is report for 7.8 not 7.10 as it has been corrected there. In the case of 7.8 when the AOR_Report is on "View" mode, the `moduleFieldsPendingFinishedCallback` function is not available, it is only available in "Edit" mode. So if you try to execute the function without verifying like how it's done on the 7.10 fix, it will fail again fail with Uncaught ReferenceError. Not sure if this the same issue on 7.10.

**Comment by samus-aran** [comment]
@cherrador Hi cherrador. 7.8.x has now reached its end of life. So we will not be resolving bugs that only appear in 7.8.x branch.
https://docs.suitecrm.com/admin/releases/7.8.x/#_7_8_31_lts

As it has already been resolved in the 7.10.x why don't you pull back that fix into your version if you are unable to upgrade.

**Comment by cherrador** [comment]
@samus-aran I missed that note about end of life of 7.8. I will put this note into our IT team to finalize the PHP 7.2 (maybe 7.3) server upgrade and certify SuiteCRM runs properly on that PHP version.

Question, after 7.8.31, will be zero patches for version 7.8? Or will be only high priority patches? If there will be patches, could I still create pull requests for some of these fixes?

**Comment by cherrador** [comment]
Now I remember, our IT team is waiting for #6750 to be completed and merged. Is there anything that I can help to this to happen?
