### ISSUE TITLE
Upgrade 7.1.3 to 7.1.4 - Files version mismatch Database version

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#76]
Upgrade to 7.1.4 (via Admin page, Upgrade Wizard) goes without error.
After last step, just as it's about to show the About page, it gives this error instead:
"Sugar CRM 6.5.17 Files May Only Be Used With A Sugar CRM 6.5.17 Database."
How to fix?
Probably will require a re-test and re-release of the upgrade package ?

**Comment by willrennie** [comment]
7.1 now EOL and it is recommended that you upgrade to either SuiteCRM 7.2.x or SutieCRM 7.3.x. If you ensure the SugarCRM version in your sugar_version.php, config.php and config table are all the same, you should have no issues.
