### ISSUE TITLE
Trying to get property of non-object in Favorites.php

### ISSUE THREAD

**Issue by Markussss** [salesagility/SuiteCRM#761]
While there might be a problem with my instance of SuiteCRM, I still think it can be smart to report this here.

When returning to work today, Monday morning, my local dev-installation of SuiteCRM was throwing notices about trying to get properties of non-objects, with the following notice:

Notice: Trying to get property of non-object in /var/www/suitecrm/modules/Favorites/Favorites.php on line 90

This is easily fixed by checking if the bean-object actually is an object to the block, just after creating the bean-object. Although this is a fix that works, it might only be a temporary fix with edge-cases that messes with something. However, checking if objects are objects before treating them as such is (as far as i can recall from my experience in other OOP languages) common practice and should be done system-wide. I don't know if it is worth the effort, though. You guys can see if there is a need to do so, or if it's better to just hide notices and warnings and only fix the problems created when they surface.

**Comment by CaptainChainsaw** [comment]
Looks like the fix for issue #826 also resolved this.
