### ISSUE TITLE
Quick create record from mail

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#762]
Hi, 

If you create the quick record from mail, via the button quick create, it  looks as on picture. 

It's going under the menu panel (i'm talking about header of quick window record) + the window of this quick create record can't resize to bigger window, only i can scroll to right site of window :(

![quick](https://cloud.githubusercontent.com/assets/5773777/11622925/795639c2-9cc9-11e5-9122-6f97c48f23aa.png)

**Comment by samus-aran** [comment]
Hey @Mausino Did you have a chance to test the fix provided?
https://github.com/salesagility/SuiteCRM/pull/2239

**Comment by Mausino** [comment]
@samus-aran  i have installed latest version of 7.8 on my local instace and it looks that working. The windows ins't going uner bar as before. Sorry at monday i got hight fewer and couldn't be on PR party.

**Comment by samus-aran** [comment]
Aww, sorry to hear that @Mausino. Hope you're feeling better. You participated all the other times so don't worry. I do have you ticked as a PR party participant ;)

**Comment by Mausino** [comment]
@samus-aran should be this moved into hotfix for 7.8 version or closed ? That we have one "Fix Proposed" issue less

**Comment by Mausino** [comment]
Should i close this issue ??? or will merge to LTS (because it not critical or security issue)

https://suitecrm.com/lts/ by this it looks that 7.8 version will soon death and will great if will corrected the graph also for 7.11 version (because was only relased now)

**Comment by Dillon-Brown** [comment]
@Mausino At the moment 7.8.x is still supported as LTS so if there is a fix for this issue it can still be merged. And yeah you are correct that the graph needs updated as it's quite out of date.

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
