### ISSUE TITLE
Make the code:coverage Robo command work outside of CI

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7622]
#### Issue
This is part of #7344, but I'm splitting it out into a separate issue.

Right now the code coverage Robo command won't work outside of CI, which is a pretty unnecessary limitation. We should make sure it can be run locally as well.

**Comment by pgorod** [comment]
Hi Connor. On a slightly (un)related issue: I'm thinking of creating a "Diagnostics" Robo task to gather basic information like versions, web server username, php.ini ath, etc. This would greatly help me in my work in the Forums.

But I would like the same code to be usable from the UI (under Admin / Diagnostics). 

I wonder if it wouldn't be a good idea to have **all** Robo tasks available from Admin screens. I guess this shouldn't be too hard for those that simply output text, and we can spit that out onto the web response. It might be a bit trickier for those that gather user input (do we have any at the moment?), but it could also be done.

Thoughts?

**Comment by connorshea** [comment]
@pgorod as long as we do it only for specific Robo tasks that make sense to have available via the web UI, I'm fine with that. That said, I don't think any of the current Robo tasks make sense to have in the web UI, except maybe the ones for clearing the cache and building the SuiteP theme.

I'm also admittedly somewhat wary of introducing them as it creates more places where we need the apache process to have access rights to files on the server, which would make it harder to eventually pull back on the file permissions.

I'd say open a new issue for the diagnostics task, it sounds like a good idea :)

**Comment by connorshea** [comment]
@pgorod I opened #7631

**Comment by connorshea** [comment]
It's kind of weird to me that it doesn't output anything when the tests fail, but other than that it seems to work 🤷‍♂

**Comment by connorshea** [comment]
@Dillon-Brown FWIW, there is one other problem I think might be worth solving here. If the XDebug extension isn't installed and configured, the code:coverage Robo task will still say that the coverage.xml is available in `tests/_output/` despite the code coverage XML file not actually being created. This is kind of confusing, but I'm not sure how best to solve it.

Maybe add a check for whether the coverage.xml file actually exists before we print that message?
