### ISSUE TITLE
Is Free SuiteCRM theme secure?

### ISSUE THREAD

**Issue by softwaresh** [salesagility/SuiteCRM#7628]
I'm using [SuiteCRM free theme](https://www.techesperto.com/news/download-free-suitecrm-theme/) offered by Techesperto Solutions. 

Is it secure for my SuiteCRM platform?

**Comment by samus-aran** [comment]
This is definitely a question for the SuiteCRM forums. We are not affiliated with third party service providers, this GitHub repo is only for core bugs or suggestions. You should ask Techesperto Solutions on their own code.

**Comment by samus-aran** [comment]
Actually... looking into your companies you are actually affiliated to each other.
