### ISSUE TITLE
Oportunities with assigned tasks not displayed

### ISSUE THREAD

**Issue by gody01** [salesagility/SuiteCRM#7634]
If task is associated with Opportunity (I suspect, any other record) Opportunities list is not displayed any more.

#### Issue

Our sales person assigned task to Oportunity.
After this acction when someone select Oportunities List Error is returned.

In suitecrm.log this error is reported:
MySQL error 1054: Unknown column 'tasks.date_end' in 'field list'

Oportunity should be displayed and task should be listed in subpanel.

Error is returned and Opportunity is not listed

MySQL error 1054: Unknown column 'tasks.date_end' in 'field list'

#### Possible Fix
Tasks/metadata/subpanels/ForActivities.php

--- ForActivities.php~	2019-07-10 11:37:28.000000000 +0200
+++ ForActivities.php	2019-07-26 09:30:17.024660184 +0200
@@ -76,8 +76,8 @@
         'date_due' => array(
             'vname' => 'LBL_LIST_DUE_DATE',
             'width' => '10%',
-            'alias' => 'date_end',
-            'sort_by' => 'date_end',
+            'alias' => 'date_due',
+            'sort_by' => 'date_due',
         ),
         'assigned_user_name' => array(
             'name' => 'assigned_user_name',

1. Add Task to Opportunity
2. Save
3. Got To Opportnity List View
4.

#### Context

Opportunity list stop working.
Very Highg priority

* SuiteCRM Version used: 7.11.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): CentOS with php 7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS.

**Comment by Dillon-Brown** [comment]
Interesting, I'm not actually able to replicate this. This might have been fixed by some of the other due_date fixes that have gone into hotfix-7.10.x recently.

**Comment by gody01** [comment]
> Interesting, I'm not actually able to replicate this. This might have been fixed by some of the other due_date fixes that have gone into hotfix-7.10.x recently.

It might be. On my pull-request  #7635 I've got some Codecov Report, which on other PR didn't write me :)

Anyhow, just that it's solved for next release ...
