### ISSUE TITLE
After upgrade from 7.11.5 to 7.11.6, Main group title not showing any more 

### ISSUE THREAD

**Issue by rholighaus** [salesagility/SuiteCRM#7644]
#### Expected Behavior

A main group had created a header block for each group with the content of the main group field for that group as title.
#### Actual Behavior

After upgrading to 7.11.6, there is no title displayed any more.
#### Steps to Reproduce

1. Create a report with at least one group
2. Define that group as main group
3. On 7.11.5, the main groups will have titles
4. on 7.11.6, the main groups no longer have titels

#### Your Environment

* SuiteCRM Version used: 7.11.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by mattlorimer** [comment]
Fixed in the current release
