### ISSUE TITLE
Text field missing for Suggestions Label?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#7647]
#### Issue

In Cases (Edit or New) - LBL_SUGGESTION_BOX label do not have a text field to be used.

#### Actual Behavior

See image:
![2019-07-26 16_10_23-SuiteCRM7](https://user-images.githubusercontent.com/3055443/61961936-5e2b7a00-afc0-11e9-8572-6ab9cb2b3082.png)

#### Steps to Reproduce

1. Open a Case or create one

#### Your Environment

* SuiteCRM Version used: Version 7.11.6 (Clean full install, with sample data)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Google Chrome, v.  75.0.3770.142 (32 bits)
* Environment name and version (e.g. MySQL, PHP 7): Wamp server, Apache 2.4.18, MySQL 5.6.17, PHP 7.2.14
* Operating System and version (e.g Ubuntu 16.04): Windows 10,

**Comment by samus-aran** [comment]
Hey @horus68 That is expected behaviour. That field is not a text field but the Knowledge Base field that display any related "suggestions" when you type into the Subject field.
