### ISSUE TITLE
Case Module: Description field not showing after Save and continue

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#7648]
#### Issue

Description Text field disappears when browsing (edit mode) or after button "Save and Continue"

#### Expected Behavior

Field should be available for edits as the other fields (Subject or Resolution)

#### Actual Behavior

![2019-07-26 16_21_38-Microsoft Edge](https://user-images.githubusercontent.com/3055443/61964457-d0eb2400-afc5-11e9-92e7-c00d718e24c3.png)

#### Steps to Reproduce

1. Open Case
2. Edit mode (Description field is visible and editable)
3. Hit "Save and Continue" or "NEXT button"
4. Now description field do not show up (even if it has some value in it)

#### Your Environment

* SuiteCRM Version used: Version 7.11.6 (Clean full install, with sample data)
* Browser name and version: Google Chrome, v. 75.0.3770.142 (32 bits)
* Environment name and version (e.g. MySQL, PHP 7): Wamp server, Apache 2.4.18, MySQL 5.6.17, PHP 7.2.14
* Operating System and version: Windows 10

**Comment by 604media** [comment]
![image](https://user-images.githubusercontent.com/64729/62044066-a85e6680-b21f-11e9-936f-6ad8aa85aad8.png)
