### ISSUE TITLE
Unable to override core Dashlet logic with files in custom/

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7649]
#### Issue
I'm unable to override the behavior of a core Dashlet from the `custom` folder.

#### Expected Behavior
I add a file called `custom/modules/Leads/Dashlets/MyLeadsDashlet/MyLeadsDashlet.php` and it overrides the file at `modules/Leads/Dashlets/MyLeadsDashlet/MyLeadsDashlet.php`.

#### Actual Behavior
Nothing happens. The dashlet isn't overwritten.

#### Possible Fix
Add code for the dashlet loader that checks for a file with the same name in the `custom/` directory.

#### Steps to Reproduce
1. Have a SuiteCRM instance
2. Add the 'My Leads' dashlet to your homepage.
3. Copy the contents of `modules/Leads/Dashlets/MyLeadsDashlet/MyLeadsDashlet.php` into a new file at `custom/modules/Leads/Dashlets/MyLeadsDashlet/MyLeadsDashlet.php`.
4. Modify the file, e.g. by adding a log statement.
5. Run a repair and load the homepage.
6. Note that the log statement is never executed.

#### Context
I was hoping to override the 'My Leads' dashlet so we could modify it's logic and filter out certain leads we didn't want to include in it, but now I have to edit the core files to do this.

#### Your Environment
* SuiteCRM Version used: 7.9.17
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave 10.14.6

**Comment by pgorod** [comment]
Copying from my reply about this in Gitter channel:

> Try to extend the class, instead of just trying to replace the code with a file in custom
> 
> More about Dashlets class architecture [here](https://web.archive.org/web/20150702210859/https://www.atcoresystems.com/blog/introduction-to-creating-sugarcrm-dashlets).
> Example [here](https://suitecrm.com/suitecrm/forum/developer-help/695-override-lead-dashlet?start=15#3315)

I'm not saying the mechanism shouldn't be improved - if things can be made simpler, sure. We should favor class extensions where possible, instead of full-file replacements. But even for class overrides it might be possible to just extend one file, instead of having to create several, as the examples seem to show (I didn't look very attentively at the examples, I must admit).

**Comment by connorshea** [comment]
@pgorod as far as I can tell, extending the LeadsDashlet class doesn't seem to change anything either. The files doesn't seem like it's being loaded, or if it is being loaded it isn't being loaded as an override for the original dashlet.

I suppose we could disable the core dashlet and just make a new dashlet that extends the core leads dashlet, if that's what you meant.

**Comment by pgorod** [comment]
This part

`class MyCustomLeadsDashlet extends DashletGeneric {`

are you sure the specific Dahslet you're overriding hasn't done a previous override? In that case you would have to override the second class, not the first.

Can you get Andy's example to work?

**Comment by connorshea** [comment]
Sorry I never responded to this @pgorod. It's been a while since I touched the code for the dashlet I was trying to customize, but I'm fairly certain it didn't get overridden by anything else.

I assume #8010 might fix the problem.
