### ISSUE TITLE
Cannot import Email if plain-text plus attachment

### ISSUE THREAD

**Issue by mullocksj** [salesagility/SuiteCRM#7667]
#### Issue
If an email consists of a plain-text section and attachment the import either does not function at all, or the imported email is missing the body. These emails read fine using another IMAP client or on Gmail. If the email has an html section and attachment the import works as expected

#### Expected Behavior
It should be able to import emails that have a plain-text body with or without attachment

#### Actual Behavior
If I use my usual IMAP server Mercury/32 vs 4.8, then most emails are fine, but any email with attachment where the body is plain-text will import but with no visible body. If I look in the database the body is blank
I have also tried sending a test email to my Gmail account and using suiteCRM to connect via IMAP. Other emails work (so I got the setup correct) but the plain-text plus attachment email will not import at all.

#### Possible Fix
I guess the email parsing code needs attention

#### Steps to Reproduce

[YSCHMMM2.txt](https://github.com/salesagility/SuiteCRM/files/3451776/YSCHMMM2.txt)

Option 1 - can see the exact email that failed for me in advance
1. Take the attached raw email and rename to .eml
2. Drop the .eml file into a local Thunderbird folder (into the application, you don't need to find the Thunderbird folders on the disk)
3. Use Thunderbird to move the email to a folder that is monitored by suiteCRM

Option 2 - try your own email
1. Send a plain text email aith attachment to your Gmail account, using e.g. Thunderbird
2. In Gmail, confirm that your email client has not helpfully added an html section
3. Enable IMAP for your Google account and use suiteCRM to look at it

#### Context
This bug has always been there as far as I know. I was using 7.10.xx before, now on 7.11.6
I cannot have a policy of importing client emails until this is fixed because some will not import. If we always have to check elsewhere for email history concerning a client or opportunity, there is little point in importing any emails. The clients send the emails, so a work-aound that says never use plain-text is no good. The only work-around is to give up on importing email altogther and have a policy of maybe cutting and pasting email history into a document held on the CRM (any other suggestions?)

#### Your Environment
suiteCRM 7.11.6
Firefox 68.0 (64-bit)): plus anything else I've tried
PHP 7.3.6
Apache 2.4.39
MySQL Version 10.2.24-MariaDB-cll-lve
IMAP server Mercury/32 4.8, but also Gmail

**Comment by fraromano** [comment]
Perhaps there is something wrong in this patch. I have upgraded to SuiteCRM 7.10.20 from 7.10.10 and now most html emails imported is missing the body. I have to revert this patch to make message body import working again.

**Comment by Dillon-Brown** [comment]
Hi @fraromano, there is an issue raised for this here: #7880. Thanks!
