### ISSUE TITLE
Schedulers module - Tasks names are not translated

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#767]
On Schedulers module Tasks names are not translated in ListView and DetailView. But they are translated ok in the edit view. 
Confirmed in different language packs and different setups form different users

In SuiteCRM 7.4.x go to Admin panel-> Schedulers
/index.php?module=Schedulers&action=index

Error: All tasks in the ListView and DetailView are displayed only in English.
![screen027](https://cloud.githubusercontent.com/assets/3055443/11689446/f90c3d62-9e89-11e5-9bef-f0d48417b232.jpg)

OK: Task name is displayed in local language olny as combobox value in the EditView.
![screen026](https://cloud.githubusercontent.com/assets/3055443/11689462/0c0ef986-9e8a-11e5-98e3-bd8e54d0289d.jpg)

Reported in forum: #25381 - https://suitecrm.com/forum/international-language-support/3898-language-strings-issues#25381

**Comment by mattlorimer** [comment]
This is actually the 'name of the scheduler not the dropdown value
