### ISSUE TITLE
Sprint Planning (16)  📅 🗣

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#7673]
Good Evening Everyone! :wave: 

We are 1 week away from commencing our Sprint 16. So we would like to take this opportunity to ask for your nominated issues here in this thread so we can assess, refine and coordinate with ourselves (the Core Team) and the community contributors on the upcoming priorities.

If you are new to this sprint planning then essentially we are asking you, as the users, to post your issues (by referencing the GitHub hash/ID) that you would like to see being tackled. We, the Core Team, will review and select the achievable ones within the sprint and allocate them among ourselves. The others we may label them as Help Wanted which would make them up for grabs by our community code contributors. This process will help encourage ownership of these bugs and their bug fixes. [Find out more of the sprint concept here](https://github.com/salesagility/SuiteCRM/issues/7358) :point_left: 

Sprints are every 2 weeks with the aim to deliver a release every 2 Sprints (monthly). However since we just had a release mid-sprint there the next release will be a single sprint giving us an ETA for 7.11.8  21 August.  

Just to re-iterate from my earlier posts, that the core team do have other tasks that may not be identified in the above sprints and these are usually from our own internal backlog i.e. improving the release process, CI/CD tools (Travis cry ), security patches etc so that accounts for our some ‘slack’ visible in the public sprints.

Look forward to your nominations! :writing_hand:

**Comment by connorshea** [comment]
There are still some flaky tests on hotfix-7.10.x (#7272) that should probably be looked-into, I don't understand why they're so fragile :/

The other two things I'm interested in seeing done are pretty much code cleanup:

- Move the remaining vendored packages in our repository to Composer #7605 - I opened a PR for Smarty two weeks ago (#7591) and a PR for Zend today (#7672), and there are a few other PRs open by various people to move vendored packages to Composer. This'll make the codebase much simpler and help us upgrade the packages more easily.
- Remove minified JavaScript from the repository #7340 - that'll help remove a lot of confusion and complexity from editing JavaScript in the CRM.

**Comment by bdcomp** [comment]
I would appreciate some love to this upgrade issue #7242

**Comment by connorshea** [comment]
Also, could I get a response from the SalesAgility team on #7463? I'd like to get a yes/no on whether we'll be able to do that with 7.10. It's preventing me from making some changes that I think are really important to maintaining simple compatibility between 7.10 and 7.11, e.g. linting, codeception 3.0, and probably other packages that we'll have problems with using on 5.5 that I haven't run into yet.

If it's a no, that's fine too, but I'd like at least like a response so I can move on to working around some of these problems in other, hackier ways if necessary. :)

**Comment by LeoZandvliet** [comment]
I'd like to have some attention for some API issues, that's quite unworkable now:

* [Filtering with relationship doesn't work](https://github.com/salesagility/SuiteCRM/issues/6074)
* [Database failure when filter custom fields by V8 API](https://github.com/salesagility/SuiteCRM/issues/7285)

Anything I tried (just started very recently with SuiteCRM) with custom or related fields doesn't work. I also have the feeling the docs are out of date on this subject, but I don't know how it's supposed to be. Coming from SugarCRM 7.9 this version of the API threw me quite some years back :)
I will struggle my way through the code to see if there's something I can throw in.

**Comment by tsmgeek** [comment]
#7533 Group folder subscriptions email broken

**Comment by kockhwie** [comment]
#6982

**Comment by samus-aran** [comment]
Closed!
