### ISSUE TITLE
en_us.SecurityGroups.php and array_merge

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#768]
Why is there so different approach on language strings? Isn't it possible to make this clean and simply? This is causing issues using translation tools. I also doubt this is not affecting SuiteCRM performance.
See this 2 different approaches for the same action under custom language files:

\custom\Extension\modules\Accounts\Ext\Language\en_us.SecurityGroups.php

```
$mod_strings = array_merge($mod_strings,
    array(
         'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => "Security Groups",
    )
);
```

But then the file en_us.SecurityGroups.php at
\custom\Extension\modules\Administration\Ext\Language\en_us.SecurityGroups.php

```
$mod_strings['LBL_MANAGE_SECURITYGROUPS_TITLE'] = 'Security Suite Group Management';
$mod_strings['LBL_MANAGE_SECURITYGROUPS'] = 'Security Suite Group Editor';
```

This is a clean way of work. Why this is not the standard?

**Comment by ghermans** [comment]
:+1:

**Comment by horus68** [comment]
I hope that the second option will be used. 
As a temporary fix, to use this file with with an online translation tool I had to change it to

```
<?php
$array = array(
		 'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => "Security Groups",
	);

$mod_strings = array_merge($mod_strings, $array);
?>
```

**Comment by Mausino** [comment]
@horus68 can you create pull request for this issue. I think will forward faster when will the patch available.

**Comment by serhiisamko091184** [comment]
Hello @horus68 

Thanks for your feedback and reminder. 

I'm closing the issue as it appears to be fixed in the latest version. 

Many thanks! 

Regards,
Serhii
