### ISSUE TITLE
Dashboard Blank

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7688]
Hi, out of nowhere, I am unable to view any information on the home dashboard, including as an Administrator.

There is no issue on the Log list about this as well.

**Comment by Mausino** [comment]
@MyBlissIT 

Hi, please should you use the issue template ? we need to know many things... like version, if you did any customization or upgrade and exact description of issue. 

@Dillon-Brown  I am suggesting to close the issue and posts it into [forum](https://suitecrm.com/suitecrm/forum/index)

**Comment by MyBlissIT** [comment]
> @MyBlissIT
> 
> Hi, please should you use the issue template ? we need to know many things... like version, if you did any customization or upgrade and exact description of issue.
> 
> @Dillon-Brown I am suggesting to close the issue and posts it into [forum](https://suitecrm.com/suitecrm/forum/index)

@Mausino My SuiteCRM Version 7.10.18
Sugar Version 6.5.25 (Build 34

I did a couple of customization including editing the User Labels under Studio. In them, I replaced SuiteCRM with a custom name.

I disabled the login page menu bar logo and changed login logo as well following this fix:

"replace the themes/SuiteP/images/p_login_logo.svg (Or delete it and replace the p_login_logo.png). For the favicon, you would be replacing include/images/sugar_icon.ico."

Other customizations were related to module fields

**Comment by gunnicom** [comment]
Three things you should try:
- check the apache error.log
- Quick-Repair & Rebuild from the Admin section
- Check the  filesystem permissions (I use this "sudo chmod -R 775 cache custom data modules upload && sudo chown www-data:www-data . -R && sudo chmod 664 config.php" )

**Comment by suneelIBMkummar** [comment]
Our Dashlets are no longer visible after the upgrade.. Any fix ?

**Comment by Dillon-Brown** [comment]
Closing in favour of #7696

**Comment by MyBlissIT** [comment]
I downloaded latest version, 7.11.7 zip file from SuiteCRM website. Following the Upgrade instruction, when I attempt to Upload Package I get an error message that "The zip file is missing a manifest.php file. Cannot proceed."

![image](https://user-images.githubusercontent.com/34719141/63128069-54d87080-bfb4-11e9-8440-6856a9896507.png)
