### ISSUE TITLE
Folder "include/SugarCharts/Jit" missing in 7.11.7 installation

### ISSUE THREAD

**Issue by Wolfpaxx** [salesagility/SuiteCRM#7696]
#### Issue
The folder "include/SugarCharts/Jit" was removed from the installation .zip between 7.11.6 and 7.11.7.
This causes not being able to modify the Dashlets on the start page.
The suitecrm.log states this as "[FATAL] Chart class not found."

#### Expected Behavior
The folder "include/SugarCharts/Jit" including the recend files and subdirectories should be in the 7.11.7 installation .zip
You should be able to add, modify or delete Dashlets on the start page.

#### Actual Behavior
The folder "include/SugarCharts/Jit" including the recent files and subdirectories are non-existant.
Clicking on the action buttons to add, modify or delete Dashlets causes no action (no error message, no loading screen)

#### Possible Fix
Include the folder "include/SugarCharts/Jit" including the recend files and subdirectories again in the next version

Current Workaround: Copy folder "include/SugarCharts/Jit" from 7.11.6 installation .zip into the 7.11.7 installation

#### Steps to Reproduce
1. Open 7.11.7 installation-zip
2. Open 7.11.6 installation-zip
3. Compare folders "include/SugarCharts/" and see the missing "Jit" folder

#### Context
Cant modify Dashlets

#### Your Environment
* SuiteCRM Version used: 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): multiple
* Environment name and version (e.g. MySQL, PHP 7): Apache 2.4, MariaDB 7.2, PHP7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS7

**Comment by Dillon-Brown** [comment]
Thanks for the detailed report @Wolfpaxx. Taking a look at this now and will push up a fix today.

**Comment by pcfreak30** [comment]
@Dillon-Brown this seems to have a bigger issue overall. I can't seem to find where the chart js is loaded/referenced at all, even after applying https://github.com/Dillon-Brown/SuiteCRM/commit/7e21c5806f1b23db91e32ec88a654bab518cfbc6. In my case, I am looking at the campaigns. Overall the file does not seem to be getting loaded?

**Comment by Dillon-Brown** [comment]
Hi @pcfreak30, whereabouts in campaigns are you running into this issue? do you have anything in your apache or suitecrm logs? I would also double-check that your browser cache has been cleared after applying #7697.

**Comment by marcovansteen** [comment]
I'm not sure if the fix really made it to the release. The issue persists in 7.11.8.

**Comment by marcovansteen** [comment]
For clarity: the folder is included in the 7.11.8 zip. But the Jit files seems to disappear after installing and using the software.

**Comment by pgorod** [comment]
Maybe the upgrade scripts are still removing it by mistake

https://github.com/salesagility/SuiteCRM-Upgrade-Scripts/blob/d13a7d645ed9516091af9d1ad13c5f9545467083/scripts/files_to_remove/UpgradeRemoval65x.php#L875-L886

But I am not sure how that file applies, or if that is the actual file used to build the upgrade pack you have. @Dillon-Brown knows.

**Comment by apexred** [comment]
Can confirm issue still persists 7.11.8.  We cannot "Add Dashlets".

Our "include/SugarCharts/Jit" folder looks like this...... but the sub-folders are empty:

drwxr-sr-x 2 www-data www-data 4096 Aug 24 11:36 css
drwxr-sr-x 2 www-data www-data 4096 Aug  2 11:14 FlashCanvas
-rwxr-xr-x 1 www-data www-data 2324 Aug 24 11:32 Jit.php
drwxr-sr-x 3 www-data www-data 4096 Aug 24 11:36 js
drwxr-sr-x 2 www-data www-data 4096 Aug 24 11:36 tpls

**Comment by Dillon-Brown** [comment]
Nice find @pgorod, that is indeed the issue. It looks like while the files are in the repo the upgrade scripts are removing them during the upgrade process (This is a problem we've had before with files that we remove and then re-add to the repo, this will be fixed for next release).

For a temporary fix, you could download the installer from the SuiteCRM download page or straight from GitHub and then copy in the ```include/SugarCharts``` directory to your instance.

**Comment by apexred** [comment]
Can confirm copying SugarCharts folder from 7.11.6 fixes the Dashlets issue.

However, Campaign charts are still missing/broken.  Is this a related problem?

**Comment by holdusback** [comment]
Come from :
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27147-cannot-add-dashlets

I got this error too. I cant add/edit dashlet

Suitecrm : 7.11.10
