### ISSUE TITLE
Sprint (16) 🚦

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#7700]
Hello Everyone!

Lets break down the previous sprint. It was a shorter sprint since we were late to raise it.

14 Cards were allocated and out of them the following were completed

To Do | In Progress | In Review | Done
------------ | ------------- | ------------- | -------------
3 | 2 | 9 | 0

![Screenshot_2019-08-09 salesagility SuiteCRM](https://user-images.githubusercontent.com/4041275/62786624-e75fa800-baba-11e9-9e77-eb26b63e9c57.png)

So it looks like we didn't get any of the allocated tasks merged which is a shame. This highlights though we have a lot in the REVIEW column.

:wave: Do you know our biggest bottleneck is testing PRs? If there is a particular fix that is ready to be merged and you want to help test it please reach out to us by commenting @salesagility/suitecrm-core. We'll try and guide you to trying out the code yourselves. This will help speed along the merging process.

Based on the Sprint 16 Planning issue ([HERE](https://github.com/salesagility/SuiteCRM/issues/7673)) these are the issues people feel are important.

* [API Filtering](https://github.com/salesagility/SuiteCRM/issues/7673#issuecomment-518333257) 
This will require a re-factor of the current filtering functionality in V8. To ensure we get it right the final time then we will need to spec this out. I'll add that to the list.

* Continue improvement of flaky tests #7272 
This we will be improving. We also want to include more unit tests and increase code coverage. That is one of our internal goals (so I don't think we can create a specific issue to it. so lets keep this one open and add to it throughout the sprint) 

* Code Cleanup
#7605 
#7591 
#7672 
#7340 

* Timeout when delete upgrade scripts #7242 
I feel this could be resolved easily. If you have a lot of upgrade scripts throughout the life does this has an affect? I think we need some help troubleshooting as we haven't been able to replicate this. ![Screenshot_2019-08-09 salesagility SuiteCRM(1)](https://user-images.githubusercontent.com/4041275/62790200-7fad5b00-bac2-11e9-9950-96aea14381c3.png)

* New user password not being generated #6982 

* Group folder subscription broken after upgrade from 7.8.x #7533 
We can't replicate this so we are asking if others can help with troubleshooting ![Screenshot_2019-08-09 salesagility SuiteCRM(1)](https://user-images.githubusercontent.com/4041275/62790200-7fad5b00-bac2-11e9-9950-96aea14381c3.png)

On top of these issues and the reviewing of the previous sprint, we also have some important things internally we are aiming to achieve. 

- Great stuff to help with automating the repo processes; 
- Clarifying and improving other Email aspects (Filtering, Debugging)
- Update API V8 documentation

As well as these we may also have high or critical issues to patch and general improvement.

**Comment by hubyhuby** [comment]
Bravo for those sprints focusing on emails.
I am a user & follower of suitecrm. I have read quite some comments along the past year about reviewing and integrating "fix proposed".

**Food for thoughts, IF reviewing is a problem , we might do a polling to find out the reasons. And how we could improve ?**

Data :
I remember having a forum talk about a year ago and there was +200 "fix proposed".
Today the situation seems MUCH BETTER, since there are 90 "fix proposed" remaining.
Of wich 37 are label:"Medium Priority" 
https://github.com/salesagility/SuiteCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Fix+Proposed%22+label%3A%22Medium+Priority%22+

Idea :
Testing could be done by non PR people like me. Personally if there was an instance in the cloud with the latest DEV Suite CRM for testing , I would be happy to test some PRs.

**Comment by hubyhuby** [comment]
The patch seems to apply a "if wysiwig "
https://github.com/salesagility/SuiteCRM/pull/5989/files
Which I can confirm is not applied in 7.8.31

**Comment by samus-aran** [comment]
Thanks @hubyhuby Yeah we had launched a nightly build which would be pointing to the hotfix branch but I don't think that would help the situation too much because each PR would potentially need it's own unique installation in order to keep the hotfix branch clean.

I enjoy netlify set up with the SuiteCRM docs PR which do somethign like that but how can we do that with a full instance I don't know. Any suggestions would be welcomed.

**Comment by pgorod** [comment]
> I enjoy Netlify set up with the SuiteCRM docs PR which does a preview for each PR but how can we do that with a full instance I don't know. Any suggestions would be welcomed.

Netlify can't handle SuiteCRM, it is strictly for serverless stuff, it can only serve static content, no PHP, no database.

Having an automated build of SuiteCRM should be possible, though, on other kinds of servers. You would basically have

* a Github hook to trigger the deploy
* server pulls the code
* server runs a silent install process with predefined parameters
* server serves SuiteCRM :-)

This isn't very different from what Travis is doing, probably, except the final part of serving the app for end-users.

We could theoretically implement all this in-house, but I don't see it happening easily, it requires some DNS magic, and some VM (or container) magic to keep all the builds simultaneously available...

**Comment by LeoZandvliet** [comment]
Excuse me bothering you, but in what way can the community/I help you guys out? For example I read in the opening of this issue:

> This will require a re-factor of the current filtering functionality in V8. To ensure we get it right the final time then we will need to spec this out. I'll add that to the list.

But where is that happening and how can we comment/review the ideas?

**Comment by samus-aran** [comment]
Didn't see your mention @LeoZandvliet apologies.
Had envisioned we would write up a RFC similar to the [Email filtering RFC](https://github.com/salesagility/SuiteCRM/issues/7725) issue, but if the community are waiting to use the same format to suggest detailed specifications on how they wish to see the filter to be robust enough for your needs then we would love to hear from yous.
