### ISSUE TITLE
Wrong version after upgrading from 7.10.x to 7.10.19 

### ISSUE THREAD

**Issue by betd-claumond** [salesagility/SuiteCRM#7707]
Hello,

#### Issue

On a SuiteCRM 7.10.17 instance, I ran the "Upgrade Wizard" following the instructions from
https://docs.suitecrm.com/admin/installation-guide/using-the-upgrade-wizard/
using the upgrade package
https://suitecrm.com/files/161/SuiteCRM-7.10-Upgrades/455/SuiteCRM-Upgrade-7.10-to-7.10.19.zip

Th process went well, but at the end, the version in suitecrm_version.php is 7.10.18 and there is change from the 7.10.19 missing (in include\SugarCharts\SugarChartFactory.php for example)

#### Expected Behavior
The version should have been 7.10.19 and all the change from the 7.10.19 should have been applied to my SuiteCRM 7.10.17 instance

#### Actual Behavior
It looks like the upgrade package SuiteCRM-Upgrade-7.10-to-7.10.19.zip is not correct.
For exemple, in the package, the file
SuiteCRM-Upgrade-7.10.x-to-7.10.19\suitecrm_version.php
has the following content

$suitecrm_version      = '7.10.18';
$suitecrm_timestamp    = '2019-07-01 17:00:00';

#### Steps to Reproduce
Upgrade a 7.10.17 or below SuiteCRM instance with the package SuiteCRM-Upgrade-7.10-to-7.10.19.zip
OR
Check the content of the package SuiteCRM-Upgrade-7.10-to-7.10.19.zip compared to the git ag 7.10.19

#### Context
7.10.19 is the new LTS version and it's important we can update our SuiteCRM instances to this version

#### Your Environment
* SuiteCRM Version used: 7.10.17
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/A
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Alpine (Docker container)

Thanks and regards,
Christophe

**Comment by Dillon-Brown** [comment]
Hi @betd-claumond, it looks like this was due to a mistake with the suitecrm_version in the sourceforge upgrade pack. I've now corrected this.

For the SugarChartFactory issue, there is a fix here: #7697

**Comment by betd-claumond** [comment]
Hi @Dillon-Brown 
Thank you very much for your feedback.
For information, I found another difference between the SuiteCRM upgraded instance and the 7.10.19 version :
- The commit
https://github.com/salesagility/SuiteCRM/commits/v7.10.19/modules/Users/SaveSignature.php
was not on my SuiteCRM upgraded instance
- but the upgrade package is containing the fix
I don't know if it is specific to my installation, but the upgrade process has not replaced the file modules/Users/SaveSignature.php
even if it was listed in the modified files at the end of the upgrade process

**Comment by Dillon-Brown** [comment]
@betd-claumond Thanks for bringing this to our attention. It looks like the upgrade process is indeed reverting the changes to ```modules/Users/SaveSignature.php``` after replacing it. I'll be taking a look at the upgrade scripts this sprint to prevent this from happening again in future releases.
