### ISSUE TITLE
Dashlet menu not working on 7.10.17

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#7709]
#### Issue
Dashlet on main page don't work properly. Buttons next page, edit, refresh, close, etc. are not working. Checked both on my and demo installation.

#### Expected Behavior
Buttons should work

#### Actual Behavior
It doesn't work

#### Steps to Reproduce

1. go to :https://demo.suiteondemand.com/index.php?module=Home&action=index
2. Try making any changes

**Comment by Dillon-Brown** [comment]
Hi @AdminPL, closing this as a duplicate of #7696 but thanks for reporting anyway! there's also a proposed fix here: #7697.
