### ISSUE TITLE
Current Sprint (17)

### ISSUE THREAD

**Issue by cameronblaikie** [salesagility/SuiteCRM#7717]
Hello Everyone! :wave: 

We are 1 week away from commencing our Sprint. So we would like to take this opportunity to ask for your nominated issues here in this thread so we can assess, refine and coordinate with ourselves (the Core Team) and the community contributors on the upcoming priorities.

If you are new to this sprint planning then essentially we are asking you, as the users, to post your issues (by referencing the GitHub hash/ID) that you would like to see being tackled. We, the Core Team, will review and select the achievable ones within the sprint and allocate them among ourselves. The others we may label them as Help Wanted which would make them up for grabs by our community code contributors. This process will help encourage ownership of these bugs and their bug fixes. [Find out more of the sprint concept here](https://docs.suitecrm.com/community/nominating-issues-in-sprint-planning) :point_left: 

Sprints are every 2 weeks with the aim to deliver a release every 2 Sprints (monthly).

Just to re-iterate from previous posts, that the core team do have other tasks that may not be identified in the above sprints and these are usually from our own internal backlog i.e. improving the release process, CI/CD tools, security patches etc so that accounts for some ‘slack’ visible in the public sprints.

Look forward to your nominations! :writing_hand:

**Comment by bjoern86** [comment]
1. Priority #7526
2. Priority #7546

I think proper E-mail referencing is one of the most basic functions a crm should support. It enables people to track a contact history properly.

**Comment by horus68** [comment]
I have more then 20 open issues on language files (some are small typos and other little issues).
Some are already too old, I don't even see the point for me to go and keep checking all of them as they are not addressed in time.
Eventually I had to keep a separate local copy of language files with some changes so the language files can work for translators.
Someday someone has to work on language files and think on the relevance of international users: first fixing issues, then, later, providing a better system. 
As you all know i don't have the code skills to create a proper solution, so life goes on like this.
See here: https://github.com/salesagility/SuiteCRM/issues/created_by/horus68

**Comment by ebogaard** [comment]
I'd like to nominate a fix for an issue with vardefs introduced in 7.10.19:  #7675
It's probably a good idea to have vardefs, db columns and db index all consistent.
I'd say the proposed length of 100 should be enough for first_name and last_name.

**Comment by ebogaard** [comment]
And I'd also like to nominate the "ghost e-mail" issue when not auto importing e-mails for group accounts: #6534
This was added to sprint 13, but wasn't completed/fixed in that sprint.

**Comment by connorshea** [comment]
Some stuff from Sprint 16:
- #7340

And some new stuff:
- #7675 - ebogaard also mentioned this one
- #7720 - This pretty much blocks usage of `pQuery`, ideally we'd also add some basic unit tests to make sure the method continues to work in the future :)
- #7627 - I'd very much like to see this fix merged
- #7659 - As well as this one

**Comment by Abuelodelanada** [comment]
Hi @cameronblaikie 

I would like to work in #7616 (PR #7617 ) 
It is working for MySQL. I can write the fix for MSSQL too but I have no way to test it.

**Comment by pgorod** [comment]
Doesn't Microsoft give away time-limited VM's of all their servers, for testing purposes?

Or even just a new Azure account, the free included credits should be enough to have an SQL Server running for a while.

**Comment by Abuelodelanada** [comment]
> Doesn't Microsoft give away time-limited VM's of all their servers, for testing purposes?
> 
> Or even just a new Azure account, the free included credits should be enough to have an SQL Server running for a while.

Oh, I didn't see that there is a 30 day free account in Azure... 
https://azure.microsoft.com/en-us/free/

I will test it!

**Comment by Mausino** [comment]
We are growing by numbers of users... and will fine if the security groups starts working in light version... #6657 [Security Groups - any fields for edit, detail or listview ?] 
will nice if will possible to assign the record in detailview, and 
will nice if will possible to search and show by SC in listview.

For me is Security Groups reason why bigger companies up 5+ employees must go to proprietorially software if want create functional HR structure in company
https://store.suitecrm.com/addons/securitysuite/pricing

I dont want replace the 3rd party sofware.. i want that SC will possible to use in fresh installation and you dont need to do custom changes that this core part of SuiteCRM you should use.

**Comment by Abuelodelanada** [comment]
Some issues with PR that I would like to nominate for this Sprint:

#7780 (PR #7783 )
#7781 (PR #7782 )

**Comment by Abuelodelanada** [comment]
One more issue with its PR:

#7810 (PR #7813)

**Comment by Abuelodelanada** [comment]
I here again suggesting a simple PR to add to this Sprint:

#7821 (PR #7822)

**Comment by timo12357** [comment]
iCal integration is critical for sales meeting and call planning while on the roead, I sync my phone calendar to SuiteCRM and this is a criticial issue. [#7691 ](github.com/salesagility/SuiteCRM/pull/7691)

Living in a Nordic country Scandinavian letters need to work in the calendar, too. There is a fix available for this, too: [#4423](github.com/salesagility/SuiteCRM/pull/4423)
