### ISSUE TITLE
Changing Field 'len' value via Vardefs - 'len' can only be increased.

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#773]
Placed the line: _$dictionary['AOS_Products_Quotes']['fields']['product_discount']['len']='26,9';_
In the location: _/custom/Extension/modules/AOS_Products_Quotes/Ext/Vardefs/product_discount.php_

This, correctly, Changes the current length for this field in the DB from _26,6_ to _26,9_

However, if I try to lower it with the line:
_$dictionary['AOS_Products_Quotes']['fields']['product_discount']['len']='26,7';_

The change is not detected and not executable after a Quick Repair & Rebuild

The same occurs when changing the 1st number:
Trying to change the length from _26,6_ to _35,6_ will work
But Trying to lower it from _35,6_ to _32,6_ will not be picked up. No Mismatch detected.

**Comment by ijdavie** [comment]
This is also related to issue #991

**Comment by Dillon-Brown** [comment]
I think this should be expected behaviour.
