### ISSUE TITLE
Catch ListView SubPanel query fail

### ISSUE THREAD

**Issue by zpangrsic** [salesagility/SuiteCRM#7735]
#### Issue

When a subpanel inside a modules DetailView fails its queries it does not show the other subpanels but reverts to showing that a failure was detected. 

> Database failure. Please refer to suitecrm.log for details.

#### Expected Behavior

Only show which subpanel failed its query and render all the other subpanels.

#### Actual Behavior

All subpanels do not render. And displays that an error occurred as a text.

#### Possible Fix

Doing a try catch finally on the SugarBean::get_union_related_list inside ListView.php -> processUnionBeans will fix this issue.

#### Steps to Reproduce

1. Create a custom subpanel or use an existing one
2. Try to do a modification on the subpanel definition so that it fails and throws an exception (for testing)
3. Go to the module that the subpanel exists and go to a record 
4. DetailView will not render the subpanels but instead show an error as a text

#### Context

The main problem i had with this is that when a subpanel failed for some reason the UI failed to render other subpanels and you had to clear the browser cookies and PHPSESSION to restore the subpanels to be then displayed.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 76.0.3809.100 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by zpangrsic** [comment]
[ListView subpanel change request zpangrsic/SuiteCRM fork](/zpangrsic/SuiteCRM/commit/7586b51d897b878b0c2df07ceb28b86dc1486ee7)

**Comment by zpangrsic** [comment]
#7737

**Comment by zpangrsic** [comment]
#7737 Reference to the pull request

**Comment by Mac-Rae** [comment]
I was unable to replicate this on the newest version of 7.10.x. Could you please provide an example of the modification you made that caused the error?

**Comment by zpangrsic** [comment]
Hi @Mac-Rae ,

In my case i use MSSQL and inside it i have views from different tables. We use a highly modified instance of SuiteCRM and custom modules that have a refference to the views in the database. Often it happens when in developing/production that we change a view and a user tries to load a module that contains a subpanel and causes the whole subpanels list inside the modules record to not be displayed. If i use the fix above it renders all other subpanels but if i try to access the broken subpanel it just renders inside it "database failure ..." which is fine. This also fixes the issue so that we dont have to clear the browsers cookies / cache which was a pain if an error in a subpanel occured.

This issue is probably more applicable to our use. If you deem this to not be applicable as an issue please close this.

Thank you.

**Comment by pgorod** [comment]
I think this is useful for everyone. Every once in a while some we have a regression where some query gets broken, and this could lead to a broken Accounts screen, for example. 
If instead of that, we could have just a broken Targets subpanel inside the Accounts screen (for example), the severity would be much lower.

I think what Mac was asking for was just a specific example of a  customization he could make to test this PR. I know that "any customization with a broken query" would do, but it's easier if he knows the exact steps and we are all looking at the same thing.

Thanks
