### ISSUE TITLE
Email Template selection in email module is not working for 7.11.16 in Edge/IE11

### ISSUE THREAD

**Issue by jr-clark** [salesagility/SuiteCRM#7738]
This is identical to issue  #7271, which was fixed, but that fix does not work in Edge or IE11.

Running a fresh install of :

Version 7.11.6
Sugar Version 6.5.25 (Build 344)

After selecting a template and hitting the OK button, nothing happens. No template data is loaded. The debug console in IE11/Edge breaks at line 1334/1335 EmailsComposeView.js with an error.

**Comment by Mac-Rae** [comment]
Confirmed in 7.11.8. Also not seen in Chrome

**Comment by pgorod** [comment]
@Dillon-Brown @Mac-Rae 	

A user [in the Forums says](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/22042-print-to-pdf-popup-window-template-chooser#88834) that 

> since my last post when we were still on 7.11.4
>
>We've upgraded to Version 7.11.8 and we're still having the same issue with the Popup window for PDF templates
>
>The issue was fixed for accounts module only - but not for quotes module, which is obviously where you print pdf's the most

I wonder if this is the same bug as listed in this Issue? It's about Templates selection. I searched briefly, but couldn't find which PR could have fixed this in the Accounts module. I guess that might be helpful...
