### ISSUE TITLE
Upload Directory not present in official Suitecrm Version 7.11.8 zip package

### ISSUE THREAD

**Issue by prbt2016** [salesagility/SuiteCRM#7745]
Hello,

I downloaded SuiteCRM 7.11.8 from official website from the following link :
https://suitecrm.com/files/162/SuiteCRM-7.11/465/SuiteCRM-7.11.8.zip

However, while manual installation I noticed that upload directory was not present. In earlier version i.e 7.11.7 it was present. Is the directory purposefully removed or is it a packaging issue?.
As while manual installation it does check for the 'upload' directory.

![test](https://user-images.githubusercontent.com/17871448/63634512-240fcf80-c675-11e9-8ba0-d9c14613b308.png)

Could you please look into this?

**Comment by samus-aran** [comment]
That is the installer package updated. Thanks for raising this.

**Comment by prbt2016** [comment]
Thanks a lot for updating.
