### ISSUE TITLE
Upgrade packages empty lato font files

### ISSUE THREAD

**Issue by lucas7793** [salesagility/SuiteCRM#7751]
Same as the issues #5915 and #7331, the lato font files in the 7.11.x to 7.11.8 upgrade packages are empty. This is also the case with (at least) the upgrade package from 7.10.x to 7.10.20 and 7.10.x to 7.11.8.
The one from 7.8.x to 7.11.8 does contain the correct font files.

According to #7331 it should be fixed, but apparently it's not the case.

#### Issue
Font files should have content

#### Expected Behavior
Font files are overwritten by empty font files

#### Actual Behavior
After running the upgrade wizard, the font files are overwritten by empty ones from the upgrade package.

#### Possible Fix
Upgrade file should not contain empty font files, or/and the upgrader should check the filesize before overwriting existing files.

#### Steps to Reproduce

1.  Download one of the upgrade packages mentioned above
2.  Do the upgrade
3. Clear cache
4. A different font will be used in the browser

#### Context
It has been an issue for every upgrade package on 7.11.x I used (maybe not all, but every one I downloaded). 

#### Your Environment

* SuiteCRM Version used: 7.11.7 -> 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 76.0.3809.100 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

**Comment by samus-aran** [comment]
That's the upgrade packages updated. Apologies on this being a frequent offender. I've identify this has a high priority to resolve in the Upgrade package scripts.
