### ISSUE TITLE
Disable Action menu has no effect on menus in subpanel

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#7758]
Although you disable "Show actions in menu" ( enable_action_menu ) actions will still be shown as menu in subpanel action menu.
The setting only affects the top menu, but it did affect the subpanel menu, too in 7.8.x

#### Expected Behavior
Subpanel action menu is shown as seperate button

#### Actual Behavior
Subpanel menu is shown as one dropdown action menu.

#### Steps to Reproduce
1. Go to "System Settings->Display actions within menus 
2. uncheck
3. Go to a module with an activity subpanel
4. See the action menu is a menu not separate buttons

#### Context
As our sales most time uses "New meeting" the action menu with "New Task" as default in the first place is not good. So the option or possibility to reorder would fix this.
Had no Problem with separating the buttons before updating to 7.11.x from 7.8.x

#### Your Environment

* SuiteCRM Version used: 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox or Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3, Apache
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Confirmed in 7.11.8

**Comment by dursuntosun** [comment]
After apply this patch, it looks like ;
![image](https://user-images.githubusercontent.com/22373035/67568232-4d5fe100-f734-11e9-90a8-5264e0d2c244.png)

**Comment by gunnicom** [comment]
@dursuntosun Maybe that is partly related to https://github.com/salesagility/SuiteCRM/issues/7759

**Comment by pgorod** [comment]
Probably related to this: #6533

There's an interesting in discussion in that PR, any way
