### ISSUE TITLE
Subpanel activity action button email shows twice

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#7759]
Additional setting:

$layout_defs['Accounts']['subpanel_setup']['activities']['flat'] = 1;

As a picture shows more than a thousand words. 

![grafik](https://user-images.githubusercontent.com/550251/63771164-e5794f80-c8d6-11e9-9441-b3122d175738.png)
![grafik](https://user-images.githubusercontent.com/550251/63771261-16f21b00-c8d7-11e9-85c7-aa2cf2430e57.png)

SuiteCRM Version: SuiteCRM 7.11.7:

**Comment by Harklink** [comment]
Could you give me the path to access the source code, so that i can try to correct this? :)

**Comment by Dillon-Brown** [comment]
Hi @Harklink, If I remember right this should be generated here:

[include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php](https://github.com/salesagility/SuiteCRM/blob/master/include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php)

**Comment by pgorod** [comment]
Please test PR #9559
