### ISSUE TITLE
CSS File Dawn/yui.css not found

### ISSUE THREAD

**Issue by greenlanegreb** [salesagility/SuiteCRM#7763]
Mon Aug 26 21:28:20 2019 [919][1][WARN] CSS File Dawn/yui.css not found

#### Issue
 This should not be appearing within the error log and I am concerned that it may cause further issues across the Suite CRM system and create additional workload. By ironing out errors generated, it provides a cast iron base to move forward with (to add to recommendations already provided to Ashley regarding end user involvement being at the core of the development work that Suite CRM undertakes. 

#### Expected Behavior
 Shouldn't be happening. 

#### Steps to Reproduce

1. By checking log with "warn status". 
2.
3.
4.

#### Context

SuiteCRM Version used: 7.11.8

Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.33 - 10.3.15-MariaDB-1 - Debian 10 Apache 2.4.28 (Debian)

Operating System and version (e.g Ubuntu 16.04): As Above.

This issue has not been resolved with a quick rebuild. 

Many thanks.

**Comment by greenlanegreb** [comment]
Good afternoon Cameron, is this something that can be fixed at my end for now and is there any chance it is causing the drop down menu editor to not display items correctly..i.e. my case status dom to have ended up on the left items as opposed to the right where it originally was (please see separate bug report). Thanks.

**Comment by horus68** [comment]
Duplicated here: https://github.com/salesagility/SuiteCRM/issues/7651
