### ISSUE TITLE
Undefined index: server_unique_key

### ISSUE THREAD

**Issue by greenlanegreb** [salesagility/SuiteCRM#7764]
Mon Aug 26 21:28:20 2019 [919][1][WARN] Undefined index: server_unique_key

#### Issue
This should not be appearing within the error log and I am concerned that it may cause further issues across the Suite CRM system and create additional workload. By ironing out errors generated, it provides a cast iron base to move forward with (to add to recommendations already provided to Ashley regarding end user involvement being at the core of the development work that Suite CRM undertakes. 

#### Expected Behavior
 Shouldn't be happening. 

#### Steps to Reproduce

1.Checking error.log on warn status. 
2.
3.
4.

#### Context

SuiteCRM Version used: 7.11.8

Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.33 - 10.3.15-MariaDB-1 - Debian 10 Apache 2.4.28 (Debian)

Operating System and version (e.g Ubuntu 16.04): As Above.

This issue has not been resolved with a quick rebuild. 

Many thanks.

**Comment by greenlanegreb** [comment]
Good Afternoon Cameron, 

Please would you be kind enough (or would someone else be kind enough to explain what this bug is about please. You can see from my end that i'm trying to clear my error.log so I can assess issues relating to my own network better but I don't understand the bug. I am concerned that this might somehow be linking in to the multiple imap issues issue I have raised here which seems to have been going on for over a year now. 

Thanks.

**Comment by greenlanegreb** [comment]
Hi, are there any updates on this? Thanks ever so much.

**Comment by Dillon-Brown** [comment]
Hi @greenlanegreb, this should be fixed by #8068. Thanks!

**Comment by greenlanegreb** [comment]
Thanks Dillon 😊 please would you be kind enough to point me In the direction of the steps to resolve these issues that you have replied on! Much appreciate
