### ISSUE TITLE
Quick repair&rebuild, execute DB-Query gives Elastic search error

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#7772]
Quick repair&rebuild, execute DB-Query gives Elastic search error although elasticsearch is disabled.

#### Expected Behavior
Quick repair when executing the SQL at the end should not throw any elasticsearch errors. Even more when elasticsearch is disabled anyway.

#### Actual Behavior
apache_error.log
`[Wed Aug 28 09:37:40.440937 2019] [proxy_fcgi:error] [pid 74097:tid 140341666113280] [client 212.aaa.bbb.ccc:51694] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: ElasticSearch in lib/Search/ElasticSearch/ElasticSearchClientBuilder.php on line 169PHP message: PHP Notice:  Undefined index: ElasticSearch in lib/Search/ElasticSearch/ElasticSearchClientBuilder.php on line 170PHP message: PHP Notice:  Undefined index: ElasticSearch in lib/Search/ElasticSearch/ElasticSearchClientBuilder.php on line 171', referer: https://xxxxxx.de/`

suitecrm.log
`Wed Aug 28 09:37:40 2019 [100151][1][FATAL] Exception handling in include/MVC/Controller/SugarController.php:400
Wed Aug 28 09:37:40 2019 [100151][1][FATAL] Exception in Controller: Failed to parse Host URL 'http://'
Wed Aug 28 09:37:40 2019 [100151][1][FATAL] backtrace:
#0 lib/Search/ElasticSearch/ElasticSearchClientBuilder.php(177): SuiteCRM\Search\ElasticSearch\ElasticSearchClientBuilder::sanitizeHost(Array)
#1 lib/Search/ElasticSearch/ElasticSearchClientBuilder.php(63): SuiteCRM\Search\ElasticSearch\ElasticSearchClientBuilder::loadFromSugarConfig()
#2 lib/Search/ElasticSearch/ElasticSearchIndexer.php(86): SuiteCRM\Search\ElasticSearch\ElasticSearchClientBuilder::getClient()
#3 lib/Search/ElasticSearch/ElasticSearchIndexer.php(576): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer->__construct()
#4 modules/Administration/repairDatabase.php(100): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::repairElasticsearchIndex()
#5 include/MVC/View/SugarView.php(834): include_once('/var/www/crmnem...')
#6 include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile('modules/Adminis...')
#7 include/MVC/View/SugarView.php(226): ViewClassic->display()
#8 include/MVC/Controller/SugarController.php(435): SugarView->process()
#9 include/MVC/Controller/SugarController.php(375): SugarController->processView()
#10 include/MVC/SugarApplication.php(113): SugarController->execute()
#11 index.php(52): SugarApplication->execute()
#12 {main}`
#### Possible Fix
Do not even call something related to elastic search when doing the db repair. Or when you do, then first check if it is enabled at all.

#### Steps to Reproduce
1. Disable elastic search, empty the config for elasticsearch
2. Have a database with a slightly different schema than defined in vardefs
3. Go to Quick repair&rebuild
4. When there is a SQL to execute at the end, press "execute"
5. Watch the error.log and suitecrm.log

#### Your Environment
* SuiteCRM Version used: SuiteCRM 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF,Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.2, PHP7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by holdusback** [comment]
Got exactly the same error. Cant even use ElasticSearch cause I dont have Java on my server

Last CRM version : 7.11.8 (But got this error in log since 2 or 3 version.)

**Comment by pgorod** [comment]
This line shouldn't run when Elastic Search isn't even enabled (so no wonder it's not configured):

https://github.com/salesagility/SuiteCRM/blob/master/modules/Administration/repairDatabase.php#L100

I've been seeing this in the Forums, and I fear it might be a little more serious than one would expect - a FATAL interrupting a QR&R. We don't know (well at least I didn't check) how much of the QR&R is still pending to be done when this crashes...

**Comment by nelem** [comment]
> I've been seeing this in the Forums, and I fear it might be a little more serious than one would expect - a FATAL interrupting a QR&R. We don't know (well at least I didn't check) how much of the QR&R is still pending to be done when this crashes...

It's serious. It causes upgrades and module installs to fail before they get to update the **upgrade_history** table. The upgrades and modules then sit there looking uninstalled.
