### ISSUE TITLE
ElasticSearch not indexing Accounts and Contacts

### ISSUE THREAD

**Issue by jrohde** [salesagility/SuiteCRM#7775]
When selecting the Accounts and/or Contacts modules to be indexed by the ElasticSearch indexer they are not picked up. When adding e.g. campaigns or something else (didn't test them all), the indexer does index them. 

Tested by manually running `vendor/bin/robo elastic:index 1` and checking the output (and doing a 'real' search as well). E.g. this is the ouput when just Accounts, Contacts & Campaigns are selected to be indexed:

```# vendor/bin/robo elastic:index 1
[=][17:09:34] Starting indexing procedures
[@][17:09:34] Indexing is performed using JsonSerializerDocumentifier
[@][17:09:34] Reading lock file cache/ElasticSearchIndexer.lock
[@][17:09:34] Last logged indexing performed on 2019-08-28 17:09:07 (27 seconds ago)
[@][17:09:34] A differential indexing will be performed
[?][17:09:34] Time metadata not found for Campaigns, performing full index for this module
[?][17:09:34] Skipping Campaigns because $beans was null. The table is probably empty
[@][17:09:34] Writing lock file to cache/ElasticSearchIndexer.lock
[@][17:09:34] No record has been indexed
[=][17:09:34] Indexing complete
```
Only Campaigns are indexed (or at least it's trying to, but i don't have one yet ;-))

Tested on SuiteCRM versions: 7.11.7 & 7.11.8

**Comment by larsschaps** [comment]
Hi @jrohde,
on my system i could see that the timezones of the timestamps are mixed up. In your output i see that last index was 27 seconds ago.

The modified timestamp in the db is UTC, the timestamp from the last index is (possibly local time). If your local timezone is +2 that means objects are indexed only after 2 hours. 

Can you verify?

**Comment by Dillon-Brown** [comment]
Unable to replicate on latest hotfix branch. Let me know if this is still something you can replicate and provide steps for and we can re-open and take another look.
