### ISSUE TITLE
Time Fields Customization

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7776]
I am trying to customize SuiteCRM Time Fields dropdown, the durrent dropdown options start from  15 minutes. Any other field has an option to edit contents of that Field under the Studio.

The option to add or edit more intervals in the Time Field does not exist.

I would like to have, for instance: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55 intervals which will be available for selection when a user sets a calendar task or logs a call.

This would enable to be log near accurate time frames.

Any advice on how I can achieve this?

**Comment by Mausino** [comment]
:) maybe you'll find something here #6790

**Comment by pgorod** [comment]
If this is a duplicate, then we should close here, do you agree?

**Comment by MyBlissIT** [comment]
> :) maybe you'll find something here #6790

Thank you, this was helpful
