### ISSUE TITLE
Project module language file: lines to translate or just mappings?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#779]
In modules/Project/language/en_us.lang.php
Are this lines to be translated or are they just mappings?
Lines ~ 132-135

```
    'LBL_START_WIDGET' => 'date_start',
    'LBL_FINISH_WIDGET' => 'date_finish',
    'LBL_PREDECESSORS_WIDGET' => 'predecessors_',

```

File: https://github.com/salesagility/SuiteCRM/blob/master/modules/Project/language/en_us.lang.php

**Comment by pribeiro42** [comment]
I guess they're only mappings. The spanish language file shipped with SuiteCRM also has those strings untranslated.

**Comment by mattlorimer** [comment]
doesn't look like there are used

**Comment by Pawes** [comment]
These strings have been deleted in #2664 so this can be closed.
