### ISSUE TITLE
Pencil present in Top Menu for users with non editing permission

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#7810]
#### Issue

An user that do not have permissions to Edit a record, see the pencil that give access to EditView.

Example:

![ContactEdit1](https://user-images.githubusercontent.com/939888/64266658-563dee80-cf0b-11e9-84fe-a22b8af323d5.png)

![ContactEdit2](https://user-images.githubusercontent.com/939888/64266680-605fed00-cf0b-11e9-9a48-4cf13f81383e.png)

#### Expected Behavior

The pencil should not be shown

#### Actual Behavior

SuiteCRM shows the pencil and when the user clicks on it goes to an ugly white page where can do nothing.

#### Possible Fix

We should control permissions to decide to show (or not) the pencil

#### Steps to Reproduce

1. Create a Contact with a non admin user.
2. Login with admin user
3. Create a new Role and let that role to edit only owned records
4. Assign another user (different from step 1) to the new Role
5. Login with that user.
6. Go to the DetailView of the Contact created in step 1.
7. Click on the pencil present in Top Menu
8. Say hello to the white page!

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3 / MySQL 8.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

**Comment by pgorod** [comment]
@Abuelodelanada I am getting a bunch of warnings form this

`[WARN] Smarty: sugar_check_access: missing 'record' parameter`

I get 6 on the Email compose screen, for example. I think that it has a field called `id` instead of `item_id` and so when the `record` is assigned, it doesn't get the value.
