### ISSUE TITLE
PSR Compliance

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#782]
It would be nice if SuiteCRM was [PSR-1](http://www.php-fig.org/psr/psr-1/) and [PSR-4](http://www.php-fig.org/psr/psr-4/) compliant. These standards provide a coding and autoloading standard which helps with creating and reusing reusable code. It also helps in using third party libraries which SuiteCRM could do better.

In the future other PSRs could also be considered (such as the logging interface and the caching interface).

**Comment by daniel-samson** [comment]
I agree. Plus we could create an autoloader that handles the custom code better. Removing the need to use require_once

**Comment by vjaro** [comment]
Why not use composer? This is basically what it is for.
I have been using composer together with suitecrm then packaging the codes that i continue to reuse for other project.

**Comment by JimMackin** [comment]
Composer would be a good idea for third party libraries, PSR-4 would simplify loading and including code from within SuiteCRM.

**Comment by jakubpas** [comment]
https://github.com/salesagility/SuiteCRM/pull/1114

- Introduce installation by composer - you can actually test it now:

```composer create-project jakubpas/suitecrm your_application_name```

- introduce PS-4 namespaces for SuiteCRM
- moving internal and abandoned classes to namespaced /src (currently SugarLogger and XTemplate)
- moving external  libraries to composer's /vendor (currenty Smarty as example)
- some minor refactoring

The" jakubpas/suitecrm" can be replaced by official SuiteCRM packagist location as soon as it will be set up.

**Comment by mattlorimer** [comment]
PSR Compliance has been added to the roadmap
