### ISSUE TITLE
7.11.7 version, Can't search custom field  in global search

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7830]
#### Issue

7.11.7 version, Can't search custom field  in global search
#### Expected Behavior

search spec value in  custom field by global search
#### Actual Behavior

Can't search customer filed.
#### Steps to Reproduce

1. add custom field "config_id_c" in quotes  module 
2. store some data in quote, and config_id_c has some spec value
3. search spec value in "config_id_c " by global search
4. search result , can't search 
5. how did config custom field into global search fileds?  

#### Your Environment

* SuiteCRM Version used: 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): 7.2 
* Operating System and version (e.g Ubuntu 16.04): Centos

**Comment by pgorod** [comment]
@cekowu when you say "customer filed" you mean "custom field", right?

**Comment by cekowu** [comment]
@pgorod yes ,it is "custom field"

**Comment by pavithra-selvam** [comment]
Hi @cekowu,
Did you enable Quotes module in search modules? if not please go to admin->Search Modules under Search Settings.

**Comment by cekowu** [comment]
@pavithra-selvam yes we enable Quotes module in search modules, but don't provide functions to add "custom field"

**Comment by pavithra-selvam** [comment]
Hi @cekowu ,
Can you please add this line " **'unified_search' => true,**" in the below mention file.
**File path:** modules/AOS_Quotes/vardefs.php 
paste the above mentioned line before "'**fields' => array(**" start line. I hope its working fine.

**Comment by cekowu** [comment]
@pavithra-selvam ok, i will test it, thanks!

**Comment by sxenny** [comment]
> Hi @cekowu ,
> Can you please add this line " **'unified_search' => true,**" in the below mention file.
> **File path:** modules/AOS_Quotes/vardefs.php
> paste the above mentioned line before "'**fields' => array(**" start line. I hope its working fine.

Hello
I have the same problem
I can enable my custom modules for Global Search by paste `'unified_search' => true,'` in modules/myModule/vardefs.php
But when I searching, the keywords are not searched, but all the items in the module are displayed.

This method has failed for SuiteCRM 7.11.15

Any tips how I can fix it now?

**Comment by cekowu** [comment]
> > Hi @cekowu ,
> > Can you please add this line " **'unified_search' => true,**" in the below mention file.
> > **File path:** modules/AOS_Quotes/vardefs.php
> > paste the above mentioned line before "'**fields' => array(**" start line. I hope its working fine.
> 
> Hello
> I have the same problem
> I can enable my custom modules for Global Search by paste `'unified_search' => true,'` in modules/myModule/vardefs.php
> But when I searching, the keywords are not searched, but all the items in the module are displayed.
> 
> This method has failed for SuiteCRM 7.11.15
> 
> Any tips how I can fix it now?
> 
> I've fixed
> so thank @suitecrm_developer from suitecrm forum
> He help me find fix
> Fixed if go to custom/modules/my_module/metadata/SearchFields.php
> and little change code to
> ‘name’ =>
> array (
> ’force_unifiedsearch’=>true,
> ‘query_type’ => ‘default’,
> ),

**Comment by cekowu** [comment]
> > Hi @cekowu ,
> > Can you please add this line " **'unified_search' => true,**" in the below mention file.
> > **File path:** modules/AOS_Quotes/vardefs.php
> > paste the above mentioned line before "'**fields' => array(**" start line. I hope its working fine.
> 
> Hello
> I have the same problem
> I can enable my custom modules for Global Search by paste `'unified_search' => true,'` in modules/myModule/vardefs.php
> But when I searching, the keywords are not searched, but all the items in the module are displayed.
> 
> This method has failed for SuiteCRM 7.11.15
> 
> Any tips how I can fix it now?
> 
> I've fixed
> so thank @suitecrm_developer from suitecrm forum
> He help me find fix
> Fixed if go to custom/modules/my_module/metadata/SearchFields.php
> and little change code to
> ‘name’ =>
> array (
> ’force_unifiedsearch’=>true,
> ‘query_type’ => ‘default’,
> ),

Thanks! Yes , it is ok now.
