### ISSUE TITLE
After Upgrade Calendar, Studio, Module Builder aren't longer shown - Error with Sugarcrm restrictions

### ISSUE THREAD

**Issue by Jonatanestam** [salesagility/SuiteCRM#7835]
#### Issue
After Upgrade SuiteCRM-Upgrade-7.11.x-to-7.11.8 (7.11.4 to 7.11.8 ) Calendar, Studio, Module Builder and some anothers aren't longer shown.

#### Expected Behavior
Show Calendar, Studio, Module Builder etc.

#### Actual Behavior
Calendar, Studio, Module Builder and some anothers aren't longer shown
Moment js is not defined, loading failed script (js).

#### Possible Fix
I edited .htaccess and comment these lines:
#RedirectMatch 403 (?i)/+vendor
#RedirectMatch 403 (?i)/+lib
#RedirectMatch 403 (?i)/+build
It works fine for me.
![1](https://user-images.githubusercontent.com/12118083/64548475-50258480-d2f4-11e9-8806-87a1f12732ae.png)
![2](https://user-images.githubusercontent.com/12118083/64548477-50be1b00-d2f4-11e9-90ae-66bd287b1871.png)
![3](https://user-images.githubusercontent.com/12118083/64548478-50be1b00-d2f4-11e9-9fa3-40a4d64d839d.png)

#### Context
After Upgrade SuiteCRM-Upgrade-7.11.x-to-7.11.8 (7.11.4 to 7.11.8 )

#### Your Environment

*SuiteCRM Version used: Version 7.11.8 Sugar Version 6.5.25 (Build 344)
*Browser name and version: Firefox, Chrome, Opera.
*Environment name and version: PHP v7.2.19
*Operating System and version: CentOS Linux release 7.6.1810.2.el7.centos.x86_64GNU/Linux
*Linux Kernel: 3.10.0-957.12.1.el7.x86_64
*CPU: Intel® Core™ i7 CPU 870 @ 2.93GHz
*RAM: MemTotal: 16163660 kB

**Comment by pgorod** [comment]
I think this is already fixed here: #7762

**Comment by Jonatanestam** [comment]
Yes,  it has already been fixed in #7762.
Thanks.
