### ISSUE TITLE
Integration with Sentry error tracking

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7849]
I wanted to propose integrating the CRM with support for reporting errors to a [Sentry](https://sentry.io/) instance.

I use Sentry for a personal project, and we used it for GitLab pretty extensively. GitLab comes with error reporting to Sentry included by default (though not enabled by default, obviously). Sentry's an open source error tracking product that you can either self-host or use as 'SaaS', it's written in Python and the devs are quite good from my experience interacting with them.

Essentially, what I'm proposing is having an "Error Tracking" page in the Admin section, that would let you activate error reporting to Sentry by providing the "Error Tracking" page with a Sentry URL, Sentry DSN, and Sentry Key. The CRM would ship with the Sentry PHP package, although it'd be disabled by default, and it would only report errors to a Sentry instance once it's been configured in the Admin panel. (or maybe the configuration should be done in `config.php`?)

The reason I want this is to enable us to track errors more easily, because right now we have to go through the php error logs manually to look for any errors that seem like they could be problematic. And once we do find an error in the logs, there's not much information to debug it with, and it lacks a lot of potentially important context (e.g. the page the user was on, the user that ran into the error, the # of users who have hit the error, the # of times the error has occurred, etc.).

Unfortunately, the latest iteration of the Sentry PHP client requires PHP 7.1 and higher, so we would have to use the 1.x client: https://docs.sentry.io/clients/php/

I don't know how long they intend to support the 1.x client, but hopefully it'll be a while. Eventually, we should obviously upgrade to 2.x.

cc: @Abuelodelanada I know you mentioned trying to integrate with Sentry before.

**Comment by Abuelodelanada** [comment]
Hi @connorshea 

I did it about 7/8 years ago. I think Sentry it's different now. Anyway it is a wonderful tool!
Having an Admin section to setup will be great. All the things you setup in Admin will be written in `config_override.php` so it is almost the same than using `config.php`

**Comment by Dillon-Brown** [comment]
Very cool tool, I definitely want to play around with this some more.


 ![sentry](https://user-images.githubusercontent.com/26431166/64993317-a6369100-d8cd-11e9-9229-da11f6c82fad.png)
