### ISSUE TITLE
Cannot Customize Dashboard

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7851]
Hi,

I am finding it impossible to customize the dashboard Dashlets view. When selecting "Action" the Add Dashlet option appears but when I select on the option, nothing happens.

If I select Add or Edit Tabs, I am able to do so.

Also, the drag and drop function is not working, instead the entire content is selected, almost as if I am trying to copy text.

**Comment by cameronblaikie** [comment]
We have found that this is no longer an issue in our latest 7.11 version and advise upgrading to this if you still find this an issue.

**Comment by MyBlissIT** [comment]
> We have found that this is no longer an issue in our latest 7.11 version and advise upgrading to this if you still find this an issue.

Hi, I am currently on Version 7.11.8 and I am experiencing this issue

**Comment by fornzix** [comment]
I'm on version 7.11.10 and experiencing the same issue.
