### ISSUE TITLE
Admin user can't add outgoing mail settings to other users

### ISSUE THREAD

**Issue by phil8900** [salesagility/SuiteCRM#7852]
#### Issue
While I am logged in as the admin user I can edit the email settings of other users, as expected. But when I tried adding outgoing email settings for a user, the settings were not added to the user profile, although they were saved and visible in the general outgoing mail settings overview. There is no error message, instead a confirmation dialog is shown, which adds to the confusion.

#### Expected Behavior
The outgoing mailserver settings for a user should be saved when they are added by the admin user.

#### Actual Behavior
The outgoing mailserver settings can only be added by the user himself, not by the admin user.

#### Steps to Reproduce

1. Log in as admin user
2. Create a new user
3. Open the email settings dialog and try to add outgoing mail settings

#### Context

I was trying to set up email settings in a way that users can send as themselves.

#### Your Environment

    SuiteCRM Version used: 7.11.8
    Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 69, Chrome 77
    Environment name and version (e.g. MySQL, PHP 7): PHP 7.3.9-1, MySQL 5.7.27
    Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04.3

**Comment by Mac-Rae** [comment]
Hey @phil8900 

Could you confirm that this is no longer an issue on your end and that I can close this issue?

**Comment by phil8900** [comment]
Hey,
I closed issue #7845, as this was a configuration issue on my end.

The issue that the admin user can't add outgoing mail settings to other users is still present and can be reproduced by following the steps I described above - it is not resolved yet, and therefore it should not be closed.

**Comment by samus-aran** [comment]
Setting as Duplicate and referenced to newer issue
