### ISSUE TITLE
Generate tel: links for phone numbers

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7876]
#### Issue
Phone fields in the CRM aren't rendered as `tel:` links, which they should be to allow users to easily call leads, accounts, etc.

<img width="548" alt="Screen Shot 2019-09-17 at 1 01 26 PM" src="https://user-images.githubusercontent.com/2977353/65071147-4979bb80-d94b-11e9-959a-6ebc6c2419ac.png">

#### Expected Behavior
The phone fields should be clickable `tel:` links.

#### Actual Behavior
The phone fields do not render as links.

#### Possible Fix
Fix the phone fields returning without links.

#### Steps to Reproduce
Note: This is reproducible on the demo instance
1. Go to a Lead, Account, or Contact (other modules probably have the same problem as well) that has a phone number.
2. Try to click the phone number to call it.
3. It does not work, because the phone number is not a `tel:` link, or a link at all.

#### Context
We have to have users install a 'telephone linker' extension for Chrome in order to make calls easily, which is pretty annoying. This should work out-of-the-box.

It seems like this commit was supposed to fix it, but I guess the sugar_phone function isn't used or something? https://github.com/salesagility/SuiteCRM/commit/02b7f9099b0ac8298067e5dfdb77ac5a90924043

#### Your Environment
* SuiteCRM Version used: 7.10.19, 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 69
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave 10.14.6

**Comment by connorshea** [comment]
Bizarrely, this line (and the similar one above it) try to add a phone class, but because it's a separate, duplicate `class` element it doesn't actually get included.

https://github.com/salesagility/SuiteCRM/blob/df18433e4bd429ecd754953a6354e38f37893efd/themes/SuiteP/include/DetailView/tab_panel_content.tpl#L124

If we fix it by moving the `{{if phone}}phone{{/if}}` stuff into the existing class declaration, the `phone` class does indeed end up being output, but it doesn't seem to change much of anything.

**Comment by connorshea** [comment]
I think we need to update [`TemplatePhone.php`](https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/modules/DynamicFields/templates/Fields/TemplatePhone.php) to be more like [`TemplateURL.php`](https://github.com/salesagility/SuiteCRM/blob/bff7aec3ea3958514e02747df4819f5d0369e306/modules/DynamicFields/templates/Fields/TemplateURL.php)

**Comment by connorshea** [comment]
Actually, I tried updating `include/SugarFields/Fields/Phone/DetailView.tpl` and it is indeed used, so we can fix this in one of two ways:
- Just remove the 'SkypeOut' config entirely, since I don't think it really has a purpose nowadays? We can just render the `tel:` link no matter what.
- Modify what's returned by the `else` branch in [`function.sugar_phone.php`](https://github.com/salesagility/SuiteCRM/blob/df18433e4bd429ecd754953a6354e38f37893efd/include/Smarty/plugins/function.sugar_phone.php) to have the link to `tel:`, since there isn't a good reason as far as I can tell not to return it as a link.

**Comment by pgorod** [comment]
@Mac-Rae This can be closed now, I believe

**Comment by pgorod** [comment]
@Mac-Rae This can be closed now, I believe
