### ISSUE TITLE
Menu ALL - Modules not listed if auto file deleted - Bug found

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#788]
Some modules on the "All" menu will not be visible if you delete the auto-generated file (as in maps modules)
  \custom\application\Ext\Language\en_us.lang.ext.php

You can only get them linked after you rebuild project!

This is one more Down vote on the system used for language cache on SuiteCRM

**Comment by samus-aran** [comment]
I'm turning this into a bug as I'm not quite sure of the issue or even suggestion.

I know it has been a long while @horus68 but if you could explain the issue again that would be much appreciated.

**Comment by horus68** [comment]
Closed. It seems solved now!
(using SuiteCRM 7.8.2 - apache 2.4.18 / PHP Version 7.0.11 / mysql 5.7.17 )
