### ISSUE TITLE
No 'Server response time' in SuiteP

### ISSUE THREAD

**Issue by CamoMacdonald** [salesagility/SuiteCRM#7882]
#### Issue

The "Server response time" that was present in the SuiteR Theme, in the footer, seems to not be present in SuiteP. This is used to help debug performance issues.

#### Expected Behavior

Server response time be included in the SuiteP theme

#### Actual Behavior

Server response time footer doesnt exist in the SuiteP theme

#### Steps to Reproduce

1.  Login to Suite, with SuiteR theme and scroll to the bottom
2.  View 'Server response time: xx.xx seconds. ' at the bottom left
3. Login to Suite, with SuiteP theme and scroll to the bottom
4. No Server response time

#### Context

Removal of this function makes debugging performance issues more challenging

#### Your Environment

* SuiteCRM Version used: Any with SuiteP
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 69
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3 Mariadb 10.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by connorshea** [comment]
There's actually a setting in the "System Settings" admin panel for whether this should be displayed, we should make sure it's respected :)

**Comment by Dillon-Brown** [comment]
Ah, really? I hadn't seen that one. Will re-label this as a bug.

**Comment by connorshea** [comment]
I assume that's what "Display server response times" is for, at least.
