### ISSUE TITLE
Elasticsearch Index runs out of memory on larger instances

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#7886]
#### Issue

I have some instances with somewhat large record counts ~10k Accounts, ~100k Contacts, etc. 
The webserver has 8GB Ram. Database is on separate server. 

I've been using the Robo command to attempt to index the instances. It fails after a few minutes. The cli simply says 'Killed'. There's no message in the SuiteLog and the `search_index.log` mirrors what's on the terminal. The search lock file is not created because the job doesn't get that far.
```
[=][18:48:56] Starting indexing procedures
[@][18:48:56] Indexing is performed using JsonSerializerDocumentifier
[@][18:48:56] Reading lock file cache/ElasticSearchIndexer.lock
[@][18:48:56] Lock file not found
[@][18:48:56] A full indexing will be performed
[@][18:48:56] Removed index '8d78fc156d3eed225d7724720bed55f3'  <-- see #7884 
[@][18:48:56] Loading mapping file /var/www/[the_crm_instance]/lib/Search/ElasticSearch/defaultParams.yml
[@][18:48:56] Created new index '8d78fc156d3eed225d7724720bed55f3'
[@][18:49:03] Indexing module Accounts...
[@][18:49:22] Indexed 7593/7593 Accounts
```

Finally, I discovered that the kernel was killing the process:
`kern.log`:
```
Sep 18 18:52:00 SuiteLAMP kernel: [113140.543060] Out of memory: Kill process 27254 (php) score 866 or sacrifice child
Sep 18 18:52:00 SuiteLAMP kernel: [113140.547187] Killed process 27254 (php) total-vm:8400152kB, anon-rss:7282848kB, file-rss:436kB
```

I believe that part of the problem is that Suite seems to be loading every record in a module into memory before sending to Elasticsearch:
`ElasticSearchIndexer.php`
```php
// line ~218:
try {
    $beanTime = Carbon::now()->toDateTimeString();
    $beans = $seed->get_full_list("", $where, false, $showDeleted);
} 
```

#### Expected Behavior

The Elasticsearch indexer should be able to process all records in a memory-safe way

#### Actual Behavior

The indexer runs out of memory and crashes in a non-restartable fashion

#### Possible Fix

It seems like the `ElasticSearchIndexer::indexModule` function should utilize some sort of pagination to chunk it's way through a module's records. 

#### Steps to Reproduce

1. Create a CRM instance with a large number of records ( over 100k)
2. Attempt to index with Elasticsearch

#### Context

I am trying to move my production customers to 7.11 with ES. Currently, I can't get them indexed, so cannot implement ES. 

#### Your Environment

* SuiteCRM Version used:7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chrome
* Environment name and version (e.g. MySQL, PHP 7):PHP 7.1, Mysql 5.6
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 16.04 on Digital Ocean droplets.

**Comment by pgorod** [comment]
Can you get a stack trace of that memory error? I'd like to see which command is actually causing it.

I guess instead of `get_full_list` we should be using a loop with `get_list` instead. This returns paginated results and allows memory to be re-used much more often:

https://docs.suitecrm.com/developer/working-with-beans/

**Comment by tsummerer** [comment]
@pgorod : I'm not familiar enough with this sort of error (where the kernel is actually deciding to kill the process) to know how to get a stack trace for it. Can you point me in the right direction? 

I'm curious about whether the failure would be the same if I triggered the reindex from cron vs robo - I've see the php error where it runs out of memory, but this is the first I've seen where the kernel decides to kill the process.

**Comment by pgorod** [comment]
There's a similar issue [in the Forums](https://suitecrm.com/suitecrm/forum/installation-upgrade-help/27438-full-elasticsearch-indexing) right now.

It includes a script to work around this.

Also includes some extra info on the error which comes from SugarBean constructor https://github.com/salesagility/SuiteCRM/blob/master/data/SugarBean.php#L481

**Comment by fschmtt** [comment]
Hey, I'm the author of mentioned forum post.

Depending on how much RAM PHP was provided the script exited in different files, so don't necessarily assume that https://github.com/salesagility/SuiteCRM/blob/master/data/SugarBean.php#L481 is the problem here, e. g.:

`root@afbf2ebc14d8:/bitnami/suitecrm# vendor/bin/robo -vvv elastic:index
[=][09:07:02] Starting indexing procedures
[@][09:07:02] Indexing is performed using JsonSerializerDocumentifier
[@][09:07:02] Reading lock file cache/ElasticSearchIndexer.lock
[@][09:07:02] Lock file not found
[@][09:07:02] A full indexing will be performed
[@][09:07:02] Removed index 'main'
[@][09:07:02] Loading mapping file /bitnami/suitecrm/lib/Search/ElasticSearch/defaultParams.yml
[@][09:07:02] Created new index 'main'
[@][09:09:56] Indexing module Accounts...
[@][09:24:18] Indexed 270076/270076 Accounts
PHP Fatal error:  Allowed memory size of 12884901888 bytes exhausted (tried to allocate 2853007200 bytes) in /bitnami/suitecrm/include/database/MysqliManager.php on line 139
ERROR: Allowed memory size of 12884901888 bytes exhausted (tried to allocate 2853007200 bytes)
in /bitnami/suitecrm/include/database/MysqliManager.php:139`

**Comment by pgorod** [comment]
I'm guessing it's inside `get_full_list`, it's trying to build the array with ALL the beans inside it, and as it allocates memory, it eventually fails. 
My guess is that if we had a full stack trace (maybe you could install XDebug?) it would always be somewhere inside that loop, though you are right, it won't fail exactly in the same place each time.

If any of you guys wants to refactor this section, try swapping that `get_full_list`

https://github.com/salesagility/SuiteCRM/blob/master/lib/Search/ElasticSearch/ElasticSearchIndexer.php#L216-L235

for a loop gathering each page with `get_list` instead, and send it batch by batch to Elastic indexer, I guess it should work. _If_ I'm seeing this correctly.

**Comment by pgorod** [comment]
@fschmtt did you get a chance to test @tsummerer 's PR #7901 on your data set?

**Comment by fschmtt** [comment]
Hey, sorry for not replying earlier, I was out of office last week.

I tested the indexing procedure locally with @tsummerer 's changes in a Docker Container.
Log output (shortened):

```root@bc9996f0c9d5:/bitnami/suitecrm# vendor/bin/robo elastic:index
[=][06:16:53] Starting indexing procedures
[@][06:16:53] Indexing is performed using JsonSerializerDocumentifier
[@][06:16:53] Reading lock file cache/ElasticSearchIndexer.lock
[@][06:16:53] Lock file not found
[@][06:16:53] A full indexing will be performed
[@][06:16:53] Removed index 'main'
[@][06:16:53] Loading mapping file /bitnami/suitecrm/lib/Search/ElasticSearch/defaultParams.yml
[@][06:16:53] Created new index 'main'
[@][06:16:53] Indexing module Accounts...
[@][06:16:54] Indexed 60
[@][06:16:54] Finished Accounts. Processed 60 Records
[@][06:16:54] Indexing module Contacts...
[@][06:16:59] Indexed 1000
[@][06:17:04] Indexed 1000
[@][06:17:08] Indexed 1000```

**Comment by tsummerer** [comment]
The core code has a `$batchSize` property and it's set to 1000. I implemented the same thing in my PR's code. 
Perhaps this value should be reduced?

If it works at, say, 250 then I could work on making the value configurable.

**Comment by fschmtt** [comment]
Tested again with the same data set and this time `memory_limit = 512`.  
`1048001` contacts were indexed, output (again shortened):
```bash
root@bc9996f0c9d5:/bitnami/suitecrm# vendor/bin/robo elastic:index
[=][07:33:08] Starting indexing procedures
[@][07:33:08] Indexing is performed using JsonSerializerDocumentifier
[@][07:33:08] Reading lock file cache/ElasticSearchIndexer.lock
[@][07:33:08] Lock file not found
[@][07:33:08] A full indexing will be performed
[@][07:33:08] Removed index 'main'
[@][07:33:08] Loading mapping file /bitnami/suitecrm/lib/Search/ElasticSearch/defaultParams.yml
[@][07:33:09] Created new index 'main'
[@][07:33:09] Indexing module Accounts...
[@][07:33:09] Indexed 60
[@][07:33:09] Finished Accounts. Processed 60 Records
[@][07:33:09] Indexing module Contacts...
...
[@][16:10:50] Indexed 1000
[@][16:11:52] Indexed 1000
[@][16:12:55] Indexed 1000
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 83886080 bytes) in /bitnami/suitecrm/include/utils/db_utils.php on line 135
ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 83886080 bytes)
in /bitnami/suitecrm/include/utils/db_utils.php:135

Over time I could watch the process slowly use more and more RAM (according to `htop` 0.1 % each few minutes) and the time between the indexing of batches increased from a few seconds to a minute.

**Comment by pgorod** [comment]
I wonder if the memory leak is in Elastic code.

Maybe (in a test system) someone could try upgrading Elastic to their latest version to see if it makes a difference. I'm not sure if it will raise any issues with SuiteCRM, this is uncharted territory...

**Comment by fschmtt** [comment]
As SuiteCRM only supports Elasticsearch 5.x, we'll have to use the 5.x branch of [elasticsearch/elasticsearch](https://github.com/elastic/elasticsearch-php).

```bash
  - Updating elasticsearch/elasticsearch (v5.4.0 => v5.5.0)```

I will try v5.5.0 with the same data set. My workaround script is using the same version without any memory issues. I'll keep you updated.

**Comment by pgorod** [comment]
There's a PR to update Elastic search to version 7, since 5.6 is soon EOL.
#7872

We'd have to wait and merge it only after we deprecate PHP5 for SuiteCRM, but that is also being considered for implementation quite soon: 
#7463

**Comment by pgorod** [comment]
Another test, if one of you can please try it...

Add a couple of 

```php
unset($params);
```
As done in the commit:
https://github.com/salesagility/SuiteCRM/compare/master...pgorod:patch-17

This is based on tips from the Elastic repo: https://github.com/elastic/elasticsearch-php/issues/204#issuecomment-85488074

We already have the `unset($responses)` inside the `sendBatch` function, but we don't have the `unset($params)` yet.

**Comment by fschmtt** [comment]
With v5.5.0 of [elasticsearch/elasticsearch](https://github.com/elastic/elasticsearch-php) still:
```bash
root@bc9996f0c9d5:/bitnami/suitecrm# vendor/bin/robo elastic:index
[=][10:34:31] Starting indexing procedures
[@][10:34:31] Indexing is performed using JsonSerializerDocumentifier
[@][10:34:31] Reading lock file cache/ElasticSearchIndexer.lock
[@][10:34:31] Lock file not found
[@][10:34:31] A full indexing will be performed
[@][10:34:31] Removed index 'main'
[@][10:34:31] Loading mapping file /bitnami/suitecrm/lib/Search/ElasticSearch/defaultParams.yml
[@][10:34:31] Created new index 'main'
[@][10:34:32] Indexing module Accounts...
[@][10:34:32] Indexed 60
[@][10:34:32] Finished Accounts. Processed 60 Records
[@][10:34:32] Indexing module Contacts...
[@][10:34:38] Indexed 1000
[@][10:34:43] Indexed 1000
[@][10:34:47] Indexed 1000
...
[@][18:56:37] Indexed 1000
[@][18:57:38] Indexed 1000
[@][18:58:40] Indexed 1000
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 83886080 bytes) in /bitnami/suitecrm/include/utils/db_utils.php on line 135
ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 83886080 bytes)
in /bitnami/suitecrm/include/utils/db_utils.php:135
```

I will test `unset($params)` next.

**Comment by fschmtt** [comment]
So, I tested both adding `unset($params['body']);` and `unset($params);` after `unset($responses);` in https://github.com/salesagility/SuiteCRM/blob/master/lib/Search/ElasticSearch/ElasticSearchIndexer.php#L516. I didn't wait for the memory error, but memory usage still increased as before.

I'm not sure but I think this was already implemented in https://github.com/salesagility/SuiteCRM/blob/master/lib/Search/ElasticSearch/ElasticSearchIndexer.php#L513
```php
// erase the old bulk request
$params = ['body' => []];
```

The memory leak seems to be somewhere else IMO.

**Comment by pgorod** [comment]
Ok, thanks for all this hard work testing. 

Maybe the best way is to move forward with the Elastic Search upgrade to the latest...

**Comment by Dillon-Brown** [comment]
Would love to... unfortunately even to just move up to 6.x would require us to drop everything below PHP 7.0.

**Comment by pgorod** [comment]
Still, as a test, this would tell us if the memory leak is in Elastic code or not. Their Issues page is full of memory leaks issues, I am afraid. 

On the other hand, if we conclude that even the newest Elastic still shows the problem, I would be more suspicious of some problem on our own side...

**Comment by fschmtt** [comment]
So, I did the following:
```bash
root@bc9996f0c9d5:/bitnami/suitecrm# composer show | grep elasticsearch
Do not run Composer as root/super user! See https://getcomposer.org/root for details
elasticsearch/elasticsearch         v7.3.0             PHP Client for Elasticsearch
```

```bash
root@bc9996f0c9d5:/bitnami/suitecrm# curl 10.0.204.15:9200
{
  "name" : "112102691ac8",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "nxj9U04gT-yMED3Jcwws2A",
  "version" : {
    "number" : "7.4.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "22e1767283e61a198cb4db791ea66e3f11ab9910",
    "build_date" : "2019-09-27T08:36:48.569419Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

```bash
root@bc9996f0c9d5:/bitnami/suitecrm# vendor/bin/robo elastic:index
[=][09:45:58] Starting indexing procedures
[@][09:45:58] Indexing is performed using JsonSerializerDocumentifier
[@][09:45:58] Reading lock file cache/ElasticSearchIndexer.lock
[@][09:45:58] Lock file not found
[@][09:45:58] A full indexing will be performed
[@][09:45:58] Removed index 'main'
[@][09:45:58] Loading mapping file /bitnami/suitecrm/lib/Search/ElasticSearch/defaultParams.yml
PHP Notice:  Undefined index: mappings in /bitnami/suitecrm/lib/Search/ElasticSearch/ElasticSearchIndexer.php on line 471
PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:702
Stack trace:
#0 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(702): Exception->__construct(Array, 500, Object(Elasticsearch\Common\Exceptions\ServerErrorResponseException))
#1 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(675): Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\\C...')
#2 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(643): Elasticsearch\Connections\Connection->tryDeserialize500Error(Array)
#3 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(313): Elasticsearch\Connections\Connection->process5xxError( in /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 702
ERROR: Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:702
Stack trace:
#0 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(702): Exception->__construct(Array, 500, Object(Elasticsearch\Common\Exceptions\ServerErrorResponseException))
#1 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(675): Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\\C...')
#2 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(643): Elasticsearch\Connections\Connection->tryDeserialize500Error(Array)
#3 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(313): Elasticsearch\Connections\Connection->process5xxError(
in /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:702
```

I utlized https://github.com/salesagility/SuiteCRM/pull/7872/files#diff-4a8ad7f6e2a08f28660519ca8914d5b7, but it seems to be broken. If you guys could help me get a correct `defaultMapping.yml`, I'll test with Elasticsearch 7.x.

**Comment by pgorod** [comment]
Maybe you can ask the author of that PR? He might have some experience with this, I don't.... :-(

But that stack trace shows it's handling a 500 error, maybe something about the web server configuration is causing trouble? Or something in `access.log` might give you clues?

**Comment by oc666** [comment]
It seems that the issue fixed but it get slow from long runs with large set:
> [@][23:04:29] Indexed 10000
> [@][23:04:42] Indexed 10000
> [@][23:04:54] Indexed 10000
> [@][23:05:07] Indexed 10000
> [@][23:05:20] Indexed 10000
> [@][23:05:33] Indexed 10000
> [@][23:05:46] Indexed 10000
> [@][23:05:59] Indexed 10000
> [@][23:06:11] Indexed 10000
> [@][23:06:25] Indexed 10000
> [@][23:06:38] Indexed 10000
> [@][23:06:51] Indexed 10000
> [@][23:07:05] Indexed 10000
> [@][23:07:18] Indexed 10000

It started at 8-10 per entry. It will be finished with 30 seconds per entry.
The instance set is around 5.5 millions records.
