### ISSUE TITLE
Manual import mail with mail (.msg) as attachment failed

### ISSUE THREAD

**Issue by polymed-op** [salesagility/SuiteCRM#7887]
#### Issue
I have a mail in a group mailbox that I want to import manually. So far this has worked well, but not with this one Mail. The special feature is that it has a mail as attachment.
If I want to import the mail, I only see this error message: Database error. 

If images or PDF or Office documents or tables are attached, it is no problem.
Only for mail attachments.

#### Expected Behavior
I expected that msg attachments would be imported or that a warning would be displayed that this does not work.

#### Actual Behavior
I see the Error in german language: "Datenbank Fehler. Bitte sehen Sie in der Datei suitecrm.log nach."
English: Database error. Please refer to the suitecrm.log file.

#### Steps to Reproduce
1. Include MS Exchange Group Mailbox
2. Receive mail with a mail as attachment. File extension .msg
3. Import mail
4. see the error 
Live access is not possible because dsa CRM is only designed for internal use.

#### Context
We have updated to the latest Version 7.11.8.
But after the Update, there is a new Problem:
The mail text of mails with attach msg is no longer visible. 
Since it is a little complicated, I have processed it in a PDF and attach it here.
Priority is medium

#### Your Environment
* SuiteCRM Version used: 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68.0.2 32-Bit
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1.1 (Xampp Version), MySQL Community Server 5.7.24 64bit
* Operating System and version (e.g Ubuntu 16.04): Windows server 2012 R2

Uploads:
[suitecrm.log](https://github.com/salesagility/SuiteCRM/files/3631264/suitecrm.log)
[Problem-Mail-import-20190917.pdf](https://github.com/salesagility/SuiteCRM/files/3631266/Problem-Mail-import-20190917.pdf)

**Comment by Mac-Rae** [comment]
Hi @polymed-op 

I have been unable to replicate this error, could you please provide screenshots of the error and if possible, the package (.msg) that you used to replicate the issue? If you would like to provide the email I would be happy to provide a secure method of sending it.

**Comment by polymed-op** [comment]
Oh, excuse me. I had been testing the old system all along instead of the new system.
The import works with the latest version, but the text is empty. But I will create this bug separately for the sake of clarity.
I close the bug.

**Comment by polymed-op** [comment]
I will create this bug separately for the sake of clarity.
