### ISSUE TITLE
Clean up the `tests/unit/phpunit/include/` directory

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7891]
> Actually, let's just make a note to clean up the `tests/unit/phpunit/include/` directory in a PR later.

_Originally posted by @connorshea in https://github.com/salesagility/SuiteCRM/pull/7807_

We should clean up whitespace and such in the tests in these files once #7807 is merged.

**Comment by cameronblaikie** [comment]
@Dillon-Brown not sure with this has came in as an issue, but this is related to https://github.com/salesagility/SuiteCRM/pull/7807

**Comment by Dillon-Brown** [comment]
@cameronblaikie Related yes but I think it should remain an open issue here until we actually get around to resolving it. Very easy to leave TODOs in PRs and then forget about them later.

**Comment by pgorod** [comment]
This can be closed now, right?
