### ISSUE TITLE
After Update to 7.11.8 REST API not available

### ISSUE THREAD

**Issue by bjoern86** [salesagility/SuiteCRM#7896]
After Update from 7.11.7 to 7.11.8 REST API not available (Opening e.g. /service/v4/rest.php
 ends up with HTTP Error 403) Files are available, chmod set to 755.

Used to work before the update. Same for the other API Versions (2, 2.1, 3, 3.1, 4, 4.1).

**Comment by bjoern86** [comment]
After renaming .htaccess to _.htaccess API is accessible again.
After rebuilding the .htaccess in "Admin > Repair > Rebuild .htaccess File" the API is not accessible again.

**Comment by pgorod** [comment]
Which version do you have, the one on the left or the one on the right?

**Comment by bjoern86** [comment]
.htaccess contains "RedirectMatch 403 /+Service"
after uncommenting this, the API is accessible again.

**Comment by bjoern86** [comment]
After merging the fix for #7761 htaccess issue everything works again after rebuilding the .htaccess in "Admin > Repair > Rebuild .htaccess File"

Thank you pgorod.
