### ISSUE TITLE
🎃 HacktoberFest 2019 - SuiteCRM style 🎃

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteCRM#7911]
# [HacktoberFest19](https://hacktoberfest.digitalocean.com/)

![Hacktoberfest_19_Events_730x90](https://user-images.githubusercontent.com/4041275/65369265-60195e80-dc3a-11e9-8395-d774717d85e7.png)

We are taking part in the [HacktoberFest2019](https://hacktoberfest.digitalocean.com/) celebrations advocating for Open Source participation and collaboration! 
This global event is an annual challenge aimed to encourage open source community member to perform valid pull requests to any open source project. As well as this they also set up that if you create 4 'valid' Pull Request within the month of October that you would be eligible to register for a limited edition T-shirt (the design this year looks fab!) :heart: 

All you need to do is:

1. Register your GitHub email account to HacktoberFest (https://hacktoberfest.digitalocean.com/)
2. Create 4 (valid) PRs to any Open Source Project within the month of October
3. See the small print:
*To qualify for the official limited edition Hacktoberfest shirt, you must register and make four pull requests between October 1-31. Pull requests can be to any public repo on GitHub, not just the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam, it will not be counted towards your participation for Hacktoberfest. If a maintainer reports behavior that’s not in line with the project’s code of conduct, you will be ineligible to participate.

We will be applying the label "Hacktoberfest" to issues that would be deemed ready/easy for new contributors to work on. **You** can help by identifying which issues you think would be easy to tackle or even ask them to be assigned to you in preparation for October.

Ontop of this fabulous event SuiteCRM will also be doing a 'month' long activity to encourage more PRs!

**Introducing .......**

# :candy: :ghost: :jack_o_lantern: Trick or Suite Thursdays! :jack_o_lantern: :ghost: :candy: 

This is where we will be hosting a virtual **8AM - 8PM BST/GMT**  Pull Request party on **each Thursday** within the month of October.  The product & community team will be ready to assess, review and merge in any valid PR into the core of SuiteCRM. This also applies to the SuiteDocs and SuitePortal repos!

### But wait there's more :scream: 

As well as this swat team powering through the PRs, each author of a successfully **merged PR** within the month of October will receive a **SuiteCRM contributor mug**!! Awesome! :coffee: 

Checkout the latest here in the new blog series - the [Community Diary](https://suitecrm.com/community-diary-sept-2019-edition/) (shameless plug I know haha)

P.S thanks to @jack7anderson7 for coming up with the name... :clap:

**Comment by samus-aran** [comment]
In no special order, and definitely not a complete list, these are some people who have made past contributions or participated in the Pull Request Party.

@horus68
@ApatheticCosmos
@mikebeck
@amariussi
@likhobory
@urdhvatech
@Mausino
@jakubpas
@JanSiero
@lazka
@jsamelko
@adriangibanelbtactic
@ChangezKhan
@Abuelodelanada
@hieuhoanghd
@LionelBino
@sanchezfauste
@adamjakab
@isleshocky77
@anhnhatuit
@ghermans
@eggsurplus
@javitoron
@sathishsengodan
@jobst
@bluquet
@connorshea
@gitbnw
@604media

**Comment by 604media** [comment]
Thank you for your update Ashley. :)

Kind regards,

Michael Loveless
President



*Process Flow Consulting Ltd.**office:* 778-832-3569 x102
*cell:* 604-679-9329

michael@processflow.ca
www.processflow.ca

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination,
publication, or copying of this e-mail is strictly prohibited. The sender
does not accept any responsibility for any loss, disruption or damage to
your data or computer system that may occur while using data contained in,
or transmitted with, this e-mail.

**Comment by Mac-Rae** [comment]
# :candy: :ghost: :jack_o_lantern: Trick or Suite Thursdays! :jack_o_lantern: :ghost: :candy: 

Go Go Go!! This Thursday is the first and the beginning of our five "Trick or Suite Thursdays" we're running in the run-up to Halloween. 

Between **8AM - 8PM BST** the product & community team will be ready to assess, review and merge in any valid PR into the core of SuiteCRM. This also applies to the SuiteDocs and SuitePortal repos! 

We have been applying the label "Hacktoberfest" to issues that would be deemed ready/easy for new contributors to work on. **You** can help by identifying which issues you think would be easy to tackle or even ask for them to be assigned to you if you would like to take them on!

Also, make sure you are signed up at the [HacktoberFest2019](https://hacktoberfest.digitalocean.com/) website to start your progress towards getting your hands on a limited-edition T-shirt

**Comment by grahambrown11** [comment]
Thank you to the **SalesAgility SuiteCRM** team for working overtime with our contributions for *Hacktoberfest* this month - I enjoyed seeing my contribution get merge in such a short time period.

I was wondering what is the process to claim the **SuiteCRM contributor mug**?

**Comment by samus-aran** [comment]
> Thank you to the **SalesAgility SuiteCRM** team for working overtime with our contributions for _Hacktoberfest_ this month - I enjoyed seeing my contribution get merge in such a short time period.
> 
> I was wondering what is the process to claim the **SuiteCRM contributor mug**?

Once the month is complete we will reach out to those eligible to discuss shipping :)

**Comment by Mac-Rae** [comment]
# :candy: :ghost: :jack_o_lantern: Trick or Suite Thursdays! :jack_o_lantern: :ghost: :candy: 

Go Go Go!! This Thursday is the last of our five "Trick or Suite Thursdays" we've run in the run-up to Halloween. 

Between **8AM - 8PM GMT** the product & community team will be ready to assess, review and merge in any valid PR into the core of SuiteCRM. This also applies to the SuiteDocs and SuitePortal repos! 

We have been applying the label "Hacktoberfest" to issues that would be deemed ready/easy for new contributors to work on. **You** can help by identifying which issues you think would be easy to tackle or even ask for them to be assigned to you if you would like to take them on yourself!

Also make sure you are signed up at the [HacktoberFest2019](https://hacktoberfest.digitalocean.com/) website to start your progress towards getting your hands on a limited edition T-shirt

For for information please see our discussion issue on GitHub - https://github.com/salesagility/SuiteCRM/issues/7911

**Comment by parammittal16** [comment]
Hi, hose who have successfully completed the contributions is here any form we have yo fill for claiming swag?

**Comment by horus68** [comment]
Installation screen on your language? Scary!
https://github.com/salesagility/SuiteCRM/pull/1697
