### ISSUE TITLE
Errors in User profile with French translation (quote)

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#7917]
browser console shows:
- SyntaxError: Unexpected identifier 'utilisateur'
- ReferenceError: Can't find variable: tinyConfig
Then, you can't edit Emails parameters

#### Possible Fix

See modules/Emails/EmailUI.php
change the way quotes are escaped:
$v = str_replace("'", "\'",$v);
=>
$v = str_replace("'", "\'",str_replace("\\'", "'", $v));

#### Steps to Reproduce

1. Install french translation
2. log in french
3. go to user profile
4. look at the browser console
5 click on Emails parameters

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any
* Environment name and version (e.g. MySQL, PHP 7): any
* Operating System and version (e.g Ubuntu 16.04): any

**Comment by Dillon-Brown** [comment]
Hi @QuickCRM, thanks for the PR! just to note for the future, if you want to post code in a GitHub issue you can encapsulate it with three backticks ``` like this:

```
<?php
echo 'Hello World!';
```

and it should keep it intact.

**Comment by pgorod** [comment]
It's gets even better if you add a language name, like this:
\`\`\`php
or 
\`\`\`bash

```php
<?php
function helloWorld() {
   echo 'Hello World!';
}
```
you get syntax highlighting.

**Comment by holdusback** [comment]
As a french dev & user so much error like this, for example in /index.php?module=Configurator&action=EditView

In the console "Uncaught SyntaxError: missing ) after argument list"

![image](https://user-images.githubusercontent.com/46958376/68188873-768d3680-ffaa-11e9-97b6-daf82d7bd42a.png)

![image](https://user-images.githubusercontent.com/46958376/68188901-886ed980-ffaa-11e9-9957-3db108ff4917.png)
