### ISSUE TITLE
AOS Settings: Initial Invoice Number

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#792]
It seems to be possible to enter an initial invoice number under Admin->AOS Settings that surpasses the allowed integer length defined in the database field "number" in table "aos_invoices" (11).

-> Entering an initial invoice number of more than 10 digits in the aos settings admin panel should produce an error.
Also it might be good to inform the user of this restriction in a help-box or something, to keep in mind, that this auto-populated number may never exceed 9'999'999'999 lest there be database errors. (if I understand correctly)

The error message I'm seeing in suitecrm.log:

> Out of range value for column 'number' at row 1

**Comment by pribeiro42** [comment]
The "11" in the field definition is not a limit on the integer range, its a display hint that mysql provides, allowing an application to check for a "maximum display width" or a "padding factor" or something like that... The column, being defined as INT, will allow values in the range -2147483648 to 2147483647. 
However, the UI should in fact warn the user...

**Comment by samus-aran** [comment]
Changing this to a bug as standard Int fields on EditView stop user entering in more than max size whereas AOS settings does not leading to the error.
