### ISSUE TITLE
Upgrade CLI fails on 7.11.8 upgrade package

### ISSUE THREAD

**Issue by CamoMacdonald** [salesagility/SuiteCRM#7920]
#### Issue

When using the upgrade pack from suitecrm.com through the CLI upgrader it returns multiple errors and then fails.

#### Expected Behavior

Upgrade should run smoothly 

#### Actual Behavior

```
PHP Warning:  include(/app/SuiteCRM-Upgrade-7.11.x-to-7.11.8.zip/manifest.php): failed to open stream: No such file or directory in /var/www/modules/UpgradeWizard/silentUpgrade_step2.php on line 315
PHP Warning:  include(): Failed opening '/app/SuiteCRM-Upgrade-7.11.x-to-7.11.8.zip/manifest.php' for inclusion (include_path='/var/www/include/..:.:/usr/share/php') in /var/www/modules/UpgradeWizard/silentUpgrade_step2.php on line 315
```

#### Steps to Reproduce

1. download the upgrade package
2. run the cli upgrade using that 
3.
4.

#### Context

Cannot successfully upgrade SuiteCRM through the CLI

#### Your Environment

* SuiteCRM Version used: 7.11.3 & 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP7.1 MariaDB 10.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by pgorod** [comment]
Is this one fixed with the two fixes to the Upgrader code? Mine and Craig's?

**Comment by Dillon-Brown** [comment]
@pgorod I believe there's actually a third fix done by Craig that still needs to go through internal testing and made into a PR.

**Comment by mattlorimer** [comment]
Fixed in current release
