### ISSUE TITLE
Sprint Planning (20)

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#7927]
Hello Everyone! :wave:

We are 1 week away from commencing our Sprint. So we would like to take this opportunity to ask for your nominated issues here in this thread so we can assess, refine and coordinate with ourselves (the Core Team) and the community contributors on the upcoming priorities.

If you are new to this sprint planning then essentially we are asking you, as the users, to post your issues (by referencing the GitHub hash/ID) that you would like to see being tackled. We, the Core Team, will review and select the achievable ones within the sprint and allocate them among ourselves. The others we may label them as Help Wanted which would make them up for grabs by our community code contributors. This process will help encourage ownership of these bugs and their bug fixes. [Find out more of the sprint concept here](https://docs.suitecrm.com/community/nominating-issues-in-sprint-planning) :point_left:

Sprints are every 2 weeks with the aim to deliver a release every 2 Sprints (monthly).

Just to re-iterate from previous posts, that the core team do have other tasks that may not be identified in the above sprints and these are usually from our own internal backlog i.e. improving the release process, CI/CD tools, security patches etc so that accounts for some ‘slack’ visible in the public sprints.

Look forward to your nominations! :writing_hand:

**Comment by connorshea** [comment]
Here are the PRs that I'd like to bring attention to:

- #7807 (State Checker removal) <= by far the most important to me.
- #7808 (`config.test.php`)
- #7771 (dotenv)
- #7900 (`aow_utils.php` notice fix) <= An easy one since I'm merciful
- #7879 (Phone fields as links) <= Relatively easy

**Comment by pgorod** [comment]
While I am not going to list specific Issues (Dillon can select them better than me), I would like to see a sustained focus on Email issues. I am also hoping the PR parties can be especially concerned with the robustness of the Email module, and then Campaigns. Thanks

**Comment by AlxGr-OS** [comment]
[ #7878](https://github.com/salesagility/SuiteCRM/issues/7878) to solve the issue with long dropdown lists in workflows' conditions  . A similar issue happens on reports.   It doesn't require to much work. Just change the lengthen of the field value.   I have manually changed it on my installation and it hasn't broke anything so far. Thanks.

**Comment by Abuelodelanada** [comment]
Here is the issues/PRs that I'd like to bring attention to:

- #7828 (PR: #7829 )

**Comment by Mausino** [comment]
I hope that somebody looks on Email Filtering RFC (Request for Comments) 🗣️ #7725 
Because nobody comments there the @samus-aran "roadmap" of Email Filtering

I suggesting.. that should we also filter in the future by API calls :)

**Comment by holdusback** [comment]
Here are some : 
https://github.com/salesagility/SuiteCRM/pull/7834 

https://github.com/salesagility/SuiteCRM/issues/7805

https://github.com/salesagility/SuiteCRM/issues/7704 ->

Maybe for this one see my topic on the forum :  https://suitecrm.com/suitecrm/forum/developer-help/27562-job-runs-too-frequently-throttled-to-protect-the-system

https://github.com/salesagility/SuiteCRM/issues/7676

https://github.com/salesagility/SuiteCRM/issues/18

**Comment by deuks** [comment]
#7842 - Potential Data Loss
#7531 - Lesser Priority
#7321 - I still get some issues here and there with the fix provided, but it works 95% and it's surprising to me that nothing has been implemented to production, this is an easy one.

**Comment by bjoern86** [comment]
Here some fore me important E-mail issues. #7546
#7526 Already in the backlog since some sprint releases.
