### ISSUE TITLE
Date Filters or start date filters are not working in reports if we add as a parameters

### ISSUE THREAD

**Issue by rahul1014** [salesagility/SuiteCRM#7934]
When i create the report and add date filters and tick the parameters in condition and select the particular dates and save the report it does show the reports but when i change the dates and update the report it show blank result and also selected dates from date fields disappear. Im using suitecrm version 7.10.9 and I have also tested this in latest version 7.11.8 has the same issue.

Please refer my post in suitecrm forum here is the link https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27300-date-filters-or-start-date-filters-are-not-working-in-reports-if-we-add-as-a-parameters

![afterchangingthedatesinfilter](https://user-images.githubusercontent.com/55878724/65764198-b0188980-e142-11e9-9cc9-1a8f2b8c7b35.png)
![Beforechangethedatesinfilter](https://user-images.githubusercontent.com/55878724/65764200-b0188980-e142-11e9-80b9-84e6807979d4.png)

**Comment by Mac-Rae** [comment]
Hi @rahul1014,

I believe this is the same as #7396

**Comment by rahul1014** [comment]
Hi,

Yes looks similar issue is reported in #7396

**Comment by Dillon-Brown** [comment]
Thanks @rahul1014, closing this as a duplicate. Let me know if the fix for #7396 doesn't resolve your issue and we can re-open this as a separate issue.

**Comment by rahul1014** [comment]
Thanks Dillon Brown, Its working now.
