### ISSUE TITLE
System Date format

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7937]
I have set the date format under "Locale" 23/12/2010 but on the actual system, date appears as 12/23/2010..

I am currently on Version 7.11.8, How can I resolve this? Happens mostly on Qoutation and Invoice

**Comment by pgorod** [comment]
I can't reproduce, works fine in my test system...

Maybe you should ask about this in the Forums first, it might be an issue with your configuration (`date.timezone` in php.ini, or something else...)

**Comment by MyBlissIT** [comment]
Thanks, I will ask there
