### ISSUE TITLE
System Upgrade failure

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7938]
I recently tried to upgrade from 7.11.7 to 7.11.8 and I get 500 error

![image](https://user-images.githubusercontent.com/34719141/65851175-4078e900-e352-11e9-855a-27a4262aae5a.png)

Every step of the upgrade process was checked well before this, this error took place after step 3, or after Pre-flight check...

my link is: https://www.myblisstech.com/crm

**Comment by pgorod** [comment]
What does your `php_errors.log` say about that FATAL? Maybe you just have to increase some resources in your `php.ini`....

memory_limit
max_upload_size
max_execution_time

**Comment by MyBlissIT** [comment]
> What does your `php_errors.log` say about that FATAL? Maybe you just have to increase some resources in your `php.ini`....
> 
> memory_limit
> max_upload_size
> max_execution_time

Here is my php.ini screenshot:
![image](https://user-images.githubusercontent.com/34719141/65942341-61623c80-e42d-11e9-92be-ca51a732b7b0.png)

How can I locate the php.errors.log? Because the issue persists...

**Comment by pgorod** [comment]
The web server log is defined in your `php.ini` also. Sometimes it's called `php_errors.log`, sometimes just `errors.log`, but you can give it any name you want.

Some errors SuiteCRM doesn't have a chance to catch, because they're PHP errors and crash the web server process. So the web server log is really essential.

**Comment by MyBlissIT** [comment]
This is my error message:

[30-Sep-2019 04:59:25 Etc/GMT] PHP Fatal error:  Uncaught Error: Class 'ComposerAutoloaderInit220bd2cf97737b02d38e9edb1643e4fb' not found in /home/myblisstech/public_html/crm/vendor/autoload.php:7
Stack trace:
#0 /home/myblisstech/public_html/crm/include/entryPoint.php(65): require_once()
#1 /home/myblisstech/public_html/crm/index.php(47): require_once('/home/myblisste...')
#2 {main}
  thrown in /home/myblisstech/public_html/crm/vendor/autoload.php on line 7

**Comment by pgorod** [comment]
Do you have `composer` installed? 

Can you run this from your root directory:

`composer install --no-dev`

I don't really know what's going wrong, but this might solve things, or provide you with further clues.

**Comment by MyBlissIT** [comment]
I have 2 composer files named:

1. composer.json - Permission: 0644
2. composer.lock - Permission: 0644

I managed to locate the Upgrade Wizard log and these are first 2 errors on the log:

Mon, 30 Sep 2019 04:59:20 +0000 [UpgradeWizard] - Starting file copy process...
Mon, 30 Sep 2019 04:59:21 +0000 [UpgradeWizard] - *** ERROR: could not copy file: /home/myblisstech/public_html/crm/vendor/zf1/zend-uri/composer.json
Mon, 30 Sep 2019 04:59:21 +0000 [UpgradeWizard] - *** ERROR: could not copy file: /home/myblisstech/public_html/crm/vendor/zf1/zend-uri/README.md


I also happen to come across this error log on SuiteCRM log (all logs via root directory)"

Mon Sep 30 04:38:48 2019 [2694365][1][FATAL] Unable to move move_uploaded_file to upload://SuiteCRM-Upgrade-7.11.x-to-7.11.8.zip You should try making the directory writable by the webserver

**Comment by Dillon-Brown** [comment]
Hi @MyBlissIT, those logs indicate that the problem is with your file permissions which caused the UpgradeWizard to fail when it couldn't copy the files over. I would suggest taking a look at the SuiteCRM docs, specifically the "Set the correct permissions on the SuiteCRM directory" (Assuming you are on Linux) found here:

https://docs.suitecrm.com/admin/installation-guide/downloading-installing/

**Comment by MyBlissIT** [comment]
Is there a way I can undo this upgrade?

I tried deleting upgrade files via cpanel but I still get the 500 error

**Comment by Dillon-Brown** [comment]
@MyBlissIT If the upgrade failed part way through there isn't really a way to "revert" it, you'd typically just go to a backup. I guess theoretically you could try running a ```composer install``` after setting the correct permissions and then running the upgrade, not sure if you'd be able to get to that point if it managed to copy over some files though.

**Comment by MyBlissIT** [comment]
Let me start afresh then, I do not even know how to run a composer install...

My main challenge will be how will be able to upgrade in the future.

**Comment by mattlorimer** [comment]
Please move this discussion to the forum if you are still having issues
