### ISSUE TITLE
TypeError: SUGAR.mySugar is undefined starting in 7.11.7

### ISSUE THREAD

**Issue by eggsurplus** [salesagility/SuiteCRM#7946]
On clean installs of 7.11.6 you could click on Actions->Add Dashlets from the home page and the dashlet pane would open up. 

In 7.11.7 and 7.11.8 clicking on Add Dashlets results in this error in the console:

TypeError: SUGAR.mySugar is undefined

The dashlet pane does not open. Other functionality such as removing a dashlet or any dashlet specific functionality that relies on javascript no longer functions.

#### Issue

TypeError: SUGAR.mySugar is undefined when trying to perform dashlet functions

**Comment by Mac-Rae** [comment]
Hi @eggsurplus,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.x or 7.11.x. If you believe this to be an issue still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:

**Comment by eggsurplus** [comment]
Have you tried the steps on either 7.11.7 or 7.11.8? Both fail on clean installs when trying to click on Add Dashlets.

**Comment by Lehnerr** [comment]
I have the same problem  in 7.11.8

**Comment by eggsurplus** [comment]
What updates beyond the steps in the original comment are needed for this issue? Happy to hop on a call to show those steps above.

**Comment by Dillon-Brown** [comment]
Thanks @eggsurplus, this looks like a problem with the upgrade packs removing a few files that they shouldn't while the JS repairs add them back while also adding a few extra useless files. I've gone ahead and fixed the JS repair here: #8185 and will include a fix for the file removal in the upgrade packs which we'll look to release asap. Thanks.

**Comment by nelem** [comment]
Still an issue on 7.11.12 (upgraded). "Rebuild JS Compressed Files" fixes it.
