### ISSUE TITLE
Custom Modules - Catchable fatal error: Argument 1 passed to Reminder::isDecline()

### ISSUE THREAD

**Issue by Anderlini** [salesagility/SuiteCRM#795]
SuiteCRM Version 7.4.3

When I use a new custom module i recive the error:

Catchable fatal error: Argument 1 passed to Reminder::isDecline() must be an instance of SugarBean, boolean given, called in C:\inetpub\wwwroot\suitecrm\modules\Reminders\Reminder.php on line 299 and defined in C:\inetpub\wwwroot\suitecrm\modules\Reminders\Reminder.php on line 374

**Comment by poviliukas** [comment]
I get this too anyone got any updates?

**Comment by mattlorimer** [comment]
Fixed in 7.5+
