### ISSUE TITLE
Cron Errors after upgrade to 7.10.20

### ISSUE THREAD

**Issue by iba-jsykes** [salesagility/SuiteCRM#7975]
#### Issue

After going from 7.8.x to 7.10.20, the following shows up when running cron.php, looks at least one of these is to be autogenerated.
#### Expected Behavior

No errors, lucene indexes run.
#### Actual Behavior
Lucene indexer task isn't running.

PHP Warning:  include(custom/metadata/note_servicedeskMetaData.php): failed to open stream: No such file or directory in C:\home\Apache24\htdocs\sugarcrm\custom\application\Ext\TableDictionary\tabledictionary.ext.php on line 116
PHP Warning:  include(): Failed opening 'custom/metadata/note_servicedeskMetaData.php' for inclusion (include_path='C:\home\Apache24\htdocs\sugarcrm\include/..;.;C:\php\pear') in C:\home\Apache24\htdocs\sugarcrm\custom\application\Ext\TableDictionary\tabledictionary.ext.php on line 116
PHP Warning:  include(custom/metadata/sd_servicedesk_tables.php): failed to open stream: No such file or directory in C:\home\Apache24\htdocs\sugarcrm\custom\application\Ext\TableDictionary\tabledictionary.ext.php on line 131
PHP Warning:  include(): Failed opening 'custom/metadata/sd_servicedesk_tables.php' for inclusion (include_path='C:\home\Apache24\htdocs\sugarcrm\include/..;.;C:\php\pear') in C:\home\Apache24\htdocs\sugarcrm\custom\application\Ext\TableDictionary\tabledictionary.ext.php on line 131
PHP

These are just warnings, so i'm a bit skeptical.

#### Steps to Reproduce

Upgrade from 7.8.x to 7.10.20

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7 , PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Windows Server 2019

**Comment by pgorod** [comment]
Have you tried a Quick Repair and Rebuild?

Also, I would prefer if you asked about this sort of thing in the Forums, not here on Github. If after some basic troubleshooting, and gathering more technical info, we find it's an issue with core code, we can then open the issue here for the developers to see.

But while we're still just fixing configurations etc we should really be in the Forums, id you don't mind. Thanks

https://suitecrm.com/suitecrm/forum/

**Comment by iba-jsykes** [comment]
I always start in the forums.    Ran repairs, rechecked file permissions, etc.  I'll keep browsing.  Thanks.

**Comment by pgorod** [comment]
But do you mean that you search the forums, or is there a thread in the forums where you're asking this? If so, please give me the link so I can go there and try to help :-)

**Comment by iba-jsykes** [comment]
I asked a question about ldap on the forums 4 weeks ago.  It is yet to be answered.  But I get it, you'd like to keep this to dev related topics.   It's cool.

**Comment by pgorod** [comment]
Yes, correct. I'm sorry about the LDAP question, I try to answer everything I know, but LDAP... I don't know. And I notice not many people seem to answer LDAP questions in the Forums, which is a shame...
