### ISSUE TITLE
Datetime field caching issue

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#7997]
#### Issue

When creating a custom module, or removing the custom code from the date create and date modified fields, it display the value as just a date and caches the value so every other detail view of that module shows the same date, until a rebuild is done

#### Expected Behavior

It should show as a date time field and not cache the value

#### Actual Behavior

Show as cached date value

#### Possible Fix

Fix the datetime template so it doesn't cache the value

#### Steps to Reproduce

1. remove the custom code from for example modules/Accounts/metadata/detailviewdefs.php on the date_entered field
2. Go to an account detail view and view the date created value, see that it is just a date
3. Go to another account detail view and see that it is the same value as the fist account you viewed, aka the wrong value for that record
4. run repair and see that it now show the correct date for the second record, if viewed first, but still just a date

#### Context

Medium

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): 7.2
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 18.04

**Comment by gunnicom** [comment]
Surprise.
https://github.com/salesagility/SuiteCRM/issues/723

**Comment by LeoZandvliet** [comment]
Archived emails still has this problem out of the box with the field `date_sent_received`.
The date time the email has been received is fetched once and cached until a repair is done.
