### ISSUE TITLE
API returns non-distinct values in Person modules

### ISSUE THREAD

**Issue by tsummerer** [salesagility/SuiteCRM#8001]
#### Issue

(EDIT: The following applies to Contacts and Leads as well)

The `/module/Users` endpoint returns nonsense since 7.11.4.

Instead of returning one record for each User, it returns one record for each user's calls and meetings. 
So if admin has 10 calls and 10 meetings, there are at least 20 admin user records in the results. 

This makes it nearly impossible to get a list of CRM Users. 

In a vanilla instance with demo data, there are 2,125 User records returned even though there are only 7 users. 

The problem was introduced by #7147

The root cause seems to be the `c_accept_status_fields` and `m_accept_status_fields` fields. These cause a `LEFT JOIN` to be added to the query which sends everything into chaos. 

#### Expected Behavior

The Users api endpoint returns one record for each user

#### Actual Behavior

The Users api endpoint returns multiple copies of each user (if they are invitees on any Meetings/Calls). The pagination is completely off and it's nearly impossible to get a list of active users on an instance. 
#### Possible Fix

I'm not completely sure. A quick bandaid would be to figure out how to turn the `singleSelect` off for the Users module. 

##### Scenario 1: Fresh Instance
(Assuming less than 100 users)

1. Spin up a fresh instance (no dummy data) and configure the API. 
2. Do a `GET` to `/Api/V8/module/Users?page[size]=100`
3. You should receive a record for each User and the `meta.records-on-this-page` should equal your user count (assuming you have less than 100 users)
4. Log in to the UI and create **2** Meetings. Your user should be one of the invitees on each.
5. Do a `GET` to `/Api/V8/module/Users?page[size]=100` 

Expected : same results as step 3.
Actual : There will be n+1 results. The User with 2 meetings will be returned twice.

##### Scenario 2: Instance with Dummy Data

1. Set up the instance and configure API
2. Do a `GET` to `/Api/V8/module/Users?page[size]=100`

Expected : 7 results
Actual : 100 results - mostly duplicates. 

#### Context

I am trying to get a list of Active Users.

i think that this is high priority because this is an important and common endpoint. 

#### Your Environment

* SuiteCRM Version used: 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): LAMP
* Operating System and version (e.g Ubuntu 16.04): LAMP

**Comment by tsummerer** [comment]
I may be able to work on a PR to address this, but I'd like some input from the maintainers about how to approach it. 

The pain point is that the `Sugarbean::create_new_list_query` function doesn't intrinsically return unique results - It's perfectly happy to create LEFT JOINS. 

It has a parameter, `$join_type` which _could_ let us override that - we could pass `'INNER JOIN'` and that would force all joins to be inner. I haven't tested it.
```php
// Sugarbean::create_new_list_query
...
if (empty($join_type)) {
    $params['join_type'] = ' LEFT JOIN ';
} else {
    $params['join_type'] = $join_type;
}
...
$join = $this->$linkField->getJoin($params, true);
```
[reference](https://github.com/salesagility/SuiteCRM/blob/v7.11.8/data/SugarBean.php#L3768)

We don't see it in the wild very often because we usually work with the `Sugarbean::get_list` function which hardcodes that parameter to blank:
```php
// Sugarbean::get_list
...
$query = $this->create_new_list_query(
            $order_by,
            $where,
            $select_fields,
            array(),
            $show_deleted,
            '',
            false,
            null,
            $singleSelect
        );
```
[reference](https://github.com/salesagility/SuiteCRM/blob/v7.11.8/data/SugarBean.php#L3462)

So **option 1** would be to edit or replicate `get_list` so that we could pass a `$join_type` parameter. (I don't like this option because typically we don't mess with Sugarbean functions)(although.....they sure could use some TLC)

A second option would be to pass the field list explicitly. `create_new_list_query` will use the `field_defs` unless you pass a list to the `$filter` parameter. You can pass an array of field names or an associative array of vardefs. 
So we could pass a list to these modules which would not include these bad relate fields. 

This could put the responsibility back in the API's code. Some of the groundwork is already laid - `BeanListRequest` is ready to accept fields. 
```php
// BeanListRequest.php
/**
 * @param array $fields
 *
 * @return BeanListRequest
 */
public function fields(array $fields)
{
    $this->fields = $fields;

    return $this;
}

/**
 * @return BeanListResponse
 */
public function fetch()
{
    return new BeanListResponse($this->bean->get_list(
        $this->orderBy,
        $this->where,
        $this->offset,
        $this->limit,
        $this->max,
        $this->deleted,
        $this->singleSelect,
        $this->fields
    ));
}
```
So in this scenario, I could see us doing something like, pulling the list of field_defs from a bean, stripping out the blacklisted, and then passing the good fields to the `BeanListRequest` which passes it on to Sugarbean's `get_list`.

I'd like opinions on whether this sounds like the right track and which classes might take responsibility for this - should `BeanListRequest` do it upon instantiation? Or would this fall under `BeanManager` or even the `ModuleService`? How and where should I store the blacklist?

**Comment by Jason-Dang** [comment]
Hey @tsummerer 

Thanks for raising this issue and for providing useful detail, it was beneficial in replicating the issue and determining a solution. :+1:

I opted for setting a default fields array as I found that's what it does in the core methods when not fields list is provided. From there it was just a matter of filtering out fields with `link_type` of `relationship_info`.
