### ISSUE TITLE
Upgrade Smarty to 3.x

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#8002]
So now that we've [moved Smarty to Composer](https://github.com/salesagility/SuiteCRM/pull/7591), the next step will be to upgrade it. It's going to cause some breakage, so it'll have to happen in `develop`.

It turns out Smarty 3 came out in November 2010 :')

Here's the 'overview' of Smarty 3's changes: https://www.smarty.net/v3_overview

It doesn't seem like _too_ bad of an upgrade, but it'll definitely not be backward compatible unless we really bend over backwards.

I've created a Gist with the backwards compatibility notes because the official source of this file now 404s. https://gist.github.com/connorshea/a05432d82e0f008c477b48e000d6c677

The biggest problem will be the lack of tests for our Smarty templates, but it's either that or we keep running an insecure piece of 9-year-old software. And removing/replacing Smarty entirely isn't realistic currently.

**Comment by Dillon-Brown** [comment]
Smarty 2 BC notes: https://github.com/smarty-php/smarty/blob/master/SMARTY_2_BC_NOTES.txt

**Comment by connorshea** [comment]
There are a handful of uses of `{php}` we should perhaps replace, but 🤷‍♂ we can just re-enable `{php}` tags I guess.

However, we'd need to use whatever SmartyBC is to get `{php}` tags in Smarty 3.1.x: https://www.smarty.net/docs/en/bc.tpl

**Comment by connorshea** [comment]
From the 3.1 notes:

```
Relative Paths in Templates (File-Resource)

As of Smarty 3.1 {include file="../foo.tpl"} and {include
file="./foo.tpl"} will resolve relative to the template they're in.
Relative paths are available with {include file="..."} and
{extends file="..."}. As $smarty->fetch('../foo.tpl') and
$smarty->fetch('./foo.tpl') cannot be relative to a template, an
exception is thrown.
```

O.o

**Comment by mattlorimer** [comment]
There are no plans to Upgrade Smarty to 3.x, we plan to move away from smarty starting with SuiteCRM 8, but thanks for the suggestion

**Comment by adrianacramirez** [comment]
Hola alguien sabe o tiene una guía de como actualizar Smarty 2.x a una versión mas nueva. Por favor
