### ISSUE TITLE
Update screen requires an update!

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#8014]
#### Issue

This is a challenge to those who can code:
Can someone create a better update screen for SuiteCRM?

#### Expected Behavior

Space for details and visually attractive!

#### Actual Behavior

So little space in use...
![2019-10-09 16_42_55-SuiteCRM7](https://user-images.githubusercontent.com/3055443/66497418-5c982b00-eab4-11e9-8257-2a1b029084cf.png)

**Comment by Mac-Rae** [comment]
Hi @horus68,
I agree, updating the upgrade screen to provide more information would be of use. I think a full overhaul of the upgrader is a must at some point as there are very little logging and suitecrm based methods of recovery.

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
