### ISSUE TITLE
Dashlet URL length

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#805]
When creating a Web-Dashlet and inserting an URL you are allowed to insert long URLs (tested with 2111 characters).

![bildschirmfoto 2015-12-21 um 13 51 18](https://cloud.githubusercontent.com/assets/15199551/11931209/87c10290-a7ea-11e5-9cfe-523a96904394.png)

Issue: 

![bildschirmfoto 2015-12-21 um 13 52 21](https://cloud.githubusercontent.com/assets/15199551/11931215/9387fa66-a7ea-11e5-98ab-230a87fcae44.png)

When you edit an existing Dashlet and are trying to change the URL, the input field is capped to 255 characters.

Tested on a clean install, version Version 7.4.1

**Comment by paulgodley** [comment]
The maxlength value appears to be set in modules/Home/Dashlets/iFrameDashlet/configure.tpl to 255.
