### ISSUE TITLE
PHP 7.4 Deprecations/Changes

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#8057]
This issue is meant to track all the deprecation warnings in SuiteCRM when running on PHP 7.4.

Notable deprecations:

- `implode()` now emits a deprecation warning when using it with the arguments in reverse order. use `implode($glue, $parts)` instead of `implode($parts, $glue)`.
- Accessing array values using curly braces is deprecated. e.g. `$array[0]` is good and `$array{0}` is bad.
   - I think all of these have been fixed in hotfix-7.10.x now, except for the uses that are in vendored libraries. We can fix those too if we want, but I didn't because I don't like messing with vendored code.
- The `get_magic_quotes_gpc()` and `get_magic_quotes_runtime()` functions are deprecated. They always return `FALSE` (and have since 5.3, I think? We can pretty remove any uses of these two in conditionals since they always return false).
- Nested ternary operators without explicit parentheses
  - [Explanation](https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.nested-ternary)

See these PRs for more info: #7987, #7976, and #8000.

A lot of the deprecated code comes from vendored dependencies, which is a problem since they're not trivial to upgrade. Thankfully, a lot of them have been moved to Composer in `develop`. We might want to backport those changes.

Some useful resources:

- https://stitcher.io/blog/new-in-php-74
- https://www.php.net/manual/en/migration74.php
- https://www.php.net/manual/en/migration74.deprecated.php

**Comment by connorshea** [comment]
Also I guess it's worth mentioning these two uses of `each()`, which was deprecated in 7.2:

- https://github.com/salesagility/SuiteCRM/blob/d9f5d17197c91de9ac37c247180888fde1f0b75c/modules/ModuleBuilder/views/view.relationship.php#L143
- https://github.com/salesagility/SuiteCRM/blob/d9f5d17197c91de9ac37c247180888fde1f0b75c/modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php#L440

**Comment by connorshea** [comment]
Here are some other deprecation notices from #7987:

```
Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /home/travis/build/salesagility/SuiteCRM/modules/InboundEmail/InboundEmail.php on line 1817

Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/travis/build/salesagility/SuiteCRM/modules/InboundEmail/InboundEmail.php on line 4366

Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /home/travis/build/salesagility/SuiteCRM/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php on line 404
```

**Comment by connorshea** [comment]
@Dillon-Brown I appreciate the enthusiasm, but this is not resolved yet ;)

**Comment by pgorod** [comment]
What is the status on this one, is it complete already?

**Comment by connorshea** [comment]
Not yet, there are still deprecation fixes that need to be backported and the tests still don't pass on 7.4.

**Comment by cperrot** [comment]
NOTICE: [8] Trying to access array offset on value of type bool on line 504 in file xxxxxxx/modules/Import/Importer.php

Still some PHP 7.4 issues with SuiteCRM version 7.11.15

**Comment by ahangarha** [comment]
Long time has passed since last update. Is there any prioritization regarding this issue?

**Comment by cperrot** [comment]
Yes we are talking about PHP 8 and we are still battling PHP 7.4 issues.

**Comment by mattlorimer** [comment]
Most issue highlighted here and we are aware of have been already been addressed. SuiteCRM does not yet officially support PHP 8 , but the latest releases should be for the most part compatible the only know issue is PDF generation, which is an area we hoping to address in 7.12.

If you still have any specific PHP 7.4 issue please open  a specific issue.
