### ISSUE TITLE
function isOwner() in SugarBean.php is not checking permissions ok 

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#8063]
#### Issue

Investigating why an user with "owner permissions" in 'Notes' module could not enter the DetailView of a record that was created by him, I found that we have a problem with the method [`isOwner()` in SugarBean.php](https://github.com/salesagility/SuiteCRM/blob/master/data/SugarBean.php#L1673)

The `isOwner()` method is [checking: `isset($this->assigned_user_id)`](https://github.com/salesagility/SuiteCRM/blob/master/data/SugarBean.php#L1685)

```php
        } elseif (isset($this->assigned_user_id)) {
            if ($this->assigned_user_id == $user_id) {
                return true;
            }
            return false;
        }
```

But if `$this->assigned_user_id` is `''` the function [`isset`](https://www.php.net/isset) will return true, so the execution will enter into the `elseif` and will check `$this->assigned_user_id == $user_id` and in other words will check something like this: `'' == '7cb40869-3ca6-7c88-006c-5da61ac6dc6e'` which is `false`.

This behavior prevents the execution from reaching the next check that will return `true` because the record was created by the user, so `$this->created_by == $user_id` is `true`

```php
        //other wise if there is a created_by that is the owner
        if (isset($this->created_by) && $this->created_by == $user_id) {
            return true;
        }
``` 

#### Expected Behavior

`isOwner()` checks permissions in a good way ;-)

#### Actual Behavior

A user that creates a 'Note' cannot go to the DetailView of that record.
The `isOwner()` method is not checking permissions in a bad way.

#### Possible Fix

We should use [`!empty()`](https://www.php.net/empty#refsect1-function.empty-description) instead of [`isset()`](https://www.php.net/isset)

#### Steps to Reproduce

1. Create and Role and assign an user to this Role.
2. Set the followings permissions to the module Notes for this Role:

```
access: 89
delete: -99
edit: 75
export: -99
import: -99
list: 75
view: 75
```
3. Login with this user
4. Create a Note
5. Try to go to the DetailView.

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Environment name and version (e.g. MySQL, PHP 7): MySQL 8.0.x / PHP 7.3.x

**Comment by Jorilx** [comment]
The fix works for me, thanks!
