### ISSUE TITLE
7.11.8 Report Paramter not working

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#8070]
#### Issue

I've created a report with a condition(modification Time) as parameter. When I run the report condition works fine. 
![grafik](https://user-images.githubusercontent.com/16813374/66921444-7fcb5900-f025-11e9-9a00-527890ecb40f.png)

As soon I select a different date and click on Update. 
![grafik](https://user-images.githubusercontent.com/16813374/66921523-b43f1500-f025-11e9-831a-ab42749351cc.png)

After Update the filter is cleared and all entries get displayed:
![grafik](https://user-images.githubusercontent.com/16813374/66921593-d6389780-f025-11e9-8c4b-82f14cb75407.png)

#### Expected Behavior

Filter should be get applied.
#### Steps to Reproduce

1. create report with  modification time filed as condition and as parameter 
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actulal  Firefox
* Environment name and version (e.g. MySQL, PHP 7): 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubunto 16.04

**Comment by pavithra-selvam** [comment]
Hi
Yes I'm also facing this issue.

**Comment by LeoZandvliet** [comment]
In my experience the only accepted date format in the parameter field is the database format `yyyy-mm-dd`. After saving the displayed value gets scrambled by some viewing mechanism. My workaround: remove those conditions as parameter and edit the report each time you want to create an different export (in my case I have to keep using the `yyyy-mm-dd` format).

**Comment by pavithra-selvam** [comment]
Hi @Lehnerr, 
I found solution for this, myself its working fine. Can you please check and use it.
Version: 7.11.8
File Path: modules/AOR_Reports/AOR_Report.js
Line No:107
Add this below line 
`if($('#aor_conditions_value' + ln + '_date').hasClass('datetimecombo_date')) {
            fieldInput = $('#aor_conditions_value' + ln + '_date').val()+" "+$('#aor_conditions_value' + ln + '_hours').val()+":"+$('#aor_conditions_value' + ln + '_minutes').val();
        }` 
**like this**
`else {
        if($('#aor_conditions_value' + ln + '_date').hasClass('datetimecombo_date')) {
            fieldInput = $('#aor_conditions_value' + ln + '_date').val()+" "+$('#aor_conditions_value' + ln + '_hours').val()+":"+$('#aor_conditions_value' + ln + '_minutes').val();
        }
        else {
          fieldInput = $("#aor_conditions_value\\[" + ln + "\\]").val();
        }        
    }`

**Comment by gunnicom** [comment]
@LeoZandvliet I thought this problem was fixed, but would not be surprised if it is still there https://github.com/salesagility/SuiteCRM/issues/1624

**Comment by Dillon-Brown** [comment]
@gunnicom Yeah I remember this being fixed a few times as well.... It would be good to get some acceptance testing for this.

**Comment by Lehnerr** [comment]
Hi. @pavithra-selvam 
The modification helps. It works now with DATE/Time paramter.
Would be great to get this in the next release.
thx

**Comment by Lehnerr** [comment]
A further problem occurs with parameter now . I've selected a text field or a relate field the values get cleared when I klick update.

**Comment by pavithra-selvam** [comment]
> A further problem occurs with parameter now . I've selected a text field or a relate field the values get cleared when I klick update.

Hi @Lehnerr ,
I'm not able to reproduce, Can you please share screen shot for references. 
Which version you are tested?

**Comment by Lehnerr** [comment]
It' solved, i forgott the last else statement
THX.

**Comment by Mac-Rae** [comment]
Appears to be resolved
