### ISSUE TITLE
7.11.8 Modules with TinyMCE are not working

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#8072]
#### Issue

After Upgrading to 7.8.11 We are not able to edit email templates or Markteing Emails or PDF -Templates with TinyMCE. 

#### Expected Behavior

Should work
#### Actual Behavior

Cannot edit the items when using tinyMCE
#### Steps to Reproduce

1.
2.
3.
4.

#### Context

It is a very serious Problem.

#### Your Environment

* SuiteCRM Version used: 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actual firefox
* Environment name and version (e.g. MySQL, PHP 7): php 7.0
* Operating System and version (e.g Ubuntu 16.04): 16.04

**Comment by Dillon-Brown** [comment]
Hi @Lehnerr, are you getting any errors in the ```suitecrm.log``` or browser? I would also try running a ```composer install```.

So far I haven't been able to replicate this locally or on [demo](https://demo.suiteondemand.com).

**Comment by Lehnerr** [comment]
Hi.
Suitcrm.log is empty
I got following in apache error.log:
[Wed Oct 16 16:11:24.316449 2019] [php7:notice] [pid 7883] [client 10.1.241.69:54227] PHP Notice:  Undefined index: email_warning_notifications in /var/www/suitecrm/modules/Administration/Administration.php on line 84, referer: https://crm-qs-01.itdesign.at/suitecrm/index.php?module=Users&action=DetailView&record=1
[Wed Oct 16 16:11:24.318074 2019] [php7:notice] [pid 7883] [client 10.1.241.69:54227] PHP Notice:  Undefined index: return_module in /var/www/suitecrm/modules/EmailTemplates/EditView.php on line 150, referer: https://crm-qs-01.itdesign.at/suitecrm/index.php?module=Users&action=DetailView&record=1
[Wed Oct 16 16:11:24.318147 2019] [php7:notice] [pid 7883] [client 10.1.241.69:54227] PHP Notice:  Undefined index: return_module in /var/www/suitecrm/modules/EmailTemplates/EditView.php on line 153, referer: https://crm-qs-01.itdesign.at/suitecrm/index.php?module=Users&action=DetailView&record=1

in browser console I get:
ReferenceError: tinymce is not defined



I have no composer installed.

regards Robert

**Comment by Lehnerr** [comment]
I found out the reason for this.
.htaccess has "RedirectMatch 403 (?i)/+vendor"  this causes the 403 error.
After remarking this, it works again on email-Templates and Markting emails.

PDF Templates still not working. Maybe a different problem.

**Comment by Dillon-Brown** [comment]
Technically a duplicate but I think it would make more sense to leave this up as a high priority for anyone searching.
