### ISSUE TITLE
Issues with Dashboard: many actions not working

### ISSUE THREAD

**Issue by labcerouno** [salesagility/SuiteCRM#8087]
Clicking on Edit dashlet, Refresh dashlet, reorder dashlet column and some other actions does nothing and throws a javascript error.

#### Issue
Since updating to version 7.11.8, dashlets on dashboard stopped responding to many click actions. Looking at the browser console, we can see a couple of error messages. For instance: 

- Click on Edit dashlet throws: 
`Uncaught TypeError: Cannot read property 'configureDashlet' of undefined
    at HTMLAnchorElement.onclick`
- Click on a dashlet column name throws or the next page arrow: 
`Uncaught TypeError: Cannot read property 'retrieveDashlet' of undefined at HTMLButtonElement.onclick`

#### My Environment

* SuiteCRM Version used: 7.11.8
* Browser name and version: Chrome 77.0.3865.120 (Build oficial) (64 bits)
* Environment name and version: PHP 7.2 FPM, Percona Server 5.7
* Operating System and version: Ubuntu 18.04

**Comment by craigpanton** [comment]
Hi there, 

I've been unable to replicate this issue. Are there any particular dashlets you are seeing this with?

Also, have you tried running a repair on the javascript files and clearing your browser cache?

**Comment by labcerouno** [comment]
You are so very right, @craigpanton . Repairing js files did the trick! Thank you!

Thinking forward, what can we do to help users who may stumble upon the same problem? Would be useful if the installation script run these repairs automatically?

Regards
