### ISSUE TITLE
themes.gif - 2 files with same name in same directory

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#809]
There are 2 files with same name and directory (one with capital letter) are in conflict on /themes/Suite7/images/
Themes.gif
themes.gif
See: https://github.com/salesagility/SuiteCRM/tree/7.5beta2/themes/Suite7/images
![2015-12-21 14_50_11-000494-d__softwareprodutos_suitecrm_downloads_75beta_suitecrm-7 5beta2_suitecrm-7 5beta](https://cloud.githubusercontent.com/assets/3055443/11933236/92ff1de2-a7f2-11e5-8a0e-1da69c86a730.png)
(I've renamed it with "_1" to create this pic)

If we unzip the install pack one of them is overwritten too:
![2015-12-21 14_48_36-000495-confirmar a substituicao do ficheiro](https://cloud.githubusercontent.com/assets/3055443/11933280/e474d9a0-a7f2-11e5-889d-7a042ce012cc.png)

Note: this is an old issue on SuiteCRM.

**Comment by pribeiro42** [comment]
This only occurs in Windows, because in Linux the two files are indeed different.

**Comment by horus68** [comment]
True, this happens in Windows but that is not the point here.
This shouldn't happen at all (it only happens with this file).
So... this is a bug that needs to be fixed!

**Comment by ghermans** [comment]
@horus68  :+1:
