### ISSUE TITLE
Add config option to hide/show columnSelector in ListViews

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#8099]
#### Issue

When having a big instance with +6000 users, sometimes it is necessary to restrict functionalities to the end user of SuiteCRM, to give everyone an interface **as unified as possible** and make it easy to give it later support.
We have had a lot of reports in help-desk like: _"A column in the ListView disappeared!!"_ And the only thing was the user hidden a column and forget about it.

One of those functionalities is the column selector in ListViews.

![imagen](https://user-images.githubusercontent.com/939888/67131318-9e268580-f1da-11e9-8696-b4bdd902bf06.png)

We do not have an option in `$sugar_config` to hide the column selector in ListViews.

#### Possible Fix

Modify SuiteP tpls to get a config from `$sugar_config` to hide/show the columnSelector

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3

**Comment by Mausino** [comment]
@Abuelodelanada 

#4566 this idea also help you to better user unified enviroment :) because restrict users is "easy" but they lost the flexibility... maybe reset function is good compromise.. 

I can't add code from our system, because is hardcoded fast solution.. not so elagant as many solutions here :(

**Comment by Abuelodelanada** [comment]
Hi @Mausino 

It is not harcoded, you have not to touch code. It's one more config in `config_override.php`, we have hundred of these ones. As simple as that.

Your solution it's very nice, may be you can share your code.

**Comment by Mausino** [comment]
Hi @Abuelodelanada 

I talked about our solution, not yours. 

Your code is nice and handly, our is fast, harcoded and is not so flexibile as yours. 
 
We can provide only inspiration how we solved this kind of user confusing isseu with columns
