### ISSUE TITLE
UI improvement: Underling in some buttons links and not in others looks bad.

### ISSUE THREAD

**Issue by parammittal16** [salesagility/SuiteCRM#8146]
#### Issue

Underling in some buttons links and not in others looks bad.
#### Expected Behavior

This should happen -
![rsz_screenshot_8](https://user-images.githubusercontent.com/31361983/67770857-32b3a200-fa7d-11e9-89d9-cb0630878006.jpg)

#### Actual Behavior

![Capture](https://user-images.githubusercontent.com/31361983/67771160-cab18b80-fa7d-11e9-8329-95e46b8d2ba2.JPG)

#### Possible Fix

Remove all underlines in buttons.

#### Your Environment

* SuiteCRM Version used: 7.10.20

**Comment by Mac-Rae** [comment]
This issue is unrelated to the Application and is a suggestion towards the SuiteCRM site which has been passed to the appropriate members of the SuiteCRM Team. Thank you for bringing this to our attention :+1:

**Comment by parammittal16** [comment]
Yeah @Mac-Rae I want to convey this issue for the site only happy to solve this.
