### ISSUE TITLE
PHPUnit tests not completing in CI on hotfix-7.10.x

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#8153]
#### Issue
PHPUnit is acting strangely in CI since at least a week ago, specifically on hotfix-7.10.x (I haven't checked other branches yet).

It just suddenly stops after the 64th test is run:

```
.   61 / 1384 (  4%)
	SugarControllerTest::testloadBean ............................. [done]
.	SugarControllerTest::testexecute .............................. [done]
.	SugarControllerTest::testprocess .............................. [done]
The command "./vendor/bin/phpunit --stop-on-failure --stop-on-error --colors --configuration ./tests/phpunit.xml.dist ./tests/unit/phpunit" exited with 0.
```

#### Expected Behavior
The tests should all be run.

#### Actual Behavior
The tests stop after around 64 tests have run. It's almost definitely not a problem with the logging because the tests are taking 2-3 minutes less than they normally would, so the other >1000 unit tests aren't being run.

#### Possible Fix
Not really sure?

You can see the normal behavior, for [this commit](https://github.com/salesagility/SuiteCRM/commit/891ed62f7895c1c80bb76c756a7bce60d7e52ff3), in [this CI job](https://travis-ci.org/salesagility/SuiteCRM/jobs/601242180?utm_medium=notification&utm_source=github_status)

You can see the bad behavior, for [this commit](https://github.com/salesagility/SuiteCRM/commit/0262a79171a3d3e75ef06d3760be4ccb60fd3a7a), in [this CI job](https://travis-ci.org/salesagility/SuiteCRM/jobs/602261388?utm_medium=notification&utm_source=github_status).

#### Steps to Reproduce
1. Look at a recent commit to hotfix-7.10.x
2. Look at the CI jobs for it
3. View the log for the PHP 5.6 or 7.3 jobs
4. See that PHPUnit stops after around 64 tests, but still has an exit code of 0?

#### Context
It means that we could be merging bad code without knowing it.

**Comment by connorshea** [comment]
The issue starts somewhere between e9768bb6bc2c409d993882f0f25f0207e60bbb56 (good) and 0262a79171a3d3e75ef06d3760be4ccb60fd3a7a (bad). Unfortunately, all the commits in between fail CI, so I can't really tell whether they have the issue.

**Comment by connorshea** [comment]
It seems like there are a bunch of errors related to an acl_actions query that didn't exist prior to this issue: 

Recent log (post-issue): https://www.simpleupload.co.uk/uploads/4c6Wo8suitecrm.log
Older log (pre-issue): https://www.simpleupload.co.uk/uploads/AdU2NOsuitecrm.log

```
Thu Oct 24 16:04:57 2019 [7958][-none-][FATAL] Mysqli_query failed.
Thu Oct 24 16:04:57 2019 [7958][-none-][FATAL]  Query Failed: SELECT * FROM 'acl_actions' WHERE name = 'edit' AND category = 'SurveyQuestions' AND acltype = 'module' AND deleted = 0: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''acl_actions' WHERE name = 'edit' AND category = 'SurveyQuestions' AND acltype =' at line 1
```

**Comment by lazka** [comment]
I should have probably commented here instead, but I added some comments in #8153

**Comment by connorshea** [comment]
@lazka I assume you mean #8154?

**Comment by lazka** [comment]
right, oops
