### ISSUE TITLE
Inline Editing: Relationship always displayed as link after inline editing

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#817]
Not sure if this is a bug, but:
for example, when i change the assigned-to relationship in accounts module via inline editing, the new entry is displayed as link, despite the fact that this field is not a link usually.

before inline-edit:
![assignedto1](https://cloud.githubusercontent.com/assets/15199551/11975772/81f16c0a-a971-11e5-820b-03dd3c8d7538.png)
while:
![assignedto2](https://cloud.githubusercontent.com/assets/15199551/11975775/8b5b008a-a971-11e5-876f-16852c574316.png)
after:
![assignedto3](https://cloud.githubusercontent.com/assets/15199551/11975778/9104a9be-a971-11e5-9d9a-ba0cc0678dd4.png)

**Comment by Mausino** [comment]
:+1:

**Comment by jobvector** [comment]
Tested on the 7.5.1 too: Same problem.

**Comment by jobvector** [comment]
it works, thx for the fix
