### ISSUE TITLE
Chrome auto fill on navbar search has same colour as background

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#8180]
#### Issue
When using the navbar search on chrome, when you select an auto-fill the font colour is the same as the search bar back ground making it not appear

#### Expected Behavior
The font colour should be the same as when you type in the search bar

#### Actual Behavior
Colour is the same as the background of the search bar making it hidden

#### Steps to Reproduce

1. Click on the navbar search 
2. Select an auto fill value
3. See that colour is same as navbar background

#### Context

Low priority

#### Your Environment

* SuiteCRM Version used: 7.11.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 75.0.3770.142 
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by pgorod** [comment]
This can be closed now, right?
