### ISSUE TITLE
Reports module date parameters ignored when change page 

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#8182]
#### Issue
When using detail view date parameters in reports the date parameter is ignored when moving to the next page of the reports results

#### Expected Behavior
Date parameter should be followed when moving to the next page

#### Actual Behavior
Date parameter are not followed when moving to the next page

#### Steps to Reproduce

1. Have 50 account records with different date modifieds
2. Create account reports to display name and date modified
3. Make 1st condition: Date Modified->Greater Than->Value-> Date in-between oldest and newest date modified of accounts
4. Make sure parameter box is ticked
5. Run report and make sure not all records are displayed
6. Go to next page and see that the (1- 10 of 25) has now changed to (11- 20 of 50) and that all records are now returned

#### Context
Unable to navigate through reports

#### Your Environment

* SuiteCRM Version used: 7.11.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by mayerelyashiv** [comment]
Hi, i just noticed the same behaviour in a 7.10.15.
I could suggest that the issue is linked to different date format (dd-mm-yyyy vs. yyyy-mm-dd).
I think so because if you select a date like 06-11-2019 it works but changed the result.

Workaround: not to set that date field in Conditions as a parameter but to leave it fixed.

**Comment by Mac-Rae** [comment]
Hi @,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version.

Thanks :+1:
