### ISSUE TITLE
non-group records show on list view if group only access

### ISSUE THREAD

**Issue by eggsurplus** [salesagility/SuiteCRM#8183]
To replicate, assign a user a role with Group only access to List. Log in as the user and the user will be able to view non-group records on the list view (assuming data is set up correctly).

To resolve edit ACLAction.php and change the new "===" comparison in userNeedsSecurityGroup() back to a "==":

`    public static function userNeedsSecurityGroup($user_id, $category, $action, $type = 'module')
    {
        //check if we don't have it set in the cache if not lets reload the cache

        if (empty($_SESSION['ACL'][$user_id][$category][$type][$action])) {
            self::getUserActions($user_id, false);
        }

        if (!empty($_SESSION['ACL'][$user_id][$category][$type][$action])) {
            return $_SESSION['ACL'][$user_id][$category][$type][$action]['aclaccess'] == ACL_ALLOW_GROUP;
        }

        return false;
    }`

**Comment by eggsurplus** [comment]
Introduced in 7.10.21 and 7.11.9.

**Comment by eggsurplus** [comment]
Lots of wholesale changes in this release. I'm fearing that there will be a bunch of fallout for users due to making these changes without knowing the ramifications.

**Comment by copyyour** [comment]
I tested your method, but still failed to solve the problem of non-role user list showing other user data.
But adding a role save to the user interface can be successful.
Thank you.

**Comment by AdminPL** [comment]
This patch works with all standard modules except repots, but takes no effect on custom

**Comment by Mac-Rae** [comment]
> the problem of non-role user list showing other user data.
@copyyour 

Can I confirm that you meant users with no role or security group are able to see all data even that of user who has roles or security groups?
If so I believe this is intended functionality

**Comment by eggsurplus** [comment]
I can't really follow what's going on after my original comment here. Just letting you all know that === in userNeedsSecurityGroup breaks SecuritySuite. Changing that to a == makes it work as intended. 

Here is how it looks with ===:
https://www.dropbox.com/s/p16i6n8samlg1pj/Screenshot%202019-11-06%2007.53.38.png?dl=0

The user does not have access to RR. Talker Co at all. The user's group is not assigned to that record and the user is not the assigned user of it.

Here is how it looks when switched back to ==:
https://www.dropbox.com/s/ks82driofrvk4ph/Screenshot%202019-11-06%2007.54.51.png?dl=0

The record is now filtered out as it should be.

Hope this helps. I have made this change in the full version of SecuritySuite for 7.10.21 and 7.11.9 so that customers are not affected.

**Comment by Dillon-Brown** [comment]
Thanks @eggsurplus, we'll look at getting a patch out for this and a few other issues (Workflows, etc) as soon as possible.
