### ISSUE TITLE
7.11.9 Confirm that the role and security suite in the user is invalid

### ISSUE THREAD

**Issue by copyyour** [salesagility/SuiteCRM#8184]
Confirm that the role and security suite in the user is invalid, cannot be saved, and the permission control is invalid.

**Comment by Mac-Rae** [comment]
Hi @copyyour,

Could you provide more information in regards to what this issue is in relation to, preferably following out template also providing replication steps as they help in assisting us to debug effectively?

Thanks :+1:

**Comment by copyyour** [comment]
I am using ubuntu 18.04
Environment installation xampp
From 7.11.8 through the System Management Upgrade Wizard for a normal upgrade, no errors occurred during the period.

However, during the use process, the permission control of the user role assignment is found to be invalid. The content of the list is set to be viewable only by the person in charge. After the upgrade, it becomes a full member to view.

BTW: I don't know English well, I use google translation, sorry.

**Comment by horus68** [comment]
Duplicated? https://github.com/salesagility/SuiteCRM/issues/8178#issuecomment-550159457

**Comment by Mac-Rae** [comment]
Bet me to it @horus68.

Thank you for providing further information @copyyour. From what I understand this has already been raised within issue #8178. I'm going to close this issue over, If you believe this to be incorrect please let me know and I will reopen
