### ISSUE TITLE
Missing Header Text & Google Calendar Settings in 7.11.9

### ISSUE THREAD

**Issue by ApatheticCosmos** [salesagility/SuiteCRM#8203]
#### Issue

In Administration, the 'Google Suite' section is missing it's header and description. It just has:
LBL_JJWG_MAPS_ADMIN_HEADER
LBL_JJWG_MAPS_ADMIN_DESC

Also, the 'Google Calendar Settings' option is missing.
![image](https://user-images.githubusercontent.com/16560296/68326766-107fdc80-009a-11ea-905e-a49c74804770.png)

Without these, it's impossible to configure Google Calendar syncing.
#### Expected Behavior

The header should be populated and the option there.
![image](https://user-images.githubusercontent.com/16560296/68327021-93089c00-009a-11ea-96b6-fdf6bbf09ac9.png)

#### Actual Behavior

It's missing.

#### Possible Fix

I'm working on a PR for this. 

It was broken by 73ded274eebfd17868b3b24e2e3294690635857e

#### Steps to Reproduce

1. Open Administration
2. Notice it's missing the Header and Google Calendar option
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.11.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by holdusback** [comment]
Got the same issue in 7.11.9 too !

**Comment by ApatheticCosmos** [comment]
@holdusback 
The commit above fixes it if you want to apply it to your local installation.

**Comment by Dillon-Brown** [comment]
Will make sure to include this one for a quick 7.11.10 and 7.10.22 release. Thanks!
