### ISSUE TITLE
Suggestion: Spam Folder Sync

### ISSUE THREAD

**Issue by thiras** [salesagility/SuiteCRM#821]
Spam folders sync at email module.

Some mail servers aggressively mark spam and this cause lots of false marking. It would be useful if we could see spam folder too.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suggestion: Spam Folder Sync](https://trello.com/c/kc1Son9Y/126-suggestion-spam-folder-sync)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
