### ISSUE TITLE
suitecrm 6.5 module does not save into custom table

### ISSUE THREAD

**Issue by maxteebabs** [salesagility/SuiteCRM#8219]
I have a module called flights that i moved from production to test. I cant seem to save data into the custom table of this module from the edit view. I only have this issue for the particular module. I believe my fields_meta_data_table is okay and my vardefs file is okay. I have done repairs but still does not work. I noticed, it will actually save into the main flights table but not into the custom table.

**Comment by pgorod** [comment]
There is no "SuiteCRM 6.5", do you mean you tried to import a SugarCRM 6.5 module into SuiteCRM (which version?) and it didn't work?

This seems like an issue for the Forums, not GitHub...

**Comment by maxteebabs** [comment]
Yes I meant SugarCRM 6.5. I have been able to fix it. Inserting into the custom table was throwing errors. Hence, it wasnt saving in there

**Comment by pgorod** [comment]
Ok, but then I am really sure this isn't an issue for Github - you should only post here when you are sure it is a bug in SuiteCRM and you have collected technical information for the developers to work on.

Please close this issue and open a thread in the Forums instead:
https://suitecrm.com/suitecrm/forum/

About your issue - you shouldn't assume that you can just "move" a custom module from SugarCRM 6.5 in to SuiteCRM. The only supported path for this is the upgrade we provide from Sugar 6.5 into SuiteCRM. Apart from that, you're on your own...
