### ISSUE TITLE
Reminders for meetings and calls (pop up and e-mail) are sent at the wrong time

### ISSUE THREAD

**Issue by lakomaa** [salesagility/SuiteCRM#822]
Probably there is a problem with the timezone, e.g. timezone: Europe/Warsaw (GMT+1), meeting is planned for 10:00, e-mail reminder is set 15 min before meeting (9:45) but it came at 10:45 which is an hour too late.

**Comment by KhyberPass** [comment]
This is a duplicate of #766. Reminders only work correctly when the users time zone is UTC.
