### ISSUE TITLE
SourceForge SuiteCRM-Upgrade-7.11.x-to-7.11.10 weirdness

### ISSUE THREAD

**Issue by eggsurplus** [salesagility/SuiteCRM#8237]
It looks like a build process went bad for just one package on SourceForge.

With the 7.11.10/7.10.22 batch of files this only happened in the SuiteCRM-Upgrade-7.11.x-to-7.11.10.zip package. The /include/DetailView/DetailView.php file is actually /modules/ACLRoles/DetailView.php. There may be other files affected as well, but I stopped at that point.

**Comment by pgorod** [comment]
How did you notice this, any error in the app? I used that package and everything seems to go fine...

**Comment by eggsurplus** [comment]
I can see how the upgrade wouldn't affect you, at least immediately. Most everything uses DetailView2.php now.

While doing my normal upkeep with SecuritySuite on each SuiteCRM release I did a diff between the 7.11.10 package and the 7.11.9 package to see what changed. /include/DetailView/DetailView.php was one of the changes. Viewing it became obvious that it was the ACLRoles DetailView.php.

**Comment by pgorod** [comment]
Well, you are right about the file swap, and I guess we should be worried about this, at least until we can be sure no other files might be wrong... thanks for the heads-up.

**Comment by eggsurplus** [comment]
If you could tell my wife that I can be right sometimes, that would be great.

**Comment by samus-aran** [comment]
Thanks @eggsurplus Just to confirm did an audit on the 7.11.x upgrade packs and there are a few minor formatting differences with the packages & master but that file you highlighted was a huge diff. I've replace that file in the package with one from master and re-uploaded the 7.11.x - 7.11.10 packs on sourceforge and will continue on with an additional review of the other packs. :+1:
