### ISSUE TITLE
Added OpenID/Oauth2 Authentication

### ISSUE THREAD

**Issue by kstan79** [salesagility/SuiteCRM#8239]
I'm new in suitecrm, but I'd added PR #8240 which allow keycloak integration. If the PR can approve into master release will be useful to user who wish to use single sign on, or extend from the work.

#### Issue

Special note: I have no ideal how to add configuration page to allow end user define OPENID configuration.

#### Your Environment

* SuiteCRM Version used: 7.11
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP7 + Mysql
* Operating System and version (e.g Ubuntu 16.04): Mac

**Comment by Mac-Rae** [comment]
Hi @kstan79 

I've commented on you PR, however, will close this issue over as it is not required.

Thanks :+1:
