### ISSUE TITLE
Search settings disappeared from Admin after upgrade 7.11.9 -> 7.11.10

### ISSUE THREAD

**Issue by Spinwing** [salesagility/SuiteCRM#8246]
#### Issue
- As per title, the "Search Settings" panel is not present anymore in the Administration section on 7.11.10. 
- It disappeared in a test upgrade, and confirmed not present in a fresh install. 
- Panel is present on 7.11.9

#### Expected Behavior
Search Settings should appear under the Administration panel 

#### Actual Behavior
Search Settings is completely missing

#### Your Environment
* SuiteCRM 7.11.10
* Ubuntu 19.10
* MariaDB 10.3.17-MariaDB-1 Ubuntu 19.10
* PHP PHP 7.3.11-0ubuntu0.19.10.1

#### Possible Fix
I'm not an expert Suitecrm developer, but a quick diff revealed that an entire section is missing from adminpaneldefs.php such as below. Unsure if just a copy/paste would solve the issue. 

```
$admin_option_defs = [];

$admin_option_defs['Administration']['search_wrapper'] = [
    'icon_SearchForm',
    'LBL_SEARCH_WRAPPER',
    'LBL_SEARCH_WRAPPER_DESC',
    './index.php?module=Administration&action=SearchSettings',
    'global-search'
];

$admin_option_defs['Administration']['global_search'] = [
    'icon_SearchForm',
    'LBL_SEARCH_MODULES',
    'LBL_SEARCH_MODULES_HELP',
    './index.php?module=Administration&action=GlobalSearchSettings',
    'global-search'
];

$admin_option_defs['Administration']['elastic_search'] = [
    'ElasticSearchIndexerSettings',
    'LBL_ELASTIC_SEARCH_SETTINGS',
    'LBL_ELASTIC_SEARCH_SETTINGS_DESC',
    './index.php?module=Administration&action=ElasticSearchSettings',
    'global-search'
];

// SearchWrapper
$admin_group_header[] = [
    'LBL_SEARCH_HEADER',
    '',
    false,
    $admin_option_defs,
    'LBL_SEARCH_HEADER_DESC'
];
```

**Comment by gunnicom** [comment]
I can confirm this, after Update 7.11.7 => 7.11.10

**Comment by craigpanton** [comment]
From the tags, it looks as though this was removed between 7.11.8 and 7.11.9.

**Comment by pgorod** [comment]
Probably related to whatever required this fix #8207

I wonder if anything else is missing?

**Comment by Dillon-Brown** [comment]
Assuming this must have accidentally been removed during a merge, don't see any reason for its removal.

**Comment by mohsanazadd** [comment]
a quick fix.
add this line in file config_ovberride.php

$sugar_config['http_referer']['actions'] =array( 'index', 'ListView', 'DetailView', 'EditView', 'oauth', 'authorize', 'Authenticate', 'Login', 'SupportPortal', 'SearchSettings', 'ElasticSearchSettings' );

and then you can access the settings using these links

https://yourdomain.com/index.php?module=Administration&action=ElasticSearchSettings
https://eurocrm.co.uk/crm/index.php?module=Administration&action=SearchSettings
