### ISSUE TITLE
7.10.22 release on the wrong branch with the wrong tag

### ISSUE THREAD

**Issue by lazka** [salesagility/SuiteCRM#8255]
The 7.10.22 release is on the branch "7.10.x" instead of "hotfix-7.10.x" and the release tag points to release commit of 7.11.10 and not 7.10.22.

**Comment by lazka** [comment]
As pointed out on gitter the branch is on purpose to get a release that doesn't include everything in hotfix.

The wrong tag should still be fixed.

**Comment by Mac-Rae** [comment]
Hi @lazka,

Thanks for raising this issue:+1: 
@samus-aran is looking into resolving this soon

**Comment by samus-aran** [comment]
Resolved the tag! Though missing a release (tho not a big issue). Thanks for the catch @lazka

**Comment by lazka** [comment]
Thanks!
