### ISSUE TITLE
7.11.10 dashboard can't do anything

### ISSUE THREAD

**Issue by copyyour** [salesagility/SuiteCRM#8262]
After upgrading to 7.11.10, the home page's dashlet can't do anything, click refresh, delete, and the edit button doesn't respond.
I also tried to fix it in system management, but it still didn't work.

I hope to get help, thank you very much.

Expected Behavior
After I upgraded to 7.11.10, in the dashboard of the homepage, all the Dashlets in the Dashlet can not be edited, deleted, or refreshed. At the same time, there is no response after adding Dashlet clicks.

Actual Behavior
I have tried using the repair tool in system management.
I use the developer option in Google Chrome. When I click the edit button in the dashlet, I get the following error: Uncaught TypeError: Cannot read property 'configureDashlet' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when the refresh button is clicked: Uncaught TypeError: Cannot read property 'retrieveCurrentPage' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when the delete button is clicked: index.php?module=Home&action=index:1 Uncaught TypeError: Cannot read property 'deleteDashlet' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when I click Add Dashlet:
Uncaught TypeError: Cannot read property 'showDashletsDialog' of undefined
    At HTMLDivElement.<anonymous> (retrievePage.js:46)
    At HTMLDivElement.dispatch (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At HTMLDivElement.r.handle (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At Object.trigger (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At HTMLDivElement.<anonymous> (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At Function.each (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:2)
    At n.fn.init.each (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:2)
    At n.fn.init.trigger (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At c.show (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:12)
    At c.toggle (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:12)

Steps to Reproduce

Context

Your Environment
SuiteCRM Version used:
Browser name and version (e.g. Chrome Version 78.0.3904.87 (64-bit)):
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version (e.g Ubuntu 18.04):

**Comment by copyyour** [comment]
@

**Comment by willrennie** [comment]
@copyyour Please can you provide more information? When logging issues on the project repository, you should use the issue template that is provided to you:





#### Issue



#### Expected Behavior


#### Actual Behavior



#### Possible Fix


#### Steps to Reproduce


1.
2.
3.
4.

#### Context



#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by copyyour** [comment]
Expected Behavior
After I upgraded to 7.11.10, in the dashboard of the homepage, all the Dashlets in the Dashlet can not be edited, deleted, or refreshed. At the same time, there is no response after adding Dashlet clicks.

Actual Behavior
I have tried using the repair tool in system management.
I use the developer option in Google Chrome. When I click the edit button in the dashlet, I get the following error: Uncaught TypeError: Cannot read property 'configureDashlet' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when the refresh button is clicked: Uncaught TypeError: Cannot read property 'retrieveCurrentPage' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when the delete button is clicked: index.php?module=Home&action=index:1 Uncaught TypeError: Cannot read property 'deleteDashlet' of undefined
    At HTMLAnchorElement.onclick (index.php?module=Home&action=index:1)

Appears when I click Add Dashlet:
Uncaught TypeError: Cannot read property 'showDashletsDialog' of undefined
    At HTMLDivElement.<anonymous> (retrievePage.js:46)
    At HTMLDivElement.dispatch (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At HTMLDivElement.r.handle (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At Object.trigger (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At HTMLDivElement.<anonymous> (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At Function.each (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:2)
    At n.fn.init.each (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:2)
    At n.fn.init.trigger (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:3)
    At c.show (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:12)
    At c.toggle (sugar_grp1_jquery.js?v=8dPPYmxseQxeIHUAuVj9vg:12)

Possible Fix

Steps to Reproduce

Context

Your Environment
SuiteCRM Version used:
Browser name and version (e.g. Chrome Version 78.0.3904.87 (64-bit)):
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version (e.g Ubuntu 18.04):

**Comment by Mac-Rae** [comment]
@copyyour, I've updated your first post. Could you please remove your additional comment as its no longer required. Thanks :+1:

**Comment by Mac-Rae** [comment]
@copyyour, Could you try running a repair and rebuild via the repair option found within the administration menu and ensure you execute the code found at the bottom

**Comment by copyyour** [comment]
I successfully solved this method. #7696 #7697

**Comment by copyyour** [comment]
Does it mean that there are still errors in 7.11.7 before 7.11.10?

**Comment by Mac-Rae** [comment]
Hi @copyyour, 

Can you confirm that this issue is solved for you?
Not sure what your question is exactly but this issue should be resolved in 7.11.10

**Comment by copyyour** [comment]
I am sure the problem has been resolved and it is determined that:  #7696  and #7697

**Comment by Mac-Rae** [comment]
None problem, I'll close this over :)
