### ISSUE TITLE
GraphQL based API

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#8282]
Hi, we are using the REST API

What are you thinking about it? Should move us further with GraphQL as with REST API ???
If you're thinking that my post is spam.. please close the ticket and i apology myself.

Source from shopify about graphql benefits:

We should be implement via 

https://webonyx.github.io/graphql-php/ 
or 
https://github.com/api-platform/api-platform (it's based on symphony + graph-php)

What are the benefits of using GraphQL instead of REST?
GraphQL addresses several problems that might sound familiar to anyone who’s worked with a REST API.

REST | Fetching associated data often requires multiple HTTP calls
REST APIs are built on the principle that every endpoint should return only one type of resource. For example, the request GET {shop_domain}/admin/api/2019-10/products/1.json retrieves the information for product 1, but nothing more. This means that if you want a product’s variants, images, and metafields, then you need to make at least four HTTP calls.

REST | Apps receive more data than they need
To solve the above problem, we end up breaking away from true REST APIs by embedding certain associations to certain end-points when the need arises. For instance, GET /products/1 returns information about the product, but also its variants, images, and options. Ultimately we end up with one-size-fits-all responses where you cannot request less nor more than what we give you.

REST | Shopify doesn't know what data an app is using
When an app requests a REST endpoint, Shopify has no way of knowing if it's actually using every piece of data that's returned. It’s similar to doing a SELECT * to a SQL database. This is problematic because when Shopify needs to make breaking changes, such as remove an attribute from a response, it’s nearly impossible to know who it will affect. We know which clients call which endpoint, but we don’t know what subset of those clients are using the attribute that we're removing. Some attributes are also costly to compute. If we knew that the app doesn’t need a costly attribute, then we wouldn’t need to compute it in the first place.

REST | REST APIs are usually weakly-typed and lack machine-readable metadata
While there exists some solutions to the problem of not knowing which data is being used (like JSON Schema), the reality is that most REST APIs do not provide this sort of metadata. The result is that apps rely on documentation, which can become out of date or might be incomplete.

GRAPHQL | Everything is typed and part of a schema
Everything that's available through a GraphQL API is included in its schema. You can use the schema to build queries that return only the data that you need. This solves the problem of over-fetching data. It also means that we know which fields each app is using, making it easier for us to evolve our APIs over time.

GRAPHQL | Everything is available from a single endpoint
All GraphQL requests are sent to the /admin/api/2019-10/graphql.json endpoint, which means that you can often retrieve all the data that you need in a single request. Using GraphQL features such as connections, variables, and aliases, you can make your queries incredibly efficient and retrieve data about many resource types in a single request.

GRAPHQL | Documentation is a first-class citizen
The documentation for a GraphQL API lives side-by-side with the code that constitutes it. Combined with the typed schema, this means that we can generate accurate and up-to-date documentation whenever something changes. Using GraphQL's introspection feature, you can query the schema itself to explore its contents and documentation.

GRAPHQL | Deprecation is a first-class citizen
We can easily mark a part of our schema as deprecated, and this will also be reflected in documentation. GraphQL tooling, such as client libraries, is also expected to communicate to the developer that they're using a deprecated tool.

**Comment by Dillon-Brown** [comment]
Hi @Mausino, thanks for bringing this up!

I definitely agree there can be some really great benefits with GraphQL, I think it's definitely something we should consider looking at for the future with GraphQL being integrated into more and more tech stacks of a ton of the big data players (Facebook, Twitter, Shopify, etc).

Although at the same time I would say that for applications with existing RESTful APIs there shouldn't need to be a big rush to replace it all with GraphQL as you can accomplish most of the benefits of a GraphQL API with a proper implementation of REST (And REST is going to be around for a looong time).

I haven't tried it myself but it's also worth also mentioning there's an existing SuiteCRM GraphQL integration here too: https://github.com/lionixevolve/GraphQLSuiteCRM

**Comment by connorshea** [comment]
I like GraphQL a lot, but generally I think it'd be a lot of work to implement a GraphQL API for not much benefit right now.

**Comment by Mausino** [comment]
@Dillon-Brown thank you so much....

> My external developer tried it in last week, and sad that never will use V8 again :( (now studying how implement any custom modules or cusotm fields) .. i think that he is only pre-motivated :D and problems will come soon also with GraphQLSuiteCRM

![2019-11-20_2001](https://user-images.githubusercontent.com/5773777/69271451-2c749980-0bd5-11ea-800f-5871108b7034.png)

The new version of SuiteCRM 8 will come...  stable release will maybe in 2021 :) i see now that are lot of issues with custom fields or modules (we also fighting with this). Everybody i hear about API first solutions... and we must for our external application use direct access to database (which is insecure) because in some points we can't move with current SuiteCRM API policy.

https://stackoverflow.com/questions/54995909/suitecrm-integration-with-graphql

> We had the same issues with the REST endpoint and we heavily rely (and like) graphql so we decided to create a helper library. https://github.com/lionixevolve/GraphQLSuiteCRM
> 
> So far we have been using this in 5 not-so-small projects (5M record tables with 100s of users).
> There are almost no custom queries everything works using SuiteCRM beans which respects logic-hooks and workflows and speed is similar to native SuiteCRM nevertheless, custom resolve methods can be created for specific scenarios (like reports or adding a large set of contacts to a target list)
> 
> Currently, its using the slim framework which allows you to write your own custom functions.
> I am active on the github repo, open an issue if you have any trouble.

We're trying develop some custom application for task and cooperation and visualizations by [Quasar framework](https://github.com/quasarframework/quasar) which can from one code base create desktop, pwa or mobile app. We need feed this app by data by in some points we're in death point (we're small company with small budged to hire some some bigger players).

I hope that we will move further with https://github.com/lionixevolve/GraphQLSuiteCRM but i see here problems like that is build on https://github.com/youshido-php/GraphQL which have this alert

> Looking for Maintainers! Unfortunatelly, we cannot longer support this package and are looking for someone to take the ownership. Currently Only PRs with bugfixes and not breaking BC are being merged. It's very sad to acknowledge this, but we hope that someone can take it further with the community. Please, PM @viniychuk if you are interested in taking over. 

That means that the base on which lays the project will dying... but on ohter hands second solution for php https://webonyx.github.io/graphql-php/ have good community and also "support" of symfony framework implementations

To the point. I think that SuiteCRM is great peace of software, it can be custom as any other free CRM but new century is based on connectivity between applications and "machines" and if big players build on new technologies, we should build on their shoulders.

Sorry for english. :)

**Comment by Mausino** [comment]
Sorry if i disturbed you guys, i want ask you your opinion about currently API situation in SuiteCRM and some your advises or experiences with current RESTful API.  

What do you think, should maybe in the future coexist REST with GraphQL in same instance ? and the developers should choose which one use.. or is bad idea and should we rely(continue) on only REST solution.

I apology if i somebody disturbed with this ticket.

@horus68
@ApatheticCosmos
@mikebeck
@amariussi
@likhobory
@urdhvatech
@Mausino
@jakubpas
@JanSiero
@lazka
@jsamelko
@adriangibanelbtactic
@ChangezKhan
@Abuelodelanada
@hieuhoanghd
@LionelBino
@sanchezfauste
@adamjakab
@isleshocky77
@anhnhatuit
@ghermans
@eggsurplus
@javitoron
@sathishsengodan
@jobst
@bluquet
@connorshea
@gitbnw
@604media
