### ISSUE TITLE
When overriding sqs for flex relate field, only works upon update, not during creation

### ISSUE THREAD

**Issue by CJorami14** [salesagility/SuiteCRM#8301]
When overriding SQS for flex relate, it doesn't seem to when during the creation mode. It only works upon update.

#### Issue
Here is the custom code I've created:
`SUGAR.util.doWhen(
        "typeof(sqs_objects) != 'undefined' && typeof(sqs_objects['EditView_parent_name']) != 'undefined'",
        customSqs
    );

    function customSqs() {
        console.log("Hi");
        var parent_type = $('#parent_type').val();
        var formName = 'EditView_'; // form name
        var fieldName = 'parent_name'; // field name to override SQS
        var sqsId = formName + fieldName;
        if (parent_type === 'Contacts') {
            sqs_objects[sqsId]['modules'] = ["Contacts"];
            sqs_objects[sqsId]['conditions'] = [
                {
                    "name": " name",
                    "op": "like_custom",
                    "end": "%",
                    "value": ""
                },
                {
                    "name": " is_technician_c", // name of field to apply filter
                    "op": "equals",
                    "value": 1 // Value to compare
                }
            ];
        }
        else {
            sqs_objects[sqsId]['modules'] = ["Users"];
            sqs_objects[sqsId]['conditions'] = [
                {
                    "name": " name",
                    "op": "like_custom",
                    "end": "%",
                    "value": ""
                },
                {
                    "name": " service_crew_c", // name of field to apply filter
                    "op": "equals",
                    "value": 1 // Value to compare
                }
            ];
        }
        sqs_objects[sqsId]['group'] = "and";`

#### Expected Behavior
In create mode, the filtering by the set conditions should work (just like upon update)

#### Actual Behavior
SQS return all results unfiltered in 'Create' mode

#### Steps to Reproduce
1. In code, create a custom sqs with customized condition  for a flex relate field for a certain module 
e.g. 
      Module: Any
      Flex field selected module: Users
      Custom condition: status = 'Active'
2. In CRM, open the module containing the selected flex relate field.
3. Type a User whom you know has an Inactive status. (does not comply with the condition)

#### Your Environment
* SuiteCRM Version used: 7.10.16

**Comment by samus-aran** [comment]
I really suspect this is just user guidance than a core bug. But I've reached out if anyone who has done this them selves I also recommend that you open this up in the SuiteCRM Community forums.

**Comment by PedroErnst** [comment]
Hi @CJorami14 

Thanks for reporting this.  
I agree with @samus-aran , a priori I don't see where the bug is, it could be in your custom code just as well. I personally have done this customization multiple times without encountering this bug you're reporting.

One thing you'd probably want to do is a listener for the `parent type` drop down on change event, so you can update the sqs data every time the `parent type` is changed.

I'd start by having a look at the sqs data in your browser console after your js has fired. Does it contain what it's supposed to? Compare with the edit view to see what's missing / different.

**Comment by mattlorimer** [comment]
we will close this issue for now, we can re open if you have more information to show this a core issue
