### ISSUE TITLE
Slight misspelling

### ISSUE THREAD

**Issue by punixer** [salesagility/SuiteCRM#831]
admin/system settings/select logo.
i: it's written 17px, when the max is 170px.

that's all.

**Comment by horus68** [comment]
As for the text, files to be changed:
\install\language\en_us.lang.php
line 634

\modules\Configurator\language\en_us.lang.php
line 136

As for the dimensions someone needs to confirm if there is any CSS related rule

**Comment by horus68** [comment]
Merged and solved. Can be closed!
