### ISSUE TITLE
Multiple IMAP Inboxes

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#8319]
#### Issue

When configured to monitor multiple IMAP Inboxes using multiple-select in the folder browser, no Emails are displayed for any folder.

#### Expected Behavior

Each monitored folder should display the relevant email in each.
#### Actual Behavior

No emails are displayed in any folder. The problem is that the multiple monitored folders are concatenated into a single string and, when the IMAP connection is opened, this concatenated string is used as the folder to open. The IMAP server does recognise this as a legitimate folder. This invalid string is used for every connection to the server so no emails are displayed.

#### Possible Fix

In modules/Emails/Folder.phpline 102
Change
```
                        if (empty($row['parent_folder'])) {
                                // root node (inbound)
                                $this->id = $row['id'];
                        } else {
```
to
```
                        if (empty($row['parent_folder'])) {
                                // root node (inbound)
                               $this->id = $row['id'];
                               $this->type = $row['folder_type'];
                               $this->mailbox = 'INBOX'; // Top level IMAP folder
                        } else {
```

In modules/Emails/include/ListView/ListViewDataEmails.php line 238
Change
```
                switch ($folder->getType()) {
                        case "inbound":
                                 $inboundEmail->mailbox = $inboundEmail->get_stored_options('mailbox');
                                break;
```
to
```
                switch ($folder->getType()) {
                        case "inbound":
                               // Use the mailbox associated with $folder rather than the option string
                              // Used in the IMAP connection string later
                               $inboundEmail->mailbox = $folder->mailbox;
                                break;
```

And to fix email pagination clicking the Last button. In modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php line 122
```
        if ($page === "end") {
                  $offset = $total - $limitPerPage;
         }

```
to
```
            if ($request['Emails2_EMAIL_offset'] === "end") {
                      $offset = $total - $limitPerPage;
             }
```

#### Steps to Reproduce

1. Select multiple folders to be monitored in Incoming Email / Monitored Folders.
2. Browse the emails
3. Select any folder from the folder chooser
4. No email

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Hi @nelem,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version.

Thanks :+1:

**Comment by nelem** [comment]
Reproduced on 7.11.15 also. You need to be monitoring multiple mailboxes to see the problem.

**Comment by Trumanp014** [comment]
I can confirm that Version 7.11.15 still has a problem displaying more than 1 subscribed imap folder. I run dovecot as my imap server, and when I select more than 1 folder to monitor in the email account setup none of them display. If I select a single folder it will display fine.

Using nelem's patch fixes the problem in version 7.11.15

**Comment by Trumanp014** [comment]
Can confirm it is still an issue with 7.11.16

Email Server running Dovecot as well. Will not display any email for any folder if more than one is selected to be monitored. Definite bug. No problems with 3rd party email clients such as Outlook, or Roundcube.

**Comment by nelem** [comment]
Can confirm still an issue in 7.11.17

The patch above still works.

**Comment by panosil79** [comment]
Can confirm still an issue in 7.11.19

The patch above still works.
