### ISSUE TITLE
Double clicking sort actions in ListView produces blank page

### ISSUE THREAD

**Issue by marin-h** [salesagility/SuiteCRM#8323]
For example when double clicking to sort ascending:
![imagen](https://user-images.githubusercontent.com/5542756/69753572-aefbdc80-1132-11ea-8194-5792ba700e09.png)

Leads to this:
![imagen](https://user-images.githubusercontent.com/5542756/69753627-c935ba80-1132-11ea-8675-cafcb5af21b8.png)

#### Expected Behavior
Double clicking sort actions should produce the same result as single clicking: sorting the records.

#### Actual Behavior
Double clicking sort actions in any field in ListView produces blank page. 

#### Possible Fix
The simplest solution would be to remove the `return !checks;` sentence in 
`include/javascript/sugar_3.js`, 
```js
sugarListView.prototype.order_checks = function (order, orderBy, moduleString) {
  checks = sugarListView.get_checks();
  document.MassUpdate.elements[moduleString].value = orderBy;
  document.MassUpdate.lvso.value = order;
  if (typeof document.MassUpdate.massupdate != 'undefined') {
    document.MassUpdate.massupdate.value = 'false';
  }

  //we must first clear the action of massupdate, change it to index
  document.MassUpdate.action.value = document.MassUpdate.return_action.value;
  document.MassUpdate.return_module.value = '';
  document.MassUpdate.return_action.value = '';
  document.MassUpdate.submit();

  return !checks;
}
```

Another approach would be moving the sorting logic to the `onclick` attribute instead of using `javascript:` within the `href` attribute. That means, replacing in every tpl, this:
...`href='javascript:sListView.order_checks(`...
with this:
...`href='#' onclick='sListView.order_checks(`...

#### Steps to Reproduce
1. Browse a ListView.
2. Click search button.
3. When data is shown, double click on sort action in any field.
4. A blank page with "false" on it shows, and in the URL you can see something like `javascript:sListView.order_checks("ASC", "{field}" , "Leads2_LEAD_ORDER_BY")`

#### Context
Error blank page when sorting records in ListView.

#### Your Environment
* SuiteCRM Version used: 7.10.x.
* Firefox (64-bit).
* MySQL, PHP 7.3.
* Ubuntu 18.04.

**Comment by Mac-Rae** [comment]
Hi @marin-h,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version.

Thanks :+1:

**Comment by mattlorimer** [comment]
This issue should be resolved in the current release
