### ISSUE TITLE
[RESOLVED] Unable to access Gmail from SuiteCRM Inbound Email Configuration

### ISSUE THREAD

**Issue by abeo** [salesagility/SuiteCRM#835]
When entering a Gmail address in Inbound Email Configuration an error is returned:  
Can't connect to gmail-imap.l.google.com,993: Network is unreachable
Please check your settings and try again.

Email error message from Gmail: Someone just tried to sign in to your Google Account [email hidden] from an app that doesn't meet modern security standards.

**Comment by chris001** [comment]
You have to either
1) go into your google account and enable "allow less secure apps" 
https://support.google.com/accounts/answer/6010255?hl=en
http://www.google.com/settings/security/lesssecureapps
Less secure apps are those such as SuiteCRM / SugarCRM, which store your cleartext gmail password on the CRM server.
2) request that SuiteCRM implement OAUTH2 for accessing your mail, OAUTH2 lets SuiteCRM store an "access token" for your password, you can revoke that gmail access token at any time in the google account web interface.
OAUTH2 is to help minimize and discourage hackers who break in your CRM server, (or evil admins who take home a backup copy of the server that they made as part of their job,) then search for email for passwords, and use the information in your gmail account for their own personal gain at your loss.  You just revoke the OAUTH2 token immediately upon detecting that your CRM server was hacked.  Saving you the trouble of changing your stored cleartext gmail password in CRM and 100 other apps that use your gmail account.

**Comment by abeo** [comment]
Thank Chris, 

Yes, my Gmail account is setup to allow IMAP and to  "allow less secure apps" for less secure apps. It just won't connect. 

I will submit a feature request for OAUTH2. 

~eric

**Comment by abeo** [comment]
Closing this as after double checking the Gmail account was not configured correctly. ~eric

**Comment by nikolricano** [comment]
Abeo what did you do wrong in the configuration? I am having the same trouble

**Comment by abeo** [comment]
Actually this never worked for me so I gave up.

**Comment by nikolricano** [comment]
Maybe this can help you, it worked for me:

[configurarCorreosSugarCRM.pdf](https://github.com/salesagility/SuiteCRM/files/1133318/configurarCorreosSugarCRM.pdf)

**Comment by Dillon-Brown** [comment]
Hi @abeo Thanks for the question! However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum). We will be able to help you with your issue there.

**Comment by softwarewala** [comment]
I think you need Suitecrm delivery partner support for configuring your Gmail account with suite crm. 
Say Hello with your Problem: info@techesperto.com
See SuiteCRM Partner Certification - https://suitecrm.com/portfolio-items/techesperto/
