### ISSUE TITLE
Missing datepicker in MassUpdate form for DateTime field

### ISSUE THREAD

**Issue by re8260** [salesagility/SuiteCRM#8351]
#### Issue

For field type `DateTime` missing calendar datepiccker in the massupdate form.
I added 2 custom fields `Date` and `DateTime` field :

![image](https://user-images.githubusercontent.com/18328936/70123333-1d80f300-167b-11ea-9dda-6561eb54a4aa.png)

For DateTime filed - no datepicker

![image](https://user-images.githubusercontent.com/18328936/70123452-63d65200-167b-11ea-8146-851eca088392.png)

For `Date` field - datepicker working correct

![image](https://user-images.githubusercontent.com/18328936/70123424-528d4580-167b-11ea-895e-2fc7bbbce6ba.png)

#### Steps to Reproduce

1. Add custom field of type DateTime with massupdate flag
2. open list view, select rows and click Bulk Action -> Mass Update
3. click on the calendar icon to select date

#### Expected Behavior

popup with date picker should be opend

#### Actual Behavior

Nothing is happens

#### Your Environment

* SuiteCRM Version used: 7.10.21
* Browser name and version (e.g. Chrome Version 78.0.3904.108 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7.2):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Hi @re8260,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version. Appears to only effect custom DateTime fields as core ones (Calls date start) works as expected.

Thanks :+1:

**Comment by re8260** [comment]
@Mac-Rae I will push MR to it now

**Comment by re8260** [comment]
@Mac-Rae FYI, fix MR: https://github.com/salesagility/SuiteCRM/pull/8353

**Comment by Mac-Rae** [comment]
Thanks @re8260, will take a look :+1:
