### ISSUE TITLE
V8 API Filtering W/ OR Operator Chained Conditions

### ISSUE THREAD

**Issue by Jason-Dang** [salesagility/SuiteCRM#8366]
#### Issue

When filtering on an API GET modules endpoint, using the `AND` operator to chain conditions appears to work fine with the below basic example. However, using the `OR` operator results in no filters being applied from what I can tell as all records are returned regardless of whether they match the criteria. 

Working `AND` example:
```
/V8/module/Accounts?filter[name][eq]=Test&filter[operator]=and&filter[account_type][eq]=Customer
```

Broken `OR` example:
```
/V8/module/Accounts?filter[name][eq]=Test&filter[operator]=or&filter[account_type][eq]=Customer
```

#### Expected Behavior

Only records matching the filter criteria should be returned and not the full list.

#### Actual Behavior

All filters are ignored and the full list is returned.

#### Possible Fix

Debug endpoint, identify where the filters are either overwritten or dropped and implement a fix.  

#### Steps to Reproduce

1. Create an Account record that matches the filter criteria outlined above.
2. Create a one or more Account records that does not match the criteria.
3. Apply the above outlined filters to the GET modules API call, targeting Accounts.
4. Run some more tests with varying modules and fields filtered etc. 

#### Context

High Priority - Unable to filter with multiple conditions using `OR` operator. This means the only way to achieve the same result is by making multiple calls (one for each option), which obviously increases overhead. 

#### Your Environment

* SuiteCRM Version used: 7.10.18
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Postman v6
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1, 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by ebogaard** [comment]
It seems the operator is having an unexpected side-effect, as it changes the query to the following:
```
SELECT COUNT(*) AS cnt FROM contacts WHERE contacts.xxx = 'yyy' OR contacts.deleted = '0'
```

Note the "OR contacts.deleted = '0'", which means that all non-deleted records are returned and the filter doesn't do a thing.
When using the and-operator, the query contains the expected "AND contacts.deleted = '0'".

**Comment by Jason-Dang** [comment]
> It seems the operator is having an unexpected side-effect, as it changes the query to the following:
> 
> ```
> SELECT COUNT(*) AS cnt FROM contacts WHERE contacts.xxx = 'yyy' OR contacts.deleted = '0'
> ```
> 
> Note the "OR contacts.deleted = '0'", which means that all non-deleted records are returned and the filter doesn't do a thing.
> When using the and-operator, the query contains the expected "AND contacts.deleted = '0'".

Good spot, if I get some spare time soon I’ll take a look at fixing this.

**Comment by ebogaard** [comment]
In "Api/V8/JsonApi/Repository/Filter.php" line 46, I can see that the "deleted = 0" condition is added tot the query parameters.
That probably means that it's treated as any other parameter and, hence, the operator.
I think this parameter should be added afterwards and kept separate from the other parameters.
