### ISSUE TITLE
Bump recommended PHP version to 7.2.0

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#8375]
#### Issue
Currently, SuiteCRM recommends PHP 7.1.0. That version is [EOL as of last week](https://www.php.net/eol.php).

We should update the recommended version in `php_version.php` to 7.2.0, or maybe even 7.3.0.

**Comment by Mac-Rae** [comment]
@Dillon-Brown

**Comment by ssnobben** [comment]
I know that Joomla new version J 4 is set to be in line with php 7.2.5 after analysis..
