### ISSUE TITLE
Deprecated messages in log

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#8376]
#### Issue

We have thousands of lines in the log like the following:

```
Mon Dec  9 14:34:10 2019 [24541][d3668622-dc93-d694-1818-5d5c459b00cd][DEPRECATED] PHP4 Style Constructors are deprecated and will be remove in 7.8, please update your code
```
This is very annoying if you are reading the log.

This was added in PR #1303 to fix Issue: #1300 

#### Expected Behavior

Those messages should be removed in SuiteCRM 7.8

#### Actual Behavior

A lot of annoying messages are stored in the log.

#### Possible Fix

We should remove legacy PHP4 Style Constructors.

#### Steps to Reproduce

1. Open the SuiteCRM log
2. Verify there are thousand of lines with that message

#### Your Environment

* SuiteCRM Version used: 7.10.x

**Comment by connorshea** [comment]
It was removed in develop, and AFAIK wasn't backported because it wasn't backwards compatible. Unfortunately that means we'd have to wait until 7.12/8.0.

**Comment by Abuelodelanada** [comment]
> It was removed in develop, and AFAIK wasn't backported because it wasn't backwards compatible. Unfortunately that means we'd have to wait until 7.12/8.0.

Yes, I think so @connorshea ...
I guess I'll have to appease the claims of the sysadmins :laughing:
