### ISSUE TITLE
Bug Menu Item

### ISSUE THREAD

**Issue by ExatechIT** [salesagility/SuiteCRM#839]
The Bugs Module does not appear on any menu's when added to Configure Module Menu Filters.
![untitled](https://cloud.githubusercontent.com/assets/16582470/12241643/60ee2912-b862-11e5-83a4-5fc7757d49f5.png)

**Comment by willrennie** [comment]
Is it enabled in 'Display modules and subpanels' within admin?

**Comment by ExatechIT** [comment]
Yup, that did it.  Thanks!
