### ISSUE TITLE
Cron.php isn't firing (or Schedulers aren't working)

### ISSUE THREAD

**Issue by jtottonb** [salesagility/SuiteCRM#8410]
#### Issue
 I'm trying to run the Google Calendar sync scheduler. 

I'm on a Windows shared hosting environment. Plesk is the admin portal. I've scheduled a task to run a php script and pointed it to cron.php. 

When I run the task, the task runs successfully (in Plesk), but has the following message: 
"Bad data passed in; <a href="http://crm.sitename.com">Return to Home</a>"

When I look at the schedulers in the Admin page of SuiteCRM, there are no completed jobs.

Update (12/29): I've stepped through and noticed that the failure happens at the following line of code: require_once('include/entryPoint.php');

#### Expected Behavior

The expected behavior is that the Scheduler shows a completed job.

#### Actual Behavior

There is no entry in the scheduler job log.

#### Possible Fix

Not sure.

#### Steps to Reproduce

1. Run cron.php from admin portal on a windows shared hosted environment.
2.
3.
4.

#### Context

I'm trying to sync my google calendar.

Medium priority

#### Your Environment

* SuiteCRM Version used: 7.11.70
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 79.0.3945.88
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Windows (shared hosting)

**Comment by pgorod** [comment]
@jtottonb I think you would get more feedback if you were asking about this in the correct place, the Forums:

https://community.suitecrm.com

Please post there and I will help you.

**Comment by jtottonb** [comment]
@pgorod: I've created a post here: https://community.suitecrm.com/t/cron-php-isnt-firing-or-schedulers-arent-working/70607
