### ISSUE TITLE
Run into an issue with PHP 7.4.1 claiming that it's deprecated

### ISSUE THREAD

**Issue by Blizzardo1** [salesagility/SuiteCRM#8419]
#### Issue
I get this message ```The recommended PHP version to install SuiteCRM is 7.1.0
Although the minimum PHP version required is 5.6.0, is not recommended due to the large number of fixed bugs, including security fixes, released in the more modern versions.
You are using PHP version 7.4.1, which is EOL: http://php.net/eol.php.
Please consider upgrading your PHP version. Instructions on http://php.net/migration70. ```

#### Expected Behavior
I should be able to setup the platform without ANY issues

#### Actual Behavior
What's to check when I can't get past the INSTALLATION page!?

#### Possible Fix
Suggest that PHP 7.4.1 is NOT EOL as IT IS NOT EOL

#### Steps to Reproduce
1. CLI: `php install.php` [Says it's fine]
2. Web: `https://ip/install.php` [Throws error]

#### Context
I can't setup the CRM because of this issue and it's frustrating me to the point where I'm just going to throw it to /dev/null and choose something that shouldn't be this tedious to setup, Docker Container, or NGINX, Unless you don't support NGINX, then we have a bigger issue.

#### Your Environment

* SuiteCRM Version used: Latest (7.11.*)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 71
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4.1
* Operating System and version (e.g Ubuntu 16.04): Debian 10

**Comment by Dillon-Brown** [comment]
Hi @Blizzardo1, I agree that the EOL message is misleading but the problem you're having here is more that we currently don't support PHP 7.4: https://docs.suitecrm.com/admin/compatibility-matrix/

**Comment by Blizzardo1** [comment]
Wonderful to hear that it's just misleading. Is there any time frame to support 7.4? In the meantime, I'll have to downgrade to 7.3 which in my opinion makes me a little uneasy, then again no version of PHP or any environment is safe... for long...

**Comment by Dillon-Brown** [comment]
@Blizzardo1 Ideally I'd like to say it will be supported for the next release but it might need to wait until 7.10.24/7.11.12 as we still have a couple of high priority blockers that need resolving.

It's very much something I'd like to get in so hopefully I can spare some time in the coming weeks to take a look at getting #7987 over the line. I'm happy to leave this one up as a bug in the meantime as it'll need to get resolved so we aren't reporting future versions after 7.4 as EOL.

Regarding the support for NGINX, I can confirm that this is currently supported and pretty widely used in the community but it's notably missing from [compatbility matrix](https://docs.suitecrm.com/admin/compatibility-matrix/) and we don't really have any specific documentation on it. That's also something we'll be looking to fix when we get a chance.

**Comment by connorshea** [comment]
I'd be happy to receive any help debugging this, because I haven't been able to figure out why this is happening. My suspicion would be that the constants for the minimum and recommended PHP versions aren't being loaded in PHP 7.4, which causes it to compare 7.4.0 against an undefined value, which makes it think it's EOL, but I don't really know how to test that theory :/ Maybe just echo-ing in the comparison function?

@Blizzardo1 could you replace the `check_php_version` function around line 3200 in `include/utils.php` with this version of the function and then retry the install?:

```php
function check_php_version($sys_php_version = '', $min_php_version = '', $rec_php_version = '')
{
    if ($sys_php_version === '') {
        $sys_php_version = constant('PHP_VERSION');
    }
    if ($min_php_version === '') {
        $min_php_version = constant('SUITECRM_PHP_MIN_VERSION');
    }
    if ($rec_php_version === '') {
        $rec_php_version = constant('SUITECRM_PHP_REC_VERSION');
    }
    echo "PHP_VERSION is {$sys_php_version}. SUITECRM_PHP_MIN_VERSION is {$min_php_version}. SUITECRM_PHP_REC_VERSION is {$rec_php_version}.";

    // versions below $min_considered_iis_version considered invalid by default,
    // versions equal to or above this ver will be considered depending
    // on the rules that follow
    $min_considered_iis_version = '6.0';
    $min_considered_iis_version = '6.0';
    // only the supported versions,
    // should be mutually exclusive with $invalid_iis_versions
    $supported_iis_versions = array('6.0', '7.0');
    $unsupported_iis_versions = array();
    $invalid_iis_versions = array('5.0');
    // default unsupported
    $retval = 0;
    // versions below $min_considered_iis_version are invalid
    if (1 == version_compare($sys_iis_version, $min_considered_iis_version, '<')) {
        $retval = -1;
    }
    // supported version check overrides default unsupported
    foreach ($supported_iis_versions as $ver) {
        if (1 == version_compare($sys_iis_version, $ver, 'eq') || strpos($sys_iis_version, $ver) !== false) {
            $retval = 1;
            break;
        }
    }
    // unsupported version check overrides default unsupported
    foreach ($unsupported_iis_versions as $ver) {
        if (1 == version_compare($sys_iis_version, $ver, 'eq') && strpos($sys_iis_version, $ver) !== false) {
            $retval = 0;
            break;
        }
    }
    // invalid version check overrides default unsupported
    foreach ($invalid_iis_versions as $ver) {
        if (1 == version_compare($sys_iis_version, $ver, 'eq') && strpos($sys_iis_version, $ver) !== false) {
            $retval = -1;
            break;
        }
    }
    return $retval;
}
```

I think it should output the system version, min version, and recommended version strings on the error page, which will hopefully help me figure out what's going on.

**Comment by connorshea** [comment]
Alright, I've figured out a fix even though it literally makes no sense whatsoever. #8424

@Blizzardo1 feel free to try applying the change from that PR in your CRM, it should fix the install erroring out.

**Comment by Blizzardo1** [comment]
Thank you, I will append this change and will try again and will also let you know if and once this fixes the issue. Dev Speed!

**Comment by Mac-Rae** [comment]
HI @Blizzardo1,

Did you have any luck with @connorshea's fix?

**Comment by Blizzardo1** [comment]
Hi @Mac-Rae I was able to use the site with PHP7.4 as this fix did the trick. I'm sorry that I'm late to let you all know.
