### ISSUE TITLE
AOS Setting don't save

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#8421]
#### Issue
When saving the AOS settings in the admin panel changes are not saved to config

#### Expected Behavior
Values set should be saved to config override

#### Actual Behavior
Values are not saved

#### Steps to Reproduce

1. Navigate to admin
2. Navigate to AOS settings
3. Add values and save
4. Check AOS Settings for saved values

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1 MYSQL
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by pgorod** [comment]
This can be closed now, right?
