### ISSUE TITLE
7.11.10 Report: date condition is saved in wrong format

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#8431]
#### Issue

Hi.
I've a custom Date/Time date_due_c field in Accounts. 
I've created a report based on Contacts with field condition on the accounts date_due_c Field greater than 01.01.2020 00:00 and saved it
When I edit the report again the date field in condition is empty.
When I check in database, the value of the date is stored in display format and not in db format.
When I change it to db format 2019-01-01 00:00:00  it is diplayed correctly but after saving it, it is stored in display format again and it doesn't work. 
 
![grafik](https://user-images.githubusercontent.com/16813374/71969784-abff0c00-3207-11ea-88bb-66d8c026f1ee.png)

#### Expected Behavior

should be stored in DB format.
#### Steps to Reproduce

1. create custum date/Time field in Accounts.
2.create report based on contacts and in condition use the custom field from Accounts.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.11.10  Check also in LTS. Ther is teh problem too.
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 
* Environment name and version (e.g. MySQL, PHP 7): php7.3 mysql 5.7
* Operating System and version (e.g Ubuntu 16.04): ubuntu 18.04

**Comment by Lehnerr** [comment]
I found the reason.
In modules/AOR_Conditions/AOR_Condition.php 
at about Line 130 there is a `$post_data[$key . $field_name][$i] = fixUpFormatting($_REQUEST['report_module'], $condition->field, $post_data[$key . $field_name][$i]);`

This will fix formating only on reports Module but we have to check the module from the condition. I changed to following and it works fine:
`                                _ppl('Correcting ModuleName');
                                global $beanList;
                                foreach ($beanList as $K => $V ){
                                    if (strtolower($_REQUEST['aor_conditions_module_path'][$i]) == strtolower($K)){
                                        $aor_conditions_module= $K;
                                    }
                                }
                                //$post_data[$key . $field_name][$i] = fixUpFormatting($_REQUEST['report_module'], $condition->field, $post_data[$key . $field_name][$i]);
                                $post_data[$key . $field_name][$i] = fixUpFormatting($aor_conditions_module, $condition->field, $post_data[$key . $field_name][$i]);
  `

**Comment by Mac-Rae** [comment]
@Lehnerr if thats a fix will you put a PR up for it and ill test it for you?

**Comment by Lehnerr** [comment]
I don't know how to create a PR.

**Comment by pgorod** [comment]
@Lehnerr 

If you need help creating a PR... For a single file fix, it's easy to do from Github website, without a local `git` required.

Just go to this file (the same file on the `hotfix-7.10.x` branch):

https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/modules/AOR_Conditions/AOR_Condition.php#L129

Then click the ✏️ pencil icon to edit it. Make your changes and save. This does a few things:

- forks the SuiteCRM repo onto your own user area;
- creates a new patch branch under your `hotfix-7.10.x` there;
- commits your new file in that branch

After that, it immediately offers to create the PR to propose the same change in our main repo. Just make sure it's pointed at `SalesAgility/SuiteCRM:hotfix-7.10.x`, fill in the template and create the PR.

Tell me if you need more help. Thanks for contributing!

**Comment by Lehnerr** [comment]
Hi.Problem doesn't occur  in7.11.13.
