### ISSUE TITLE
Update to 7.11.10 gives database error on MSSQL

### ISSUE THREAD

**Issue by gerdb42** [salesagility/SuiteCRM#8432]
On update, a database error is thrown when index `idx_user_name` is to be created on table `users`. Reason is that it tries to create the index with fields `last_name (30)` and `first_name (30)`. These partial Indexes are not allowed in MSSQL. Please remove partial length specification.

File affected: `SuiteCRM-Upgrade-7.11.x-to-7.11.10\scripts\files_to_add_post\modules\Users\vardefs.php`

Environment:
Windows 2012R2
Apache 2.4.39
PHP 7.3.6
SQL Server 2014

**Comment by Mac-Rae** [comment]
@Dillon-Brown
