### ISSUE TITLE
Quotes issue - List field overwrite Sale Price field

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#844]
I tested it on my SuiteCRM 7.4.3 and also on Demo of SuiteCRM official

![quota](https://cloud.githubusercontent.com/assets/5773777/12296823/5008ca40-ba0a-11e5-889c-704d7a1b2158.png)

This screenshot is from official DEMO SuiteCRM on demo.suiteondemand.com

The issue is if you add the group of Product or Service Line and the List field overwrite you the  Sale Price. If you want change the Sale Price, still change you it to same value as has List Field

Here is the short video with the issue:  http://screencast.com/t/LjH1ktNi

Miky

**Comment by CaptainChainsaw** [comment]
This is by design as I understand it.  If you want to reduce the sale price then you would enter a discount value.

**Comment by Mausino** [comment]
That my question is: when i have product... which price is for 1 piece... and this piece have price... and i will need change it to 200 pieces, where i can to this ? as normal person change value of List and this rate for me price... i dont need the discount... i need have in product the price of one piece and in quote or contract i need change numbers of this pieces, and program muss automaticaly rate the end price.

That is my opinion. :)

**Comment by Mausino** [comment]
Hi, now we solved this problem by adding the Quantity field to Service line (row) :) I am sure that this solved our problem and i think, that will help to other users by everyday using of SuiteCRM

I advice to add this new field + also the field Notice field to "Service row" into quotes in SuiteCRM

![quantity](https://cloud.githubusercontent.com/assets/5773777/17168056/874260b4-53e0-11e6-8933-98f515cc604f.png)
