### ISSUE TITLE
No or not complete Searchresults using elasticsearch engine 

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#8472]
#### Issue

I got no or incomplete Searchresults when using elasticsearch engine.
I configured Opportunities,Accounts,Contacts,Calls,AOS_Contracts for global search.
I cleaned the elasticsearch index and started full indexing.
In search_index.log I got no errors and all is finished:
Finished Opportunities. Processed 10969 Records [] [
Finished Accounts. Processed 14587 Records [] []
Finished Contacts. Processed 6831 Records [] []
Finished Calls. Processed 1544 Records [] []
Finished Tasks. Processed 28127 Records [] []
Finished AOS_Contracts. Processed 407 Records [] []
6 modules, 62465 records and 1818702 fields indexed in 122.238 s [] []

In elasticsearch.log, Apache error.log and suitecrm logs are no errors

When I now search I get always different outputs and often no output:
ie: When i searched for Raiffeisen. I get only Accounts, and no other entries from other modules.
![grafik](https://user-images.githubusercontent.com/16813374/72972621-14cfb200-3dcc-11ea-832f-fcdcc89439ec.png)

When I look for Raiff only, i get no results:
![grafik](https://user-images.githubusercontent.com/16813374/72972709-392b8e80-3dcc-11ea-9c95-3aba6f2aafd7.png)

When I look for Raiff* , I get only Accounts again but more than the fist search result:
![grafik](https://user-images.githubusercontent.com/16813374/72972990-b22ae600-3dcc-11ea-80c0-5e43c41f34fd.png)
 
When I search for a Opportunity I get always no results. When I seach for users, I get sometimes a result with some modules but not always

 The only error I can see is in apache error.log:
 PHP Recoverable fatal error:  Object of class Link2 could not be converted to string in /var/www/sugarcrm/lib/Search/SearchResults.php on line 213, referer: https://XXXX/sugarcrm/index.php?action=Search&search-query-string=Raiff*&search-query-size=10&search-query-from=10&search-engine=ElasticSearchEngine 

#### Expected Behavior

All entries and should be displayed 
#### Actual Behavior

incomplete results
#### Possible Fix

?
#### Steps to Reproduce

?
#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actual Browsers
* Environment name and version (e.g. MySQL, PHP 7): 7.2
*Operating System and version (e.g Ubuntu 16.04): ubuntu 18.04
* elasticsearch 5.6.16

**Comment by pgorod** [comment]
I believe the default wildcard is %, not *

Have you tried the config_override options?

`search_wildcard_infront`
`search_wildcard_char`

You'll find some results in Google explaining these. Does it solve your issue?

Thanks

**Comment by tsitle** [comment]
I've been playing around with the Elasticsearch implementation and have found
that having the "Advanced OpenDiscovery" (AOD) service enabled can create quite some confusion
when trying to figure out whether some records where indexed by Elasticsearch or not.
Plus it should be completely redundant if Elasticsearch is enabled.
I believe that @pgorod 's advice is very helpful, too.

What I came up with are the following lines in the `config_override.php`:
```
$sugar_config['search_wildcard_char'] = '%';  // this is default anyway
$sugar_config['search_wildcard_infront'] = true;
$sugar_config['aod']['enable_aod'] = false;
$sugar_config['search']['defaultEngine'] = 'ElasticSearchEngine';
$sugar_config['search']['ElasticSearch']['enabled'] = true;
$sugar_config['search']['ElasticSearch']['host'] = '<YOUR_ES_HOST>';
```
These set the wildcard options as suggested by @pgorod, disable the AOD service
and define Elasticsearch as default search engine.
If you'd like to use the asterisk ('*') as wildcard character you'd obviously have to use the following line:
```
$sugar_config['search_wildcard_char'] = '*';
```

Additionally I've disabled the Scheduler jobs "Perform Lucene Index" and "Optimise AOD Index" in the Admin panel -> Scheduler.

**Comment by Lehnerr** [comment]
I've tried:
$sugar_config['search_wildcard_char'] = '%';  
$sugar_config['search_wildcard_infront'] = true;
$sugar_config['aod']['enable_aod'] = false;
$sugar_config['search']['defaultEngine'] = 'ElasticSearchEngine';
$sugar_config['search']['ElasticSearch']['enabled'] = true;

Nothing has changed.

**Comment by tsitle** [comment]
@Lehnerr : For the sake of completeness I just added another line to the above config values:
```
$sugar_config['search']['controller'] = 'Search';
```
It looks like you propably already had that config value set in either `config.php` or `config_override.php`

**Comment by tsitle** [comment]
@Lehnerr I just opened the PR #8513 which should hopefully fix the issue you were experiencing.
