### ISSUE TITLE
Discrepancy in installation zip files between SuiteCRM.com and GitHub.com

### ISSUE THREAD

**Issue by jon-freed** [salesagility/SuiteCRM#848]
The 7.4.3 zip file at https://github.com/salesagility/SuiteCRM/archive/v7.4.3.zip does **not** contain a cache sub-folder.  (I used that URL with wget in accordance with [the releases page](https://github.com/salesagility/SuiteCRM/releases) and also as per [a forum post](https://suitecrm.com/community/suitecrm-7-0-discussion/3721-need-help-downloading-in-ubuntu).)

On the other hand, the 7.4.3 zip file at https://suitecrm.com/download **does** contain the cache sub-folder.

I first tried my install with the github no-cache folder version.  When the install said the cache folder was missing I just manually created an empty cache folder and restarted the install.  I was able to complete the install, but when I logged in the first time I got 403 errors on a number of files in the cache sub-folder.  The files had been created by the install, but they just weren't accessible to the end user.  (See attached screenshot.)
![screenshot](https://cloud.githubusercontent.com/assets/6800576/12355923/ce8c6016-bb6d-11e5-86fb-b01602d06a71.jpg)

I next tried an install with the suitecrm.com version of the zip file.  When I logged in I did not get the 403 errors as before.  

I'm a first time user and I'm looking forward to exploring!

**Comment by mattlorimer** [comment]
this is purely for convenience to speed up the install process, the cache will be build if its not present, if it isn't it generally means the permission are not set correctly so fails
