### ISSUE TITLE
API V8 file upload to Documents module fails with `Property filename_file in Document module is invalid`

### ISSUE THREAD

**Issue by atelierJVA** [salesagility/SuiteCRM#8494]
I have searched for similar issues but I could not find any. The only one related is #6362.

#### Issue

 I am trying to upload a file to Documents using the following V8 API call

Endpoint: `<base_url>/Api/V8/module`
Payload:
```
{
	"data":{
		"attributes": {
			"document_name": "some document",
		     "filename": "some_document.pdf",
		     "filename_file": "ZmlsZSBjb250ZW50",
		     "revision": "1"
		},
		"type": "Documents"
	}
}
```

#### Expected Behavior
A document created in the Documents module with the upload file attached to it.

#### Actual Behavior
The following error is returned:
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Property filename_file in Document module is invalid"
    }
}
```

#### Steps to Reproduce
- Install SuiteCRM
- Configure  API use following the documentation
- Use postman to run the request

#### Your Environment

* SuiteCRM Version used: 7.10.22 fresh install
* Environment name and version: MySQL / PHP 7.2
* Operating System and version: macOS 10.15.2

**Comment by Mac-Rae** [comment]
Hi @atelierJVA,

I believe this feature is within the next release, let me know if this looks like the correct thing;
https://github.com/salesagility/SuiteCRM/pull/8408

**Comment by atelierJVA** [comment]
Hi @Mac-Rae,

Yes, that is what I want to achieve. The only thing is that #8408 seems to be focused in the Notes module, and we need to update files for the Documents module (although, it would be great to have this option in any module that extends the `File` class.
Any ETA for the next release?

**Comment by ivanfr90** [comment]
Hi @Mac-Rae,

Has been released the fix to this bug?

I have the same issue:

**Endpoint** 
<base_url>/Api/V8/module

**Payload**
```
{
  "data": {
    "type": "Documents",
    "attributes": {
      "name": "TEST FILE",
      "document_name": "TEST FILE",
      "filename": "fichero_prueba.txt",
      "filename_file": "MTIzNDU=",
      "revision": "1"
    }
  }
}
```

**Actual Behavior**
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Property filename_file in Document module is invalid"
    }
}
```

**Environment**
    SuiteCRM Version: 7.11.4

**Comment by sheathy** [comment]
Hi @Mac-Rae 

Any news on this fix?

Uploading documents is still a problem in 7.11.15 (same response as mentioned above), this is a much needed feature.

Cheers

**Comment by Mac-Rae** [comment]
Hey @sheathy,

I'm not 100% sure on this one. The original fix PR should be in but if your saying the documetion side of the functionality still doesn't work then I'd have to take a look. Will update you with my findings in a bit. In short I'm sure it will be included in 7.12 at very worst as it feels like a must have to me 👍

**Comment by sheathy** [comment]
Hi @Mac-Rae @Dillon-Brown 

Any news on this? The inability to upload files using the API is a deal breaker for me!

Cheers

**Comment by Mac-Rae** [comment]
Hi @sheathy,

Working on a workaround that I can get out to you should it work. If so hopefully in the next 7.11 release also :+1:

Will keep you updated

**Comment by sheathy** [comment]
Hi @Mac-Rae 

Legend. Thanks for your help.

**Comment by Mac-Rae** [comment]
Hi @sheathy,

Tested a customisation (Made by @PedroErnst :clap: ) that will resolve your issues for now until its converted and pushed into the core. Anyone who wants to try it out please give me a shout and ill fire it over :+1:

**Comment by sheathy** [comment]
Hi @Mac-Rae 

Yes please! I will give it a try, let me know where to get the code.

Cheers

**Comment by Mac-Rae** [comment]
Assuming your API is working as expected all you need to do is drop the files from [this gist](https://gist.github.com/Mac-Rae/64d9f79edceb0557391d3a66244de5b0) into the CRM,

Copy the files to these locations;
`custom/application/Api/V8/Service/CustomModuleService.php`
`custom/application/Api/V8/services.php`
`custom/Extension/modules/Documents/Ext/Vardefs/Documents.php`

Then run a Quick Repair and Rebuild and you should be good to try uploading using the following method.

Note: Like notes, you have to base64 encode what you upload

```
{
  "data": {
    "type": "Documents",
    "attributes": {
        "filename":"test.txt",
        "document_name":"test.txt",
        "filecontents": "VGhpcyBpcyBhIHRleHQgZmlsZQ=="
    }
  }
}
```

(I was using postman however whatever method you use should be good hopefully)

**Comment by sheathy** [comment]
Hi @Mac-Rae 

I followed the instructions and I now get the following error:

{
  "errors": {
    "status": 400,
    "title": null,
    "detail": "Notes module with id e4ba9428-8fad-6cc8-a9da-5f983f3ac1de is not found"
  }
}

Any ideas what I may of missed?

Cheers

**Comment by Mac-Rae** [comment]
Assuming your API is working as expected all you need to do is drop the files from #8910 into the CRM,

Copy the files to these locations;
`Api/V8/Service/ModuleService.php`
`modules/Documents/vardefs.php`

Then run a Quick Repair and Rebuild and you should be good to try uploading using the following method.

Note: Like notes, you have to base64 encode what you upload

```
{
  "data": {
    "type": "Documents",
    "attributes": {
        "filename":"test.txt",
        "document_name":"test.txt",
        "filecontents": "VGhpcyBpcyBhIHRleHQgZmlsZQ=="
    }
  }
}
```

(I was using postman however whatever method you use should be good hopefully)

**Comment by sheathy** [comment]
Hi @Mac-Rae 

Sorted, it works perfectly. Thank you for your help with this, much appreciated.

Cheers

**Comment by Mac-Rae** [comment]
Glad to hear @sheathy, if you want to put a comment on the PR saying the same it would help in getting it merged :+1:
