### ISSUE TITLE
Calls status dropdown new items dont move call from Activities to History

### ISSUE THREAD

**Issue by communig8-public** [salesagility/SuiteCRM#8500]
#### Issue
If new Items are added to the Calls Module Status DropDown field and a Call is set to a new Status, the call does not move from the Activities subpanel to the History subpanel of another Modes's DetailView page. Only changing the Status to the original "Held" or "Not Held" statuses causes the move.

#### Expected Behavior
Setting a status to anything other than "Planned" should cause the Call to move out of the Activities subpanel to the History subpanel.

#### Actual Behavior
Any status other than "Held" and "Not Held" remain in the Activities subpanel.

#### Steps to Reproduce
1. In Studio add another item to the Calls Modules's Status field dropdown list.
2. Create a new Call record in Accounts with the default status of "Planned".
3. Call shows in Accounts Activities subpanel.
4. Edit the Call record and change the status to the new status.
5. The Call stays in the Activities subpanel.

#### Context
This prevents us from adding a Status that gives more detail on why a call was not held.

#### Your Environment
* SuiteCRM Version used: Version 7.11.10
* Browser name and version: Any
* Environment name and version: MySQL Ver 14.14 Distrib 5.7.29, for Linux (x86_64), PHP 7.2.24-0ubuntu0.18.04.2
* Operating System and version: 18.04.3 LTS (GNU/Linux 4.15.0-1054-aws x86_64)

**Comment by Mac-Rae** [comment]
Hi @communig8-public,

Sounds correct to me, when a call is Held or Not Held then it is moved to the history otherwise it remains as an activity. You could work around this using workflows or logic hooks to get the functionality you want.

If you believe this to be an issue, please leave a comment with further justification otherwise this issue will be closed.

Thanks :+1:

**Comment by communig8-public** [comment]
OK understood
