### ISSUE TITLE
dropdown editor: can't save new dropdown list (empty line and integers)

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#8512]
#### Issue

can't save dropdown lists when starting with empty line combined with integers as item name in the second line.

#### Expected Behavior

User can save dropdown lists using integers (e.g. "0") as item names and using an empty line as first line.

#### Actual Behavior

User can enter items with integer as item name e.g. "0" and empty line as first line.
But when user hits save => user sees popup "Loading... in progress"
=> list is never saved.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/15463075/73596130-da7ab900-451f-11ea-9e5f-0f093345e426.png">

#### Steps to Reproduce

1. Open Studio Dropdown Editor
2. click add dropdown
3. enter list name
4. Add empty line
5. enter Item Name "0" and Display Label "0" => Add
6. Save 

#### Your Environment

* SuiteCRM Version used: Version 7.10.22
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari Mac

**Comment by Mac-Rae** [comment]
Hi @EZS-JD,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.x or 7.11.x. If you believe this to be an issue still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:
