### ISSUE TITLE
v7.5 JS files not found on homepage

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#852]
404 not found for the following files on the home page
    - custom/include/MySugar/javascript/AddRemoveDashboardPages.js 
    - custom/include/MySugar/javascript/retrievePage.js 

Fix applied to
themes/SuiteR/tpls/MySugar.tpl:156
I've just reference the one on the native includes directory

**Comment by dearaujoj** [comment]
Hi guys,
is it supposed to be included in 7.5.1 ? Because I have just installed a fresh version for testing and the themes/SuiteR/tpls/MySugar.tpl template still contains the wrong path.
