### ISSUE TITLE
User import message

### ISSUE THREAD

**Issue by rouhu** [salesagility/SuiteCRM#8521]
SuiteCRM 7.11.10. When importing users from CSV file and during submit of the Step 4, a popup message comes "Provide Both User Name and Email Address" even if all mandatory fields are provided. Despite of the message first 100 users are imported but the last page (Step 5) does not load.

**Comment by Mac-Rae** [comment]
Would you be able to provide demo data to allow us to test? Ensure there not live data or confidential data :+1:

**Comment by pgorod** [comment]
I think the system is failing to generate a password for the new users, are you providing a hash?

Do you have "system genereated" passwords option set to on?

https://github.com/salesagility/SuiteCRM/blob/master/modules/Users/User.php#L2390

These are just pointers for exploration, I think there might be a bug here anyway, or at least a better message would be appropriate.

**Comment by rouhu** [comment]
Here is test data. You only get to step 5 if you make intentional error on import data.

First Name,Last Name,username,status,email address,system generated password
Jack,Jones,jack.jones,active,jack@jones.com,1

**Comment by pgorod** [comment]
It works if you set `system generated password` to 0

I'm not sure if you should be attemtpting to get the system to generate passwords during the import, because I don't see any signs that SuiteCRM is ready to do that - it's likely nobody ever thought of this or wrote any code for it.

You can generate one yourself and provide it in `user_hash` field.

**Comment by rouhu** [comment]
Are you able to get to the last page of the import wizard by setting "system generated password" to zero, because I am not ?

Test data:
First Name,Last Name,username,status,email address,system generated password
Jack,Jones,jack.jones,active,jack@jones.com,0

**Comment by pgorod** [comment]
It stays in the same page of the wizard, but it doesn't give that error, and the user is created successfully.

**Comment by Mac-Rae** [comment]
@rouhu @pgorod This one still an issue i never got time to check?

**Comment by pgorod** [comment]
I think it can be closed...

It's true that some improvement could be made here, and code could be written for this case. But I don't see it happening soon, it's more of a suggestion, so I guess the issue can be closed, it's still here for reference in case somebody searches for it later.

**Comment by Mac-Rae** [comment]
@rouhu I'll close this issue for now however if you would prefer this be left as a suggestion please let me know.

**Comment by rouhu** [comment]
We need to import 5000 users but import only works for the first 100 records. Looks like a defect to me.

**Comment by pgorod** [comment]
That's probably your PHP resource settings limiting you. If you ask about that in the Forums you will likely get appropriate help
.

**Comment by rouhu** [comment]
I have tested it in newly installed SuiteCRM 7.11.15 and only first 100 records is imported. 
You may try with the test data below:
First Name,Last Name,username,status,email address,system generated password
jack,Jones,jack.jones1,active,jack.jones1@jones.com,0
jack,Jones,jack.jones2,active,jack.jones2@jones.com,0
jack,Jones,jack.jones3,active,jack.jones3@jones.com,0
jack,Jones,jack.jones4,active,jack.jones4@jones.com,0
jack,Jones,jack.jones5,active,jack.jones5@jones.com,0
jack,Jones,jack.jones6,active,jack.jones6@jones.com,0
jack,Jones,jack.jones7,active,jack.jones7@jones.com,0
jack,Jones,jack.jones8,active,jack.jones8@jones.com,0
jack,Jones,jack.jones9,active,jack.jones9@jones.com,0
jack,Jones,jack.jones10,active,jack.jones10@jones.com,0
jack,Jones,jack.jones11,active,jack.jones11@jones.com,0
jack,Jones,jack.jones12,active,jack.jones12@jones.com,0
jack,Jones,jack.jones13,active,jack.jones13@jones.com,0
jack,Jones,jack.jones14,active,jack.jones14@jones.com,0
jack,Jones,jack.jones15,active,jack.jones15@jones.com,0
jack,Jones,jack.jones16,active,jack.jones16@jones.com,0
jack,Jones,jack.jones17,active,jack.jones17@jones.com,0
jack,Jones,jack.jones18,active,jack.jones18@jones.com,0
jack,Jones,jack.jones19,active,jack.jones19@jones.com,0
jack,Jones,jack.jones20,active,jack.jones20@jones.com,0
jack,Jones,jack.jones21,active,jack.jones21@jones.com,0
jack,Jones,jack.jones22,active,jack.jones22@jones.com,0
jack,Jones,jack.jones23,active,jack.jones23@jones.com,0
jack,Jones,jack.jones24,active,jack.jones24@jones.com,0
jack,Jones,jack.jones25,active,jack.jones25@jones.com,0
jack,Jones,jack.jones26,active,jack.jones26@jones.com,0
jack,Jones,jack.jones27,active,jack.jones27@jones.com,0
jack,Jones,jack.jones28,active,jack.jones28@jones.com,0
jack,Jones,jack.jones29,active,jack.jones29@jones.com,0
jack,Jones,jack.jones30,active,jack.jones30@jones.com,0
jack,Jones,jack.jones31,active,jack.jones31@jones.com,0
jack,Jones,jack.jones32,active,jack.jones32@jones.com,0
jack,Jones,jack.jones33,active,jack.jones33@jones.com,0
jack,Jones,jack.jones34,active,jack.jones34@jones.com,0
jack,Jones,jack.jones35,active,jack.jones35@jones.com,0
jack,Jones,jack.jones36,active,jack.jones36@jones.com,0
jack,Jones,jack.jones37,active,jack.jones37@jones.com,0
jack,Jones,jack.jones38,active,jack.jones38@jones.com,0
jack,Jones,jack.jones39,active,jack.jones39@jones.com,0
jack,Jones,jack.jones40,active,jack.jones40@jones.com,0
jack,Jones,jack.jones41,active,jack.jones41@jones.com,0
jack,Jones,jack.jones42,active,jack.jones42@jones.com,0
jack,Jones,jack.jones43,active,jack.jones43@jones.com,0
jack,Jones,jack.jones44,active,jack.jones44@jones.com,0
jack,Jones,jack.jones45,active,jack.jones45@jones.com,0
jack,Jones,jack.jones46,active,jack.jones46@jones.com,0
jack,Jones,jack.jones47,active,jack.jones47@jones.com,0
jack,Jones,jack.jones48,active,jack.jones48@jones.com,0
jack,Jones,jack.jones49,active,jack.jones49@jones.com,0
jack,Jones,jack.jones50,active,jack.jones50@jones.com,0
jack,Jones,jack.jones51,active,jack.jones51@jones.com,0
jack,Jones,jack.jones52,active,jack.jones52@jones.com,0
jack,Jones,jack.jones53,active,jack.jones53@jones.com,0
jack,Jones,jack.jones54,active,jack.jones54@jones.com,0
jack,Jones,jack.jones55,active,jack.jones55@jones.com,0
jack,Jones,jack.jones56,active,jack.jones56@jones.com,0
jack,Jones,jack.jones57,active,jack.jones57@jones.com,0
jack,Jones,jack.jones58,active,jack.jones58@jones.com,0
jack,Jones,jack.jones59,active,jack.jones59@jones.com,0
jack,Jones,jack.jones60,active,jack.jones60@jones.com,0
jack,Jones,jack.jones61,active,jack.jones61@jones.com,0
jack,Jones,jack.jones62,active,jack.jones62@jones.com,0
jack,Jones,jack.jones63,active,jack.jones63@jones.com,0
jack,Jones,jack.jones64,active,jack.jones64@jones.com,0
jack,Jones,jack.jones65,active,jack.jones65@jones.com,0
jack,Jones,jack.jones66,active,jack.jones66@jones.com,0
jack,Jones,jack.jones67,active,jack.jones67@jones.com,0
jack,Jones,jack.jones68,active,jack.jones68@jones.com,0
jack,Jones,jack.jones69,active,jack.jones69@jones.com,0
jack,Jones,jack.jones70,active,jack.jones70@jones.com,0
jack,Jones,jack.jones71,active,jack.jones71@jones.com,0
jack,Jones,jack.jones72,active,jack.jones72@jones.com,0
jack,Jones,jack.jones73,active,jack.jones73@jones.com,0
jack,Jones,jack.jones74,active,jack.jones74@jones.com,0
jack,Jones,jack.jones75,active,jack.jones75@jones.com,0
jack,Jones,jack.jones76,active,jack.jones76@jones.com,0
jack,Jones,jack.jones77,active,jack.jones77@jones.com,0
jack,Jones,jack.jones78,active,jack.jones78@jones.com,0
jack,Jones,jack.jones79,active,jack.jones79@jones.com,0
jack,Jones,jack.jones80,active,jack.jones80@jones.com,0
jack,Jones,jack.jones81,active,jack.jones81@jones.com,0
jack,Jones,jack.jones82,active,jack.jones82@jones.com,0
jack,Jones,jack.jones83,active,jack.jones83@jones.com,0
jack,Jones,jack.jones84,active,jack.jones84@jones.com,0
jack,Jones,jack.jones85,active,jack.jones85@jones.com,0
jack,Jones,jack.jones86,active,jack.jones86@jones.com,0
jack,Jones,jack.jones87,active,jack.jones87@jones.com,0
jack,Jones,jack.jones88,active,jack.jones88@jones.com,0
jack,Jones,jack.jones89,active,jack.jones89@jones.com,0
jack,Jones,jack.jones90,active,jack.jones90@jones.com,0
jack,Jones,jack.jones91,active,jack.jones91@jones.com,0
jack,Jones,jack.jones92,active,jack.jones92@jones.com,0
jack,Jones,jack.jones93,active,jack.jones93@jones.com,0
jack,Jones,jack.jones94,active,jack.jones94@jones.com,0
jack,Jones,jack.jones95,active,jack.jones95@jones.com,0
jack,Jones,jack.jones96,active,jack.jones96@jones.com,0
jack,Jones,jack.jones97,active,jack.jones97@jones.com,0
jack,Jones,jack.jones98,active,jack.jones98@jones.com,0
jack,Jones,jack.jones99,active,jack.jones99@jones.com,0
jack,Jones,jack.jones100,active,jack.jones100@jones.com,0
jack,Jones,jack.jones101,active,jack.jones101@jones.com,0
jack,Jones,jack.jones102,active,jack.jones102@jones.com,0
jack,Jones,jack.jones103,active,jack.jones103@jones.com,0
jack,Jones,jack.jones104,active,jack.jones104@jones.com,0
jack,Jones,jack.jones105,active,jack.jones105@jones.com,0
jack,Jones,jack.jones106,active,jack.jones106@jones.com,0
jack,Jones,jack.jones107,active,jack.jones107@jones.com,0
jack,Jones,jack.jones108,active,jack.jones108@jones.com,0
jack,Jones,jack.jones109,active,jack.jones109@jones.com,0

**Comment by pgorod** [comment]
I had a run with the debugger, I didn't fix the problem but I can give you a few insights:

Despite your field specifying zero for the generated passwords, it's looking at the system options instead:

https://github.com/salesagility/SuiteCRM/blob/master/modules/Users/User.php#L990

And it is generating passwords, though it seems to start failing after a while (weird, no?)

I am not sure if this is the problem, but at least I know the error you're getting comes from there:

https://github.com/salesagility/SuiteCRM/blob/master/modules/Users/GeneratePassword.php#L104

I don't think that stopping after 100 means much, I bet it's just that it accumulates errors and stops after a batch. To confirm this you can try changing [this number here](https://github.com/salesagility/SuiteCRM/blob/master/modules/Import/ImportFileSplitter.php#L92) (to 10, for example) and restarting the import, see if it fails after just 10 records.

I also advise that after each attempt of the import you delete the previous imported rows from both the `users` and the `email_addresses` tables.

**Comment by rouhu** [comment]
After changing the config.php parameter to
'import_max_records_per_file' => 110,
I was able to import all test rows.

Thank you for providing this workaround.

**Comment by chris001** [comment]
@rouhu For comparison, try importing your 109 users on the demo site https://demo.suiteondemand.com and see if it fails the same way as your server.  It should fail the same way.
