### ISSUE TITLE
User Profile Folder Managment creating duplicate/incorrect Email folder subscriptions

### ISSUE THREAD

**Issue by stratacorps** [salesagility/SuiteCRM#8522]
#### Issue

Users cannot select which Mail account folders to view, any attempts to use the User Profile+Settings panel results in duplicate folder subscriptions. Also, users are automatically subscribed to all folders including other users' personal email accounts.

//SuiteCRM log will eventual show 'Duplicated folder detected' errors

Additionally, the Mail Accounts panel has checkboxes to select Group Emails, but checking/unchecking the Active checkbox continues to duplicate folder subscriptions for ALL folders, automatically selecting them in the General tab's Available User Folders select/options element.
#### Expected Behavior

The Folder Management select list should be properly initialized with all folders available to that user with any folder id selected if the user is already subscribed to that folder.

The user should then be able to change that selection using the click/multi-select UI

The folders_subscription table should be updated with the folders that are selected.

When a user selects the Active checkbox for any Group email account in the Mail Accounts tab, the Available User Folders list should be updated to include (active checked) or exclude (active unchecked) from the options list.

Selecting --None-- should remove all subscriptions for the user.

The user should not see other users personal inbound email accounts.

#### Actual Behavior

When any selection is attempted in:

	User Profile--Settings--General (tab)--Folder Management
	-or-
	User Profile--Settings--Mail Accounts (tab)--Mail Accounts Active checkbox check/uncheck

The function updateSubscriptions in EmailUI.js is invoked.

This function incorrectly appends the table folders_subscription with every available folder that is in the folder table, even if the folder has already been subscribed to by that user.

In addition, the GUI in the Settings panel doesn't allow you to select/deselect any entry displayed by the rebuildFolders function. Also, checking/unchecking the Active checkbox in the Mail Accounts tab also invokes the updateSubscriptions function, and automatically changes the DOM for each selectable entry in userFolders select/option list (each item is forced to 'selected').

There isn't any way to deselect, all Available User Folders are selected.

Attempting to select/multi-select elements modifies the folder list somewhat, but not correctly.

When the User Profile [index.php?module=Users&action=EditView&record=xxxxxx] is displayed, the rebuildFolders script in EMailUI.js is initialized.

Then when the Settings button is clicked, SUGAR.email2.settings.showSettings(getUserEditViewUserId()) is invoked.

This displays the Settings panel for the User's email settings.

When the panel is first displayed, everything appear normal (if the user has visited and attempted to interact with the Folders at all, they will probably see ALL folders in the system and they will be selected. Also any group Email will be checked Active in the Mail Accounts tab).

Any interaction with any element in the userFolders select/option list will trigger the updateSubscription function, which continues to append the folders_subscriptions table creating duplicate subscriptions for the folder/user. This table doesn't have a unique key restriction, which allows it to continue.

The logs will begin to show "Duplicated folder detected" errors.

Any user will be able to view/read any other user's Email defined by other users.

#### Steps to Reproduce

1. Create a new user
2. Login as that user and edit the profile (/index.php?module=Users&action=EditView&record={current_user->id}
3. Note: on load, rebuildFolders in EmailUI.js calls the ajax routine getAllFoldersTree in EmailUIAjax.php
(/index.php?sugar_body_only=true&to_pdf=true&module=Emails&action=EmailUIAjax&emailUIActions=getAllFoldersTree&user=xxxxxx
4. The new user doesn't have any email accounts created for them so some errors are showing up in the suitecrm.log:
```
[ERROR] error: no ieID
[ERROR]  SugarFolder::retrieveFoldersForProcessing() Cannot Retrieve Folders - Please check the users inbound email settings.
```
5. Click Settings to invoke SUGAR.email2.settings.showSettings(getUserEditViewUserId());
6. No items are available initially in the Available User Folders and all Group accounts are selected as Active in the Mail Accounts tab.
7. Click on ANY element in the userFolders UI (this causes updateSubscriptions to be called, populating the folders_subscriptions table with entries for every group and personal folder the their sub-folders defined in the system including other users' personal accounts).
8. Click again on any element in the UI.
9. Now Duplicated folder detected errors appear in the log and the folders_subscriptions table is appended with duplicate folder subscriptions.

#### Context

Users are allowed access to other user's personal email (security)
Errors result in duplicate folder subscriptions
Users can't select from which folders they wish to view

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any (Firefox, Safari, Chrome)
* Environment name and version (e.g. MySQL, PHP 7): Mysql 5.7.29, PHP 7.3.14
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by Mac-Rae** [comment]
Hi @stratacorps,

Thank you for submitting this report. We have taken time to review and believe that this report may qualify as a security issue, therefore in following with our security procedures will be removed from the public domain to allow the Security team to provide a fix and limit the impact to our users. If you would like to be kept up to date, please contact us at security[at]suitecrm[dot]com using reference **104**.

We ask in the future that you refer to our policy on reporting security issues which can be found [here](https://github.com/salesagility/SuiteCRM/security/policy).

Best,
Mac :+1:
