### ISSUE TITLE
Email archive folder query slow when lots of data

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#8533]
https://github.com/salesagility/SuiteCRM/blob/master/include/SugarFolders/SugarFolders.php#L465-L476

Currently using 7.8,x but query seems the same in current master branch.

We are finding that any user that trys to open the Archive folder the query will hang on the DB for a few mins processing. Its doing a tmp table and filesort. This may be due to how much data we have in our DB. Just the subselect statement itself can return 22k+ results for a particular user.

I have taken the query that it generates and altered it to use JOINS instead and its much quicker, it also seems to be the recommended way to write the SQL statement.

```
SELECT emails.id , emails.name, emails.date_sent, emails.status, emails.type, emails.flagged, emails.reply_to_status
, emails_text.from_addr, emails_text.to_addrs, 'Emails' polymorphic_module
FROM emails
JOIN emails_text on emails.id = emails_text.email_id
WHERE emails.deleted=0 AND emails.type NOT IN ('out', 'draft') AND emails.status NOT IN ('sent', 'draft') AND emails.id = (
SELECT eear.email_id FROM emails_email_addr_rel eear
JOIN email_addr_bean_rel eabr ON eabr.email_address_id=eear.email_address_id AND eabr.bean_id = 'xxxxxxxxxxxxxxxxxxxxxxxxx' AND eabr.bean_module = 'Users'
WHERE eear.deleted=0
) ORDER BY date_sent DESC LIMIT 0,20
```

to 

```
SELECT emails.id , emails.name, emails.date_sent, emails.status, emails.type, emails.flagged, emails.reply_to_status
, emails_text.from_addr, emails_text.to_addrs, 'Emails' polymorphic_module
FROM emails
JOIN emails_text on emails.id = emails_text.email_id
JOIN emails_email_addr_rel eear ON eear.email_id = emails.id
JOIN email_addr_bean_rel eabr ON eabr.email_address_id=eear.email_address_id 
WHERE emails.deleted=0 AND emails.type NOT IN ('out', 'draft') AND emails.status NOT IN ('sent', 'draft')
AND eabr.bean_id = 'xxxxxxxxxxxxxxxxxxxxxxxxx' AND eabr.bean_module = 'Users'
AND eear.deleted=0
GROUP BY id
ORDER BY date_sent DESC LIMIT 0,20
```

**Comment by pgorod** [comment]
Thanks @tsmgeek!

Do you need help creating a PR? For a single file fix, it's easy to do from Github website, without a local `git` required.

Just go to this file (the samne file on the `hotfix-7.10.x` branch:

https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/include/SugarFolders/SugarFolders.php#L465-L476

Then click the ✏️ pencil icon to edit it. Make your changes and save. This does a few things:

- forks the SuiteCRM repo onto your own user area;
- creates a new patch branch under your `hotfix-7.10.x` there;
- commits your new file in that branch

After that, it immediately offers to create the PR to propose the same change in our main repo. Just fill in the template and create the PR.

Tell me if you need more help. Thanks for contributing!

**Comment by tsmgeek** [comment]
https://github.com/salesagility/SuiteCRM/pull/8534

**Comment by tsmgeek** [comment]
Seems to be very similar issue to this issue except that did not tackle the archive folder just the count() wuery, plus we are using MariaDB 10.1.x and its the main SELECT query that is the issue.

https://github.com/salesagility/SuiteCRM/issues/7156

**Comment by fcorluka** [comment]
I have the same issue on 7.10.22 when opening Email module.
I have more than 50.000 emails in database and 4 active InboundEmail groups (createing case from email). Opening Email module takes more than 1 minute.
