### ISSUE TITLE
When edit and save (archived) email, related addresses are soft deleted

### ISSUE THREAD

**Issue by LeoZandvliet** [salesagility/SuiteCRM#8535]
When editing an archived email, the related email addresses like 'from' and 'to' are removed from the email. 

#### Issue
When viewing emails archived by an Outlook plugin (we use the one from Grinnmark) all looks great.
But if you 'edit' the e mail, don't change anything, and save, the related email adresses are not visible anymore. When looking in the database, the link between email and addresses are marked as `deleted`.
Out of the box, when 'editing' an email, the following fields are in the form:

* assigned to
* related to
* category

#### Expected Behavior
I expect that the email addresses stay related to the email, and also stay visible in the DetailView.

#### Actual Behavior
The email is saved and related addresses are marked `deleted`.

#### Possible Fix
Stop touching data that's not edited through the EditView :)

#### Steps to Reproduce

1. Archive an e-mail through a Outlook plugin (or: create in another way an record in the 'email module')
2. Go to the created e-mail
  `/index.php?action=DetailView&module=Emails&record={EMAIL_ID}`
3. Verify the 'to', 'from', 'cc' and 'bcc' fields are filled correctly
  When running the following query on the database one can verify the 'before' status:
  ```
SELECT SQL_NO_CACHE
	`emails`.`name`, `emails_email_addr_rel`.`address_type`, `emails_email_addr_rel`.`deleted`, `email_addresses`.`email_address` 
FROM 
	`emails` 
JOIN 
	`emails_email_addr_rel` 
		ON (`emails_email_addr_rel`.`email_id` = `emails`.`id`) 
JOIN 
	`email_addresses` 
		ON (`email_addresses`.`id` = `emails_email_addr_rel`.`email_address_id`) 
WHERE 
	`emails`.`id` = "{EMAIL_ID}";
```
4. Edit the e-mail (Actions -> Edit)
5. Just hit the save button, don't touch any field.
6. The fields 'to', 'from', 'cc' and 'bcc' are empty.
7. Verify in the database that the related addresses are soft deleted (run query in step 3. again)

#### Context
In reality I tried above with an added 'subject' field to the EditView to change the subject of archived emails for a better tracebility. Then noticed the loss of data and produced the steps above on stock EditView.
At least a medium priority for us, or an acceptable workaround.

#### Your Environment
* SuiteCRM Version used: 7.11.8

**Comment by Mac-Rae** [comment]
Hi @LeoZandvliet,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version.

Thanks :+1:

**Comment by Mac-Rae** [comment]
@Dillon-Brown Thoughts on this being High Priority?

**Comment by PedroErnst** [comment]
Hi @LeoZandvliet 

Please if you get a chance could you apply the changes from my MR above and see if that fixes the issue for you.
Thanks

**Comment by LeoZandvliet** [comment]
Hey @PedroErnst,

Nice find, that does the job! 
When looking back in the history of this file, the lines you removed were there since the initial commit, 23 sept. 2013:
https://github.com/salesagility/SuiteCRM/blob/8e51b0e900d7e8cf39529c39ab2976583c638e69/modules/Emails/Save.php

I'm not able to test what will happen if related emailaddresses (from, to, cc) are added/removed through the 'edit form' as I can't add those fields to the view (they are not listed at all). But just editing the subject for example will keep the change made while leaving the related email addresses intact.
Maybe the update mechanism works as follows: 

1. remove all emailaddresses on update
2. add related emailaddresses that are posted

But I'm unable to test that.
Can someone please look into that mechanism?
Or: how should I add the from, to, cc addresses to the edit view so I can test myself?
