### ISSUE TITLE
Issue after upgrading from 7.11.10 to 7.11.11

### ISSUE THREAD

**Issue by holdusback** [salesagility/SuiteCRM#8541]
Hey there,

After upgrading to 7.11.11 I have two breaking issue : 

Detailview of a lot of module not work (but not all !) : 
sugar_grp1.js?v=jcyaO5ilLUe3IMh7qizj0A:643 Uncaught AjaxUI error parsing response

If I disable ajax it working back, but special character are not handled : 
![image](https://user-images.githubusercontent.com/46958376/74440225-e777a080-4e6d-11ea-83ed-e8ac31a997f0.png)

Before update everything was working great. My only option was to re upload a backup from before the update.

Tested on my production server on a shared hosting and on a WAMP locally, same issue on both.

I had no error during the upgrade wizard process, it run like every other update.

I surely have a lot of customisation but everything under the custom/ folder , nothing too fancy.

**To note / Possible Reason I found during debugging** : 
My account module is working. And all the accent are displayed well. My contact detailview is not working, if I disable ajax I can see that accent are NOT displayed well... So I think its related. I dont know how It can run for my account, and not for my contact. (My database interclassement is latin1_swedish_ci)

Version:
PHP 7.3
Latest Chrome Version
Latest wamp version (for the local version)

**Comment by Mac-Rae** [comment]
Hi @holdusback,

Could you confirm the version you upgraded from?

**Comment by Mac-Rae** [comment]
Hi @holdusback,

This issue has been confirmed to exist and is replicable while upgrading from 7.11.10 to the latest version.

We will continue to investigate further and aim to find a resolution as soon as possible.

Thanks :+1:

**Comment by holdusback** [comment]
Thanks a lot for the feedback ! Happy to help and hope you will be able to fix it 👍 

I have a mysql database.

**Comment by Mac-Rae** [comment]
Just as a notice to others who may come here seeking a resolution to this problem please take note of the following announcement on the forums [here](https://community.suitecrm.com/t/suitecrm-7-11-11-7-10-23-is-now-available/71348/2?u=mac-rae).
