### ISSUE TITLE
Not able to upgrade SuiteCRM 7.11.8 to SuiteCRM 7.11.12 using Upgrade Patch

### ISSUE THREAD

**Issue by riteshd2** [salesagility/SuiteCRM#8562]
#### Issue
Not able to upgrade SuiteCRM 7.11.8 to SuiteCRM 7.11.12 using Upgrade Patch

#### Expected Behavior
Should be upgraded from version 7.11.8 to 7.11.12 using upgrade patch

Not able to upgrade SuiteCRM 7.11.8 to SuiteCRM 7.11.12 using Upgrade Patch

#### Actual Behavior

Showing error message 
The uploaded file is not compatible with this version of SuiteCRM.
SuiteCRM System Version: 7.11.8

#### Steps to Reproduce

1. Download SuiteCRM Upgrade 7.8.X to 7.11.12 from SuiteCRM website
2. Go to Upgrade wizard
3. Upload and Install package
4. Observe the error message

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome Version 79.0.3945.130 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL , PHP 7
* Operating System and version (e.g Ubuntu 16.04): `Windows`

![2020-02-25_1522](https://user-images.githubusercontent.com/53225153/75235970-1cc3ad00-57e3-11ea-8f69-225392b0977e.png)

**Comment by Mac-Rae** [comment]
Hi @riteshd2,

You'll need the 7.11.x to 7.11.12 upgrade pack downloadable [here](https://suitecrm.com/files/162/SuiteCRM-7.11/491/SuiteCRM-Upgrade-7.11.x-to-7.11.12.zip)

**Comment by riteshd2** [comment]
> Hi @riteshd2,
> 
> You'll need the 7.11.x to 7.11.12 upgrade pack downloadable [here](https://suitecrm.com/files/162/SuiteCRM-7.11/491/SuiteCRM-Upgrade-7.11.x-to-7.11.12.zip)

Hi @Mac-Rae Thank you very much. I got it.
