### ISSUE TITLE
Invalid Duration Validation issues when trying to create meeting

### ISSUE THREAD

**Issue by Mac-Rae** [salesagility/SuiteCRM#8573]
## Issue

An issue where validation fails when trying to create a meeting

![Screenshot from 2020-02-28 17-31-28](https://user-images.githubusercontent.com/45397629/75571063-5baa6a80-5a50-11ea-9491-9e96bfb2dfb1.png)

#### Steps to Reproduce

1. Create a meeting
2. Set date
3. Save

#### Your Environment

* SuiteCRM Version used: Hotfix-7.10.x

**Comment by Mac-Rae** [comment]
Can someone please assess this @Dillon-Brown @cameronblaikie @craigpanton

**Comment by Mausino** [comment]
@Mac-Rae 
I can't confirm this issue on 7.11.12 on fresh installation...
Only one issue which i found with duration field is, that ins't working if you inline edit this field on detail view and if you save this value you got value "none" and on refresh of page there is old value again.

**Comment by Mac-Rae** [comment]
Aye @Mausino,

This is a weird issue that plages me every now and then. Glad to hear it's not affecting our users

**Comment by Mausino** [comment]
@Mac-Rae i can't confirm that this issue isn't in version 7.10.x .. but i saw on official SuiteCRM site that you can download only 8.11.x version... that it shouldn't affect new new users or users which is using the 7.11.x version :)

**Comment by Mac-Rae** [comment]
This page doesn't show 8.11? https://suitecrm.com/download/

**Comment by Mausino** [comment]
@Mac-Rae Sorry... I thought 7.11 and wrote 8.11 
my mistake :(

**Comment by Mac-Rae** [comment]
Phew :sweat_smile: 

The validation issue does appear to be something local for me as no one else I spoke to has the issue. Just not sure what's causing it :/

**Comment by pgorod** [comment]
@Mac-Rae have a look at the developer console to see if there are Javascript errors there....
