### ISSUE TITLE
Several Dashlets Broken in 7.10.24

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#8577]
#### Issue
After upgrade from 7.10.22 to 7.10.24 several chart dashlets are broken: 
- Pipeline By Sales Stage
- Outcome by Month
- My Pipeline By Sales Stage
- Campaign ROI

This issue also causes a blank homepage area for users which already had these chart-dashltes before the SuiteCRM upgrade. 

Error seems common across dashlets and is related to issues in call of abstract method DBManager::convert()
```
PHP Fatal error:  Uncaught Error: Cannot call abstract method DBManager::convert() in /BASE/modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php:331
Stack trace:
#0 /BASE/modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php(129): PipelineBySalesStageDashlet->constructQuery()
#1 /BASE/include/MySugar/MySugar.php(187): PipelineBySalesStageDashlet->display()
#2 /BASE/modules/Home/DynamicAction.php(56): MySugar->displayDashlet()
#3 /BASE/include/MVC/View/SugarView.php(818): include_once('/var/www/crm.rn...')
#4 /BASE/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile('modules/Home/Dy...')
#5 /BASE/include/MVC/View/SugarView.php(211): ViewClassic->display()
#6 /BASE/include/MVC/Controller/SugarController.php(435): SugarView->process()
#7 /BASE/include/MVC/Controller/Suga in /BASE/modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php on line 331, referer: https://CRM_URL/index.php?module=Home&action=index
 ```

#### Expected Behavior
Chart dashlets should work as expected. 

#### Actual Behavior
Several dashlets do not work.
Homescreen area (not entire page) is blank 

#### Possible Fix
Fix call issues to method DBManager::convert()

#### Steps to Reproduce
1. Reset homepage from user profile menu
2. Observe websterver log files for PHP errors. 
3. Add one of the chart-dashlets
Pipeline By Sales Stage
Outcome by Month
My Pipeline By Sales Stage
Campaign ROI

#### Context
Can not see monthly business pipeline and performace data. 

#### Your Environment
* SuiteCRM 7.10.24
* PHP 7.2.27 
* MySQL 5.6.47
* CentOS 7.7

**Comment by evgu** [comment]
Seems realted to de2a546cb767903cdb38bd275010862e59b3bb68 
When I reverse the code changes related to updateing db_convert to DBManager::convert, dashlets charts work again. 

Please advise if this is a community-wide issue, or if there is a new DB a new DBManager related PHP library I might be missing and should be using to enable obsoletion of db_utils. 

@Dillon-Brown pls triage.

**Comment by andrmo** [comment]
FWIW we're experiencing the same issue going from 7.10.16 to 7.10.24.

- PHP 7.2.24
- MySQL  5.7.29
- Ubuntu 18.04.2

**Comment by bunglex** [comment]
I also lost synchronisation to exchange,  the issue was fixed with help from the developer at Grinmark, and reverting DBManager::convert back to db_convert  in service/v4_1/SugarWebServiceImplv4_1.php.

**Comment by mattlorimer** [comment]
This should be resolved in the latest release
