### ISSUE TITLE
This requires the installation of SuiteCRM Mail Merge add-in to Microsoft Word.

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#859]
When I run Mail merge in campaign, I got following message: This requires the installation of SuiteCRM Mail Merge add-in to Microsoft Word.

I cannot find any add-in. Pls remove this funktion or give link to a working plugin or make it work with the pdf-Templates

**Comment by shogunpol** [comment]
@Lehnerr , can you confirm is that issue still exist in recent version of SuiteCRM(7.8), if not please close an issue, or if you want we can do it for you.

**Comment by Lehnerr** [comment]
It is fixed. thx
