### ISSUE TITLE
Menus resetting on upgrade

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#86]
On upgrade of SuiteCRM, module menus reset. Some disabled modules are enabled and group menus are sometimes reset.

**Comment by shogunpol** [comment]
The case has been examined for all possible upgrade-chains from version 7.1.6 to 7.66. The testing included changes on:
- Display Modules and Sub-panels
- Configure Module Menu Filters
Conclusion: for all testing cases it was no possible to replicate bug, all upgrades hold changes.

**Comment by willrennie** [comment]
Closing as @shogunpol has done extensive testing for upgrades and this issue cannot be reproduced.
