### ISSUE TITLE
failed upgrade 7.4.3 to 7.5

### ISSUE THREAD

**Issue by ventoh** [salesagility/SuiteCRM#863]
Many users in the forum have this problem:
"Ran the upgrade through the Upgrade Wizard. Once I committed the upgrade, the Upgrade Wizard page went blank and remains blank"
https://suitecrm.com/forum/installation-upgrade-help/7858-upgrade-from-7-4-x-to-7-5-problems#27614

For me the problem seems related to a custom relation between Contacts and Projects that i have created in suiteCRM. 
The installer try to clean some not existent files like this
Exception in Controller: file not found for clean: custom/Extension/application/Ext/TableDictionary/project_contacts_1.php

while the file should by 
custom/Extension/application/Ext/TableDictionary/contacts_project_1.php

I copied all the missed files from contacts_project_1.* to project_contacts_1.* and reload the upgrade wizard blank page and it worked. I don't know if there is some side effects.

**Comment by willrennie** [comment]
This issue should now be resolved in SuiteCRM 7.5.1, can you confirm?

**Comment by ventoh** [comment]
7.4.1 to 7.5.1 went perfectly, no problems

**Comment by willrennie** [comment]
Fix confirmed in 7.5.1
