### ISSUE TITLE
Subpanels COMPOSE EMAIL button : missing Related to

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#8641]
If an account does not have and email address, the Related to field is not populated when clicking Compose Email under Accounts or Opportunities.

#### Expected Behavior

even without an email address (which you would have to enter manually in the compose view), the related to field should be populated.

#### Possible Fix

move if (targetCount < 2) after if (targetCount > 0)
in jssource/src_files/include/javascript/EmailsComposeViewModal.js 

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Hi @QuickCRM,

This issue has been confirmed to exist and is replicable in the latest 7.10.x version.

Thanks :+1:
