### ISSUE TITLE
Duplicated string - Include - case_status_default_key

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#866]
include language file has 2 duplicated keys with different values:

Line 401
  'case_status_default_key' => 'New',

Line 3350
$app_list_strings['case_status_default_key'] = 'Open_New';

This is causing issues when tanslating with crowdin. Even hidden from translators they get download with same value (the first on the file).

**Comment by horus68** [comment]
Still waiting for a fix.
String duplicated: 'case_status_default_key'

Line 401
```
  'case_status_default_key' => 'New',
  'case_status_dom' =>
  array (
    'New' => 'New',
    'Assigned' => 'Assigned',
    'Closed' => 'Closed',
    'Pending Input' => 'Pending Input',
    'Rejected' => 'Rejected',
    'Duplicate' => 'Duplicate',
  ),
```

Line 3351
```
$app_list_strings['case_status_default_key'] = 'Open_New';
$app_list_strings['case_status_dom'] =
    array (
        'Open_New' => 'New',
        'Open_Assigned' => 'Assigned',
        'Closed_Closed' => 'Closed',
        'Open_Pending Input' => 'Pending Input',
        'Closed_Rejected' => 'Rejected',
        'Closed_Duplicate' => 'Duplicate',
    );
```

So this second array should get the  'Open_New' value but it is filled as 'New'

The solution would be to change the 401 line array to have different words for keys and values (as the 3351 array do)

so instead of 
`    'New' => 'New',`
it would be something like 
`    'New_New' => 'New',`

and so on.
Now... can someone implement this to not break the files calling this array?

**Comment by pribeiro42** [comment]
I think the best way to correct this issue is to simply remove the lines 401 and following. The definition of the array key 'case_status_default_key' and the 'case_status_dom' array is duplicated and the one that stands is the last.
