### ISSUE TITLE
Task Status is not using translation in View Summary

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#8662]
Task Status is not using translation in View Summary
The key is displayed.

#### Issue

- Load any translation
- Click View Summary under an account
- It shows "Task Completed" on tasks

#### Expected Behavior

Status should be translated

#### Possible Fix

#8661 
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.10, SuiteCRM 7.11
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by samus-aran** [comment]
This has been merged.
