### ISSUE TITLE
Changes on Description is not appearing

### ISSUE THREAD

**Issue by CobaJashi** [salesagility/SuiteCRM#8667]
Hello :)
and first of all, best regards to everybody :)

I create a product. Open an quote. Add the product there. Save and print it. Works very well. 

https://prnt.sc/s0k9hb

I am now changing the text in the product description. 

https://prnt.sc/s0ka1d

Save it and print it as PDF. Then I still get the old values from the product description. He always takes over the values from the products, he igborates the changes ...

https://prnt.sc/s0k4nx

The latest version of SuiteCRM is installed ... The error is also present on the test server 
http://demo.suiteondemand.com/

This error only affects the product description for the PDF in invoices and offers. Service is taken over and can be printed.

Best regards from Berlin and stay healthy

**Comment by chris001** [comment]
Without looking at the code, it sounds like the values are cached, yet they shouldn't be.

**Comment by mattlorimer** [comment]
Probably not, it's more likely your are using the wrong field variable in the pdf template. As you can use the description field from the line items, or you can use the description direct from the product. So if you use the wrong one and update the other it will appear exactly as you have described.

**Comment by chris001** [comment]
Are you saying that the app copies the description from the product, to the description from the line items, one time once, when it creates the PDF invoice or offer, and then, suppose the user makes changes to the description from the product, the app will not copy that new description of the product, to the description field of the line item?

**Comment by CobaJashi** [comment]
Hello :) and thank you very much for your answers. We've been a little bit lost the last days :) A lot of crazy things are happening in the corona crisis...

here is the code of our offers:

<table style="width:100%;border-spacing:5px;" cellpadding="5"><tbody><tr><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;width:70%;"><span style="font-family:helvetica;font-size:small;"><strong>Produktbeschreibung</strong></span></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;width:15%;"><span style="font-family:helvetica;font-size:small;"><strong>Menge</strong></span></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;width:15%;"><span style="font-family:helvetica;font-size:small;"><strong>Preis</strong></span></td></tr><tr><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><p><span style="font-family:helvetica;font-size:small;">$aos_products_description</span>&nbsp;</p></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><p><span style="font-family:helvetica;font-size:small;">$aos_products_quotes_product_qty</span></p></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><p><span style="font-family:helvetica;font-size:small;">$aos_products_quotes_product_unit_price</span></p></td></tr><tr><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><p><span style="font-family:helvetica;font-size:small;">$aos_services_quotes_name</span></p></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><span style="font-family:helvetica;font-size:small;">&nbsp;</span></td><td style="border-width:1px;border-style:solid;text-align:left;vertical-align:top;"><span style="font-family:helvetica;font-size:small;">$aos_services_quotes_service_unit_price</span></td></tr></tbody></table>

**Comment by CobaJashi** [comment]
hello :) and thanks a lot for your hints. Error found.

It was the `$aos_products_quotes_item_description` 

Now it works...
