### ISSUE TITLE
Inbound/Group Email: Assignment Filtering Configuration Does Not Save

### ISSUE THREAD

**Issue by ctucker1984** [salesagility/SuiteCRM#8668]
#### Issue
When admin sets up email accounts, filtering and assignment aren't saved properly.

#### Expected Behavior
I would expect that settings input would be saved. When I click Done > Save and refresh, then go back into the same edit windows to inspect the retained settings, my configuration should persist.

#### Actual Behavior
No settings, denoted by intentional exclusions (support@, as in the example), persist after the save. Maximal access is assigned to all users. This includes deleted inbound mailboxes, which don't ever get deleted for anybody.

#### Possible Fix
No idea. However, web research lead me to the folders table where I found that every email account folder ever all have deleted values of 0 when most should be 1 and therefore pruned. I read this Community thread which lead me to the table and sounds as if it may be related. I'm not able to tell for certain. https://community.suitecrm.com/t/inbound-email-broken-perhaps-corrupted/69007

#### Steps to Reproduce
I, the Admin User, provision Regular User. While logged in as Admin, I provision a number of inbound group email accounts (sales@domain.com, support@domain.com, for example). My users are volunteers, and not the types to do a lot of their own config. So, as the Admin, I need to provision their company accounts. As Admin, I go to their user profile and edit. I click Settings in the email frame and get the popup window. I pick the folders I want to assign them and the accounts I want enabled to them. I click done, and then save to close out the user edit process. I intentionally exclude support@ for testing. I did this in Chrome

In Safari on the same machine (but I assume the different browser isolates the session sufficiently) I log into the Regular User's account. That user has access to every folder of every inbound account, deleted or not, despite my configured exclusions. Filtering and exclusion within this user's settings are also left unsaved as above.

#### Context
This makes deploying SuiteCRM a non-starter for my non-profit organization whose membership is exclusively emergency responders. Some group accounts relate to internal disciplinary procedure and must be reserved only for authorized users. As the CRM applies to larger organizations, I would suspect that a similar control of information flow would be a requirement. I suggest high prioritization.

#### Your Environment

* SuiteCRM Version used: 7.11.13
* Browser name and version: Chrome Version 80.0.3987.163 (Official Build) (64-bit) and Safari Version 13.0.5 (15608.5.11)
* Environment name and version (e.g. MySQL, PHP 7): BlueHost Shared Hosting on Linux, Cpanel Version 78.0 (Build 47), Apache 2.4.39, PHP Version 7.3.13, MySQL 5.6.41-84.1
* Operating System and version: MacOS Catalina 10.15.3

**Comment by samus-aran** [comment]
I believe this is a duplicate to this issue. That the Administrator needs to set up user email accounts. Feel free to comment if it isn't and I'll re-open.

https://github.com/salesagility/SuiteCRM/issues/8796
