### ISSUE TITLE
Error when posting a new comment in 4.3.0 service pack 4

### ISSUE THREAD

**Issue by acoolov** [salesagility/SuiteCRM#8670]
I get this error when posting a comment in tickets module in 4.3.0 service pack 4. Looks like it's only happening with ticket comments. Please see below.

![Screenshot (7)](https://user-images.githubusercontent.com/38298689/79701024-c5ccd800-8267-11ea-8f14-b2b2e0515851.png)

**Comment by mattlorimer** [comment]
This is not SuiteCRM, I would suggest posting your issue in the relevant project.
