### ISSUE TITLE
Merging Contacts fails when both/all records contain Account references (7.11.12)

### ISSUE THREAD

**Issue by sjuvonen-delta** [salesagility/SuiteCRM#8673]
#### Issue
Merging multiple Contacts that each contain a reference to an Account leads to a blank screen and fails to merge.

#### Expected Behavior
Primary record as selected during merge should be the record remaining post-merge, with other record(s) deleted.

#### Actual Behavior
The merge operation leads to a blank screen and all involved records remain.

#### Possible Fix
Allow merging when all involved Contact records contain a reference to an Account

#### Steps to Reproduce
1. In the list of Contacts, select 2 to merge that both have a reference to an Account
2. Use bulk actions to merge
3. Set primary data fields in merge screen
4. Click Save Merge and then OK in the confirmation popup
5. Observe a blank screen
6. Check list of Contacts and observe that the involved records remain

#### Context
This is preventing users from performing a merge unless they remove the referenced Account from record(s) they don't wish to retain after the merge.

#### Environment
* SuiteCRM Version used: 7.11.12
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 80.0.3987.163 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7, SQL Server 2017
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04.1 LTS

**Comment by pgorod** [comment]
I tried this and couldn't reproduce the problem.

On 7.11.13 it works ok (live demo)
On a local 7.10.25 it also works ok

It's better if you ask about these issues in the Forums before posting here, so we can first check if it is a problem just with your system, and ask you to get more technical information (errors in your logs, for example)...

**Comment by sjuvonen-delta** [comment]
Fair enough.  I will close this item.
