### ISSUE TITLE
Arrow characters position on the buttons not positioned properly

### ISSUE THREAD

**Issue by mandryszczak-dc** [salesagility/SuiteCRM#8674]
Hi,

I noticed that we have styling issues in our copy of the SuiteCRM. 
![thumbnail_image_1](https://user-images.githubusercontent.com/60137652/80010866-f8264180-84c2-11ea-8e20-327cb083c2f6.png)

The arrows on the navigation buttons are not properly aligned. It looks like it is because of the "vertical-align" option for the ".suitepicon" class ":before" in the style.css file is set to "top". 

When I change that in my browser developer tools to "middle", it seemed to fix the issue.
![thumbnail_image_2](https://user-images.githubusercontent.com/60137652/80010904-04120380-84c3-11ea-953f-f95b78e30a3b.png)

Hope this helps.

Thank you.

Kind Regards,
Maciek

**Comment by chris001** [comment]
You can drag-and-drop the image into this github text box: _"Attach files by dragging and dropping, selecting, or pasting them."_

**Comment by mandryszczak-dc** [comment]
Thank you, Chris. I updated my post.

**Comment by chris001** [comment]
A good place to dig for these `CSS` styles, is in the **SuiteP theme "template" files (`.tpl`)** which are Smarty templates...  Also, in the relevant `.scss` files which is a new improved `CSS`...

**Comment by pgorod** [comment]
@mandryszczak-dc I don't see this on the live demo. 
demo.suiteondemand.com (user: will, pass: will)

Are you using any custom CSS? If you use other sub-themes, does the same thing happen?

**Comment by mandryszczak-dc** [comment]
Hi Guys, 

We have a standard setup with no custom CSS files. 
Also, I noticed that the hight for the "disabled" button is shorter.
![Annotation 2020-04-23 122629](https://user-images.githubusercontent.com/60137652/80094229-ce6e2880-855d-11ea-94ab-6c776a91b758.png)

@pgorod, hmm... that demo page is different from what we can see on our copy and when I looked into the master branch I can see that the style.css has the same settings as we have:
![Annotation 2020-04-23 123715](https://user-images.githubusercontent.com/60137652/80095115-53a60d00-855f-11ea-8e18-3e40ab5afc75.png)
(sorry that I'm showing that in Notepadd++ but I could not catch everything in one line) 

Regards,
Maciek

**Comment by Mac-Rae** [comment]
Hi @mandryszczak-dc,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.x or 7.11.x. If you believe this to be an issue still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:
