### ISSUE TITLE
Group update produces inconsistent results

### ISSUE THREAD

**Issue by jchristensen-1wa** [salesagility/SuiteCRM#8678]
Hi,

We are starting an instance of SuiteCRM and I would like to import a set of Contacts from a different data source and have them mostly read only in SuiteCRM.

To do this I have set up security group that has the correct permissions and then I try to apply this security group to all the records.

This is a large number of Contacts, 20,000+. Only some of the records have the correct security group applied.

Is there any know problems with applying security groups to this many records?

Thanks.

**Comment by pgorod** [comment]
Hi, welcome.

Can I please ask you to open this question in the Forums? It is more adequate for that site.

https://community.suitecrm.com

I will answer you there.
