### ISSUE TITLE
Opcache Invalidation

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#8706]
If user has disabled PHP opcache stat cache then any updates to config.php will not be recognised on next page load.

It may be an idea to trigger `opcache_invalidate()` against specific script names to correct issue.

https://www.php.net/manual/en/function.opcache-invalidate.php

**Comment by JanSiero** [comment]
The following PR implements this:

https://github.com/salesagility/SuiteCRM/pull/8514

**Comment by tsmgeek** [comment]
> The following PR implements this:
> 
> #8514

Thanks, I can not believe quite a major issue has been open so long.

**Comment by JanSiero** [comment]
Fixed by #8514
