### ISSUE TITLE
Duplicate inserts if save in before_save logic hook

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#8709]
If a `$bean->save()` is called in a `before_save` logic hook on a new record, it will trigger a duplicate constraint issue in DB.

#### Expected Behavior
works correctly

#### Actual Behavior
DB duplicate constraint issue as it tries to insert the record multiple times as its not detected as already inserted.

#### Context
This has only happened since upgrade from 7.8.x to 7.10.25

#### Your Environment
* SuiteCRM Version used: 7.10.25
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3 MySQL

**Comment by chrisdent** [comment]
Use $bean->save() only in after_save not in before_save

**Comment by mattlorimer** [comment]
Thanks for reporting this issue, from what you have described this is not a bug. as @chrisdent says calling save in a before save is not generally recommend, but I would add that there are way to use it and perhaps this is something you come discuss in our community forum how to better approach this within your code.

**Comment by tsmgeek** [comment]
My point is the issue did not happen in 7.8.x and now it does. 
I know that one way to use it in before save is to only apply it to records that are not new but essentially we do not need it to save anyway so took the save out, just highlighting a change between versions.

**Comment by mattlorimer** [comment]
thanks for the update. but from the information that has been provided we can only deduce that 7.10 is working as expected and 7.8 is maybe not, as 7.8 is no longer supported this issue has been marked as invalid and closed. However, you may be able to provide more detail as why you think this is an issue, perhaps with custom code example being used, to show why you think this shouldn't be the case, then we could perhaps reopen this issue and investigate further, but at the moment we see no reason to.
