### ISSUE TITLE
Next Sprint Planning

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#8726]
We are coming up nearly 2 months since the last 7.10.x release.
Is there an idea when the next one will be or planning for it?

There are so many issues since the 7.10.x release regarding email that are not getting on top.
Ive personally added several PRs targeting various email/imap/reports issues.

**Comment by pgorod** [comment]
Thanks for your email fixes, they're very necessary. I'm really glad someone is diving into this, like you are. Let's hope some of the Covid-chaos starts to settle soon and things return to normal for sprint planning etc...

**Comment by chris001** [comment]
👍  COVID pandemic is the perfect time to #SprintFromHome

**Comment by Mac-Rae** [comment]
Hey @tsmgeek,

Priorities are constantly changing atm as I'm sure you understand. I have seen all your PRs and really appreciate the work your putting in. Currently, we are not consistently assessing PR however we are hoping this will change soon. For now, know we are looking into our next release and will update you when I know more!
