### ISSUE TITLE
Double modal window when i use activities subpanel in Contact and Lead Modules

### ISSUE THREAD

**Issue by trevonio** [salesagility/SuiteCRM#8730]
We are using a fresh installation of SuiteCRM  7.10.24.

We have found an error very simmilar to https://github.com/salesagility/SuiteCRM/issues/6351

When I click in "Compose Email" in the Activities Subpanel of a Lead or Contact it opens two modal windows. In the last of the modal windows the To address is duplicated.

![Sin nombre](https://user-images.githubusercontent.com/222990/82131363-c7d97680-97d4-11ea-8171-30e12f388966.png)

Expected Behavior

It should be opening only one modal window.

Actual Behavior
Possible Fix
Steps to Reproduce

    Open any lead in Lead module
    Try to send email from Activities subpanel
    See result

**Comment by Mac-Rae** [comment]
Hi @trevonio,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.25 or 7.11.13. If you believe this to be an issue still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:

**Comment by PedroErnst** [comment]
Can confirm this still happens in 7.10.25

**Comment by PedroErnst** [comment]
Hi @trevonio 

Please if you get a chance could you apply the changes from my MR above and see if that fixes the issue for you.
Thanks
