### ISSUE TITLE
Upload files to Documents Module fail using API V8

### ISSUE THREAD

**Issue by ivanfr90** [salesagility/SuiteCRM#8749]
Related issues: #8494 

#### Issue

Upload files throught the Documents module fails using the REST API.

#### Expected Behavior

A document created in the Documents module with the uploaded file attached to it.

#### Actual Behavior

Response received from the REST API:
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Property filename_file in Document module is invalid"
    }
}
```

#### Steps to Reproduce

1. Configure postman or create a php script to post a new document.
2. Fill the fields needed to create a new document with an attachment encoded using **base64**:
```
{
  "data": {
    "type": "Documents",
    "attributes": {
      "name": "TEST FILE",
      "document_name": "TEST FILE",
      "filename": "fichero_prueba.txt",
      "filename_file": "MTIzNDU=",
      "revision": "1"
    }
  }
}
```
3. After post the new document, the response is:
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Property filename_file in Document module is invalid"
    }
}
```

#### Context

Priority high: impossible create documents using the REST API.

#### Your Environment

* SuiteCRM Version used:  7.11.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
This is a duplicate to the "related issue" If someone is able to correct me on why they aren't the same then I'm happy to re-open it.
