### ISSUE TITLE
Duplicating all task when we duplicate project in project module

### ISSUE THREAD

**Issue by pjyoti562** [salesagility/SuiteCRM#8756]
#### Issue
Hi,

There is an issue in the CRM that if you duplicate a project, all tasks that are in CRM are getting copied to the project.

I tested in crm demo site as well, the same issue I have seen there also -

https://demo.suiteondemand.com/index.php?module=Project&offset=2&stamp=1591608393095738400&return_module=Project&action=DetailView&record=eec53f5c-68fb-705e-3697-5edd20a21679

https://demo.suiteondemand.com/index.php?module=Project&offset=1&stamp=1591608393095738400&return_module=Project&action=DetailView&record=3db5180a-851e-16e4-e031-5ede03faf1a2
 

#### Expected Behavior

When we duplicate any project it should copy exactly the same project with the same task in the subpanel.
like if we are duplicating any project and if there are 5 tasks in the subpanel so in the duplicate record also, there should be only 5 tasks listed as before.
#### Actual Behavior

For now, if you duplicate a project, all tasks that are in CRM are getting copied to the project.
#### Steps to Reproduce

1. Go to the project module, go to the detail view of any record, click on action button, and then duplicate and then create a duplicate record of that project.
2. now when you check the original record and duplicate record sub panel you can see both tasks will be different in the duplicate record you will see more tasks than the original record.
3.
4.

#### Context

High
I tried to check the duplicate code of project module for the task subpanel
#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

suitecrm_version => 7.11.10
Chrome Version 83.0.4103.97 (Official Build) (64-bit)
PHP Version => 7.4.4

**Comment by Mac-Rae** [comment]
Hmm, @pjyoti562 ive not had any luck replicating this. If you jump onto demo.suitecrm.com are you able to replicate it in the new 7.11.13 version?

**Comment by pjyoti562** [comment]
@Mac-Rae
 demo.suitecrm.com is not accessible as I am getting "This site can’t be reached" at this moment.

**Comment by pjyoti562** [comment]
@Mac-Rae, I tried but demo.suitecrm.com is not opening

**Comment by Mac-Rae** [comment]
@pjyoti562 Sorry mate, demo.suiteondemand.com is the correct URL

**Comment by pjyoti562** [comment]
@Mac-Rae 

https://demo.suiteondemand.com/index.php?module=Project&offset=2&stamp=1591608393095738400&return_module=Project&action=DetailView&record=eec53f5c-68fb-705e-3697-5edd20a21679

https://demo.suiteondemand.com/index.php?module=Project&offset=1&stamp=1591608393095738400&return_module=Project&action=DetailView&record=3db5180a-851e-16e4-e031-5ede03faf1a2


I have already tested here also and  I got the same error.

**Comment by pjyoti562** [comment]
@Mac-Rae Please help its an urgent issue

**Comment by Mac-Rae** [comment]
Hi, on duplicating a project record like the following the tasks are still related correctly, could you provide some screenshots so we can see what you're seeing?

**Comment by pjyoti562** [comment]
Hi, when I checked earlier, I saw same issue in the demo site as well, but now, it's working fine on the demo site. Can you tell me how we can solve if we this issue while duplicating a record?


The issue is -  if you duplicate a project record, all tasks that are in CRM are getting copied to that duplicated record. 

The requirement is - If we duplicate a record say A1 which has 4 tasks in its task subpanel so when we duplicate A1 record, it should have 4 tasks only in its tasks subpanel. 

Please help.

**Comment by Mac-Rae** [comment]
Hey @pjyoti562,

Sorry this discussion dropped off, I'm unsure what's causing this one but will ask around and see if I can find a fix. Could you do a few things for me;

Run a Repair and Rebuild,
Rebuild JS Grouping
Rebuild JS Minified

Test if the issue still exists and if it does check your SuiteCRM and PHP logs for errors or debug info which may help. If you find anything please upload it here

**Comment by pjyoti562** [comment]
Hi @Mac-Rae, I resolved it.

it was because of one addon I was using, and it was not sending correct id while duplicating. So after passing the correct record id, it started working.
