### ISSUE TITLE
Suitecrm- How to add Year View /Enable the Year View Option

### ISSUE THREAD

**Issue by praveen88074** [salesagility/SuiteCRM#8761]
In the calendar display page there is day/week/month with drag and resize for activities. I need the year view in the calendar display page with drag and resize … please help me with this with solution

**Comment by pgorod** [comment]
This was already answered in the Forums

https://community.suitecrm.com/t/calendar-how-to-add-year-view-enable-the-year-view-option/73192

@praveen88074 GitHub is not for this kind of questions. It's not a community support site for users, it is a place where developers contribute code to open-source projects and manage bug reports.
