### ISSUE TITLE
Custom Session Directory

### ISSUE THREAD

**Issue by maxxatgit** [salesagility/SuiteCRM#877]
Greetings;
I setup a custom "sessions" directory on a fresh install of version 7.5, under setup >> site security.

I logged in, browsed 2 or 3 screens, and then logged out. The sessions directory that I specified had around 50 files in it. They all start with "sess_".

So I logged out, and deleted all of the files. I checked the directory, and it was empty.

Then I reloaded the login screen. I did not attempt to log in, I just reloaded the screen.
I checked the directory, and there were 5 session files.

I logged in, checked the directory, and there were 11 session files...

I don't know how the session directory/files are supposed to work (I assumed 1 file per login, but that is just an uninformed guess), but this is generating a lot of useless files...

Regards.

**Comment by paulgodley** [comment]
Hi there, I will install a fresh instance of 7.5 and set up a custom sessions directory and see what files are created for me.

**Comment by paulgodley** [comment]
I have performed a clean install of 7.5 and set up a custom sessions directory.  When I log in, change multiple screens and then logout, there is only one session file created for me.  When I repeat the process, a single session file (sess_****) is created for me.  I deleted the files and then hit the login screen again and this created a single file.

I am not sure what can be causing this.  What web server are you using?

**Comment by willrennie** [comment]
@maxxatgit do you have any follow up in response to @paulgodley questions?

**Comment by maxxatgit** [comment]
Very sorry for the delayed response!
For some reason, I didn't see a notification about ghost's question.

I'm using 64 bit CentOS v6 on a VPS  with PHP 5.6, and Apache 2.4. That custom sessions directory was outside of the web root, but readable by apache.

I deleted the custom sessions directory, and set the config for the standard location.

I have since upgraded to 7.7, I will try using a custom sessions directory again, and post my findings.

Regards.

**Comment by maxxatgit** [comment]
I'm still getting the same behavior. This doesn't seem to have anything to do with the custom sessions directory. I checked the /tmp directory, and I get a lot of session files there as well (when the custom session dir is disabled).

I did a few tests with the custom sessions dir:

with suitercm dir chmod 751:
I deleted all of the files in the custom sessions dir
- 6 session files get added when I navigate to the site (without logging in)
- when I log out, 1 session file is deleted

with suitercm dir chmod 750:
I deleted all of the files in the custom sessions dir
- the 6 sessions files don't get added until I log in
- when I log out, 1 session file is deleted

The session files accumulate while surfing the site, regardless of the chmod settings.
If there are any other tests that you would like me to perform, please let me know.

This is not a clean install, this install has been upgraded a few times, starting with 7.5.

**Comment by maxxatgit** [comment]
One more point of information, my VPS is now CentOS v7.

regards...

**Comment by maxxatgit** [comment]
This is some kind of permissions issue...

With custom_sessions_dir owned by suite:suite and permissions 751:
- 6 session files after login; 1 session file deleted after log out

With custom_sessions_dir owned by suite:apache and permissions 700:
- 2 session files after login; 1 session file deleted after logout
- The session files are not accumulating while browsing.

I hope this helps...

**Comment by maxxatgit** [comment]
This is probably pertinent:
I'm running PHP under fcgid and suexec

**Comment by chris001** [comment]
@maxxatgit 
Could you check, what is the owners and groups of the session files in your session folder?
I can guess what your answer will be, because I am quite sure your issue is related to a bug I've fixed concerning this exact matter which has negatively impacted the application in many ways!

**Comment by samus-aran** [comment]
I will close this issue as it is a duplicate (but realy this was created first) of a more detailed issue.

https://github.com/salesagility/SuiteCRM/issues/3157
