### ISSUE TITLE
Can't upload logo when perform install

### ISSUE THREAD

**Issue by IBlasterus** [salesagility/SuiteCRM#8785]
Hi.
You miss a bracket in line 263 file install.php.

Now: 
`echo "<script>window.top.window.uploadLogoCallback" . json_encode($result) . ");</script>";`
Need: 
`echo "<script>window.top.window.uploadLogoCallback(" . json_encode($result) . ");</script>";`

Without this bracket browther throw error:
`Uncaught SyntaxError: Unexpected token '{'`
and can't finish upload process.

Best regards, Aleksandr. ;)

**Comment by Mac-Rae** [comment]
Hey @IBlasterus,

Could you raise a PR to fix this wee one?

**Comment by IBlasterus** [comment]
@Mac-Rae
How?

**Comment by Mac-Rae** [comment]
If it's just a single change like said you should be able to do it via the web interface.

1. If you don't have one press "Create Fork" button on the top right of this page.
2. Go to this URL: https://github.com/salesagility/SuiteCRM/edit/hotfix-7.10.x/install.php
3. Find line 263 and make the simple change adding in the missing bracket.
4. Scrolling to the bottom of the page, add a title: "Fix #8785 - Incorrect Syntax in install.php" or something similar would work well.
5. Press Propose changes
6. You may have to fill out a Pull Request template, if so then It can be light as to how small this change is.

Let me know if you have any issue!

**Comment by IBlasterus** [comment]
Ok. I did it.
https://github.com/salesagility/SuiteCRM/pull/8810

**Comment by Mac-Rae** [comment]
Looking good! :+1:
