### ISSUE TITLE
Need to Search twice before getting results

### ISSUE THREAD

**Issue by cameronblaikie** [salesagility/SuiteCRM#8794]
Using the upper right hand search box, it is taking them to a basic search screen and not loading the information. Once they click on "basic search" then it will load the information. Its basically making them search twice.

#### Expected Behavior

To search and get the results first time
#### Actual Behavior

Get no results back unless Basic search is clicked after searching.

#### Steps to Reproduce

1. Search for an account name in the search bar
2. Expect no results
3. Now, hit 'basic search' 
4. See there is now your expected result 

![image](https://user-images.githubusercontent.com/42933743/85843929-df275e80-b799-11ea-8527-899c7bd596b1.png)
![image](https://user-images.githubusercontent.com/42933743/85843951-e64e6c80-b799-11ea-8d78-18dc62b126d0.png)

#### Your Environment

* SuiteCRM Version used: 7.11.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by mattlorimer** [comment]
this is not an issue you just have lucene search advanced (AOD) search enabled, but you probably haven't indexed
