### ISSUE TITLE
Potential information leak with default install

### ISSUE THREAD

**Issue by dmeulen** [salesagility/SuiteCRM#8803]
#### Issue
A default install of SuiteCRM puts `suitecrm.log` in the ducument root. As a result the log ( amongst other files ) are world readable. This will leak information about the system, queries, login info and e-mail addresses. Some installations have DEBUG logging enabled and will expose even more information!

#### Expected Behavior
System logs should never be readable by world!

#### Actual Behavior
`curl -s https://example.com/suitecrm.log` retrieves the full log in default installs.

#### Possible Fix
Move logs outside of the document root by default.

#### Steps to Reproduce
`curl -s https://example.com/suitecrm.log`

#### Context
I found this issue in our own install, I did a query on shodan to find more suitecrm instances and tested if I could read logs. I could, so this seems to be something quite common.

#### Your Environment
SuiteCRM version 7.11.13+

**Comment by pgorod** [comment]
The default htaccess blocks that

`RedirectMatch 403 (?i).*\.log$`

Which [web server](https://docs.suitecrm.com/admin/compatibility-matrix/) are you using?

**Comment by dmeulen** [comment]
You are right, I found an incorrect setting in our apache2 config. But still, this seems to be quite common (looking at my random picks on shodan). IMHO logs should always be outside of the document root.

**Comment by Mac-Rae** [comment]
Are we happy this isn't an issue @dmeulen?
