### ISSUE TITLE
Unable to see Postgresql Database type.

### ISSUE THREAD

**Issue by asharabu** [salesagility/SuiteCRM#8805]
Hi,

I am trying to install SuiteCrm version latest LTS version 7.10.27 which is downloaded from the [link](https://suitecrm.com/files/160/SuiteCRM-7.10/508/SuiteCRM-7.10.27.zip). I am trying it in Nginx + PHP 7.3 but while installing we can see that only MySQL database type, we can not see Postgresql database type.  Please see the attached screenshot. Also please let us confirm will it support Postgresql?
![suitecrmdatatype](https://user-images.githubusercontent.com/42669995/86372858-6300af80-bca0-11ea-9409-0e2b297203e9.jpg)

**Comment by Mac-Rae** [comment]
Hi @asharabu,

Postgresql isn't supported by SuiteCRM unfortunately. Personally I would suggest MariaDB, however, a few variants of MySQL or MSSQL are supported also. Have a look at our [compatibility matrix](https://docs.suitecrm.com/admin/compatibility-matrix/) for official info related to your question.
