### ISSUE TITLE
Upgrade Wizard: Missing "Next" option after successful system check

### ISSUE THREAD

**Issue by heviiguy** [salesagility/SuiteCRM#8808]
Upgrading from 7.11.13 to 7.11.15

After activating the Wizard, the system check begins and reports that all is suitable. However, there is no option to proceed to the the next stage ("Upload Upgrade Package").  The only options are "Back", "Cancel" and "Recheck". I ran "Recheck" twice but nothing had changed.

I had installed the System Upgrade Patch (ver 1.0) prior to running the wizard. 

Can somebody please provide guidance so that I can complete this upgrade? Many thanks in advance.

**Comment by tsmgeek** [comment]
I think this is related to this.
https://github.com/salesagility/SuiteCRM/issues/8784

Check that your cache directory has the correct permissions required, I found that if they are wrong this system check hides the next button.

**Comment by Mac-Rae** [comment]
Any luck @heviiguy?

**Comment by heviiguy** [comment]
Alas, no, changing permissions (and then restarting Apache) did not solve the problem. I still can't get beyond the initial System Check.

**Comment by pgorod** [comment]
Same thing here
https://community.suitecrm.com/t/upgrade-wizard-no-next-button/73576

**Comment by Mac-Rae** [comment]
Whats meant by the System Upgrade Patch (ver 1.0) sorry?

**Comment by pgorod** [comment]
@Mac-Rae it's that small patch with the fixed upgrade wizard files, that is recommended to use in the Release Notes

**Comment by Mac-Rae** [comment]
Thanks @pgorod

**Comment by stenfalp** [comment]
Same problem for me trying to upgrade from 7.11.12. I've read that the problem could be the "Suitecrm Upgrade Patch" which I have installed. Does anyone know how to uninstall it?

Thanks

**Comment by heviiguy** [comment]
"Next" is missing again!!

Just tried to upgrade from 7.11.13.  Same as before. Yet now I'm not sure how I was able to overcome the issue the last time! Any hints?

**Comment by pgorod** [comment]
@mattlorimer there's a possible fix here:

https://community.suitecrm.com/t/7-8-31-update-wizard-broken-no-next-button-after-patch/76854/26?u=pgr

**Comment by JanSiero** [comment]
Hi, please consider correcting the "Upgrade Patch" which can be found here under “SuiteCRM 7.11.18 Upgrades” and “SuiteCRM 7.10.29 LTS Upgrades”

https://suitecrm.com/upgrade-suitecrm/

"SuiteCRM Upgrade Patch - Fix upgrade Issues, prior to upgrading"

Direct link:
https://suitecrm.com/files/162/SuiteCRM-7.11/507/SuiteCRM_Upgrade_Patch.zip

by replacing the old file
`UpgradeWizard/systemCheck.php`
with an actual version from the SuiteCRM source tree found in:
`modules/UpgradeWizard/systemCheck.php`

This would solve the issue of the missing “Next” button.

The patch which @pgorod mentioned also addresses notices due to non existing index `$_REQUEST['additional_step']`, which however don't impede the upgrade process

**Comment by heviiguy** [comment]
Has there been any further work on this one? I've tried installing @JanSiero patch via module loader but, I can select Upload to my heart's content but, nothing happens; the process times-out after awhile. When I refresh, the patch is neither uploaded nor still selected.

Why hasn't an "official" patch been provided with this "fix"? Clearly, I'm not the only one suffering from this problem.

**Comment by JanSiero** [comment]
hi @heviiguy,

You probably can't install because the same module has already been installed. Could you modify the module by editing the file `manifest.php` and change the following line, zip the module and try again?

`'version' => '1.0',`
to
`'version' => '1.01',`

**Comment by heviiguy** [comment]
Thanks @JanSiero . I followed your instructions. But, I have the same results...


![Screenshot 2021-02-11 at 16 39 13](https://user-images.githubusercontent.com/7117360/107702217-ed25e300-6c87-11eb-9309-11b01e8a189f.png)

**Comment by heviiguy** [comment]
![Screenshot 2021-02-11 at 16 52 03](https://user-images.githubusercontent.com/7117360/107703355-873a5b00-6c89-11eb-9635-58c04bb31247.png)

**Comment by heviiguy** [comment]
> Edit: I have overwritten the patch files with the previous ones and this solved the problem.

@stenfalp, 
- which " patch files", specifically, did you overwrite?
- which "previous ones", specifically, were overwritten? From where did you copy them?

**Comment by JanSiero** [comment]
Hi @heviiguy,

Please make sure that `manifest.php` is in the root directory of your zip-file. Don't zip the parent directory.

On the command line, go into directory where manifest.php is located, then:
`zip -r upgradepatch.zip LICENSE.txt manifest.php UpgradeWizard`

**Comment by heviiguy** [comment]
> Don't zip the parent directory.

That was it, @JanSiero. So, as a result of your kind assistance (and patience), I was able to load the patch. Not only that but, I was then able to complete the update; I'm now running version 7.11.18!

In essence, this appears to be a very "simple" fix. I was going to mention that it perplexes me why SA don't replace the offending .php file. In retrospect, it's not such a mystery as this would seem to be a conflict-of-interest with their commercial goals. With this said, I truly appreciate the community of expert users who not only help SA develop and refine a great product with which they can continue to generate an income but who also graciously help those of us who are less technically astute. Thanks again, @JanSiero.
