### ISSUE TITLE
Project logic hook created in wrong location during install

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#8816]
### Issue
During the SuiteCRM installation process, the /custom/Projects/logic_hooks.php file is created in an incorrect location, since the module's final name is Project (not Projects).
As a result, the call to the logic hook it contains is never executed.
This logic hook is responsible for eliminating related project tasks, when a project is deleted.
### Expected Behavior
The location of the created file must be `/custom/Project/logic_hooks.php`
### Actual Behavior
The file is created in a wrong location: `/custom/Projects/logic_hooks.php`
### Possible Fix
Modify file https://github.com/salesagility/SuiteCRM/blob/e523df75ffaeaa593a1eebb4f7306b9e9c81759c/install/suite_install/Projects.php#L48 replacing 
`'module' => 'Projects', `
with
` 'module' => 'Project',`
### Steps to Reproduce
1) Do new SuiteCRM installation
2) Check the file /custom/Projects/logic_hooks.php
### Your Environment
SuiteCRM Version used: 7.11.8 (and SugarCRM 6.5)
Browser name and version: Chrome 83.0.4103 and Firefox 77.0.1 (64-bit)
Environment name and version: PHP 7.3, MySQL
Operating System and version: Debian 9

**Comment by PedroErnst** [comment]
Can confirm, seen this happen too.

**Comment by samus-aran** [comment]
Looks like a quick solution. Anyone willing to create a PR for it, be our guest *sings*

**Comment by SinergiaCRM** [comment]
This has certainly a quick solution.

Although there are other parts of the code, where it also exists an inconsistency on the module's name "project", regarding the included "s" at the end of the word. More specifically on the original definition of relationships, like those:
![Selection_120](https://user-images.githubusercontent.com/61022311/88912796-1d63e200-d260-11ea-9c2a-3311428cd91d.png)
Accounts vardef
![Selection_121](https://user-images.githubusercontent.com/61022311/88912846-32d90c00-d260-11ea-86a2-72470fd2d674.png)
Contacts vardef

And in other modules too:
![Selection_122](https://user-images.githubusercontent.com/61022311/88912950-5f8d2380-d260-11ea-8411-396981bb0b4a.png)

For standardization, and comparing with the rest of the modules, it seems that the original module's name should be in plural as "Projects". 

We place this here only because it might affect on the current open PR, But this discussion should be probably happening in another Issue.
