### ISSUE TITLE
PDF of Report contains blank space when using a Main Group and a Total Calculation

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#8826]
#### Issue
When creating a PDF of a report that utilizes a main group and a total option, the report is littered with blank rows.  On a longer report, it can produce hundreds of blank pages.

For example, I am creating a report to total in person visits (total time and number of visits).  To do that, I have to group the report by company representative.  I am including the Count of the visits, and the sum of the hours.  If either or both of those are included, the report is hundreds of pages longer with blank entries.  The actual rows are there too, just buried in the blanks.  I have confirmed this on multiple different reports, and even a test report just showing 2 fields.  

#### Expected Behavior
Report PDF should only include rows with actual data

#### Actual Behavior
Report PDF is full of blank rows.  Nothing relevant in the suitecrm log or PHP log.

#### Steps to Reproduce
1 - Create report with main grouping and a total function (SUM, COUNT, etc)
2 - Ensure report contains fairly significant amount of results
3 - Create PDF of report

#### Your Environment

* SuiteCRM Version used: 7.10.27
* Browser name and version: Firefox 78.0.2, IE 11.9
* Environment name and version MySQL, PHP 7.1
* Operating System and version: CentOS 7.7.1908

**Comment by likhobory** [comment]
Confirmed in 7.11.15

![изображение](https://user-images.githubusercontent.com/5983672/88092727-9cd71e80-cb99-11ea-8b9d-8f50e56e1a19.png)

Result:

![изображение](https://user-images.githubusercontent.com/5983672/88092469-33efa680-cb99-11ea-8bf9-fb92e6f7edc6.png)

**Comment by cjmny** [comment]
If I can provide any other info or help, please let me know.

**Comment by QuentinDoe** [comment]
i have the same problem with version 7.11.15

**Comment by QuentinDoe** [comment]
no news ?

**Comment by mattlorimer** [comment]
The news is that if you fix this issue it breaks another issue, then they fix that issue and this get broken again, so we are fairly close to having a fix that will satisfy both issues

**Comment by QuentinDoe** [comment]
Bonjour , Nous vous confirmons la bonne réception de votre message par nos services .Nous mettons tout en oeuvre pour y répondre dans les meilleurs délais. A très vite, Vos dévoués courtiersCabinet l'assureur itinérant
