### ISSUE TITLE
Changing Account list view layout from Studio

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#8853]
#### Issue

When i try to change account list view layout from studio, it doesn't reflect to page view.

#### Expected Behavior

When i add or remove some fields to there, it should be shown.

#### Steps to Reproduce

1. Open studio
2. Go Account > Layout >list view
3. Add or remove some field to there.
4. Look at page view.

#### Your Environment

* SuiteCRM Version used: 7.11.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): Php 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by stenfalp** [comment]
Same problem for me. Version 7.11.20.
