### ISSUE TITLE
Problem with subpanel navigation

### ISSUE THREAD

**Issue by manuelopensymbol** [salesagility/SuiteCRM#8859]
Hello Everyone!

We’re notice that there is a problem with subpanels navigation buttons in SuiteCRM 7.11.12.
In any module you are on, if you try to click ‘Go to end page’ subpanel navigation button the list view will not update.

I’ve also try this functionality in a standard installation of SuiteCRM 7.11.8 and there is the same problem.

Anyone has also encountered this problem ?

Thank you in advance.

I've already open a support ticket on SuiteCRM support portal.
Here the link to the ticket.
https://community.suitecrm.com/t/problem-with-subpanel-navigation/74812/4

**Comment by pgorod** [comment]
See #8677

**Comment by manasan3010** [comment]
> See #8677

😭

**Comment by manuelopensymbol** [comment]
Thank you @manasan3010 and @pgorod, you fix works like a charm.
Thank you again for the support.
