### ISSUE TITLE
Access denied Error in suitecrm log file

### ISSUE THREAD

**Issue by kumaravel3657** [salesagility/SuiteCRM#8887]
Access denied Error in suitecrm log file
#### Issue
 I installed newly on suitecrm. 7.10.26 version. its working also fine but in that suitecrm.log file showing access denied error for all the run the application
Thu Oct  8 07:21:00 2020 [17893][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:22:00 2020 [18887][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:23:00 2020 [20248][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:24:00 2020 [21460][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:25:01 2020 [22497][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:26:00 2020 [23613][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:27:00 2020 [24656][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:28:00 2020 [25756][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:29:00 2020 [27097][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:30:00 2020 [28271][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:31:01 2020 [29306][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)
Thu Oct  8 07:32:00 2020 [30333][-none-][FATAL] Could not connect to DB server localhost as root. port 8889: Access denied for user 'root'@'localhost' (using password: YES)

#### Your Environment

* SuiteCRM Version used: 7.10.26
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Google Chrome
* Environment name and version (e.g. MySQL, PHP 7): 7.3.*
* Operating System and version (e.g Ubuntu 16.04): MAC OS

**Comment by pgorod** [comment]
This belongs in the Forums, not on GitHub...

https://community.suitecrm.com/c/suitecrm-forum-english-language/installation-upgrade-help/11
