### ISSUE TITLE
I can not duplicate line items from contracts to contact 

### ISSUE THREAD

**Issue by Beatific-Angel** [salesagility/SuiteCRM#8891]
I am using suitecrm
I gonna duplicate line items from contracts to contact
so I edited in studio and changed
But it can not show correctly
and I can not editing in contacts such as contracts.
my goal is duplicate line items from contracts to contacts
if you want i will provide my site access
Could you  help me?

**Comment by pgorod** [comment]
Cam you please close this thread and open it in the Forums?

https://community.suitecrm.com/

It's appropriate there, but not here, Github is for something else.
