### ISSUE TITLE
"Schedule Full Index" only does a partial index

### ISSUE THREAD

**Issue by cartbar** [salesagility/SuiteCRM#8899]
If you go to Admin->ElasticSearch and click "Schedule Full Index", it actually performs a partial index

#### Issue

In SchedulersJob.php, function runJob()

`
            $data = array($this);
            if (!empty($this->data)) {
                $data[] = $this->data;
            }
            $res = call_user_func_array($func, $data);
`

This calls runElasticSearchIndexerScheduler() in _AddJobsHere.php,

`
function runElasticSearchIndexerScheduler($data)
{
    return \SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::schedulerJob(json_decode($data));
}
`

Unfortunately, the $data parameter is the SchedulersJob, so the json_decode return an empty string.

#### Possible Fix

Change 
`function runElasticSearchIndexerScheduler($data)`

to

`function runElasticSearchIndexerScheduler($job, $data)`

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
Version 7.11.15   
Sugar Version 6.5.25 (Build 344)

* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by JanSiero** [comment]
Fixed by #10275
