### ISSUE TITLE
Email compose body field missing after upgrade to 7.11.16

### ISSUE THREAD

**Issue by brendan-pike** [salesagility/SuiteCRM#8913]
I upgraded two installs using the upgrade package from 7.11.15 to 7.11.16 and ran into this very serious issue. Both installs suffered the same outcome.

Forum thread also initiated by ceopx.

**Comment by SpyderZ** [comment]
I also have this problem, please fix it ASAP!

**Comment by brendan-pike** [comment]
Sorry but I think this fix is incomplete, if you reply to an email it appears different templates are used and the same issue occurs.

**Comment by mattlorimer** [comment]
cannot replicate, have you clear your cache

**Comment by QuentinDoe** [comment]
I have the same problem after update to 7.11.18 ...
