### ISSUE TITLE
Strings missing from hotfix-7.10.x but in the latest zip file [Language]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#8927]
#### Issue

/modules/Home/language/en_us.lang.php in 7.11.17 zip uses the language file from the develop branch (more strings) then the salesagility:hotfix-7.10.x 

https://github.com/salesagility/SuiteCRM/blob/develop/modules/Home/language/en_us.lang.php
See the strings for LBL_ELASTIC_SEARCH_EXCEPTION
https://github.com/salesagility/SuiteCRM/blob/0be76e34af63f13fca9700887242b44ccab77e79/modules/Home/language/en_us.lang.php#L241-L248

There must be a conflict with files has the develop branch has (on another language files) many other language strings not used in hotfix-7.10.x  / or in the released ZIP pack

#### Possible Fix

Update hotfix-10 from the released zip pack!

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by johnM2401** [comment]
Hi @horus68 

The language lines you've highlighted above seem to be for the Elasticsearch functionality
I may be mistaken, but I believe the Elasticsearch functionality is only available in 7.11.x versions currently,
Which would explain why the language strings for it are not found in the "hotfix-7.10.x" branch

You mentioned that there are mismatches on other language files also, do you perhaps have examples of these?

Thanks!

**Comment by horus68** [comment]
@johnM2401 i now see that was a mistake i did because I should have compared the released zip against the "Hotfix" branch not the "hotfix-7.10.x".
A question: should a language bugfix PR (non-breakable, no new functionalities) be made against the hotfix branch or the "hotfix-7.10.x"?

Please double check the diagram on PR submitting here:
https://docs.suitecrm.com/community/contributing-code/bugs/

**Comment by horus68** [comment]
Compare results 1 (language files diff)
Branches: Hotfix against Hotfix-7.10.x

![SuiteCRM-hotfix versus 7 10 x](https://user-images.githubusercontent.com/3055443/98138711-49c07780-1ebb-11eb-9fba-fd5c3794653c.png)

**Comment by johnM2401** [comment]
Hey @horus68 

I believe the ideal process would be to make a PR according to the oldest supported release that the issue is found in.
So:
PR to "hotfix-7.10.x" if the bug is in 7.10.x
PR to "hotfix" if the issue is only in 7.11.x

Hopefully that clears things up!
