### ISSUE TITLE
All fields starting with + or - get the + or - stripped

### ISSUE THREAD

**Issue by hertell** [salesagility/SuiteCRM#8936]
#### Issue
fields starting with + and - will get these characters deleted when saving the record

#### Expected Behavior
All characters you enter should be stored as you enter them. You should be able to store phonenumbers starting with +, like +3589123456. Now they get stored as 3589123456 which makes eg. tel-links giving a wrong phonenumber

#### Actual Behavior
Saving a record with + or - as the first character in the field, will get these characters deleted.

#### Temporary fix
As discoverde by John on the Forum, saving the record as ++3589123456 will result in +3589123456. You just have to remember to add the extra + every time you edit the record, otherwise it get's deleted the second time you save the record..

#### Steps to Reproduce
1. Enter in any field a text starting with + or -
2. Save the record
3. Fields with beginning with - and + get these characters stripped
4.

#### Your Environment
Latest 7.11.17-version running on Debian + PHP 7.4.11 + Apache

**Comment by pgorod** [comment]
I couldn't reproduce the error. Note that PHP 7.4 isn't supported - can you try with an earlier PHP please?

Also, if you can specify one specific module, one specific procedure to edit, and a specific field where the bug occurs for you, I can test exactly the same that you're testing.

**Comment by hertell** [comment]
I will test with an other php-version
I tested this with the Account and Contact.

**Comment by hertell** [comment]
This issue is now resolved. The + and - are not stripped anymore. Thanks for a quick fix!

**Comment by mwalbeck** [comment]
I also experienced this issue but with products when using the default currency, as the default currency has the id of "-99". So when one edited or created a new product the currency id would be stored as "99" with the "-" removed. This causes product pricing to show up as an error when trying to add a product to a quote or invoice.

I have tested it with the provided fix and it resolves the issue.
