### ISSUE TITLE
Broken link (partner list in About page)

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#894]
In the SuiteCRM 7.4.1 I'm running, the About page has a link to a list of partners on the suitecrm site that is throwing a 404, page doesn't exist:

https://suitecrm.com/index.php/suitecrm-partners

Google tells me the correct link could be 
https://www.suitecrm.com/component/content/article?id=170:partners&catid=126:pages

**Comment by willrennie** [comment]
Thanks for highlighting this. I have pushed a fix and referenced the issue.
