### ISSUE TITLE
Hardcoded 'by' label in calls history

### ISSUE THREAD

**Issue by QuickCRM** [salesagility/SuiteCRM#8999]
#### Issue

Call history has an english label which can't be translated 

#### Expected Behavior

by should be translated with user language

#### Possible Fix

change modules/Calls/reschedule_history.php
`$html .= '<li>'.$app_list_strings["call_reschedule_dom"][$reschedule->reason].' - '.$reschedule->date_entered.' by '.$reschedule->created_by_name.'</li>';`

#### Steps to Reproduce

1. Log in a non-english language
2. Reschedule the call
3. It shows reason, date **by** User

#### Your Environment

* SuiteCRM Version used: Any
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mac-Rae** [comment]
Able to raise a PR for this one @QuickCRM? Any questions please give me a shout!
