### ISSUE TITLE
cleanVardefs unsets every fieldDefs definition

### ISSUE THREAD

**Issue by adriangibanelbtactic** [salesagility/SuiteCRM#900]
In current code cleanVardefs unsets every fieldDefs field definition.

This bug is also present in current master branch. I refer to it thanks to the most current commit up to date.

So, please take a look at:

https://github.com/salesagility/SuiteCRM/blob/b533ad20e5cf0a51dcd35cb99b9c2f97eabd86bc/include/SugarObjects/VardefManager.php#L145-L151

What we have is:
```
        foreach($fieldDefs as $field => $defs)
        {
            if (empty($def['name']) || empty($def['type']))
            {
                unset($fieldDefs[$field]);
            }
        }
```
and if I'm not mistaken this is a TYPO error which seems to be safe but, a TYPO error nonetheless.

So I guess it can be corrected by using:

```
        foreach($fieldDefs as $field => $def)
        {
            if (empty($def['name']) || empty($def['type']))
            {
                unset($fieldDefs[$field]);
            }
        }
```

I wonder myself it this fix will have secondary effects elsewhere. I'll let the Suitecrm experts figure it out.

What's obvious right now is that many fields are being unset to be set up later without having to be deleted/setup in the first place.

That means that if this bug is fixed SuiteCRM should feel more responsive / fast.

**Comment by mattlorimer** [comment]
great find :clap:
