### ISSUE TITLE
new SugarBean per se iterates all fields_meta_data

### ISSUE THREAD

**Issue by adriangibanelbtactic** [salesagility/SuiteCRM#901]
Introduction
----------------

I found this bug while debugging exactly v7.4 version. The bug happens to arise when going into Meetings (List View).

So the lines that trigger this problem are:

https://github.com/salesagility/SuiteCRM/blob/v7.4/data/SugarBean.php#L3912-L3913

So:
```
            $objSugarBean = new SugarBean();
            $count_query = $objSugarBean->create_list_count_query($query);
```

If you take a look at newer tags (v7.4.1 and up) and current 7.4.x branch it's all ok. They are using previous code like:

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/data/SugarBean.php#L3912

So:
```
$count_query = SugarBean::create_list_count_query($query);
```

How has been this fixed?

Thanks to commit: 134088e61a98e9a6091641852cbdb3f570926b2d which reverses many other things at the same time. More details in original reverted pull request: https://github.com/salesagility/SuiteCRM/pull/606 .

Problem about iterating
---------------------------------

So, I don't know if you are not supposed to do a new SugarBean() directly but it happens to do some strange stuff while doing it that I think it was not intented to do.

So, let's take a look at the current code when trying to create a new SugarBean:

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/data/SugarBean.php#L339

```
$this->setupCustomFields($this->module_dir);
```

Take notice that $this->module_dir would be null or an empty string here.

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/data/SugarBean.php#L1309-L1314

```
    function setupCustomFields($module_name, $clean_load=true)
    {
        $this->custom_fields = new DynamicField($module_name);
        $this->custom_fields->setup($this);
    }
```

Now we are creating a new DynamicField which seems to be happy with an empty $module_name (Maybe there should be a safety check here? Or before trying to create a DynamicField?).

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L49-L52

```
    function DynamicField($module = '') {
        $this->module = (! empty ( $module )) ? $module :( (isset($_REQUEST['module']) && ! empty($_REQUEST['module'])) ? $_REQUEST ['module'] : '');
        $this->base_path = "custom/Extension/modules/{$this->module}/Ext/Vardefs";
    }
```

And then it setups it.

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L77-L87

which in turn runs:

```
$this->buildCache ( $this->module )
```
because custom_fields is not defined.

So, now we are in: buildCache function:

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L104-L161

which somehow handles an empty module:

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L117-L120

```
        else
        {
            $results = array ( ) ; // clear out results - if we remove a module we don't want to have its old vardefs hanging around
        }
```
but then it continues to rebuild the cache for SugarBean .

So if you debug it like I did you wil notice that in this line:
https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L123

```
$query = "SELECT * FROM fields_meta_data WHERE $where deleted = 0";
```

$query value will be:

```
SELECT * FROM fields_meta_data WHERE deleted = 0
```

which I'm not sure we want to use in the first place in order to iterate ALL OF the fields_meta_data.

If this line is used somewhere in the code (or maybe when the class is being defined initially) and this is nonsense (I mean, not needed at all) we could make Suitecrm to run faster.

If it's the intented behaviour then it's ok for me.

**Comment by samus-aran** [comment]
@adriangibanelbtactic 
As the other Issue had provided a fix then I would like to proceed to close this issue.
