### ISSUE TITLE
Target-List sub-panel not populating

### ISSUE THREAD

**Issue by policyhorizons** [salesagility/SuiteCRM#9012]
#### Issue

When adding a contact to a Target-List, the Target-List Sub-Panel under the Contact module doesn't get populated.
(Work for Projects). Also, when adding a Contact to a Target-List using the sub-panel in the contact module (which works)
if we try later to remove the contact using the Target-List module the Contact still appears in the Contact Sub-Panel (Target-List).
It's as if the sub-panel table for Target-List in the database is not linked properly to the main Target-List table. (not sure if that is how this works)

#### Expected Behavior

We should see which Target-List a Contact is a part of by opening the contact details.
The contact should get removed from the Sub-Panel target list when deleting it from the Target-List module.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by johnM2401** [comment]
Hey there, 

I might be mistaken, but I don't believe that there is a Target List subpanel beneath Contacts, out of the box.

Has this been added to the module through Code/Studio?
(Unless you are referring to the "Events" subpanel, perhaps?)

Would you be able to provide some Screenshots of this, to give a little clarity on the situation?
Also, which version of SuiteCRM are you using?

Thanks!

**Comment by pgorod** [comment]
An Issue where the person doesn't bother to fill in the Issue Template is a waste of our time...

**Comment by policyhorizons** [comment]
Thanks for the quick reply,

You might be correct. I took over this installation so they might’ve tried to add the sub-panel but didn’t
program all the other functions around it for it to work properly (I had assumed it was default like the other panels).
I’ll see if I can make it work somehow. Surprised this is not default…seems to function similarly to the Events or Projects sub-panels..)
Since they have a function to add contacts in Bulk to a Target-List I thought the Target-List sub-panel under contact made sense.

I am running the latest patch (7.11.18)

**Comment by policyhorizons** [comment]
Thanks for the helpful comment.

Replying with this type of answer is probably much more wasted time than me
filling out what I know and trying to get help.

**Comment by johnM2401** [comment]
Hey @policyhorizons 

Thanks for your response

It certainly sounds like custom work and I can see why you would assume the Subpanel was there by default.

<br>

You could check if it is a double-relationship by going to Admin->Studio->Contacts->Relationships in the CRM.

The OOTB relationship seems to be "prospect_list_contacts", so if there are others, then that would explain it.

<br>

However, if not, there's still the possibility that it has been added by Code.
(Likely somewhere around /custom/Extension/modules/Contacts/Ext/Vardefs/ )

<br>

I'm going to close this bug report for now, but let us know how you get on, and I'll be happy to re-open if a bug has been identified

Thanks again!
