### ISSUE TITLE
new SugarBean per se resets custom_fields on Callvardefs.php

### ISSUE THREAD

**Issue by adriangibanelbtactic** [salesagility/SuiteCRM#902]
Read first
========
So, please read: #901 . This is a continuation. This means this bug happens in tag: v4.7 exactly. I'm not sure it can be triggered in a clean v4.7 installation but it happens to our installation.

What happens
===========
So basically when visit: Meetings (List View) the file:
cache/modules/Calls/Callvardefs.php
(and, actually many of the other files)
lose the:
custom_fields definition.

Once that happens when you go to: Calls the first search is doomed to fail and the logs show something similar to:

```
Thu Jan 28 18:36:14 2016 [7062][1][FATAL]  Query Failed:  SELECT  calls.id , calls.parent_id , calls.assigned_user_id , calls.recurring_source , calls.status , calls.direction , calls.name , calls.contact_c  , LTRIM(RTRIM(CONCAT(IFNULL(contacts.first_name,''),' ',IFNULL(contacts.last_name,'')))) contact_name, jtl0.contact_id contact_id, calls.parent_type , calls.date_start  , jt1.user_name assigned_user_name , jt1.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod, calls.date_entered , calls.created_by  FROM calls   LEFT JOIN  calls_contacts jtl0 ON calls.id=jtl0.call_id AND jtl0.deleted=0

 LEFT JOIN  contacts contacts ON contacts.id=jtl0.contact_id AND contacts.deleted=0
 AND contacts.deleted=0  LEFT JOIN  users jt1 ON calls.assigned_user_id=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0 where calls.deleted=0 ORDER BY calls.direction ASC LIMIT 0,101: MySQL error 1054: Unknown column 'calls.contact_c' in 'field list'
```
where: contact_c is a Calls' custom field.

Digging into the code
================

So, now I continue my #901 explanation. So, when you visit Meetings (List View) somehow it uses getListViewData function from ListViewData.php.

https://github.com/salesagility/SuiteCRM/blob/b533ad20e5cf0a51dcd35cb99b9c2f97eabd86bc/include/ListView/ListViewData.php#L232

which in turn calls: getTotalCount either here:
https://github.com/salesagility/SuiteCRM/blob/b533ad20e5cf0a51dcd35cb99b9c2f97eabd86bc/include/ListView/ListViewData.php#L317
or here:
https://github.com/salesagility/SuiteCRM/blob/b533ad20e5cf0a51dcd35cb99b9c2f97eabd86bc/include/ListView/ListViewData.php#L464

.

That's where we get into:

https://github.com/salesagility/SuiteCRM/blob/b533ad20e5cf0a51dcd35cb99b9c2f97eabd86bc/include/ListView/ListViewData.php#L187

which it's fixed on master branch.

But if you are using: v7.4 tag you get:

https://github.com/salesagility/SuiteCRM/blob/v7.4/include/ListView/ListViewData.php#L187-L188

```
            $objSugarBean = new SugarBean();
	        $count_query = $objSugarBean->create_list_count_query($main_query);
```

so, once again, taking a look at: #901 for intermediate debug steps we are finally in:

https://github.com/salesagility/SuiteCRM/blob/5e73e57778bacc7cf88d99f15c409210244dd387/modules/DynamicFields/DynamicField.php#L149

saveToVardef is called.

If you debug it further you will see that it will somehow resave the:
```
cache/modules/Calls/Callvardefs.php
```
file without taking into account the:
```
custom_fields
```
value.

And  then when going into Calls, well, I guess it assumes the Callvardefs.php it's correct, it loads it, and it lacks custom_fields. So... you get the mysql error.

I'm bringing this error here because although as I said in #901 it only happens in v7.4 tag this other part of the code which continues to work with $module being empty is here on master branch ( Current commit: d7f628911d4165a8033bdf14cb51cceff3977f05 ).

And in this case it has unattended consequences.

As I said maybe there's something going around that only affects our installation that I'm unaware of.

But, currently, this makes going to Meetings ... to fail any other module that has custom fields. Only once but it happens.

So...

* Going into Meetings. Going into Calls. The search fails.
* Going into Meetings. Someone else is in Accounts trying to create a Contact from subpanel... it fails.

All of these actions fail because of this problem.

**Comment by mattlorimer** [comment]
fixed in 7.5

**Comment by adriangibanelbtactic** [comment]
Sorry to reopen this. It's quite strange you don't make any reference to any commit.

Let's try to make clear my statement about this bug.

I do not care too much about:

* Going into Meetings. Going into Calls. The search fails.
* Going into Meetings. Someone else is in Accounts trying to create a Contact from subpanel... it fails.

because, as I said, it's fixed on last version.

This bug is more about:

1) Why when someone does:

```
$objSugarBean = new SugarBean();
```

it implies that cache/modules/Calls/Callvardefs.php (and many other files) loses: custom_fields definition ?
2) Shouldn't that behaviour had to be corrected?
3) Or is it somehow forbidden / not recommended that anyone does a:
```
new SugarBean()
```
in the first place?

Thank you.

**Comment by chris001** [comment]
This is definitely a bug!
Creating a new object should not have massive side effects of resetting all custom fields and destroy cached php files that other users are depending on!
Good thing it's fixed now in 7.5.

For creating SugarBean .... in other words, CRUD operations.... 
it's suggested to use the BeanFactory for CRUD operations (create read update delete).
http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.5/API/Classes/BeanFactory/

**Comment by adriangibanelbtactic** [comment]
> fixed in 7.5
> Good thing it's fixed now in 7.5.

I'm still waiting for a commit or code reference where this has been fixed.

Else, with the current code I am pretty convinced that doing a:

```
$objSugarBean = new SugarBean();
```
will have the same side-effects in cached php files as I described originally.

Thank you.

**Comment by mattlorimer** [comment]
You very easily look at the code and see this is not the case
But in v7.4.1:

- https://github.com/salesagility/SuiteCRM/commit/134088e61a98e9a6091641852cbdb3f570926b2d
- https://github.com/salesagility/SuiteCRM/commit/285963471bc65cd4dd7aee190abcc549c6cf5499

**Comment by adriangibanelbtactic** [comment]
I'm pretty sure that I am right (I just gave a quick look at the code) but you seem sure of yourself.

So If I have some spare time I will try replace:
```
$count_query = SugarBean::create_list_count_query($query);
```
by:
```
$objSugarBean = new SugarBean();
$count_query = $objSugarBean->create_list_count_query($query);
```
on:

https://github.com/salesagility/SuiteCRM/blob/134088e61a98e9a6091641852cbdb3f570926b2d/data/SugarBean.php#L3912

in the latest Suitecrm 7.5.x stable release and probably I will give feedback here.
