### ISSUE TITLE
User Preferences Wrong Label

### ISSUE THREAD

**Issue by peter-lernyx** [salesagility/SuiteCRM#9021]
Should this say 'Time Zone'? It does when yo ugo to Edit Mode..

![grafik](https://user-images.githubusercontent.com/75390480/105966072-7502cf00-6084-11eb-82ca-047a6e6ef0d8.png)

**Comment by peter-lernyx** [comment]
That's weird, in Edit Labels it actually has the right label assigned...?

![grafik](https://user-images.githubusercontent.com/75390480/105969155-3b33c780-6088-11eb-9bba-d719ed323b50.png)

**Comment by pgorod** [comment]
You don't say where this screen is...

You don't say your SuiteCRM version...

**Comment by peter-lernyx** [comment]
It does say user preferences right up there in the title? Version is 7.11.18, so if it is there it is presumably in all others.

![grafik](https://user-images.githubusercontent.com/75390480/105983333-da60bb00-6098-11eb-86de-f9de5d326146.png)

**Comment by pgorod** [comment]
This doesn't appear on the live demo, and in one other system I tried.

You might be seeing some caching glitch, assuming you don't have any customizations or unsupported PHP version that might be causing this.

Filling in the complete Issue report template helps narrow down things. It costs you more time but saves maintainers/testers' time.

**Comment by peter-lernyx** [comment]
OK, thanks. Will investigate.

**Comment by horus68** [comment]
From softaculous demo (Version 7.11.18 Sugar Version 6.5.25 (Build 344)) https://www.softaculous.com/demos/SuiteCRM
![2021-01-27 12_21_18-SuiteCRM](https://user-images.githubusercontent.com/3055443/105990397-4ee82980-609a-11eb-9650-434cb5545483.png)

**Comment by peter-lernyx** [comment]
Yes, that's what I said. Unfortunately I can't even log in to the demo instance, no idea why

**Comment by horus68** [comment]
> Yes, that's what I said. Unfortunately I can't even log in to the demo instance, no idea why

The softaculous demo has some issues if you try to login in the initial screen:
1- Enter https://www.softaculous.com/demos/SuiteCRM
2- Waite till the instance starts... do not enter login details
3- Click the link "Admin Panel" on the top right
4- then, in the new windows, enter the login details

**Comment by pgorod** [comment]
I'm not seeing the bug in the Softaculous demo, it shows ok for me... both on Firefox and on Edge.

**Comment by peter-lernyx** [comment]
You need to look on the right page, i.e. the overview page, NOT the detail page (i.e. not after clicking ACTIONS -> EDIT)

![grafik](https://user-images.githubusercontent.com/75390480/106045700-96de6f00-60e1-11eb-87b6-03e70cbb952d.png)

**Comment by horus68** [comment]
> I'm not seeing the bug in the Softaculous demo, it shows ok for me... both on Firefox and on Edge.
@pgorod 
(in portuguese just to make a direct note to the user) No botão da direita não carregues logo no utilizador administrador (pois surge a página de edição).
Carrega na lista de Utilizadores. Aí entras na página dos utilizadores e escolhes o Administrador (é o único na lista) e tens estes ecrãs (que são o ecrã  de visualização

**Comment by pgorod** [comment]
Thanks. So, 12 posts later, here are the "steps to reproduce" that are missing from the Issue:

1. Click Admin
1. Click User management
1. Click a specific user name
1. Click Advanced

I confirm that I can reproduce this issue.

Going directly from the top-right menu into the current user's preferences page does not exhibit the bug.

**Comment by pgorod** [comment]
The problem comes from here:

https://github.com/salesagility/SuiteCRM/blob/master/themes/SuiteP/modules/Users/tpls/DetailView-advanced-tab-content.tpl#L184
