### ISSUE TITLE
Moved required module (InboundEmail) needs reference to be corrected in _AddJobsHere.php

### ISSUE THREAD

**Issue by LewisR** [salesagility/SuiteCRM#903]
Line 535 of modules/Schedulers/_AddJobsHere.php in 7.5.1 reads:

`require_once 'custom/modules/InboundEmail/AOPInboundEmail.php';`

however, InboundEmail has been moved to /modules from /custom/modules, so this triggers an error for the "missing" required module.

Suggest:

`require_once 'modules/InboundEmail/AOPInboundEmail.php';`

unless a conditional is required (I don't know this code all that well; I'm just cleaning up after a 7.5.1 upgrade).

**Comment by ghermans** [comment]
I guess this is fixed in v7.5.1

**Comment by LewisR** [comment]
Comment above, corrected. This appears in 7.5.1. I'm still cleaning up other bits.

**Comment by ghermans** [comment]
@LewisR Thanks for submitting this issue, it was safe to remove the missing custom

**Comment by LewisR** [comment]
Thanks for reminding me that I upgraded to 7.5.1 and not to 7.5! (Too much on my mind!)

Cheers, Glenn.

**Comment by LewisR** [comment]
Oops. Didn;t mean to close this until fixed in trunk.
