### ISSUE TITLE
Log Call Activity not working

### ISSUE THREAD

**Issue by bawatkins** [salesagility/SuiteCRM#904]
Just upgraded to 7.5.1 from 7.4.3 and the log call activity under opportunities is not working, schedule meeting and compose email are. No pop up appears and the create task button disappears.

Have tried on IE 11 and Firefox 43.0.4

Server is Ubuntu 14.04 with Apache and MySQL

**Comment by willrennie** [comment]
This works fine on an upgrade locally. Did the upgrade run successfully? Have you run a Quick Repair & Rebuild? Have you set permissions correctly for the environment the CRM is installed on? Are there any errors in your browser console log?

**Comment by willrennie** [comment]
Closing as no response received in 6 weeks or so. If you can provide a response to my previous questions/statements then we can further progress your issue.
