### ISSUE TITLE
Question: How can I add LDAP authentication to OAuth

### ISSUE THREAD

**Issue by terencejackson8000** [salesagility/SuiteCRM#9040]
Dear all,

this is more a question then an issue: How can I add my LDAP authentication to authenticate these users via OAuth?

I think I have already found the right file to do this, which is: /Api/V8/OAuth2/Repository/UserRepository.php
I have added LDAPAuthenticateUser.php as an import and can also initialize the LDAPAuthenticateUser class. When calling the authenticateUser method I am always getting an error: Not able to connect to the LDAP server.

This is because the LDAP server information is stored in GLOBALS and somehow these information is not available when calling it in the OAuth context.

I was also looking for config options in the config.php and similar files, but could not find a LDAP section in these.

Can you help me how I can get the LDAP authentication into the OAuth context? Maybe there is even a simpler way of achieving this.

**Comment by chris001** [comment]
Have a look at #5107 and #8642 you should be able to call into a class in that code to authenticate the user thru `LDAPS` (the secure `LDAP`).
