### ISSUE TITLE
Calling custom folder facebook/twitter mapping

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#905]
Social hooks.php was calling the custom facebook/twitter mapping, which no longer existed due to the moving of custom files to the core application.

**Comment by xzax** [comment]
Please share the fix.

**Comment by horus68** [comment]
The fix is associated with the commit posted above by Willrennie.
If you click it you will see the file diff and the changes proposed

**Comment by pgorod** [comment]
@willrennie @shogunpol I suggest reopoeing this. A few [instances of the old reference](https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=custom%2Fmodules%2FConnectors%2Fconnectors%2Fsources%2Fext%2Frest%2Ftwitter&type=Code) are still left in the code:

This breaks installations with Facebook and Twitter feeds turned on in `Admin->Activity Streams`, it gives a blank screen on Home, or show these errors for people who have error reporting turned on:

```
Notice: Undefined index: Facebook in C:\xampp\htdocs\SuiteCRM\modules\SugarFeed\Dashlets\SugarFeedDashlet\SugarFeedDashlet.php on line 83

Notice: Undefined index: Twitter in C:\xampp\htdocs\SuiteCRM\modules\SugarFeed\Dashlets\SugarFeedDashlet\SugarFeedDashlet.php on line 83

Warning: require_once(custom/modules/Connectors/connectors/sources/ext/rest/twitter/config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\SuiteCRM\include\social\get_feed_data.php on line 60

Fatal error: require_once(): Failed opening required 'custom/modules/Connectors/connectors/sources/ext/rest/twitter/config.php' (include_path='C:\xampp\htdocs\SuiteCRM;C:\xampp\htdocs\SuiteCRM\include\HTMLPurifier/standalone;C:\xampp\htdocs\SuiteCRM\include/..;C:\xampp\php\PEAR') in C:\xampp\htdocs\SuiteCRM\include\social\get_feed_data.php on line 60
```

I don't have this problem myself, I'm just reporting from what I heard [in the forums](https://suitecrm.com/forum/suitecrm-7-0-discussion/12877-homepage-appears-as-blank-when-i-log-in-help-please#43509). @CamoMacdonald was also helping out on that thread.

**Comment by pgorod** [comment]
There must be something in the newest versions that works especially bad with this bug.

There are users popping up every day in the forums complaining about this:

Yesterday: https://suitecrm.com/forum/suitecrm-7-0-discussion/13067-missing-dashboard-for-new-users
Today: https://suitecrm.com/forum/international-language-support/13061-blank-screen-on-home-page#44123

We didn't see these complains before maybe 7.7.9, but the broken references have been there long before... I don't know why they are causing problems only now...?

**Comment by pgorod** [comment]
Thanks @chris001 and @mattlorimer 

But I'm afraid maybe this is not quite enough, that link I gave above lists quite a few more instances of the wrong path in our code base:
https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=custom%2Fmodules%2FConnectors%2Fconnectors%2Fsources%2Fext%2Frest%2Ftwitter&type=Code

**Comment by horus68** [comment]
@samus-aran should this be closed?

**Comment by samus-aran** [comment]
Yeah @pgorod I need to see where that additional commits have gone too and then we can mereg the rest in.  I'll unlabel it for now.

@chris001 Are you able to link in your PR that has these additional fixes?

**Comment by pgorod** [comment]
@samus-aran the link is in my comment above, #3142 (that's a PR, not an Issue). You just need to merge that one and everything will be completed.

**Comment by samus-aran** [comment]
Re-applied label ;)
