### ISSUE TITLE
Studio Layout Update Issue

### ISSUE THREAD

**Issue by eagarao** [salesagility/SuiteCRM#9062]
Problematic Layout updates in Studio.

Issue

1. **List View:** 
- When updating layout in Studio, some fields disappear when hitting Save. 
- When you hit the Save button again, they'll re-appear but not in Available column. You need to add them back again and hit save to add back in layout though they'll disappear again.

2.  **Search**
- When updating Search layout, you need to do a Quick Repair and Rebuild for changes to reflect

3. **Edit/Detail View**
- When saving layout, Studio would display old version of layout. 
- Need to refresh to show new layout

Expected Behavior
Studio should be able to update layouts without issues

Actual Behavior
Studio layout updates is buggy

Possible Fix
--

Steps to Reproduce
Update layouts in Studio.
This should be High Priority

Your Environment
SuiteCRM Version used: Version 7.11.15
Browser name and version: Chrome, Firefox, Edge
Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by Mac-Rae** [comment]
1. Agreed and replicable, 100% an issue here
2. Nothing we could change I would believe unless anyone has a suggestion to handle it better
3. Super minor but yet would be nice to have
