### ISSUE TITLE
email settings not working no matter what

### ISSUE THREAD

**Issue by Shootify** [salesagility/SuiteCRM#9065]
Hello, been posting all over trying to figure out why my suitecrm wont get my smtp server to work, i use a cpanel with 

IMAP Hostname: | mail.domain.com
-- | --
IMAP Port: | 143
IMAP Security: | STARTTLS
IMAP Authentication Method: | Normal Password
SMTP Hostname: | mail.domain.com
SMTP Port: | 587
SMTP Security: | STARTTLS
SMTP Authentication Method: | Normal Password
However no matter what i do it just wont work. i get error :

MAIL FROM command failed,Access denied - Invalid HELO name (See RFC2821 4.1.3) ,550,SMTP server error: MAIL FROM command failed Detail: Access denied - Invalid HELO name (See RFC2821 4.1.3) SMTP code: 550SMTP server error: MAIL FROM command failed Detail: Access denied - Invalid HELO name (See RFC2821 4.1.3) SMTP code: 550

another weird behavior is when i am on email settings i click on other to set my smtp, whatever a filled in there it gets populated on gmail, yahoo and microsoftexchange TABs as well. needs to get this ASAP. thanks in advanced and sorry if for some reason this is not the right place to ask, but as i said before i already ask on the forums. but no help.

**Comment by mattlorimer** [comment]
I believe "Invalid HELO" typically mean that SMTP is not available or enabled on you email provider. SMTP is required for SuiteCRM to work at the moment. So may be something to check, who or what are you using for email?

**Comment by Shootify** [comment]
i use my own email server with hestiacpanel, i know its working since is in use. in fact we have invoiceninja working with it.

**Comment by JedMeister** [comment]
Please excuse me jumping in here.

A quick google suggests that `code: 550 SMTP server error`is user "blocked", or ignored for some other reason.

`Invalid HELO name (See RFC2821 4.1.3)` suggests to me that the name given by the client (SuiteCRM in this case) is invalid and/or isn't resolvable via DNS. If you look at [RFC2821 - section 4.1.3](https://tools.ietf.org/html/rfc2821#section-4.1.3) (as noted in the error message), that relates to using IP address if domain name isn't resolvable.

So filling in the gaps, my guess is that there is some issue with the SuiteCRM config (not using a domain name that is valid and/or resolvable via DNS; or a public IP address), DNS config issues, or perhaps some problem with the SMTP server looking up this particular address (perhaps new DNS records that haven't propagated to the SMTP server itself)?

Please note, that I'm a Linux user and developer with no experience with this particular SMTP error nor significant experience with or knowledge of SuiteCRM.

So @Shootify - firstly I would recommend double checking what domain is in the SutieCRM config. If that's not right, update it (and restart your webserver). If that all appears ok and you have shell access to the SMTP server, then I would recommend doing a domain name lookup and checking that it resolves ok. If you don't have shell access, I suggest at least checking the DNS records for your domain with a number of different DNS nameservers (unfortunately, if that seems ok, it still doesn't rule out your SMTP server not being able to lookup the domain, but it might confirm an issue).
