### ISSUE TITLE
Project Tasks showing as empty rows in My Project Tasks Dashlet

### ISSUE THREAD

**Issue by aromasko** [salesagility/SuiteCRM#907]
```
PHP Notice:  Undefined index: columns in /modules/ProjectTask/Dashlets/MyProjectTaskDashlet/MyProjectTaskDashlet.php on line 58

PHP Warning:  Invalid argument supplied for foreach() in /include/Dashlets/DashletGeneric.php on line 176, referer: /index.php?module=Home&action=index&record=
```

There are rows being created for each record, and the edit button takes you to the correct page, but there is no data or columns populating the rows.
See screenshot: https://i.imgsafe.org/4e0b9c1.png 

Also, the dashlet edit page shows no available columns to either add or remove.
See screenshot: https://i.imgsafe.org/9ee677d.png

**Comment by ctucker1984** [comment]
Go to /modules/ProjectTask/Dashlets/MyProjectTaskDashlet/MyProjectTaskDashlet.data. Line 54.
Replace: $dashletData['ProjectTaskDashlet']['columns']
With: $dashletData['MyProjectTaskDashlet']['columns']

They left out the My

**Comment by emcrobert** [comment]
Thanks for the fix ctucker1984. Have tested and agree that works. I have created a pull request so your change should be included in next release.
