### ISSUE TITLE
Decimal places change after saving a workflow

### ISSUE THREAD

**Issue by alexcodelab** [salesagility/SuiteCRM#9074]
#### Issue

When I save a workflow, all decimal places are converted to .00 It converts from 46,41 to 46,00

**Screenshot when i create a workflow**

![image](https://user-images.githubusercontent.com/20392674/113110669-9e1c1900-9207-11eb-8a20-5fe7ff3f8fef.png)

**Screenshot after saving the workflow and edit again, the decimal points goes to 00**

![image](https://user-images.githubusercontent.com/20392674/113110863-dcb1d380-9207-11eb-9872-128a23f655e8.png)

#### Expected Behavior

If i save the workflow, the values with decimal places should not be changed

#### Actual Behavior

When I save the workflow, the decimal places on the values change

#### Possible Fix

If I replace the commas with a point and then save the workflow, then the decimal places are displayed. But when I edit the workflow, the points with the commas are exchanged by the system and when I save, the decimal places are converted back to .00

#### Steps to Reproduce

1. Create Workflow
2. Fill out the nessesary fields
3. Then scroll down to Actions
4. Choose "Create record"
5. Datatype: Invoice
6. Put a field in for example Tax, Value =>7,41
7. And Save the Workflow
8. Than edit again the created workflow and you see by tax 7,00

#### Your Environment

* SuiteCRM Version used: 7.11.18
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7.3.27-1):
* Operating System and version (e.g Raspbian GNU/Linux 10):

**Comment by jack7anderson7** [comment]
Hi @alexcodelab,

I'm unable to replicate this issue on the latest hotfix-7.10 and hotfix branches. Please let me know if this is still an issue for you.

Thanks
