### ISSUE TITLE
JSON Error in related field's popup Since 7.11.19

### ISSUE THREAD

**Issue by holdusback** [salesagility/SuiteCRM#9106]
#### Issue

In a related field if you select the small arrow button, search in any field, select an entry from it you will have a json error
 
![image](https://user-images.githubusercontent.com/46958376/116698582-d52b4900-a9c4-11eb-8a07-b9f5401a3a54.png)

Screenshot is from the demo website. I search "Smith" in last name and then click on the entry.
The error look like to happen only if you search in the popup, if you select directly without re search you dont have it.

When the error happen, the popup don't close and the fields is not filled with the entry.

#### Expected Behavior
Close popup and fill the fields with selected entry.

#### Actual Behavior
the popup dont close and the fields is not filled with the entry.

#### Steps to Reproduce
1. Select any related field
2. Click on the arrow to display the popup
3. Search any word in any field
4. Click on an entry after the search happen

#### Your Environment

* SuiteCRM Version used: 7.11.19
* Browser name and version : Latest Chrome version
* Environment name and version : PHP 7.4

**Comment by digitecmedia** [comment]
Hello. We have same issue.

Kind regards.

**Comment by QuickCRM** [comment]
This also happens on SuiteCRM 7.10.30

**Comment by QuickCRM** [comment]
Hi @holdusback,

Could you please try that PR: https://github.com/salesagility/SuiteCRM/pull/9109

I checked it on a 7.10.30 (LTS) instance, but I don't have any 7.11 instance to try it.

**Comment by digitecmedia** [comment]
> Hi @holdusback,
> 
> Could you please try that PR: #9109
> 
> I checked it on a 7.10.30 (LTS) instance, but I don't have any 7.11 instance to try it.

It works!!. Thanks a lot.

Kind regards.

**Comment by holdusback** [comment]
Look like it fixed it 👏

**Comment by labcerouno** [comment]
it worked! thank you my lord, gods from pantheon, github and all you devs

**Comment by SuiteLover** [comment]
On 7.11.19 problem remains in few scenarios. 

If you try to add products to quoetes using popup window and before picking product you use search mechanism, you won't be able to pick any record. Bug is present on demo installation - 01.06.2021

If you have custom modul created with Many 2 Many relation you can add realttion record between modules from custom module view but if you try to do it other way it won't work.
