### ISSUE TITLE
Email Import does not work after 7.10.30 upgrade. 

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#9114]
#### Issue
After upgrading from 7.10.29 to 7.10.30, the email import functionality no longer works.  

#### Expected Behavior
Email import works as before. 

#### Actual Behavior
Email import no longer works. 

#### Possible Fix
Potentially a JS bug. 

#### Steps to Reproduce
1. Go to CRM inbox.
2. Slect from emails list emails to import. 
3. Click on Bulk Action -> Import. 
4. Select Related to -> Search. This opens a new window. 
5. Make the search.
6. When cliecking on the Lead Name, the following error is generated (as opposed to the name being passed to the parent window) 

(See sequence below)
<img width="1424" alt="1" src="https://user-images.githubusercontent.com/18371928/117291479-5c6a3800-ae6f-11eb-9aa3-29f2485b5d55.png">
<img width="892" alt="2" src="https://user-images.githubusercontent.com/18371928/117291489-5f652880-ae6f-11eb-915b-77548182ff72.png">
<img width="748" alt="3" src="https://user-images.githubusercontent.com/18371928/117291495-612eec00-ae6f-11eb-815e-87a97985173b.png">
<img width="896" alt="4" src="https://user-images.githubusercontent.com/18371928/117291517-65f3a000-ae6f-11eb-991d-431eb8fbc453.png">

#### Context
High priority, we can not upload any emails to CRM and traceability of email conversation is lost. 

#### Your Environment
* SuiteCRM Version used: 7.10.30
* PHP 7.3.28
* MySQL 5.6.51
* Browser name and version: Safari 14.1, Chrome 90, Edge. 
* Operating System and version (e.g Ubuntu 16.04): Mac OS 11.3. Windows 10.

**Comment by johnM2401** [comment]
Thanks for raising!

Just as additional info, looks like this is potentially the same as: https://github.com/salesagility/SuiteCRM/issues/9106

**Comment by evgu** [comment]
Thanks @johnM2401. It is the same issues as #9106 and proposed fix solves it.
