### ISSUE TITLE
Changing "Required" property in a custom field from Studio, doesn't apply immediately

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9119]
When setting a custom field as mandatory in Studio, it won't be displayed immediately in the EditView of the module. 

#### Issue
When setting a custom field as mandatory in Studio, it won't be displayed immediately in the EditView of the module. A quick repair is needed, or deleting manually the folder cache/themes.

#### Expected Behavior
When changing the required property of a custom field in studio, the changes should appear immediately.

#### Actual Behavior
When changing the required property of a field from studio, the cache/modules folder is rebuilt. But the required property is also present in the `cache/themes` files, therefore the folder (or the folder of the module) needs to be rebuilt as well.

#### Possible Fix
In the lines 130-135 of the file `include/TemplateHandler/TemplateHandler.php` inside the function clearCache(), it says:
```
/**
         * Due to a change since 7.7, the tpl files may also exist in the current theme folder.
         *
         * So we need to also clear tpl files in eg cache/[Current Theme]/[modules]/**.tpl
         * The tpl files for each theme should be cleared for consistency.
         */
```
And the following code rebuilds the + cache/themes/modules` folder. 

Probably this needs to be implemented as well inside the buildCache() function of the file `modules/DynamicFields/DynamicField.php`, which recreated the `cache/modules` folder but doesn't change anything from the `cache/themes` folder

#### Steps to Reproduce
1. Deactivate Developer Mode (important for the themes folder to persist)
2. Create a custom Field from Studio
3. Add it to the EditView of the module
4. Go inside the EditView of the module and check that the field appears (so the cache/themes/module... folder is generated)
5. Go back to Studio and enable the "require" property of the custom field
6. Go back to the EditView and check if the field appears as required (with the red star and validation)

#### Context
-

#### Your Environment
* SuiteCRM Version used: 7.11.17
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all
* Environment name and version (e.g. MySQL, PHP 7): all
* Operating System and version (e.g Ubuntu 16.04): all

**Comment by timo-ecm2** [comment]
Hi SinergiaCRM & johnM2401 , I can confirm this issue is still there in v7.11.20 / 21. Perhaps  this issue is related #9300 .
