### ISSUE TITLE
Overall Slow Performance

### ISSUE THREAD

**Issue by mpbunch** [salesagility/SuiteCRM#9120]
#### Issue

I'm running the crm on an AWS Amazon Linux 2 t3.medium EC2 instance, with an RDS t3.medium mysql db.

The crm is super slow. 

~5 seconds for TTFB

Total load time 12.3 seconds, 1.5MB transferred in 55 requests.

Chrome lighthouse wont even return a number 80% of the time.

What do I need to do to make this less terrible?

#### Expected Behavior

To have subsecond load times, and to score a 100 on each lighthouse category (desktop, and mobile).

#### Actual Behavior

Slow, Slow

#### Possible Fix

Unsure at the moment.
I doubt it is hardware related, which makes me think it is software related.
So, I guess I will watch the slow query log to determine if the issue is DB related, or web app specific.
Also, the html markup is fairly dirty so the browser needs to do extra work to close tags.
Deferring JS would help speed up the UI.
Adding swap to each font would improve performance.
Preloading urls
If it is a php problem, I'm less sure what to suggest.

#### Steps to Reproduce

1. start an aws instance
2. load the crm
3. setup rds
4. load the crm and test its speed.

#### Your Environment

* SuiteCRM Version used: Version 7.11.18 Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 90.0.4430.93 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): php7.3 (I tried 7.4, but there are errors when importing data)
* Operating System and version (e.g Ubuntu 16.04): Linux 4.14.231-173.361.amzn2.x86_64 GNU/Linux

**Comment by chris001** [comment]
1. Looks like AWS t3.medium has only one physical CPU core.  You could try upgrading to 2 CPU cores temporarily and see what effect it has on your lighthouse score.
2. Set your PHP `memory_limit` to at least `256M`.
3. Run a `mysql` settings tuner script one time, to improve your db performance.
4. Enable scheduled pruning of the db, and enable Gzip file compression: https://community.suitecrm.com/t/guide-how-to-speed-up-your-crm-get-a-better-response-time/41293
5. Install and activate google `mod_pagespeed` in your Apache web server, and then:
6. Measure your CRM home page improved load time on Google PageSpeed Insights: https://developers.google.com/speed/pagespeed/insights/ and lighthouse.

**Comment by mpbunch** [comment]
Thanks for the quick response.
1. I will change the instance type to something with more cores.
2. I increased the memory limit to 512M
3. I will need to find a different mysql tuner script, as the one I found would not easily work with RDS.
4.a. I will enable scheduled pruning, Gzip is enabled
5. I have mod_pagespeed installed 
6. I'm still at a 5 second TTFB. (will run again once I have made the aforementioned changes)

Thanks again.

**Comment by thomas-ashcraft** [comment]
I wonder - do you have many users and/or security groups (like thousands of them)? Or maybe big tables with a hundred of thousands or millions of rows? I do and its hell. I'm digging in this right now, and seeing that issue made me thought - it would be nice if we can share some info.

**Comment by mpbunch** [comment]
@thomas-ashcraft  
My table info:
![image](https://user-images.githubusercontent.com/7864344/117546475-99156b00-aff8-11eb-86d5-bd2c477fc616.png)
```
SELECT 
    CONCAT(table_schema, '.', table_name) as 'table name',
    CONCAT(ROUND(table_rows / 1000000, 3), 'M') as 'rows',
    CONCAT(ROUND(data_length / ( 1024 * 1024 * 1024 ), 3), 'G') as 'data',
    CONCAT(ROUND(index_length / ( 1024 * 1024 * 1024 ), 3), 'G') as 'idx',
    CONCAT(ROUND(( data_length + index_length ) / ( 1024 * 1024 * 1024 ), 3), 'G') as 'total_size',
    ROUND(index_length / data_length, 3) as 'idxfrac'
FROM
	information_schema.TABLES
WHERE
	table_schema = '< table-schema >'
ORDER  BY
	data_length + index_length DESC
LIMIT  10;

Nothing seems to be ridiculously sized. I don't have many security groups, I don't have many users. I do have ~400k contacts, and ~40k accounts.

I think enabling slow query logs might point you in the right direction as to which components/tables/queries are taking up the most time to execute.

**Comment by chris001** [comment]
Is your DB storage on Amazon HDD or SSD?  Try moving to SSD if not already.
The absolute fastest would be to add RAM and tune MySQL to keep all of your data in RAM.
https://dba.stackexchange.com/questions/5666/possible-to-make-mysql-use-more-than-one-core
