### ISSUE TITLE
Changing columns while using Quick Filter changes search back to Advanced Filter

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#9137]
#### Issue

On any list/search view of a module, if you run a search using the Quick Filter and then modify the columns, the search will revert back to Advanced Filter and clear your search.

#### Expected Behavior

If you modify the columns in a search, the previous search and search type (quick, advanced) should be kept

#### Actual Behavior

Quick search filters are being cleared and search is revered back to the advanced search filter

#### Possible Fix

1. This is an issue in `include/ListView/ListViewColumnsFilterDialog.tpl`
    -  https://github.com/salesagility/SuiteCRM/blob/9cb957e4f41562eb44f6ce8c982e2a3c169fc951/include/ListView/ListViewColumnsFilterDialog.tpl#L93
3. The line `                        var url = 'index.php?module=' + module_sugar_grp1 + '&action=index&search_form_only=true&to_pdf=true&search_form_view=advanced_search&columnsFilter=true';` has the advanced search hard coded in the URL
4. This can be modified to dynamically find which search the user is in
```
var searchFormTab = $('#search_form input[name="searchFormTab"]').val();
var url = 'index.php?module=' + module_sugar_grp1 + '&action=index&search_form_only=true&to_pdf=true&search_form_view=' + searchFormTab + '&columnsFilter=true';
```

#### Steps to Reproduce

1. Navigate to a search page: https://demo.suiteondemand.com/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DAccounts%26action%3Dindex
2. Use the quick filter to run a search
3. After running the search modify the columns (add one, remove one, etc)
4. The search will be cleared and you will get new search results. When you open the search form again, it will be switched back to advanced search

#### Your Environment

* SuiteCRM Version used: 7.10.24
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by wiatrp** [comment]
I just realized I already made one of these https://github.com/salesagility/SuiteCRM/issues/7360.

Sorry for the unnecessary clutter, this one can be closed.

**Comment by johnM2401** [comment]
Hey, 
Thanks for clarifying that, closing this one now.
