### ISSUE TITLE
Reports fails to show pagination when filtering by Date range

### ISSUE THREAD

**Issue by StevenCuasqui** [salesagility/SuiteCRM#9138]
#### Issue
In SuiteCRM v7.11.18, all reports are unable to show their different pages when using two Date fields as parameters. This happens when the report is bigger than one page. Users can only see the records from the first page. The report fails to show the rest of the pages when you navigate away from the first page either by clicking the “next” or “end” pagination buttons.

#### Expected Behavior
When you generate a report with more than one page, you should be able to click on the "Next" button and continue seeing the report's records for the rest of the pages.

#### Actual Behavior
When you click on the "Next" pagination button then the report shows no records and no other pages even though the report had several pages. This also happens when clicking the "End" pagination button.

#### Steps to Reproduce
You can watch the bug at this link: [Suite CRM Bug](https://youtu.be/cYEHVgZQCLE)

1. Log in to SuiteCRM with any user.
2. Create a Report. Make sure the report has a Date field.
3. In the Conditions tab, add a Date field with a "Greater Than or Equal To" Operator. Be sure to check the Parameter box.
4. In the Conditions tab, add another Date field with a "Lesser Than or Equal To" Operator. Be sure to check the Parameter box.
5. Save the Report.
6. In the created Report, pick a start date for the "Greater Than or Equal To" parameter. Pick an end date for the "Lesser Than or Equal To" parameter.
7. Be sure the Date range generates enough rows on the report in order to get more than one page.
8. Click on the "Next" or "End" pagination buttons.
9. Report fails to show the records.

#### Context
This issue affects directly Management/H.R. teams and makes them unable to get a report filtered by a Date range. It should be considered a high-priority issue.

#### Your Environment
- SuiteCRM Version used: 7.11.18. Also in the Demo version of SuiteCRM with 7.11.19.
- Browser name and version: Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- Environment name and version: MariaDB 3.3.0, PHP 7
- Operating System and version: Linux Debian 9.12.0 (Stretch64). Nginx 1.18.0.

**Comment by pgorod** [comment]
Is this the same as https://github.com/salesagility/SuiteCRM/issues/8182 ?

**Comment by StevenCuasqui** [comment]
It is not the same but may be related. While in #8182 the pagination still works but shows all records (with filters ignored), here the report shows no records after trying the pagination.

**Comment by StevenCuasqui** [comment]
Actually, this issue is solved in the latest version of SuiteCRM 7.11.19 and the solution is shown in this commit [5c9e870](https://github.com/salesagility/SuiteCRM/commit/5c9e8700baa9e203bf75b94f5c8d908116b62286).
