### ISSUE TITLE
Targets and Target Lists missing in modules in my install directory

### ISSUE THREAD

**Issue by dan286608** [salesagility/SuiteCRM#9154]
#### Issue
I am going through each module within SuiteCRM and adjusting each modules editviewdefs.php and detailviews.php to have a 4-column layout as opposed to two. I was able to adjust every other module accordingly except for the Targets and Target Lists because those directories seem to not exist.

#### Expected Behavior

When I navigate to C:\SuiteCRm\modules I would expect to see a folder for the Targets and Target Lists modules as I see every other module listed in here.

#### Actual Behavior

When I navigate to the said directory I do not see the Targets or Target Lists modules.

#### Your Environment
SuiteCRM Version used: 7.11.18
Browser name and version: Chrome version 90.0.4430.212 (Official Build)(64-bit)
Environment name and version: Microsoft SQL Server, PHP 7.3.26
Operating System and version: Windows Server 2019 build 17763

**Comment by mattlorimer** [comment]
The name of the folders are prospects and prospectlists. The display name is not necessary the name in the underlying code or folder structure.
