### ISSUE TITLE
Importing previously exported module results yields errors due to quotes

### ISSUE THREAD

**Issue by sweettbug3** [salesagility/SuiteCRM#9165]
#### Issue
When Importing files that I have exported from other instances of Suitecrm, I cannot import due to quotes in the csv.  

Workaround: If I open up the exported csv in excel and then export it without quotes this issue goes away, but if Suitecrm is going to export with double quotes around the fields, it should be able to import with double quotes.

#### Expected Behavior
Should be able to import previously exported contents from a module.

#### Actual Behavior
Suitecrm fails on ID exceeding size:
`Error ID given is too long to fit in the field (maximum length is 36 characters)`
Suitecrm fails on email address when importing module with email address exceeding size:
```
Error Invalid Email address
Field Name Email Address: (email1)
Value ""
```

#### Possible Fix

```
--- modules/Import/Importer.php.orig	2021-04-28 15:30:19.000000000 -0600
+++ modules/Import/Importer.php	2021-06-02 12:17:43.000000000 -0600
@@ -169,6 +169,8 @@
             if (isset($row[$fieldNum])) {
                 // issue #6442 - translateCharset was already executed in an earlier step
                 $rowValue = strip_tags(trim($row[$fieldNum]));
+                // Suitecrm issue #9165 - bulk action export includes quotes, import should ignore them
+                $rowValue = preg_replace('~^[\'"]?(.*?)[\'"]?$~', '$1', $rowValue);
             } elseif (isset($this->sugarToExternalSourceFieldMap[$field]) && isset($row[$this->sugarToExternalSourceFieldMap[$field]])) {
                 $rowValue = $locale->translateCharset(strip_tags(trim($row[$this->sugarToExternalSourceFieldMap[$field]])), $this->importSource->importlocale_charset, $sugar_config['default_charset']);
             } else {


```
#### Steps to Reproduce
1. Go to the Accounts Module
2. Select a few rows
3. Bulk Action->export
4. Go to another instance of Suitecrm 
5. import the file just exported

#### Context
This is somewhere between an annoyance and important bug to fix.

It might not be obvious to users that they need to remove the quotes or open the exported module up and re-export it to import the rows.

Priority is medium.

#### Your Environment
* SuiteCRM Version used: docker.io/bitnami/suitecrm:7.11.19
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 90.0.4430.212 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): MacOS Catalina 10.15.7

**Comment by johnM2401** [comment]
Hey, 

I believe there *were* some issues with Importing/CSVs in 7.11.19

I've given this a try in 7.11.20 and cannot seem to replicate, using your Steps, I am able to import the CSV in 7.11.20.

Would you be able to take a look at the most recent version, and let us know if you are still able to replicate this issue?

Thanks for raising!

**Comment by sweettbug3** [comment]
I did test this in 7.11.20 today and it is not an issue anymore, I will remove my patch, and  you can close this.

-Teresa Gordon

**Comment by johnM2401** [comment]
Hey, 
Thank you for confirming!
I have closed this off now.
