### ISSUE TITLE
Notifications do not pop up. 

### ISSUE THREAD

**Issue by Nurasyl-Absamat** [salesagility/SuiteCRM#9167]
I enabled notifications in the advanced tab but it still doesn't show up. 

Notifications are showing but the problem is they don't pop up on the desktop

#### Possible Fix

Enable chrome to send notifications from your windows.

#### Steps to Reproduce

1. Notifications
2. Manage Notifications
3. Find Google Chrome from *Get notifications from these senders* list
4. Toggle to ON

**Comment by Mac-Rae** [comment]
Closing due to no response, please reopen if you still require assistance!
