### ISSUE TITLE
How to do data verification and prompt the user before the server saves the database?

### ISSUE THREAD

**Issue by 296721605** [salesagility/SuiteCRM#9173]
#### Expected Behavior

# **like this ：**
![1623142870(1)](https://user-images.githubusercontent.com/9688306/121156609-6bcc0f00-c87b-11eb-95f5-89737abbf1de.jpg)

**Comment by johnM2401** [comment]
Hey there, 

Are you looking for assistance on adding custom validation?

I've had a quick look, and hopefully some of these links can come in handy?:
https://community.suitecrm.com/t/form-validation-before-save/51157/
https://community.suitecrm.com/t/field-validation/78988/
https://community.suitecrm.com/t/how-set-assigned-to-user-into-no-value-by-default-when-creating-a-meeting/29208/

However, if you need further info, you might reach a larger audience via the Forums:
https://community.suitecrm.com


<br>

Although, If i've misunderstood, and this is indeed an issue, please let me know!
Thanks!
