### ISSUE TITLE
Can't use edit inline in UserType field in Users module

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9177]
We can't use inline edit in the field User Type of Users module. After editing from Regular User to Administrator, it appears this:
![Selection_192](https://user-images.githubusercontent.com/61022311/121337490-e0a35580-c91c-11eb-91e2-64f955aa427a.png)
After reloading the page, it appears again Regular User.

#### Issue
The field UserType in the Users module can't be edited inline

#### Expected Behavior
The inline edit should work in all fields

#### Actual Behavior
After editing inline, it appears some code in the field. After reloading, it appears the previous value.

#### Possible Fix
Didn't research yet

#### Steps to Reproduce
1. Go to a record in the Users module
2. Try changing the value of the UserType from the DetailView using the inline edit.
3.
4.

#### Context
The Users can't edit that field directly from the Inline edit.

#### Your Environment
- SuiteCRM 7.11.18
- Chrome Version 90.0.4430.93 (Build oficial) (64 bits)
- MariaDB, PHP 7, Apache
- Windows 10

**Comment by pgorod** [comment]
From a quick search, it's coming from here:

https://github.com/salesagility/SuiteCRM/blob/master/modules/Users/User.php#L1484

Having that **echo** there is a bug, it should be removed. But I am not sure why the actual change isn't happening, can you understand the logic around that line?
