### ISSUE TITLE
Change navbar color

### ISSUE THREAD

**Issue by zackzulg** [salesagility/SuiteCRM#918]
Hi everyone, 
I want to change the color of navbar, so I added background-color:#ff0000 into bootstrap file: .container-fluid{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;background-color:#ff0000;}
When I refresh my page the color still blue instead of red :(

**Comment by willrennie** [comment]
You can change the theme colours within the application within Admin -> Themes -> SuiteR.

**Comment by zackzulg** [comment]
Hey willrennie,
It gives me only two themes, I want to personalize my theme 
![suitetheme](https://cloud.githubusercontent.com/assets/11558642/12849333/16c83f12-cc17-11e5-9950-a0342c8b1112.png)

**Comment by zackzulg** [comment]
Actually I had link on Suite R, I had to check it and configure my theme :) thanx for help.

**Comment by willrennie** [comment]
So does your theme now appear, and you can edit the colours?

**Comment by zackzulg** [comment]
Yes, Thank you for help willrennie.
