### ISSUE TITLE
AOR_Reports chart's wrong labeling when format options

### ISSUE THREAD

**Issue by macala** [salesagility/SuiteCRM#919]
The date format options are not used for axis label. The chart use allways not formated data.

For example if the date type field is formated like "Y-m" the report result in grid displays the correct format  Year-Mounth (2015-02, 2015-04, 2016-07. etc). The chart on the same report displays additionally the days, hours and minutes value (2015-02-11 01:00, 2015-04-09 02:00, 2016-07-21 02:00. etc).

![report_1](https://cloud.githubusercontent.com/assets/15381196/12849639/00c61d56-cc21-11e5-9b47-24c924fe6959.png)
![report_2](https://cloud.githubusercontent.com/assets/15381196/12849640/0371f20a-cc21-11e5-8fb5-6642e0fa2746.png)
![report_3](https://cloud.githubusercontent.com/assets/15381196/12849645/0b156eec-cc21-11e5-9966-f4fcac8b5696.png)
![report_4](https://cloud.githubusercontent.com/assets/15381196/12849648/0fe88e68-cc21-11e5-9f80-3388253e71c5.png)

**Comment by JimMackin** [comment]
In 7.5.2
