### ISSUE TITLE
Notification emails - duplicate notification emails being sent.

### ISSUE THREAD

**Issue by gaspare-joubert** [salesagility/SuiteCRM#9203]
### Issue
Duplicate notification emails being sent. When changing the assigned to user and the module has a workflow with a Calculate Fields action with a formula and the workflow Repeated Runs option is selected.

### Expected Behaviour
One notification email sent.   

### Actual Behaviour
Two notification emails sent.  

### Possible Fix
in `data/SugarBean.php`
Add additional flag to set to true when the notification email has been sent.
Add additional check before sending the notification email.

### Steps to Reproduce
Once Scheduler has been setup to process workflow tasks:
1. Create a workflow for a module.
2. Select "Repeated Runs" in the workflow.
3. Add a "Calculate Fields" action to the workflow.
4. Add a formula parameter to the "Calculate Fields" action of the workflow.
5. Go to Detail View of a record of the module used in the workflow.
6. Change the "Assigned To" field to a different user.
7. Check notification emails sent to the new assigned user.

### Context
Want to avoid duplicate notification emails being sent to assigned user.

### Your Environment
* SuiteCRM Version used: 7.10.29
* Browser name and version: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
* Environment name and version: PHP7.2
* Operating System and version: Ubuntu 18.04.5 LTS

**Comment by tsmgeek** [comment]
Problem with this is that some users have custom hooks that may do multiple saves and internal steps, this change could interfere with audit records being created.

It would be best in your workflow to only fire off only when specific fields are changed or (im not sure if it can be done) not fire off if certain fields are changed.
ie track if `any change` is done on the fields that you are calculating

**Comment by tsmgeek** [comment]
Cross link to other ticket with similar change but against audit logs.
https://github.com/salesagility/SuiteCRM/issues/9205
