### ISSUE TITLE
Workflows sending an extra email notification

### ISSUE THREAD

**Issue by dan286608** [salesagility/SuiteCRM#9225]
3 emails are being sent in a scenario when only two should be sent.

#### Issue

I have a total of 4 workflows setup to send out email notifications. (Case update, Acct change, Acct update, and Case change).
In my company Cases are ran by IT and Accounts are ran by Sales.

Case Email Workflows-
Case update: When an IT person makes a change to the Case Updates field, the workflow sends a Case Email to the Assigned To user of the Case (IT). It then modifies a custom Date Time field to the current date and time on the Account that the Case is associated with.
Acct change: This workflow runs when the Date Time field of the Account has any change and sends out the same Case Email but to the Assigned To user of the Account (Sales).

Acct Email Workflows-
Acct update: When an Sales person makes a change to a custom Important Updates field, the workflow sends an Acct Email to the Assigned To user of the Account (Sales). It then modifies a custom Date Time field to the current date and time on the Case that the Account is associated with.
Case change: This workflow runs when the Date Time field of the Case has any change and sends out the same Acct Email but to the Assigned To user of the Case (IT).

#### Expected Behavior
Whenever an IT person updates the Case Updates field in a Case, the owner of the Case and the Owner of the Account the Case is related to get a Case Email stating there were changes made. (1 email to IT and 1 to Sales; Both the Case Email)

Whenever a Sales person updates the Important Notes field in an Account, the owner of the Account and the Owner of the Case the Account is related to get an Acct Email stating there were changes made. (1 email to Sales and 1 to IT; Both the Acct Email)

#### Actual Behavior
When and IT person updates the Case Updates field, a Case Email is sent to both IT and Sales, but an extra Acct Email gets sent to Sales as well, even though Acct Email workflows never get ran in this scenario.

When a Sales person updates the Important Updates field, an Acct Email gets sent to both IT and Sales and no extra email is sent. (Correct Behavior)

#### Possible Fix
I'm not sure exactly how or where, but from what I have found in my testing it seems that in the first Actual Behavior scenario above, Case Update workflow runs fine and so does the Acct Change workflow. It seems as if the Acct Update workflow runs (when its not supposed to) but only runs the Send Email function and doesn't go and modify the Date Time field in the Cases Module.

#### Steps to Reproduce
I have attached screenshots of my 4 workflows to this post. 
![CaseChange](https://user-images.githubusercontent.com/75691487/124159390-1beefb00-da69-11eb-8b1d-8797cb8b8b45.PNG)

![AcctChange](https://user-images.githubusercontent.com/75691487/124159391-1c879180-da69-11eb-930f-e04bbf45aa5f.PNG)

![CaseUpdate](https://user-images.githubusercontent.com/75691487/124159393-1c879180-da69-11eb-9a48-48a5233bb4e6.PNG)

![AcctUpdate](https://user-images.githubusercontent.com/75691487/124159396-1d202800-da69-11eb-99e7-20e60d739cec.PNG)

#### Context

I am trying to utilize SuiteCRM so we can have a better understanding as IT members where Sales stands with a company and so Sales can have a better understanding of the IT work we are doing for the company.

#### Your Environment

SuiteCRM Version used: 7.11.18
Browser name and version: Chrome version 90.0.4430.212 (Official Build)(64-bit)
Environment name and version: Microsoft SQL Server, PHP 7.3.26
Operating System and version: Windows Server 2019 build 17763

**Comment by pgorod** [comment]
Why are using "Always/All records" workflows for this?

https://docs.suitecrm.com/user/advanced-modules/workflow/#_creating_a_workflow_process

Further details here
https://pgorod.github.io/SuiteCRM-Workflows-Tutorial/

Use "On save/Modified records", and drop the "Any change" condition. This will make the workload thousands of times smaller (if you have thousands of records) and much less likely to get erratic behaviors.

**Comment by johnM2401** [comment]
Hey @dan286608 

Thanks for all that info!

It's hard to tell how it may be behaving from screenshots, but it does sound like the "Account Update Sends Email to Sales" workflow is being fired incorrectly.

Is this right?
You can check by viewing the "Process Audit" subpanel on the Workflow Record, after you believe it has fired under the wrong circumstance.

<br>

If this is wrongly firing, I agree with pgorod, I think it would be worth using "Only on Save" for some of these
![image](https://user-images.githubusercontent.com/13675281/124268105-fdeccd80-db30-11eb-911e-3605f523c245.png)

<br>

However, I'd personally suggest trying it on just the "Case Update Sends Email to IT" and "Account Update Sends Email to Sales" Workflows, and keeping the "Any Change" parameters.

If my thinking is correct, this should (hopefully) prevent the "Account Update Sends Email to Sales" workflow from firing unless a user directly updates the Accounts->"Important Notes" field

While also preventing the Workflow(s) from firing on every single save of the Account/Case record, even if the two fields haven't been modified.

<br>

Let us know how you get on!

**Comment by dan286608** [comment]
> Why are using "Always/All records" workflows for this?
> 
> https://docs.suitecrm.com/user/advanced-modules/workflow/#_creating_a_workflow_process
> 
> Further details here
> https://pgorod.github.io/SuiteCRM-Workflows-Tutorial/
> 
> Use "On save/Modified records", and drop the "Any change" condition. This will make the workload thousands of times smaller (if you have thousands of records) and much less likely to get erratic behaviors.


> Hey @dan286608
> 
> Thanks for all that info!
> 
> It's hard to tell how it may be behaving from screenshots, but it does sound like the "Account Update Sends Email to Sales" workflow is being fired incorrectly.
> 
> Is this right?
> You can check by viewing the "Process Audit" subpanel on the Workflow Record, after you believe it has fired under the wrong circumstance.
> 
> 
> If this is wrongly firing, I agree with pgorod, I think it would be worth using "Only on Save" for some of these
> ![image](https://user-images.githubusercontent.com/13675281/124268105-fdeccd80-db30-11eb-911e-3605f523c245.png)
> 
> 
> However, I'd personally suggest trying it on just the "Case Update Sends Email to IT" and "Account Update Sends Email to Sales" Workflows, and keeping the "Any Change" parameters.
> 
> If my thinking is correct, this should (hopefully) prevent the "Account Update Sends Email to Sales" workflow from firing unless a user directly updates the Accounts->"Important Notes" field
> 
> While also preventing the Workflow(s) from firing on every single save of the Account/Case record, even if the two fields haven't been modified.
> 
> 
> Let us know how you get on!

Thanks @pgorod and @johnM2401 for your help. I applied the suggestions to set Run: to Only on Save and Run On: to Modified records for the "Case Update Sends Email to IT" and "Account Update Sends Email to Sales" workflows. Doing so caused another issue. It used to be when and IT person updates the Case Updates field, a Case Email is sent to both IT and Sales, but an extra Acct Email gets sent to Sales as well. After the changes, Sales still gets and extra Acct Email when IT updates the custom Case field, but now IT is also getting an extra Case Email whenever Sales updates the custom Account field.

@johnM2401 To answer you question the "Process Audit" is saying the workflows are running even though they are not supposed to. That would explain the extra email being sent but regardless the workflow that sends the extra email shouldn't be running based on the conditions I have set.

@pgorod I am a little confused about what you mean by "dropping the any change condition." If I get rid of that condition how will the workflow run if its not told to run off anything? Or did you mean to change the "any change" condition to something else? I would appreciate it if you could clarify that a little bit more.

Thanks again to you both for putting your input into my issue @pgorod @johnM2401 !

**Comment by pgorod** [comment]
What are your "fakeDateLinkA" and "fakeDateLinkB" fields?

**Comment by dan286608** [comment]
> What are your "fakeDateLinkA" and "fakeDateLinkB" fields?

@pgorod the "fakeDateLinkA" and "fakeDateLinkB" fields are DateTime fields that are hidden from the detail view. I use them as a "Link" between modules so my workflows know when information has been updated in another module.

**Comment by pgorod** [comment]
Ok. Forget what I said about "drop the any change condition", I see now why that needs to be there.

I wonder what could be causing this double-firing of save events: do you happen to have any logic hooks in place?

**Comment by dan286608** [comment]
@pgorod I don't have any logic hooks in place. Most of my SuiteCRM instance is default and I haven't made many customizations other than some work in studio and the only code changes I have made have been to the detailviewdefs and editviewdefs pages for every module to make a site-wide 4 column layout. Is there any sort of log file for workflows that may shed some light on why my workflows may be double-firing?

**Comment by pgorod** [comment]
The normal `suitecrm.log` will have a ton of info (probably too much, but it's there).

It's probably some side-effect from the original action that is causing a second action, a second record that gets saved, triggering another workflow. This side-effect can come from your own code or workflows, or it can come from some bit of core code (sometimes modules are connected in non-obvious ways).

If I was in your place I would just use PhpStorm to debug the entire flow, go through everything. If that's not an easy option for you, you might try using logic hooks instead of workflows; then it's easier to do your own logging, or if needed, to extract full stack traces that will show you from where the hook is being called.

**Comment by dan286608** [comment]
@pgorod Thanks for the advice! I think I'm going to look into using logic hooks instead of workflows.

I would also like to add some more weird behavior with my workflows. This morning when I tested them they worked just fine on the first run of each. From the second run and on however I get the extra email.

**Comment by dan286608** [comment]
I am trying to set up a Logic Hook example I found in the Sugar Developer Guide 6.5 found here: https://support.sugarcrm.com/files/317538cc-6bff-11e7-916c-067914c4cb97.pdf (Page 200 of the guide). My suiteCRM instance is running Sugar version 6.5.25 so I figured this guide would work best for me. Like the example, I added the Array to logic_hooks.php in custom/modules/Accounts and created a new php file Accounts_Save.php in the same directory. On the last step of the example it says to create a new file in the custom/Extension/modules/Schedulers/Ext/ScheduledTasks directory, but that directory does not exist for me. I can get to custom/Extension/modules but that's as far as I can go. Does that directory exist anymore or should I be looking at a newer guide?

**Comment by mattlorimer** [comment]
This directory does not exist by default, so you just need to create the directories yourself to use it. This directory would only exist already if there was a previous extension to scheduled tasks.

**Comment by dan286608** [comment]
@mattlorimer Thank you, creating the directories worked. I will dive more into the logic hook once I am back at work.

**Comment by pgorod** [comment]
BTW, I believe this sort of discussion is better suited to the Forums, and I promise to help you out there.

I am not (yet) convinced this is a bug, and anyway this learning and troubleshooting is best done there. We can always come back here when we finally understand what is happening "under the hood".
