### ISSUE TITLE
SuiteCRM throwing 502 bad gateway

### ISSUE THREAD

**Issue by adityasingh699** [salesagility/SuiteCRM#9243]
Both  prod (http://suitecrm.vahan.co/) and stage instances of suiteCRM (https://stg.suitecrm.vahan.co/) are throwing 502 bad gateway error . 

#### Issue
Both  prod (http://suitecrm.vahan.co/) and stage instances of suiteCRM (https://stg.suitecrm.vahan.co/) are throwing 502 bad gateway error . We have tried hard rebooting , but the issue still persist . Following network call is failing :
Request URL: https://suitecrm.vahan.co/
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 65.2.34.18:443
Referrer Policy: strict-origin-when-cross-origin

#### Expected Behavior
https://suitecrm.vahan.co/ should pass with 200 status and home page should open up.

#### Actual Behavior
https://suitecrm.vahan.co/ throwing 502 Bad gateway error .

#### Possible Fix
Suspecting suiteCRM servers are down . Getting them up might help resolve

#### Steps to Reproduce

1.Hit url  - https://suitecrm.vahan.co/ . It given 502 bad gateway error.

#### Context
This has blocked all our operations. 
Priority : High

#### Your Environment

* SuiteCRM Version used: SuiteCRM Version used: 7.11.15

**Comment by mattlorimer** [comment]
this is nit relevant to the core project, you may have posted this in the wrong place

**Comment by adityasingh699** [comment]
Can you suggest the correct place ?.I have searched everywhere , couldn't find any other relevant place to post this.

**Comment by mattlorimer** [comment]
if you are looking for help from the community in regard to you issue -  I would suggest the community forum https://community.suitecrm.com/, maybe a better place.

or if you looking for dedicated support, you can see what options are available of the SuiteCRM website -https://suitecrm.com/enterprise/support-plans/
