### ISSUE TITLE
Popup help texts are not displayed when editing a field in Studio

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9256]
#### Issue
Help pop-up messages  for the _Importable_ and _Duplicate Merge_ properties are not displayed when crating/editing a field in Studio. The same occurs for _Width_ and _Height_ properties in _Image_ fields.

#### Expected Behavior
In Studio help pop-up messages should display.

#### Actual Behavior
Help pop-up messages do not display.

#### Possible Fix
Add these labels in modules/ModuleBuilder/language/en_us.lang.php file.
* LBL_POPHELP_DUPLICATE_MERGE
* LBL_POPHELP_IMPORTABLE
* LBL_POPHELP_IMAGE_WIDTH
* LBL_POPHELP_IMAGE_HEIGHT

#### Steps to Reproduce
1. Go to Studio.
2. Enter any module
3. Create or edit a field.
4. Verify that help information is not displayed by clicking the information icon in the _Importable_ and _Duplicate Merge_ properties.
5. Create or edit an image type field and check that the help text for the Height and Width properties is not displayed.

#### Your Environment

* SuiteCRM Version used: Version 7.11.19 - Sugar Version 6.5.25 (Build 344)
* Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Ubuntu 18.04

**Comment by craigpanton** [comment]
Closing as this issue was fixed as per https://github.com/salesagility/SuiteCRM/pull/9521
