### ISSUE TITLE
Primary Email property is lost after adding an Email address field

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9271]
Primary Email property is lost after adding an Email address field.

#### Issue
If you have a Contact with an Email address marked as Primary email, after adding the second or third email, the property of Primary Email is lost, and it needs to be selected again manually

#### Expected Behavior
The Primary email property should be maintained, even if added more emails.

#### Actual Behavior
The Primary Email property is lost and it needs to be set manually

#### Possible Fix
Modify jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js
Adding 288-317:
```
// Primary checkbox

      /**/ SinergiaCRM- When a new radio button is added dinamically in the HTML, all buttons with same name are unchecked
      // Retriving current primary value, if any
      var primaryPreviousValue = $("input[name='"+ _eaw.module + "0emailAddressPrimaryFlag']:checked").val();
      // END SinergiaCRM**

      var primaryCheckbox = lineContainer.find('input#email-address-primary-flag');
      primaryCheckbox.attr('name', _eaw.module + '0emailAddressPrimaryFlag');
      primaryCheckbox.attr('id', this.module + _eaw.id + 'emailAddressPrimaryFlag');
      primaryCheckbox.attr('value', this.module + _eaw.id + 'emailAddress');
      primaryCheckbox.attr('tabindex', tabIndexCount);
      primaryCheckbox.attr('enabled', "true");
      primaryCheckbox.attr("checked", (primaryFlag == '1'));

      if (_eaw.totalEmailAddresses == 0 && primaryFlag != '1') {
        primaryCheckbox.prop("checked", true);
      }


      // Prevent users from removing their primary email address
      if (this.module == 'Users' &&  primaryCheckbox.attr("checked")) {
        removeButton.prop('disabled', true);
      }

      **// SinergiaCRM - Checking the original radio button for the primary email flag
      if (!primaryFlag && primaryPreviousValue) {
        $('input[value="'+primaryPreviousValue+'"].email-address-primary-flag').prop("checked", true);
      }
      // END SinergiaCRM**
```

#### Steps to Reproduce
1. Create a record in Contacts module with an Email address set as Primary
2. Add a second email
3. Check that the primary property has been lost
4.

#### Context
The Primary Email shouldn't be lost.

#### Your Environment

    SuiteCRM Version used: Version 7.11.21
    Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
    Environment name and version: MySQL, PHP 7
    Operating System and version: Ubuntu 18.04

**Comment by fcorluka** [comment]
This is active issue for some time, I have dealt with it for over a 2 years. Additional problem is database.
Lets say we have 1 email address (EA) in contacts and it is marked as primary. When second is added, primary marker is removed and needs to be set again. In databes (email_addresses) there are 3 records:
- deleted original EA
- added again original EA
- added new EA

This is wrong 10000%. I have over 30.000 email addresses and editing them means X10 or X100 records more.

**Comment by vaudoin** [comment]
If your database is corrupted: for instance some Contacts with several email addresses don't have any primary_adress set.
Here is a SQL request that can set the first email address to primary_adress:
```
UPDATE email_addr_bean_rel c SET primary_address = '1' WHERE c.email_address_id IN 
(SELECT d.email_address_id FROM
	(SELECT a.* FROM email_addr_bean_rel a 
		 JOIN email_addr_bean_rel b 
			ON a.bean_id = b.bean_id AND a.bean_module = b.bean_module AND a.email_address_id <> b.email_address_id AND a.primary_address = b.primary_address
	WHERE a.primary_address = 0 AND a.bean_module = 'Contacts'
	GROUP BY bean_id,  bean_module, primary_address
	HAVING COUNT(*) <= 2
	ORDER BY bean_id) d
) 
```
There might be a simpliest way to do it but this one works. 
And Indeed if you need to do the same for other modules, just replace 'Contacts' by the module name (for instance 'Leads').
