### ISSUE TITLE
Suite R Theme - changing dashlet header color almost impossible

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#928]
There is an option to change the Dashlet Header colour on the Theme options. 

However, since we can only change the background colour, it is very hard to get the text of the dashlet title to look right. It is always blue, like the rest of the links in SuiteCRM, so if I try to use a darker background there, I stop seeing the text (e.g. "My Calls") properly.

The icons on the dashlet header (edit, refresh) would also need an option to change colour, for the same reason.

I don't usually mess with little aesthetic details, but giving the dashlets more contrast with the white background seems like a usability issue to me now: I notice that some new users don't interpret the dashlet areas correctly because it's all too similar (especially when projecting the image onto a wall in demonstrations).

**Comment by ghermans** [comment]
@pgorod since my latest pull request the "dashlet icons" are the same as the "icon" option in color picker.

:+1: for text dashlet header colors, I will add another option for the text color in the dashlet header

**Comment by ghermans** [comment]
@pgorod i hope this is what you had in mind.

1. I have added "Dashlet header text color" to the theme settings page.
![feature_105](https://cloud.githubusercontent.com/assets/1594411/12898535/793811ac-cead-11e5-8854-d01c631a5a92.png)

2. Below is the result after saving.
![feature_104](https://cloud.githubusercontent.com/assets/1594411/12898493/44b56ed4-cead-11e5-90d5-b6addbbf5561.png)

**Comment by pgorod** [comment]
Yep, that's it. 

Thank you very much!
