### ISSUE TITLE
Setting Recommended installation pre-requisites XML Parsing want guidance

### ISSUE THREAD

**Issue by eugeneruthven** [salesagility/SuiteCRM#9281]
for SuiteCRM 7.10.32

in Recommended installation pre-requisites there is XML Parsing.

what does this mean?

from looking at the php manual it looks like this extension is enabled by default so i don't need to do anything - right?

the extensions included in this XML Parsing extension:
SimpleXML Parser
DOM Parser
XMLParser
XMLReader

in my host's cpanel --> Software section --> Select PHP Version --> Extensions
the following extensions are already checked/enabled - how do they affect anything?
xmlreader
xmlrpc
xmlwriter

**Comment by tsmgeek** [comment]
Your cPanel must be different from mine, I have WHM/cPanel and it seems different from you, I manage all my extenisions via EasyApache module in WHM.

When you run the install script it will check if your platform has all required extensions.
