### ISSUE TITLE
what is the required PHP version for SuiteCRM 7.10.32 LTS?

### ISSUE THREAD

**Issue by eugeneruthven** [salesagility/SuiteCRM#9282]
#### Issue
i plan to use suitecrm with wordpress - i've already set the php version to 7.4 because wordpress requires it

#### Expected Behavior
to install suitecrm without encountering php issues

#### Actual Behavior
haven't tried installing SuiteCRM 7.10.32 LTS yet

#### Possible Fix
none

#### Steps to Reproduce
none

#### Your Environment
SuiteCRM 7.10.32 LTS?

**Comment by mikethetreeclimber** [comment]
"require": { "php": ">=5.6.0", ..... 
This from the composer.json

**Comment by johnM2401** [comment]
Hi @eugeneruthven 

You can find all the compatibility information here:
https://docs.suitecrm.com/admin/compatibility-matrix/

So, as of 7.10.30, PHP 7.4 should be compatible.


If you come across any issues with installing, please feel free to raise it on the [forums](https://community.suitecrm.com)
Or, if you have come across a bug, feel free to raise another ticket here

Thanks!

**Comment by samus-aran** [comment]
Hi @eugeneruthven These sort of questions are super for the forums as you would most likely find your answers there for end user questions. The github repo is the bug tracker so it may not be the best for these sort of general questions. Hope to see you on the forums soon.

Has regards to your suggestion on updating the pre-requisites documentation, that sounds reasonable. If you have suggestions then we would love to hear that.

https://community.suitecrm.com/
