### ISSUE TITLE
for the SuiteCRM Installation Pre-Requisite   "Writable SugarCRM Configuration File (config.php)" what does this mean?

### ISSUE THREAD

**Issue by eugeneruthven** [salesagility/SuiteCRM#9284]
#### Issue
i've downloaded the SuiteCRM 7.10.32 LTS zip file

I've unzipped it on my windows 10 machine

i cannot find config_override.php or config.php

an explanation would be appreciated or point me to documentation

#### Expected Behavior
see config_override.php or/and config.php

#### Actual Behavior
config_override.php or config.php not found

.

**Comment by johnM2401** [comment]
Hi, 

I believe the config.php and config_override.php files get automatically created during the initial install process, after the Database Configuration / Site Configuration stage.

So, not having a config.php file before you first install the CRM should be totally fine.

You very well may use an existing config.php file when going through other processes
(ie, Re-installation / Moving the CRM / Using the config.php from another environment)

In which case, having a "Writable SugarCRM Configuration File (config.php)" would be more applicable.


However, as long as your File/Folder permissions are set correctly, the install should go smoothly and the config.php file should be created automatically.

**Comment by eugeneruthven** [comment]
ok - i understand that process - config.php and config_override.php do not exist until after the install process is done - thx

before the SuiteCRM Installation Pre-Requisites section there are 4 permission statements:

Line 1:  sudo chown -R www-data:www-data .
Line 2:  sudo chmod -R 755 .
Line 3:  sudo chmod -R 775 cache custom modules themes data upload
Line 4:  sudo chmod 775 config_override.php 2>/dev/null

Line 3 i understand although the themes folder is not mentioned in the SuiteCRM Installation Pre-Requisites section .

Line 4 is done after the install is done and config_override.php exists.

Re: Line 1 my hosting provider says the system user is "nobody" so for me Line 4 becomes:
           sudo chown -R nobody:nobody  .
   which looks weird to me - and what does the last period mean? i had a look thru differt copies of the chown doc without finding out what the period means
  also how would i execute that command? i can set file and folder permissions using filezilla but i don't see how i would do it thru my cpanel

Line 2 is another thing i don't understand.
          i understand permissions are being changed recursively on what? the period? does the period mean suitecrm's root folder? the root folder must be writable before doing the install to allow config.php and config_override.php to be created during the install.
after the install the root folder's permissions have to be changed back?

**Comment by johnM2401** [comment]
Hi, 

For Line 1, I think "nobody:nobody" should be fine for the chown command.
"nobody" is a valid web-server user, it just depends on what the environment itself uses.


In terms of executing the command, I would typically run these chmod/chown commands through the command line.
I haven't used cPanel myself, I'm afraid, but do you have some form of SSH/CLI access to the CRM, to apply this ownership permissions change?

If not, it might be worth getting in touch with your hosting provider, to see if they are able to apply this.



Regarding the period, in this scenario, it signifies that the command will be run against the current directory.
So, these commands should be run in the root SuiteCRM directory.
This would mean that the permissions are applied to all of the SuiteCRM Files/Folders, recursively.

I believe those permission levels are what the CRM needs to function at its best, so you shouldn't need to change them back after installing.

**Comment by johnM2401** [comment]
Closing Issue for now.

Please let us know if you have any further questions, via the [community forums](https://community.suitecrm.com/).

However, if you do come across any bugs, or have any suggestions for the project, please don't hesitate to raise them here.

Thanks!
