### ISSUE TITLE
Calendar dashlet is blank on dashboard after upgrading from 7.4 to 7.5.1

### ISSUE THREAD

**Issue by vlastr** [salesagility/SuiteCRM#933]
After upgrading from 7.4 to 7.5.1 the Calendar dashlet is blank and frozen.
You have to logout and log back to display it but once you go to any other screen and go back to Home
it is blank and broken again.
Firebug produces the following error when reloading Home page:
GET http://192.168.1.173/include/javascript/jsclass_async.js 200 OK 40ms
GET http://192.168.1.173/type=%22text/javascript%22%20src=include/MySugar/javascript/**AddRemoveDashboardPages.js%22 **404 Not Found** **14ms
The file itself exists with correct 644 www-data permissions.
Since initial load of the Home page with dashlets is OK and subsequent loads produce blank calendar dashlet, I assume this is something with ajax call ?

**Comment by maxxatgit** [comment]
Greetings;
This may be the problem:
In the template file: themes/SuiteR/tpls/MySugar.tpl,
lines 155 & 156 contain references to files in the custom directory:
`<script` type="text/javascript" `src="custom/include/MySugar/javascript/AddRemoveDashboardPages.js"></script>`
`<script` type="text/javascript" `src="custom/include/MySugar/javascript/retrievePage.js"></script>`

Those files have moved from "custom/include..." to "include..."

Similarly, in the template files: themes/Suite7/tpls/Home.tpl, and themes/SuiteR/tpls/Home.tpl,
lines 73 - 77 contain references to files in the custom directory:
`<link type="text/css" href="{sugar_getjspath file='custom/include/SugarCharts/js/Jit/Examples/css/base.css'}" rel="stylesheet" />`
`<link type="text/css" href="{sugar_getjspath file='custom/include/SugarCharts/js/Jit/css/Examples/BarChart.css'}" rel="stylesheet" />`
`<!--[if IE]><script language="javascript" type="text/javascript" src="{sugar_getjspath file='custom/include/SugarCharts/js/Jit/Extras/excanvas.js'}"></script><![endif]-->`
`<!-- JIT Library File -->`
 `<script language="javascript" type="text/javascript" src="{sugar_getjspath file='custom/include/SugarCharts/js/Jit/jit.js'}"></script>`

Those files have also moved from "custom/include..." to "include..."

Look in your apache error logs for "custom/include/MySugar/javascript/AddRemoveDashboard"

**Comment by vlastr** [comment]
Will it be considered a bug and fixed in the next 7.5.x release?
We are not going to upgrade to 7.5 until it is save.

**Comment by maxxatgit** [comment]
I am a end-user. I'm sure the developers will fix it.

**Comment by mattlorimer** [comment]
resolved in 7.5.2
