### ISSUE TITLE
Can't move Subpanels in Contacts module

### ISSUE THREAD

**Issue by ballesj** [salesagility/SuiteCRM#934]
After updating to version 7.5.1 it's not possible to move the Subpanels, concerning the sequence of the subpanels.

It's possible to move the subpanels in any each other module, for example Accounts.

**Comment by adamjakab** [comment]
You are right - the PR #906  has just been merged into hotfixes branch for this 
If you need quick fix look at modified file in PR

**Comment by ijdavie** [comment]
This issue has been addressed in pull request.  #906
