### ISSUE TITLE
Cannot upgrade to 7.12 due to PHP restriction

### ISSUE THREAD

**Issue by FR-JS** [salesagility/SuiteCRM#9340]
#### Issue
The upgrade file for 7.11.x to 7.12 cannot be applied through the upgrade wizard when using PHP 7.4 since the manifest only allows PHP 7.3.x.

#### Expected Behavior
The update file should be accepted and processed.

#### Actual Behavior
After the file is uploaded in the upgrade wizard you are presented with the message:
`The uploaded file is not compatible with this version of PHP: PHP Version: 7.4.x`

#### Possible Fix
Add at least '^7.4(.*)' to the 'acceptable_php_versions' entry in the manifest file.

#### Steps to Reproduce
1. Use a 7.11.x installation of Suite
2. Upload the 7.11.x-7.12 upgrade file into the Upgrade Wizard

#### Context
Cannot upgrade to latest version without either downgrading PHP or modifying the released ZIP file.

#### Your Environment
* SuiteCRM Version used: 7.11.22
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4.25
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by SpyderZ** [comment]
I changed this file from 7.3 to 7.4, re-zipped the files and folder and it upgraded without issue on PHP 7.4.

**Comment by matteoraggi** [comment]
Yes I get the same issue with fastcomet, and downgrading php to 7.3 then I get database error: please check the log of the errors of SuiteCrm. and I found it:
```
suitecrm3454352345blablabla_11_02_21.log ( ASCII text )
Tue Nov  2 01:14:25 2021 [9240][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 2027: Malformed packet
Tue Nov  2 01:14:25 2021 [9240][-none-][FATAL] Mysqli_query failed.
Tue Nov  2 01:14:25 2021 [9240][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 2013: Lost connection to MySQL server during query
Tue Nov  2 01:15:23 2021 [10732][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 2027: Malformed packet
Tue Nov  2 01:15:23 2021 [10732][-none-][FATAL] Mysqli_query failed.
Tue Nov  2 01:15:23 2021 [10732][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 2013: Lost connection to MySQL server during query
Tue Nov  2 01:16:14 2021 [11864][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 2027: Malformed packet
Tue Nov  2 01:16:14 2021 [11864][-none-][FATAL] Mysqli_query failed.
Tue Nov  2 01:16:14 2021 [11864][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 2013: Lost connection to MySQL server during query
Tue Nov  2 01:17:04 2021 [13166][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 2027: Malformed packet
Tue Nov  2 01:17:04 2021 [13166][-none-][FATAL] Mysqli_query failed.
Tue Nov  2 01:17:04 2021 [13166][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 2013: Lost connection to MySQL server during query
Tue Nov  2 01:17:40 2021 [13824][-none-][FATAL]  Query Failed: SELECT id, name, symbol, conversion_rate FROM currencies WHERE status = 'Active' and deleted = 0: MySQL error 2027: Malformed packet
Tue Nov  2 01:17:40 2021 [13824][-none-][FATAL] Mysqli_query failed.
Tue Nov  2 01:17:40 2021 [13824][-none-][FATAL] Unable to retrieve system settings Query Failed: SELECT category, name, value FROM config: MySQL error 2013: Lost connection to MySQL server during query
```

**Comment by SpyderZ** [comment]
I had so many errors appearing in the log of various things, mostly related to inbound and outbound email that I decided to install a fresh copy and migrate over data using the export and import features. That seemed to really clean up a lot of bugs. Also, noticed the theme had some CSS additions that screw with custom themes compilation, so it's best to re-make those from scratch and do a file comparison between the color-pallet.css files of the old and new isntall to copy your customizations over.

**Comment by tsmgeek** [comment]
@Dillon-Brown Ive confirmed issue as stated, needs to be repackaged

**Comment by jack7anderson7** [comment]
Thanks to everyone who reported this. New packages have now been built to address this issue. Please find them in the upgrade section of the site.
