### ISSUE TITLE
SuiteCRM 7.12.0 issue on MYSQL 5.6

### ISSUE THREAD

**Issue by prbt2016** [salesagility/SuiteCRM#9356]
#### Issue
I was in the process of manual installation of SuiteCRM 7.12.0 on CentOS Linux release 7.6.1810 (Core) with Apache 2.2.34, PHP 7.3.27, MYSQL 5.6.46.

However after entering the database details, admin details. I get the following error i.e : 

.......................................Database error. Please check suitecrm.log for details.

Following is the screenshot of the same : 

![image](https://user-images.githubusercontent.com/17871448/141088731-329abebe-4b6c-48c9-b64c-fe769e1e5c16.png)

#### Expected Behavior

SuiteCRM installation should be successful.

#### Actual Behavior

Database error is thrown at Step2.

Following is the output of suitecrm.log : 
```

Wed Nov 10 09:26:47 2021 [22118][-none-][FATAL] Mysqli_query failed.

Wed Nov 10 09:26:47 2021 [22118][-none-][FATAL] Error creating table: fields_meta_data: Query Failed: CREATE TABLE fields_meta_data (`id` varchar(255)  NOT NULL ,`name` varchar(255)  NULL ,`vname` varchar(255)  NULL ,`comments` varchar(255)  NULL ,`help` varchar(255)  NULL ,`custom_module` varchar(255)  NULL ,`type` varchar(255)  NULL ,`len` int(11)  NULL ,`required` bool  DEFAULT '0' NULL ,`default_value` varchar(255)  NULL ,`date_modified` datetime  NULL ,`deleted` bool  DEFAULT '0' NULL ,`audited` bool  DEFAULT '0' NULL ,`massupdate` bool  DEFAULT '0' NULL ,`duplicate_merge` smallint  DEFAULT '0' NULL ,`reportable` bool  DEFAULT '1' NULL ,`importable` varchar(255)  NULL ,`ext1` varchar(255)  NULL ,`ext2` varchar(255)  NULL ,`ext3` varchar(255)  NULL ,`ext4` text  NULL  , PRIMARY KEY (id),   KEY idx_meta_id_del (id, deleted),   KEY idx_meta_cm_del (custom_module, deleted)) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: MySQL error 1071: Specified key was too long; max key length is 767 bytes
```

#### Steps to Reproduce
1. Hit the installation URL for ex : http://domain.com/suitecrm/install.php and Click Next
2. Enter database details and admin details and click Next
3. Database error is thrown

#### Your Environment
* SuiteCRM Version used: 7.12.0
* Browser name and version : Mozilla Firefox Version 94.0.1
* Environment name and version : MYSQL 5.6.46, PHP 7.3.27, Apache 2.2.34
* Operating System and version : Centos 7.6.1810 (Core)

**Comment by tsmgeek** [comment]
Can you put the message into a codeblock to make it easier to read.

Have you got any custom modules?

**Comment by tsmgeek** [comment]
I meant the code sections not whole message else images etc will not work.

**Comment by prbt2016** [comment]
Hello @tsmgeek 

Have put the code section in block.

> Have you got any custom modules?
No I don't have any custom modules.

**Comment by tsmgeek** [comment]
#9217 #7509 #7510 

https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes

was merged to 7.10 but seems never to be also merged into master for 7.12, this ticket was on a separate table but issue will persist across the board on MySQL 5.6.

**Comment by tsmgeek** [comment]
Checked that #7510 never even made it into 7.11

https://github.com/salesagility/SuiteCRM/blob/d57e91389d97791fe621d811f03fe05f8f5a7f78/modules/DynamicFields/vardefs.php#L70-L74

Problem is likely to be the `idx_meta_id_del` and `idx_meta_cm_del` indexes mixed with UTF8 database charset as its 3 bytes per character + `deleted`. Is there really any advantage to have these additional indexes as you can not have duplicate rows with the same PK anyway as that is a unique index, unless of course this is being used as a prefix index but then is that not what `custom_module` column should be for.

Across the board any compound indexes may have this same issue with 5.6.

**Comment by psatasiya** [comment]
I still have the same issue.

PHP version 7.2.
MySQL 5.6
SuiteCRM 7.12
