### ISSUE TITLE
Filter by Email1 Field Through the API

### ISSUE THREAD

**Issue by daheile** [salesagility/SuiteCRM#9378]
#### Issue

Please check the last comments of issue #8423 
This ticket is not yet fixed:
You still cannot filter Leads by ```email1``` with REST API

#### Expected Behavior

to get a HTTP response with code 200 and the lead I am looking for.

#### Actual Behavior

The http response is
```
{
    "errors": {
        "status": 400,
        "title": null,
        "detail": "Datenbank Fehler. Bitte sehen Sie in der Datei suitecrm.log nach."
    }
}
```

#### Possible Fix

See last comments of issue #8423

#### Steps to Reproduce

HTTP GET to URL https://<servername>/Api/V8/module/Leads?filter%5Bemail1%5D%5Beq%5D=hans%40wurst.de

#### Context

Filtering by email is very important if you want to get a concrete person, while filtering by name can be ambigous (there are many different Peter Smith)

#### Your Environment

* SuiteCRM Version used:  SuiteCRM 7.12.1 Release

**Comment by daheile** [comment]
Attached is the current patch I am using.
Note: I also had to change === to == in line 146
[patch9378.patch.log](https://github.com/salesagility/SuiteCRM/files/7596724/patch9378.patch.log)

**Comment by eduardo-albelo** [comment]
I had same issue:
Version 7.12.2
Sugar Version 6.5.25 (Build 344)
