### ISSUE TITLE
Send email page still blank.

### ISSUE THREAD

**Issue by zackzulg** [salesagility/SuiteCRM#938]
Hello everyone,
I want to send an email from suitecrm but when I click on Compose button I can't get email form. when I check what happen I got these errors : 

> Uncaught TypeError: Cannot set property '-1' of undefined
> sugar_grp_emails.js:949 Uncaught TypeError: Cannot read property 'LBL_LIST_DATE' of undefined
> sugar_grp_emails.js:700 Uncaught TypeError: Cannot read property 'LNK_NEW_SEND_EMAIL' of undefined

**Comment by paulgodley** [comment]
Hi there, what version of SuiteCRM are you using?  Can you try a quick repair and rebuild and see if the problem persists?

**Comment by zackzulg** [comment]
Hi Paul ,
I use SuiteCRM V7.5.1, even if I try quick repair and rebuild the problem still the same.
Actually I made some modifications on ../cache/include/javascript/sugar_groupe_emails.php, I changed mod_strings.LBL_LIST_DATE with app_strings.LBL_LIST_DATE (lign n° 949) and mod_strings.LNK_NEW_SEND_EMAIL by app_strings.LNK_NEW_SEND_EMAIL. I've got my form but when I click on compose button I got this error : Uncaught TypeError: Cannot read property 'LBL_MOVE_TO_BCC' of undefined my problem is I can't find the place where they declar this property.
Regards 
![email](https://cloud.githubusercontent.com/assets/11558642/12980994/c0591632-d0d6-11e5-91b0-fb73fd16b475.png)

**Comment by mattlorimer** [comment]
try 'Rebuild .htaccess File'

**Comment by zackzulg** [comment]
.htaccess File still blank to :(

**Comment by mattlorimer** [comment]
your .htaccess is blank? check your permission are set correctly

**Comment by zackzulg** [comment]
Hi. 
I downloaded SuiteCRM project again and I replace emails folders and It works fine now. Thank you for help guys.

**Comment by paulgodley** [comment]
Glad to hear it is now working.  @mattlorimer can you please close this call?
