### ISSUE TITLE
PHP 8 - function 'each' has been removed

### ISSUE THREAD

**Issue by peterkracik** [salesagility/SuiteCRM#9383]
#### Issue
There are two (maybe more) files that use the function `each()` which [has been removed in the PHP 8](https://www.php.net/manual/en/function.each.php)

files affected:
- `public/legacy/modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php`
- `public/legacy/modules/ModuleBuilder/views/view.relationship.php`

#### Possible Fix
1. with the package: [https://packagist.org/packages/christiaanbye/polyfill-each](https://packagist.org/packages/christiaanbye/polyfill-each)
2. by replacing the code

#### Your Environment

* SuiteCRM Version used: 8.0.0
* Environment name and version (e.g. MySQL, PHP 7): PHP 8

**Comment by tsmgeek** [comment]
I am in two minds if a polyfill should be used or just write specific code to fix issue.
https://stackoverflow.com/questions/46492621/how-can-i-update-code-that-uses-the-deprecated-each-function
