### ISSUE TITLE
Workflow not saving parameters

### ISSUE THREAD

**Issue by jorgemme7** [salesagility/SuiteCRM#9400]
#### Issue
When creating a Workflow Action that creates a new record, it doesn't save/storage the parameters.

Other version of SuiteCRM handles the new Workflow Action as expected. Version 7.13.18.

#### Expected Behavior

After creating  and saving the Workflow with Actions . The Workflow actions should show the parameters given when created.
#### Actual Behavior

The Workflow Condition and Actions can viewed and edited, but the parameters are not displayed.
Also, when running the workflow nothing happen for those actions where the parameters are not displayed.

#### Steps to Reproduce

1. Create a new Workflow
2. Add conditions 
3.Create an Action to create a new record
4. Add a date parameter to increase the Due Date + 1 week
5. Save the workflow.
6. Go back and edit the Workflow and confirm that the date parameter still shows.

#### Your Environment

* SuiteCRM Version used: 8.0.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Crhome / Safari / Firefox
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04 / and Windows

**Comment by Mac-Rae** [comment]
Hi @jorgemme7,

This issue appears to already exist, if you believe your issue to differ or include more specifics please let me know and we can reopen this issue! - https://github.com/salesagility/SuiteCRM/issues/9380

As a side note: Although this issue appears to affect 7.12 and therefore is passed into Suite8. If you believe you have found a Suite8 specific issue you should open the issue in the SuiteCRM-Core repo - https://github.com/salesagility/SuiteCRM-Core
