### ISSUE TITLE
added a way to run the app instantly?

### ISSUE THREAD

**Issue by fangdajiang** [salesagility/SuiteCRM#9403]
Hello, we are TeamCode. We have created a Tin application for this app, which help users to quickly run and try the app without installing and configuring the environment. Users don't need to pay for this service. Hope it can help you better promote the app. Thx.

[![TeamCode try-it-now](https://static01.teamcode.com/badge/demo.svg)](https://www.teamcode.com/tin/clone?applicationId=273461926832795648)
Guidance: https://www.teamcode.com/docs/en-US/tin/clone-tin

This is the entire usage process：

Users click the badge Run in Cloud (teamcode demo).
Sign up first if they have not logged in.
After that, they will be directed to the Clone page and start to build & run this app.

**Comment by pgorod** [comment]
I was trying this and I couldn't log in to SuiteCRM, what is the default user/password?

**Comment by samus-aran** [comment]
I dunno if we want this platform to officially provide this service but thank you for sharing it. Does the project gain insight on how many folk use this service?

**Comment by fangdajiang** [comment]
> I was trying this and I couldn't log in to SuiteCRM, what is the default user/password?

I am sorry for not providing them: user/bitnami

**Comment by fangdajiang** [comment]
> I dunno if we want this platform to officially provide this service but thank you for sharing it. Does the project gain insight on how many folk use this service?

I'd thought users could register by themselves, obviously I was wrong. Please use user/bitnami to log in.
