### ISSUE TITLE
Displayed text on validation error for non-required field isn't correct

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9406]
When a custom validation is added using this JS code:

```
addToValidateCallback("EditView", "phone_work", "integer", false, "Custom label", function() {
    return false;
});
```
The first part of the message, that it's an static text provided by the CRM, it's "Missing required field", like this:
![Selection_385](https://user-images.githubusercontent.com/61022311/147924466-939e41ec-55cf-4c81-84c7-6212a2526b3b.png)

That first part of the message isn't correct, instead it should appear "Invalid Value", like this:
![Selection_384](https://user-images.githubusercontent.com/61022311/147924368-ba830073-ff83-4623-850f-2a7266e9ebb7.png)

#### Issue
The text used in the field validation of non-required fields isn't correct.

#### Expected Behavior
It should appear the text "Invalid Value:" + "Custom validation text".

#### Actual Behavior
It appears a wrong static message.

#### Possible Fix
File jssource/src_files/include/javascript/sugar_3.js - Line 1101. Replace "requireText" for "invalidTxt"

#### Steps to Reproduce
1. Add the above field validation Javascript code in an EditView
2. Go to the EditView and check the validation message
3.
4.

#### Context
The message can be confusing.

#### Your Environment
SuiteCRM Version used: Version 7.12.2 - Sugar Version 6.5.25 (Build 344)
Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Assessed and confirmed :+1:
