### ISSUE TITLE
Displayed value when aborting an Email inline edit

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9412]
![EmailErrorInline](https://user-images.githubusercontent.com/61022311/148557059-3a581ade-f53b-41c3-aeb7-d8a4405c512d.gif)

#### Issue
Whenever you open the inline edit of an Email field, but instead of saving, abort it, clicking outside of the input box, a JS code is displayed.

#### Expected Behavior
The previous Email address should be displayed

#### Actual Behavior
A Javascript code is displayed, see image above

#### Possible Fix
Add "false" to the second parameter to function setValueClose() of include/InlineEditing/inlineEditing.js Line 353

#### Steps to Reproduce
1. Edit inline an Email field that has already a value
2. Do not save it, but abort the operation
3. A wrong value is displayed
4.

#### Context
This can be confusing for a user

#### Your Environment
SuiteCRM Version used: Version 7.12.2 - Sugar Version 6.5.25 (Build 344)
Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
Environment name and version: MariaDB, PHP 7.4
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Hi @SinergiaCRM,

This issue is confirmed in 7.12+

**Comment by timo-ecm2** [comment]
In Version 7.12.6 (Sugar Versie 6.5.25 (Build 344)) on Google Chrome Version 103.0.5060.134 (Officiële build) (64-bits)on W11, 
I have the situation that it is not possible to inline edit this Email field. Modifications are not saved. The value did not change.

In the previous version 7.12.3 Sugar Versie 6.5.25 (Build 344), this did not occur. Online editing is possible and changes are saved.

**Comment by SinergiaCRM** [comment]
I've just tested it in a SuiteCRM 7.12.3 installation and I could reproduce the issue.
![emailtest](https://user-images.githubusercontent.com/61022311/182386770-3270edf8-0742-457d-b025-be4ec92c2a74.gif)

Both in Ubuntu 20.04 with:
Firefox: 103.0 (64-bit)
Chrome: 103.0.5060.134 (Official Build) (64-bit)
