### ISSUE TITLE
Faker package gone rogue?

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#9415]
https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

I think we use this package.

We shouldn't be affected because we didn't create any build with the broken package, I suppose.

But I think we should note the event and perhaps consider if anything needs to be done.

Feel free to close this issue when it's not useful anymore (even if that is today 😄 )

**Comment by samus-aran** [comment]
Thanks Pedro! What an interesting discussion about the whole situation (and that's being super diplomatic)
I don't think we do use this package (or colors.js) as it is front end library and couldn't see it in the code. But we'll get the team to check and close accordingly. 

However it may be important for our SuiteCRM add-on developers to be aware of this and update accordingly if they are using it.

**Comment by samus-aran** [comment]
Confirmation is that Suite 8 uses colors as part of a package but only as a dev dependancy so not in any of the installer packages. :+1:

**Comment by pgorod** [comment]
You're right, I was sure I had seen the name "faker" but we use the PHP faker, 

https://github.com/salesagility/SuiteCRM/blob/master/composer.json#L83

not the JS one.

Still, that article is a very interesting read, it's like he's defending open source, but he sure picked a reckless way to do it... 😱 I wonder if SuiteCRM is vulnerable to this sort of package-maintainer burn outs? I guess not, because we don't release that often (and we don't bump versions _that_ automatically) so we should have time to read about these things in the news before they hurt us...
