### ISSUE TITLE
Missing strings popup help labels are missing in Studio

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9427]
At some point in the repository history some of the literals went missing. 

The labels are:
LBL_POPHELP_IMPORTABLE
LBL_POPHELP_IMAGE_WIDTH
LBL_POPHELP_IMAGE_HEIGHT
LBL_POPHELP_DUPLICATE_MERGE

And they should be here modules/ModuleBuilder/language/en_us.lang.php inside ``` //POPUP HELP ```

The last time we saw them it was here:
https://github.com/salesagility/SuiteCRM/blob/f5d0c83ec590594bbacc3f22c79cdb8fe531e6c6/modules/ModuleBuilder/language/en_us.lang.php

No idea why they are missing.

There are two more labels that we think they might not be used anymore
LBL_POPHELP_SEARCHABLE
LBL_POPHELP_GLOBAL_SEARCH

#### Issue
Some help strings are missing when editing the property of field in Studio:

![Selection_395](https://user-images.githubusercontent.com/61022311/149808278-f0385d5f-782f-4a31-be04-1563a1d11e90.png)

#### Expected Behavior
Text should appear

#### Actual Behavior
No text appear, so the user is missing information

#### Possible Fix
Add the label strings in the language file

#### Steps to Reproduce
1. Go to Studio
2. Go to any Module
3. Edit a field
4. Check that the Info points available aren't working

#### Context
This should work

#### Your Environment
SuiteCRM Version used: Version 7.12.2 - Sugar Version 6.5.25 (Build 344)
Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
Environment name and version: MariaDB, PHP 7.4
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Hi @SinergiaCRM,

Confirmed in 7.12.x
