### ISSUE TITLE
Workflow: Dropdown always returns default value when empty item is selected

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9435]
The editview of a workflow is built using a Smarty template. When editing an existing workflow with an action that sets to blank an enum field which has a not blank default value, the template does not show the blank value (as expected) but the default value. 

See image bellow:

![WF_defaultValueDropdown](https://user-images.githubusercontent.com/61022311/150200488-eecbcb55-71e4-429e-809d-4eba7ae79b55.gif)

#### Issue
After opening a saved workflow that contains a condition using a dropdown with the empty item selected, the dropdown field always displays the default value if the default value isn't empty.

#### Expected Behavior
The empty ítem should be displayed when the saved workflow record is loaded

#### Actual Behavior
The workflow actually runs well, using the condition "empty" for the dropdown, but the displaying in the EditView is wrong.

#### Possible Fix
Forcing the value " ' ' " into the vardef definition. Some changes in modules/AOW_WorkFlow/aow_utils.php

#### Steps to Reproduce
1. Set any item as a default value for the dropdown Category in Documents
2. Create a Workflow based in Documents
3. Add condition of the field Category selecting the empty value
4. Save and open the workflow, check that the value displayed in the condition is the default and not the empty one.

#### Context
This can be very confusing for users

#### Your Environment
SuiteCRM Version used: Version 7.12.2
Browser name and version: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Assessed :+1:
