### ISSUE TITLE
Saving "0" value in numeric fields when it's empty

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9440]
In a new module (from the ModuleBuilder) that contains a non-required non-custom/core numeric field (integer or float). If the record is saved without filling that field, the field will display and contain (in DB) a "0" value.

After, if you edit the record, remove the 0 and save it again, it saves fine.

#### Issue
The numeric fields with default empty value are wrongly filled with a "0" after the saving the record. This happens with non-required non-custom/core numeric field (integer or float) from newly created modules from Module builder

#### Expected Behavior
It should be saved "null" if no value is set.

#### Actual Behavior
A "0" value appears on that field.

#### Possible Fix
Change behaviour of the DBManager for those fields.

#### Steps to Reproduce
1. Create a new module in Module Builder
2. Add an Integer or Decimal field
3. Add the field to Edit and Detail View
4. Deploy module
5. Create a new record to the module, filling only the required name
6. Check that the numeric field has a "0" value

#### Context
This is very confusing. It isn't the same a value 0 than an empty one. This should be fixed.

#### Your Environment
SuiteCRM Version used: Version 7.12.2
Browser name and version: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by gunnicom** [comment]
I think I fix this like this since years (I tried to integrate that in the original Sugar years ago):
```
diff --git a/include/database/DBManager.php b/include/database/DBManager.php
index 5d172ba93..0fe7644c4 100644
--- a/include/database/DBManager.php
+++ b/include/database/DBManager.php
@@ -543,7 +543,7 @@ abstract class DBManager
                     continue;
                 }

-                if (isset($data[$field])) {
+                if(isset($data[$field]) && (strlen($data[$field])>0 || $data[$field]===false)) { // GUNNIFIX
                     // clean the incoming value..
                     $val = from_html($data[$field]);
                 } else {
```
