### ISSUE TITLE
Checkbox not parsing in SuiteCRM 7..4.3 reports

### ISSUE THREAD

**Issue by CRMConsultant** [salesagility/SuiteCRM#945]
Hi 

We are generating a report in suitecrm. everything is working fine but its not parsing the checkbox value in both export and download pdf action.

**Comment by samus-aran** [comment]
This could be related - #592

**Comment by recci** [comment]
These were two separate issues. I fixed both. One is #517.

**Comment by ijdavie** [comment]
This is a duplicate of #517 and #592.
