### ISSUE TITLE
Calendar date selector popup doesn't use user-fdow in range date search and Massupdate

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9470]
Calendar date selector popup doesn't use user's defined first day of the week in range date search with operator "is between" and Massupdate assignment. See image bellow:
![fdowCalendar](https://user-images.githubusercontent.com/61022311/151176053-e942f2ea-e3d0-4b3d-ba15-16cec684fa03.gif)

#### Issue
Calendar date selector popup doesn't use user's defined first day of the week in range date search with operator "is between" and Massupdate assignment

#### Expected Behavior
First day of the week is a user-defined parameter and should be used in all Calendars

#### Actual Behavior
It always displayes Sunday (that is Day 0)

#### Possible Fix
Add the parameter for the startWeek in the setup of the Calendar

#### Steps to Reproduce
1. Set Monday as First day of the Week
2. Go to Contact Mass update view
3. Open the Calendar of the date field
4. Check that the first day of the week is Sunday

#### Context
This might confuse users.

#### Your Environment
SuiteCRM Version used: Version 7.12.2
Browser name and version: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Hi @SinergiaCRM,

Confirmed in latest,

For future testers: Best to use contracts module as it has one of these fields in the advanced filter, as far as I can tell this is the only area this issue exists.
