### ISSUE TITLE
Notes/attachments created via history sub-panel

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#95]
Relationship is not correctly set when a note/attachment is created via the history sub-panel on a contact.

Example: https://suitecrm.com/forum/bug-tracker/2481-cannot-attach-files-to-contacts

**Comment by recci** [comment]
I cant see any issue here. The Note?attachment seems to get attached to contact via the subpanel without issue.

**Comment by skrrp** [comment]
I'm also failing to see the problem. 

True, by default the subpanel is pointing to the Account of the Contact by default, but when you change it to Contact and type in the name of the contact (to select it from the auto-fill) I managed to get a Note with an attachment on the Contat just fine.

**Comment by willrennie** [comment]
Tested this issue and it doesn't appear to be an issue in the latest releases.
