### ISSUE TITLE
Global search error after upgrade

### ISSUE THREAD

**Issue by dtosun61** [salesagility/SuiteCRM#9516]
#### Issue

After upgrade from 7.10.15 to 7.12.4, global search doesn't work some modules like Contacts. There is an error like this;
```
Error
An unknown error has occurred while performing the search. Contact an administrator if the problem persists. More information available in the logs.
```
![image](https://user-images.githubusercontent.com/22373035/155119328-4fb7ac25-4e83-4163-bbf0-ca590e83f5ba.png)

![image](https://user-images.githubusercontent.com/22373035/155119404-25eae1c1-0f2e-4275-94e7-21e331b85aa0.png)

If i remove Contacts module from settings, it is working good. When i try to do for new fresh installation, it is working good. May be some files missing in upgrade package?

**This is log;**

`Tue Feb 22 14:03:42 2022 [2430483][134bd9c7-f8ed-de37-4ab0-4b9de86a2a13][FATAL] [ERROR] [SearchThrowableHandler] An unknown error has occurred while performing the search.
Tue Feb 22 14:03:42 2022 [2430483][134bd9c7-f8ed-de37-4ab0-4b9de86a2a13][FATAL] [ERROR] [SearchThrowableHandler] TypeError: Return value of SuiteCRM\Search\SearchResults::getRelatedId() must be of the type string, null returned in /var/www/crm/sractivities/lib/Search/SearchResults.php:227
Stack trace:
#0 /var/www/crm/sractivities/lib/Search/SearchResults.php(179): SuiteCRM\Search\SearchResults->getRelatedId()
#1 /var/www/crm/sractivities/lib/Search/SearchResults.php(162): SuiteCRM\Search\SearchResults->updateObjLinks()
#2 /var/www/crm/sractivities/lib/Search/SearchResults.php(145): SuiteCRM\Search\SearchResults->updateFieldDefLinks()
#3 /var/www/crm/sractivities/lib/Search/UI/SearchResultsController.php(132): SuiteCRM\Search\SearchResults->getHitsAsBeans()
#4 /var/www/crm/sractivities/lib/Search/SearchEngine.php(102): SuiteCRM\Search\UI\SearchResultsController->display()
#5 /var/www/crm/sractivities/lib/Search/SearchEngine.php(78): SuiteCRM\Search\SearchEngine->displayResults()
#6 /var/www/crm/sractivities/lib/Search/SearchWrapper.php(94): SuiteCRM\Search\SearchEngine->searchAndDisplay()
#7 /var/www/crm/sractivities/modules/Home/Search.php(50): SuiteCRM\Search\SearchWrapper::searchAndDisplay()
#8 /var/www/crm/sractivities/modules/Home/UnifiedSearch.php(41): require_once('/var/www/crm/sr...')
#9 /var/www/crm/sractivities/include/MVC/View/SugarView.php(823): include_once('/var/www/crm/sr...')
#10 /var/www/crm/sractivities/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
#11 /var/www/crm/sractivities/include/MVC/View/SugarView.php(210): ViewClassic->display()
#12 /var/www/crm/sractivities/include/MVC/Controller/SugarController.php(432): SugarView->process()
#13 /var/www/crm/sractivities/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#14 /var/www/crm/sractivities/include/MVC/SugarApplication.php(101): SugarController->execute()
#15 /var/www/crm/sractivities/index.php(52): SugarApplication->execute()
#16 {main}`
#### Expected Behavior

It should work for all modules.
#### Steps to Reproduce

1. Upgrade your CRM from any version to latest.
2. Add modules to search settings
3. Try it with global search
4. See the result.

#### Your Environment

* SuiteCRM Version used: 7.12.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 98.0.4758.102 64 bit
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04):

**Comment by johnM2401** [comment]
Hey @dtosun61 

I'm unable to replicate this, i'm afraid

I've upgraded from 7.10.15 to 7.12.4, but I'm still able to search on all modules:
![image](https://user-images.githubusercontent.com/13675281/155323905-a50fbe0b-f79c-44e4-b6fb-a3558f93a1d4.png)
![image](https://user-images.githubusercontent.com/13675281/155323935-8fa078c4-77ea-4478-b0d7-e71ac4ec1179.png)


Though I have some questions that might help with replicating:

- I see you have some custom Modules in the Search Modules
   Do you know if the Search Functionality works without these custom modules?

- Have you made any customizations to the Contacts Module?  (ie: Studio or via Code)
    If so, there could be something there causing conflict

- Does your CRM have Elasticsearch enabled? 
   The error messages in your screenshot appear to be associated to the label:
   `LBL_ELASTIC_SEARCH_EXCEPTION_DEFAULT`
  (Though this message very well could be used outside of Elasticsearch, for general error-displaying to users)

- Do you have this searching issue when using strictly non-utf8 data?
  (for example, Searching "Test" for a contact named "Test Test" )

Thanks!

**Comment by dtosun61** [comment]
Hello @johnM2401,

These are my answear:

I see you have some custom Modules in the Search Modules
Do you know if the Search Functionality works without these custom modules?
>>> Yes i have a custom module but i was tried it with without custom module, same results. It is is working with my custom module. As you see.
![image](https://user-images.githubusercontent.com/22373035/155338556-aa63ec87-5112-4339-a282-470107dfd30a.png)

Have you made any customizations to the Contacts Module? (ie: Studio or via Code)
If so, there could be something there causing conflict
>>> Yes, i made some customizations to the Contacts Module, but when i delete Contacts module in custom folder, it is same results.

Does your CRM have Elasticsearch enabled?
The error messages in your screenshot appear to be associated to the label:
LBL_ELASTIC_SEARCH_EXCEPTION_DEFAULT
(Though this message very well could be used outside of Elasticsearch, for general error-displaying to users)
>>> No, My CRM have not Elasticsearch enabled. It is already disabled.
![image](https://user-images.githubusercontent.com/22373035/155339204-cc07f02f-48ef-4b79-8231-9efeaf274ed4.png)


Do you have this searching issue when using strictly non-utf8 data?
(for example, Searching "Test" for a contact named "Test Test" )
>>> When i search "test" it doesn't give me any result. But when i search "Şule", it is giving error. "Şule" has Turkish character. But Turkish Character search doesn't work with Contacts. It is working good for others module.
![image](https://user-images.githubusercontent.com/22373035/155339803-4dd0a97d-f39a-4b86-8d08-064006d71cce.png)

![image](https://user-images.githubusercontent.com/22373035/155339844-db9c9cd4-d5d2-4f84-8ba7-62672c7ebada.png)

![image](https://user-images.githubusercontent.com/22373035/155340128-06210710-88d1-49ee-b75b-7883b4c8b18e.png)


Thanks!

**Comment by dtosun61** [comment]
Hello, 

I controlled my Contacts module for customization, i added two custom fields in vardefs.php. But it was working good before update :(
Removed them and tried again, same results.

**Comment by johnM2401** [comment]
Hey @dtosun61 

Thank you for your responses!

<br>

After removing the Contacts' Custom folder, did you run a Quick Repair and Rebuild & Clear Browser Cache?

The custom changes very well could still have been on the CRM instance, in auto-generated/cache files, which should be updated by a Quick R&R

It may be worth trying this, if you hadn't performed this initially

<br>

Also, after upgrading, did you run both:

"Quick Repair and Rebuild"

AND

"Repair UTF Encoding"

Found in Admin->Repair?


If not, I would recommend running these

(However, as the Repair UTF Encoding will make changes to UTF8-data, I would recommend taking a backup of your DB just incase you wish to revert the change)

<br>

Additionally, on your Contacts module, what field-type are the fields you are searching on?

Is it the Standard Firstname/Lastname fields? 

Or are these custom fields that contain Turkish characters?


Thank you again!

**Comment by dtosun61** [comment]
Hello @johnM2401,

Thank you for your support.

- After removing the Contacts' Custom folder, did you run a Quick Repair and Rebuild & Clear Browser Cache?
>>> Yes i did.

- Also, after upgrading, did you run both: "Quick Repair and Rebuild" AND "Repair UTF Encoding"
>>> Yes i did, both.

- Additionally, on your Contacts module, what field-type are the fields you are searching on?
Is it the Standard Firstname/Lastname fields? Or are these custom fields that contain Turkish characters?
>>> I'm using Name field in search field. Name of the contact list includes Turkish Char but i don't have any problems when i search it via filters. It it working good with Turkish Char. 

![image](https://user-images.githubusercontent.com/22373035/155962411-dc1fed02-5818-49b0-a864-90dc0575c6c9.png)

![image](https://user-images.githubusercontent.com/22373035/155962466-b41f406c-b005-4662-9bef-126526271230.png)
![image](https://user-images.githubusercontent.com/22373035/155962651-53ed7aed-891b-4529-8eb7-7fda859ec896.png)
![image](https://user-images.githubusercontent.com/22373035/155962680-3a1647ad-cb4c-414a-886e-43e6b77f5f08.png)

**Comment by johnM2401** [comment]
Hey @dtosun61 

Thank you again for your response!

hmmmm
I'm still not sure what the issue may be, i'm afraid 


- Have you ensured that your CRM's permissions are set correctly, both before and after the upgrade?

We typically recommend: 
```
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload config_override.php
sudo chown -R www-data:www-data 
```


- Have you checked your PHP error logs?
   There may be some items there that don't appear in the SuiteCRM error log


- Could you pass over the MD5 info of the CRM?
   This can be retrieved by going to: Admin -> Diagnostic Tool -> Uncheck everything except "MD5 Info", and click "Execute Diagnostic"

![image](https://user-images.githubusercontent.com/13675281/156531088-296244f6-cc3b-43c2-8239-948be53226f1.png)

If you could Download & Send that .zip to us, that might help us see if any files are not as they should be

**Comment by dtosun61** [comment]
Hello @johnM2401,

- Have you ensured that your CRM's permissions are set correctly, both before and after the upgrade?
>>> Yes i did it like this.

- Have you checked your PHP error logs?
>>> My php log
[log_sractivities.txt](https://github.com/salesagility/SuiteCRM/files/8212699/log_sractivities.txt)
This is my PHP log; 

- Could you pass over the MD5 info of the CRM?
>>> 
[27ebf4e2-2fad-db95-96f1-6228594f90bc.zip](https://github.com/salesagility/SuiteCRM/files/8212644/27ebf4e2-2fad-db95-96f1-6228594f90bc.zip)

**Comment by johnM2401** [comment]
Hey @dtosun61 

Thank you for your response!

<br>
<br>

I've unfortunately not yet been able to replicate

However, I did go through a 7.10.15 -> 7.12.4 process, and have grabbed the MD5 generated there
[c7141e42-ba04-d8c0-c730-622f4cebfa13.zip](https://github.com/salesagility/SuiteCRM/files/8246101/c7141e42-ba04-d8c0-c730-622f4cebfa13.zip)

This one, from a vanilla 7.10.15->7.12.4 is ~2376 lines, whereas the one from your instance is ~4627 lines

So, I'm curious if there was an issue with the upgrade, given the vast amount of custom changes on your instance

Perhaps there was a conflict somewhere?

<br>
<br>

First thing to check, Would you be able to run the "Rebuild JS Grouping Files" action in Admin->Repair

And let me know if this resolves any issues?

<br>
<br>

Then, it would be worth checking if any PHP errors display on-screen, when Global Searching on Contacts

You could do this by either enabling it in your php.ini

Or, adding:
```
ini_set('display_errors',1);
error_reporting(E_ALL ^ E_STRICT ^ E_NOTICE);
```

To the index.php file, below the <php tag, and clearing your browser cache

ie: 

![image](https://user-images.githubusercontent.com/13675281/157036145-75b08565-79a1-47c1-ac41-aec67229edfd.png)

This should display any Errors on-screen, that are not Notices/Strict Standards.

With this enabled, do you see any errors on-screen when Globally Searching with Contacts Enabled?

<br>
<br>

If not, would it be possible to check the Searching functionality on a fresh 7.12.5, with the same dataset?

This would allow us to narrow down whether or not your issues stem from the Dataset
(As there were issues with Searching on UTF8 characters, that were largely resolved as of 7.12.4, this would be good to confirm)


If all is well, you could try adding your Custom Changes to this instance, to see if issues then start to appear

<br>
<br>

Thank you again for your time and Patience on this!

**Comment by dtosun61** [comment]
Hello @johnM2401,

Thank you for your support and patience.

First thing to check, Would you be able to run the "Rebuild JS Grouping Files" action in Admin->Repair
And let me know if this resolves any issues?
>>> Yes i did it. But the problem is continue.

With this enabled, do you see any errors on-screen when Globally Searching with Contacts Enabled?
>>> There is no error, just warning.

![image](https://user-images.githubusercontent.com/22373035/158361744-6b8b7ef6-ccf0-48b4-85a6-0eaf00c2606c.png)

When i check the Searching functionality on a fresh 7.12.5, with the same dataset, it is working good.

Can i replace Search functionality files with working ones? If yes, which files should i replace. Let me know please.

**Comment by dtosun61** [comment]
The problem was fixed after recheck and improve my custom folder.

**Comment by dtosun61** [comment]
Hello,

I found the problem. When add target list filter to Contacts module, it is occurring.

![image](https://user-images.githubusercontent.com/22373035/165450231-e76c6a79-1e8a-4720-aec1-2f9f13ea6700.png)

When i remove it, it is working good.

**Adding filter like this;**

Add the file:

custom/Extension/modules/Contacts/Ext/Vardefs/targetlistfilter.php
with content:


```
<?php
$dictionary['Contact']['fields']['prospect_list_name'] = array (
	'name' => 'prospect_list_name',
	'rname' => 'name',
	'id_name' => 'prospect_list_id',
	'vname' => 'LBL_PROSPECTLIST_NAME',
	'type' => 'relate',
	'link' => 'prospect_lists',
	'table' => 'prospect_lists',
	'isnull' => 'true',
	'module' => 'ProspectLists',
	'dbType' => 'char',
	'len' => '255',
	'source' => 'non-db',
	'duplicate_merge'=> 'disabled',
);
```
Add the file:

custom/Extension/modules/Contacts/Ext/Language/en_us.targetlistfilter.php
with content:


```
<?php
$mod_strings['LBL_PROSPECTLIST_NAME'] = 'Target List:';
```
Afterwards, do a Admin / Repair / Quick Repair and Rebuild

Open Studio, module Contacts / Layouts / Filter
The filter field Target List is now available in the Hidden list and can be added to the Quick Filter and the Advance Filter layout.

**Comment by rj2Skipper** [comment]
I do confirm this issue.

I tested with 3 installations:
- crm1: upgrade from 7.11.10 to 7.11.23 to 7.12.5
- crm2: upgrade from 7.11.10 to 7.11.23 to 7.12.5, which is a crm playground with same modules etc as crm1
- crm3: clean install with demo data 7.12.5

Global-Search Test results:
- no issue in global search on crm3
- no issue in global search on crm2 when module "Power Prospecting  6.5.16.1  30.07.2017 21:41 Target Lists from Subpanels & Mass Update" is DISABLED
- **yes** issue in global search on crm2 when module "Power Prospecting  6.5.16.1  30.07.2017 21:41 Target Lists from Subpanels & Mass Update" is RE-ENABLED
- **yes** issue in global search on crm1 when module "Power Prospecting  6.5.16.1  30.07.2017 21:41 Target Lists from Subpanels & Mass Update" is ENABLED <- because that's the production-crm, i must not disable this module

ciao Ralf

**Comment by johnM2401** [comment]
Hey @dtosun61, @rj2Skipper 

Thank you both for your additional info here, I've given this another try by making the suggested customization on 7.11.10, and upgrading to 7.12.5

I was able to search without issues on 7.11.10, but the global search fails on 7.12.5

I've marked this as a bug now

Thank you again for your assistance!
