### ISSUE TITLE
After Search URL of items in list show localhost not the FQDN

### ISSUE THREAD

**Issue by mckinnon81** [salesagility/SuiteCRM#9534]
#### Issue
When using the search function to search for accounts a list is produced. When you hover of the items in the list the FQDN shows localhost, not the FQDN of the site.

#### Expected Behavior
The correct FQDN URL should display when hovering over link so you can click on and open item.

#### Actual Behavior
Attempts to load URL with localhost

#### Your Environment
* SuiteCRM Version 7.12.5
* Running in Docker Container

**Comment by pgorod** [comment]
Check your **site_url** setting in **config.php** or **config_override.php**

**Comment by mckinnon81** [comment]
> Check your **site_url** setting in **config.php**

Thank you, that fixed it. Manually applying site_url in config.php

I will reach out to the maintainer of the Docker Image on why the SUITECRM_HOST environment variable is not updating the config.php.
