### ISSUE TITLE
Activity subpanel isn't working in a module with a parent_type / flex relate field

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9537]
When having a custom module that contains a flex relate field in detail view and a relationship with the Activities modules (Activity/History subpanels), the Activity/History subpanel aren't working, instead they display a DB error:
![Selection_470](https://user-images.githubusercontent.com/61022311/158377598-fb2e8402-8cb6-4e92-b2c6-461ea74474a5.png)
The log shows this:
```
Tue Feb 15 09:05:22 2022 [29][2][FATAL] Error running count query for stic_Bookings List:  Query Failed: ( SELECT count(*) c FROM meetings  LEFT JOIN meetings_cstm ON meetings.id = meetings_cstm.id_c  INNER JOIN  stic_bookings stic_bookings_activities_1_meetings_rel ON meetings.parent_id=stic_bookings_activities_1_meetings_rel.id AND stic_bookings_activities_1_meetings_rel.deleted=0
 AND parent_type = 'stic_Bookings'
 where ( meetings.parent_id='70ee6925-1771-cbef-ae90-62051ffd8b6f' AND (meetings.status='Held' OR meetings.status='Not Held')) AND meetings.deleted=0 ) UNION ALL ( SELECT count(*) c FROM tasks  INNER JOIN  stic_bookings stic_bookings_activities_1_tasks_rel ON tasks.parent_id=stic_bookings_activities_1_tasks_rel.id AND stic_bookings_activities_1_tasks_rel.deleted=0
 AND parent_type = 'stic_Bookings'
 where ( tasks.parent_id='70ee6925-1771-cbef-ae90-62051ffd8b6f' AND (tasks.status='Completed' OR tasks.status='Deferred')) AND tasks.deleted=0 ) UNION ALL ( SELECT count(*) c FROM calls  INNER JOIN  stic_bookings stic_bookings_activities_1_calls_rel ON calls.parent_id=stic_bookings_activities_1_calls_rel.id AND stic_bookings_activities_1_calls_rel.deleted=0
 AND parent_type = 'stic_Bookings'
 where ( calls.parent_id='70ee6925-1771-cbef-ae90-62051ffd8b6f' AND (calls.status='Held' OR calls.status='Not Held')) AND calls.deleted=0 ) UNION ALL ( SELECT count(*) c FROM notes  INNER JOIN  stic_bookings stic_bookings_activities_1_notes_rel ON notes.parent_id=stic_bookings_activities_1_notes_rel.id AND stic_bookings_activities_1_notes_rel.deleted=0
 AND parent_type = 'stic_Bookings'
 where ( notes.parent_id='70ee6925-1771-cbef-ae90-62051ffd8b6f') AND notes.deleted=0 ) UNION ALL ( SELECT count(*) c FROM emails  INNER JOIN  stic_bookings stic_bookings_activities_1_emails_rel ON emails.parent_id=stic_bookings_activities_1_emails_rel.id AND stic_bookings_activities_1_emails_rel.deleted=0
 AND parent_type = 'stic_Bookings'
 where ( emails.parent_id='70ee6925-1771-cbef-ae90-62051ffd8b6f') AND emails.deleted=0 ): MySQL error 1052: Column 'parent_type' in on clause is ambiguous
```

#### Issue
The Activity subpanel doesn't work in a custom module that contains a flex relate field in the detail view. The custom module and the field are built using the module builder

#### Expected Behavior
They should work as in any other module

#### Actual Behavior
A DB error appears

#### Possible Fix
https://github.com/salesagility/SuiteCRM/blob/e93b269f637de313f45b32c58cef5ec012a34f58/data/Relationships/One2MBeanRelationship.php#L371-L373

The field $tableInRoleFiler is empty here, therefore it builds the query without specifying the table in the column selection

https://github.com/salesagility/SuiteCRM/blob/e93b269f637de313f45b32c58cef5ec012a34f58/data/Relationships/One2MBeanRelationship.php#L347-L365
We tested that removing the second part of the condition it solves the issue. Although we aren't sure if it won't break something else.

#### Steps to Reproduce
1. Create a module in the module builder that contains a flex relate field added to the DetailView
2. Deploy the module and create a relationship with Activities using Studio
3. Create a record in the module and open the Activity subpanel, an error appears

#### Context
**

#### Your Environment
SuiteCRM Version used: Version 7.12.4
Browser name and version: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment]
Assessed and confirmed in lastest :+1:

**Comment by gunnicom** [comment]
Removing this part fixes it for me, too:
`     && 
     ( 
         $targetTable == "meetings" 
         || $targetTable == "notes" 
         || $targetTable == "tasks" 
         || $targetTable == "calls" 
     ) `

**Comment by gunnicom** [comment]
Bug still present in 7.14.1
