### ISSUE TITLE
Timezone ignored in report period

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#9551]
#### Issue

The users timezone appears to be ignored when using the period conditions (spotted on the "Last Month" condition). I'm unsure if this is intended or not.

#### Expected Behavior

A user viewing a report with the condition "Last Month" should only see records for the last month.

#### Actual Behavior

Records that fall within the timezone offset are shown. This means the user may see entries in the report for the last day of the month two months ago,

#### Possible Fix

`getPeriodDate` in `aor_utils` could subtract the users timezone offset before returning the date. This would mean a user will always see the correct list of results but also means that users in different timezones will see different report results.

#### Steps to Reproduce

1. Create a new report on calls with date created = Last Month and add date created to the columns
2. Switch TZ to Arizona
3. Modifiy a call so it's date created is 23:00 on the last day of two months ago (i.e when running the report in March created date should be 31st Jan 23:00
4. Check the report - the call that is outside of the period will appear in the results and the date created will show as outside of the conditions.

#### Context

Trying to create a report that is viewed by users in a different timezone.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04

**Comment by jack7anderson7** [comment]
When testing this issue, it is better to set the date to the first on the month (ie if last month is February, set the date to 2022-02-01 03:00:00) and then you will see that in the report that the date is set to outside the parameters of the period on the report.
