### ISSUE TITLE
SuiteCRM Admins are able to uncheck the SuiteP theme when no other themes are available.

### ISSUE THREAD

**Issue by lok1946** [salesagility/SuiteCRM#9562]
#### Issue

I am new to SuiteCRM.  We have a fresh install of SuiteCRM on Unbuntu. While exploring the admin section I disabled the only theme available which is the SuiteP theme.
I was exploring to see if disabling the SuiteP theme would cause SuiteCRM to display only in black and white.
After disabling the SuiteP theme and saving my change, I attempted to return to my Calendar page. At that point SuiteCRM became non-functional with a message similar to "No theme available".
Disabling the SuiteP theme when no other thems are availble crashed SuiteCRM. This is why this is a bug.

#### Expected Behavior

When only one theme is available to SuiteCRM the theme should not be able to be disabled.

#### Actual Behavior

SuiteCRM was unable to display any pages with company data. Instead a message that no theme was available was displayed.

#### Possible Fix

A fix for this would be to disallow the checkbox used to enable/disable a theme from being active when only one theme is available.

#### Steps to Reproduce

1. Go to admin->themes
2.  Make sure only the SuiteP theme is available.
3.  Disable the SuiteP theme and save your change.
4. Refresh your page or attempt to jump to a different page.

#### Context

I feel this should be a high priority.  If other people new to SuiteCRM perform the same actions I did, then the product becomes useless and their trust in your QA process would be diminshed.

#### Your Environment

* SuiteCRM Version used:  Version 7.11.23
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Latest version of Edge and Firefox
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

**Comment by johnM2401** [comment]
Hey there, 

I've had a look at this, but I've been unable to replicate, I'm afraid

As far as I can see, the "Enabled" Checkbox is disabled in Themes:
![image](https://user-images.githubusercontent.com/13675281/163794857-bf87bff7-a340-4353-8628-99f2a215d228.png)


So I am unable to de-select the SuiteP theme

<br>

Do you know if anything specific is required for this?
ie: Specific PHP Version / Other themes installed but disabled / etc

Thanks!
