### ISSUE TITLE
HTML Type field doesn't populate

### ISSUE THREAD

**Issue by dtosun61** [salesagility/SuiteCRM#9563]
#### Issue
When i create HTML type field and add it to Edit View layout, it doesn't editable. There is no input box.
I was tried it with new latest 7.12.5 version. 

#### Expected Behavior

It should be editable.
#### Actual Behavior

it is not editable. There is no input box.
#### Possible Fix

I don't know.
#### Steps to Reproduce

1. Add HTML type field
![image](https://user-images.githubusercontent.com/22373035/163334551-dc6fc7a4-e3f3-4315-9b6e-1b92de502953.png)

2. Add it to Edit View layout
![image](https://user-images.githubusercontent.com/22373035/163334744-75a8c0df-59d7-4304-87e8-1c73ac6b0516.png)

3. Save and Deploy
4. Quick Repair and Rebuild
5. Look add the added module, The field is not editable
![image](https://user-images.githubusercontent.com/22373035/163335072-39cc1f4e-aca1-4926-aed6-5db75b8c4776.png)

#### Your Environment

* SuiteCRM Version used: 7.12.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04):

**Comment by johnM2401** [comment]
Hey there, 

As far as I'm aware, the HTML field is primarily used for Displaying purposes by the CRM, and is not normally for User-editing

The [Documentation ](https://docs.suitecrm.com/admin/administration-panel/studio/)describes it as:
![image](https://user-images.githubusercontent.com/13675281/163797073-24bf2753-b2ca-411a-95a6-69adee7f59a9.png)


I would recommend creating a WYSIWYG-type field, as this will allow you to edit HTML-style text freely
![image](https://user-images.githubusercontent.com/13675281/163797219-d40115d7-25d0-455c-b8c5-3ec38ea90850.png)
![image](https://user-images.githubusercontent.com/13675281/163797241-449dbee2-013c-4347-82a7-4045b136e178.png)

<br>


However, I have noticed that, even if you set a default value for this in studio:
![image](https://user-images.githubusercontent.com/13675281/163797624-8132a6be-5378-4540-8076-b30e12dd4a14.png)
![image](https://user-images.githubusercontent.com/13675281/163797685-e6aa268c-3702-4426-b6ea-0582cae0fa38.png)


It doesn't appear to display this on the Detailview, so I will mark this as a bug


Thanks!
