### ISSUE TITLE
Error on first time setup

### ISSUE THREAD

**Issue by web-sharp** [salesagility/SuiteCRM#9585]
#### Issue

When performing setup on 7.12 I receive the following error

PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in ./install/performSetup.php on line 715

#### Expected Behavior
I'm able to connect to mysql db, database is created, then fails.

#### Actual Behavior

Does SuiteCRM work with PHP 8?  Should I be using version 7?

#### Steps to Reproduce
1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 17.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari
* Environment name and version (e.g. MySQL, PHP 7):   PHP 8.1
* Operating System and version (e.g Ubuntu 16.04):   MacOS aarch64

**Comment by samus-aran** [comment]
Hey there @web-sharp 

Here is the compatibility matrix for the versions.
https://docs.suitecrm.com/admin/compatibility-matrix/

We don't officially support PHP 8.1 so you may run into issues (possibly you already have :sweat_smile: )
I'll close this issue for now but jump into the forums if you need help setting up on the other PHP versions :+1:

**Comment by web-sharp** [comment]
It doesn't seem to matter which version I'm using 7.4 is the same.


[Fri May 13 09:07:11.990853 2022] [php:warn] [pid 12121] [client 192.168.12.3:49192] PHP Warning:  Trying to access array offset on value of type null in /Library/WebServer/Documents/include/utils.php on line 1873
[Fri May 13 09:07:11.990873 2022] [php:warn] [pid 12121] [client 192.168.12.3:49192] PHP Warning:  Trying to access array offset on value of type null in /Library/WebServer/Documents/include/utils.php on line 1827
[Fri May 13 09:08:14.271590 2022] [php:error] [pid 12121] [client 192.168.12.3:49204] PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /Library/WebServer/Documents/install/performSetup.php on line 715, referer: http://crm.websharpstudios.com/install.php
