### ISSUE TITLE
Invalid login or password for IMAP, Exchange

### ISSUE THREAD

**Issue by peterze123** [salesagility/SuiteCRM#9612]
Hello, I’m working on version 7.12, PHP 7.3.33-2+ubuntu22.04.1. I was able to successfully connect my personal outlook account to inbound email via the following settings:
Mail Server Address: outlook.office365.com
Mail Server Protocol: IMAP
Mail Server Port:993

But, when I try with an office 365 business account with a specified domain: xxx@xxx.group, it repeatedly complains about invalid login and password, despite it being correct. I was not able to locate anything in suitecrm.log, and my server log just complains: PHP Notice: Unknown: Can not authenticate to IMAP server: AUTHENTICATE failed

I went to the office 365 admin and made sure IMAP is enabled for every user, also looked into azure apps and OAuth, but still could not get it to work. Are there any hints to better debug or solutions for this? Thanks in advance!!!

**Comment by pgorod** [comment]
Can you please try with a really simple password with no special characters? Just numbers and letters.

**Comment by peterze123** [comment]
The password is really simple. I tried with imap_open ("{outlook.office365.com:993/imap/ssl/novalidate-cert}", "EMAILADDRESS", "PASSWORD"); PHP continues to complain about authenticating failed, is there any way to get past the authentication? Thanks in advance

**Comment by pgorod** [comment]
You can get extra SMTP logging, that should help

https://community.suitecrm.com/t/office-365-suite-v-7-10-7-ubuntu-16-04/65589/2?u=pgr

**Comment by peterze123** [comment]
The issue is with O365, tried with the connectivity analyzer, had the error S: 2 NO LOGIN failed. While the authentication policy is set as enabled for all IMAP-related settings, still does not work. So, probably due to basic authentication going to be disabled by Microsoft? Just used another mailbox as an alternative.
