### ISSUE TITLE
where are the instructions to install

### ISSUE THREAD

**Issue by f1-outsourcing** [salesagility/SuiteCRM#9631]
I am getting these errors:

Composer autoloader not found. please run "composer install"

bash-4.2$ php -d disable_functions=none ../composer.phar install --ignore-platform-req=ext-imap
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.

bash-4.2$ php -d disable_functions=none ../composer.phar update --ignore-platform-req=ext-imap
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wikimedia/composer-merge-plugin ^1.4 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.0, v1.4.1].
    - wikimedia/composer-merge-plugin[v1.4.0, ..., v1.4.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.

bash-4.2$ php -d disable_functions=none ../composer.phar install --ignore-platform-req=ext-imap
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.

branch 7.11.x

**Comment by f1-outsourcing** [comment]
v7.12.6 works fine, but a manual some instructions would be nice.

**Comment by pgorod** [comment]
Google tells me they're here: 
https://docs.suitecrm.com/admin/installation-guide/

If you have questions, please use the Community Forums: 
https://community.suitecrm.com

**Comment by f1-outsourcing** [comment]
I think it needs to be here.

**Comment by pgorod** [comment]
Sorry, what do you mean here? The documentation site is big and complex, and user-editable, it can't just be put into a README... how would you do it?

**Comment by pgorod** [comment]
Granted, I just checked the README here on Github and it has all links there, EXCEPT the one to the Docs site and installation instructions. Maybe we could just add that there.

**Comment by f1-outsourcing** [comment]
I am not installing that often via the cli/php/composer, so it is nice to have a little guidance. I would just put something basic, like I have now created for myself.

CREATE DATABASE macrm CHARACTER SET utf8 COLLATE utf8_general_ci;



```
git clone -b v7.12.6 https://github.com/salesagility/SuiteCRM.git crm.example.com

scl enable rh-php73 bash

php -d allow_url_fopen=1 -d disable_functions=none -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

php -d allow_url_fopen=1 -d disable_functions=none composer-setup.php
php -r "unlink('composer-setup.php');"

umask 0027
cd crm.example.com/
php -d disable_functions=none ../composer.phar install
```
