### ISSUE TITLE
Display TinyMCE in step 4 of the campaigns form wizard

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9646]
#### Issue
In step 4 of the form creation wizard, the TinyMCE editor is not displayed after the second run of the wizard. The first time it shows it correctly but from the next execution it shows the textarea with the raw html code.

![Do not display TinyMCE](https://user-images.githubusercontent.com/61022311/178539521-859eafc9-0565-49a0-9f7c-3b656782e4b6.gif)

#### Expected Behavior
The CRM should show the tinyMCE editor with the content of the form

#### Actual Behavior
The first time it shows it correctly but from the next execution it shows the textarea with the raw html code.

#### Steps to Reproduce

1. Generate different forms (leads, contacts o targets )and check that the TinyMCE editor is not displayed in step 4 of the form creation wizard

#### Context
Medium priority
In step 4 of the form creation wizard, users cannot view or edit the form in the TinyMCE Editor.

#### Your Environment

SuiteCRM Version used: Version 7.12.6
Browser name and version: Versión 100.0.4896.88 (Build oficial) (64 bit
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 20.04

**Comment by pgorod** [comment]
This should be tested also in other places that use the editor, namely Case updates. 

These two past issues touch the part of the code that is being fixed here, and they're both about Case updates:

#6570
#7152

Also, the Compose Windows, and the Email Templates edit view.

**Comment by SinergiaCRM** [comment]
Hi @pgorod,

In an environment with PR #9648 deployed, I configured TinyMCE as the editor and accessed the following views to check that after adding content in the editor and saving, it was saved:
- Email compose window,
- Edit view of email templates
- Step 3 of the campaign wizard

In relation to Issues #6570 and #7152, we do not use the cases module but doing some quick tests I have verified that the description field can be edited (both in the edition view and from the inline edition in the detail view ) and the Updates: text field (edit view)

**Comment by pgorod** [comment]
Thanks for this, and for the valuable work you've been doing.

I hope your PR's start getting merged...
