### ISSUE TITLE
Admin Connectors gives white page. Cannot find class ConnectorsController. Autoloader?

### ISSUE THREAD

**Issue by chris001** [salesagility/SuiteCRM#97]
From forum thread...
https://suitecrm.com/forum/bug-tracker/2586-admin-connectors-module-blank-page-crash-bug

When you view the Connectors page, it gives a white page.

Error in the php log says it can't find the class ConnectorsController....

Looking at the source of modules/Connectors/controller.php it shows the class CustomConnectorsController but not the class ConnectorsController.
https://github.com/salesagility/SuiteCRM/blob/master/modules/Connectors/controller.php

Looking at github sugarcrm_dev , the file is different, it contains the class ConnectorsController not CustomConnectorsController
https://github.com/sugarcrm/sugarcrm_dev/blob/master/modules/Connectors/controller.php

Looking further at suitecrm github, it appears the class ConnectorsController is in the custom/modules/Connectors/controller.php - the reverse of what it probably should be - it should be in the standard system location, with the CustomConnectorsController in the custom/modules/Connectors/controller.php
https://github.com/salesagility/SuiteCRM/blob/master/custom/modules/Connectors/controller.php

Is this a bug ?
Is the autoloader looking for the class in the original Sugar location for the php file, but the actual class in that file has changed ?

**Comment by recci** [comment]
This issue apears to have been fixed.

**Comment by jobst** [comment]
I can second that https://github.com/patovala fix works with ONE addition:
download the full version of SuiteMAX (latest version) and rsync the content of "include/connectors" over the top of your own SuiteCRM install.

It fixed it for me, I can now see the connectors, my first step was to disable the InsideVIEW thing.

I would assume that the upgrade from the last version of SugarCRM to SuiteCRM did (possibly) not copy this, but there also is a problem with the classes in the controller.php for the connectors.
