### ISSUE TITLE
Replace the address country input field with a dropdown

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#970]
As written in the [blog] (https://suitecrm.com/suitecrm/blog/entry/convert-the-country-text-field-in-suitecrm-to-a-drop-down-list), the country dropdown list is already in SuiteCRM. 
Why wouldn't we use this by default for the country field in accounts/contacts/leads instead of the input field?

**Comment by GeorgeUni** [comment]
For data integrity wouldn't it make sense to have it behave as a drop down of all countries?

I'd suggest in the format of [Country Name (ISO 3166-1 Code)] or even to be fancy [Country Flag Icon 
Country Name(Country ISO Code)]

for e.g. 
imageUnited Kingdom(GB)

**Comment by GeorgeUni** [comment]
Why is this closed then?

**Comment by ghermans** [comment]
@GeorgeUni this one is not closed.

**Comment by GeorgeUni** [comment]
:+1: 
I'd call this high priority

**Comment by GeorgeUni** [comment]
:+1: Please label as high priority.

from a design standpoint the current method makes no sense.

**Comment by georgiel** [comment]
I'd love for it to actually have a UI, just a simple checkbox when adding a address field type that let's you choose whether want dropdown. It can't be that complex at all.

I'm honestly surprised it wasn't an option from day one.

**Comment by GeorgeUni** [comment]
:+1:

**Comment by ghermans** [comment]
@Georgiel don't count on it that this will integrated in the next release :)

**Comment by ghermans** [comment]
Since we don't get any feedback i will close this one.

**Comment by chris001** [comment]
Agreed, activate the countries dropdown would be a sensible improvement for the app, to keep the country data clean and tidy.
The country dropdown list, `countries_dom`, is already shipping with the app, so, why not use it.
Code to use the country list was provided by Andrew McLauchlan, 2.5 years ago, as a hand modification.
Why not just add this to the core?  Save a lot of time.
https://suitecrm.com/suitecrm/blog/entry/convert-the-country-text-field-in-suitecrm-to-a-drop-down-list

**Comment by GeorgeWL** [comment]
reopen the issue. 

it's bloody obvious that it's wanted

**Comment by ghermans** [comment]
@GeorgeWL no.

**Comment by GeorgeWL** [comment]
@gherman well the 3 other commented seem to disagree with the idea that there's no interest.
