### ISSUE TITLE
Converted contact activity doesn't appear in Calendar

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#971]
If the “copy” option in systems => “convert lead” is selected, after that the lead is converted to a Contact & Account, the "copied" call in the Contacts activities subpanel doesn't appear in Calendar.
Tested with Suitecrm test data.

STEP TO REPRODUCE:
Created a Call Activity "TestCalendar" for the Lead « Galen Polak », assigned to Chris Olliver
Converted Lead to Contact (selecting contact, not Account)
RESULT =>  Call from the Lead is displayed at the calendar, but not the call of the Contact

VERSION: SuiteCRM v7.5.1 Sugar - Version 6.5.20 (Build 1001)
BROWSER & DATABASE: Mozilla firefox 44.0 & MySQL 5.1.40

**Comment by recci** [comment]
This appears (to me at least ) to be the way its supposed to work. When you convert the Lead to a Contact you are forced to create or select an Account. The Call is then linked to the Account rather than the Contact. This therefore doesn’t show up in the Calendar. I am not sure if its meant to. 

You have to set Lead Conversion Options to Copy in the system settings for this work.

**Comment by jobvector** [comment]
Like described in the original post the conversion option is set to "copy". I think ist clearly a bug if the call is not displayed in the Calender that is linked either to account or contact or both. 
For example a planned Call for the Lead that is displayed in the Calender of an account manager (user), after the conversion it is still a planned Call that should be displayed in the Calender of the account manager.

Its the same problem if you "link" (actually a new call is created and related) the call to an account during the conversion.

The **solution** is to re-save (find call either in accounts or contacts or both, go to EditView and click save) the created call after that it will be displayed in the Calender.

We would rather use the "Move" option for lead conversion but that has its own issues.
There are quite a few bugs related to lead conversion that we had reported to sugarcrm back in the day that are still not fixed and creeped their way into the suitecrm code: see also https://github.com/salesagility/SuiteCRM/issues/965
