### ISSUE TITLE
Date field value isn't saved in a Workflow action related module

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9725]
When assigning a value to a date field of a related module in an action of a Workflow, the value isn't saved properly. After Saving and Editing, the value is gone.
![wfemptydate](https://user-images.githubusercontent.com/61022311/182413440-9e8f3883-04a6-4cae-89b9-378eb4b9ecbf.gif)

#### Issue

Date field value isn't saved in a Workflow action related module

#### Expected Behavior

The vlaue should besaved

#### Actual Behavior

The value dissappears

#### Possible Fix

fixUpFormating function from Workflow doesn't identify the module and the field type. Therefore it formats the value, ending up erasing its content.

#### Steps to Reproduce

1. Create a Workflow based in Accounts
2. Add an action that modifies the record
3. Add the Birthdate field from the Contacts::Contacts relationship
4. Assign a value to the date field
5. Save the WF
6. Edit again de WF and check that the value has gone.

#### Context

This is troublesome when an user wants to modify fields from related records

#### Your Environment

SuiteCRM Version used: Version 7.12.6
Browser name and version: Versión 100.0.4896.88 (Build oficial) (64 bit
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 20.04

**Comment by rgrif** [comment]
Try this. I have been looking into this issue too. Change the beginning of the function fixUpFormatting to the following and see of that resolves your issue.

    function fixUpFormatting($module, $field, $value)
    {
        // Fix 2022_07_15 for date in related module not saving from creation or updating from view
        global $timedate, $beanFiles, $beanList;

        require_once($beanFiles[$beanList[$module]]);
        $bean = new $beanList[$module];

        static $boolean_false_values = array('off', 'false', '0', 'no');

        $type="";
        if (isset($bean->field_defs[$field])) {
            //$field exists in bean field_defs. Probably because in root report module
            $type=$bean->field_defs[$field]['type'];
        }else{
            //$field does not exists in bean field_defs it will have come from a date in a related module
            //Check to see if it has a date format
            
            $date_part = substr($value, 0, 10);

            // Allowing for different date separators
            $date_part = str_replace(".", "/", $date_part);
            $date_part = str_replace("-", "/", $date_part);
            
            $is_date = false;

            $date_formats = array (
                '^([0-9]{4})/[0-9]{2}/[0-9]{2}', // 'Y/m/d'
                '^([0-9]{2})/[0-9]{2}/[0-9]{4}'  // 'd/m/Y' or m/d/Y
            );

            foreach ($date_formats as $regexp) {
                if (preg_match ('|' . $regexp . '|', $date_part)) {
                    $is_date = true;
                    break;
                }
            }

            if($is_date) {
                $type='datetimecombo';
            }
            else {
                $type="unknown"; // Other kind of error
            }
        }

        switch ($type) {

**Comment by SinergiaCRM** [comment]
Hi @rgrif ,

Thanks for sharing your patch.

We provided as well a patch in this PR that is working fine: https://github.com/salesagility/SuiteCRM/pull/9726
