### ISSUE TITLE
In step 3 "Templates" of the Campaign Wizard, something has somehow removed the full content of your email template

### ISSUE THREAD

**Issue by timo-ecm2** [salesagility/SuiteCRM#9737]
#### Issue
If you want to open an existing Campaign of any type with an email template by clicking on the template name below the subtab Email Marketing, something strange happens. When it opens in step 3 "Templates" of the Wizard, scroll down to the editor TinyMCE. The content of your Email template has disappeared, it's empty. 

Do not try to save this because it will overwrite the content of the original email template, rendering it useless. However, before you save, you can get your original email template back. First select another existing one and after that reselect your original. In TinyMCE the content of your Email template will show up, in its original state. Now you can save it before you go to the next stage in the Wizard.

#### Expected Behavior
In step 3 "Templates" of the Wizard, the editor TinyMCE must show the original email template, unharmed.

#### Actual Behavior
When you have opened step 3 "Templates" of the Campaign Wizard, something has somehow removed the full content of your email template. Perhaps TinyMCE has removed it or something related to the Wizard of the Campaign Module. 

#### Possible Fix
I don't know.

#### Steps to Reproduce
1. First check if TinyMCE is you editor for Emails.    
2. Navigate to module Campaigns from the navigation menu.   
3. Open an existing Campaign.    
4. Click on an email template.         
5. Step 3 "Templates" of the Wizard opens.   
6. Scroll down to the TinyMCE editor below.    
7. Your email template should have disappeared.    

#### Context
Design new Campaign.

#### Your Environment
1. SuiteCRM Version used: 7.12.6
2. Browser name and version: Google Chrome Versie 104.0.5112.81 (Officiële build) (64-bits)
3. Environment name and version: MariaDB 10.5, PHP 7.4
4. Operating System and version User: Windows 11 - 21H2 - 22000.856

**Comment by johnM2401** [comment]
Hey
Thanks for raising this issue!

A quick note for future reference, This appears as though it may be an issue with Chromium-based browsers
(ie: Chrome/Opera/Edge)

As I cannot replicate this in Firefox, but can replicate in Chrome/Chromium

Thanks!

**Comment by timo-ecm2** [comment]
Indeed, thnx.
