### ISSUE TITLE
Cases created automatically from E-mails showing HTML in fresh install of 7.5.1

### ISSUE THREAD

**Issue by meethoss** [salesagility/SuiteCRM#975]
As you can see from the below screenshots when a case is automatically created from an E-mail it is displaying HTML. That same E-mail, however, when used to manually create a case shows up fine. I've looked around for similar issues which I have attempted to resolve in the same way but could not get it working properly; either way this needs a permanent fix as this is a fresh install.

A little extra info if it helps - I used Gmail as the mailbox and the test E-mail was sent from Outlook 2013.

![capture1](https://cloud.githubusercontent.com/assets/15215178/13107608/6c7b36aa-d566-11e5-80f9-8a763ffcc285.PNG)

![capture2](https://cloud.githubusercontent.com/assets/15215178/13107616/6f2e4ff4-d566-11e5-929a-aced8dfddb5e.PNG)

**Comment by opensourcecrm** [comment]
go to custom/modules/Cases/metadata/detailviewdefs.php
and add this piece of code it will resolve your issue. 
 array (
          0 => 
          array (
            'name' => 'description',
            'customCode' => '{$fields.description.value|escape:\'html_entity_decode\'}',
          ),

**Comment by meethoss** [comment]
Hi there,

Thanks for your response, unfortunately it hasn't fixed the issue. I have modified line 122 from:

        array (
		'description',
        ),

to:

        array (
          0 => array (
			'description',
			'customCode' => '{$fields.description.value|escape:\'html_entity_decode\'}',
		  ),
        ),

But no luck. Any ideas?

**Comment by opensourcecrm** [comment]
check with this :
'customCode' => '{$fields.description.value|escape:\'htmlentitydecode\' |escape:\'html\'|strip_tags|url2html|nl2br}',

**Comment by meethoss** [comment]
This has fixed the issue, thanks - I take it this is going into a later release? I wouldn't know how to add this myself otherwise I would offer to :)

**Comment by opensourcecrm** [comment]
go to custom/modules/Cases/metadata/detailviewdefs.php update that customcode with description field

**Comment by abeo** [comment]
Running 7.5.3 and still have this issue. 

Using opensourcecrm's suggestion I edited custom/modules/Cases/metadata/detailviewdefs.php
to look like this,
array (
      0 => array (
        'description',
        'customCode' => '{$fields.description.value|escape:\'html_entity_decode\'}',
      ),
and this,
 array (
          0 => 'description',
		  'customCode' => '{$fields.description.value|escape:\'htmlentitydecode\' |escape:\'html\'|strip_tags|url2html|nl2br}',
        ),

Not joy, HTML still displays either way.

**Comment by meethoss** [comment]
Maybe it's because you're editing the file in the custom directory? I directly edited the one in the modules directory: modules/Cases/metadata

That worked for me.

**Comment by abeo** [comment]
Yes I was editing in the Custom directory. However, when I edit in the Modules directory same result, Case Description still displays HTML tags.

This is my code'
'
4 => 
        array (
		0 => array (
			'description',
		'customCode' => '{$fields.description.value|escape:\'htmlentitydecode\' 
		|escape:\'html\'|strip_tags|url2html|nl2br}',
		),
5 => 
'

**Comment by abeo** [comment]
I also edited custom/modules/Cases/metadata/detailviewdefs.php
with the same code but this cases and error that does not allow the Cases page to display.

**Comment by meethoss** [comment]
I'd suggest you get rid of the custom one - I don't know how that works as my experience of Suite so far is limited, but I would guess that's not helping.

My code from line 121 to 127 looks like this:

        4 => 
        array (
          0 => array (
			'description',
			'customCode' => '{$fields.description.value|escape:\'htmlentitydecode\' |escape:\'html\'|strip_tags|url2html|nl2br}',
		  ),
        ),

Looks like mine but you seem to be missing a bracket and comma?

**Comment by abeo** [comment]
Okay I removed any changes from custom./modules/Cases/metadata/detailviewdefs.php and  updated /modules/Cases/metadata/detailviewdefs.php with 
`
array (
		0 => array (
        'description',
        'customCode' => '{$fields.description.value|escape:\'htmlentitydecode\' |escape:\'html\'|strip_tags|url2html|nl2br}',
		  ),
		),
`
Still no joy

**Comment by meethoss** [comment]
Can you attach the file? Do you have any other changes in custom/modules/Cases/metadata/detailviewdefs.php? If not then delete the file, it may be overriding the default file.

**Comment by abeo** [comment]
Thanks for the help. I deleted custom./modules/Cases/metadata/detailviewdefs.php
No effect from doing that. 
Attached is the /modules/Cases/metadata/detailviewdefs.php file
[detailviewdefs.zip](https://github.com/salesagility/SuiteCRM/files/208337/detailviewdefs.zip)

**Comment by meethoss** [comment]
Hmm, your file is an exact match to mine. Sorry I've got no other ideas beyond deleting your custom/modules/Cases folder.

**Comment by abeo** [comment]
Weird, I renamed the custom/modules/Cases folder.

Still no joy. 

Thanks for the help.

**Comment by meethoss** [comment]
Sorry got no other ideas - good luck with it!

**Comment by opensourcecrm** [comment]
after making changes with metadata file please repair and rebuild which will adopt the changes.

**Comment by abeo** [comment]
I updated the /modules/Cases/metadata/detailviewdef.php by replacing the file with a new file containing the updated code. Then I ran a Quick Repair.

Still no joy.

**Comment by gokhanerdogdu** [comment]
Is this problem still valid in 7.7.4?

**Comment by bmwtourer** [comment]
I can confirm that this problem is still in 7.7.4
I would add :
If I do not put one of the suggested patch I get this
 
![image](https://cloud.githubusercontent.com/assets/9001018/18722880/5cdcd746-8004-11e6-803e-7663916d7f3b.png)


when I put the patch (or very like) I get this 
![image](https://cloud.githubusercontent.com/assets/9001018/18722807/1bc650ca-8004-11e6-918f-34adb3944459.png)

as one can see, with no patch the foreign characters are shown properly but html tags are also shown
if i put the patch html renders correctly but I lose the foreign characters.



btw here is my detailviewdev file portion 
` array (
            'name' => 'description',
            'comment' => 'Full text of the note',
            'label' => 'LBL_DESCRIPTION',
               'customCode' => '{$fields.description.value|escape:\'html_entity_decode\'}',
          ),`

**I would believe that this problem is getting old and seems to attract little attention.**

**The MAJOR issue is that when we reply to customers the wrong code is shown which is not really good for our image and by association SuiteCRM image too...** 

If I am wrong and a solution exist please point me in the right direction.

**Comment by vladbar** [comment]
I could not replicate this issue - description box does not contain any html markup and foreign characters are displayed correctly. Tested with SuiteCRM 7.7.9, email was sent from Gmail, FastMail was used for the Case Handler (Inbound Email).

**Comment by shogunpol** [comment]
@meethoss , an issue has been tested on recent version of SuiteCRM(7.8.1), and not appear, can you confirm it and close the case?

**Comment by bmwtourer** [comment]
@shogunpol I will test and report
Serge

**Comment by bmwtourer** [comment]
Problem was still there after upgrade to 7.8.1 on test instance...
I deleted my custom detail view , performed a repair
I looked at the standard view and the problem is gone! 👍 
I rebuilt my custom detail view and still ok 👍 
Thank you!
Serge

**Comment by bmwtourer** [comment]
BTW my problem was related to &nbsp; characters... all (most?) other html stuff was ok but not the space for some reason.

**Comment by shogunpol** [comment]
@meethoss , according to community review, an issue doesnt exist any more. If this issue still exists and information can be given to allow us to proceed with this it can be reopened.

**Comment by fcorluka** [comment]
Hi,
I have similar problem i ListView (SuiteCRM 7.8.23).

EditView nad DetailView are all good but Listview is not:


  |  <div dir="ltr">HEEJJJ<br clear="all"  /><div><div><div dir="ltr"  class="gmail_signature"><div dir="ltr"><div><div  dir="ltr"><div><span style="font-family:arial, helvetica,  sans-serif;">Filip<br  /></span></div><span style="font-family:arial,  helvetica, sans-serif;">Software Developer<br />  </span><div> <p><span style="font-family:arial, helvetica,  sans-serif;">Tel: <br />Skype: </span></p></div></div></div></div></div></div><div  class="gmail_quote"><div dir="ltr"><br /></div> </div></div></div>
-- | --

I have tried to put custom code line but with no luck.
Any ideas?
Filip
