### ISSUE TITLE
SuiteCRM unable to retrieve saved Case "Update Text" Value

### ISSUE THREAD

**Issue by Laurentzed** [salesagility/SuiteCRM#9752]
#### Issue

When new case is created or existing case modified with a text string saved in field "Update Text", this value is not rerieved in read or edit mode later on of teh here case.

#### Expected Behavior

Case "Update - Text" is expected to reflect what has been saved last tim it's been modified.

#### Actual Behavior

Case with an existing text in "Update Text" is shown with zero text in this field.
I checked with PhpMyAdmin the table aop_case_updates and verified the update text is present in the table field "name".
SuiteCRM log file shows:
Mon Sep  5 16:25:23 2022 [32383][341070ec-005e-0c7e-31e2-538378e9a6ea][DEBUG] SugarBean.load_relationships, failed Loading relationship (contacts_aop_case_updates)

I exercised several times the admin repair for relationships without any improvement.
#### Steps to Reproduce

1. Create a new case with some text in the "Update - Text" fiel, and, then save it.
2. When screen is refreshed the "Update - Text" is empty

#### Context

All cases I am working with cannot be used with information/data indicating updates as so far far, all that text becomes impossible to retreive.

#### Your Environment

* SuiteCRM Version used: 7.12.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Microsoft Edge Version 104.0.1293.70 (Official build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.3.34-MariaDB, PHP 7.4.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04.5 LTS (up-to-date)

**Comment by johnM2401** [comment]
Hey there!

hmmm, I'm afraid I can't seem to replicate this at the moment.

If I create a case, all Updates are saving & showing in the Thread:
![image](https://user-images.githubusercontent.com/13675281/188888549-856aaeba-4f7a-4867-9c10-61dd1a255844.png)

(Even after a Hard browser refresh)

<br>

Do you perhaps know if there are specific steps to replicate this?

ie;  Upgrade to 7.12.7 from a previous version? / Insert a Case Update value WHILE saving / Anything else?

Also, do you know if your CRM perhaps has customizations on the Cases module?
(ie Code Changes / Changes in Studio)

Any further information you may have on this would be greatly appreciated.

Thanks!

**Comment by Laurentzed** [comment]
Please find below my screen about creating a new case:
![New Case Creation Screen 2022-09-07](https://user-images.githubusercontent.com/69970292/188895823-9c57c494-25b1-4fe0-a4cc-b0ef83590145.PNG)

After being saved here this case in view mode:
![New Case Creation Screen after being saved 2022-09-07](https://user-images.githubusercontent.com/69970292/188895898-31a5e2ef-1a59-4e47-bee0-a392bbac2417.PNG)

Here is the same case being edited
![New Case Edited Screen 2022-09-07](https://user-images.githubusercontent.com/69970292/188897927-7755995d-a090-4056-b338-21642c6ea1d0.PNG)

My SuiteCRM 7.12.7 was upgraded from 7.12.5 itself b
eing an upgrade from a previous version 7.12...
I don't recall any code customization besides adding fields and working on the layout with Studio.

Please let me know if there is any further information I can supply helping you here.

**Comment by Laurentzed** [comment]
Hello John

I do not see a similar screen as yours where is "Case Updates Threaded".
Is there any settings I would have missed to enable this feature?
Can I spot this "Case Updates Threaded" into Studio as a relationship from "Cases" module?
Thx

**Comment by johnM2401** [comment]
Hey!

Ahhh, I think I see what the issue is

So, any updates to a Case record will be added to the Case Updates Thread.
(for example, when you enter a value in "Updates - Text" and Save)

However, it looks like your Cases module doesn't have the "Cases Updates Thread" field on the Layout

<br>

You can add this by going to:

Studio->Cases->Layouts->Detailview
Then add the "Case Updates Threaded" item onto the view, by dragging it from the Field List on the Left
ie:
![image](https://user-images.githubusercontent.com/13675281/188903197-ff805041-f7a8-4c7d-9407-10a188506deb.png)

After Save & Deploy, you **Should** see the Thread of updates on the Case Records.

<br>

Hopefully this resolves your issue!

Thanks!

**Comment by Laurentzed** [comment]
Thanks John. I got it.
Allow me to ask if it makes sense to keep the "Update-Text" and "Internal Update" as part of the "Overview" panel in both Edit and Detail Views.
Also, is it possible to edit one of the "Case Updates Threaded" item if needed after it's being saved?

**Comment by johnM2401** [comment]
Hey

I think it should be safe to remove the "Update-Text" and "Internal Update" fields from the Detailview

These won't display any information and are only used when submitting to the Case Updates Thread.


<br>

In regards to editing Case Updates;
Typically, you cannot edit a Case Update once it has been submitted.

However, if you DO want to modify a Case Update, you can do so by going to the "Case Updates" hidden module

I don't believe you can access this normally via the CRM, (as it is not intended to be edited), but you can access it directly in the URL

It can be found at:
[your crm]/index.php?module=AOP_Case_Updates

(Though, i'd note that I'm not 100% sure how stable it is to edit records in here, as I haven't done it myself)

Thanks again for getting in touch!

**Comment by Laurentzed** [comment]
Thank you John.
Now it works. I experienced the work around in case of a need to modify an update. It works too.
