### ISSUE TITLE
Workflows conditions fails if contains a related field of a related module

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9761]
#### Issue
An error occurs in the query built by the CRM to check a condition of a workflow that works with a related field of a module related to the base module. Due to this error the workflow is not executed even if the condition is true.

#### Expected Behavior
Option 1: The FdT should be launched if the indicated condition is true. 
Option 2: Do not show those related fields that fail in the dropdown field of a related module of a condition (we have seen that some related fields like assigned to, created by and modified by do work because these fields are defined as columns of the database table.)

#### Actual Behavior
The FdT is not launched if it has any condition indicated with a related field of a related module

#### Steps to Reproduce
1. Create an event, a location and relate it
2. Create a 1 to N relationship between Events and Products
3. Create a workflow with:
- Base module: Products
- Run: Always and All Records
- A condition on the Events module where it is indicated that the location is the one created in point 1
- Some action
4. Create a product from the event subpanel.
5. Check that the flow has not been launched even though the condition is true.

#### Context
There are workflows that seem functional and that are not
Causes hard-to-find bugs

#### Your Environment
SuiteCRM Version used: Version 7.12.6
Browser name and version: Chrome Versión 100.0.4896.88 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7.4
Operating System and version: Ubuntu 20.04

**Comment by SinergiaCRM** [comment]
Same happens when the workflow is run by the scheduler. 

Example:
1- Create a one to many relationship between Accounts and Contacts. Where Accounts is the many side.
2- Create a workflow with a condition that tests that the Contacts field is empty:
![Selection_082](https://user-images.githubusercontent.com/61022311/203354486-3f1842a7-ae5e-463b-b0de-4b1678c00feb.png)
3- Run the workflow using the Scheduler and check the error in the log:
`
2022-11-22 11:34:41 [23][2][FATAL] Mysqli_query failed.
2022-11-22 11:34:41 [23][2][FATAL]  Query Failed: SELECT accounts.id AS id FROM accounts  WHERE accounts.contacts_accounts_1contacts_ida = '' AND accounts.deleted = 0 : MySQL error 1054: Unknown column 'accounts.contacts_accounts_1contacts_ida' in 'where clause'
`
The query is always built as if the relationship field is a related field, instead of building a query with the relationship table.

This doesn't happen with the option "Only on Save" because the audited bean is already loaded and the relationship field "_ida" returns its value.

**Comment by SinergiaCRM** [comment]
Hi @gemartin21 , any news about this issue?

Thanks

**Comment by SinergiaCRM** [comment]
Hi @jack7anderson7, I see that #8682 is closed. Does this solution also solve this issue?

Thanks

**Comment by jack7anderson7** [comment]
Hi @SinergiaCRM 

I have tested this in the latest version (7.14.2) and I am unable to replicate. This issue should now be resolved. I will close this issue as a result.

Thanks, 
Jack
