### ISSUE TITLE
Quick create menu not restricted by roles

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#978]
The quick menus are hard coded on the _headerModuleList.tpl files. I would be great if we hide/remove the items if the modules are restricted to the current user.

**Comment by ghermans** [comment]
:+1:

**Comment by vladbar** [comment]
Hello vjaro, could you please clarify which links you want to be hidden/removed? 
Are you asking about the modules displayed in the Add Dashlets popup?

**Comment by ChangezKhan** [comment]
Hello @vladbar, he is talking abount the `Create` button available on top bar.

![Quick Create Top Bar button](https://raw.githubusercontent.com/ChangezKhan/CRM/master/quick_create.jpg)

**Comment by cameronblaikie** [comment]
Closed due to inactivity, if you feel this should be reopened then do so and we will review your issue again.
