### ISSUE TITLE
Clicking on 'Sugar Document ' button opens a separate window with error message 'Server Error' .

### ISSUE THREAD

**Issue by vladbar** [salesagility/SuiteCRM#980]
Steps : 
1.Select Emails module
2.Click on Create Email Template option
3.Click on 'Sugar Document ' button

Actual Result : 
A separate window opens with error message 'Server Error' .

Expected Result :
A list of documents should be displayed.

**Comment by samus-aran** [comment]
@vladbar Is this still a valid issue on the latest version?  Tried to recreate this and I don't receieve an error message.

**Comment by vladbar** [comment]
@samus-aran I will test it again.

**Comment by vladbar** [comment]
@samus-aran It is fixed in a more consistent way starting from version 7.6.3

**Comment by vladbar** [comment]
@samus-aran Could you please close this pull requests:
https://github.com/vladbar/SuiteCRM/commit/9a62c7d2880ce0452dac8b2c841afa6a59df3148
https://github.com/vladbar/SuiteCRM/commit/7d08b8b4bb241a9fc71c9e309e76fbdd3b3f027f

and also this Github issue when/if you have time. Thanks!
