### ISSUE TITLE
No valid themes are found on this instance

### ISSUE THREAD

**Issue by madhatt30** [salesagility/SuiteCRM#982]
**Server**
Windows Server 2012 R2 running IIS
8GB Ram

**PHP Version**
PHP 5.5

**MySql Server** 
Version 5.1

**Prev. Installation**
SugarCRM CE 6.5.22

**Current Installation**
SuiteCRM 7.5.1 by way of Migration using the Upgrade path.

Although this message appears to be random I have noticed that they show up almost every time I create and new entry in a module and I click on save. It is also important to note that if I hit F5 when I get this error message "No valid themes are found on this instance" the page appears with not problems.

**Comment by mattlorimer** [comment]
please ask your question on the [support forum](https://suitecrm.com/forum/index), this is the best place to resolve issue of this type
