### ISSUE TITLE
Fatal error during upgrade on PHP 8.0 from 7.12 with custom user layouts

### ISSUE THREAD

**Issue by FR-JS** [salesagility/SuiteCRM#9829]
#### Issue
Performing a silent upgrade of 7.12.7 to 7.12.8 failed with a fatal error resulting in a broken system due to static call to a non-static method.

#### Expected Behavior
Upgrade should be performed successfully.

#### Actual Behavior
Upgrade fails part way throwing the fatal error
`PHP Fatal error: Uncaught Error: Non-static method MetaParser::hasMultiplePanels() cannot be called statically in crm/modules/UpgradeWizard/SugarMerge/EditViewMerge.php:611`

#### Possible Fix
Replace all static calls to MetaParser::hasMultiplePanels() with calls to an instance of the MetaParser class in the file modules/UpgradeWizard/SugarMerge/EditViewMerge.php

#### Steps to Reproduce
1. Install 7.12.7
2. Download SuiteCRM-Upgrade-7.12.x-to-7.12.8.zip upgrade package
3. Perform silent upgrade

#### Context
High priority - System is left broken

#### Your Environment
* SuiteCRM Version used: 7.12.7
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.0
* Operating System and version (e.g Ubuntu 16.04): Debian 11

**Comment by JanSiero** [comment]
Hi, this issue requires a more detailed description of the steps to reproduce this. I was able to reproduce this by the following 

**Steps to reproduce**

- Install version 7.12.14 on a system running PHP 8.0
- After installation, go into Admin / Studio
- Navigate to Users / Layouts / Edit View
- Click "Save & Deploy"
- Go to Admin / Upgrade Wizard
- On "Welcome" click "Next"
- On "System Check" click "Next"
- Upload the file "SuiteCRM-Upgrade-7.12.x-to-7.14.3.zip" and click "Next"
- On "Preflight Check" click "Next"

**Expected result**
The following step "Commit Upgrade" is shown

**Actual behavior**
 - The Upgrade Wizard shows an empty screen
 - The web server log shows an entry
`PHP Fatal error: Uncaught Error: Non-static method MetaParser::hasMultiplePanels() cannot be called statically in ... /modules/UpgradeWizard/SugarMerge/EditViewMerge.php:611`

I'd suggest to change the title to: "Fatal error during upgrade on PHP 8.0 from 7.12 with custom user layouts"
