### ISSUE TITLE
Looking for suiteCrm demo  destined to inssurance

### ISSUE THREAD

**Issue by zackzulg** [salesagility/SuiteCRM#983]
Hey guys,

I'm looking for suiteCRM demo for insurance. I make my searchs in the internet but I can't find what I want. I'd like to find some suggestions here.

Thanks.

**Comment by ghermans** [comment]
There is only one [demo](https://suitecrm.com/demo).  what are the features that you need?

**Comment by zackzulg** [comment]
Hey ghermans, so I need devis, accounts, prospects and opportunities. 
Regards.

**Comment by Mausino** [comment]
:-1:

**Comment by chris001** [comment]
SuiteCRM includes Quotations ("Devis"), Accounts and Contacts, Targets ("Prospects") and Leads, and Opportunities.

**Comment by samus-aran** [comment]
As @Mausino pointed out - this is a forum question.  Closed for this reason.
