### ISSUE TITLE
How do I use the refresh token? Where do I send it?

### ISSUE THREAD

**Issue by charlesdsmith** [salesagility/SuiteCRM#9850]
I was able to retrieve a refresh token using the `password` type grant. But what endpoint am I supposed to send it to exactly?

**Comment by johnM2401** [comment]
Hey!

Thanks for getting in touch!

This sort of query would likely be best suited for the [Community Forums](https://community.suitecrm.com/)

The "Issues" tab here should primarily be used to log/track known Issues & Suggested Features.

<br>

However, to answer your question, I imagine it would depend on your intended usage of the API.

Some of the documentation may help, if you have not yet found an answer: 

https://docs.suitecrm.com/developer/api/developer-setup-guide/configure-authentication/
https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/#_authentication

As well as some example Endpoints for the CRM:
https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/#_endpoints

**Comment by pichitachi** [comment]
@johnM2401 are you able to find the solution? The doc just simply mentions the login & get access token part. I couldn't find anywhere on how to use the refresh token.
