### ISSUE TITLE
7.13.0 - Inbound Email's "Test Connection Settings" appears to use OAuth, if Auth Type is changed in current Edit Session

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#9854]
#### Issue

As of 7.13.0, There is now the ability to use OAuth to Authenticate Inbound Email Accounts.

However, if the user previously had Oauth2 chosen as their Auth Type
Then, they switch to "Basic Auth" and click "Test Settings"

Assuming that their Oauth connection was Valid, they will ALWAYS see a "Connection Successful" message, even if their Basic Auth settings are wrong.

#### Expected Behavior

The "Test Settings" should use the Connection Settings of the currently chosen Auth Type.

#### Actual Behavior

It appears to use the Connection Settings of the currently SAVED auth type.

#### Steps to Reproduce

1. Create an inbound Mail Account, and successfully connect it using Oauth
2. Use "Test Connection Settings" to ensure the connection succeeds, then save.
3. Edit the Record, change Auth Type to "Basic Auth" and click "Test Connection Settings"
4. See that it succeeds, even if you have no Password entered

![image](https://user-images.githubusercontent.com/13675281/208676831-01d4ca12-715c-49a4-ac3b-39143a9df16f.png)

#### Context
This will cause Connection status to be unclear to users.

#### Your Environment

* SuiteCRM Version used: 7.13.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 108.0
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

**Comment by jack7anderson7** [comment]
Closing as was fixed in this PR: https://github.com/salesagility/SuiteCRM/pull/10120
