### ISSUE TITLE
Calendar displays times which overlap.  (Not caused by CR)

### ISSUE THREAD

**Issue by CaptainChainsaw** [salesagility/SuiteCRM#987]
When creating a meeting within the calendar the time span of the meeting appears slightly longer than it should.  In the screenshot the meeting should be 7 hours but it displays as almost 7.5 hours.

![calendar-overlap-issue](https://cloud.githubusercontent.com/assets/3913259/13221487/95aafd7e-d973-11e5-9137-68eb17c872b0.png)

**Comment by shogunpol** [comment]
The issue has been tested on the recent version of SuiteCRM(7.7.4), and it not appear,
@CaptainChainsaw  , can you confirm the issue is not exist any more?
If yes can you close an issue?
