### ISSUE TITLE
Case module : Cannot batch search based on number

### ISSUE THREAD

**Issue by julibo** [salesagility/SuiteCRM#9897]
### Expected Behavior
Enter multiple case numbers to batch search for cases.

![image](https://user-images.githubusercontent.com/20227617/212049552-347187a4-92f2-49b3-9e5b-f72b7895d430.png)

### Actual Behavior
Only one number search case can be entered.

I think the batch search function is very important.

### Version number
SuiteCRM Version used: 8.1.3

**Comment by johnM2401** [comment]
Hey Folks!

Thanks for getting in touch @julibo 

As you've raised this issue on the Suite8 Repo: https://github.com/salesagility/SuiteCRM-Core/issues/197

I'll close this item off here, and we can continue discussion/resolution on the linked ticket.

Thank you again!
