### ISSUE TITLE
Default empty item when creating a new Dropdown field

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9909]
When creating a new Dropdown field in Studio/ModuleBuilder, the default ítem that appears in the list is always the first list alphabetically available in the system:
![DropDownDefaultEmpty](https://user-images.githubusercontent.com/61022311/213258449-f14c4b8c-d3e2-4cbb-bd45-4ba5fbe299fb.gif)

This can be confusing for users, and they might think that they can use that list. But if that list is already used by another field, they might change something it wasn't intended, without knowing it.

#### Issue
The default list of a new field is always the first list available alphabetically.
![Selection_141](https://user-images.githubusercontent.com/61022311/213258911-83bf64eb-c126-4407-b80f-81ad89308475.png)

#### Expected Behavior
No list should be selected by default

#### Actual Behavior
During a fresh installation, the list "account_type_dom" is always selected. Even if this is already in used.

#### Possible Fix
We propose to display and "empty" option be default when creating a new DropDown / DynamicEnum /Multienum field. 

#### Steps to Reproduce

1. Create a new Dropdown field
2. Check the item that appears by default in the Drop Down List field.

#### Context
Many users don't notice they should change the list and they keep using and editing the first list that appears.

#### Your Environment

* SuiteCRM Version used: 7.12.8
* Browser name and version: Versión 107.0.5304.121 (Build oficial) (64 bits)
* Environment name and version: MariaDB 10.6.5, PHP 7.4
* Operating System and version : KDE Neon 5.26

**Comment by sicay** [comment]
The fix generate a new bug. When adding a new Dropdown field, a popup error is displayed.

<img width="635" height="638" alt="Image" src="https://github.com/user-attachments/assets/328e541b-9b08-4eb7-b76f-706d9b9081e2" />

Since a default empty value is added to the top of the $dropdowns array, the ELSE {} of the IF at line 97 of of enum2.php become obsolete.
