### ISSUE TITLE
Pages stuck in reload loop when coming out of hibernation

### ISSUE THREAD

**Issue by virtualme123** [salesagility/SuiteCRM#992]
SuiteCRM version 7.5.1
Ubuntu 12.04
PHP 5.3.1
Google Chrome

I'm seeing when I bring my laptop out of hibernation that any tabs I had open to my SuiteCRM instance reload then get stuck in a loop reloading which I can see it hammering the server in the access logs over and over again. This in turn pushes the CPU usage up to 100% and almost grinds the server to a halt.

I haven't experienced any other users having this problem yet but I'm concerned others might have the problem when I least expect it and the server gets knocked out.

Any ideas as to what might be causing this, and a possible solution?

Thanks,

Chris

**Comment by mrbarletta** [comment]
+1 - Same issue here on Ubuntu 15.10 and Chrome @stable

**Comment by Mausino** [comment]
:+1:  i agree... all employees have this problem at the company... and it makes us crazy... this loop uses all  cpu of our PCs and only one solution is close this cards with SuiteCRM aplication... or open new tab and loging again. After i open  in new tab the SuiteCRM and i must log in again.. and after we can working again...

I thinked that is problem with configuration of server... but i see that other users have same issue 

@virtualme123 that you described this issue
@willrennie @mattlorimer  @gymad  could you help us ?

**Comment by virtualme123** [comment]
Excellent work, I am impressed with the reaction so thanks to the team! I look forward to the next release.

**Comment by mrbarletta** [comment]
+1 Thanks a lot
