### ISSUE TITLE
Product can't be creat in demo

### ISSUE THREAD

**Issue by Claudine357** [salesagility/SuiteCRM#9958]
I try to create product in demo 8 but it's not possible.
I can create categories but no product.

**Comment by pgorod** [comment]
Hi Claudine

the Forums are better suited to this kind of basic troubleshooting, you should ask there first. Here it's for more technical bug reports for developers.

https://community.suitecrm.com/

You're probably running into this known issue:

https://github.com/salesagility/SuiteCRM-Core/issues/211

it already has a fix which hopefully will come out in the next version.

I will close this issue now, if you have more question feel free to ask in the Forums and I will follow-up with you there. Thanks!
