### ISSUE TITLE
Some Characters not displaying correctly in Street, City and Country Address fields

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#999]
The characters:  '     "       <       > 
All display incorrectly in the Address fields for the Street, City and Country values.
The characters display correctly for the State and Postcode values.

Tested in SuiteCRM 7.5.1 and appears to occur on any module where there is an Address block.

'  displays as: &# 039; 
" displays as: \&quot;
< displays as: \&lt; 
\> displays as: \&gt;

Mentioned in forum posts: https://suitecrm.com/forum/suitecrm-7-0-discussion/6984-not-displaying-apostrophe-properly#25318

And: https://suitecrm.com/forum/installation-upgrade-help/6928-character-not-displayed-properly-after-upgrade-to-7-4#28905

Possibly related to the previously logged: https://github.com/salesagility/SuiteCRM/issues/655

**Comment by Petrouchka** [comment]
Same bug in account address field :
![screenshot at 2016-06-25 14 33 53](https://cloud.githubusercontent.com/assets/3955499/16357591/3045650c-3afb-11e6-859d-ee2b98acde6c.png)

**Comment by vladbar** [comment]
@Petrouchka  This solution will also fix this bug for account address field
